### ISSUE TITLE
default local tracking uri not working on windows? "Tracking URI must be a local filesystem URI of the form 'file:///...' or a remote URI "

### ISSUE THREAD

**Issue by rquintino** [mlflow/mlflow#10]
Was just testing on windows, had to force a tracking url for mlflow to work

the default for this case is:
>>> mlflow.get_tracking_uri()
'd:\\Code\\mlflow\\mlruns'

throws:
**Exception: Tracking URI must be a local filesystem URI of the form 'file:///...' or a remote URI of the form 'http://...'. Please update the tracking URI via mlflow.set_tracking_uri**

workaround:

>>> mlflow.set_tracking_uri("file://d:/code/mlflow/mlruns")
>>> mlflow.log_param("test",5)

seemed to work, mlruns folder now with the expected run info

thx!
(solid work, congrats, very promising, 
ps-license would benefit from clarification on that api calls usage though)

**Comment by mateiz** [comment]
Thanks for the note -- this is indeed likely to be broken. We'd recommend running on Linux through Docker or through bash-on-Windows for now, but we would like to fix this for Windows users.

**Comment by makcedward** [comment]
I am using Window as well. Another tricks is 
``
mlflow.set_tracking_uri("http://localhost:5000")

**Comment by sfilipi** [comment]
@mateiz does this mean that the tracking server cannot run on windows? I keep getting (this error)[https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl] trying to start it.

**Comment by mateiz** [comment]
It should be working on Windows in the master branch now. Maybe there's something wrong in the dependencies? Try asking some of the engineers who were involved in that (they were from Microsoft).

**Comment by tomasatdatabricks** [comment]
This should be working on Windows right now as well as most of MLflow tracking functionality.
