### ISSUE TITLE
[FR] Add support for Huggingface Text Generation Inference

### ISSUE THREAD

**Issue by SDonkelaarGDD** [mlflow/mlflow#10010]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Add support for [Huggingface Text Generation Inference](https://huggingface.co/text-generation-inference) endpoints in MLflow AI gateway.

##### What is the use case for this feature?
MLflow AI gateway is a powerful tool for controlling and securing access to Language Model (LLM) endpoints. However, the current support for providers is limited. In our specific case, we are utilizing Huggingface's Text Generation Inference (TGI) toolkit to deploy LLMs on-premises. Unfortunately, this provider is not currently supported by MLflow AI gateway.

##### Why is this use case valuable to support for MLflow users in general?
Expanding support for additional providers is beneficial for all MLflow users that are using the AI gateway. This enhancement would allow users to leverage MLflow AI gateway in a wider range of contexts and with different providers.

##### Why is this use case valuable to support for your project(s) or organization?
Within our organization (large enterprise in financial domain), we are considering implementing MLflow AI gateway to manage access to LLM endpoints. However, the lack of support for the TGI provider is currently preventing us from adopting this solution.

##### Why is it currently difficult to achieve this use case?
The difficulty lies in the fact that the TGI provider is not currently supported by MLflow AI gateway.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
cc @vladimirk-db @mingyu89

**Comment by serena-ruan** [comment]
Hi @SDonkelaarGDD This is a great idea! Please feel free to raise a PR and we'll review :)

**Comment by SDonkelaarGDD** [comment]
Awesome! Please assign this issue to me and I will make a start this weekend.

**Comment by BenWilson2** [comment]
Merged! :)
