### ISSUE TITLE
Inconsistent Metric entity timestamp

### ISSUE THREAD

**Issue by mociarain** [mlflow/mlflow#1002]
Currently the Metric entity model has the following docstring description for the timestamp attribute:

"""Metric timestamp as an integer (milliseconds since the Unix epoch)."""

However, in `fluent.py` in the implementation of `log_metric`, the timestamp is set in seconds and then passed to the `MlflowClient`. 

This is misleading and I wonder if it was meant to be set as milliseconds in the client similarly to  the `set_terminated` & `create_run`?

Happy to help implement any resulting changes

**Comment by smurching** [comment]
Hi @mociarain, thanks for raising this & sorry for the delay - the Python client should set the timestamp in milliseconds, I'd be happy to review a PR to this effect :) - thanks!
