### ISSUE TITLE
[BUG]after disable or comment all mlflow code,its still tracking all the metrics

### ISSUE THREAD

**Issue by floyddcn** [mlflow/mlflow#10036]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

python api
- mlflow: 2.7.1 

### System information

- **Linux 82798d7d5de4 5.4.0-149-generic #166-Ubuntu SMP Tue Apr 18 16:51:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux **:
- **python=3.10.11**:

### Describe the problem

After using disable=True or commenting all mlflow code,it seems the mlflow still tracking all the metrics  and save them to the disk in mlrun folder. Why?
Is it a normal result for the environment which installed both mlflow and transformers?

Here is my code:
![image](https://github.com/mlflow/mlflow/assets/48442748/620e88cf-becf-4596-b02b-32c48a727982)
The screenshot is from  the following code (https://github.com/hiyouga/LLaMA-Factory/blob/0fcf66049df0893e8f0f20b2098a98bedb291259/src/train_bash.py#L5),and the git project 'LLaMA-Factory' is a training tool using transformers. I just want to use mlflow with the project LLaMA-Factory

### Tracking information

from llmtuner import run_exp
# import mlflow

def main():
    # with mlflow.start_run():
    # mlflow.transformers.autolog(log_input_examples=True, log_model_signatures=True, log_models=True,
    #                             log_datasets=True, disable=True, exclusive=False,
    #                             disable_for_unsupported_versions=False, silent=False, extra_tags=None)
    run_exp()

def _mp_fn(index):
    # For xla_spawn (TPUs)
    main()

if __name__ == "__main__":
    main()

### Code to reproduce issue

N/A

### Stack trace

N/A

### Other info / logs

N/A

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by floyddcn** [comment]
OK, 'report_to' does solve my problem . But i still wandering why it 's still logging after i commented the all the mlflow code including 'import' code (in my snapshot)? Do you mean  logging/auto-tracking is depending on 'report_to' when mlflow and transformers are both installed ,and mlflow modify the transformers code and add mlflow's callback staticly  ？

**Comment by harupy** [comment]
@floyddcn because transformers imports mlflow and uses it.

**Comment by floyddcn** [comment]
Got u .  I check the transformers code . ![image](https://github.com/mlflow/mlflow/assets/48442748/afb310a6-c7b5-47d0-b4e9-abae58efbf17)
I really really appreciate your patience.
Thanks a lot:)

**Comment by floyddcn** [comment]
BTW,in the document says 'Autologging functionality is not implemented fully for the transformers flavor' does it means autologging doesnt implement all the autolog parameter like log_models.Because , when i digged into both mlflow and transformers integrations code,i didnt found any 'log_model' to env parameter 'HF_MLFLOW_LOG_ARTIFACTS'(see following code snapshot)
![image](https://github.com/mlflow/mlflow/assets/48442748/e6e3b2de-00f6-402a-af43-b725e5ec8a7d)
So mlflow's autologging will not log model/checkpoints to artifacts，am i right? The only way is to enable it is to set the env parameter?
