### ISSUE TITLE
Support Flask 3.0 in MLflow

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#10067]
### Summary

We currently pin `Flask` to `< 3.0`. Flask 3.0 was recently released. We should update the requirement:

```diff
diff --git a/requirements/core-requirements.txt b/requirements/core-requirements.txt
index 99f4cdd62..11f7e3770 100644
--- a/requirements/core-requirements.txt
+++ b/requirements/core-requirements.txt
@@ -4,7 +4,7 @@
 
 alembic<2,!=1.10.0
 docker<7,>=4.0.0
-Flask<3
+Flask<4
 numpy<2
 scipy<2
 pandas<3
diff --git a/requirements/core-requirements.yaml b/requirements/core-requirements.yaml
index 5447b07c7..4ffb44c6b 100644
--- a/requirements/core-requirements.yaml
+++ b/requirements/core-requirements.yaml
@@ -17,7 +17,7 @@ docker:
 
 flask:
   pip_release: Flask
-  max_major_version: 2
+  max_major_version: 3
 
 numpy:
   pip_release: numpy
```

References:

- https://pypi.org/project/Flask/3.0.0/

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by harupy** [comment]
@Sai-Suraj-27 sorry, this issue already has an asignee.

**Comment by Sai-Suraj-27** [comment]
@harupy Ok! but I saw that it was assigned yesterday and I see that assignee don't have a fork of mlflow as of now. So, I created a PR. Sorry for not asking before making a PR.

**Comment by harupy** [comment]
Please ask first if an issue has already an assignee.

**Comment by Sai-Suraj-27** [comment]
> Please ask first if an issue has already an assignee.

Sure, from next time 😄.
