### ISSUE TITLE
 Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found

### ISSUE THREAD

**Issue by jcvall** [mlflow/mlflow#1009]
### System information
 MLflow)**:
- **OS Platform and Distribution (windows 10 64x)**:
- **MLflow installed from (source)**: 
- **MLflow version (run ``mlflow 0.8``)**:
- **Python version**:  N/A Running in Rstudio
### Script
install.packages('mlflow', dependencies = T, repos = "https://cloud.r-project.org/")
mlflow::mlflow_install()
library(mlflow)

mlflow_ui()

### Describe the problem
when I run mllflow_ui().... i get the following error:  Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found

### Source code / logs
    Failed validating 'additionalProperties' in error:

    On instance['cells'][2]['outputs'][0]:
    {'ename': 'ERROR',
     'evalue': 'Error in process_initialize(self, private, command, args, '
               'stdin,...',
     'execution_count': 3,
     'output_type': 'error',
     'traceback': ['Error in process_initialize(self, private, command, args, '
                   'stdin,...',
                   '1. mlflow_ui()',
                   '2. mlflow_ui.NULL()',
                   '3. mlflow_client()',
                   '4. mlflow_server(file_store = tracking_uri, port = '
                   'mlflow_connec...',
                   '5. do.call("mlflow_cli", c("server", args, list(background = '
                   'get...',
                   '6. mlflow_cli("server", "--port", 5139, "--file-store", '
                   '"C:/User...',
                   '7. with_envvar(env, {\n'
                   ' .     if (background) {\n'
                   ' .         result...',
                   '8. force(code)',
                   '9. process$new(mlflow_bin, args = unlist(args), echo_cmd = '
                   'verbo...',
                   '10. .subset2(public_bind_env, "initialize")(...)',
                   '11. process_initialize(self, private, command, args, stdin, '
                   'stdo...']}

**Comment by Augusttell** [comment]
I am having a simliar issue when running the mlflow_create_experiment() function within R.

**Comment by tellyshia** [comment]
Same here. 
```
Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  Command not found
```
Any clue so far?

**Comment by Phlogi** [comment]
See: https://github.com/plotly/orca/issues/120#issuecomment-424000634

**Comment by fmannhardt** [comment]
Same problem here, adding the `mlflow.exe` to the path as proposed by the issue linked by @Phlogi does not help. Maybe this is related to running on Windows, as the Github page says

> Note 2: We do not currently support running MLflow on Windows. Despite this, we would appreciate any contributions to make MLflow work better on Windows.

**Comment by nathmenini** [comment]
Same problem here.. Any update?

**Comment by vikassrikanth** [comment]
Hey, I am facing the same issue when I am trying to build a package from its source.

**Comment by flostracke** [comment]
The command mlflow_ui() is working for me. I just get an error when running 

`library(mlflow)
writeLines("Hello world!", "output.txt") 
mlflow_log_artifact("output.txt") `

**Comment by Prasan03** [comment]
Hi Everyone,
I am running into the same error, I am trying out the [Quickstart](https://mlflow.org/docs/latest/quickstart.html) example using R and I get this error in all the lines where we access 'mlflow_.....' methods. (I am able to run using Python) 
Any help in this regard will be much appreciated.
System Info: [Win 10 64x, mlflow 0.9.0.1, Rstudio 1.2.1335, R x64 3.6.0]

**Comment by javierluraschi** [comment]
Could you please upgrade to `mlflow 1.0.0` by running the following and retrying? From looking at the code, this should have been fixed already.

```
install.packages("mlflow")
```

**Comment by ldanai** [comment]
Just try it again with `mlflow 1.0.0`, still errors: 

``` r
library(mlflow)

mlflow_set_experiment("Test")
#> Error in get_python_bin(): MLflow not configured, please run install_mlflow().

param1 = 12
mlflow_log_param("param1", 5)
#> Error in get_python_bin(): MLflow not configured, please run install_mlflow().

mlflow::mlflow_install()
#> Error: 'mlflow_install' is not an exported object from 'namespace:mlflow'

version
#>                _                           
#> platform       x86_64-w64-mingw32          
#> arch           x86_64                      
#> os             mingw32                     
#> system         x86_64, mingw32             
#> status                                     
#> major          3                           
#> minor          6.0                         
#> year           2019                        
#> month          04                          
#> day            26                          
#> svn rev        76424                       
#> language       R                           
#> version.string R version 3.6.0 (2019-04-26)
#> nickname       Planting of a Tree
```

<sup>Created on 2019-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by javierluraschi** [comment]
@ldanai I believe you want to run `mlflow::mlflow_install()` instead of `mlflow::install_mlflow()`, I would also restart the R session after installing the updated `mlflow` package.

**Comment by tellyshia** [comment]
This is what i get with `mlflow::mlflow_install()`

``` r
library(mlflow)
mlflow::mlflow_install()
#> Error: 'mlflow_install' is not an exported object from 'namespace:mlflow'
```
and with `mlflow::install_mlflow()`

``` r
library(mlflow)
mlflow::install_mlflow()
# WARNING: The conda.compat module is deprecated and will be removed in a future release.
# Collecting package metadata: ...working... failed
# 
# CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/msys2/win-64/repodata.json.bz2>
#   Elapsed: -
#   
#   An HTTP error occurred when trying to retrieve this URL.
# HTTP errors are often intermittent, and a simple retry will get you on your way.
# 
# If your current network has https://www.anaconda.com blocked, please file
# a support request with your network engineering team.
# 
# SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/msys2/win-64/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))
#> Error: Error 1 occurred creating conda environment r-mlflow-1.0.0
```

**Comment by ldanai** [comment]
> @ldanai I believe you want to run `mlflow::mlflow_install()` instead of `mlflow::install_mlflow()`, I would also restart the R session after installing the updated `mlflow` package.

Ahh thanks @javierluraschi, I got that command function from some old docs. The installation works fine now :)

Now comes an errors below
``` r
library(mlflow)

mlflow_set_experiment("Test")
#> Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found

param1 = 12
mlflow_log_param("param1", 5)
#> Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found

version
#>                _                           
#> platform       x86_64-w64-mingw32          
#> arch           x86_64                      
#> os             mingw32                     
#> system         x86_64, mingw32             
#> status                                     
#> major          3                           
#> minor          6.0                         
#> year           2019                        
#> month          04                          
#> day            26                          
#> svn rev        76424                       
#> language       R                           
#> version.string R version 3.6.0 (2019-04-26)
#> nickname       Planting of a Tree
```

``` r
library(mlflow)

# Log a parameter (key-value pair)
mlflow_log_param("param1", 5)
#> Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found

```
<sup>Created on 2019-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tonyk7440** [comment]
Installation also works fine for me but can't run any of the functions on windows. Reprex below.
Please let me know if there is any further details that would be helpful.

installed mlflow using:
```
install.packages("mlflow")
mlflow::install_mlflow()
```

Reprex
``` r
library(mlflow)

mlflow_set_experiment("Test")
#> Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found

param1 <- 12
mlflow_log_param("param1", 5)
#> Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found
```

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United Kingdom.1252 
#>  ctype    English_United Kingdom.1252 
#>  tz       Europe/London               
#>  date     2019-06-28                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  askpass       1.1     2019-01-13 [1] CRAN (R 3.5.2)
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.5.3)
#>  base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.5.0)
#>  callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.2)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
#>  devtools      2.0.2   2019-04-08 [1] CRAN (R 3.5.3)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.5.2)
#>  forge         0.2.0   2019-02-26 [1] CRAN (R 3.5.3)
#>  fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.2)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  highr         0.7     2018-06-09 [1] CRAN (R 3.5.1)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
#>  httpuv        1.4.5.1 2018-12-18 [1] CRAN (R 3.5.2)
#>  httr          1.4.0   2018-12-11 [1] CRAN (R 3.5.2)
#>  ini           0.3.1   2018-05-20 [1] CRAN (R 3.5.2)
#>  jsonlite      1.6     2018-12-07 [1] CRAN (R 3.5.2)
#>  knitr         1.21    2018-12-10 [1] CRAN (R 3.5.2)
#>  later         0.8.0   2019-02-11 [1] CRAN (R 3.5.2)
#>  lattice       0.20-38 2018-11-04 [2] CRAN (R 3.5.3)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  Matrix        1.2-15  2018-11-01 [2] CRAN (R 3.5.3)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
#>  mlflow      * 1.0.0   2019-06-06 [1] CRAN (R 3.5.3)
#>  openssl       1.2.1   2019-01-17 [1] CRAN (R 3.5.2)
#>  pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.2)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
#>  processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.2)
#>  promises      1.0.1   2018-04-13 [1] CRAN (R 3.5.1)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)
#>  purrr         0.3.2   2019-03-15 [1] CRAN (R 3.5.3)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.5.3)
#>  remotes       2.0.4   2019-04-10 [1] CRAN (R 3.5.3)
#>  reticulate    1.12    2019-04-12 [1] CRAN (R 3.5.3)
#>  rlang         0.3.4   2019-04-07 [1] CRAN (R 3.5.3)
#>  rmarkdown     1.11    2018-12-08 [1] CRAN (R 3.5.2)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  swagger       3.9.2   2018-03-23 [1] CRAN (R 3.5.2)
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.2)
#>  usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.2)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
#>  xfun          0.4     2018-10-23 [1] CRAN (R 3.5.2)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
#>  zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.5.3)
#> 
#> [1] C:/Users/akenny/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.3/library
```

</details>

**Comment by mik3y64** [comment]
So has there been any solution on this issue? I hit this issue today.

**Comment by maurony** [comment]
Is there any solution to this issue; I face the same issue after installing mlflow as described in the quickstart here: https://www.mlflow.org/docs/latest/quickstart.html.

Installation works, tracking API does not seem to work however...

`
> library(mlflow)
> 
> # Log a parameter (key-value pair)
> mlflow_log_param("param1", 5)
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977
> 
> # Log a metric; metrics can be updated throughout the run
> mlflow_log_metric("foo", 1)
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977
> mlflow_log_metric("foo", 2)
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977
> mlflow_log_metric("foo", 3)
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977
> 
> # Log an artifact (output file)
> writeLines("Hello world!", "output.txt")
> mlflow_log_artifact("output.txt")
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977
`

**Comment by rockraptor5** [comment]
I'm running into the same issue with mlflow on windows when attempting the [r_wine tutorial](https://mlflow.org/docs/latest/tutorial.html). 

I can successfully write metrics and params to an existing mlflow server but when I attempt to set my tracking uri to a local file I get the Command not found error.

This works:
```
mlflow_set_tracking_uri("http://existing_mlflow_server")
```
This doesn't work:
```
mlflow_set_tracking_uri(uri = 'file:/mlruns/1')
```

**Comment by vrankenjulie** [comment]
@rockraptor5, with your work around the mlflow_log_metric() and mlflow.log_param() functions indeed work in my example in R. However for  the log_model() and log_artificact() functions, I still encounter the same issue. When using Python however I do not have this problem. 

### Code

``
install.packages("mlflow")
install.packages("glmnet")
install.packages("carrier")
install.packages("Matrix")
install.packages("reticulate")

library(mlflow)
library(glmnet)
library(carrier)
library(data.table)
library(Matrix)
library(reticulate)

mlflow::install_mlflow()



mlflow_set_tracking_uri("http://localhost:5000")


#load the data

setwd("/Users/Julie.Vranken/Desktop/Data Science/MLflow_Houses")
data <- read.csv("Train.csv")


#Clean the data

#data cleaning
data$LotFrontage[is.na(data$LotFrontage)] <- as.integer(0)
data$Alley = factor(data$Alley, levels=c(levels(data$Alley), "NoAlley"))
data$Alley[is.na(data$Alley)] <- "NoAlley"
data$FireplaceQu = factor(data$FireplaceQu, levels=c(levels(data$FireplaceQu), "NoFP"))
data$FireplaceQu[is.na(data$FireplaceQu)] <- "NoFP"
data$GarageType = factor(data$GarageType, levels=c(levels(data$GarageType), "NoGarage"))
data$GarageType[is.na(data$GarageType)] <- "NoGarage"
data$GarageYrBlt[is.na(data$GarageYrBlt)] <- as.integer(0)
data$GarageFinish = factor(data$GarageFinish, levels=c(levels(data$GarageFinish), "NoGarage"))
data$GarageFinish[is.na(data$GarageFinish)] <- "NoGarage"
data$GarageQual = factor(data$GarageQual, levels=c(levels(data$GarageQual), "NoGarage"))
data$GarageQual[is.na(data$GarageQual)] <- "NoGarage"
data$GarageCond = factor(data$GarageCond, levels=c(levels(data$GarageCond), "NoGarage"))
data$GarageCond[is.na(data$GarageCond)] <- "NoGarage"
data$PoolQC = factor(data$PoolQC, levels=c(levels(data$PoolQC), "NoPl"))
data$PoolQC[is.na(data$PoolQC)] <- "NoPl"
data$Fence = factor(data$Fence, levels=c(levels(data$Fence), "NoFnc"))
data$Fence[is.na(data$Fence)] <- "NoFnc"
data$MiscFeature = factor(data$MiscFeature, levels=c(levels(data$MiscFeature), "None"))
data$MiscFeature[is.na(data$MiscFeature)] <- "None"
data$Id <- NULL
data <- na.omit(data)

# Split the data into training and test sets. (0.75, 0.25) split.
sampled <- sample(1:nrow(data), 0.75 * nrow(data))
train <- data[sampled, ]
test <- data[-sampled, ]

labels(data)

# The predicted column is "SalePrice"
train_x <- train[, !(names(train) == "SalePrice")]
train_x <- model.matrix( ~ .,train_x)
test_x <- test[, !(names(train) == "SalePrice")]
test_x <- model.matrix( ~ .,test_x)
train_y <- train[, "SalePrice"]
test_y <- test[, "SalePrice"]

alpha <- mlflow_param("alpha", 0.5, "numeric")
lambda <- mlflow_param("lambda", 0.5, "numeric")
mlflow_set_experiment(experiment_name = 'MLflow_Houses')
                     

with(mlflow_start_run(), {

  model <- glmnet(train_x, train_y, alpha = alpha, lambda = lambda, family= "gaussian", standardize = FALSE)
  predictor <- crate(~ glmnet::predict.glmnet(!!model, as.matrix(.x)), !!model)
  predicted <- predictor(test_x)
  
  rmse <- sqrt(mean((predicted - test_y) ^ 2))
  mae <- mean(abs(predicted - test_y))
  r2 <- as.numeric(cor(predicted, test_y) ^ 2)
  
  message("Elasticnet model (alpha=", alpha, ", lambda=", lambda, "):")
  message("  RMSE: ", rmse)
  message("  MAE: ", mae)
  message("  R2: ", r2)
  
  mlflow_log_param("alpha", alpha)
  mlflow_log_param("lambda", lambda)
  mlflow_log_metric("rmse", rmse)
  mlflow_log_metric("r2", r2)
  mlflow_log_metric("mae", mae)
  mlflow_log_model(predictor, artifact_path ="model")
})
``
### Error:
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977

Is there any solid solution to this issue? 

Thanks a lot!

**Comment by vrankenjulie** [comment]
@rockraptor5 , when using your workaround the functions mlflow_log_param() and mlflow_log_metric() indeed work in my R example. However for the mlflow_log_model() and mlflow_log_artifact() I still encounter the same problem. 

```
install.packages("mlflow")
install.packages("glmnet")
install.packages("carrier")
install.packages("Matrix")
install.packages("reticulate")

library(mlflow)
library(glmnet)
library(carrier)
library(data.table)
library(Matrix)
library(reticulate)

mlflow::install_mlflow()

mlflow_set_tracking_uri("http://localhost:5000")

data <- read.csv("Data.csv")

#Split the data into training and test sets. (0.75, 0.25) split.
sampled <- sample(1:nrow(data), 0.75 * nrow(data))
train <- data[sampled, ]
test <- data[-sampled, ]

#The predicted column is "SalePrice"
train_x <- train[, !(names(train) == "SalePrice")]
train_x <- model.matrix( ~ .,train_x)
test_x <- test[, !(names(train) == "SalePrice")]
test_x <- model.matrix( ~ .,test_x)
train_y <- train[, "SalePrice"]
test_y <- test[, "SalePrice"]

alpha <- mlflow_param("alpha", 0.5, "numeric")
lambda <- mlflow_param("lambda", 0.5, "numeric")
mlflow_set_experiment(experiment_name = 'mlflow_test_houseprice')
                     

with(mlflow_start_run(), {

  model <- glmnet(train_x, train_y, alpha = alpha, lambda = lambda, family= "gaussian", standardize = FALSE)
  predictor <- crate(~ glmnet::predict.glmnet(!!model, as.matrix(.x)), !!model)
  predicted <- predictor(test_x)
  
  rmse <- sqrt(mean((predicted - test_y) ^ 2))
  mae <- mean(abs(predicted - test_y))
  r2 <- as.numeric(cor(predicted, test_y) ^ 2)
  
  message("Elasticnet model (alpha=", alpha, ", lambda=", lambda, "):")
  message("  RMSE: ", rmse)
  message("  MAE: ", mae)
  message("  R2: ", r2)
  
  mlflow_log_param("alpha", alpha)
  mlflow_log_param("lambda", lambda)
  mlflow_log_metric("rmse", rmse)
  mlflow_log_metric("r2", r2)
  mlflow_log_metric("mae", mae)
  mlflow_log_model(predictor, artifact_path ="model")
})`
```
```
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977

```
Is there any solution for this problem? When using Python code, I do not have this problem.

**Comment by sstorey-nephila** [comment]
The root cause of the issue flagged by @vrankenjulie is caused when the call to the Mlflow_cli fails. After digging through the mlflow/R/mlflow code in git I have found how to fix this. 

First add this line to the .Rprofile file in your RProject directory. 

```
Sys.setenv(MLFLOW_VERBOSE=TRUE)
```

This will show the mlflow cli call being made in the R console, here is an example:

> Running "C:/Users/XXX/Anaconda3/envs/r-mlflow-1.5.0/mlflow" artifacts download -u model

Now, as a result of providing the full path (and even though this path is included in the ENV path variable) windows is unable to run mlflow and fails with the following error

> Command not found @win/processx.c:977

So, to fix this I added the following (again to the .Rprofile file)

```
Sys.setenv(MLFLOW_BIN="C:/UsersXXX/Anaconda3/envs/r-mlflow-1.5.0/Scripts/mlflow.exe")
```

And hey presto, all the commands that now delegate from R to the mlflow_cli work like a charm...

These are my entries in my .Rprofile which I'm using to run mlflow hosted on K8 using GCS for the artifact repo.

```
Sys.setenv(RETICULATE_PYTHON="C:/Users/XXX/Anaconda3/envs/r-mlflow-1.5.0")
Sys.setenv(GOOGLE_APPLICATION_CREDENTIALS="C:/Users/XXX/.googleKeys/mlflow-user.json")
Sys.setenv(MLFLOW_TRACKING_URI="http://XX.XX.XX.XXX:XXXX")
Sys.setenv(MLFLOW_VERBOSE=TRUE)
Sys.setenv(MLFLOW_BIN="C:/Users/XXX/Anaconda3/envs/r-mlflow-1.5.0/mlflow.exe")
```

**Comment by n8shadow** [comment]
Hi @sstorey-nephila,
I am working on Databricks wishing to enable mlflow for our projects. However, I'm getting an error similar to that reported by @vrankenjulie: 

 `Elasticnet model (alpha=0.5, lambda=0.5): Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : `
  `cannot start processx process '0' (system error 2, No such file or directory) @unix/processx.c:592 (processx_exec)`

`Elasticnet model (alpha=0.5, lambda=0.5):`
  `RMSE: 0.837190754437358`
  `MAE: 0.627903149006039`
  `R2: 0.220213264479505`
`Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : `
`  cannot start processx process '0' (system error 2, No such file or directory) @unix/processx.c:592 (processx_exec)`

Is there solution already suggested? Help would be much appreciated!

**Comment by GitHunter0** [comment]
I am having similar issue...

**Comment by n8shadow** [comment]
Here is what fixed my issue and made mlflow fully work for me https://github.com/mlflow/mlflow/issues/3177. 
In addition there seems to be a mismatch of the versions of mlflow python backend and R package (both should be 1.10.0). It turned out that an init script getting correct versions and setting the environment variables works best.

**Comment by GitHunter0** [comment]
@n8shadow , I do not use databricks, I tried to set the environment variables but still does not work, but thank you for the response.

**Comment by n8shadow** [comment]
So then, what is the environment you are working on? As said mismatching versions and/or need to set variables might cause that.

**Comment by GitHunter0** [comment]
@n8shadow , right now I'm just experimenting with MLflow locally
