### ISSUE TITLE
[FR] Extend previous work on FIPS compliance

### ISSUE THREAD

**Issue by DueViktor** [mlflow/mlflow#10106]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

From python 3.9 hashlib introduced the usedforsecurity argument:
> Changed in version 3.9: All hashlib constructors take a keyword-only argument usedforsecurity with default value True. A false value allows the use of insecure and blocked hashing algorithms in restricted environments. False indicates that the hashing algorithm is not used in a security context, e.g. as a non-cryptographic one-way compression function.

MLFLOW use hashing in many cases where the purpose is indeed not for security purposes. This should be specifed in the code.

Why you ask?

MLFLOW use MD5 and SHA1 from hashlib, which is not a secure algorithm, but are not specifying that it is for other purposes than security. This is causing issues for organisations following certain security standard. FIPS compliance could be an example.

**My contribution:**
I will attach a PR implementing the similar solution from #9961. I would argue that specifying the kwarg directly could be a cleaner solution, but this is simply a code preference. Another solution can be seen in [this streamlit pull request.](https://github.com/streamlit/streamlit/pull/7527/files)

**Earlier contributions**
I can see that a similar problem was solved in #9961 and addressed in #5959, #9905, #9961.

### Motivation

> #### What is the use case for this feature?

Security compliance

> #### Why is this use case valuable to support for MLflow users in general?
My guess is that pretty much all federal systems in the world would have this issue: "_Federal Information Processing Standards (FIPS) 140-2 is a mandatory standard for the protection of sensitive or valuable data within Federal systems._" - https://www.wolfssl.com/license/fips/

> #### Why is this use case valuable to support for your project(s) or organization?

^^^

> #### Why is it currently difficult to achieve this use case?

As specified in the hashlib documentation both MD5 and SHA1 are proven to have hash collisions: "_Warning Some algorithms have known hash collision weaknesses (including MD5 and SHA1). Refer to [Attacks on cryptographic hash algorithms](https://en.wikipedia.org/wiki/Cryptographic_hash_function#Attacks_on_cryptographic_hash_algorithms) and the [hashlib-seealso](https://docs.python.org/3/library/hashlib.html#hashlib-seealso) section at the end of this document._"

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@DueViktor What should we fix? Apply the same fix to sha1?

**Comment by DueViktor** [comment]
Yes exactly. `hashlib.sha1` is not secure either.

**Comment by harupy** [comment]
Sounds good. https://github.com/streamlit/streamlit/pull/7527/files seems like a cleaner approach. I don't have a strong preference.

**Comment by harupy** [comment]
@DueViktor I'm also considering lint-ability. I think this is something we should prevent as a lint check. We're using ruff and it has SIM324 that prevents insecure hash functions such as md5.

**Comment by harupy** [comment]
@DueViktor We filed #10121.

The following command install mlflow from this PR's branch:

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/10121/merge
```

**Comment by DueViktor** [comment]
Thanks a lot for the quick solution!

**Comment by harupy** [comment]
@DueViktor Do you happen to know how we can this test in GitHub Actions?

**Comment by DueViktor** [comment]
@harupy, I don't know. 

I guess there are two things that can be tested for. (1) Whether mlflow is FIPS compliant. (2) Whether unsecure algorithms are used with a `useforsecurity=True`.

(1) The only idea I have for FIPS compliance is to actually start a server configured in FIPS mode.
(2) Probably solved with ruff

**Comment by harupy** [comment]
Thanks for the reply! Agree on (2). For (1), I'll investigate whether it's possible to build a FIPS-enabled environment.

**Comment by shsma** [comment]
@harupy was this fixed? in which MLFlow version?
Any documentation on how to set `useforsecurity=False` globally for any MLFlow invocation?
