### ISSUE TITLE
Facing issue with Azure Flexibel Mysql Server 8.0

### ISSUE THREAD

**Issue by amitganvir23** [mlflow/mlflow#10105]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- MLflow Version 2.5.0
- Docker Image: ghcr.io/mlflow/mlflow:v2.5.0

### System information

- Docker Image: ghcr.io/mlflow/mlflow:v2.5.0
- pymysql 1.1.0
- mysqlclient  2.2.0
- Azure Mysql 8.0

### Describe the problem

**The first error i was getting**
`sqlalchemy.exc.NotSupportedError: (MySQLdb.NotSupportedError) (1235, "This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key. In @@sql_generate_invisible_primary_key=ON mode table should have a primary key. Please add a new primary key to be able to drop existing primary key.'")`

For the first error I tried below command on Azure mysql server and above error has gone but but it gives second error.
`mysql> SET sql_generate_invisible_primary_key=OFF;`

**The second error i was getting**
```
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1060, "Duplicate column name 'step'")
[SQL: ALTER TABLE metrics ADD COLUMN step BIGINT NOT NULL DEFAULT '0']
```

```
MySQL [(none)]> use amit4;
MySQL [amit4]> desc metrics;
+-----------+--------------+------+-----+---------+-------+
| Field     | Type         | Null | Key | Default | Extra |
+-----------+--------------+------+-----+---------+-------+
| key       | varchar(250) | NO   | PRI | NULL    |       |
| value     | float        | NO   |     | NULL    |       |
| timestamp | bigint       | NO   | PRI | NULL    |       |
| run_uuid  | varchar(32)  | NO   | PRI | NULL    |       |
| step      | bigint       | NO   |     | 0       |       |
+-----------+--------------+------+-----+---------+-------+
5 rows in set (0.004 sec)
MySQL [amit4]> 
```

This is the command which ran with container 
`mlflow server --host 0.0.0.0 -p 5100 --backend-store-uri mysql+pymysql://USERNAME:PASSWORD@DBURL:3306/amit4 --artifacts-destination wasbs://amitg@amit4.blob.core.windows.net --serve-artifacts`

I tried with below mysql docker image and it worked on local but same version of Azure Mysql 8.0 it didnt work but it worked with Azure Mysql 5.7.
mysql:8.0
mysql/mysql-server:8.0

### Tracking information

```
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
@akshaya-a Is this a known issue with the Azure MySQL server? Are there workarounds available to address the alembic / sqlalchemy migration issue?

**Comment by akshaya-a** [comment]
I don't have up to date knowledge on MySQL unfortunately, as Azure Machine Learning uses a completely different CosmosDB based architecture. Let me poke around to see if I can find an SME in that area. A quick internet search pulls up this document specific to the Flexible target that sounds related: https://learn.microsoft.com/en-us/azure/dms/known-issues-azure-mysql-fs-online

I'm not sure if that helps you understand what's going on here, though

**Comment by amitganvir23** [comment]
I found the solution, Earlier it was working with Azure Flexible Mysql 8.0 after sometime it stopped working,  so It was issue from Azure side after recently they have update new global parameters and due to that it was failing it.. To resolve this issue we need to "OFF" the Global Parametes on Azure DB portal on your database and select Server Parameters and set sql_generate_invisible_primary_key OFF on Portal only dont run as command on SQL level.

Thanks,
Amit Ganvir

**Comment by amitganvir23** [comment]
It is fixed now
