### ISSUE TITLE
Model Serving in Production

### ISSUE THREAD

**Issue by avinashraghuthu** [mlflow/mlflow#1015]
Can you help how we can approach the model serving in production? As of now it is running in a single threaded flask server and getting below message while deploying it using mlflow pyfunc command:

mlflow pyfunc serve -r <RUN_ID> -m model

```
 * Serving Flask app "mlflow.pyfunc.scoring_server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:1234/ (Press CTRL+C to quit)

```

I saw that mlflow UI and tracking servers are running on gunicorn. Can we do the same for model serving as well?

**Comment by yassineAlouini** [comment]
That would be a very useful features indeed. I have used the `pyfunc serve` CLI but due to the single-threaded nature of the flask server, it isn't a viable solution for production. 
Making this scoring server more production-ready will be very appreciated. 👍

**Comment by avinashraghuthu** [comment]
I am currently working on this one.I have looked into the code.Unlike mlflow UI and tracking,for model serving we are creating new conda env based on user defined conda.yaml file or default conda.env configuration for model deployment in a new process.So we need to add gunicorn installation at time of creation of this conda env.I will try to finish as soon as possible and raise a PR for the same.

Please let me if I miss any.

**Comment by avinashraghuthu** [comment]
I am currently working on this one.I have looked into the code.Unlike mlflow UI and tracking,for model serving we are creating new conda env based on user defined conda.yaml file or default conda.env configuration for model deployment in a new process.So we need to add gunicorn installation at time of creation of this conda env.I will try to finish as soon as possible and raise a PR for the same.

Please let me if I miss any.

**Comment by yassineAlouini** [comment]
Awesome, that would be great. 👍

**Comment by avinashraghuthu** [comment]
Closing the issue as gunicorn support has been added in MLflow 1.0.0

**Comment by finelycheng** [comment]
when i call the function  mlflow.pytorch.save_model(model,"model")   the model save successed. 
but when i use the command  **mlflow models serve -m "model path"**  -p 1234  to serve the model 
the exception happened like this
  ```
Traceback (most recent call last):
  File "/home/academy/svn-Center/src/LoadModel.py", line 8, in <module>
    mlflow.pytorch.load_model("hdfs://finely:9000/3/b81d968bc5244c879cd2a13935b94b23/artifacts/model")
  File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 345, in load_model
    return _load_model(path=torch_model_artifacts_path, **kwargs)
  File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 296, in _load_model
    return torch.load(model_path, **kwargs)
  File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.networks'
```
i use this api to test load the model, but failed with the same error. **mlflow.pytorch.load_model("hdfs://finely:9000/3/b81d968bc5244c879cd2a13935b94b23/artifacts/model")**

but when i use the pytorch orgin api to save the model, then load use mlflow.pytorch.load_model , it right works

**Comment by utopianpallu** [comment]
> when i call the function mlflow.pytorch.save_model(model,"model") the model save successed.
> but when i use the command **mlflow models serve -m "model path"** -p 1234 to serve the model
> the exception happened like this
> 
> ```
> Traceback (most recent call last):
> File "/home/academy/svn-Center/src/LoadModel.py", line 8, in <module>
>   mlflow.pytorch.load_model("hdfs://finely:9000/3/b81d968bc5244c879cd2a13935b94b23/artifacts/model")
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 345, in load_model
>   return _load_model(path=torch_model_artifacts_path, **kwargs)
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 296, in _load_model
>   return torch.load(model_path, **kwargs)
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
>   return _load(f, map_location, pickle_module)
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/torch/serialization.py", line 538, in _load
>   result = unpickler.load()
> ModuleNotFoundError: No module named 'models.networks'
> ```
> 
> i use this api to test load the model, but failed with the same error. **mlflow.pytorch.load_model("hdfs://finely:9000/3/b81d968bc5244c879cd2a13935b94b23/artifacts/model")**
> 
> but when i use the pytorch orgin api to save the model, then load use mlflow.pytorch.load_model , it right works

add your model.py file code in main.py file. It worked for me.

**Comment by utopianpallu** [comment]
> when i call the function mlflow.pytorch.save_model(model,"model") the model save successed.
> but when i use the command **mlflow models serve -m "model path"** -p 1234 to serve the model
> the exception happened like this
> 
> ```
> Traceback (most recent call last):
> File "/home/academy/svn-Center/src/LoadModel.py", line 8, in <module>
>   mlflow.pytorch.load_model("hdfs://finely:9000/3/b81d968bc5244c879cd2a13935b94b23/artifacts/model")
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 345, in load_model
>   return _load_model(path=torch_model_artifacts_path, **kwargs)
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 296, in _load_model
>   return torch.load(model_path, **kwargs)
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
>   return _load(f, map_location, pickle_module)
> File "/opt/anaconda3/envs/center/lib/python3.7/site-packages/torch/serialization.py", line 538, in _load
>   result = unpickler.load()
> ModuleNotFoundError: No module named 'models.networks'
> ```
> 
> i use this api to test load the model, but failed with the same error. **mlflow.pytorch.load_model("hdfs://finely:9000/3/b81d968bc5244c879cd2a13935b94b23/artifacts/model")**
> 
> but when i use the pytorch orgin api to save the model, then load use mlflow.pytorch.load_model , it right works

Hi can you try pasting your model code into main.py file and then run, It worked for me.
