### ISSUE TITLE
Upgrade ruff to `0.1.3`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#10217]
### Summary

```diff
diff --git a/requirements/lint-requirements.txt b/requirements/lint-requirements.txt
index 5f7e290d3..9558b903a 100644
--- a/requirements/lint-requirements.txt
+++ b/requirements/lint-requirements.txt
@@ -1,5 +1,5 @@
 pylint==2.14.4
-ruff==0.0.292
+ruff==0.1.3
 rstcheck==6.1.1
 black[jupyter]==23.7.0
 blacken-docs==1.16.0
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by harupy** [comment]
This is preparation to migrate to `ruff format` from `black`.

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign me.

**Comment by harupy** [comment]
@milinddethe15 Thanks!
