### ISSUE TITLE
Enable useless-comparison (B015)

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#10215]
### Summary

Enable [useless-comparison (B015)](https://docs.astral.sh/ruff/rules/useless-comparison/):

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 3a6cb6617..2177577e7 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -16,6 +16,7 @@ target-version = "py38"
 dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
 select = [
   "B006",
+  "B015",
   "E",
   "F",
   "C4",
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `Resolve #{issue_number}` (e.g. `Resolve #123`) in the PR description when opening a PR.

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign me.

**Comment by harupy** [comment]
@milinddethe15 thanks!
