### ISSUE TITLE
Add `extend-include = ["*.ipynb"]` in `pyproject.toml`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#10216]
### Summary

To opt in to linting Jupyter Notebook (.ipynb) files, add the *.ipynb pattern to your [extend-include](https://docs.astral.sh/ruff/settings/#extend-include) setting: https://docs.astral.sh/ruff/faq/#does-ruff-support-jupyter-notebooks

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 3a6cb6617..34200dc97 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -70,6 +70,7 @@ ignore = [
   "E741",  # ambiguous-variable-name
   "F811",  # redefined-while-unused
 ]
+extend-include = ["*.ipynb"]
 extend-exclude = [
   "setup.py",
   "docs",
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by flooxo** [comment]
Hey, I'd like to work on this issue :)

**Comment by harupy** [comment]
@flooxo Awesome, assigned!
