### ISSUE TITLE
Rename `LLM Evaluation Examples -- RAG.ipynb` and  `LLM Evaluation Examples -- QA.ipynb`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#10225]
### Summary

A space in a filename can cause errors. They should be removed by running this command:

```
git mv 'examples/evaluation/LLM Evaluation Examples -- RAG.ipynb' examples/evaluation/rag-evaluation.ipynb
git mv 'examples/evaluation/LLM Evaluation Examples -- QA.ipynb' examples/evaluation/qa-evaluation.ipynb
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `Resolve #{issue_number}` (e.g. `Resolve #123`) in the PR description when opening a PR.

**Comment by milinddethe15** [comment]
Hi @harupy, I want to work on this. Assign me.

**Comment by harupy** [comment]
@milinddethe15 Thanks!
