### ISSUE TITLE
[DOC-FIX] Link to new AI gateway on homepage goes to bad index.html page

### ISSUE THREAD

**Issue by srinify** [mlflow/mlflow#10228]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

- Homepage: https://mlflow.org/

<img width="771" alt="Screenshot 2023-10-30 at 9 30 24 AM" src="https://github.com/mlflow/mlflow/assets/801507/9a7f8055-cbac-4b04-97ef-eaa32c3e9bd4">

- "New AI gateway... Check out the [docs](https://www.mlflow.org/docs/latest/gateway/index.html) to get started!" -> goes to https://www.mlflow.org/docs/latest/gateway/index.html instead of https://mlflow.org/docs/latest/index.html
<img width="1028" alt="Screenshot 2023-10-30 at 9 31 19 AM" src="https://github.com/mlflow/mlflow/assets/801507/bedbb2b3-f8dd-4976-9739-6e31afbe5ff0">

I'm happy to fix this if someone can point me to the source code for the homepage. I only see the docs source code in the repo at the moment.

### Description of proposal (what needs changing)

Fix the busted link

**Comment by BenWilson2** [comment]
The fix (well, removing it) has been deployed. Thanks again for reporting the issue!
