### ISSUE TITLE
Enhancement: None value is not supported to be default value of an argument in MLproject file

### ISSUE THREAD

**Issue by therajmaurya** [mlflow/mlflow#1022]
name: test

conda_env: conda.yaml

entry_points:
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main:
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameters:
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;train-data: path
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;test-data: path
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n-estimators: {type: int, default: 25} 
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;criterion: {type: string, default: 'gini'}
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max-depth: {type: int, default: None}
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;class-weight: {type: string, default: None}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;command: "python train.py --train-data {train-data} --test-data {test-data} --n-estimators {n-estimators} --criterion {criterion} --max-depth {max-depth} --class-weight {class-weight}"

When I run my project using "mlflow run /path/to/project -P train-data=/path/to/train.csv -P test-data=/path/to/test.csv", and let other parameters to be default, i get the following error:

*train.py: error: argument --max-depth: invalid int value: 'None'
2019/03/21 11:54:01 ERROR mlflow.cli: === Run (ID '32b29882442347ad9d361035b70fc116') failed ===*

**Comment by kydos93** [comment]
I would like this to be reopened. There is no way to specify an optional/default value of None for string/uri types either

**Comment by sn1c** [comment]
This would definitely be a useful feature, e.g. in cases in which a parameter is only used for one classifier.

**Comment by alam-shahul** [comment]
Is there any progress on this?
