### ISSUE TITLE
MLFlow Azure ML Build Image Failing: xgboost package not found

### ISSUE THREAD

**Issue by brijenshah** [mlflow/mlflow#1023]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks 5.2, Spark 2.4.0
- **MLflow installed from (source or binary): binary
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**: 3
- **npm version (if running the dev UI): NA
- **Exact command to reproduce**:mlflow.azureml.build_image

### Describe the problem
I am trying to deploy the model to Azure Machine Learning Service from Azure Databricks using mlflow.azureml apis but it's failing at image creation

### Source code / logs
model_path="sk_models"

model_image, azure_model = mlflow.azureml.build_image(model_path=model_path, 
                                                      workspace=ws, 
                                                      run_id=run_id,
                                                      model_name="model",
                                                      image_name="model",
                                                      description="Model Deployment",
                                                      synchronous=False)
### conda.yaml
channels:
- defaults
dependencies:
- python=3.5.2
- scikit-learn=0.18.1
- cloudpickle==0.8.0
- xgboost
name: mlflow-env

### Error
FailedImage creation operation finished for image model:6, operation "Failed"
Image creation failed with
StatusCode: 400
Message: Docker image build failed.

### Logs 
Step 11/14 : RUN sed -i '/^\s*-\s*python\s*[<>=]/d' '/var/azureml-app/conda.yaml' && cat '/var/azureml-app/conda.yaml'
 ---> Running in 4b6dba625481
channels:
- defaults
dependencies:
- scikit-learn=0.18.1
- cloudpickle==0.8.0
- xgboost
name: mlflow-env
Removing intermediate container 4b6dba625481
 ---> 73c983a5af9e
Step 12/14 : RUN CONDA_ROOT_DIR=$(conda info --root) && if [ -n "$CONDA_ENV_PATH" ]; then conda env update -p "$CONDA_ENV_PATH" -f '/var/azureml-app/conda.yaml'; else conda env update -n base -f '/var/azureml-app/conda.yaml'; fi && conda clean -aqy && rm -rf /root/.cache/pip && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} +
 ---> Running in dbdcbb6a6f5a
Collecting package metadata: ...working... done
Solving environment: ...working... failed
[91m
ResolvePackageNotFound: 
  - xgboost

I also tried removing XGBoost from conda.yaml and image was successfully but it was failing at Webservice.deploy_from_image. It's not able to find XGBoost dependency or load package.

**Comment by brijenshah** [comment]
It got resolved by updating the conda.yaml. 
### conda.yaml 
channels:
- defaults
dependencies:
- python=3.5.2
- scikit-learn=0.18.1
- cloudpickle==0.8.0
- pip:
    - xgboost 
name: mlflow-env

I updated with pip package

**Comment by prakharter** [comment]
@brijenshah I also got the same issue but with Scikit-learn. Can you please advise where you edit the conda.yaml as i am not getting any option to edit it either on databricks or Azure ML. Thank you
