### ISSUE TITLE
ModuleNotFoundError: No module named 'mlflow.pytorch'; 'mlflow' is not a package [BUG]

### ISSUE THREAD

**Issue by ss8319** [mlflow/mlflow#10298]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

mlflow  2.8.0                    pypi_0    pypi
- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution Windows 10 Home Single Language**:
- **Python version Python 3.9.7**:
- **yarn version, if running the dev UI**:

### Describe the problem
**Intend:** I have a separate script -'train.py' used to train my DL model on my local machine. Once it is trained, I am trying to log it on MLflow using it as a Model Registry.

This other error might also be a useful hint.
`$ python mlflow.py
Traceback (most recent call last):
  File "D:\Lunit Assignment Conda\mlflow.py", line 1, in <module>
    import mlflow
  File "D:\Lunit Assignment Conda\mlflow.py", line 2, in <module>
    from mlflow import pytorch
ImportError: cannot import name 'pytorch' from partially initialized module 'mlflow' (most likely 
due to a circular import) (D:\Lunit Assignment Conda\mlflow.py)`

Doing `conda list`, shows - `mlflow                    2.8.0                    pypi_0    pypi`.

My understanding of whats happening is that mlflow has not been installed properly. But I dont know how to fix this. 
Thank you!

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
1.
 conda activate my_env
 conda install mlflow/pip install mlflow
2. Create file mlflow_register.py
 'import mlflow
import mlflow.pytorch
from argparse import ArgumentParser
from train_light import LitMNIST 

def log_to_mlflow(model, model_name, run_name):    
    with mlflow.start_run(run_name=run_name):
        mlflow.pytorch.log_model(model, model_name)

if __name__ == '__main__':
    parser = ArgumentParser(description="Log a PyTorch model to MLflow")
    parser.add_argument("--model_path", type=str, default="saved_model.pth", help="Path to the saved PyTorch model file")
    parser.add_argument("--model_name", type=str, default="my_mnist_model", help="Name for the model in MLflow")
    parser.add_argument("--run_name", type=str, default="training_run_1", help="Name for the MLflow run")
    args = parser.parse_args()

    # Initialize the model with the desired configuration
    model = LitMNIST()  # You can customize this further with your specific parameters

    # Load the model from the specified file
    checkpoint = torch.load(args.model_path)
    model.load_state_dict(checkpoint)

    # Log the model to MLflow with the specified model name and run name
    log_to_mlflow(model, args.model_name, args.run_name)'

3.  python mlflow.py --model_path saved_model_1epochs.pth
```

### Stack trace

```
**Error**
`$ python mlflow_register.py
Traceback (most recent call last):
  File "D:\Lunit Assignment Conda\mlflow.py", line 1, in <module>
    import mlflow
  File "D:\Lunit Assignment Conda\mlflow.py", line 2, in <module>
    import mlflow.pytorch
ModuleNotFoundError: No module named 'mlflow.pytorch'; 'mlflow' is not a package
(test) `
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@ss8319 Could you rename your file to a different name other than `mlflow.py`? I can't repro your problem in a python repl

**Comment by ss8319** [comment]
Hi @serena-ruan. I am not sure what you mean but I changed the filename to `mlflow_register.py`
