### ISSUE TITLE
Persist metadata within Document NOSQL store

### ISSUE THREAD

**Issue by dschmitz** [mlflow/mlflow#1031]
### Describe the problem
For better analytics of the machine learning life cycle it would be very handy to persist the metadata (including metrics) of mlflow into a document store like elasticsearch or mongodb. This would make things a lot more easier for reasoning about changes throughout the lifecycle.

**Comment by acroz** [comment]
@dschmitz a plugin system was recently merged (and will be available in 0.9.0) that allows registration of additional tracking store implementations with MLflow. For an example of what this looks like, you can see the plugin we're developing at @facultyai:

https://github.com/facultyai/mlflow-faculty

I'd be happy to collaborate on developing one if you're interested.

**Comment by harshitsaini** [comment]
@dschmitz @acroz  
This plugin sounds like a good solution to many use-cases. Is the plugin already built as of now, I would like to collaborate further.
