### ISSUE TITLE
[FR] Renaming a run has no immediate visual effects

### ISSUE THREAD

**Issue by baxtree** [mlflow/mlflow#10371]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

2.8.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 12
- **Python version**: 3.10.13
- **yarn version, if running the dev UI**:

### Describe the problem

This is more of a missing feature than a bug so feel free to re-tag it. Saving a run with a new name leads to no UI effects and the old name is still displayed.

<img width="873" alt="RenameRun" src="https://github.com/mlflow/mlflow/assets/351072/715b7a4c-006e-40d9-90e2-3117f510c3af">

### Steps to reproduce the bug

On the run page, after clicking the vertical ellipsis button and renaming the run, the previous name persists on the same page after the renaming dialogue is closed. It is a bit tricky to tell if the operation is successful or not unless users go back to the previous experiment page and scroll through the potentially lengthy list of runs.

### Is the console panel in DevTools showing errors relevant to the bug?

No errors shown in the console.

### Does the network panel in DevTools contain failed requests relevant to the bug?

No failed requests. The successful response does contain `run_name` with the new value:
```json
{
  "run_info": {
    "run_uuid": "4b839826310a47f8b745f83caece045b",
    "experiment_id": "11",
    "run_name": "test-run",
    "user_id": "rmhixba",
    "status": "FINISHED",
    "start_time": 1699620596317,
    "end_time": 1699620749232,
    "artifact_uri": "s3://cms-model-bucket/11/4b839826310a47f8b745f83caece045b/artifacts",
    "lifecycle_stage": "active",
    "run_id": "4b839826310a47f8b745f83caece045b"
  }
}
```

**Comment by BenWilson2** [comment]
What version of the MLflow client were you using when you created that run? That is the legacy naming convention (a UUID) from prior to MLflow 1.30 release. https://github.com/mlflow/mlflow/pull/6736 Are you setting a uuid as the name within your code or are you using a very old version of the MLflow package within your code base?

**Comment by BenWilson2** [comment]
https://github.com/mlflow/mlflow/assets/39283302/34a62709-8a70-4019-ab69-934e7d4ecd3e

Also, it works just fine on the 2.8.0 release.

**Comment by baxtree** [comment]
I used UUID as the run name intentionally and the version is 2.8.0. Sorry, maybe my description was not clear enough. What I meant is after the Save button is clicked, the run name on the page is not changed accordingly. I did notice in the screencast, you refreshed the whole page to get the on-page name updated. Anyway, this FR is not a big deal but a nice-to-have.

**Comment by BenWilson2** [comment]
@baxtree I'll pass on the idea to one of the folks that maintains the UI to see if activating the button for setting a new name could initiate a page refresh. We'll see what they think!

**Comment by baxtree** [comment]
Oh thanks @BenWilson2
