### ISSUE TITLE
[DOC-FIX] No information on how to enable model staging

### ISSUE THREAD

**Issue by xecarlox94** [mlflow/mlflow#10387]
### Willingness to contribute

Yes. I would be willing to contribute a document fix with guidance from the MLflow community.

### URL(s) with the issue

I am finishing the "getting started" tutorial [https://mlflow.org/docs/latest/getting-started/quickstart-2/index.html#register-your-best-model](url). I am using a local machine. When I first registered the I remember that I got a pop-up window asking me if I wanted staging enabled.

By mistake, I did not enable it (I rushed it to be fair) but I really would like to enable it again.

I have tried to search through the official MlFlow documentation, and the wider internet, but I could not find any resource mentioning this. The Model Registry page does not offer information relative to this issue.
[https://mlflow.org/docs/latest/model-registry.html](url)

Is it possible to re-enable model staging?

I think this would be something important to be cleared up.

### Description of proposal (what needs changing)

I would like to add a small note section with a small description on how to re-enable model staging, or at least to point to a resource that can help.

**Comment by BenWilson2** [comment]
The model registry is only available if you have your backend store (https://mlflow.org/docs/latest/tracking.html#backend-stores) set as a Database (see the first note in that section). You can use your local filesystem as a database with a SQLite DB if you just want to do local testing. 
For an actual deployment of MLflow for "real use", you should look into starting an actual Database (MySQL, PostGres, MSSQL, etc.) to persist your experiments, runs, and their data permanently. 
We're working on more extensive guides that will provide detailed step-by-step walkthroughs of how to get this infrastructure set up. Stay tuned if you'd like to have that experience be much less frustrating for getting everything up and running!
