### ISSUE TITLE
[feature request] Measuring drift in accuracy of an ML model deployed in production over time

### ISSUE THREAD

**Issue by keerath** [mlflow/mlflow#1044]
This is a very common problem that people face when models are deployed in production. End users want to know when to re-train a model in order to bridge this gap. I was just wondering if this could be added as an additional component to MLFlow post model deployment. Would like to know your thoughts about this.

**Comment by keerath** [comment]
@smurching @aarondav @dbczumar

**Comment by flowersw** [comment]
why was this FR closed? Was it determined out of scope for mlflow?
