### ISSUE TITLE
result_type='double' is hardcoded when in the UI for logged Model

### ISSUE THREAD

**Issue by praateekmahajan** [mlflow/mlflow#10453]
Currently it always shows 
```python
loaded_model = mlflow.pyfunc.spark_udf(spark, model_uri=logged_model, result_type='double')
```
Irrespective of model signature. I believe the fix would be to a) remove `result_type` altogether as model_signature becomes a required field b) the function [`sparkDataFrameCodeText`](https://github.com/mlflow/mlflow/blob/a87ae86eb446f5215c7efab9b3160e895a061581/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.tsx#L116) also accepts `model_signature` as an argument rather than only `modelPath`

![image](https://github.com/mlflow/mlflow/assets/7589415/77a2ab35-2531-4ef8-8c59-b8d9a5a583a2)

https://github.com/mlflow/mlflow/blob/a87ae86eb446f5215c7efab9b3160e895a061581/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.tsx#L116

**Comment by WeichenXu123** [comment]
I think we can remove `result_type` argument in the UI code, if we do not set the argument, when the model has "output signature", result type is inferred from output signature, otherwise 'double' is used as default `result_type`.
