### ISSUE TITLE
#Query#: Does Gridsearch parent runid correspond to the best model #mflow versions used : 1.28 and 2.3.2

### ISSUE THREAD

**Issue by LakshmiN5** [mlflow/mlflow#10530]
### Summary

I tried this example - >  https://github.com/mlflow/mlflow/blob/master/examples/sklearn_autolog/grid_search_cv.py

Please confirm if the parent run (last active run)  corresponds to the best estimator. If not how do I extract the run id that corresponds to the best clf.best_estimator_ ?

**Comment by B-Step62** [comment]
@LakshmiN5 Thank you for reaching out. 

> Please confirm if the parent run (last active run) corresponds to the best estimator. If not how do I extract the run id that corresponds to the best clf.best_estimator_ ?

No, the parent run doesn't represent the one with the best score. You can search children runs using [MLflowClient().search_run()](https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_experiments) API, with filtering by the parent id as tag and sorting with the target metric. Please find more details in [Search Run](https://mlflow.org/docs/latest/search-runs.html) documentation.

Also, `good first issue` label and template should be used by maintainer only. Please file an issue with other appropriate templates e.g. Bug Report next time. Thank you.

**Comment by LakshmiN5** [comment]
thank you for the update @B-Step62 , I ensure to use the appropriate template next time. Thanks for pointing out.
