### ISSUE TITLE
[BUG] Chart line for the chart tab is inconsistently linking points

### ISSUE THREAD

**Issue by ThR3742** [mlflow/mlflow#10536]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.8.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- Linux
- **Python version**:
- Python3.9
- **yarn version, if running the dev UI**:
- N/A

### Describe the problem

When we add a chart of type "Line Chart" through the Chart tab on the experiment view,  points in the chart are linked by time of arrival instead of the x axis value which makes this feature essentially unusable (in many use cases, especially asynchroneous evaluation use case, points might arrive not in order and we need to use the x axis value instead to link them).

Fortunately, this bug is not present when we generate a line chart from the experiment detail.

### Steps to reproduce the bug

Run the code indicated below, add a chart of type "Line Chart" in the "Chart" tab.

### Code to generate data required to reproduce the bug

```python
import mlflow

mlflow.set_tracking_uri(YOUR_SERVER)
mlflow.set_experiment("Default")

with mlflow.start_run(run_name="test"):
    mlflow.log_metric("loss", 7, step=4)
    mlflow.log_metric("loss", 10, step=1)
    mlflow.log_metric("loss", 9, step=2)
    mlflow.log_metric("loss", 4, step=7)
    mlflow.log_metric("loss", 3, step=8)
    mlflow.log_metric("loss", 3, step=9)
    mlflow.log_metric("loss", 6, step=5)
    mlflow.log_metric("loss", 5, step=6)
```

**Comment by ThR3742** [comment]
The issue might come from https://github.com/mlflow/mlflow/blob/4b8bb73ea5e30e3df312ae4ce9d1d3825a6faf09/mlflow/server/js/src/experiment-tracking/components/runs-charts/components/RunsMetricsLinePlot.tsx#L136C18-L136C48 where we don't sort the metricHistory

**Comment by B-Step62** [comment]
@ThR3742 Yes, this looks like a critical bug. Thank you so much for reporting this issue!! I also greatly appreciate you for pointing out the exact lines causing the issue. As we have incoming release, I took a quick step to implement the fix so as to make sure it is resolved in the next version.
