### ISSUE TITLE
Input forms in MLflow UI for 0.9.0 are not editable

### ISSUE THREAD

**Issue by shu-yusa** [mlflow/mlflow#1056]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX 10.14.3
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**: 3.6.5
- **npm version (if running the dev UI):
- **Exact command to reproduce**: `mlflow server --backend-store-uri ./mlruns --host 0.0.0.0`

### Describe the problem
I am running the mflow tracking server by the above command, and access to http://localhost:5000.
Input forms for `Search Runs`, `Filter Params`, and `Filter Metrics` are not editable.  
When I downgrade mlflow to 0.8.2 by `pip install mlflow==0.8.2`, and launch the server by `mlflow server --file-store ./mlruns --host 0.0.0.0`, then it works fine.

**Comment by mparkhe** [comment]
Hi @shu-yusa:

There was an issue with a javascript library pulled into MLflow which caused this issue. This should not affect `0.9.0` and was fixed in #1007 in `master` branch. My recommendation is to either use `branch-0.9` or rebase `master` to post #1007 fix.

**Comment by shu-yusa** [comment]
@mparkhe Understood. Thank you for the quick response!

**Comment by mparkhe** [comment]
You may need to re-build javascript server code. 
https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#install-node-modules

**Comment by shu-yusa** [comment]
@mparkhe got it. I will try that. Thanks again.

**Comment by timothyjlaurent** [comment]
Rebuilding the package isn't a very satisfactory resolution to this issue -- Y'all should release a fix, instead.

**Comment by timothyjlaurent** [comment]
I installed mlflow 0.9.0 from pypi -- time for 0.9.1 ??

**Comment by timothyjlaurent** [comment]
I installed from branch branch-0.9 -- still can't type

**Comment by mparkhe** [comment]
@timothyjlaurent : so I understand do you see this issue with `0.9.0` from pypi?
The earlier issue we were aware of only affected master not any releases. If #1113 is from pypi `mlflow 0.9.0`, that is a different issue we need to address.

cc: @smurching

**Comment by timothyjlaurent** [comment]
Yes, @mparkhe  installing from pypi mlflow==0.9.0 you can't type -- I've also tried installing from source, branch-0.9 and master, and rebuilding the js dependencies as mentioned in #1113 and still can't input in the web form.

**Comment by smurching** [comment]
@timothyjlaurent @shu-yusa thanks for catching & reporting this issue! It is a legitimate bug & we've fixed it in MLflow 0.9.0.1 (a PyPI-only release). You can upgrade to the new version via pip install --upgrade mlflow - let me know if there are any other issues, and thanks again :)

**Comment by timothyjlaurent** [comment]
Woot!! Thanks @shu-yusa
