### ISSUE TITLE
mlflow ui - cannot type?

### ISSUE THREAD

**Issue by mxlei01** [mlflow/mlflow#1057]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**:  pip
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**: 3.6
- **npm version (if running the dev UI):3.5.2
- **Exact command to reproduce**: mlflow ui

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

Cannot type anything into the webpage?

![image](https://user-images.githubusercontent.com/7399324/55193514-cd0cd980-516c-11e9-8517-e76723a25876.png)

**Comment by mparkhe** [comment]
Duplicate #1056.
