### ISSUE TITLE
[FR] An argument to `mlflow.login()` that toggles interactive behavior

### ISSUE THREAD

**Issue by henxing** [mlflow/mlflow#10571]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Add an argument that controls whether or not user input is solicited after the initial call to `_validate_databricks_auth` fails.

### Motivation

> #### What is the use case for this feature?
In any automated uses of `mlflow`, e.g. CI/CD pipelines, where there will be no user.

> #### Why is this use case valuable to support for MLflow users in general?
Many users make use of CI/CD pipelines to start training/testing runs that will be logged with `mlflow`.

> #### Why is this use case valuable to support for your project(s) or organization?
Because I am currently setting up a CircleCI pipeline that will not have a user to provide input.

> #### Why is it currently difficult to achieve this use case?
My current workaround is to import `_validate_databricks_auth` from `mlflow.utils.credentials` and run that directly, which is making use of a non-public function.

### Details

My proposed implementation would add the argument `interactive` with the default value of `True` to `mlflow.login()` and check its value before proceeding to ask for user input after an unsuccessful attempt to log in via `_validate_databricks_auth`. If it is set to `False`, I would raise a relevant exception, rather than continue to ask for user input.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @henxing this seems valuable. Feel free to file a PR and link it to this issue when you file it. I'll assign this issue to you for next steps of implementation and PR filing. Thanks for the great idea :)

**Comment by henxing** [comment]
@BenWilson2 I've opened #10623 with the changes, let me know what you think!
