### ISSUE TITLE
[FR] Slim down dependencies in registered models

### ISSUE THREAD

**Issue by jlopezpena** [mlflow/mlflow#10681]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Replace `mlflow` dependency by `mlflow-skinny` in exported requirement files when logging a model into the model registry.

### Motivation

> #### What is the use case for this feature?

When using `mlflow.log_model(...)` in a `mlflow` run, a series of files get stored as artifacts in order to be able to deploy/serve the model. Some of these files (`conda.yaml`, `requirements.txt`) contain the dependencies needed by the model. One of these dependencies is always `mlflow`, pointing at whatever version the run happens to be using.

These dependencies get later installed when deploying serving a model.

The `mlflow` dependency, however, contains a lot of additional stuff that is not required to run or use the model, particularly all the server-side `mlflow` code. This results in creating larger virtual environments or docker containers than strictly needed, resulting in slower and potentially more expensive deployments.

The proposal is to replace the `mlflow` dependency by `mlflow-skinny`, which would just contain the client side code. This should be enough to load and run the model from the model serving side.

> #### Why is this use case valuable to support for MLflow users in general?

Model deployments virtual envs would be smaller, snappier to build and deploy, and not lack any needed functionality

> #### Why is this use case valuable to support for your project(s) or organization?

I end up parsing the requirements files and making the replacement before building our model containers, this would remove the required extra step

> #### Why is it currently difficult to achieve this use case?

Nothing is particularly difficult, it looks mostly like an oversight when assembling the dependencies required by a model

### Details

This would just require changing the string included in the dependencies files logged into the artifact store when calling `mlflow.log_model`. Depending of how fragmented the export code is the change might need to be implemented repeatedly across different model flavors.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Sorry @jlopezpena I pinged the wrong person. After a second thought, this might be affecting model serving so we need to be careful. There are two options: 1. specifying `extra_pip_requirements=["mlflow-skinny"]` when you log a model and this would remove mlflow as default dependency. 2. We could add an argument to enable/disable using mlflow-skinny or mlflow as default dependency, and still default to use mlflow for backwards compatibility.

**Comment by serena-ruan** [comment]
Seems loading model function now depends on flask, so for now we shouldn't change it with mlflow-skinny

**Comment by serena-ruan** [comment]
mlflow/pyfunc/scoring_server/__init__.py file imports flask
