### ISSUE TITLE
BAD_REQUEST when fetching metrics data from Azure ML workspace jobs

### ISSUE THREAD

**Issue by TheBugKing** [mlflow/mlflow#10694]
### Discussed in https://github.com/mlflow/mlflow/discussions/10693

<div type='discussions-op-text'>

<sup>Originally posted by **TheBugKing** December 14, 2023</sup>
I am working for a client and have finetuning ML jobs in a workspace which produces metrics data.
I am using MLFLOW to fetch the metrics from the jobs including historical runs ( all the iterations ).

It was working fine for long time, but since yesterday whenever we fetch the metrics, a new error is encountered as given below.

"BAD_REQUEST: Response: {'Error': {'Code': 'UserError', 'Severity': None, 'Message': 'MaxResults = 25000 is invalid: MaxResults must be less than 1000.', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None, 'AdditionalInfo': None}, 'Correlation': {'operation': '61e2e76bd130c2178dc08f899a089b62', 'request': '2578e530e9bffb59'}, 'Environment': 'westeurope', 'Location': 'westeurope', 'Time': '2023-12-13T16:27:55.0540052+00:00', 'ComponentName': 'mlflow', 'statusCode': 400, 'error_code': 'BAD_REQUEST'}"

code used:
[2312140030000687.zip](https://github.com/mlflow/mlflow/files/13668954/2312140030000687.zip)

Ideally the output of the code should looking like the attached json file
[matrix_sample_when_mlflow_is_working.json](https://github.com/mlflow/mlflow/files/13668800/matrix_sample_when_mlflow_is_working.json)

stack trace:
[stack trace.txt](https://github.com/mlflow/mlflow/files/13668958/stack.trace.txt)

packages:
azureml-mlflow==1.53.0
mlflow==2.7.1

the value causing the error:
GET_METRICS_HISTORY_MAX_RESULTS
mlflow\store\tracking\__init__.py
![image](https://github.com/mlflow/mlflow/assets/40294161/d7b264c5-9e53-4c9e-9dd8-c553957df34d)
</div>

**Comment by daniellok-db** [comment]
Hi @TheBugKing, what does [your setup](https://mlflow.org/docs/latest/tracking.html#common-setups) look like? Are you trying to fetch metrics from a remote tracking server, and if so, have you checked if anything changed on the remote server?

**Comment by serena-ruan** [comment]
@akshaya-a Any ideas about this?

**Comment by akshaya-a** [comment]
@wamartin-aml is tracking this already and the fix for the validation is rolling out across regions with WEU being released today.

If you would like to unblock yourself before that, please manually set a lower page size in the client api

**Comment by wamartin-aml** [comment]
The fix should have been rolled out to westeurope about 12 hours ago - please tag me here if you need any other regions expedited or are still seeing issues in westeurope!

**Comment by TheBugKing** [comment]
Hi all,

upon discussion with MS Product team, it was issue on the remote server, and fixes were rolled out in WE region.

**Comment by TheBugKing** [comment]
> @wamartin-aml is tracking this already and the fix for the validation is rolling out across regions with WEU being released today.
> 
> If you would like to unblock yourself before that, please manually set a lower page size in the client api

yes, that is what I did. as temporary fix
