### ISSUE TITLE
Do not run `protect` job on push

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#10739]
### Summary

The protect job doesn't need to run on push.

```diff
diff --git a/.github/workflows/protos.yml b/.github/workflows/protos.yml
index d3bd1527e1..28b00792b6 100644
--- a/.github/workflows/protos.yml
+++ b/.github/workflows/protos.yml
@@ -10,10 +10,6 @@ on:
     paths:
       - mlflow/protos/**
       - mlflow/java/client/src/main/java/com/databricks/api/proto/**
-  push:
-    branches:
-      - master
-      - branch-[0-9]+.[0-9]+
 
 permissions:
   contents: read
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by Ankit8848** [comment]
Hey @harupy  , Can I work on this? Last time, I accidentally combined both issues pr.
