### ISSUE TITLE
[BUG] mlflow.pytroch.load_model() can't load register model after the model class moved to another .py file

### ISSUE THREAD

**Issue by zorro-gridi** [mlflow/mlflow#10766]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow == 2.9.2

### System information

MacOS

### Describe the problem

when I moved the 'LstmModel' model class from '../lstm_ts.py' file to another package file, and use mlflow.pytorch.load_model or pyfunc to load the register model,  I got a AttributeError like thiis below:
AttributeError: Can't get attribute 'LstmModel' on <module 'mlops.tasks.lstm_ts' from '/home/mlops/tasks/lstm_ts.py'> 
How to change the model package filepath or any other solution about the Exception to give a flexiblity, thank you!

### Tracking information

Traceback (most recent call last):
  File "/home/zorro/project/pycharm/Fund/Index_Markup_Forecasting/test.py", line 22, in <module>
    loaded_model = mlflow.pyfunc.load_model(f'models:/{model_name}/{version}')._model_meta
  File "/home/zorro/miniconda3/envs/ts/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 680, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/home/zorro/miniconda3/envs/ts/lib/python3.10/site-packages/mlflow/pytorch/__init__.py", line 722, in _load_pyfunc
    return _PyTorchWrapper(_load_model(path, **kwargs))
  File "/home/zorro/miniconda3/envs/ts/lib/python3.10/site-packages/mlflow/pytorch/__init__.py", line 628, in _load_model
    return torch.load(model_path, **kwargs)
  File "/home/zorro/miniconda3/envs/ts/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/zorro/miniconda3/envs/ts/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/zorro/miniconda3/envs/ts/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'LstmModel' on <module 'mlops.tasks.lstm_ts' from '/home/mlops/tasks/lstm_ts.py'>

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
I think you're going to need to load the model weights directly using torch APIs directly and then re-save the model with MLflow in order to reflect the changes in your import module resolution. Torch uses pickle, which will maintain references to relative path imports for finding appropriate class definitions to deserialize objects from their stored bytes data. 
This isn't an MLflow issue, though. This is a core Python concept with respect to how namespaces are resolved. 

Can you update that old location with an import to the new file in your project? If not, you might want to work on some custom deserialization logic to handle the loading within your framework.

**Comment by zorro-gridi** [comment]
Thanks you, I just do what you recommended, that import the model class temporarily to an old file to load the model and saved a new one, it is solved.
