### ISSUE TITLE
[DOC-FIX] LLM page at docs site pointing to work link

### ISSUE THREAD

**Issue by elsatch** [mlflow/mlflow#10773]
### Willingness to contribute

Yes. I would be willing to contribute a document fix with guidance from the MLflow community.

### URL(s) with the issue

In the documentation for LLMs at: https://mlflow.org/docs/latest/llms/index.html

The link to the MLflow examples in the [Getting Started Examples for each Provider](https://mlflow.org/docs/latest/llms/index.html#id2) is broken. Currently this points to https://github.com/mlflow/mlflow/blob/master/examples/deployments/deployments_server/mlflow_serving/README.md

Github returns a 404 - page not found error

### Description of proposal (what needs changing)

It seems that the correct link is either:

https://github.com/mlflow/mlflow/tree/master/examples/deployments/deployments_server/mlflow_models
 or
https://github.com/mlflow/mlflow/blob/master/examples/deployments/deployments_server/mlflow_models/README.md

(Note the wrong link points to **mlflow_serving** while the working link points to **mlflow_models**)

**Comment by BenWilson2** [comment]
I'm not seeing the same behavior. Can you ensure that your browser cache is cleared with a force-reload of the site?

**Comment by elsatch** [comment]
Hi Ben,

I have just tried it again from my phone (which never visited the LLM
section of mlflow before). This is the URL I opened:
https://mlflow.org/docs/latest/llms/index.html

The link I am clicking is called: MLflow quickstart. It points to
https://github.com/mlflow/mlflow/blob/master/examples/deployments/deployments_server/mlflow_serving/README.md

The same 404 error happens. (In the top menu, I am in the latest (2.9.2
version)

I hope it helps!

**Comment by BenWilson2** [comment]
Gotcha! Yeah that link is completely broken :D I'll get a fix in for it. Thanks for reporting this!!
