### ISSUE TITLE
Feature Request: UI Limited Preview of Artifacts

### ISSUE THREAD

**Issue by kaleko** [mlflow/mlflow#1077]
When using the tracking UI to "preview" a *.csv file that is stored as an artifact, it seems to try to load the entire file to be viewed. If the file is hundreds of MB (e.g. generated features for training) then this process can take a long time. Perhaps "preview" should print on the head of the file? Or, perhaps there should be a maximum file size to preview?

**Comment by smurching** [comment]
Hi @kaleko, thanks for raising this - I haven't looked into technical feasibility much, but it does seem pretty reasonable to add a cap on the size of fetched artifacts (e.g. a UX that loads artifact data up to some size limit/timeout and then displays a "show more" link could be nice). Somewhat orthogonally, there is an outstanding PR adding support specifically for limited previews of CSVs: https://github.com/mlflow/mlflow/pull/436 but it's been inactive for some time. If you (or someone else) is interested in taking it over we could ping the author.
