### ISSUE TITLE
How to visualize the metrics over time?

### ISSUE THREAD

**Issue by FredYao** [mlflow/mlflow#1079]
I have an experiment which runs a training script every day, every time when the script is running, it will log some metrics (e.g., AUC, LogLoss, RMSE). 

When I launch the MLflow tracking UI, I can see the runs of the experiment. However, I can only view the metrics for a particular run for a certain day, which means I can only see one value of that metric for that day. 
![Screenshot from 2019-04-01 16-27-04](https://user-images.githubusercontent.com/4297204/55365869-0c079b80-549b-11e9-9fff-d42d3b9f2ef2.png)

I am wondering if there is a way to visualize the metrics over time, for example, AUC over days? With such feature, I can tell whether the model has steady performance or not.

**Comment by drewmcdonald** [comment]
@FredYao you should be able to make that comparison by checking the 'compare' box on the relevant runs within the experiment and then clicking the 'compare' button

**Comment by FredYao** [comment]
@drewmcdonald, thanks for your suggestion. It works for my case. However, there are still some concerns. For example, 
1) In order to show the metrics over time, I have to explicitly select the runs to compare. 
2) The compared graph uses runIds as X-axis, which is not flexible enough, since runIds are just some random strings, which fail to show the date-time of a run. 

I searched the issue history, and found the proposal #598 satisfies my needs. But need to wait for its implementation.

**Comment by drewmcdonald** [comment]
Ah I see. In the meantime you could workaround by logging a run_date parameter as something like “20190401” or the current day of the year at training, then you could use the built in parameter/metric line plot at the bottom of the comparison page for a more useful plot. Worth a shot!

**Comment by FredYao** [comment]
Yes, @drewmcdonald , thanks for your point! I am actually logging the training time as a parameter, and able to plot the curves over training time.

**Comment by Zangr** [comment]
We've [enhanced metrics plotting](https://github.com/mlflow/mlflow/pull/1225) in Mlflow 1.0. Could you please check that out?

**Comment by PavelKovalets** [comment]
Hi! I have mlflow, version 1.7.1 and still not able to find a way to plot metric over time without explicitly add time as a parameter (which looks like a hack because each run already has a related Start Time). Is there a way to do this?

**Comment by notha99y** [comment]
@PavelKovalets did you managed to find a way to fix this?

**Comment by marchinho11** [comment]
Up :) End time of run_id as X-axis is great feature, now i am logging date as param and compare metrics using it
