### ISSUE TITLE
[BUG] Unable to Execute Tests with Only Test Requirements Installed from test-requirements.txt.

### ISSUE THREAD

**Issue by manijhariya** [mlflow/mlflow#10815]
### Summary

The issue pertains to the inability to run tests when exclusively installing the required dependencies specified in the test-requirements.txt file. The provided fix addresses this issue, enabling the successful execution of tests under these circumstances.

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by manijhariya** [comment]
yeah I did installed pyspark manually. It was not listed in test-requirements.txt. I thought it was missing from there. It should at least be in extra requirements to let devs. know it is required package.

**Comment by kru2710shna** [comment]
Can I work on this ?

**Comment by filippopellizzari** [comment]
Does my fix solve this issue?
https://github.com/mlflow/mlflow/pull/10996

**Comment by kru2710shna** [comment]
Yes. can you type 
```pip install -r requirement.txt"```
and added optuna as well. #11090PR
