### ISSUE TITLE
[FR] Does MLFlow UI & Python SDK Utilise same REST API?

### ISSUE THREAD

**Issue by luke-gerschwitz** [mlflow/mlflow#10865]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Hi team, I'm just wondering if MLflow UI and its SDK's both utilise the MLflow REST API under the hood?
It is unclear from the documentation and there is prior Issues created that do not include a definitive answer (See: https://github.com/mlflow/mlflow/issues/5390)

### Motivation

> #### What is the use case for this feature? 

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Hi @luke-gerschwitz ,

Both MLflow UI and python SDK calls the same REST APIs:

Reference: available rest APIs: https://mlflow.org/docs/latest/rest-api.html

Example of how javascript side invoke rest API: [mlflow/server/js/src/experiment-tracking/sdk/MlflowService.ts](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/experiment-tracking/sdk/MlflowService.ts)
