### ISSUE TITLE
[SETUP-BUG] Unpin `pyarrow`

### ISSUE THREAD

**Issue by dannyfriar** [mlflow/mlflow#10884]
### System information

`mlflow` is not compatible with the latest arrow release which makes it much more difficult to use. Is it possible to unpin the `pyarrow` version here? https://github.com/mlflow/mlflow/blob/master/requirements/core-requirements.txt#L16

Is there a reason it needs to be pinned?

### Code to reproduce issue

```pip install mlflow pyarrow==15.0.0```

### Describe the problem

Cannot use `mlflow` with `pyarrow==15`

**Comment by WeichenXu123** [comment]
We just set pin upper-bound of major version for ensuring compatibility. Once we test the new arrow major version is compatible with MLflow, we will update it. You can file a PR to test it. :)

**Comment by dannyfriar** [comment]
Thanks @WeichenXu123 PR here https://github.com/mlflow/mlflow/pull/10904
