### ISSUE TITLE
Update experiment_id from int64 to string, and move default behavior into respective stores

### ISSUE THREAD

**Issue by eedeleon** [mlflow/mlflow#1090]
### Describe the problem
Currently experiment_id is an int, FileStore and SQLAlchemyStore handle the local case by incrementing an integer, however, this behavior does not translate well to servers that might benefit from using UUIDs or other unique identifiers.

The overall proposal includes an update from int64 -> string for experiment_id
However, updating the type is also not enough, this is best explained below:

### Quote from @acroz  that covers a lot of the benefits of removing default experiment_id and possible ways to implement this change
Retaining a default experiment ID of "0" seems like a lost opportunity in this case - it (for example) prevents a backend developer from using UUIDs as their ID schema.For the experiment ID schema to truly be flexible like the run ID schema, I think a fixed default value hard coded in MLflow would need to be removed. This could be solved either by something like https://github.com/mlflow/mlflow/pull/1032 or by making store implementation responsible for determining the ID of a default experiment with something like:

```class StoreWithIntIds(AbstractStore):

    def _create_experiment_with_id(self, name, experiment_id, artifact_location=None):

        pass

    def create_default_experiment(self):

        self._create_experiment_with_id('Default', 0)

    def create_experiment(self, name, artifact_location=None):

        self._create_experiment_with_id(name, self._next_available_id(), artifact_location)
```

UUIDs (for example) could then be supported with:

```from uuid import uuid4

class StoreWithUuids(AbstractStore):

    def _create_experiment_with_id(self, name, experiment_id, artifact_location=None):

        pass

    def create_default_experiment(self):

        self._create_experiment_with_id('Default', uuid4())

    def create_experiment(self, name, artifact_location=None):

        self._create_experiment_with_id(name, uuid4(), artifact_location)
```

### Proposal
- make experiment_id an optional string parameter of the REST API/protos
- return None instead of a value for experiment_id if no value is set
- stores implement the default behavior as desired for store.get_experiment(None)
#### Support varying id schemas
For this, changing the type to string allows for UUID based id schemas, as well as many other id schemas
#### to and from proto
- new client reading old proto
This will be added by editing the yaml of a new proto, int casting experiment_id, then loading the entity from the new modified proto/yaml
- new client reading new proto(existing tests cover this)
#### servers
- New client old server
(option 1) Test serialization and deserialization logic for old and new protos - less expansive but also lower maintenance costs
(option 2) add a flag for old and new server behavior parametrize tests for rest store to run against both
- new client new server(existing tests cover this)
- optional(nice to have), old client new server

**Comment by namikhai** [comment]
Keep in mind you need to change _get_experiment_id() in fluent.py to not cast the experiment id to int in all cases. try to cast it to int otherwise just return the experiment id. 
def _get_experiment_id():
    experiment_id = (_active_experiment_id or
               _get_experiment_id_from_env() or
               (is_in_databricks_notebook() and get_notebook_id()) or
               Experiment.DEFAULT_EXPERIMENT_ID)
    try:
        return int(experiment_id)
    except ValueError:
        return experiment_id
The current PR addressing this issue https://github.com/mlflow/mlflow/pull/1067/files doesn't include these changes

**Comment by aarondav** [comment]
We should clarify what the recommended proposal is. I believe it is currently that we will assume there may be no default experiment_id, and make it an optional parameter of the REST API. If absent, the remote tracking server will pick an appropriate default.

**Comment by dbczumar** [comment]
Experiment IDs are now, indeed, strings.
