### ISSUE TITLE
[BUG] Getting "RESOURCE_ALREADY_EXISTS" when creating new experiment due experiment_permissions

### ISSUE THREAD

**Issue by cjidboon94** [mlflow/mlflow#10913]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.9.2
- Tracking server: 2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04
- **Python version**: 3.9.16

### Describe the problem

When calling `create_experiment`, I get the following error about experiment permissions. I am running my mlflow in cloud run on gcp with basic auth using the following command:

`mlflow server  --backend-store-uri $BACKEND_STORE_URI -artifacts-destination $ARTIFACT_ROOT --host 0.0.0.0 --port 8080 --app-name basic-auth `. The experiment is still being created.

The basic-auth db is in the postgresql same instance as the backend store db, but in a different db so I think it should be accessible. To setup the basic-auth db I followed the steps described in https://github.com/mlflow/mlflow/issues/9155#issuecomment-1719446985 .
However, when I log into the postgresql, I actually don't see any changes, so not sure if auth is properly connected
For now, I have wrapped all my calls to `create_experiment` in a try-except block

### Tracking information

```shell
System information: Linux #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2
Python version: 3.9.16
MLflow version: 2.9.2
MLflow module location: /home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: [redacted]
Registry URI: [redacted]
MLflow environment variables: 
  MLFLOW_TRACKING_PASSWORD: [redacted]
  MLFLOW_TRACKING_USERNAME: admin
MLflow dependencies: 
  Flask: 2.2.2
  Jinja2: 3.1.2
  alembic: 1.9.2
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.30
  google-cloud-storage: 2.14.0
  gunicorn: 20.1.0
  importlib-metadata: 5.2.0
  markdown: 3.4.1
  matplotlib: 3.6.3
  numpy: 1.23.5
  packaging: 22.0
  pandas: 1.5.3
  protobuf: 4.21.12
  pyarrow: 10.0.1
  pytz: 2022.7.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.2.0
  scipy: 1.10.0
  sqlalchemy: 1.4.46
  sqlparse: 0.4.3
```

### Code to reproduce issue

```python
import mlflow
import os
def test_mlflow():
    os.environ["MLFLOW_TRACKING_USERNAME"] = "admin"
    os.environ["MLFLOW_TRACKING_PASSWORD"] = "[redacted]"
    mlflow.set_tracking_uri("[redacted]")
    exp = mlflow.get_experiment_by_name("test-artifacts-uploads2")
    if  exp == None:
        exp = mlflow.create_experiment("test-artifacts-uploads2")
    with mlflow.start_run(experiment_id=exp.experiment_id):
        mlflow.log_artifact(local_path="./grace_hopper_517x606.jpg") #from torchvision

test_mlflow()
```

### Stack trace

```python
Traceback (most recent call last):
  File "/home/cjidboon/test-mlflow-artifacts.py", line 15, in <module>
    test_mlflow()
  File "/home/cjidboon/test-mlflow-artifacts.py", line 9, in test_mlflow
    exp = mlflow.create_experiment("test-artifacts-uploads2")
  File "/home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 1560, in create_experiment
    return MlflowClient().create_experiment(name, artifact_location, tags)
  File "/home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/tracking/client.py", line 570, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location, tags)
  File "/home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 235, in create_experiment
    return self.store.create_experiment(
  File "/home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 98, in create_experiment
    response_proto = self._call_endpoint(CreateExperiment, req_body)
  File "/home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/cjidboon/anaconda3/envs/mlflow2/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 151, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_ALREADY_EXISTS: Experiment permission (experiment_id=3, username=admin) already exists. Error: (psycopg2.errors.NotNullViolation) null value in column "id" of relation "experiment_permissions" violates not-null constraint
DETAIL:  Failing row contains (null, 3, 1, MANAGE).

[SQL: INSERT INTO experiment_permissions (experiment_id, user_id, permission) VALUES (%(experiment_id)s, %(user_id)s, %(permission)s) RETURNING experiment_permissions.id]
[parameters: {'experiment_id': '3', 'user_id': 1, 'permission': 'MANAGE'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by gabrielfu** [comment]
@cjidboon94 I cannot reproduce the error. It seems like your PostgreSQL is complaining null `id` field when creating new permission.

What's the version of your PostgreSQL instance, and also `psycopg2` library?

Can you also try starting the PostgreSQL with `log_statement=all`, then start the MLflow server, and look for logs like this and share with us?
```
2024-01-31 09:44:44.415 UTC [69] LOG:  statement:
        CREATE TABLE experiment_permissions (
                id SERIAL NOT NULL,
                experiment_id VARCHAR(255) NOT NULL,
                user_id INTEGER NOT NULL,
                permission VARCHAR(255),
                PRIMARY KEY (id),
                CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users (id),
                CONSTRAINT unique_experiment_user UNIQUE (experiment_id, user_id)
        )
```

**Comment by cjidboon94** [comment]
@gabrielfu 

Postgresql db version: 15.4
psycopg2 version: psycopg2-binary==2.9.9

However, I have decided that I do not need the basic-auth setup nor any of the permissions (all users will have the same permissions) as provided by mlflow and it didn't feel too stable yet either (e.g. when I configure the auth db to use the postgresql db instead of the default sqlite, it fails, similar as to what is in issue #9155. Instead I had to create the authdb manually by running the statements that the sqlite produces. ) 
 
Instead, I opted for running mlflow without auth with a nginx frontend that handles the basic auth for me.
So for me it is not necessary to solve this issue anymore and can be closed.

**Comment by gabrielfu** [comment]
> @gabrielfu
> 
> Postgresql db version: 15.4 psycopg2 version: psycopg2-binary==2.9.9
> 
> However, I have decided that I do not need the basic-auth setup nor any of the permissions (all users will have the same permissions) as provided by mlflow and it didn't feel too stable yet either (e.g. when I configure the auth db to use the postgresql db instead of the default sqlite, it fails, similar as to what is in issue #9155. Instead I had to create the authdb manually by running the statements that the sqlite produces. )
> 
> Instead, I opted for running mlflow without auth with a nginx frontend that handles the basic auth for me. So for me it is not necessary to solve this issue anymore and can be closed.

@cjidboon94 thanks for letting us know. We are planning to upgrade the authentication and your issue might help us on improving it. 

My guess is the `id SERIAL NOT NULL` column did not get created properly. If you can share your postgresql log it'll be helpful.

**Comment by cjidboon94** [comment]
> > @gabrielfu
> > Postgresql db version: 15.4 psycopg2 version: psycopg2-binary==2.9.9
> > However, I have decided that I do not need the basic-auth setup nor any of the permissions (all users will have the same permissions) as provided by mlflow and it didn't feel too stable yet either (e.g. when I configure the auth db to use the postgresql db instead of the default sqlite, it fails, similar as to what is in issue #9155. Instead I had to create the authdb manually by running the statements that the sqlite produces. )
> > Instead, I opted for running mlflow without auth with a nginx frontend that handles the basic auth for me. So for me it is not necessary to solve this issue anymore and can be closed.
> 
> @cjidboon94 thanks for letting us know. We are planning to upgrade the authentication and your issue might help us on improving it.
> 
> My guess is the `id SERIAL NOT NULL` column did not get created properly. If you can share your postgresql log it'll be helpful.

This is all that I have with regards to the basicauth database. Can't find any other relevant logs (all other logs are either GCP cloudsql checks/heartbeats or related to other DBs, so I left those out). Not sure how much this helps, but good luck!
```
2024-01-26 10:42:22.542 UTC [34913]: [3-1] db=basicauth,user=postgres STATEMENT:  INSERT INTO experiment_permissions (experiment_id, user_id, permission) VALUES ('4', 1, 'MANAGE') RETURNING experiment_permissions.id
2024-01-26 10:42:22.542 UTC [34913]: [2-1] db=basicauth,user=postgres DETAIL:  Failing row contains (null, 4, 1, MANAGE).
2024-01-26 10:42:22.542 UTC [34913]: [1-1] db=basicauth,user=postgres ERROR:  null value in column ""id"" of relation ""experiment_permissions"" violates not-null constraint
2024-01-26 10:33:32.066 UTC [34916]: [3-1] db=basicauth,user=postgres STATEMENT:  INSERT INTO experiment_permissions (experiment_id, user_id, permission) VALUES ('3', 1, 'MANAGE') RETURNING experiment_permissions.id
2024-01-26 10:33:32.066 UTC [34916]: [2-1] db=basicauth,user=postgres DETAIL:  Failing row contains (null, 3, 1, MANAGE).
2024-01-26 10:33:32.066 UTC [34916]: [1-1] db=basicauth,user=postgres ERROR:  null value in column ""id"" of relation ""experiment_permissions"" violates not-null constraint
2024-01-26 09:46:46.982 UTC [18653]: [3-1] db=basicauth,user=postgres STATEMENT:  INSERT INTO experiment_permissions (experiment_id, user_id, permission) VALUES ('2', 1, 'MANAGE') RETURNING experiment_permissions.id
2024-01-26 09:46:46.982 UTC [18653]: [2-1] db=basicauth,user=postgres DETAIL:  Failing row contains (null, 2, 1, MANAGE).
2024-01-26 09:46:46.982 UTC [18653]: [1-1] db=basicauth,user=postgres ERROR:  null value in column ""id"" of relation ""experiment_permissions"" violates not-null constraint
2024-01-25 20:20:52.627 UTC [12823]: [3-1] db=basicauth,user=postgres STATEMENT:  INSERT INTO experiment_permissions (experiment_id, user_id, permission) VALUES ('1', 1, 'MANAGE') RETURNING experiment_permissions.id
2024-01-25 20:20:52.627 UTC [12823]: [2-1] db=basicauth,user=postgres DETAIL:  Failing row contains (null, 1, 1, MANAGE).
2024-01-25 20:20:52.627 UTC [12823]: [1-1] db=basicauth,user=postgres ERROR:  null value in column ""id"" of relation ""experiment_permissions"" violates not-null constraint
```
