### ISSUE TITLE
[BUG] Unable to load models or artifacts from remote Mlflow server, 

### ISSUE THREAD

**Issue by Ignatius224** [mlflow/mlflow#10919]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.10.0
- Tracking server: 2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Mac OS 13.12.6
- **Python version**: Python 3.9.18

### Describe the problem

I'm trying to complete a remote MLflow Server setup as defined here: mlflow.org/docs/latest/tracking/tutorials/remote-server.html

The remote Mlflow Server is running remotely on a Linode VM with a Debian 11 distribution. With a Postgresql database, and a Linode Object Storage S3 Bucket.

mlflow.sklearn.load_model fails to load model with the exception: API request to http://XXXX.com/api/2.0/mlflow-artifacts/artifacts failed with exception HTTPConnectionPool(host='XXXX.com', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts?path=0%2Fad28536b927645a7b830f0d339597ec1%2Fartifacts%2Ftest (Caused by ResponseError('too many 500 error responses'))

This problem persists when trying to load any model or artifact to the local machine. Despite the fact that I was able to load models and artifacts to the Mlflow Server, and Linode S3 Bucket.

### Tracking information

```shell
System information: Darwin Darwin Kernel Version 22.6.0: Tue Nov  7 21:42:31 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T8112
Python version: 3.9.18
MLflow version: 2.10.0
MLflow module location: /Users/imudoh/miniconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: "http://172-234-208-8.ip.linodeusercontent.com"
MLflow environment variables: 
  MLFLOW_TRACKING_PASSWORD: XXXX
  MLFLOW_TRACKING_USERNAME: XXXX
MLflow dependencies: 
  Flask: 3.0.1
  Jinja2: 3.1.3
  alembic: 1.13.1
  boto3: 1.34.28
  botocore: 1.34.28
  click: 8.1.7
  cloudpickle: 3.0.0
  databricks-cli: 0.18.0
  docker: 7.0.0
  entrypoints: 0.4
  gitpython: 3.1.41
  gunicorn: 21.2.0
  importlib-metadata: 7.0.1
  markdown: 3.5.2
  matplotlib: 3.8.2
  numpy: 1.26.3
  packaging: 23.2
  pandas: 2.2.0
  protobuf: 4.25.2
  pyarrow: 15.0.0
  pytz: 2023.3.post1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.4.0
  scipy: 1.12.0
  sqlalchemy: 2.0.25
  sqlparse: 0.4.4
```

### Code to reproduce issue

```
import mlflow
from mlflow.models import infer_signature
from mlflow import MlflowClient
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor

tracking_uri = "http://172-234-208-8.ip.linodeusercontent.com"
mlflow.set_tracking_uri(tracking_uri)
client = MlflowClient(tracking_uri)


with mlflow.start_run() as run:
    # Load the diabetes dataset.
    db = load_diabetes()
    X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

    # Create and train models.
    rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)
    rf.fit(X_train, y_train)


    # Use the model to make predictions on the test dataset.
    predictions = rf.predict(X_test)
    #print(predictions)

    signature = infer_signature(X_test, predictions)
    # mlflow.register_model(f"runs:/{run.info.run_id}/model", "demo-model")
    mlflow.sklearn.log_model(rf, signature=signature, artifact_path="test", registered_model_name="new-model")

model_name = "demo_test"
model_version = 1

remote_uri = f"models:/{model_name}/{model_version}"
model = mlflow.sklearn.load_model(model_uri=remote_uri)

```

### Stack trace

```
Traceback (most recent call last):
  File "/Users/imudoh/VSProjects/demo/load.py", line 14, in <module>
    local_path = ModelsArtifactRepository(f"models:/{model_name}/{model_version}").download_artifacts("", dst_path="/Users/imudoh/VSProjects/demo")
  File "/Users/imudoh/miniconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 178, in download_artifacts
    model_path = self.repo.download_artifacts(artifact_path, dst_path)
  File "/Users/imudoh/miniconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repo.py", line 190, in download_artifacts
    if self._is_directory(artifact_path):
  File "/Users/imudoh/miniconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repo.py", line 93, in _is_directory
    listing = self.list_artifacts(artifact_path)
  File "/Users/imudoh/miniconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 88, in list_artifacts
    resp = http_request(host_creds, endpoint, "GET", params=params)
  File "/Users/imudoh/miniconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 130, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://172-234-208-8.ip.linodeusercontent.com/api/2.0/mlflow-artifacts/artifacts failed with exception HTTPConnectionPool(host='172-234-208-8.ip.linodeusercontent.com', port=80): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts?path=0%2Fad28536b927645a7b830f0d339597ec1%2Fartifacts%2Ftest (Caused by ResponseError('too many 500 error responses'))
```

### Other info / logs

```
// Code to run systemctl service for mlflow at remote Linode VM 

[Unit]
Description=MLFlow Server

[Service]
Type=simple

ExecStart=/bin/bash -c 'PATH=/usr/bin/python3/:$PATH exec mlflow server --backend-store-uri postgresql://<postgres-username>:<postgres-pass>@<postgres-ip>:5432/<dedicated-dbname> --artifacts-destination s3://<linode-bucket-fq-name> --host 0.0.0.0 --port 80'

User=<user>
Group=<group>
WorkingDirectory=/home/<username> #ensure user and group mentioned has all the rights on this working dir
Restart=always
RestartSec=10
#KillMode=mixed

[Install]
WantedBy=multi-user.target
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@B-Step62 Hey Yuki, do you have any insights on what might be wrong here? Could it be permission issue 🤔

**Comment by serena-ruan** [comment]
@Ignatius224 Is there any more useful logs from the server side? It's more like something might be wrong with your setup... It's hard for us to tell what's going wrong :(

**Comment by Ignatius224** [comment]
I was able to solve this issue, it turns out the endpoint we provided for the Linode Object Storage was incorrect. 

In the systemd ".service" file provided above:
1. The 'artifacts_destination' flag was changed to s3://<bucket-name>
2. The '--serve artifacts' flag was added

Added environment variables: 
MLFLOW_S3_ENDPOINT_URL=https://<aws-region-here>.linodeobjects.com/<bucket-name>
AWS_ACCESS_KEY_ID=<redacted>
AWS_SECRET_ACCESS_KEY=<redacted>

These changes fixed the issue completely. Thank you!
