### ISSUE TITLE
[BUG] anthropic-version header is missing in AnthropicProvider

### ISSUE THREAD

**Issue by xwangotter** [mlflow/mlflow#10917]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.10.0
- Tracking server: 2.10.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.6 LTS
- **Python version**: Python 3.8.10
- **yarn version, if running the dev UI**:

### Describe the problem

It seems anthropic-version header is missing in AnthropicProvider [here](https://github.com/mlflow/mlflow/blob/5d13d6ec620a02de9a5e31201bf1becdb9722ea5/mlflow/gateway/providers/anthropic.py#L107), which caused this error:

![Screenshot 2024-01-26 at 1 43 33 PM](https://github.com/mlflow/mlflow/assets/157841226/eb357e4e-28c6-441e-9be0-e4390fa6bdf9)

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @xwangotter Thanks for raising the issue, please feel free to file a PR to fix it! BTW is this a newly introduced header for newer anthropic version?

**Comment by serena-ruan** [comment]
https://docs.anthropic.com/claude/reference/complete_post shows `--header "anthropic-version: 2023-06-01"` @hubertzub-db @dbczumar We might need to fix this on databricks side as well

**Comment by ngo-minh-thang-nguyen** [comment]
I can contribute to fix this bug if anyone can show me how to recompile source of mlflow that has been modified. Currently, mlflow source appears inside of site-packages in my project. 

I have already modified some py files to test and then make a 'python -m compileall' from the parent directory but nothing changes.

**Comment by serena-ruan** [comment]
@ngo-minh-thang-nguyen You could follow https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md to get started, you need to clone the github repo and raise a PR

**Comment by xhw1** [comment]
@serena-ruan @ngo-minh-thang-nguyen Hi, I have the fix ready and was able to compile it. I can create a PR today.

**Comment by ngo-minh-thang-nguyen** [comment]
Hello @xhw1, have you created the PR to fix this problem?

Thank you for your reply

**Comment by xhw1** [comment]
Hi @serena-ruan , can you please review the PR? Thank you!

**Comment by thnguyendn** [comment]
Hi @serena-ruan , I follow the contributing guide. And I am stucked by executing the following cli : `pre-commit run --all-files` (failed at `black` and `rstcheck`, cf image attached) before submitting my pull request. I do not know if we need to pass everything with success 
![image](https://github.com/mlflow/mlflow/assets/12558275/8126d4fe-490e-4f1c-adea-61deedca123f)
