### ISSUE TITLE
[BUG] Header 'anthropic-version' problem while querying Anthropic provider

### ISSUE THREAD

**Issue by ngo-minh-thang-nguyen** [mlflow/mlflow#10938]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: 3.10.11
- **yarn version, if running the dev UI**:

### Describe the problem

Hello,

I just have a problem while querying the provider Anthropic in Mlflow LLM Deployment.

Everything is configured in the yml file containing endpoints (cf. screenshot below)

![image](https://github.com/mlflow/mlflow/assets/12558275/f5d7d0dd-8580-4be9-a30e-f5304b5b0cd8)

However, when I query the Anthropic model, I get the error that requires header in the API call (as seen in the screenshot below).

Bad Request for url: http://service-llm-deployment:5000/endpoints/anthropic-here/invocations. Response text: {"detail":"anthropic-version: header is required"}

![image](https://github.com/mlflow/mlflow/assets/12558275/31244886-4a8d-46f9-8380-1f9c26e5cba9)

Could you please tell me if it is really a bug or is there something that is missing in my configuration?

Thank you very much in advance

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Duplicate to #10917
