### ISSUE TITLE
[BUG] Alias for model version doesn't show up in the table

### ISSUE THREAD

**Issue by elvira-salakhova-r** [mlflow/mlflow#10961]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 10 (buster)
- **Python version**: 3.9.18

### Describe the problem

Inside the Models section when a certain model is selected there is a pivot table with model versions, their tags and aliases. After assigning an alias via button "Add" from UI or from code using client.set_registered_model_alias method, the alias doesn't show up in the pivot table. 

When I click the button "Add" for the model version I've just assigned the alias, the alias becomes visible in search panel as if it was actually assigned. The method client.get_model_version_by_alias also return the correct alias.

So, the problem is that column "Aliases" won't display any aliases even if they are set.

The expected behavior is the following: after setting an alias it should be displayed in the pivot table similarly to the "Tags" column.

### Steps to reproduce the bug

https://github.com/mlflow/mlflow/assets/147606144/c48be945-1dd3-4dd7-b046-99e0211d431a

**Comment by BenWilson2** [comment]
Thanks, this is definitely a UI bug. We'll look into fixing it. 
cc @hubertzub-db

**Comment by hubertzub-db** [comment]
@elvira-salakhova-r I couldn't reproduce the bug on `v2.9.2` nor on the latest version (videos attached). Can you confirm the bug still persists on the latest version from `master` branch, i.e. `v2.10.1`? If true: is it possible for you to record the screen while having browser developer tools -> "Network" tab open?

https://github.com/mlflow/mlflow/assets/104438646/f3dcd305-3396-45b2-b9d1-bff3c2c5e389

https://github.com/mlflow/mlflow/assets/104438646/d8f94ee8-03b4-4452-8907-c1fca14bd470

**Comment by ippen** [comment]
I can confirm that I also run into the same issue when using a PostgreSQL storage backend. With it the alias tag is not shown like @elvira-salakhova-r mentioned [here](https://github.com/mlflow/mlflow/issues/10961#issue-2109779397).

**Comment by hubertzub-db** [comment]
@ippen thanks a lot!
@jerrylian-db @smurching can you take a look at this one? It seems that aliases API is breaking  when database backend is 
 being used

**Comment by smurching** [comment]
Thanks for flagging, I'll take a look at this & options for a fix
