### ISSUE TITLE
[BUG] when creating an experiment using artifact_location the files are created without experiment/run directories

### ISSUE THREAD

**Issue by carmithersh** [mlflow/mlflow#10966]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.10.0
- Tracking server: 2.10.0

### System information

- macOS Sonoma Version 14.3 (23D56) 
- python 3.11

mlflow.doctor():
-------------------
System information: Darwin Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
Python version: 3.11.7
MLflow version: 2.10.0
MLflow module location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlflow/__init__.py
Tracking URI: http://127.0.0.1:8080/
Registry URI: http://127.0.0.1:8080/
MLflow dependencies: 
  Flask: 3.0.1
  Jinja2: 3.1.3
  aiohttp: 3.9.1
  alembic: 1.13.1
  boto3: 1.33.3
  botocore: 1.33.3
  click: 8.1.7
  cloudpickle: 3.0.0
  databricks-cli: 0.18.0
  docker: 7.0.0
  entrypoints: 0.4
  fastapi: 0.95.2
  gitpython: 3.1.41
  gunicorn: 21.2.0
  importlib-metadata: 7.0.1
  markdown: 3.5.2
  matplotlib: 3.8.2
  numpy: 1.26.3
  packaging: 23.2
  pandas: 2.2.0
  prometheus-flask-exporter: 0.23.0
  protobuf: 4.25.2
  pyarrow: 15.0.0
  pydantic: 1.10.14
  pytz: 2023.4
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: null
  scipy: 1.12.0
  sqlalchemy: 2.0.25
  sqlparse: 0.4.4
  uvicorn: 0.22.0

### Describe the problem

I am developing an mlflow plugin for artifacts-destination, and have added logs to make sure the code is behaving as expected.
I have an issue with this scenario: 
I am creating an experiment with a new artifact_location and set_experiment to the new experiment
then I create and log a model:

with mlflow.start_run():
    mlflow.log_metric("foo", 1)
    model_name = "local_model"
    mlflow.transformers.log_model(transformers_model=classifier, artifact_path=model_name)
    mlflow.set_tags({"team": "ml-infra", "budget": "ml infra group"})

this is behaving a bit differently than when running on the default artifact_location
1. instead of the code running on the mlflow server, I see its running on the client side.
2. instead of calling my plugin log_artifact method the method being called in this scenario is log_artifacts
3. in log_artifacts(self, local_dir, artifact_path=None) instead of getting artifact_path=experiment-id/run-id/artifacts/local_model , I get artifact_path=local_model this is causing the plugin to save the model directly under the root location of my repo

the different behavior is causing the local created experiment look different, but a critical issue is that when later on I create that experiment and run a GC, my plugin shows that on delete_artifacts(self, artifact_path=None), artifact_path parameter arrived as none. plus I have no idea what the artifact_location is for that experiment.
so basically, I cannot delete anything because if I do I will be ending up recursively deleting the entire repo from its root. 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

%pip install --upgrade pip
%pip install mlflow~=2.9.2 
%pip install transformers==4.36.2
%pip install tensorflow==2.15.0
%pip install torchvision==0.15.2  
%pip install -U scikit-learn==1.4.0     

%pip install --ignore-installed my-mlflow-plugin (this is the plugin I am developing)

import mlflow
from transformers import pipeline
mlflow.set_tracking_uri(
    "http://127.0.0.1:8080"
)
exp_name="local-check"
mlflow.create_experiment(
   exp_name, artifact_location="my_repo://localhost:8082/my_repo"
)
mlflow.set_experiment(exp_name)
classifier = pipeline("sentiment-analysis", model="michellejieli/emotion_text_classifier")

with mlflow.start_run():
    mlflow.log_metric("foo", 1)
    mlflow.log_metric("bar", 2)
    model_name = "local_model"
    mlflow.transformers.log_model(transformers_model=classifier, artifact_path=model_name)
    mlflow.set_tags({"team": "ml-infra", "budget": "ml infra group"}) 
mlflow.end_run()

### Stack trace

when creating an experiment with a different artifact_location:

1. adding this log line to 
def log_artifacts(self, local_dir, artifact_path=None):
   print(f"log_artifacts Started parameters local_dir={local_dir}, artifact_path={artifact_path}")

printed:
log_artifacts Started parameters local_dir=/var/folders/yb/lg7ybrkx29b1nph626hjmjl00000gp/T/tmpqclui6th/model, artifact_path=local_model

* notice artifact_path does not contain experiment id and run id, as it is on  log_artifact calls

2. adding this log line to my plugin delete_artifacts:
def delete_artifacts(self, artifact_path=None): 
    print(f"delete_artifacts in artifact_path={artifact_path}

printed (mlflow gc shell):
delete_artifacts in artifact_path=None

* notice that if at this point I perform the delete, it would be on my default artifacts-destination on root recursively, which might just delete ALL my artifacts on all experiments

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Artifact path is the relative path within the model_uri absolute path. Have you tried using the [get_artifact_uri](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.get_artifact_uri) API ? 
Alternatively, if you're making your own plugin, you should probably be using the lower-level developer APIs that are exposed as utilities and as integration points within the artifact store APIs. Try looking at utilities like this: https://github.com/mlflow/mlflow/blob/785d181012e0ad3f72663555aac1cf39d9ce098e/mlflow/tracking/artifact_utils.py#L21-L56

**Comment by carmithersh** [comment]
@BenWilson2, thank you for your reply. I am indeed writing a plugin. 
my main issue is that I do not really get any information in my plugin code from mlflow, specifically inside:
def log_artifacts(self, local_dir, artifact_path=None)

specifically, I am missing the experiment id or run id.
and in the scenario I described, the artifact_path is also very partial and does not include experiment/run

is there a way for me to get these from mlflow at that point?

**Comment by carmithersh** [comment]
Found that the specific run if is being sent to the plugin through the plugin init instead of through the log_artifacts method, so, that should prevent the delete all bug.
It would be great if the init might get the entire {new-location}/{experiment-id}/{run-id}/artifacts instead of just the {run-id}/artifacts, but it does not have the bug I thought it had so I am closing this
