### ISSUE TITLE
[BUG] start_time of runs created and logged to from airflow pipeline are not set correctly

### ISSUE THREAD

**Issue by JohannesZellingerSCCH** [mlflow/mlflow#10978]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.10.0
- Tracking server: 2.9.0

### System information

- **Debian12**:
- **3.11.6**:
- **Ubuntu 20.04**
The code is run in different containers based on `python:3.11.6` and `nvidia/cuda:11.3.1-devel-ubuntu20.04` image 

### Describe the problem

We run and track experiments using an [Airflow ](https://airflow.apache.org/)pipeline with `KubernetesPodOperators` on our cluster. Each pipeline run is tracked as parent run in MLflow and consists of several sub-runs (same experiment, different hyperparameters) which are tracked as childruns in MLflow. The problem is that the start time of the parent runs is not logged correctly:
![image](https://github.com/mlflow/mlflow/assets/107187601/53482c05-22fb-4ad0-b9ee-61105ba36d98)
The parent runs will always show `Date:(unknown)`. This makes searching and ordering more difficult. 

### Tracking information

Actually no unexpected log output in our case. 
We will add `mlflow.doctor()` to the images where possible and rebuild/re-run them and updated the question as soon as that is available.

### Code to reproduce issue

What seems to be the cause of the problem is the setup with multiple kubernets pods / containers for the same run, because we have already tried the following (which works normally without issues)
- Tracking nested runs from local PC
- Starting, stopping and later resuming runs from local PC 
- Checking timestamps in the pods created by Airflow (we suspected problems with time servers)

As mentioned, runs are logged over several containers. 

Example code of the function (this is done by the Airflow-DAG using the REST API since here we don't have access to the mlflow python sdk) which initializes the parent run:
```
    def pipeline_preparation():
        @task
        def get_mlflow_runid() -> str:
            experiment_response = requests.get(
                f"{mlflow_url}/api/2.0/mlflow/experiments/get-by-name?experiment_name=MyExperiment"
            )
            experiment = experiment_response.json()
            experiment_id = experiment.get("experiment").get("experiment_id")

            run_response = requests.post(
                f"{mlflow_url}/api/2.0/mlflow/runs/create",
                json={"experiment_id": experiment_id},
            )

            run = run_response.json()
            print(run)

            return run.get("run").get("info").get("run_id")
```

Example code of container which initializes sub runs:
```
        mlflow.set_tracking_uri(os.getenv("MLFLOW_URL", ""))
        mlflow.set_experiment("MyExperiment")
        with mlflow.start_run(run_id=pipeline_run_id) as pipeline_run:
            num_classes = int(pipeline_run.data.params.get("num_classes", 0))
            pipeline_input.training_input.datamodule["num_classes"] = num_classes

            class_names = json.loads(pipeline_run.data.params.get("class_names", [""]))
            pipeline_input.training_input.datamodule["class_names"] = class_names

            points_per_class = json.loads(pipeline_run.data.params.get("points_per_class", {}))
            pipeline_input.training_input["points_per_class"] = points_per_class

            with mlflow.start_run(nested=True) as run:
                pipeline_run_id_path = os.path.join(temp_data_folder, pipeline_run_id)
                run_id_path = os.path.join(pipeline_run_id_path, 'results', run.info.run_id)

                pipeline_input.training_input.pipeline_run_id = pipeline_run_id
                pipeline_input.training_input.run_id = run.info.run_id
                pipeline_input.training_input.output_dir = run_id_path

                Path(run_id_path).mkdir(parents=True)
                with open((os.path.join(run_id_path, 'input.yaml')), "w") as yaml_file:
                    yaml.dump(pipeline_input.model_dump(), yaml_file)
```

And finally example code of a training container with actual tracking:

```
    mlflow.set_tracking_uri(os.getenv("MLFLOW_URL"))
    mlflow.set_experiment("PointNext")
    mlflow.enable_system_metrics_logging()
    with mlflow.start_run(run_id=cfg.run_id) as run:
        # lots of other stuff
         mlflow.log_artifacts(f"{os.environ.get('TEMP_FOLDER')}/{cfg.pipeline_run_id}/results/{cfg.run_id}", "results")
```

Additionally we also have some trainings with [lighting](https://lightning.ai/) which have a MLFlow Logger built in.

### Stack trace

No exception, code runs normally.

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
The following example might shed some light on how to resolve the issue that you're experiencing: 

https://github.com/mlflow/mlflow/blob/785d181012e0ad3f72663555aac1cf39d9ce098e/examples/rest_api/mlflow_tracking_rest_api.py 

Of particular note, notice the submission of the `start_time` parameter within the call to `create_run` in line 35.
