### ISSUE TITLE
MLFlow UI

### ISSUE THREAD

**Issue by kurian-dm** [mlflow/mlflow#10995]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.9.2
- Tracking server: 2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Python version**: 3.9.16
- **yarn version, if running the dev UI**:

### Describe the problem

I had the following queries.
 Is it possible to modify the UI so that
1) We can remove references to Github and Docs, we are running the tracking server as a Docker container
2) When we bring up the tracking server is it possible not to create the default experiment or when the tracking server is launched not to display the default experiment.

### Tracking information

```
None
```

### Code to reproduce issue

```
NONE
```

### Stack trace

```
NONE
```

### Other info / logs

```
NONE
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
1. We'd prefer not to remove them. As for whitelisting the MLflow UI, there are plenty of organizations that do this (some even create an entirely custom skin for the UI!) by forking the repository and maintaining their own version of the UI. While this may become quite a burden to maintain, particularly as we focus on large refactoring of the UI in the next year, it is an option to fully customize what you choose to see. 
2. Without a default experiment, failing to set an experiment when logging a run will result in a failure to create a run or log artifacts associated with said run. The Default experiment is quite important to prevent a very frustrating user experience. As for hiding the display of the Default experiment, this might not be something that you want. If a user forgets to set a named experiment at any time, the runs that are logged will go to the default experiment. Failing to display this within the UI might create a somewhat broken experience. 

We won't be entertaining modifications to the MLflow source code for these requests, but you are always more than welcome to fork the repo and make the UI as customized as you'd like!

**Comment by kurian-dm** [comment]
@BenWilson2 
1) In order to fork the repository and build the tracking server image in our organization , do we have any instructions or pipelines that we can look at.

2) We are ensuring that an experiment is always created when the tracking server is launched and all runs will get diverted to that experiment

**Comment by BenWilson2** [comment]
We don't have any examples of how to wrap MLflow APIs in this way, but there are plenty of examples within MLflow's source code of patching functionality in other libraries to modify behavior of an installed library when used. You could monkeypatch the MLflow server startup logic to create the initial experiment, but as far as removing the Default Experiment, that might be a bit complex as the tracking store backends require its existence in order to perform validation checks when certain API calls are made. 
Best of luck with whichever path you choose (private fork or patching). I'm sorry that I can't provide much more guidance here as there are far too many nuanced design considerations that would need to be thought through to provide any salient and concrete advice.

**Comment by kurian-dm** [comment]
Thanks for your response @BenWilson2 any guidance on how to build the tracking server docker image
