### ISSUE TITLE
[FR] Expose System Metrics 

### ISSUE THREAD

**Issue by Data-drone** [mlflow/mlflow#10994]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

When training in a distributed setup, it can be good to understand the resource consumption across various nodes. This helps us to diagnose whether the cluster configuration is fit for purpose or not.

In order to do this, it is necessary to start a mlflow run per node with system metrics enabled. As the 'system' prefix is not exposed, it is not possible to log for example each `cpu_utilization_percentage` to a different prefix ie `system_node_!`.

Allowing for this prefix to be changed via the `start_run` method would allow for this to happen and make logging system metrics across multiple nodes more seamless. In the current state, it is necessary to log different nodes to different child runs which adds to clutter in the experiments screen.

The system metrics monitor currently already has an internal method for changing the metrics_prefix that could be make public
https://github.com/mlflow/mlflow/blob/8968aa713de6070066f083567b2ba034f699b4b1/mlflow/system_metrics/system_metrics_monitor.py#L73C9-L73C41

This isn't exposed to users and would need to be added to this call here: https://github.com/mlflow/mlflow/blob/8968aa713de6070066f083567b2ba034f699b4b1/mlflow/tracking/fluent.py#L399

### Motivation

> #### What is the use case for this feature?

Tracking distributed LLM training and in particular GPU Consumption

> #### Why is this use case valuable to support for MLflow users in general?

Understanding resource consumption is key for efficient use of resources

> #### Why is this use case valuable to support for your project(s) or organization?

Finetuning LLMs is becoming increasingly common but distributed configurations are key to make this fast.

> #### Why is it currently difficult to achieve this use case?

Currently, the tools are there to make this easy but the necessary parameters are not exposed to end users.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by chenmoneygithub** [comment]
we don't expose self._metrics_prefix = "system/"  because our server uses this prefix to group metrics. The feature is released in Databricks staging server, and will come to OSS in the near future (probably a few weeks). That is to say, we don't want users to have the freedom to change this prefix.

re distributed training support, right now the code supports multi-gpu on a single node (we use pynvml to fetch GPU stats), but not multi-node setup because different platforms have different ways to communicate between master node (rank 0) and worker node, so we cannot make a standardized API. Users can write custom code and log to the same MLflow run as a workaround.

To address your request, I think we should provide a new argument `node_id`, which can be appended to `_metrics_prefix` to indicate which rank the system metrics come from without breaking the metrics grouping UI.
