### ISSUE TITLE
Feature request : scala or R tracking api

### ISSUE THREAD

**Issue by xmehaut** [mlflow/mlflow#110]
### Describe the problem
Is it planned to add Tracking API for other languages like R or Scala? 
Will the MLFlow project be able to handle project in other languages too?

regards

**Comment by mateiz** [comment]
Yes, we'd like to support both of the. Do you have a specific preference / priority for these? What libraries do you want to use MLflow with in these languages?

**Comment by xmehaut** [comment]
hi
for scala/java, h2o, sparkml, keras/tensorflow
for R, the main libraries like xgboost, and so on (the  cran)
it gives the idea that you could also display some results in the ui with a language agnostic graphical api derived from gnuplot for instance

Envoyé de mon iPhone

**Comment by notiv** [comment]
For R, I would probably go one level higher and “integrate” mlflow with mlr, caret, h2o, i.e. libraries that provide/ facilitate hyperparameter tuning. Just my 2 cents :-)

**Comment by smurching** [comment]
There is now a public Java & R API, so closing this issue :)
