### ISSUE TITLE
Inquiry: Is it possible to connect to remote Spark Cluster

### ISSUE THREAD

**Issue by oelesinsc24** [mlflow/mlflow#1100]
Is it possible to connect to a remote spark cluster, running on AWS EMR from Mlflow spark object:
```python
from mlflow import spark

spark.conf.set("spark.master", "some-remote-spark-yarn-cluster")
```

**Comment by aarondav** [comment]
`mlflow`'s spark support allows registering trained models as UDFs inside an existing SparkConteext -- so you can use the standard spark library to connect to a remote cluster, then user mlflow to run batch inference on it.
