### ISSUE TITLE
[BUG] cli.py AttributeError upon running mlflow ui 

### ISSUE THREAD

**Issue by turkunov** [mlflow/mlflow#11016]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow==2.10.0
- Client: 2.10.0
- Tracking server: 2.10.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.12.0

### Describe the problem
Following a quicksart guide in official docs (https://mlflow.org/docs/latest/tracking/autolog.html), every time I try running `mlflow ui --port 8080` inside parent directory with particular conda env activated same error keeps popping up.

I have tried multiple versions, reinstalling `importlib-metadata` (following the same issue https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean) and installing older versions prior to `mlflow=2.10.0`.

### Tracking information

```shell
mlflow ui --port 8080
```

### Code to reproduce issue

**Project structure:**

[![enter image description here][1]][1]

**regModel.py**:
```py
import warnings
import argparse
import logging
import pandas as pd
import numpy as np
import mlflow
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet

logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(__name__)

#evaluation function
def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return rmse, mae, r2


def run_experiment(alpha, l1_ratio):
    warnings.filterwarnings("ignore")

    # Read the wine-quality csv file from local
    data = pd.read_csv("data/red-wine-quality.csv")
    data.to_csv("data/red-wine-quality.csv", index=False)

    # Split the data into training and test sets. (0.75, 0.25) split.
    train, test = train_test_split(data)

    # The predicted column is "quality" which is a scalar from [3, 9]
    train_x = train.drop(["quality"], axis=1)
    test_x = test.drop(["quality"], axis=1)
    train_y = train[["quality"]]
    test_y = test[["quality"]]

    lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
    lr.fit(train_x, train_y)

    predicted_qualities = lr.predict(test_x)

    (rmse, mae, r2) = eval_metrics(test_y, predicted_qualities)

    print("Elasticnet model (alpha={:f}, l1_ratio={:f}):".format(alpha, l1_ratio))
    print("  RMSE: %s" % rmse)
    print("  MAE: %s" % mae)
    print("  R2: %s" % r2)
    mlflow.log_param("alpha", alpha)
    mlflow.log_param("l1", l1_ratio)
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("r2", r2)
    mlflow.log_metric("mae", mae)
    mlflow.sklearn.log_model(lr, "models")
```

**inroduction.ipynb**:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/TRylW.png
  [2]: https://i.stack.imgur.com/RySV8.png

### Stack trace

```
C:\Users\user\miniconda3\envs\regular\Lib\site-packages\pydantic\_internal\_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\miniconda3\envs\regular\Scripts\mlflow.exe\__main__.py", line 4, in <module>  
  File "C:\Users\user\miniconda3\envs\regular\Lib\site-packages\mlflow\cli.py", line 356, in <module>
    type=click.Choice([e.name for e in importlib.metadata.entry_points().get("mlflow.app", [])]),   
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
can you run the doctor command (or, alternatively, just run `pip freeze`) and report the results here? I think your version of pydantic is incompatible.

**Comment by turkunov** [comment]
> can you run the doctor command (or, alternatively, just run `pip freeze`) and report the results here? I think your version of pydantic is incompatible.

I have latest pydantic version installed, but perhaps a downgrade is needed?

```
aiofiles==23.2.1
alembic==1.13.1
altair==5.2.0
aniso8601==9.0.1
annotated-types==0.6.0
anyio==3.7.1
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
attrs==23.1.0
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1687772187254/work
blinker==1.7.0
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1691044910542/work
contourpy==1.2.0
cycler==0.12.1
databricks-cli==0.18.0
debugpy @ file:///D:/bld/debugpy_1695534453785/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
docker==7.0.0
entrypoints==0.4
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1692026125334/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
fastapi==0.105.0
fastjsonschema==2.19.0
ffmpy==0.3.1
filelock==3.13.1
Flask==3.0.2
fonttools==4.45.0
fsspec==2023.12.2
gitdb==4.0.11
GitPython==3.1.41
gradio_client==0.7.3
graphene==3.3
graphql-core==3.2.3
graphql-relay==3.2.0
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.2
httpx==0.25.2
huggingface-hub==0.19.4
idna==3.6
importlib-metadata==4.13.0
importlib-resources==6.1.1
ipykernel @ file:///D:/bld/ipykernel_1698244157926/work
ipython @ file:///D:/bld/ipython_1698846796959/work
itsdangerous==2.1.2
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1699283905679/work
jupyter_core @ file:///D:/bld/jupyter_core_1698673832306/work
kiwisolver==1.4.5
Mako==1.3.2
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mdurl==0.1.2
mlflow==2.10.0
nbformat==5.9.2
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1697083700168/work
numpy==1.26.2
oauthlib==3.2.2
orjson==3.9.10
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1696202382185/work
pandas==2.1.3
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==10.1.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1699715570510/work
plotly==5.18.0
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1699963054032/work
protobuf==4.25.2
psutil @ file:///D:/bld/psutil_1695367295750/work
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pyarrow==14.0.0
pydantic==2.6.1
pydantic_core==2.16.2
pydub==0.25.1
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1700395971011/work
PyJWT==2.8.0
pyparsing==3.1.1
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-multipart==0.0.6
pytz==2023.3.post1
pywin32==306
PyYAML==6.0.1
pyzmq @ file:///D:/bld/pyzmq_1698062575483/work
querystring-parser==1.2.4
referencing==0.31.0
requests==2.31.0
rich==13.7.0
rpds-py==0.13.1
scikit-learn==1.3.2
scipy==1.11.4
semantic-version==2.10.0
setuptools==68.0.0
shellingham==1.5.4
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap==5.0.1
sniffio==1.3.0
SQLAlchemy==2.0.25
sqlparse==0.4.4
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
starlette==0.27.0
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomlkit==0.12.0
toolz==0.12.0
tornado @ file:///D:/bld/tornado_1695373547508/work
tqdm==4.66.1
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1698671135544/work
typer==0.9.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1695040754690/work
tzdata==2023.3
urllib3==2.1.0
uvicorn==0.24.0.post1
waitress==2.1.2
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1699959196938/work
websockets==11.0.3
Werkzeug==3.0.1
wheel==0.41.2
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work

```

**Comment by turkunov** [comment]
Unfortunately still no solution found yet

**Comment by Gabomfim** [comment]
Guys, I did it! Leave this up to me! 💪😤
The fiz works on my machine, I will be making a PR today.

The error is in `cli.py`, just substitute `get("mlflow.app", [])` by `.select(group="mlflow.app")`

The interface changed and an update was needed.

if this still doesn’t work, just assign `type=None'

**Comment by turkunov** [comment]
@Gabomfim tysm!

**Comment by Gabomfim** [comment]
Actually, as referenced in #11109 by @harupy:
> Sorry for the confusion. https://github.com/mlflow/mlflow/pull/10752 fixed this issue. This patch will be release in the next version.

I’ve checked the code and the fix was already there when cloning the repository.
