### ISSUE TITLE
git commit not detected properly with `GitPython < 3.1.9`

### ISSUE THREAD

**Issue by mdering** [mlflow/mlflow#11050]
Hi all,
MLFlow requires GitPython > 2.1.0, however, the function `get_git_commit` relies on `repo.ignored` which did not get added to `GitPython` until [version 3.1.9](https://github.com/gitpython-developers/GitPython/commit/e2067ba536dd78549d613dc14d8ad223c7d0aa5d). This is causing the git commit logging to fail silently since it throws an exception and it is caught and squashed.

**Comment by harupy** [comment]
@mdering Thanks for reporting this. We'll upgrade the GitPython requirement.
