### ISSUE TITLE
[BUG] Python client not respecting environment variables for tracking server auth 

### ISSUE THREAD

**Issue by harrystuart** [mlflow/mlflow#11074]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.10.1
- Tracking server: 2.10.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: 3.12.0
- **yarn version, if running the dev UI**:

### Describe the problem

I am unable to authenticate to my MLFlow server using the Python (3.12) client. I am able to authenticate by making a simple HTTP request using the `requests` library and the same username and password. I have validated that my environment variables are being correctly loaded by printing `os.environ`. Any help would be greatly appreciated, cheers.

### Tracking information

```shell
mlflow server --host 0.0.0.0 --serve-artifacts --artifacts-destination s3://mlflow-artifacts --app-name basic-auth
-----
System information: Windows 10.0.22621
Python version: 3.12.0
MLflow version: 2.10.1
MLflow module location: D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\__init__.py
Tracking URI: http://myhost:5000
Registry URI: http://myhost:5000
MLflow environment variables:
  MLFLOW_TRACKING_PASSWORD: ...
  MLFLOW_TRACKING_USERNAME: ...
MLflow dependencies:
  Flask: 3.0.2
  Jinja2: 3.1.3
  alembic: 1.13.1
  click: 8.1.7
  cloudpickle: 3.0.0
  databricks-cli: 0.18.0
  docker: 7.0.0
  entrypoints: 0.4
  gitpython: 3.1.41
  importlib-metadata: 7.0.1
  markdown: 3.5.2
  matplotlib: 3.8.2
  numpy: 1.26.4
  packaging: 23.2
  pandas: 2.2.0
  protobuf: 4.25.2
  pyarrow: 15.0.0
  pytz: 2023.4
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.4.0
  scipy: 1.12.0
  sqlalchemy: 2.0.25
  sqlparse: 0.4.4
  waitress: 2.1.2
```

### Code to reproduce issue

```
# This fails with 401
import mlflow
os.environ["MLFLOW_TRACKING_USERNAME"] = ...
os.environ["MLFLOW_TRACKING_PASSWORD"] = ...
mlflow.set_tracking_uri('http://my_host:5000')
mlflow.get_experiment_by_name("...")

# This returns 200
import requests
response = requests.get(
    "http://myhost:5000/",
    auth=("...", "..."),
)
```

### Stack trace

```
Traceback (most recent call last):
  File "d:\Users\...\Code\...\test.py", line 23, in <module>
    mlflow.get_experiment_by_name("...")
  File "D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\tracking\fluent.py", line 1412, in get_experiment_by_name
    return MlflowClient().get_experiment_by_name(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\tracking\client.py", line 520, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 221, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 306, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\utils\rest_utils.py", line 220, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\mlflow\utils\rest_utils.py", line 158, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 401 != 200. Response body: 'You are not authenticated. Please see https://www.mlflow.org/docs/latest/auth/index.html#authenticating-to-mlflow on how to authenticate.'
```

### Other info / logs

```

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@harrystuart can you try the following? Does it work?

```
os.environ["MLFLOW_TRACKING_USERNAME"] = "admin"
os.environ["MLFLOW_TRACKING_PASSWORD"] = "password"
```

**Comment by harrystuart** [comment]
This is embarrassing but it turns out that the password manager I am using (1password) did not update my credentials in the browser extension (which I use to retrieve my secrets) - despite being updated in the 1password portal... I somehow missed this discrepancy. A good reminder to always triple check secrets lol. Apologies for the false alarm @harupy.
