### ISSUE TITLE
[BUG] ChatMessagePromptTemplate type gets changed during log and then subsequent load phase

### ISSUE THREAD

**Issue by viktorsobol** [mlflow/mlflow#11081]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 210.2
- Tracking server: 2.10.0

### System information

Both for client and server
OS: CentOS Linux 7 (Core)
Python version: 3.8.13

### Describe the problem

The issue pertains to the integration of Langchain with the MLflow.
While following this [documentation](https://mlflow.org/docs/latest/python_api/mlflow.langchain.html) and using the following methods:
- `mlflow.langchain.log_model`
- `mlflow.langchain.load_model`

When a chain that includes the `ChatMessagePromptTemplate` is saved and subsequently retrieved from MLflow, it gets loaded as a `HumanMessagePromptTemplate`. 

And as a result the whole chain works in a unpredictable way. 

I understand that this is a experimental feature as of now. 

### Tracking information

```shell
System information: Linux #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023
Python version: 3.8.6
MLflow version: 2.9.2
MLflow module location: /opt/app-root/lib64/python3.8/site-packages/mlflow/__init__.py
Tracking URI: <>
Registry URI:  <>
MLflow environment variables: 
  MLFLOW_S3_ENDPOINT_URL: <internal s3 storage>
MLflow dependencies: 
  Flask: 2.3.1
  Jinja2: 3.1.2
  aiohttp: 3.9.3
  alembic: 1.10.4
  boto3: 1.34.38
  botocore: 1.34.38
  click: 8.1.3
  cloudpickle: 2.2.1
  docker: 6.0.1
  entrypoints: 0.4
  fastapi: 0.109.2
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 6.6.0
  markdown: 3.4.3
  matplotlib: 3.7.1
  numpy: 1.24.4
  packaging: 23.1
  pandas: 2.0.3
  prometheus-flask-exporter: 0.22.3
  protobuf: 4.22.3
  pyarrow: 14.0.2
  pydantic: 2.5.2
  pytz: 2023.3
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.29.0
  scikit-learn: 1.2.2
  scipy: 1.10.1
  slowapi: 0.1.9
  sqlalchemy: 2.0.10
  sqlparse: 0.4.4
  tiktoken: 0.6.0
  uvicorn: 0.27.0.post1
  watchfiles: 0.21.0
```

### Code to reproduce issue

```shell
from langchain.prompts import ChatPromptTemplate, ChatMessagePromptTemplate
from langchain.llms import Mlflow, MlflowAIGateway
from langchain_core.messages import SystemMessage
from langchain.prompts import HumanMessagePromptTemplate
from langchain.prompts import PromptTemplate
import mlflow
from langchain import LLMChain

EXPERIMENT_NAME = "mlops-chat-template-example"
GPT_35_TURBO_0613_ENDPOINT = "completions-gpt-3.5-turbo-0613"
TRACKING_URL = '<REPLACE_ME>'
TARGET_URI = '<REPLACE_ME>'
TOP_P = 0.0
TEMPERATURE = 0.0

PROMPT = """
You will analyzing emails from customer. If email contains any disagreement then reply "Bad" 
If the text in email is positive then reply "Good"
"""

mlflow.set_tracking_uri(TRACKING_URL)
mlflow.set_experiment(EXPERIMENT_NAME)


prompt = ChatPromptTemplate.from_messages(
    [
        ChatMessagePromptTemplate.from_template(role = "system", template=PROMPT),
        ChatMessagePromptTemplate.from_template(role = "user", template="{email}"),
    ],
)

llm_gateway = Mlflow(target_uri=TARGET_URI, endpoint=GPT_35_TURBO_0613_ENDPOINT, extra_params = {"top_p": TOP_P, "temperature": TEMPERATURE})
llm_chain = LLMChain(
        llm=llm_gateway,
        prompt=prompt)

# Testing original chain
original_positive = llm_chain.run(email='I disagree')
original_negative = llm_chain.run(email='I agree')

# Logging  
run_name = "test_run"
params = {
        "temperature": TEMPERATURE,
        "top_p": TOP_P,
        "endpoint": GPT_35_TURBO_0613_ENDPOINT,
    }
with mlflow.start_run(run_name=run_name):
        mlflow.log_params(params)
        model_info = mlflow.langchain.log_model(llm_chain, "model")

# Loading model
llm_chain_from_mlflow = mlflow.langchain.load_model(model_info.model_uri)
loaded_negative = llm_chain_from_mlflow.run(email="I disagree")
loaded_positive = llm_chain_from_mlflow.run(email="I agree")

assert type(llm_chain.prompt.messages[0]) == type(llm_chain_from_mlflow.prompt.messages[0]) # FAIL
assert len(llm_chain.prompt.messages) == len(llm_chain_from_mlflow.prompt.messages) # FAIL
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [x] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@viktorsobol It looks like this is a bug in langchain. Here's a script to reproduce the same issue without using mlflow:

```python
import tempfile

from langchain.prompts import ChatPromptTemplate, ChatMessagePromptTemplate
from langchain.llms import OpenAI
from langchain import LLMChain
from langchain.chains.loading import load_chain


PROMPT = """
You will analyzing emails from customer. If email contains any disagreement then reply "Bad"
 If the text in email is positive then reply "Good"
"""


prompt = ChatPromptTemplate.from_messages(
    [
        ChatMessagePromptTemplate.from_template(role="system", template=PROMPT),
        ChatMessagePromptTemplate.from_template(role="user", template="{email}"),
    ],
)

chain = LLMChain(llm=OpenAI(), prompt=prompt)
with tempfile.TemporaryDirectory() as tmpdir:
    chain.save(f"{tmpdir}/model.yaml")
    loaded_chain = load_chain(f"{tmpdir}/model.yaml")

assert type(loaded_chain.prompt.messages[0]) == type(chain.prompt.messages[0]), (
    type(loaded_chain.prompt.messages[0]),
    type(chain.prompt.messages[0]),
)

# AssertionError: (<class 'langchain_core.prompts.chat.HumanMessagePromptTemplate'>, <class 'langchain_core.prompts.chat.ChatMessagePromptTemplate'>)
```
