### ISSUE TITLE
Nested runs should inherit experiment ID from parent

### ISSUE THREAD

**Issue by zhilingc** [mlflow/mlflow#1109]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**: 3.61
- **npm version (if running the dev UI): -
- **Exact command to reproduce**: 

```
# start parent run
with mlflow.start_run(experiment_id=1):
  with mlflow.start_run(nested=True, name="nested"):
    # do something
```

### Describe the problem
When nesting a run under a parent run, the children run do not inherit the experiment ID of their parent by default - is this the expected behavior? If the experiment_id parameter is not provided, the children runs default to the default experiment (0), even if their parent is under another experiment.

**Comment by smurching** [comment]
Hi @zhilingc, thanks for raising this - agree that it's confusing. One recommendation is to use the `mlflow.set_experiment()` API, which will set a global active experiment & use that experiment's ID across both parent & child runs. For 1.0 we may want to consider removing the `experiment_id` argument from `start_run` entirely to reduce confusion / redundancy in the APIs.

**Comment by zhilingc** [comment]
Thanks for the response! Makes sense- setting the experiment id outside of run initialisation does seem like a better practice.

**Comment by ankit-db** [comment]
@zyxue have you tried the workaround here? Is there something that blocks using the best practice of setting the experiment at the start of your code?

**Comment by zyxue** [comment]
@ankit-db , I see. I tried `set_experiment` and it works. I was just wondering. I thought mllfow would figure out the experiment_id automatically given a parent run_id. my code is like

```
        with mlflow.start_run(run_id=parent_run_id):
            with mlflow.start_run(
                run_id=None, run_name=run_name, nested=True
            ) as child_run:
```
