### ISSUE TITLE
[BUG] AttributeError: 'EntryPoints' object has no attribute 'get' while trying to start the local mlflow server

### ISSUE THREAD

**Issue by arghhjayy** [mlflow/mlflow#11109]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.10.0
- Tracking server: x.x.x

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Using a Conda Docker image from MSFT: `mcr.microsoft.com/devcontainers/miniconda:0-3`
- **Python version**: 3.12.1
- **yarn version, if running the dev UI**: N/A

### Describe the problem

I'm using [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) in VSCode, and for the base Docker image, I'm using the Miniconda image from MSFT: `mcr.microsoft.com/devcontainers/miniconda:0-3`. When I try to start a dev server while being in the dev container, I get the following error:

```
Traceback (most recent call last):
  File "/opt/conda/envs/endtoend/bin/mlflow", line 5, in <module>
    from mlflow.cli import cli
  File "/opt/conda/envs/endtoend/lib/python3.12/site-packages/mlflow/cli.py", line 356, in <module>
    type=click.Choice([e.name for e in importlib.metadata.entry_points().get("mlflow.app", [])]),
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
$ mlflow server
```

### Stack trace

```
Traceback (most recent call last):
  File "/opt/conda/envs/endtoend/bin/mlflow", line 5, in <module>
    from mlflow.cli import cli
  File "/opt/conda/envs/endtoend/lib/python3.12/site-packages/mlflow/cli.py", line 356, in <module>
    type=click.Choice([e.name for e in importlib.metadata.entry_points().get("mlflow.app", [])]),
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@arghhjayy thanks for reporting this bug! #11109 resolved it.

**Comment by arghhjayy** [comment]
Didn't get you @harupy. Which PR closed it? I'm still facing this issue

**Comment by harupy** [comment]
Sorry for the confusion. #10752 fixed this issue.

**Comment by arghhjayy** [comment]
Thanks for the clarification @harupy. Any ETA on the next release?

**Comment by harupy** [comment]
@arghhjayy Around 2/25 :)

**Comment by Leomorya** [comment]
C:\Users\leomo>mlflow ui -p 1234
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\leomo\AppData\Local\Programs\Python\Python312\Scripts\mlflow.exe\__main__.py", line 4, in <module>
  File "C:\Users\leomo\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\cli.py", line 356, in <module>
    type=click.Choice([e.name for e in importlib.metadata.entry_points().get("mlflow.app", [])]),
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'

**Comment by arghhjayy** [comment]
@Leomorya the next release should also fix your changes as it directly deals with Mlflow CLI module

**Comment by Gabomfim** [comment]
You can use my fix for now, as it is simpler:

The error is in cli.py, just substitute `get("mlflow.app", [])` by `.select(group="mlflow.app")`

The interface changed and an update was needed.

if this still doesn’t work, just assign `type=None`

**Comment by Leomorya** [comment]
Yes fix thanks, only go  
 C:\Users\leomo\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\cli.py
great

**Comment by janjur** [comment]
> @arghhjayy ETA is 2/25 ~ 2/27 :)

Wen release? 🐵

Thank you for great work :)

**Comment by arghhjayy** [comment]
@janjur 
![Alt Text](https://media1.tenor.com/m/rec5dlPBK2cAAAAd/mr-bean-waiting.gif)
