### ISSUE TITLE
How to close mlflow ui safely? 

### ISSUE THREAD

**Issue by JonXia** [mlflow/mlflow#1111]
- Python: 3.6.5
- pip: 19.0.3
- Nginx: 1.10
How to close mlflow ui safely, I didn't find some usage from the command line like --help or the 
official website.
I close it by kill -9 <pid>,then start it by mlflow ui, but the mlflow ui shows that "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", help me please.

**Comment by sephib** [comment]
Can you share your solution? 
I'm having the same problem
