### ISSUE TITLE
0.9.0 Can't type in form inputs

### ISSUE THREAD

**Issue by timothyjlaurent** [mlflow/mlflow#1113]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX and docker-miniconda
- **MLflow installed from (source or binary)**:  installed from pypi 0.9.0 and from release-0.9 branch
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.9.0
- **Python version**: Python 3.7.2
- **npm version (if running the dev UI): 
- **Exact command to reproduce**: `mlflow ui`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

I installed mlflow==0.9.0 from pypi and noticed that I couldn't type. I see that this was mentioned in #1056 and supposedly fixed with #1007.  I tried installing from `branch-0.9` and from `master` but the problem persists. So this is still a problem

**Comment by timothyjlaurent** [comment]
OK I tried to build from source an manually build js dependencies -- still no dice:

Dockerfile
```
FROM node as js-builder

RUN git clone --single-branch --branch branch-0.9 https://github.com/mlflow/mlflow

WORKDIR /mlflow/mlflow/server/js

RUN npm install

FROM continuumio/miniconda

COPY --from=js-builder /mlflow /mlflow

WORKDIR /mlflow

RUN pip install cloudpickle==0.6.1 nose
RUN python setup.py install

WORKDIR /app

```

**Comment by timothyjlaurent** [comment]
Installing from the master branch isn't any better

**Comment by smurching** [comment]
@timothyjlaurent thanks for catching & reporting this issue! It is a legitimate bug & we've fixed it in MLflow 0.9.0.1 (a PyPI-only release). You can upgrade to the new version via `pip install --upgrade mlflow`

**Comment by smurching** [comment]
One other comment - to build from master, we recommend following the steps [here](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#building-a-distributable-artifact) - the dockerfile you linked looks basically correct, there's just a missing `npm run build` step before you run `python setup.py install` which is needed to generate the JS assets

**Comment by timothyjlaurent** [comment]
Whoops. I overlooked that --- Maybe it would've worked if I had done it correctly -- 

I've built and installed with the 0.9.0.1 tag from pypi and am able to type in the UI -- Thanks for pushing a fix so quickly.
