### ISSUE TITLE
Issue #11109 isn't solved but was closed

### ISSUE THREAD

**Issue by arghhjayy** [mlflow/mlflow#11147]
Hello,

I had put an issue regarding mlflow local server not getting run here: https://github.com/mlflow/mlflow/issues/11109
However, I couldn't understand why the issue was closed by @harupy. The comment made by @harupy said "#11109 fixed it", what does that mean?

2 other people commented how they're still facing the issue.

**Comment by arghhjayy** [comment]
@StathisKap and @QuantLandi, just tagging you guys here since we weren't getting any replies in the previous one

**Comment by rvelasquezrojas** [comment]
I am still experiencing the same problem

**Comment by harupy** [comment]
@arghhjayy Sorry for the confusion. #11109 will be released in the next release. Can we close this?

**Comment by harupy** [comment]
Sorry for the confusion. https://github.com/mlflow/mlflow/pull/10752 fixed this issue. This patch will be release in the next version.

**Comment by Gabomfim** [comment]
You can use my fix for now, as it is simpler:

The error is in cli.py, just substitute `get("mlflow.app", [])` by `.select(group="mlflow.app")`

The interface changed and an update was needed.

if this still doesn’t work, just assign `type=None`

**Comment by Gabomfim** [comment]
Couldn’t we deliver this fix now? I think this is a major issue that should be solved ASAP

**Comment by arghhjayy** [comment]
@Gabomfim interesting. Here's how I made it work:

In `lib/python3.12/importlib/metadata/__init__.py/`, add a method `get()` to the class `EntryPoints(tuple)`:

```
def get(self, name, default):
    try:
        return self.__getitem__(name)
    except Exception:
        return default
```
