### ISSUE TITLE
Add support for ONNX flavor

### ISSUE THREAD

**Issue by avflor** [mlflow/mlflow#1117]
ONNX is an open-format to serialize and represent deep learning models (https://onnx.ai/) that helps users transparently move models between various tools. 

It would be good to add an ONNX flavor so that ONNX models and their metadata can be saved, tracked and eventually loaded and served by various downstream tools. I suggest the following steps:

1) Enhance MLFlow to use the ONNX APIs to save and log models in the MlFlow model format (mlflow.onnx).
2) The mlflow.onnx persistence module should support the py_func flavor so that ONNX models can be loaded and served through Python functions that underneath invoke the ONNX runtime.

**Comment by smurching** [comment]
Thanks @avflor for contributing this in #1127 in time for the MLflow 1.0 release! Will close this issue for now :)
