### ISSUE TITLE
Backup Method of Artifacts Stored on Minio

### ISSUE THREAD

**Issue by lester1027** [mlflow/mlflow#11180]
Dear all,

I would like to get some suggestions about backing up artifacts from a minio server. For now, all my mlflow artifacts are stored on a minio server. When I open the minio directory, I can see all the files are stored in binary forms. 

Moreover, if I export everything with https://github.com/mlflow/mlflow-export-import,  I cannot see any meta.yaml. Instead, I can see experiments.json, experiment.json and run.json. Therefore, I cannot browse the runs with mlflow ui. Under this situation, how should I back up everything such that I can reuse the runs elsewhere?

Thank you.

**Comment by BenWilson2** [comment]
Please file questions in our discussion board, not in the issues board. https://github.com/mlflow/mlflow/discussions
