### ISSUE TITLE
System Tags not getting logged

### ISSUE THREAD

**Issue by ElisonSherton** [mlflow/mlflow#11238]
Hey guys,

I am using the client API and using the `create_run` function from the same to create my runs. At the start I have also called `mlflow.enable_system_metrics_logging()`. 

When I run an experiment, all my metrics get logged properly but the tags associated with the run like those [mentioned here](https://github.com/mlflow/mlflow/blob/master/mlflow/utils/mlflow_tags.py) do not get logged.

![image](https://github.com/mlflow/mlflow/assets/45599762/646c0e83-a8a5-4402-9121-e212a7e409be)

I am actually running my code from a git repo which has multiple branches. Can this be autologged? If yes, how should I configure it?

On [the documentation page here](https://mlflow.org/docs/latest/tracking/tracking-api.html#system-tags) it is mentioned that **The following tags are set automatically by MLflow, when appropriate**. How does mlflow decide on when it is appropriate to log and when it is not?
![image](https://github.com/mlflow/mlflow/assets/45599762/6f5dbcd0-7604-4512-b5b1-58e3c7e1c029)

**Comment by B-Step62** [comment]
Thanks for bringing this up, @ElisonSherton!

- The `mlflow.source.git.commit` is specifically logged when executing code as a standalone script, such as when running `python train.py`. This functionality stems from MLflow's ability to capture git information directly from the script file being executed. You can find the implementation details in the [MLflow source code](https://github.com/mlflow/mlflow/blob/9f0c91e7924286f66290fa2077a4cf6f44e41da5/mlflow/tracking/context/git_context.py#L11-L14). Consequently, this tag won't be logged if you're working within a notebook environment. It's also worth noting that this information doesn't appear under the "Tags" section in the UI but is instead displayed at the top, labeled as "Git Commit:".
![Screenshot 2024-02-28 at 7 18 32](https://github.com/mlflow/mlflow/assets/31463517/78f462f2-fff0-42e4-b9c6-15eae38722db)

- Regarding the `branch` and `repoURL`, these are logged exclusively within the contexts of MLflow Projects and MLflow Recipes.

I hope this response clarifies your question, but the documentation definitely needs to be improved on this.

**Comment by ElisonSherton** [comment]
Sure this does clarify! Thanks for the response @B-Step62 kun, appreciate it. I will use these internal functions and log these tags myself to make them visible for me in the UI for now.
