### ISSUE TITLE
[FR] Support for other APIs when using LangChain

### ISSUE THREAD

**Issue by ai-learner-00** [mlflow/mlflow#11266]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

I realized that logging/loading is only for HuggingFace and OpenAI when using the langchain flavor. It would be nice to have support for other APIs such as ChatOpenAI and Azure OpenAI.

```
llm = ChatOpenAI(temperature=0.1, max_tokens=1000)
chain = LLMChain(llm=llm, prompt=chat_prompt)
with mlflow.start_run():
    model_info = mlflow.langchain.log_model(chain, "langchain_model")
```
```
2024/02/05 09:28:12 WARNING mlflow.langchain.utils: MLflow does not guarantee support for LLMs outside of HuggingFaceHub and OpenAI, found ChatOpenAI
```

I am not sure how we can use custom pyfuncs to add functionality to the existing langchain flavor.

### Motivation

> #### What is the use case for this feature?
To reproduce experiments that involve APIs instead of HuggingFace

> #### Why is this use case valuable to support for MLflow users in general?
When logging only the evaluation results (with a function `model(input_df)` instead of a `logged_model`), we miss out on features such as the ability to register the model that performed best

> #### Why is this use case valuable to support for your project(s) or organization?
Keep track of the prompts and models that performed best by clicking on "Register model"

> #### Why is it currently difficult to achieve this use case?
Unclear how to add functionality to existing langchain flavor

### What component(s) does this bug affect?

- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by rabah-khalek** [comment]
I have the same problem doing this:
```py
from langchain_openai import ChatOpenAI


llm = ChatOpenAI(model="gpt-4", temperature=0) 
chain = RetrievalQA.from_llm(llm=llm, retriever=db.as_retriever(), prompt=prompt)

with tempfile.TemporaryDirectory() as temp_dir:
    persist_dir = os.path.join(temp_dir, "faiss_index")

    # Persist the db to a local fs folder
    db.save_local(persist_dir)

    def load_retriever(persist_directory):
        db = FAISS.load_local(persist_directory, OpenAIEmbeddings())
        return db.as_retriever()


    with mlflow.start_run(run_name="gpt-4"):
        info = mlflow.langchain.log_model(chain,
                                        artifact_path="retrieval_qa",
                                        loader_fn=load_retriever,
                                        persist_dir=persist_dir)
        
        model = mlflow.pyfunc.load_model(info.model_uri)
```
which breaks with the following error:
```
[python3.10/site-packages/mlflow/langchain/__init__.py:648](.venv/lib/python3.10/site-packages/mlflow/langchain/__init__.py:648), in _load_pyfunc(path)

ValueError: Loading openai-chat LLM not supported
```

**Comment by B-Step62** [comment]
Thank you for reporting the issue, @ai-learner-00, @rabah-khalek  !

ChatOpenAI model is not supported in MLflow Langchain flavor yet, due to a known limitation of deserialization in Langchain ([ref](https://github.com/langchain-ai/langchain/pull/8164#issuecomment-1673796125)). We reported the issue to Langchain but it may take time to be able to support that.

In the meantime, you can work around the issue by either:

1. Using the legacy [OpenAI](https://python.langchain.com/docs/integrations/llms/openai) class. (this may not work with the latest Langchain/OpenAI version tho).
2. It appears that the new `lancghain.load` deserialization method works for the new Chat model like ([this](https://github.com/langchain-ai/langchain/pull/8164#issuecomment-1665072602)). You could use this method to create a custom pyfunc model. Please refer to [Serving LLMs with MLflow: Leveraging Custom PyFunc](https://mlflow.org/docs/latest/llms/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.html) for the concrete steps for defining and logging the custom pyfunc model. The example uses Transformers model but you should be able to achieve the same thing for langchain by a few modification like `transformers.AutoModelForCausalLM.from_pretrained(...)` -> `langchain.load.loads(...)`

Sorry for the inconvenience, but I hope this answer helps mitigate the issue!

**Comment by rabah-khalek** [comment]
Thanks a lot @B-Step62,

None of these workarounds work:

> 1. Using the legacy [OpenAI](https://python.langchain.com/docs/integrations/llms/openai) class. (this may not work with the latest Langchain/OpenAI version tho).

Indeed as you said, while the `mlflow.langchain.log_model`/`mlflow.pyfunc.load_model` work with the legacy `langchain_community.llms.OpenAI` (or `langchain.llms.OpenAI`) class, this API was removed from the side of openai so `model.predict(...)` fails (see below).
<details> <summary> code + error </summary> 

```py
from langchain_community.llms import OpenAI
# or from langchain.llms import OpenAI

llm = OpenAI(model="gpt-4", temperature=0) 
chain = RetrievalQA.from_llm(llm=llm, retriever=db.as_retriever(), prompt=prompt)

with tempfile.TemporaryDirectory() as temp_dir:
    persist_dir = os.path.join(temp_dir, "faiss_index")

    # Persist the db to a local fs folder
    db.save_local(persist_dir)

    def load_retriever(persist_directory):
        db = FAISS.load_local(persist_directory, OpenAIEmbeddings())
        return db.as_retriever()


    with mlflow.start_run(run_name="gpt-4"):
        info = mlflow.langchain.log_model(chain,
                                        artifact_path="retrieval_qa",
                                        loader_fn=load_retriever,
                                        persist_dir=persist_dir) # --> this works
        
        model = mlflow.pyfunc.load_model(info.model_uri) # --> this works
        
        model.predict(df_example) # --> this fails
```
```
MlflowException: 2 tasks failed. Errors: {0: 'error: APIRemovedInV1(\'\\n\\nYou tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0
```

</details>

> 2. It appears that the new lancghain.load deserialization method works for the new Chat model like (https://github.com/langchain-ai/langchain/pull/8164#issuecomment-1665072602). You could use this method to create a custom pyfunc model. Please refer to [Serving LLMs with MLflow: Leveraging Custom PyFunc](https://mlflow.org/docs/latest/llms/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.html) for the concrete steps for defining and logging the custom pyfunc model. The example uses Transformers model but you should be able to achieve the same thing for langchain by a few modification like transformers.AutoModelForCausalLM.from_pretrained(...) -> langchain.load.loads(...)

This doesn't work for example code above (with `RetrievalQA` powered by `gpt-4`) with the following error:
```
NotImplementedError: Trying to load an object that doesn't implement serialization
```

Indeed, the problem stems from langchain's support... Appreciated your reactiveness and response here: https://github.com/langchain-ai/langchain/issues/18420 and your 3 proposals. I am happy to contribute to help on any of these 3. This problem has been blocking us for a while

**Comment by B-Step62** [comment]
@rabah-khalek Thank you for the detailed response!

> this API was removed from the side of openai so model.predict(...) fails (see below).

Yes, this seems to block usage of OpenAI >= 1.0.

> Indeed, the problem stems from langchain's support... Appreciated your reactiveness and response here: https://github.com/langchain-ai/langchain/issues/18420 and your 3 proposals. I am happy to contribute to help on any of these 3. This problem has been blocking us for a while

Thank you so much for the willingness to contribute! I thought the second option is preferable in long term (it seems the first option was tried multiple times but always closed suddenly like [this](https://github.com/langchain-ai/langchain/pull/12331)), but the error `NotImplementedError: Trying to load an object that doesn't implement serialization` error you've got might indicate it takes some effort to make it serializable. Ideally they could provide some short-term workaround but sadly we haven't get any attention to the issue yet. It would be really appreciated if you could spend some time for investigating if it is feasible to serde the new chat models. I will also try digging into this but may not have much bandwidth very soon.
