### ISSUE TITLE
[BUG] Cannot use multipart upload for artifacts without artifact_path argument

### ISSUE THREAD

**Issue by gdiepen** [mlflow/mlflow#11268]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.10.2
- Tracking server: 2.10.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.3 LTS
- **Python version**: 3.11.7
- **yarn version, if running the dev UI**:

### Describe the problem

When using the artifact multipart upload functionality with tracking server using artifact serving/proxy with an S3 bucket for artifact storage, you cannot use mlflow.log_artifact(some_local_file). You must also provide the artifact_path argument, because the tracking server expects a path after the `/api/2.0/mlflow-artifacts/mpu/create` in the trcking url (which is not provided if you don't provide an artifact_path argument)

This code will work as expected:
```python
import os
import mlflow

os.environ["MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD"]="True"
os.environ["MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE"]=str(500_000_000)


EXPERIMENT_NAME="testing-large-artifacts"

mlflow.set_experiment(EXPERIMENT_NAME)

with mlflow.start_run() as ml_run:

    # large_file.dat is 250MB
    # Can be generated with command dd if=/dev/zero of=large_file.dat bs=10M count=25

    # This works, since it will NOT use the multipart upload because
    # the filesize which is expected

    # It will upload the file large_file.dat into a folder "artifacts"
    # that is under the key <experiment_id> / <run_id>
    # So for example 
    #   67/d20986b83d054eeb81cf7a2b786b5a38/artifactx/large_file.dat
    os.environ["MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE"]=str(500_000_000)
    mlflow.log_artifact("./large_file.dat")
```

Reducing the threshold for `MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE` to 200MB, means that large file should now be sent to the artifact s3 storage using the MPU functionality, so with the following code (still having large_file.dat being 250 MB):
```python
with mlflow.start_run() as ml_run:
    os.environ["MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE"]=str(200_000_000)
    # Now the 250MB file is above the threshold, so it will use the multipart
    # upload code


    # This will fail, because I am not providing the artifact_path argument
    mlflow.log_artifact("./large_file.dat")
```

will result in the following error:
```
Traceback (most recent call last):
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guido/Projects/Small Test Projects/testing_mlflow_large_artifact_upload/log_large_artifact.py", line 37, in <module>
    mlflow.log_artifact("./large_file.dat")
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 1010, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/tracking/client.py", line 1149, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/client.py", line 529, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 52, in log_artifact
    self._try_multipart_upload(local_file, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 178, in _try_multipart_upload
    error_message = e.response.json().get("message", "")
                    ^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I slightly modified the `store/artifact/http_artifact_repo.py` script to print the exact error and saw the following:
```
404 Client Error: Not Found for url: https://guido-test-mlflow-server/api/2.0/mlflow-artifacts/mpu/create. Response text: <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```
(which explains the fact that json has a problem decoding this)

It looks to me that the new `/api/2.0/mlflow-artifacts/mpu/create` api endpoint has a hardcoded dependency on a path variable in the URL. Also, looking at `protos/mlflow_artifacts_pb2.py` file, I see the following:
![image](https://github.com/mlflow/mlflow/assets/2786853/cdf94ca8-5cdb-4e22-a4b0-8f0d4314be4b)

This might be related to #11225  (When using the multipart upload using proxy and s3 as backend, the final location of the artifact seems to be wrong, namely outside of the experiment_id/run_id folder, but in the root, next to the different folders for the experiment_ids)

### Tracking information

```shell
System information: Linux #1 SMP Thu Oct 5 21:02:42 UTC 2023
Python version: 3.11.7
MLflow version: 2.10.2
MLflow module location: /home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/__init__.py
Tracking URI: https://guido-test-mlflow-server/
Registry URI: https://guido-test-mlflow-server/
MLflow environment variables:
  MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD: True
  MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE: 50000000
  MLFLOW_TRACKING_URI: https://guido-test-mlflow-server/
MLflow dependencies:
  Flask: 3.0.2
  Jinja2: 3.1.3
  alembic: 1.13.1
  click: 8.1.7
  cloudpickle: 3.0.0
  docker: 7.0.0
  entrypoints: 0.4
  gitpython: 3.1.41
  gunicorn: 21.2.0
  importlib-metadata: 7.0.1
  markdown: 3.5.2
  matplotlib: 3.8.2
  numpy: 1.26.4
  packaging: 23.2
  pandas: 2.2.0
  protobuf: 4.25.2
  pyarrow: 15.0.0
  pydantic: 2.6.0
  pytz: 2023.4
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.4.0
  scipy: 1.12.0
  sqlalchemy: 2.0.26
  sqlparse: 0.4.4
```

### Code to reproduce issue

```python

# This reproduction code assumes you have set environment variable
# MLFLOW_TRACKING_URI
# 
# to a MLFlow Tracking server that is using --serve-artifacts AND use s3 as backend storage that is
# started with command similar to:
#     mlflow server \
#      --backend-store-uri postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME} \
#      --artifacts-destination s3://${BUCKET_MLFLOWSTORAGE_NAME}/mlflow \
 #     --serve-artifacts \
 #     --host 0.0.0.0 


import os
import mlflow

# Enable multipart upload in this application
os.environ["MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD"]="True"
os.environ["MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE"]=str(500_000_000)


EXPERIMENT_NAME="testing-large-artifacts"

mlflow.set_experiment(EXPERIMENT_NAME)

with mlflow.start_run() as ml_run:
    os.environ["MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE"]=str(200_000_000)
    # Now the 250MB file is above the threshold, so it will use the multipart
    # upload code

    # You can generate the large file with the command     dd if=/dev/zero of=large_file.dat bs=10M count=25


    # This will fail, because I am not providing the artifact_path argument
    mlflow.log_artifact("./large_file.dat")

  
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guido/Projects/Small Test Projects/testing_mlflow_large_artifact_upload/log_large_artifact.py", line 37, in <module>
    mlflow.log_artifact("./large_file.dat")
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 1010, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/tracking/client.py", line 1149, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/client.py", line 529, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 52, in log_artifact
    self._try_multipart_upload(local_file, artifact_path)
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 178, in _try_multipart_upload
    error_message = e.response.json().get("message", "")
                    ^^^^^^^^^^^^^^^^^
  File "/home/guido/miniconda3/envs/testing_mlflow_robert/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```


### Other info / logs

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```

2024/02/27 12:41:25 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
[2024-02-27 12:41:27 +0000] [137] [INFO] Starting gunicorn 21.2.0
[2024-02-27 12:41:27 +0000] [137] [INFO] Listening at: http://0.0.0.0:5000 (137)
[2024-02-27 12:41:27 +0000] [137] [INFO] Using worker: sync
[2024-02-27 12:41:27 +0000] [138] [INFO] Booting worker with pid: 138
[2024-02-27 12:41:27 +0000] [139] [INFO] Booting worker with pid: 139
[2024-02-27 12:41:27 +0000] [140] [INFO] Booting worker with pid: 140
[2024-02-27 12:41:27 +0000] [141] [INFO] Booting worker with pid: 141```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@gdiepen thanks for reporting, filed #11284

**Comment by gdiepen** [comment]
Thanks @harupy 

I was already trying to wok on some of it locally (stated under guidance would be willing to help out ;-) )

I have my implementation kinda ready (which btw is similar to what you are having in the PR), but having the problem that the final uploaded artifact is one level too deep, using a folder still for the filename.

For example, if you try to upload the file "some_large_file.dat" without any additional path, after uploading it, in the s3 bucket it will be under
`/<experiment_id>/<run_id>/artifacts/some_large_file.dat/some_large_file.dat`

Not sure if your implementation suffers from the same, can give it a quick test here
