### ISSUE TITLE
yes , may be I didn't clear out enough , but I mean when you select many trials from the table and press compare button , a window with parallel view figure opens , this figure is not interactive as the figure you showed in the video.

### ISSUE THREAD

**Issue by osama-ammar** [mlflow/mlflow#11282]
yes , may be I didn't clear out enough , but I mean when you select many trials from the table and press compare button , a window with parallel view figure opens , this figure is not interactive as the figure you showed in the video.

_Originally posted by @osama-ammar in https://github.com/mlflow/mlflow/issues/10987#issuecomment-1930548829_

**Comment by harupy** [comment]
We can discuss in #10987
