### ISSUE TITLE
[BUG]  register_model fails to properly register the model  

### ISSUE THREAD

**Issue by goncalo-maia** [mlflow/mlflow#11316]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.8.0
- Tracking server: 2.8.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Occurs both in windows and ubuntu 22.04
- **Python version**:
3.10.12

### Describe the problem

After creating a run, logging a model and running `register_model()` the model is present in the registry and linked to the run that created it. But it is impossible to download it with `load_model()` , also in the UI the button to register that model is still available, pressing it creates a new model version that can be properly downloaded. 

The use case behind using the register_model function is to automate the process of adding model versions to the registry. I would appreciate some guidance here, thanks.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
mlflow.start_run()
mlflow.onnx.log_model(onnx_model=onnx_model, artifact_path=artifact_path) 
mlflow.register_model(model_uri=model_uri, name=model_name)
```

### Stack trace

What occurs when the model is loaded from the registry
```
Traceback (most recent call last):
    model = mlflow.onnx.load_model(
  File "/usr/local/lib/python3.10/dist-packages/mlflow/onnx/__init__.py", line 434, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/tracking/artifact_utils.py", line 100, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/usr/local/lib/python3.10/dist-packages/mlflow/store/artifact/models_artifact_repo.py", line 178, in download_artifacts
    model_path = self.repo.download_artifacts(artifact_path, dst_path)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/store/artifact/artifact_repo.py", line 221, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from ....
##### File  #####
API request to "model_artifact_uri"  failed with exception HTTPSConnectionPool(host='tracking_uri', port=443): Max retries exceeded (Caused by ResponseError('too many 500 error responses'))
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@goncalo-maia I ran the following code, but could not reproduce the issue.

```python
from sklearn.linear_model import LogisticRegression

import mlflow

with mlflow.start_run():
    info = mlflow.sklearn.log_model(LogisticRegression(), "model")
    mlflow.register_model(model_uri=info.model_uri, name="hello")
    mlflow.sklearn.load_model(info.model_uri)

```

**Comment by goncalo-maia** [comment]
Thanks for the reply. That code runs successfully on my machine.
It made me understand that the issue was related to the way I was passing the model_uri:
`runs:/run_id/artifacts/model` instead of `runs:/run_id/model`

I will close this issue.
