### ISSUE TITLE
[BUG]Commit hash not displayed anymore

### ISSUE THREAD

**Issue by jrakotobe** [mlflow/mlflow#11317]
### Willingness to contribute

No. I cannot contribute a fix for this bug independently.

### MLflow version

2.11.0

### System information

MacOS 14.0

### Describe the problem

Since the recent updates in the UI, the commit hash is not displayed anymore on the UI. Could you please put it back?

### Steps to reproduce the bug

import mlflow
import git
repo = git.Repo()
sha_commit=repo.head.object.hexsha

mlflow.start_run()
mlflow.set_tag('mlflow.source.git.commit', sha_commit)

# open UI and find the run.

**Comment by daniellok-db** [comment]
Looks like this was missed as part of the new migration. Thanks for reporting! I'm working on a PR to add it back.

**Comment by jrakotobe** [comment]
Great! Thank you!
