### ISSUE TITLE
How to use log_metric to store train and test errors in one chart

### ISSUE THREAD

**Issue by chaupmcs** [mlflow/mlflow#1133]
Hi,

I think this is a question rather than an issue. 
I have been using MLFlow for a while and for me it's quite useful. But when it comes to chart, I cope with some minor problems. When saving the train and test errors, I want to put those numbers in the same chart, but I couldn't figure out how to do it.

Here what I've been trying:

    with mlflow.start_run():
        for error in log_loss_error_list_of_train_set:
            mlflow.log_metric("log_loss_train", error)
        for error in log_loss_error_list_of_test_set:
            mlflow.log_metric("log_loss_test", error)`

It worked but it's not exactly what I'm looking for. It creates 2 separate charts.
So, is there any way that I can put the 2 list numbers in 1 chart ?

Thank you

**Comment by apurva-koti** [comment]
You can view multiple metrics in the same graph with the UI.
Navigate to the graph view for either `log_loss_train` or `log_loss_test` and add the other to the Y-axis list on the sidebar controls:
![image](https://user-images.githubusercontent.com/51172624/61749531-d3e0dd00-ad57-11e9-81cd-c9221f7f8c7a.png)

**Comment by chaupmcs** [comment]
Thanks for the answer, but I could not found the sidebar control. What am I missing ?
I tried to re-install mlflow but still couldnt found it.
My version: *mlflow, version 0.8.1*
Please take a look at the attached image.
![image](https://user-images.githubusercontent.com/42042991/61789883-00702400-ae40-11e9-8536-3c46189f319e.png)

**Comment by apurva-koti** [comment]
MLflow was recently updated to version 1.1 on PyPI, Maven and CRAN. Please update your installation of MLflow and file another issue if you're unable to do so.

**Comment by chaupmcs** [comment]
Thanks. I updated MLflow and it now works like a charm.
