### ISSUE TITLE
Feature Request: Support GCS/Azure/SFTP in download utilities

### ISSUE THREAD

**Issue by drewmcdonald** [mlflow/mlflow#1134]
Though GCS, Azure, and (S)FTP are supported as artifact stores in tracking, currently download functionality is limited to S3 and DBFS only. Using GCS as an example, this restricts both `mlflow download gs://bucket/file` and `mlflow run -P my_path_param=gs://bucket/file` (and potentially other areas I have not yet come across). 

The download functionality for DBFS and S3 is handled in [data.py:63](https://github.com/mlflow/mlflow/blob/9199dfcdf27b7395e5094acececa52b26ca4e6e2/mlflow/data.py#L63), and explicitly rejects all other paths.

**Comment by acroz** [comment]
This could possibly be achieved by having the `mlflow download` utility use the artifact repositories to resolve and download paths - then two parallel flows for downloading artifacts from various types of URI don't need to be maintained.
