### ISSUE TITLE
[BUG] Experiments not opening if no training runs are selected

### ISSUE THREAD

**Issue by joshphase** [mlflow/mlflow#11388]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.29.0
- Tracking server: 2.7.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

If I go into an experiment and deselect every single training run, it immediately takes me to the following page and I'm unable to open that experiment in isolation anymore (I can view it if I select multiple experiments at the same time though).

<img width="1667" alt="image" src="https://github.com/mlflow/mlflow/assets/163070214/581c9f78-8b69-4522-862e-35c60c66120d">

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
I tried mlflow 2.7.1 ui, I can't really deselect all experiments, while runs by default you're not selecting them.
<img width="1507" alt="image" src="https://github.com/mlflow/mlflow/assets/82044803/60bbfc51-cebb-4247-9d3a-32ad6c97a9df">

Could you provide your steps to reproduce the problem?

**Comment by joshphase** [comment]
Hmm, it seems to be fixed today, I'm unable to reproduce it at the moment
and I can get into my experiment again. I'll record it in the future if it
happens again to see if I can capture it.

Thanks,
Josh

**Comment by serena-ruan** [comment]
Thanks, please reopen this issue if you encounter it again.

**Comment by joshphase** [comment]
Will do, thanks again for your help!

Best,
Josh
