### ISSUE TITLE
[DOC-FIX] Add JFrog MLFlow plugin in order to store your artifacts on a preferred JFrog repository

### ISSUE THREAD

**Issue by yonarbel** [mlflow/mlflow#11425]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/plugins.html#artifact-repository-plugins

### Description of proposal (what needs changing)

Include details about the [mlflow-jfrog-plugin](https://pypi.org/project/mlflow-jfrog-plugin), and also provide simplified installation instructions, such as `pip install mlflow[jfrog]`

**Comment by daniellok-db** [comment]
Thanks for bringing this up! Feel free to file a PR to contribute, the guide for docs is here: https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md#writing-docs

Let me know if you have any trouble getting set up.

**Comment by yonarbel** [comment]
@daniellok-db  I raised a [PR](https://github.com/mlflow/mlflow/pull/11426) 🙏
