### ISSUE TITLE
[DOC-FIX] Inference server example 

### ISSUE THREAD

**Issue by cile98** [mlflow/mlflow#11421]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/deployment/deploy-model-locally.html

### Description of proposal (what needs changing)

In the python examples on this page, after sending POST request, the output of the `requests.json()` is being printed, which will raise `AttributeError: module 'requests' has no attribute 'json'`. In order to display the response, one would first need to store it in a variable and then call the `.json()` method. It'd look like this

```
response = requests.post(
    url=f"http://localhost:5678/invocations",
    data=payload,
    headers={"Content-Type": "application/json"},
)

print(response.json())

**Comment by daniellok-db** [comment]
Oops, thanks for the catch! Filed #11432 to fix.
