### ISSUE TITLE
[FR] Render Tags and Aliases in the MLFlow Models UI 

### ISSUE THREAD

**Issue by kylegallatin** [mlflow/mlflow#11467]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Currently, `$MLFLOW_URI/#/models` renders tags and aliases.

<img width="755" alt="Screenshot 2024-03-19 at 3 00 37 PM" src="https://github.com/mlflow/mlflow/assets/24701256/65737c04-2d1b-4d45-95d7-a85586bde21f">

But `$MLFLOW_URI/#/models/$MODEL` does not, only showing an "Add" button. 

<img width="1118" alt="Screenshot 2024-03-19 at 3 01 12 PM" src="https://github.com/mlflow/mlflow/assets/24701256/a165a19f-256c-455b-ada2-861b5dfbe68d">

This makes it appear as though a given version of a model has no alias, even when it does. Only when clicking the "Add" button can you see "Add/Edit" and the existing aliases.

<img width="722" alt="Screenshot 2024-03-19 at 3 01 26 PM" src="https://github.com/mlflow/mlflow/assets/24701256/e76c43ee-c363-408c-b786-623f1ccbea93">

This is a _very_ small issue (and potentially a good first UI issue) - but it would be nice to render the tags and aliases associated with model versions in the table that's rendered on `$MLFLOW_URI/#/models/$MODEL`.

### Motivation

> #### What is the use case for this feature?

More easily identify tags and aliases assigned to model versions.

> #### Why is this use case valuable to support for MLflow users in general?

It makes MLFlow more intuitive and user-friendly.

> #### Why is this use case valuable to support for your project(s) or organization?

It makes MLFlow more intuitive and user-friendly.

> #### Why is it currently difficult to achieve this use case?

It's not, but it's a low effort task with a presumably a low/med value add and potentially worth picking up.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
cc @hubertzub-db is this intentional? my read on this is that it may be an intended separation of tags on the model-level and on the version-level.

**Comment by kylegallatin** [comment]
Upgrading to latest 2.11.3 resolved the issue!
