### ISSUE TITLE
Can't able to version the run name but we can add version as tag which is not usefull for sorting in the UI. The Version column in the UI is empty.

### ISSUE THREAD

**Issue by JoelTrulin-capestart** [mlflow/mlflow#11488]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Can't able to version the run name but we can add version as tag which is not usefull for sorting in the UI. The Version column in the UI is empty.
![Screenshot 2024-03-21 164321](https://github.com/mlflow/mlflow/assets/149688798/55b54fdf-b63a-41b2-8270-32b3c13aed25)

### Motivation

> #### What is the use case for this feature?

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
I think the version column is to show the "mlflow.source.git.commit" tag value. e.g., if you do:

```
with mlflow.start_run(tags={"mlflow.source.git.commit": "aabbcc"}):
    pass
```

The version column will show "aabbcc" for this run.

**Comment by WeichenXu123** [comment]
You can read doc: https://mlflow.org/docs/latest/tracking/tracking-api.html

"mlflow.source.git.commit" tag will be automatically logged if in a git repository. This tag is only logged when the code is executed as a Python script like python train.py or as a project. If the code is executed in a notebook, this tag is not logged.

**Comment by JoelTrulin-capestart** [comment]
Ok, Got it
