### ISSUE TITLE
[FR] How to add llm evaluation metrics to existing run?

### ISSUE THREAD

**Issue by ai-learner-00** [mlflow/mlflow#11504]
### Proposal Summary

The page on [prompt engineering](https://mlflow.org/docs/latest/llms/prompt-engineering/index.html#step-13-perform-metric-based-evaluation-of-your-model-s-outputs) has a section on evaluation, but it doesn't show how to add evaluation metrics to the existing prompt engineering run.

Given a `eval_results_table`, can we append evaluation metrics to each row? (without creating a new run)
```python
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000/")
mlflow.set_experiment("test-prompt-engineering-evaluation")

# Load input and output data across all Runs (configurations) as a Pandas DataFrame
eval_df = mlflow.load_table(
    # All inputs and outputs created from the MLflow UI are stored in an artifact called
    # "eval_results_table.json"
    artifact_file="eval_results_table.json",
    # Include the run ID as a column in the table to distinguish inputs and outputs
    # produced by different runs
    extra_columns=["run_id"],
)
```

![image](https://github.com/mlflow/mlflow/assets/158079614/e46289d9-aad9-4b66-bfb2-df9176792243)

Would the following be a good approach? I think it creates new rows each time.
```python
run_id = "2eee3d662a854d04a9d60b69c6b58dff"
eval_df_filtered = eval_df[eval_df["run_id"] == run_id]
with mlflow.start_run(run_id=run_id):
    results = mlflow.evaluate(
        data=eval_df_filtered,
        predictions="output",
        model_type="text",
    )
```

---

Instead of using one run `logged_model = "runs:/840a5c43f3fb46f2a2059b761557c1d0/model"`, it might be nice to include code that iterates over all runs in an experiment.

### Motivation

> #### What is the use case for this feature?
Compare prompt templates.

> #### Why is this use case valuable to support for MLflow users in general?
Prompt engineering is a common problem.

> #### Why is this use case valuable to support for your project(s) or organization?
Easily compare the performance of each run/prompt.

> #### Why is it currently difficult to achieve this use case?
Not sure how to append evaluation metrics to existing rows (maybe duplicate rows will be ignored so it's not a problem?)

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
You can use

```
with mlflow.start_run(run_id='an existing run id'):
  mlflow.log_metric(...)
```

to add any metric value to existing run.

**Comment by ai-learner-00** [comment]
@WeichenXu123 I meant [LLM evaluation metrics](https://mlflow.org/docs/latest/llms/llm-evaluate/index.html#metrics-with-llm-as-the-judge) such as correctness for each row/input. (`mlflow.evaluate` also creates "global" metrics such as average answer correctness score)

Since the prompt engineering UI doesn't add metrics, they need to be "appended" programmatically.

**Comment by WeichenXu123** [comment]
emm, I think current `mlflow.evaluate` doesn't support this patten. for each `mlflow.evalute` invocation, you have to prepare the whole dataset you want to evaluate

**Comment by ai-learner-00** [comment]
I would suggest adding something like `overwrite=True` and `dont_recompute=True` to `mlflow.evaluate`. The problem is similar to [evaluate metrics inside a prompt engineering UI run](https://github.com/mlflow/mlflow/issues/10937).

Currently, are we supposed to create new runs each time we add a row and prompt? (We won't be able to use the prompt engineering UI with runs added programmatically.)
