### ISSUE TITLE
mlflow.start_run() spike

### ISSUE THREAD

**Issue by chmjelek** [mlflow/mlflow#11507]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.11.2

### System information

- **OS Platform and Distribution: Ubuntu 22.04 LTS
- **Python version**: 3.8.18

### Describe the problem

I am using mlflow to log artifacts in a flask application. Within one experiment I need to have multiple runs. I have noticed that sometimes, at random, the response to a request is much longer than the standard (up to ~15 times). The source of the problem seems to be the mlflow.start_run() function.

**Code to reproduce issue**

To reproduce the problem i have created a simple snippet:

```
import time

import mlflow


def get_or_create_experiment(recipe_id: str) -> str:
    experiment = mlflow.get_experiment_by_name(recipe_id)
    if experiment is None:
        return mlflow.create_experiment(recipe_id)
    return experiment.experiment_id


times = []
exp_id = get_or_create_experiment("My_Experiment")
for i in range(2500):
    start = time.time()
    with mlflow.start_run(experiment_id=exp_id) as run:
        run_id = run.info.run_id
    end = time.time()
    elapsed = end - start
    times.append(elapsed)
    with open("times.txt", "a") as f:
        f.write(str(i) + " " + str(elapsed) + "\n")

print(max(times))
```
 
The place where the "spikes" occurred:

```
2060 0.07198357582092285
2061 0.07214164733886719
2062 0.39851284027099614        # suddenly from 0.07s to 0.4s
2063 1.03893780708312996        # then to 1s
2064 0.06491684913635254        # back to normal
2065 0.07542610168457031
2066 0.06549763679504395
2067 0.07014608383178711
2068 0.08010697364807129
2069 0.06647610664367676
2070 0.20720028877258314        # again minor spike, this time not followed up by bigger one
2071 0.06598067283630371
2072 0.06618285179138184
```

These are the statistics of the times: 

Average: 0.06594382448196406
Median: 0.063284158706665
Minimum: 0.0444378852844238
Maximum: 1.03893780708313

The response from my application must be received within a certain time, there can be no such spikes.

What causes and how to fix them?

**Comment by WeichenXu123** [comment]
emm, interesting, did you do  some profiling to confirm which function causes it ?

btw, seemingly this is not a bug but a performance issue.

**Comment by WeichenXu123** [comment]
No response for a long time. I will close it for now. If you have update , feel free to reopen it  :)
