### ISSUE TITLE
[BUG] Fetching run via GraphQL ends up in enum-related error

### ISSUE THREAD

**Issue by hubertzub-db** [mlflow/mlflow#11526]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.10.3.dev0
- Tracking server: 2.10.3.dev0

### System information

- `Darwin 22.6.0 Darwin Kernel Version 22.6.0: Sun Dec 17 22:12:45 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_ARM64_T6000 arm64`
- `Python 3.8.13`

### Describe the problem

When resolving `status` field on `mlflowGetRun` query, I'm getting `"Enum 'MlflowRunStatus' cannot represent value: 3"` error

### Code to reproduce issue

```
POST http://localhost:5000/graphql

{
    "operationName": "GetRun",
    "variables": {
        "data": {
            "runId": "39332a27cb3942959e7e10b3677d437c"
        }
    },
    "query": "query GetRun($data: MlflowGetRunInput\u0021) {\n  mlflowGetRun(input: $data) {\n    run {\n      info {\n     status\n   runId\n    }\n                 __typename\n    }\n    __typename\n  }\n}\n"
}
```

### Stack trace

```
{
    "data": {
        "mlflowGetRun": {
            "__typename": "MlflowGetRunResponse",
            "run": {
                "__typename": "MlflowRunExtension",
                "info": {
                    "runId": "39332a27cb3942959e7e10b3677d437c",
                    "status": null
                }
            }
        }
    },
    "errors": [
        "Enum 'MlflowRunStatus' cannot represent value: 3"
    ]
}
```

### Other info / logs

```
{
    "data": {
        "mlflowGetRun": {
            "__typename": "MlflowGetRunResponse",
            "run": {
                "__typename": "MlflowRunExtension",
                "info": {
                    "runId": "39332a27cb3942959e7e10b3677d437c",
                    "status": null
                }
            }
        }
    },
    "errors": [
        "Enum 'MlflowRunStatus' cannot represent value: 3"
    ]
}
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
@edwardfeng-db Could you help taking a look ? I am not familiar with GraphQL

**Comment by edwardfeng-db** [comment]
Yes, will do
