### ISSUE TITLE
[BUG] re-creating a previously deleted model name will result in SQL error

### ISSUE THREAD

**Issue by thesuperzapper** [mlflow/mlflow#11591]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.11.1
- Tracking server: 2.11.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Python version**: 3.10
- **yarn version, if running the dev UI**:

### Describe the problem

When attempting to create a new model using `client.create_registered_model()`, with a name that has been used previously (but subsequently deleted), you will get a Python error because the SQL table with permissions already has that model.

Note, the model will still be created, but I am not sure if there are any other effects, like permissions being messed up.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
import os
import mlflow

# create a client
os.environ["MLFLOW_TRACKING_URI"] = "https://mlflow.example.com"
os.environ["MLFLOW_TRACKING_INSECURE_TLS"] = "true"
os.environ["MLFLOW_TRACKING_USERNAME"] = "admin"
os.environ["MLFLOW_TRACKING_PASSWORD"] = "admin"
client = mlflow.tracking.MlflowClient()

# configs
MODEL_NAME = "my-model-3"

# create a registered model
print("===== Creating registered model...")
client.create_registered_model(name=MODEL_NAME)
print("===== Success.")

# delete the registered model
print("===== Deleting registered model...")
client.delete_registered_model(name=MODEL_NAME)
print("===== Success.")

# try to re-create the registered model
print("===== Re-creating registered model...")
client.create_registered_model(name=MODEL_NAME)
print("===== Success.")
```

### Stack trace

```
===== Creating registered model...
===== Success.
===== Deleting registered model...
===== Success.
===== Re-Creating registered model...
Traceback (most recent call last):
  File "/Users/mathew/PycharmProjects/test-mlflow/python/bad.py", line 36, in <module>
    client.create_registered_model(name=model_name)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlflow_torch/lib/python3.10/site-packages/mlflow/tracking/client.py", line 2192, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlflow_torch/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlflow_torch/lib/python3.10/site-packages/mlflow/store/model_registry/rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlflow_torch/lib/python3.10/site-packages/mlflow/store/model_registry/base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlflow_torch/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 220, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlflow_torch/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 152, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_ALREADY_EXISTS: Registered model permission (name=my-model-3, username=admin) already exists. Error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "unique_name_user"
DETAIL:  Key (name, user_id)=(my-model-3, 1) already exists.

[SQL: INSERT INTO registered_model_permissions (name, user_id, permission) VALUES (%(name)s, %(user_id)s, %(permission)s) RETURNING registered_model_permissions.id]
[parameters: {'name': 'my-model-3', 'user_id': 1, 'permission': 'MANAGE'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@thesuperzapper Could you share more about the database, and also check if there is any configuration that prevent the hard delete of a row? I could delete and re-register the model on my end with MLflow 2.11.1 with SQLite.

**Comment by thesuperzapper** [comment]
@B-Step62 I am using PostgreSQL `16.1.0`, but I think the issue is that `registered_model_permissions` is not getting cleaned up when you delete a model. 

So, databases that actually enforce "unique constraints" will fail when recreating a model and will be unable to INSERT a new row to `registered_model_permissions` (because one with that key already exists). Clearly the semantics should be UPSERT (or we should remove the permission row when deleting the model).

I am not sure if SQLite is used the same as more traditional DBs in MLFlow.

**Comment by B-Step62** [comment]
@thesuperzapper Understood, thank you for the description! Yes that seems to be a bug, I will investigate and file a patch.
