### ISSUE TITLE
[DOC-FIX] Restoring access to older versions of the documentation from the website

### ISSUE THREAD

**Issue by Stefano97** [mlflow/mlflow#11629]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://mlflow.org/docs/1.7.2/tracking.html

### Description of proposal (what needs changing)

Access Denied when trying to access older versions of the library. Might want to keep just fewer versions, but at least one working with python2. It would be of great help also for future reference for older projects.

**Comment by harupy** [comment]
@Stefano97 We recently removed the old docs for faster website rebuild and save the storage costs (s3). I can send you the 1.7.2 docs if necessary.

**Comment by Stefano97** [comment]
I imagined that. If it is possible that would be of great help. Thought of reporting just because version 1.7.2 to my knowledge is the last version that supports python2 and therefore is not compatible with newer versions and you could consider of keeping just that.

**Comment by harupy** [comment]
@Stefano97 Here's the 1.7.2 documentation:

[1.7.2.zip](https://github.com/mlflow/mlflow/files/14901090/1.7.2.zip)

**Comment by Stefano97** [comment]
Thanks. It is of great help in learning mlflow for python2
