### ISSUE TITLE
[BUG]: mlflow.langchain.log_model and mlflow.langchain.save_model do not save n_gpu_layers parameter of local GGUF llama-cpp-python models

### ISSUE THREAD

**Issue by filbert42** [mlflow/mlflow#11645]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.11.3
- Tracking server: 2.6.0

### System information

- **OS Platform and Distribution**: CentOS Stream 9
- **Python version**: 3.11

### Describe the problem

I'm using MLFlow to track Langchain's chain that uses local GGUF model opened with ```langchain.llms.LlamaCpp```.
For some reason `model.yaml` file created by MLFLow doesn't include the `n_gpu_layers` parameter from the model object.
As a result, `mlflow.langchain.load_model` function tries to open my model with 0 GPU layers.
I can add `n_gpu_layers` parameter manually to the YAML file of the corresponding step and then it opens the model with the correct number of layers.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
from langchain.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    MessagesPlaceholder,
)
from langchain_core.messages import SystemMessage
from langchain_experimental.chat_models import Llama2Chat
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableParallel, RunnablePassthrough
from langchain.llms import LlamaCpp 
import mlflow

model_path = "/opt/app-root/src/llama-2-13b-chat.Q5_K_M.gguf"
llm=LlamaCpp(
    model_path=model_path,
    temperature=0, 
    max_tokens=2000,
    top_p=1,
    n_gpu_layers=-1, # Set to use all 41 layers
    n_batch=512,
    n_ctx=2048,
    f16_kv=True
)

print(llm) # LlamaCpp object
print(llm.n_gpu_layer) # prints 41

template_messages = [
    ("system", "You are a helpful assistant."),
    ("human", "{input}"),
]
prompt_template = ChatPromptTemplate.from_messages(template_messages)

chain = (
    {"input": RunnablePassthrough()} 
    | prompt_template 
    | llm
    | StrOutputParser()
)

with mlflow.start_run() as run:
    model_info = mlflow.langchain.log_model(chain, 'langchain_model') 

loaded_model = mlflow.langchain.load_model(model_info.model_uri) # loads with 0 GPU layers

print(loaded_model.middle[1]) # LlamaCpp object
print(loaded_model.middle[1].n_gpu_layers) # prints nothing
```

### Stack trace

```
```

### Other info / logs

```
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@filbert42 Thanks for reporting this. Are other parameters such as `n_batch` logged?

**Comment by harupy** [comment]
@filbert42 This might be an issue in langchain.

**Comment by filbert42** [comment]
@harupy Thank you!

> @filbert42 I think this is an issue in langchain. A `LlamaCpp` is serialized as a yaml file but the `_default_params` method doesn't output `n_gpu_layers`:

I think you're right - those (from the  ` _default_params`) are the parameters that are being logged into the model.yaml and other parameters like `n_batch` or `n_ctx` are not.
However, as far as I can see, there are some additional meta-parameters for model's loading inside the YAML file, like `model_path` and `_type`. Wouldn't it be reasonable to also include `n_gpu_layers` in it? 

In the meantime, maybe there is some workaround to `load_model` from MLFLow passing custom parameters?
Without this it seems impossible to load local models from MLFlow and actually use them or evaluate them on GPU hardware :(

**Comment by harupy** [comment]
>　However, as far as I can see, there are some additional meta-parameters for model's loading inside the YAML file, like model_path and _type. Wouldn't it be reasonable to also include n_gpu_layers in it?

I think langchain should do this, not mlflow. What mlflow does is to call `LlamaCpp.dict` and saves the result as a yaml file.

**Comment by harupy** [comment]
> In the meantime, maybe there is some workaround to load_model from MLFLow passing custom parameters?
Without this it seems impossible to load local models from MLFlow and actually use them or evaluate them on GPU hardware :(

This is a hack, but you can try monkey-patching `LlamaCpp.dict` to include `n_gpu_layers`.

```
orig = LlamaCpp.dict

def patch(self, *args, **args):
    res = orig(self, *args, **kwargs)
    res["n_gpu_layers"] = ...
```

I'm not 100% sure if this really works.

**Comment by harupy** [comment]
I'm closing this PR. I think this should be fixed in langchain.
