### ISSUE TITLE
Can someone provide an example on how to use mlflow server in artifacts-only mode? How do clients interact with it using python, rest, etc. There is absolutely no documentation on this.[DOC-FIX]

### ISSUE THREAD

**Issue by guzman109** [mlflow/mlflow#11650]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/tracking/server.html#optionally-using-a-tracking-server-instance-exclusively-for-artifact-handling

### Description of proposal (what needs changing)

Examples on how to setup and use mlflow server in artifacts-only mode along with a a tracking server. The website says its possible but does not show how to do it.

**Comment by harupy** [comment]
@guzman109 Thanks for reporting this. I've filed #11654.

**Comment by guzman109** [comment]
It's still not clear how a client would interact with it. An example would really help.
