### ISSUE TITLE
[BUG] Further local dev environment setup dependency issues for Apple Silicon Macs

### ISSUE THREAD

**Issue by chilir** [mlflow/mlflow#11686]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: M1 macOS Sonoma 14.2.1
- **Python version**: 3.X
- **yarn version, if running the dev UI**:

### Describe the problem

Following up on https://github.com/mlflow/mlflow/issues/11569, I'm observing further issues trying to set up the dev environment on my laptop. I have some ideas on how to address these issues but would like to discuss them before committing to any changes. Given that I'm new to contributing, I may be lacking some context.

#### 1) LightGBM wheel requires `libomp`. Affects 3.8, 3.9, and 3.10. Did not try out with 3.11 and 3.12.
Straightforward fix: install `libomp` with brew here
 https://github.com/mlflow/mlflow/blob/fc858460b719be7c1dfec414b5219533a3424455/dev/dev-env-setup.sh#L163

This line wouldn't run if the user already has `pyenv` installed, would just have to hope the new contributor can parse the stack trace themselves in that case 😅.

Unknown if this affects Linux as well, will opt against making this change for the Linux library installation lines

#### 2) Full dev dependencies for Python 3.8 on Apple Silicon Mac are currently not resolvable at all due to `tensorflow`.
(Note that Python 3.8 support was dropped in `tensorflow 2.14.0`)
The only available wheels built for Python 3.8 and ARM Mac are `tensorflow 2.13.x` versions, which requires `typing-extensions <4.6.0` and conflicts with multiple dependencies needing `typing-extensions >=4.6.0` - previously noted in https://github.com/mlflow/mlflow/pull/9466. `tensorflow 2.12.x` is not installable, no 3.8 ARM Mac wheels are available on PyPi https://pypi.org/project/tensorflow/2.12.0/#files.

The Python 3.8 + ARM Mac combo *shouldn't* affect too many people? Should probably just note in documentation somewhere (like CONTRIBUTING) that this combination is currently not able to set up the dev environment locally and nudge people towards using dev containers.

#### 3) 3.9+3.10 (and probably 3.11 and 3.12 as well) issues with `doc-requirements.txt`
As noted in https://github.com/mlflow/mlflow/issues/11569, `tensorflow-cpu` wheels seem to no longer available at all for ARM Macs across the board. And also as with the 3.8 issues above, only `tensorflow 2.13.x` and above have any ARM Mac wheels available. Both of these are in conflict with the `tensorflow-cpu<=2.12.0` dependency in doc requirements https://github.com/mlflow/mlflow/blob/fc858460b719be7c1dfec414b5219533a3424455/requirements/doc-requirements.txt#L2

Given that `tensorflow-cpu` was added in https://github.com/mlflow/mlflow/pull/9754 to seemingly to speed up the `build_docs` job on CircleCI and that job directly installs requirements through `doc-requirements.txt`, would it be reasonable to swap out `doc-requirements` with `doc-min-requirements` in `dev-requirements.txt` and `dev-env-setup.sh`?
https://github.com/mlflow/mlflow/blob/fc858460b719be7c1dfec414b5219533a3424455/.circleci/config.yml#L54-L58

Please correct me if I'm wrong, but full doc requirements don't seem to be needed for the dev environment unless people are looking to build the docs locally, so it should be low risk and low impact to swap it out for minimum doc requirements when setting up the dev environment. It doesn't seem like docs can even be built with `make html` without gateway requirements, which currently isn't part of the dev environment setup.

This would also partially address the Python 3.8 issues from above, non-full dev requirements would be installable.

The alternative is to replace `tensorflow-cpu<=2.12.0` with just `tensorflow` in `doc-requirements` since `tensorflow 2.16.1` no longer requires `typing-extensions <4.6.0`, but it could lead to a slowdown in the CI/CD job.
  

### Code to reproduce issue

```
dev/dev-env-setup.sh -f -o 3.8  # affects lightgbm in extra-ml-requirements.txt
dev/dev-env-setup.sh -o 3.8 # affects lightgbm as a flaml[automl] dependency in test-requirements.txt
```

### Stack trace

```
Building wheels for collected packages: lightgbm
  Building wheel for lightgbm (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lightgbm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      2024-04-11 10:45:06,590 - scikit_build_core - INFO - RUN: /private/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/pip-build-env-__7lw5xy/normal/lib/python3.8/site-packages/cmake/data/bin/cmake --version
      2024-04-11 10:45:06,596 - scikit_build_core - INFO - CMake version: 3.29.1
      *** scikit-build-core 0.8.2 using CMake 3.29.1 (wheel)
      2024-04-11 10:45:06,602 - scikit_build_core - INFO - Build directory: /private/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/tmpj68rp24s/build
      *** Configuring CMake...
      2024-04-11 10:45:06,613 - scikit_build_core - INFO - RUN: /private/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/pip-build-env-__7lw5xy/normal/lib/python3.8/site-packages/ninja/data/bin/ninja --version
      2024-04-11 10:45:06,705 - scikit_build_core - INFO - Ninja version: 1.11.1
      2024-04-11 10:45:06,707 - scikit_build_core - INFO - RUN: /private/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/pip-build-env-__7lw5xy/normal/lib/python3.8/site-packages/cmake/data/bin/cmake -S. -B/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/tmpj68rp24s/build -DCMAKE_BUILD_TYPE:STRING=Release -C/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/tmpj68rp24s/build/CMakeInit.txt -DCMAKE_MAKE_PROGRAM=/private/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/pip-build-env-__7lw5xy/normal/lib/python3.8/site-packages/ninja/data/bin/ninja -D__BUILD_FOR_PYTHON:BOOL=ON
      loading initial cache file /var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/tmpj68rp24s/build/CMakeInit.txt
      -- The C compiler identification is AppleClang 15.0.0.15000100
      -- The CXX compiler identification is AppleClang 15.0.0.15000100
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
      -- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
      -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
      -- Found OpenMP_C: -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include
      -- Found OpenMP_CXX: -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include
      -- Found OpenMP: TRUE
      -- Performing Test MM_PREFETCH
      -- Performing Test MM_PREFETCH - Failed
      -- Performing Test MM_MALLOC
      -- Performing Test MM_MALLOC - Success
      -- Using _mm_malloc
      -- Configuring done (0.8s)
      -- Generating done (0.0s)
      -- Build files have been written to: /var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/tmpj68rp24s/build
      *** Building project with Ninja...
      2024-04-11 10:45:07,563 - scikit_build_core - INFO - RUN: /private/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/pip-build-env-__7lw5xy/normal/lib/python3.8/site-packages/cmake/data/bin/cmake --build /var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/tmpj68rp24s/build
      ninja: error: '/opt/homebrew/opt/libomp/lib/libomp.dylib', needed by '/private/var/folders/80/fyvm09wn1dl7fx9kyz8fjxxh0000gn/T/pip-install-iafoid59/lightgbm_6f40e9cabf934f48bd565b564b79f345/lib_lightgbm.so', missing and no known rule to make it

      *** CMake build failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lightgbm
Failed to build lightgbm
ERROR: Could not build wheels for lightgbm, which is required to install pyproject.toml-based projects
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@chilir You could install tensorflow-macos instead. Adding libomp sounds good to me! Could you revert the doc-min-requirements change?

**Comment by chilir** [comment]
Do you mean like temporarily change `tensorflow-cpu<=2.12.0` to `tensorflow-macos<=2.12.0` in `doc-requirements.txt`, run the dev set up script, then revert the change once the environment is set up?
