### ISSUE TITLE
[BUG] latest mlflow version does not support conda environment docker 

### ISSUE THREAD

**Issue by menno4000** [mlflow/mlflow#11681]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.11.3
- Tracking server: 2.11.3

### System information

- Linux Ubuntu 20.04
- Python 3.10.13

### Describe the problem

When creating docker images from completed runs using the mlflow models CLI, either using build-docker or generate-dockerfile commands, we set the environment manager flag to use conda in order to make use of our conda.yaml environment definition.

Since 2.11.x, the environment manager in the resulting dockerfiles and images is always set to "local" despite the value of the flag -env--manager being "conda". Implying virtualenv usage, the resulting image only draws library installations from pip dependencies (in generate-dockerfile, these are redirected into a requirements.txt file), while the dependencies normally installed through conda are not part of the resulting image, resulting in defunct docker containers unable to execute our inference code.

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

CLI Command to reproduce: 
`mlflow models generate-dockerfile -m file:/./mlruns/0/<run id>/artifacts/models --env-manager=conda`

Resulting Dockerfile:
```
# Build an image that can serve mlflow models.
FROM python:3.10.13-slim

RUN apt-get -y update && apt-get install -y --no-install-recommends nginx



WORKDIR /opt/mlflow

# Install MLflow
RUN pip install mlflow==2.11.3

# Copy model to image and install dependencies
COPY model_dir/models /opt/ml/model
RUN python -c "from mlflow.models import container as C; C._install_pyfunc_deps('/opt/ml/model', install_mlflow=False, enable_mlserver=False, env_manager='local');"

ENV MLFLOW_DISABLE_ENV_CREATION=True
ENV ENABLE_MLSERVER=False
ENV GUNICORN_CMD_ARGS="--timeout 60 -k gevent"

# granting read/write access and conditional execution authority to all child directories
# and files to allow for deployment to AWS Sagemaker Serverless Endpoints
# (see https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html)
RUN chmod o+rwX /opt/mlflow/

# clean up apt cache to reduce image size
RUN rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["python", "-c", "from mlflow.models import container as C; C._serve('local')"]
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Seems it's updated here https://github.com/mlflow/mlflow/blob/c2d13b1bb9f84fb37bba57026026508c58f0326f/mlflow/pyfunc/backend.py#L379-L382 @B-Step62 Yuki, is there any specific reason why we set local here? If it's not consistent with the env_manager user set then maybe we should emit a warning at least 🤔

**Comment by B-Step62** [comment]
> Yuki, is there any specific reason why we set local here? 

The original motivation was multiple requests saying the docker image doesn't need additional virtualization (virtualenv/conda). But I think we shouldn't override what user specifies, so the better way would be default to local and let users to pass either (note that if the base image is not python, we should default to virtualenv because direct python installation to ubuntu image is troublesome). How does that sound?
