### ISSUE TITLE
[BUG] onnx model logged twice (second time in metadata folder)

### ISSUE THREAD

**Issue by mayorblock** [mlflow/mlflow#11684]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: mlflow-skinny==2.11.3 
- Tracking server: 2.11.3

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 14.4.1
- **Python version**: 3.10

### Describe the problem

Thanks for providing mlflow for us to use :)

Work on [this PR](https://github.com/mlflow/mlflow/pull/11357) introduces double-logging of external data for ONNX model:
<img width="1006" alt="image" src="https://github.com/mlflow/mlflow/assets/126508264/1ef89ed6-20e3-4593-a7f2-6ef2b0ebaed9">

It happens under the hood because `save_as_external_data=True` by default in [mlflow.onnx.log_model](https://mlflow.org/docs/latest/python_api/mlflow.onnx.html#mlflow.onnx.log_model) 

I don't fully understand the reasoning behind the copying into `metadata` folder (maybe you can explain it to me?) but at least logging the sizeable data twice seems like a bug?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@WeichenXu123 Can we only copy model and other artifacts into metadata folder when the model is registered as UC model? It seems a bug to me when we by default save the same artifacts twice 🤔 And this seems true for all flavors besides onnx.

**Comment by WeichenXu123** [comment]
Thoughts: @BenWilson2 

I think we can let each flavor choose whether to use blacklist or whitelist to filter out metadata files.

For some flavors, blacklist is easier way but some others whitelist is easier way.

i.e. each flavor can define either`non_metadata_file_paths` attribute or `metadata_file_paths` .
