### ISSUE TITLE
Supporting multiple inputs to PyTorch

### ISSUE THREAD

**Issue by jendrikjoe** [mlflow/mlflow#1172]
## Feature request

Would it be possible to allow multiple inputs for PyTorch models.
I currently work on a neural network which requires multiple input tensors that can not be merged or stacked in advance and the requirement to only have one FloatTensor as an input prevents me from using mlflow for this model.

**Comment by ocharles** [comment]
So is this possible?

**Comment by ocharles** [comment]
I think https://github.com/mlflow/mlflow/pull/13933 is maybe the solution
