### ISSUE TITLE
[DOC-FIX] Fix invalid function parameter type from into to str

### ISSUE THREAD

**Issue by 80rian** [mlflow/mlflow#11777]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/getting-started/registering-first-model/step3-load-model.html

### Description of proposal (what needs changing)

```python3
client.set_registered_model_alias(
    model_name, model_version_alias, 1
)
```

this throws an error as `TypeError: bad argument type for built-in operation` since `set_registered_model_alias` accepts str for `version` parameter.

```python3
def set_registered_model_alias(
    name: str,
    alias: str,
    version: str
) -> None
```

Would like to suggest fixing the document as 

```python3
client.set_registered_model_alias(
    model_name, model_version_alias, "1"
)
```

**Comment by daniellok-db** [comment]
Hi @80rian, thanks for catching this! Please let me know if you need any help fixing it 😃
