### ISSUE TITLE
[BUG] Proxied multipart upload artifact using S3 backend not working: `Error parsing the X-Amz-Credential parameter; the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\'`

### ISSUE THREAD

**Issue by job-almekinders** [mlflow/mlflow#11828]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.12.1
- Tracking server: 2.12.1

### System information

Client:
- Mac M1 - OS Sonoma 14.1.1
- Python 3.10.13

Tracking server:
- Debian GNU/Linux 11 (bullseye), Version 11
- Python 3.10.13

### MLFlow tracking server

* AWS S3 artifact store
* Postgres backend store
* Running this command in a kubernetes pod container: 

```bash
mlflow server \
--serve-artifacts \
--host 0.0.0.0 \
--port 5001
```

Relevant env vars set:
- AWS_REGION=eu-west-1

### Client

Relevant env vars set:
- MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD=True
- MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE=2_000_000
- MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE=1_000_000
- AWS_DEFAULT_REGION=eu-west-1
- AWS_REGION=eu-west-1

### Actual

When logging an artifact using multipart upload from the mlflow python client, the upload fails with an MlflowException stating: `the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\` (full StackTrace below).
My S3 bucket is located in `eu-west-1`. It is very strange to me that `us-east-1` is stated here. 

When uploading the same artifact **without** multipart upload, everything works fine.

### Expected

The upload would execute using the multipart upload strategy, and the upload would succeed.

### Steps to reproduce
1. Host the mlflow tracking server with the version mentioned above in proxied pattern using AWS S3 as artifact store and postgresql as backend store (use the command mentioned in the setup section above).
2. On client side: Set the environment variables as described above, and use the python mlflow client with the version mentioned above to -
- Create an experiment
- Create a run
- Log artifact that is more than 2MB

### Tracking information

```shell
System information: Darwin Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Python version: 3.10.13
MLflow version: 2.12.1
MLflow module location: /*my-path*/Library/Caches/pypoetry/virtualenvs/mlflow-tracking-test-vApRi4MC-py3.10/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: file:///*my-path*/mlruns
Registry URI: file:///*my-path*/mlruns
MLflow environment variables: 
  MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD: True
  MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE: 1_000_000
  MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE: 2_000_000
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.3
  alembic: 1.13.1
  boto3: 1.34.90
  botocore: 1.34.90
  click: 8.1.7
  cloudpickle: 3.0.0
  docker: 7.0.0
  entrypoints: 0.4
  gitpython: 3.1.43
  graphene: 3.3
  gunicorn: 21.2.0
  importlib-metadata: 7.1.0
  markdown: 3.6
  matplotlib: 3.8.4
  numpy: 1.26.4
  packaging: 23.2
  pandas: 2.2.2
  protobuf: 4.25.3
  pyarrow: 15.0.2
  pytz: 2024.1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.4.2
  scipy: 1.13.0
  sqlalchemy: 2.0.29
  sqlparse: 0.5.0


DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): *my-url*.com:443
DEBUG:urllib3.connectionpool:https://*my-host*:443 "GET /api/2.0/mlflow/experiments/get-by-name?experiment_name=mlflow-demo HTTP/1.1" 200 233
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/*my-path*, stdin=None, shell=False, universal_newlines=False)
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/*my-path*, stdin=None, shell=False, universal_newlines=False)
DEBUG:git.cmd:Popen(['git', 'check-ignore', '/*my-path*'], cwd=/*my-path*, stdin=None, shell=False, universal_newlines=False)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/*my-path*, stdin=<valid stream>, shell=False, universal_newlines=False)
DEBUG:urllib3.connectionpool:https://*my-host*:443 "POST /api/2.0/mlflow/runs/create HTTP/1.1" 200 1397
DEBUG:urllib3.connectionpool:https://*my-host*:443 "GET /api/2.0/mlflow/runs/get?run_uuid=*my-run-id*&run_id=*my-run-id* HTTP/1.1" 200 1415
DEBUG:urllib3.connectionpool:https://*my-host*:443 "POST /api/2.0/mlflow/runs/log-batch HTTP/1.1" 200 2
DEBUG:urllib3.connectionpool:https://*my-host*:443 "POST /api/2.0/mlflow-artifacts/mpu/create/8/*my-run-id*/artifacts HTTP/1.1" 200 1987
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.eu-west-1.amazonaws.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.eu-west-1.amazonaws.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.eu-west-1.amazonaws.com:443
DEBUG:urllib3.connectionpool:https://s3.eu-west-1.amazonaws.com:443 "PUT /*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=3&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-ams-signature-3* HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://s3.eu-west-1.amazonaws.com:443 "PUT /*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=2&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-signature* HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://s3.eu-west-1.amazonaws.com:443 "PUT /*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=1&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-ams-signature-2* HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://*my-host*:443 "POST /api/2.0/mlflow-artifacts/mpu/abort/8/*my-run-id*/artifacts HTTP/1.1" 200 2
2024/04/25 13:02:48 WARNING mlflow.store.artifact.http_artifact_repo: Failed to upload file artifact.txt using multipart upload: Failed to upload at least one part of artifact.txt. Errors: {3: 'HTTPError(\'400 Client Error: Bad Request for url: https://s3.eu-west-1.amazonaws.com/*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=3&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-ams-signature-3*. Response text: <?xml version="1.0" encoding="UTF-8"?>\\n<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\'</Message><Region>eu-west-1</Region><RequestId>*my-request-id*</RequestId><HostId>*my-host-id*=</HostId></Error>\')', 2: 'HTTPError(\'400 Client Error: Bad Request for url: https://s3.eu-west-1.amazonaws.com/*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=2&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-signature*. Response text: <?xml version="1.0" encoding="UTF-8"?>\\n<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\'</Message><Region>eu-west-1</Region><RequestId>DZNBF6JE05TKK78V</RequestId><HostId>4F4Cgy1bzEfAsNqfw35eisvIEXmhWemV2tMtrVtQG8uYY3SZP4/8wWmvTM5qVCt0sVdVWqiGdFc=</HostId></Error>\')', 1: 'HTTPError(\'400 Client Error: Bad Request for url: https://s3.eu-west-1.amazonaws.com/*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=1&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-ams-signature-2*. Response text: <?xml version="1.0" encoding="UTF-8"?>\\n<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\'</Message><Region>eu-west-1</Region><RequestId>*my-request-id*</RequestId><HostId>*my-host-id*</HostId></Error>\')'}
DEBUG:urllib3.connectionpool:https://*my-host*:443 "POST /api/2.0/mlflow/runs/update HTTP/1.1" 200 456
Traceback (most recent call last):
  File "/*my-path*/run.py", line 31, in <module>
    mlflow.log_artifact("artifact.txt", "artifact_folder")
  File "/*my-path*/Library/Caches/pypoetry/virtualenvs/mlflow-tracking-test-vApRi4MC-py3.10/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1058, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/*my-path*/Library/Caches/pypoetry/virtualenvs/mlflow-tracking-test-vApRi4MC-py3.10/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1194, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/*my-path*/Library/Caches/pypoetry/virtualenvs/mlflow-tracking-test-vApRi4MC-py3.10/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 560, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/*my-path*/Library/Caches/pypoetry/virtualenvs/mlflow-tracking-test-vApRi4MC-py3.10/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 52, in log_artifact
    self._try_multipart_upload(local_file, artifact_path)
  File "/*my-path*/Library/Caches/pypoetry/virtualenvs/mlflow-tracking-test-vApRi4MC-py3.10/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 209, in _try_multipart_upload
    raise MlflowException(
mlflow.exceptions.MlflowException: Failed to upload at least one part of artifact.txt. Errors: {3: 'HTTPError(\'400 Client Error: Bad Request for url: https://s3.eu-west-1.amazonaws.com/*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=3&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-ams-signature-3*. Response text: <?xml version="1.0" encoding="UTF-8"?>\\n<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\'</Message><Region>eu-west-1</Region><RequestId>*my-request-id*</RequestId><HostId>*my-host-id*=</HostId></Error>\')', 2: 'HTTPError(\'400 Client Error: Bad Request for url: https://s3.eu-west-1.amazonaws.com/*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=2&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-signature*. Response text: <?xml version="1.0" encoding="UTF-8"?>\\n<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\'</Message><Region>eu-west-1</Region><RequestId>*my-request-id*</RequestId><HostId>*my-host-id*</HostId></Error>\')', 1: 'HTTPError(\'400 Client Error: Bad Request for url: https://s3.eu-west-1.amazonaws.com/*my-endpoint*/mlartifacts/8/*my-run-id*/artifacts/artifact.txt?partNumber=1&uploadId=*my-upload-id*-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240425T110246Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=*my-ams-signature-2*. Response text: <?xml version="1.0" encoding="UTF-8"?>\\n<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region \\\'us-east-1\\\' is wrong; expecting \\\'eu-west-1\\\'</Message><Region>eu-west-1</Region><RequestId>*my-request-id*</RequestId><HostId>*my-host-id*</HostId></Error>\')'}
```

### Code to reproduce issue

```
import mlflow


mlflow.set_tracking_uri("REPLACE_THIS_WITH_YOUR_TRACKING_URI")

os.environ['MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD'] = 'True'
os.environ['MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE'] = '2_000_000'
os.environ['MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE'] = '1_000_000'
os.environ['AWS_DEFAULT_REGION'] = 'eu-west-1'
os.environ['AWS_REGION'] = 'eu-west-1'

experiment_id = mlflow.create_experiment(name="mlflow-demo")
with mlflow.start_run(experiment_id=experiment_id) as run:
        mlflow.log_artifact(local_path="artifact.txt", artifact_path="artifact_folder")
```

### Stack trace

```
See `Tracking information` above
```

### Other info / logs

```
[2024-04-25 08:27:08 +0000] [25] [INFO] Starting gunicorn 21.2.0
[2024-04-25 08:27:08 +0000] [25] [INFO] Listening at: http://0.0.0.0:5001 (25)
[2024-04-25 08:27:08 +0000] [25] [INFO] Using worker: sync
[2024-04-25 08:27:08 +0000] [26] [INFO] Booting worker with pid: 26
[2024-04-25 08:27:08 +0000] [27] [INFO] Booting worker with pid: 27
[2024-04-25 08:27:08 +0000] [28] [INFO] Booting worker with pid: 28
[2024-04-25 08:27:08 +0000] [29] [INFO] Booting worker with pid: 29
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
I guess you set the wrong param value ? 

`X-Amz-Credential=*my-ams-credentials*us-east-1%2Fs3%2Faws4_request` it has something relating to `us-east-1`

**Comment by WeichenXu123** [comment]
Is this related ? https://github.com/aws/aws-sdk-ruby/issues/690

**Comment by job-almekinders** [comment]
> https://repost.aws/questions/QUQxB1G_rhQzOr3DbkpjFd4g/error-parsing-the-x-amz-credential-parameter

I think this one is related indeed! 

I also tried setting the environment variables as described in [this stackoverflow post](https://stackoverflow.com/questions/49522014/imagefield-with-django-storages-leads-to-error-parsing-the-x-amz-credential-pa) that is mentioned in the link you provided. For both the client and the server side. However, that also didn't work.

**Comment by WeichenXu123** [comment]
looks like it is AWS boto3 library bug ?
I created a branch for your testing: https://github.com/mlflow/mlflow/compare/master...WeichenXu123:test-region?expand=1

you can install it by : `%pip install git+https://github.com/mlflow/mlflow.git@test-region --foce-reinstall` , it will forcibly set region name to be the value configured by env var `AWS_REGION` @job-almekinders

**Comment by job-almekinders** [comment]
@WeichenXu123 Thank you for your reply! 

> looks like it is AWS boto3 library bug ? 
I think that is indeed a possibility as well.. However, I'm having a hard time pin-pointing how to verify whether it is truely a boto3 bug or a mlflow bug

I just tried to run my application using the changes you suggested. However, it seems like it never reaches that part of the code. When I put a breakpoint at that location in the code, it never stops there..

**Comment by WeichenXu123** [comment]
The code implementation is here:
https://github.com/mlflow/mlflow/blob/e90aa196ca0c80a8eb0efad466ef103a88beb9e4/mlflow/store/artifact/optimized_s3_artifact_repo.py#L174

So the major steps are:

1. Get credential info: https://github.com/mlflow/mlflow/blob/e90aa196ca0c80a8eb0efad466ef103a88beb9e4/mlflow/store/artifact/optimized_s3_artifact_repo.py#L151
2. Creating multipart upload request: https://github.com/mlflow/mlflow/blob/e90aa196ca0c80a8eb0efad466ef103a88beb9e4/mlflow/store/artifact/optimized_s3_artifact_repo.py#L177 (invoking boto3 client API)
3. Generate presinged URL for chunk uploading: https://github.com/mlflow/mlflow/blob/e90aa196ca0c80a8eb0efad466ef103a88beb9e4/mlflow/store/artifact/optimized_s3_artifact_repo.py#L187 (invoking boto3 client API)
4. Uploading chunk data https://github.com/mlflow/mlflow/blob/e90aa196ca0c80a8eb0efad466ef103a88beb9e4/mlflow/store/artifact/optimized_s3_artifact_repo.py#L197 (invoking HTTP restful API)
5. Complete multipart uploading https://github.com/mlflow/mlflow/blob/e90aa196ca0c80a8eb0efad466ef103a88beb9e4/mlflow/store/artifact/optimized_s3_artifact_repo.py#L227 (invoking boto3 client API)

So that I think you can add breakpoint() in above related places, then you can get all arguments of above invocations.
then you can reproduce the bug with pure boto3 client API + Http rest API invocations, without MLFlow.

**Comment by WeichenXu123** [comment]
tips: when adding breakpoint in MLflow server side, you can add one option `--gunicorn-opts "--timeout 3600"` when starting the mlflow server. (otherwise the server worker would be killed after 60s)

**Comment by job-almekinders** [comment]
Thanks a lot for your help @WeichenXu123! 

I managed to solve the issue by setting the `AWS_DEFAULT_REGION` to `eu-west-1` on the MLflow server side. I missed the fact that `boto3` still works with `AWS_DEFAULT_REGION` instead of `AWS_REGION`.
