### ISSUE TITLE
Unable to log prophet model in mlflow gives " 'Prophet' object has no attribute 'y_min'" [BUG]

### ISSUE THREAD

**Issue by AsheeshJandaDS** [mlflow/mlflow#11824]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

I have tried logging prophet model into mlflow using the [documentation](https://mlflow.org/docs/latest/python_api/mlflow.prophet.html?highlight=mlflow%20prophet#module-mlflow.prophet), I used log model my code looks like this 
```
mlflow.prophet.log_model(model,
                              'model',
                              signature=signature)

```

However I get 'Prophet' object has no attribute 'y_min', I then tried 

```
class ProphetWrapper:
    def __init__(self, model):
        self.model = model
        self.y_min = None  # Add this attribute
        self.history = None  # Add this attribute
        self.params = None  # Add this attribute
        self.uncertainty_samples = None 

    def predict(self, X):
        return self.model.predict(X)

    def save(self, path):
        self.model.save(path)

    def load(self, path):
        self.model = Prophet.load(path)
wrapped_model = ProphetWrapper(model)
  model_details = mlflow.prophet.log_model(wrapped_model,
                              'model',
                              signature=signature)

```

But got "ValueError: This can only be used to serialize models that have already been fit", Can someone help what's going wrong, It appears unlikely that mlflow doesn't support a library like "Prophet" since it's been around for sometime, perhaps I am missing something?, Appreciate any support on this. 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Hello, 
could you try saving your prophet model without MLFlow, i.e.:

```
from prophet.serialize import model_to_json

model_ser = model_to_json(your_prophet_model)
```
if it raises the same exception, then you can report the issue to prophet project.

**Comment by WeichenXu123** [comment]
I think Prophet model can only be saved after `fit` is invoked.

**Comment by WeichenXu123** [comment]
If you want to save a prophet model haven't been called `fit`, you can use `cloudpickle.dump(model, file)`

**Comment by WeichenXu123** [comment]
I think above comments should answer your question and provide solutions. I will close it. feel free to reopen it if you have follow-up questions.
