### ISSUE TITLE
Hello, I encountered an issue while attempting to run the official MLflow image. Can anyone assist me with this? I'm a beginner. Thanks

### ISSUE THREAD

**Issue by maramoueslati** [mlflow/mlflow#11950]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.12.1

### System information

j

### Describe the problem

tracker_mlflow         |     return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
tracker_mlflow         |   File "<string>", line 2, in create_engine
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
tracker_mlflow         |     return fn(*args, **kwargs)  # type: ignore[no-any-return]
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
tracker_mlflow         |     dbapi = dbapi_meth(**dbapi_args)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 75, in import_dbapi
tracker_mlflow         |     return __import__("pymysql")
tracker_mlflow         | ModuleNotFoundError: No module named 'pymysql'
tracker_mlflow         | 2024/05/08 23:43:17 ERROR mlflow.cli: Error initializing backend store
tracker_mlflow         | 2024/05/08 23:43:17 ERROR mlflow.cli: No module named 'pymysql'
tracker_mlflow         | Traceback (most recent call last):
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 425, in server
tracker_mlflow         |     initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 306, in initialize_backend_stores
tracker_mlflow         |     _get_tracking_store(backend_store_uri, default_artifact_root)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 283, in _get_tracking_store
tracker_mlflow         |     _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 42, in get_store
tracker_mlflow         |     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 52, in _get_store_with_resolved_uri
tracker_mlflow         |     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 137, in _get_sqlalchemy_store
tracker_mlflow         |     return SqlAlchemyStore(store_uri, artifact_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 151, in __init__
tracker_mlflow         |     ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 230, in create_sqlalchemy_engine_with_retry
tracker_mlflow         |     engine = create_sqlalchemy_engine(db_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 286, in create_sqlalchemy_engine
tracker_mlflow         |     return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
tracker_mlflow         |   File "<string>", line 2, in create_engine
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
tracker_mlflow         |     return fn(*args, **kwargs)  # type: ignore[no-any-return]
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
tracker_mlflow         |     dbapi = dbapi_meth(**dbapi_args)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 75, in import_dbapi
tracker_mlflow         |     return __import__("pymysql")
tracker_mlflow         | ModuleNotFoundError: No module named 'pymysql'
tracker_mlflow         | 2024/05/08 23:44:19 ERROR mlflow.cli: Error initializing backend store
tracker_mlflow         | 2024/05/08 23:44:19 ERROR mlflow.cli: No module named 'pymysql'
tracker_mlflow         | Traceback (most recent call last):
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/cli.py", line 425, in server
tracker_mlflow         |     initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 306, in initialize_backend_stores
tracker_mlflow         |     _get_tracking_store(backend_store_uri, default_artifact_root)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 283, in _get_tracking_store
tracker_mlflow         |     _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 42, in get_store
tracker_mlflow         |     return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 52, in _get_store_with_resolved_uri
tracker_mlflow         |     return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/server/handlers.py", line 137, in _get_sqlalchemy_store
tracker_mlflow         |     return SqlAlchemyStore(store_uri, artifact_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 151, in __init__
tracker_mlflow         |     ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 230, in create_sqlalchemy_engine_with_retry
tracker_mlflow         |     engine = create_sqlalchemy_engine(db_uri)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/mlflow/store/db/utils.py", line 286, in create_sqlalchemy_engine
tracker_mlflow         |     return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
tracker_mlflow         |   File "<string>", line 2, in create_engine
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
tracker_mlflow         |     return fn(*args, **kwargs)  # type: ignore[no-any-return]
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
tracker_mlflow         |     dbapi = dbapi_meth(**dbapi_args)
tracker_mlflow         |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 75, in import_dbapi
tracker_mlflow         |     return __import__("pymysql")
tracker_mlflow         | ModuleNotFoundError: No module named 'pymysql'

### Tracking information

```shell
REPLACE_MEe
```

### Code to reproduce issue

```
REPLACE_MEe
```

### Stack trace

```
REPLACE_ME
```j


### Other info / logs

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```
REPLACE_ME
```


### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@maramoueslati can you give us code/command that can reproduce the issue?

**Comment by maramoueslati** [comment]
Good morning , when i tried to run this image "ghcr.io/mlflow/mlflow:v2.12.1"
i got that error message and also when i tried to use it in a
docker-compose file

**Comment by maramoueslati** [comment]
Good morning , when i tried to run this image "ghcr.io/mlflow/mlflow:v2.12.1"
i got that error message and also when i tried to use it in a
docker-compose file

Le jeu. 9 mai 2024 à 08:21, Harutaka Kawamura ***@***.***> a
écrit :

**Comment by cgilviadee** [comment]
I ran into the same issue. The official image seems to be missing the python mysql driver. 
You can build the image yourself.
Your Dockerfile would look something like this.
```
FROM ghcr.io/mlflow/mlflow:v2.12.1
RUN pip install pymysql
```

Hopefully they fix it upstream with the next release.

**Comment by harupy** [comment]
@maramoueslati can you try what @cgilviadee suggested? I think it should work.
