### ISSUE TITLE
SqlAlchemyStore is created on every request

### ISSUE THREAD

**Issue by ashtuchkin** [mlflow/mlflow#1197]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**:  binary
- **MLflow version (run ``mlflow --version``)**: 0.9.1
- **Python version**: 2.7
- **npm version (if running the dev UI):
- **Exact command to reproduce**: `mlflow server --backend-store-uri mysql://user:password@localhost:3306`

### Describe the problem
When we switched to mysql, web UI became really slow. REST API requests started to take 2+ seconds. Looking at the code here:
https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L35
it looks like we're creating a new SqlAlchemyStore on every request and not saving it to a global `_store`, like we do with the FileStore. On my machine every new SqlAlchemyStore takes 1.8 seconds, which I think is the reason for the slowdown.

**Comment by smurching** [comment]
Hi @ashtuchkin, thanks for the catch. It's definitely not the intended behavior to create a new SQLAlchemyStore on each request in the OSS server - would be happy to review & merge a PR that fixes this (basically just replace https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L35 with `_store = SqlAlchemyStore(store_dir, artifact_root)`)

**Comment by ashtuchkin** [comment]
Thanks @smurching!
