### ISSUE TITLE
Error: No such command "sklearn" for mlflow CLI

### ISSUE THREAD

**Issue by Kublai-Jing** [mlflow/mlflow#1198]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra
- **MLflow installed from (source or binary)**:  pip install mlflow
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.9.1
- **Python version**: Python 3.7.3
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
`cd mlflow/mlflow/examples`
`python sklearn_logistic_regression/train.py`
`mlflow sklearn serve -r f27a5f9a9a5d4f35a8787bf50289f4f3-m model`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

I am following the https://github.com/mlflow/mlflow#saving-and-serving-models section to try to serve a single model. It turns out there is no sklearn command for mlflow CLI: The output of `mlflow --help`:

```
Usage: mlflow [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  artifacts    Upload, list, and download artifacts from an MLflow artifact...
  azureml      Serve models on Azure ML.
  download     Download the artifact at the specified DBFS or S3 URI into...
  experiments  Manage experiments.
  pyfunc       Serve Python models locally.
  rfunc        Serve R models locally.
  run          Run an MLflow project from the given URI.
  runs         Manage runs.
  sagemaker    Serve models on SageMaker.
  server       Run the MLflow tracking server.
  ui           Launch the MLflow tracking UI.

```

**Comment by lp-noel** [comment]
@Kublai-Jing I'm getting the same issue. How did you fix it?

**Comment by vinod-b-yond** [comment]
This occurs on M1 chip with python3.8. The output of `mlflow` command is as follows:

```
Usage: mlflow [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  artifacts    Upload, list, and download artifacts from an MLflow...
  db           Commands for managing an MLflow tracking database.
  deployments  Deploy MLflow models to custom targets.
  experiments  Manage experiments.
  gc           Permanently delete runs in the `deleted` lifecycle stage.
  run          Run an MLflow project from the given URI.
  runs         Manage runs.
  server       Run the MLflow tracking server.
  ui           Launch the MLflow tracking UI for local viewing of run...
```

As we see here, `mlflow models` is not available here. @Kublai-Jing any idea here?
