### ISSUE TITLE
Documentation is unclear about the relationship between experiments and runs

### ISSUE THREAD

**Issue by maltzj** [mlflow/mlflow#1205]
### System information
N/A

### Describe the problem
I was recently investigating MLFlow Tracking and found that there is a mismatch between how the documentation describes the entities in MLFlow Tracking and how the code models those entities.

In the documentation, it states `MLflow Tracking is organized around the concept of runs`, and further on `You can optionally organize runs into experiments`.  From this, I would expect that I can create a run without an experiment id.  However, when I looked into the API and client libraries, I found that any call to `create_run` had to be accompanied by an `experiment_id`.  

This was surprising, and feels (at least to me) like it reflects a mismatch between the model expressed by the documentation and the one expressed by the code.  Are there plans to rectify this mismatch, or should the documentation be updated?

### Source code / logs
N/A

**Comment by AveshCSingh** [comment]
I came across this issue while sorting through old issues. Sorry for the very late response, @maltzj. You can use the start_run function, which does not require an experiment_id.
https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run
