### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ykisi** [mlflow/mlflow#12063]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

mlflow-skinny==2.9.2

### System information

pyspark==3.5.0

### Describe the problem

**When running the model I have encountered this problem:**
_"Model passed for registration did not contain any signature metadata. All models in the Unity Catalog must be logged with a model signature containing both input and output type specifications. See https://mlflow.org/docs/latest/models.html#model-signature for details on how to log a model with a signature"_

backround:
1. the code has been running for 3 weeks but this issues started 2 days ago
2. We use Data Bricks and this issues happens in production environment when running the script but does not happen when I run the code in under my data bricks user name.
3. From my understanding - signature is not mandatory, no?

### Code to reproduce issue

```
assembler = VectorAssembler(
            inputCols=self.feature_columns,
            outputCol='features',
            handleInvalid="keep"
        )

        xgb = SparkXGBClassifier(**CommonVariables.default_spark_xgb_classifier_params, **params)

        pipeline = ml_Pipeline(stages=[assembler, xgb])

        experiment = mlflow.set_experiment(f'{data_catalog.mlflow_workspace_id}/algo_{self.ALGORITHM_ID}_experiment')
        print("experiment name:", experiment.name)
        with mlflow.start_run(run_name=f'{self.date}_{self.hour}'):
            # Fit the pipeline to the training data
            model = pipeline.fit(train_df)
            mlflow.log_params(params)
            predictions = model.transform(test_df)
            mlflow.spark.log_model(
                model, f'algo_{self.ALGORITHM_ID}', registered_model_name=f'algo_{self.ALGORITHM_ID}')```


### Stack trace

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```
REPLACE_ME
```


### Other info / logs

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```
RuntimeError: Pipeline `variant_X` failed with exception: Model passed for registration did not contain any signature metadata. All models in the Unity Catalog must be logged with a model signature containing both input and output type specifications. See https://mlflow.org/docs/latest/models.html#model-signature for details on how to log a model with a signature
```


### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@Ykisi I believe signature is mandatory if you use uc registry with `mlflow.set_registry_uri("databricks-uc")`, it's been there for a while, not a new thing. Could you either set the signature, or if you really don't want to set it then use `mlflow.set_registry_uri("databricks")` to register it as a workspace model.

**Comment by Ykisi** [comment]
thank you for the answer! Indeed I have discovered that we switched to UC and that what causes the issue.
