### ISSUE TITLE
Calling pyflow.pyfunc.log_model alone doesn't create a run

### ISSUE THREAD

**Issue by frederickaczynski** [mlflow/mlflow#1209]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**:  binary
- **MLflow version (run ``mlflow --version``)**: `mlflow, version 0.9.0`
- **Exact command to reproduce**:

Have this in a file called `train.py`:

```python
import mlflow.pyfunc

mlflow.pyfunc.log_model(
    "model"
)
```

Execute `python train.py`, it will yield an error (reported below).

### Describe the problem
It seems MLflow doesn't create a run when only calling `mlflow.pyfunc.log_model` inside a run. If I add a call like `mlflow.log_metric("test", 4")` before the call to `log_model`, it will work correctly.

### Source code / logs
The error when running `python train.py`:

```
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    "model"
  File "/usr/local/lib/python3.6/dist-packages/mlflow/pyfunc/__init__.py", line 608, in log_model
    run_id = active_run().info.run_uuid
AttributeError: 'NoneType' object has no attribute 'info'
```

**Comment by ankitmathur-db** [comment]
Addressed in PR #1514 - thanks for reporting! Closing out this issue.
