### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by elisevansbbfc** [mlflow/mlflow#12135]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.13.0

### System information

- OS Platform and Distribution: Windows 11 Pro 23H2
- Python version: 3.11.9

### Describe the problem

I am trying to use the Prompt Engineering UI, following the instructions [here](https://mlflow.org/docs/latest/llms/prompt-engineering/index.html)

But when running `mlflow deployments start-server --config-path config.yaml` in Command Prompt I get the error `ModuleNotFoundError: No module named 'fcntl'`

I do NOT get this error when running `mlflow ui` as is the case [here](https://github.com/mlflow/mlflow/issues/1611)

### Code to reproduce issue

```
mlflow deployments start-server --config-path config.yaml
```

### Stack trace

```
C:\Users\USERNAME\AppData\Local\pypoetry\Cache\virtualenvs\atp-mlflow-Xsm6hfnp-py3.11\Lib\site-packages\pydantic\_internal\_config.py:334: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USERNAME\AppData\Local\pypoetry\Cache\virtualenvs\atp-mlflow-Xsm6hfnp-py3.11\Lib\site-packages\gunicorn\__main__.py", line 6, in <module>
    from gunicorn.app.wsgiapp import run
  File "C:\Users\USERNAME\AppData\Local\pypoetry\Cache\virtualenvs\atp-mlflow-Xsm6hfnp-py3.11\Lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "C:\Users\USERNAME\AppData\Local\pypoetry\Cache\virtualenvs\atp-mlflow-Xsm6hfnp-py3.11\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "C:\Users\USERNAME\AppData\Local\pypoetry\Cache\virtualenvs\atp-mlflow-Xsm6hfnp-py3.11\Lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
Unfortunately, mlflow deployments is not supported on windows yet (it uses `gunicorn` as a server). The team is aware of this and there are plans to enable `waitress` as a serving option in windows, but as of now we aren't prioritizing the feature.
