### ISSUE TITLE
[BUG] module 'PIL' has no attribute 'Image' when performing mlflow.log_image

### ISSUE THREAD

**Issue by cnguyen10** [mlflow/mlflow#12150]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.13.0
- Tracking server: 2.13.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04
- **Python version**: 3.10
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When performing `mlflow.log_image` to log a jax.numpy.ndarray (where each element is in [0, 1]), it popped up an error:

> AttributeError: module 'PIL' has no attribute 'Image'

Eventually, `mlflow.log_image` only accepts `numpy.ndarray`, `PIL.Image` or `mlflow.Image`. Nevertheless, the import statement at line 2280 in `mlflow/tracking/client.py` is the cause of the issue. It should be:

```python
from PIL import Image
```
or
```python
import PIL.Image
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
import jax
import mlflow

key = jax.random.key(seed=0)
x = jax.random.uniform(key=key, shape=(32, 32, 3))

with mlflow.start_run():
    mlflow.log_image(image=x, key='test_image', step=0)
```

### Stack trace

```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/user/HS300/cn0025/jax/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1357, in log_image
    MlflowClient().log_image(run_id, image, artifact_file, key, step, timestamp, synchronous)
  File "/user/HS300/cn0025/jax/lib/python3.10/site-packages/mlflow/tracking/client.py", line 2282, in log_image
    if not isinstance(image, PIL.Image.Image):
AttributeError: module 'PIL' has no attribute 'Image'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
Thank you for the report! I'll follow up with a fix
