### ISSUE TITLE
Operation not permissed

### ISSUE THREAD

**Issue by vchauha6** [mlflow/mlflow#1215]
This is how my mlflow is running; artifact is the mapped drive in the Linux machine. user has full blown up rights in the artifact folder.

 sudo mlflow server  --file-store /zz/yy/artifacts  --default-artifact-root /zz/yy/artifacts  --host a12456 -p 8888.

> when user try to write the artifact, it completes the operation of writing but gives a permission error:[Error1] Opertion not permitted.
> Error seems to be popping up in the function,  chmod_fun(dat, stat.s_IMODE(st.st_mode))

when user writes it in his own local directory error goes away but mlfow not able to access the artifact, It seems like permission issue, but as a Linux admin, we can't provide everysingle user chmod permissions.

**Comment by vchauha6** [comment]
bot you need to get tech people answer the question

**Comment by abawchen** [comment]
@vchauha6 : Did you find the solution? I have the same issue. Thanks.
