### ISSUE TITLE
will legacy_databricks_cli submodule be deprecated?

### ISSUE THREAD

**Issue by Willem-J-an** [mlflow/mlflow#12187]
### Summary

Will the legacy_databricks_cli submodule be deprecated eventually or is it okay to build code that relies on this "legacy" part?

**Comment by WeichenXu123** [comment]
Hi @Willem-J-an 

our long-term goal is to fully migrate to use "databricks-sdk" python library.

**Comment by Willem-J-an** [comment]
Currently I'm able to use the set_config_provider to inject my

**Comment by WeichenXu123** [comment]
> I'm able to use the set_config_provider to inject my own DatabricksConfigProvider that uses my endpoint and azure.identity credential to authenticate to mlflow on databricks

Got it , but I think you can set environmental variables directory, you can set either `DATABRICKS_HOST + DATABRICKS_TOKEN` or `DATABRICKS_HOST + DATABRICKS_CLIENT_ID + DATABRICKS_CLIENT_SECRET` environmental variables instead

**Comment by Willem-J-an** [comment]
> > I'm able to use the set_config_provider to inject my own DatabricksConfigProvider that uses my endpoint and azure.identity credential to authenticate to mlflow on databricks
> 
> Got it , but I think you can set environmental variables instead of setting DatabricksConfigProvider, (DatabricksConfigProvider is internal API which we does not expose it to user), you can set either `DATABRICKS_HOST + DATABRICKS_TOKEN` or `DATABRICKS_HOST + DATABRICKS_CLIENT_ID + DATABRICKS_CLIENT_SECRET` environmental variables instead

@WeichenXu123 I can access these classes and functions and there's no private module or class indicating that it's internal API. Good to know I can fallback on the environment variables if it will be needed.

**Comment by Willem-J-an** [comment]
Hi @WeichenXu123, 
Trying to bump to 2.16 version.
I'm trying to use the DATABRICKS_HOST + DATABRICKS_CLIENT_ID + DATABRICKS_CLIENT_SECRET route as suggested, but it appears all is not as it seems. These environment variables seem to lead me down the oauth-m2m route and then fails, where I wanted to go down the azure-client-secret route. To use it I would need to create a Databricks specific secret in Databricks, instead of using the Azure secret. I tried to use the Azure secret following the Databricks SDK way of working:

I can successfully configure the environment variables for the WorkspaceClient like:
```py
    os.environ["DATABRICKS_HOST"] = ...
    os.environ["ARM_CLIENT_ID"] = ...
    os.environ["ARM_CLIENT_SECRET"] = ...
    os.environ["ARM_TENANT_ID"] = ...
```
I then have a valid WorkspaceClient from mlflow.utils.databricks_utils::626, however, line 637 tries to build the DatabricksConfig, and neglects to use my valid WorkspaceClient, None of the providers in _get_databricks_creds_config function returns a valid DatabricksConfig.

I guess I can create a custom `_dynamic_token_config_provider`, but it is not a sustainable solution. I can also try to contribute a provider but as those all seem to be legacy, not sure if it makes sense either.

Any ideas?
Thanks!

**Comment by youldb** [comment]
I'm also facing the same challenge. 
Using the env variables DATABRICKS_HOST, DATABRICKS_CLIENT_ID and  DATABRICKS_CLIENT_SECRET work with a databricks service principal but not with an Azure Service Principal which required the env variables (ARM_xxx). 

Any ideas ?
