### ISSUE TITLE
[BUG] unity catalog 

### ISSUE THREAD

**Issue by Willem-J-an** [mlflow/mlflow#12217]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.13.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.10

### Describe the problem

Databricks uc backend search_model_versions by run_id does not work.

### Tracking information

DATABRICKS UC

### Code to reproduce issue

```
import mlflow
from mlflow import MlflowClient
from mlflow.legacy_databricks_cli.configure.provider import set_config_provider
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

from rmg_lakehouse.session import MlFlowConfigProvider

mlflow.set_tracking_uri("databricks")
mlflow.set_registry_uri("databricks-uc")
mlflow.set_experiment("/experiments/test-experiment")
X, y = load_iris(return_X_y=True)
model = LogisticRegression().fit(X, y)
with mlflow.start_run():
    model_info = mlflow.sklearn.log_model(model, "model")

client = MlflowClient()
model_versions = client.search_model_versions(f"run_id='{model_info.run_id}'")
```

### Stack trace

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/noortw01/.conda/envs/rmg-lakehouse/lib/python3.10/site-packages/mlflow/tracking/client.py", line 4190, in search_model_versions
    return self._get_registry_client().search_model_versions(
  File "/home/noortw01/.conda/envs/rmg-lakehouse/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 347, in search_model_versions
    return self.store.search_model_versions(filter_string, max_results, order_by, page_token)
  File "/home/noortw01/.conda/envs/rmg-lakehouse/lib/python3.10/site-packages/mlflow/store/_unity_catalog/registry/rest_store.py", line 904, in search_model_versions
    response_proto = self._call_endpoint(SearchModelVersionsRequest, req_body)
  File "/home/noortw01/.conda/envs/rmg-lakehouse/lib/python3.10/site-packages/mlflow/store/model_registry/base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
  File "/home/noortw01/.conda/envs/rmg-lakehouse/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 304, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/noortw01/.conda/envs/rmg-lakehouse/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 174, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Unsupported filter query : `run_id='23bfb54b487445d19ebc5a07b717bf2b'`. Please specify your filter parameter in the format `name = 'model_name'`.
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
I think databricks-uc backend hasn't supported search_model_versions by run_id,
I pinged our UC team about this issue.

**Comment by Willem-J-an** [comment]
Thought so. I need the version so I can put an alias on it. I can get versions by name and take the last one but seems more deterministic to actually get the model produced by this run_id. Not sure if it's feasible to add the version to the ModelInfo returned from log_model function?

**Comment by smurching** [comment]
@Willem-J-an thanks for flagging this - support for complex searches in UC is a bit further out, but it should definitely be easier to get the version number of a newly-registered model version when calling `log_model`, @WeichenXu123 I wonder if we could return it as part of the [ModelInfo](https://mlflow.org/docs/latest/python_api/mlflow.sklearn.html?highlight=log_model#mlflow.sklearn.log_model) returned by log_model? If the interface change seems sensible I'm happy to review a PR to add this

**Comment by WeichenXu123** [comment]
> @Willem-J-an thanks for flagging this - support for complex searches in UC is a bit further out, but it should definitely be easier to get the version number of a newly-registered model version when calling `log_model`, @WeichenXu123 I wonder if we could return it as part of the [ModelInfo](https://mlflow.org/docs/latest/python_api/mlflow.sklearn.html?highlight=log_model#mlflow.sklearn.log_model) returned by `log_model`? If the interface change seems sensible and won't break things/abstractions elsewhere I'm happy to review a PR to add this

Sounds good to me!
