### ISSUE TITLE
[BUG] set_experiment race

### ISSUE THREAD

**Issue by nkarpov** [mlflow/mlflow#12259]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.13.0
- Tracking server: 2.13.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac
- **Python version**: 3.11.13
- **yarn version, if running the dev UI**:

### Describe the problem

Experienced this when having >1 web app workers call `set_experiment` in a Heroku environment (they are logging traces) with `databricks` tracking server. Confirmed this also happens locally,

```
import mlflow

import concurrent.futures

def set_exp():
    mlflow.set_experiment("my_exp_race")

def run_in_parallel():
    with concurrent.futures.ThreadPoolExecutor() as executor:
        futures = [executor.submit(my_function) for _ in range(2)]
        concurrent.futures.wait(futures)
```

```
2024/06/05 08:18:03 INFO mlflow.tracking.fluent: Experiment with name 'my_exp_race' does not exist. Creating a new experiment.
2024/06/05 08:18:03 INFO mlflow.tracking.fluent: Experiment with name 'my_exp_race' does not exist. Creating a new experiment.
```
Results in two experiments being created with the same name.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
MLflow version: 2.13.0
Tracking URI: .../mlruns
Artifact URI: .../mlruns/620992874949554164/e3adfb31ec5c443cbdf3113b1b4344c7/artifacts
System information: Darwin Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
Python version: 3.11.3
MLflow version: 2.13.0
MLflow module location: /opt/homebrew/anaconda3/lib/python3.11/site-packages/mlflow/__init__.py
Tracking URI: .../mlruns
Registry URI: .../mlruns
Active experiment ID: 620992874949554164
Active run ID: e3adfb31ec5c443cbdf3113b1b4344c7
Active run artifact URI: .../mlruns/620992874949554164/e3adfb31ec5c443cbdf3113b1b4344c7/artifacts
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.2
  aiohttp: 3.9.5
  alembic: 1.4.1
  botocore: 1.29.76
  cachetools: 5.3.3
  click: 8.1.7
  cloudpickle: 2.2.1
  docker: 7.1.0
  entrypoints: 0.4
  fastapi: 0.111.0
  gitpython: 3.1.40
  graphene: 3.3
  gunicorn: 22.0.0
  importlib-metadata: 6.0.0
  markdown: 3.4.1
  matplotlib: 3.7.1
  numpy: 1.26.4
  opentelemetry-api: 1.25.0
  opentelemetry-sdk: 1.25.0
  packaging: 23.0
  pandas: 1.5.3
  prometheus-flask-exporter: 0.23.0
  protobuf: 4.24.3
  pyarrow: 11.0.0
  pydantic: 2.7.1
  pytz: 2022.7
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.2.2
  scipy: 1.10.1
  sqlalchemy: 2.0.23
  sqlparse: 0.4.4
  tiktoken: 0.5.1
  uvicorn: 0.29.0
  watchfiles: 0.21.0```


### Stack trace

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```
2024/06/05 08:18:03 INFO mlflow.tracking.fluent: Experiment with name 'my_exp_race' does not exist. Creating a new experiment.
2024/06/05 08:18:03 INFO mlflow.tracking.fluent: Experiment with name 'my_exp_race' does not exist. Creating a new experiment.
```


### Other info / logs

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```
2024/06/05 08:18:03 INFO mlflow.tracking.fluent: Experiment with name 'my_exp_race' does not exist. Creating a new experiment.
2024/06/05 08:18:03 INFO mlflow.tracking.fluent: Experiment with name 'my_exp_race' does not exist. Creating a new experiment.
```


### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@nkarpov Thank you for reporting the issue!

Yes, the `mlflow.set_experiment()` API with experiment name parameter is not thread-safe. This is because it searches for an experiment ID with the given name and then create it if doesn't exist. We're currently evaluating a plan to make the API thread-safe.

In the meantime, here are two potential workarounds to help you overcome this limitation:

**Option 1: Use lock object.**
```
from threading import Lock

exp_lock = Lock()

with exp_lock.acquire():
    mlflow.set_experiment("my_exp_rase")
```

**Option 2: Use `create_experiment` client API** (only applicable if you are using SQL backend)
If you are using SQL-Alchemy backend, `mlflow.MlflowClient().create_experiment(name)` offers thread safety. Experiment creation is executed as a single transaction, so the latter request will raise `MlflowException` "experiment already exists". Unfortunately, for file-based backend, experiment creation is not atomic and still suffers from a race condition without explicit locking.
```
try:
   client.create_experiment(name)
except MlflowException:
   exp = client.get_experiment_by_name(name)
   mlflow.set_experiment(experiment_id = exp.experiment_id)
```

These workarounds are not ideal, but they should help you unblock your situation. We appreciate your patience and understanding.

**Comment by nkarpov** [comment]
The first workaround won't work unfortunately since we have several independent processes, but the second workaround is 👌 Thank you @B-Step62 - appreciate your kind and thorough response!
