### ISSUE TITLE
[BUG] mlflow.evaluate fails with KeyError given DataFrame type input and index not containing 1..5 values

### ISSUE THREAD

**Issue by julcsii** [mlflow/mlflow#12269]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.13.0
- Tracking server: 2.13.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  
    - Distributor ID:	Ubuntu
    - Description:	Ubuntu 22.04.4 LTS
    - Release:	22.04
- **Python version**: Python 3.10.14
- **yarn version, if running the dev UI**: -

### Describe the problem

The `mlflow.evaluate()` method fails when we evaluate using a DataFrame that has a float type index.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler


target_name = "target"
test_size = 0.2
random_state = 42

experiment_name = "bug_example"
model_type = "classifier"

input_data = load_wine(as_frame=True).frame
input_data = input_data.set_index("malic_acid") # Set a float as index that causes the error

X = input_data.copy()
y = X.pop(target_name)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=test_size,
    random_state=random_state,
    stratify=y
)

# Create ML pipeline
pipeline = make_pipeline(
    StandardScaler(),
    RandomForestClassifier(random_state=random_state, n_jobs=-1)
)

mlflow.set_experiment(experiment_name)

# Train & evaluate
with mlflow.start_run() as run:
    fitted_pipeline = pipeline.fit(X_train, y_train)
    mlflow.sklearn.log_model(fitted_pipeline, "model")
    model_path = mlflow.get_artifact_uri(artifact_path="model")
    # This step fails
    mlflow.evaluate(
        model=model_path,
        data=input_data,
        targets=target_name,
        model_type=model_type,
    )
```

### Stack trace

```
/lib/python3.10/site-packages/mlflow/models/evaluation/base.py:553: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  head_rows = data[: EvaluationDataset.NUM_SAMPLE_ROWS_FOR_HASH]
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 219, in pandas._libs.index.IndexEngine._get_loc_duplicates
  File "index.pyx", line 227, in pandas._libs.index.IndexEngine._maybe_get_bool_indexer
  File "index.pyx", line 119, in pandas._libs.index._unpack_bool_indexer
KeyError: 5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./test_example.py", line 44, in <module>
    mlflow.evaluate(
  File "/lib/python3.10/site-packages/mlflow/models/evaluation/base.py", line 2084, in evaluate
    dataset = data.to_evaluation_dataset(dataset_path, feature_names)
  File "/lib/python3.10/site-packages/mlflow/data/pandas_dataset.py", line 155, in to_evaluation_dataset
    return EvaluationDataset(
  File "/lib/python3.10/site-packages/mlflow/models/evaluation/base.py", line 734, in __init__
    _gen_md5_for_arraylike_obj(md5_gen, self._features_data)
  File "/lib/python3.10/site-packages/mlflow/models/evaluation/base.py", line 553, in _gen_md5_for_arraylike_obj
    head_rows = data[: EvaluationDataset.NUM_SAMPLE_ROWS_FOR_HASH]
  File "/lib/python3.10/site-packages/pandas/core/frame.py", line 3876, in __getitem__
    return self._getitem_slice(key)
  File "/lib/python3.10/site-packages/pandas/core/generic.py", line 4284, in _getitem_slice
    slobj = self.index._convert_slice_indexer(key, kind="getitem")
  File "/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 4238, in _convert_slice_indexer
    return self.slice_indexer(start, stop, step)
  File "/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6602, in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step)
  File "/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6825, in slice_locs
    end_slice = self.get_slice_bound(end, "right")
  File "/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6744, in get_slice_bound
    raise err
  File "/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6738, in get_slice_bound
    slc = self.get_loc(label)
  File "/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 5
```

### Other info / logs

Pandas lazy slicing example with float index.
```
import pandas as pd
import numpy as np
float_indices = np.random.uniform(low=0.5, high=13.3, size=(8,))
df = pd.DataFrame(np.random.randn(8, 4),
                  index=float_indices, columns=['A', 'B', 'C', 'D'])
df.iloc[:5]
# df[:5]
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
Thank you for reporting the issue, @julcsii !!

I could reproduce the issue, and it seems the error happens when getting first 5 rows for computing dataset digest [here](https://github.com/mlflow/mlflow/blob/3d9d67f596e03e868d79d6a27b48cec4882839da/mlflow/models/evaluation/base.py#L579). If the dataset is a Pandas DataFrame with float index, this index-based slicing doesn't work. Updating this line should resolve this particular error (there may be another place that assumes integer index in downstream tho).

```
    else:
        head_rows = data[: EvaluationDataset.NUM_SAMPLE_ROWS_FOR_HASH]
        tail_rows = data[-EvaluationDataset.NUM_SAMPLE_ROWS_FOR_HASH :
```

I see you've marked that you're willing to contribute - Once you've completed your fix, please submit a PR and we'll be happy to review it. If you need any guidance during the contribution process, please don't hesitate to reach out to us😊
