### ISSUE TITLE
[BUG] 404 Not Found pop ups in UI

### ISSUE THREAD

**Issue by paramazo** [mlflow/mlflow#12273]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.13.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 11
- **Python version**: 3.9

### Describe the problem

After upgrade mlflow from 2.4.1 to 2.13.2, i got several error message notification pop ups on accessing the web interface of my mlflow.

"404 Not Found Not Found The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

### Steps to reproduce the bug

Update mlflow and check the webinterface (`sudo -H pip install mlflow --upgrade`)

**Comment by B-Step62** [comment]
Hi @paramazo. Let us confirm the exact steps you went through - did you run `sudo -H pip install mlflow --upgrade` while keep running the server?

**Comment by B-Step62** [comment]
@paramazo Thanks for the confirmation! It is generally not possible to upgrade library version for a running process.
