### ISSUE TITLE
[BUG]Registered model name with trailing space may not be handled correctly

### ISSUE THREAD

**Issue by yukimori** [mlflow/mlflow#12321]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.12.2
- Tracking server: 2.12.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RockyLinux9
- **Python version**: 3.9
- **yarn version, if running the dev UI**:

### Describe the problem

We can register model name with trailing space to MLflow server.
In this case, I registered model name as "test_autolog_registered_model_with_space " which has trailing space.
This name has trainling space and I can view this registerd model with Web UI at `'http://<mlflow tracking server>/#/models/test_autolog_registered_model_with_space%20'` .
![image](https://github.com/mlflow/mlflow/assets/1590363/9786aabe-2521-46cf-ab97-305337398903)

If I specify the model name with trailing spaces removed such as `'http://<mlflow tracking server>/#/models/test_autolog_registered_model_with_space'`, I can access Web UI without any error.
![image](https://github.com/mlflow/mlflow/assets/1590363/163d5655-2f43-4378-999f-a806ccb1b262)

Originally, if I specify a model name that does not exist, I should get 404 not found page like below.
![image](https://github.com/mlflow/mlflow/assets/1590363/6add23fb-8122-48d8-8f5c-e19ae674fb06)
(I access `http://<mlflow tracking server>/#/models/no_registered_name`. I don't register model has name`no_registered_name`. )

I debugged it using the browser's functionality.
I noticed that when I accessed 'http://<mlflow tracking server>/#/models/test_autolog_registered_model_with_space' which mean without trailing space, the models API returns information of `test_autolog_registered_model_with_space ` (with trailing space).

![image](https://github.com/mlflow/mlflow/assets/1590363/c8f2085d-62fd-46dc-a633-42b1742ba53f)

The original behavior is Search API return https status 404 when a non-existent model name is specified.
![image](https://github.com/mlflow/mlflow/assets/1590363/1bfdabeb-11f1-476f-8385-051e799acae0)

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

If you use MySQL as database, you can reproduce the issue the following code.
I have already registered a model with the name "test_autolog_registered_model_with_space " (including a space at the end).

```
import mlflow
from mlflow import MlflowClient
MODEL_NAME_WITH_TRAILING_SPACE = "test_autolog_registered_model_with_space "
MODEL_NAME_WITHOUT_TRAILING_SPACE = "test_autolog_registered_model_with_space"
MODEL_NAME_NO_EXIST = "xxxx_no_exits_model_yyy"

client = MlflowClient()

print("=== with trailing space ===")
registered_model = client.get_registered_model(MODEL_NAME_WITH_TRAILING_SPACE)
print(registered_model.name == MODEL_NAME_WITH_TRAILING_SPACE)

print("=== without trailing space ===")
registered_model = client.get_registered_model(MODEL_NAME_WITHOUT_TRAILING_SPACE)
print(registered_model.name == MODEL_NAME_WITHOUT_TRAILING_SPACE)
print(registered_model.name == MODEL_NAME_WITH_TRAILING_SPACE)

print("=== no exist model name ===")
try:
    registered_model = client.get_registered_model(MODEL_NAME_NO_EXIST)
except Exception as e:
    print(e)
```

the output below:

```
=== with trailing space ===
True
=== without trailing space ===
False 
True 
# I have not registered a model with the name "test_autolog_registered_model_with_space", so this method should 
# return a RESOURCE_DOES_NOT_EXIST error as shown below.
=== no exist model name ===
RESOURCE_DOES_NOT_EXIST: Registered Model with name=xxxx_no_exits_model_yyy not found
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by yukimori** [comment]
Now, I have figured out the case.
In MySQL, trailing spaces are ignored during string comparisons. I have confirmed this behavior in MySQL 5.7, and I believe it is the same in MySQL 8.

```
mysql> SELECT registered_models.name AS registered_models_name, registered_models.creation_time AS registered_models_creation_time, registered_models.last_updated_time AS registered_models_last_updated_time, registered_models.description AS registered_models_description FROM registered_models WHERE registered_models.name = 'test_autolog_registered_model_with_space '
    -> ;
+-------------------------------------------+---------------------------------+-------------------------------------+-------------------------------+
| registered_models_name                    | registered_models_creation_time | registered_models_last_updated_time | registered_models_description |
+-------------------------------------------+---------------------------------+-------------------------------------+-------------------------------+
| test_autolog_registered_model_with_space  |                   1718116813657 |                       1718117063437 |                               |
+-------------------------------------------+---------------------------------+-------------------------------------+-------------------------------+
1 row in set (0.04 sec)

mysql> SELECT registered_models.name AS registered_models_name, registered_models.creation_time AS registered_models_creation_time, registered_models.last_updated_time AS registered_models_last_updated_time, registered_models.description AS registered_models_description FROM registered_models WHERE registered_models.name = 'test_autolog_registered_model_with_space'
    -> ;
+-------------------------------------------+---------------------------------+-------------------------------------+-------------------------------+
| registered_models_name                    | registered_models_creation_time | registered_models_last_updated_time | registered_models_description |
+-------------------------------------------+---------------------------------+-------------------------------------+-------------------------------+
| test_autolog_registered_model_with_space  |                   1718116813657 |                       1718117063437 |                               |
+-------------------------------------------+---------------------------------+-------------------------------------+-------------------------------+
1 row in set (0.04 sec)
```

**Comment by harupy** [comment]
@yukimori Thanks for the investigation! I'll close this issue.

**Comment by yukimori** [comment]
@harupy 
if you mind, I can fix this issue with sqlalchemy.func.binary function.

In the search model version process, binary function is also used belows:
https://github.com/mlflow/mlflow/blob/db9143d1db19468fa7a6484f80c409ff003de7d9/mlflow/utils/search_utils.py#L242-L254

May I create PR for this issue？
