### ISSUE TITLE
[FR] Move serving base images from being built in MLflow to being built in GH Actions

### ISSUE THREAD

**Issue by lababidi** [mlflow/mlflow#12322]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Currently, MLflow is responsible for building the docker image/container of a deployed model by using a base python or ubuntu image. This process includes the actual installation of various standard libraries. I propose we move the building of most of the image to GH Actions just as the MLflow server is currently done. This will speed up building and deploying models being served.

### Motivation

> #### What is the use case for this feature?
Every time a model is deployed/served, this will be used when a model is being served. It will be using a base image (i.e. mlflow-model-python or mlflow-model-java)

> #### Why is this use case valuable to support for MLflow users in general?
This will speed up building and serving model drastically. in addition, many of the tests in MLflow would be much faster since the base image would not need to be rebuilt for every test that test model serving/building.

> #### Why is this use case valuable to support for your project(s) or organization?
MLflow based models being hosted would have drastic speedup in their deployment.

> #### Why is it currently difficult to achieve this use case?
The current code depends on building from scratch a new image with default packages.

### Details

A new feature has been added to MLflow to allow custom images. This will allow the ability to provide a custom image to iterate through until the full base image process is created in GH Actions.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by lababidi** [comment]
tagging @BenWilson2 @WeichenXu123 since you're familiar with this

**Comment by B-Step62** [comment]
@lababidi Thank you for much for the suggestion! The benefit of having pre-built images for speeding up the deployment process sounds fruitful. 

However, there are a couple of challenges for us to offer such pre-built images
1.  Python/Java versions and standard libraries vary depending on users' models. There are indefinite numbers of combination for the versions and standard libraries, so we have to prepare hundreds of images, not only `mlflow-model-python` and `mlflow-model-java`. Managing that many number of Docker images and ensuring them to work well with a wide variety of ML libraries, will be extremely heavy operational loads. 
2. It is not trivial to define "standard libraries" for the base image, given the huge variance of models we have to support. If we make it minimum to install only the tiny set of libraries that are used for *all* models, the benefit of pre-built image will be small. However, if we make it general image to contain many optional libraries, it will increase the image size and less optimal when serving.

Therefore, our stance is that building a custom image for each different model on top of python/ubuntu  is the optimal solution. Please let us know if you have any other perspectives, or better solution to the above challenges!🙌

**Comment by lababidi** [comment]
Thanks for the well written, clear explanation. At the very least, having it stated is helpful to understand, the system. 

My only thought is maybe have a handful of prebuilt images to speed up some tests. Outside of that, everything you said makes sense.
