### ISSUE TITLE
Is it possible to change user_id?

### ISSUE THREAD

**Issue by tkocmathla** [mlflow/mlflow#1232]
When using mlflow in a Sagemaker notebook, the user_id always shows up in the UI as "ec2-user". I've tried to override this using "user_id" and "mlflow.user" tags, but neither change the value that's shown in the UI.

Is it possible to override the user_id?

**Comment by waryak** [comment]
Actually setting this tag "mlflow.user" just like uou said did the job for me))) You just need to set the tag just after experiment/run context initialization
