### ISSUE TITLE
[BUG]Function wrapping example in mlflow tracing doc does not work

### ISSUE THREAD

**Issue by dannikay** [mlflow/mlflow#12333]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I am willing to contribute to this bug with guidance from MLflow community.

### MLflow version

- Client: 2.14.0rc0
- Tracking server: 2.14.0rc0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.11.3
- **yarn version, if running the dev UI**: N/A

### Describe the problem

See the repro below.

### Tracking information

```shell
```

### Code to reproduce issue

```
import math

import mlflow

mlflow.set_experiment("External Function Tracing")


def invocation(x, y=4, exp=2):
    # Initiate a context handler for parent logging
    with mlflow.start_span(name="Parent") as span:
        span.set_attributes({"level": "parent", "override": y == 4})
        span.set_inputs({"x": x, "y": y, "exp": exp})

        # Wrap an external function instead of modifying
        traced_pow = mlflow.trace(math.pow)

        # Call the wrapped function as you would call it directly
        raised = traced_pow(x, exp)

        # Wrap another external function
        traced_factorial = mlflow.trace(math.factorial)

        factorial = traced_factorial(raised)

        # Wrap another and call it directly
        response = mlflow.trace(math.sqrt)(factorial)

        # Set the outputs to the parent span prior to returning
        span.set_outputs({"result": response})

        return response


for i in range(8):
    invocation(i)
```

### Stack trace

```
N/A
```

### Other info / logs

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[10], line 35
     31         return response
     34 for i in range(8):
---> 35     invocation(i)

Cell In[10], line 23, in invocation(x, y, exp)
     20 # Wrap another external function
     21 traced_factorial = mlflow.trace(math.factorial)
---> 23 factorial = traced_factorial(raised)
     25 # Wrap another and call it directly
     26 response = mlflow.trace(math.sqrt)(factorial)

File ~\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\mlflow\tracing\fluent.py:141, in trace.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    139 except Exception:
    140     _logger.warning(f"Failed to capture inputs for function {fn.__name__}.")
--> 141 result = fn(*args, **kwargs)
    142 span.set_outputs(result)
    143 return result

TypeError: 'float' object cannot be interpreted as an integer
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@dannikay Thank you for reporting the issue! We will update the example to handle type properly.
