### ISSUE TITLE
[FR] Provide a way to override OPENAI_API_BASE in mlflow.openai.log_model usage

### ISSUE THREAD

**Issue by dannikay** [mlflow/mlflow#12362]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

This FR is asking to allow to mock the  requests to open AI so we can hermatically test customer logic that interacts with mlflow. For example the code below always logs a model that makes a request to open AI so the retrieved model depends on  openAI backend:

logged_model_info = mlflow.openai.log_model(
        model="gpt-4",
        task=openai.chat.completions,
        artifact_path="model",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "{question}"},
        ],
    )

Ideally, I would love the ability to override API base so we use the real open ai API base in production but uses a mocked backend in unit test/ integration test.

Please let me know whether this FR makes sense or not.

### Motivation

> #### What is the use case for this feature?

Hermatically testing the mlflow.openai.log_model usage.

> #### Why is this use case valuable to support for MLflow users in general?

This makes testing of mlflow.openai.log_model more flexible and increase usage of it. 

This also reduces cost of integration tests (since no longer need to pay open AI).

> #### Why is this use case valuable to support for your project(s) or organization?

I'm trying to write hermatic test for my business logic but was not able to due to the fact that my code always makes a request to openAI.

> #### Why is it currently difficult to achieve this use case?

Please let me know if there is a workaround.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Can you set the `OPENAI_API_BASE` environment variable? Doesn't that work?

**Comment by dannikay** [comment]
Thanks @harupy and setting OPENAI_API_BASE as the system variable works like a charm for my setup!
