### ISSUE TITLE
[BUG] _expand_duplicate_retrieved_docs adds predictions' id to targets.

### ISSUE THREAD

**Issue by loomlike** [mlflow/mlflow#12361]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

mlflow 2.13.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04.4
- **Python version**: 3.10
- **yarn version, if running the dev UI**: NA

### Describe the problem

The function `mlflow.metrics.metric_definitions._expand_duplicate_retrieved_docs` is currently designed to rename duplicate IDs in predictions for the purpose of counting them when calculating NDCG.
However, this function adds these renamed duplicate IDs into the targets, without checking if the original IDs are present in the targets.

The expected behavior should be that these renamed duplicate IDs are added to the targets only if their corresponding original IDs are already in the targets. 
 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
from mlflow.metrics import ndcg_at_k

import pandas as pd
targets = pd.Series([["a", "b"]])
predictions = pd.Series([["c", "c", "c"]])
metrics = ndcg_at_k(k=3).eval_fn(predictions, targets)
print(metrics.scores)

# expected: 0.0 as no ids in the predictions match to targets'
# returned: 0.5307212739772434
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@loomlike thanks for finding this bug!

**Comment by harupy** [comment]
@loomlike 

Is this fix correct?

```diff
diff --git a/mlflow/metrics/metric_definitions.py b/mlflow/metrics/metric_definitions.py
index f9320c15c..23a0652cb 100644
--- a/mlflow/metrics/metric_definitions.py
+++ b/mlflow/metrics/metric_definitions.py
@@ -395,7 +395,8 @@ def _expand_duplicate_retrieved_docs(predictions, targets):
                 f"{doc_id}_bc574ae_{counter[doc_id]}"  # adding a random string to avoid collisions
             )
             expanded_predictions.append(new_doc_id)
-            expanded_targets.add(new_doc_id)
+            if doc_id in expanded_targets:
+                expanded_targets.add(new_doc_id)
     return expanded_predictions, expanded_targets
```

**Comment by loomlike** [comment]
@harupy your fix looks good to me! Also found one typo in the error message in the same file.
```
def _recall_at_k_eval_fn(k):
    if not (isinstance(k, int) and k > 0):
        _logger.warning(
            f"Cannot calculate 'precision_at_k' for invalid parameter 'k'. "
```
`precision_at_k` -> `recall_at_k`  in the warning message.

**Comment by harupy** [comment]
@loomlike Thanks for finding typos, but that's a different issue. We can file two PRs, one for fixing `_expand_duplicate_retrieved_docs` and one for fixing the typos.
