### ISSUE TITLE
 RuntimeError: Scikit-learn requires Python 3.5 or later in Docker example

### ISSUE THREAD

**Issue by gusseppe** [mlflow/mlflow#1239]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: No, by using pip install mlflow
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.9.1
- **Python version**: Python 3.7.1
- **npm version (if running the dev UI):
- **Exact command to reproduce**: docker build -t mlflow-docker-example -f Dockerfile .

### Describe the problem
When running the above command in the examples/docker folder it raises an error regarding the scikitlearn library, so the building process doesn't finish.

### Source code / logs

Collecting scikit-learn (from mlflow==0.8.1)
  Downloading https://files.pythonhosted.org/packages/9b/94/a24da18837e32ae2d5275b18308a542ae07891617501336b31c81a383cad/scikit-learn-0.21.0.tar.gz (12.2MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-M7EhiL/scikit-learn/setup.py", line 30, in <module>
        % (platform.python_version(), sys.executable))
    RuntimeError: Scikit-learn requires Python 3.5 or later. The current Python version is 2.7.15 installed in /opt/conda/bin/python.
    
The possible fix will be change the Dockerfile as follows:

FROM continuumio/miniconda3
RUN pip install mlflow==0.8.1 \
    && pip install azure-storage==0.36.0 \
    && pip install numpy==1.14.3 \
    && pip install pandas==0.22.0 \
    && pip install scikit-learn==0.19.1 \
    && pip install cloudpickle

I just changed: **continuumio/miniconda:4.5.4**
to **continuumio/miniconda3**

**Comment by HyukjinKwon** [comment]
Seems fixed as of https://github.com/mlflow/mlflow/commit/04b6ec7847a64cb949fb4be0cbb70b11a0cd4c5b

**Comment by vanetoj** [comment]
any idea how to fix the same error for aws?
