### ISSUE TITLE
[BUG] Empty S3 objects created when logging artifacts with nested prefix

### ISSUE THREAD

**Issue by sateeshmannar** [mlflow/mlflow#12413]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.13.0
- Tracking server: 2.13.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: AWS Linux
- **Python version**: 3.12.2
- **yarn version, if running the dev UI**: NA

### Describe the problem

This issue is specific to logging artifacts with s3 as the artifactory store.

PR https://github.com/mlflow/mlflow/pull/10695 introduced a change to mlflow/store/artifact/s3_artifact_repo.py. The change was to 'put' object for a path with no file objects (filenames is empty) - https://github.com/mlflow/mlflow/commit/c9529165931ea58599cbe1ff8cedbd06100804d4#r143269656

When a prefix just has just sub-folders and no other file objects, the change is adding empty files with the name of the parent prefix.  See example screen shot:
![image](https://github.com/mlflow/mlflow/assets/111794978/199c9eaa-d0b5-4a68-b2fb-f603f4e8263f)

I tested the code by commenting the change and the empty objects were not created.

@harupy please take a look.

### Tracking information

```shell
NA
```

### Code to reproduce issue

```
import mlflow
import os

def create_dummy_text_file(file_path):
    with open(file_path, 'w') as file:
        file.write('This is a dummy text file.')

# In the example below prefixes "parent" and "child2" will have a dummy/zero byte s3 object created with the same name

os.makedirs("path/to/artifact/parent")
os.makedirs("path/to/artifact/parent/child1")
os.makedirs("path/to/artifact/parent/child2/grandchild1")

create_dummy_text_file('path/to/artifact/parent/child1/dummy.txt')
create_dummy_text_file('path/to/artifact/parent/child2/grandchild1/dummy.txt')

with mlflow.start_run():
    mlflow.log_artifacts('/path/to/artifact')
```

### Stack trace

```
NA
```

### Other info / logs

```
NA
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@sateeshmannar Thanks for reporting this. We filed #12415 to revert the change.
