### ISSUE TITLE
Add `pass_filenames: false`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#12427]
### Summary

`dev/pyproject.py` doesn't have any arguments. `pass_filenames` should be disabled.

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 7c6ef1ace..89ec65869 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -81,6 +81,7 @@ repos:
         language: system
         stages: [commit]
         require_serial: true
+        pass_filenames: false
 
       - id: mlver
         name: ml-package-versions-consistency
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by victolee0** [comment]
@harupy Can I take this ?

**Comment by harupy** [comment]
absolutely!

**Comment by harupy** [comment]
@victolee0 assigned :)
