### ISSUE TITLE
Fix typo: `precision_at_k` -> `recall_at_k`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#12429]
### Summary

Originally reported at https://github.com/mlflow/mlflow/issues/12361#issuecomment-2179812283. Fix typos in `_recall_at_k_eval_fn`.

https://github.com/mlflow/mlflow/blob/9f1adbc020da996961b92a22c5f0691b73615447/mlflow/metrics/metric_definitions.py#L478-L490

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by yukimori** [comment]
@harupy May I take this issue？

**Comment by harupy** [comment]
@yukimori of course!
