### ISSUE TITLE
Remove trailing whitespace in maintainer email address

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#12455]
### Summary

Originally found in https://github.com/mlflow/mlflow/pull/12426#discussion_r1648552924

```diff
% gd
diff --git a/dev/pyproject.py b/dev/pyproject.py
index 7157d17e5..9e5d1e684 100644
--- a/dev/pyproject.py
+++ b/dev/pyproject.py
@@ -69,7 +69,7 @@ def build(skinny: bool) -> None:
             "name": "mlflow" if not skinny else "mlflow-skinny",
             "version": version,
             "maintainers": [
-                {"name": "Databricks", "email": "mlflow-oss-maintainers@googlegroups.com "}
+                {"name": "Databricks", "email": "mlflow-oss-maintainers@googlegroups.com"}
             ],
             "description": (
                 "MLflow is an open source platform for the complete machine learning lifecycle"
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by Venki1402** [comment]
@harupy Can I work on this issue?

**Comment by harupy** [comment]
@Venki1402 of course!

**Comment by Venki1402** [comment]
I have submitted a PR #12458 that should fix this issue, I hope it's correct. I apologize if there are any mistakes since I am just getting started with open source.

**Comment by Venki1402** [comment]
I had to create a new PR #12460
