### ISSUE TITLE
[DOC-FIX]  Getting Started with MLflow missing a command

### ISSUE THREAD

**Issue by jsuchome** [mlflow/mlflow#12462]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/getting-started/logging-first-model/step5-synthetic-data.html

### Description of proposal (what needs changing)

The call to `generate_apple_sales_data_with_promo_adjustment` is missing. It's mentioned in the notebook, but not in the HTML code

**Comment by BenWilson2** [comment]
It's in the notebook: https://mlflow.org/docs/latest/getting-started/logging-first-model/notebooks/logging-first-model.html

**Comment by jsuchome** [comment]
Yes, I know it's in the notebook, I even mentioned in the description. 
I think the HTML tutorial should reflect the final notebook version though.
