### ISSUE TITLE
Launch Mlflow error

### ISSUE THREAD

**Issue by Musarath-Rahamathullah** [mlflow/mlflow#12488]
### Summary

When I launch the Mlflow from studio, its giving me following error "Something went wrong
If this error persists, please report an issue [here](https://github.com/mlflow/mlflow/issues)."

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by BenWilson2** [comment]
Hi @Musarath-Rahamathullah could you ask questions like these over in the Discussions tabs of the MLflow repo? Thanks!
