### ISSUE TITLE
Autologging with nested runs?

### ISSUE THREAD

**Issue by SjoerdTimovanVliet** [mlflow/mlflow#12492]
https://mlflow.org/docs/latest/traditional-ml/hyperparameter-tuning-with-child-runs/part1-child-runs.html

Does someone have a working example how to use this on combination with auto logging?

Additionally, how to reproduce the run afterwards?

**Comment by BenWilson2** [comment]
Hi @SjoerdTimovanVliet could you ask this over in the Discussions section of the repository?
