### ISSUE TITLE
docker build fails with Double requirement given for  botocore and boto3 & mysqlclient install error

### ISSUE THREAD

**Issue by jimthompson5802** [mlflow/mlflow#1250]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.4
- **MLflow installed from (source or binary)**: N/A
- **MLflow version (run ``mlflow --version``)**: master branch:  '0.9.2.dev0'
- **Python version**: N/A
- **npm version (if running the dev UI): N/A
- **Exact command to reproduce**:
```
docker build -t mlflow_dev .
```

### Describe the problem
`docker build` ends with this error message.
```
Double requirement given: botocore<=1.12.84 (from -r travis/large-requirements.txt (line 4)) (already in botocore==1.12.84 (from -r travis/small-requirements.txt (line 4)), name='botocore')
The command '/bin/sh -c pip install -r dev-requirements.txt &&     pip install -r test-requirements.txt &&     pip install -e . &&     apt-get update && apt-get install -y gnupg &&     apt-get install -y openjdk-8-jre-headless &&     curl -sL https://deb.nodesource.com/setup_10.x | bash - &&     apt-get update && apt-get install -y nodejs &&     cd mlflow/server/js &&     npm install &&     npm run build' returned a non-zero code: 1
```

### Source code / logs
[Dockerfile used is the one](https://github.com/mlflow/mlflow/blob/master/Dockerfile) in the repo's root directory.

This is full log for the error.
[docker_build_double_requirement_error.txt](https://github.com/mlflow/mlflow/files/3169537/docker_build_double_requirement_error.txt)

### Root Cause Analysis
From what I can tell, this error occurs because there are inconsistent dependency specification in `test-requirements.txt` brought on by the change to allow running 'large' integration tests in a separate build stage.  These inconsistencies were found in the travis large and small requirements files.

|travis/large-requirements.txt|travis/small-requirements.txt|
|-----------------------------|-----------------------------|
|botocore<=1.12.84|botocore==1.12.84|
|boto3<=1.9.84|boto3==1.9.84 |

I'll submit a PR to make the `large-requirements.txt` specification match the `small-requirements.txt`.

**Comment by jimthompson5802** [comment]
Encountered another `docker build` error when installing mysqlclient Python package
```
Collecting mysqlclient (from -r travis/large-requirements.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz (85kB)
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Rzl2tJ/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Rzl2tJ/mysqlclient/
The command '/bin/sh -c pip install -r dev-requirements.txt &&     pip install -r test-requirements.txt &&     pip install -e . &&     apt-get update && apt-get install -y gnupg &&     apt-get install -y openjdk-8-jre-headless &&     curl -sL https://deb.nodesource.com/setup_10.x | bash - &&     apt-get update && apt-get install -y nodejs &&     cd mlflow/server/js &&     npm install &&     npm run build' returned a non-zero code: 1
```

**Comment by anibaleproductions** [comment]
write on Dockerfile 
`COPY requirements.txt .`
