### ISSUE TITLE
[BUG] Databricks Bundle Run on DBR 15.3 no longer works after MLFlow 2.14.2 Release?

### ISSUE THREAD

**Issue by aabilov-dataminr** [mlflow/mlflow#12568]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.14.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks Runtime 15.3
- **Python version**: 3.11
- **yarn version, if running the dev UI**:

### Describe the problem

Our Databricks workflow runs deployed via bundles on DBR 15.3 are unable to start.

This seems to be caused by the release of MLFlow 2.14.2 which has made changes to `mlflow.tracing.utils`.

Our workflow uses MLFlow 2.13.0 so I don't see why we should encounter this exception -- I'm guessing that the Databricks runtime has an unpinned dependency under the hood?

### How to reproduce issue
Attempt to start a Databricks workflow on DBR 15.3

### Stack trace

```
ImportError: cannot import name 'extract_span_inputs_outputs' from 'mlflow.tracing.utils' (/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/mlflow/tracing/utils/__init__.py)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/.ipykernel/1788/command--1-3729142775:8
      5 del sys
      7 with open(filename, "rb") as f:
----> 8   exec(compile(f.read(), filename, 'exec'))

File /Workspace/Shared/.bundle/dm-llm-workflows/prod/files/llm_workflows/cli/generate.py:5
      2 from dataclasses import dataclass, field
      3 from typing import Optional
----> 5 import mlflow
      6 import torch
      7 from datasets import Dataset

File /databricks/python_shell/dbruntime/PostImportHook.py:231, in _ImportHookChainedLoader.exec_module(self, module)
    229 def exec_module(self, module):
    230     try:
--> 231         self.loader.exec_module(module)
    232         notify_module_loaded(module)
    233     except (ImportError, AttributeError):

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/mlflow/__init__.py:109
    107 from mlflow.models import evaluate
    108 from mlflow.projects import run
--> 109 from mlflow.tracing.fluent import (
    110     get_current_active_span,
    111     get_trace,
    112     search_traces,
    113     start_span,
    114     trace,
    115 )
    116 from mlflow.tracking._model_registry.fluent import (
    117     register_model,
    118     search_model_versions,
    119     search_registered_models,
    120 )
    121 from mlflow.tracking.fluent import (
    122     ActiveRun,
    123     active_run,
   (...)
    158     start_run,
    159 )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/mlflow/tracing/fluent.py:25
     23 from mlflow.tracing.display import get_display_handler
     24 from mlflow.tracing.trace_manager import InMemoryTraceManager
---> 25 from mlflow.tracing.utils import (
     26     SPANS_COLUMN_NAME,
     27     capture_function_input_args,
     28     encode_span_id,
     29     extract_span_inputs_outputs,
     30     get_otel_attribute,
     31     traces_to_df,
     32 )
     33 from mlflow.tracking.fluent import _get_experiment_id
     34 from mlflow.utils import get_results_from_paginated_fn

ImportError: cannot import name 'extract_span_inputs_outputs' from 'mlflow.tracing.utils' (/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/mlflow/tracing/utils/__init__.py)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [x] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Could you elaborate how to reproduce the issue in databricks runtime ? What do you mean by "Databricks Bundle Run"?

**Comment by WeichenXu123** [comment]
Do you mean this ? https://docs.databricks.com/en/dev-tools/bundles/settings.html

Do you have minimal script to reproduce it ?

**Comment by WeichenXu123** [comment]
Didn't receive more response. I will close this. Once it gets new response, we can reopen this.
