### ISSUE TITLE
mlflow is not working in colab

### ISSUE THREAD

**Issue by dsnsabari** [mlflow/mlflow#12563]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:
- **databricks-sdk-0.29.0**
-  **mlflow 2.14.1**

### Describe the problem

https://mlflow.org/docs/latest/deep-learning/tensorflow/quickstart/quickstart_tensorflow.html

I am trying to run the TensorFlow-based image classification model using the code mentioned above. I ran the code on Colab and created a community account on Databricks. Please help me with solving the issue.

```bash

NotFound: Not Found

During handling of the above exception, another exception occurred:

MlflowException                           Traceback (most recent call last)
MlflowException: Failed to validate databricks credentials: Not Found

During handling of the above exception, another exception occurred:

MlflowException                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/mlflow/utils/credentials.py](https://localhost:8080/#) in _databricks_login(interactive)
    229     except Exception as e:
    230         # If user entered invalid auth, we will raise an error and ask users to retry.
--> 231         raise MlflowException(f"`mlflow.login()` failed with error: {e}")

MlflowException: `mlflow.login()` failed with error: Failed to validate databricks credentials: Not Found
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by aditi-raj** [comment]
Ensure you have set up your Databricks credentials correctly. Set environment variables correctly and Verify MLflow is configured for Databricks:import mlflow
mlflow.set_tracking_uri("databricks")
If you have already done these please provide additional context about your setup.

**Comment by WeichenXu123** [comment]
Since this is user auth config issue but not MLflow side issue, I will close this ticket. Feel free to reopen it if you still can't address it.
