### ISSUE TITLE
[FR] Auto Serve Registered Models

### ISSUE THREAD

**Issue by khari998** [mlflow/mlflow#12589]
### Willingness to contribute

Yes. I can contribute this feature with help from the MLFlow community.

### Proposal Summary

I propose is that we automatically serve each model in the registry and disable/enable them based on the environment flag. We can setup a port for staging and a port for production and models on either flag would deploy on that port. Any model that is archived is no longer served. I saw that the environment flags are being deprecated in favor of something new so this can be adapted for whatever that future change is.

Additionally, all we would need to do is supply the POST body to the `/invocations` route with the name of the model or do something like `/invocations/{model_name}` in order to get this to work dynamically for each model. We already have a unique name constraint on the model registry models. This should allow us to invoke models dynamically much easier than setting up one port for each model.

### Motivation

> #### What is the use case for this feature?

The current process for serving models locally is to write code to serve each model individually. It also seems like this needs to be done at one port per model. This is very inconvenient if you are working with a lot of models in production. Configuring a port for each in order to properly do dynamic invocations makes this process unnecessarily complex.

> #### Why is this use case valuable to support for MLFlow users in general?

For users that have projects with a lot of different models, this allows them to build their architecture in a much more scalable way. 

> #### Why is this use case valuable to support for your project(s) or organization?

 I am trying to utilize MLFlow to manage hundreds of models that can scale up to even more in the future. If I have to make a new port for each model, I have to write code around understanding port mappings which makes the system much more complex than it needs to be. It also takes away from the point of using MLFlow to manage my model infrastructure.

> #### Why is it currently difficult to achieve this use case?

This would require bindings to the registry and code generation to automatically serve models.

### What component(s) does this bug affect?
 
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations 
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors

**Comment by WeichenXu123** [comment]
So that I think your main idea is to serve all registered models by one mlflow server ?

**Comment by WeichenXu123** [comment]
One concern of this design is:

Model serving requires loading model into server memory, note that many models (e.g. transformers) might be very large. If your design is to serve all models in one server, then for each model inference request, you have to load that model into memory, it might cause memory explosion.

**Comment by khari998** [comment]
I was essentially trying to host multiple models locally. I understand the memory explosion argument. 

The only solution I've seen so far to manage this at scale in a similar way I want is by using Databricks. But even they still use one model per endpoint. This idea would've essentially been something similar to Databricks serving but served locally through one endpoint. 

However, given how big models can get, there would be some need to distribute models to different compute nodes for this to be able to work well at scale. Seems like it may be too big of a request for not much reward for most users. 

The only thing that irks me is that I was hoping to have an option where we didn't have to rely on the cloud to deploy multiple models easily. The only work around I've seen so far is to use a custom model that would conditionally call different models in the registry which is a real pain to write for a ton of models which is what led me to writing this feature request in the first place. Hopefully some solution can be derived thats simple to implement and allows users to easily deploy multiple models locally. @WeichenXu123

**Comment by khari998** [comment]
I thought about this a little more in depth. The memory usage would get absurd at scale. One of the things Databricks handles for you is deploying models on GPU accelerated hardware automatically. Doing this locally or across multiple compute nodes would be horrendous to account for. So yeah I don't think the juice is worth the squeeze for this feature. Even though I'd rather not hitch my architecture to the cloud, this is one of those instances where cloud infrastructure makes much more sense to take advantage of. Closing this issue due to this.

**Comment by CKAbundant** [comment]
Hi, I'm trying to serve multiple models using the same endpoint with reference to https://mlflow.org/docs/latest/traditional-ml/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial.html

Instead of launching MLServer locally via `mlflow models serve -m "models:/{MME_MODEL_NAME}/latest" --env-manager local -p {PORT}`, I have build MLServer docker using `mlflow.models.build_docker` command as shown:

```
# Build 'Model Serve' docker
mlflow.models.build_docker(
    model_uri=<model_uri>,
    name=<image_name>,
    env_manager="conda",
    enable_mlserver=True,
    base_image=<base_image>,
)
```
I managed to build and run the docker but somehow the params are not able to be passed properly:

```
def score_model(pdf, params):
    headers = {"Content-Type": "application/json"}
    url = f"http://127.0.0.1:{PORT}/invocations"
    ds_dict = {"dataframe_split": pdf, "params": params}
    data_json = json.dumps(ds_dict, allow_nan=True)

    response = requests.request(method="POST", headers=headers, url=url, data=data_json)
    response.raise_for_status()

    return response.json()
    
score_model(<inference_dataframe>, params={"model_type", "ensemble"})
```

For some reason, the prediction result is always based on {"model_type", "aapl"}.

May I know if there is limitation on passing 'params' in payload to inference endpoint? Thanks.
