### ISSUE TITLE
Can't use pyfuncs.load_model() and pyfuncs.predict() without AWS Credentials

### ISSUE THREAD

**Issue by Rietty** [mlflow/mlflow#12630]
So I have an MLflow server for which I have a login credentials, and a tracking `uri`. This server has models loaded on it for us that I would like to use. Initially I had the AWS Credentials for the server and I set them in my environmental variables and it worked fine.. however now I would like to avoid having them on my server, or leak them or anything really and decided to use the username and password option to connect.

So I have code like so:
```
model = mlflow.pyfunc.load_model(model_uri=model_uri)
resp = model.predict(input.data).to_dict()
print(resp)
```
However I get the following error from it: `Unable to locate credentials`. How do I properly set-up/authenticate to my tracking server using credentials so I can run predict on the loaded model? I've searched literally every piece of documentation and nothing covers this.

**Comment by WeichenXu123** [comment]
You have to use custom model in this case.
You can in create a custom python model, and in `load_context()` making a call to a secrets server / AWS services to get the token. 

Currently MLflow builtin code can only read AWS token from environmental variables

**Comment by Rietty** [comment]
> You have to use custom model in this case. You can in create a custom python model, and in `load_context()` making a call to a secrets server / AWS services to get the token.
> 
> Currently MLflow builtin code can only read AWS token from environmental variables

But I don't want to have to rely on the AWS Token at all, what is the point of using a username/password if the AWS environmental variables are still needed?

**Comment by WeichenXu123** [comment]
> read AWS token from environmental variables

Unfortanetely currently MLflow only supports this way to set up auth with AWS service.

If you want to get rid of AWS code and use other auth way,
you have to use custom model and write your own model loading code for setting up auth with AWS
