### ISSUE TITLE
[FR] Make parent_run_id a parameter in start_run for hyperparameter tuning using multiple jobs

### ISSUE THREAD

**Issue by Flametaa** [mlflow/mlflow#12639]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Add `parent_run_id ` as a parameter in `mlflow.start_run` to avoid having to start a parent run in order to be able to use nested runs.

### Motivation

> #### What is the use case for this feature?
Performing hyperparameter tuning using multiple jobs in parallel on Kubernetes. Each trial needs to create nested runs under the same parent run. It would be great if we can simply specify the parent_run_id for nested runs where the run already exists.

> #### Why is this use case valuable to support for MLflow users in general?
I believe that this change can make the user experience better.

> #### Why is this use case valuable to support for your project(s) or organization?
Our training pipelines are time consuming and it is a requirement for us to parallelize hyperparameter tuning experiments.

> #### Why is it currently difficult to achieve this use case?
It is possible to use the current approach to implement this, however the code looks more complex as we simply need to start the nested runs at each trial iteration. 

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@Flametaa The proposal makes a lot sense! Would you mind contributing for this feature?

A few pointers to start:
* The parent_id is recorded to the run as a system tag here. https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/fluent.py#L362C9-L362C22
* We may want to deprecate the existing `nested` parameter as `parent_run_id` appears to be more precise and convenient. https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/fluent.py#L238

Please let me know if there is any help needed to implement the feature. Thank you so much!

**Comment by Flametaa** [comment]
I don't think it is a good idea to deprecate `nested` parameter, as we might still want to be able to infer the `parent_id` from the active runs. In that sense, if we already have an active run, we might still want to be able to create other runs that are not nested. What I propose is:

- keep both `nested` and `parent_id` parameters
- If `parent_id` is specified then the run will be nested under that parent run
- else if `nested` is True, then we infer the `parent_id` from the active run
- else if `nested` is False then the run is not nested (so the last two steps will remain the same as now)
What do you think @B-Step62 ?

**Comment by B-Step62** [comment]
@Flametaa Thank you for giving some thoughts on the design!

> If parent_id is specified then the run will be nested under that parent run
> else if nested is True, then we infer the parent_id from the active run
> else if nested is False then the run is not nested (so the last two steps will remain the same as now)

The third option is not allowed in current implementation. If the active run exists but a new run is started with `nested=False`, MLflow raise an exception [here](https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/fluent.py#L305). This is because some of the Run operation relies on global context and may cause pollution between two runs that are intended to be separate. Therefore, practically we don't really support `nested=False` case.

That said, I'm fine with keeping the parameter for now. Then this change can be purely framed as enhancement and no breaking change. Let's go with that approach🙂
