### ISSUE TITLE
[BUG] PyFuncModel.unwrap_python_model fails when used on a pytorch model

### ISSUE THREAD

**Issue by MirandaRosalise** [mlflow/mlflow#12644]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.9.2

### System information

- Databricks Runtime 14.3 LTS ML

### Describe the problem

`PyFuncModel` contains a method, "`unwrap_python_model`", which unwraps the underlying model object of a loaded `PyFuncModel`. However, when called on a wrapped, loaded pytorch model object, this fails because of the [following line](https://github.com/mlflow/mlflow/blob/b6248786c6ef49e36dce95db3d161699482abb09/mlflow/pyfunc/__init__.py#L871C1-L877C28):

```        
try:
>   python_model = self._model_impl.python_model
    if python_model is None:
        raise AttributeError("Expected python_model attribute not to be None.")
except AttributeError as e:
    raise MlflowException("Unable to retrieve base model object from pyfunc.") from e
return python_model
```

Specifically, the error is that the `_PyTorchWrapper` [init names this property "pytorch_model" and not "python_model"](https://github.com/mlflow/mlflow/blob/b6248786c6ef49e36dce95db3d161699482abb09/mlflow/pytorch/__init__.py#L727). When using `_model_impl.pytorch_model`, the model is unwrapped correctly

This should be an easy fix in one of two ways:

1) Add more logic to `unwrap_python_model` to detect and correctly unwrap pytorch models
2) Change the property name of `_PyTorchWrapper.pytorch_model` to match the conventional name of `python_model` instead

I'm willing to submit a PR for 1) as it seems like an easier fix, but will defer to the maintainers.

### Stack trace

```
MlflowException: Unable to retrieve base model object from pyfunc.
File /databricks/python/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py:544, in PyFuncModel.unwrap_python_model(self)
    543 try:
--> 544     python_model = self._model_impl.python_model
    545     if python_model is None:
AttributeError: '_PyTorchWrapper' object has no attribute 'python_model'

The above exception was the direct cause of the following exception:
MlflowException                           Traceback (most recent call last)
File <command-3380363878052250>, line 1
----> 1 AEModelWrapper.unwrap_python_model()
File /databricks/python/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py:548, in PyFuncModel.unwrap_python_model(self)
    546         raise AttributeError("Expected python_model attribute not to be None.")
    547 except AttributeError as e:
--> 548     raise MlflowException("Unable to retrieve base model object from pyfunc.") from e
    549 return python_model
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by MirandaRosalise** [comment]
NB: this probably also happens with other flavors, this just happens to be the one I found, so would be worth someone who's familiar combing for similar issues in other wrapper flavors

**Comment by MirandaRosalise** [comment]
also addresses https://github.com/mlflow/mlflow/issues/12119

**Comment by B-Step62** [comment]
@MirandaRosalise Thank you for reporting the issue.

The `unwrap_python_model` function and `python_model` attribute is only intended to be used with a model saved as [a custom python model.](https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#module-mlflow.pyfunc). Other native flavors don't support this method. In order to access the underlying pytorch model instance, you can use `mlflow.pytorch.load_model()`.

```
torch_model = mlflow.pytorch.load_model(model_uri)
```
