### ISSUE TITLE
sso configuration in mlflow

### ISSUE THREAD

**Issue by dakdba1980** [mlflow/mlflow#12650]
how to configure sso in mlflow?

I configured mlflow in kubernetes using helm chart. I need to configure sso (azure ad) with mlflow.

**Comment by B-Step62** [comment]
@dakdba1980 MLflow doesn't support SSO. Please consider using [managed MLflow](https://www.databricks.com/product/managed-mlflow) or plugging in custom solutions upon the proxy tracking server.
