### ISSUE TITLE
SQLAlchemy backend is ignored when a driver is included in the URI

### ISSUE THREAD

**Issue by drewmcdonald** [mlflow/mlflow#1266]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.9.1
- **Python version**: 3.6.8
- **npm version (if running the dev UI):
- **Exact command to reproduce**: use a database backend URI that specifies a driver (in the form `'dialect+driver://...'`)

### Describe the problem

When starting a server, the`backend-store-uri` is parsed in `SQLAlchemyStore.__init__` [here](https://github.com/mlflow/mlflow/blob/2ee4c64a5d8d089ca23195e835fd6d1b986fcba8/mlflow/store/sqlalchemy_store.py#L66). The scheme (everything before `://`) is used as a key to identify what type of backend is being requested. 

However, it's very common to specify a database connection using both a dialect and a driver for that dialect, as in `dialect+driver://...`. In this situation, mlflow takes `dialect+driver` as the key, and has to fall back to the file store since that key does not match to a supported backend type.

This URI style [is supported in sqlalchemy](https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls) and should be allowed in mlflow as well. For one example, I use the `pymysql` driver heavily as it's easiest to install. It's also worth noting that this breaks even when the default drivers are the drivers specified.

### Suggested Solution

Add another step to the URI parsing procedure that keeps everything before `'+'` as the key for the backend type.

Instead of `self.db_type = urllib.parse.urlparse(db_uri).scheme`, we could split at '+' and take the first value (`self.db_type = urllib.parse.urlparse(db_uri).scheme.split('+')[0]`), or do some sort of regex scrub.

* `mysql+pymysql` -> `mysql`
* `mysql` -> `mysql`
* `postgresql+pg8000` -> `postgresql`
* etc.

This would yield the correct keys for identifying database types and allow users to use the driver of their choice (the connection would still be built on the db_uri as specified).

**Comment by mateiz** [comment]
Thanks for reporting this. The suggested solution makes sense.

**Comment by drewmcdonald** [comment]
The changes in #1297 will resolve this. Thanks!

**Comment by drewmcdonald** [comment]
Per https://github.com/mlflow/mlflow/pull/1297#issuecomment-498776897 this is actually still not supported unfortunately.

**Comment by drewmcdonald** [comment]
#1402 presents one way to resolve this issue again.
