### ISSUE TITLE
[BUG] MLFlow.sklearn.autolog compatability with 0.24.1 <= scikit-learn <= 1.4.2 whilst scikit-learn sensitive data leakage vulnerability

### ISSUE THREAD

**Issue by judithts** [mlflow/mlflow#12696]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

Latest MLFlow version: 2.14.3
Although I am using the 1.30.0 version because of compatability with Databricks.

### System information

Windows 10
Python 3.10.2

### Describe the problem

The mlflow.sklearn.autolog() functionality is compatible with 0.24.1 <= scikit-learn <= 1.4.2 (https://mlflow.org/docs/latest/python_api/mlflow.sklearn.html). The scikit-learn versions < 1.5.0 do however suffer from a data leakage vulnerability (https://github.com/advisories/GHSA-jw8x-6495-233v). I would like to use the autologging functionality whilst also updating the scikit-learn version, which is currently giving me an AttributeError.

With scikit-learn 1.5.0 the following AttributeError occurs:
in the site-packages/mlflow/sklearn/__init__.py file in line 1755 in _autolog for scorer in sklearn.metrics.SCORERS.values():
AttributeError: module 'sklearn.metrics' has no attribute 'SCORERS'

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
import mlflow.sklearn
from sklearn.svm import SVR
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)
mlflow.sklearn.autolog()
with mlflow.start_run() as run:
  SVR.fit(X,y)
```

### Stack trace

```
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -   File "/app/src/training/model_train_and_register.py", line 198, in train_model
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -     mlflow.sklearn.autolog(registered_model_name=model_name)
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -   File "/usr/local/lib/python3.9/site-packages/mlflow/utils/autologging_utils/__init__.py", line 416, in autolog
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -     return _autolog(*args, **kwargs)
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -   File "/usr/local/lib/python3.9/site-packages/mlflow/sklearn/__init__.py", line 1209, in autolog
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -     _autolog(
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -   File "/usr/local/lib/python3.9/site-packages/mlflow/sklearn/__init__.py", line 1755, in _autolog
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO -     for scorer in sklearn.metrics.SCORERS.values():
[2024-07-16 14:04:25,204] {{pod_manager.py:235}} INFO - AttributeError: module 'sklearn.metrics' has no attribute 'SCORERS'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @judithts I believe the issue that you're reporting is due to the test dataset you're using. 

This autologs just fine:
```python
import mlflow
from sklearn import svm

mlflow.sklearn.autolog()

X = [[0, 0], [2, 2]]
y = [0.5, 2.5]
regr = svm.SVR()
regr.fit(X, y)
regr.predict([[1, 1]])
```

However, your example, with mlflow autologging disabled, throws a numpy AttributeError:

```python
import mlflow
from sklearn import svm

mlflow.autolog(disable=True)

SVR.fit(X,y)
```

**Comment by BenWilson2** [comment]
If you validate a working example that doesn't involve MLflow and find that you still encounter an autologging issue, please feel free to re-open this ticket. 
Thanks for using MLflow!
