### ISSUE TITLE
Update `gpt-3.5-turbo` references to `gpt-4o-mini`

### ISSUE THREAD

**Issue by B-Step62** [mlflow/mlflow#12724]
### Summary

OpenAI recently released [GPT-4o mini](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/) model. It is cheaper and more performant than GPT-3.5 Turbo and they are planning to deprecate the GPT-3.5 Turbo in favor of the new one.

We still have [many references](https://github.com/search?q=repo%3Amlflow%2Fmlflow+gpt-3.5-turbo&type=code) to the old model in the documentation, examples, and tutorials. We want to replace those reference to the new `gpt-4o-mini` model.

### Notes

- Setting up dev environment following [the contribution guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md#setting-up-the-repository).
- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Run `pre-commit run --all-files` 
- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by pravo23** [comment]
Hi, can I work on this? Thanks

**Comment by Acksout** [comment]
I've sent a PR with the following changes. https://github.com/mlflow/mlflow/pull/12740

**Comment by B-Step62** [comment]
@pravo23 Sorry for replying late, but we don't typically "assign-and-work" model for a quick issue like this. Please feel free to open a PR without waiting for assignment from next time!
