### ISSUE TITLE
Cannot open UI, 404 Not Found

### ISSUE THREAD

**Issue by johny-c** [mlflow/mlflow#1274]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: 
source
- **MLflow version (run ``mlflow --version``)**:
0.9.2.dev0
- **Python version**: 
3.6.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
mlflow ui

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.
Cannot open UI, 404 Not Found. It was running smoothly from the official release (0.9.1).
(I'm not running from the mlflow cloned repo.)
I installed from source to use the step feature for logging metrics.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

mlflow ui --backend-store-uri ./mlruns
[2019-05-15 14:44:15 +0200] [9236] [INFO] Starting gunicorn 19.9.0
[2019-05-15 14:44:15 +0200] [9236] [INFO] Listening at: http://127.0.0.1:5000 (9236)
[2019-05-15 14:44:15 +0200] [9236] [INFO] Using worker: sync
[2019-05-15 14:44:15 +0200] [9239] [INFO] Booting worker with pid: 9239
[2019-05-15 14:44:55 +0200] [9236] [CRITICAL] WORKER TIMEOUT (pid:9239)

**Comment by stanpcf** [comment]
+1

**Comment by mateiz** [comment]
Unfortunately, just pip installing from source isn't enough to run the UI. We have some instructions on how to do that over here: https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#launching-the-development-ui. You can either run the development server or build a wheel that contains the JS for the UI as well. Please let us know if this doesn't fix the issue.
