### ISSUE TITLE
[BUG] Security Vulnerability

### ISSUE THREAD

**Issue by hsechier** [mlflow/mlflow#12759]
Hello, 

I'm using mlflow in my company, and I have this auto bot that give me a security flag :

![image](https://github.com/user-attachments/assets/96f04c51-1eb7-4e1e-9ee6-19f9fe66273c)

Can you help me to understand that please ?

**Comment by BenWilson2** [comment]
This is because of the `pickle` module being used in MLflow recipes. If you are not running MLflow in a publicly accessible server, this won't apply to you.
