### ISSUE TITLE
[BUG] Cannot permanently delete experiment

### ISSUE THREAD

**Issue by dmrub** [mlflow/mlflow#12760]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.14.3
- Tracking server: 2.14.3

### System information

- **OS Platform and Distribution**: Linux Ubuntu 22.04.3
- **Python version**: 3.10.14
- **Backend store**: Postgres
- **Artifacts store**: MinIO

### Describe the problem

I'm trying to figure out how to permanently delete an experiment to reuse its name via the mlflow API. When I delete it either via the mlflow UI or the mlflow.delete_experiment API function, I still can't reuse the name. I use the following Python script to test the permanent deletion:

```python
#!/usr/bin/env python3

import mlflow
mlflow.set_tracking_uri("https://myserver")

exp_name = "test"

experiment = mlflow.get_experiment_by_name(exp_name)
print(experiment)
if experiment:
    mlflow.delete_experiment(experiment.experiment_id)
else:
    mlflow.set_experiment(exp_name)
```

If the experiment has already been deleted and I use mlflow.delete_experiment to delete it permanently, I get the following error message:
```
<Experiment: artifact_location='mlflow-artifacts:/6', creation_time=1721743985125, experiment_id='6', last_update_time=1721743991258, lifecycle_stage='deleted', name='test', tags={}>
Traceback (most recent call last):
  File "/home/jenkins/data/./mlflow_test_delete_experiment.py", line 12, in <module>
    mlflow.delete_experiment(experiment.experiment_id)
  File "/home/jenkins/.local/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1760, in delete_experiment
    MlflowClient().delete_experiment(experiment_id)
  File "/home/jenkins/.local/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1329, in delete_experiment
    self._tracking_client.delete_experiment(experiment_id)
  File "/home/jenkins/.local/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 512, in delete_experiment
    self.store.delete_experiment(experiment_id)
  File "/home/jenkins/.local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 142, in delete_experiment
    self._call_endpoint(DeleteExperiment, req_body)
  File "/home/jenkins/.local/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 81, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/jenkins/.local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 304, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/jenkins/.local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 174, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: No Experiment with id=6 exists
```

I have this problem only when I use postgres as a backend store (`MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:PASSWORD@postgres/mlflow`), I don't have this problem if I use file as a backend store: `MLFLOW_BACKEND_STORE_URI=file:/data` 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@dmrub You can use `mlflow gc` to permanently delete runs in the `deleted` lifecycle. https://mlflow.org/docs/latest/cli.html?highlight=gc#mlflow-gc

**Comment by serena-ruan** [comment]
For the non-consistent behavior for sql backend store issue, I'll file a PR to fix it.

**Comment by dmrub** [comment]
> @dmrub You can use `mlflow gc` to permanently delete runs in the `deleted` lifecycle. https://mlflow.org/docs/latest/cli.html?highlight=gc#mlflow-gc

Yes, but as far as I understand, I can't run mlflow gc without access to the postgres backend. I want to run the garbage collection only with access to the tracking server and using its API.

**Comment by dmrub** [comment]
> For the non-consistent behavior for sql backend store issue, I'll file a PR to fix it.

Thank you !

**Comment by serena-ruan** [comment]
> > @dmrub You can use `mlflow gc` to permanently delete runs in the `deleted` lifecycle. https://mlflow.org/docs/latest/cli.html?highlight=gc#mlflow-gc
> 
> Yes, but as far as I understand, I can't run mlflow gc without access to the postgres backend. I want to run the garbage collection only with access to the tracking server and using its API.

Unfortunately this is impossible, if you don't have access to the backend you cannot hard delete anything from it.
You could recover the experiment to reuse the name, or choose a different name.
