### ISSUE TITLE
[BUG] Cannot load Scikit models with PyFunc flavor

### ISSUE THREAD

**Issue by rsayn** [mlflow/mlflow#12775]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client:  2.14.3
- Tracking server:  2.14.3

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS-14.5-arm64-arm-64bit
- **Python version**: 3.9.12
- **yarn version, if running the dev UI**: N/A

### Expected behavior

I should be able to log a model with the `sklearn` flavor, load it back with the `pyfunc` flavor and call `unwrap_python_model()` to retrieve the original model.

### Actual behavior

When calling `unwrap_python_model()` in the described scenario, an exception is raised.

### Tracking information

```shell
System information: Darwin Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
Python version: 3.9.12
MLflow version: 2.14.3
MLflow module location: /Users/rsayn/Library/Caches/pypoetry/virtualenvs/project-M-gywEHC-py3.9/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: file:///Users/rsayn/dev/project/mlruns
Registry URI: file:///Users/rsayn/dev/project/mlruns
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  alembic: 1.13.2
  cachetools: 5.4.0
  click: 8.1.7
  cloudpickle: 3.0.0
  docker: 7.1.0
  entrypoints: 0.4
  gitpython: 3.1.43
  graphene: 3.3
  gunicorn: 22.0.0
  importlib-metadata: 7.2.1
  markdown: 3.6
  matplotlib: 3.9.1
  numpy: 1.26.4
  opentelemetry-api: 1.16.0
  opentelemetry-sdk: 1.16.0
  packaging: 24.1
  pandas: 1.5.3
  protobuf: 4.25.3
  pyarrow: 15.0.2
  pytz: 2024.1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.32.3
  scikit-learn: 1.5.1
  scipy: 1.13.1
  sqlalchemy: 2.0.31
  sqlparse: 0.5.1
  virtualenv: 20.26.3
```

### Code to reproduce issue

```python
from sklearn.datasets import load_iris
from sklearn.svm import SVC
import mlflow

X, y = load_iris(return_X_y=True)
svc = SVC().fit(X, y)
with mlflow.start_run() as run:
    mlflow.sklearn.log_model(svc, "model")
    model = mlflow.pyfunc.load_model(f"runs:/{run.info.run_id}/model")
    loaded_svc = model.unwrap_python_model() # here is where it breaks
```

### Stack trace

```python
Traceback (most recent call last):
  File "/Users/rsayn/Library/Caches/pypoetry/virtualenvs/project-M-gywEHC-py3.9/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 872, in unwrap_python_model
    python_model = self._model_impl.python_model
AttributeError: '_SklearnModelWrapper' object has no attribute 'python_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rsayn/dev/project/main_ignore.py", line 13, in <module>
    loaded_svc = model.unwrap_python_model() # here is where it breaks
  File "/Users/rsayn/Library/Caches/pypoetry/virtualenvs/project-M-gywEHC-py3.9/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 876, in unwrap_python_model
    raise MlflowException("Unable to retrieve base model object from pyfunc.") from e
mlflow.exceptions.MlflowException: Unable to retrieve base model object from pyfunc.
```

### Other info / logs

```
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Pyfunc only works for sklearn model if it defines a `predict` function. Your model doesn't have a `predict` function so it cannot be loaded as pyfunc model. The workaround is to write your own custom pyfunc model, example: https://mlflow.org/docs/latest/traditional-ml/creating-custom-pyfunc/notebooks/index.html?

**Comment by rsayn** [comment]
No, that is definitely not the issue here. I can serialize the `SVC` with `mlflow.sklearn.log_model`, load it with `mlflow.pyfunc.load_model` AND predict with it, everything works. Note that `SVC` is a builtin SKLearn model.

What's failing is the call to `unwrap_python_model`, which is most definitely a bug.

**Comment by serena-ruan** [comment]
@rsayn Sorry for the confusion, I missed the stacktrace. 

For your problem, `unwrap_python_model` only works for python model wrapper, if you log a model with `mlflow.pyfunc.log_model` then it should work. But in your case you're logging with `mlflow.sklearn.log_model` which doesn't contain a python_model. You can use `model._model_impl..get_raw_model()` instead as a workaround.

The underlying model for different flavors are not all defined as `python_model`, and this `unwrap_python_model` method is meant to only work for pyfunc models.
We can add an API inside PyFuncModel named `get_raw_model` and try fetch the underlying raw model if it exists.

**Comment by rsayn** [comment]
I see your point, but isn't the `sklearn` flavor (and all other flavors) also supposed to log the model as `pyfunc`?

From the UI I see this:

![image](https://github.com/user-attachments/assets/024d1900-3886-44b1-99e4-fbcf1b7776ed)


As proof, I can perform this with an XGBoost model and it works just fine:

```python
import mlflow
import xgboost

with mlflow.start_run() as run:
    xgb = xgboost.XGBClassifier().fit(...)
    mlflow.xgboost.log_model(xgb, "model")
    loaded_xgb = mlflow.pyfunc.load_model(f"runs:/{run.info.run_id}/model")
    original_xgb = loaded_xgb.unwrap_python_model()
```

Then again, it should be a pretty quick and easy fix, I just need some feedback about how to approach this.

Otherwise I can just go ahead with a PR and move the discussion there 😄

**Comment by serena-ruan** [comment]
@rsayn I'm surprised if xgboost model works, because its underlying model is named `xgb_model` instead of `python_model`. The part you mentioned in the UI means the model can be loaded as pyfunc model, and it's true for almost all flavors. Filed a PR to get raw models in pyfunc, you could use this API instead after it's merged.

**Comment by rsayn** [comment]
@serena-ruan I realized it also breaks on XGBoost, yeah. However I'm pretty sure I did this a couple versions back and it worked, I'll check and get back to you
