### ISSUE TITLE
[DOC-FIX] MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD docs were (accidentally?) removed

### ISSUE THREAD

**Issue by ddl-ebrown** [mlflow/mlflow#12776]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://www.mlflow.org/docs/latest/tracking.html

### Description of proposal (what needs changing)

As noted in https://github.com/mlflow/mlflow/pull/10471#issuecomment-2248633266, that PR removed a bunch of really important details about `MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD` -- in both how to use it and how it works. I think it's important to call out because the server still maintains credentials for reading / writing the files, but clients actually perform the uploads. In this way, it can actually be a preferred approach when it's desirable to not give clients their own credentials, but to still allow their file uploads to scale horizontally rather than making the artifact server a performance bottleneck.

These docs were originally part of https://github.com/mlflow/mlflow/commit/d0062b2dbac7e4eb5013040c31ce1202dfb71865#diff-6eadaad38a8167d8665725f9405be4c742984310009aabaa11452d3dd1a11ef4R1204-R1237 which was merged just prior to the tracking server doc overhaul, so I suspect they were removed by accident.

It would also be good to document `MLFLOW_MULTIPART_UPLOAD_CHUNK_SIZE` and `MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE ` as they are relevant to how the client behaves.

**Comment by harupy** [comment]
@ddl-ebrown Thanks for reporting this. I'll fix.
