### ISSUE TITLE
[BUG] `mlflow.evaluate` function crash on binary classification evaluation

### ISSUE THREAD

**Issue by ehcalabres** [mlflow/mlflow#12790]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.11.1
- Tracking server: 2.11.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: 3.12.2
- **yarn version, if running the dev UI**:

### Describe the problem

I'm trying to evaluate model outputs for different binary classification problems but the function `mlflow.evaluate()` is crashing sometimes.

The problem that I'm facing is that for some unbalanced problems, when I call `evaluate()` with already precomputed predictions of different data subsets, sometimes I end up with a targets-predictions dataframe that only contains one of the labels (e.g. 0):

```
   target  prediction
0       0           0
1       0           0
...   ...         ...
n       0           0
```

By inspecting the `evaluate()` function, I've seen that docs say that:

```
For binary classification tasks, the negative label value must be 0 or -1 or False, and
the positive label value must be 1 or True.
```

But the problem is that there's no label `"1"` in the dataframe, so mlflow crashes with the Exception:

```
File "C:\Users\Enrique\miniconda3\envs\...\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1844, in _evaluate
    self._generate_model_predictions(compute_latency=compute_latency)
  File "C:\Users\Enrique\miniconda3\envs\...\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1447, in _generate_model_predictions
    f"{self.label_list[1]}, negative label is {self.label_list[0]}."
       ~~~~~~~~~~~~~~~^^^
IndexError: index 1 is out of bounds for axis 0 with size 1
```

It's trying to infer the labels from the target column, assuming that there will always be at least one representative of each one and `len(self.label_list) == 2`, but that's not the case.

Would it be possible to fix this so that, if it's a binary classification problem, it always completes the labels with the one that is missing?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import pandas as pd
import mlflow

data = pd.DataFrame({
    'target': [0, 0, 0, 0],
    'prediction': [0, 0, 0, 0]
})

results = mlflow.evaluate(
    data=data,
    model_type="classifier",
    targets="target",
    predictions="prediction",
)
```

### Stack trace

```
Traceback (most recent call last):
  File "c:\users\enrique\documents\development\ehcalabres\...\hpx_lab\experiments\base.py", line 720, in start
    self._pipeline_output = self.trial.pipeline.run(experience=self.experience,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\enrique\documents\development\ehcalabres\...\hpx_lab\experiments\base.py", line 392, in run
    evaluation, predictions = self._run_training(model=model,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\enrique\documents\development\ehcalabres\...\hpx_lab\experiments\base.py", line 536, in _run_training
    val_eval_result = evaluate(targets=self._get_targets(split=validation_data),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\enrique\documents\development\ehcalabres\...\hpx_lab\models\base.py", line 416, in evaluate
    evaluation_results[output['name']] = mlflow.evaluate(data=target_predictions_df,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enrique\miniconda3\envs\...\Lib\site-packages\mlflow\models\evaluation\base.py", line 2102, in evaluate
    evaluate_result = _evaluate(
                      ^^^^^^^^^^
  File "C:\Users\Enrique\miniconda3\envs\...\Lib\site-packages\mlflow\models\evaluation\base.py", line 1252, in _evaluate
    eval_result = evaluator.evaluate(
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enrique\miniconda3\envs\...\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1962, in evaluate
    evaluation_result = self._evaluate(model, is_baseline_model=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enrique\miniconda3\envs\...\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1844, in _evaluate
    self._generate_model_predictions(compute_latency=compute_latency)
  File "C:\Users\Enrique\miniconda3\envs\...\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1447, in _generate_model_predictions
    f"{self.label_list[1]}, negative label is {self.label_list[0]}."
       ~~~~~~~~~~~~~~~^^^
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @ehcalabres Could you address your data to make it contain two labels? Even if we get passed the error you mentioned above, there's only a single class in the dataset then we cannot calculate the confusion matrix.

**Comment by ehcalabres** [comment]
Hi @serena-ruan!

I could check if my data has only one label in the `targets` column and in that case don't call `evaluate`, but I'm not sure about that being the solution. 

The thing is that the problem actually has two classes, but some specific subsets only have one target class. While that is not the most common scenario, you should be able to compute the confusion matrix anyway, because predictions may have, for instance, both classes (and even with just one, or just the opposite). In those cases, this would work fine:

```
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix

data = pd.DataFrame({
    'target': [0, 0, 0, 0, 0, 0, 0],
    'prediction': [0, 1, 0, 0, 1, 0, 0]
})

tn, fp, fn, tp = confusion_matrix(data['target'],
                                  data['prediction'],
                                  labels=[0, 1]).ravel()

conf_matrix = confusion_matrix(data['target'],
                               data['prediction'],
                               labels=[0, 1])

print('True positives:', tp)
print('False positives:', fp)
print('True negatives:', tn)
print('False negatives:', fn)

fig, ax = plt.subplots()
cax = ax.matshow(conf_matrix)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()
```

Which leads to an output like:

```
True positives: 0
False positives: 2
True negatives: 5
False negatives: 0
```
![image](https://github.com/user-attachments/assets/f2de413a-1915-4c6f-9335-ec9864c11373)

So I'm thinking about something like this:

- Compute evaluator `label_list` based on both tagets and predictions columns instead of just the targets, following the behavior of the `confusion_matrix` function in [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html#:~:text=those%20that%20appear%20at%20least%20once%20in%20y_true%20or%20y_pred%20are%20used%20in%20sorted%20order). This will also fix another related error that I just faced: identifying problems as binary classification when they are actually multiclass classification (`targets` column may have just 2 classes and `predictions` may have `>2`), leading to a crash. I can provide another example of this if you find it necessary.
- If after that `len(label_list)` is still `<2`, assume that we are in a binary classification problem (that's the current implementation) and add to `label_list` the opposite label to the one founded (be 0 or 1).

I don't mind working on a PR that handles this situation, I think it's useful and the current state is a bit messy and lacks these checks.

Let me know what do you think, and thanks for the work! 🤗

**Comment by serena-ruan** [comment]
Thanks for the explanation @ehcalabres! I think you'll get error when computing confusion matrix if both target and predictions only contain one class, while that's a separate issue.

Another option is to manually specify the label list when you use `mlflow.evaluate`, you can use `evaluator_config={"default": {"pos_label": 1}}` to manually specify the positive label. Pls let me know if this helps.

For the multiclass issue, could you provide an example as I want to know where it crashes? I'm also wondering if it will be easier if users can directly pass label_list 🤔 
cc @prithvikannan if you have any thoughts on this

**Comment by ehcalabres** [comment]
Hey @serena-ruan! As long as you pass the `label_list` with both labels `[0, 1]`, computing the confusion matrix will work properly (just checked) if targets and predictions only have one class.

I've just tried passing the `pos_label` to the evaluator but I'm still getting the same error, so that wouldn't help.

Wrt multiclass clasification, I've found 2 issues so far, both happening when you pass a list of predictions with more classes than the ones founded in the targets list. So for instance:

### 1. Inferring binary classification for multiclass problems

```
import matplotlib.pyplot as plt
import mlflow
import pandas as pd
from sklearn.metrics import confusion_matrix

data = pd.DataFrame({
    'target': [2, 0, 2, 2, 0, 0, 0],
    'prediction': [0, 1, 2, 0, 1, 0, 0]
})

results = mlflow.evaluate(
    data=data,
    model_type="classifier",
    targets="target",
    predictions="prediction",
)
```

In this case, `mlflow.evaluate()` will mark the problem as binary classification (classes 0 and 2) instead of multiclass (classes 0, 1 and 2), and thus failing to extract `tn, fp, fn, tp`. See trace below:

```
File c:\Users\Enrique\miniconda3\envs\hpx-lab\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py:217, in _get_binary_classifier_metrics(y_true, y_pred, y_proba, labels, pos_label, sample_weights)
    [214](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:214) def _get_binary_classifier_metrics(
    [215](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:215)     *, y_true, y_pred, y_proba=None, labels=None, pos_label=1, sample_weights=None
    [216](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:216) ):
--> [217](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:217)     tn, fp, fn, tp = sk_metrics.confusion_matrix(y_true, y_pred).ravel()
    [218](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:218)     return {
    [219](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:219)         "true_negatives": tn,
    [220](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:220)         "false_positives": fp,
   (...)
    [231](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:231)         ),
    [232](file:///C:/Users/Enrique/miniconda3/envs/hpx-lab/Lib/site-packages/mlflow/models/evaluation/default_evaluator.py:232)     }

ValueError: too many values to unpack (expected 4)
```

### 2. Omiting classes in confusion matrix

```
import matplotlib.pyplot as plt
import mlflow
import pandas as pd
from sklearn.metrics import confusion_matrix

data = pd.DataFrame({
    'target': [2, 0, 2, 2, 0, 0, 1],
    'prediction': [0, 1, 2, 0, 1, 0, 3]
})

results = mlflow.evaluate(
    data=data,
    model_type="classifier",
    targets="target",
    predictions="prediction",
)

image = mlflow.artifacts.load_image(results.artifacts['confusion_matrix'].uri)
image.show()
```

Here, everything will run without crashing, but if you see the confusion matrix artifact generated, you will notice that class 3 is removed, as the `label_list` passed to sklearn is `[0, 1, 2]`.

![conf_matrix](https://github.com/user-attachments/assets/409b96be-0577-49d4-9bd1-c7171547c839)

To me, allowing the user to pass the `label_list` manually is a good thing to have, and it will solve these errors when provided. However, they will still emerge when no `label_list` is provided, so I would also try to implement some code to compute the `label_lsit` properly from both targets and predictions, as I mentioned before.
