### ISSUE TITLE
Is there any way to log MXNet model like mlflow.keras.log_model ?

### ISSUE THREAD

**Issue by Akashdesarda** [mlflow/mlflow#1280]
### System information
- **Linux Ubuntu 16.04**
- **MLflow installed from (pip)**: 
- **MLflow version (0.9.1)**:
- **Python version**: 3.5 

### Describe the problem
similair to mlflow.keras.log_model() or mlflow.pytorch.log_model() api, is there any api that I can used to log MXNet model.

**Comment by mateiz** [comment]
There's no built in way yet, but you can wrap them into a Python class and log that as described here: https://mlflow.org/docs/latest/models.html#custom-python-models. It would be great to add a built-in MXNet package if someone is willing to write that.

**Comment by cosmincatalin** [comment]
#1973

**Comment by sueann** [comment]
Looks like #1973 has been merged. @Akashdesarda does that PR address your concerns?

**Comment by Akashdesarda** [comment]
Yes it does

**Comment by sueann** [comment]
great, thanks!

**Comment by cosmincatalin** [comment]
@Akashdesarda , if you need any support with the Gluon implementation or have related question, I'm more than willing to help.

**Comment by Akashdesarda** [comment]
Sure thanks
