### ISSUE TITLE
[BUG] Unable to refresh model metrics on Experiment page (chart) or Run page (Model metrics tab) using refresh buttons

### ISSUE THREAD

**Issue by cnguyen10** [mlflow/mlflow#12839]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.15.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.10.12
- **yarn version, if running the dev UI**:  N/A

### Describe the problem

Currently, there are 2 refresh buttons: one is in Experiment page, and another is in Model metrics tab of Run page:
 - The refresh button in Experiment page can only refresh to get new data (metrics) whenever there is a new run. Otherwise, it will not get anything updated, except running duration and status of runs.
 - The refresh button in Model metrics tab of each Run page is supposed to refresh model metrics. However, pression on it does not refresh nor get anything updated.

The workaround solution is to refresh the whole webpage, which waste resources. It is better to have those two buttons work as expected.

### Steps to reproduce the bug

Here, a run is shown with 2 running steps, although the actual running step was 3 at the moment making the video. Pressing on either those buttons does not refresh metrics, but need to refresh the whole web page.

[Screencast from 30-07-24 17:02:09.webm](https://github.com/user-attachments/assets/37e1c929-cc05-471a-bf73-3262c30ce2b2)

**Comment by serena-ruan** [comment]
Thanks for reporting this @cnguyen10 ! cc @daniellok-db Could you take a look and fix this bug (if it's easy)?

**Comment by daniellok-db** [comment]
Thanks for reporting! I'll take a look!

**Comment by daniellok-db** [comment]
Yes it looks like that refresh button only fetches the runs. The metric fetching happens in the charts themselves for performance reasons, rather than at the page-level.

cc @hubertzub-db was there any discussion about putting a refresh button on a chart for on-demand metric fetching? and actually i guess we can probably enable these features already right?

https://github.com/mlflow/mlflow/blob/e944178852bb916e583cb02cc345cbbc262dae79/mlflow/server/js/src/common/utils/FeatureUtils.ts#L18-L20

**Comment by hubertzub-db** [comment]
@daniellok-db by design, enabling auto-refresh was also supposed to replace manual refresh completely (both for runs and metrics). We can enable those features, then runs and metrics should start refreshing automatically - then, the escape hatch to manually refresh everything is reloading the page.

**Comment by beomsun0829** [comment]
I just found out why the manual reload didn't work

When 'refreshMode' set all, it should filter nothing and 'skippedRunUuids' have to be empty array
but returning [] to filter, it makes filter everything and fill all the uuid to 'skippedRunUuids'

By returning false instead, I have confirmed that manual refresh is working well

https://github.com/mlflow/mlflow/blob/ee23704d8489ed5cdf48a3ee964898346e2dd89c/mlflow/server/js/src/experiment-tracking/sdk/SampledMetricHistoryService.ts#L49-L53
