### ISSUE TITLE
[DOC-FIX] change "LangChain Automatic Tracing" to "OpenAI Automatic Tracing" under OpenAI tab

### ISSUE THREAD

**Issue by djliden** [mlflow/mlflow#12830]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/llms/tracing/index.html#automatic-tracing

### Description of proposal (what needs changing)

The heading under the OpenAI tab for Automatic Tracing says "LangChain Automatic Tracing"—I assume this should be "OpenAI Automatic Tracing."

**Comment by serena-ruan** [comment]
Thanks for the catch @djliden! Please feel free to file a PR to fix it!
