### ISSUE TITLE
[BUG] llamaindex integration fails with external vector stores

### ISSUE THREAD

**Issue by pavanjava** [mlflow/mlflow#12856]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.15.0
- Tracking server: 1.3.5

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX 14.5
- **Python version**:3.11.4
- **yarn version, if running the dev UI**:

### Describe the problem

The Inference will work with the default `VectorStoreIndex.from_documents(docs)` but what if suppose we want to use some external vector_stores are preferred like Qdrant and Weaviate etc? The integration fails with below error

### Tracking information

```shell
╰─ mlflow server --backend-store-uri postgresql://root:root@localhost:5432/mlflow --default-artifact-root ./mlruns --host 127.0.0.1 --port 3000
/Users/pavanmantha/venv-metal/lib/python3.11/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
[2024-08-01 21:28:24 +0530] [22054] [INFO] Starting gunicorn 22.0.0
[2024-08-01 21:28:24 +0530] [22054] [INFO] Listening at: http://127.0.0.1:3000 (22054)
[2024-08-01 21:28:24 +0530] [22054] [INFO] Using worker: sync
[2024-08-01 21:28:24 +0530] [22055] [INFO] Booting worker with pid: 22055
[2024-08-01 21:28:24 +0530] [22056] [INFO] Booting worker with pid: 22056
[2024-08-01 21:28:24 +0530] [22057] [INFO] Booting worker with pid: 22057
[2024-08-01 21:28:24 +0530] [22058] [INFO] Booting worker with pid: 22058

```

### Code to reproduce issue

```
import os
from getpass import getpass

from llama_index.core import Document, VectorStoreIndex, Settings, SimpleDirectoryReader, StorageContext
from llama_index.core.text_splitter import SentenceSplitter
from llama_index.core.schema import TextNode, MetadataMode
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.llms.ollama import Ollama
from llama_index.llms.openai import OpenAI
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.embeddings.openai import OpenAIEmbedding
from dotenv import load_dotenv, find_dotenv
import qdrant_client
import mlflow

_ = load_dotenv(find_dotenv())
# os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API key: ")

embed_model = OllamaEmbedding(model_name=os.environ['OLLAMA_EMBED_MODEL'])
llm = Ollama(model=os.environ['OLLAMA_LLM_MODEL'])

# embed_model = OpenAIEmbedding(model=os.environ['OPENAI_EMBED_MODEL'])
# llm = OpenAI(model=os.environ['OPENAI_LLM_MODEL'])

Settings.embed_model = embed_model
Settings.llm = llm

# load the local data directory and chunk the data for further processing
print("------------- Example Document used to Enrich LLM Context -------------")
docs = SimpleDirectoryReader(input_dir="data", required_exts=[".pdf"]).load_data(show_progress=True)
text_parser = SentenceSplitter(chunk_size=512, chunk_overlap=100)

client = qdrant_client.QdrantClient(url="http://localhost:6333/", api_key="th3s3cr3tk3y")
vector_store = QdrantVectorStore(client=client, collection_name="research_papers")

Settings.transformations = [text_parser]

print("------------- vector store indexing -------------")
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(documents=docs,
                                        storage_context=storage_context,
                                        transformations=Settings.transformations,
                                        show_progress=True)

# index = VectorStoreIndex.from_documents(documents=docs)
print("------------- mlflow tracking start -------------")
mlflow.llama_index.autolog()  # This is for enabling tracing

mlflow.set_tracking_uri("http://127.0.0.1:3000")
mlflow.set_experiment("experiment-9")

with mlflow.start_run() as run:
    mlflow.llama_index.log_model(
        index,
        artifact_path="llama_index",
        # Defines the pyfunc and spark_udf inference type, Query Engine, Chat Engine, Retriever
        engine_type="query",
        input_example="What are Context LLMs?",  # Infers signature
        registered_model_name="my_llama_index_vector_store",  # Stores an instance in the model registry
    )

    run_id = run.info.run_id
    model_uri = f"runs:/{run_id}/llama_index"
    print(f"Unique identifier for the model location for loading: {model_uri}")

user_query: str = "What all datasets are mentioned in paper that are used for experimentation purpose?"

print("\n------------- Inference via Llama Index   -------------")
index = mlflow.llama_index.load_model(model_uri)
query_response = index.as_query_engine().query(user_query)
print(query_response)
```

### Stack trace

```
------------- Inference via Llama Index   -------------
Traceback (most recent call last):
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/serve_model.py", line 43, in <module>
    model = mlflow.pyfunc.load_model(model_uri)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/tracing/provider.py", line 237, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/pyfunc/__init__.py", line 1027, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/llama_index/__init__.py", line 367, in _load_pyfunc
    index = load_model(path)
            ^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/tracing/provider.py", line 241, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/llama_index/__init__.py", line 361, in load_model
    return _load_index(local_model_path, flavor_conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/mlflow/llama_index/__init__.py", line 325, in _load_index
    return load_index_from_storage(storage_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/llama_index/core/indices/loading.py", line 33, in load_index_from_storage
    indices = load_indices_from_storage(storage_context, index_ids=index_ids, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/llama_index/core/indices/loading.py", line 78, in load_indices_from_storage
    index = index_cls(
            ^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 78, in __init__
    super().__init__(
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 79, in __init__
    self._vector_store = self._storage_context.vector_store
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.11/site-packages/llama_index/core/storage/storage_context.py", line 264, in vector_store
    return self.vector_stores[DEFAULT_VECTOR_STORE]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'default'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [x] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@pavanjava Thank you for reporting the issue. Currently we only support default vector store and not external ones.
https://github.com/mlflow/mlflow/blob/182fdb5dcc5254b703d578eb53328b5eb56faff6/mlflow/llama_index/__init__.py#L324

Indeed, external vector store support is one of top priorities for this integration. Please remain attentive for further update! cc: @michael-berk @BenWilson2

**Comment by pavanjava** [comment]
Thanks for the update and keeping this as one of the priority items. The concern is the external vector stores offer you lot of features which the default vector store many do not offer so default vector store integration may not be helpful for developing full-fledged applications.

**Comment by pavanjava** [comment]
> @pavanjava Thank you for reporting the issue. Currently we only support default vector store and not external ones.
> 
> https://github.com/mlflow/mlflow/blob/182fdb5dcc5254b703d578eb53328b5eb56faff6/mlflow/llama_index/__init__.py#L324
> 
> Indeed, external vector store support is one of top priorities for this integration. Please remain attentive for further update! cc: @michael-berk @BenWilson2

Keep as a note in the documentation as well for now because documentation does not state about this.

**Comment by B-Step62** [comment]
> The concern is the external vector stores offer you lot of features which the default vector store many do not offer so default vector store integration may not be helpful for developing full-fledged applications.

Totally makes sense. We started the design and will get back to you once we have sth runnable.

> Keep as a note in the documentation as well for now because documentation does not state about this.

Absolutely, will add a note in the documentation.

**Comment by pavanjava** [comment]
Team, Is there any update on this ?

**Comment by B-Step62** [comment]
@pavanjava We have added the support for external vector store via "model-from-code" logging. Please refer to https://mlflow.org/docs/latest/llms/llama-index/index.html#how-to-log-and-load-an-index-with-external-vector-stores for the detailed guidance and examples!
