### ISSUE TITLE
JSON serialization in scoring server changes input data types

### ISSUE THREAD

**Issue by avflor** [mlflow/mlflow#1286]
The scoring server uses JSON serialization to serialize/deserialize input dataframes before passing them to the `predict` function for scoring. However, this way of serializing the data might result in data type changes.  Please see code below:

```
import pandas as pd
import numpy as np

df = pd.DataFrame([[1.0, 2.1], [3.1, 4.0]], columns=['col 1', 'col 2'])
print(df.dtypes)
df = df.astype(np.float32)
print(df.dtypes)
print(df.to_json())
df2 = pd.read_json(df.to_json(),orient='records', dtype=False)
print(df2)
print(df2.dtypes)
```

Output:
```
Python 3.6.1 (default, Dec 2015, 13:05:11)
[GCC 4.8.2] on linux
col 1    float64
col 2    float64
dtype: object
col 1    float32
col 2    float32
dtype: object
{"col 1":{"0":1.0,"1":3.0999999046},"col 2":{"0":2.0999999046,"1":4.0}}
   col 1  col 2
0    1.0    2.1
1    3.1    4.0
col 1    float64
col 2    float64
dtype: object
```

As you see the datatype  after deserializing from json is float64 even if the type was explicitly set to float32 before the serialization. The scoring server has similar behavior which can create problems for some models such as ONNX (see #1127).

I think we should use another serialization framework that preserves the representation. Maybe pickle?

**Comment by mateiz** [comment]
Yes, we'd love to add at least one binary format that preserves types better in addition to JSON. Have you looked into these and do you have a preference? One other thing we were thinking is to change the server to use gRPC, so it would be nice if we pick a format that works with that.

On a related note, we also need to decide whether we want models to declare a schema for their inputs or we want to leave it undeclared, as it is today. Asking them to declare a schema would create extra work for users, so it would be nice to support at least a couple of formats that don't need that.

**Comment by avflor** [comment]
@mateiz I did some preliminary research on the different serialization types for dataframes taking into account the following features: 1) binary vs text, 2) schema-first or not, and 3) compatibility with gRPC. Pandas dataframes has built-in support for converting dataframes to JSON, HDF5, parquet and CSV. It seems to me that using a self-describing binary file format such as HDF5 might be a good approach for serializing dataframes assuming we want to use one of the built-in serializers that pandas provides. Note that HDF5 is not schema-first (like protobufs) and preserves data types across serialization/deserialization.  

Connection to gRPC might be tricky as gRPC works mainly with protobufs and JSON. 
However, we can always serialize the dataframe in HDF5 (or any other self-describing binary format) , wrap it around a protobuf object with a fixed/immutable schema (e.g., 'data': bytes) and send it to the server through gRPC. Any thoughts?

**Comment by mateiz** [comment]
OK, makes sense. Another approach I've seen is to use protobuf but let the format within the protobuf itself be dynamic using enums (for example, see the data fields in https://github.com/SeldonIO/seldon-core/blob/master/proto/prediction.proto). Then it's compatible with gRPC and other libraries, but you can still have a mix of types of data. It would be good to do something simple here and not have to add lots of data types later. I'll see whether we can get some input from Seldon on this too.

**Comment by avflor** [comment]
I'm not sure I understand what the end goal is. Is the intention for the server to process not only dataframes but other types of data as well? If yes, then I can see how the enums would be useful in this context. 

But, if the server will only process pandas dataframes, then there are 3 possible approaches: 1) serialize the dataframe as a whole using one of the serialization methods that pandas provides, 2) serialize the dataframe column-by-column, 3) serialize the dataframe row-by-row. I can see the protobuf/enum approach being useful in 2 and 3 but I wonder what are the pros of this approach compared to 1.

**Comment by andremoeller** [comment]
Another option: dataframes can be serialized to NPY or NPZ format, which preserves dtype:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.asarray.html
https://www.numpy.org/devdocs/reference/generated/numpy.lib.format.html

This fits binary and schema-less requirements, but I do not know about gRPC support, other than wrapping serialized array in protobuf

**Comment by markusweimer** [comment]
> On a related note, we also need to decide whether we want models to declare a schema for their inputs or we want to leave it undeclared, as it is today.

Having at least an *optional* schema in the metadata of the model would be awesome for tooling: Imagine dropping a MLFlow model into your IDE of choice, and having datatypes for input and output auto-created for you. I believe CoreML enables this in XCode, and it removes a barrier of ML adoption by devs.

**Comment by mateiz** [comment]
Yup, it definitely makes sense to add an optional one. What data types do you think should be allowed in the schema btw?

**Comment by markusweimer** [comment]
> On a related note, we also need to decide whether we want models to declare a schema for their inputs or we want to leave it undeclared, as it is today.

Ideally, we allow all the base types, and a "record" type for composition. That way, code generation can happen at the level of generating classes for the composite type, and don't require a method with dozens of parameters.

I actually think that the DDL of protobuf / gRPC could be a good fit here: Code generators for many languages already exist, the DDL is expressive, there is little chance for support for it to disappear, ...

Another potential source of inspiration could be the Apache Arrow type system, as it seems to gain traction across different data science systems.

**Comment by mateiz** [comment]
Both (nested) record types and Arrow are pretty complex, so I was hoping for something simpler. For example, maybe make the type be a record with named fields, which can be one of {int, double, double[], byte[], string} or something like that. Then these can be represented in many ML libraries and many existing data formats. I noticed that TF Serving and Seldon only have very simple types too, and people seem to be doing fine with those (at least for deep learning).

**Comment by markusweimer** [comment]
Yes, but deep learning is much simpler than full pipelines in terms of the data types involved. I believe we can get away without nested records. But a single *named* record would be required. That way, the codegen knows what to call the generated type.

**Comment by nicocti** [comment]
gRPC / protobuf makes more sense than serializing JSON. I also think that static typing cannot be avoided for both reliability of the model server, and performance tuning of serialization. AFAIK tensorflow serving is using it (google stuff obviously...).

**Comment by nicocti** [comment]
Apache Arrow Flight could also be investigated. I need to dig a bit on my side to get the ins ant outs of it but it seems to offer a standard data-oriented gRPC protocol (+ using arrow so compatible with pandas). https://www.dremio.com/understanding-apache-arrow-flight/

**Comment by nicocti** [comment]
@wesm would you recommand trying to implement Arrow Flight as a new API protocol for MLFlow model serving besides the json-based rest api ?

**Comment by aarondav** [comment]
I did a [survey of a few the serving frameworks available](https://docs.google.com/document/d/1ly3bLczrwqCauqzQURopw8UpUdK0mniG0rXAagPmC2k/edit#heading=h.sxxyogx14x9f), including Seldon, TensorFlow Serving, and the potential for Arrow Flight. Please read through and give feedback on that doc; the TL;DR strawman proposal is to extend our existing HTTP/1.2 API with a binary, protobuf-backed format.

I am working on creating a concrete protobuf/JSON/Python API proposal as well, which will take into account our existing serving format schema and improved support for (possibly multiple) tensors.

**Comment by mazzma12** [comment]
@aarondav for an example of implementation of protobuf format with tensor you might want to take a look at [onnxruntime](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxRuntimeServerSSDModel.ipynb) (not mentionned in your list)
