### ISSUE TITLE
[BUG] Error when logging batch of metrics via mlflow.log_metrics

### ISSUE THREAD

**Issue by cnguyen10** [mlflow/mlflow#12870]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.15.0
- Tracking server: 2.15.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.10.12
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When logging a batch of metrics `mlflow.log_metrics`, mlflow raises an exception:
```
mlflow.exceptions.MlflowException: Got invalid value 1.0 for metric 'x' (timestamp=1722625307265). Please specify value as a valid double (64-bit floating point)
```

Logging each metric separately using `mlflow.log_metric` works fine.

### Tracking information

N/A

### Code to reproduce issue

```python
import numpy as np
import mlflow

x = np.array(1.)
y = np.array(2.)

with mlflow.start_run():
     # this won't work
    mlflow.log_metrics(metrics={'x': x, 'y': y}, step=1)

    # but this works
    mlflow.log_metric(key='x', value=x, step=1)
    mlflow.log_metric(key='y', value=y, step=1)
```

### Stack trace

```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/n10/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 916, in log_metrics
    return MlflowClient().log_batch(
  File "/home/n10/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1846, in log_batch
    return self._tracking_client.log_batch(
  File "/home/n10/venv/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 732, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "/home/n10/venv/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 1070, in log_batch
    metrics, params, tags = _validate_batch_log_data(metrics, params, tags)
  File "/home/n10/venv/lib/python3.10/site-packages/mlflow/utils/validation.py", line 345, in _validate_batch_log_data
    _validate_metric(metric.key, metric.value, metric.timestamp, metric.step)
  File "/home/n10/venv/lib/python3.10/site-packages/mlflow/utils/validation.py", line 156, in _validate_metric
    raise MlflowException(
mlflow.exceptions.MlflowException: Got invalid value 1.0 for metric 'x' (timestamp=1722625307265). Please specify value as a valid double (64-bit floating point)
```

### Other info / logs

N/A

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by beomsun0829** [comment]
https://github.com/mlflow/mlflow/blob/4a7ea20a3e8603e00bae9724193c56436ff27bd9/mlflow/tracking/_tracking_service/client.py#L673

metrics.value should be float type, but in log_batch function value still remains np array type.

https://github.com/mlflow/mlflow/blob/4a7ea20a3e8603e00bae9724193c56436ff27bd9/mlflow/tracking/_tracking_service/client.py#L559-L562

I applied convert_metric_value_to_float_if_possible function to metric.value and checked out your code works well after my fix

after complete test, I will PR my code soon
