### ISSUE TITLE
[BUG] The Device parameter has no effect when loading an existing model from the registry with MLflow > 2.3.1

### ISSUE THREAD

**Issue by dennisschultz-db** [mlflow/mlflow#12871]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

> 2.3.1  (tested with 2.9.2 and 2.13.1)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

I'm updating some older code that runs fine on Databricks runtime 13.1 (MLflow 2.3.1), but not on newer runtimes such as 14.3 (MLflow 2.9.2) or 15.4 Beta (MLflow 2.13.1).  I've tracked down the issue to loading the transformer model.  The model was trained on a GPU, but it needs to be loaded and run on a CPU endpoint. I've provided a minimal snippet that demonstrates the issue.

In DBR 13.1, the display statement returns `device(type='cpu')`.  In DBR 14.3, it returns `device(type='cuda', index=0)`

This is preventing me from wrapping the model and serving it on a CPU-only Databricks model serving endpoint.

I have tried `pipeline_cpu.model = pipeline_cpu.model.cpu()`, but this causes other issues with the input image data not being on the CPU.

### Code to reproduce issue

```python
import mlflow
import torch

model_uri = "models:/<path-to-model>"

pipeline_cpu = mlflow.transformers.load_model(
  model_uri, 
  return_type="pipeline", 
  device=torch.device("cpu").index)
display(pipeline_cpu.device)
```

### Stack trace

```
/root/.ipykernel/39407/command-1643111387547108-131983805:7: FutureWarning: The 'transformers' MLflow Models integration is known to be compatible with the following package version ranges: ``4.25.1`` -  ``4.35.2``. MLflow Models integrations with transformers may not succeed when used with package versions outside of this range.
  pipeline_cpu = mlflow.transformers.load_model(
/databricks/python/lib/python3.10/site-packages/mlflow/store/artifact/utils/models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.9.2/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
 
/databricks/python/lib/python3.10/site-packages/mlflow/store/artifact/utils/models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.9.2/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
2024/07/27 19:46:04 INFO mlflow.transformers: 'models:/dbdemos_pcb_classification/Production' resolved as 'dbfs://databricks/databricks/mlflow-registry/9e0fe40de9e0416b8118416ced05ad2e/models/model'


2024-07-27 19:46:06.278234: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-27 19:46:06.324822: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-27 19:46:06.324859: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-27 19:46:06.324887: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-27 19:46:06.333386: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/databricks/python/lib/python3.10/site-packages/transformers/models/vit/feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(

device(type='cuda', index=0)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@dennisschultz-db Could you try setting environment variable MLFLOW_DEFAULT_PREDICTION_DEVICE="cpu"? I think it's because `torch.device("cpu").index` is None and in such case we automatically detect if gpu is available, but setting the environment variable should work

**Comment by dennisschultz-db** [comment]
@serena-ruan , thanks for looking into this.  Unfortunately, setting MLFLOW_DEFAULT_PREDICTION_DEVICE="CPU" does not seem to change the behavior.  I have set the variable both at the cluster level and in the notebook using os.environ.  I have also tried different values for the device parameter of the load_model() call including "cpu", -1, and removing it entirely.  The value of `pipeline_cpu.device` is still always `device(type='cuda', index=0)`

**Comment by dennisschultz-db** [comment]
Hi, @serena-ruan .  Any more thoughts on this?  The behavior seems to be oddly dependent on the mlflow version AND the device parameter value, but I cannot find a combination that works with recent versions of mlflow.

- mlflow==2.3.1, device=torch.device("cpu").index
   -   output: `device(type='cpu')`
- mlflow==2.3.1, device=torch.device("cpu")
   -   output: `device(type='cpu')`
- mlflow==2.3.1, device=-1
   -   output: `device(type='cpu')`

- mlflow==**2.3.2**, device=torch.device("cpu").index
   -   output: `device(type='cuda', index=0)`
- mlflow==**2.3.2**, device=torch.device("cpu")
   -   output: `device(type='cpu')`
- mlflow==**2.3.2**, device=-1
   -   output: `device(type='cpu')`

- mlflow==**2.9.2 (and above)**, device=torch.device("cpu").index
   -   output: `device(type='cuda', index=0)`
- mlflow==**2.9.2 (and above)**, device=torch.device("cpu")
   -   output: `device(type='cuda', index=0)`
- mlflow==**2.9.2 (and above)**, device=-1
   -   output: `device(type='cuda', index=0)`

So it seems that removing the index attribute from torch.device("cpu") did, in fact, cause it to work for version 2.3.2, but does not help in newer versions. Setting the environment variable MLFLOW_DEFAULT_PREDICTION_DEVICE seems to have no effect.

**Comment by serena-ruan** [comment]
Could you try not passing device when load the model, and only set MLFLOW_DEFAULT_PREDICTION_DEVICE?

**Comment by serena-ruan** [comment]
Update: could you try setting env variable MLFLOW_HUGGINGFACE_USE_DEVICE_MAP to False? Just noticed you've tried device=-1, so probably this is the cause

**Comment by dennisschultz-db** [comment]
@serena-ruan , thanks for this.  setting `MLFLOW_HUGGINGFACE_USE_DEVICE_MAP` to False does seem to do the trick.  I'm still using the parameter `device=torch.device("cpu")`, although I'm not sure that has any effect now.

Is this a bug in the device parameter handling, or is using this environment variable the preferred way to force the load_model to cpu?

**Comment by serena-ruan** [comment]
Thanks for the confirmation @dennisschultz-db! device=torch.device("cpu") should be the correct usage, MLFLOW_DEFAULT_PREDICTION_DEVICE is used when device is None, and if device is None and the env variable is not set, we check if gpu is available and has a fallback. 
Seems like we have a bug that when MLFLOW_HUGGINGFACE_USE_DEVICE_MAP is set (default to True) then we always reset device to None, let me talk to the team who made this change to avoid breaking them, then we'll fix it.
