### ISSUE TITLE
[BUG]  No such file or directory serving_input_payload.json error in Artifacts tab

### ISSUE THREAD

**Issue by beomsun0829** [mlflow/mlflow#12878]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

version 2.15.1.dev0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: Python 3.10.11
- **yarn version, if running the dev UI**: Yarn 4.3.1

### Describe the problem

After saving model with mlflow.pytorch.log_model,
when enter in to run_name/Artifacts, several error message from Flask comes out.

It seems that this error not produces serious problem, but bunch of error message at console feels uncomfortable

### Tracking information

```shell
System information: Windows 10.0.22631
Python version: 3.12.4
MLflow version: 2.15.1.dev0
MLflow module location: [D:\PROGRAMMING\mlflow\mlflow\__init__.py](file:///D:/PROGRAMMING/mlflow/mlflow/__init__.py)
Tracking URI: file:///D:/PROGRAMMING/MLFlow_Contribute/mlruns
Registry URI: file:///D:/PROGRAMMING/MLFlow_Contribute/mlruns
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.3
  alembic: 1.13.2
  docker: 7.1.0
  graphene: 3.3
  markdown: 3.6
  matplotlib: 3.9.1
  mlflow-skinny: 2.15.0
  numpy: 1.26.3
  pandas: 2.2.2
  pyarrow: 15.0.2
  querystring-parser: 1.2.4
  scikit-learn: 1.5.1
  scipy: 1.14.0
  sqlalchemy: 2.0.31
  virtualenv: 20.26.3
  waitress: 3.0.0
```

### Code to reproduce issue

```
import mlflow
from dataclasses import dataclass, asdict

import torch
import torch.nn as nn
import numpy as np

from time import sleep

print(os.path.dirname(mlflow.__file__))

@dataclass
class Config:
    EPOCHS: int = 100
    LEARNING_RATE: int = 0.1

CONFIG = Config()

mlflow.set_experiment('Test')
def mlflow_run_decorator(run_name=None):
    def decorator(func):
        def wrapper(*args, **kwargs):
            mlflow.start_run(run_name=run_name)
            try:
                result = func(*args, **kwargs)
                mlflow.set_tag("Status", "SUCCEESS")
            except Exception as e:
                mlflow.log_param("Exception", e)
                mlflow.set_tag("Status", "FAIL")
                raise e
            finally:
                mlflow.end_run()
            return result
        return wrapper
    return decorator

X = np.random.rand(100, 1)
y = 1 + 2 * X + .1 * np.random.randn(100, 1)

class LinearRegression(nn.Module):
    def __init__(self):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = LinearRegression()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=CONFIG.LEARNING_RATE)

@mlflow_run_decorator(run_name='Model_Save_Issue')
def train_model():
    mlflow.log_params(asdict(CONFIG))
    
    for epoch in range(CONFIG.EPOCHS):
        inputs = torch.from_numpy(X.astype(np.float32))
        labels = torch.from_numpy(y.astype(np.float32))

        outputs = model(inputs)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        mlflow.log_metric('loss', loss.item(), step=epoch)
        
        if epoch % 100 == 0:
            print(f'Epoch {epoch}/{CONFIG.EPOCHS}, Loss: {loss.item()}')
    
        sleep(0)
    
    mlflow.pytorch.log_model(model, "My_Model")

train_model()
```

### Stack trace

```
2024/08/04 13:35:25 ERROR mlflow.server: Exception on /get-artifact [GET]
Traceback (most recent call last):
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\__init__.py", line 74, in serve_artifacts
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\__init__.py", line 74, in serve_artifacts
    return get_artifact_handler()
    return get_artifact_handler()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\handlers.py", line 566, in wrapper
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\handlers.py", line 566, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\handlers.py", line 633, in get_artifact_handler
    return _send_artifact(artifact_repo, artifact_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\handlers.py", line 554, in _send_artifact
    file_path = os.path.abspath(artifact_repository.download_artifacts(path))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 91, in download_artifacts
    raise OSError(f"No such file or directory: '{local_artifact_path}'")
OSError: No such file or directory: 'D:\PROGRAMMING\MLFlow_Contribute\mlruns\524980164502243114\7d5bf6dfb76f420bb11a5306ad2d2ae9\artifacts\My_Model\serving_input_payload.json'
```

### Other info / logs

```
# Tracking which file called at artifact tab

artifact_repo : <mlflow.store.artifact.local_artifact_repo.LocalArtifactRepository object at 0x0000020837120EE0>
artifact_path : My_model/serving_input_example.json
artifact_repo : <mlflow.store.artifact.local_artifact_repo.LocalArtifactRepository object at 0x0000020837120730>
artifact_path : My_model/MLmodel
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by beomsun0829** [comment]
'serving_input_payload.json' not saving when mlflow.pytorch.log_model

Is this file actually need? 

![image](https://github.com/user-attachments/assets/58078f58-b1bd-4671-b83f-2918ab530b9f)

**Comment by serena-ruan** [comment]
Hi @beomsun0829 Which version of MLflow UI are you using? BTW I can't repro your problem using the same code snippet from mlflow master 
<img width="1711" alt="image" src="https://github.com/user-attachments/assets/9b74e8f5-76dc-40f6-b883-ef05b2e2b90c">

Could you take a screen recording to show the problem if possible?

**Comment by beomsun0829** [comment]
There's no problem at UI, but I can see error messages on console (after turn server [mlflow ui], go to artifacts )

I also tested both release(2.15.0) and dev(2.15.1) version, but I can see same error, serving_input_payload.json not exists when I logging model

Some warnings printed out on console when execute mlflow.pytorch.log_model
```
2024/08/06 01:05:28 WARNING mlflow.utils.requirements_utils: Found torch version (2.3.1+cu121) contains a local version label (+cu121). MLflow logged a pip requirement for this package as 'torch==2.3.1' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2024/08/06 01:06:16 WARNING mlflow.utils.requirements_utils: Found torch version (2.3.1+cu121) contains a local version label (+cu121). MLflow logged a pip requirement for this package as 'torch==2.3.1' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2024/08/06 01:06:20 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.
```


Below error messages are occur when I open artifacts tab, on console.

```
2024/08/06 01:20:36 ERROR mlflow.server: Exception on /get-artifact [GET]
Traceback (most recent call last):
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\__init__.py", line 74, in serve_artifacts
    return get_artifact_handler()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\handlers.py", line 566, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\handlers.py", line 633, in get_artifact_handler
    return _send_artifact(artifact_repo, artifact_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\server\handlers.py", line 554, in _send_artifact
    file_path = os.path.abspath(artifact_repository.download_artifacts(path))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 91, in download_artifacts
    raise OSError(f"No such file or directory: '{local_artifact_path}'")
OSError: No such file or directory: 'D:\PROGRAMMING\MLFlow_Contribute\mlruns\399939669739484606\aba4f013c420418f976afc05e0e618da\artifacts\My_Model\serving_input_payload.json'
```


![image](https://github.com/user-attachments/assets/7b976770-c9eb-4c1f-881b-28de9ef6ec59)

Is this just a version mismatch problem?

**Comment by serena-ruan** [comment]
This is so weird, I can't repro your issue. Could you check several things: 
1. which MLflow UI version are you using? It's the number showing on the top left corner. 
2. Use devtools when you click to artifacts tab, and share the details of the request & response here (It's better if you could clean up the experiment and only include this specific run)

<img width="657" alt="image" src="https://github.com/user-attachments/assets/05af6944-7a50-4feb-b1ee-04024ddb7164">

3. Try navigate to mlflow/server/js folder and run `yarn install` then `yarn start` to use UI from master branch, then see if you  still get the issue.

**Comment by beomsun0829** [comment]
1. mlflow version is 2.15.0

2. screenshots below
![image](https://github.com/user-attachments/assets/e8bc33a8-ea94-4958-bcd2-bd249197835c)
![image](https://github.com/user-attachments/assets/ba3d9898-efe9-4111-b8ba-6890bf8d0a4b)

unlike your screenshot, mine requests 
```http://127.0.0.1:5000/get-artifact?path=My_Model%2Fserving_input_payload.json&run_uuid=304c4e87bce34c57923601a9ab38134e```

3. I also tried 2.15.1.dev0 version but could see same error
![image](https://github.com/user-attachments/assets/aa8a2721-80fc-4895-960f-0cfa3e85991d)

**Comment by Dundrevialdo** [comment]
I have the same issue. I used an sklearn model. I run MLFlow locally with 'mlflow server' and after logging the model using mlflow.sklearn.autolog() I just visit the Artifacts tab under the experiment in UI. The same error appears in my console.

Win11
mlflow 2.15.0
python: 3.10.4
build_dependencies:
- pip==22.3.1
- setuptools==65.5.1
- wheel==0.38.4

**Comment by beomsun0829** [comment]
Great, I will close this issue than.

**Comment by serdar-akyol** [comment]
I also have same issue
Ubuntu 22.04LTS
MLFlow: 2.15.1
Python: 3.10.12

build_dependencies:
- pip==24.2
- setuptools
- wheel==0.40.0
