### ISSUE TITLE
experiment_id expected to be a str but is an integer in runs table

### ISSUE THREAD

**Issue by rugeer** [mlflow/mlflow#1288]
As we can see, object is converted to str only when its an instance of SqlExperiment class, but we need to convert it to str when its an instance of SqlRun as well:

https://github.com/mlflow/mlflow/blob/cde6da6fa554b5b2b4f404f0feff5ffa58b9140d/mlflow/store/dbmodels/models.py#L65

When using rest store, an error occurs when trying to get_run, list_run_infos, etc, because experiment_id is an integer in the runs table, whereas it is expected to be a string

Temporary solution I used:
`if k == "experiment_id":`

**Comment by dbczumar** [comment]
Fixed in #1187. See https://github.com/mlflow/mlflow/blob/9a8ee6cde189206d65be76b0b62e5fe46a1422aa/mlflow/store/dbmodels/models.py#L163.
