### ISSUE TITLE
[FR] Update how langchain objects are saved/loaded

### ISSUE THREAD

**Issue by felipemonroy** [mlflow/mlflow#12896]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

At the moment objects such as `langchain_openai.ChatOpenAI` and `langcain_aws.BedrockChat` are serialize as yaml files using de `.dict()` method. Then, the objects are loaded again using `langchain_community.llms.loading.load_llm`, which seems to be deprecated in favor of https://python.langchain.com/v0.2/docs/how_to/serialization/. For instance, this type of de-serialization for `BedrockChat` is not supported.

### Motivation

> #### What is the use case for this feature?
Support new serialization. I tried to include BedrockChat with the current de-serialization with no luck https://github.com/langchain-ai/langchain/issues/25086

> #### Why is this use case valuable to support for MLflow users in general?
It is recommended way of serializing and de-serializing langchain objects.

> #### Why is this use case valuable to support for your project(s) or organization?
We are currently using `langcain_aws.BedrockChat`, which can't be serialized with the current way of doing it.

> #### Why is it currently difficult to achieve this use case?
It is not implemented.

### Saving
Add the new serialization when the old one fails, adding a warning that old serialization will be deprecated. This could be done here:

https://github.com/mlflow/mlflow/blob/ed0d1f3f585e1bd6dd76add2385ee82d920c394a/mlflow/langchain/runnables.py#L247-L265

 ### Loading
 Add the new de-serialization when the config object contains the key `type=="constructor"`. That could be done here:
 
 https://github.com/mlflow/mlflow/blob/ed0d1f3f585e1bd6dd76add2385ee82d920c394a/mlflow/langchain/runnables.py#L71-L85

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
cc @serena-ruan any thoughts about using the langchain_core save/load functions? i feel like i remember some discussion about this before—do they support all the things we need to support? their docs say it supports "most" runnables

**Comment by B-Step62** [comment]
@felipemonroy Thank you for raising the issue. Unfortunately, we cannot migrate to the new serialization format right now as its limitation is still significant. The biggest unsupported class is `RunnableLambda`, which is very widely used in chains written with RCEL (and not trivial to serialize). Please see the discussion in https://github.com/mlflow/mlflow/pull/12931#issue-2462787905 as well.

The practical solution we recommend is the [model-from-code](https://mlflow.org/docs/latest/models.html#models-from-code) approach. It does not require serializing objects and thus more robust and has better coverage. This should unblock you to log a chain with `langcain_aws.BedrockChat`. Please let us know if you have any further issue!
