### ISSUE TITLE
[BUG] Deleting orphaned artifacts 

### ISSUE THREAD

**Issue by cile98** [mlflow/mlflow#12917]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Mlflow: 2.15.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.10
- **yarn version, if running the dev UI**:

### Describe the problem

The latest update finally solved the issue with deleting artifacts from s3 storage (https://github.com/mlflow/mlflow/pull/12451), but it doesn't handle orphaned artifacts - the ones that weren't deleted if `mlflow gc` was used prior to `2.15.0` update. Would it be possible to add functionality to delete those too? 

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by WeichenXu123** [comment]
emm, then we don't have good way, maybe we have to manually find out these orphaned artifacts and delete them manually

**Comment by cile98** [comment]
> emm, then we don't have good way, maybe we have to manually find out these orphaned artifacts and delete them manually

Do you have an idea how to manually find those? Always found mlflow naming of directories rather random, don't know where the mapping to actual experiments is

**Comment by WeichenXu123** [comment]
MLFlow artifacts path are like `{experiment_id}/{run_id}/artifacts`, so if you have deleted the specific runs or experiments, the artifact directory can be safely deleted. You can use MLflow client API to traverse all experiments and runs.

**Comment by WeichenXu123** [comment]
You need to be very careful when you doing this . You need to double check `{experiment_id}/{run_id}/artifacts` path is under the correct mlflow backend store root path that matches your MLflow tracking URI you used in MLflow client.

**Comment by cile98** [comment]
Thanks for the pointers, wrote a script for doing so, and will share here high-level details in case someone else finds this useful: 
```
import mlflow 

mlflow.set_tracking_uri(<MLFLOW_URI>)
saved_experiments = get_saved_experiments() # you need to implement this based on your artifact store
safe_to_delete_runs = []
for experiment_id in saved_experiments:
    saved_runs = get_saved_runs(experiment_id)  # you need to implement this based on your artifact store
    for run_id in saved_runs:
        existing_runs = mlflow.search_runs(experiment_ids=[experiment_id] , filter_string=f"attributes.run_id = '{run_id}'")
        if existing_runs.shape[0] == 0: # runs with such id don't exist
            safe_to_delete_runs.append([experiment_id, run])
delete_orphaned_artifacts(safe_to_delete_runs) # you need to implement this based on your artifact store
```
