### ISSUE TITLE
sklearn pipeline custom transformers can't be in different module

### ISSUE THREAD

**Issue by joshpeng** [mlflow/mlflow#1291]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**: 3.7.3

### Describe the problem
When trying to deploy a sklearn pipeline pickle which has steps that are of functions imported from other modules (not in the same main program file), MLflow doesn't add it to the Docker container for Sagemaker and thus ends up running into errors on loading the pickled pipeline with a `No module named 'xyz'` error.

```
ModuleNotFoundError: No module named 'preprocessing'
```

How can we get the Docker to store our custom module files too?

**Comment by joshpeng** [comment]
This is not stale :( definitely very much still an issue.

**Comment by ustcscgyer** [comment]
@joshpeng I can take a look at this issue, but can you provide more information so I can reproduce the error?

**Comment by DanyalAndriano** [comment]
Same issue....@joshpeng did you find a solution?

**Comment by vivian-usc-2009** [comment]
Hi @joshpeng  , is this problem solved? I am facing the same issue and would like to see your solution. Thanks!
