### ISSUE TITLE
[BUG] Error creating a run manually

### ISSUE THREAD

**Issue by Danniilpz** [mlflow/mlflow#12920]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No, I can't contribute at this time.

### MLflow version

- Client: 2.15.1
- Tracking server: 2.14.3

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**: 3.12
- **yarn version, if running the dev UI**:

### Describe the problem

When manually creating a MlflowClient, Experiment and Run, an error is raised:
![image](https://github.com/user-attachments/assets/25737b4b-e6dc-41d7-a9fb-1bff62e46ca4)
I was creating the instances manually in order to try to use MLFlow with multithreading, creating an indepent run per thread.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
from mlflow import MlflowClient
from mlflow.entities import Experiment, Run

client: MlflowClient = MlflowClient(tracking_uri="...")
experiment: Experiment = mlflow.set_experiment("Example")
run: Run = client.create_run(experiment_id=str(experiment.experiment_id))
client.log_metric(run_id=run.info.run_id, key="metric", value=1.0)
```

### Stack trace

```
Traceback (most recent call last):
  File "\project\scripts\testing.py", line 9, in <module>
    run: Run = client.create_run(experiment_id=str(experiment.experiment_id))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\project\env\Lib\site-packages\mlflow\tracking\client.py", line 393, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\project\env\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 167, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "\project\env\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 208, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\project\env\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 81, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\project\env\Lib\site-packages\mlflow\utils\rest_utils.py", line 362, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\project\env\Lib\site-packages\mlflow\utils\rest_utils.py", line 232, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.NumericValueOutOfRange) value "704313527135806737" is out of range for type integer
LINE 3: WHERE experiments.experiment_id = '704313527135806737' AND e...
                                          ^

[SQL: SELECT experiments.experiment_id AS experiments_experiment_id, experiments.name AS experiments_name, experiments.artifact_location AS experiments_artifact_location, experiments.lifecycle_stage AS experiments_lifecycle_stage, experiments.creation_time AS experiments_creation_time, experiments.last_update_time AS experiments_last_update_time 
FROM experiments 
WHERE experiments.experiment_id = %(experiment_id_1)s AND experiments.lifecycle_stage IN (%(lifecycle_stage_1_1)s, %(lifecycle_stage_1_2)s)]
[parameters: {'experiment_id_1': '704313527135806737', 'lifecycle_stage_1_1': 'active', 'lifecycle_stage_1_2': 'deleted'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
How did you create the experiment ?

We set experiment ID to be autoincrement, https://github.com/mlflow/mlflow/blob/7c835d405131ca4885b51b7a715a90197e00b3b3/mlflow/store/tracking/dbmodels/models.py#L63

so it should start from `1` and increase one by one. How does it grow to so large value ?

**Comment by beomsun0829** [comment]
Can you delete tracking_uri parameter temporally? all experiment data will be saved in "mlruns" instead

alternative code:
```
import mlflow
from mlflow import MlflowClient
from mlflow.entities import Experiment, Run

client: MlflowClient = MlflowClient()
experiment: Experiment = mlflow.set_experiment("Example")
run: Run = client.create_run(experiment_id=str(experiment.experiment_id))
client.log_metric(run_id=run.info.run_id, key="metric", value=1.0)
```

**Comment by beomsun0829** [comment]
https://github.com/mlflow/mlflow/blob/7c835d405131ca4885b51b7a715a90197e00b3b3/mlflow/tracking/fluent.py#L133C5-L148C14

MlflowClient recreated in set_experiment, so your client with path will be ignored

**Comment by Danniilpz** [comment]
The problem was the one indicated by @beomsun0829  .I finally solved it this way:
`import mlflow
from mlflow import MlflowClient
from mlflow.entities import Experiment, Run

mlflow.set_tracking_uri(tracking_uri="...")
experiment: Experiment = mlflow.set_experiment("Example")
run: Run = MLFlowClient().create_run(experiment_id=str(experiment.experiment_id))
client.log_metric(run_id=run.info.run_id, key="metric", value=1.0)`
