### ISSUE TITLE
[BUG] logging langchain model fails due to large mlflow.models.ModelConfig

### ISSUE THREAD

**Issue by harshilprajapati96** [mlflow/mlflow#12926]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.15.1
- Tracking server: 2.15.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Apple M2 Pro MacOS 14.5
- **Python version**: 3.11.7
- **yarn version, if running the dev UI**: 

### Describe the problem

I have langchain `chain_as_a_code.py` with
```
from mlflow.models import ModelConfig

base_config = ModelConfig(development_config="./config.yaml")
...
...

mlflow.set_model()chain
```
and  `config.yaml` has 
```
param1: ...
param2: ...
prompt_template: <really long prompt>
```

When the prompt template is really long, when i run the following with `logging.getLogger("mlflow").setLevel(logging.DEBUG)` 
```
logged_chain_info = mlflow.langchain.log_model(
            lc_model="chain_as_a_code.py",
            artifact_path="chain",
            model_config="config.yaml",=
        )
```
It throws error 
```
mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(5000)

[SQL: INSERT INTO tags (key, value, run_uuid) VALUES (%(key)s, %(value)s, %(run_uuid)s)]
```

It logs the code properly and I can load it properly as well but the `Artifacts` tab is blank
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/d8e8e5e1-40d0-49fd-9b75-3f436c9dd248">
and `Models` coloumn is empty for cases where the prompt is long and works fine if I shorten the prompt in config
<img width="706" alt="image" src="https://github.com/user-attachments/assets/1e0f034a-794e-46f0-a2f9-8f9c94a782da">

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
System information: Darwin Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
Python version: 3.11.7
MLflow version: 2.15.1
MLflow module location: project/.venv/lib/python3.11/site-packages/mlflow/__init__.py
Tracking URI: http://localhost:8080/
Registry URI: http://localhost:8080/
MLflow environment variables: 
  MLFLOW_TRACKING_PASSWORD: 
  MLFLOW_TRACKING_URI: http://localhost:8080/
  MLFLOW_TRACKING_USERNAME: 
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  aiohttp: 3.10.2
  alembic: 1.13.2
  boto3: 1.34.158
  botocore: 1.34.158
  docker: 7.1.0
  graphene: 3.3
  gunicorn: 22.0.0
  langchain: 0.2.10
  markdown: 3.6
  matplotlib: 3.9.1.post1
  mlflow-skinny: 2.15.1
  numpy: 1.26.4
  pandas: 2.2.2
  pyarrow: 15.0.2
  pydantic: 2.8.2
  querystring-parser: 1.2.4
  scikit-learn: 1.5.1
  scipy: 1.14.0
  sqlalchemy: 2.0.32
  tiktoken: 0.7.0
```

### Stack trace

```
2024/08/12 11:43:53 DEBUG mlflow.models.model: 
Traceback (most recent call last):
  File "/project/.venv/lib/python3.11/site-packages/mlflow/models/model.py", line 750, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model, run_id)
  File "/project/.venv/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 1530, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/project/.venv/lib/python3.11/site-packages/mlflow/tracking/client.py", line 2729, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/project/.venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/client.py", line 771, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/project/.venv/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 539, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/project/.venv/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 81, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/.venv/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 362, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/.venv/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 232, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(5000)

[SQL: INSERT INTO tags (key, value, run_uuid) VALUES (%(key)s, %(value)s, %(run_uuid)s)]
[parameters: {'key': 'mlflow.log-model.history', 'value': '[{"run_id": "6e67bded872746438abcba57c7e95b1b", "artifact_path": "chain", "utc_time_created": "2024-08-12 16:43:19.255703", "flavors": {"python_funct ... (6136 characters truncated) ... \": true}]", "outputs": "[{\\"type\\": \\"string\\", \\"name\\": \\"response\\", \\"required\\": true}]", "params": null}, "model_size_bytes": 6236}]', 'run_uuid': '6e67bded872746438abcba57c7e95b1b'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
@prithvikannan should we be thinking of storing this as an artifact instead of a tag?

**Comment by harshilprajapati96** [comment]
any update?

**Comment by WeichenXu123** [comment]
CC @prithvikannan Can we storing `ModelConfig` as artifact instead of tag value ? otherwise it might exceed max tag value length.

**Comment by prithvikannan** [comment]
> CC @prithvikannan Can we storing `ModelConfig` as artifact instead of tag value ? otherwise it might exceed max tag value length.

From the original errror message, the problem seems to be with `mlflow.log-model.history` tag. This tag contains the entire MLmodel contents, which includes the model config. But I don't think we need to store the model config -- the only relevant keys that are needed by clients of this tag are `artifactPath`, `flavors`, and `utcTimeCreated`, so I think we can implement some optimization here. 

The ModelConfig is also flattened (rather than just one big dict for the yaml) and logged as params, but I think that is needed  to support search/filtering runs with a certain config value (ie. "find all runs where I used llama-405b so i can compare their results").

**Comment by WeichenXu123** [comment]
Sounds good. We can only log `artifactPath` , `flavors`, and `utcTimeCreated` info in `mlflow.log-model.history` tag. @harshilprajapati96 Do you have time to file a PR ?

**Comment by harshilprajapati96** [comment]
I can fix it, are we saying I ignore the `config` when we `record_logged_model` ?
```
     def record_logged_model(self, run_id, mlflow_model):
-        req_body = message_to_json(LogModel(run_id=run_id, model_json=mlflow_model.to_json()))
+        ## Ignore config while 
+        model_info = {
+            k: {
+                k1: {k2: v2 for k2, v2 in v1.items() if k2 != 'config'} if 'config' in v1 else v1
+                for k1, v1 in v.items()
+            } if k == 'flavors' else v
+            for k, v in mlflow_model.to_dict().items()
+        }
+        model_json = json.dumps(model_info)
+        req_body = message_to_json(LogModel(run_id=run_id, model_json=model_json))
         self._call_endpoint(LogModel, req_body)
```

with this change it works without the error and logs properly. Let me know if this is correct!

**Comment by harshilprajapati96** [comment]
@WeichenXu123 I have the PR open, let me know if this is the correct approach!
cc: @prithvikannan
