### ISSUE TITLE
[FR] Allow  colon (":") in mlflow param and metric names

### ISSUE THREAD

**Issue by piyushdaftary** [mlflow/mlflow#12940]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.13.2, 2.15.1

### System information

- **OS Platform and Distribution** : MacOS 14 Sonoma and Linux Ubuntu 24.04
- **Python version**: 3.12.1

### Describe the problem

Currently mlflow doesn't support colon (`:`)  in metric name.
While logging metrics in mlflow with colon (`:`)  in metric name  , mlflow throws `INVALID_PARAMETER_VALUE` exception. 

For example while trying to log metric with name `n:estimators`, it throws below exception:  

```
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Invalid parameter name: 'n:estimators'. Names may only contain alphanumerics, underscores (_), dashes (-), periods (.), spaces ( ), and slashes (/).
```

IMO colon (`:`) is safe to be accepted in metric name.

### Tracking information

```shell
System information: Darwin Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000
Python version: 3.12.1
MLflow version: 2.15.2.dev0
MLflow module location: /Users/pdaftary/sagemaker/mlflowOSS/mlflow/mlflow/__init__.py
Tracking URI: file:///Users/pdaftary/sagemaker/mlflowOSS/mlflow/mlruns
Registry URI: file:///Users/pdaftary/sagemaker/mlflowOSS/mlflow/mlruns
Active experiment ID: 0
Active run ID: e442536bc70a40719eaaa490856d9dea
Active run artifact URI: mlflow-artifacts:/0/e442536bc70a40719eaaa490856d9dea/artifacts
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  alembic: 1.13.1
  boto3: 1.34.118
  botocore: 1.34.118
  click: 8.1.7
  cloudpickle: 3.0.0
  docker: 4.4.1
  entrypoints: 0.4
  gitpython: 3.1.43
  graphene: 3.3
  gunicorn: 21.2.0
  importlib_metadata: 7.1.0
  markdown: 3.6
  matplotlib: 3.9.0
  numpy: 1.26.4
  packaging: 23.2
  pandas: 2.2.2
  protobuf: 4.25.3
  pyarrow: 15.0.2
  pydantic: 2.5.3
  pytz: 2024.1
  pyyaml: 6.0.1
  querystring_parser: 1.2.4
  requests: 2.32.3
  scikit-learn: 1.5.0
  scipy: 1.13.1
  sqlalchemy: 2.0.30
  sqlparse: 0.5.0

```

### Code to reproduce issue

```
import mlflow.sklearn
from sklearn.datasets import make_regression

X, y = make_regression(n_features=4, n_informative=2, random_state=0, shuffle=False)
mlflow.set_tracking_uri("http://localhost:5000/")
# Log MLflow entities
with mlflow.start_run() as run:
    mlflow.log_params({"n:estimators": 3, "random_state": ""})
model_uri = f"runs:/{run.info.run_id}/sklearn-model"
mv = mlflow.register_model(model_uri, "RandomForestRegressionModel-3")
print(f"Name: {mv.name}")
print(f"Version: {mv.version}")

```

### Stack trace

```
/miniconda3/bin/python /mlflowOSS/mlflow/piyush.py 
2024/08/13 23:17:36 INFO mlflow.tracking.fluent: [<Param: key='n:estimators', value='3'>, <Param: key='random_state', value=''>]
2024/08/13 23:17:36 INFO mlflow.tracking._tracking_service.client: 🏃 View run efficient-mouse-703 at: http://localhost:5000/#/experiments/0/runs/db67b7b9109f4a78b7327cc2dbe94aed.
2024/08/13 23:17:36 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://localhost:5000/#/experiments/0.
Traceback (most recent call last):
  File "/mlflowOSS/mlflow/piyush.py", line 8, in <module>
    mlflow.log_params({"n:estimators": 3, "random_state": ""})
  File "mlflowOSS/mlflow/mlflow/tracking/fluent.py", line 969, in log_params
    return MlflowClient().log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlflowOSS/mlflow/mlflow/tracking/client.py", line 1846, in log_batch
    return self._tracking_client.log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlflow/mlflow/tracking/_tracking_service/client.py", line 718, in log_batch
    self.store.log_batch(
  File "/mlflowOSS/mlflow/mlflow/store/tracking/rest_store.py", line 535, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "/mlflowOSS/mlflow/mlflow/store/tracking/rest_store.py", line 81, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlflowOSS/mlflow/mlflow/utils/rest_utils.py", line 362, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlflowOSS/mlflow/mlflow/utils/rest_utils.py", line 232, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Invalid parameter name: 'n:estimators'. Names may only contain alphanumerics, underscores (_), dashes (-), periods (.), spaces ( ), and slashes (/).

```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
quick question: in your use-case, why not using `.` or `/` to replace `:` ? Any strong reason that has to use `:` ?

**Comment by piyushdaftary** [comment]
@WeichenXu123 : Thanks for looking into it. `AWS SageMaker Jumpstart` have list of predefined metrics with `:` in it's metric name, for example `huggingface-textgeneration:eval-loss` for evaluating loss, `huggingface-textgeneration:eval-ppl` for evaluating perplexity etc . Changing all those metrics is not possible. 

Can we add support for colon `:` in mlflow ? IMO it is non breaking change and will help mlflow community members who want to log metrics with `:` predefined in it.

**Comment by WeichenXu123** [comment]
ok make sense. I think we can allow `:` in param metric name. Feel free to file a PR.

**Comment by piyushdaftary** [comment]
@WeichenXu123 : I have raised pr :  https://github.com/mlflow/mlflow/pull/12943/ . Can you please review it.
