### ISSUE TITLE
Documentation linking to archived GitHub repository

### ISSUE THREAD

**Issue by brylie** [mlflow/mlflow#1295]
When reading the MLFlow documentation, we clicked the "edit on GitHub" link and were taken to an [archived repository](https://github.com/databricks/mlflow). For a moment, we were a bit disappointed, since MLFlow is a fairly exciting project. After a looking a bit closer, we noticed that the archived repository had been forked from this one.

Please update any/all links in the documentation, relating to source code, to point to this repository.

**Comment by mateiz** [comment]
Good catch! We'll fix this.
