### ISSUE TITLE
Unable to install with Numpy version > 2.0

### ISSUE THREAD

**Issue by saurabhmahra91** [mlflow/mlflow#12967]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Apple M2 Mac MacOS Sonoma Version 14.6.1 

- **MLflow installed from (source or binary)**:
Not applicable. This is decided by the package management tool.

- **MLflow version (run ``mlflow --version``)**:
2.15.1

- **Python version**:
3.12.3

### Code to reproduce issue

```bash
poetry new testbug
cd testbug
poetry add numpy
poetry add mlflow
```

### Describe the problem

[This line](https://github.com/mlflow/mlflow/blob/master/pyproject.toml#L41) in the pyproject.toml has listed numpy < 2.0 as dependency.

I am not able to use numpy>2.0 and mlflow at the same time

Here's what I get when trying to install mlflow in an environemnt that already has numpy==2.0.1

Using version ^2.15.1 for mlflow

Updating dependencies
Resolving dependencies... (0.0s)

Because no versions of mlflow match >2.15.1,<3.0.0
 and mlflow (2.15.1) depends on numpy (<2), mlflow (>=2.15.1,<3.0.0) requires numpy (<2).
So, because <package> depends on both numpy (^2.0.1) and mlflow (^2.15.1), version solving failed.

**Comment by victoriarouton** [comment]
We’re also not able to upgrade numpy because numpy> 2.0 is not yet supported by mlflow

**Comment by luizmachado** [comment]
There is a pull request to enable numpy > 2 

Reference:
 #1560

**Comment by B-Step62** [comment]
Thank you for these pointers, both! Yes, we have an ongoing work for updating `numpy`, but we first need to update Python version in our test infra. Closing as duplication.
