### ISSUE TITLE
Fix pyarrow test and remove pyarrow version upper bound

### ISSUE THREAD

**Issue by serhio-k** [mlflow/mlflow#12994]
It appears there is an issue with the loop that checks the pyarrow version to select the appropriate method for running the tests. 
Here are the details:
`pyarrow.fs.HadoopFileSystem` is the current method for connecting to HDFS.
`pyarrow.hdfs.connect` is obsolete and has been deprecated since version 2.0.0.

The test contains a faulty loop that checks the pyarrow version and incorrectly uses `pyarrow.fs.HadoopFileSystem` for versions earlier than 2.0.0, and vice versa.
https://github.com/mlflow/mlflow/blob/474be52ae273358b62b69cb7eb904adf11e79970/mlflow/store/artifact/hdfs_artifact_repo.py#L195

The correct 'if' condition should be:
`if packaging.version.parse(pyarrow.__version__) > packaging.version.parse("2.0.0"):`

This ensures that `pyarrow.fs.HadoopFileSystem` is used for versions greater than 2.0.0

_Originally posted by @serhio-k in https://github.com/mlflow/mlflow/issues/12980#issuecomment-2302432151_

**Comment by B-Step62** [comment]
The condition issue is being addressed in https://github.com/mlflow/mlflow/pull/12592, with additional changes to handle new interface.
