### ISSUE TITLE
UI preferences file

### ISSUE THREAD

**Issue by johny-c** [mlflow/mlflow#1302]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **MLflow installed from (source or binary)**:  source
- **MLflow version (run ``mlflow --version``)**: 0.9.2.dev0
- **Python version**: 3.6.6
- **npm version (if running the dev UI): v6.9.0
- **Exact command to reproduce**:

### Feature request:
I find myself constantly changing the options for run views like "step" instead of "time" for the x-axis, whether or not "points" are shown or not, etc. I think it would be useful to have something like a user preferences file that stores either the latest user options used or some user specified defaults. Ideally, one could specify such a preferences file per experiment.

**Comment by Zangr** [comment]
Thank you @johny-c, sounds like a reasonable feature to provide.

**Comment by johny-c** [comment]
unstale

**Comment by johny-c** [comment]
This should be no biggie.
