### ISSUE TITLE
Update ruff

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#13111]
### Summary

Looking for someone who wants to help us update the ruff version to the latest:

```diff
diff --git a/requirements/lint-requirements.txt b/requirements/lint-requirements.txt
index 6dfb4385a..a160a8be4 100644
--- a/requirements/lint-requirements.txt
+++ b/requirements/lint-requirements.txt
@@ -1,4 +1,4 @@
-ruff==0.2.1
+ruff==0.6.4
 rstcheck==6.1.1
 black[jupyter]==23.7.0
 blacken-docs==1.18.0
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by levscaut** [comment]
Hi @harupy can I try with this issue? Willing to step into the mlflow community!
