### ISSUE TITLE
[BUG] The `eval_results_table.json ` artifact  Preview is incomplete, please add scroll bar

### ISSUE THREAD

**Issue by liuhu** [mlflow/mlflow#13129]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.13.2

### System information

- **OS Platform and Distribution** :  MacOS Sonoma 14.6.1
- **Python version**: 3.9.16

### Describe the problem

The `eval_results_table.json `  artifact  Preview information display is incomplete, please add scroll bar. 
![image](https://github.com/user-attachments/assets/6fa30a92-6b2e-4af3-a350-fccc27f9ca92)

### Steps to reproduce the bug

Open tracking service UI artifact Preview  `eval_results_table.json `

**Comment by WeichenXu123** [comment]
CC @daniellok-db can we make it scrollable?

**Comment by daniellok-db** [comment]
Thanks for filing the bug! Yes I think this should be a quick fix.

**Comment by daniellok-db** [comment]
It is scrollable on the latest version. Can you try upgrading MLflow?


https://github.com/user-attachments/assets/5993c4b4-b747-493a-bd45-cbea01c2a31e

**Comment by liuhu** [comment]
@daniellok-db  thanks a lot.  And cloud you tell me in which version it was fixed?
Because I'm using the MLflow tracking service hosted by AWS segemaker, and they will be upgrading to 2.14.0 at the end of September, and I checked the release notes for [2.14.0](https://mlflow.org/releases/2.14.0) and it seems to mention that. 
So I can ask aws tech support for a minimal version upgrade.

**Comment by daniellok-db** [comment]
The fix was made 2 months ago, so the earliest version that contains it should be 2.15.0!
