### ISSUE TITLE
[BUG] JSONDecodeError: Unterminated string when using log_table

### ISSUE THREAD

**Issue by plamen-alcatraz** [mlflow/mlflow#13170]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client:2.16.0
- Tracking server: 2.13.0

### System information

- **Ubuntu 22.04.2 LTS**
- **Python 3.9.18**

### Describe the problem

After many calls to `mlflow_client.log_table` I get the following exception: json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 4998 (char 4997). 
The last artifact is logged correctly. It seems to me that after 5000 characters the `MLFLOW_LOGGED_ARTIFACTS` tag used is used to store the paths of all logged tables is clipped, maybe because of the database column type. 
`

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

  File "/home/plamen/anaconda3/envs/mlops2/lib/python3.9/site-packages/mlflow/tracking/client.py", line 2577, in log_table
    current_tag_value = json.loads(run.data.tags.get(MLFLOW_LOGGED_ARTIFACTS, "[]"))
  File "/home/plamen/anaconda3/envs/mlops2/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/plamen/anaconda3/envs/mlops2/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/plamen/anaconda3/envs/mlops2/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 4998 (char 4997)

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Yes I think it is because "MLFLOW_LOGGED_ARTIFACTS" tag value overflows.

CC @sunishsheth2009 could you help fixing it ?

**Comment by WeichenXu123** [comment]
@plamen-alcatraz We can increase the `MLFLOW_LOGGED_ARTIFACTS` tag value length limit to 64K (keep consistent with Databricks managed MLflow), does this way address your issue ?

**Comment by WeichenXu123** [comment]
@plamen-alcatraz PR is out. would you test it ? https://github.com/mlflow/mlflow/pull/13176

**Comment by plamen-alcatraz** [comment]
> Yes I think it is because "MLFLOW_LOGGED_ARTIFACTS" tag value overflows.
> 
> CC @sunishsheth2009 could you help fixing it ?

**Comment by plamen-alcatraz** [comment]
> @plamen-alcatraz We can increase the `MLFLOW_LOGGED_ARTIFACTS` tag value length limit to 64K (keep consistent with Databricks managed MLflow), does this way address your issue ?

It is not ideal but will do the job.
