### ISSUE TITLE
[BUG] `mlflow gc` failing at getting artifact repository when using filesystem as storage

### ISSUE THREAD

**Issue by JosephPenaQuino** [mlflow/mlflow#13188]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.16.2
- Tracking server: 2.16.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.5 LTS
- **Python version**: 3.12.5
- **yarn version, if running the dev UI**:

### Describe the problem

I'm running MLflow with the local filesystem, using the `mlruns` and `mlartifacts` directories to log my runs. Using the UI, I manually deleted some of these runs. Afterward, I ran the `mlflow gc` command to permanently remove the deleted runs and artifacts. However, the command fails with exception: `mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
`

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

I run the mlflow server with command below:
```bash
mlflow server --host 0.0.0.0 --port 8081
```

I used this script to generate fake data to later be removed:

```python
import mlflow

mlflow.set_tracking_uri("http://localhost:8081")

# Start an MLflow run
with mlflow.start_run():
    # Log parameters
    mlflow.log_param("param1", 5)
    mlflow.log_param("param2", "valueB")

    # Log metrics
    mlflow.log_metric("metric1", 0.75)
    mlflow.log_metric("metric2", 0.85)

    # Create and log a simple artifact (a CSV file)
    data = {
        "col1": [1, 2, 3],
        "col2": [4, 5, 6]
    }
    artifact_file = "fake_data.json"

    # Log the CSV file as an artifact
    mlflow.log_table(data, artifact_file)

print("Run and artifact logged successfully!")

```

### Stack trace

I executed the command `mlflow gc` in the same directory where I executed the `mlflow server...`
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mlflow-latest/bin/mlflow", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/mlflow/cli.py", line 618, in gc
    artifact_repo = get_artifact_repository(run.info.artifact_uri)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 132, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 77, in get_artifact_repository
    return repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "/home/user/miniconda3/envs/mlflow-latest/lib/python3.12/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
Hi, @JosephPenaQuino. Thank you for raising the issue and provide the code example for reproduction. I ran it on my machine, however, I could not reproduce the issue (`mlflow gc` succeeded). Do you perhaps setting tracking URI or artifact URI via environment variables?

**Comment by JosephPenaQuino** [comment]
Hi, @B-Step62. Thank you for your response.

I checked there were no environment variables.

I have repeated the process using the `--backend-store-uri` and `--artifacts-destination` flags, but I still encounter the same issue.
I realize I may not have described the steps clearly, so I’ve provided a detailed procedure below.
I’m using Python version 3.12.5:

Steps to Reproduce:

1. Create a directory and navigate into it:

```bash
mkdir mlflow-test && cd mlflow-test
```

2. Set up a Python virtual environment:

```bash
python -m venv venv
source venv/bin/activate
pip install mlflow==2.16.2
```

3. Create the `fake_data.py` script: Inside the mlflow-test directory, I created a Python script named `fake_data.py` with the code provided in my original issue description.

4. Start the MLflow server: I started the MLflow server using the following command, specifying the directories for the backend store and artifacts:

```bash
mlflow server --host 0.0.0.0 --port 8081 --backend-store-uri ./mlruns --artifacts-destination ./mlartifacts
```

5. Run the `fake_data.py` script in another terminal: In a separate terminal, I activated the virtual environment and executed the `fake_data.py` script:

```bash
source venv/bin/activate
python fake_data.py
```

6. Verify the files and directories: After running the script, I confirmed the presence of the following in the mlflow-test directory:

    - One file: `fake_data.py`
    - three directories: venv, mlartifacts and mlruns

7. Access the MLflow UI: Using a browser, I navigated to http://0.0.0.0:8081 to open the MLflow UI. I selected the run and clicked the "Delete" button.

8. Run the gc command: In the same terminal where I executed `fake_data.py`, I ran the garbage collection command, specifying the backend store and artifacts paths:

```bash
mlflow gc --backend-store-uri ./mlruns --artifacts-destination ./mlartifacts
```

9. Encounter the error: The above command raised the error mentioned in the issue.

**Comment by francisco-simoes** [comment]
I have the same issue.

**Comment by B-Step62** [comment]
Thank you so much @JosephPenaQuino for providing the detailed repro steps! Now I could reproduce the issue (the key was `--artifacts-destination` option). Investigating on the root cause.

**Comment by B-Step62** [comment]
@JosephPenaQuino I found the root cause, the issue was that `mlflow gc` does not recognize the tracking server you started in a separate command. 

When a tracking server is running and the tracking URI is set to that via `set_tracking_uri`, experiments and runs are created via the server's REST APIs under the hood, even if they are stored locally after all. Then, the delete operations also must be done through its REST APIs, however, you don't tell the tracking server URI for the `mlflow gc` command, `gc` tries to delete local files directly not through the REST APIs, resulting in the validation error.

The quick solution is to set the `MLFLOW_TRACKING_URI` env variable before running `mlflow gc`. 
```
export MLFLOW_TRACKING_URI=http://localhost:8081
mlflow gc --backend-store-uri ./mlruns --artifacts-destination ./mlartifacts
```

While this is not literary a bug, the error message and documentation are not helpful. We will update them to suggest setting tracking URI before running the command.

**Comment by JosephPenaQuino** [comment]
Thank you very much, @B-Step62 
I followed your recommendation, and it worked perfectly. Would you prefer that I close the issue, or would you like to handle it? I'm not entirely sure about the protocol, so I appreciate your guidance.
