### ISSUE TITLE
 'NoneType' object has no attribute 'to_dictionary'

### ISSUE THREAD

**Issue by meigaoms** [mlflow/mlflow#1318]
### System information
- **OS Platform and Distribution **: macOS Mojave
- **MLflow installed from (source or binary)**: conda
- **MLflow version (run ``mlflow --version``)**: 0.9.1
- **Python version**: 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
mlflow.start_run()
runs = mlflow.active_run()
print(runs.to_dictionary())

### Describe the problem
mlfow.active_run() returns 'NoneType' object, instead of active runs

### Source code / logs
import mlflow
r = mlflow.start_run()
active_runs = mlflow.active_run()
print((active_runs.to_dictionary()))

log:
/Users/xxxx/anaconda3/envs/benchml/bin/python /Users/xxxx/work/sandbox/benchml/analysis/content_moderator_text/test_mlflow.py
Traceback (most recent call last):
  File "/Users/xxxx/work/sandbox/benchml/analysis/content_moderator_text/test_mlflow.py", line 4, in <module>
    print((active_runs.to_dictionary()))
  File "/Users/xxxx/anaconda3/envs/benchml/lib/python3.6/site-packages/mlflow/entities/run.py", line 56, in to_dictionary
    return {"info": dict(self.info), "data": self.data.to_dictionary()}
AttributeError: 'NoneType' object has no attribute 'to_dictionary'

**Comment by aarondav** [comment]
Thanks @meigaoms. @dbczumar is fixing this in #1328.
