### ISSUE TITLE
Artifacts location 

### ISSUE THREAD

**Issue by JK87iab** [mlflow/mlflow#132]
Hi,
I can save my logs to `dbfs` via `mlflow.set_tracking_uri("FileStore/foo/")` inside databricks, afterwards I use the CLI to download everything including Artifacts to my local machine where `mlflow ui` is running

It displays all the experiment metrics fine but the Artifact Location is still set to `dbfs` and not to my local folder. Is there a way to change the Location?

**Comment by andymancodes** [comment]
@smurching Hi, could you take a look at an issue https://github.com/databricks/mlflow/issues/138, its very simple but I am not getting it to work. Gracias.

**Comment by mparkhe** [comment]
Hi @JK87iab,

Are you trying to download artifact data from databricks to your local machine? You could do that using `dbfs` and `cli` commands. You can create new experiments with any location you like (however if the location is not accessible to MLflow artifacts would not be displayed in UI). Alteratively, you can use `dbfs` commands in a notebook to move artifacts between locations.

mani
