### ISSUE TITLE
[FR] Add support for tracking per-node level hardware specs and resource utilization in distributed training

### ISSUE THREAD

**Issue by kimminw00** [mlflow/mlflow#13202]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Add support for automatically tracking hardware specifications and resource utilization of each node in distributed training environments.

### Motivation

> #### What is the use case for this feature?
The use case for this feature is to enable comprehensive tracking of hardware specifications and resource utilization of each node in distributed training environments. 

> #### Why is this use case valuable to support for MLflow users in general?
This is valuable for MLflow users in general because it allows for better understanding of performance bottlenecks, optimization of resource allocation, and improved reproducibility of experiments. 

> #### Why is this use case valuable to support for your project(s) or organization?
For our project/organization, this feature is crucial because we frequently run large-scale distributed training jobs and need to optimize resource utilization to reduce costs and improve efficiency. 

> #### Why is it currently difficult to achieve this use case?
Currently, it is difficult to achieve this use case because MLflow does not provide a built-in mechanism for tracking hardware specifications and resource utilization of each node in distributed training environments.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@kimminw00 MLflow supports recording system metrics https://mlflow.org/docs/latest/system-metrics/index.html

For multi-nodes environment, MLflow by default only collects metrics from the master node (rank 0). However, you can start system metric collector thread by calling `mlflow.start_run(log_system_metrics=True, run_id=<your-main-run-id>)` in the other nodes. Does this work for your case?

**Comment by kimminw00** [comment]
Thank you for the suggestion! However, in my case, the training loop and MLflow logging are well-abstracted within the SFTTrainer, making it challenging to directly call mlflow.start_run on other nodes. I'll need to explore further to find a suitable solution.
