### ISSUE TITLE
Fix D417 (`undocumented-param`)

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#13210]
### Summary

#13198 enabled a lint rule to prevent undocumented parameters in the docstring. #13200 fixed some of them, but there are still many functions violating this rule. The goal of this ticket is to fix them. The function violating this rule are marked with `# noqa: D417`.

Example:

```diff
diff --git a/mlflow/utils/databricks_utils.py b/mlflow/utils/databricks_utils.py
index 57c37460b..731e6d411 100644
--- a/mlflow/utils/databricks_utils.py
+++ b/mlflow/utils/databricks_utils.py
@@ -773,11 +773,11 @@ def get_databricks_run_url(tracking_uri: str, run_id: str, artifact_path=None) -
         return None
 
 
-def get_databricks_model_version_url(registry_uri: str, name: str, version: str) -> Optional[str]:  # noqa: D417
+def get_databricks_model_version_url(registry_uri: str, name: str, version: str) -> Optional[str]:
     """Obtains a Databricks URL corresponding to the specified Model Version.
 
     Args:
-        tracking_uri: The URI of the Model Registry server containing the Model Version.
+        registry_uri: The URI of the Model Registry server containing the Model Version.
         name: The name of the registered model containing the Model Version.
         version: Version number of the Model Version.
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by harupy** [comment]
@levscaut are you interested in working on this?

**Comment by rafyzg** [comment]
I would love to work on this one.

**Comment by levscaut** [comment]
Hi @harupy Thanks for refering me! I can work on this real quick.

**Comment by harupy** [comment]
@levscaut You don't need to. Let's just fix low hanging fruits like the example in the issue description!

**Comment by levscaut** [comment]
> @levscaut You don't need to. Let's just fix low hanging fruits like the example in the issue description!

Great! I will seek what I can do.

**Comment by harupy** [comment]
Closed this issue. I'll file a new one if we need to.
