### ISSUE TITLE
[FR] Feature to pass `route_optimized=True/False` parameter in Databricks deployment client

### ISSUE THREAD

**Issue by prabhatkgupta** [mlflow/mlflow#13221]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Databricks provides `route_optimized=True/False` support to ensure faster routing of requests to end points. This field is missing in `MLFlow.DatabricksDeploymentClient.create_endpoint()` 

<br><br>
Error: <br>
**TypeError: DatabricksDeploymentClient.create_endpoint() got an unexpected keyword argument 'route_optimized'**

<br><br>

<img width="757" alt="image" src="https://github.com/user-attachments/assets/8a45793b-7ae6-47af-926f-6092872a8cb7">

### Motivation

> #### What is the use case for this feature?
- To provide support in deploying endpoints in databricks that can support faster routing
 

> #### Why is this use case valuable to support for MLflow users in general?
- It reduces inference latency by 20-30%

> #### Why is this use case valuable to support for your project(s) or organization?
- A lot of organization uses route_optimized endpoints in databricks, supporting that in mlflow will allow teams to easily deploy their models in databricks using mlflow

> #### Why is it currently difficult to achieve this use case?
- No support in current databricks client function

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by prabhatkgupta** [comment]
Created a feature PR: https://github.com/mlflow/mlflow/pull/13222

Maintainers Please review & merge

**Comment by prabhatkgupta** [comment]
@MehulKothari-Circuitry databricks doesn't support updating endpoint to`route_optimization` once it is already created. Hence, there would be no effect adding that code to mlflow

**Comment by MehulKothari-Circuitry** [comment]
https://docs.databricks.com/api/workspace/servingendpoints/updateconfig

based on this doc its showing supported.?? can you please check?.Thanks

**Comment by MehulKothari-Circuitry** [comment]
Hey @prabhatkgupta  got it , But databricks needs to add this feature.

**Comment by MehulKothari-Circuitry** [comment]
Hey @prabhatkgupta  @B-Step62 has this been releases

**Comment by B-Step62** [comment]
@MehulKothari-Circuitry This will be released as a part of MLflow 2.17.0 coming next week.
