### ISSUE TITLE
Changing artifact location inside databricks

### ISSUE THREAD

**Issue by matallanas** [mlflow/mlflow#1324]
### System information
- Azure Databricks.

### Describe the problem
After creating an experiment within Databricks and change the artifact directory to a mounted blob storage, the mlflow ui chrashes inside databricks.

Thank you very much

**Comment by aarondav** [comment]
Thanks for the report -- since this sounds like a bug specific to Databricks, please submit a bug report via Databricks support (https://databricks.com/support) or via Azure support to make sure it's tracked appropriately.
