### ISSUE TITLE
Failed to run mlflow project with docker_env

### ISSUE THREAD

**Issue by shayts7** [mlflow/mlflow#1335]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Trying to run mlflow project with docker_env yield exception

### Source code / logs
019/05/26 11:34:02 INFO mlflow.projects: === Building docker image mlflow-test-model-v1-ebf1f04 ===
2019/05/26 11:34:04 INFO mlflow.projects: === Created directory /tmp/tmpOnGmBj for downloading remote URIs passed to arguments of type 'path' ===
2019/05/26 11:34:04 INFO mlflow.projects: === Running command 'docker run --rm -v /test_repo/src/research/models/test-model-v1/mlruns:/mlflow/tmp/mlruns -e MLFLOW_TRACKING_URI=/mlflow/tmp/mlruns -e MLFLOW_RUN_ID=4ccf791bab4d48e48f2ad955e0be872e -e MLFLOW_EXPERIMENT_ID=0 mlflow-test-model-v1-ebf1f04 python train.py' in run with ID '4ccf791bab4d48e48f2ad955e0be872e' ===
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    with mlflow.start_run():
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/fluent.py", line 115, in start_run
      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1316            5.4              0.74         0.00             1.2      0.041
1507            7.5              0.38         0.57             2.3      0.106
849             6.4              0.63         0.21             1.6      0.080
82              7.4              0.50         0.47             2.0      0.086
644             9.9              0.54         0.45             2.3      0.071

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1316                 16.0                  46.0  0.99258  4.01       0.59
1507                  5.0                  12.0  0.99605  3.36       0.55
849                  12.0                  32.0  0.99689  3.58       0.66
82                   21.0                  73.0  0.99700  3.36       0.57
644                  16.0                  40.0  0.99910  3.39       0.62

      alcohol  quality
1316     12.5        6
1507     11.4        6
849       9.8        5
82        9.1        5
644       9.4        5
    active_run_obj = MlflowClient().get_run(existing_run_uuid)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/client.py", line 53, in get_run
    return self.store.get_run(run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/file_store.py", line 368, in get_run
    run_info = self._get_run_info(run_uuid)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/file_store.py", line 384, in _get_run_info
    databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run '4ccf791bab4d48e48f2ad955e0be872e' not found
2019/05/26 11:34:08 ERROR mlflow.cli: === Run (ID '4ccf791bab4d48e48f2ad955e0be872e') failed ===

**Comment by shayts7** [comment]
The problem is relevant for "local mlruns" storage
I checked and the run exist outside of the docker_env, so the run cannot be reached from inside docker.
volume mapping could be a solution here (to map the mlruns folder)

**Comment by AndreyBulezyuk** [comment]
Same issue on Windows. Basic Example from the MLFlow Documentation does not work.

MLFlow Project with Docker as Environment fails when used with 'mlflow run .'
Exception:
`docker: Error response from daemon: invalid mode: \Users\andre\code\mlflow1\productionfirst\mlruns\0\c4132f95210546f787f89591b0e6d00e\artifacts.`

MLProject
`name: productionfirst

docker_env:
    image:  mlflow-docker-example

entry_points:
  main:
    command: "python classifier.py"`

Dockerfile
`FROM continuumio/miniconda:4.5.4

RUN pip install mlflow>=1.0 \
    && pip install numpy==1.14.3 \
    && pip install scipy \
    && pip install pandas==0.22.0 \
    && pip install scikit-learn==0.19.1 \
    && pip install cloudpickle \
    && pip install Keras \
    && pip install sklearn
`

**Comment by AndreyBulezyuk** [comment]
Here is the cmd that is being executed:
```
020/03/03 14:15:32 INFO mlflow.projects: === Running command 'docker run --rm -v C:\Users\andre\code\mlflow1\productionfirst\mlruns:/mlflow/tmp/mlruns -v C:\Users\andre\code\mlflow1\productionfirst\mlruns\0\9fd34ea8e7ed4e289a0d3c1b1b826fd8\artifacts:C:\Users\andre\code\mlflow1\productionfirst\mlruns\0\9fd34ea8e7ed4e289a0d3c1b1b826fd8\artifacts -e MLFLOW_RUN_ID=9fd34ea8e7ed4e289a0d3c1b1b826fd8 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 productionfirst:latest python3 classifier.py' in run with ID '9fd34ea8e7ed4e289a0d3c1b1b826fd8' ===
docker: Error response from daemon: invalid mode: \Users\andre\code\mlflow1\productionfirst\mlruns\0\9fd34ea8e7ed4e289a0d3c1b1b826fd8\artifacts.
```

docker run mounts two volumes

1. C:\Users\andre\code\mlflow1\productionfirst\mlruns
2. C:\Users\andre\code\mlflow1\productionfirst\mlruns\0\9fd34ea8e7ed4e289a0d3c1b1b826fd8\artifacts

The second mount is a) logilly incorrect and b) redundant since the files in mlruns are already covered with the first mount.

Removing the second mount and executing the command manually in Command Shell solves the issue. Will try to code a fix and create a PR later.

Seems like a bug to me. @mparkhe

**Comment by jwa5426** [comment]
Is there any news on this? I’m having the same issue on Windows.

**Comment by AndreyBulezyuk** [comment]
The Bugfix Was published last year. Can you please describe your setup and the error msg including stack trace?

**Comment by jwa5426** [comment]
Using mlflow 1.15.0 on Windows 10 with a recent install of Docker. The error trace is identical to the one you posted. Following the steps in the mlflow/examples/docker directory.

**Comment by jwa5426** [comment]
@AndreyBulezyuk it looks like maybe the bug fix wasn’t completed (assuming it’s this one) https://github.com/mlflow/mlflow/pull/2555#issuecomment-656080670

**Comment by jwa5426** [comment]
Removing the second mount as you did also fixes the underlying docker command in my case, by the way.
