### ISSUE TITLE
[BUG] python artifact API `delete_artifact(single_file)` fails with http: and file:

### ISSUE THREAD

**Issue by mazer-ai** [mlflow/mlflow#13368]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.16.0
- Tracking server: 2.16.2 (using as both tracking and artifact server via http connection)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 24.04.01 LTS
- **Python version**: 3.12.3
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When trying to use the `delete_artifacts()` to delete a single file (vs a directory) if fails, even though the docstring indicates single file deletion is supported:
```python
In [86]: ?artifact_repo.delete_artifacts
?artifact_repo.delete_artifacts
Signature: artifact_repo.delete_artifacts(artifact_path=None)
Docstring:
Delete the artifacts at the specified location.
Supports the deletion of a single file or of a directory. Deletion of a directory
is recursive.

Args:
    artifact_path: Path of the artifact to delete.
File:      ~/src/taut/venv12/lib/python3.12/site-packages/mlflow/store/artifact/http_artifact_repo.py
Type:      method
```

Deleting a directory works fine, but deleting a single file results in an exception. See below.

### Tracking information

```shell
$ run-mlflow.sh doctor
System information: Linux #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024
Python version: 3.12.3
MLflow version: 2.16.2
MLflow module location: /home/mazer/mlflow/mlflow-venv/lib/python3.12/site-packages/mlflow/__init__.py
Tracking URI: http://raclette:5000
Registry URI: http://raclette:5000
MLflow environment variables:
  MLFLOW_TRACKING_URI: http://raclette:5000
MLflow dependencies:
  Flask: 3.0.3
  Jinja2: 3.1.4
  alembic: 1.13.3
  docker: 7.1.0
  graphene: 3.3
  gunicorn: 23.0.0
  markdown: 3.7
  matplotlib: 3.9.2
  mlflow-skinny: 2.16.2
  numpy: 2.1.1
  pandas: 2.2.3
  pyarrow: 17.0.0
  scikit-learn: 1.5.2
  scipy: 1.14.1
  sqlalchemy: 2.0.35
```

### Code to reproduce issue

```
import mlflow
from mlflow.store.artifact.artifact_repository_registry import get_artifact_repository


# connect to server and open experiment and run
uri = 'http://raclette:5000'.   # changing uri to `file:/tmp` has similar issue -- see reply tbelow
client = mlflow.client.MlflowClient(uri, uri)
exper = client.get_experiment_by_name('foo')
if exper is None:
    client.create_experiment('foo')
    exper = client.get_experiment_by_name('foo')
run = client.create_run(experiment_id=exper.experiment_id)

# log artifact - this logs as `passwd` in repo root
client.log_artifact(run.info.run_id, '/etc/passwd')

# delete artifact
artifact_repo = get_artifact_repository(run.info.artifact_uri)
artifact_repo.delete_artifacts('passwd')
```

### Stack trace

```
In [91]: artifact_repo.delete_artifacts('passwd')

ResponseError: too many 500 error responses


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File ~/src/taut/venv12/lib/python3.12/site-packages/requests/adapters.py:667 in send
    resp = conn.urlopen(

  File ~/src/taut/venv12/lib/python3.12/site-packages/urllib3/connectionpool.py:944 in urlopen
    return self.urlopen(

  File ~/src/taut/venv12/lib/python3.12/site-packages/urllib3/connectionpool.py:944 in urlopen
    return self.urlopen(

  File ~/src/taut/venv12/lib/python3.12/site-packages/urllib3/connectionpool.py:944 in urlopen
    return self.urlopen(

  File ~/src/taut/venv12/lib/python3.12/site-packages/urllib3/connectionpool.py:944 in urlopen
    return self.urlopen(

  File ~/src/taut/venv12/lib/python3.12/site-packages/urllib3/connectionpool.py:944 in urlopen
    return self.urlopen(

  File ~/src/taut/venv12/lib/python3.12/site-packages/urllib3/connectionpool.py:934 in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)

  File ~/src/taut/venv12/lib/python3.12/site-packages/urllib3/util/retry.py:519 in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]

MaxRetryError: HTTPConnectionPool(host='raclette', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/257954152503913884/a40fdc7231034d3995664eb8290b9853/artifacts/passwd (Caused by R\
esponseError('too many 500 error responses'))
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mazer-ai** [comment]
As a sanity check -- I changed the URI to `file:/tmp/flow` and have same problem, though different error:
```python
Traceback (most recent call last):

  File ~/src/taut/notebooks/jamie/ksparse/manager_test.py:189
    artifact_repo.delete_artifacts('passwd')

  File ~/src/taut/venv12/lib/python3.12/site-packages/mlflow/store/artifact/local_artifact_repo.py:125 in delete_artifacts
    shutil.rmtree(artifact_path)

  File /usr/lib/python3.12/shutil.py:785 in rmtree
    _rmtree_safe_fd(fd, path, onexc)

  File /usr/lib/python3.12/shutil.py:661 in _rmtree_safe_fd
    onexc(os.scandir, path, err)

  File /usr/lib/python3.12/shutil.py:657 in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:

NotADirectoryError: [Errno 20] Not a directory: '/tmp/mlflow/314241748371059102/dd21063b1bea43e49b9bdfe16934bd50/artifacts/passwd'
```
Here the underlying code is clearly calling `shutils.rmtree()` on a file, which causes the error.

Am I doing something wrong here? Or is this intentional and the docstrings are just wrong?

**Comment by harupy** [comment]
@mazer-ai https://github.com/mlflow/mlflow/commit/f810d03ec4188c06c61219650b97e64df7748aa1 might be the fix for this issue. Let me double-check.

**Comment by harupy** [comment]
I think https://github.com/mlflow/mlflow/commit/f810d03ec4188c06c61219650b97e64df7748aa1 is the fix. This patch will be shipped in the next release soon. Closing this issue. Thanks for reporting!

**Comment by mazer-ai** [comment]
Thanks. Any idea if that fixes it only for local_store backends (file:) or also for the http/rest backend? Guess i'm asking if the http backend uses the local_store methods internally. Sorry if that's a bad question -- just haven't had time to dive deeply enough into the code base to know on my own.
