### ISSUE TITLE
[BUG] Deprecated dependencies in root Dockerfile

### ISSUE THREAD

**Issue by johanvdw** [mlflow/mlflow#13377]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Tracking server: 2.16.2

### System information

- official docker container
- Python 3.8

### Describe the problem

The official Dockerfile for mlflow contains some dependencies which no longer get updates:
* Python 3.8: end of life since this month (october 2024) https://devguide.python.org/versions/
* Node JS 16: deprecated since october 2023 / includes unsupported openssl version

While on it , it is probably wise to also upgrade debian bullseye to bookworm. In that case, protobuf can also be fetched from debian rather than custom.

https://github.com/mlflow/mlflow/blob/master/Dockerfile

### Tracking information

Not applicable

### Code to reproduce issue

Not applicable

### Stack trace

Not applicable

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by johanvdw** [comment]
FYI, this is a draft update:

https://github.com/johanvdw/mlflow/commit/746a041941a14e608eff2b1f385c5b022f4db8ee

I've not yet created a full PR because I want to do additional testing.

**Comment by harupy** [comment]
@johanvdw can we just bump python version 
to 3.9 and node version to 20? The reason we use 3.8 currently is to avoid using the features or syntax that don't exist in 3.8.
