### ISSUE TITLE
Bug - Unable to install Version 1.0.0 on R with miniconda

### ISSUE THREAD

**Issue by nettoyoussef** [mlflow/mlflow#1337]
### System information
- No custom code
- Linux Ubuntu 18.04
- Installed from source as described in https://docs.google.com/document/d/1Hu1y73aR21uDPbuUTBlTfSN7e5tR-9txqk_VHlCnupk/edit#
- Mlflow version 1.0.0
- Python 3.7.3

### Describe the problem
When installing package from source, version appears incorrectly as "0.9.2" instead of "1.0.0" in the R session. This appears to break some functionality with the Conda environment created, as it is named as "r-mlflow-1.0.0".

I tried to correct the code version manually in the Description file to "Version: 1.0.0" and reinstall the tar.package using devtools::install_local("path/to/corrected/version").

The installation in R occurs without any errors. However, after loading the library, when trying to run any command, such as mlflow_start_run(), the following error appears:

"Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  processx error: 'No such file or directory' at unix/processx.c:454"

Trying to reinstall the conda environment using install_mlflow() also doesn't correct the problem, probably because this version is not available on Github/CRAN:

"ERROR: Could not find a version that satisfies the requirement mlflow==1.0.0 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.0.1, 0.9.1)
ERROR: No matching distribution found for mlflow==1.0.0
Error: Error 1 occurred installing packages into conda environment r-mlflow-1.0.0"

I must add that I am not too familiar with Conda, so probably this is something easy to correct.

### Code to reproduce problem
Rscript -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
Rscript -e 'devtools::install_url("https://mlflow-snapshots.s3-us-west-2.amazonaws.com/r-mlflow-1.0.0.rc0-1173-fb8a711.tar.gz")'
Rscript -e 'reticulate::conda_create("r-mlflow-1.0.0")'
source activate r-mlflow-1.0.0
pip install https://mlflow-snapshots.s3-us-west-2.amazonaws.com/mlflow-1.0.0.rc0-1173.fb8a711-py2.py3-none-any.whl
Rscript -e 'library(mlflow); utils::packageVersion("mlflow")'

**Comment by smurching** [comment]
@nettoyoussef I believe this is fixed now with the MLflow 1.0 release (i.e. we've updated the package version to 1.0. Closing this for now, but if it's still an issue please reopen!

**Comment by nettoyoussef** [comment]
Yes, the last version fixed the problem. Thanks!
