### ISSUE TITLE
Cannot preview artifacts in UI when uploaded to remote machine via FTP

### ISSUE THREAD

**Issue by kafendt** [mlflow/mlflow#1338]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: 
installed via from pypi via pip
- **MLflow version (run ``mlflow --version``)**:
0.9.1
- **Python version**: 
3.6.7
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
Server runs with:
```
mlflow server --backend-store-uri ./mlruns --default-artifact-root ./artifacts -h 0.0.0.0 -p 5020
```
within a folder holding a `mlruns` and a `artifacts` folder

### Describe the problem
I am running the server on a remote machine.
On the local machine which uploads via the tracking API the
tracking uri is set to: `http://path.to.server:port`
and artifact uri to: `ftp://anonymous:@path.to.server/artifacts`

uploading the tracking information and artifacts work fine and everything shows in the ui:
![image](https://user-images.githubusercontent.com/12450485/58400502-7d0e9e00-805b-11e9-8d4f-b89a1bab5cb1.png)

However when I try to click one of the artifacts I always get the message that something went wrong:
![image](https://user-images.githubusercontent.com/12450485/58400530-99aad600-805b-11e9-8887-4f2640765ba4.png)

Previewing the artifacts work when I store them locally on my machine but as soon as I transfer them via FTP and then try to preview them from the remote machine I get the error shown above.

### Source code / logs
-

**Comment by analystanand** [comment]
Did you check error(trace log) on the server side?
I have faced similar issue while using s3 as storage and facing a similar issue when I run sever in a docker container?

**Comment by kafendt** [comment]
> Did you check error(trace log) on the server side?
> I have faced similar issue while using s3 as storage and facing a similar issue when I run sever in a docker container?

Where would I find that? There are no messages being printed to the console. Is mlflow writing to some log file?

**Comment by kafendt** [comment]
```
Error: "Can't find child."
    value ArtifactUtils.js:50
    value ArtifactUtils.js:46
    value ArtifactView.js:190
    value ArtifactView.js:57
    React 9

react-dom.production.min.js:151:111
    React 8

Error: "Can't find child."
    value ArtifactUtils.js:50
    value ArtifactUtils.js:46
    value ArtifactView.js:190
    value ArtifactView.js:57
    React 9

AppErrorBoundary.js:19:4

Unhandled promise rejection TypeError: "c is undefined"
    w Reducers.js:228
    w Reducers.js:227
    Redux 7
    j es6.promise.js:75
    j es6.promise.js:60

    u _microtask.js:18
es6.promise.js:110
```
This is what the firefox console outputs

**Comment by kafendt** [comment]
I think I have found the cause for this.
As I am using `ftp://anonymous:@path.to.server/artifacts` as my artifact_uri the following happens:

```js
   static findChild(node, path) {
      const parts = path.split('/');
      let ret = node;
      parts.forEach((part) => {
        if (ret.children && ret.children[part] !== undefined) {
          ret = ret.children[part];
        } else {  
          throw new Error("Can't find child.");
        }
      });
      return ret; 
   }         
```

The code above is taken from [ArtifactUtils.js](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/utils/ArtifactUtils.js#L43) here `path` now is `/artifacts/<runUuid>/artifacts` which is split by `/` therefore the first element in `parts` is now an empty string `""` which then leads to throwing the Error as `ret.children[part]` with part = "" is not retrievable. 

Unfortunately I cannot change my ftp artifact_uri as the ftp server won't allow to write directly into the root of the ftp so I need to add a subdirectory to the end of my path.

I would love to fix the problem but I currently cannot find the time for it and don't really know which would be the best place to fix this. It would be great if this could be fixed however as it is the only thing which keeps me from using mlflow in our team currently.

**Comment by nlaille** [comment]
@kafendt I had a similar issue with ftp server and absolute path instead of relative ones.
I was using vsftpd, but there is an "issue" with NLS command which returns absolute path... (https://github.com/quarkslab/irma-brain/issues/17, https://stackoverflow.com/questions/5153378/should-nlst-ftp-command-return-records-with-or-without-absolute-paths).
It is working way better with pure-ftpd.

Btw, our issue solving the RETR #919

**Comment by kafendt** [comment]
Thats good to know! Thank you

**Comment by Christoph460** [comment]
I just encountered the ftp preview artifact bug, which i was not able to solve via pure-ftpd. Whats the current status here, will this be solved?
Thanks for your help.

**Comment by nuno-chicoria** [comment]
I believe I am having a similar problem and none of the above solutions worked for me.
In my case I'm setting the artifact URI in the `mlflow.create_experiment()` and the tracking URI at `mlflow.set_tracking_uri()`.
For these experiments I have a VM that I can access through SFTP to store the artifacts and I can also access through PostgreSQL to edit a DB file and store the different params and metrics.
The main page of the UI works and I can see a list of all the runs, tags, params and metrics but once I try to see a specific run so I can see a list of the artifacts I get a page with the message "Something went wrong  - If this error persists (...)". The console shows the following error:
`Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
Actions.js:234 XHR failed Object
error @ Actions.js:234
react-dom.production.min.js:151 TypeError: Cannot read property 'getErrorCode' of undefined
    at RunPage.js:63
    at t.value (RequestStateWrapper.js:51)
    at f (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
    at i (react-dom.production.min.js:176)
    at a (react-dom.production.min.js:176)
    at _ (react-dom.production.min.js:182)
    at y (react-dom.production.min.js:181)
    at g (react-dom.production.min.js:181)
    at d (react-dom.production.min.js:180)
wt @ react-dom.production.min.js:151
AppErrorBoundary.js:19 TypeError: Cannot read property 'getErrorCode' of undefined
    at RunPage.js:63
    at t.value (RequestStateWrapper.js:51)
    at f (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
    at i (react-dom.production.min.js:176)
    at a (react-dom.production.min.js:176)
    at _ (react-dom.production.min.js:182)
    at y (react-dom.production.min.js:181)
    at g (react-dom.production.min.js:181)
    at d (react-dom.production.min.js:180)
value @ AppErrorBoundary.js:19
:8000/#/experiments/9/runs/95005cd32eb14fd6a9b521aa77477954:1 Uncaught (in promise) e`
Can someone help me sort this out? Thanks for the help in advance.

**Comment by nlaille** [comment]
@nuno-chicoria, were you able to `save_artifact` from your client ? Are you sure that your mlflow server is able to access to your sftp server ?
Btw, do you have some stacktraces from server side ?

**Comment by grco-xp** [comment]
Hey @nlaille. I am working with @nuno-chicoria on this. 

We are able to save artifacts on the server.

Here is the server side log, when we try to access a specific run page:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/58782224/70641716-f48dce80-1c35-11ea-8325-1fe69df32903.png)

We have switched from sftp to ftp, and we are running it with pure-ftpd as you suggested, but the problem persists. 

Also we have writing and reading permissions on relevant folders and set the _AllowUserFXP_ to yes on the pure-ftdp.conf file.

**Comment by nlaille** [comment]
@grco-xp I never faced this one.
Have you tried to connect to your ftp from the server on which you have started your mlflow server, using a ftp client or a python interpreter with ftplib to reproduce this issue ?
Could you give me some informations about your ftp configurations so I could reproduce it on my side.

**Comment by nuno-chicoria** [comment]
Hi, @nlaille. We were able to solve the problem.
The issue is at `ftp_artifact_repo.py` in the function `list_artifacts()`.
In line 106, the function `ftp.nlst(list_dir)` creates a list that is later used to get the artifacts. The problem is that the first 2 items of this list are "." and "..", bash commands to remain or leave the directory. When MLflow tries to search for these files it returns an error. The fix we found was to change line 108 to `for file_name in artifact_files[2:]:` so it starts the iteration at the firts real file.

**Comment by nuno-chicoria** [comment]
This workaround has been proposed at PR #2196.

**Comment by PaulZhangIsing** [comment]
> I believe I am having a similar problem and none of the above solutions worked for me. In my case I'm setting the artifact URI in the `mlflow.create_experiment()` and the tracking URI at `mlflow.set_tracking_uri()`. For these experiments I have a VM that I can access through SFTP to store the artifacts and I can also access through PostgreSQL to edit a DB file and store the different params and metrics. The main page of the UI works and I can see a list of all the runs, tags, params and metrics but once I try to see a specific run so I can see a list of the artifacts I get a page with the message "Something went wrong - If this error persists (...)". The console shows the following error: `Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR) Actions.js:234 XHR failed Object error @ Actions.js:234 react-dom.production.min.js:151 TypeError: Cannot read property 'getErrorCode' of undefined at RunPage.js:63 at t.value (RequestStateWrapper.js:51) at f (react-dom.production.min.js:131) at beginWork (react-dom.production.min.js:138) at i (react-dom.production.min.js:176) at a (react-dom.production.min.js:176) at _ (react-dom.production.min.js:182) at y (react-dom.production.min.js:181) at g (react-dom.production.min.js:181) at d (react-dom.production.min.js:180) wt @ react-dom.production.min.js:151 AppErrorBoundary.js:19 TypeError: Cannot read property 'getErrorCode' of undefined at RunPage.js:63 at t.value (RequestStateWrapper.js:51) at f (react-dom.production.min.js:131) at beginWork (react-dom.production.min.js:138) at i (react-dom.production.min.js:176) at a (react-dom.production.min.js:176) at _ (react-dom.production.min.js:182) at y (react-dom.production.min.js:181) at g (react-dom.production.min.js:181) at d (react-dom.production.min.js:180) value @ AppErrorBoundary.js:19 :8000/#/experiments/9/runs/95005cd32eb14fd6a9b521aa77477954:1 Uncaught (in promise) e` Can someone help me sort this out? Thanks for the help in advance.

Hi @nuno-chicoria. I am facing the same problem using MLFlow 1.29.0.
I try to use sftp to do the connection between my machine and the MLFLow server.
It apparently could log metric and save the artifacts to the server machine.
 But the UI does not reflects the artifacts being uploaded.
Do you have any ideas on this problem?
it is the last comment in issue #3030
