### ISSUE TITLE
[BUG] Load sentence_transformers

### ISSUE THREAD

**Issue by tcambon** [mlflow/mlflow#13380]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.5.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks 
- **Python version**: Python 3.10.12
- **yarn version, if running the dev UI**:

### Describe the problem

I logged sentence_transformers model to mlflow. When I try to load it with the sentence_transformers I get an error. Whereas with pyfunc no problem.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
from sentence_transformers import SentenceTransformer
import mlflow.sentence_transformers
model = SentenceTransformer('all-MiniLM-L6-v2')

# Log the model
with mlflow.start_run():
    mlflow.sentence_transformers.log_model(model, 'model')

# Error: Load the model with sentence_transformers flavor
loaded_model_st = mlflow.sentence_transformers.load_model(model_path)

# Works: Load the model with pyfunc
loaded_model_pf = mlflow.pyfunc.load_model(model_path)

```

### Stack trace

```
Traceback (most recent call last)
File <command-1659882932533551>, line 1
----> 1 loaded_model_st = mlflow.sentence_transformers.load_model('runs:/48a1dfade6484f488a01dc80a8d49777/model')

File /databricks/python/lib/python3.10/site-packages/mlflow/utils/docstring_utils.py:263, in docstring_version_compatibility_warning.<locals>.annotated_func.<locals>.version_func(*args, **kwargs)
    261 if installed_version < Version(min_ver) or installed_version > Version(max_ver):
    262     warnings.warn(notice, category=FutureWarning, stacklevel=2)
--> 263 return func(*args, **kwargs)

File /databricks/python/lib/python3.10/site-packages/mlflow/sentence_transformers.py:317, in load_model(model_uri, dst_path)
    313 flavor_config = _get_flavor_configuration_from_uri(model_uri, FLAVOR_NAME, _logger)
    315 _add_code_from_conf_to_system_path(local_model_path, flavor_config)
--> 317 return sentence_transformers.SentenceTransformer.load(local_model_dir)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1e88fd42-9d8d-4ecc-9663-03fb171f8c7d/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py:1754, in SentenceTransformer.load(input_path)
   1752 @staticmethod
   1753 def load(input_path) -> SentenceTransformer:
-> 1754     return SentenceTransformer(input_path)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1e88fd42-9d8d-4ecc-9663-03fb171f8c7d/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py:371, in SentenceTransformer.__init__(self, model_name_or_path, modules, device, prompts, default_prompt_name, similarity_fn_name, cache_folder, trust_remote_code, revision, local_files_only, token, use_auth_token, truncate_dim, model_kwargs, tokenizer_kwargs, config_kwargs, model_card_data, backend)
    367 if model_name_or_path in ("hkunlp/instructor-base", "hkunlp/instructor-large", "hkunlp/instructor-xl"):
    368     self.set_pooling_include_prompt(include_prompt=False)
    369 elif (
    370     model_name_or_path
--> 371     and "/" in model_name_or_path
    372     and "instructor" in model_name_or_path.split("/")[1].lower()
    373 ):
    374     if any([module.include_prompt for module in self if isinstance(module, Pooling)]):
    375         logger.warning(
    376             "Instructor models require `include_prompt=False` in the pooling configuration. "
    377             "Either update the model configuration or call `model.set_pooling_include_prompt(False)` after loading the model."
    378         )

TypeError: argument of type 'PosixPath' is not iterable
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/10695 fixed the failed line (`sentence_transformers.SentenceTransformer.load(local_model_dir)`).

**Comment by tcambon** [comment]
Hi Harupy,
Thanks for your quick answer.
Indeed upgrading mlflow fix my issue.
Maybe updating the version requirements in the doc could be useful ?

**Comment by harupy** [comment]
> Maybe updating the version requirements in the doc

can you elaborate? where should we update?

**Comment by tcambon** [comment]
https://mlflow.org/docs/latest/python_api/mlflow.sentence_transformers.html
In load model there is a note:
The ‘sentence_transformers’ MLflow Models integration is known to be compatible with the following package version ranges: 2.2.2 - 3.1.1
Whereas in my example it needs to be higher than 2.10

**Comment by harupy** [comment]
@tcambon 2.2.2 - 3.1.1 is the sentence_transformers version range. Filed #13382 to improve the message.
