### ISSUE TITLE
[BUG] Can't specify params when running inference on MLServer 

### ISSUE THREAD

**Issue by svpino** [mlflow/mlflow#13411]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.16.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sequoia 15.0.1
- **Python version**: 3.12.6
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When deploying the model using MLServer, we can't specify `params` as part of the request.

Here is the error returned by the server:

```
{"error":"mlflow.utils.proto_json_utils.MlflowInvalidInputException: Invalid input. One of \"instances\" and \"inputs\" must be specified (not both or any other keys).Received: ['inputs', 'params']"}%
```

Here is how I'm running the server:

```
mlflow models serve -m runs:/<run_id>/model -p 5000 --enable-mlserver
```

Here is an example of the request:

```
curl -X POST http://0.0.0.0:8080/invocations \
    -H "Content-Type: application/json" \
    -d '{"inputs": [{
            "sex": "MALE"
        }], 
        "params": {"capture": true}}'
```

The above request works when not using the MLServer:

```
mlflow models serve -m runs:/<run_id>/model -p 5000
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
cc @serena-ruan do you know if this is an MLserver problem? it looks like the serving JSON input should be correct

**Comment by serena-ruan** [comment]
Hi @svpino Thanks for asking, this is because MLServer doesn't support this feature https://github.com/SeldonIO/MLServer/blob/8ac1d28c518fbfd39af2f8e0ef0b892208635148/runtimes/mlflow/mlserver_mlflow/runtime.py
If you'd like this feature, could you open an issue in their repo? It seems MLServer is not super active now :)

**Comment by svpino** [comment]
Thanks @serena-ruan! I'll open an issue on their repo. Let's hope they look at it.
