### ISSUE TITLE
is `mlflow server` and `mlflow ui` linked internally while running on server

### ISSUE THREAD

**Issue by analystanand** [mlflow/mlflow#1341]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**:  pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**:  3.5.2
- **npm version (if running the dev UI):
- **Exact command to reproduce**: `mlflow server`

### Describe the problem
`mlflow server` automatically starts the user interface(`mlflow ui`).  

is it expected behavior?

I thought we need to run both explicitily on different ports.

**Comment by ankitmathur-db** [comment]
Yes, this is expected behavior - you can run one or the other. MLFlow UI is more intended for local usage, whereas MLFlow Server runs on a different IP.
