### ISSUE TITLE
[BUG] Once model.set_retriever_schema is set, it is not possible to update it

### ISSUE THREAD

**Issue by edurdevic** [mlflow/mlflow#13424]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.17.0

### System information

- Databricks serverless

### Describe the problem

There is a regression on the function `mlflow.models.set_retriever_schema`.
Previously calling it multiple time it used to overwrite the retriever schema, since #13246 it throws an exception.
Since there are no methods to remove/clear a retriever schema, once set it cannot be updated.

### Tracking information

```shell
MLflow version: 2.17.0
Tracking URI: databricks
Artifact URI: dbfs:/databricks/mlflow-tracking/d8fed2d0835f4e3b98a6bf18a8c00f2b/5359f67824c34335b63faa2c0f332d39/artifacts
System information: Linux #76~20.04.1-Ubuntu SMP Mon Sep 2 12:20:36 UTC 2024
Python version: 3.10.12
MLflow version: 2.17.0
MLflow module location: /local_disk0/.ephemeral_nfs/envs/pythonEnv-ac98e3ee-7906-434e-9234-552292e0a4e9/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: databricks
Registry URI: databricks-uc
Databricks runtime version: client.1.11
Active experiment ID: d8fed2d0835f4e3b98a6bf18a8c00f2b
Active run ID: 5359f67824c34335b63faa2c0f332d39
Active run artifact URI: dbfs:/databricks/mlflow-tracking/d8fed2d0835f4e3b98a6bf18a8c00f2b/5359f67824c34335b63faa2c0f332d39/artifacts
MLflow environment variables: 
  MLFLOW_CONDA_HOME: /databricks/conda
  MLFLOW_DEPLOYMENTS_TARGET: databricks
  MLFLOW_GATEWAY_URI: databricks
  MLFLOW_PYTHON_EXECUTABLE: /databricks/spark/scripts/mlflow_python.sh
  MLFLOW_TRACKING_URI: databricks
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.2
  alembic: 1.13.3
  azure-storage-file-datalake: 12.17.0
  boto3: 1.35.41
  botocore: 1.35.41
  docker: 7.1.0
  google-cloud-storage: 2.18.2
  graphene: 3.3
  gunicorn: 23.0.0
  markdown: 3.7
  matplotlib: 3.7.0
  mlflow-skinny: 2.17.0
  numpy: 1.23.5
  pandas: 1.5.3
  pyarrow: 8.0.0
  pydantic: 1.10.6
  scikit-learn: 1.1.1
  scipy: 1.10.0
  sqlalchemy: 2.0.36
  virtualenv: 20.16.7
```

### Code to reproduce issue

```
import mlflow

mlflow.models.set_retriever_schema(
            primary_key="a",
            text_column="b",
            doc_uri="c",
        )

mlflow.models.set_retriever_schema(
            primary_key="a2",
            text_column="b2",
            doc_uri="c2",
        )
```

### Stack trace

```
---------------------------------------------------------------------------
MlflowException                           Traceback (most recent call last)
File <command-3819540237271006>, line 3
      1 import mlflow
----> 3 mlflow.models.set_retriever_schema(
      4             primary_key="a",
      5             text_column="b",
      6             doc_uri="c",
      7         )
      9 mlflow.models.set_retriever_schema(
     10             primary_key="a2",
     11             text_column="b2",
     12             doc_uri="c2",
     13         )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-ac98e3ee-7906-434e-9234-552292e0a4e9/lib/python3.10/site-packages/mlflow/models/dependencies_schemas.py:61, in set_retriever_schema(primary_key, text_column, doc_uri, other_columns, name)
     58 if any(schema["name"] == name for schema in retriever_schema):
     59     # reset if there is an error to clear the global state for next run
     60     _clear_retriever_schema()
---> 61     raise MlflowException(
     62         f"A retriever schema with the name '{name}' already exists.",
     63         error_code=ALREADY_EXISTS,
     64     )
     66 retriever_schema.append(
     67     {
     68         "primary_key": primary_key,
   (...)
     73     }
     74 )
     75 globals()[DependenciesSchemasType.RETRIEVERS.value] = retriever_schema

MlflowException: A retriever schema with the name 'retriever' already exists.
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by sunishsheth2009** [comment]
Fixed here: https://github.com/mlflow/mlflow/pull/13422
