### ISSUE TITLE
[FR] MLflow Tracing for Anthropic

### ISSUE THREAD

**Issue by B-Step62** [mlflow/mlflow#13426]
### Summary

Expand [auto-tracing integration](https://mlflow.org/docs/latest/llms/tracing/index.html#automatic-tracing) of MLflow Tracing to Anthropic SDK. MLflow already supports auto-tracing for OpenAI SDK, so this work will look similar to that.

### Required Changes
Please refer to [how to add new integration to MLflow Tracing](https://mlflow.org/docs/latest/llms/tracing/contribute.html) for the actual steps of adding new auto-tracing integration. MLflow maintainers will provide attentive support for designing and implementing the change.

### Expected Behavior

1. Users can enable auto-tracing by calling `mlflow.anthoropic.autolog()`
```
import mlflow

mlflow.anthropic.autolog()

client = anthropic.Anthropic()  # with env var ANTHROPIC_API_KEY set 
message = client.messages.create(
    model="claude-3-5-sonnet-20240620",
    messages=[
        {"role": "user", "content": "Hello, Claude"}
    ]
)
```
2. This will generates a trace like this (taken from OpenAI example):
![image](https://github.com/user-attachments/assets/54188ec0-c061-4e3e-8397-3d886b2c3e07)

**Comment by TomeHirata** [comment]
Hi, @gabrielfu. I'm a new core maintainer member of the ML OSS team in Databricks. I'm sorry that we didn't communicate this with you before you picked this ticket up, but can you let us work on this ticket?

**Comment by gabrielfu** [comment]
> Hi, @gabrielfu. I'm a new core maintainer member of the ML OSS team in Databricks. Have you started implementing this task? If not, can you let us work on this ticket?

Hey @TomeHirata , no problem :)

**Comment by TomeHirata** [comment]
@gabrielfu Sorry for the back-and-forth, but after discussing it internally, we'd like you to own this ticket. So can you continue to work on this ticket? Please ping any of us if you need any clarification. 🙏

**Comment by gabrielfu** [comment]
> @gabrielfu Sorry for the back-and-forth, but after discussing it internally, we'd like you to own this ticket. So can you continue to work on this ticket? Please ping any of us if you need any clarification. 🙏

@TomeHirata no problem! I have started working on it :)
