### ISSUE TITLE
Add support for adding notes to Experiments

### ISSUE THREAD

**Issue by aminought** [mlflow/mlflow#1346]
It's true that everyone understands words "experiment" and "run" their own way. I think that "experiment" is something like hypothesis testing and it would be cool if I could take some notes about what is my hypothesis. Yes, now we have notes for runs, but it is something unique for each run, and I want something to describe all runs in experiment. So, I would like to see something similar to Run Notes in Experiments section. What do you think?

**Comment by Zangr** [comment]
This is coming soon. (@ankitmathur-db is working on this)

**Comment by rquintino** [comment]
I was about to create a new fr issue, but think will post thoughts here instead :) Maybe experiments could be enough! looking forward to test this one.

----
Comparing, documenting and evaluating run results and results of experiments probably plays a major role for teams using mlflow. But currently there's no much support for saving those evaluations/insights on mlflow, where they seem to belong.  We do have notes for runs, but  evaluation usually involves comparing several runs. 

Could a new kind of "report" concept be added? that would allow to pick runs (even from different experiments), eval results, and at least support adding notes to the report?

Adding this to experiments instead could be an option also (quicker?). But concerned that right now we cannot compare runs between experiments, so would limit a bit.

Anything that could capture minimal evaluation of experiments inside mlflow.
---

**Comment by ankitmathur-db** [comment]
Hi @rquintino! Tags on experiments are live on the API in master, and a UI-side PR is coming soon. We'll take your recommendation about adding the concept of generating reports to compare runs under advisement, but we can't promise this is going to be on the immediate roadmap. If there's an easy way to include it, we'd love to review PRs though!

**Comment by ankitmathur-db** [comment]
We just merged the UI side of things as well - feel free to try it out!
