### ISSUE TITLE
[SETUP-BUG] Error duing MLFlow installation

### ISSUE THREAD

**Issue by kumareshav** [mlflow/mlflow#13500]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**:
- **Python version**:
Windows 10 x64
pip install MLFlow
Python 3.13

### Code to reproduce issue

pip install MLFlow

### Describe the problem

Receive the below error while executing the above command.

![image](https://github.com/user-attachments/assets/3de376e9-1917-42b5-9f51-37d39a471c9c)

**Comment by WeichenXu123** [comment]
could you paste your pyarrow version to be installed ? and the python version you use ?

I think pyarrow don't have prebuilt wheel for the python version 3.13. you can try using lower python version. And building pyarrow wheel error is not related to MLflow.

**Comment by WeichenXu123** [comment]
Seemingly pyarrow hasn't supported python 3.13 yet: https://pypi.org/project/pyarrow/

**Comment by kumareshav** [comment]
ok perfect, I am downgrading my python version to 3.12.5 and will install mlflow again

**Comment by niklasdiehm** [comment]
Python 3.13 is [now supported by pyarrow](https://github.com/apache/arrow/issues/44510#issuecomment-2441257335). Are you planning to include pyarrow==18.0.0 in one of the next releases?
