### ISSUE TITLE
[ARTIFACTS-BUG] Active run artifact URI is not matching --default-artifact-root 

### ISSUE THREAD

**Issue by khac** [mlflow/mlflow#13509]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.17.0
- Tracking server: 2.16.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux release 7.4
- **Python version**: 3.9.20
- **yarn version, if running the dev UI**: n/a

### Describe the problem

I am defining tracking server with 

```
 mlflow server --host <ip_addr>  --port <port_num>  --default-artifact-root hdfs://path1/path2/path3 --artifacts-destination  hdfs://path1/path2/path3 
```

At the client side the artiface URI is local dir
```
Active experiment ID: 477343419273435142
Active run ID: 722e0c59924f492f9bb8bab4e16d456b
Active run artifact URI: /MLflow/artifacts/722e0c59924f492f9bb8bab4e16d456b/artifacts
```

the active run artifact URI is not the `hdfs` path, this is causing the ML artifacts to be stored on the clients local machine rather than on `hdfs`

### Tracking information

```shell
 mlflow server --host <ip_addr>  --port <port_num>  --default-artifact-root hdfs://path1/path2/path3 --artifacts-destination  hdfs://path1/path2/path3 
```

### Code to reproduce issue

```
import mlflow

def main():
    mlflow.set_tracking_uri(uri="URI")
    exp = mlflow.set_experiment(experiment_name="experiment_name")

    date = "2024-10-01"
    model_tags = {"tag1":"val1", "tag2":"val2", "tag3":"val3"}
    with mlflow.start_run(experiment_id=exp.experiment_id, tags=model_tags):
        mlflow.doctor()
        mlflow.log_params(params)
        mlflow.log_artifacts(artifacts)

if __name__ == "__main__":
    main()

```

### Stack trace

Client Machine
```
System information: Linux #1 SMP Tue Aug 22 21:09:27 UTC 2017
Python version: 3.9.20
MLflow version: 2.17.0
MLflow module location: /home/user/anaconda3/envs/conda-env/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: http://10.145.80.204:9001/
Registry URI: http://10.145.80.204:9001/
Active experiment ID: 477343419273435142
Active run ID: 97a4c11757744b9cab0860e1fb853e26
Active run artifact URI: /MLflow/artifacts/97a4c11757744b9cab0860e1fb853e26/artifacts
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  aiohttp: 3.9.5
  alembic: 1.13.3
  cachetools: 5.5.0
  click: 8.1.3
  cloudpickle: 3.1.0
  databricks-sdk: 0.34.0
  docker: 7.1.0
  gitpython: 3.1.43
  graphene: 3.4
  gunicorn: 22.0.0
  importlib-metadata: 6.8.0
  markdown: 3.6
  matplotlib: 3.4.3
  numpy: 1.26.4
  opentelemetry-api: 1.27.0
  opentelemetry-sdk: 1.27.0
  packaging: 23.1
  pandas: 2.2.1
  prometheus-flask-exporter: 0.23.1
  protobuf: 4.25.3
  pyarrow: 16.1.0
  pyyaml: 6.0.1
  requests: 2.32.3
  scikit-learn: 1.4.2
  scipy: 1.13.1
  sqlalchemy: 1.4.49
  sqlparse: 0.5.1

2024/10/22 01:34:31 INFO mlflow.tracking._tracking_service.client: 🏃 View run incongruous-hog-897 at: http://<ip_addr>/#/experiments/477343419273435142/runs/97a4c11757744b9cab0860e1fb853e26.
2024/10/22 01:34:31 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://<ip_addr>/#/experiments/477343419273435142.

```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by khac** [comment]
@WeichenXu123 can you take a look

**Comment by WeichenXu123** [comment]
Seems to be a similar issue of https://github.com/mlflow/mlflow/issues/13470

Could you try approach https://github.com/mlflow/mlflow/issues/13470#issuecomment-2423598516 ? :) 

and if you specifies `--default-artifact-root`, you don't need to specify `--artifacts-destination`

**Comment by khac** [comment]
```
--default-artifact-root configuration only works when MLflow creates backend storage the first time.
```
makes sense, ok closing this issue
