### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nicorne** [mlflow/mlflow#13520]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

2.17

### System information

- **OS Platform and Distribution (e.g., MacOs 14.1.1 (23B81))**:
- **Python 3.11**:

### Describe the problem

Pages for LLM Traces give me an error

### Steps to reproduce the bug

I am using the OpenAI lib to create embeddings and make completions.

My MLflow code:
```
import mlflow
mlflow.set_tracking_uri("http://127.0.0.1:5000")

with mlflow.start_run():
   mlflow.openai.autolog()
   ### My OpenAI completion and embedding requests ###
 ```
   
In my terminal, I run:
`mlflow ui`

I open http://127.0.0.1:5000/ and I can see the list of Traces:
![Screenshot 2024-10-23 at 13 17 09](https://github.com/user-attachments/assets/0359ebf2-6f16-4bc7-a637-967d6c9be05b)

However when clicking on a Trace, I get an error:
![Screenshot 2024-10-23 at 13 17 40](https://github.com/user-attachments/assets/29b8e23d-cdb8-43a0-bae9-9d5e5ae7fcf0)

### Code to generate data required to reproduce the bug
See above

### Is the console panel in DevTools showing errors relevant to the bug?
![Screenshot 2024-10-23 at 13 20 27](https://github.com/user-attachments/assets/e3041c94-31cf-4d26-8db5-13813faa13b4)

### Does the network panel in DevTools contain failed requests relevant to the bug?
![Screenshot 2024-10-23 at 13 20 27](https://github.com/user-attachments/assets/e3041c94-31cf-4d26-8db5-13813faa13b4)

**Comment by B-Step62** [comment]
@nicorne I cannot reproduce the issue - I ran the example code and successfully see the trace on the UI.

Could you share more details about your environment setup? Are you setting a custom artifact store location?

**Comment by nicorne** [comment]
hey @B-Step62, I'll try this again and give you more context on the error. 

Are you setting a custom artifact store location?
I am not. An mlartifacts folder is created by mlflow when running it.
