### ISSUE TITLE
Feature request: Zooming plots

### ISSUE THREAD

**Issue by stablum** [mlflow/mlflow#1354]
### Describe the problem
Sometimes the plot of a quantity evolves over the epochs to amounts that are way more stable than the beginning.
For example, MAE might be around a value of 30.0 at the beginning and then converging at 0.1 after 100 epochs. This is where it's interesting, especially to compare with other runs. Sometimes it's very important to verify that a certain run is converting towards 0.09 versus another one that is 0.11. Hence, zooming is the only way to verify the amount with those tiny deltas.
The initial uninteresting large amounts are skewing the zooming to a uselessly large view.

I understand that the ui is using plotly. Maybe it's just matter of setting a parameter and then zoom is activated without much effort?

**Comment by stablum** [comment]
WOW you actually implemented it in version 1.0.0! That's amazing!! :D

**Comment by jeremyjordan** [comment]
I suggest you close this issue :)
