### ISSUE TITLE
Feature request: number of epochs column

### ISSUE THREAD

**Issue by stablum** [mlflow/mlflow#1355]
It's really important to have an overview of how far is each run, but the only current solution is log_metric the epoch number in order to have it visualized in the summary table in the ui.
This is a horrible hack, and it would be nice to have mlflow count the epochs for me.

**Comment by aminought** [comment]
log_param

**Comment by stablum** [comment]
the *current epoch number* during a run is not a parameter

**Comment by aminought** [comment]
Why? You can create nested runs and log current epoch number as a parameter. Technically, it _is_ a hyperparameter that you want to optimize.

**Comment by andrewmchen** [comment]
Using `set_tag` or `log_param` seems reasonable to me. Please re-open if you'd like to discuss more.
