### ISSUE TITLE
mlflow server ignoring --default-artifact-root

### ISSUE THREAD

**Issue by yorickvP** [mlflow/mlflow#1357]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: NixOS 19.03
- **MLflow installed from (source or binary)**:  source (aba3ab278ecf2d06c0d25703609db7410b63e00b)
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: Python 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**: `mlflow server --default-artifact-root asdf; mlflow experiments create -n asdf; mlflow experiments list`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

Recently, 
https://github.com/mlflow/mlflow/blob/master/mlflow/store/file_store.py#L195-L196 was changed. This change causes artifact locations like `file:./mlruns/3`, even when `--default-artifact-url` is set. This has two problems:
1. I was depending on `--default-artifact-uri`, which is still available to this function as `self.artifact_root_uri`
2. the `file:` prefix is invalid, causing `mlflow.exceptions.MlflowException: Could not find a registered artifact repository for: file:./mlruns/2/25b088aa1ead480696244d46cbf1b461/artifacts. Currently registered schemes are: ['', 's3', 'gs', 'wasbs', 'ftp', 'sftp', 'dbfs']  `

**Comment by dbczumar** [comment]
This will be fixed by #1332.
