### ISSUE TITLE
[BUG] Cannot convert Param using to_proto if value is not a string

### ISSUE THREAD

**Issue by KantiCodes** [mlflow/mlflow#13588]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.17.1
- Tracking server: 2.17.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: WSL2
- **Python version**: 3.10

### Describe the problem

Cannot make `mlflow.entities.Param` that have values as strings:
# Does not work
```python
from mlflow.entities import Param
params = {
    "a": 5,
    "b": 6
}
params_conveted = [Param(key, value) for key, value in params.items()]
protobuffed = [param.to_proto() for param in params_conveted]
```

# Works
```python
from mlflow.entities import Param


params = {
    "a": 5,
    "b": 6
}

params_conveted = [Param(key, str(value)) for key, value in params.items()]
protobuffed = [param.to_proto() for param in params_conveted]
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/bartek/projects/netra-mlflow-monitoring/zzz.py", line 10, in <module>
    protobuffed = [param.to_proto() for param in params_conveted]
  File "/home/bartek/projects/netra-mlflow-monitoring/zzz.py", line 10, in <listcomp>
    protobuffed = [param.to_proto() for param in params_conveted]
  File "/home/bartek/.local/share/virtualenvs/netra-mlflow-monitoring-81cyanGE/lib/python3.10/site-packages/mlflow/entities/param.py", line 35, in to_proto
    param.value = self.value
TypeError: bad argument type for built-in operation
```

**Comment by B-Step62** [comment]
@KantiCodes The [mlflow.log_param()](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_param) API can be called with non-string values and MLflow handles proto converstion. What is the motivation to call `to_proto` manually?

**Comment by KantiCodes** [comment]
MlflowClient.log_batch calls it when I log parameters. So now in order to log batch I must convert all parameters to string now before sending

**Comment by KantiCodes** [comment]
mlflow.log_parameter converts to string all parameter values behind the scenes and this logic was not implemented into down stream calls of MlflowClient.log_batch

**Comment by KantiCodes** [comment]
No joke I cannot find my branch :D

**Comment by KantiCodes** [comment]
@B-Step62 can you respond?

**Comment by B-Step62** [comment]
@KantiCodes Sorry for the late response.

Strictly to say, by design the value of `Param` and `Tag` must be string. It is just that convenient APIs (`mlflow.log_param`) does conversion for users.

https://github.com/mlflow/mlflow/blob/4e61e71b4d099d84510b601aff0d043b98ba1c37/mlflow/entities/param.py#L29
```
    @property
    def value(self):
        """String value of the parameter."""
        return self._value
```

Since those entity classes should represent the data models, I don't think we should add implicit stringification for those classes directly. Instead, `log_batch` can do some sanitization on behalf of users. I will file a PR for that change.

**Comment by KantiCodes** [comment]
Thanks, lovely job!
