### ISSUE TITLE
[BUG] Too many `experiment_ids` specified in SearchRuns request error

### ISSUE THREAD

**Issue by sk-nagarro** [mlflow/mlflow#13590]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.14.1
- Tracking server: 2.14.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks Runtime 13.3 LTS
- **Python version**: 3.10

### Describe the problem

I expected to be able to query with more than 10 experiment IDs without encountering an error, as this was functioning correctly until recently.
Currently, I am unable to specify more than 10 experiment IDs in a `SearchRuns` request, receiving the error above.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
mlflow.search_runs(experiment_ids=experiments_df.rdd.map(lambda x: x.experiment_id).collect())
```

### Stack trace

```
---> 88     runs = mlflow.search_runs(experiment_ids=experiments_df.rdd.map(lambda x: x.experiment_id).collect())
     89     base_metrics = [
     90         "test_brier",
     91         "test_f1",
   (...)
     99         "train_recall",
    100     ]
    102     base_metrics = ["metrics." + x for x in base_metrics]

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/tracking/fluent.py:1980, in search_runs(experiment_ids, filter_string, run_view_type, max_results, order_by, output_format, search_all_experiments, experiment_names)
   1970     def pagination_wrapper_func(number_to_get, next_page_token):
   1971         return MlflowClient().search_runs(
   1972             experiment_ids,
   1973             filter_string,
   (...)
   1977             next_page_token,
   1978         )
-> 1980     runs = get_results_from_paginated_fn(
   1981         pagination_wrapper_func,
   1982         NUM_RUNS_PER_PAGE_PANDAS,
   1983         max_results,
   1984     )
   1986 if output_format == "list":
   1987     return runs  # List[mlflow.entities.run.Run]

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/utils/__init__.py:271, in get_results_from_paginated_fn(paginated_fn, max_results_per_page, max_results)
    269     page_results = paginated_fn(num_to_get, next_page_token)
    270 else:
--> 271     page_results = paginated_fn(max_results_per_page, next_page_token)
    272 all_results.extend(page_results)
    273 if hasattr(page_results, "token") and page_results.token:

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/tracking/fluent.py:1971, in search_runs.<locals>.pagination_wrapper_func(number_to_get, next_page_token)
   1970 def pagination_wrapper_func(number_to_get, next_page_token):
-> 1971     return MlflowClient().search_runs(
   1972         experiment_ids,
   1973         filter_string,
   1974         run_view_type,
   1975         number_to_get,
   1976         order_by,
   1977         next_page_token,
   1978     )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/tracking/client.py:3037, in MlflowClient.search_runs(self, experiment_ids, filter_string, run_view_type, max_results, order_by, page_token)
   2948 def search_runs(
   2949     self,
   2950     experiment_ids: List[str],
   (...)
   2955     page_token: Optional[str] = None,
   2956 ) -> PagedList[Run]:
   2957     """
   2958     Search for Runs that fit the specified criteria.
   2959 
   (...)
   3035         tags: {'s.release': '1.1.0-RC'}
   3036     """
-> 3037     return self._tracking_client.search_runs(
   3038         experiment_ids, filter_string, run_view_type, max_results, order_by, page_token
   3039     )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py:940, in TrackingServiceClient.search_runs(self, experiment_ids, filter_string, run_view_type, max_results, order_by, page_token)
    938 if isinstance(experiment_ids, int) or is_string_type(experiment_ids):
    939     experiment_ids = [experiment_ids]
--> 940 return self.store.search_runs(
    941     experiment_ids=experiment_ids,
    942     filter_string=filter_string,
    943     run_view_type=run_view_type,
    944     max_results=max_results,
    945     order_by=order_by,
    946     page_token=page_token,
    947 )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/store/tracking/abstract_store.py:548, in AbstractStore.search_runs(self, experiment_ids, filter_string, run_view_type, max_results, order_by, page_token)
    519 def search_runs(
    520     self,
    521     experiment_ids,
   (...)
    526     page_token=None,
    527 ):
    528     """
    529     Return runs that match the given list of search expressions within the experiments.
    530 
   (...)
    546         meaningful in such cases.
    547     """
--> 548     runs, token = self._search_runs(
    549         experiment_ids,
    550         filter_string,
    551         run_view_type,
    552         max_results,
    553         order_by,
    554         page_token,
    555     )
    556     return PagedList(runs, token)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py:499, in RestStore._search_runs(self, experiment_ids, filter_string, run_view_type, max_results, order_by, page_token)
    490 sr = SearchRuns(
    491     experiment_ids=experiment_ids,
    492     filter=filter_string,
   (...)
    496     page_token=page_token,
    497 )
    498 req_body = message_to_json(sr)
--> 499 response_proto = self._call_endpoint(SearchRuns, req_body)
    500 runs = [Run.from_proto(proto_run) for proto_run in response_proto.runs]
    501 # If next_page_token is not set, we will see it as "". We need to convert this to None.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py:81, in RestStore._call_endpoint(self, api, json_body, endpoint)
     79     endpoint, method = _METHOD_TO_INFO[api]
     80 response_proto = api.Response()
---> 81 return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/utils/rest_utils.py:304, in call_endpoint(host_creds, endpoint, method, json_body, response_proto, extra_headers)
    301     call_kwargs["json"] = json_body
    302     response = http_request(**call_kwargs)
--> 304 response = verify_rest_response(response, endpoint)
    305 js_dict = json.loads(response.text)
    306 parse_dict(js_dict=js_dict, message=response_proto)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/utils/rest_utils.py:174, in verify_rest_response(response, endpoint)
    172 if response.status_code != 200:
    173     if _can_parse_as_json_object(response.text):
--> 174         raise RestException(json.loads(response.text))
    175     else:
    176         base_msg = (
    177             f"API request to endpoint {endpoint} "
    178             f"failed with error code {response.status_code} != 200"
    179         )

RestException: INVALID_PARAMETER_VALUE: Too many `experiment_ids` specified in SearchRuns request. Maximum number of experiments allowed is 10. Found 45
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@sk-nagarro The error comes from Databricks backend. I will check with them for any change in service quota and get back to you.

**Comment by B-Step62** [comment]
@sk-nagarro Got response from the backend team. They recently deployed a change to limit number of experience ID to be passed to 10. They mentioned the limit can be adjusted, but need a bit more inputs to determine the right number. Could you elaborate on your use case, for instance, what is the motivation to query many experiments, what is the average number of experiments you would specify?

**Comment by sk-nagarro** [comment]
Thank you, @B-Step62 , for your response.

My use case is to create an ML metrics dashboard, where I am fetching metrics data from all experiments. Currently, I have over 50 experiments, and this number may increase in the future.

As you mentioned, the backend team has set a limit of 10. Could you please share the documentation link where this is detailed?

Additionally, could you provide the steps to adjust these limits?

**Comment by sk-nagarro** [comment]
Hello @B-Step62 , any update on above comments?

**Comment by B-Step62** [comment]
@sk-nagarro The backend team has merged a change to increase the limit to 100, which should be gradually rolled out to customer workspaces.

> Additionally, could you provide the steps to adjust these limits?

Afaik there is no way to adjust the limit. For further assistant, could you contact to the Databricks support team? This is OSS MLflow repository so we cannot help much but just transfer the request to the Databricks dev team.
