### ISSUE TITLE
[BUG] Trace recorded by openai.autolog does not map correct Run

### ISSUE THREAD

**Issue by yukimori** [mlflow/mlflow#13608]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.15.1
- Tracking server: 2.15.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Rocky Linux9
- **Python version**: python3.9
- **yarn version, if running the dev UI**:

### Describe the problem

I created runs with two different system prompts and executed openai.autolog within them. By specifying log_trace=True, I recorded the trace. While parameters and metrics were recorded for each run, the trace is associated with the first run in both cases.

I create 2 run and use openai.autlog on each run. 
1st Run: openai-evaluate-20241030-134133-0
2nd Run: openai-evaluate-20241030-134133-1
![image](https://github.com/user-attachments/assets/ae7cd394-50de-4e38-9777-7089ca1d5f31)

but the both traces is associated with the first Run.
I think trace should be associated with each Run.
![image](https://github.com/user-attachments/assets/27235503-e81c-4d6d-b4c5-68aa6a23b102)

I think the reason for this bug is that when run_id is retrieved with getattr, it is not checked if the id matches the active_run.

https://github.com/mlflow/mlflow/blob/master/mlflow/openai/_openai_autolog.py#L101
```
    config = AutoLoggingConfig.init(flavor_name=mlflow.openai.FLAVOR_NAME)
    run_id = getattr(self, "_mlflow_run_id", None)
    active_run = mlflow.active_run()
    mlflow_client = mlflow.MlflowClient()
```

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
import os
from openai import OpenAI
import datetime

client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY", "<your OpenAI API key if not set as env var>"))

system_prompts = [
    "Please provide an answer to the question in 50 characters or less.",
    "You are a Python expert. Please provide an answer related to Python in response to the question, within 100 characters.",
]

test_input = "What is MLflow？"
mlflow.set_experiment("examin-openai-en")
run_date = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# Change the system prompt with each run. Record the input and the corresponding output (OpenAI API response).
for i, system_prompt in enumerate(system_prompts):
    with mlflow.start_run(run_name=f"openai-evaluate-{run_date}-{i}") as run:
        print(f"active_run_id: {mlflow.active_run().info.run_id}")
        mlflow.openai.autolog(log_input_examples=True,
                                log_model_signatures=True,
                                log_models=True,
                                log_traces=True,
                                extra_tags={"system_prompt": system_prompt})

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": test_input},
            ],
            temperature=0,
        )
```

### Stack trace

This bug has no stack trace. But I explained the detail cause of this bug on description.

### Other info / logs

```
[13:38:49] -> % python mlflow_openai_autolog_en.py

# here is the first active run
active_run_id: 9678e903550846308c6f08c62c6bd113

2024/10/30 13:41:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run openai-evaluate-20241030-134133-0 at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705/runs/9678e903550846308c6f08c62c6bd113.
2024/10/30 13:41:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705.

# here is the second active run
active_run_id: cbbf2c5ed2404faea7135ffc3c0184a2
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run openai-evaluate-20241030-134133-0 at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705/runs/9678e903550846308c6f08c62c6bd113.
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705.
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run openai-evaluate-20241030-134133-1 at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705/runs/cbbf2c5ed2404faea7135ffc3c0184a2.
2024/10/30 13:41:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://myuhara.mlflow.yahoo.co.jp/#/experiments/2705.
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@yukimori Thank you for reporting the issue! I could reproduce the issue and it seems this is a bug in the priority of run ID handling within autolog.

We submitted the fix PR https://github.com/mlflow/mlflow/pull/13611. Could you install the patch and verify the fix? 
`pip install git+https://github.com/mlflow/mlflow.git@refs/pull/13611/merge`

**Comment by yukimori** [comment]
@B-Step62 Thank you for your PF!
I installed the PR according to your instructions and and confirmed it works as expected.
