### ISSUE TITLE
Enable global-variable-not-assigned (PLW0602)

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#13634]
### Summary

Related to https://github.com/mlflow/mlflow/pull/13419#discussion_r1824167284. https://docs.astral.sh/ruff/rules/global-variable-not-assigned/ should be enabled

> The global keyword allows an inner scope to modify a variable declared in the outer scope. If the variable is not modified within the inner scope, there is no need to use global.

Example:

```
tests/db/test_tracking_operations.py:121:16: PLW0602 Using global for `connect_counter` but no assignment is done
    |
119 |     def connect(*args, **kwargs):
120 |         """Wraps sqlite3.dbapi.connect(), returning a wrapped connection."""
121 |         global connect_counter
    |                ^^^^^^^^^^^^^^^ PLW0602
122 |         conn = old_connect(*args, **kwargs)
123 |         return ConnectionWrapper(conn)
```

### Required changes

```diff
diff --git a/pyproject.toml b/pyproject.toml
index ca1a9eb40..17f7e28cf 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -186,6 +186,7 @@ select = [
   "PIE790",  # unnecessary-placeholder
   "PLR0402", # manual-from-import
   "PLE1205", # logging-too-many-args
+  "PLW0602", # global-variable-not-assigned
   "PT001",   # pytest-fixture-incorrect-parentheses-style
   "PT002",   # pytest-fixture-positional-args
   "PT003",   # pytest-extraneous-scope-function
```

Once the rule is added, run `ruff check .` in the repository root to locate the violating lines and remove them.

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by gitlijian** [comment]
hi, harupy.  I am interested in taking up this issue. Can I solve this problem?

**Comment by harupy** [comment]
@gitlijian Go ahead!

**Comment by gitlijian** [comment]
I have checked all global-variable-not-assigned places and made modifications，Can my changes be merged? Do you still want me to write a ruff rule? @harupy

**Comment by harupy** [comment]
@gitlijian Thanks! Can you file a PR?

**Comment by gitlijian** [comment]
@harupy ok
