### ISSUE TITLE
Model parameters added to gateway query

### ISSUE THREAD

**Issue by rmporsch** [mlflow/mlflow#13648]
> Having the same issue as OP
> 
> When I include only `set_deployments_target("http://127.0.0.1:7000")` I get `mlflow.exceptions.MlflowException: No Gateway server uri has been set. Please either set the MLflow Gateway URI via `mlflow.gateway.set_gateway_uri()` or set the environment variable MLFLOW_GATEWAY_URI to the running Gateway API server's uri`
> 
> When I include only `mlflow.gateway.set_gateway_uri("http://127.0.0.1:7000")` I get requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://127.0.0.1:7000/gateway/claude-instant-1.2/invocations. Response text: {"detail":"route_type: Extra inputs are not permitted"}
> 
> Using latest version `2.15.1`

I am observing the same with `2.17.3`, both setting the variables within python or via ENV.

It seems that models created via the Prompt Engineering UX are adding the following parameter
![image](https://github.com/user-attachments/assets/72e45754-fd3e-4bad-8c33-9e1dab99c2b3)

This is then wrongfully added to the json data 

```python
model_parameters_as_dict = {param.key: param.value for param in self.model_parameters}
```
within the `_PromptLabModel`

```python
class _PromptlabModel:
    import pandas as pd

    def __init__(self, prompt_template, prompt_parameters, model_parameters, model_route):
        self.prompt_parameters = prompt_parameters
        self.model_parameters = model_parameters
        self.model_route = model_route
        self.prompt_template = prompt_template

    def predict(self, inputs: pd.DataFrame) -> List[str]:
        from mlflow.gateway import query

        results = []
        for idx in inputs.index:
            prompt_parameters_as_dict = {
                param.key: inputs[param.key][idx] for param in self.prompt_parameters
            }

            # copy replacement logic from PromptEngineering.utils.ts for consistency
            prompt = self.prompt_template
            for key, value in prompt_parameters_as_dict.items():
                prompt = re.sub(r"\{\{\s*" + key + r"\s*\}\}", value, prompt)

            model_parameters_as_dict = {param.key: param.value for param in self.model_parameters}
            query_data = self._construct_query_data(prompt)

            response = query(
                route=self.model_route, data={**query_data, **model_parameters_as_dict}
            )
            results.append(self._parse_gateway_response(response))

        return results
``` 

Not sure how to fix this as I am not too familiar with this library.

_Originally posted by @rmporsch in https://github.com/mlflow/mlflow/issues/11049#issuecomment-2453311314_

**Comment by harupy** [comment]
@rmporsch Thanks for reporting this. I'll reply to @11049. Closing this one as it's a duplicated.
