### ISSUE TITLE
Use `monkeypatch.setenv` to set environment variables in tests

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#13651]
### Summary

https://docs.pytest.org/en/stable/reference/reference.html#pytest.MonkeyPatch.setenv should be used when setting environment variables in tests to ensure they are cleaned up after test invocation:

```diff
diff --git a/tests/deployments/test_deployments.py b/tests/deployments/test_deployments.py
index 4902c3ee8a..c2598de54a 100644
--- a/tests/deployments/test_deployments.py
+++ b/tests/deployments/test_deployments.py
@@ -95,13 +95,12 @@ def test_plugin_doesnot_have_required_attrib():
         plugin_manager["dummy"]
 
 
-def test_plugin_raising_error():
+def test_plugin_raising_error(monkeypatch):
     client = deployments.get_deploy_client(f_target)
     # special case to raise error
-    os.environ["raiseError"] = "True"
+    monkeypatch.setenv("raiseError", "True")
     with pytest.raises(RuntimeError, match="Error requested"):
         client.list_deployments()
-    os.environ["raiseError"] = "False"
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by parag-shendye** [comment]
Hi I am interested in taking up this issue, I have searched for "monkeypatch" in other test files for example db.conftest, it is already done there. Should I check all the test files for it or should it be done only in deployment?

**Comment by harupy** [comment]
@parag-shendye Thanks for the comment! No, just fixing `test_plugin_raising_error` is fine :)

**Comment by parag-shendye** [comment]
@harupy  thanks ! I will take up this issue then
