### ISSUE TITLE
[BUG] Runs with 0-valued metrics don't appear in experiment list scatter plots

### ISSUE THREAD

**Issue by erik-hasse** [mlflow/mlflow#13659]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.17.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Sonoma 14.5
- **Python version**: 3.11
- **yarn version, if running the dev UI**: N/A

### Describe the problem

Runs with 0-valued metrics don't appear in experiment list scatter plots. 0-valued params work as expected. There are 5 runs logged with (0,4), (1, 3), (2, 2), (3, 1), and (4, 0) as the param, metric pairs. Note that only 4 dots appear
![Screenshot 2024-11-04 at 16 49 56](https://github.com/user-attachments/assets/ea33830c-b0e6-4a26-99a6-3a01f34419ab)

A few additional notes:
- The run name does appear in the legend
- If the corresponding CSV is downloaded the run is there
- This also seems to happen for metrics in the contour plot

### Steps to reproduce the bug

1. Log runs with the provided code
2. Start the UI
3. View the experiment list plots
4. Add a new plot with Metrics.y on one or both axes
5. Notice that the run with Metrics.y==0 is missing

### Code to generate data required to reproduce the bug

```python
import mlflow

for i in range(5):
    with mlflow.start_run():
        mlflow.log_param("x", i)
        mlflow.log_metric("y", 4-i)
```

**Comment by harupy** [comment]
@erik-hasse I was able to reproduce the issue. I'll look into what's the cause.

**Comment by erik-hasse** [comment]
Incredible speed. Thanks @harupy!
