### ISSUE TITLE
[DOC-FIX] `mlflow.log_image` sygnature inconsistent with docs

### ISSUE THREAD

**Issue by OliBravo** [mlflow/mlflow#13687]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_image

### Description of proposal (what needs changing)

In docs we read the function takes `run_id` as one of arguments. But the signature of the function is different. When providing a run_id as a named argument to the function call one gets an error "unexpected keyword argument 'run_id'". Add `run_id` to arguments.

**Comment by harupy** [comment]
@OliBravo Thanks for reporting this. https://github.com/mlflow/mlflow/pull/13399 removed the `run_id` argument in the dcostring.
