### ISSUE TITLE
[BUG] OpenAI Tracing does not work inside evaluate

### ISSUE THREAD

**Issue by heyitsaamir** [mlflow/mlflow#13765]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.17.2

### System information

- **MacOS Sequoia**:
- **3.11**:

### Describe the problem

I'm running an experiment where my experiment is a codeblock function. Inside that function I have an open AI completions call. At the top of my experiments file, I have set autologging to true for OpenAI. However, the tracing never happens.

I've narrowed it down to this line:
https://github.com/mlflow/mlflow/blob/727e2477382243774324cfe332a5b422b68f2a23/mlflow/models/evaluation/default_evaluator.py#L870

It seems like when `evaluate` is being called, autlogging is globally disabled for some unknown reason. If, in my evaluate function I set `mlflow.utils.autologging_utils._AUTOLOGGING_GLOBALLY_DISABLED = False`, then tracing works as expected.

### Tracking information

```shell
System information: Darwin Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
Python version: 3.12.5
MLflow version: 2.17.2
MLflow module location: /python/.venv/lib/python3.12/site-packages/mlflow/__init__.py
Tracking URI: http://127.0.0.1:8080
Registry URI: http://127.0.0.1:8080
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  aiohttp: 3.10.5
  alembic: 1.14.0
  docker: 7.1.0
  graphene: 3.4.3
  gunicorn: 23.0.0
  langchain: 0.3.4
  markdown: 3.7
  matplotlib: 3.9.2
  mlflow-skinny: 2.17.2
  numpy: 1.26.4
  pandas: 2.2.3
  pyarrow: 17.0.0
  pydantic: 2.9.1
  scikit-learn: 1.5.2
  scipy: 1.14.1
  sqlalchemy: 2.0.36
  tiktoken: 0.7.0
```

### Code to reproduce issue

```python
import click
import mlflow
import openai
import pandas
from mlflow.metrics import MetricValue, make_metric
from mlflow.metrics.base import standard_aggregations

mlflow.set_tracking_uri("http://127.0.0.1:8080")
mlflow.openai.autolog(
    log_traces=True,
)

eval_data = [
    "What is MLflow?",
    "What is Spark?",
]


def eval_fn(predictions: pandas.Series):
    scores = []
    print("predictions", predictions)
    for i in range(len(predictions)):
        print(predictions.values[i])
        if len(predictions.values[i]) > 10:
            scores.append(1.0)
        else:
            scores.append(0.0)
    return MetricValue(
        scores=scores,
        aggregate_results=standard_aggregations(scores),
    )


# Create an EvaluationMetric object.
passing_code_metric = make_metric(eval_fn=eval_fn, greater_is_better=False, name="over_10_chars")


def openai_qa(inputs):
    answers = []
    system_prompt = "Please answer the following question in formal language."
    for index, row in inputs.iterrows():
        completion = openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": "{row}"},
            ],
        )
        answers.append(completion.choices[0].message.content)

    return answers


@click.command()
def run():
    with mlflow.start_run() as run:
        results = mlflow.evaluate(openai_qa, eval_data, extra_metrics=[passing_code_metric])


if __name__ == "__main__":
    run()

```

### Stack trace

```
REPLACE_ME
```
No stack trace.

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Thanks for reporting this @heyitsaamir ! This looks like a bug, we should add OpenAI flavor to the exemption as well since it only contains tracing in autologging. Any concerns here @B-Step62 ?

**Comment by B-Step62** [comment]
@serena-ruan Right, but we have to fix openai flavor's prediction logic, which uses raw requests library instead of OpenAI SDK. Since we patch OAI client, we need to fix it first to generate traces. Both are planned items in this quarter🙂

Btw this issue duplicates to existing one from the same author, so let me close this one now: https://github.com/mlflow/mlflow/issues/12952
