### ISSUE TITLE
gunicorn as optional dependency

### ISSUE THREAD

**Issue by js3711** [mlflow/mlflow#1378]
Currently gunicorn is listed as a required dependency even though it is only needed to start the mellow server (I believe).  This is preventing people from using mlflow to create runs from Windows.

Could gunicorn be listed as an option depency,  imported lazily and have a good error message if the package is missing?

**Comment by smurching** [comment]
@js3711 thanks for bringing this up, do you have an example of an error that results from this on Windows? We actually run our tests on Windows via Travis CI, so it's surprising to hear that run creation is broken.

Assuming `pip install gunicorn` works on Windows, the only benefit I think we get from removing gunicorn is dependency & package-size reduction. Gunicorn itself is a pretty small dependency ([~112Kb](https://pypi.org/project/gunicorn/#files)) and [only depends on setuptools](https://github.com/benoitc/gunicorn/blob/master/setup.py), so I'm not if the package

**Comment by js3711** [comment]
I was trying to install the gunicorn conda package from conda-forge where there is no windows version available:
https://anaconda.org/conda-forge/gunicorn/files

I have not attempted to pip install gunicorn from windows.  I did not have any concerns about introducing additional dependencies or trying to save space, I just ran into a road block installing via conda.

**Comment by dbczumar** [comment]
`gunicorn` is now specified as a Unix-only dependency (https://github.com/mlflow/mlflow/blob/1c85add051ccf88a570ac5c809180f630238c109/setup.py#L38); this should not affect Windows usability. I am going to close this issue because @js3711 was able to install `gunicorn` on Unix successfully.
