### ISSUE TITLE
[BUG] Can download artifacts for specific run, but cannot delete them. 

### ISSUE THREAD

**Issue by dkoterwa** [mlflow/mlflow#13792]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.16.0
- Tracking server: 2.16.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.4
- **Python version**: 3.10.12

### Describe the problem

I would like to delete artifacts for a specific run. However, I receive this error all the time:
`ResponseError('too many 500 error responses')`

This error is not raised when I am trying to download the artifact and the whole operation is handled without any issues.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
from mlflow.store.artifact.artifact_repository_registry import get_artifact_repository
from mlflow import MlflowClient

client = MlflowClient(tracking_uri=<tracking_uri>)
run = client.get_run(<run_id>)
repository = get_artifact_repository(run.info.artifact_uri)
repository.delete_artifacts(repository.list_artifacts()[0].path)
```

### Stack trace

```
Traceback (most recent call last):
  File "", line 25, in <module>
    repository.delete_artifacts(repository.list_artifacts()[0].path)
  File "/venv/lib/python3.10/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 113, in delete_artifacts
    resp = http_request(self._host_creds, endpoint, "DELETE", stream=True)
  File "/venv/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 211, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to <uri>/api/2.0/mlflow-artifacts/artifacts/experiment_id/run_id/artifacts/table.json failed with exception HTTPConnectionPool(host='', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/experiment_id/run_id/artifacts/table.json (Caused by ResponseError('too many 500 error responses'))
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@dkoterwa can you reproduce this error with the latest version of mlflow?

**Comment by dkoterwa** [comment]
@harupy Changing the version of mlflow and mlfow server fixed the problem, thank you. However, only admin users are able to delete artifacts from specific runs. Do you know what should be changed in order to give users with MANAGE permission access to experiments deletion?

**Comment by harupy** [comment]
@dkoterwa I think the user who creates the experiment should also have MANAGE permission.

**Comment by dkoterwa** [comment]
@harupy Thank you, my issue has been resolved.
