### ISSUE TITLE
How can I display Runs' status in the MLFlow UI?

### ISSUE THREAD

**Issue by Ahmedn1** [mlflow/mlflow#1380]
### Describe the problem
A feature request: 
Can we have a customizable table view or at least add the run's status to the table view?

**Comment by Galileo-Galilei** [comment]
I totally agree, it would be a nice feature to see in the ui which runs failed, are still running or have terminated. The run status is available through the run object but when you're collaborating or experimenting, it is useful to see at a glance what happenend in the various runs which are settled. My current workaround is to retireve the status it programmatically but it is not really convenient.

I guess the UI is not the current priority for mlflow developpers which focus on the core of the product (which is really amazing btw), but let's hope it will be added in the future releases.

**Comment by aarondav** [comment]
Definitely a good idea -- would welcome such a contribution!

**Comment by jdlesage** [comment]
Hello. There is this suggestion https://github.com/mlflow/mlflow/issues/2052 that try to solve the same problem ? What do you think ? What about to add also colors in the PR ?

**Comment by jdlesage** [comment]
Sorry, I just see in the PR the small color icons. That's nice! I think it solves both issues. Looking forward this PR merged in mlflow!

**Comment by simonberthaux** [comment]
This would be a game changer for productivity. Looking forward to this as well!

**Comment by florianblume** [comment]
This has already been integrated, hasn't it? I.e. the issue should be closed.

**Comment by Zangr** [comment]
@florianblume thanks for checking. Run status is supported on runs table since MLflow 1.6. Closing this issue.
