### ISSUE TITLE
[BUG] MLFlow LLM Traces UI is not able to render traces

### ISSUE THREAD

**Issue by HrushikeshPawar** [mlflow/mlflow#13829]
### MLflow version

2.18.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 24.04
- **Python version**: 3.12.6
- **yarn version, if running the dev UI**: NA

### Describe the problem

When opening any trace of a LLM call, the trace UI starts loading, but not able to show any traces, just blank screen.
Problem started after updating mlflow from 2.17.2 to 2.18.0

### Steps to reproduce the bug

- Setup mlflow server
- Start a new VSCode notebook (any Jupyter notebook should work)
- Setup mlflow autolog from llama-index
- Run a LLM query using llama-index
- Go to mlflow UI and the LLM Traces page
- Click on the latest trace to open
- The web-ui won't load

### Code to generate data required to reproduce the bug

```bash
mlflow server --host 127.0.0.1 --port 5000
```

```python
import mlflow
from llama_index.llms.gemini import Gemini
from llama_index.llms.openai import OpenAI

mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("llama-index-demo")
mlflow.llama_index.autolog()

gemini = Gemini(model="models/gemini-1.5-flash-002")
openai = OpenAI(model="gpt-4o-mini")

gemini.complete("Hello, how are you?")
openai.complete("Hello, how are you?")
```

### Is the console panel in DevTools showing errors relevant to the bug?

![image](https://github.com/user-attachments/assets/3d654d62-945a-4ee0-9e13-77cfb2a536ff)
```
GET http://localhost:5000/static-files/lib/ml-model-trace-renderer/js/ml-model-trace-renderer.6cdc9226.js net::ERR_ABORTED 404 (NOT FOUND)
```

### Does the network panel in DevTools contain failed requests relevant to the bug?

![image](https://github.com/user-attachments/assets/1fb3cdd0-924b-47ea-891f-17e7f99a1553)
```
Request URL: http://localhost:5000/static-files/lib/ml-model-trace-renderer/js/ml-model-trace-renderer.6cdc9226.js
Request Method: GET
Status Code: 404 NOT FOUND
Remote Address: 127.0.0.1:5000
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by harupy** [comment]
@HrushikeshPawar MLflow 2.18.0 has `ml-model-trace-renderer.7412f0e7.js`. `ml-model-trace-renderer.6cdc9226.js` is 2.17.0's `ml-model-trace-renderer.js`. Can you force-refresh your browser?

**Comment by harupy** [comment]
I could not reproduce the issue in 2.18.0.

<img width="982" alt="image" src="https://github.com/user-attachments/assets/397cc623-9dcc-4284-83e5-ef1be7fd408f">

<img width="982" alt="image" src="https://github.com/user-attachments/assets/bf2ada20-7a05-4563-9a23-153603ec94c8">

**Comment by harupy** [comment]
Trace UI uses two files:

- `mlflow/server/js/public/lib/ml-model-trace-renderer/index.html`
- `js/ml-model-trace-renderer.<hash>.js` (loaded by `ml-model-trace-renderer/index.html`)


I think this issue occurs when `mlflow/server/js/public/lib/ml-model-trace-renderer/index.html` is cached but `js/ml-model-trace-renderer.<hash>.js` is not.

**Comment by harupy** [comment]
Filed #13836

**Comment by harupy** [comment]
@HrushikeshPawar let me know if you find a way to reproduce the issue constantly.

**Comment by HrushikeshPawar** [comment]
> @HrushikeshPawar MLflow 2.18.0 has `ml-model-trace-renderer.7412f0e7.js`. `ml-model-trace-renderer.6cdc9226.js` is 2.17.0's `ml-model-trace-renderer.js`. Can you force-refresh your browser?

This did it. Was using brave browser. Clearing cache from before mlflow update made it work.
Was cache issue.
Thanks
