### ISSUE TITLE
[BUG] end_run() within nested run context affects parent run as well

### ISSUE THREAD

**Issue by casellimarco** [mlflow/mlflow#13874]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.15.5
- Tracking server: 2.12.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.10

### Describe the problem

Executing this code terminates both the nested and parent run, but from the documentation it should terminate only the nested one.

```
import mlflow

mlflow.set_experiment("nested_run_debugging")
with mlflow.start_run():
    for i in range(10):
        with mlflow.start_run(nested=True):
            mlflow.log_param("index", i)
            if i == 3:
                mlflow.end_run("FAILED")
```

![image](https://github.com/user-attachments/assets/aa0d0dce-60a7-4671-93e6-4e38b9a4761e)

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow

mlflow.set_experiment("nested_run_debugging")
with mlflow.start_run():
    for i in range(10):
        with mlflow.start_run(nested=True):
            mlflow.log_param("index", i)
            if i == 3:
                mlflow.end_run("FAILED")
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
no.

`with mlflow.start_run(nested=True):`

means when the code exit the `with` block, the started run is ended.


if you use `mlflow.start_run(...)` without `with`, then it will not be ended.

**Comment by WeichenXu123** [comment]
oh , I got your point, 

in your case, it unexpectedly terminates the parent run at the step 3 in the loop, then it leads to all subsequential nested runs become top-level runs.

**Comment by WeichenXu123** [comment]
I will file a fix later.

**Comment by WeichenXu123** [comment]
PR is out : @casellimarco please test it by:

```
pip install git+https://github.com/WeichenXu123/mlflow.git@fix-end-run
```

**Comment by casellimarco** [comment]
> PR is out : @casellimarco please test it by:
> 
> ```
> pip install git+https://github.com/WeichenXu123/mlflow.git@fix-end-run
> ```

It worked like a charm, thanks a lot!
