### ISSUE TITLE
[BUG] Pandas Dataset gets really slow when using a strings column in mlflow.log_input

### ISSUE THREAD

**Issue by uliseshdzc** [mlflow/mlflow#13872]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.18.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.11.4
- **yarn version, if running the dev UI**: N/A

### Describe the problem

**Description:**
When using a pandas dataframe and one of the columns is composed by strings, the client crashes when a dataset created out of it is passed to the method `mlflow.log_input`.

**Expected behavior:**
The client should infer that is a string type faster.

**Actual behaviour:**
The client gets slow.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
import time
import pandas as pd
import mlflow
import numpy as np

# Generate data
SIZE = 70000
data = {
    'Strings': [f'String {i}' for i in range(1, SIZE + 1)],
    'Numbers1': np.random.randint(1, SIZE, size=SIZE),
    'Numbers2': np.random.rand(SIZE) * SIZE
}

# Create DataFrame
df = pd.DataFrame(data)

# Log input into MLflow
with mlflow.start_run():
    start = time.time()
    dataset=mlflow.data.from_pandas(df)
    mlflow.log_input(dataset=dataset)
    end = time.time()

    print(f"Time elapsed: {end - start}")
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Time elapsed: 220.82042694091797 seconds
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
in my test your code can run but it takes some time executing this function:
https://github.com/mlflow/mlflow/blob/fbe4569885fb3f18588a9f5ff369431cdd00f68e/mlflow/types/utils.py#L223

the `_infer_schema` function is not optimized well in your case.

**Comment by WeichenXu123** [comment]
Attached the flamegraph:

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/759b2c20-7f7f-4488-bc8c-276f6175ee40">

@serena-ruan Can we optimize the `_infer_datatype` part ? 


Full profiling code:
```
import time
import pandas as pd
import mlflow
import numpy as np

# Generate data
SIZE = 70000
data = {
    'Strings': [f'String {i}' for i in range(1, SIZE + 1)],
    'Numbers1': np.random.randint(1, SIZE, size=SIZE),
    'Numbers2': np.random.rand(SIZE) * SIZE
}

# Create DataFrame
df = pd.DataFrame(data)

import cProfile

# Log input into MLflow
with mlflow.start_run(), cProfile.Profile() as pr:
    dataset=mlflow.data.from_pandas(df)
    mlflow.log_input(dataset=dataset)
    pr.dump_stats("/tmp/profile.out")
```
Generating flamegraph command: (install `pip install flameprof` first)
```
cd /tmp; flameprof profile.out > profile.svg
```

**Comment by serena-ruan** [comment]
I think we can improve _infer_scalar_datatype, I can test it tomorrow :)

**Comment by WeichenXu123** [comment]
@uliseshdzc could you test against latest mlflow master ?

```
pip install git+https://github.com/mlflow/mlflow.git
```

**Comment by uliseshdzc** [comment]
Yes, now it works like a charm, thanks!
