### ISSUE TITLE
Typo fix: `model.complete` -> `model.compile`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#13909]
### Summary

A minor issue introduced in https://github.com/mlflow/mlflow/pull/13868.

```diff
diff --git a/mlflow/tensorflow/callback.py b/mlflow/tensorflow/callback.py
index f9d6d0da3..4d187409f 100644
--- a/mlflow/tensorflow/callback.py
+++ b/mlflow/tensorflow/callback.py
@@ -207,7 +207,7 @@ class MlflowModelCheckpointCallback(Callback, MlflowModelCheckpointCallbackBase)
 
     def on_train_batch_end(self, batch, logs=None):
         # Note that `on_train_batch_end` might be invoked by every N train steps,
-        # (controlled by `steps_per_execution` argument in `model.complete` method).
+        # (controlled by `steps_per_execution` argument in `model.compile` method).
         # the following logic is similar to
         # https://github.com/keras-team/keras/blob/e6e62405fa1b4444102601636d871610d91e5783/keras/callbacks/model_checkpoint.py#L212
         add_batches = batch + 1 if batch <= self._last_batch_seen else batch - self._last_batch_seen
```
                                                                                                        

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by Ajay-Satish-01** [comment]
Hey,
I am new to open source and would love to contribute to this. 

I would like to know a bit more about the issue and how I can test it. 

Is it just renaming it from "complete" to "compile" and raising a PR?

**Comment by abhishekpawar1060** [comment]
Should I work on this issue ?

**Comment by harupy** [comment]
@abhishekpawar1060 Sorry, @Ajay-Satish-01 was a bit faster.

**Comment by Ajay-Satish-01** [comment]
@harupy please check if the PR is according to your expectations.
