### ISSUE TITLE
[FR] MLflow Tracing for Groq

### ISSUE THREAD

**Issue by B-Step62** [mlflow/mlflow#13911]
### Summary

Expand [auto-tracing integration](https://mlflow.org/docs/latest/llms/tracing/index.html#automatic-tracing) of MLflow Tracing to [Grop](https://groq.com/) SDK. MLflow already supports auto-tracing for OpenAI SDK, so this work will look similar to that.

### Required Changes
Please refer to [how to add new integration to MLflow Tracing](https://mlflow.org/docs/latest/llms/tracing/contribute.html) for the actual steps of adding new auto-tracing integration. MLflow maintainers will provide attentive support for designing and implementing the change.

### Expected Behavior

1. Users can enable auto-tracing by calling `mlflow.groq.autolog()`
```python
import mlflow
from groq import Groq

mlflow.groq.autolog()

client = Groq(api_key=os.environ["GROQ_API_KEY"])
message = client.chat.completons.create(
    model="mistral-small-latest",
    messages=[
        {"role": "user", "content":  "Explain the importance of low latency LLMs",}
    ]
)
```
2. This will generates a trace like this (taken from OpenAI example):
![image](https://github.com/user-attachments/assets/54188ec0-c061-4e3e-8397-3d886b2c3e07)

### Contact

If you have any question or willing to work on this feature, leave a comment with tagging @B-Step62

**Comment by anumita0203** [comment]
Hi @B-Step62, I can work on this FR. I've drafted the design document for it. Could you please review it and let me know if it's good to proceed?
[OSS Project Design Template Groq Autologging.docx](https://github.com/user-attachments/files/18009646/OSS.Project.Design.Template.Groq.Autologging.docx)

**Comment by B-Step62** [comment]
Thank you so much @anumita0203 for drafting the design doc! Patching approach makes 100% sense, please go ahead to implement it and file a PR. Please feel free to ping me whenever you have a question or an issue🙂

**Comment by anumita0203** [comment]
I've raised a PR for this issue - [#14006](https://github.com/mlflow/mlflow/pull/14006)

**Comment by B-Step62** [comment]
@anumita0203 Thank you for the PR!

Tracing documentation is defined at `docs/source/llm/tracing.index.rst`. You can follow the steps in [CONTRIBUTION.md`](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md#writing-docs) to set up doc preview environment. Also please refer to https://github.com/mlflow/mlflow/pull/13851 for the actual contents to update🙂

**Comment by anumita0203** [comment]
I added documentation for Groq, and the CI tests are passing now. @B-Step62 can you please take a look? I addressed all your comments in my PR.

**Comment by anumita0203** [comment]
Hi @B-Step62, thanks for your detailed comments on my PR! I've addressed all the issues you mentioned.

**Comment by B-Step62** [comment]
@anumita0203 Merged the PR! It is going to be released in mid January. Thank you so much for the huge addition and we are looking forward to see your contribution again!!😄

**Comment by anumita0203** [comment]
Thank you so much @B-Step62! Really appreciate your guidance in implementing this feature.
