### ISSUE TITLE
[FR] support to the Open Inference Protocol

### ISSUE THREAD

**Issue by chriss1245** [mlflow/mlflow#13935]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

A lot of ml servers are addopting the Open Inference Protocol. The Open Inference Protocol (OIP) is a standardized protocol designed to facilitate machine learning (ML) model inference across various serving runtimes and ML frameworks. It supports Rest and gRPC.

### Motivation

> #### What is the use case for this feature?
The use case is enabling MLflow to support the Open Inference Protocol (OIP) for standardized model inference. This would allow MLflow users to seamlessly deploy and interact with models served on multiple platforms (e.g., KServe, NVIDIA Triton, Seldon Core) using a unified API for inference, health checks, and metadata retrieval.
thens its role as a central hub for ML lifecycle management, integrating seamlessly with modern serving solutions.

> #### Why is this use case valuable to support for MLflow users in general?
* Simplify Deployment: MLflow users could deploy models to any OIP-compliant serving platform without needing custom integration for each platform.
* Enhance Flexibility: MLflow projects could leverage a variety of serving runtimes while maintaining a consistent interface for inference requests.
* Improve Ecosystem Compatibility: By aligning with OIP, MLflow strength.

> #### Why is this use case valuable to support for your project(s) or organization?
* Unify Serving Workflows: We use multiple serving solutions, and supporting OIP in MLflow would standardize how we handle inference across all platforms.
* Reduce Integration Costs: Currently, we spend significant resources creating custom wrappers or APIs for each serving solution. OIP would eliminate this overhead.
* Future-Proof Our Workflow: Supporting OIP ensures that MLflow deployments can evolve with the rapidly changing ML serving ecosystem without requiring additional development effort.

> #### Why is it currently difficult to achieve this use case?
* Missing data types: It is difficult to work with torch types of float16, float8. 
* Inconsistent APIs: Every serving platform MLflow integrates with (or is used alongside) has unique APIs, requiring custom logic for model deployment and inference.
* High Maintenance Overhead: Custom integrations must be updated as serving runtimes evolve, which can lead to compatibility issues and maintenance costs.
* Limited Portability: Models deployed via MLflow are often tied to specific serving platforms, limiting our ability to migrate them across environments.

### Details

[Open Inference Protocol](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/v2-protocol.html)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@chriss1245 Thank you for the proposal. We already support Open Inference Protocol via [Seldone ML Server](https://mlflow.org/docs/latest/deployment/deploy-model-locally.html#serving-frameworks) deployment option. We don't consider changing the default protocol as it will be critical breaking change for existing users. Updating client side logic will be a huge effort and we don't see strong practical benefits for enforcing that.
