### ISSUE TITLE
[BUG] log model using models from code langgraph not able to infer signature

### ISSUE THREAD

**Issue by matteociccozzi-ah** [mlflow/mlflow#13963]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 2.18.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 14.7
- **Python version**: 3.11.9

### Describe the problem

Trying to use models from code to log a langgraph model as described here: https://mlflow.org/docs/latest/llms/langchain/index.html#how-can-i-log-an-agent-built-with-langgraph-to-mlflow

I define in a .py file my agent and then run `mlflow.models.set_model(graph)`. 

In a separate jupyter notebook I then run:

```
with mlflow.start_run():
    logged_model = mlflow.langchain.log_model(
        lc_model=graph_path,
        artifact_path="langgraph",
        input_example=input_example
    )
    
    print(logged_model.model_uri)
```

But this won't work for my case as I cannot pass a configurable that is needed to work with the checkpointer, so I get the following error:
```
2024/12/03 09:05:44 WARNING mlflow.utils.requirements_utils: Failed to run predict on input_example, dependencies introduced in predict are not captured.
MlflowException('1 tasks failed. Errors: {0: \'error: ValueError("Checkpointer requires one or more of the following \\\'configurable\\\' keys: [\\\'thread_id\\\', \\\'checkpoint_ns\\\', \\\'checkpoint_id\\\']")
```

To bypass this, I tried using a model signature instead of the input example. I provided the signature as follows:

```
input_example = {"messages": [{"role": "user", "content": "Hi, can you help me?"}]}
output_example = graph.invoke(input=input_example, config=...)
signature = infer_signature(input_example, output_example)
```
but this also fails with:
```
MlflowException: Data content='Hi, can you help me?' additional_kwargs={} response_metadata={} id='53f08b92-94a3-43f3-a90a-327bc5ef383e' is not one of the supported DataType
```

For completeness sake, I also tried copy pasting the agent code in the mlflow doc (the one that uses `graph = create_react_agent(llm, tools)`) and replaced that script and I still get the same error when trying to infer the signature.

The issue here is that as is I cannot see how to use the models from code to log the model, then subsequently register it etc if I cannot use checkpointers which are essential to our application. The root issue is that I should be able to use the infer signature instead of the input_example but that fails.

### Code to reproduce issue

agent script: 

```
from typing import Literal

from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent

import mlflow

@tool
def get_weather(city: Literal["seattle", "sf"]):
    """Use this to get weather information."""
    if city == "seattle":
        return "It's probably raining. Again."
    elif city == "sf":
        return "It's always sunny in sf"


llm = ChatOpenAI()
tools = [get_weather]
graph = create_react_agent(llm, tools)

mlflow.models.set_model(graph)

```

jupyter notebook:

```
from <python script import the graph>
from mlflow.models import infer_signature
import mlflow

input_example = {"messages": [{"role": "user", "content": "Hi"}]}
output_example = graph.invoke(input=input_example)


signature = infer_signature(input_example, output_example)
```

### Stack trace

```
---------------------------------------------------------------------------
MlflowException                           Traceback (most recent call last)
Cell In[7], line 11
      8 print(output_example)
     10 # Infer the signature
---> 11 signature = infer_signature(input_example, output_example)

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/models/signature.py:240, in infer_signature(model_input, model_output, params)
    235     inputs = None
    236 if model_output is not None:
    237     outputs = (
    238         convert_dataclass_to_schema(model_output)
    239         if is_dataclass(model_output)
--> 240         else _infer_schema(model_output)
    241     )
    242 else:
    243     outputs = None

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/types/utils.py:317, in _infer_schema(data)
    314         if any(not isinstance(key, str) for key in data):
    315             raise MlflowException("The dictionary keys are not all strings.")
    316         schema = Schema(
--> 317             [
    318                 ColSpec(
    319                     _infer_colspec_type(value),
    320                     name=name,
    321                     required=_infer_required(value),
    322                 )
    323                 for name, value in data.items()
    324             ]
    325         )
    326 # pandas.Series
    327 elif isinstance(data, pd.Series):

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/types/utils.py:319, in <listcomp>(.0)
    314         if any(not isinstance(key, str) for key in data):
    315             raise MlflowException("The dictionary keys are not all strings.")
    316         schema = Schema(
    317             [
    318                 ColSpec(
--> 319                     _infer_colspec_type(value),
    320                     name=name,
    321                     required=_infer_required(value),
    322                 )
    323                 for name, value in data.items()
    324             ]
    325         )
    326 # pandas.Series
    327 elif isinstance(data, pd.Series):

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/types/utils.py:99, in _infer_colspec_type(data)
     89 def _infer_colspec_type(data: Any) -> Union[DataType, Array, Object]:
     90     """
     91     Infer an MLflow Colspec type from the dataset.
     92 
   (...)
     97         Object
     98     """
---> 99     dtype = _infer_datatype(data)
    101     # Currently only input that gives None is nested list whose items are all empty e.g. [[], []],
    102     # because flat empty list [] has special handlign logic in _infer_schema
    103     if dtype is None:

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/types/utils.py:122, in _infer_datatype(data)
    119     return Object(properties=properties)
    121 if isinstance(data, (list, np.ndarray)):
--> 122     return _infer_array_datatype(data)
    124 return _infer_scalar_datatype(data)

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/types/utils.py:151, in _infer_array_datatype(data)
    148 if _is_none_or_nan(item):
    149     continue
--> 151 dtype = _infer_datatype(item)
    153 # Skip item with undetermined type
    154 if dtype is None:

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/types/utils.py:124, in _infer_datatype(data)
    121 if isinstance(data, (list, np.ndarray)):
    122     return _infer_array_datatype(data)
--> 124 return _infer_scalar_datatype(data)

File ~/Library/Caches/pypoetry/virtualenvs/mutli-agent-chatbot-YdyyLTyT-py3.11/lib/python3.11/site-packages/mlflow/types/utils.py:199, in _infer_scalar_datatype(data)
    197 if DataType.is_datetime(data):
    198     return DataType.datetime
--> 199 raise MlflowException.invalid_parameter_value(
    200     f"Data {data} is not one of the supported DataType"
    201 )

MlflowException: Data content='Hi' additional_kwargs={} response_metadata={} id='b3c27764-b96f-47d1-97bb-45a8da4d917d' is not one of the supported DataType
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@matteociccozzi-ah Thank you for reporting the issue!

The `infer_signature` issue is fixed by https://github.com/mlflow/mlflow/pull/13968 and we will be releasing a RC version (2.19.0rc0) today, including this fix.

We are also working on a general fix for signature inference on LangGraph models with checkpoint, targeting the first release in 2025. By that time, you should be able to pass the `configurable` dictionary to additional parameter of input example and the signature is automatically inferred from it🙂
