### ISSUE TITLE
Remove `flaml` pin

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#13999]
### Summary

https://github.com/microsoft/FLAML/issues/1353 has been fixed. We can remove the pin.

```diff
diff --git a/requirements/test-requirements.txt b/requirements/test-requirements.txt
index cfbb9a3f7..0d411a94a 100644
--- a/requirements/test-requirements.txt
+++ b/requirements/test-requirements.txt
@@ -19,8 +19,7 @@ hyperopt
 # Required by recipes tests
 ipython
 # Required by automl tests
-# TODO: Remove pin once https://github.com/microsoft/FLAML/issues/1353 is resolved
-flaml[automl]!=2.3.0
+flaml[automl]
 # Required by evaluator tests
 shap
 # Required to evaluate language models in `mlflow.evaluate`
```

https://github.com/mlflow/mlflow/blob/fdf4913c7d4011f3d678bfd4fed264d230a18819/requirements/test-requirements.txt#L22-L23

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by Ajay-Satish-01** [comment]
Hey, I can work on this.

**Comment by harupy** [comment]
@Ajay-Satish-01 Thanks!

**Comment by harupy** [comment]
@Ajay-Satish-01 Assigned!

**Comment by Ajay-Satish-01** [comment]
@harupy please check and let me know if there are any issues. Thanks.
