### ISSUE TITLE
Support db-backend for the artifact store

### ISSUE THREAD

**Issue by avflor** [mlflow/mlflow#1399]
This feature would allow users that perform ML tasks in the database (e.g., scoring on DB data) to have direct access to the artifacts from within the DB. The models could be stored as blobs in the DB.

**Comment by mateiz** [comment]
Shouldn't this already be supported through SQLAlchemy? I believe you can put in any SQLAlchemy database URI there.. we just didn't list all the available ones.

**Comment by avflor** [comment]
@mateiz Thanks for the clarification. I think I confused the notions of backend store and artifact store. 

The feature I would like to see is storing/logging ML models in SQL Server and not just the experiment-related data.  This is important for our use cases where the users perform scoring using SQL Server data directly in SQL Server. In many such cases, the models are already stored in SQL Server as Blobs. 

Would it make sense to add a generic db-store interface (a la SQLAlchemy) for the artifact store as well? 

I will update the issue description to better reflect this discussion.

**Comment by finelycheng** [comment]
when i started the server by this way   mlflow server --backend-store-uri  mysql://root:123456@127.0.0.1/mlflow  --default-artifact-root   mysql://root:123456@127.0.0.1/mlflow   -p 5200 -h 0.0.0.0  then i can not find how to save my parameter and runs into DB
