### ISSUE TITLE
when i rename model registry , after update i lost access to the model registry with permission denied 

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [mlflow/mlflow#14094]
1) first i create model registry 
2) then i update model registry name
3) when i do search on model registry i no longer have access to the model registry 

![image](https://github.com/user-attachments/assets/71056945-736f-4ebc-9d44-1ead67f8e118)

![image](https://github.com/user-attachments/assets/bbb6e53a-f0f9-488c-a4ef-455b4b16600f)

am using mlflow 2.14.0

**Comment by MohamedKHALILRouissi** [comment]
after investigating the database i found that when rename model registry entry in registered_model_permissions is not updated the old model registry name is kept is this existing issue should i upgrade ?

**Comment by serena-ruan** [comment]
> after investigating the database i found that when rename model registry entry in registered_model_permissions is not updated the old model registry name is kept is this existing issue should i upgrade ?

Could you elaborate your question? I don't follow. You can also try upgrading MLflow

**Comment by MohamedKHALILRouissi** [comment]
i have issue where updating the model registry name , it doesnt update the model registry permission , once i do update name i lose access to that registry from the user who created and updated the name

**Comment by MohamedKHALILRouissi** [comment]
still testing to give final result but 
1) if you update experiment name using ( experiment id and name in the json ) you dont lose permission because table experiments_permission use the experiment_id to reference the link between experiments and experiment_permission 
2) if you update model registry name using ( name and new name ) , you lose permission because table model registry use the previous name a link to registered_model_permissions , so when you update name it doesnt propagate to update the  registered_model_permissions
this happen at 2.14.0

am checking latest now to try and reproduce the issue

**Comment by serena-ruan** [comment]
Got it. cc @gabrielfu for awareness :)

**Comment by MohamedKHALILRouissi** [comment]
it can be reproduced at 2.19.0

**Comment by MohamedKHALILRouissi** [comment]
workflow 
---------------------------- config init for auth (1)--------------------------------------------------------------
[mlflow]
default_permission = "NO_PERMISSIONS"
database_uri = postgresql://user:password@db:5432/authdb
admin_username = admin
admin_password = password
authorization_function = mlflow.server.auth:authenticate_request_basic_auth
---------------------------------------------------------------------------------------------------------------------
i have a separate database for tracking mlflow 
basically use this in the docker compose 
      MLFLOW_BACKEND_STORE_URI: "postgresql://user:password@db:5432/mlflowdb" # for tracking 
      MLFLOW_ADMIN_USERNAME: admin
      MLFLOW_ADMIN_PASSWORD: password
      MLFLOW_AUTH_CONFIG_PATH: "/tmp/app/basic_auth.ini"           # for auth contain config init for auth  (1)
      
      
1)create a new user using the mlflow client or api 
2) sign in as the user ui or basic auth api    
3) create model registry with name "test-1" 
4) use the api ( there no ui for rename ) and rename the model registry to "test-2" 
5) user lose access to the test-2 model registry 

because the model registry doesn't update 
can i take this if reproducible for your end i will fix it 
      
![image](https://github.com/user-attachments/assets/8c5aa109-474a-4b7f-99d0-9ebf3081323d)

**Comment by MohamedKHALILRouissi** [comment]
i will push fix for this 
- if user rename the model registry am going also to update the store.update_model_registry_permission() to propagate the changes , this will be a separate function as there's no  direct foreign key relationship across different databases authdb and trackingdb

**Comment by MohamedKHALILRouissi** [comment]
#14113
