### ISSUE TITLE
[Feature request] Deploy models as aws lambda functions

### ISSUE THREAD

**Issue by ahmed-shariff** [mlflow/mlflow#1415]
I have some of my models deployed as lambda functions in AWS. In my pipeline I export my models to onnx, upload them to s3 and have the production lambda function point to the uploaded model.

**Comment by iqDF** [comment]
Hi @ahmed-shariff have you figured out a way around this? I know Sagemaker can do but I want it from MLFlow, Pytorch serving or TFserving if possible. 

I would like to have the following features:

1. Ability to seperate AI model deployment and API deployment, such that both AI modelling and API deployment can be decoupled. Say Data Science team do their own research, Backedn/Devops focus on app.
2. Ability to deploy and update AI model with another model by simply rolling in new TF/Pytorch code (model), artifacts (pretrained checkpoints), and other file/weight artifacts from notebooks. Train once and able to deploy them as AWS Lambda without downtime. Then the AWS Lambda can already server new model without bugging the developer team.

**Comment by ahmed-shariff** [comment]
I had moved on from that project, and I haven't done much in terms of deployment recently, so what I had done might be a little outdated. I mean that was pre-pytroch serving and all. It is just as I describe in the OP. My lambda function looked something like this:

```python
import json
import boto3
import os
from utils import process_scene, ModelSession

bucket_name = os.environ['BUCKET_NAME']
onnx_file_location = os.environ['ONNX_FILE'] 
synset_file_location = os.environ['SYNSET_FILE'] 
s3 = boto3.resource('s3')
onnx_file = s3.Object(bucket_name, onnx_file_location).download_file('/tmp/model.onnx')

model_session = ModelSession("/tmp/model.onnx")

def lambda_handler(event, context):
    images = json.loads(event['body'])['images']
    output = process_scene(images, model_session)
    return {
        'statusCode': 200,
        'body': json.dumps(output)
    }
```

The way I had set up the pipeline, the models get pushed from the data science end of things to s3. So the next time a lambda function is spun up, it'll use the new model. The models also return a version ID which I was using to track performance of the models. The lambda function was not directly exposed to the client, it was used by a beanstalk server to process images: it processes client requests and the model results; and the performance tracking was all set up in there.
