### ISSUE TITLE
MLFlow - run tasks in Parallel

### ISSUE THREAD

**Issue by radu-nedelcu-de** [mlflow/mlflow#1420]
Hi guys,

We are considering using ML Flow to define our ML Pipeline for a new project. However, I cannot find any information if ML Flow can automatically parallelise tasks that don't have inter-dependencies - i.e. training multiple models at the same time through our Databricks cluster?

Thanks!

Kind regards,
Radu

**Comment by aarondav** [comment]
MLflow's notion of dependencies right now is manual (see the [multistep example](https://github.com/mlflow/mlflow/blob/master/examples/multistep_workflow/main.py)), which means you can parallelize using python's multithreading/multiprocessing libraries.
