### ISSUE TITLE
Package MLeap model to Docker

### ISSUE THREAD

**Issue by phillyfan1138** [mlflow/mlflow#1429]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX
- **MLflow installed from (source or binary)**:  Binary (pip3 install mlflow)
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.7.3
- **npm version (if running the dev UI): N/A
- **Exact command to reproduce**: mlflow models build-docker -m mleapmodel

### Describe the problem
When I try to package an MLeap model created from 
```python
mleap.save_model(
  spark_model=fittedModel, path="mleapmodel", 
  sample_input=df
)
``` 

I get the exception "No suitable flavor backend was found for the model."  The packaging of MLeap models into docker images would be incredibly convenient.  Currently I use scala code to wrap a serialized MLeap model and deploy as a web service, but this requires custom coding and packaging.  

Edit:

This part of the source code seems promising in terms of packaging into a docker image:

https://github.com/mlflow/mlflow/tree/master/mlflow/java/scoring

However, I see very little documentation about this feature.

**Comment by phillyfan1138** [comment]
After looking through the code some more...it seems like MLeap should be supported already.  It is one of the supported flavors in https://github.com/mlflow/mlflow/blob/619d18f1f981b9b82d57d93bdf04356e7e6e389f/mlflow/models/container/__init__.py#L33.  However, when actually calling the CLI in https://github.com/mlflow/mlflow/blob/619d18f1f981b9b82d57d93bdf04356e7e6e389f/mlflow/models/cli.py#L122, it only has py_func as a supported flavor from https://github.com/mlflow/mlflow/blob/619d18f1f981b9b82d57d93bdf04356e7e6e389f/mlflow/models/flavor_backend_registry.py#L14.

**Comment by andychow-db** [comment]
I believe MLflow has support for MLeap right now. See docs [here](https://www.mlflow.org/docs/latest/python_api/mlflow.mleap.html).
