### ISSUE TITLE
Feature request: Make MLflow UI table sortable

### ISSUE THREAD

**Issue by emres** [mlflow/mlflow#143]
It'll be great if the user can click on a column name, e.g. `Date`, `rmse` or `mae`, and sort the results ascending / descending based on that column.

**Comment by mateiz** [comment]
Makes sense! This is hopefully something we'll prioritize soon.

**Comment by ToonKBC** [comment]
Commit 12a65cb4ec2be90fb59d98fe9295242c2eb342b9 implements this. This issue can be closed.

**Comment by ividal** [comment]
> Commit [12a65cb](https://github.com/mlflow/mlflow/commit/12a65cb4ec2be90fb59d98fe9295242c2eb342b9) implements this. This issue can be closed.

Thanks for this!

@ToonKBC Is there documentation somewhere as to how to use this? I just started using mlflow (1.3.0) and ran [the wine example](https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine), filtered by individual metrics (RMSE, etc.) but couldn't see them sortable. 

Does it have to be activated in the code somehow?
