### ISSUE TITLE
cannot explore experiment runs [AWS EB, S3]

### ISSUE THREAD

**Issue by rami3e** [mlflow/mlflow#1435]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**: 
```
    CMD mlflow server \
    --backend-store-uri /mlflow/myruns \
    --default-artifact-root s3://${BUCKET}/mlflow-artifacts \
    --host 0.0.0.0
```
### Describe the problem
I am deploying mlflow to an AWS EB server. Artifacts are stored in s3. Everything seems to be working in the sense that I can load up the mlflow start page, see the different experiments and they get populated with respective metadata. However, when I click on a run to view (i.e. to look at the metrics or artifacts) it crashes and i get the Oops Niagra Falls page. Going into the deployed docker image, all files are present and metadata is being populated and updated. 

```
Failed to load resource: http://1234.elasticbeanstalk.com/ajax-api/2.0/preview/mlflow/artifacts/list?run_uuid=1234 the server responded with a status of 500 (INTERNAL SERVER ERROR)
```

**Comment by jeremypleb** [comment]
I am running into the same issue on python 3.6, mlflow 1.0.0, macOS Sierra. I can log data, artifacts etc., but clicking on an individual run causes an error. 

The network tab shows that the request to 
`<remote-url>/ajax-api/2.0/preview/mlflow/artifacts/list?run_uuid=<run-id>` 
returns a 500 internal server error

**Comment by gauthiermartin** [comment]
I'm running into the same issue here here is the stack trace of the js console if it can help
[Error](https://i.imgur.com/xb4l6W9.png)

**Comment by gauthiermartin** [comment]
@rami3e and @jeremypleb Did you try checking mlflow logs...it might be a missing dependency like boto3 library

**Comment by rami3e** [comment]
where are these logs? i cannot find them

**Comment by rami3e** [comment]
looks like my specific issue is related to aws permissions. i have created an iam role thought this was working no problem. ill update in case anyone else runs into this

**Comment by jeremypleb** [comment]
> @rami3e and @jeremypleb Did you try checking mlflow logs...it might be a missing dependency like boto3 library

By installing `mlflow[extras]` I was able to resolve the error. However, in the case that the artifacts cannot be retrieved, I think it would be better to still load the rest of the UI and simply state that the artifacts cannot be retrieved. This would be more helpful than crashing the whole UI with no apparent reason as to why.
