### ISSUE TITLE
How to update mllfow version to 1.0.0 and reserve the experiments

### ISSUE THREAD

**Issue by Guoyoyo** [mlflow/mlflow#1449]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:14.04.5
- **MLflow installed from (source or binary)**: docker-compose.yml 
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Mlflow just released the latest version 1.0.0 few days ago.  How can i update the docker container from 0.9.1 to 1.0.0 and keep all my original experiments simultaneously??

I tried to fix the image version in the docker-compose.yml  (mlflow:1.0.0)  and restart the docker container. After that, the mlflow server is work. All the experiments display in the left too. However, when i click to the experiments records, the error happened ! So, after i tried to change to the original version 0.9.1 and restart again, it restoring normal operations.

### Source code / logs
The docker-compose.yml 
services:
  mlflow:
    image: mlflow:1.0.0
    container_name: mlflow
    ports:
      - 8888:5000
    volumes:
      - /data:/data
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://<IP>
      - AWS_ACCESS_KEY_ID=XXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXX
    command: >
      mlflow server --backend-store-uri /data --default-artifact-root s3://<bucket_name>/ --host 0.0.0.0

It shows the error message:  "Oops! Something went wrong. If this error persists, please report an issue on our GitHub page." (A waterfall landscape...)

**Comment by smurching** [comment]
Thanks for reporting this @Guoyoyo, we do expect migration from MLflow 0.9.1 to 1.0.0 to work when using file-backed storage (.eg. `/data` in your case).

Would you be able to share the JS stacktrace? You can find the stacktrace by opening the developer console (e.g. as described in https://developers.google.com/web/tools/chrome-devtools/open, basically right-click -> click inspect -> open the "console" tab).

**Comment by Guoyoyo** [comment]
@smurching  Like this ???

![2019-06-14_133044](https://user-images.githubusercontent.com/17918702/59485531-be4edc80-8ea8-11e9-8294-c71d835eec96.png)

**Comment by cappaberra** [comment]
I'm using file-backend storage with MLflow 0.6.0 and want to upgrade to MLflow v1.2.0 (latest as of this writing).... if I should write up another issue, I can, but this seemed relevant.  Performing the following does not work as expected, and I didn't find any documentation on the process.

`mlflow db upgrade file:///data_1.2.0/
Traceback (most recent call last):
  File "/var/opt/mlflow/venv_1.2.0/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/mlflow/db.py", line 22, in upgrade
    if mlflow.store.db.utils._is_initialized_before_mlflow_1(url):
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/mlflow/store/db/utils.py", line 69, in _is_initialized_before_mlflow_1
    engine = sqlalchemy.create_engine(url)
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 450, in create_engine
    return strategy.create(*args, **kwargs)
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/var/opt/mlflow/venv_1.2.0/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 240, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:file`

**Comment by cappaberra** [comment]
Anyone?

**Comment by weldpua2008** [comment]
Guys @Guoyoyo , @smurching, @cappaberra 
I wonder if someone successfully migrated from pre-1.0.0 to 1.x?

We have 0.8.1 and no DB. As I understand - we can migrate in such way:
1. MLFlow 0.8.1 -> 0.8.2 -> 0.9.0 -> 1.0.0
2. Then we should switch file-backend  -> db-backend
3. Re-import everything in DB (I found only this script https://gist.github.com/bnekolny/8ec96faa0d57913eea6bb7848c06b912)
Am I right?

**Comment by Guoyoyo** [comment]
Hi, sorry can not help you.
I finally remove all experiments and recreate a new service with nwer
version 1.7.2 now.

Best,
Guoyoyo

Valera <notifications@github.com> 於 2020年5月12日 週二 上午12:04寫道：

**Comment by weldpua2008** [comment]
@Guoyoyo thank you for your reply
I'd recently started the migration 0.8.1 -> 1.8.0 and wrote the following script based on another script ;) https://gist.github.com/weldpua2008/7f0c4644d247bd0fc7ba9a83c2d337d5
