### ISSUE TITLE
Feature request: Pass DB connection parameters to SQLAlchemy

### ISSUE THREAD

**Issue by julilien** [mlflow/mlflow#1452]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6.7
- **npm version (if running the dev UI): -
- **Exact command to reproduce**: -

### Describe the problem
Currently, the default pool size used by SQLAlchemy is set to 5 which is an appropriate number of connections for only a few runs. However, when performing large scale experiments with hundreds or thousands of jobs in parallel, this is a problem due to blocked connections by the database servers when exceeding the maximum number of connections. I could not find a way to parameterize mlflow to overcome this issue, e.g. by decreasing the used connection pool size. Adding these parameters as key-value-pair at the end of the database URL didn't work either.

This is only one parameter which could be useful to be able to parameterize. [Here](https://docs.sqlalchemy.org/en/13/core/engines.html#engine-creation-api) is a detailed list of further possible parameters.

### Source code / logs
In `SQLAlchemyStore`, the engine is created without using the opportunity to pass arguments like `pool_size` (cf. line 72 in the 1.0.0 binary release):
```self.engine = sqlalchemy.create_engine(db_uri)```

Wouldn't it be great to let mlflow configure how your database connections should behave in detail?

**Comment by julilien** [comment]
Addition:
For MySQL, the keywords described [here](http://mysql-python.sourceforge.net/MySQLdb.html#id7) are currently supported as key-value-pairs in the MySQLdb implementation.

**Comment by smurching** [comment]
@julilien thanks for raising this - would be happy to review a PR that contributes this if you're interested :)

It'd be helpful to first quickly sketch out exactly how we'd allow specifying connection parameters would work - maybe via e.g. an extra `--db-opts` argument to `mlflow server`?

**Comment by julilien** [comment]
I'd say that `--db-opts` should be the way to go since the connection string itself is processed by the DB engine, such as MySQLdb. By using `--db-opts`, you'd have a clear distinction between parameterizing SQLAlchemy in general and specifically configuring the database's driver engine (e.g. by MySQLdb specific configuration parameters).
@smurching Let me know if you share this opinion. Then I would start working on it. :)

**Comment by smurching** [comment]
Hi @julilien, yep the `--db-opts` approach seems reasonable to me :)

**Comment by smurching** [comment]
Also out of curiosity, what's the use case in which you're running hundreds or thousands of jobs in parallel (hyperparam tuning)? Mainly wondering if there's anything else MLflow can do to better support that use case.

**Comment by julilien** [comment]
Hi @smurching, thanks for your interest. My use case for running that many jobs is to perform experiments for some models on a large set of reference datasets with different seeds. The huge number of jobs is performed to achieve statistical significance in the evaluation. In each job, a hyperparameter optimization is performed. Due to a high runtime of the experiments, a subsequent execution is not feasible.

I analyzed the number of connections opened by every run. Following the default parameterization of the SQLAlchemy engine, a pool size of 5 connections is created at startup. I got at least 10 connections (sometimes closing the connection of former runs takes some time) for each hyperparameter step (5 for the outer run, 5 for the current nested run). I've already increased the maximum number of connections allowed by the database but there are still too many.

I tried different things, incl. trying to reset the connection pool after the engine's creation, but, however, had no success. Is there a way to reuse connections opened by the outer runs using `mlflow.start_run()`?

**Comment by smurching** [comment]
Ah, it sounds like you might be using e.g. `mlflow.set_tracking_uri("mysql://...")` from within your hyperparameter tuning program? The current behavior of the MLflow fluent Python APIs is indeed to create a new `MlflowClient` (and therefore a new SQLAlchemy engine, if your tracking URI is set to a DB URI like `mysql://...`) on each call to `log_metric`, `start_run`, etc - we do this to allow for dynamically pulling credentials on each function call, e.g. when logging to a remote tracking server. However, if you run the tracking server we create & reuse a single SQLAlchemy engine. Thus one approach could be to run a tracking server with `mlflow server --backend-store-uri mysql://... --default-artifact-root <your-default-artifact-root>` and configure your hyperparam tuning program to log to the server via `mlflow.set_tracking_uri("http://your-server's-uri")`. 

I'd be curious to hear if this works for you, but happy to review a contribution making the SQLAlchemy settings configurable either way - thanks!

**Comment by julilien** [comment]
That sounds reasonable and solved my problem with a huge amount of jobs, thanks for that! :)

Nevertheless, I think it is helpful to configure the SQLAlchemy engine creation in many situations, e.g. for manually fixing the initial connection pool size. Therefore, I'll go for a contribution.

**Comment by adeandrade** [comment]
Hi @julilien,

Have you started working on this? I am having problems with MLFlow. Need to pass `pool_pre_ping=True` to the SQLAlchemy engine so expired connections are handled and connection failures are not transferred to the client. See: https://docs.sqlalchemy.org/en/13/core/pooling.html#pool-disconnects

Let me know if you need help.

**Comment by adeandrade** [comment]
I created a PR for this: https://github.com/mlflow/mlflow/pull/1635

**Comment by smurching** [comment]
Seems like this has since been resolved (see discussion in https://github.com/mlflow/mlflow/pull/1635), closing

**Comment by rockey5520** [comment]
@adeandrade 
 how were you able to user aurora and pass its connection details to mlflow ? it would be superhelpful if you could point me to a an example. I am on same boat
