### ISSUE TITLE
can not start ui

### ISSUE THREAD

**Issue by azarnyx** [mlflow/mlflow#1453]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Linux Ubuntu 16.04 fresh brand-new GCP instance with minconda
- **MLflow installed from (source or binary)**: 
installed from source: pip install git+https://github.com/mlflow/mlflow.git
though, server works just fine with last release: pip install mlflow
- **MLflow version (run ``mlflow --version``)**:
mlflow, version 1.0.0
- **Python version**: 
Python 3.7.3
- **npm version (if running the dev UI):
--
- **Exact command to reproduce**:
pip install git+https://github.com/mlflow/mlflow.git
mlflow server
wget -v http://127.0.0.1:5000

### Describe the problem
gunicorn (version 19.9.0), Python 3.7.3
Can not start server from the last version of repo. master branch, commit number 8c825d9

### Source code / logs
Error-log:

DEBUG output created by Wget 1.17.1 on linux-gnu.

Reading HSTS entries from /home/dima/.wget-hsts
URI encoding = 'ANSI_X3.4-1968'
converted 'http://127.0.0.1:5000' (ANSI_X3.4-1968) -> 'http://127.0.0.1:5000' (UTF-8)
--2019-06-14 10:36:58--  http://127.0.0.1:5000/
Connecting to 127.0.0.1:5000... connected.
Created socket 3.
Releasing 0x0000560bcdfa9ce0 (new refcount 0).
Deleting unused 0x0000560bcdfa9ce0.

---request begin---
GET / HTTP/1.1
User-Agent: Wget/1.17.1 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: 127.0.0.1:5000
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 404 NOT FOUND
Server: gunicorn/19.9.0
Date: Fri, 14 Jun 2019 10:36:58 GMT
Connection: close
Content-Type: text/html
Content-Length: 232

---response end---
404 NOT FOUND
Closed fd 3
2019-06-14 10:36:58 ERROR 404: NOT FOUND.

**Comment by azarnyx** [comment]
Basically, the issue is in the setuptools. For example, the folder server/js does not copy when install.

**Comment by smurching** [comment]
@azarnyx glad you found a resolution - you're correct that source builds of MLflow do not include the UI by default, as documented in https://github.com/mlflow/mlflow/blob/49c9b8423653738bebdc62d33b3e2f885ee2aa6a/README.rst#launching-the-tracking-ui

**Comment by azarnyx** [comment]
Yeah, I put js/build in the corresponding folder of installed package and it works. Somehow, I had problems in compilation of js part with npm. Do you have any plans to separate server with js part to distinct package? That might make development easier :)
