### ISSUE TITLE
C# API

### ISSUE THREAD

**Issue by geffzhang** [mlflow/mlflow#1457]
Microsoft releases open source ML.NET https://github.com/dotnet/machinelearning,  c# as machine learning language will get better, Is there someone started to implement the c# API?

**Comment by mateiz** [comment]
Nobody's started yet, but it would be interesting to hear a proposal if someone wants to do it. I'd start with a doc about how to do it, what's in scope, etc. It's also important that there be a good way for all developers to test it -- unlike Java, Python and R, C# may not easily be accessible outside of Windows dev environments.

**Comment by geffzhang** [comment]
C# can also be easy to run on mac, linux, because .NET Core is an open source cross-platform。This is the dotnet open source repository on github ：https://github.com/dotnet

**Comment by mateiz** [comment]
If that's enough to reliably run tests and do development, that's great.

**Comment by geffzhang** [comment]
Yes, .NET Core is stable enough, and excellent performance is his feature  https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharp.html

**Comment by Esther2013** [comment]
I'm sure [SciSharp](https://github.com/SciSharp) team could help, they're python/ C#/ ML enthusiasts.

**Comment by sueann** [comment]
As the demand for #C surges, this might be something we can consider later down the roadmap; but for now marking as low priority until we hear more. Thanks!

**Comment by Ellyster** [comment]
+1 to both the C# API, and builtin support of ML.NET as a model flavor.

I'm part of one of those enterprise software companies that use mostly C# and are now adding ML capabilities to their software. 

We have models in Scikit-learn, TensofFlow, XGBoost and ML.NET; but so far, we have found the later perform best (faster training times, smaller serializer models,...) with our production-size data, so we are prioritizing them in our internal platform.

**Comment by lqdev** [comment]
@lqdev tagging myself to track this conversation.

**Comment by jcf0419** [comment]
+1 from me
