### ISSUE TITLE
mlflow.tracking.artifact_utils._download_artifact_from_uri does not supported nested artifacts.

### ISSUE THREAD

**Issue by eedeleon** [mlflow/mlflow#1460]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows Subsytem for Linux Ubuntu 18.04
- **MLflow version**: 1.0.0
- **Python version**: 3.6.1
- **Exact command to reproduce**:

### Describe the problem
While debugging a user scenario I noticed _download_artifact_from_uri uses basename internally while parsing for the artifact path. This works for flat artifact paths such as "model" or "artifact_path", but omits the directory structure for "artifact_path/model".

Our scenario had a user passing runs:/run_id/ after a recent update to mlflow.azureml.build_image. However, this behavior should affect other code paths.

I started a PR resolving the runs:/run_id/path/to/file scenario but am opening up an issue since there are more affected code paths but not all of them are within mlflow's control. 

I think the issue here is parsing for the artifact path is ArtifactRepository specific. 

It may be useful to add a new function to the ArtifactRepository() with a default behavior of what was originally implemented in _download_artifact_from_uri for backwards compatibility.

def extract_artifact_path(self, artifact_uri):
    parse for schema 
    schema + artifact_uri to artifact repository  #  root_uri would be more correct
    artifact_path = artifact repository.extract_artifact_path(artifact_uri)
    return artifact_path

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by eedeleon** [comment]
@aarondav @tomasatdatabricks

This behavior is related to the move to model_uri instead of model_path. And the use of basename. I may be missing something since _download_artifact_from_uri is used in many places but the failures I was seeing seem consistent with the reported issue and the PR resolved them for me locally

**Comment by tomasatdatabricks** [comment]
Hi @eedeleon. thanks for the report!

The current code should work for nested artifacts.
 Do you have an example that we can repro? 
I have just tried it with the following inputs and all worked:

```
...
mlflow.log_artifact("aaa.txt", "some/nested/artifact/path")
from mlflow.tracking.artifact_utils import _download_artifact_from_uri
```

a) 
```
os.system("find %s" % _download_artifact_from_uri("runs:/58cc61f0b8354f68ab4f2f57505c8f24/some/nested/"))
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact/path
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact/path/aaa.txt
0
```

b)
```
os.system("find %s" % _download_artifact_from_uri("runs:/58cc61f0b8354f68ab4f2f57505c8f24/some/nested/artifact/path"))
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact/path
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact/path/aaa.txt
```

c) 
```
os.system("find %s" % _download_artifact_from_uri("runs:/58cc61f0b8354f68ab4f2f57505c8f24/some/nested/artifact/path/"))
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact/path
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact/path/aaa.txt
0
```

d)
```
os.system("find %s" % _download_artifact_from_uri("runs:/58cc61f0b8354f68ab4f2f57505c8f24/some/nested/artifact/path/aaa.txt"))
/Users/tomas/dev/mlflow-prototype/mlruns/0/58cc61f0b8354f68ab4f2f57505c8f24/artifacts/some/nested/artifact/path/aaa.txt
0
```

**Comment by aarondav** [comment]
Closing for lack of repro -- please reopen if you find one!
