### ISSUE TITLE
Runs with certain invalid names prevent UI from displaying

### ISSUE THREAD

**Issue by jhadjar** [mlflow/mlflow#1461]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
```
Linux silver 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- **MLflow installed from (source or binary)**: 
Source
- **MLflow version (run ``mlflow --version``)**:
```
/home/jugurtha/workspace/python/mlflow/mlflow/tracking/context.py:195: UserWarning: Failure attempting to register context provider "unused": module 'mlflow_test_plugin' has no attribute 'PluginRunContextProvider'
  _run_context_provider_registry.register_entrypoints()
mlflow, version 1.0.0
```
- **Python version**: 
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
```

- **npm version (if running the dev UI)**:
6.4.1
- **Exact command to reproduce**:
```
# in root directory mlflow
mkdir mlruns/_foo
mlflow ui
# Visit http://localhost:5000 and an image with 'Oops! Something went wrong.' returns
```
### Describe the problem

User James Salvatore opened a thread on mlflow's Slack general channel on this thread https://mlflow-users.slack.com/archives/CBFQ95Y2G/p1559066402036200 and the problem was raised when mlflow considered `__pycache__` directories as runs.

Why it's a problem:

A malformed run name silently renders the application unusable instead of being discarded and raising a warning/error message.

### Source code / logs

There are no error logs in the terminal, as opposed to when a run lacks a `meta.yaml` file and gives an error log like the following *without* preventing the UI from displaying:

```
Traceback (most recent call last):
  File "/home/jugurtha/workspace/python/mlflow/mlflow/store/file_store.py", line 183, in list_experiments
    experiment = self._get_experiment(exp_id, view_type)
  File "/home/jugurtha/workspace/python/mlflow/mlflow/store/file_store.py", line 233, in _get_experiment
    meta = read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "/home/jugurtha/workspace/python/mlflow/mlflow/utils/file_utils.py", line 159, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file './mlruns/foo_/meta.yaml' does not exist.
```

The browser logs however indicate that there was an error 500:

```
GET http://localhost:5000/ajax-api/2.0/preview/mlflow/experiments/list 500 (INTERNAL SERVER ERROR)
```
One has to inspect the browser console and then visit the link to get:

```
{"error_code": "INVALID_PARAMETER_VALUE", "message": "Invalid experiment ID: '_foo'"}
```

A `git grep "Invalid experiment ID"` points to `mlflow/utils/validation.py`, function `_validate_experiment_id`, which validates the experiment id against a regular expression found in the same file:

```python
_EXPERIMENT_ID_REGEX = re.compile(r"^[a-zA-Z0-9][\w\-]{0,63}$")
```
The function is called from `mlflow/store/file_store.py` in function `_get_experiment`.

The problem is that `mlflow.exceptions.MlflowException` is caught by `mlflow.server.handlers.catch_mlflow_exception`, and contrary to a missing YAML file that raises a `MissingConfigException`, the handler returns data as JSON without terminal logs.

In other words, in `mlflow.store.file_store.FileStore.list_experiments`, the method iterates over found runs:

```python
for exp_id in rsl:
    try:
        # trap and warn known issues, will raise unexpected exceptions to caller
        experiment = self._get_experiment(exp_id, view_type)
        if experiment:
            experiments.append(experiment)
    except MissingConfigException as rnfe:
        # Trap malformed experiments and log warnings.
        logging.warning("Malformed experiment '%s'. Detailed error %s",
                        str(exp_id), str(rnfe), exc_info=True)
```

If a directory is named `foo_` (trailing underscore) without a `meta.yaml` will simply cause a `MissingConfigException` to be raised and caught and logged without impeding on the rest of the runs/experiments.

However, if a directory is named `_foo` (leading underscore),  `_get_experiment_` calls `_validate_experiment_id` which  calls `_validate_experiment_id`, which raises an `mlflow.exceptions.MlflowException`. When the request is made and `mlflow.server.handlers._list_experiments` runs and calls `mlflow.store.file_store.FileStore.list_experiments` internally, the `mlflow.exceptions.MlflowException` is caught by the decorator `mlflow.server.handlers.catch_mlflow_exception` which simply returns a JSON response.

The same pattern is in `mlflow.store.file_store.list_experiments` and `mlflow.store.file_store.list_run_infos`.

Proposal:

- The loops in both methods should complete even with bad runs or experiments
- An informative log message in the terminal would be nice and keep the same logic as MissingConfigException (log, discard run, and continue).

**Approach 1: Catch MlflowException instead of MissingConfigException**:

MissingConfigException is a subclass of MlflowException, we can just catch MlflowException for logging

```python
except MlflowException as rnfe:
    # trap malformed run exception and log warning
    logging.warning("Malformed run '%s'. Detailed error %s", r_id, str(rnfe),
                    exc_info=True)
```

Or, 

**Approach 1: Savagely discard MissingConfigException**:

We can insert a line at the end of  `mlflow/exceptions.py` that reads:

```python
MissingConfigException = MlflowException
```

Which causes log warnings to appear that reads:

```
WARNING:root:Malformed experiment '_foo'. Detailed error Invalid experiment ID: '_foo'
Traceback (most recent call last):
  File "/home/jugurtha/workspace/python/mlflow/mlflow/store/file_store.py", line 183, in list_experiments
    experiment = self._get_experiment(exp_id, view_type)
  File "/home/jugurtha/workspace/python/mlflow/mlflow/store/file_store.py", line 228, in _get_experiment
    _validate_experiment_id(experiment_id)
  File "/home/jugurtha/workspace/python/mlflow/mlflow/utils/validation.py", line 142, in _validate_experiment_id
    error_code=INVALID_PARAMETER_VALUE)
mlflow.exceptions.MlflowException: Invalid experiment ID: '_foo'
```

And the UI to render correctly ignoring the bad run and giving us plenty of information in logs.

The downside is that we miss the information that it's a `MissingConfigException`, an exception raised at a grand total of three places in the code, in the same `file_utils.py` module. Nobody will miss it.

**Comment by ankitmathur-db** [comment]
Thanks for reporting and filing a PR - we'll be taking a look into this!

**Comment by ankitmathur-db** [comment]
Actually, I dug into this and I can't repro the issue - both solutions are not reasonable because in (1) you ignore any exceptions thrown and in (2) you lose specificity on what the error is. Moreover, it doesn't seem like you can legitimately create experiments in this way. If you're concerned about this though, feel free to use the SQL store.

**Comment by jhadjar** [comment]
> Actually, I dug into this and I can't repro the issue - both solutions are not reasonable because in (1) you ignore any exceptions thrown and in (2) you lose specificity on what the error is. Moreover, it doesn't seem like you can legitimately create experiments in this way. If you're concerned about this though, feel free to use the SQL store.

These are the very things that make the code break. The code neither logs the exception, nor raises it, nor handles it. It simply breaks the front end. There also is no specificity in the current code: the exception that's being silenced is a MissingConfig, when in fact it's the invalid directory that's the culprit.

The problem is:

- A malformed directory breaks the application instead of listing the good directories and warning about the malformed one (`_foo`)
- The error message is not displayed on the front end, which breaks, but in the console
- The Python exception does not show on the terminal, it's caught, not logged, burried, and sent to the broken front end
- The exception raised is misleading: the problem is not a missing configuration, it's the invalid directory name


Here are the steps to reproduce the issue:

- Create a directory named `_foo` in `mlruns`
- Run `mlflow ui`
- Visit `http://localhost:5000`


Using the SQL store is not a "solution".
