### ISSUE TITLE
Feature request: integrate with KFServing

### ISSUE THREAD

**Issue by rakelkar** [mlflow/mlflow#1465]
KFServing (https://github.com/kubeflow/kfserving) is an open source Kubeflow effort for model serving on Kubernetes. The effort is aligned with MLSpec and already supports a bunch of frameworks and is working on supporting more advanced inference graph scenarios. KFServing is intended to work on-prem as well as on major cloud providers.

Opening this issue to get feedback on if it makes sense to support KFServing as a serving target from MLFlow so that data scientists have a clean unified interface open optimized serving across clouds.

**Comment by pisymbol** [comment]
What is the status of this PR?

**Comment by AveshCSingh** [comment]
@gkorland is working on a PR that introduces a plugin system for integrating deployment tools. I believe this will be easier to implement once that is complete.

@rakelkar, let me know if you'd like to drive this.

@pisymbol, I don't believe a PR has been opened implementing this.

**Comment by hhsecond** [comment]
If it helps, I have made a RedisAI plugin [here](https://github.com/RedisAI/mlflow-redisai). Also, there are a few changes I am making over the coming week. It's not a lot of changes to break the implementation but just a heads up. It should be ready to merge by end of the coming week

**Comment by nehalecky** [comment]
https://github.com/mlflow/mlflow/pull/2327, has been merged. Congrats @hhsecond! 

This with the KFServing Python API, the https://github.com/kubeflow/kfserving/pull/218, makes all things aligned. Myself and @pakelley are interested to see this move forward, and wanted to know how we can contribute. @rakelkar @pisymbol @AveshCSingh , is a proposal in motion? Let us know how we can help, and thanks for these efforts. Awesome to see this functionality emerge!

**Comment by AveshCSingh** [comment]
Fantastic. Now that #2317 has been merged, we have the capability to add plugins for serving. I would recommend creating a separate repo to host the plugin, then linking to it from https://github.com/mlflow/mlflow/blob/master/docs/source/plugins.rst#deployment-plugins.

We'll be pushing an update to document the deployment plugin interface in https://mlflow.org/docs/latest/plugins.html over the next day or so. Until then, you can refer to the docs in the master branch: https://github.com/mlflow/mlflow/blob/master/docs/source/models.rst#deployment-to-custom-targets

**Comment by sevmardi** [comment]
Is KFServing migration a work-in-progress?
