### ISSUE TITLE
pickle is insecure and shouldn't be used for distributing models

### ISSUE THREAD

**Issue by KOLANICH** [mlflow/mlflow#1468]
### Describe the problem
`pickle` is a well-known security issue. Unpickling pickled data from an untrusted source can be dangerous. Also it is a nice place to hide backdoors because source code is readily accesable, including search, but to inspect pickled files one need special tools.

So pickle is a very bad solution for distributing pretrained models. So a way of serializing models without pickling them is needed.

Unfortunately some models, like neural networks, may be a security issue by itself. For example TensorFlow authors [say](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md):

>TensorFlow models are programs, and need to be treated as such from a security perspective.
>TensorFlow itself is not a sandbox. When executing the computation graph, TensorFlow may read and write files, send and receive data over the network, and even spawn additional processes. All these tasks are performed with the permissions of the TensorFlow process. Allowing for this flexibility makes for a powerful machine learning platform, but it has implications for security.
>As a general rule: Always execute untrusted models inside a sandbox (e.g., nsjail).
>Even if the untrusted party only supplies the serialized computation graph (in form of a GraphDef, SavedModel, or equivalent on-disk format), the set of computation primitives available to TensorFlow is powerful enough that you should assume that the TensorFlow process effectively executes arbitrary code.

**Comment by stablum** [comment]
I agree, always had problem with pickle. Better to develop a dedicated serialization system.

**Comment by dbczumar** [comment]
@KOLANICH We do not currently plan to introduce a custom model serialization format for MLflow. Many ML frameworks leverage pickle (e.g., Scikit-learn and PyTorch) for persisting models. It is possible to leverage MLflow's Models APIs without using pickle: many model flavors (such as `mlflow.tensorflow`) do not leverage pickle; you can also create your own model flavors, as well as custom `pyfunc` models that do not depend on pickle (see workflow 2 in https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#workflows).
