### ISSUE TITLE
AzureML Model Build Image Failure: ResolvePackageNotFound:- pyspark=2.4.3.dev0

### ISSUE THREAD

**Issue by joshuafennessy** [mlflow/mlflow#1470]
### System information

- Azure Databricks Runtime 5.3 and 5.4:
- MLflow installed from PyPi: 
- MLflow version 1.0.0:
- Python version 3.5.2: 

### Describe the problem
- I am adopting the code found in the [MLFlow Quickstart Part 2](https://docs.azuredatabricks.net/_static/notebooks/mlflow/mlflow-quick-start-deployment-azure.html) tutorial for instructional and demonstration purposes.

Attempting to create the model image 

```
model_image, azure_model = mlflow.azureml.build_image(model_uri=model_uri, 
                                                      workspace=workspace,
                                                      model_name="model",
                                                      image_name="model",
                                                      description="ALS product recomendation engine",
                                                      synchronous=False)

model_image.wait_for_creation(show_output=True)
```

results in error shown below
```
Step 11/14 : RUN sed -i '/^\s*-\s*python\s*[<>=]/d' '/var/azureml-app/conda.yaml' && cat '/var/azureml-app/conda.yaml'
 ---> Running in f4458dd2fa6b
channels:
- defaults
dependencies:
- pyspark=2.4.3.dev0
- pip:
  - mlflow
name: mlflow-env
Removing intermediate container f4458dd2fa6b
 ---> 75e7450423f8
Step 12/14 : RUN CONDA_ROOT_DIR=$(conda info --root) && if [ -n "$AZUREML_CONDA_ENVIRONMENT_PATH" ]; then conda env update -p "$AZUREML_CONDA_ENVIRONMENT_PATH" -f '/var/azureml-app/conda.yaml'; else conda env update -n base -f '/var/azureml-app/conda.yaml'; fi && conda clean -aqy && rm -rf /root/.cache/pip && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} +
 ---> Running in 862f157747b0
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata: ...working... done
Solving environment: ...working... failed
[91m
ResolvePackageNotFound: 
  - pyspark=2.4.3.dev0
```

### Source code / logs
[Model Image Build Log](https://github.com/mlflow/mlflow/files/3304056/build.3.log)
[Model Training and Deployment Code](https://github.com/mlflow/mlflow/files/3304072/mflow_azureml_sample.txt)

**Comment by akshaya-a** [comment]
@rastala FYI on needing sample code to unblock deployment outside mlflow

@joshuafennessy  The direct issue seems to be that the version of pyspark you're actually running within Databricks isn't a public pypi package (dev0). In the future, you can get around this issue by specifying the conda_env parameter in log_model to configure the environment file saved with the serialized model (in this case by specifying the public pyspark=2.4.3 instead of pyspark=2.4.3dev0).

However, looking deeper the azureml.build_image command currently only supports the "python" deployment framework in Azure ML - we'll get that fixed so that you get native pyspark support in AzureML. Your best bet right now might be to use mlflow all the way up to the build image command, where you then switch to using Azure ML SDK APIs directly.

**Comment by joshuafennessy** [comment]
@akshaya-a Thanks for the info and the suggestions!

I did end up getting it to work with MLFlow by manually editing the conda.yaml file in the model deployment directory.

Should I leave this issue open while you are working on the new feature?

**Comment by dbczumar** [comment]
@joshuafennessy Thank you for raising this. The version of PySpark installed by the Databricks Runtime is not available on Anaconda. We are working to make the version string for PySpark on Databricks consistent with the Anaconda version string in order to resolve this issue.

**Comment by akhisreelibra** [comment]
So I had the same issue as @joshuafennessy. As he said I edited conda.yaml in my saved pyspark model with Databricks-CLI.
