### ISSUE TITLE
Cannot install mlflow on Windows via pip

### ISSUE THREAD

**Issue by rilut** [mlflow/mlflow#1471]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: binary, pip
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.7.3 from Microsoft Store
- **Exact command to reproduce**: pip install --user mlflow

### Describe the problem
Cannot install mlflow on Windows 10 from pip
`'C:\\Users\\username\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\mlflow\\temporary_db_migrations_for_pre_1_users\\versions\\__pycache__\\'` exists but `ff01da956556_ensure_unique_constraint_names.cpython-37.pyc` don't.

### Source code / logs
```ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\username\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\mlflow\\temporary_db_migrations_for_pre_1_users\\versions\\__pycache__\\ff01da956556_ensure_unique_constraint_names.cpython-37.pyc'```

**Comment by akshaya-a** [comment]
This looks like a MAX_PATH issue. I suspect if you downloaded Miniconda and installed it into a reasonably short path (the 50 characters in the new Python package name aren't helping), you'd be able to install it successfully.

For this specific issue, you might be able to get around it with pip's no-cache-dir option, but you might end up hitting more MAX_PATH issues later on.

**Comment by MainHanzo** [comment]
not recommended to use mlflow on a win at present because it doesn't support gunicorn which is required by mlflow. I think a new feature will be coming soon with the support of windows but for the moment a unix machine would be a better choice.

**Comment by mbloem** [comment]
Any updates on this issue on Windows?
