### ISSUE TITLE
[RFC] Supporting Oracle databases as backing stores

### ISSUE THREAD

**Issue by mstrosaker** [mlflow/mlflow#1475]
This proposal is for allowing Oracle databases to be used as backing stores, using the same SqlAlchemyStore implementation used for other databases.  There are three identified issues that need to be addressed to add this support:  URI parsing, autoincrementing primary keys, and creation of the default experiment.

### URI Parsing

The URI parsing in six.moves.urllib does not appear to like underscores in the scheme part of URIs, which is unfortunate considering that cx_Oracle is a commonly-used driver:

```
>>> from six.moves import urllib
>>> urllib.parse.urlparse('oracle+cx_Oracle://user:passw0rd@127.0.0.1:1521/?service_name=FOO')
ParseResult(scheme='', netloc='', path='oracle+cx_Oracle://user:passw0rd@127.0.0.1:1521/', params='', query='service_name=FOO', fragment='')
>>> urllib.parse.urlparse('oracle+cxOracle://user:passw0rd@127.0.0.1:1521/?service_name=FOO')
ParseResult(scheme='oracle+cxoracle', netloc='user:passw0rd@127.0.0.1:1521', path='/', params='', query='service_name=FOO', fragment='')
```

The six.moves.urllib behavior seems to be the same as the python3 urllib behavior (as expected).

Altering this behavior is not proposed in this RFC.  Instead, it should be documented that URIs intending to specify the use of the cx_Oracle driver should start with “oracle://“ instead of “oracle+cx_Oracle://“ (leveraging the fact that cx_Oracle is the default driver for that dialect).

### Autoincrementing Primary Keys

Databases generally support one (or both) of two techniques for producing monotonically-increasing primary keys.  First is the use of database-specific autoincrementig column types; this is supported in SqlAlchemy by passing autoincrement=True when creating a column.  This technique is supported by sqlite, mssql, mysql, and postgresql.  It is not supported by Oracle.  (Technically, recent versions of Oracle database products, 12.1 or later, add an IDENTITY column type that implements this behavior, but SqlAlchemy is not currently capable of emitting SQL using that column type.)

The second technique is the use of Sequences, which are database constructs used to produce monotonically-increasing values.  With an autoincrement column type, the primary key does not need to be specified in INSERT statements; it will automatically receive the next value.  With sequences, the value of a primary key must be specified in an INSERT statement (it is specified as next_val(seq), or similar).  Sequences are supported in Oracle (and, incidentally, in postgresql).

There is only one autoincrementing value in the current schema: the primary key in the experiments table.  This proposal is to define the column as either:
```
    experiment_id = Column(Integer, autoincrement=True)
```
or
```
    experiment_id = Column(Integer, Sequence('experiment_seq’, start=1))
```
depending on the dialect that is being used.

Note that the sequence should be created to start at 1, since 0 is reserved for the default experiment.  Oracle defaults to starting sequences at 1, but it should be made explicit in case that changes, or in case other dialects need to use Sequences in the future.

### Creating the default experiment

The _create_default_experiment method in the SqlAlchemyStore class (mlflow/store/sqlalchemy_store,py) includes an SQL INSERT statement for creating the default (ID: 0) experiment.  This statement produces the following error:

```
mlflow.exceptions.MlflowException: (cx_Oracle.DatabaseError) ORA-00933: SQL command not properly ended
```

Further investigation shows that the cx_Oracle driver rejects statements that are terminated with semicolons; the statement works as expected if the semicolon is omitted.  I have been able to test sqlite, which works correctly if the semicolon is deleted.  This proposal includes removing the semicolon at the end of the INSERT statement, assuming it does not affect the other dialects.

**Comment by AveshCSingh** [comment]
I don't see a problem with any of the 3 proposals in this RFC. @mstrosaker, if you would like to send out a PR implementing these changes, I would be happy to review it.

I've also added tags to solicit help from others. I know this is an old request, and you may no longer be interested in implementing it.

**Comment by mparkhe** [comment]
Couple of comments from the RFC

For **Autoincrementing Primary Keys**, the proposal recommends changing `experiment_id` field to be `Sequence` based rather than using `autoincremental` for Oracle backend. The datamodel for `SqlExperiment` in `tracking/dbmodels/models.py` are independent of the type of DB backend used in `SqlAlchemyStore`. This simplifies the SQL alchemy logic and only the `SqlAlchemyStore` is aware of the `db_type`. Changing the definition would need to change how the models and store is instantiated.

Are there other Oracle libraries/dialect that support `autoincremental` syntax?

**Comment by gwadhwa** [comment]
Hello Guys, Is the oracle supported by ML Flow? I get an unsupported dialect error if I use oracle or oracle+oracle_cx as suggested by  SQL Alchemy. Please advise.

**Comment by DavidJardim** [comment]
> Hi, I know this is an old thread but I was also wondering if Oracle DB is currently supported by MLFlow? As the previous comment oracle or oracle+oracle_cx does not work. Thank you.

**Comment by josiahrohrer** [comment]
I am also currently looking into this and wondered if MLFlow is currently supported to be used with an Oracle DB as a backend store? Thanks a lot!
