### ISSUE TITLE
Artifacts not shown in UI

### ISSUE THREAD

**Issue by akagan2018** [mlflow/mlflow#1477]
### System information 
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:no, I am running sklearn_elasticnet_wine/train.py example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:MacOS
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**:1.0.0
- **Python version**: 3.7.3
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
I run MLflow server with Postgres as --backend-store-uri and local directory as --default-artifact-root
When I run experiments using: 
  python  $MLFLOW_PATH/sklearn_elasticnet_wine/train.py 0.5 0.51

All my experiments and runs are shown in MLflow UI, but artifacts are not shown. Artifacts are created in the mlruns directory (this directory is listed in UI for each experiment).

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

**All my experiments and runs are shown in MLflow UI, but artifacts are not. Artifacts are created in the mlruns directory (this directory is listed in UI for each experiment), but they are not shown on UI**

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by MainHanzo** [comment]
I am no pro at mlflow but I suggest you inspect the web page to see if there are some errors when loading your artifact in the run. In the case where mlflow did persist your artifacts in your run as you claimed in your description, it will be a prob between the front end and back end.

**Comment by AlonLek** [comment]
I had the same issue, moved to mlflow server (instead of mlflow ui ) and it was solved.

**Comment by glennelong** [comment]
AlonLek - Interesting, I tried moving the mlflow.set_tracking_uri to my server, recorded the run and nothing at all shows up in the UI? Were there any other changes? When I point tracking to the ML Flow UI, everything but the artifacts are tracked. Subsequently, I cannot register the model from the UI because the Register button never shows up.


e.g. 
UI Endpoint mlflow.set_tracking_uri('http://localhost:5001')
Server Endpoint mlflow.set_tracking_uri('http://localhost:5000')
