### ISSUE TITLE
How to pass 2D array as an input to the MLFlow Model

### ISSUE THREAD

**Issue by AwasthiMaddy** [mlflow/mlflow#1480]
### System information
- **Wrote a custom code of a NN in TensorFlow and converted into MLFlow Format**
- **Linux Ubuntu 16.04**
- **MLflow installed from pip** 
- **MLflow version 1.0.0**
- **Python version 3.7.3**

### Describe the problem
I have written a NN in TensorFlow and converted into MLFlow Format.     
This Model takes 5 inputs among them one of the input is a 2 dimensional array. 
Served this MLFlow Model. Now trying to infer like below -       
        
`curl -X POST -H "Content-Type:application/json; format=pandas-split" --data '{"columns":["u", "i",  "j",  "sl",  "hist_i"], "data":[[2, 234, 345, 2, [1234, 2345]]]}' http://127.0.0.1:1234/invocations`       
where last `hist_i` input takes 2D array in original model. 

But MLFlow reads this inputs and converts it into a pandas dataframe where each column is an input. So here, one of the column would have numpy arrays/list as its elements. And when you send this to TF for prediction here https://github.com/mlflow/mlflow/blob/fcb6fa8d18c3f8981806f220f65c3888f99a8046/mlflow/tensorflow.py#L330 you convert the column using pandas `df[tensor_column_name].values` which gives back a 1D numpy array and inside which there are again 1D numpy arrays/list and this fails the TF prediction as it was expecting a 2D array. 

Instead of pandas `df[tensor_column_name].values` you should be using `np.vstack(df[tensor_column_name].values)` which will give back 2D array. 

Does MLFlow supports multi-dimensional input? If yes, then how can I pass it?

**Comment by Metareflektor** [comment]
@AwasthiMaddy I've the same issue with passing a 2D-Array. Did you solve this problem?

**Comment by roadtorajendra** [comment]
@Metareflektor Were you able to solve the problem?

**Comment by Metareflektor** [comment]
@roadtorajendra I managed it with a custom predict method (https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#pyfunc-inference-api)
