### ISSUE TITLE
Can not connect to remote machine in local network

### ISSUE THREAD

**Issue by mcemilg** [mlflow/mlflow#1481]
### System information
- **OS Platform and Distribution `Linux Ubuntu 16.04.5`**:
- **MLflow installed from `binary`**: 
- **MLflow version `1.0.0`**:
- **Python version `3.6.6`**: 
- **Exact command to reproduce**:
`mlflow server --host 0.0.0.0`
`mlflow server --host <local_ip_addr>`

### Describe the problem
I am trying to connect remote machine on my local network. But it seems the  `mlflow server` did not listens all network interfaces. I tried to start server with local ip address of machine but it did not work. I am sure I can access to the machine because I have different services running on it. The problem maybe caused by gunicorn.

**Comment by pwais** [comment]
*bump*

related: `mlflow ui` does not allow the user to specify an IP to bind to (like `jupyter` does) but instead hard-codes 127.0.0.1: https://github.com/mlflow/mlflow/blob/69fabbcf59b690f021bf047c0bf3e2de594c70e6/mlflow/cli.py#L198

also, it's confusing to have two entrypoints to the UI?  are we supposed to use `mlflow ui` or `mlflow server`?  

I was able to get `mlflow server --host $MY_IP` to work the same way as `jupyter` does.  But `mlflow ui` binds to an IP that doesn't work.

FWIW I am running `mlflow` in a docker container on a remote machine.  Also Tensorboard always binds to a useable IP (or maybe it just listens on all interfaces).  Not sure why Tensorboard does the right thing while `mlflow` and `jupyter` need configuration.

I would propose fixing / deprecating the `mlflow ui` entrypoint.

**Comment by pwais** [comment]
*bump*

**Comment by pwais** [comment]
Perhaps we should create a new issue that allows the server to listen to arbitrary IP address? Similar to jupyter, flask, etc.

**Comment by pwais** [comment]
*bomp*

**Comment by pwais** [comment]
*bamp*

**Comment by pwais** [comment]
yesssss thank you @mparkhe !  🎉  this was actually one of the biggest blockers for me b/c my machines have multiple network interfaces
