### ISSUE TITLE
support addition/deletion of tags from the UI

### ISSUE THREAD

**Issue by jeremyjordan** [mlflow/mlflow#1486]
### Describe the problem
Is it possible to incorporate tag management in the UI? 

As I understand, you can only set tags from code when executing a run. It would be nice to be able to flexibly add tags after training when looking across model runs. For example, I might look across a set of 10 training runs and decide to choose 3 of those models for a test deployment. To keep things organized, it would be nice to have the ability (from the UI) to add a tag (eg. 'candidate_model=True') for the selected models.

**Comment by ankitmathur-db** [comment]
We've added the ability to add tags from the UI on runs in MLFlow 1.1 and we've introduced an API call that will allow you to delete them! Please let us know if these work for you.
