### ISSUE TITLE
How does MLflow capture (during training) and restore (before serving) model-dependencies

### ISSUE THREAD

**Issue by henningsway** [mlflow/mlflow#1489]
First of all, I really like the concepts used by MLflow to manage the ML-Lifecycle.

The MLflow Model Serving component doesn't fit my requirements exactly, but I would like to take advantage of the MLflow `save_model()` functionality, because I like the convention of storing the serialised model + required dependencies together.

I've been taking a first look at the documentation and the source code, but I would like to understand the processes involved a little better.

#### a) How does MLflow capture the dependencies?
When I run `save_model()` on a simple model a basic conda-environment is produced, while the dependencies seemt to depend on the mlflow-module `save_model()` was imported on.

- How exactly are the required dependencies (to serve the model) determined?
- Is this fully automatic or do I need to pass some dependencies manually (to `_mlflow_conda_env()` or similar)?
    - If it is automatic, how are the dependencies required for serving distinguished from the all the packages loaded during training (some of which may not be needed for serving)?
    - if its partly manual, what workflow do you suggest to capture all the dependencies required for serving?
- which role exactly does cloudpickle play? (is it possible, that some classes used are just bundled with the pickle-object, so the respective package doesn't have to be installed at serving time?)

#### b) How does MLflow Serving restore the conda-environment?
I'm currently considering to use your Tracking component and use my own custom Docker-based Serving-Solution. I assume, `conda env create -f conda.yml` may be enough, but maybe there is more to consider, which you could share a little about the process of recreating the required environments?

**Comment by fryzito** [comment]
:(

**Comment by totalhack** [comment]
:( as well. I'm also looking for some clarity on this. I had assumed logging a model would package all of the dependencies together such that load_model would "just work". But it seems I may have to manually use the pip/conda info in the artifact to make sure all dependencies are installed first?
