### ISSUE TITLE
Proposal: Allow explicitly pass active (parent) run_id

### ISSUE THREAD

**Issue by hyzhak** [mlflow/mlflow#1494]
### System information
- mlflow, version 1.0.0:
- Python 3.6.5

### The problem
I'm running MLFlow runs inside of Luigi which spin separate Worker for each task, as result I don't have run's nesting by default and should wrap explicitly each child run in:

```python
with mlflow.start_run(run_id=parent_id):
  with mlflow.start_run(nested=True):
    mlflow.log_metric('score', 1.0)
```

### Proposal

could it be something like?:

```python
with mlflow.start_run(parent_id=parent_id):
  mlflow.log_metric('score', 1.0)
```

**Comment by hyzhak** [comment]
Is there any chance to get response from human? 🤖

**Comment by stasinos** [comment]
@hyzhak I was looking for information on how to use nested runs and came across #2446 , which you might find interesting if you haven't spotted it already.
