### ISSUE TITLE
Feature Request: run experiment on remote server/spark cluster (e.g. cloudera) (and not through Databricks)

### ISSUE THREAD

**Issue by chanansh** [mlflow/mlflow#1505]
According to docs:

> "Remote execution for MLflow projects with Docker environments is not currently supported."
> And that remote execution "Support for running projects remotely on Databricks is in public preview".

How difficult is to contribute a running of project on a remote machine (e.g. multi-core server) or a remote Spark cluster (e.g. Cloudera)?

**Comment by AveshCSingh** [comment]
We now support running an MLflow Project on Kubernetes. Here are some details: https://www.mlflow.org/docs/latest/projects.html#run-an-mlflow-project-on-kubernetes-experimental

We don't yet have a clean mechanism for running MLflow Projects on Spark clsuters.
