### ISSUE TITLE
Document supported npm versions for JS dev environment

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#1506]
As @ankitmathur-db found, attempting to `npm install` packages to run the dev UI fails with node 12.4.0, with a very similar error to that described in https://github.com/fsevents/fsevents/issues/278. Downgrading to node 11.14 by installing from conda fixed the issue, but we should document this or upgrade the version of fsevents we depend on

**Comment by ankmathur96** [comment]
Hey @smurching - I don't see an option to re-open the issue myself, so replying here. 

I was following the instructions to set up the development environment, and I ran into an issue like this: https://pastebin.com/vbgdMHq2 , which I'm pretty sure is similar to what I had last time. Downgrading to Node v11 worked for me, but I think as of 10/2019, Node 12 is the LTS-supported release. I think upgrading the fsevents package might work!
