### ISSUE TITLE
Docker env flattening source directory structure

### ISSUE THREAD

**Issue by ngallot** [mlflow/mlflow#1516]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.10
- **MLflow installed from**: binary
- **MLflow version**: 1.0.0
- **Python version**: 3.7.0

### Describe the problem
I am using the Docker env to run the code in examples/docker. On my own project, I have a src folder inside my repo where I put all the python code, and the Dockerfile and MLproject files are located at the root of the repo (one level above the src folder). Strange thing is, when I run the mlflow run command, it seems that all my python files within the src folder are copied directly in /mlflow/projects/code, and not in /mlflow/projects/code/src.

### Source code / logs
I have reproduced this behavior directly in examples/docker folder. If I run the following commands:
```bash
mkdir examples/docker/myfolder
touch examples/docker/myfolder/myfile.txt
mlflow run examples/docker -P alpha=0.5
docker run mlflow-docker-example-<git-version> ls
```

I get the below output:

```
Dockerfile
Dockerfile.mlflow-autogenerated
MLproject
README.rst
kubernetes_config.json
kubernetes_job_template.yaml
myfile.txt
train.py
wine-quality.csv
```

The folder myfolder disappeared, and myfile.txt is copied at root level.

Is that a desired behavior?

Thanks!

**Comment by rixula** [comment]
I am facing the same issue. It seems not to be possible to use a docker_env with a project that has a more complicated folder structure than the toy example. In my case, the train.py is also not located in the project root, but in a subfolder. In general, it seems that the content of the project root folder is not properly copied to /mlflow/projects/code, in contrast to the documentation: "When you run an MLflow project that specifies a Docker image, MLflow adds a new Docker layer that copies the project’s contents into the /mlflow/projects/code directory."

**Comment by rixula** [comment]
Found the fix: https://github.com/mlflow/mlflow/pull/1160/commits/7c63f5d8ce6ec85af61683423d624baa6b164b93
