### ISSUE TITLE
What is the recommended way to log confusion matrix metrics?

### ISSUE THREAD

**Issue by hyzhak** [mlflow/mlflow#1529]
I'd like to be able to monitor dynamics of confusion matrix, And have tried to store it element-wise (`cm_{true}_{pred}`) to be able to monitor dynamics by epoch and be able to compare with other experiments. But in case of multiple classes (in my case it's 10) it becomes very huge metrics mlflow table, and breaks UX. 

What is the recommended way to log confusion matrix metrics? Can I group metrics so be able to collapse/expand them?

**Comment by whiletruelearn** [comment]
I have tried to plot confusion matrix as an image and then save that image as an artifact. This is something i found to be useful.

**Comment by hyzhak** [comment]
@whiletruelearn yes it partly work and I tried it as well, but in contrast to metrics (e.g. `cm_{true}_{pred}`), I wasn't be able to compare different runs matrices and their dynamics.

**Comment by mcamila777** [comment]
I also wonder if it exist a way of store and compare the confusion matrices as metrics in ml_flow, to be compared among experiments. Does anyone know if this is possible?

**Comment by hyzhak** [comment]
hm, I'd like to get a more useful answer than an automatic answer from a bot.

**Comment by 2mariya** [comment]
> I'd like to be able to monitor dynamics of confusion matrix, And have tried to store it element-wise (`cm_{true}_{pred}`) to be able to monitor dynamics by epoch and be able to compare with other experiments. But in case of multiple classes (in my case it's 10) it becomes very huge metrics mlflow table, and breaks UX.
> 
> What is the recommended way to log confusion matrix metrics? Can I group metrics so be able to collapse/expand them?

This would do it.
cm = confusion_matrix(y, y_pred)
t_n, f_p, f_n, t_p = cm.ravel() 
mlflow.log_metric("tn", t_n)
mlflow.log_metric("fp", f_p)
mlflow.log_metric("fn", f_n)
mlflow.log_metric("tp", t_p)

**Comment by hyzhak** [comment]
@2mariya yes, I usually do that way but it somehow work only in case of binary classification, but quickly becomes inefficient when number of classes grows

**Comment by redaelhail** [comment]
Is there any solution for this issue yet?

**Comment by skshahidur** [comment]
Following

**Comment by AlxndrMlk** [comment]
Hey everyone,

one thing that you can use is `mlflow-extend`. It enhances `mlflow` capabilities by adding confusion matrix logging and a couple of other useful functionalities:

**Repo:** https://pypi.org/project/mlflow-extend/

**Docs:** https://mlflow-extend.readthedocs.io/en/latest/index.html

**Comment by dswah** [comment]
I solved this for my use-case by with `mlflow.log_dict`

```python
mlflow.log_dict(np.array(confusion_matrix).tolist(), "confusion_matrix.json")
```

**Comment by terbed** [comment]
Confusion matrix logging and the ability to compare them across experiments would be an extra beneficial feature (like it is nicely done in [weight and biases](https://wandb.ai/wandb/plots/reports/Confusion-Matrix-Usage-and-Examples--VmlldzozMDg1NTM)).

**Comment by DWarez** [comment]
> Confusion matrix logging and the ability to compare them across experiments would be an extra beneficial feature (like it is nicely done in [weight and biases](https://wandb.ai/wandb/plots/reports/Confusion-Matrix-Usage-and-Examples--VmlldzozMDg1NTM)).

+1
it's really a crucial feature

**Comment by ramesh-lazr** [comment]
Any updates on this?

**Comment by FabricioArendTorres** [comment]
How is this still an open and completely unanswered issue in 2025?
