### ISSUE TITLE
MLflow Java searchRuns returns list[RunInfo] instead of list[Run]

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#1530]
### System information
- **MLflow version (run ``mlflow --version``)**: 1.0.0

MLflow Java client searchRuns returns list[RunInfo] instead of list[Run]. The REST and Python methods return the correct type.

Documentation links:
- Java: https://mlflow.org/docs/latest/java_api/org/mlflow/tracking/MlflowClient.html#searchRuns-java.util.List-java.lang.String-
- Python: https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.search_runs
- REST: https://mlflow.org/docs/latest/rest-api.html#search-runs

**Comment by max-allen-db** [comment]
Hey @amesar, 

Yes, this was a mistake on our part when 1.0.0 released. Unfortunately, we don't want to break 1.0 API.

What we've done to address this is that in the MLflow 1.1 release, the `searchRuns` method will be overloaded with additional arguments and return a `RunsPage` object. This object will have access to an Iterator over all the `Run`s in the result, plus add the ability to get the next Page of results if there are more results than can fit in one page.

You can see the 1.1 branch's MLflowClient here: https://github.com/mlflow/mlflow/blob/branch-1.1/mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java#L179
And RunsPage here: https://github.com/mlflow/mlflow/blob/branch-1.1/mlflow/java/client/src/main/java/org/mlflow/tracking/RunsPage.java#L9
