### ISSUE TITLE
MLflow Python get_experiment does not return list[RunInfo]

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#1531]
### System information
- **MLflow version (run ``mlflow --version``)**: 1.0.0

MLflow Python API get_experiment does not return an array of RunInfo as specified by the REST API. It only returns an Experiment. The REST and Java versions return an Experiment and list[RunInfo]. 

Documentation links: 
* Python: https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.get_experiment
* REST: https://mlflow.org/docs/latest/rest-api.html#get-experiment
* Java: https://mlflow.org/docs/latest/java_api/org/mlflow/api/proto/Service.GetExperiment.Response.html#getExperiment--

**Comment by mparkhe** [comment]
Good catch! However, changing this entails a breaking API change. We will try and address this in future major releases.
