### ISSUE TITLE
Try to use MSSQL as backend store but see error unexpected URI type

### ISSUE THREAD

**Issue by weng271190436** [mlflow/mlflow#1538]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: 
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
![image](https://user-images.githubusercontent.com/6925089/60467118-7f3fbb80-9c0a-11e9-98d5-8c9e310d1746.png)
- **MLflow installed from (source or binary)**:
pip install mlflow 
- **MLflow version (run ``mlflow --version``)**:
![image](https://user-images.githubusercontent.com/6925089/60467156-a7c7b580-9c0a-11e9-90d7-34e4b86869f9.png)
- **Python version**: 
![image](https://user-images.githubusercontent.com/6925089/60467146-98e10300-9c0a-11e9-8966-cbc03d643d3e.png)
- **npm version (if running the dev UI):
![image](https://user-images.githubusercontent.com/6925089/60467200-ce85ec00-9c0a-11e9-84ca-a775930b8b1b.png)
- **Exact command to reproduce**:
sudo -E env "PATH=$PATH" mlflow server --host 0.0.0.0 --port 5000 \
--default-artifact-root wasbs://blob-container@azure-storage-account.blob.core.windows.net \
--backend-store-uri "mssql+pyodbc://username:password@mssql-server-name.database.windows.net:1433/database-name"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

See ERROR 
![image](https://user-images.githubusercontent.com/6925089/60467724-36890200-9c0c-11e9-96cd-cb8948e337e9.png)

SQLAlchemy supports the scheme mssql+pymssql but MLflow doesn't seem to support it.
![image](https://user-images.githubusercontent.com/6925089/60467787-6b955480-9c0c-11e9-905f-7e0758ee11a8.png)
https://docs.sqlalchemy.org/en/13/core/engines.html#microsoft-sql-server

![image](https://user-images.githubusercontent.com/6925089/60467828-92538b00-9c0c-11e9-9bf2-f0b8df092d53.png)

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by dbczumar** [comment]
@weng271190436 This has been fixed in `master`. Can you clone the MLflow repo, install MLflow from the `master` branch, and attempt to reproduce the problem?

**Comment by weng271190436** [comment]
> @weng271190436 This has been fixed in `master`. Can you clone the MLflow repo, install MLflow from the `master` branch, and attempt to reproduce the problem?

I had trouble running npm install on master branch following this guide: https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst

Will let you know if I get it set up. Or maybe you guys are going to release a new version soon so that I can pip install the latest version and verify?
