### ISSUE TITLE
Cannot insert explicit value for identity column in table 'experiments'

### ISSUE THREAD

**Issue by weng271190436** [mlflow/mlflow#1539]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Debian 9.9
- **MLflow installed from (source or binary)**:
pip install mlflow 
- **MLflow version (run ``mlflow --version``)**:
1.0.0
- **Python version**:
3.7.3 
- **npm version (if running the dev UI):
none
- **Exact command to reproduce**:
sudo -E env "PATH=$PATH" mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root <blob storage uri> --backend-store-uri <mssql uri>

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.
MLflow tries to insert a default experiment with experiment_id 0 into the experiments table in _create_default_experiment method in sqlalchemy_store.py. However, experiment_id is a primary key and SQL Server database rejects it.

![image](https://user-images.githubusercontent.com/6925089/60488528-0ca8fd00-9c57-11e9-9326-8dbfae832c64.png)

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

![image](https://user-images.githubusercontent.com/6925089/60488770-b092a880-9c57-11e9-9435-3a2deadb9897.png)

**Comment by stevenluda** [comment]
Same issue. Any solution?

**Comment by ankitmathur-db** [comment]
Can you try this with MLFlow 1.1 and confirm you see the same issue?
