### ISSUE TITLE
error with “mlflow ui” at windows

### ISSUE THREAD

**Issue by MammadTavakoli** [mlflow/mlflow#154]
when i run `mlflow ui` this error occurred:

    Traceback (most recent call last):
      File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Anaconda3\Scripts\gunicorn.exe\__main__.py", line 5, in <module>
      File "c:\anaconda3\lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
        from gunicorn.app.base import Application
      File "c:\anaconda3\lib\site-packages\gunicorn\app\base.py", line 12, in <module>
        from gunicorn import util
      File "c:\anaconda3\lib\site-packages\gunicorn\util.py", line 9, in <module>
        import fcntl
    ModuleNotFoundError: No module named 'fcntl'
    Traceback (most recent call last):
      File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Anaconda3\Scripts\mlflow.exe\__main__.py", line 9, in <module>
      File "c:\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "c:\anaconda3\lib\site-packages\click\core.py", line 697, in main
        rv = self.invoke(ctx)
      File "c:\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "c:\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "c:\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "c:\anaconda3\lib\site-packages\mlflow\cli.py", line 131, in ui
        mlflow.server._run_server(file_store, file_store, host, port, 1)
      File "c:\anaconda3\lib\site-packages\mlflow\server\__init__.py", line 48, in _run_server
        env=env_map, stream_output=True)
      File "c:\anaconda3\lib\site-packages\mlflow\utils\process.py", line 38, in exec_cmd
        raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
    mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1

I used anaconda + python 3.6.5 and I installed git and set path with `C:\Program Files\Git\bin\git.exe` and `C:\Program Files\Git\cmd`.

I installed `mlflow` whit `pip install mlflow` and its version is 0.2.1.

I set a variable with name `GIT_PYTHON_GIT_EXECUTABLE` and value `C:\Program Files\Git\bin\git.exe` in Environment Variables.
how can solve this

**Comment by wmeints** [comment]
Turns out the `fcntl` module [is unavailable on Windows systems](https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows). In Windows there's an alternative called the `win32api`. But the interface is very different from the `fcntl` library. 

If you're running on windows 10 consider using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I use it quite a bit, especially for these kind of cases where there isn't a suitable alternative that works on Windows.

**Comment by smurching** [comment]
Thanks @MammadTavakoli & @wmeints for answering the question! Will close this out since the question was answered, but feel free to reopen :)

**Comment by swayson** [comment]
Are there any plans to have Windows supported for the `mlflow ui` ?
I am also experiencing that problem with `fcntl`.

**Comment by AaronFaltesek** [comment]
Had this same problem

**Comment by ektaraj** [comment]
Did anyone get the solution of this issue?

`ModuleNotFoundError: No module named 'fcntl'
Running the mlflow server failed. Please see the logs above for details.`

**Comment by aarondav** [comment]
I think #1080 would resolve these issues -- @akshaya-a in case he gets time to update the PR.

**Comment by akshaya-a** [comment]
Thanks for the ping @aarondav - currently looking to close out Tomas' comments this week!

**Comment by Gryshchuk** [comment]
Hi, do you have any updates on this?

> Thanks for the ping @aarondav - currently looking to close out Tomas' comments this week!

Hi, do you have any updates?

**Comment by ecrtmt** [comment]
Tested "mlflow ui" with the latest commit.  Waitress was installed, it started but I was unable to connect to localhost:5000.

Using Python 3.7.3 and mlflow 1.0 .

**Comment by siddhesh1991** [comment]
Hey @akshaya-a

I installed mlflow on windows for python using pip install mlflow, then installed waitress using pip install waitress. I am still not able to start mlflow ui. I get the following error:
No module named 'fcntl'. Running the mlflow server failed

**Comment by akshaya-a** [comment]
@ecrtmt  are you on slack? I'd love to dig into your issue to diagnose it, might need to debug a bit back and forth, however.

@siddhesh1991  you'd need to install mlflow from the commit from #1080  or higher as we haven't released mlflow with the change to PyPI yet

**Comment by allen108108** [comment]
@akshaya-a 
I saw #1080 but I still don't know how to use it to avoid " No module named 'fcntl' " problem.
Can you help me ?

**Comment by akshaya-a** [comment]
@aarondav do we have a rough estimate on the next PyPI release for MLflow? Happy to drive the release if it’s something more involved and not planned in the short term

**Comment by MainHanzo** [comment]
@ecrtmt @akshaya-a  I think I've run into the same issue, the server was started but I got nothing in my localhost:5000. How did you solve this? I  have pip installed waitress and the latest commit of your replace_gunicorn_with_waitress branch.

**Comment by ghizmodave** [comment]
Hello, I've tried to fix the problem with #1080 but my mlflow still doesn't work. 
With the original mlflow 1 installation I get the fcntl error and replacing the files from the commit at #1080 it just doesn't find required files to run.
Is there any update on this?

**Comment by MainHanzo** [comment]
@ghizmodave  @ecrtmt 
I finally figure it out!
To anyone who might be still stuck here:
**Here is what I do:**
Before starting:
1. make sure you don't have another mlflow installed by pip. Best solution is to creeate a new env in your conda

**Process**
1. download the code of https://github.com/akshaya-a/mlflow/tree/ak/replace-gunicorn-with-waitress
2. in your cmd(if you use conda env activate it beforehand, maybe you need to install a new pip as well for your new env) pip install /path/to/the.zip
3. mlflow ui           in you cmd, you will be returned a "not found" error, that's normal because there is no code for frontend in the code you download :/
4. copy the js dir in the server dir in master branch of mlflow:
https://github.com/mlflow/mlflow/tree/edfce0148203b867254594b31b30bb4197fbb6cd/mlflow/server
(if what I am saying confuse you, just get the js dir in the link)
5. copy the js dir to the dir of mlflow you just installed by pip(if you used new env in conda, it would be in a dir like /path/to/your/conda/envs/your/conda/name/Lib/site-packages/mlflow/server)
6. relaunch the mlflow by mlflow ui, Done!
7. I hate to develop in windows, I am turning back to my linux now. :/

**Comment by diptipatil** [comment]
This is really helpful.

**Comment by diptipatil** [comment]
> @ghizmodave @ecrtmt
> I finally figure it out!
> To anyone who might be still stuck here:
> **Here is what I do:**
> Before starting:
> 
> 1. make sure you don't have another mlflow installed by pip. Best solution is to creeate a new env in your conda
> 
> **Process**
> 
> 1. download the code of https://github.com/akshaya-a/mlflow/tree/ak/replace-gunicorn-with-waitress
> 2. in your cmd(if you use conda env activate it beforehand, maybe you need to install a new pip as well for your new env) pip install /path/to/the.zip
> 3. _mlflow ui_           in you cmd, and check your browser of _localhost:5000_ an "not found" error will be returned  , that's normal because there is no code for frontend in the code you download :/
> 4. install mlflow(pypi version) with your system pip not the conda one:
>    **pip install mlflow**
>    go to site-packgas of your sys pip and copy a dir named js in mlflow/server, its path should look like this:
>    _"toyoursyspip/site-packages/mlflow/server/js"_  , makesure that there is a dir named "build" inside.
> 5. copy the js dir to the dir of mlflow you just installed by pip(if you used new env in conda, it would be in a dir like /path/to/your/conda/**envs**/yourEnvName/**Lib/site-packages/mlflow/server**)
> 6. relaunch the mlflow by _mlflow ui_, Done!
> 7. I hate to develop in windows, I am turning back to my linux now. :/

This is really helpful
