### ISSUE TITLE
AttributeError: module 'mlflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by gusseppe** [mlflow/mlflow#1540]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**:  no
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.7.3
- **npm version (if running the dev UI)**:
- **Exact command to reproduce**: 
```
import mlflow
mlflow.keras
```
### Describe the problem

When saving a keras model using: 
```
mlflow.keras.log_model(model, "models")
```
it yields the mentioned error. 
A workaround is to export:
```
from mlflow.keras import log_model
```
But it is not the wanted behaviour.

### Source code / logs

```
import mlflow
mlflow.keras
```
_Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'mlflow' has no attribute 'keras'_

**Comment by apurva-koti** [comment]
Have you tried `import mlflow.keras`?

**Comment by gusseppe** [comment]
Should I import keras methods only by doing: _import mlflow.keras_  and not as always first: _import mlflow_  and then just use it as : _mlflow.keras_?

**Comment by apurva-koti** [comment]
`keras` is a module within the `mlflow` package. You can `import mlflow.keras` or `from mlflow.keras import X` as you mentioned, but there is no `keras` attribute in `mlflow/__init__.py`.

**Comment by apurva-koti** [comment]
@gusseppe Does this resolve the issue?

**Comment by gusseppe** [comment]
@apurva-koti  Yes yes thanks, I got it!. I gonna close this thread.

**Comment by diazmanne** [comment]
I upgraded pip, Tensorflow and mlflow and it get fixed
