### ISSUE TITLE
Exception: Unexpected data for param [...]. Param recorded more than once

### ISSUE THREAD

**Issue by wmeints** [mlflow/mlflow#155]
### System information
- I used mlflow from my python notebook
- Ubuntu 16.04
- MLflow is installed using pip from the master branch
- MLflow version: 0.2.1
- Python version: 3.6

### Describe the problem
When you accidently record parameters twice with `log_param` you get an error: 

```
Exception: Unexpected data for param 'features'. Param recorded more than once
```

In my case I recorded the features param twice.

Once you've recorded a parameter more than once the error persists and the ui becomes unusable. Also, you can't run any new experiments or create runs for existing experiments. It fails always.

### Expected behavior
When I record my parameters twice, I would expect the value of the parameter to be overwritten with the second value. A warning is fair, but it shouldn't fail. 

I can imagine that not everyone wants the behavior I described above. In that case, raise an error, but don't break the application, because in a production environment that would require someone to manually fix the database. Which is bad.

**Comment by smurching** [comment]
Hi @wmeints, thanks for reporting this issue - our intended behavior is actually the one you expected (that when you log a param twice, the value of the param is overwritten with the second value). We write the param to disk [here](https://github.com/databricks/mlflow/blob/6722b025a0186dd9962bd911f09823b42b796eb8/mlflow/store/file_store.py#L288), opening the file in [write mode](https://github.com/databricks/mlflow/blob/6722b025a0186dd9962bd911f09823b42b796eb8/mlflow/utils/file_utils.py#L222). 

Would you be able to share the code that led to this issue? Also agreed that printing a warning rather than raising an exception seems preferable.

**Comment by wmeints** [comment]
Sure I have that, here's the code I use for training my model.

``` python
mlflow.set_tracking_uri('http://localhost:5000')
experiment_id = mlflow.create_experiment('Predict MPG')

with mlflow.start_run(experiment_id=experiment_id, source_name='train.py', source_version='1'):
    model = LinearRegression()
    model.fit(train_features,train_targets)
    
    predicted_y = model.predict(test_features)
    
    mae = mean_absolute_error(test_targets,predicted_y)
    mse = mean_squared_error(test_targets,predicted_y)
    r2 = model.score(test_features, test_targets)
    
    mlflow.log_metric('mae',mae)
    mlflow.log_metric('mse',mse)
    mlflow.log_metric('r2', r2)
    
    mlflow.log_param('samples', train_features.shape[0])

    model_path = '{}/model.pkl'.format(mlflow.get_artifact_uri())
    
    with open(model_path, 'wb') as model_file:
        pickle.dump(model, model_file)
        
    mlflow.log_artifact('model.pkl','model.pkl')
```

**Comment by smurching** [comment]
@wmeints sorry for the slow response - your script looks fine, I was able to rerun it successfully with slight modifications:

```
import mlflow
import pickle
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Load the diabetes dataset
diabetes = datasets.load_diabetes()

# Use only one feature
diabetes_X = diabetes.data[:, np.newaxis, 2]

# Split the data into training/testing sets
train_features, test_features = diabetes_X[:-20], diabetes_X[-20:]

# Split the targets into training/testing sets
train_targets, test_targets = diabetes.target[:-20], diabetes.target[-20:]

mlflow.set_tracking_uri("http://localhost:5000")

with mlflow.start_run(experiment_id=0, source_name='train.py', source_version='1'):
    model = LinearRegression()
    model.fit(train_features,train_targets)

    predicted_y = model.predict(test_features)

    mae = mean_absolute_error(test_targets,predicted_y)
    mse = mean_squared_error(test_targets,predicted_y)
    r2 = model.score(test_features, test_targets)

    mlflow.log_metric('mae',mae)
    mlflow.log_metric('mse',mse)
    mlflow.log_metric('r2', r2)

    mlflow.log_param('samples', train_features.shape[0])

    model_path = '{}/model.pkl'.format(mlflow.get_artifact_uri())

    with open(model_path, 'wb') as model_file:
        pickle.dump(model, model_file)
    # Removed the log_artifact call since we already write directly to the artifact dir
```

Are you able to consistently reproduce this issue? It could also come up if there are concurrent accesses to the same file (e.g. if you log metrics from a multithreaded application), although it doesn't look like that's the case in your script.

**Comment by arnabbiswas1** [comment]
I am encountering with the same error message:

> Exception: Unexpected data for param 'ntree'. Param recorded more than once

In my case, I saved a pandas.core.series.Series object accidentally as a parameters and then the UI become unusable.
> mlflow.log_param("ntree", number_of_trees)

Here number_of_trees is a "pandas.core.series.Series" object holding a numeric value:

> 0    37.0
> Name: number_of_trees, dtype: float64

Ideally, log_param should not accept the value itself? Please let me know.

**System information**
Ubuntu 16.04
MLFlow : Installed using pip via Anaconda (conda 4.5.4)
MLflow version: 0.5.2
Python version: 3.7.0

**Comment by joshuacook** [comment]
I encountered this issue this morning. I wish there was a better way to handle the error. Write now it stalls the server forcing a server reboot. IMO the MLflow server should be able to handle a bad parameter being passed.

**Comment by smurching** [comment]
Got it, yeah it seems like there are a couple of issues at play:
* Writing a param whose value contains a newline causes our read-side validation to fail when reading back the param (e.g. for display in the UI). The validation logic is [here](https://github.com/mlflow/mlflow/blob/HEAD/mlflow/store/file_store.py#L326). My guess is that this is the most likely issue to be hit (it's what happens in the Pandas series case)
* Concurrently writing the same parameter may result in it being written more than once. This seems less likely / hard to prevent without file locking, so I'd prefer to punt on this.
* The UI doesn't handle corrupt parameters well. 

Maybe for now we can validate that parameter values don't contain newlines when writing them. I'd suggest adding a `validate_param_value` helper [here](https://github.com/mlflow/mlflow/blob/1b8f954d2691890c1168675e8942f8259121b2d8/mlflow/utils/validation.py#L38) that uses [str.splitlines](https://docs.python.org/3/library/stdtypes.html#str.splitlines) to verify that the param value contains a single line, calling `validate_param_value` in the [top-level log_param implementation](https://github.com/mlflow/mlflow/blob/1b8f954d2691890c1168675e8942f8259121b2d8/mlflow/tracking/service.py#L107). We should also unit-test `validate_param_value` [here](https://github.com/mlflow/mlflow/blob/1b8f954d2691890c1168675e8942f8259121b2d8/tests/utils/test_validation.py). Would you be interested in making a PR for this fix @joshuacook @arnabbiswas1 @wmeints? Thanks again for reporting this issue :)

**Comment by joshuacook** [comment]
I could do it.

**Comment by joshuacook** [comment]
@smurching Thinking more about this. I see two issues here:

1. an object of type `pandas.Series` will raise an error when passed as a parameter. I believe that expected behavior should be that a `pandas.Series` is rendered as a list. Note that an `np.array` of shape `(n, )` is rendered as a list.
2. The server handles errors poorly causing the behavior that @wmeints saw. When an API call results in an error that server hangs on that error. I believe that expected behavior should be that the server handles and logs the error, but then returns to a ready state.
