### ISSUE TITLE
500 byte REST endpoint logging limit

### ISSUE THREAD

**Issue by johntiger1** [mlflow/mlflow#1552]
![image](https://user-images.githubusercontent.com/14852840/60739095-89292d80-9f2e-11e9-9e0f-69dd127650b4.png)

An actual use case is that I am trying to log the entire model as a param: 

![image](https://user-images.githubusercontent.com/14852840/60739121-acec7380-9f2e-11e9-8b46-2d26874b7600.png)

Not necessarily asking for the limit to be changed, but I am curious as to why it is there? Thanks

**Comment by ankitmathur-db** [comment]
We added tags, which have a significantly higher limit - you could try using that!

**Comment by ankitmathur-db** [comment]
For your actual use case, you might want to consider ``log_model`` or ``log_artifact``. Params are meant to be machine learning parameters - they're not really supposed to be arbitrarily large byte strings. For larger string related things to log, we have tags. Reading your use case though, you should consider using the ``log_model`` or ``log_artifact`` options.
