### ISSUE TITLE
Log numpy arrays

### ISSUE THREAD

**Issue by guist** [mlflow/mlflow#1560]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6.7

### Describe the problem
Is it possible to log other artifacts apart from scalars and models, such as numpy arrays? It would be interesting to store intermediate data and not process the full pipeline for each run if it does not need to. Thanks!

**Comment by ankitmathur-db** [comment]
You can probably use tags for this purpose by serializing the Numpy array (depending on what the size of the array you want to serialize is). Did you want to log a bunch of arrays throughout the training process (like logging the "loss" value every iteration), or did you want to just log a single array (or a few)

**Comment by guist** [comment]
Thanks for the answer.

My idea would be to store a bunch of arrays such as:
-arrays with pre-processed data
-arrays containing features

Sometimes, when we do a small change in the code, for example a parameter in the classification, the pre-processed data and the features remain the same. It would be great not to re-calculate the unchanged parts.

Thus, I was wondering if mlflow could store intermediate arrays and, for each new run, check whether these arrays need to be calculated or if they have already been calculated during a previous run.

**Comment by ankitmathur-db** [comment]
If the features remain the same, why not just read them directly in your training script?

If you really want to log intermediate arrays, what prevents you from logging them as artifacts on the run?

**Comment by guist** [comment]
Actually I read about 
`mlflow.log_param()`
`mlflow.log_metric()`

But I did not know that there was also the option to call 
`mlflow.log_artifact()`

I guess this does what I was asking for. Thanks!
