### ISSUE TITLE
RDS Clogs with mlflow connections

### ISSUE THREAD

**Issue by nachiketparanjape** [mlflow/mlflow#1565]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6

### Describe the problem
I am running an MLflow Server on an EC2 instance. It is backed by a tracking store on an Postgres RDS instance. 
While training a number of models in a parallel manner, my DB gets clogged by connections resulting in my job to fail. 
I was wondering if we could enable connection pooling here: https://github.com/mlflow/mlflow/blob/master/mlflow/store/sqlalchemy_store.py#L73

Also, if there was any other suggestion to avoid the current issue. 

### Source code / logs
```
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

**Comment by mparkhe** [comment]
This seems unusual. Do you use non-default settings for # of connections? How many workers are you using for `mlflow server` and could you talk about the query volume, amount of data and query runtime on database. Is there any way to profile your query pattern.

Connection pooling will help avoid this error in database but will error our upsteam if you have bursty loads or if the query volume is high.

**Comment by nachiketparanjape** [comment]
Hi @mparkhe , 

I am currently running an RDS remote tracking server. I have a multi-thread python code which does something like this. Here's the pseudo code:

`
- Each thread: Acquire Lock
- mlflow.set_tracking_uri(): Set to RDS endpoint
- mlflow.set_experiment
- with mlflow.start_run, log params, metrics
`

We then also have setup an EC2 server which we use for UI purposes and has a process running similar to the given documentation. 
`mlflow server --backend-store-uri RDS_ENDPOINT --default-artifact-root S3 -p 5050 --host 0.0.0.0`

I seem to have long running connections on the DB which I have to externally shut down for the mlflow run to complete successfully.

**Comment by nachiketparanjape** [comment]
Closing this. Realized where I went wrong.
