### ISSUE TITLE
Feature request: Support type 'logical' for parameters in R 

### ISSUE THREAD

**Issue by lorenzwalthert** [mlflow/mlflow#1572]
```r
mlflow::mlflow_param(..., type)
```
Does supports only "numeric", "integer", or "string", but not "logical" ([source](https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/R/project-param.R#L28)). Why not?

**Comment by ankitmathur-db** [comment]
You can convert your logical to an int before logging it? Params are semantically intended to represent machine learning parameters, and we believe parameters typically correspond to numeric, integer, or string-like values. As such, we don't intend on supporting logical into the API, but the framework doesn't need to change for your use case to be supported.

**Comment by lorenzwalthert** [comment]
Thanks @ankitmathur-db. Yes, I could probably but don't you think it's bad practice to change the type of a parameter between declaring and logging? Also, I don't see why machine learning parameters should be strings and integers and numeric, but not logical. There are many libraries and algorithms that take logical also. I just browsed the keras overview page [here](https://www.tensorflow.org/beta/guide/keras/overview) and found a few.
