### ISSUE TITLE
Cannot connect to S3

### ISSUE THREAD

**Issue by abaveja313** [mlflow/mlflow#158]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Sierra
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.2.1
- **Python version**: 3.6
- **npm version (if running the dev UI): 
- **Exact command to reproduce**: mlflow server --host 0.0.0.0 --artifact-root s3://<my s3>

### Describe the problem
Hi. I am using MLFlow and would like to store all of my model artifacts in S3. However, when I try to execute the above command, it isn't communicating with S3. I think that it is still trying to create a local directory (in my tmp), using this name. When I do `mlflow experiments list`, I get:
```
  Experiment Id  Name     Artifact Location
---------------  -------  -------------------------------
              0  Default  /private/tmp/s3:/<my s3>/0
```
Additionally, if I ran `mlflow server` in a directory where there was already an mlruns directory present, it would use that and ignore my S3 input. I have credentials setup in ~/.aws/credentials

**Comment by smurching** [comment]
Thanks @abaveja313 for reporting this issue, I'm looking into it now. The result displayed by `mlflow experiments list` is a little confusing, we currently resolve the artifact location to an absolute path [here](https://github.com/databricks/mlflow/blob/master/mlflow/experiments.py#L43) before displaying it (even though the artifact location is stored on-disk as `s3://...` - you can verify this by manually inspecting the experiment metadata, e.g. via `cat mlruns/0/meta.yaml`). Will try to repro the issues with the server reading from S3.

**Comment by abaveja313** [comment]
also, I was wondering-- where does the client actually get this artifact URL from. There is a set tracking url method, but no set artifact url method. How can I set this?

**Comment by smurching** [comment]
Ah interesting, I was able to successfully log to S3 & view the artifacts in the UI (on MacOSX). I suspect your default experiment (experiment 0) actually does have a non-S3 artifact_location - would you be able to post the output of `cat mlruns/0/meta.yaml`? Mine looks like:

```
artifact_location: s3://<my-bucket>/0
experiment_id: 0
name: Default
```

Here's what I did to log / view artifacts in S3, would be curious to hear if/how your workflow differed:
* Created an S3 bucket at `<my-bucket>`.
* Verified I could read/write from/to the bucket by running `aws s3 ls s3://<my-bucket>` and `aws s3 cp some-local-file s3://<my-bucket>`.
* Cleared out my local mlruns directory via `rm -r mlruns`
* Created an experiment with an S3 artifact directory via `mlflow experiments create --artifact-root s3://<my-bucket> "S3 backed experiment"`. This created two experiments (experiment 0 and experiment 1, with `artifact_location`s of s3://<my-bucket>/0 and s3://<my-bucket>/1 (we should only create one experiment, but I moved on)
* From my checkout of MLflow, ran an example script that logs metrics/artifacts to S3 via `python example/advanced/test_remote_server.py` (note: this will write small files to your S3 bucket)
* Ran the UI via `mlflow server --host 0.0.0.0` (`mlflow server --host 0.0.0.0 --artifact-root s3://<my-bucket>` also worked).

**Comment by abaveja313** [comment]
Ah. I forgot to create a new experiment. If I do that, it works!!! Thanks so much

**Comment by abaveja313** [comment]
Actually, one more question-- is file-store with S3 supported?

**Comment by smurching** [comment]
Good question, an S3 store doesn't exist yet although it could be interesting to add one (one challenge is I think the performance of e.g. logging metrics might not be great). We have been meaning to add a MySQL store.

**Comment by smurching** [comment]
Also - would you be interested in making a PR to address the (a) list experiments issue ? I think we just need to update [this method](https://github.com/databricks/mlflow/blob/master/mlflow/experiments.py#L43) to not call `os.path.abspath` on URIs, checking if the path is a URI via `mlflow.data.is_uri`.

**Comment by abaveja313** [comment]
Sure. Why don't I take a stab at it and see what I can do! Thanks!

**Comment by smurching** [comment]
Hi @abaveja313, would you mind if I closed this issue? Thanks!
