### ISSUE TITLE
mlflow ui doesnot start on windows

### ISSUE THREAD

**Issue by bb786112** [mlflow/mlflow#1580]
I have successfully installed mlflow on windows but when I want to start **mlflow ui**, It says command not exist. I dont know from where I can start mlflow ui in windows.

Do we have any folder which we need to setup in PATH variable after installing using pip?

Thanks In Advance

**Comment by ankitmathur-db** [comment]
Have you taken a look at https://github.com/mlflow/mlflow/issues/154? Please try those instructions and reopen if that doesn't work for you
