### ISSUE TITLE
log_artifacts and S3 documentation 

### ISSUE THREAD

**Issue by staghvaeeyan** [mlflow/mlflow#1587]
The log_artifacts documentation here seems not be valid anymore. 
https://github.com/mlflow/mlflow/blob/master/docs/source/tracking.rst#referencing-artifacts

mlflow.tracking.log_artifacts returns an error and it seems that this should be changed to mlflow.log_artifacts in the doc.

The documentation for s3 also is not clear. I could not log my models into s3 bucket with the simple 's3://my_bucket/path/to/model' argument example provided int he doc.

**Comment by apurva-koti** [comment]
Could you provide more details on those errors? 
The `log_artifacts` documentation has been updated to correct an inaccuracy, but I can't tell if it's the same error you're getting; the same for S3.

**Comment by apurva-koti** [comment]
Doc fix for log_artifacts is merged in #1589

**Comment by apurva-koti** [comment]
@staghvaeeyan Were you able to resolve the S3 issue?

**Comment by staghvaeeyan** [comment]
@apurva-koti, I found the issue. I ended up directly using S3ArtifactRepository but then had to write a semi-custom log_artifacts as the current method does not accept ExtraArgs when calling upload_file as it is required for some buckets.
