### ISSUE TITLE
Feature Request: Do not use a global _active_run

### ISSUE THREAD

**Issue by Rjdrenth** [mlflow/mlflow#159]
The current version of mlflow uses a global _active_run variable. This makes it very hard to log results from multiple runs in parallel.
This is an issue when multi-threading, but also when you performing an extensive search for optimal (hyper) parameters and data processing settings and you want to minimise the time spent data processing. I.e. looping over your data processing parameters, then over cross-validation folds, then over your ML and last over algorithms + hyper parameters.

I'd much prefer that every single 'with mlflow.start_run() ..' would internally just keep track of a local active run. 

Even if you don't think these good arguments, it is what you simply would expect I think, given that with-statements are very localised and you expect them to have a localised scope; you don't expect them to have global consequences.

**Comment by kepler** [comment]
I agree. It makes it much harder than it's actually implied in the second example here: https://www.mlflow.org/docs/latest/projects.html#building-multi-step-workflows.

**Comment by ankitmathur-db** [comment]
In case this is a problem, does being able to now specify a parent run in start_run, help with this?
