### ISSUE TITLE
Refer to other (utilised) experiment (e.g. feature extraction)

### ISSUE THREAD

**Issue by ptoews** [mlflow/mlflow#1591]
Hi,

first of all, I'm a big fan of MLflow already because of how useful it is.
However, I don't know yet how I can model my two-step pipeline. In the first step, I extract features from my data, and this varies depending on which dataset (and which version) I choose, and of course the parameters for the feature extraction algorithms. I generate a feature file, which I then use for many different classification runs (again with many parameters obviously). These two steps are therefore independent from each other and completely separately executed. 

**Possible existing solutions**

- Stuff the feature extraction parameters into the classification run (as suggested in #25). 
This would require storing them in the first step somewhere near to the feature file, and then loading them during classification to insert them into mlflow. Additionally, the parameters column(s) in the dashboard would become very cluttered. It would also not be possible to store artifacts of the first step, or to add notes about which data I chose.
- Create an experiment for each dataset.
No possibility to add parameters or, again, notes. Also I could not use the experiments feature as it is intended anymore.
- Use nested runs.
This would make a lot of sense, but I could not find out how to choose a specific parent run, and whether it is possible to have a finished run as a parent. Maybe this would even be better than below suggested solution.

**Suggested Solution**

Maybe there is another better way to do it, but this seems to be the simplest to implement. I would make runs for each feature extraction, where I could add all my parameters and notes etc. Then, for classification I would specify a run id of a feature extraction run, let my code extract the feature file from that run's artifacts and do the work. In the dashboard, optimally there would be a column (like a parameter column) where each entry is a clickable link to the feature extraction run, where I can look up all the details.

**Comment by ankitmathur-db** [comment]
Hey! I'd love to discuss how we can help make your use case better supported - correct me if I'm wrong, but you're saying that putting a tag on the run is inconvenient because: (1) it means that when you start your classification run, you have to load the parameters that you used to generate the dataset and (2) the tags would become cluttered in the UI because you have several parameters.

It seems to me that option 2 makes the most sense to me - logically, each new dataset that you're working with should warrant a new experiment and multiple runs under that. Is the biggest problem that you can't add notes and tags to experiments? We're scoping out how we can actually support that kind of use case. What do you mean by you can't use it as intended?

For option 3, you can specify a parent run explicitly when you do `with mlflow.start_run`. How do you feel about that kind of solution?

**Comment by ptoews** [comment]
Yes, it seems very awkward to load all the parameters that were used for feature file generation and attach them to the separate second process. Also it would be difficult to compare all classification runs executed with the same dataset (by querying all params individually).

In general it makes probably a lot of sense to have an experiment per dataset. But here, the feature file is dependent on a chosen dataset as well as chosen feature extraction methods. I would love to be able to compare the performance of the whole pipeline by just modifying e.g. one parameter in the feature extraction step. This would be really cumbersome with multiple experiments.
What I mean with not being able to use it as intended is the missing possibility to use experiments to completely separate runs, e.g. for testing very different strategies or whatever, because I would already be "abusing" the experiments feature to separate datasets.

I tried to specify a parent run as you suggested and made it work like this:
1. use `mlflow.start_run(parent_run_id)` to "continue" the parent run
2. use `mlflow.start_run(nested=True)` no start a nested run with the current run as parent

Is this the proper way to do this? Because I could not find it in the documentation.
However as far as I can tell this is pretty much what I was looking for. I'll see if I miss something, thank you already!

**Comment by ankitmathur-db** [comment]
Yeah that seems reasonable - we should work on documenting it better, but for the time being, our blog post on the feature release has an example that might help! (https://databricks.com/blog/2018/11/21/mlflow-v0-8-0-features-improved-experiment-ui-and-deployment-tools.html)
