### ISSUE TITLE
R API requires different environment variable name for authentication token than Python

### ISSUE THREAD

**Issue by jwpestrak** [mlflow/mlflow#1593]
### Describe the problem
There is an inconsistency about the name of the environment variable used by the R API to authenticate with the tracking service with respect to (at least) the Python API.  The R API uses an environment variable named `MLFLOW_TOKEN` whereas the Python API uses `MLFLOW_TRACKING_TOKEN`.
This inconsistency resulted in some lost time on my part. I first (successfully) used the Python API to familiarize myself with the tracking component, and then tried the R API but received "invalid token" errors.  Only after `grep`ing through the code base did I discover the difference.

### Source code / logs
The latest commit of the source code I used is 
f2d13fc13634081a907de422f9aefb2b1f3b71d9

**Comment by tomasatdatabricks** [comment]
Nice catch @jwpestrak, thanks for posting! This will be fixed in the upcoming release.
