### ISSUE TITLE
Does Java API support MLflow models?

### ISSUE THREAD

**Issue by FredYao** [mlflow/mlflow#1595]
In MLflow models, there are bunch of Python APIs for supporting model loading/saving for multiple Machine Learning frameworks (e.g., SKLearn, PyTorch, TensorFlow).

Is ml model loading/saving only done using the Python APIs?
 
Does the Java API also support such functionalities? 

Thanks!

**Comment by ankitmathur-db** [comment]
We don't currently have support for the Java API outside of tracking

**Comment by Christos-Hadjinikolis** [comment]
Has this changed?
