### ISSUE TITLE
[Feature request] Support for tracking using NoSQL (eg mongodb)

### ISSUE THREAD

**Issue by ahmed-shariff** [mlflow/mlflow#1597]
If would be phenomenal if I can store my meta data using mongodb.

**Comment by drorata** [comment]
@ahmed-shariff do mean you want to be able to provide `--backend-store-uri` with a mongodb?

**Comment by ahmed-shariff** [comment]
Something along those lines, yeah

**Comment by tomasatdatabricks** [comment]
Thank you for submitting this. This would be an interesting feature, however, we are not planning to add support for nosql stores to mlflow-core at this point in time. You can develop this as a plugin but we can not commit to maintaining it right now.

**Comment by Pushpalathahareesh** [comment]
satyamajay: the plug in from ur github not getting installed nor working, if u have tried thenpls post proper steps ehere to use with mlflow
