### ISSUE TITLE
[Feature request] Support for more advanced search in UI

### ISSUE THREAD

**Issue by ahmed-shariff** [mlflow/mlflow#1598]
Allow more advanced searches:
- Partial string matching (`in` operator?)
- Regex support
- Allow searching notes

**Comment by jdlesage** [comment]
I am also interested by partial string matching. I am thinking to add LIKE operator + % (SQL equivalent syntax)
Also, I suggest to allow also the search on run name.

If I understand correctly the code, currently the filter is done in python. I am wondering if we can delegate it to sqlalchemy. It will be faster and enables to have all the expressiveness of SQL language.

**Comment by Nithanaroy** [comment]
Looks like we can search by run name like so,
```sql
tag."mlflow.runName" = "my run name"
```
Other things that may work are https://www.mlflow.org/docs/latest/tracking.html#system-tags

**Comment by jcuquemelle** [comment]
On the same topic, from what I understand searching on attributes has been restricted in favor of searching on tags (https://github.com/mlflow/mlflow/issues/983).

I do understand that it might be cumbersome to add new attributes to the run_info, however is it really necessary to convert the existing ones to tags ? I guess it is normal to have a minimal set of metadata in each run, plus tags can be modified or removed (and this might invalidate the reproduceability of an experiment) which is not the case with attributes.
This duplicates data, complexifies search in databases (one join for each filter/ordering clause on tags vs no joins for attributes) and is less intuitive ('attribute.runName' vs 'tags."mlflow.runName"').

**Comment by devstein** [comment]
@jdlesage We've also been wanting to use partial string matching (`LIKE` operator) in our searches. After reading through the [search code](https://github.com/mlflow/mlflow/blob/7779b87540ea57ec56d1b7ac42e420a6a6f9df23/mlflow/utils/search_utils.py#L20-L21), it looks like it is supported. I ran the following query via the UI and it appears to work:

```
tags."mlflow.runName" like "some-name-prefix%"
```

Does anyone know why this feature undocumented?

**Comment by t-henri** [comment]
Hello, I developed the feature some time ago and it is indeed possible to search using the LIKE operator.
But you're right I forgot to add documentation, I will do a PR to add it.
