### ISSUE TITLE
How to configure artifactory repo while creating conda environment with mlflow

### ISSUE THREAD

**Issue by sivakumarl** [mlflow/mlflow#1612]
Hi Friends,
   I am using mlflow of version 1.0.0 , when I was using MLProject , mlflow is trying to conda environment but unfortunately we working behind proxy , so unfortunately mlflow trying to connect anaconda repo instead of using the channels from condarc file which i have configured, so please let me know how to use or configure artifactory while creating conda environment with mlflow.

Thanks 
Siva Kumar

**Comment by nlaille** [comment]
Hi,

Is it working if you specify your artifactory repository as a channel in your conda environment.yaml ?

**Comment by sivakumarl** [comment]
Hi nlaille,
      I am able to fix the issue by adding the artifactory channels in conda.yml . Thanks

Siva Kumar
