### ISSUE TITLE
Artifact preview not working for uppercase extentions

### ISSUE THREAD

**Issue by Stannislav** [mlflow/mlflow#1618]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 LTS

- **MLflow installed from (source or binary)**: binary (pypi)
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: Python 3.6.8

### Describe the problem
Take an image file, e.g. `image.jpg` and copy it to the artifacts folder of one of the runs. Run `mlflow ui` and verify that the image is rendered in the artifacts view.

Change the extension of the image file to upper case, e.g. change `image.jpg` to `image.JPG` and refresh the artifacts view in the mlflow UI. The image is not rendered any more.

**Comment by ankitmathur-db** [comment]
Fixed - thanks for reporting!
