### ISSUE TITLE
Proposal to create extra cli sub-command for generate Dockerfile.

### ISSUE THREAD

**Issue by andriisoldatenko** [mlflow/mlflow#1619]
### Describe the problem
What do you think about create extra sub-command generate Dockerfile, instead of hardcode it in source code https://github.com/mlflow/mlflow/blob/deeb7f0f753fd9af228917675e4020eeb6a53668/mlflow/models/docker_utils.py#L16
E.g.
```
mlflow models gen-build-docker -m s3:// 
or similar
```
and than you can use this Dockerfile in CI or for development?

Pls feel free share any feedback.

**Comment by LarsDu** [comment]
Hell yes! 👍 💯

**Comment by andychow-db** [comment]
We added some support to build a docker image using the sagemaker subcommand. See the docs [here](https://www.mlflow.org/docs/latest/python_api/mlflow.sagemaker.html) for more information.

Please repoen and @ me if it does not work for your use case.
