### ISSUE TITLE
[Feature request] Support the ability to only show finished experiments

### ISSUE THREAD

**Issue by LeanderK** [mlflow/mlflow#1620]
A constant problem for me is that the mlflow-UI is full of crashed or canceled experiments (I do a bit more esoteric stuff than just training CNNs and have a lot of custom code), but most of the time I am only interested in querying and comparing finished experiments. A button to only display these would really help, as i understood it the information is already available in the backend.

I have already disabled mlflow during development, but there are still a lot of crashed/cancelled runs in my logs.

**Comment by mparkhe** [comment]
You can put this string in the `Search Expression` field.

```
attributes.status = "FINISHED"
```

This will filter runs using status field.

![image](https://user-images.githubusercontent.com/6900999/61576736-5df81f80-aa92-11e9-92e9-aba0855594dd.png)

You can do this for "KILLED", "FAILED", "RUNNING" ... etc status fields as well. More details on [search](https://mlflow.org/docs/latest/search-syntax.html).

**Comment by LeanderK** [comment]
Thanks, I did not know that!

I would still prefer a button because it does not seem very user-friendly. I'll leave the issue open, but you can close it if you disagree.

**Comment by aarondav** [comment]
Let's close this one and refer to #1380 for the ability to sort on run status.

**Comment by LeanderK** [comment]
i overlooked the already existing ticket. Thanks!
