### ISSUE TITLE
Under what circumstances, hyperopt will be __exit__() after a round of max-runs, not the next round of training？

### ISSUE THREAD

**Issue by lyw615** [mlflow/mlflow#1623]
### Describe the problem
All followings  are the log of pdb debug,  and I can't find out which part of the link has caused the error. The value of metrics are normal. There is no error report during training.
/home/do/lyw/mlflow_x/Semantic-Segmentation-Suite-master/seg_search.py(69)run()
-> max_evals=max_runs)
(Pdb) n
--Return--
> /home/do/lyw/mlflow_x/Semantic-Segmentation-Suite-master/seg_search.py(69)run()->None
-> max_evals=max_runs)
(Pdb) n
--Call--
> /software/conda/lib/python3.6/site-packages/click/core.py(348)__exit__()
-> def __exit__(self, exc_type, exc_value, tb):
(Pdb) n
> /software/conda/lib/python3.6/site-packages/click/core.py(349)__exit__()
-> self._depth -= 1
(Pdb) n
> /software/conda/lib/python3.6/site-packages/click/core.py(350)__exit__()
-> if self._depth == 0:
(Pdb) n
> /software/conda/lib/python3.6/site-packages/click/core.py(352)__exit__()
-> pop_context()
(Pdb) n
--Return--
> /software/conda/lib/python3.6/site-packages/click/core.py(352)__exit__()->None
-> pop_context()
(Pdb) n
--Call--
> /software/conda/lib/python3.6/contextlib.py(85)__exit__()
-> def __exit__(self, type, value, traceback):
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(86)__exit__()
-> if type is None:
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(94)__exit__()
-> if value is None:
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(98)__exit__()
-> try:
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(99)__exit__()
-> self.gen.throw(type, value, traceback)
(Pdb) n
Warning: Unknown argument(s): {'postfix': 'best loss: ?'}
> /software/conda/lib/python3.6/contextlib.py(99)__exit__()
-> self.gen.throw(type, value, traceback)
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(100)__exit__()
-> except StopIteration as exc:
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(105)__exit__()
-> except RuntimeError as exc:
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(115)__exit__()
-> except:
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(123)__exit__()
-> if sys.exc_info()[1] is value:
(Pdb) n
> /software/conda/lib/python3.6/contextlib.py(124)__exit__()
-> return False
(Pdb) n
--Return--
> /software/conda/lib/python3.6/contextlib.py(124)__exit__()->False
-> return False
(Pdb) n
--Call--
> /software/conda/lib/python3.6/site-packages/click/core.py(348)__exit__()
-> def __exit__(self, exc_type, exc_value, tb):
(Pdb) n
> /software/conda/lib/python3.6/site-packages/click/core.py(349)__exit__()
-> self._depth -= 1
(Pdb) n
> /software/conda/lib/python3.6/site-packages/click/core.py(350)__exit__()
-> if self._depth == 0:
(Pdb) n
> /software/conda/lib/python3.6/site-packages/click/core.py(351)__exit__()
-> self.close()
(Pdb) n
> /software/conda/lib/python3.6/site-packages/click/core.py(352)__exit__()
-> pop_context()
(Pdb) n
--Return--
> /software/conda/lib/python3.6/site-packages/click/core.py(352)__exit__()->None
-> pop_context()
(Pdb) 
Warning: Unknown argument(s): {'postfix': 'best loss: ?'}
> /home/do/lyw/mlflow_x/Semantic-Segmentation-Suite-master/seg_search.py(91)<module>()
-> run()
(Pdb) n
--Return--
> /home/do/lyw/mlflow_x/Semantic-Segmentation-Suite-master/seg_search.py(91)<module>()->None
-> run()
(Pdb) n
Warning: Unknown argument(s): {'postfix': 'best loss: ?'}
> <string>(1)<module>()->None
(Pdb) n
--Return--
> <string>(1)<module>()->None
(Pdb) n
Traceback (most recent call last):
  File "/software/conda/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/software/conda/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/software/conda/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/do/lyw/mlflow_x/Semantic-Segmentation-Suite-master/seg_search.py", line 91, in <module>
    run()
  File "/software/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/software/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/software/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/software/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/do/lyw/mlflow_x/Semantic-Segmentation-Suite-master/seg_search.py", line 69, in run
    max_evals=max_runs)
  File "/software/conda/lib/python3.6/site-packages/hyperopt/fmin.py", line 407, in fmin
    rval.exhaust()
  File "/software/conda/lib/python3.6/site-packages/hyperopt/fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/software/conda/lib/python3.6/site-packages/hyperopt/fmin.py", line 198, in run
    disable=not self.show_progressbar, dynamic_ncols=True,
  File "/software/conda/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 427, in __init__
    Warning("Unknown argument(s): " + str(kwargs)))
Warning: Unknown argument(s): {'postfix': 'best loss: ?'}
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /software/conda/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py(427)__init__()
-> Warning("Unknown argument(s): " + str(kwargs)))

### Source code / logs
 ```python
def run(training_data,max_runs,epochs,metric,algo):#params in evaluate process
    tracking_client=mlflow.tracking.MlflowClient()#a manage client
    def new_eval(nepochs,experiment_id,
                 null_valid_loss,null_test_loss,return_all=False):#target function,input params
        def eval(params):
            import mlflow.tracking
            learning_rate,decay_p=params
            with mlflow.start_run(nested=True) as child_run:
                p=mlflow.projects.run(uri='.',entry_point='train',
                    run_id=child_run.info.run_id,
                    parameters={'training_data':training_data,'epochs':str(nepochs),'learning_rate':str(learning_rate),
                                'decay_p':str(decay_p)},experiment_id=experiment_id,use_conda=False)
                succeded=p.wait()
            if succeded:
                training_run=tracking_client.get_run(p.run_id)
                metrics=training_run.data.metrics
                #due to  the data.metrics format,notice minus,all of this value should be negative number except first epoch
                #train_loss=min(null_train_loss,metrics['train_{}'.format(metric)])
                valid_loss=min(null_valid_loss,metrics['val_{}'.format(metric)])
                test_loss=min(null_test_loss,metrics['test_{}'.format(metric)])
                if valid_loss<0:
                    valid_loss=-valid_loss
                if test_loss<0:
                    test_loss=-test_loss
            else:
                tracking_client.set_terminated(p.run_id,'FAILED')
                #train_loss=null_train_loss
                valid_loss=null_valid_loss
                test_loss=null_test_loss
            mlflow.log_metrics({
                #'train_{}'.format(metric):train_loss,
                'val_{}'.format(metric):valid_loss,
                'test_{}'.format(metric):test_loss
            })
            if return_all:
                return valid_loss,test_loss
            else:
                return valid_loss
        return eval
    #find the best group for such hyperparams in specify space
    space=[hp.uniform('learning_rate',1e-5,1e-1),
           hp.uniform('decay_p',.0,1.0)]
    with mlflow.start_run() as run:#parent run
        experiment_id=run.info.experiment_id
        #evaluate null model first
        valid_null_loss,test_null_loss=new_eval(1,experiment_id,_inf,_inf,True)(params=[1e-3,0.995])
        best=fmin(fn=new_eval(epochs,experiment_id,valid_null_loss,test_null_loss),
                  space=space,algo=tpe.suggest if algo== 'tpe.suggest' else  rand.suggest,
                  max_evals=max_runs)
        mlflow.set_tag('best params',str(best))
        client=MlflowClient()
        runs=client.search_runs([experiment_id],"tags.mlflow.parentRrunId='{run_id}'".format(
            run_id=run.info.run_id
        ))
        #best_val_train=_inf
        best_val_valid=_inf
        best_val_test=_inf
        best_run=None
        for r in runs:
            if r.data.metrics['val_avg_precision']<best_val_valid:
                best_run=r
                #best_val_train=r.data.metrics['train_avg_precision']
                best_val_valid=r.data.metrics['val_avg_precision']
                best_val_test=r.data.metrics['test_avg_precision']
        mlflow.set_tag('best_run',best_run.info.run_id)
        mlflow.log_metrics({
            'train_{}'.format(metric):best_val_valid,
            'val_{}'.format(metric):best_val_test
        })
if __name__=='__main__':
    run()
```

**Comment by ankitmathur-db** [comment]
It looks like the postfix argument was added to tqdm in 4.11, and you seem to have 4.7. Did you install tqdm separately?

**Comment by lyw615** [comment]
Yeah,the the problem is on the version of tqdm.When i execute the command " conda  install hyperopt",got the such reply:

The following NEW packages will be INSTALLED:
    hyperopt: 0.1.2-py_0   https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
    tqdm:     4.7.2-py36_0 https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
It's obvious the version of tqdm is  lower .But when i   install hyperopt by pip, it shows "hyperopt (0.1.2) tqdm (4.32.2) ".Therefore, uninstalling hyperopt re-installed the high version of hyperopt and tdqm via pip to solve the problem.
