### ISSUE TITLE
Mlflow ui not working on windows "Even after trying the replace-gunicorn-with-waitress" update

### ISSUE THREAD

**Issue by SaadAhmed96** [mlflow/mlflow#1637]
I have looked at the different issues (especially this one #1080 ) to resolve the problem of getting mlflow ui working for windows. 

OS Specs: Windows 8.1 64 bit
Python version 3.7.1 (Installed Using Anaconda)
mlflow versions installed 1.0.0

Here is what I have done so far

-Uninstalled the PyPI version by doing `pip uninstall mlflow`

-Installed mlflow from this [link](https://github.com/akshaya-a/mlflow/tree/ak/replace-gunicorn-with-waitress) using this command from the anaconda command prompt `pip install git+https://github.com/akshaya-a/mlflow.git`

-Successfully installed mlflow flow but still `mlflow ui` doesnot work  giving ModeulNotFoundError (Picture is attached)

I am new to git and somewhat of a beginner so kindly while providing any solution mention the exact steps.

![image](https://user-images.githubusercontent.com/30757857/61518826-eee3e200-aa23-11e9-99ae-796087f00a70.png)

**Comment by apurva-koti** [comment]
Hey Saad,

This was also discussed in #1611 - a fix for this will be coming in MLflow 1.1. Keep a look out for that and thanks for filing the issue.

**Comment by ankitmathur-db** [comment]
Please try this again with MLFlow 1.1 and reopen if the issue persists!
