### ISSUE TITLE
Dose mlflow support git version control，How was it implemented?

### ISSUE THREAD

**Issue by lyw615** [mlflow/mlflow#1644]
### Describe the problem
I understand that information about git version control is just like "mlflow.source.git.commit". Any other relevant information or instructions?

**Comment by hamroune** [comment]
I thins you should try this, it works well for me

`mlflow.tracking.fluent.context._get_source_version() `

**Comment by lyw615** [comment]
Is this a version control method for python files pushed to github? How do I view historical version records or get a specific version? Can you provide detailed instructions if you are convenient?


------------------ 原始邮件 ------------------
发件人: "hamroune zahir"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 下午5:04
收件人: "mlflow/mlflow"<mlflow@noreply.github.com>;
抄送: "百多达"<931253898@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mlflow/mlflow] Dose mlflow support git version control，How was it implemented? (#1644)




I thins you should try this, it works well for me
 
mlflow.tracking.fluent.context._get_source_version()

**Comment by ankitmathur-db** [comment]
Hi @lyw615, issues are more for real problems with the project as opposed to help needed. We're happy to help though! See this section from the README on places you'll more easily be able to engage in a back and forth discussion to help you use MLFlow:

> To discuss MLflow or get help, please subscribe to our mailing list (mlflow-users@googlegroups.com) or join us on Slack at https://tinyurl.com/mlflow-slack.

>
