### ISSUE TITLE
[Feature request] Support to filter on start_time and end_time column in UI

### ISSUE THREAD

**Issue by wegamekinglc** [mlflow/mlflow#1645]
Currently the expresion in UI doesn't support filter on column `Date`. I think it is very useful for user to do some filter on this field.

**Comment by Zangr** [comment]
@wegamekinglc Thank you for submitting the FR, this makes sense. We will consider it in recent planning.

**Comment by wegamekinglc** [comment]
> @wegamekinglc Thank you for submitting the FR, this makes sense. We will consider it in recent planning.

Great thanks. I m looking forward to it~

**Comment by fernandorovai** [comment]
Please, do we have a way to query the entries by date?

**Comment by dbczumar** [comment]
Closing this out, as this capability is now available. Thanks folks!
