### ISSUE TITLE
Adding custom models to docker environment 

### ISSUE THREAD

**Issue by code-blooded245** [mlflow/mlflow#1651]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution**: ubuntu 18.04 bionic beaver
- **MLflow installed from**: using pip3  
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6.8

### Description
I have created a custom model using mlflow.pyfunc.log_model() and also I have deployed it using the **mlflow models serve** command, but now I want to add the same thing in a docker and deploy the docker image, but I couldn't sync the custom model with the given environment of mlflow for docker utility. I used the following command,

**$sudo mlflow models build-docker -m ./mlruns/0/abc123abc/artifacts/model/ -n test_image**

I get the following error,
**ModuleNotFoundError: No module named 'custom_model'**

**Comment by ankitmathur-db** [comment]
Is this similar to #1291 ?

**Comment by code-blooded245** [comment]
Yeah, it is similar, but I don't see any solution for that particular issue.

**Comment by vivian-usc-2009** [comment]
Hi @code-blooded245 , is this problem solved? I am facing the same issue and would like to see your solution. Thanks!

**Comment by dbczumar** [comment]
The https://mlflow.org/docs/latest/cli.html#mlflow-models-build-docker CLI addresses this issue.
