### ISSUE TITLE
How to run Jupyter Notebook (ipynb) examples from the command line?

### ISSUE THREAD

**Issue by SaadAhmed96** [mlflow/mlflow#1652]
Hi, I am trying to run the train.ipynb file located inside sklearn_elasticnet_wine folder but it is giving me the following error (picture attached). Am I doing it the wrong way? kindly suggest how can I resolve this issue.
OS: Win 8.1
![image](https://user-images.githubusercontent.com/30757857/61696879-8e201680-ad4f-11e9-87e4-3cd313fa4178.png)

**Comment by ankitmathur-db** [comment]
Jupyter notebooks are a really nice notebook interface that people often use to organize their examples and experiments in Python - I would recommend learning about them [here](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/what_is_jupyter.html). That link will also teach you how to run a Jupyter notebook.

If you want to just try the example without that, then you should just use the `train.py` file located in the same folder.
