### ISSUE TITLE
[Feature request] Highlight parameters diff in run comparison

### ISSUE THREAD

**Issue by johny-c** [mlflow/mlflow#1653]
### Feature request.

It would be useful, when doing a run comparison, to highlight the parameters/lines, where runs differ (like git diff). That would save a lot of time for runs that have many (hyper-)parameters.

**Comment by rquintino** [comment]
would be great
related some others could be evaluated:
able to put params with diff on top
color metrics, bold best one,etc
(although probably for that we would need an option for identifying default metric and direction)

**Comment by fzyzcjy** [comment]
+1

**Comment by AgrawalAmey** [comment]
Looks like this is already resolved in https://github.com/mlflow/mlflow/pull/2565
