### ISSUE TITLE
[Feature request] Re-introduce host option in mlflow ui

### ISSUE THREAD

**Issue by petibear** [mlflow/mlflow#1654]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Cloudera Data Science Workbench with Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: `pip3 install mlflow`
- **MLflow version (run ``mlflow --version``)**: `1.1.0`
- **Python version**:  `3.6.1`
- **npm version (if running the dev UI): not using npm
- **Exact command to reproduce**: `mlflow ui -p 8080`

### Describe the problem
mlflow version 1.0.0 removed `--host` argument (PR #1267). The reasoning was that mlflow ui was intended only for simple local use-cases and that for anything else one should use mlflow server. That's understood, however in my environment (Cloudera Data Science Workbench) the simple use-case still requires to change host name, otherwise I cannot get to see the UI (that would be running on a different host than the browser I access the "workbench" from). 

I'm trying to use mlflow in a very simple way just to track metrics saved in a local directory (or sqllite db), I don't want to spin up a server for that unnecessarily. In order to access mlflow ui running on a CDSW I need to open http server at port `8080` (cf. [Cloudera documentation](https://www.cloudera.com/documentation/data-science-workbench/latest/topics/cdsw_web_ui.html)) however with host set to `0.0.0.0` . The latter is [hard-coded](https://github.com/mlflow/mlflow/blob/3861af2c148a4259be969af12211aeb0e8815659/mlflow/cli.py#L198) to 127.0.0.1 in `cli.py` since PR #1267. Altering the hard-code to `0.0.0.0` made me see the UI. 

Could we re-introduce the option of setting up host also with mlflow ui, please? There are "simple" (sort of local) use-cases that would still benefit from it.

**Comment by smurching** [comment]
@petibear would it be possible to satisfy your use case by running `mlflow server` from within CDSW? It should be just as easy to do that as to run `mlflow ui`, AFAICT. Will close for now but please reopen if something comes up or that doesn't work out, thanks!

**Comment by petibear** [comment]
@smurching I finally tried, and yes, tracking using an mlflow server launched with `mlflow server --host 0.0.0.0 -p 8080` is indeed quite easy within CDSW. UI is accessible too. So nothing really needed here. Thanks !

**Comment by meechos** [comment]
@petibear, could you please elaborate on how you can view the UI when `mlflow` is running on` cdsw`? I am experiencing the same issue. Many thanks

**Comment by petibear** [comment]
@meechos 
I know of two ways of tracking your runs within CDSW. Either directly locally or against an mlflow server (that too can run locally, but can be also elsewhere). 

__Local Tracking__
You simply start tracking in your Python code with `mlflow.start_run()`. To inspect the tracked items, you then launch MLflow UI separately from (CDSW) terminal. You can launch it before, during or after tracking.  In CDSW, it needs to be launched to listen on `0.0.0.0` and on a specific port (typically `8080`; see [CDSW documentation](https://docs.cloudera.com/documentation/data-science-workbench/1-6-x/topics/cdsw_embedded_web_apps.html#ml_frameworks) and inspect the corresponding environmental variables in your installation). When launched, you can see the UI from outside CDSW at `http://<$CDSW_ENGINE_ID>.<$CDSW_DOMAIN>` (or perhaps something else depending on your setup).

Since #2176 added  `host` option back to MLflow UI, launching it in CDSW should be as easy as running `mlflow ui -p 8080 -h 0.0.0.0` in CDSW terminal (but see the note below). 

(In older versions `127.0.0.1` was hardcoded in [mlflow/cli.py](https://github.com/mlflow/mlflow/blob/master/mlflow/cli.py) in a call to `_run_server()`, so I needed to change it to `0.0.0.0` in `cli.py` inside my mlflow installation)

__Tracking against an mlflow server__
You first launch a server and then track against it. I launch server locally within my CDSW session's terminal with e.g. `mlflow server --backend-store-uri sqlite:///mlflow_tracking_server.db  --default-artifact-root file:///path/to/mflow_bucket/ 
  -p 8080 --host 0.0.0.0`. Once launched, you then "connect" to it from Python by setting tracking uri `mlflow.set_tracking_uri("http://127.0.0.1:8080")` before `mlflow.start_run()` . 

Server UI is then again available at `http://<$CDSW_ENGINE_ID>.<$CDSW_DOMAIN>`.

__(my) Recommendation__
I believe that tracking against a server is a better way as it gives you more flexibility and also more options. It is conceptually cleaner (i.e. you follow client/server model) and it is also the recommended way. So, I would recommend to consider tracking with a server (albeit a local one) instead of a direct local tracking. 

_Note_:
In my case, I also needed to expand `PATH` to include the directory with gunicorn binary. `pip install mlflow` in my case raises a warning if that needs to be done, so read carefully its output. I have to do it with both alternatives.
