### ISSUE TITLE
[Feature Request] Passing additional POST information to scoring_server

### ISSUE THREAD

**Issue by LarsDu** [mlflow/mlflow#1655]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **Linux Ubuntu 18.04**:
- **MLflow installed from (source or binary)**: 
- **MLflow version 1.0.0**:
- **Python 3.7**: 
- **`mlflow models serve`**:

### Describe the problem
Right now when using `mlflow models serve`, we can pass data to the service using a command like:
`curl -X POST -H 'Content-Type: application/json; format=pandas-records' --data '{}' http://127.0.0.1:5000/invocations`

Where the "--data" has to be of type pandas.DataFrame, pandas.Series, or numpy array.

I was interested in sending additional data to mlflow.pyfunc.PythonModel.predict() method. For example, a string flag on what type of thresholding should be used for the .predict() output.

At the moment, it seems there is no way to do this (correct me if I am wrong). I believe it would be nice to be able to extract the header data directly in PythonModel, or provide means to pass additional flags.

**Comment by LarsDu** [comment]
For now, one hacky way to do this is by providing a column in the input array or dataframe with one cell that contains a string containing all flags.

**Comment by DOH-WLD0303** [comment]
Reviving this thread as I think it would be an incredibly useful feature where I currently work. We're currently leveraging the Databricks hosted MLflow instance and being able to pass in additional header content would allow for more flexible model pipelines. The use case I have been investigating is record linkage and having the ability to signal which dataset is being used and how to treat it or which model to select for that particular dataset would be incredibly helpful.

This is a feature that I'd love to contribute but could use a little guidance on. @zhidongqu-db, would you be able to point me in the right direction with this? I understand that it's a Flask application, what I'm not clear on is the entry point to the model itself when a post request comes in.
