### ISSUE TITLE
Assume IAM Role in another account to store MLFlow Artifact on S3 bucket

### ISSUE THREAD

**Issue by Behel** [mlflow/mlflow#1662]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks with DBR 5.4 Conda Beta
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**: 3.7.0

### Describe the problem
I have to save my MLFlow artifacts (using Databricks Unified Analytics) to a S3 bucket, with service-side encrpytion using a custom KMS key.

My instances are into an AWS account A, my S3 bucket and my KMS key into an account B. I can't have my KMS Key into my account A.

I don't want to use DBFS to mount S3 buckets, for security reasons (buckets can contains sensitive data and I don't want to share this between users).

I have to assume an IAM role in the account B order to access the bucket, as I did to access it through s3a (with `spark.hadoop.fs.s3a.credentialsType` and `spark.hadoop.fs.s3a.stsAssumeRole.arn` parameters).

### Source code / logs
When I create an experiment with s3 and try to log a model like this : 
```python
import mlflow
import mlflow.sklearn
id_exp = mlflow.create_experiment("/Users/first.last@company.org/Experiment",'s3://s3-bucket-name/')
with mlflow.start_run(experiment_id=id_exp):
  clf_mlf = tree.DecisionTreeClassifier()
  clf_mlf = clf_mlf.fit(X_train, y_train)
  y_pred = clf_mlf.predict(X_test)
  mlflow.sklearn.log_model(clf_mlf, "model", serialization_format='pickle')
```

I have this error : 
```
S3UploadFailedError: Failed to upload /tmp/tmp2yl2olhi/model/conda.yaml to s3-bucket-name//05c17a33a33d46a5ad3cc811a9faf35a/artifacts/model/conda.yaml: An error occurred (KMS.NotFoundException) when calling the PutObject operation: Key 'arn:aws:kms:eu-central-1:account_a_id:key/key_id' does not exist
```

How can I told MLFlow to assume a role on another AWS account before accessing to S3 ?

**Comment by dbczumar** [comment]
@Behel Are you attaching an IAM role in Account B to your Databricks cluster (https://docs.databricks.com/administration-guide/cloud-configurations/aws/iam-roles.html#iamroles)?

`s3://s3-bucket/` refers to a bucket in Account B, right?

**Comment by Behel** [comment]
Yes, the S3 Bucket is in the account B.
According to my Cloud Architect, I can't attach IAM Role from account B, only from account A, among other things for safety. But my account B Role can be assumed from my account A (as I did with s3a). 
I'll ask him if I can do this, but it may be only a workaround, not not our target architecture

**Comment by mrwillihog** [comment]
I think this needs to go here:

https://github.com/mlflow/mlflow/blob/master/mlflow/store/artifact/s3_artifact_repo.py#L26-L29

Perhaps we could allow another environment variable and if it's present we assume the role? 

Perhaps, something like this:

```
    def _get_s3_client_with_assumed_role(self, iam_role, s3_endpoint_url):
        sts = boto3.client('sts')
        assumed_role_object = sts_client.assume_role(
            RoleArn=iam_role,
            RoleSessionName="MLFlow"
        )
        credentials = assumed_role_object['Credentials']
        return s3_resource = boto3.client(
            's3',
            aws_access_key_id=credentials['AccessKeyId'],
            aws_secret_access_key=credentials['SecretAccessKey'],
            aws_session_token=credentials['SessionToken'],
            endpoint_url=s3_endpoint_url
        )

    def _get_s3_client(self):
        import boto3
        s3_endpoint_url = os.environ.get('MLFLOW_S3_ENDPOINT_URL')
        s3_assume_role_iam = os.environ.get('MLFLOW_S3_ASSUME_ROLE_IAM')

        if s3_assume_role:
            return _get_s3_client_with_assumed_role(s3_assume_role_iam, s3_endpoint_url)
        else:
            return boto3.client('s3', endpoint_url=s3_endpoint_url)
```

Following this guide: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-api.html

Not 100% happy with having to specify the env variable as it isn't particularly flexible.

**Comment by weldpua2008** [comment]
Hi @Behel 
I have [PR#2461](https://github.com/mlflow/mlflow/pull/2461)  which should allow MLFlow client to store artifacts from another AWS account than MLFlow server. I have even docker-compose MVP for such use-case.  
The bucket policy `aws s3api --profile sandbox get-bucket-policy --bucket mlflow-test-acl-bucket| jq -r .Policy |jq .`
```
{
  "Version": "2012-10-17",
  "Id": "Policy1582321859566",
  "Statement": [
    {
      "Sid": "Stmt1582321857124",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::mlflow-test-acl-bucket/*",
        "arn:aws:s3:::mlflow-test-acl-bucket"
      ],
      "Condition": {
        "ArnEquals": {
          "aws:PrincipalArn": "arn:aws:iam::AWS_PROFILE_ID:user/AWS_USER"
        }
      }
    }
  ]
}

```

**Comment by andychow-db** [comment]
Hi @Behel 

My advice as follows:

### Given
Account A - The account using the S3 bucket but does not have ownership of the S3 bucket
Account B - The account owning the S3 bucket.

### Problem
S3 allows Account B to own an S3 bucket and Account A to own the object within the S3 bucket. Therefore, when Account A uploads an object to S3, it will fail because it tries to use Account A's KMS key. 

### Solution A (Recommended)
Account B should provide Account A with an IAM role that has access to the S3 bucket and a KMS key. The S3 bucket and KMS key should be both owned by Account B. Account A should assume that IAM role. 

### Solution B 
When uploading to S3, the API contract allows the client to specify S3 specific ACLs. This ACL gives Account B ownership of object. Therefore the S3 object can be uploaded.

**Comment by granturing** [comment]
I've had similar issues of wanting to customize the boto3 session. For now, until an official option is available you could override the default S3ArtifactRepository to do the cross-account assume role:

```
from mlflow.store.artifact.s3_artifact_repo import S3ArtifactRepository

class MyS3ArtifactRepository(S3ArtifactRepository):
  def _get_s3_client(self):
    # build client here
    return client

from mlflow.store.artifact.artifact_repository_registry import _artifact_repository_registry

_artifact_repository_registry.register("s3", MyS3ArtifactRepository)
```

**Comment by vaisakhpisharody** [comment]
> I've had similar issues of wanting to customize the boto3 session. For now, until an official option is available you could override the default S3ArtifactRepository to do the cross-account assume role:
> 
> ```
> from mlflow.store.artifact.s3_artifact_repo import S3ArtifactRepository
> 
> class MyS3ArtifactRepository(S3ArtifactRepository):
>   def _get_s3_client(self):
>     # build client here
>     return client
> 
> from mlflow.store.artifact.artifact_repository_registry import _artifact_repository_registry
> 
> _artifact_repository_registry.register("s3", MyS3ArtifactRepository)
> ```

I also came across this issue, and I just had some queries on this.
This solution would work only in cases where we add `mlflow` as a python dependency right? This won't be helpful in cases where we run `mlflow server` and we need to have the boto3 client assume roles? Please let me know in case I am missing something here.

That said, is there any way we could have something similar to [this solution](https://github.com/mlflow/mlflow/issues/1662#issuecomment-558574996), or, any reason why this solution has not been considered?

I apologize if I missed out on any hints/points in between.

**Comment by vaisakhpisharody** [comment]
Hi @dbczumar 

Sorry for tagging you here directly, but I wanted to know if there are any plans of getting this out in the next version?
I would be happy to add a PR with [this](https://github.com/mlflow/mlflow/issues/1662#issuecomment-558574996) change if that is an acceptable solution.

The solution by @andychow-db would also work, but that can only be done when we are using `mlflow` as a python dependency and not while running the server itself, right? The solution by @mrwillihog seems to be something that would work for all the cases (we did the same thing for our internal company codebase, where we initialize the boto3 client directly)

Please let me know if I missed something here.

Thanks,
Vaisakh Pisharody

**Comment by vladiceanu** [comment]
Hi folks,
we're also looking forward to IAM Role assume option and keen to help with the change to the code. 

If anyone works on this already, we would love to support all methods of assuming IAM Roles, [plain](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html#STS.Client.assume_role), [assume_role_with_saml()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html#STS.Client.assume_role_with_saml), and especially the [assume_role_with_web_identity()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html#STS.Client.assume_role_with_web_identity) ❤️  for EKS/GKE users. 

Please let me know if you need any help with the implementation or testing. Cheers

**Comment by zomri** [comment]
For whoever is looking for solution for this... 
After trying out solving using environment variables (to no avail), we found a rather good workaround without changing mlflow code itself - call the following function to assume role and update the default boto3 session (which mlflow uses in it's s3 client):

def assume_role():
    client = boto3.client("sts")
    assumed_role_object = client.assume_role(
        RoleArn=<your role arn string>,
        RoleSessionName=<your role session name string>,
    )
    credentials = assumed_role_object["Credentials"]

    # setting default session with aws keys - will be used internally in mlflow
    boto3.setup_default_session(
        aws_access_key_id=credentials["AccessKeyId"],
        aws_secret_access_key=credentials["SecretAccessKey"],
        aws_session_token=credentials["SessionToken"],
    )

**Comment by dbczumar** [comment]
Given that https://github.com/mlflow/mlflow/issues/1662#issuecomment-939995591 appears to be an excellent solution to this problem, I'm going to go ahead and close this issue. Please feel free to reopen it if the stated solution is insufficient.

**Comment by jazzyguitar** [comment]
@dbczumar Unfortunately the above solution isn't sufficient when using assumed role for calling the tracking server with `MLFLOW_TRACKING_AWS_SIG4 = True`, suggested solution is to allow passing session here: https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L157

**Comment by ejh-alexchatwin** [comment]
> For whoever is looking for solution for this... After trying out solving using environment variables (to no avail), we found a rather good workaround without changing mlflow code itself - call the following function to assume role and update the default boto3 session (which mlflow uses in it's s3 client):


Thank you, this has saved me hours!!
