### ISSUE TITLE
TensorFlow 怎么保存模型给这个平台调用啊  (how to save & use a TensorFlow model in MLflow?)

### ISSUE THREAD

**Issue by zyjcs** [mlflow/mlflow#1665]
求大佬指点一下

**Comment by smurching** [comment]
请在https://stackoverflow.com/tags/mlflow/ 上提问

请看: https://github.com/mlflow/mlflow/blob/master/examples/tensorflow/train_predict.py#L46。 你也能看这个: https://mlflow.org/docs/latest/python_api/mlflow.tensorflow.html#mlflow.tensorflow.log_model, https://mlflow.org/docs/latest/models.html。

(对不起我的中文不好!).
