### ISSUE TITLE
[FR] What happened to the runs compact view button?

### ISSUE THREAD

**Issue by johny-c** [mlflow/mlflow#1666]
Yesterday I upgraded from 1.0.0 to 1.1.0. Suddenly the runs compact view button disappeared from the UI. It was really useful as my runs have many parameters, and now I have to scroll endlessly to get an overview. Is there a reason for removing it?

**Comment by imaluengo** [comment]
I would also love to have it back :)

**Comment by t-henri** [comment]
I found this commit: https://github.com/mlflow/mlflow/commit/9d4e526e1b1ffaaac5072583ceb4cefa41a1ef55#diff-fa151380130110b5b1f7ba277afb356a

It removes the compact view, and is supposed to add a "Load more" button in the UI (I can't find this button). I reverted it in our fork, and it works, the compact view is back but there is no longer the 100 runs display limit.

**Comment by johny-c** [comment]
Thanks @t-henri, so probably @Zangr knows what's up?

**Comment by Zangr** [comment]
The other view was removed to allow us to have one consistent run-listing experience with the ability to list a param/metrics as a separate column on demand. If you want to display a metric/param on a separate column, you can click on that metric/param and select `Display as a separate column`.  If there are other use cases that make you want the removed view back please feel free to post here as well.
![display-collapse-column](https://user-images.githubusercontent.com/6811562/61964392-9744f980-af82-11e9-89d0-3bab32f2d625.gif)

**Comment by Zangr** [comment]
The "Load more" button will only show when you have more runs to load. Currently, the load-size is set to 100, which means if you have less than 100 runs, you won't see the "Load more" button.

**Comment by johny-c** [comment]
Well, yes, so the button was just doing and undoing the "Display as a separate column" function for all metrics and params at once, which is reasonable to have and becomes necessary, the more parameters your runs have. I think the use case is just to get an overview over more runs faster.

**Comment by imaluengo** [comment]
For me removing the button is a step back. I can collect over 20 metrics for each run, which makes runs vertically looong.

Comparing 5 runs was quick before (had to scroll horizontally to the correct metric, but then all the runs were at reach.

As an additional comment (separate bug), I find current release doesn't "remember" well all the filter params and columns, which makes me have to re-enter filtering conditions every single time I reload webpage; making current version a step back from 1.0 to me, at least from the tracking UI point of view.

**Comment by t-henri** [comment]
@Zangr about the "Load More" button, I have 201 runs and I don't see it in the UI.

**Comment by Zangr** [comment]
@t-henri, the "Load more" button will show when you scroll to the bottom of the table.

**Comment by andremesarovic** [comment]
I really miss the tabular button. It made comparing runs so easy. Now its not.

**Comment by giordyb** [comment]
Another issue that I see is that once the metric has been moved into its own column the heading only displays the first 18 characters and cannot be resized and the full name doesn't show up by hovering with the mouse.

**Comment by geniki** [comment]
Do you plan to bring back this view/feature? The suggested workaround doesn't work at all for my workflow.

**Comment by Zangr** [comment]
@geniki, I plan to work on some refactoring on the runs table with @gioa during the last two weeks of this month. You are welcome to provide more details about your workflow and view preference so I can take those into consideration during the refactor.

**Comment by geniki** [comment]
Thanks, looking forward to that. 

We often have dozens of runs with dozens of params and as others above pointed out above, it's difficult to compare when you can see only, say, two runs at the same time.

Spreadsheet-like view is fairly established as useful I think.

**Comment by geniki** [comment]
@Zangr any new thoughts on this issue?

**Comment by Zangr** [comment]
@geniki the plan was slightly postponed, we will start working on bringing this next week. We will keep this thread posted.

**Comment by rom1504** [comment]
I propose to handle this in a new component for the runs, I detailed what I implemented and proposed changes there https://github.com/mlflow/mlflow/issues/2084

**Comment by mlisovyi** [comment]
It is extremely unfortunate, that such change, that is not particularly welcomed by users, is not reverted since half a year. For me it just means sticking to v1.0 for the time being :(

**Comment by imaluengo** [comment]
Me and my team have stopped using MLFlow actively and has just become a "convenient storage service for runs" for us. We run tens of experiments weekly with several parameters each of them. Unfortunately, current experiment exploring UI is not very useful for our purposes.

**Comment by Zangr** [comment]
Sorry to hear that @imaluengo @mlisovyi . I spent some time in Q4 working on building a better view for browsing MLFlow runs. PR for the new runs table multi-column view was merged last week. It provides a superset of features compare to both old views plus a series of other improvements like column group collapsing, column resizing and column filtering to help user to explore runs with a large amount of parameters and metrics. It will be available in the next release. We plan to collaborate with the community to continue improving this view to fit more feature requests.

PR & Demo: https://github.com/mlflow/mlflow/pull/2251
![888368EB-BAAA-464F-93E9-5284C71BADE5](https://user-images.githubusercontent.com/6811562/73140513-7d1dce00-402e-11ea-846c-fc8687ff0de6.gif)

**Comment by imaluengo** [comment]
@Zangr this is amazing, exactly what I was hoping for!! Thanks a lot for keeping us in the loop! Do you know rough timelines for next release when this will be available? Tempted to go nightly/master otherwise!!

Thanks a lot! :)

**Comment by mlisovyi** [comment]
Thanks you @Zangr! This looks like a very useful improvement in the UI. Looking forward to try it out!

**Comment by rom1504** [comment]
This looks great @Zangr , thanks for working on this !
This seems to fulfil most (maybe all ? I will confirm when I test it) of the UI ideas I had put in that issue https://github.com/mlflow/mlflow/issues/2084 👍

**Comment by Zangr** [comment]
@imaluengo @mlisovyi we just released [MLFlow 1.6.0](https://github.com/mlflow/mlflow/releases/tag/v1.6.0) with the new runs table multi-column view.

@rom1504 , yes except we are doing the search filter altogether at the top instead of on each columns.

**Comment by johny-c** [comment]
Hi @Zangr, awesome work. The new UI is pretty nice. I'm closing this.
