### ISSUE TITLE
[FR]How to transfer the multi-dimensional pixel information of the image to the model after the model is deployed as docker？

### ISSUE THREAD

**Issue by lyw615** [mlflow/mlflow#1668]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please do not delete this template unless you are sure your issue is outside its scope.

-------
## Guidelines

I have deployed the model as docker via mlflow. We can pass data to the docker using a command like:
curl -X POST -H 'Content-Type: application/json; format=pandas-records' --data '{}' http://127.0.0.1:5000/invocations.
But my input of the model is the pixel information of the image. The multidimensional data cannot be stored as pandas.DataFrame data. Can i upload a json file like this via curl {\"data\":ndarray object=（shape=(256,256,3) ）} ？Does the model return results? Or what content form should it be?

**Comment by apurva-koti** [comment]
Hi @lyw615,

Please refer to our [issue policy](https://github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for guidance on how to file an issue and what to file for. I'm unsure as to what exactly you're asking.
