### ISSUE TITLE
[BUG]model serve with pandas-splits format returns data in pandas-records format

### ISSUE THREAD

**Issue by stfj77** [mlflow/mlflow#1671]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:add_n_model example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**:1.1.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:  curl http://127.0.0.1:5000/invocations -H "Content-Type: application/json; format=pandas-split" -d "{\"columns\":[\"TestValue\"],\"index\":[0,1,2,3],\"data\":[[1],[4],[7],[12]]}"

### Describe the problem
When posting data with format pandas-split, the result is still sent back in record format, as this is being set hardcoded in scoring_server \_init__.py:

```python
def predictions_to_json(raw_predictions, output):
    predictions = _get_jsonable_obj(raw_predictions, **pandas_orient="record")**
    json.dump(predictions, output, cls=NumpyEncoder)
```

As as result the index information of the original dataframe gets lost in the response

For consistency I think the response serialization should be done in the same format as the input data

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.

**Comment by max-allen-db** [comment]
Hey @stfj77 ,

Coming back to review this right now. Thanks for pointing this out! Since you have the context on the different pandas formats, would it be possible for you to make a pull request with the necessary change? We'd greatly appreciate it.
