### ISSUE TITLE
Errors using Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by andrie** [mlflow/mlflow#1674]
### System information
- I'm testing using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
- I installed Ubuntu in WSL
- MLflow installed from source, using [instructions](https://github.com/mlflow/mlflow/tree/master/mlflow/R/mlflow)
- mlflow, version 1.1.0
- Python 3.7.3
- npm version 3.5.2

### Describe the problem

When I run:

```r
library(mlflow)
mlflow_set_experiment("Test")
```

I get: 

```
Error in supervisor_start() :
  processx supervisor was not ready after 5 seconds.
```

I have tried again, using MLFlow 1.1.0, but get the same error:

Error in supervisor_start() :
  processx supervisor was not ready after 5 seconds.

**Comment by mik3y64** [comment]
@javierluraschi I am having the same issue here. I am following the [MLflow tutorial] 

(https://www.mlflow.org/docs/latest/tutorial.html)

Windows 10 64bit and Ubuntu in WSL
MLflow version 1.2.0
Installed Anaconda3-2019.07-Linux-x86_64.sh
Python 3.7.3
conda 4.7.0

```
# The data set used in this example is from http://archive.ics.uci.edu/ml/datasets/Wine+Quality
# P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis.
# Modeling wine preferences by data mining from physicochemical properties. In Decision Support Systems, Elsevier, 47(4):547-553, 2009.

library(mlflow)
library(glmnet)
library(carrier)

set.seed(40)

# Read the wine-quality csv file
data <- read.csv("wine-quality.csv")

# Split the data into training and test sets. (0.75, 0.25) split.
sampled <- sample(1:nrow(data), 0.75 * nrow(data))
train <- data[sampled, ]
test <- data[-sampled, ]

# The predicted column is "quality" which is a scalar from [3, 9]
train_x <- as.matrix(train[, !(names(train) == "quality")])
test_x <- as.matrix(test[, !(names(train) == "quality")])
train_y <- train[, "quality"]
test_y <- test[, "quality"]

alpha <- mlflow_param("alpha", 0.5, "numeric")
lambda <- mlflow_param("lambda", 0.5, "numeric")

with(mlflow_start_run(), {
  model <- glmnet(train_x, train_y, alpha = alpha, lambda = lambda, family= "gaussian", standardize = FALSE)
  predictor <- crate(~ glmnet::predict.glmnet(!!model, as.matrix(.x)), !!model)
  predicted <- predictor(test_x)
  
  rmse <- sqrt(mean((predicted - test_y) ^ 2))
  mae <- mean(abs(predicted - test_y))
  r2 <- as.numeric(cor(predicted, test_y) ^ 2)
  
  message("Elasticnet model (alpha=", alpha, ", lambda=", lambda, "):")
  message("  RMSE: ", rmse)
  message("  MAE: ", mae)
  message("  R2: ", r2)
  
  mlflow_log_param("alpha", alpha)
  mlflow_log_param("lambda", lambda)
  mlflow_log_metric("rmse", rmse)
  mlflow_log_metric("r2", r2)
  mlflow_log_metric("mae", mae)
  
  mlflow_log_model(predictor, "model")
})

# Error in supervisor_start() : 
#  processx supervisor was not ready after 5 seconds.
```

**Comment by andrie** [comment]
My hunch is that this not going to work in WSL 1, but may possibly get fixed with [WSL 2](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/), although WSL-2 is still only available on the Windows Insiders program.

**Comment by mik3y64** [comment]
The initial starts seem to fail a few times but if you keep running it can get through. Need to run multiple times to get through.

library(mlflow)

run <- mlflow_start_run()
# Error in supervisor_start() : 
#   processx supervisor was not ready after 5 seconds.
run <- mlflow_start_run()
# Error in supervisor_start() : 
#   processx supervisor was not ready after 5 seconds.
run <- mlflow_start_run()
# Error in supervisor_start() : 
#   processx supervisor was not ready after 5 seconds.
mlflow_start_run()
# Error in supervisor_start() : 
#   processx supervisor was not ready after 5 seconds.

run <- mlflow_start_run()


mlflow_log_param("param1", 5)

mlflow_log_metric("foo", 2, step = 1)
mlflow_log_metric("foo", 4, step = 2)
mlflow_log_metric("foo", 6, step = 3)

write("Hello world!", file = "output.txt")

mlflow_log_artifact("output.txt")

# 2019/08/23 22:24:16 INFO mlflow.store.cli: Logged artifact from local file output.txt to artifact_path=None
# 2019/08/23 22:24:16 INFO mlflow.store.cli: Logged artifact from local file output.txt to artifact_path=None
# Root URI: /mnt/c/Users/<your_path>/mlruns/0/f22c17ea0e9c40ac8db5e4151c867696/artifacts
# A tibble: 1 x 3
# path       is_dir file_size
# <chr>      <lgl>  <chr>    
#   1 output.txt FALSE  13       

mlflow_end_run()
# A tibble: 1 x 12

# run_uuid experiment_id user_id status start_time          end_time            artifact_uri lifecycle_stage
# <chr>    <chr>         <chr>   <chr>  <dttm>              <dttm>              <chr>        <chr>          
#   1 f22c17e… 0             <username>     FINIS… 2019-08-23 22:23:15 2019-08-23 22:24:20 /mnt/c/User… active         
# … with 4 more variables: run_id <chr>, metrics <list>, params <list>, tags <list>

# Warning messages:
# 1: closing unused connection 4 (/tmp/RtmphmCbjd/supervisor_stdout37f26037eb0) 
# 2: closing unused connection 3 (/tmp/RtmphmCbjd/supervisor_stdin37f3ce87437) 
# 3: closing unused connection 6 (/tmp/RtmphmCbjd/supervisor_stdout37f2608f737) 
# 4: closing unused connection 5 (/tmp/RtmphmCbjd/supervisor_stdin37f15181bec)

**Comment by andrie** [comment]
Hopefully this gets resolved with WSL 2, since this will include "full system call capability" (https://docs.microsoft.com/en-us/windows/wsl/wsl2-about)
