### ISSUE TITLE
What is the best way to handle feature requirements of the model?

### ISSUE THREAD

**Issue by zcharli** [mlflow/mlflow#1682]
I recently stumbled across the this neat library that packages a ML model into a deployable artifact. After an artifact is hosted on a server, it seems that we will need to know what features it consumes ahead of time. From examples, `--data` is used pass in the data required for scoring. If we're managing a large pool of models, the caller has to either know what features the model needs before hand (repository or hardcoded) or pass in a large payload in hopes that the model uses something. I was thinking the best way to manage this was to ask the deployment for a a list of features it uses. Since features are specific to models, does it make sense to expose the feature requirements to the caller. In addition, if we were to pass the deployment some form of context: "hey, heres what I know about my invocation at the moment,  tell me what features do you need", opens up the ability to return dynamic feature that are customizable to the request. What would dynamic features be good for? It can be useful if we have extra dimensions in the feature data that is contextually driven. For an example feature name “conversion count”; can be broken up by point of sale or user country. A different value would back this feature for every country but share the conversion counts feature name. The deployment server can pass back meta data on what the key of the feature would look like for a users conversion count in their country, assuming feature stores are key value stores.

How are you inferring what features are used by the deployment server today? Although I shared what I think could work for my case, what's typically best practice in your opinion?

**Comment by raghav20** [comment]
Any update ?

**Comment by mparkhe** [comment]
#2698 added functionality to log model schema along with the model. This addresses the concern about identifying exact required for a served model.
