### ISSUE TITLE
mlflow ui does not start on windows 10

### ISSUE THREAD

**Issue by swamat** [mlflow/mlflow#1684]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please do not delete this template unless you are sure your issue is outside its scope.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:windows 10
- **MLflow installed from (source or binary)**: mlflow installed using pip install mlflow command
- **MLflow version (run ``mlflow --version``)**:1.1.0
- **Python version**: 3.7
- **Exact command to reproduce**:mlflow ui

### Describe the problem
I installed mlflow using 'pip install mlflow' command in anaconda prompt(conda version 4.7.10). Clone the sample repository using **git clone https://github.com/mlflow/mlflow**. Ran a python script from examples folder. It worked fine. But when i give 'mlflow ui' am getting the below error

### Other info / logs
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\mlflow.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\cli.py", line 198, in ui
    _run_server(backend_store_uri, default_artifact_root, "127.0.0.1", port, None, 1)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\server\__init__.py", line 83, in _run_server
    exec_cmd(full_command, env=env_map, stream_output=True)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\utils\process.py", line 34, in exec_cmd
    stdin=subprocess.PIPE, **kwargs)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Please help in solving this

**Comment by thomasryck** [comment]
@ankitmathur-db I did `pip install waitress` and mlflow ui command worked. However when I tried mlflow models serve -m runs:/a6656995a0a34bbebfea43e54f265fea/model I still get the same error. (I was doing the following example python sklearn_logistic_regression/train.py)

**Comment by swamat** [comment]
Thanks @ankitmathur-db The same worked for me. But as you mentioned am getting the below error when i try to serve the model using the command: mlflow models serve -m runs:/5db9a956f1414595978e28dc5f1c3329/artifacts/model

Error:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\mlflow.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\models\cli.py", line 56, in serve
    host=host)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\pyfunc\backend.py", line 77, in serve
    command_env=command_env)
  File "c:\programdata\anaconda3\lib\site-packages\mlflow\pyfunc\backend.py", line 142, in _execute_in_conda_env
    child = subprocess.Popen(["bash", "-c", command], close_fds=True, env=command_env)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Can someone help on this

**Comment by thomasryck** [comment]
@swamat 

In fact , now I have the following error

> STDERR:Traceback (most recent call last):
>   File "C:\Users\tryck\Anaconda3\Scripts\conda-env-script.py", line 5, in <module>
>     from conda_env.cli.main import main
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 39, in <module>
>     from . import main_create
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 12, in <module>
>     from conda.cli import install as cli_install
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
>     from ..core.index import calculate_channel_urls, get_index
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
>     from .package_cache_data import PackageCacheData
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
>     from conda_package_handling.api import InvalidArchiveError
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
>     from libarchive.exception import ArchiveError as _LibarchiveArchiveError
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
>     from .entry import ArchiveEntry
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
>     from . import ffi
>   File "C:\Users\tryck\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
>     libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
>   File "C:\Users\tryck\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Users\tryck\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
>     self._handle = _dlopen(self._name, mode)
> TypeError: LoadLibrary() argument 1 must be str, not None

Which I solved by doing pip install libarchive.

But now I have the following error:

> Traceback (most recent call last):
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\tryck\Anaconda3\envs\tensorflow_capu\Scripts\mlflow.exe\__main__.py", line 9, in <module>
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\models\cli.py", line 56, in serve
>     host=host)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\pyfunc\backend.py", line 78, in serve
>     command_env=command_env)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\pyfunc\backend.py", line 132, in _execute_in_conda_env
>     conda_env_name = _get_or_create_conda_env(conda_env_path, env_id=env_id)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\projects\__init__.py", line 494, in _get_or_create_conda_env
>     print(json.loads(stdout))
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\json\__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Which I solved by changing anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\projects\__init__.py file:

line 494:

From

> env_names = [os.path.basename(env) for env in json.loads(stdout)['envs']]

to

> env_names = [os.path.basename(env) for env in json.loads(stdout.split('\n', 1)[-1])['envs']]

It's not clean but I try to get thinks working.

Now I get the following error, due to linux command:

> 2019/08/01 10:18:33 INFO mlflow.pyfunc.backend: === Running command 'source C:\Users\tryck\Anaconda3\condabin\..\Scripts/../etc/profile.d/conda.sh && conda activate mlflow-684f146d22dc8c22cc480b2dfa1335663a7b1c8f 1>&2 && gunicorn --timeout 60 -b 127.0.0.1:5000 -w 1 mlflow.pyfunc.scoring_server.wsgi:app'
> Traceback (most recent call last):
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\tryck\Anaconda3\envs\tensorflow_capu\Scripts\mlflow.exe\__main__.py", line 9, in <module>
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\models\cli.py", line 56, in serve
>     host=host)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\pyfunc\backend.py", line 78, in serve
>     command_env=command_env)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\site-packages\mlflow\pyfunc\backend.py", line 144, in _execute_in_conda_env
>     child = subprocess.Popen(["bash", "-c", command], close_fds=True, env=command_env)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "c:\users\tryck\anaconda3\envs\tensorflow_capu\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified

I am still digging

**Comment by swamat** [comment]
@ankitmathur-db Please let me know if you fins a solution for the same

**Comment by thomasryck** [comment]
@swamat I got it working for the server, I did not manage to get it working to made a prediction.
It seems that I didn't had the modification from #1080 even if I have version 1.1.0 . So I did other modification and modification from this pull request in the lib code to get things working
I will uploaded these changes later so you can make it work.
@smurching @dbczumar @tomasatdatabricks @ankitmathur-db

**Comment by thomasryck** [comment]
I modified the following method in the __init__.py in mlflow projects

> def _get_conda_command(conda_env_name):
>     #  Checking for newer conda versions
>     if os.name != "nt" and ('CONDA_EXE' in os.environ or 'MLFLOW_CONDA_HOME' in os.environ):
>         conda_path = _get_conda_bin_executable("conda")
>         activate_conda_env = ['source ' + os.path.dirname(conda_path) +
>                               '/../etc/profile.d/conda.sh']
>         activate_conda_env += ["conda activate {0} 1>&2".format(conda_env_name)]
>     else:
>         activate_path = _get_conda_bin_executable("activate")
>         # in case os name is not 'nt', we are not running on windows. It introduces
>         # bash command otherwise.
>         if os.name != "nt":
>             return ["source %s %s 1>&2" % (activate_path, conda_env_name)]
>         else:
>             return ["conda %s %s |" % ('activate', conda_env_name)]
>     return activate_conda_env

I changed in backend.py

> def _execute_in_conda_env(conda_env_path, command, install_mlflow, command_env=None):
>     if command_env is None:
>         command_env = os.environ
>     env_id = os.environ.get("MLFLOW_HOME", VERSION) if install_mlflow else None
>     conda_env_name = _get_or_create_conda_env(conda_env_path, env_id=env_id)
>     activate_conda_env = _get_conda_command(conda_env_name)
>     if install_mlflow:
>         if "MLFLOW_HOME" in os.environ:  # dev version
>             install_mlflow = "pip install -e {} 1>&2".format(os.environ["MLFLOW_HOME"])
>         else:
>             install_mlflow = "pip install mlflow=={} 1>&2".format(VERSION)
> 
>         activate_conda_env += [install_mlflow]
>     command = " ".join(activate_conda_env + command)
>     _logger.info("=== Running command '%s'", command)
>     child = subprocess.Popen(["powershell", "-c", command], close_fds=True, env=command_env)
>     rc = child.wait()
>     if rc != 0:
>         raise Exception("Command '{0}' returned non zero return code. Return code = {1}".format(
>             command, rc
>         ))

And 

 

>    def serve(self, model_uri, port, host):
>         """
>         Serve pyfunc model locally.
>         """
>         local_path = _download_artifact_from_uri(model_uri)
>         # NB: Absolute windows paths do not work with mlflow apis, use file uri to ensure
>         # platform compatibility.
>         local_uri = path_to_local_file_uri(local_path)
>         command = (['waitress-serve'] + [
>             "--host=%s" % host,
>             "--port=%s" % port,
>             "--ident=mlflow",
>             "mlflow.server:app"
>     ]
> )
>         command_env = os.environ.copy()
>         command_env[scoring_server._SERVER_MODEL_PATH] = local_uri
>         if not self._no_conda and ENV in self._config:
>             conda_env_path = os.path.join(local_path, self._config[ENV])
>             return _execute_in_conda_env(conda_env_path, command, self._install_mlflow,
>                                          command_env=command_env)
>         else:
>             _logger.info("=== Running command '%s'", command)
>             subprocess.Popen(command.split(" "), env=command_env).wait()

**Comment by swamat** [comment]
@thomasryck I tried the above mentioned changes in mlflow project init.py and pyfunc backend.py. Still am getting the same error

**Comment by thomasryck** [comment]
@swamat  Show traceback please

**Comment by thomasryck** [comment]
I saw in changelog that only tracking and UI were available on Windows

**Comment by ankitmathur-db** [comment]
Thanks @thomasryck - please feel free to file a PR if you think you have something working that doesn't currently work on MLFlow. For Windows, we currently only support tracking and the UI, so the server isn't expected to work on Windows at the moment. If you'd like to take on this task, we'd love to review PRs on it!

**Comment by kriss024** [comment]
python -m pip install --upgrade pip
pip install mlflow
