### ISSUE TITLE
Can we get any examples based on JAVA?[FR]

### ISSUE THREAD

**Issue by pandae7** [mlflow/mlflow#1686]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please do not delete this template unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Provide a clear high-level description of the feature request in the following sections. Feature requests that are likely to be accepted:
* Are minimal in scope (note that it's always easier to add additional functionality later than remove functionality)
* Are extensible (e.g. if adding an integration with an ML framework, is it possible to add similar integrations with other frameworks?)
* Have user impact & value that justifies the maintenance burden of supporting the feature moving forwards. The [JQuery contributor guide](https://contribute.jquery.org/open-source/#contributing-something-new) has an excellent discussion on this.

### Motivation
What is the use case in mind?  Why is it valuable to support, and why is it currently difficult or impossible to achieve? Could the desired functionality alternatively be implemented as a third-party package using MLflow public APIs? 

### Proposed Changes
For user-facing changes, what APIs are you proposing to add or modify? For internal changes, what code paths will need to be modified?

**Comment by ankitmathur-db** [comment]
Is there something in particular that is unclear?

**Comment by pandae7** [comment]
I'm not a JAVA based Coder, and I'm experimenting with a ML Model written in JAVA. I Couldn't launch the JAVA's tracking API.
I tried Installing Maven Package and I'm getting this error

Running TestSuite
Configuring TestNG with: TestNG652Configurator
Tests run: 84, Failures: 1, Errors: 0, Skipped: 83, Time elapsed: 0.42 sec <<< FAILURE! - in TestSuite
beforeAll(org.mlflow.artifacts.CliBasedArtifactRepositoryTest)  Time elapsed: 0.241 sec  <<< FAILURE!
java.io.IOException: Cannot run program "mlflow": error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at org.mlflow.tracking.TestClientProvider.startServerProcess(TestClientProvider.java:88)
	at org.mlflow.tracking.TestClientProvider.initializeClientAndServer(TestClientProvider.java:45)
	at org.mlflow.artifacts.CliBasedArtifactRepositoryTest.beforeAll(CliBasedArtifactRepositoryTest.java:38)


Results :

Failed tests: 
  CliBasedArtifactRepositoryTest.beforeAll:38 » IO Cannot run program "mlflow": 

It says that the Build of MLFlow Tracking API is failed.

**Comment by ankitmathur-db** [comment]
Could you reply with the specific command that you ran and the set up that you were trying with? If this is a bug, we'd love to fix it ASAP!

**Comment by pandae7** [comment]
The Issue mentioned above is sorted, But I have a basic query on how to exactly run a Java Model downloaded from the net, MLFlow claims that it provides end to end support for any ML Model and in any Language. 
Suppose, I have a Java Model in the examples folder. Now, how to use the tracking feature mentioned in the MLFlow Java Client Read.me file?

**Comment by smurching** [comment]
@pandae7 apologies for the delay, the `mleap` flavor is the one example of a model flavor implemented in Java, you can log models from Python using the flavor ([see docs](https://mlflow.org/docs/latest/python_api/mlflow.mleap.html)) and then load logged models back using the `MleapLoader` Java class, you can see an example in the [Java tests](https://github.com/mlflow/mlflow/blob/889e46269256c3bef5c9744312fd860c0136521a/mlflow/java/scoring/src/test/java/org/mlflow/MLeapPredictorTest.java#L57)

We'd welcome doc enhancements to better surface this use case, if you'd be interested - thanks!

**Comment by smurching** [comment]
Closing this for now, but feel free to reopen if anything comes up
