### ISSUE TITLE
[BUG] Keras Summary Too Long for SQL Column

### ISSUE THREAD

**Issue by fdabek1** [mlflow/mlflow#1688]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX 10.14 (Client) & Ubuntu 18.04 (Tracking Server)
- **MLflow installed from (source or binary)**: From PyPi
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**: 3.6.8
- **npm version, if running the dev UI**: 5.6.0
- **Exact command to reproduce**: _See code to reproduce steps_

### Describe the problem
When using the `mlflow.keras.autolog()` function with a SQL backend on a tracking server, the server is unable to add the **summary** key generated by the autolog function into the database.  The **summary** key is a very long string while the database column is only VARCHAR(250).

### Code to reproduce issue
1. Setup a tracking server using MySQL backend with the following script:
> mlflow server --backend-store-uri mysql+pymysql://user:pass@localhost/db_name --default-artifact-root s3://bucket_name_here --host 0.0.0.0

2. Then used the keras training script here: https://github.com/mlflow/mlflow/blob/master/mlflow/keras.py

3. Added the tracking server uri to the top of the script:

> mlflow.set_tracking_uri('http://mywebsite.com')

4. Ran the training script and received an error on the server.

### Other info / logs
I attempted PostgreSQL instead of MySQL just to attempt and it had the same issue.

Full traceback here: [traceback.txt](https://github.com/mlflow/mlflow/files/3458279/traceback.txt) or [traceback as a gist](https://gist.github.com/fdabek1/1f3a0d82e090f064926e8fe5a0f21aac)

**Comment by apurva-koti** [comment]
Thanks for the issue! @ankitmathur-db has a fix for this in #1687 and I'll put out an autolog-specific try-catch for this.

**Comment by apurva-koti** [comment]
@fdabek1 Is the traceback from a warning or did your code actually fail with an exception?

**Comment by fdabek1** [comment]
> @fdabek1 Is the traceback from a warning or did your code actually fail with an exception?

@apurva-koti Sorry should have been more specific.  The traceback was from the tracking server on the request.  The training code ran fine and showed three attempts to contact the server.


> Thanks for the issue! @ankitmathur-db has a fix for this in #1687 and I'll put out an autolog-specific try-catch for this.

This is great!  I am assuming that I need to wait for the next release to get this update via pip?  In the meantime is there anything else that I can do since I am assuming that will be a while?  Basically, if I update the column in the SQL table myself, would that break any future updates?

**Comment by apurva-koti** [comment]
@fdabek1 We are hoping to get both #1687 and  in the next release, which should be coming soon. You could [install MLflow from source](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst) which will have more up-to-date commits from master.

 If your training code ran okay, you should be fine, though summary tags and model checkpointing won't be auto-logged until the fix. Updating the column manually shouldn't break updates.

**Comment by ankitmathur-db** [comment]
Both PRs have merged on master! If you install MLFlow from source, you should be able to get this working.
