### ISSUE TITLE
Run failed for mlflow run example/tutorial -P alpha=0.4

### ISSUE THREAD

**Issue by liuzx32** [mlflow/mlflow#169]
=== Fetching project from example/tutorial ===
=== Work directory for this run: example/tutorial ===
=== Created directory /var/folders/cj/c1hgw6t57xj3dwf622tg5wtc0000gn/T/tmpzd_PhV for downloading remote URIs passed to arguments of type 'path' ===
=== Running command: source activate mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b && python train.py 0.4 0.1 ===
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    with mlflow.start_run():
  File "/Users/liuzhixin/anaconda2/envs/mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b/lib/python2.7/site-packages/mlflow/tracking/__init__.py", line 262, in start_run
    run = store.get_run(existing_run_uuid)
  File "/Users/liuzhixin/anaconda2/envs/mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b/lib/python2.7/site-packages/mlflow/store/file_store.py", line 175, in get_run
    run_info = self.get_run_info(run_dir)
  File "/Users/liuzhixin/anaconda2/envs/mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b/lib/python2.7/site-packages/mlflow/store/file_store.py", line 182, in get_run_info
    meta = read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
  File "/Users/liuzhixin/anaconda2/envs/mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b/lib/python2.7/site-packages/mlflow/utils/file_utils.py", line 147, in read_yaml
    raise e
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/liuzhixin/github/mlflow/mlruns/0/2abf936fb7f9471ebe38fb1d1294a1c2/meta.yaml", line 9, column 17
=== Run failed ===

**Comment by smurching** [comment]
Hi @liuzx32, thanks for reporting this issue. What version of Python (`python --version`) & MLflow (`mlflow --version`) are you running with? Also, did you make any changes to the `conda.yaml` file in `example/tutorial`? After changing the conda.yaml to specify a `python=2.7` (instead of `python=3.6`) dependency, I'm able to run successfully (& my conda environment hash also seems to match yours):

```
=== Creating conda environment mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b ===
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.5.9

Please update conda by running

    $ conda update -n base conda



Downloading and Extracting Packages...
[skipping package installation logs]
#
# To activate this environment, use
#
#     $ conda activate mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b
#
# To deactivate an active environment, use
#
#     $ conda deactivate

=== Created directory /var/folders/z9/lf6w6gqj5bj2sgz237pjdky00000gp/T/tmpcaict49b for downloading remote URIs passed to arguments of type 'path' ===
=== Running command 'source activate mlflow-69aa8a47b2df3cf095c2b7178b8f2079fc0e0e0b && python train.py 0.5 0.1' in run with ID 'f4bec3ca974e4ae7bc7c2b61055a820c' === 
Elasticnet model (alpha=0.500000, l1_ratio=0.100000):
  RMSE: 0.794793101904
  MAE: 0.618913083423
  R2: 0.184116687182
=== Run (ID 'f4bec3ca974e4ae7bc7c2b61055a820c') succeeded ===
```
