### ISSUE TITLE
[FR] Decorate flask endpoints to add monitoring/authentication

### ISSUE THREAD

**Issue by t-henri** [mlflow/mlflow#1698]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please do not delete this template unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
To be able to add extra functionalities to the MLFlow tracking server, we would like to be able to decorate flask endpoints. It could be used for many use cases like monitoring or authentication.

### Motivation
At Criteo, we use MLFlow tracking server to track our experiments, and we would like to be able to monitor our server.
For this, we usually use prometheus, so we could use this for flask: https://pypi.org/project/prometheus-flask-exporter/
It could be usefull to monitor the requests response time, the errors on the server...

Possible alternative:
On my side, before launching the server, I get the list of endpoints and decorate them, but then it wouldn't be reusable by others and we are probably not the only ones who want to monitor the server.

### Proposed Changes
1/ Add a mlflow-prometheus-exporter that decorates flask endpoint so prometheus can get metrics on server usage.
2/ Add a parameter to the mlflow server command line to activate the prometheus exporter

**Comment by helltone** [comment]
isn't this implemented already by [this](https://github.com/mlflow/mlflow/pull/2097/commits)?

**Comment by dbczumar** [comment]
I'm going to go ahead and close this issue because the prometheus monitoring use case has been addressed via https://github.com/mlflow/mlflow/pull/2097/ and other issues, such as https://github.com/mlflow/mlflow/issues/1825, track interfaces for general auth.
