### ISSUE TITLE
Tag in seperate Columns

### ISSUE THREAD

**Issue by aim-nfunke** [mlflow/mlflow#1701]
As a Data Scientist ich want to display Tags in seperate Columns.  [FR]

This functions  already exists for parameters and metrics.

It is useful to have a good overview and more flexibility to find runs with a special tag.

Thank you :)

**Comment by Zangr** [comment]
@aim-nfunke We do provide showing tags in a separate column from 1.0. Could you please try upgrade?

**Comment by aim-nfunke** [comment]
We have already upgraded to 1.1. This function doesnt work. Is this maybe a bug?
For Parameters and metrics it is no problem.

**Comment by Zangr** [comment]
@aim-nfunke, I'm not sure what do you mean by "this function doesn't work"? Could you please elaborate more by following the issue template? That will help the investigation greatly. I'd also recommend providing more information on how you upgraded to 1.1. 

Tags related features are provided in the following PRs, you can refer to the gif in the PR description for a quick look at how these features should work. https://github.com/mlflow/mlflow/pull/1400 https://github.com/mlflow/mlflow/pull/1426

**Comment by aim-nfunke** [comment]
Hi, 
okay i will explain it with pictures:
![display as a new column](https://user-images.githubusercontent.com/53812472/62604277-0104c200-b8f8-11e9-80f6-80ecb1e0a695.PNG)

Parameters and metrics u can display as a separate Column.

If u try this with Tags, u dont get the possibility to display tags as a separate Column:

![tags](https://user-images.githubusercontent.com/53812472/62604368-39a49b80-b8f8-11e9-8512-00c3ef7f6c48.PNG)

**Comment by Zangr** [comment]
I see, listing individual tag as a separate column is currently not supported. We will consider putting it on the roadmap and you are also welcome to submit a PR for it.
CC @gioa

**Comment by aim-nfunke** [comment]
Have you decided to put the issue on the roadmap? And where can i find the official Roadmap of ML Flow?

**Comment by Zangr** [comment]
Hi @aim-nfunke we do have a plan to refactor the runs table UI in Q4 to resolve a list of community requests including this.

**Comment by aim-nfunke** [comment]
@Zangr do you still refactor the runs table UI in 2019? 
To which update the change will take place? This issue would be interessting too: https://github.com/mlflow/mlflow/issues/1829

**Comment by Zangr** [comment]
@aim-nfunke we are actively working on a new column view. It will land in Q4.

**Comment by Zangr** [comment]
Resolved by https://github.com/mlflow/mlflow/pull/2251
