### ISSUE TITLE
http://localhost:5000/2.0/preview/mlflow/experiments/list, response status 304

### ISSUE THREAD

**Issue by liuzx32** [mlflow/mlflow#171]
Restful api: http://localhost:5000/2.0/preview/mlflow/experiments/list, return status 304.
Is there other port for the restful api?

**Comment by smurching** [comment]
Hi @liuzx32, thanks for reporting this - the server by default hosts the API at `/api` (i.e. if you try http://localhost:5000/api/2.0/preview/mlflow/experiments/list it should work). This is a gap in our REST API docs, will work on a fix :)

**Comment by liuzx32** [comment]
@smurching Thank you very much.
