### ISSUE TITLE
[FR] Run MLFlow Project on Azure

### ISSUE THREAD

**Issue by smwade** [mlflow/mlflow#1711]
# Run MLFlow Project on Azure

## Proposal

Expand the open source remote execution backend for MLflow projects to include Azure. This will be similar and build off of kubernetes support in release 1.1.0. Once complete will add to the CLI the command: 

`mlflow run <project_uri> --backend azure --backend-config azure_config.json`

where the `backend-config` is of the form:

```json
{
   "subscription-id": "b1c23f06-f9b5-4ccb-8a65-a8cb3dcd6a5a",
   "resource-group": "myResourceGroup",
   "workspace-name": "myWorkspaceName",
   "aml-compute": {
     "name": "cpu-compute",
     "max-nodes": 4,
     "vm-size": "Standard_D4_v2",
     "vm-priority": "dedicated",
     "retian-cluster": false
   }
 }
```

### Motivation

External compute resources are very important to ML training. This will expand the functionality to the second largest cloud provider. It will also further solidify and develop the remote execution backend.

### Proposed Changes

- modify CLI for projects to accept `azure` as a backend

**Comment by smwade** [comment]
I'd love to get started on this. Let me know if you have any feedback or suggestions

**Comment by smurching** [comment]
Hi @smwade! There's now a plugin interface for running MLflow projects against custom backends - see https://mlflow.org/docs/latest/plugins.html for details. If you or someone else ends up writing a plugin for executing projects on Azure, we'd be happy to link to it / document it on mlflow.org - thanks!
