### ISSUE TITLE
[FR] Support Snowflake DB connections for SQL store

### ISSUE THREAD

**Issue by Casyfill** [mlflow/mlflow#1712]
It is a little unclear from the documentation but can I use snowflake as a backend for MLflow server (backend-store-uri)?

I tried to install the snowflake-sqlalchemy connector and pass a sqlalchemy string, but seems the mlflow itself is not validating it - any way to bypass? 

I see a corresponding db fail test - is there any reason snowflake won't suffice? 

Thanks!

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please do not delete this template unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal

Provide a clear high-level description of the feature request in the following sections. Feature requests that are likely to be accepted:
* Are minimal in scope (note that it's always easier to add additional functionality later than remove functionality)
* Are extensible (e.g. if adding an integration with an ML framework, is it possible to add similar integrations with other frameworks?)
* Have user impact & value that justifies the maintenance burden of supporting the feature moving forwards. The [JQuery contributor guide](https://contribute.jquery.org/open-source/#contributing-something-new) has an excellent discussion on this.

### Motivation
What is the use case in mind?  Why is it valuable to support, and why is it currently difficult or impossible to achieve? Could the desired functionality alternatively be implemented as a third-party package using MLflow public APIs? 

### Proposed Changes
For user-facing changes, what APIs are you proposing to add or modify? For internal changes, what code paths will need to be modified?

**Comment by ankitmathur-db** [comment]
Hi! Thanks for your feature request. As of now, we support: mysql, mssql, sqlite, and postgresql. It very well might be that adding Snowflake to [this](https://github.com/mlflow/mlflow/blob/master/mlflow/store/dbmodels/db_types.py) would work, but it's not clear - as it turns out, each dialect has slight idiosyncrasies that affect how we have to do things like write migrations.

If your use case needs Snowflake, we'd love if you could investigate and contribute your findings

**Comment by Casyfill** [comment]
Thanks for the response! Will try that, if other options won't work out for our use case.
