### ISSUE TITLE
[FR] Managed artifacts

### ISSUE THREAD

**Issue by mgbckr** [mlflow/mlflow#1723]
# Managed artifacts
## Describe the proposal
The idea is to support "managed artifacts" that allow:
* automatic artifact loading (load artifacts from a previous run replacing otherwise calculated artifacts (e.g., a sampled dataset or a trained neural network)
* automatically handling temporary folders for artifacts during parallel runs (e.g., when you run your script multiple times on the same server)
* central management of loading and logging
* less biolerplate for saving artifacts

Please note that this proposal is a rough draft for now to gauge interest. I can go into more depth about specific API specifcations. For a more complete (but by all means not a final version), please see: [mlflowhelper](https://github.com/mgbckr/mlflowhelper)

### Motivation
I have written a lot of boilerplate code to log and load artifacts. This makes the code error prone and hard to maintain since it obfuscates the actual ML code by lot's of tracking code. The tracking API should be as unintrusive as possible while still giving as much control as necessary. 

It is possible to implement the proposed functionality as a wrapper (see [mlflowhelper](https://github.com/mgbckr/mlflowhelper)) but I feel like this (or an improved version of this) should be part of the core API to improve the tracking experience.

### Proposed Changes (Python API only)
Basically, the idea is to introduce an `ArtifactManager`  that eases artifact management. However, I am only going to discuss the changes for the `fluent` API for now. Please note that this is a rough draft with quite a few missing details. For a more complete version please see: [mlflowhelper](https://github.com/mgbckr/mlflowhelper)

#### Simple artifact management. 

Takes care of logging and deleting the artifact automatically.
```python
from matplotlib import pyplot as plt
import mlflow

with mlflow.start_run():
    with mlflow.managed_artifact("plot.png") as artifact:
        fig = plt.figure()
        plt.plot([1,2,3], [1,2,3])
        fig.savefig(artifact.get_path())
```

Same works on the directory level:
```python
from matplotlib import pyplot as plt
import mlflow

with mlflow.start_run():
    with mlflow.managed_artifact_dir("plots") as artifact_dir:

        # plot 1
        fig = plt.figure()
        plt.plot([1,2,3], [1,2,3])
        fig.savefig(artifact_dir.get_path("plot1.png"))

        # plot 2
        fig = plt.figure()
        plt.plot([1,2,3], [1,2,3])
        fig.savefig(artifact_dir.get_path("plot2.png"))
```

#### Artifact loading
Artifact loading allows to load artifacts from previous runs instead of recalcualting them.
```python
import mlflow
import pandas as pd

with mlflow.start_run():
    mlflow.set_load(run_id="e1363f760b1e4ab3a9e93f856f2e9341", stages=["load_data"]) # activate loading from previous run
    with mlflow.managed_artifact_dir("data.csv", stage="load_data") as artifact:
        if artifact.loaded:
            # load artifact
            data = pd.read_csv(artifact.get_path())
        else:
            # create and save artifact
            data = pd.read_csv("/shared/dir/data.csv").sample(frac=1)
            data.to_csv(artifact.get_path())
```

Same for directories:
```python
import mlflow
import pandas as pd

mlflow.set_load(run_id="e1363f760b1e4ab3a9e93f856f2e9341", stages=["load_data"]) # activate loading from previous run
with mlflow.start_run():
    with mlflow.managed_artifact_dir("data", stage="load_data") as artifact_dir:
        train_path = artifact_dir.get_path("test.csv")
        test_path = artifact_dir.get_path("train.csv")
        if artifact_dir.loaded:
            # load artifacts
            train = pd.read_csv(train_path)
            test = pd.read_csv(test_path)
        else:
            data = pd.read_csv("/shared/dir/data.csv").sample(frac=1)
            train = data.iloc[:100,:]
            test = data.iloc[100:,:]
            # save artifacts
            train.to_csv(train_path)
            test.to_csv(test_path)
```

#### Central logging behavior

```python
import mlflow
import pandas as pd

with mlflow.start_run():

    # activate loading the stage `load_data` from previous run `e1363f760b1e4ab3a9e93f856f2e9341`
    mlflow.set_load(run_id="e1363f760b1e4ab3a9e93f856f2e9341", stages=["load_data"])

    # deactivate logging the stage `load_data`, in this case for example because it was loaded from a previous run
    mlflow.set_skip_log(stages=["load_data"])

    with mlflow.managed_artifact_dir("data", stage="load_data") as artifact_dir:
        train_path = artifact_dir.get_path("test.csv")
        test_path = artifact_dir.get_path("train.csv")
        if artifact_dir.loaded:
            # load artifacts
            train = pd.read_csv(train_path)
            test = pd.read_csv(test_path)
        else:
            data = pd.read_csv("/shared/dir/data.csv").sample(frac=1)
            train = data.iloc[:100,:]
            test = data.iloc[100:,:]
            # save artifacts
            train.to_csv(train_path)
            test.to_csv(test_path)
```

#### Notes
There are many things that are up for discussion and which can be improved in this proposal. Also some details are missing. Here are some pointers:
* API simplifications for multiple artifacts by returning paths instead of a "managed resource" object
* loading across experiments
* loading from external sources
* behavior for nested runs (at the moment this can be easily covered manually, but again, adds biolderplate code)
* load different stages from more than one run
* tracking loading behavior
* and on and on ... ;)

**Comment by pogil** [comment]
Hey @mgbckr, there definitely some interesting ideas in here and we recognize that there's room for improvement in the APIs for how people can work with artifacts. I agree that there are several things here that could be up for discussion. 

I'm hoping that as we add more clear areas of ownership for committers we can pair you up with someone that could take a closer look and have that discussion with you.

**Comment by mgbckr** [comment]
Sure thing :) Thanks for the answer.

**Comment by dbczumar** [comment]
@mgbckr Apologies for the very substantial delay here. In the time since this issue was filed, we've introduced several APIs to make it easier to log artifacts, such as `mlflow.log_image()` (https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_image) and `mlflow.log_text()` (https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_text), which automatically handle persistence of artifact content to files, logging, and file cleanup. Accordingly, I'm going to go ahead and close this issue for now. Please feel free to reopen it if you believe there's significantly more work to be done. Thank you for your usage of MLflow!
