### ISSUE TITLE
[FR] Implement autolog for tensorboardX support for pytorch

### ISSUE THREAD

**Issue by zhangruiskyline** [mlflow/mlflow#1731]
## Describe the proposal

Right now we have autolog feature to automatically log tensorboard tracking status into mlflow tracking in tensorflow and keras, would like to have this feature also in pytorch(tensorboardX)

smoothly integrate current pytorch based machine learning code base into mlflow

### Motivation

can help to migrate pytorch code which uses tensorboardX tracking easily into mlflow

### Proposed Changes
mlflow.pytorch.autolog()

**Comment by johny-c** [comment]
This would be really useful ;)
