### ISSUE TITLE
Dose MLflow support distributed TensorFlow?

### ISSUE THREAD

**Issue by pingsutw** [mlflow/mlflow#1732]
If I run distributed tensorflow on 4 machines, dose mlflow still store those job in one run id ?
Could i also reproduce distributed tensorflow by running mlflow model ?
if mlflow support this, where can i find the document about this
Thanks in advanced.

**Comment by jdlesage** [comment]
I didn't find any doc on this. But in on our hadoop cluster, we will be able to do register distributed tensorflow run. 
Before to launch your workers, create a run and get the run_id
Then on all workers, set MLFLOW_RUN_ID with this id + MLFLOW_TRACKING_URI with your mlflow server adress. All workers will log into the same run.

**Comment by pingsutw** [comment]
@jdlesage Thanks for your reply,dose you use TonY ? 
I tried create run_id before run application.
I am working on Hadoop-submarine (ML on Yarn), I'm trying to do a sdk for distributed deep learning on yarn  
So that user can just easily use **log_metric(....)** and **log_param(....)** and then store this data with applicationID or job-name instead of run_id

**Comment by jdlesage** [comment]
At criteo, we develop tf-yarn (https://github.com/criteo/tf-yarn) to run tensorflow on yarn. 
Run_id is set by mlflow. I think you should let the server to create a run_id and not enforce it.
If you set the MLFLOW_RUN_ID environment variable, you can then use this API https://www.mlflow.org/docs/latest/python_api/mlflow.html that does not take as parameter run_id.

**Comment by pingsutw** [comment]
I'm doing another python SDK not MLflow
We try to use MLflow in our project in beginning,but when we launch yarn application, 
we can have ApplicationID and user_name and other detail in yarn 
We don't want to store duplicate data from mlflow in our server, 
btw we just want tracking metric and param.
So we want to do a lightweight sdk for our project
How do you thought about this.
I want to know how will you solve there problem.

**Comment by fhoering** [comment]
@pingsutw 
If you need some example, at Criteo, we added default mlflow metrics to [tf-yarn] (https://github.com/criteo/tf-yarn).
In the distributed case it basically works with a [TensorFlow hook](https://github.com/criteo/tf-yarn/blob/master/tf_yarn/metrics.py#L83) that only logs from a chief node (in order not to spam mlflow when running with 100s or workers). You can also filter on other roles like evaluator & workers
