### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by pandae7** [mlflow/mlflow#1736]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please do not delete this template unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Provide a clear high-level description of the feature request in the following sections. Feature requests that are likely to be accepted:
* Are minimal in scope (note that it's always easier to add additional functionality later than remove functionality)
* Are extensible (e.g. if adding an integration with an ML framework, is it possible to add similar integrations with other frameworks?)
* Have user impact & value that justifies the maintenance burden of supporting the feature moving forwards. The [JQuery contributor guide](https://contribute.jquery.org/open-source/#contributing-something-new) has an excellent discussion on this.

### Motivation
What is the use case in mind?  Why is it valuable to support, and why is it currently difficult or impossible to achieve? Could the desired functionality alternatively be implemented as a third-party package using MLflow public APIs? 

### Proposed Changes
For user-facing changes, what APIs are you proposing to add or modify? For internal changes, what code paths will need to be modified?

**Comment by pandae7** [comment]
There is an example in mlflow documentation on how to run the project published on Github, here is the command which we are supposed to use

**mlflow run https://github.com/mlflow/mlflow-example -P alpha=0.3**

This works fine, Now when i try to run an example give in the master branch it gives me a different error

**mlflow run https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine -P alpha=0.4**

the above command is what I've used and the error is - 


> from collections import Container, Iterable, MutableSet
> /home/pandae/anaconda3/lib/python3.7/site-packages/jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   from collections import MutableMapping
> /home/pandae/anaconda3/lib/python3.7/site-packages/jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   from collections import Mapping
> 2019/08/14 10:12:23 INFO mlflow.projects: === Fetching project from https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine into /tmp/tmpg5l5fcbf ===
> Traceback (most recent call last):
>   File "/home/pandae/anaconda3/bin/mlflow", line 10, in <module>
>     sys.exit(cli())
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/mlflow/cli.py", line 137, in run
>     run_id=run_id
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 265, in run
>     use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 86, in _run
>     work_dir = _fetch_project(uri=uri, force_tempdir=False, version=version)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 390, in _fetch_project
>     _fetch_git_repo(parsed_uri, version, dst_dir)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 430, in _fetch_git_repo
>     origin.fetch()
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/git/remote.py", line 790, in fetch
>     res = self._get_fetch_info_from_stderr(proc, progress)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/git/remote.py", line 674, in _get_fetch_info_from_stderr
>     proc.wait(stderr=stderr_text)
>   File "/home/pandae/anaconda3/lib/python3.7/site-packages/git/cmd.py", line 412, in wait
>     raise GitCommandError(self.args, status, errstr)
> git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
>   cmdline: git fetch -v origin
>   stderr: 'fatal: repository 'https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine/' not found'

**Comment by pandae7** [comment]
So how exactly are we supposed to run any example on Github using **https** link and not **ssh**

**Comment by apurva-koti** [comment]
https://github.com/mlflow/mlflow-example is a git repository. https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine/ is not a git repository - it is a folder within a git repository.
You can run MLflow projects directly from Git if you provide as an argument a link to a git repository (which contains a valid MLProject file).
