### ISSUE TITLE
[BUG]MlflowException: Could not find an "MLmodel" configuration file at "/ceph/yuanjie/6_FeatureTools/automated-feature-engineering/walk_through/spark-model"

### ISSUE THREAD

**Issue by Jie-Yuan** [mlflow/mlflow#1738]
MlflowException: Could not find an "MLmodel" configuration file at "/ceph/yuanjie/6_FeatureTools/automated-feature-engineering/walk_through/spark-model"

**Comment by apurva-koti** [comment]
Hello,
Far more information is needed to effectively diagnose this bug. Please file another issue and fill out the template.
