### ISSUE TITLE
How to server?

### ISSUE THREAD

**Issue by Jie-Yuan** [mlflow/mlflow#1739]
![image](https://user-images.githubusercontent.com/20265321/63087850-b6351b00-bf85-11e9-9b35-7dab61ede0de.png)

mlflow models serve --model-uri runs:/Users/yuanjie/Desktop/Projects/Python/tql-Python/examples/deploy/mlruns/0/3f52da7ab25649de825ed8d344ea4be6/artifacts/
---
mlflow.exceptions.MlflowException: Run 'Users' not found

**Comment by apurva-koti** [comment]
Please fill out the respective issue template with the relevant information for your concern.
