### ISSUE TITLE
[SETUP-BUG]

### ISSUE THREAD

**Issue by sifanLV** [mlflow/mlflow#1748]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker Base Image [python:3.7-stretch](https://github.com/docker-library/python/tree/master/3.7/stretch)
- **MLflow installed from (source or binary)**: Installed through pip
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 3.7.4
- **Exact command to reproduce**: 
```
mlflow server \
    --backend-store-uri "$MLFLOW_SERVER_FILE_STORE" \
    --default-artifact-root "$MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT" \
    --host "$MLFLOW_SERVER_HOST" \
    --port "$MLFLOW_SERVER_PORT" \
    --workers "$MLFLOW_SERVER_WORKERS"
```

### Describe the problem
Provide the exact sequence of commands / steps that you executed before running into the problem.
`mlflow server` set as CMD executable in Dockerfile. Container could not start due to the following error.
### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert explicit value for identity column in table 'experiments' when IDENTITY_INSERT is set to OFF. (544) (SQLExecDirectW)")

```

**Comment by seeder** [comment]
Back on 0.9.1 , I had devised a fix in sqlalchemy_store.py  : 
https://github.com/gnrkou/mlflow/commit/e3208168c5a9654a795467a1c7e8d18d6b4e94dc#diff-9dbd29fa18674e2743b2073bca3e250d
