### ISSUE TITLE
[FR] Parallel Coordinate Plot Enhancements

### ISSUE THREAD

**Issue by bfowler1** [mlflow/mlflow#1752]
## Describe the proposal
Allow for zoom functionality on the parallel coordinate plot similar to the zoom functionality in the scatter plot.

**Comment by bfowler1** [comment]
Correction, params are noted on the left portion of the plot. Adding a zoom functionality to the plot would still be helpful.

**Comment by Zangr** [comment]
@bfowler1 Thank you for submitting the feature request. Could you please elaborate more on your specific use case where zoom can help?
