### ISSUE TITLE
[BUG] tracking server worker timeout

### ISSUE THREAD

**Issue by mrmutator** [mlflow/mlflow#1760]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**: 3.6.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: -

### Describe the problem
When using a remote tracking server, the tracking server sometimes gets stuck and then connections from the clients are refused. Since MLFlow on the client side is not able to set the logged metrics to the tracking server, an exception is raised and the experiment script is aborted.

### Code to reproduce issue
I use a remote tracking server and S3 as an artifact storage. The training loss is communicated to the tracking server after each step (approx. 1 per second). After an entire epoch, various metrics are sent to the server and some rather large artifacts are uploaded to an S3 instance.

### Suggestion
The server should be a bit more robust. And ideally the client as well. There should be a fallback option that logs the metrics locally if the tracking server is unavailable.

**Comment by dbczumar** [comment]
This class of performance issues has been addressed by #1767 and #1805. These changes will be incorporated into the next MLflow release. In the mean time, you can test the changes by cloning the MLflow repository running the MLflow tracking server on the `master` branch. If this issue is still occurring, please feel free to re-open the ticket.
