### ISSUE TITLE
[BUG] mlflow run MLproject failed but same python command worked

### ISSUE THREAD

**Issue by zhangruiskyline** [mlflow/mlflow#1762]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu VERSION="18.04.2 LTS (Bionic Beaver)"

- **MLflow installed from (source or binary)**: 
pip

- **MLflow version (run ``mlflow --version``)**:
1.2.0

- **Python version**: 
3.6

### Describe the problem

I have set up a **MLproject** like this

```
name: Same as project folder name

conda_env: conda.yaml

entry_points:
  main:
    command: "python some.py -p some.json"
```

when I execute "`mlflow run /project folder/`", I always get some error like 

 ```
 File "/home/miniconda/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/home/miniconda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/miniconda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/miniconda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/miniconda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/miniconda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/cli.py", line 137, in run
    run_id=run_id
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 266, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 94, in _run
    active_run = _create_run(uri, experiment_id, work_dir, entry_point)
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/projects/__init__.py", line 622, in _create_run
    active_run = tracking.MlflowClient().create_run(experiment_id=experiment_id, tags=tags)
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 88, in create_run
    tags=[RunTag(key, value) for (key, value) in iteritems(tags)]
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 153, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 64, in _call_endpoint
    response = self._verify_rest_response(response, endpoint)
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 47, in _verify_rest_response
    return verify_rest_response(response, endpoint)
  File "/home/miniconda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 84, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: experiment_id must be set to a non-zero value
```

however, when I directly execute the python command in MLproject command "python some.py -p some.json", it works and can correctly log stuff into my MLflow server in Azure data bricks

anything wrong with MLproject? and do I use it in correct way?

Thanks
Rui

**Comment by dbczumar** [comment]
@zhangruiskyline When running an MLflow project that logs to the Databricks-hosted MLflow server, your project code must explicitly set a valid experiment name. If you do not explicitly set an experiment, the default value is `0`, which is not a valid experiment id in Databricks.

Please try adding a call to `mlflow.set_experiment(/path/to/workspace/experiment)` in your project's training code and let me know if this resolves your issue.

**Comment by zhangruiskyline** [comment]
Thanks, @dbczumar , Yes we have set the experiment as follow.

BTW, also how to we pass around the experiment_id for different part in our code? looks like if we just define experiment_id here, if we try to log_params somewhere else we get error that no experiment_id found

```
if __name__ == "__main__":
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
    params = parse_args(sys.argv)
    exp_id = mlflow.set_experiment('/Users/xxx/myflow_exp1')
    mlflow.start_run(experiment_id=exp_id, run_name="online")
    main(params)
```

**Comment by dbczumar** [comment]
@zhangruiskyline Can you provide an example of a `log_param` call in your `main()` method that fails? The `set_experiment` call should automatically set the experiment ID for all subsequent runs.

**Comment by zhangruiskyline** [comment]
@dbczumar the code flow is like this

so if experiment_id can not be passed by

```
def main(params):
    # Lots of code
       for key, value in params.items():
        mlflow.log_param(key, value)

if __name__ == "__main__":
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
    params = parse_args(sys.argv)
    exp_id = mlflow.set_experiment('/Users/zhrui@microsoft.com/horizon_DLTS')
    mlflow.start_run(experiment_id=exp_id, run_name="online")
    main(params)
```

**Comment by dbczumar** [comment]
@zhangruiskyline After calling `mlflow.set_experiment` within a Python process, all calls to `mlflow.start_run()` should automatically use the experiment you specified. There is no need to explicitly pass `experiment_id` to `start_run()`.

**Comment by zhangruiskyline** [comment]
Hi @dbczumar , I got the same error as before 
`mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: experiment_id must be set to a non-zero value`

I try to directly run the `some.py -p some.json `and via `mlflow run /myproject/`, but give same error

seems experiment ID is not globally recognized yet, but If I set the experiment right before my para log, it works at least for directly python call.

any clue? or any environment variable I am missing?

**Comment by dbczumar** [comment]
@zhangruiskyline My mistake! The target experiment for the MLflow project run is determined before the entrypoint script is executed. Calls to `set_experiment` within the project's training code are ignored.

You should be able to set the `MLFLOW_EXPERIMENT_NAME` environment variable before running the project. This will log results to the appropriate experiment. For example:

```
MLFLOW_EXPERIMENT_NAME='/Users/zhrui@microsoft.com/horizon_DLTS' mlflow run /myproject/
```

Can you try this and let me know if it's successful for your use case?

**Comment by zhangruiskyline** [comment]
Hi @dbczumar  Thanks for help

with the environment variable set up, I am able to run python script directly successfully without set the experiment ID

but somehow if I run mlflow project, it will need to first create the conda env, and then pip install, and then conda activate, but still failed since we are running in some docker container environment do not have permission to do lots of things.,

 so I wonder if I need to do all those manual step by step, then it seems I can not automation mlflow project. For my use case, I will host MLproject in Azure databricks, but our training job and some preprocess like spark and normalization python job are all running in a remote SSH connected cluster. Can we define our MLproject in Azure databricks, and then define our MLproject workflow in Azure data bricks, but the command will be ssh to remote training cluster to execute the python or spark script?

what should be best practice here?

**Comment by andrewbrooks-o** [comment]
@dbczumar - I'm experiencing the same pain as @zhangruiskyline using databricks hosted MLFlow tracking.

I'd like the experiment to be set or created dynamically per the configurations in a config.yaml, like this:

```
mlflow run ./ -e train -P config=config.yaml
```

While I can specify the `--experiment-id` argument in `mlflow run`, this requires the experiment to have already been created and named.  I'd like to wrap this up in the train endpoint.  

```
mlflow run ./ -e train --experiment-id 83818 -P config=config.yaml
```

Is it possible to have the entry point determine experiment to set or create?


Minimal example of what I'd like to do:

**MLProject**
```
name: myproject

conda_env: conda.yaml

entry_points:
  train:
    parameters:
      config: {type: string, default: "config.yaml"}
    command: "python train.py --config {config}"
```

**train.py**
```python

def init_experiment(experiment_name, artifact_location):
    existing_experiments = mlflow_client().list_experiments()
    if experiment_name in [exp.name for exp in existing_experiments]:
        mlflow.set_experiment(experiment_name)
    else:
        mlflow.create_experiment(experiment_name, artifact_location=artifact_location)

init_experiment('my_exp', 's3://mybucket/mypath')
# model training code ... 
```

**config.yaml**
```yaml
mlflow:
  databricks_token: "MYTOKEN"
  experiment_name: "/Users/myuser/myexperiment"
```

**Comment by ohindialign** [comment]
Hey Guys, Do you have any conclusion to share? I'm facing this issue too.

I'm trying to run mlflow projects from a databricks job using mlflow.run(uri="uri", parameters=<params> ) , at the moment im running mlflow project example from github.

I want the experiment + run to be set dynamically per project from the code - in mlflow example from train.py.
Inside train.py I have mlflow.set_experiment('my exp') and after this mlflow.start_run(),
I saw @dbczumar mentioned that all calls of set_experiment are ignored, which mean in my use case i need to set the exp name and run name manually at the start of job run ( pass them as parameters into mlflow.run ( ) ).
When i specify those params inside the mlflow.run and wanted to create a nested run within my python code i got unexpected results ( swapped between run names and duration), and actually one run got a random name instead the name the specified.


Besides, Im getting an errror from databricks on creating an experiment from a job if the exp_name isn't specified in the run call. 

Is there a way to run mlflow project without specify exp_name / run_name and let it specified by the code?
Thanks.
