### ISSUE TITLE
[FR] S3 Artifact Repository: ServerSideEncryption support

### ISSUE THREAD

**Issue by MFreidank** [mlflow/mlflow#1764]
## Describe the proposal
Currently, the S3 artifact repository as implemented in `mlflow/store/s3_artifact_repo` does not allow one to specify arguments that pertain to server side encryption when communicating with S3.  
This would require passing e.g. `ExtraArgs={"ServerSideEncryption": "aws:kms"}` as additional argument to `s3_client.upload_file` (see lines [38](https://github.com/mlflow/mlflow/blob/0ff05042fb4c67b6fd3fe63a88b2a8946860e026/mlflow/store/s3_artifact_repo.py#L38) and [53](https://github.com/mlflow/mlflow/blob/0ff05042fb4c67b6fd3fe63a88b2a8946860e026/mlflow/store/s3_artifact_repo.py#L53) respectively). 
Note that in production environments, there is frequently a security requirement forcing developers to use server side encryption. More generally, the design of artifact stores currently does not allow passing any additional keyword arguments from `mlflow.log_artifact` or `mlflow_client.log_artifact` that may then be forwarded to the underlying store a user specified as tracking URI. 

### Motivation
Passing down additional (keyword) arguments to the artifact repositories they register via tracking URI is currently not possible, but would allow users to specify repository-specific settings like server-side encryption for AWS (or storing metadata alongside artifacts on S3, etc). I don't believe this should be implemented as a third-party package. The functionality can be hacked  into `mlflow` via monkey-patching of logging and store functions, but this is highly suboptimal.

### Proposed Changes
1. Extend `mlflow.log_artifact`, `mlflow.log_artifacts` and `mlflow_client.log_artifact`, `mlflow_client.log_artifacts` to pass keyword arguments down to the artifact repository used. 
2. Make artifact repositories (in particular `s3_artifact_reposito.S3ArtifactRepository`) receive and pass these keyword arguments on whereever it is useful.

I am willing to help put together a pull request (and have some code ready for the S3 case) for this feature, but would first like to pick your brain on this feature.

**Comment by SagurovA93** [comment]
@MFreidank I'm testing now mlflow with S3 bucket as artifact storage. 
I did not find any words about S3 SSE KMS support in documentation: https://www.mlflow.org/docs/latest/tracking.html

Am I right that MLFlow tracking server does not support S3 SSE KMS at this moment?

**Comment by MFreidank** [comment]
@SagurovA93 Correct. I was proposing to add support for SSE KMS (and other potential keyword parameters of S3) and outlining one way to achieve it. I have some code ready for how an implementation could look. 

@mparkhe You seem to have worked on S3 artifact repo and others. Could you have a look/share your opinion?

**Comment by MFreidank** [comment]
Any comments on this request?

**Comment by tallen94** [comment]
I think this would be a good enhancement, especially pertaining to pickle files. We have requirements around ensuring pickle files are encrypted in order to prevent data leakage and verify integrity when de-serializing them. It would be nice to have the upload function for artifacts specify and encryption method.

**Comment by dbczumar** [comment]
Now that #1300 has been merged and released, I'm going to go ahead and close this issue! Please let me know if additional support is missing in this area.
