### ISSUE TITLE
[BUG] Only meta.yaml file with mlflow and Apache Spark modeling

### ISSUE THREAD

**Issue by gfleetwood** [mlflow/mlflow#1771]
**System information**

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Custom Code 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**:  source (with pip)
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 3.6.3 (through Anaconda)
- **npm version, if running the dev UI**: NA
- **Exact command to reproduce**: See below

**Describe the problem**

Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

I used mlflow to log a parameter and a metric of an Apache Spark Logistic Regression model. and save the model. When I checked the '0' subfolder (for the experiment) of the mlruns folder the only content was a meta.yaml file. 

If it's relevant, I did something similar on a difference machine (Windows 10) using scikit-learn and there were no issues.

**Code to reproduce issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
with mlflow.start_run():
    
    mdl = LogisticRegression()
    #evaluator = BinaryClassificationEvaluator()
    evaluator = MulticlassClassificationEvaluator(metricName = "accuracy")

    grid = ParamGridBuilder()
    grid = grid.addGrid(mdl.regParam, np.arange(0, .1, .01))
    grid = grid.addGrid(mdl.elasticNetParam, [0, 1])
    grid = grid.build()

    cv = CrossValidator(estimator = mdl, evaluator = evaluator, estimatorParamMaps = grid, numFolds = 5)  
    training = cv.fit(train)
    
    mlflow.log_param("agg_depth", training.bestModel._java_obj.getAggregationDepth())
    mlflow.log_metric("accuracy", np.mean(training.avgMetrics))
    #mlflow.spark.log_model(training.bestModel, "mdl_los_spark")
```

**Other info / logs**

NA

**Comment by dbczumar** [comment]
@gfleetwood Did you specify a tracking URI before running your logging code? The model, parameter, and metric are logged to the location specified by the tracking URI. If you did not specify a URI, these outputs should be present within the `mlruns/{experiment_id}` subdirectory of your current working directory.

**Comment by gfleetwood** [comment]
No, I didn't. When I used the scikit-learn mlflow workflow (on the Windows machine) all the info for runs was in `mlruns/0` along with the meta.yaml file. However, with the code above I only had `mlruns/0/meta.yaml` and nothing else.
