### ISSUE TITLE
mlflow tracking server

### ISSUE THREAD

**Issue by whillas** [mlflow/mlflow#1790]
I'm trying to setup a central MLFlow server and artifact store for our team to log and store models and their artifact. Is this possible with MLFlow? Eventually this will be run on a Kubernetes cluster and a shared NAS drive will be mounted for the server to write to...

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**:1.2.0
- **Python version**: 3.6.8
- **Exact command to reproduce**: 

```
version:  '3'
services:
  # docker-compose run mlflow
  mlflow:
    image: 192.168.1.84:6666/mlflow-server
    command: mlflow server --host 0.0.0.0
    ports:
      - "5000:5000"
    container_name: mlflow-server

    command: >
      mlflow server 
        --backend-store-uri sqlite:///app/mlflow.db
        --default-artifact-root sftp://mlflowuser:mlflowuser@192.168.1.25/
        --host 0.0.0.0
    volumes:
       - /home/alex/dev/mlflow:/app
```
then `docker-compose up`

Also set `MLFLOW_TRACKING_URI=127.0.0.1:5000`

then when i run the example:

` python remote_store/remote_server.py`

### Describe the problem

```
18:15 $ python remote_store/remote_server.py
Running remote_store/remote_server.py with tracking URI 127.0.0.1:5000
Metadata & data for run with UUID 564c1263e0a7490c946d1acf991186a6: <Run: data=<RunData: metrics={'foo': 7.0, 'random_int': 11.0}, params={'param1': '5'}, tags={'mlflow.source.git.commit': 'cf248098793bd1d750830a58c9ec8bfbdefed89f',
 'mlflow.source.name': 'remote_store/remote_server.py',
 'mlflow.source.type': 'LOCAL',
 'mlflow.user': 'alex'}>, info=<RunInfo: artifact_uri='127.0.0.1:5000/0/564c1263e0a7490c946d1acf991186a6/artifacts', end_time=None, experiment_id='0', lifecycle_stage='active', run_id='564c1263e0a7490c946d1acf991186a6', run_uuid='564c1263e0a7490c946d1acf991186a6', start_time=1566973136383, status='RUNNING', user_id='alex'>>
Traceback (most recent call last):
  File "remote_store/remote_server.py", line 32, in <module>
    log_artifacts(local_dir, "some_subdir")
  File "/home/alex/dev/mlflow/__modules__/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 277, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/alex/dev/mlflow/__modules__/lib/python3.6/site-packages/mlflow/tracking/client.py", line 253, in log_artifacts
    artifact_repo = get_artifact_repository(run.info.artifact_uri)
  File "/home/alex/dev/mlflow/__modules__/lib/python3.6/site-packages/mlflow/store/artifact_repository_registry.py", line 100, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/alex/dev/mlflow/__modules__/lib/python3.6/site-packages/mlflow/store/artifact_repository_registry.py", line 68, in get_artifact_repository
    artifact_uri, list(self._registry.keys())
mlflow.exceptions.MlflowException: Could not find a registered artifact repository for: 127.0.0.1:5000/0/564c1263e0a7490c946d1acf991186a6/artifacts. Currently registered schemes are: ['', 'file', 's3', 'gs', 'wasbs', 'ftp', 'sftp', 'dbfs', 'hdfs', 'runs']
```
I've also tried 
`--default-artifact-root /someplace` and `--default-artifact-root file:/someplace` and I'm getting the same error on the client.

I don't understand the note in the docs:
> If you do not specify a --default-artifact-root or an artifact URI when creating the experiment ...  the artifact root is a path inside the file store. Typically this is not an appropriate location, as the client and server probably refer to different physical locations (that is, the same path on different disks).

Particularly "client and server probably refer to different physical locations"? I thought the client would send the artifacts to the server and it would take care of storing it? Or is the client supposed to write to the same location that is shared by the server? If so, how am I supposed to configure this to do that?

**Comment by brewkode** [comment]
If you don't specify the `MLFLOW_TRACKING_URI` as an environment variable for the client or call `set_tracking_uri` with the tracking server uri, it would record it in the local file system.

**Comment by whillas** [comment]
AGH! the problem was that I did `export MLFLOW_TRACKING_URI=192.168.1.25:5000` instead of `export MLFLOW_TRACKING_URI=http://192.168.1.25:5000. :(..
