### ISSUE TITLE
mlflow run from private github repository

### ISSUE THREAD

**Issue by mhs321** [mlflow/mlflow#1791]
In version 0.9.1 we can run mlflow projects from private github repositories by providing the following parameters 

```
--git-username <git user name>
--git-password <access token>
```

As of version 1.2 these parameters are no longer available via the cli.

Can we bring this back? Or what is the current way to run mlflow projects from private github repositories? I have not found any documentation to do this yet for version 1.2

**Comment by nlaille** [comment]
@mhs321 mlflow is using gitpython to fetch git project : https://github.com/mlflow/mlflow/blob/master/mlflow/projects/__init__.py#L429 
> Assumes authentication parameters are specified by the environment, e.g. by a Git credential helper.

But using an ssh url is working out of the box if you have setup an ssh key.

`mlflow run git@github.com:username/my-private-repo`

**Comment by mhs321** [comment]
@nlaille Thanks for the update. I can confirm that using ssh url works fine.

**Comment by rafmacalaba** [comment]
how does this work in a private gitlab repository?

**Comment by tgy** [comment]
@rafmacalaba it should be exactly the same
