### ISSUE TITLE
[BUG] Building docker container fails

### ISSUE THREAD

**Issue by mazzma12** [mlflow/mlflow#1793]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18 Bionic)**:
- `docker build -t mlflow . `: 

Hi, when I try to build the container it fails : 
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'travis/small-requirements.txt'
```
It looks like it's only meant for Travis CI, but couldn't find a mention in the doc

**Comment by ustcscgyer** [comment]
If no one is working on this, I can take a look.

**Comment by brewkode** [comment]
The RCA for this is the entries in `.dockerignore`. I tried setting it up too and found that `.dockerignore` has `.travis` & `tests` in them. `ADD` in Dockerfile skips over the entries in dockerignore file. Try commenting out the necessary dirs and see how things go.
