### ISSUE TITLE
[FR]Running from a Branch and other doubts

### ISSUE THREAD

**Issue by pandae7** [mlflow/mlflow#1794]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

I have multiple feature requests and I'm listing them one by one:
lets assume we have a git repository which has multiple folders containing ML projects in the same folder structure given by MLFlow 
eg - one folder named sklearn_elasticnet_wine on the master branch has mlproject file, conda.yaml, train.py, wine-quality.csv .

## Describe the proposal

1. let's say we also have a branch named "dev" other than master branch on our repository, and it also has a ML project (has a valid MLProject file). We intend to run it too from our terminal using
   **mlflow run <git repo url/tree/dev>** 
-even this doesn't work, Is there anyway to work around this?

 **Motivation for point no 1** - Want to run a developing model which is on a git branch.

 **MLFlow claims that we can deploy our mlflow projects anywhere and reproduce runs**

2. If we want to upload our ML project which is on our local machine onto git, we are supposed to do it manually using general git commands, is there any particular support mlflow is providing to push everything onto github?
 
**Motivation for point no 2** - We want mlflow to support us in sharing the project on git. 

3. Whenever we run a ML project, mlflow creates a mlruns folder, Now let's say I pushed this on to a git repository. Now, Some other guy who has access to the same git repository wants to reproduce one of the runs. How can we do it?

**Comment by nlaille** [comment]
Some remarks that might help you.

1. You can use --version option from run 

`mlflow run <git repo url> --version dev`
`mlflow run --help`

> -v, --version VERSION        Version of the project to run, as a Git commit reference for Git projects.

2. You should consider using a tracking server : https://www.mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers 

3. When viewing a specific run in mlflow ui : 
<img width="1323" alt="Capture d’écran 2019-09-01 à 16 58 47" src="https://user-images.githubusercontent.com/5285727/64078326-aafa2300-ccd9-11e9-97fe-600df52baac9.png">

**Comment by dbczumar** [comment]
@nlaille Thank you for addressing each of these questions - these are great responses in line with our best practice recommendations. @pandae7  if you're still having difficulty with any of these tasks, please feel free to reopen this issue.
