### ISSUE TITLE
Is there any limitation for the data size to be served using REST API?

### ISSUE THREAD

**Issue by FredYao** [mlflow/mlflow#1795]
I am new to the REST API. I have a sklearn model and built a service for serving incoming prediction request. As the document indicates, I started a mlflow server:
"mlflow models serve --no-conda -m /path/to/mlflowmodel -p 1234"

I am calling the REST API through curl command:
"curl http://w.x.y.z:1234/innovations -H 'Content-Type: application/jsob; format=pandas-records' -d [[1,2,3],[4,5,6],[7,8,9],...]]' "

My concern is that how many records that I can pass through this curl command? Can I pass 1M records? What is the best practice if I want to predict 1M+ records using the REST API?
BTW, is there a way to pass a text file which has all records to be predicted?

Thanks.

**Comment by RexG** [comment]
MLflow uses Gunicorn as the HTTP server.. and for Gunicorn, different from Tomcat which use attribute **maxPostSize** to limit the post payload size, looks like there is no limit now... which makes attribute **timeout** important..
