### ISSUE TITLE
[SETUP-BUG] ResolvePackageNotFound - python=3.5.2

### ISSUE THREAD

**Issue by FredYao** [mlflow/mlflow#1796]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**:  binary (pip install mlflow)
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: mlflow models build-docker -m /path/to/model -n "my-model" 

### Describe the problem
mlflow models build-docker -m /path/to/model -n "my-model"

### Other info / logs
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your condadependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Pleaseadd an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound:
  - python=3.5.2

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/miniconda/lib/python3.7/site-packages/mlflow/models/container/__init__.py", line 102, in _install_pyfunc_deps
    raise Exception("Failed to create model environment.")
Exception: Failed to create model environment.
creating and activating custom environment
The command '/bin/sh -c python -c                 'from mlflow.models.container import _install_pyfunc_deps; _install_pyfunc_deps("/opt/ml/model", install_mlflow=False)'' returned a non-zero code: 1

**Comment by AlistairLR112** [comment]
bumping as I am experiencing this too

**Comment by AlistairLR112** [comment]
Python 3.5.2 is no longer available on the conda-forge repo

**Comment by AlistairLR112** [comment]
It seems like databricks clusters (if you built it on Databricks) run python 3.5.2
