### ISSUE TITLE
Cannot find module in Docker container

### ISSUE THREAD

**Issue by mhs321** [mlflow/mlflow#1797]
When I run the sample it seems that the docker container does not contain the required modules:

`2019/08/30 07:51:51 INFO mlflow.projects: === Running command 'source activate mlflow-da39a3ee5e6b4b0d3255bfef95601890afd80709 1>&2 && python train.py --alpha 0.5 --l1-ratio 0.1' in run with ID '9e2a8c9ee0a045e0a639ac177748fcf8' === 
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
`

I have confirmed that my local docker image container the required packages.

**Comment by nlaille** [comment]
@mhs321 can you provide a full example ? MLProject file and command line you are using.

**Comment by mhs321** [comment]
@nlaille 

I am using the mlflow example found here: https://github.com/mlflow/mlflow/tree/master/examples/docker

Some adjustments I made:

Dockerfile:
`FROM ubuntu:18.04

# Install python 3
RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN pip install mlflow>=1.0 \
    && pip install azure-storage==0.36.0 \
    && pip install numpy==1.14.3 \
    && pip install scipy \
    && pip install pandas==0.22.0 \
    && pip install scikit-learn==0.19.1 \
    && pip install cloudpickle

CMD ["/bin/bash"]`

MLproject:
`name: docker-sample

docker-env:
  image: mlflow-docker:latest

entry_points:
  main:
    parameters:
      alpha: float
      l1_ratio: {type: float, default:0.1}
    command: "python train.py --alpha {alpha} --l1-ratio {l1_ratio}"`

Command line:
`mlflow run <directory containing MLproject> -P alpha=0.5 -P l1_ratio=0.1`

The docker image I created was named mlflow-docker.

**Comment by nlaille** [comment]
You are having a typo in your MLProject file.
`docker-env` instead of `docker_env`.

**Comment by mhs321** [comment]
@nlaille thanks. That fixed the issue.
