### ISSUE TITLE
[FR] UI Metric: Adding an additional plot.

### ISSUE THREAD

**Issue by Roffild** [mlflow/mlflow#1806]
On the page for comparing metrics of one run, there is not enough opportunity to add an additional plot.
This is necessary when the compared metrics have too different ranges of values.

For example:
first plot with a range of 1000, 5000
second plot with a range of 0.0, 1.0

**Comment by johny-c** [comment]
I agree this is much needed. In my opinion, there should be an "add new plot" button, so the user can separate the metrics as he chooses. And each newly created plot should have a close/delete button.

**Comment by smurching** [comment]
Thanks @Roffild, @johny-c, I've filed this in our backlog for future consideration

**Comment by johny-c** [comment]
Hi @smurching , you mean querying via code, right? Regarding customized dashboards, I recently discovered [redash](https://github.com/getredash/redash). It would be amazing if this kind of functionality was integrated in mlflow.

**Comment by johny-c** [comment]
Well, I guess someone at databricks had the same thought :P 
[databricks acquires redash](https://techcrunch.com/2020/06/24/databricks-acquires-redash-a-visualizations-service-for-data-scientists/?guccounter=1&guce_referrer=aHR0cHM6Ly9kdWNrZHVja2dvLmNvbS8&guce_referrer_sig=AQAAABO-TnUR3hfSbDftd62tyHw2gAJ4tg3T8oKK48DwBHYaTO0lmsDVNO2i6GkW3KLOriTlzYL8W2hnT1ZzNkNicnCT3A0a5iz8JUUSvlb7g3qUVLYZqS63EEceI6EVpZYxMA9fvqfCUFgaPvUxAl6yNYPQ2HhSYvZRCjOC2TuQheI8)

**Comment by smurching** [comment]
@johny-c haha :P - yeah I think an example demonstrating how to display & query MLflow experiment data with redash would make a lot of sense. Looks like redash supports JSON-over-HTTP as a datasource ([see docs](https://redash.io/help/data-sources/querying/json-api)). Thus it could be worth looking into building a redash dashboard backed by the MLflow search API - if you or someone else is interested in investigating, we'd be happy to provide guidance & could document the solution publicly on https://mlflow.org/!

**Comment by johny-c** [comment]
@smurching , that's great, I didn't know about JSON as datasource. For me it is hard to dedicate time now, as I'm trying to finish my PhD..
