### ISSUE TITLE
[BUG] Race condition in create_experiment with PostgresSql Backend

### ISSUE THREAD

**Issue by elixxx** [mlflow/mlflow#1811]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: We wrapped Scala around the Java Implementation but this is pretty sure not influencing the issue
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 10 
- **MLflow installed from (source or binary)**: pypi
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.1.0
- **Python version**: 3.6.9
- **Exact command to reproduce**: create_experiment(self, name, artifact_location=None):

### Describe the problem
If multiple runs of the same experiment starts simultaneously and execute the create_experiment rest call. Our PostgresSQL throws following error:
ERROR:  duplicate key value violates unique constraint "experiments_name_key"
DETAIL:  Key (name)=(***) already exists.
INSERT INTO experiments (name, artifact_location, lifecycle_stage) VALUES ('***', '', 'active') RETURNING experiments.experiment_id

### expected behavior ###
Multiple create_experiment calls with the same experiment name will return the same unique experiment-id, so parallel/distributed training is easily possible.

### Relatives ###
Here we need a lock and/or create_or_get experiment-id handling:
https://github.com/mlflow/mlflow/blob/30a90ec9cbffa5c0d0212368b9f2a7e8c8a3fc81/mlflow/store/sqlalchemy_store.py#L238

**Comment by elixxx** [comment]
Still an issue

**Comment by aim-nfunke** [comment]
@Zangr Still an issue.

**Comment by sueann** [comment]
It sounds like you want something like `getOrCreate` - could you write a wrapper method around that?

**Comment by jrock08** [comment]
Just want to suggest that this might be closed since set_experiment seems to implement the get or create functionality that @sueann suggested.

**Comment by royshil** [comment]
a silly way i used to solve the problem was 

```
            try:
                mlflow.set_experiment(exp_name)
            except mlflow.exceptions.RestException as e:
                logging.info('ML Flow couldn\'t create experiment (%s). Retrying' % e.msg)
                mlflow.set_experiment(exp_name)
```
