### ISSUE TITLE
[SETUP-BUG]

### ISSUE THREAD

**Issue by fizika734** [mlflow/mlflow#1814]
### System information
- **OS Platform and Distribution **: Debian 9 container with Conda image
- **MLflow installed from**: Python
- **MLflow version**: 1.2.0
- **Python version**: 3.7.3
- **Exact command to reproduce**:

### Describe the problem
HI! im trying to figure out with mlflow in Docker container with Conda image, i also have an ftp container and container with postgres database. im trying to make artifacts store to my ftp server. but the only thing what happening is that mlflow creates folders for experiments, but didnt store any artifact in there. in the UI i can see the run, but then im trying to watch the run page i see niagara falls image.
the comand i run inside the container is
mlflow server --backend-store-uri postgresql://user:pass@172.17.0.3:5432/mlflow --default-artifact-root ftp://user:pass@172.17.0.2/vsftpd --host 0.0.0.0 &
also then im trying to dive into the page of run i see the python error from mlflow server container "Connection refused". 
Please help me!

**Comment by sczerniawski** [comment]
Two ideas:
- Google ftp active/passive mode.
- Try using a 21st century protocol like sftp.

**Comment by pmavrodiev** [comment]
@sczerniawski I am sorry, but this is not an answer. Either provide actual concreteness or spare us the sarcasm.

**Comment by nlaille** [comment]
@fizika734 Have you take a look at #1338 ?

**Comment by dbczumar** [comment]
@fizika734 It sounds like this may be related to https://github.com/mlflow/mlflow/issues/1338, but I can't confirm that suspicion without further details. We'll work to get https://github.com/mlflow/mlflow/pull/2196 merged, which will fix https://github.com/mlflow/mlflow/issues/1338. Please feel free to re-open this if you're still running into issues!
