### ISSUE TITLE
[FR] Models api for Java/ Scala

### ISSUE THREAD

**Issue by salqadri** [mlflow/mlflow#1817]
Proposal:
Can we please add the models api to the Java sdk?

Motivation:
I would like to serve models through scala code deployed on Spark.

**Comment by dnzprmksz** [comment]
I have a similar motivation for this feature. I would like to save Scala Spark models as mlflow models and serve using Python.

**Comment by sueann** [comment]
Hi @dnzprmksz @salqadri, would you need to register models from java/scala to model registry _in addition to_ being able to read the model information from java/scala? 

For reading, https://github.com/mlflow/mlflow/pull/2308 was recently merged to provide the APIs in java. Would the APIs implemented there be sufficient for you? Are there any missing functionalities?  Is anything about the current set of APIs that would be cumbersome for you to use?

cc @andychow-db

**Comment by salqadri** [comment]
The models would be created by PyTorch in my case and stored on Cloud Storage. I then need my Scala code to stream the model file and serve the PyTorch model on data coming from a Apache Spark dataframe.

**Comment by dnzprmksz** [comment]
Hi @sueann, thanks for sharing. In my use case I would like to save/export a Scala/Spark model as a MLflow compatible model to deploy it anywhere else using MLflow. As far as I understood from the diff in PR, this API changes introduce reading models from model registry, right? If I am not mistaken, I think I am looking for the Java version of this Python API: https://mlflow.org/docs/latest/python_api/mlflow.spark.html#mlflow.spark.save_model

@salqadri interesting use case, if it is doable 👍

**Comment by sueann** [comment]
Got it - thanks for the clarification. 

@dnzprmksz, for your use case, it sounds like having the equivalent of the `mlflow.spark.log_model` in java would be sufficient? (`save_model` saves to the local filesystem and `log_model` allows saving to remote/cloud ones)

@salqadri, for yours, if you are using MLflow tracking, you may be able to use https://mlflow.org/docs/latest/java_api/org/mlflow/tracking/MlflowClient.html#downloadArtifacts-java.lang.String- ? or if you need to version your models, using model registry (by registering models into it from python) and downloading on the java/scala side with https://github.com/mlflow/mlflow/blob/master/mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java#L751 might work.

**Comment by dnzprmksz** [comment]
@sueann I think both are OK. Final destination for the model would be AWS S3, but it is OK to save to the local filesystem and copy to S3 as well. I think those are not implemented for Java API, right? Do you have any plan in roadmap or a target version for those?

**Comment by amesar** [comment]
> The models would be created by PyTorch in my case and stored on Cloud Storage. I then need my Scala code to stream the model file and serve the PyTorch model on data coming from a Apache Spark dataframe.

Check out ONNX. https://github.com/onnx/onnxmltools/tree/master/onnxmltools/convert/sparkml

**Comment by andychow-db** [comment]
Since this time, we've added the ability to download an MLflow artifact via the Java client. 

[MlflowClient.downloadModelVersion(model_name, version)](https://github.com/mlflow/mlflow/blob/master/mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java#L750)

Is that sufficient for y'alls needs?

**Comment by juntai-zheng** [comment]
Hi all, will close this issue now that we have implemented the above mentioned API. Feel free to reopen if it doesn't fulfill your requirements. Thanks!

**Comment by jotarada** [comment]
CliBasedArtifactRepository its not a java/Scala based API is just a piece of python wrapped  in java code. What if i can't have a python env in my java/scala running machine? i'm running jvm code why should i need python? 

At leat make it clear in the docs that this part of the java API needs has Python dependencies.  It's already hard to manage dependencies in the same language, now depende on other languages doesn't make sense IMO.

**Comment by yetanothercoder** [comment]
yes, I also agree: "Java sdk" which can't ran without installed python with specific configs - seems strange and confusing.
if it's java sdk then it should run on pure jvm without issues
