### ISSUE TITLE
[BUG] Dockerized MLflow only creating .trash

### ISSUE THREAD

**Issue by akashkumar398** [mlflow/mlflow#1818]
Issue:

While dockerizing mlflow , only .trash is getting created. Because of that,  mlflow ui shows "no experiments exists" 

```dockerfile  FROM python:3.7.0  RUN pip install mlflow==1.0.0  WORKDIR /data  EXPOSE 5000  CMD mlflow server \ --backend-store-uri /data/ \ --default-artifact-root /data/ \ --host 0.0.0.0  docker compose :  mlflow: # builds track_ml Dockerfile build: context: ./mlflow_dockerfile expose: - "5000" ports: - "5000:5000" volumes: - ./data:/data```

**Comment by ankitmathur-db** [comment]
@akashkumar398 please ping us if the issue persists
