### ISSUE TITLE
predict/serve to support image classification/detection

### ISSUE THREAD

**Issue by 0wu** [mlflow/mlflow#182]
What's the proper treatment if we want to use MLModel to package a image object detection model whose
* inputs are images (encoded as jpg/png or tensors) and 
* outputs are list of bounding boxes and corresponding object types.

### input
are we suppose to encode the image in JSON so it be handled properly by
https://github.com/databricks/mlflow/blob/f8f6e4aa86bcb3816031e022af5ac520558cc588/mlflow/pyfunc/scoring_server.py#L56

### output
are we suppose to encode the list of bounding box in a encoded string to be packaged into pandas.dataframe or numpy.array container datatypes?

Any working example for image classification or detection to follow?

### Reference
Here are some examples 
* AWS Sagemaker
https://docs.aws.amazon.com/sagemaker/latest/dg/object-detection-in-formats.html
https://docs.aws.amazon.com/sagemaker/latest/dg/API_runtime_InvokeEndpoint.html
inputs: RecordIO, jpg or png

* GCP Cloud ML
https://cloud.google.com/ml-engine/docs/v1/predict-request
inputs: base64 encoded images in json

Thanks!

**Comment by wilmeragsgh** [comment]
I'm also interested in this, for the moment i figured it out, as a work-around, to only provide id of the db entry that store the image on the api call, for that, you may need to create a custom model that inherits from BaseEstimator, but i'm not sure if this approach is suitable to you.

**Comment by manugarri** [comment]
@0wu  [here](https://github.com/mlflow/mlflow/blob/master/examples/flower_classifier/) there is an example implementation.

**Comment by mparkhe** [comment]
You can in
