### ISSUE TITLE
MLFlow Pyfunc failing on Databricks (missing python lib pip dependencies)  

### ISSUE THREAD

**Issue by arnaudsj** [mlflow/mlflow#1823]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes, I have made the code available in this repo: https://github.com/arnaudsj/sample-mlflow-spacy
- **OS Platform and Distribution**: OS 10.14.6 locally / Databricks 5.5 Conda Beta (includes Apache Spark 2.4.3, Scala 2.11)
- **MLflow installed from**:  binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.2.0
- **Python version**: Python 3.7.3
- **npm version, if running the dev UI**: n/a
- **Exact command to reproduce**: `mlfow run .` then 

### Describe the problem
I am attempting to wrap up a simple Spacy model for language detection using the mlflow.pyfunc class, and running it locally on OS X in a conda env works fine, but when attempting to run it in Databricks, even though I confirmed that the right conda env gets created, when executed it in Spark it appears to be either outside of the conda env, or the env did not get provisioned with the pip dependencies and therefore fails to find the needed python libs (e.g. spacy, spacy_langdetect). It sound very similar to #1208, but the work around described in that issue did not work.

### Code to reproduce issue
- Clone the repo I prepared here: https://github.com/arnaudsj/sample-mlflow-spacy
- run mlflow locally to test it works in a conda env `mlflow run .`
- the expected output should be:
```
0    {'language': 'en', 'score': 0.9999975821644531}
1    {'language': 'fr', 'score': 0.9999969564108246}
```
- set MLFLOW_EXPERIMENT_NAME to a valid path in .env
- run `make` it will execute locally again, but this time log the model to Databricks
- Launch a Databricks cluster with the proper runtime (Databricks 5.5 Conda Beta) and create a new Python notebook
- Adapt and execute the following Python code based on the path to the MLFlow model:
```
from mlflow import pyfunc
from pyspark.sql.types import *

pyfunc_udf = pyfunc.spark_udf(spark, model_uri="dbfs:/databricks/mlflow/3664730769366758/4328856e8c2f44d0af13566bda773536/artifacts/model", result_type=StringType())
sqlContext.udf.register("sample_spacy_lang_detect", pyfunc_udf)
```
- Test the new UDF function in SparkSQL
```
SELECT sample_spacy_lang_detect('Hello, world!')
```
- Get traceback (as shared below) about missing python lib

### Other info / logs
Here is the traceback I get back from Databricks:
```
(TID 636, 10.27.239.82, executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 480, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 472, in process
    serializer.dump_stream(out_iter, outfile)
  File "/databricks/spark/python/pyspark/serializers.py", line 404, in dump_stream
    timely_flush_timeout_ms=self.timely_flush_timeout_ms)
  File "/databricks/spark/python/pyspark/serializers.py", line 214, in dump_stream
    for batch in iterator:
  File "/databricks/spark/python/pyspark/serializers.py", line 394, in init_stream_yield_batches
    for series in iterator:
  File "<string>", line 1, in <lambda>
  File "/databricks/spark/python/pyspark/worker.py", line 108, in <lambda>
    verify_result_type(f(*a)), len(a[0])), arrow_return_type)
  File "/databricks/spark/python/pyspark/util.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-6cdf22b7-0350-45ea-a13c-4fa6f6ae7d68/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 423, in predict
  File "/databricks/python/lib/python3.7/site-packages/mlflow/pyfunc/spark_model_cache.py", line 63, in get_or_load
    SparkModelCache._models[archive_path] = load_pyfunc(temp_dir)
  File "/databricks/python/lib/python3.7/site-packages/mlflow/utils/annotations.py", line 40, in deprecated_func
    return func(*args, **kwargs)
  File "/databricks/python/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 313, in load_pyfunc
    return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/databricks/python/lib/python3.7/site-packages/mlflow/pyfunc/model.py", line 214, in _load_pyfunc
    python_model = cloudpickle.load(f)
ModuleNotFoundError: No module named 'spacy'
```

Thank you in advance for your help. And let me know if there is something that I am not doing correctly in the first place.

**Comment by arnaudsj** [comment]
Am I the only one experiencing this issue? Is this a known issue?

**Comment by carlos-rodrigo** [comment]
I have the same issue too

**Comment by carlos-rodrigo** [comment]
@arnaudsj reading the docs found that at the moment of log your model you probably must add the code_path too. This path is where are located the dependencies of the model you code. 

reference: https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.log_model

I'm trying this approach right now, if it works I will comment the results in this thread.

**Comment by arnaudsj** [comment]
@carlos-rodrigo did your approach work? The issue I was seeing was not with my code, but with the inability to find a dependent library (specified in the conda.yaml file)

**Comment by carlos-rodrigo** [comment]
Hi @arnaudsj! yes it works! if I add the folder where the dependencies of my model are in the code_path, the ModuleNotFoundError doesn't appear anymore.
