### ISSUE TITLE
Authentication Mechanism & OAuth Support

### ISSUE THREAD

**Issue by shubham311994** [mlflow/mlflow#1825]
Hi, 
1) I am looking for a way to provide authentication to mlflow tracking server. I tried with setting up the environment variables(TRACKING_USERNAME & PASSWORD) but it is not showing anything on the logs ( I am running everything using Docker).
2) Does mlflow supports OAuth and if it does then how?

**Comment by lopezco** [comment]
Is there any news on this?
@shubham311994 do yo manage to setup an authentication mechanism?
Thanks

**Comment by blueloony** [comment]
I'm looking for similar authentication. Any resolutions @shubham311994?

**Comment by devstein** [comment]
+1 My team would like this feature

**Comment by lopezco** [comment]
@blueloony 
I've managed to setup authentication by running mlflow server in a container next to an nginx container that handles [basic auth using](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/).
The exposed port is the one from nginx container while the redirections to the mlflow container are done by nginx.
[Here](http://www.codingtricks.biz/how-to-deploy-mlflow-with-docker-compose/) I've found a guide explaining the deployment using `docker-compose`

**Comment by AveshCSingh** [comment]
There's an open issue to remove barriers to running MLflow behind a reverse proxy (#1825). MLflow does not support OAuth, but once these barriers are resolved you should be able to run MLflow on a server that requires authentication.

**Comment by jonnor** [comment]
That link leads back to this issue. I think correct issue is #2823

**Comment by dbczumar** [comment]
MLflow now has a built-in authentication and authorization layer: https://mlflow.org/docs/latest/auth/index.html. Please try it out and provide feedback. Thank you for using MLflow!

**Comment by yogi4289** [comment]
@dbczumar, @blueloony @lopezco  is there a way to support oidc-oauth (okta or ping idp etc) based authentication on Mlflow?
