### ISSUE TITLE
Model comparison with Pivot Tables 

### ISSUE THREAD

**Issue by aim-nfunke** [mlflow/mlflow#1826]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
As a data scientist, I want to create pivot tables to compare models. I want to aggregate by specific parameters, tasks or tags and display metrics.

### Motivation
This provides an individual configuration option for different aggregations of the model data. The comparison of runs by model classes, datasets or tasks can be done flexibly. This enables easier and efficient operation.

**Comment by smurching** [comment]
@aim-nfunke thanks for filing this issue & apologies for the delay, from what I understand this is already possible using the search bar, e.g. you can filter out to runs that correspond to a particular model class or dataset as long as such information is logged in the metrics/params/tags of the runs. Is there something additional that a pivot table UX would add?
