### ISSUE TITLE
Save Global Configuration for Parallel Coordinates Plot

### ISSUE THREAD

**Issue by aim-nfunke** [mlflow/mlflow#1827]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------

## Describe the proposal
As a data scientist, I want to save global configurations of parameters and metrics of the Parallel coordinates Plot.
If I compare runs of an experiment, then I would like to compare certain parameters and metrics.

### Motivation
This would allow me to compare models faster and require fewer clicks. My problem is that every time I compare runs with the parallel coordinates Plot, I have to add metrics again and again and hide parameters. This costs time and nerves.

**Comment by sueann** [comment]
It doesn't quite solve the same issue, but does https://github.com/mlflow/mlflow/pull/2779 help in your workflow?

**Comment by Zangr** [comment]
@aim-nfunke Thank you for submitting the feature request. It makes sense to be considered as part of plan for MLflow to provide more customized visualization.

**Comment by dbczumar** [comment]
These global configurations are now persisted in the MLflow UI. Thank you for using MLflow!
