### ISSUE TITLE
Navigation on the experiment table with Tags

### ISSUE THREAD

**Issue by aim-nfunke** [mlflow/mlflow#1829]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

## Describe the proposal
As a data scientist/product owner I would like to create a freely configurable tag herachie on the experiment/run table. We work with keys and values (tags) to structure our experiments. For example something like that: customer / project / task / ...
We assign these tags to each experiment to find them again

### Motivation
With the help of the search function, the experiments are laborious to find. 
On the left side of the run table the experiments are currently displayed. Some of the experiments have long names and we can not read certain experiments anymore. There are only one long list. 

To find experiments faster, tags should be displayed on the left side of the experiment/run table to filter experiments.

**Comment by aim-nfunke** [comment]
@Zangr : Hello this issue is for us very important. Can u give me feedback for this issue?

**Comment by Zangr** [comment]
@aim-nfunke We are actively working on a new column view. It will land in Q4. It will support a good number of features related to this request.

**Comment by aim-nfunke** [comment]
@Zangr Hello, thanks for ur feedback. Which issue do you mean? This #1829 or #1701? More important for us is to find our experiments again with Tags. 

Look here at Slack: 
Tomas Nykodym  vor 1 Tag:
Hi Nils, thanks for posting, I will look at this issue this week. From a quick look it sounds like this would be a great feature to have.

**Comment by Zangr** [comment]
@aim-nfunke, it's more related to displaying tags in separate columns #1701

**Comment by dbczumar** [comment]
I'm going to go ahead and close this, as we've made significant improvements to the layout of information on the MLflow Experiment page over the last 2 years, including separate columns for specific tags that can be hidden / resized, as well as a search box for experiments.
