### ISSUE TITLE
UI plot returning 404 on metrics with forward slash in tag

### ISSUE THREAD

**Issue by niladell** [mlflow/mlflow#1830]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ManjaroLinux 18.0.4
- **MLflow installed from (source or binary)**: binary (via pip)
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 3.7.3

### Describe the problem
Whenever I log variables with `mlflow.log_metrics` if the metric has a forward slash (`/`) in the name tag, it will throw a 404  error on the MLFlow UI plot.

I couldn't find anywhere a reference of the allowed characters in the tags, neither I know if that's an intended behavior.

**Comment by ankitmathur-db** [comment]
@niladell I'm on master, and I have been trying to log metrics with forward slashes in the name, and the UI seems to display them correctly. Can you clarify what view the UI is failing in?

**Comment by niladell** [comment]
Basically what happens to me is that if, for example, I record:
`mlflow.log_metrics({'train/loss': loss})` the page of the plot 
> `#/metric/train/loss?runs=["791f2a7c6b70461e9b0c55ea771a9d8c"]&experiment=0&plot_metric_keys=["train/loss"]`

just gives me the 404 with "Page not found. Go back to home page"

If instead I record the metric as: `train_loss`, the plot page
> `#/metric/train_loss?runs=["791f2a7c6b70461e9b0c55ea771a9d8c"]&experiment=0&plot_metric_keys=["train_loss"]`

works without any problem (showing me the training loss). In fact, I can then set `plot_metric_keys=["train_loss", "train/loss"]` and both are displayed properly.

I haven't tried to replicate with a new project. If I have time, I'll try to check tomorrow and see if in that case I get a different behavior. Tell me if you need any other particular info, log or anything.

**Comment by jpambrun** [comment]
This is a duplicate of #1692

**Comment by niladell** [comment]
You are right! I didn't see that one. Closing this issue then.
