### ISSUE TITLE
[FR] Ability to retrieve run based on 'run_name'

### ISSUE THREAD

**Issue by Akashdesarda** [mlflow/mlflow#1844]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on a feature request, start implementation

## Describe the proposal
Provide a clear high-level description of the feature request in the following sections. Feature requests that are likely to be accepted:
* Are minimal in scope (note that it's always easier to add additional functionality later than remove functionality)
* Are extensible (e.g. if adding integration with an ML framework, is it possible to add similar integrations with other frameworks?)
* Have user impact & value that justifies the maintenance burden of supporting the feature moving forward. The [JQuery contributor guide](https://contribute.jquery.org/open-source/#contributing-something-new) has an excellent discussion on this.

### Motivation
What is the use case in mind?  Why is it valuable to support, and why is it currently difficult or impossible to achieve? Could the desired functionality alternatively be implemented as a third-party package using MLflow public APIs? 
Currently (as per my knowledge) we can retrieve a Mlflow run from MlflowClient using either experiment_id or run_id but not run_name for any particular experiment. Even MlflowClient.list_run_infos() doesn't show any info regarding to run_name. 

### Proposed Changes
For user-facing changes, what APIs are you proposing to add or modify? For internal changes, what code paths will need to be modified? 
Maybe MlflowClient.list_run_infos() could also include run_name

**Comment by MFreidank** [comment]
I don't think runs have a run name. They only have a run id and retrieving runs based on their id is already implemented as (`mlflow.tracking.get_run`)[https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.get_run].

**Comment by Akashdesarda** [comment]
> I don't think runs have a run name. They only have a run id and retrieving runs based on their id is already implemented as [`mlflow.tracking.get_run(run_id)`](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.get_run).

They have run name. You can check it in UI

**Comment by kelvins** [comment]
Indeed mlflow provides a way to set a `run name` related to a specific `run`. If I'm not wrong, the `run name` is stored as the `mlflow.runName` tag in the `tags` table. Based on it we could retrieve a run based on the `run name` using the `search_runs` function, for example:

```python
mlflow.search_runs(
    experiment_ids=['29'],
    filter_string='tags.mlflow.runName = "my_run_name"'
)
```

But I agree it could have a simpler way to retrieve a run based on the run name.

Doc reference: 
- Python API: https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.search_runs
- REST API: https://www.mlflow.org/docs/latest/rest-api.html#search-runs

**Comment by dbczumar** [comment]
@Akashdesarda Because the run name is not a unique field, we recommend using the tag-based search procedure recommended by @kelvins. Thank you @kelvins for providing this solution!
