### ISSUE TITLE
[FR] SVG MLflow icon

### ISSUE THREAD

**Issue by xhochy** [mlflow/mlflow#1853]
I'm building a Jupyterlab extension to embed mlflow server with https://github.com/jupyterhub/jupyter-server-proxy. There it would be nice to also use the official MLflow logo. Sadly the logo only seems to be available in the rendered PNG version. Would it also be possible to get it as an SVG?

**Comment by gioa** [comment]
@xhochy How does the Jupyterlab extension go? Here are the SVG files:
[MLflow-logo-set.zip](https://github.com/mlflow/mlflow/files/3881869/MLflow-logo-set.zip)

Let us know what else we can help. Thanks!

**Comment by Gsbreddy** [comment]
Hey @gioa 
Hope you are well.
I am using mlflow svg icon you provided in my own application. I wanted to know if there is a license for this image. I opened up that zip you provided and there's no license in there either. Without a license, we can't use the images, is there perhaps one on website or anything? (here's an example from github [https://github.com/logos](https://github.com/logos))

Please help me on this. Thanks!

**Comment by prateekkhera** [comment]
@xhochy - did you manage to make mlflow work with jupyter proxy as I am facing issues. I'd appreciate if you can share your experience. Thanks

**Comment by xhochy** [comment]
It does work without any issues for me since two years now.

**Comment by Gsbreddy** [comment]
@prateekkhera  You can check basic implementation [here.](https://github.com/americanexpress/mlflow-server-proxy)
I have yet to release a pypi package so let me know if you need any help in building the python package. Thanks!
