### ISSUE TITLE
[BUG] password of artifact store connection (ftp, sftp) is visible

### ISSUE THREAD

**Issue by sim-san** [mlflow/mlflow#1854]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 3.7.4
- **npm version, if running the dev UI**: /
- **Exact command to reproduce**: 
mlflow ui --default-artifact-root ftp://user:password@192.168.1.128/MLFLOW

### Describe the problem
The URI may optionally include a password for logging into the server, e.g. ftp://user:pass@host/path/to/directory. However, the username and password should not be visible in the ExperimentView for security reasons.

### Code to reproduce issue
/

### Other info / logs
![FR_Mlflow2_snall](https://user-images.githubusercontent.com/7436938/65139032-3ed32b00-da0c-11e9-89bf-fe54985bba64.PNG)

**Comment by sim-san** [comment]
Possible solution:

```
artifact_location = 'ftp://simon:12345678@192.168.1.128/MLFLOW/7'

var artifact_regx = new RegExp('(.*):\/\/(.*):(.*)@(.*)')
    function artifact_location_replacer(match, p1, p2, p3, p4, offset, string){
      replaces_loc = p1 + '://' + 'user' + ':' + 'password' + '@' + p4
      return replaces_loc;
    }

var artifact_location_fix = artifact_location.replace(artifact_regx, artifact_location_replacer)
```

**Comment by push-kar-desh-pande** [comment]
The best and shortest way to solve this is to change the UI components in the built JS components.
You can change that by changing python packages in the machine where you installed MLFlow.
go to : `/usr/lib/python3.6/site-packages/mlflow/server/js/build/static/js`
There will be two files `main.*.chunk.js` and  `main.*.chunk.js.map`
Search and remove value for "Full Path".
The default value is a js variable. You can make that as a standard text or even meddle with the js variable to mask the password part using regular expressions. 


Note: This is going to be overwritten every time you update and build a newer version of MLflow. So be extremely careful while updating the library.  
You can prevent conda auto updates using  `conda config --set auto_update_conda False`

Also: you can enable passwordless sftp to avoid showing any passwords at all 

Hopefully mlflow will fix it in the next iteration of updates.

**Comment by wisalsamigoogle** [comment]
yes, @push-kar-desh-pande 
passwordless sftp work fine for me,
the only thing to remember, that mlflow.ui will pick artifact from that sftp location, and if by any chance like me, your mlflow server and the artifact path are on the same server, then you have to keep server's public key in its own [authorized_keys] file as well along with client-side's public key

note: not to forget, to add the "PubkeyAcceptedAlgorithms +ssh-rsa" or any other protocol in the [/etc/ssh/sshd_config] file.

afterwards, "sftp://[USER]@[IP]:/home/[USER]/.../track/" can work fine
