### ISSUE TITLE
[FR] Create gitter.im Chat for better inegration with github

### ISSUE THREAD

**Issue by arita37** [mlflow/mlflow#1866]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.
  
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Gitter is very convenient and closely integrated with Github.
A chat forum for users has been created here : 
https://gitter.im/arita37/mlflow

**Comment by smurching** [comment]
Hi @arita37 - thanks for raising this. We currently encourage discussion of MLflow on Slack at https://mlflow-users.slack.com/ (see invite link on https://mlflow.org/), closing this for now
