### ISSUE TITLE
mlflow pyfunc predict using csv input file for XGBoost not working

### ISSUE THREAD

**Issue by donigian** [mlflow/mlflow#187]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes custom XGBoost on Ames Housing dataset 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.2.1
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
XGBoost predict function takes as input a numpy array while mlflow predict CLI application takes as input Pandas CSV data row. Do you have a suggestion for how to save a single test instance so that `mlflow pyfunc predict` will work? 

FYI, subsequent runs of `mlflow pyfunc predict` result in a different order of expected columns in the output.

Server CLI invoked using:

`mlflow pyfunc serve -m mlruns/0/faccff5e8a8c42ae82dd1f2c68a9dfa6/artifacts/model/`

To score a single instance using CLI run:

`mlflow pyfunc predict -m mlruns/0/7635c0c89f8543c9a2c45234b18a1177/artifacts/model/  -i /Users/arm/code/Deploying_ML_models_to_Production_Toolkit/instance.csv`

Code Snippet:
```
my_model = XGBRegressor(n_estimators=100, learning_rate=0.05)
my_model.fit(training_examples, training_targets, early_stopping_rounds=5, 
             eval_set=[(test_examples, test_targets)], verbose=False)
predictions = my_model.predict(test_examples)
```

### Source code / logs
 ```
ValueError: feature_names mismatch: ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36'] ['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

expected f14, f12, f4, f34, f15, f31, f3, f6, f23, f25, f24, f35, f2, f36, f7, f13, f5, f10, f11, f19, f16, f0, f22, f18, f32, f21, f29, f26, f33, f8, f17, f30, f1, f9, f28, f27, f20 in input data

training data did not have the following fields: MiscVal, YrSold, Fireplaces, FullBath, OverallCond, LotFrontage, HalfBath, 2ndFlrSF, LotArea, LowQualFinSF, BsmtHalfBath, GarageArea, 3SsnPorch, MoSold, YearRemodAdd, GrLivArea, WoodDeckSF, BsmtFinSF1, YearBuilt, MSSubClass, BedroomAbvGr, ScreenPorch, BsmtFinSF2, BsmtFullBath, GarageCars, BsmtUnfSF, TotRmsAbvGrd, Id, MasVnrArea, EnclosedPorch, 1stFlrSF, OpenPorchSF, PoolArea, GarageYrBlt, TotalBsmtSF, OverallQual, KitchenAbvGr
```

**Comment by tomasatdatabricks** [comment]
Ho @donigian, thanks for the report. 

Model input / output is currently an active issue we are working on. For now, can you try to train your XgBoost model as a sklearn pipeline and prepend a pipeline element which will fetch the data by name?

**Comment by kangjin2014** [comment]
Hi @tomasatdatabricks I have the same error. May I have some update on this issue?

**Comment by brijenshah** [comment]
I am also facing the same issue. Any update?

**Comment by Ishitori** [comment]
I have the same issue, and it seems like the error is somewhere inside of log_model of mlflow.xgboost
