### ISSUE TITLE
[BUG] Spark UDF cannot load models with empty directories

### ISSUE THREAD

**Issue by dwyatte** [mlflow/mlflow#1881]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **MLflow installed from (source or binary)**:  Binary
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Loading a MLflow model with empty directories as a Spark UDF raises an IsADirectoryError. I encountered this for TensorFlow models without variables (which is the case for models with all variables converted to constants), but it looks like it will be triggered for any MLflow model with an empty directory (untested).

```
IsADirectoryError: [Errno 21] Is a directory: 'path/to/model/tfmodel/variables'

/databricks/python/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py in spark_udf(spark, model_uri, result_type)
    417     with TempDir() as local_tmpdir:
    418         local_model_path = _download_artifact_from_uri(
--> 419             artifact_uri=model_uri, output_path=local_tmpdir.path())
    420         archive_path = SparkModelCache.add_local_model(spark, local_model_path)
    421 

/databricks/python/lib/python3.7/site-packages/mlflow/tracking/artifact_utils.py in _download_artifact_from_uri(artifact_uri, output_path)
     64     root_uri = prefix + urllib.parse.urlunparse(parsed_uri)
     65     return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
---> 66         artifact_path=artifact_path, dst_path=output_path)
```

### Code to reproduce issue
```
import tensorflow as tf
import mlflow
import mlflow.tensorflow
import mlflow.pyfunc

inputs = tf.placeholder(tf.float32, [None])
outputs = inputs/2 + 2
signature = (
    tf.saved_model.signature_def_utils.build_signature_def(
        inputs={"inputs": tf.saved_model.utils.build_tensor_info(inputs)},
        outputs={"outputs": tf.saved_model.utils.build_tensor_info(outputs)},
        method_name="predict"
    )
)

with tf.Session() as sess:
    builder = tf.saved_model.builder.SavedModelBuilder("saved_model")
    builder.add_meta_graph_and_variables(
        sess,
        [tf.saved_model.tag_constants.SERVING],
        signature_def_map={"predict": signature}
    )
    builder.save()

mlflow.tensorflow.save_model(tf_saved_model_dir="saved_model",
                             tf_meta_graph_tags=[tf.saved_model.tag_constants.SERVING],
                             tf_signature_def_key="predict",
                             path="model")

udf = mlflow.pyfunc.spark_udf(spark=spark, model_uri="model")
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.

**Comment by tomasatdatabricks** [comment]
Hey @dwyatte, thanks for posting! I have been able to reproduce this. The issue occurs when downloading artifacts which include empty directory.
