### ISSUE TITLE
MLflow Tracking's web interface times out trying to connect to a CDN on air-gapped servers[BUG]

### ISSUE THREAD

**Issue by mirekphd** [mlflow/mlflow#1886]
- **Exact command to reproduce**:
Run `mlflow ui` on an air-gapped server (e.g. in a Jupyter Notebook Terminal) and try to connect through any web browser (e.g. Chrome or Firefox). 

The REST API connection between the browser-based client and the tracking server (gunicorn) should be left open, but any other connections (including all outgoing TCP connections) should be blocked (as on air gapped corporate servers).

### Describe the problem
The MLflow tracking server page load times are very high, in tens of seconds (suggesting a timeout). Most of the time Firefox displays info on the following connection attempt: [Connecting to] maxcdn.bootstrapcdn.com [...]

### Other info / logs
Searching code base for 'cdn' revealed this URL, but other external URLs also seem possible it the server was not tested in such conditions:
https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js

**Comment by tomasatdatabricks** [comment]
Hi @mirekphd, thanks for posting!

Can you clarify what is your use case? Why do you want to run ``mlflow ui`` on a "air-gapped" server?  Can you use ``mlflow server`` instead?

**Comment by mirekphd** [comment]
Hi @tomasatdatabricks, thanks for leaving Issues enabled (unlike, say, H2O:)

I agree that `mlflow server` would probably be more appropriate on an
aur-gapped server. Even then I would still need to show my users the MLflow
Tracking interface, and the Windows VMs where they have their browsers
installed are hosted on corporate servers without access to your CDN. Just
internal network connections are open for data leak prevention reasons. So
if you're assuming browser by definition has access to the internet, think
again:) it is only used here to connect to servers running on corporate
compute nodes, also incidentally aur-gapped for the same reasons.

**Comment by mirekphd** [comment]
Mind you, this problem with reliance on open access to external CDN's is not that uncommon, it affects even some of the most popular on-premise platforms. I have to deal with it on a daily basis in Altlassian's products (notably Bitbucket), for which the company has to pay handsomely. 

Other commercial products such as Red Hat's Openshift or JFrog's Artifactory and almost all open-source apps we use (like Jupyter Notebook / Lab and RStudio Server), with the exception of H2O Flow (which is not fully open, because their Github Issues are locked...) do manage to bundle all images and scripts together with the webpage, so are unaffected by these timeouts.
