### ISSUE TITLE
[BUG] Slack Group Link Broken

### ISSUE THREAD

**Issue by jonathanmeier5** [mlflow/mlflow#1887]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14
- **MLflow installed from (source or binary)**: N/A
- **MLflow version (run ``mlflow --version``)**: N/A
- **Python version**: N/A
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
The slack group link in the docs is broken. It says I cannot proceed unless I have a `@databricks` email address.

### Code to reproduce issue
Click the slack group link in the docs/on the website as a non-databricks user.

### Other info / logs
<img width="1680" alt="Screen Shot 2019-09-30 at 7 58 43 AM" src="https://user-images.githubusercontent.com/10645526/65876801-26420980-e358-11e9-8e66-5fc8af8bc0c3.png">

**Comment by tomasatdatabricks** [comment]
Thanks for posting! We will look into that.

**Comment by tomasatdatabricks** [comment]
The link should work now. Thanks for posting!

**Comment by jtdigital** [comment]
I know this is marked as closed and fixed, but I'm having the same issue today. :-/  Would love to join :)

**Comment by harupy** [comment]
@jtdigital 
The link (named public slack server) at the bottom of this page worked for me.
https://mlflow.org/

**Comment by jtdigital** [comment]
Oh thank you! The broken link I followed was in: https://github.com/mlflow/mlflow/blob/master/README.rst#community
