### ISSUE TITLE
[BUG] Download artifacts from HDFS is broken in v1.3 candidate.

### ISSUE THREAD

**Issue by jdlesage** [mlflow/mlflow#1889]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS7
- **MLflow installed from (source or binary)**:  Source
- **MLflow version (run ``mlflow --version``)**: master branch
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

Use HDFS as artifact store. Download any artifacts

### Describe the problem
Method `_download_hdfs_file` from `mlflow/store/hdfs_artifact_repo.py` always creates a temporary directory even if it already exists

### Code to reproduce issue
See unit test  in https://github.com/mlflow/mlflow/pull/1890

### Other info / logs
I created https://github.com/mlflow/mlflow/pull/1890 with the fix. Could you merge it in v1.3 before the release, please? Thanks a lot!

**Comment by tomasatdatabricks** [comment]
Thanks for the catch! I have merged your PR to master, I will close this ticket once the PR is merged to the release branch.

**Comment by tomasatdatabricks** [comment]
Fix was included in the mlflow 1.3 release. Thanks!
