### ISSUE TITLE
[BUG] Null Values ignored in data

### ISSUE THREAD

**Issue by GiteshKhanna** [mlflow/mlflow#1897]
Hi guys,

I was trying to pass data having null values in some columns, Since ML Libraries like XGBoost support null values in their input.
The problem I found in mlflow code was that you use pd.read_json(json_input, orient=orient, dtype=False) and pd.to_json(orient='split') which ignores Null values.

if instead of the above method "json" library is used, this problem can be easily tackled.

**Comment by tomasatdatabricks** [comment]
Hi @GiteshKhanna, thanks for posting.

Can you elaborate a bit about your use case? Are you referring to how we parse data when deploying models?

**Comment by GiteshKhannaOYO** [comment]
Hi @tomasatdatabricks  thanks for the reply.
Yes I want to have some clarity on how the data is parsed when the models are deployed.

I actually want to pass comma separated values which seem to be giving an error. When I tried checking out the code in the library I found out that when I pass ContentType as text/csv , mlflow expects the path to the data file rather than data itself, which is the reason I was getting the error.

Although I want to have a solution such that I am able to pass directly csv as input data and hence get the outputs.

Eg.

```
def query_endpoint_csv(input_json):
  print(input_json)
  client = boto3.session.Session().client("sagemaker-runtime", REGION_NAME)
  
  response = client.invoke_endpoint(
      EndpointName="xgtestxyz32",
      Body=input_data,
      ContentType='text/csv',
  )
  preds = response['Body'].read().decode("ascii")
  preds = json.loads(preds)
  print("Received response: {}".format(preds))
  return preds

predictions = query_endpoint_csv(input_data=('1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10\n1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10'))
```

**Comment by GiteshKhanna** [comment]
Hi @tomasatdatabricks  thanks for the reply.
Yes I want to have some clarity on how the data is parsed when the models are deployed.

I actually want to pass comma separated values which seem to be giving an error. When I tried checking out the code in the library I found out that when I pass ContentType as text/csv , mlflow expects the path to the data file rather than data itself, which is the reason I was getting the error.

Although I want to have a solution such that I am able to pass directly csv as input data and hence get the outputs.

Eg.

```
def query_endpoint_csv(input_data):
  client = boto3.session.Session().client("sagemaker-runtime", REGION_NAME)
  
  response = client.invoke_endpoint(
      EndpointName="xgtestxyz32",
      Body=input_data,
      ContentType='text/csv',
  )
  preds = response['Body'].read().decode("ascii")
  preds = json.loads(preds)
  print("Received response: {}".format(preds))
  return preds

predictions = query_endpoint_csv(input_data=('1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10\n1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10'))
```
