### ISSUE TITLE
One trial per GPU? Is it possible?

### ISSUE THREAD

**Issue by thrmotta** [mlflow/mlflow#1903]
Is it possible in a multiple GPU scenario, to have each available GPU doing a separate trial? So far it seems that using multi_gpu_model is not accelerating our computer vision deep learning model (U-net / Mask RCNN), so having each trial running on a separate GPU could provide us with great speedups, but I've found no information on the matter.

Thank you.

**Comment by pogil** [comment]
Hi @thrmotta, 

The core of MLflow itself doesn't really manage model training itself and it is agnostic to the code you run. Is there a specific example you're referring to?

**Comment by thrmotta** [comment]
Hi @pogil,

Sorry, I made some confusion with MLflow and some other framework that was being used along side it. This was the wrong place to post this question. 

Sorry for taking your time and thank you for your attention.

**Comment by thrmotta** [comment]
Hi @pogil,

Sorry, I made some confusion with MLflow and some other framework that was being used along side it. This was the wrong place to post this question.

Sorry for taking your time and thank you for your attention.
