### ISSUE TITLE
[FR] Make MLFlow PyTorch log_model and save_model supports PyTorch models with custom inputs.

### ISSUE THREAD

**Issue by axelborja** [mlflow/mlflow#1909]
## Describe the proposal
Make MLFlow PyTorch log_model and save_model supports PyTorch models with custom inputs.

### Motivation
We are currently using PyTorch models a list of inputs, so we cannot use MLFlow to deploy our model.

**Comment by ssYkse** [comment]
I have the same Issue! I would like to send a png/base64/numpy pickle from the frontend. It would be complete overkill to have the web client do a conversion into a very specific json pandas split orientation model.
