### ISSUE TITLE
[FR] logging during prediction

### ISSUE THREAD

**Issue by geoHeil** [mlflow/mlflow#1916]
A plain flask API nicely can combine the prediction with logging the results and maybe running an explainer: https://github.com/ThoughtWorksInc/ml-app-template/blob/master/src/app_with_logging.py

how can this be integrated with mlflow?

Only as a custom model? Or is there a more straight forward approach?

**Comment by smurching** [comment]
@geoHeil that's a cool idea (& apologies for the delay), yep for now the best approach to logging metrics after making predictions seems to be defining a custom model that does this, see https://www.mlflow.org/docs/latest/models.html#custom-python-models for reference. Would you have any interest in adding an example under the `examples` directory that does this?
