### ISSUE TITLE
[BUG] Running MLflow projects remotely from a Windows machine fails

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#1926]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**:  Binary
- **MLflow version (run ``mlflow --version``)**: 1.3.0
- **Python version**:  3.6
- **Exact command to reproduce**:

### Describe the problem
As described in https://stackoverflow.com/questions/58234777/mlflow-remote-execution-on-databricks-from-windows-creates-an-invalid-dbfs-path, running an MLflow project remotely against a Databricks cluster from a Windows 10 environment fails. The fix described in the SO post (replacing `os.path.join` with `os.posixpath.join` when joining paths within DBFS, e.g. [this one](https://github.com/mlflow/mlflow/blob/2a6b2bdf2b682d708620848c29b8c9b2743fc577/mlflow/projects/databricks.py#L26)) seems appropriate

**Comment by hemantkshirsagar8** [comment]
I faced a similar issue at windows.
Can you explain the solution to this for Windows users?

**Comment by hemantkshirsagar8** [comment]
I resolved this issue at my end, with replacing all 'os.path' to 'posixpath' at 'databricks.py' file.
It worked perfectly fine for me.

**Comment by aestene** [comment]
I did the same as @hemantkshirsagar8 intending to create a PR for this issue. However, I've had quite abit of problems setting up the tests and have been working with this on and off for the past week. Now I managed to run them on a personal computer away from the world of corporate proxies. However, there are some errors and failures, some of which are linked to asserting paths are equal on linux vs. my windows system. 

Would creating a PR for the tests to run here be an option @smurching?

**Comment by smurching** [comment]
@aestene yep that's a good option, thanks for being willing to open a PR! Travis will run the tests for you in a sandboxed environment - once you've opened the PR, I'd be curious to see if there are tests that fail for you locally but pass on Travis. If so, we should update our contributor guide to make sure the instructions result in the same local dev environment as is used on Travis.

**Comment by smurching** [comment]
This was fixed by @aestene in #1996, which was released in v1.5.0 - thanks @aestene for the fix!
