### ISSUE TITLE
[FR] Enable http compression in API

### ISSUE THREAD

**Issue by rom1504** [mlflow/mlflow#1936]
## Proposal
Enable http compression in API

### Motivation
Makes API calls faster. Some responses of search_runs in particular can take up to 20MB of json, which is easily compressed in 1MB.

### Proposed Changes
Enabling http compression

**Comment by rom1504** [comment]
Since mlflow is providing its API and front under gunicorn, it would actually make sense to use an http server such as nginx for compression purposes.
So I think the solution to this issue is a simple guide on how to setup a simple nginx configuration to host mlflow.

**Comment by andychow-db** [comment]
Thank you for the feedback.
