### ISSUE TITLE
keras.backend has no attribute _BACKEND at line 293 keras.py

### ISSUE THREAD

**Issue by abdullasaifee** [mlflow/mlflow#1937]
found this issue while using mlflow to serve my model.

**Comment by blister96** [comment]
I got this error while using tensorflow.keras. I was using tensorflow==1.12 and the only version that seems to work is tensorflow==1.14. It would be nice if a more portable solution existed.
I think changing 
`if keras_module.__name__ == "tensorflow.keras" or K._BACKEND == 'tensorflow':`
to 
`if 'tensorflow' in keras_module.__name__ or K.backend() == 'tensorflow':`
_might_ be better.

**Comment by neb42** [comment]
I have the same issue with tensorflow==2.1.0

**Comment by OrthoDex** [comment]
Hi! First time contributor here, can I take a shot at this?

**Comment by sueann** [comment]
Sure, thanks @OrthoDex !

**Comment by zhidongqu-db** [comment]
@OrthoDex Hey, are you still working on this? If you can make a PR on this based on suggestion from @blister96 and add relevant test we would love to review it!

**Comment by OrthoDex** [comment]
Hello! Yes I am still working on it, I'll be putting a PR sometime by next week.

**Comment by Karan-Choudhary** [comment]
Try using 
```
K.backend()=='tensorflow'
```
instead of
```
K._BACKEND()=='tensorflow' 
``` 
Already solved this issue.

**Comment by dbczumar** [comment]
Closing this out, as it has been addressed :)
