### ISSUE TITLE
[FR] Add support for sentry.io for MLflow python backend

### ISSUE THREAD

**Issue by Djailla** [mlflow/mlflow#1939]
In order to track exception happening in a Python project, Sentry.io service is great, it gather data per version, with a full stack trace and help the developer and SRE team to be more agile in problem solving.

The integration is pretty straightforward :

https://sentry.io/for/flask/

**Comment by RenaultAI** [comment]
I couldn't find any documentation about how I can integrate mlflow with Sentry. Does anyone know? Thanks!
