### ISSUE TITLE
[FR] Add templating to create new projects

### ISSUE THREAD

**Issue by conorbmurphy** [mlflow/mlflow#1944]
Creating a project from scratch is a difficult process and requires custom templating.  It'd be nice to add a command like `mlflow project init` to initialize a new project using a template.  It could also have commands to input values such as the project name, environment, etc.  It would then create a directory with all necessary files.

This would be a pretty lightweight change to MLflow

**Comment by jeloi** [comment]
Would using something like [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/) work?   Would just be a matter of seeding templates in the format of useful mlflow projects. Cookiecutter has a command line tool. You point the "create"command at a template repo and answer a series of prompts to configure the scaffolding.

**Comment by dbczumar** [comment]
@jeloi That sounds like a good idea. Is this something you'd be willing to work on?

**Comment by jeloi** [comment]
I can’t take this on at the moment unfortunately!

**Comment by chenmoneygithub** [comment]
this has been deprioritized for years, I am closing it and opening new one if necessary.
