### ISSUE TITLE
[BUG] Postgresql Alembic Migration Automatically Runs when running 'mlflow server' with no way to disable

### ISSUE THREAD

**Issue by JoeJasinski** [mlflow/mlflow#1948]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Stretch (Python 3.7.3 docker base image)
- **MLflow installed from (source or binary)**: from pypi via pip
- **MLflow version (run ``mlflow --version``)**: 1.3.0
- **Python version**: 3.7.3
- **npm version, if running the dev UI**: na
- **Exact command to reproduce**:

```
mlflow server \
    --default-artifact-root file://shared/mlruns/  \
    --backend-store-uri postgresql://***** \
    --host 0.0.0.0 \
    --port 5000 \
    --workers 4
```

### Describe the problem

When I run `mlflow server` using Postgresql for the storage backend, the migrations are automatically executed and I don't see a way in the docs or code to disable that behavior. 

This automatic migration is undesirable in situations where one would like to control exactly when their database is migrated (and not have it automatically migrated). Since MLFLow does have the `mlflow db upgrade` command, it does seem to indicate MLFlow may have been designed to separate the serving of the app from the migration of the database. However, it seems that adding the `--default-artifact-root` and the `--backend-store-uri` causes the database to automatically migrate. (I'm not sure what the purpose of `db upgrade` would be if its automatically run on first run of the server.)

I'm able to reproduce this inside of the python:3.7.3 docker image running inside of docker-compose and in kubernetes. 

### Code to reproduce issue

See the above command. This looks like where the tables are migrated as soon as `__init__` is called on the sqlalchemy backend.

https://github.com/mlflow/mlflow/blob/v1.3.0/mlflow/store/sqlalchemy_store.py#L97

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.

```
root@6e554811:/srv/# mlflow server --backend-store-uri ${BACKEND_STORE_URI} --default-artifact-root ${DEFAULT_ARTIFACT_ROOT}  --host 0.0.0.0 --port 5000
2019/10/17 19:54:31 INFO mlflow.store.sqlalchemy_store: Creating initial MLflow database tables...
2019/10/17 19:54:31 INFO mlflow.store.db.utils: Updating database tables at postgresql://*****
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
....
...
```

**Comment by sueann** [comment]
`mlflow server` should error out if you have an existing database with an older schema (https://github.com/mlflow/mlflow/blame/v1.3.0/mlflow/store/sqlalchemy_store.py#L135). The code you pointed to is actually creating tables if no mlflow tables exist in the database (so it assumes the database is "fresh"), and then it runs the migrations. Does this match your experience, or are you seeing migration happen if you already have an mlflow-initialized database as well?

**Comment by JoeJasinski** [comment]
Thank you for your reply. 

What I was noticing was that mlflow was trying to run the migration logic whenever one runs the server process (`mlflow server`). I understand that, when the migrations have already been applied, alembic sees that there is nothing to do and exits. 

However, when productionalizing mlflow inside a cluster, I would have to have absolute control over when the migrations run, and would like to run them independently of running `mlflow server`. Unless I am missing something, it looks like currently you cannot separate the running of the application from the running of the migrations - when you run the `mlflow server`, the migrations will always try to run. 

I was looking for a way to disable that automatic migration behavior.

**Comment by sueann** [comment]
It's essentially disabled by default because if you have a database with an older schema, `mlflow server` will error out telling you to run `mlflow db upgrade` and quit without applying any migrations. It's only if your database looks new (because it doesn't have any mlflow tables in it) it will create the tables with the latest schema (by applying all of the migrations).

**Comment by JoeJasinski** [comment]
Thank you again for the reply. So if I understand correctly, the first time the app runs (on an empty database) the migrations will run automatically? However, if I upgrade MLFlow and the upgrade requires database migrations, it will wait for me to manually apply the migrations with `mlflow db upgrade`?

**Comment by sueann** [comment]
Yeah that's correct.

**Comment by sueann** [comment]
Going to close this -- please reopen if you need, thanks!
