### ISSUE TITLE
Feature request: set the artifcat-root when creating an experiment programmatically. 

### ISSUE THREAD

**Issue by yassineAlouini** [mlflow/mlflow#195]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra Version 10.13.6
- **MLflow installed from (source or binary)**: binary (using pip)
- **MLflow version (run ``mlflow --version``)**: 0.3
- **Python version**: 2.7.10
- **npm version (if running the dev UI):
- **Exact command to reproduce**: 

### Describe the problem
I need to set the `artifcat-root` to a remote one (S3 store) while creating a new experiment using the `mlflow.create_experiment` method. Inspecting the code of this method, it seem that the only argument is `experiment_name`. 
I was able to change the `artifcat-root` default by creating an experiment using the command line `mlflow experiments create <experiment-name> --artifact-store <remote/artifact/store>` then using the  `mflow.create_experiment(<experiment-name>)`. 
Maybe it is possible to change the `artifcat-root` by using the `mlflow.set_tracking_uri`? If that is the case, then the method name is a little bit confusing (I though it was responsible for only changing where the metrics and logs are stored, i.e. the `file-store`). 

Thanks in advance. Let me know if you need more details.

**Comment by aarondav** [comment]
You're absolutely right, the experiment creation API should have support for providing an artifact store.

Do note that if you just need one or all experiments to be stored in the same bucket, the recommended path is to use `mlflow server` with `--default-artifact-root`. If you point mlflow to this tracking server, then all newly-created experiments will be at `$artifactRoot/$experimentId`. This might solve your immediate use-case.

**Comment by yassineAlouini** [comment]
Thanks for your response @aarondav. 
For now, I will deploy to a server with `mlflow server` + set the `--default-artifact-root` to `S3`. Then, point to that server URI using `mlflow.set_tracking_uri`.

**Comment by aarondav** [comment]
Great, glad that solves your problem. Let me make a PR to enable overriding the artifact-root from the experiment API; I will keep this issue open to track that work.

**Comment by smurching** [comment]
Thanks @yassineAlouini @aarondav! Closing this as #232 was merged (released with MLflow 0.4.2) :)

**Comment by yassineAlouini** [comment]
@smurching That's a good news. Thanks a lot. :)
