### ISSUE TITLE
[FR] Is it possible to version control the data 

### ISSUE THREAD

**Issue by dpanshu** [mlflow/mlflow#1950]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. I understand that you provide version control for source code, but is it possible to version control the data itself. I have some training data that is bootstrapped from weak labelers. I am making changes to the data every day. Is it possible to not store copies of data but instead use git like version control over changes made to training data.

**Comment by H4dr1en** [comment]
You might want to check dvc for that

**Comment by Lucas-Cerqueira** [comment]
Is there any thoughts on integrating mlflow with dvc? What I think is very interesting about dvc is when you define dependencies and outputs on a `run` command and it handles the version of these inputs/outputs.

**Comment by sueann** [comment]
Let's add to the discussion in https://github.com/mlflow/mlflow/issues/867 so we can keep track of everyone's thoughts in one place. Thanks!
