### ISSUE TITLE
Automated CrossValidator tracking [FR]

### ISSUE THREAD

**Issue by CyborgDroid** [mlflow/mlflow#1962]
When will automated spark MLlib tracking and scikit-learn tracking be available for CrossValidators? It is available only for databricks + spark MLlib. If it is not on the roadmap, can it be added? In the meantime, is there a workaround to log all of the parameters and metrics a CrossValidator tried using a local spark MLlib pipeline or scikit-learn pipeline?

https://docs.databricks.com/applications/machine-learning/automl/mllib-mlflow-integration.html

**Comment by CyborgDroid** [comment]
First attempt to replicate auto tracking of a Spark MLlib CrossValidator outside of databricks:

https://github.com/CyborgDroid/spark_mlflow/tree/develop

In the example above, I am logging the results of all Kfolds, but I still need to verify that databricks auto tracking does the same.

**Comment by dbczumar** [comment]
@CyborgDroid Sorry for the super delayed response here. Closer integration with CrossValidation tools in popular frameworks like scikit-learn and SparkML is definitely something we'd be interested in introducing. Please let me know if you're interested in filing a PR based on the work you've already done in this area.

**Comment by chenmoneygithub** [comment]
Sorry about it, but I don't think we will prioritize it in the foreseeable future. We will close it and reopen if necessary.
