### ISSUE TITLE
Alternative options to store artifacts remotely

### ISSUE THREAD

**Issue by ojtwist** [mlflow/mlflow#197]
Currently it is possible to let artifacts be stored either locally, using S3 or GFS. However, it would be interesting to have an additional option to let artifacts be stored on a custom NFS, or even have an option to let artifacts be stored on the same remote server that is logging all the other information. As far as I understand, this is not possible for the moment.

**Comment by mateiz** [comment]
You can use a file:// URI or a file system path to store things in NFS. You just need to mount it at the same path on all machines, but that's pretty common. That's also supported already by just specifying a file system path.

**Comment by aarondav** [comment]
+1 for NFS. Closing for now, but feel free to reopen for further discussion if the current solution is lacking.
