### ISSUE TITLE
[BUG] Missing boto3 dependency in mlflow python package

### ISSUE THREAD

**Issue by mirekphd** [mlflow/mlflow#1970]
- **Exact command to reproduce**:
-  take any system (e.g. an ubutunu with miniconda and python 3.6 docker container) with mlflow python package v1.3 installed using `pip install mlflow`,
- make sure that the connection from the mlflow python client library to the s3 bucket (in my case created using minio) is working (e.g. with curl),
- make sure mlflow server has no access to the internet (should you try to download and install the dependency at first use),
- create a new experiment, because otherwise local folder will still be used for artifact storage),
- train the model in python mlflow 1.3 client library, 
- log using log_model() and then 
- go to MLflow Tracking Web UI 
- click on the appropriate run (the one which should be stored remotely not locally), trying to access the artifacts from a remote S3 bucket (e.g. serverd by minio),
- hey presto, Niagara Falls gets displayed!

### Describe the problem
All dependencies of mlflow package should be either bundled-in (they were apparently not installed) or stated explicitly. Eg. "If you want to use S3 buckets for artifact storage (e.g. through minio) please install boto3 python package on the MLflow Tracking server side (e.g. in the docker container with the server)."

### Other info / logs
As we see, boto3 (and botocore) dependencies were not installed together with mlflow:
```
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'boto3'

>>> import botocore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'botocore'

>>> exit()

$ pip freeze
alembic==1.2.1
asn1crypto==0.24.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
conda==4.5.4
configparser==4.0.2
cryptography==2.2.2
databricks-cli==0.9.0
docker==4.1.0
entrypoints==0.3
Flask==1.1.1
gitdb2==2.0.6
GitPython==3.0.3
gorilla==0.3.0
gunicorn==19.9.0
idna==2.6
itsdangerous==1.1.0
Jinja2==2.10.3
Mako==1.1.0
MarkupSafe==1.1.1
mlflow==1.3.0
numpy==1.17.3
pandas==0.25.2
protobuf==3.10.0
pycosat==0.6.3
pycparser==2.18
pyOpenSSL==18.0.0
PySocks==1.6.8
python-dateutil==2.8.0
python-editor==1.0.4
pytz==2019.3
PyYAML==5.1.2
querystring-parser==1.2.4
requests==2.18.4
ruamel-yaml==0.15.37
simplejson==3.16.0
six==1.11.0
smmap2==2.0.5
SQLAlchemy==1.3.10
sqlparse==0.3.0
tabulate==0.8.5
urllib3==1.22
websocket-client==0.56.0
Werkzeug==0.16.0
jovyan@ml-mlflow-node1-4-rg5zs:~$ 

```

From server logs:
```
2019/10/22 07:24:53 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 366, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/s3_artifact_repo.py", line 65, in list_artifacts
    s3_client = self._get_s3_client()
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/s3_artifact_repo.py", line 27, in _get_s3_client
    import boto3
ModuleNotFoundError: No module named 'boto3'
2019/10/22 07:26:00 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/server/handlers.py", line 366, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/s3_artifact_repo.py", line 65, in list_artifacts
    s3_client = self._get_s3_client()
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/s3_artifact_repo.py", line 27, in _get_s3_client
    import boto3
ModuleNotFoundError: No module named 'boto3'

```

**Comment by mirekphd** [comment]
I can confirm now that installing boto3 together with mlflow solves this particular bug.

**Comment by gustavomr** [comment]
same problem here. 

I installed it manually and then asking me for a package called dateutil. I installed it manually again (pip3 install python-dateutil) and now getting this error:

botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by jmdinis** [comment]
@gustavomr I'm having the same issue. 

I'm running mlflow server from an EC2 instance with artifact root pointing to an S3 bucket. It all runs fine. Artifacts are saved to S3. But when I access the UI and click in a run, the issue "ModuleNotFoundError: No module named 'boto3'" jumps in in the server. I installed boto3 in the server and fixed it, but now I'm getting "botocore.exceptions.NoCredentialsError: Unable to locate credentials" even though I have AWS credentials defined as env variables. 

How can I solve this?

**Comment by gustavomr** [comment]
@jmdinis What I noticed is that running with db configured solved my problem. The command that I used:

mlflow server \
    --backend-store-uri sqlite:///mlflow.db \
    --default-artifact-root file:///home/myuser/mlruns \
    --host 127.0.0.1

**Comment by mirekphd** [comment]
Two minor releases later... This unmet dependency on `boto3` is still going on in `mlflow` v1.5, so it is increasingly looking like a feature.

**Comment by smurching** [comment]
@mirekphd the lack of boto3 dependency in core MLflow is indeed intentional to keep the set of MLflow dependencies minimal. Note that you can `pip install mlflow[extras]` and boto3 will be installed

**Comment by qcha41** [comment]
Having the same issue, I had to install manually boto3 on the client side.

**Comment by DeboraLott** [comment]
How can I install manually boto3 on the client or the server side? Because I already tried all the pip, conda, update end etc kinds of ways to install boto3 on the virtual env created on conda, but It always appear that boto3 is not installed, but if I check the version, it is there!! 

(myenv) C:\RepositoriosGitLab\mlflow_ne_test>mlflow run examples/sklearn_elasticnet_wine_ne -P alpha=0.42
2021/02/09 15:40:57 INFO mlflow.projects.utils: === Created directory C:\Users\DEBORA~1.LOT\AppData\Local\Temp\tmpxmslboz0 for downloading remote URIs passed to arguments of type 'path' ===
2021/02/09 15:40:57 INFO mlflow.projects.backend.local: === Running command 'conda activate mlflow-004410b12f95e2e00831a0ba11ee1bfdc29d6f9d && python train.py 0.42 0.1' in run with ID '86fce21773314a06ad417ea061aa7efd' ===
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import boto3, os, io
ModuleNotFoundError: No module named 'boto3'
2021/02/09 15:40:57 ERROR mlflow.cli: === Run (ID '86fce21773314a06ad417ea061aa7efd') failed ===


(myenv) C:\RepositoriosGitLab\mlflow_ne_test>conda list boto3
# packages in environment at C:\Users\debora.lott\Anaconda3\envs\myenv:
#
# Name                    Version                   Build  Channel
boto3                     1.9.66                   py37_0    anaconda

**Comment by DeboraLott** [comment]
The solution for my problem was really simple, I just needed to add the library that I was trying to import as a dependence in the archive: **conda.yaml**. 
Previous of my modification the archive was: 

              name: tutorial
              channels:
                - defaults
              dependencies:
                - python=3.6
                - pip
                - pip:
                  - scikit-learn==0.23.2
                  - mlflow>=1.0

Now I just put boto3 in the end, turning it on this:

              name: tutorial
              channels:
                - defaults
              dependencies:
                - python=3.6
                - pip
                - pip:
                  - scikit-learn==0.23.2
                  - mlflow>=1.0
                  - boto3

End them, finally it works!
