### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MeisterUrian** [mlflow/mlflow#1975]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: custom model training script
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu  16.04 in Docker container
- **MLflow installed from (source or binary)**: source (mlflow repository, master branch)
- **MLflow version (run ``mlflow --version``)**: 1.3.1.dev0
- **Python version**: 3.7.3
- **npm version, if running the dev UI**: 3.10.10
- **Exact command to reproduce**: docker-compose up

### Describe the problem
1) On open some run in **mlflow ui**: 
```python
2019/10/22 10:20:08 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/Flask-1.1.1-py3.7.egg/flask/app.py", line 2446, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.7/site-packages/Flask-1.1.1-py3.7.egg/flask/app.py", line 1951, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python3.7/site-packages/Flask-1.1.1-py3.7.egg/flask/app.py", line 1820, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/local/lib/python3.7/site-packages/Flask-1.1.1-py3.7.egg/flask/_compat.py", line 39, in reraise
     raise value
   File "/usr/local/lib/python3.7/site-packages/Flask-1.1.1-py3.7.egg/flask/app.py", line 1949, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.7/site-packages/Flask-1.1.1-py3.7.egg/flask/app.py", line 1935, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/usr/local/lib/python3.7/site-packages/mlflow-1.3.1.dev0-py3.7.egg/mlflow/server/handlers.py", line 137, in wrapper
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/mlflow-1.3.1.dev0-py3.7.egg/mlflow/server/handlers.py", line 581, in _search_model_versions
     model_versions_detailed = _get_model_registry_store().search_model_versions(
 AttributeError: 'NoneType' object has no attribute 'search_model_versions'
```

2) On click **Register Model**:

![mlflow_model_registry_error](https://user-images.githubusercontent.com/21148145/67286896-1d86c280-f515-11e9-8880-8c38d4bf2b37.png)

### Code to reproduce issue

*Project sources* [mlflow_model_registry.zip](https://github.com/mlflow/mlflow/files/3755699/mlflow_model_registry.zip)

Archive content:

I. Dockerfile

```dockerfile
FROM python
WORKDIR /home

# RUN pip install sklearn git+https://github.com/mparkhe/mlflow.git@ssue-19
RUN apt-get update && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs npm

RUN pip install sklearn

RUN git clone https://github.com/mlflow/mlflow && \
    cd mlflow && python setup.py install && \
    cd mlflow/server/js && npm install

ENV MLFLOW_TRACKING_URI=/home/mlruns

CMD mlflow server --host 0.0.0.0 --port 5000 & (cd mlflow/mlflow/server/js && npm start)
```
II. docker-compose.yml
```yaml
version: '3'

services:
  mlflow_model_registry:
    build:
      context: .

    image: mlflow_model_registry:latest

    container_name: mlflow_model_registry_1

    ports:
      - 5000:5000
      - 3000:3000

    volumes:
      - ./main.py:/home/main.py
      - ./mlruns:/home/mlruns
````
III. main.py

```python
import joblib
import mlflow
from mlflow.sklearn import log_model
from sklearn import svm
from sklearn import datasets


clf = svm.SVC(gamma='scale')
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf.fit(X, y)

joblib.dump(clf, 'iris.model')

log_model('iris.model', 'model')
```

Run all:

1. build image and run container

```bash
docker-compose build
docker-compose up
```

2. enter docker container in new terminal window

```bash
docker exec -ti mlflow_model_registry_1 /bin/bash
```

3. run training script

```bash
python main.py
```

4. open [dev UI](http://localhost:3000)

**Comment by harupy** [comment]
@MeisterUrian I ran into the exact same issue. 

> Model Registry does not support file based stores.

https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L60

**Comment by MeisterUrian** [comment]
@harupy Thank you very much! I will try it some later

**Comment by harupy** [comment]
@MeisterUrian I followed this doc.

https://www.mlflow.org/docs/latest/tracking.html#logging-to-a-tracking-server

**Comment by kadakia** [comment]
@harupy Should model registry work if the tracking server is on an ec2 instance, with artifacts being logged to s3?  Because I'm running into the same issue, it seems.

**Comment by harupy** [comment]
@kadakia I haven't tested that case yet. How does your tracking server URI look like?

**Comment by kadakia** [comment]
@harupy Thanks for getting back to me so quickly.  Can you clarify what you mean?  Thanks.

**Comment by kadakia** [comment]
@harupy And when I try `mlflow.sklearn.log_model(model, "model", registered_model_name="test-model")`, I am seeing `mlflow.exceptions.MlflowException: API request to https://<REMOTE_TRACKING_URI>/api/2.0/preview/mlflow/registered-models/create failed to return code 200 after 3 tries` in my terminal

**Comment by harupy** [comment]
```
mlflow.exceptions.MlflowException: API request to https://<REMOTE_TRACKING_URI>/api/2.0/preview/mlflow/registered-models/create failed to return code 200 after 3 tries
```

Is this the whole error message?

**Comment by harupy** [comment]
`mlflow.set_tracking_uri("<REMOTE_TRACKING_URI>")`

Did you replace `<REMOTE_TRACKING_URI>` with a valid URI when you ran the code?

**Comment by kadakia** [comment]
@harupy Yes

**Comment by kadakia** [comment]
@harupy Let me know if I can provide more information about the issue

**Comment by harupy** [comment]
@kadakia Got it

**Comment by liuweibin6566396837** [comment]
> @MeisterUrian I ran into the exact same issue. This is because Model Registry does not support file based stores yet. (https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L60)
> 
> I used my local PostgreSQL as a tracking server and it worked.

I met the same problem, how can PostgreSQL save model flies, thanks!

**Comment by Guoyoyo** [comment]
I also tried postgresql to replace file-based and it worked. Just revise this line: --backend-store-uri postgresql://<user>:<password>@<ip>/<db>

**Comment by SteNicholas** [comment]
@harupy If model registry is file-based, how to solve this INTERNAL_SERVER_ERROR when create a new model in "Register Model" window?

**Comment by SteNicholas** [comment]
> Model Registry does not support file based stores yet.

When does Model Registry support file based stores? And [MLflow Model Registry](https://mlflow.org/docs/latest/model-registry.html#concepts) doesn't mention about this.

**Comment by SteNicholas** [comment]
> @MeisterUrian I ran into the exact same issue. This is because Model Registry does not support file based stores yet. (https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L60)
> 
> I used my local PostgreSQL as a tracking server and it worked.

When does Model Registry support file based stores? And [MLflow Model Registry](https://mlflow.org/docs/latest/model-registry.html#concepts) doesn't mention about this. It is necessary to tell the truth for new users that Model Registry doesn't support file based stores.

**Comment by SteNicholas** [comment]
> @MeisterUrian I ran into the exact same issue. This is because Model Registry does not support file based stores yet. (https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L60)
> 
> I used my local PostgreSQL as a tracking server and it worked.

@harupy When does Model Registry support file based stores? And [MLflow Model Registry](https://mlflow.org/docs/latest/model-registry.html#concepts) doesn't mention about this. It is necessary to tell the truth for new users that Model Registry doesn't support file based stores.

**Comment by harupy** [comment]
> When does Model Registry support file based stores?

Sorry, I'm not sure...

**Comment by SteNicholas** [comment]
> @SteNicholas
> 
> > When does Model Registry support file based stores?
> 
> Sorry, I'm not sure...

Okay, thanks.
