### ISSUE TITLE
[FR] Allow more than 250 characters for parameter values

### ISSUE THREAD

**Issue by sadanand-singh** [mlflow/mlflow#1976]
Currently only parameters that have a value less than 250 characters are allowed.

It would be great to make this limit an user parameter. I have a use case where I would like this to be 500 characters.

**Comment by aarondav** [comment]
Tags have a higher allowed limit -- could your use-case be satisfied with tags instead of parameters?

**Comment by sadanand-singh** [comment]
No, I would like it to be a parameter specially since tags are mutable. Rather than an arbitrary larger limit, I think if possible, it would be great to provide an option for user-defined limit.

**Comment by ncoish** [comment]
We're having the same issue, and this feature would be greatly appreciated

**Comment by dbczumar** [comment]
We now have a higher, 500-character limit for parameters. Thank you for using MLflow!
