### ISSUE TITLE
[BUG] failed artifact logging to s3 breaks run view in UI

### ISSUE THREAD

**Issue by C-nit** [mlflow/mlflow#1979]
### Describe the problem
"Oops! Something went wrong." appears in the mflow UI detail view for runs.
This error page comes up in different scenarios where logging artifacts to s3 is not successful. I don't know if other remotes are also affected in some form.

The UI should not break from this, but rather inform the user what the problem is (e.g. in the artifacts section).
While logging on client side I would expect a warning message that the artifact logging failed.

### Code to reproduce issue
Possible ways to break artifact logging to s3 include
- bucket missing on s3 (`--default-artifact-root`, `--artifact-location`)
- wrong credentials (`AWS_ACCESS_KEY_ID, `AWS_SECRET_ACCESS_KEY`)
- wrong endpoint_url ( `MLFLOW_S3_ENDPOINT_URL`)

### Other info / logs
related to https://github.com/mlflow/mlflow/issues/1855#issuecomment-534276087

**Comment by Zangr** [comment]
@C-nit Thank you for filing this bug. It makes sense to have UI show more explanatory text rather than just break. Would you like to submit a PR to fix it?

**Comment by dbczumar** [comment]
Hi @C-nit , we believe our UI is now robust to this case. Please feel free to reopen it if the issue still occurs.
