### ISSUE TITLE
Feature request: Handle PyTorch models 

### ISSUE THREAD

**Issue by vfdev-5** [mlflow/mlflow#198]
Hi, wonder on your planning to itegrate the support for PyTorch models as it is done for [TF models](https://github.com/databricks/mlflow/blob/master/mlflow/tensorflow.py)?
Thanks

PS: I can give a hand on it if needed.

**Comment by aarondav** [comment]
We definitely want to add PyTorch support, and your contribution would be more than welcome! If you want an example PR that added support for H2O models, take a look at #170.

**Comment by vfdev-5** [comment]
@aarondav I'm trying to work on this issue. A question on tests, why h2o tests are in `tests/mlflow/h2o` and other model handlers as spark, sklearn, tensorflow are at `tests` and not in `tests/mlflow` ? 

and 

Wrapper classes as `_PyFuncModelWrapper`, `_H2OModelWrapper`, `_TFWrapper` should not inherite from an interface with `predict` method and a well described input (today `pandas.DataFrame`) ? Another question concerning tensorflow wrapper and similar probably future ones for pytorch, keras etc such wrappers can be also devoted to predict on images. So user is intended to put his image(s) into `pandas.DataFrame` ?

Thanks!

PS: I asked the same questions on slack

**Comment by juntai-zheng** [comment]
Hi @vfdev-5, we've actually started some work on designing MLflow support for PyTorch, which you can see [here](https://docs.google.com/document/d/1dVljRv54oUcc5uGAiAzv2tZCUlxBu7LveKdNzBS-fXQ/edit?usp=sharing). What do you think? Would you have time to work on it? If not, I could start working on it soon.

@smurching do you have input on the questions that vfdef-5 has?

**Comment by vfdev-5** [comment]
@juntai-zheng I already implemented some stuff in [my fork](https://github.com/mlflow/mlflow/compare/master...vfdev-5:pytorch_save_model). Could you also give me the access to the google drive doc you are mentioning here ?

**Comment by aarondav** [comment]
@vfdev-5 Ah, `tests/h2o` is where the tests should be. We actually did a refactoring where we moved all the tests to the appropriate location; that PR must've been in flight when we did that. We'll move that one as well.

It's a good point that there should be a top-level class that the wrapper classes inherit from, to help enforce the schema, although this is not strictly required within Python. And also a good point re: images, today they would have to be encoded as a list within the DataFrame, which is not super easy to work with. 

We are currently thinking about how to deal with pyfunc input in a way that better supports use-cases like this (cc @mateiz). In the case of images, what is the most natural format you've worked with? TF tensors? Numpy arrays?

**Comment by vfdev-5** [comment]
@aarondav 
> In the case of images, what is the most natural format you've worked with? TF tensors? Numpy arrays?

I'm mostly working with pytorch than TF, I think numpy array would be a more natural type of input. 

However, single image as input can be a restrictive choice as model can potentially work with multiple inputs. I think pyfunc predict interface can work no a data (by default a single ndarray) and may need to accept a two adapter functions for input and output. So in case of a specific input, user could provide methods to transform input into model's input and to transform model's output into mlflow acceptable data. What do you think ?

**Comment by juntai-zheng** [comment]
Hey @vfdev-5, I updated the link to the design doc [here](https://docs.google.com/document/d/1dVljRv54oUcc5uGAiAzv2tZCUlxBu7LveKdNzBS-fXQ/edit?usp=sharing).
