### ISSUE TITLE
[FR] Keep nested runs in UI filtering

### ISSUE THREAD

**Issue by julilien** [mlflow/mlflow#1984]
### Motivation
In Mlflow's UI, the string provided in "Search Runs" in the experiments' run lists is used to eliminate runs from search results based on given attribute masks (for instance ```param.xy = "test"```). While this works as expected, it requires nested runs to also store the parameters of the parent run if you want to query them in combination. If parameters are only assigned to parent runs, filtering for these will result in the elimination of the child runs.

As an example, consider organizing hyperparameter optimization runs by having a parent run characterized by more general settings, e.g. the maximal runtime budget for the complete optimization, while the nested runs are individual evaluations for specific parameter sets. It would be redundant to also store all the parent run's parameters (and also metrics btw) in the child runs. If you now want to filter runs with a specific maximal runtime, you will only get these parents runs, but none of their child runs.

Additionally, the lack of the ability to "jump" from a parent run to a list of the children runs (as you can jump from the child to the parent, which is of course more "natural" due to the ```1:n``` relation of parents to children) makes it difficult to retrieve the actual runs for a specific parameter, which is only available at parent nodes.

### Proposed Changes
One could fix this issue by adding a checkbox indicating whether one would also include the nested runs in the search results. Consequently, filtering runs would keep the nested runs in the search result for easier traceability. Since this is often not desired, e.g. to keep the number of search results small, the checkbox is disabled by default. Alternatively, one could add a keyword for the search query, which would include the nested results.
Technically speaking, this checkbox would change the internal queries, s.t. for each run, which is returned by this statement, all of its nested runs are considered, too.

**Comment by ODemidenko** [comment]
In general, in search results - for a run that contains other nested runs it should be always clear that smth nested exists (now it is not clear in the search dialog, when nested runs are not shown in the search result).
To continue with this idea of linking parent and nested runs:
Now there is no way to navigate to the nested runs from the parent run window.
It will greatly improve the convenience to be able to open from the parent run the "compare runs" window with all its children. As parent run by itself is usually used only as a mean to navigate to its children.

**Comment by smurching** [comment]
Related: https://github.com/mlflow/mlflow/issues/1896

**Comment by chenmoneygithub** [comment]
duplicated #1896
