### ISSUE TITLE
mlflow.org/docs/ and mlflow.org/docs/latest/ should redirect to mlflow.org/docs/latest/index.html

### ISSUE THREAD

**Issue by andyk** [mlflow/mlflow#201]
Currently they return an AccessDenied error, but they should just redirect for when people manually enter mlflow.com/docs -- which will probably happen somewhat regularly

**Comment by aarondav** [comment]
Good point. Probably we can add an `index.html` that posts a redirect, that might be the simplest for CloudFront deployment. PR? :)
