### ISSUE TITLE
CLI Tracking Issues w/ v1.3.0, works with v1.0.0 [BUG]

### ISSUE THREAD

**Issue by kaleko** [mlflow/mlflow#2015]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX and Ubuntu
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 1.0.0 AND 1.3.0
- **Python version**: Python 3.7.3 

### Describe the problem
Unit test of listing existing experiments in the tracking UI which used to work for mlflow v1.0.0 fails for v1.3.0.

### Code to reproduce issue
```
>>> import os, mlflow
>>> from mlflow.tracking import MlflowClient
>>> os.environ['MLFLOW_TRACKING_URI'] = 'http://mytrackurl:mytrackport'
>>> foo = MlflowClient()
>>> foo.list_experiments()
```
In my case I am using an external tracking server, where the url is not localhost.

This works as expected (returns a list of experiments) for mlflow v1.0.0, but fails for mlflow v1.3.0. The failure output in v1.3.0 is:

mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/list failed with error code 404 != 200. Response body: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

**Comment by jrinvictus** [comment]
did you ever solve this issue?  I'm running into the same thing.

**Comment by kaleko** [comment]
> did you ever solve this issue? I'm running into the same thing.

No, I am still using mlflow 1.0.0 specifically because of this issue.

**Comment by juntai-zheng** [comment]
Hi @jrinvictus and @kaleko, is this issue still appearing for you in 1.6?
