### ISSUE TITLE
[FR] parameter information in Active Run object

### ISSUE THREAD

**Issue by CJ-Wright** [mlflow/mlflow#2023]
Would it be possible to access the data about an active run from the `ActiveRun` object? This would prevent needing to go to the mlflow store itself to load the run information.

### Motivation
The use case is for viewing the metadata about the current run. This would be valuable for exporting to other services and preventing the need to examine the data store for information that could be in memory.

### Proposed Changes
Rather than returning an empty parameter dict for `ActiveRun.to_dictionary()` populate with the parameters that have been added so far. Similar changes for artifacts and metrics.

**Comment by chenmoneygithub** [comment]
I had the same ask weeks earlier, and the context is it's more challenging than it seems to keep sync between active run and the run in store, so for clarity the store provides the single source of truth.
