### ISSUE TITLE
[BUG] Kubernetes environment issue

### ISSUE THREAD

**Issue by chuber1986** [mlflow/mlflow#2025]
Hi,

when using the kubernetes bakend I encounter some issues:

- within the container the environmental variable MLFLOW_TRACKING_URI is set to the host tracking path instead of the _MLFLOW_DOCKER_TRACKING_URI.
- the tracking path is not mounted in the container (the mountpoint had to be specified manually in the kubernetes_job_template.yaml)

BR Christian

**Comment by marcusrehm** [comment]
HI @chuber1986 , 

Did you setup the MLFLOW_TRACKING_URI  pointing to host and had a mlflow server running on it? Are you running in minikube?

Can you try to run following the steps described in this issue https://github.com/mlflow/mlflow/issues/2060#issuecomment-629222242 ?

**Comment by AveshCSingh** [comment]
Closing this issue, as it was fixed by #2874.
