### ISSUE TITLE
[FR] run duration comparison

### ISSUE THREAD

**Issue by alexnikitchuk** [mlflow/mlflow#2029]
Current version of run comparison doesn't show run duration I suggest it will be useful to observe it there
![image](https://user-images.githubusercontent.com/8694829/67938488-41629c00-fbd8-11e9-860a-05d50fe2d83f.png)

**Comment by smurching** [comment]
@alexnikitchuk this is a good idea, I'd be happy to review a PR that contributes this. @gioa do you have ideas on what a good UX for this would be? I guess a naive strawman would be another table row (below "Run ID", "Run Name", "Start Time") that includes the run duration across runs

**Comment by RealArpanBhattacharya** [comment]
@pogil @alexnikitchuk  Potential fix - https://github.com/mlflow/mlflow/pull/3378

**Comment by harupy** [comment]
Addressed by #3378
