### ISSUE TITLE
[BUG] MLFlow UI not displaying as expected

### ISSUE THREAD

**Issue by ssami** [mlflow/mlflow#2032]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.14.6
- **MLflow installed from (source or binary)**: binary (pip install)
- **MLflow version (run ``mlflow --version``)**: `1.4.0`
- **Python version**: `3.7.4`
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: `mlflow ui`

### Describe the problem
The UI is not as clearly laid out as the examples and quickstart show. Here's what you would expect: 
<img width="1468" alt="Screen Shot 2019-11-01 at 1 52 43 PM" src="https://user-images.githubusercontent.com/940521/68055877-ea7bc600-fcae-11e9-90ca-348a894ab7fa.png">

But here is the UI I see, in both my local environment as well as built in a Docker container. 
<img width="1799" alt="Screen Shot 2019-11-01 at 1 46 36 PM" src="https://user-images.githubusercontent.com/940521/68055681-72ad9b80-fcae-11e9-845b-0a287426f8ad.png">
`corpus_path` is a parameter, and `foo` and `foo2` are metrics, but you can't see that from this rendering of the UI. 

Longer parameter names don't seem to wrap around and I can't see those from the UI unless I inspect element. Basically, the UI isn't rendering as expected. 

### Code to reproduce issue
- create a Conda environment and install mlflow with `pip install mlflow==1.4.0`
- run `mlflow server --backend-store-uri ${DB_CONNECTION} --default-artifact-root ${ARTIFACT_ROOT} --host ${HOST} --port ${PORT}` or even `mlflow ui`

**Comment by Christoph460** [comment]
I can reproduce the meant bug in the GUI rendering. There is no header line grouping the "parameters" and "metrics". 

Example image: column "input", "input1" and "Paramters" are Parameter, "i", "looooong" and "result" are metrics. This not clear, if you don't know that. 
![image](https://user-images.githubusercontent.com/9005118/72602445-954b6a00-3917-11ea-82fe-47d3418c6a8b.png)

**Comment by dbczumar** [comment]
@Christoph460 @ssami Thank you for filing this issue. The images in these parts of our MLflow documentation have note been updated to account for recent UI changes. We'll audit images that need updating and hopefully have the docs updated soon!

**Comment by ssami** [comment]
Thanks for checking on this @dbczumar. Does this mean that the images that @Christoph460 and I have been uploading reflect the current, latest UI? If so that's disappointing, because the UI becomes harder to read. Looking forward to the clarifications in the readme and docs.

**Comment by dbczumar** [comment]
@ssami The new default MLflow UI (column-based view) provides parameter / metric grouping headers and enables columns to be resized. 

cc @Zangr for information about the old view: are we deprecating this view?

**Comment by Zangr** [comment]
Recent change has already made the new multi-column view the default view. Let's get more data on the usage and see if we need a deprecation plan.

**Comment by ssami** [comment]
@dbczumar Updating to 1.7 has answered pretty much all my concerns about the view -- I'm able to see the full names, etc and columns are visualizing as expected. Thank you! I am closing this as a bug.
