### ISSUE TITLE
[BUG] Unable to run mlflow behind jupyter-server-proxy

### ISSUE THREAD

**Issue by xhochy** [mlflow/mlflow#2038]
Same issue as https://github.com/mlflow/mlflow/issues/1120 but 1.4 reintroduced the need for absolute paths which is not possible when running behind a dynamic proxy.

**Comment by xhochy** [comment]
The problem roots in the react app added in https://github.com/mlflow/mlflow/pull/1943 This leads to links for me in the `static-worker.js` that refer to `https://localhost/proxy/5346/static-files/static-files/static/media/empty.91661969.svg`. I guess this needs an adjustment of https://github.com/mlflow/mlflow/blob/ce299a7b8f9de50b4c4c4c76a82ba0386edca44f/mlflow/server/js/package.json#L76

**Comment by xhochy** [comment]
The UI is working well, the only thing that produces these errors is the pre-caching using the service-worker. This leads to a lot of failed requests in the JavaScript console. Thus fixing is not a critical for using `mlflow` behind proxy under a different path but still worth exploring if we need to adjust the `swUrl` in the source.

**Comment by mattlbeck** [comment]
HI @xhochy, I'm afraid I have the same issue on 1.6.0 but I am only half following your diagnosis here. What do I need to do to prevent the mlflow UI errors, leading to internal server errors, when attempting to use the UI behind a jupyter proxy?
