### ISSUE TITLE
[BUG] Spark UDF spark_udf() fails for H2o models

### ISSUE THREAD

**Issue by kucera-jan-cz** [mlflow/mlflow#2041]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker (debian stretch) in Windows 10
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**: Python 3.5.3
- **npm version, if running the dev UI**: No
- **Exact command to reproduce**: Below

### Describe the problem
I am trying to use your spark_udf function for Spark to run model created by H2O. My setup is one docker image with spark and one with mlflow. I was able to log model through your code and serve it through `mlflow models serve` however I am failing to achive prediction in spark where H2O is failing saying my dataframe doesn't have required columns (see log where is also printing that DF contains required columns). H2o version is same on both containers however python version differs. Can you please advise me whether there is some way to achieve predictions?

### Code to reproduce issue
```
from pyspark.sql import SparkSession
import mlflow
from mlflow import pyfunc
import h2o
from mlflow.h2o import load_model
from pyspark.sql.types import IntegerType

h2o.init()

sc = SparkSession.builder.appName("Python Spark with MlFlow").getOrCreate()

mlflow.set_tracking_uri("http://mlflow:5000")

model_path = "runs:/87da0a12c7974f1b9cf6d1d6726aaed8/model"
model_udf = mlflow.pyfunc.spark_udf(sc, model_path, IntegerType())

model = load_model(model_path)
print('MODEL:')
print('-----')
print(model.summary())

df = sc.read.csv('/var/local/data/rai_data/wine_quality_h2o_test.csv',
                 header=True,
                 sep='|')
df.show(1)
df.select("density", "alcohol", "pH", "sulphates").show(1)
print(df.withColumn("prediction",
                    model_udf("density", "alcohol", "pH", "sulphates")
                    ).show(3))
```

### Other info / logs
Logs with output and error placed in file [output.txt](https://github.com/mlflow/mlflow/files/3809527/output.txt)

**Comment by kucera-jan-cz** [comment]
Pinging regarding this issue.

**Comment by MichaelMarien** [comment]
hi @kucera-jan-cz i believe this is because of a known issue:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mlflow-users/y8hhL4ecb7k/RFK4dC7tAQAJ
not sure about the fix mentioned there. In my organisaton we are using a custom h2o flavor that uses the "_model_json" property of h2o models to do the correct renaming of the columns (names are lost in the way mlflow sets up the udf). I'd be happy to PR that fix but haven't because it uses a private property. I made an issue at h2o a while ago to provide a stable interface, but no response on that :(

**Comment by MichaelMarien** [comment]
@kucera-jan-cz , I think the solution will be provided by Spark 3.x In that case, you can send a struct column to a pandas_udf and that one actually still knows the column names. Seems this functionality is already implemented in mlflow, just waiting for a stable PySpark release that supports it!

**Comment by tomasatdatabricks** [comment]
Thanks for responding @MichaelMarien!
