### ISSUE TITLE
[BUG] Gif animation stopped working after MLFlow 1.4 upgrade

### ISSUE THREAD

**Issue by andrey-tsykunov** [mlflow/mlflow#2042]
### System information
- **OS Platform and Distribution (RHL 7.6)**:
- **MLflow installed from (binary, pip)**:
- **MLflow version (1.4.0)**:
- **Python version 3.6.8**:

### Describe the problem
Previously MLFlow UI artifacts viewer was able to display animated gifs which were VERY useful. Since 1.4 it stopped working.

It might be related to this PR: #1934

**Comment by harupy** [comment]
@andrey-tsykunov @aarondav  I didn't notice this side effect.

**Comment by harupy** [comment]
Fixed it
![gif-demo](https://user-images.githubusercontent.com/17039389/68228507-ecd87a00-0038-11ea-8d58-fcea1cb1ccd1.gif)

**Comment by harupy** [comment]
I'll clean up the code and create a PR.

**Comment by andrey-tsykunov** [comment]
@harupy Thanks for quick turn around!

**Comment by harupy** [comment]
@andrey-tsykunov Created a PR to fix this issue #2070

**Comment by harupy** [comment]
@andrey-tsykunov Can you close this issue because it's resolved by #2070?
