### ISSUE TITLE
[DOC-FIX] Artifact store URI not only as Tracking Server config

### ISSUE THREAD

**Issue by fabboe** [mlflow/mlflow#2044]
### URL(s) with the issue:
https://www.mlflow.org/docs/latest/tracking.html#id37

### Description of proposal (what needs changing):
mlflow server with default artifact root
```
mlflow server --backend-store-uri file:///mnt/mlflow-backend/tracking/mlruns --host 0.0.0.0 --default-artifact-root file:///mnt/mlflow-backend/artifacts
```
Now the client tries to create `/mnt/mlflow-backend/artifacts` on the local client. The section "[Artifact Stores](https://www.mlflow.org/docs/latest/tracking.html#artifact-stores)" is a subsection of "Tracking Servers" and says "In addition to local file paths ..". Does it really support local file paths on the server? Am I hitting a bug>

If not, assuming that the client needs a network-type URI for artifact stores - should this section maybe not be _only_ in Tracking Servers but also in the Client docs? Currently I read it as if Artifact Stores can be configured inside Tracking Servers and then a client just takes `MLFLOW_TRACKING_URI` and that's it (as also [this](https://github.com/mlflow/mlflow/issues/1790#issuecomment-526050888) answer suggests) - it can log artifacts to the servers artifact store.

**Comment by dbczumar** [comment]
@fabboe "In addition to local file paths" refers to the fact that artifacts can be stored on UNIX or Windows filesystems. It is not possible at this juncture to stream artifacts through the MLflow server to a remote filesystem; you may log them to your local filesystem.
