### ISSUE TITLE
[DOC-FIX] Unexpected artifact path on local client instead default inside --backend-store-uri

### ISSUE THREAD

**Issue by fabboe** [mlflow/mlflow#2045]
### URL(s) with the issue:
https://www.mlflow.org/docs/latest/tracking.html#id37

#### mlflow server w/o default artifact root
```
mlflow server --backend-store-uri file:///mnt/mlflow-backend/tracking/mlruns --host 0.0.0.0
```
Then a simple example like `log_artifacts(..)` from the [example](https://github.com/mlflow/mlflow/blob/master/examples/quickstart/mlflow_tracking.py#L20) actually tries to put the artifact on the path /mnt/mlflow-backend/tracking/mlruns on the client machine - not the server. 

Current docs say
```
If you do not specify a --default-artifact-root [..], the artifact root is a path inside the file store. Typically this is not an appropriate location, as the client and server probably refer to different physical locations (that is, the same path on different disks).
```
I would emphasize: ... the artifact root is a path inside the **client's** file store. Otherwise I would assume the file store of the server is meant (since that's what this whole page and section is about).

**Comment by dmatrix** [comment]
This is related to [this issue](https://github.com/mlflow/mlflow/issues/2834) and will get documented once the PR is filed, reviewed, and merged.
