### ISSUE TITLE
[FR] Color rows in "Experiments" page

### ISSUE THREAD

**Issue by simonberthaux** [mlflow/mlflow#2052]
### Describe the proposal
We should be able to color rows in "Experiments" page (i.e. green, red or blue)

### Motivation
With this, we could see in one look which experiments have succeeded, failed or are running

**Comment by dbczumar** [comment]
Hi @simonberthaux, MLflow 1.6 was just released and includes run status icons (succeeded, failed, running, etc) in the MLflow Runs table within the Experiment view. Accordingly, I'm going to go ahead and close this issue. Happy MLflow-ing!
