### ISSUE TITLE
[BUG] MLflow with kubernetes (docker example) run locally

### ISSUE THREAD

**Issue by macimovic** [mlflow/mlflow#2060]
System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Pop OS 18.04
- **MLflow installed from (source or binary)**: using pip
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**: 3.6.5
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow run examples/docker -P alpha=0.5 --backend kubernetes --backend-config examples/docker/kubernetes_config.json

Describe the problem
I am trying to run the docker example on Kubernetes and my container crashes. I am providing the traceback of the container. I am running on a local Kubernetes cluster (minikube). I did not edit the kubernetes_job_template.yaml. I've edited the kubernetes_config.json to point to my kube-context and to my repository. Is there anything else that I should be doing (like volume mounts etc.) otherwise this is a bug.

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

### Other info / logs
2019/11/08 14:05:36 INFO mlflow.projects: === Building docker image macimovic/mlflow-kubernetes-example:7fd12b4 ===
2019/11/08 14:05:36 INFO mlflow.projects.kubernetes: === Pushing docker image macimovic/mlflow-kubernetes-example:7fd12b4 ===
2019/11/08 14:05:50 INFO mlflow.projects: === Created directory /tmp/tmpso5eg5at for downloading remote URIs passed to arguments of type 'path' ===
2019/11/08 14:05:50 INFO mlflow.projects.kubernetes: === Creating Job docker-example-2019-11-08-14-05-50-362961 ===
2019/11/08 14:05:50 INFO mlflow.projects.kubernetes: Job started.
2019/11/08 14:05:55 INFO mlflow.projects.kubernetes: Job has reached the specified backoff limit
2019/11/08 14:05:55 ERROR mlflow.cli: === Run (ID '3ddb5f0527674fe3b396e4300c946868') failed ===

Traceback (most recent call last):
  File "train.py", line 53, in <module>
    with mlflow.start_run():
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/fluent.py", line 121, in start_run
    active_run_obj = MlflowClient().get_run(existing_run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/client.py", line 92, in get_run
    return self._tracking_client.get_run(run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 47, in get_run
    return self.store.get_run(run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/tracking/file_store.py", line 395, in get_run
    run_info = self._get_run_info(run_id)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/store/tracking/file_store.py", line 411, in _get_run_info
    databricks_pb2.RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: Run '3ddb5f0527674fe3b396e4300c946868' not found

**Comment by maximmold** [comment]
I am seeing this as well.

**Comment by marcusrehm** [comment]
Hi @macimovic and @maximmold , did you still getting this error? I was able to run without any issue using mlflow version 1.8.0 and 1.4.0.

The steps I did in order to setup the example and environment were:
- Set credentials in `docker login`
- Build the base image as described in `README.rst` in docker example: `docker build -t mlflow-docker-example -f Dockerfile .`
- Update my `kubernetes_config.json` including my username in `repository-uri` and changed `kube-context` from "docker-for-desktop" to "docker-desktop".
- Create the mlflow namespace in kubernetes. You can change namespace but need to change in `kubernetes_job_template.yaml`: `kubectl create namespace mlflow`
- Start your tracking server:
```
		mlflow server \
			--backend-store-uri file:///c/Repos/mlruns \
			--default-artifact-root file:///c/Repos/mlruns \
			--host 0.0.0.0
```
- Configure environment variable with tracking url: `export MLFLOW_TRACKING_URI=http://host.docker.internal:5000`
- Run example from inside mlflow folder

**Comment by macimovic** [comment]
Hi @marcusrehm,
I was able to make it work later on, using exactly the same steps as you just explained, the problem being the namespace.
Thanks so much for replying!

**Comment by priyankdemo** [comment]
Hi @macimovic I followed the same steps as @marcusrehm described.

I am also facing the same issue.
In .json file, kube-context is set to minikube, while giving other it is showing error.
In .yaml file namespace is mlflowexample and also created that namespace using kubectl create ns <name>

Can you please help me for solving the issue.
