### ISSUE TITLE
Consolidate artifact and backend URI naming

### ISSUE THREAD

**Issue by blazzup** [mlflow/mlflow#2071]
Although it is described in various pages of the documentation, it is confusing and difficult to figure out where things will be stored.
In my opinion, this is due to:
1. different names for the same things, e.g., artifact_uri, artifact_location, artifact-root (there is also artifact_path which means something else)
2. the fact that experiment settings in backend store override artifact_uri

Since I am just starting with mlflow there may be other reasons I am not aware of, but it seems to me that tracking_uri and artifact_uri explicitly set by the user would suffice. This could be either with `mlflow.set_*_uri()` methods, `MLFLOW_*_URI` env. vars or parameters passed to the server.

#### Artifacts
mlflow.get_artifact_uri()
mlflow.log_artifacts(local_dir, artifact_path=None)
mlflow.create_experiment(name, artifact_location=None)
--default-artifact-root
--artifact-uri

#### Backend
--backend-store-uri
MLFLOW_TRACKING_URI
mlflow.set_tracking_uri

**Comment by fabboe** [comment]
Proposing some related changes here, maybe you can add your suggestions in the doc?

https://github.com/mlflow/mlflow/pull/2075

**Comment by blazzup** [comment]
I think the documentation is fine, but could be much easier to understand if the naming in various APIs were the same.
