### ISSUE TITLE
Does mlflow works with submodules?

### ISSUE THREAD

**Issue by damejovanoski** [mlflow/mlflow#2080]
Hello, I am trying to run a project which has a submodules, is there are way to force it to pull the submodules when running the projects?

**Comment by mparkhe** [comment]
Hi @damejovanoski,

I am a bit confused with the terminology. Can you give an example of what you mean by `submodule`? Do you mean entry points or like a directory structure with multiple `MLproject` files.

An MLflow Project is simple directly that as `MLproject` file and other stuff which is an organization of environment, code, data, etc to be able to reproduce a machine learning run. [MLproject File](https://www.mlflow.org/docs/latest/projects.html#mlproject-file) section in the documentation shows 2 entry points `main` and `validate`. Each of these details out parameters and the underlying command to run. When running an MLflow project a user has to specify the entry point to run and any parameters.

**Comment by dbczumar** [comment]
@mparkhe @damejovanoski If I understand correctly, this issue is referring to git submodules (https://git-scm.com/book/en/v2/Git-Tools-Submodules). I'm going to review https://github.com/mlflow/mlflow/pull/2103, which adds support for fetching git submodules before running a project.

**Comment by dbczumar** [comment]
#2103 is merged. This has been fixed!
