### ISSUE TITLE
LOGS for Model deployed to SAGEMAKER through mlflow

### ISSUE THREAD

**Issue by AbhinavMudgal** [mlflow/mlflow#2090]
Hi,
I deployed a model to aws sagemaker through pyfunc mlflow.
I want to see my print statements or logger.info when the sagemaker endpoint hits.
Where can I view that?
Please help.

**Comment by AdamBarnhard** [comment]
Hey @AbhinavMudgal - check out the documentation here:
https://docs.aws.amazon.com/sagemaker/latest/dg/logging-cloudwatch.html

You should be able to see the `stdout` or `stderr` for each endpoint/variant there.

**Comment by AbhinavMudgal** [comment]
Thank you for your response. It helped a lot.

**Comment by mparkhe** [comment]
Thanks @AbhinavMudgal and @AdamBarnhard. I am closing this issue.
