### ISSUE TITLE
Add filtering capabilities for "compare runs" screen

### ISSUE THREAD

**Issue by ruibastos-xpand** [mlflow/mlflow#2091]
When comparing runs, I would like to have the ability to dynamically change the selected runs, instead of going back and changing the filter query.

**Comment by mparkhe** [comment]
Thanks for the feature request. This would involve some UI/UX design.

cc: @gioa, @Zangr

**Comment by Zangr** [comment]
@ruibastos-xpand  thank you for submitting the FR. It makes sense and we will consider this while working on improving the run comparison UI.

**Comment by chenmoneygithub** [comment]
this issue has been inactive for 3 years, so I am closing it. We can reopen on demand in the future.
