### ISSUE TITLE
[FR] save_model() support for remote paths

### ISSUE THREAD

**Issue by TheTravellingSalesman** [mlflow/mlflow#2092]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Provide a clear high-level description of the feature request in the following sections. Feature requests that are likely to be accepted:
* Are minimal in scope (note that it's always easier to add additional functionality later than remove functionality)
* Are extensible (e.g. if adding an integration with an ML framework, is it possible to add similar integrations with other frameworks?)
* Have user impact & value that justifies the maintenance burden of supporting the feature moving forwards. The [JQuery contributor guide](https://contribute.jquery.org/open-source/#contributing-something-new) has an excellent discussion on this.

### Motivation
What is the use case in mind?  Why is it valuable to support, and why is it currently difficult or impossible to achieve? Could the desired functionality alternatively be implemented as a third-party package using MLflow public APIs?

- The goal of this feature request is to provide a way to directly save models to remote paths using the MLflow API. Per my understanding, there is no existing workflow for this. The workaround I've used is to use `mlflow.<flavor>.save_model(model, temp_local_path)` to write it to a local file, then copy it out to the remote path. This method, while effective, is somewhat cumbersome, and does not generalize well between file systems like `mlflow.<flavor>.load_model()` does (`load_model()` does support remote file systems).

- It appears that there is support for remote paths built into `mlflow.<flavor>.log_model()`, but there does not seem to be any way to save a MLflow artifact to a remote path without having a running tracking server (or at least it hasn't worked for me; happy to provide further details if it helps).

### Proposed Changes
For user-facing changes, what APIs are you proposing to add or modify? For internal changes, what code paths will need to be modified?

- I have a working implementation of this which leverages a decorator which provides `mlflow.<flavor>.save_model()` with access to a file-system-agnostic file path. The decorator function uses `fsspec`, so that it can generalize between `gcsfs`, `s3`, local paths, etc (happy to utilize another library if you don't want to add dependencies, although `gcsfs`' API is much smoother than the official GCS API). The workflow is roughly as follows:

1. The decorator determines the file system. If it is remote it runs `mlflow.<flavor>.save_model()` with a temporary local path, and if not it runs it with the original local path.
2. At the end of `mlflow.<flavor>.save_model()`, if the original path is a remote path, it uses the appropriate file system protocol to `put()` the MLflow artifact into the remote path. 

- In either case, the function behaves as expected, but is now able to directly write out to remote paths. The API remains unchanged, and it shouldn't break any existing functionality, or cause unusual behavior in existing codebases. 

I'm mainly interested in finding out if your team would be interested in supporting this sort of functionality. If so, I can get started on a pull request. If you have any comments, concerns, or suggestions, I would be happy to implement them.

**Comment by dbczumar** [comment]
@TheTravellingSalesman Sorry for the delay here. We'd be interested in reviewing a pull request for this behavior - feel free to file one. Ideally, we encourage users to leverage MLflow Tracking for model logging in most cases.
