### ISSUE TITLE
cusom user Id

### ISSUE THREAD

**Issue by hannahmoiseww** [mlflow/mlflow#2096]
When using mlflow on a remote Jupyter server, the user_id always shows up in the UI as "root". I've tried to override this using "user_id" and "mlflow.user" tags, but neither change the value that's shown in the UI.

Is it possible to override the user_id?

**Comment by mparkhe** [comment]
Are you using `mlflow.start_run`. This will automatically resolve user as the local system user where the process is running. If that is running as remote server as `root` it will pick up the user ID using `getpass`. Do you know if you have a mechanism to run as a different user? Does [changing env variable](https://docs.python.org/2/library/getpass.html) in python help?

**Comment by smurching** [comment]
As @mparkhe mentioned, the MLflow client uses the ID of the user who launched the current Python process (e.g. the user who launched your remote jupyter server) as the run's user ID. Running the jupyter server as a different user should work, as should overwriting the `mlflow.user` tag (just verified the latter works using MLflow 1.9.1). Closing for now, but feel free to reopen if you're still running into issues here!

**Comment by TUMAAA** [comment]
> As @mparkhe mentioned, the MLflow client uses the ID of the user who launched the current Python process (e.g. the user who launched your remote jupyter server) as the run's user ID. Running the jupyter server as a different user should work, as should overwriting the `mlflow.user` tag (just verified the latter works using MLflow 1.9.1). Closing for now, but feel free to reopen if you're still running into issues here!

I am not sure how you tested that but I am using 1.22 and for sure submitting the tag "user" ( mlflow.set_tag("User","some_user") ) **does not override** the User column but rather adds a new column with that name under the category "Tags".

**Comment by ahmedsalhin** [comment]
You need to set the `mlflow.use`r tag as follows:

`mlflow.set_tag("mlflow.user", "NAME")`

**Comment by MikeHeiber** [comment]
> You need to set the `mlflow.use`r tag as follows:
> 
> `mlflow.set_tag("mlflow.user", "NAME")`

I am trying this on a MLFlow Tracking server that we have running v2.0.1 and am getting a 500 server error. I get the same error when going directly through the REST API. Anyone know what might be happening?

**Comment by addisonklinke** [comment]
@MikeHeiber same here. I have MLflow client 2.9.2 and get this error when setting the tag on a Databricks tracking server

```
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Cannot update tag 'mlflow.user'
```

@smurching do you need to make sure `set_tag()` is called before the run ends?
