### ISSUE TITLE
[FR] Automatically update metric plots for in-progress runs

### ISSUE THREAD

**Issue by miwojc** [mlflow/mlflow#2099]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We're seeking help with the implementation of roadmap items tagged with the `help wanted` label. Items tagged with the `needs design` label are awaiting a design sketch from an MLflow maintainer: @harupy.

For requirements clarifications and implementation questions, or to request a PR review, please tag @harupy in your communications related to this issue.

## Describe the proposal
Automatically update MLflow metric plots for in-progress runs periodically, enabling users to track the performance of in-progress runs without having to perform periodic page refreshes and reset UI state.

### Motivation
It would be great to be able to monitor training progress via metric graphs for a particular set of runs.

### Proposed Changes
Currently when i plot a chart say for loss of an in-progress run, the MLflow UI creates a snapshot of the current status of the training. However the chart will not automatically update with new data. The browser must be manually refreshed in order to display updated data. However, updating the chart causes certain plot state & settings to be lost.

**Comment by rquintino** [comment]
would be much appreciated, prob better by a checkbox or similar, being disabled as default, if possible avoid refresh the whole page and keep all visual settings, filters,etc

**Comment by teristam** [comment]
Just come in to say that this feature is much appreciated! Will make mlflow a tensorboard killer! Now I am using some auto-refresh extension in firebox but obviously it is not ideal.

**Comment by Zangr** [comment]
@miwojc thank you for the FR and this use case make sense to me. @gioa what do you think about providing an auto-update toggle for certain visualization pages?

**Comment by gioa** [comment]
Thank you for FR!
Stupid question: why don't we always auto-update visualization? Is there a use case that users don't want to see the updates?

**Comment by cedkoffeto** [comment]
Hi everyone I am new in the open-source world and I am interested in this feature so I  tried to do it by updating the MetricPlotPanel every 5 seconds with a new query of metric history and the result I think is quite acceptable for a beginning.

It looks like this...

![image](https://user-images.githubusercontent.com/38736306/140563584-e89302fc-98e8-428a-a34b-9ce7f7dea544.png)

What do you think about it  @harupy?
