### ISSUE TITLE
[FR] Clicking on column field fills the "Search Runs" bar

### ISSUE THREAD

**Issue by simonberthaux** [mlflow/mlflow#2102]
### Describe

Clicking on a column field automatically fills "Search Runs" bar. Example below:

<img width="1160" alt="Screenshot 2019-11-15 at 11 27 52" src="https://user-images.githubusercontent.com/3306233/68937192-43ae2400-079c-11ea-8ab8-be03f8ccfc34.png">
<img width="1159" alt="Screenshot 2019-11-15 at 11 27 25" src="https://user-images.githubusercontent.com/3306233/68937204-47da4180-079c-11ea-832e-fd0d75e26091.png">

### Motivation

Currently, searching runs solely relies on copy-pasting. This feature would make searching way faster

**Comment by rom1504** [comment]
https://github.com/mlflow/mlflow/issues/2084 should fix it

**Comment by dbczumar** [comment]
@simonberthaux Thank you for your feature request. We're investigating mechanisms for more easily/effectively constructing search queries in the UI.

**Comment by smurching** [comment]
Thanks @rom1504 for filing, looks like column filters were implemented in https://github.com/mlflow/mlflow/pull/2251 :), closing for now!
