### ISSUE TITLE
[FR] Display execution progress logs on UI

### ISSUE THREAD

**Issue by Tradunsky** [mlflow/mlflow#2106]
## Describe the proposal
Apart from run results, it would be useful to get execution logs, so in case of training failure, users could see the stack trace with failure reason.

### Motivation
We are using MLflow as training tracking system in particular, making training and evaluation before packaging artifacts, it may fail on some module not found (dependency missed to be added for example). Another use case is when training process takes significant time, users may want to see the progress on MLFlow UI.

### Proposed Changes
![image](https://user-images.githubusercontent.com/4522842/68992067-efc03f80-086e-11ea-8fe7-0819b4c96858.png)

API which would return path to logs and/or tail logs itself while running training.

**Comment by chenmoneygithub** [comment]
Directing std output to MLflow is a tough work, and it's not aligned with our product scope. Actually logging should be handled by the training platform, like GCP/AWS/Azure instead on mlflow.
