### ISSUE TITLE
[FR] New wrapper method mlflow.get_or_create_experiment

### ISSUE THREAD

**Issue by haridas** [mlflow/mlflow#2111]
## Describe the proposal
Simple helper method to get or create an experiment, seems it's very handy when creating or reusing the mlflow experiments.

### Motivation
To simply the usage pattern and bring the common usage patterns with in the library.

### Proposed Changes

Here is the relevant code change involved.

```python

# Set the tracking URL.
mlflow.set_tracking_uri("http://127.0.0.1:5000")


# Helper fun.
def get_or_create_experiment(name, artifact_location=None):
    experiment = mlflow.get_experiment_by_name(name)
    if not experiment:
        experiment_id = mlflow.create_experiment(name, artifact_location)
        experiment = mlflow.get_experiment(experiment_id)
    return experiment


mlflow.get_or_create_experiment = get_or_create_experiment

```

**Comment by fhoering** [comment]
Already discussed here:
https://github.com/mlflow/mlflow/pull/1924

The final conclusion was that the api should stay simple and use should do it on their side.
In my opinion there is nevertheless something to do if everybody does this again and again on client side.
@smurching

**Comment by AveshCSingh** [comment]
I think the most common use case for this is to set the active experiment. This is already covered by [mlflow.set_experiment](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_experiment), so I'm going to close this issue.
