### ISSUE TITLE
[DOC-FIX]

### ISSUE THREAD

**Issue by ca8888** [mlflow/mlflow#2123]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### URL(s) with the issue:

https://groups.google.com/forum/#!topic/mlflow-users/E9QW4HdS8a8 

### Description of proposal (what needs changing):
ML flow works great, I log E-V-E-R-Ything there ( including my mdoels ).My problem is that there is no authentication mechanism documented , no example in the documentation, only a few words on tokens....
I would very appreciate it if one can add to the documentation how to run mlflow with username and password

**Comment by sueann** [comment]
@ca8888 - was matei's answer in https://groups.google.com/forum/#!topic/mlflow-users/E9QW4HdS8a8 sufficient for you? (i won't close this ticket, but want to understand if we'd need to add more information when we work on an example for this)

**Comment by ca8888** [comment]
@sueann  -   matei's answer is not sufficient, the link attached to the utils.py is broken. In addition, he dose not explain how to use the ENV variables. A small example how to set it up will be very helpful. Further more to the nginx example, I tried to set it up with nginx https://stackoverflow.com/questions/58956459/how-to-run-authentication-on-a-mlflow-server
but without success. 
If you can maybe wirte some guide line, example would very appreciate it.

**Comment by dmatrix** [comment]
@ca8888 

User provisioning/authentication varies across many organizations, and there's no real generic way to do that. What was suggested far the most generic way to do it via nginx. We would love the help from the community to write various plugins to do auth via identity management scheme, such as SCIM.

Or if they have done via other schemes to share with the community.
