### ISSUE TITLE
[BUG] mlfow server failed to start in k8s

### ISSUE THREAD

**Issue by suoych** [mlflow/mlflow#2126]
I tried to start mlflow server in a load balancer pod in k8s and exposed port 8111, the server progress could start up successfully, but when I visit the url of the pod, the website keep showing the error page
<img width="1232" alt="d600794350d4092a8f6710513d296d01" src="https://user-images.githubusercontent.com/29878050/69297942-62eafc80-0c47-11ea-95d8-623185ee6cf0.png">

I checked the server log and don't know how to solve it. I can make sure that the server progress started successfully, and there is a directory named mlruns with right structure and data in it.

![d80ccf37c2a549b7d1cf0d64901e6dc2](https://user-images.githubusercontent.com/29878050/69297901-49e24b80-0c47-11ea-914a-69bb9d60f0e0.png)

**Comment by smurching** [comment]
@suoych apologies for the delay, would you be able to retry with the latest MLflow and attach full server logs? The search_model_versions error should be fixed.
