### ISSUE TITLE
[FR]Show summary of of parameters 

### ISSUE THREAD

**Issue by xgk** [mlflow/mlflow#2133]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
When there are plenty of parameters, only show a summary of parameters instead of show all.

### Motivation
Make the list of runs clear when the parameters are too many to show

### Proposed Changes
Show a summary of parameters like tags.

**Comment by pogil** [comment]
@xgk, with the revamped run table view in MLflow 1.6.0, we made column management much easier and collapse parameters/tags/metrics to show just the first few by default. Does this meet your needs?
