### ISSUE TITLE
[FR] Scatter Plot add color as optional third axis

### ISSUE THREAD

**Issue by Nudin** [mlflow/mlflow#2135]
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Allow to colorcode the points in the Scatter Plot depending on a parameters value.

### Motivation
Currently when you have two important numerical parameters and one metric or when you have one numerical parameter and one categorical parameter (e.g. two different algorithms) and one metric it is hard to see how the two parameters affect the result. The "Parallel Coordinates Plot" is an alternative for those situations but doesn't work in all cases and is less intuitional, harder to understand and harder to interpret.

### Proposed Changes
In the "Scatter Plot"-tab in the UI add a third option bellow "X-axis" and "Y-axis", called "Color", when some parameter is chosen with this dropdown-list the colors of the dots should depend on the values of those parameters.

**Comment by harupy** [comment]
Adressed by https://github.com/mlflow/mlflow/pull/2225
