### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rashmeetmalik** [mlflow/mlflow#2141]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: **Yes**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: **Ubuntu 16.04**
- **MLflow installed from (source or binary)**: **binary**
- **MLflow version (run ``mlflow --version``)**: **1.2.0**
- **Python version**: **3.7**
- **npm version, if running the dev UI**: **NA**
- **Exact command to reproduce**: **NA**

### Describe the problem
Predict operation is not working for the spark models that are deployed as REST end point using mlflow serve command and have prediction column name other than "prediction".  For instance, I have attached the code snippet to build a GBTClassifier on IRIS dataset and deploy it as REST endpoint using mlflow. Now when I pass the model some sample data using curl command to see the predictions, I am getting the mentioned error:

### Code to reproduce issue
from pyspark.ml import Pipeline
from pyspark.ml.classification import GBTClassifier
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.context import SparkContext
from pyspark.sql.session import SparkSession
import mlflow
import mlflow.spark
# Load and parse the data file, converting it to a DataFrame.
sc = SparkContext('local')
spark = SparkSession(sc)

# Training DataFrame
training = spark.createDataFrame([
(5.1,3.5,1.4,0.2,"setosa"),
(4.9,3.0,1.4,0.2,"setosa"),
(4.7,3.2,1.3,0.2,"setosa"),
(4.6,3.1,1.5,0.2,"setosa"),
(5.0,3.6,1.4,0.2,"setosa"),
(5.1,3.5,1.4,0.3,"setosa"),
(5.7,3.8,1.7,0.3,"setosa"),
(5.1,3.8,1.5,0.3,"setosa"),
(5.4,3.4,1.7,0.2,"setosa"),
(5.1,3.7,1.5,0.4,"setosa"),
(7.0,3.2,4.7,1.4,"versicolor"),
(6.4,3.2,4.5,1.5,"versicolor"),
(6.9,3.1,4.9,1.5,"versicolor"),
(5.5,2.3,4.0,1.3,"versicolor"),
(6.5,2.8,4.6,1.5,"versicolor"),
(6.8,2.8,4.8,1.4,"versicolor"),
(6.7,3.0,5.0,1.7,"versicolor"),
(6.0,2.9,4.5,1.5,"versicolor"),
(5.7,2.6,3.5,1.0,"versicolor"),
(5.5,2.4,3.8,1.1,"versicolor")], ["SepalWidth","SepalLength","PetalWidth","PetalLength","Species"])

labelIndexer = StringIndexer(inputCol="Species", outputCol="indexedSpecies")

assembler = VectorAssembler(
    inputCols=["SepalWidth", "SepalLength", "PetalWidth", "PetalLength"],
    outputCol="features")

gbt = GBTClassifier(labelCol="indexedSpecies", featuresCol="features", maxIter=10)
gbt.setPredictionCol("predictionCol")
pipeline = Pipeline(stages=[labelIndexer, assembler, gbt])
model = pipeline.fit(training)
mlflow.spark.log_model(model, <some_path>)

print('deploying model as a service')
cmd = 'nohup mlflow models serve -m ' + '<path_to_model>'+ ' -p 7534 -h 0.0.0.0 --no-conda &'
popen_obj = subprocess.Popen(cmd, shell=True)
popen_obj.communicate()

### Other info / logs
"stack_trace": "Traceback (most recent call last):\n  File \"/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/sql/utils.py\", line 63, in deco\n    return f(*a, **kw)\n  File \"/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py\", line 328, in get_return_value\n    format(target_id, \".\", name), value)\npy4j.protocol.Py4JJavaError: An error occurred while calling o373.select.\n: org.apache.spark.sql.AnalysisException: cannot resolve '`prediction`' given input columns: [PetalWidth, probability, features, SepalWidth, predictionCol, SepalLength, PetalLength, rawPrediction];;\n'Project [features#58, 'prediction]\n+- Project [SepalWidth#10, SepalLength#11, PetalWidth#12, PetalLength#13, features#58, rawPrediction#64, probability#71, UDF(rawPrediction#64) AS predictionCol#79]\n   +- Project [SepalWidth#10, SepalLength#11, PetalWidth#12, PetalLength#13, features#58, rawPrediction#64, UDF(rawPrediction#64) AS probability#71]\n      +- Project [SepalWidth#10, SepalLength#11, PetalWidth#12, PetalLength#13, features#58, UDF(features#58) AS rawPrediction#64]\n         +- Project [SepalWidth#10, SepalLength#11, PetalWidth#12, PetalLength#13, UDF(named_struct(SepalWidth, SepalWidth#10, SepalLength, SepalLength#11, PetalWidth, PetalWidth#12, PetalLength, PetalLength#13)) AS features#58]\n            +- LogicalRDD [SepalWidth#10, SepalLength#11, PetalWidth#12, PetalLength#13], false\n\n\n\tat org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:92)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:89)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)\n\tat org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:95)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:95)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:107)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:107)\n\tat org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:106)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:118)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$1.apply(QueryPlan.scala:122)\n\tat scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)\n\tat scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)\n\tat scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)\n\tat scala.collection.TraversableLike$class.map(TraversableLike.scala:234)\n\tat scala.collection.AbstractTraversable.map(Traversable.scala:104)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:122)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:127)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:127)\n\tat org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:95)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:89)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:84)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)

**Comment by dbczumar** [comment]
@rashmeetmalik can you try renaming `predictionCol` to `prediction`?

**Comment by rashmeetmalik** [comment]
Hello dbczumar. Thanks for your reply :)

Actually we have the requirement in which we have a model which is already trained and we need to deploy the model using mlflow. That model's prediction column is set as "predictionCol" instead of the default name "prediction". Now when we pass some sample data using curl command command to see the prediction, we are getting the error. 

I can see in mlflow/spark.py file, inside predict() method of class __PyFuncModelWrapper, we are selecting the "prediction" column from the transformed dataframe.
Instead of hard-coding "prediction" column, can we just update the code to take the prediction column for the model type using getPredictionCol().
