### ISSUE TITLE
[FR] Add the support of LIKE operator when filtering in the experiment view

### ISSUE THREAD

**Issue by t-henri** [mlflow/mlflow#2143]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal

I would like to add the `LIKE` operator when using filters in the experiment view.

### Motivation

I would like to be able to use filters like:
-runName LIKE %name% 
-tag.myTag LIKE %tag%

### Proposed Changes

Add an extra operator when parsing the filter string, and allowing the user to use the LIKE operator.

**Comment by dbczumar** [comment]
@t-henri This sounds great. Is it possible to add support for ILIKE as well (case-insensitive `LIKE`)?. `%` is a good wildcard operator.

If possible, it would be useful to have this in both the SQLAlchemyStore and the FileStore.

**Comment by pogil** [comment]
Hi @t-henri! Thanks for you contribution on #2217. Does your contribution on #2217 resolve this issue, or is there more that would be needed here?

**Comment by t-henri** [comment]
Hello, yes this contribution fixed it, I totally forgot about this issue, I will close it now.
