### ISSUE TITLE
[FR] Local Bootstrap CSS to avoid opening access to external CDNs

### ISSUE THREAD

**Issue by joelcthomas** [mlflow/mlflow#2145]
## Describe the proposal
Host bootstrap CSS locally instead of using external CDN

### Motivation
Security focused enterprises would not like to whitelist and open up access to external CDNs and hence its currently unable to render CSS. Serving the file locally would avoid the issue.

### Proposed Changes
Minimal changes with locally hosted CSS and update the stylesheet link

**Comment by juntai-zheng** [comment]
Thanks for making the pull request! Closing this issue now that it's solved.
