### ISSUE TITLE
mlflow.spark.save_model() doesn`t work as expected

### ISSUE THREAD

**Issue by HikmatDashdamir** [mlflow/mlflow#2156]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Oracle Linux 7.6
- **MLflow installed from (source or binary)**: Anaconda
- **MLflow version (run ``mlflow --version``)**:1.4.0
- **Python version**:3.6.5
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
There are no errors or warnings reported after finishing a run. But when I checked it on HDFS files(model. conda etc.) are not there. It seems something appears on tmp folder than disappears. But nothing is recorded on artifact directory.

**Comment by tomasatdatabricks** [comment]
HI @HikmatDashdamir, thanks for posting! Can you describe your setup (ie. mlflow server runs locally or remote? which artifact repository do you use?) and provide code that reproduces the behavior that you describe? 

In general, the model is not expected to be persisted only in the artifact directory associated with your run.

**Comment by HikmatDashdamir** [comment]
Hi @tomasatdatabricks ,  hanks for the reply.

Mlflow server runs on remote node. We use **MariaDB for backend storage** and **HDFS for artifact storage**.
Server was started as follows:  `mlflow server --backend-store-uri mysql+pymysql://mariadb_database --default-artifact-root hdfs://some_directory --host x.x.x.x -p x`

The code which I run:
```
with mlflow.start_run():
        model = pipeline.fit(traindf)
        ###piece of code which is not relevant###
        mlflow.log_param("data_version", data_version)
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("f1", f1)
        mlflow.log_metric("wp", wp)
        mlflow.log_metric("wr", wr)
        mlflow.log_metric("run_time", time_rf)
        mlflow.spark.save_model(model,  "test")
```
It should save model file and related conda.yaml to artifact directory. However files doesnt appear at all. When use log_model() instead of save_model() I can see some related files. It gives me feeling that there is nothing wrong regarding HDFS connectivity.
It worked as it should before update but there was bug on UI which is supposed to be fixed on the latest version. Please see #1800. 

Please let me know if you need any further info.

**Comment by tomasatdatabricks** [comment]
Oh, I see our interface is a bit confusing. save_model saves model locally, **log_model** will log it as mlflow artifact. You need to call :
`mlflow.spark.log_model(model,  "test")`

**Comment by tomasatdatabricks** [comment]
Let me know if ^ works.

**Comment by HikmatDashdamir** [comment]
Hi @tomasatdatabricks thanks for pointing out this issue. I missed this, my bad.

It works as expected with local storage. Unfortunately i wasnt able to test it on HDFS because of libhdfs issue. I report it back once I will have hdfs related results.

Thanks
