### ISSUE TITLE
Impossible to save model with R (Databricks)

### ISSUE THREAD

**Issue by JLSMforPYR** [mlflow/mlflow#2158]
I'm trying to use MLFlow in Databricks ( I'm using 6.0 Conda Beta (includes Apache Spark 2.4.3, Scala 2.11) Runtime) with R.
The problem is that if I install mlflow from CRAN and next I'll execute mlflow::install_mlflow(), the installation go well but install the 1.4.0 version of R package, which not include the crate() function.

To solve this, I have tried to install the mlflow package for R from github (devtools::install_github("mlflow/mlflow", subdir = "mlflow/R/mlflow")) that runs, but when I execute mlflow::install_mlflow() try to find version 1.4.1 of mlflow, that doesn't exist.

**Comment by JLSMforPYR** [comment]
The problem is that de R Package Version is 1.4.1 while mlflow version is 1.4.0. The only thing you need to change to run is the version of the R package, but this implementacion could cause bug in the future.

**Comment by tomasatdatabricks** [comment]
Instead of calling mlflow::install_mlflow() you can install mlflow from pip and set MLFLOW_PYTHON_BIN and MLFLOW_BIN environment variables. See the bottom of install_mlflow section in https://www.mlflow.org/docs/latest/R-api.html.

Let me know if it helps.
