### ISSUE TITLE
Unable to save subclassed tf.keras model [BUG]

### ISSUE THREAD

**Issue by torjush** [mlflow/mlflow#2159]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04
- **MLflow installed from (source or binary)**:
pip install
- **MLflow version (run ``mlflow --version``)**:
1.4.0
- **Python version**:
3.7

### Describe the problem
I have a subclassed model (inheriting from tf.keras.Model) that I want to log using mlflow. As it is subclassed, I pass in ```save_format='tf'``` to ```mlflow.keras.log_model()``` which is passed on to the save call in [this line](https://github.com/mlflow/mlflow/blob/b78293ea22be103adcc784d9d0ba6b274486fd37/mlflow/keras.py#L164). The problem is, that in the [line above](https://github.com/mlflow/mlflow/blob/b78293ea22be103adcc784d9d0ba6b274486fd37/mlflow/keras.py#L163) ```_MODEL_SAVE_PATH``` is appended so that the path gets a .h5 extension, fooling keras into trying to save the model as a HDF file in stead.

As saving in the savedmodel format is the default in tensorflow 2, I would suggest that the extension be removed when [```_is_tf_keras(keras_model)```](https://github.com/mlflow/mlflow/blob/b78293ea22be103adcc784d9d0ba6b274486fd37/mlflow/keras.py#L144) evaluates to ```True```, optionally after checking ```kwargs``` for the ```save_format=='tf'```.

**Comment by juntai-zheng** [comment]
Hi @torjush, is this issue still happening with MLflow 1.9? And if so, would you be willing to open a PR to fix the issue? Thanks!

**Comment by harupy** [comment]
Fixed by #3552
