### ISSUE TITLE
[FR]  want to copy files and subfolders both from artifact_uri

### ISSUE THREAD

**Issue by xd21303** [mlflow/mlflow#2162]
## Describe the proposal
mlflow V1.4.0
mlflow/store/artifact/local_artifact_repo.py, line 88, in _download_file
```python
shutil.copyfile(remote_file_path, local_path)
```
my artifact_uri have subfolders, I want to copy files and subfolders both.
shutil.copyfile can only copy files.

### Motivation
I want to copy files and subfolders both from artifact_uri.

### Proposed Changes
```
if os.path.isdir(remote_file_path):
    shutil.copytree(remote_file_path, local_path)
elif os.path.isfile(remote_file_path):
    shutil.copyfile(remote_file_path, local_path)
```

**Comment by dbczumar** [comment]
@xd21303 The ArtifactRepository abstraction handles directory downloads by making recursive calls to `_download_file`. `_download_file` is intended to download single files. Please let me know if this isn't working for your use case. I'm going to go ahead and close this issue for now.
