### ISSUE TITLE
[DOC-FIX] mlflow ui results with 404  when running the tutorial

### ISSUE THREAD

**Issue by sephib** [mlflow/mlflow#2163]
Hi,
This is regarding the documentation of the [tutorial](https://mlflow.org/docs/latest/tutorial.html) 

### running the mlflow ui  results with 404
When following the tutorial documentation it seems that the relative path when running the first part of the tutorial is the root of the cloned [github repo](https://github.com/mlflow/mlflow).
Thus running the example requires running with the parent directory to the example(** examples/sklearn_elasticnet_wine/**):  
` python examples/sklearn_elasticnet_wine/train.py`  

However when running the `mlflow ui` (after running the train several times -  I can see the results in the folder `mlruns/0/` ) from the same directory  I get an *404 error NOT FOUND* 

moving to the root project `cd examples/sklearn_elasticnet_wine/` and then running `mlflow ui` the site successfully load **BUT** the `Artifact Location./mlruns/0` (obviously since the runs are saved in the parent folder.). 

After running running the `python train.py` from within the folder `examples/sklearn_elasticnet_wine` the runs are save under the local mlruns and thus are able to be seen from the `ui`

1. please clarify this issue (including using the `--default-artifact-root`)
2. running in an offline environment I can see that it is looking for `maxcdn.bootstrapcdn.com`  - is there a way to disable any external calls from the `ui`?
3. BTW the table output for the ui from the current master git is different from the screenshots in the documentations (e.g. it has the `metrics` columns as one whereas in the tutorial documentation it is split out into 3)

**Comment by sephib** [comment]
can someone from mlflow validate this issue?

**Comment by sephib** [comment]
?

**Comment by asandu1971** [comment]
I have the same issue

**Comment by pogil** [comment]
Hi @sephib and @asandu1971, I was able to reproduce the issue. The problem happens when you run `mlflow ui` from the root directory of the mlflow repository. If you go into another directory to launch the UI, it should work. For example
```
cd examples
mlflow ui --default-artifact-root ../mlruns --backend-store-uri ../mlruns
```

**Comment by aurelsandu** [comment]
Thank you Pogil ! With your help I go further  but now I have a little problem with the mlflow serve

When I issued the command 
                 mlflow models serve -m runs:/c94c36bb6c0c48a2a7c895d93ec1866f/model
I get the following
2020/05/06 14:04:33 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2020/05/06 14:04:35 INFO mlflow.projects: === Creating conda environment mlflow-4133253245e67fa1d3bbd74212a1eb60c04fbc0a ===
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - scikit-learn=0.22.2.post1

It seems conda cannot find this version of scikit-learn
I have installed https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
Please help me,
Aurel

**Comment by sephib** [comment]
> 
> 
> Hi @sephib and @asandu1971, I was able to reproduce the issue. The problem happens when you run `mlflow ui` from the root directory of the mlflow repository. If you go into another directory to launch the UI, it should work. For example
> 
> ```
> cd examples
> mlflow ui --default-artifact-root ../mlruns --backend-store-uri ../mlruns
> ```

Thx for the update - currently we are managing to work with mlflow in other project

**Comment by dmatrix** [comment]
@sephib and @asandu1971 
Is this still an issue now. Can we close the bug?

**Comment by dmatrix** [comment]
The general convention is that you launch the `mlflow ui` from the directory where you either ran the example as a MLflow Project `mlflow run . -e <entry_point>` or `cd examples/dir_name; python file_name.py`

Let me know if this is still an issue. We are planning to have more extensive documentation with this `examples` README.md file to clarify and expound how to use these examples
