### ISSUE TITLE
Model registry CI/CD and extra stages

### ISSUE THREAD

**Issue by hazardsy** [mlflow/mlflow#2165]
Greetings,

As a new user of MLflow, I am kind of lost as to whether the features mentionned in the title are available yet or not.
In the [intended documentation](https://mlflow.org/docs/latest/model-registry.html), there is no mention of them, but I somehow got on [this documentation page](https://mlflow.org/docs/latest/registry.html) which presents them, as well as [this Databricks documentation page](https://databricks.com/product/managed-mlflow) which says they are available in the open-source version of MLflow.

I know the Model Registry is still a new feature in the project and is likely still evolving, but this discrepancy between documentation is kind of surprising to me.
Does anyone have more information on this ?

Thank you very much.

**Comment by mparkhe** [comment]
You can integrate with your existing CI/CD tools by calling into Model Registry REST endpoints. We currently do not have any standardized API for CI/CD.

For now the stages are fixed. Model Registry supports:
`None` (for newly added model version), `Staging`, `Production`, and `Archived`. In the future, we may support custom stages.

documentation will be fixed with PR #2232

**Comment by hazardsy** [comment]
Thank you for your answer, that makes sense.
I am eager for the custom stages feature as it would fit my needs perfectly but I guess I'll have to wait for a new version :)

**Comment by nayaks** [comment]
I have a related question. Are Workflow features available in the opensource Model Registry?

**Comment by mparkhe** [comment]
Hey @nayaks,

Can you give more specifics on what do you mean by workflows features? Are you referring to CI/CD workflows or training/deployment/scoring related? Can you describe you use case on what you are trying to achieve.

**Comment by zerafachris** [comment]
Hi @mparkhe. Any updates on the addition of additional Model Registry Stage apart from `Stage`, `Prod` and `Archived`?
