### ISSUE TITLE
[FR] mlflow features

### ISSUE THREAD

**Issue by Sandy2904** [mlflow/mlflow#2173]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

Proposal

We have installed mlflow and found it very useful for our project.
It would be extremely valuable to have the ability to manage the data lifecycle , source code enhancements tracking and saving model output metrics as part of model serving which is described in detail below.

Motivation

As an ML Flow user, We would like to be able to track which data version went for model training at that particular instant. Also we would like to know if any incremental changes in the source code is being tracked by the mlflow. Also does mlflow has any mechanism which saves/logs the prediction metrics/result as part of model serving?

Proposed Changes

We are having below queries so wanted to know if these features are being incorporated or is in progress

1.Does mlflow support data lifecycle management as well, which means if the training data is refined and model is built on this changing data, then is there any mechanism how mlflow tracks which data version was used for training the model at that particular instant.

2.Does mlflow allows/tracks the incremental changes in the source code, which means if there is any additional piece of code/logic written for the same application, then is there any mechanism if mlflow saves this incremental source code changes.

3 When we serve the model using mlflow and pass the validation/real data for predictions,is there any mechanism if mlflow saves/logs this prediction metrics as part of model serving?

**Comment by Sandy2904** [comment]
Please provide an update on the above query...

**Comment by Sandy2904** [comment]
Can anybody comment on the above queries ?

**Comment by pogil** [comment]
Hi @Sandy2904 

Thanks for your patience in our reply.

1) MLflow does not support data lifecycle management. Our current recommendation is to use another tool that tracks data versions and record the versions of your data artifacts as a tag in the experiment run. If your data are small, then you could snapshot them as artifacts in MLflow as a part of the runs themselves using `log_artifact`.

2) MLflow does record the git hash of the code when you create a run. However, if you have local, uncommitted changes, MLflow does not capture that. If you want to capture this information, there's a few ways you could make this happen:
 - create an archive (.zip, .tar.gz) of your code and logging it as an artifact using `log_artifact`
 - if using git, run git diff and log that as an artifact with the run
 - script up creating a commit on the users behalf when code is run to log a commit that can be referenced by git hash

3) Right now the serving utilities do not support logging input or prediction data. It's something we have thoughts on and is something we'd like to support but we haven't been able to prioritize this work yet.

**Comment by Sandy2904** [comment]
Thanks Paul for the response.


Regards
Sandeep
