### ISSUE TITLE
[FR] Respect ordering of params and metrics

### ISSUE THREAD

**Issue by jmwoloso** [mlflow/mlflow#2179]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Respect ordering of metrics and params submitted via `log_metrics` and `log_params` and their singular forms `log_metric` and `log_param`

### Motivation
We often track multiple metrics for context, but usually there are only one or two that we're optimizing for and so it makes sense to present them first in the metrics section. 

For the Params section, we often want to describe the parameters top-down from higher level concepts (e.g. classifier algo) down to the details used to train that algo (e.g. learning rate).

Alphabetical ordering doesn't make sense in either case and can disrupt consumption of the results by the end-user.

### Proposed Changes
For the `log_metrics` and `log_params` methods, respect the ordering of the submitted object. As of Python 3.6, dicts are insertion-ordered and of course you'd want to accept `collections.OrderedDict` for any version.

For the `log_metric` and `log_param` methods, respect the order the metrics and params were submitted.

Thanks!

**Comment by AveshCSingh** [comment]
This is a good idea, but I think a better interface would be to allow the user to drag and reorder columns within the Runs Table. I've added a feature request for this here: https://github.com/mlflow/mlflow/issues/3101

I will close this Issue to consolidate discussion to the above feature request. If anyone feels that it would be better to order the columns by order of calling `log_parameter` and `log_metrics`, feel free to reopen.
