### ISSUE TITLE
MLflow behind reverse proxy

### ISSUE THREAD

**Issue by lucmos** [mlflow/mlflow#2193]
Hi,

### Context

I'm trying to run MLflow behind a reverse Caddy proxy.

### Describe the problem

Defining the proxy in this way works fine:
```Caddy
proxy / http://localhost:4000/#/ { 
  websocket  
} 
```

Defining the proxy in this way:
```
proxy /mlflow http://localhost:4000/#/ {
  websocket
  without /mlflow
}
```

Leads to a white page or an error page (depending if I redirect to ` http://localhost:4000/#/` or ` http://localhost:4000/`):
![image](https://user-images.githubusercontent.com/11019190/70717533-d3d57f80-1cee-11ea-9ca7-eb7bd6ebe636.png)

### Maybe related

Maybe related: https://github.com/mlflow/mlflow/issues/597, https://github.com/mlflow/mlflow/issues/111

**Comment by sabman** [comment]
ref https://github.com/mlflow/mlflow/issues/1120

**Comment by pogil** [comment]
Hi all, using a reverse proxy w/ MLflow has come up a bunch, but it's a bit hard to for us to keep track of the issues and help here. We definitely need some community help. I've created #2823 as a place to request this help.
