### ISSUE TITLE
[FR] Python - allow multi-process nested runs

### ISSUE THREAD

**Issue by battlesnake** [mlflow/mlflow#2194]
## Describe the proposal

The Python library appears not to allow specifying the run ID of the parent run, when doing nested runs.  It maintains its own internal stack of run IDs instead.

### Motivation

When doing hyperparameter training jobs, or multi-stage pipelines with some external orchestrator, this seems to prevent us from being able to nest parts of the same high-level task under it as nested jobs.  Possible short-term hacks include setting the `mlflow.parentRunId` tag explicitly in client code (which documentation advises against).

The Java API appears to already allow specifying the `parentRunId` when starting a run, so this work would seem confined to the Python library only.

### Proposed Changes

The only changes I think we'd need would be to the Python library.  Some way to specify the ID of an externall-started run for it to use as the top-level parent-run.  This could be via environment-var (as already used for e.g. auth), and/or an extra method e.g. `set_parent_run_id` which just asserts that the internal job stack is empty, then pushes the given ID onto it.

**Comment by battlesnake** [comment]
@deniskovalenko

**Comment by mparkhe** [comment]
Hi @battlesnake,

We have been thinking of ways to make this easier.

One of the other ways to achieve this is to do the following in the external orchestrator-

```
# main run for hyperparam
mlflow.start_run(experiment_id=exp_id, run_name="hyper_param_tuning")

# start individual runs
for param in list_of_params_for_hyper:
  with mlflow.start_run(experiment_id=exp_id, nested=True):
    # schedule each logged child run

# end parent run
mlflow.end_run()
```

If you want to keep the orchestrator running -- you could restart the parent run using `run_id` argument on `mlflow.start_run`

**Comment by mparkhe** [comment]
I am going to keep this open: to improve parent/nested runs handling, workflows, ... etc for roadmap planning.

cc: @clemens-db

**Comment by jkthompson** [comment]
> Hi @battlesnake,
> 
> We have been thinking of ways to make this easier.
> 
> One of the other ways to achieve this is to do the following in the external orchestrator-
> 
> ```
> # main run for hyperparam
> mlflow.start_run(experiment_id=exp_id, run_name="hyper_param_tuning")
> 
> # start individual runs
> for param in list_of_params_for_hyper:
>   with mlflow.start_run(experiment_id=exp_id, nested=True):
>     # schedule each logged child run
> 
> # end parent run
> mlflow.end_run()
> ```
> 
> If you want to keep the orchestrator running -- you could restart the parent run using `run_id` argument on `mlflow.start_run`

Would this approach work if the child runs are started in a separate python context (e.g. as separate airflow tasks)?

**Comment by battlesnake** [comment]
The orchestrator is potentially a separate process on a separate machine to the child runs - so some way to set the parent run ID in the child to the run created in the orchestrator would be needed.

**Comment by jkthompson** [comment]
I think @mparkhe is suggesting that it's possible to restart the parent run prior to starting the child run, when on a separate machine / context.  However, this requires a few more lines of code and is not intuitive or documented.  I would like to see this FR implemented.  Interesting that the JAVA API seems to already supports this.

**Comment by battlesnake** [comment]
In the next month, I'll be starting on the task that this issue relates to.

So the current approach, if I understand, is:
 - start a parent run in orchestrator, get ID
 - pass ID to child tasks
 - each child task "resumes" the parent run then creates a child run within it

**Comment by battlesnake** [comment]
I did a quick experiment yesterday which seems to work:

tuning.py
```
import random
import subprocess
import mlflow

# pylint: disable=invalid-name,bare-except

experiment_name = 'nested_runs-' + ''.join(random.sample(list('abcdefghihjlmnop'), 6))

experiment_id = mlflow.create_experiment(experiment_name)

run_name = ''.join(random.sample(list('abcdefghihjlmnop'), 6))

print(f'experiment_id: {experiment_id}')
print(f'run_name: {run_name}')

with mlflow.start_run(experiment_id=experiment_id, run_name=run_name) as run:
    for x in range(0, 10):
        subprocess.call(['python', 'training.py', experiment_id, str(x)])

```

training.py
```
import sys
import mlflow

# pylint: disable=invalid-name

experiment_id = int(sys.argv[1])
x = int(sys.argv[2])

with mlflow.start_run(experiment_id=experiment_id, run_name=str(x), nested=True) as run:
    mlflow.log_param('x', x)
    mlflow.log_metric('x', x)
```


Output from running tuning.py:

![image](https://user-images.githubusercontent.com/4949354/93198561-dcfbed00-f755-11ea-83ae-6dc1b98763c0.png)

**Comment by battlesnake** [comment]
I've noticed that multi-level nesting is supported, but that the UI will flatten the second layer onwards in the list view.  I'm guessing this is by design.

If we have periodic training runs, and each run has e.g. one model per product category, I was deciding whether to nest this as `experiment / product_category / run_date` or as `experiment / run_date / product_category`...

But after remembering that the UI provides the ability to filter+order by parameters, I realise the multi-level nesting doesn't matter much.  Would you be open to a feature-request / PR adding Kibana-style one-click filtering?  So clicking a button next to some `value` in `column` would append a filter for `... [AND] column = value`.
