### ISSUE TITLE
[BUG] Big text artifacts get corrupted 

### ISSUE THREAD

**Issue by lucmos** [mlflow/mlflow#2198]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Manjaro
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**: 3.7.4

### Describe the problem
Sometimes text files are truncated in the mlflow UI. Even the file downloaded from the UI is truncated.

I have a file `data_split.json` that contains a long list of files.

This is the end of the file on mlflow:
![image](https://user-images.githubusercontent.com/11019190/70758027-e9c06000-1d41-11ea-90c8-0edae8c9fc05.png)

This is the end of the file using `tail` directly on the file:
![image](https://user-images.githubusercontent.com/11019190/70758057-06f52e80-1d42-11ea-89d0-6e4e3d1e1d57.png)

This is the end of the file  downloaded from mlflow, when the UI was buggy:
![image](https://user-images.githubusercontent.com/11019190/70758138-46237f80-1d42-11ea-9ddb-bf447d15b522.png)

The file gets truncated.

### Code to reproduce issue
I can't reproduce the issue everytime: changing the name of the file and/or moving the file to different runs sometimes doesn't reproduce the issue

I'm attaching the complete file: [data_split.json](https://drive.google.com/file/d/1aNx9Xpid9HrRp36RmZ-fS75Oud_V2SJu/view?usp=sharing)

### Other info
Restarting the server and/or the computer doesn't solve the problem.
Searching in the datastore with `find . -name "data_split.json"` returns only sane files.

**Comment by Zangr** [comment]
Thank you for reporting this issue @lucmos. We will take a look at it.

**Comment by lucmos** [comment]
Hi @Zangr thank you for your reply!

I found the problem, it wasn't a bug in MLFlow, so this can be closed.
