### ISSUE TITLE
[FR] Optionally include a data tranformation.

### ISSUE THREAD

**Issue by cfusting** [mlflow/mlflow#2199]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------

## Describe the proposal
When deploying a model via build-docker it would be useful to provide a transformation function that takes raw (non-encoded) data. This will enable anyone using the Prediction REST API to pass human readable data to the service and thus better encapsulates the transformation dependency.  

### Motivation
Users of the Prediction REST API will not be required to manage and run a transformation dependency.

### Proposed Changes
It feels like the best place to add this functionality is in the model API. The predict method will call the transform method before proceeding. Thoughts?

**Comment by dbczumar** [comment]
Hi @cfusting, sorry for the absurd delay here. Can you take a look at https://mlflow.org/docs/latest/models.html#custom-python-models and see if this meets your requirements? Custom Python models allow arbitrary feature transformations and business logic to be encoded in your model's inference routine. During serving, this logic is ultimately executed behind the RESTful server created by `mlflow models serve` or within the Docker containers used for external service deployment, which requires inputs to be structured as Pandas DataFrames. Is raw data / un-encoded data a strict requirement here, or does custom logic behind a Pandas interface meet your requirements?

**Comment by cfusting** [comment]
Hey @dbczumar. I have a PR open 2189 that encapsulates the need for a custom base image. Looks like it's just about ready to go pending a final review.

**Comment by dbczumar** [comment]
Hi @cfusting ! We'll get that reviewed promptly! So sorry for the delay

**Comment by cfusting** [comment]
I just realized that this was a completely separate issue from the PR I pointed you to. Yes I believe the functionality you pointed out would work for this.
