### ISSUE TITLE
sftp artifact logging to remote server : Permission denied

### ISSUE THREAD

**Issue by gandroz** [mlflow/mlflow#2203]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**: 3.7

### Describe the problem
I setup a remote MLFlow tracking server along with a SFTP server. The server is running well, it logs metadata, and I can access the SFTP server remotely with a SSH key.

The SFTP server allows the users of the remote server to access it.

On my local machine I run the simple example file found in the doc to log some metrics and artifact, but I encountered a `Permission Denied` error as mlflow tries to save the artifacts in a local path (that does not exist) instead of using the remote SFTP server.

### Code to reproduce issue
**Launching tracking remote server**
mlflow server --backend-store-uri postgresql://mlflow:mlflow@localhost/mlflow --default-artifact-root sftp://<remote_server_user>@localhost:/home/<remote_server_user>/mlflow/mlruns -h 0.0.0.0 -p 8000

**local python code**
I added the following environment variable 
```export MLFLOW_TRACKING_URI="http://<remote_server_ip>:8000```

I also tried to add the following environment variable but it does not change anything
```export MLFLOW_ARTIFACT_URI='sftp://<remote_server_user>@<remote_server_ip>:20'```

```
import os
import mlflow
from mlflow import log_metric, log_param, log_artifact, set_experiment, start_run

if __name__ == "__main__":
    set_experiment("test")
    with start_run():
        # Log a parameter (key-value pair)
        log_param("param1", 5)

        # Log a metric; metrics can be updated throughout the run
        log_metric("foo", 1)
        log_metric("foo", 2)
        log_metric("foo", 3)

        # Log an artifact (output file)
        with open("output.txt", "w") as f:
            f.write("Hello world!")
        print(mlflow.get_artifact_uri())
        log_artifact("output.txt")
```

### Other info / logs
**The artifact uri used:**
```
file:/home/<remote_server_user>/mlflow/mlruns/1/d478434e4f1a4370a0bf577615c869d7/artifacts
```

**Error trace**
```
Traceback (most recent call last):
  File "tracking.py", line 20, in <module>
    log_artifact("output.txt")
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 292, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/tracking/client.py", line 251, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 247, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 31, in log_artifact
    mkdir(artifact_dir)
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 106, in mkdir
    raise e
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 103, in mkdir
    os.makedirs(target)
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/home/<local_username>/miniconda3/envs/mlflow_env/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/<remote_server_user>'
```

Obviously, the artifact URI is set to a local file path, the SFTP server URI is not used and I can't figure out how to set it....

**Comment by grco-xp** [comment]
Create an experiment before setting it. This way you can specify artifact location.
Something like this:
```
import os
import mlflow
from mlflow import log_metric, log_param, log_artifact, set_experiment, create_experiment, start_run

if __name__ == "__main__":
    ARTIFACT_URI = "sftp://<remote_server_user>@<remote_server_ip>:20"
    EXPERIMENT_NAME = "test"
    create_experiment(EXPERIMENT_NAME, artifact_location=ARTIFACT_URI)
    set_experiment(EXPERIMENT_NAME)
    with start_run():
        # Log a parameter (key-value pair)
        log_param("param1", 5)

        # Log a metric; metrics can be updated throughout the run
        log_metric("foo", 1)
        log_metric("foo", 2)
        log_metric("foo", 3)

        # Log an artifact (output file)
        with open("output.txt", "w") as f:
            f.write("Hello world!")
        print(mlflow.get_artifact_uri())
        log_artifact("output.txt")
```

**Comment by gandroz** [comment]
Ok, this works now, the artifacts are logged, but the URL is badly managed. I have to specify the whole path like `sftp://<remote_server_user>:
<remote_server_password>@<remote_server_ip>:/home/<remote_server_user>/mlflow/mlruns/<experiment_id>/runs` which is quite annoying. 
Furthermore, when I try to open the experiement in the UI, I got a generic error page `Something went wrong`, so I guess the server is unable to find the path to the artifacts ?

**Comment by grco-xp** [comment]
You can point your ftp to the mlruns folder on your server, instead of pointing to root.
Check out this issue #1338 and PR #2196. It's a solution for a similar problem while using ftp, instead of sftp, but it should/can be related. 
Let me know if it works.

**Comment by gandroz** [comment]
I notice a first issue when logging the artifact. In the artifact URI, I have to specify the absolute path of the artifact store, not the relative one, which is quite annoying. This comes from

```
parsed = urllib.parse.urlparse(artifact_uri)
self.path = parsed.path
```

where `parsed.path` returns an absolute path. For example:

`artifact_uri = ""sftp://user:password@server_ip/mlflow" ---> path = "/mlflow'`
`artifact_uri = ""sftp://user:password@server_ip:mlflow" ---> invalid port number`

**Comment by pogil** [comment]
@gandroz, did @grco-xp's latest suggestion work? If not, would the fix in https://github.com/mlflow/mlflow/pull/2196 help resolve the issue? If this is still an issue, it would be great to have an updated description from you where things stand.

**Comment by gandroz** [comment]
@pogil sorry Paul, I gave up and I've used the S3 artifact store instead which is more convenient finally...

**Comment by pogil** [comment]
@gandroz Thanks - I'm glad you found a solution. I'm closing this issue since you seem unblocked.
