### ISSUE TITLE
[BUG] Model Registry does not show username in the UI for Model Versions

### ISSUE THREAD

**Issue by grco-xp** [mlflow/mlflow#2208]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.6 LTS
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.4.0
- **Python version**: 3.6.9 

### Describe the problem
The model registry UI does not show the user tag value, both when viewing all versions within one registry in the table (fig1) and when accessing version details (fig2).
Mlfow user is recognized/logged normally in the tracking UI (fig3)

### Code to reproduce issue
Using a tracking remote PostgreSQL db and saving artifacts with a nfs mount.
Mlflow user is set with mlflow.utils.mlflow_tags.MLFLOW_USER.

### Other info / logs
Fig1
![image](https://user-images.githubusercontent.com/58782224/70905328-7f3a4900-1ffb-11ea-8d54-f9cd771b2ffe.png)
Fig2
![image](https://user-images.githubusercontent.com/58782224/70905372-9c6f1780-1ffb-11ea-882d-279b9f7250ae.png)
Fig3
![image](https://user-images.githubusercontent.com/58782224/70905414-b577c880-1ffb-11ea-8853-148429a542b2.png)

**Comment by Christoph460** [comment]
Would be cool to have this fixed. I digged a little bit around in the code. The "created by" database entry is never written when a new model is registered.

**Comment by RahulKulhari** [comment]
I am also facing same issue.  Is there any update on this ?

**Comment by HailinDu** [comment]
Hi everyone, any update about this?

**Comment by dbczumar** [comment]
This has been addressed via https://github.com/mlflow/mlflow/pull/5089.

**Comment by AurelienNioche** [comment]
Has the bug been reintroduced? I'm encountering the same problem
