### ISSUE TITLE
[DOC-FIX] License with templated values

### ISSUE THREAD

**Issue by Sinclert** [mlflow/mlflow#2224]
### URL(s) with the issue: 

https://github.com/mlflow/mlflow/blob/master/LICENSE.txt#L190

### Description of proposal (what needs changing):

The Apache `LICENSE.txt` is a template, and it does not contains either the year, or the list of _"license owners"_. Right now, it states the following:

```txt
...
Copyright [yyyy] [name of copyright owner]
...
```

I guess it should be changed to:

```txt
...
Copyright 2018 Databricks, Inc.
...
```

**Comment by dmatrix** [comment]
All this has changed with the new CONTRIBUTION.rst guidelines. Closing this.
