### ISSUE TITLE
[FR] Support HDFS URIs for parameters of type path in MLProject files

### ISSUE THREAD

**Issue by orair** [mlflow/mlflow#2233]
## Describe the proposal
Adds the ability to handle hdfs:// URIs for parameters of type path in MLProject files.

MLflow seems to support just S3 and DBFS based on [docs](https://www.mlflow.org/docs/latest/projects.html#specifying-parameters). Verifying the source code (mlflow/data.py) I noticed the functionality was expanded to support GCS on #1168.

On #1011 the ability to store artifacts in an HDFS was implemented and it included a feature to download artifacts from the [HdfsArtifactRepository](https://github.com/mlflow/mlflow/blob/master/mlflow/store/artifact/hdfs_artifact_repo.py).

So, there is no much impact on including this functionality because downloading from HDFS is already supported.

### Motivation
Ability to store files on a HDFS and execute programs that can only read local files.

### Proposed Changes
Include hdfs scheme to [download_uri](https://github.com/mlflow/mlflow/blob/master/mlflow/data.py)) reusing the code for parsing the URI and the environment variables from [HdfsArtifactRepository](https://github.com/mlflow/mlflow/blob/master/mlflow/store/artifact/hdfs_artifact_repo.py).

**Comment by pogil** [comment]
Thanks for the request @orair. This would be a good first issue, and we would accept either the one-off addition of HDFS support to this utility or an addition that pulls in all supported artifact types, including artifact stores registered via the plug-in mechanism (https://mlflow.org/docs/latest/plugins.html).

**Comment by whiletruelearn** [comment]
Hi, I would like to pick this issue if no one else is working on it.

**Comment by pogil** [comment]
@whiletruelearn that would be fantastic. I don't know of anyone working on this. Let me know if you want me to connect you with someone on the team here at Databricks to brainstorm the solution.

**Comment by pogil** [comment]
Fixed by #2774
