### ISSUE TITLE
log_param failes logging string containing \n

### ISSUE THREAD

**Issue by reidarkind** [mlflow/mlflow#2235]
### System information
mlflow, version 1.4.0
Python 3.7.4

### Describe the problem
mlflow throws and exception: "Exception: Unexpected data for param <key>. Param recorded more than once" when trying to log a multiline string with log_param. 

Ok, this is a special case and I don't see many use-cases, but I stumbled this today. That said, I don't think the Exception description is not very clear (took me a while do understand what actually was wrong - I only tried to log the param once...).

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import mlflow

# create a multiline string
a_two_line_str = "a\nb"

with mlflow.start_run() as mlrun:

    # this works
    clean_str = a_two_line_str.replace("\n|\r", "")
    mlflow.log_param("two_liner", clean_str)
    print("no exception yet")

    # this fails
    print(a_two_line_str)
    mlflow.log_param("two_liner", a_two_line_str)
    # >> Exception: Unexpected data for param 'two_liner'. Param recorded more than once

```

### Other info / logs
The reason for the exception is that `len(param_data)>1`, since `len("a\nb")>1`.

Propose either 1) a fix to strip for \n and \r, or 2) give a more describing Exception string, e.g:

#### 1) Strip \n and \r from param data strings
mlflow.tracking._tracking_service.client.TrackingServiceClient.log_param:
```
def log_param(self, run_id, key, value):
    """
    Log a parameter against the run ID. Value is converted to a string.
    """
    _validate_param_name(key)
    param = Param(key, str(value).replace("\n|\r", "")) #change: the '.replace(..)
    self.store.log_param(run_id, param)
```

#### 2) Change Exception description
mlflow.store.tracking.file_store.FileStore._get_param_from_file:
```
@staticmethod
def _get_param_from_file(parent_path, param_name):
    _validate_param_name(param_name)
    param_data = read_file_lines(parent_path, param_name)
    if len(param_data) > 1:
        raise Exception("Unexpected data for param '%s'. Len of param data is bigger than 1"
                        % param_name)
    # The only cause for param_data's length to be zero is the param's
    # value is an empty string
    value = '' if len(param_data) == 0 else str(param_data[0].strip())
    return Param(param_name, value)
```

**Comment by dbczumar** [comment]
@reidarkind This appears to be an issue with the File Store. I'll address it!
