### ISSUE TITLE
[FR] Support for None type in mlflow params or optional arguments

### ISSUE THREAD

**Issue by k-scherer** [mlflow/mlflow#2236]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Allow MLproject files to support passing None type down to command line arguments of the underlying application or allow the specification of optional params that are ignored when not supplied.

Currently, providing a None value is not allowed for non-string types and is a "None" string when used in the downstream python script.

### Motivation
Allowing this functionality will allow for maximum compatiblity with common python commandline parsing packages (argparse) without the need to modify that code to conform to how mlflow treats MLproject parameters.

Currently, we are able to define defaults and optional arguments in our argparse ArgumentParser arguments and can perform checking for the presence of such arguments in the application

```
parser = argparse.ArgumentParser()
parser.add_argument('--assume_role', type=str, default=None)
_args = parser.parse_args()

if _args.assume_role:
    # some logic here
```

However, MLproject files would force us to either provide the argument or default to some other string value, which causes us to have to conform our code to always expect some sort of default value i.e. `if _args.assume_role == ""` and ultimately changes how we need to use it outside of mlflow workflows

### Proposed Changes
For user-facing changes, what APIs are you proposing to add or modify? For internal changes, what code paths will need to be modified?

Modify the MLproject file specification and interpretation such that it better aligns with argparsing functionality as described above

**Comment by alam-shahul** [comment]
Can this please be reopened/put on the agenda? This would be very useful...

**Comment by VladOnMyOwn** [comment]
Any updates? This would be VERY helpful and useful
