### ISSUE TITLE
[DOC-FIX] Document errors for all methods

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#2248]
### URL(s) with the issue:

https://mlflow.org/docs/latest/python_api/mlflow.html
https://mlflow.org/docs/latest/python_api/mlflow.tracking.html

### Description of proposal (what needs changing):

Document what errors are returned for method calls especially in the core mlflow and mlflow.tracking packages. 

For example, if we pass a non-existent experiment ID to MlflowClient.get_experiment, document that an exception is thrown. 

If we pass a non-existent experiment name to MlflowClient.get_experiment_by_name, document that None is returned. 

https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.get_experiment

https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.get_experiment_by_name

**Comment by dmatrix** [comment]
This is a continuing effort to enhance document all APIs with:

- code snippets

- description of input and output parameters 

- method description, behavior, and semantics

- Any errors returned or exception thrown.

**Comment by chenmoneygithub** [comment]
Yes we are in an effort to improve our docstrings.
