### ISSUE TITLE
Have you encountered this in version 0.4? When setting up a local development environment?

### ISSUE THREAD

**Issue by wqcqikvc** [mlflow/mlflow#2250]
![image](https://user-images.githubusercontent.com/53934027/71571512-99087f80-2b15-11ea-9388-505568381037.png)

**Comment by sueann** [comment]
Do you still see a problem if you use a more recent version of MLflow? Do you need to use version 0.4 for a particular reason?

**Comment by juntai-zheng** [comment]
Hi @wqcqikvc, I'm going to close this for now. If upgrading MLflow doesn't work for you, feel free to reopen this issue. Thanks!
