### ISSUE TITLE
[BUG]Issue with subprocess.Popen in backend.py

### ISSUE THREAD

**Issue by michael-vh** [mlflow/mlflow#2252]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MS Windows 10 Enterprise N
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 1.5.0
- **Python version**: Python 3.7.4 (anaconda)
- **Exact command to reproduce**: mlflow models predict -m models/scikitlearn -i testdata/test_new.csv -t csv

### Describe the problem
I'm trying to run a prediction on an MLflow model that I have created with a python script and logged with mlflow.sklearn.log_model(). When running "mlflow models predict" I'm expecting to get predictions for the records that are included in a csv file, but instead I get an EOL error:

> mlflow models predict -m models/scikitlearn -i testdata/test_new.csv -t csv
2019/12/30 13:53:01 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2019/12/30 13:53:03 INFO mlflow.pyfunc.backend: === Running command 'conda activate mlflow-0a64134cb46544fe47c7e20ac258fdf249f3f174 & python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///C:/Users/xxx/Documents/mlflowtest/models/scikitlearn', input_path='testdata/test_new.csv', output_path=None, content_type='csv', json_format='split')"'
File "", line 1
"from
^
SyntaxError: EOL while scanning string literal

When I copy and execute the command that mlflow is trying to execute
`conda activate mlflow-0a64134cb46544fe47c7e20ac258fdf249f3f174 & python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///C:/Users/xxx/Documents/mlflowtest/models/scikitlearn', input_path='testdata/test_new.csv', output_path=None, content_type='csv', json_format='split')"`
it works perfectly fine and returns the predictions for the records in the csv file. So the model seems to be working.

Going into the source code, the issue seems to be located inside the backend.py file (https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/backend.py). Where the command above is executed with
`subprocess.Popen(["cmd", "/c", command], close_fds=True, env=command_env)`
So it seems the Popen command is creating this issue.

I confirmed this by running a simple python script with the following lines, which returned the same EOL error:
```
import subprocess
command = '''conda activate mlflow-0a64134cb46544fe47c7e20ac258fdf249f3f174 & python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///C:/Users/xxx/Documents/mlflowtest/models/scikitlearn', input_path='testdata/test_new.csv', output_path=None, content_type='csv', json_format='split')"'''
child = subprocess.Popen(["cmd", "/c", command], close_fds=True, env=None)
```

### Code to reproduce issue
mlflow models predict -m models/scikitlearn -i testdata/test_new.csv -t csv

### Other info / logs

Full error:
> mlflow models predict -m models/scikitlearn -i testdata/test_new.csv -t csv
2019/12/30 13:53:01 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2019/12/30 13:53:03 INFO mlflow.pyfunc.backend: === Running command 'conda activate mlflow-0a64134cb46544fe47c7e20ac258fdf249f3f174 & python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///C:/Users/xxx/Documents/mlflowtest/models/scikitlearn', input_path='testdata/test_new.csv', output_path=None, content_type='csv', json_format='split')"'
File "", line 1
"from
^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"\__main\__", mod_spec)
File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\Scripts\mlflow.exe__main__.py", line 9, in
File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 764, in \__call\__
return self.main(*args, **kwargs)
File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 717, in main
rv = self.invoke(ctx)
File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
return callback(*args, **kwargs)
File "c:\programdata\anaconda3\lib\site-packages\mlflow\models\cli.py", line 92, in predict
json_format=json_format)
File "c:\programdata\anaconda3\lib\site-packages\mlflow\pyfunc\backend.py", line 62, in predict
return _execute_in_conda_env(conda_env_path, command, self._install_mlflow)
File "c:\programdata\anaconda3\lib\site-packages\mlflow\pyfunc\backend.py", line 172, in _execute_in_conda_env
command, rc
Exception: Command 'conda activate mlflow-0a64134cb46544fe47c7e20ac258fdf249f3f174 & python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///C:/Users/xxx/Documents/mlflowtest/models/scikitlearn', input_path='testdata/test_new.csv', output_path=None, content_type='csv', json_format='split')"' returned non zero return code. Return code = 1

MLflow model conda.yaml file:
- channels:
  - defaults
- dependencies:
  - python=3.6.9
  - scikit-learn=0.22
  - pip:
    - mlflow
    - cloudpickle==1.2.2
- name: mlflow-env

**Comment by jykeung** [comment]
I'm running into a similar issue on my Windows laptop.

Simplified example:

```python
import subprocess
child = subprocess.Popen(["cmd", "/c", "python -c 'import os'"], close_fds=True, env=None)
```

```
>>>   File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal
```

System information

- OS Platform and Distribution: `MS Windows 10 Enterprise N`
- Python version: `Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32`

**Comment by dbczumar** [comment]
This problem appears to have been addressed, so I'm going to go ahead and close this issue. Feel free to reopen it if the problem still ocurs.
