### ISSUE TITLE
[FR] Model Monitoring after Deployment

### ISSUE THREAD

**Issue by nuno-chicoria** [mlflow/mlflow#2260]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Implement features/UI for model monitoring after deployment e.g. accuracy logging over time and retraining/deployment of new models.

### Motivation
Accurate tracking of production models' performance and model retraining necessity.

**Comment by echarso** [comment]
that would be a nice addition.

**Comment by chenmoneygithub** [comment]
This is out of the current roadmap of MLflow, production monitoring is handled by each cloud provider for now.
