### ISSUE TITLE
[FR] Make deployment tool integration pluggable

### ISSUE THREAD

**Issue by hhsecond** [mlflow/mlflow#2274]
## Describe the proposal

Making integration with different deployment tools (like we have sagemaker) pluggable. Similar to the plugin system for Tracking & Artifact repository, a plugin system based on python's entrypoint groups which is then picked up by mlflow is one way of doing it

There will be three (or more in the future) allowed serving methods - `deploy`, `delete` & `run-local` (shamelessly copied from sagemaker). User can specify which method to call and which plugin to use. MLflow look for the plugin and then searches whether the plugin has that function defined or not. If defined, it calls the function with given parameters

#### From CLI
```mlflow redisai deploy ...```
We could also group it under `serving` subcommand but that makes the whole command ugly. It could look like ```mlflow serving redisai deploy```

#### From program
```mlflow.serving.deploy(plugin='redisai', *args, **kwargs)```

Links:
* PR: #2327 
* [API usage examples](https://gist.github.com/smurching/f00e3b771b2956da7281c427b5f5a681)
* [Design doc](https://docs.google.com/document/d/1KsyYO82OtHPEV4Uq8_ukDyZdBfgt7EuCtE2zFSQVea4/edit?usp=drive_web&ouid=109660911842186433457)

**Comment by smurching** [comment]
Thanks @hhsecond for filing this, it'd be great to make MLflow model deployment more pluggable. 

It'd be helpful to fully list out the options & tradeoffs (pros/cons) for the CLI & programmatic API.

For example, another option to consider is exposing pluggable deployment functionality under the `mlflow models` CLI (e.g. `mlflow models deploy ...` and `mlflow.models.deploy(...)`), for ease of discoverability given that we already have `mlflow models serve` and `mlflow models predict` CLI commands. We could also consider exposing deploy functionality through `mlflow models serve` (currently deploys a model for local serving but could be extended to deploy elsewhere), although I think users might be confused by the name.

We should also explicitly write out answers to the following
* How will developers write/specify plugins (likely via a similar mechanism to [existing tracking/artifact plugins](https://github.com/smurching/mlflow/blob/contributor-guide-plugins/docs/source/plugins.rst), i.e. using the [Python entry-point mechanism](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins))? How will plugin names like “redisai” be mapped to deployment logic (Python entry-points should make this easy)?
* What is the interface I implement as a plugin developer? A Python module with a deploy(model_uri) method? What does the API return? 
* Is the deploy functionality synchronous or asynchronous by default? What (if any) options and arguments should we expose?


Another question is how the deployment target (local vs redisai vs sagemaker etc) should be specified. When using the CLI, the target necessarily must be specified as a string. In code, we could start by specifying the target as a string, and maybe later allow users to alternatively pass a Python module containing a `deploy` method. The ability to specify a module explicitly might enable e.g. writing an MLflow script with self-contained deployment logic, but seems reasonable to start with a string in the CLI/API for consistency

**Comment by smurching** [comment]
FWIW, I think the simple answer of "copy the existing plugin mechanisms for model deployment" gets us pretty far, but would be good to just write out answers to the above questions - thanks :)

**Comment by hhsecond** [comment]
`mlflow models deploy` (and `mlflow.models.deploy(...)` from the program seems to be the best way to go, IMO. Now, let me try answer your queries
1. Yes, we can use the same entry point mechanism with {`group`: `key` = `value`} where, group could be `mlflow.deployment`, key is the name of the plugin (or the target i.e `redisai`) and value is the module that has required functions (such as `deploy` or `delete`) are defined
2. Two API methods I consider to implement are `deploy` and `delete`. I think it has to be a class (inherited from our plugin metaclass) that defines two abstract methods for `deploy` and `delete`. We should consider the possibility of other API methods such as `deploy-local` in the future. I don't think these APIs should return anything. What do you think?
3. I like the approach of what the current sagemaker API follows for synchronous/asynchronous decision
4. I think we should not do local vs others where local means `pyfunc` based. Although local vs sagemaker make sense because sagemaker is remote only, deployment tools like redisai, tensorflow serving can run locally as well. So what I'd say is to make `run-local` an API method that could be defined in the plugin if local deployment is possible for that particular plugin. For answering your question, I think passing string should be the way to go now. From program, we could do something like `mlflow.models.deploy(targe='redisai')` or `mlflow.models.deploy(plugin='redisai') or something similar. This would avoid the need of passing `deploy` function and let `mlflow` pick the plugin's `deploy` function. Did I process your thought correctly here or am I missing something obvious?

Let me know what do you think

**Comment by smurching** [comment]
@hhsecond that sounds reasonable to me. I have a couple of additional questions, largely aimed at fully fleshing out the CLI & API interface.

For 2 (which API methods to implement), you bring up a good point that there are multiple API methods (`deploy`, `delete`) we may want to require. In fact, looking at the `sagemaker` & `azureml` CLIs it seems reasonable that we'd want to allow plugins to define custom deployment subcommands in addition to `deploy` and `delete`.

Given that, I wonder if it makes sense to expose deployment functionality under `mlflow models deploy` after all. There are two considerations here:

## Question 1: What's the user workflow for running deployment CLI commands?
For example, assuming we go with `mlflow models deploy ...` we might have something like:

Finding commands under top-level MLflow namespace:

```
mlflow --help
* run
* server
* ui
* models
* sagemaker [deprecated, see models CLI instead]
* azureml [deprecated, see models CLI instead]
...
```

Finding subcommands under models CLI
```
mlflow models --help
* deploy
* serve
* predict
```

Finding subcommands under `deploy` CLI (maybe this is where plugins are exposed?)
```
mlflow models deploy --help
* sagemaker
* azureml

No plugins detected. Additional model deployment targets (e.g. redisai) can be made available by installing the appropriate plugin. See mlflow.org/docs/latest/plugins.html for more information
```

Looking up subcommands within individual deployment targets:
```
mlflow models deploy sagemaker --help
* create
* delete
* run-local
* build-and-push-container
````

Actually deploy a model:

```
mlflow models deploy sagemaker create runs:/myrunid/mymodel
```

Note that the CLI command ends up being pretty unwieldy - maybe if we exposed the commands under e.g. an `mlflow deploy` namespace it'd be slightly better (e.g. `mlflow deploy sagemaker create runs:/myrunid/mymodel`). I'd hesitate to just directly expose the subcommands under the top-level `mlflow` namespace as `mlflow redisai deploy` etc as this could lead to collisions with other non-model-deployment CLI functionality we add to the project later on. 

## Question 2: What does the programmatic workflow look like for calling custom deployment subcommands?

### Option 1: Initially, don't allow calling programmatically calling custom subcommands 

In this option, MLflow provides no Python API for calling custom deployment plugin subcommands, like Sagemaker's `run_local` or `build_and_push_container`, and instead just exposes APIs for standard subcommands like `create` & `deploy`:

```
mlflow.models.deploy.create(model_uri="...", target="redisai", *args, **kwargs)
mlflow.models.deploy.delete(target="redisai", *args, **kwargs)
```

If users want to call custom subcommands, they should directly import the plugin & invoke its methods:
```
from redis_mlflow_plugin import run_local
run_local(model_uri="...", *args, **kwargs)
```

### Option 2: Allow users to programmatically call custom subcommands

This seems difficult to achieve in a clean/Pythonic way, at least AFAICT. We could dynamically discover these custom subcommands (e.g. expose a function like `mlflow.models.deploy.run_local` if the `redisai` plugin is installed), but users would be confused about where this function comes from/surprised that simply installing MLflow is insufficient for calling it.

## Question 3: How should users pass plugin-specific arguments to deployment APIs?

### Option 1: Via a dictionary of plugin-specific keyword arguments

For example (if `target_config` is the argument name):
```
mlflow.models.deploy.create(model_uri="...", target="sagemaker", target_config={"name": "mySagemakerDeployment", "instance_type": "i3.xlarge"}
```

### Option 2: Via extra keyword args
The example in option 1 now becomes:
```
mlflow.models.deploy.create(model_uri="...", target="sagemaker", name="mySagemakerDeployment", instance_type="i3.xlarge")
```

IMO the main tradeoff here is extensibility to adding new cross-plugin arguments to model-deployment methods, e.g. a `synchronous` argument, vs ease of use (it's easier to pass keyword arguments than a dictionary IMO). Will ask other committers for thoughts - I lean towards the keyword argument approach, as I feel it's unlikely we'd add more cross-plugin deployment arguments.

**Comment by smurching** [comment]
Sorry, I know that was a lot of text, but would welcome your thoughts. I'll schedule a review of this design w/ other committers early this coming week. Given your deadline, if you want to get started with an initial implementation (by assuming specific answers to the questions above), feel free to do so - the only caveat is we may end up having to refactor it depending on the outcome of the design review

**Comment by hhsecond** [comment]
@smurching Thanks a ton for the extensive review. Here are my thoughts
### Question 1
I have been assuming all the deployment tools such as sagemaker & azureml would go out of the core of MLFlow and become a plugin as per the comment from Paul (in slack). If that is the case, what would be the most used workflow here.
- User doesn't have any plugin installed initially
- User installs the plugin he/she needs i.e They'll mostly have only one plugin installed. If this is the case, `mlflow models deploy` can pick it up magically without user specifying the target name in the command at all. User can specify plugin specific commands as CLI options which is then passed to the plugin as `**kwargs`. So the `host`, `port` and `username` arguments from below would go to `redisai`'s deploy function as keyword arguments.
```
mlflow models deploy <model uri> --host my_redisai_server --port 6379 --username myname
mlflow models delete <name/key pointing to the deployed model>
```
One caveat I see here is `mlflow models deploy --help` would not bring any information about plugin specific arguments and users should rely completely on the plugin's documentation

- If User installs multiple plugins, let's say one for `redisai` and another for `sagemaker`. We can make the target as an option and user could specify which target to pick by `mlflow models deploy --target redisai`. We can even go ahead and make the MLModel file keeps the default deployment option for each flavor as well (thinking aloud here)

Giving flexibility to plugin developers to create their own command (like given below) is not something I'd prefer because plugin developers could mess up the UI and make really bad CLIs. 
```
mlflow models deploy sagemaker --help
* create
* delete
* run-local
* build-and-push-container
```
My thought is to keep few commands we know they need for sure and let them do any operations under those command - like deploying to docker hub can execute under `deploy` itself instead of `dockerhub-push` or something similar. Also, if plugin developers wants their own CLI, they can expose that as part of their package. 
```
mlflow_redisai crazy command
```
But you know your community way better than me :)
So if I failed to convince you above limiting the CLI options, then `deploy` itself is not required and we could group it under `serve` as you were initially suggesting.
```
mlflow models serve sagemaker --help
* create
* delete
* run-local
* build-and-push-container
```

### Question 2
I like the option 1 here and that sort of goes hand in hand with my suggestion above about Question 1. 

### Question 3
I like the second option here but I don't think we should limit the extensibility here in anyways. Can't we take any keyword arguments users pass under `**kwargs` and pass it downstream for the plugins to process? Or am I missing something?


I have the basic version of what I had suggested initially coded up already and will wait for the final design before I make any intensive efforts. Also, I assume I beat you with the quantity of the text here, sorry about that too

**Comment by smurching** [comment]
Thanks @hhsecond, some more thoughts inline:

### Question 1

> User installs the plugin he/she needs i.e They'll mostly have only one plugin installed. If this is the case, mlflow models deploy can pick it up magically without user specifying the target name in the command at all. User can specify plugin specific commands as CLI options which is then passed to the plugin as **kwargs. So the host, port and username arguments from below would go to redisai's deploy function as keyword arguments.
>
> ```mlflow models deploy <model uri> --host my_redisai_server --port 6379 --username myname```


:) this is a creative way to simplify the CLI (& I agree often users won't install many different plugins), but I think we should avoid this as it'll make it hard for users to reproduce deployment commands, since the behavior of the same deployment command may differ across machines/environments based on which plugins are installed. Personally I'd prefer a command like ```mlflow models deploy redisai <model uri> --host my_redisai_server --port 6379 --username myname``` as it's clear from reading the command how it'll behave, but will check this with the other committers tomorrow.

I'll also ask about the ideal end state for the `sagemaker` and `azureml` deploy functionality, but agree that at least initially we don't need to reimplement/refactor them to use the deployment plugin.

> If User installs multiple plugins, let's say one for redisai and another for sagemaker. We can make the target as an option and user could specify which target to pick by mlflow models deploy --target redisai. We can even go ahead and make the MLModel file keeps the default deployment option for each flavor as well (thinking aloud here)

If possible (I think `click`, the Python library we use for our CLI, probably allows dynamically registering subcommands & command groups?), it'd be nice to drop the `--target` from the command, & just be able to invoke `mlflow models deploy redisai <model-uri> --host ...`. It's a good point that we may not want plugin authors to write their own CLIs, & I'm ok with disallowing custom CLI commands at least initially.

Maybe the approach we take could be to dynamically register a command group with the name of the plugin (e.g. "redisai", resulting in a `mlflow deploy redisai` command group), and then expose the `create` & `delete` functions of the plugin module as `create` & `delete` CLIs. Let me know if that makes sense

**Comment by hhsecond** [comment]
All of these were the answers I was looking for. I think I am in good position to start the development effort. Just to collate the whole discussion output here and what I'll be working on

## CLI
```
mlflow models serve/deploy <target> create <model-uri> [plugin specific options]
mlflow models serve/deploy <target> delete <key-to-model> [plugin specific options]
```
##### For custom commands from the plugin
```
mlflow_redisai custom commands
```

## Python API
All the custom arguments to the plugin would be passed as keyword arguments through `**kwargs` downstream
```
mlflow.models.deploy.create(model_uri="...", target="redisai", *args, **kwargs)
mlflow.models.deploy.delete(key="...", target="redisai", *args, **kwargs)
```

##### For custom API interfaces
```
from redis_mlflow_plugin import run_local
run_local(model_uri="...", *args, **kwargs)
```

## Plugin's structure
- Each plugin needs to inherit from the metaclass we define
- The plugin class should expose the functionalities we defined as class methods i.e. `deploy` & `delete` (and perhaps some utility functions and property attributes) for now


We use the entry point mechanism to pick up the plugins with {`group`: `key` = `value`} where, group could be `mlflow.deployment`, key is the name of the plugin (or the target i.e `redisai`) and value is the module that has required functions  defined (such as `deploy` or `delete`)

**Comment by smurching** [comment]
For linking purposes, mentioning #2327 here

**Comment by dmatrix** [comment]
This will serve as an exemplary document and discussion for future pluggable PRs!

**Comment by hhsecond** [comment]
This is implemented and merged to master
