### ISSUE TITLE
[FR][UI] Enable clicking through to individual runs from metric plots

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#2279]
## Describe the proposal

Currently, once you view a metric/plot comparing many runs in the MLflow UI, you cannot click through to individual runs that appear in the plot (e.g. the run with the best final accuracy etc). We should fix this, starting with metric comparison plots defined in [MetricPlotView.js](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/components/MetricsPlotView.js) - the exact fix may be nontrivial as it's not clear that Plotly supports adding links to legends/tooltips, although [this doc page](https://help.plot.ly/adding-HTML-and-links-to-charts/)) suggests that it's possible.

**Comment by harupy** [comment]
Nice feature to have, but tooltip doesn't seem to be hoverable (link seems to be working though).

![link-in-toolip](https://user-images.githubusercontent.com/17039389/72034869-9c4ff800-32d9-11ea-8851-ac07bf90b248.gif)

**Comment by harupy** [comment]
Or we can set an on-click callback function on each line which shows a modal with the run link.

![modal](https://user-images.githubusercontent.com/17039389/72038836-24d49580-32e6-11ea-8795-8e2316a7e774.gif)

**Comment by smurching** [comment]
@harupy awesome, I'm a fan of this as a workaround given that Plotly doesn't allow making the tooltips "sticky". I guess if users have a plot with many runs (many overlapping lines), they can isolate the run (line) of interest by double-clicking it in the legend on the right, then click the selected line. 

@gioa @mateiz @clemens-db any thoughts here?

Also, I was wondering if we could also/instead add a link to the run in the plotly legend, e.g:

![image](https://user-images.githubusercontent.com/2358483/72107654-9a406600-32e6-11ea-9266-4b380972c03f.png)

However this seems difficult to do - it's possible to change the legend text [here](https://github.com/mlflow/mlflow/blob/3440c127c9e27d8b5cf6affd0b1ced3890720e8f/mlflow/server/js/src/components/MetricsPlotView.js#L29) to include a hyperlink, e.g. by replacing that line with something like

```
    if (isComparing) {
      legendText += `, ${Utils.truncateString(runDisplayName, MAX_RUN_NAME_DISPLAY_LENGTH)}`;
      return `${legendText} <a href='http://google.com'>(link)</a>`;
    }
```

However, customizing the toggle behavior of the legend (getting the link text to actually trigger when clicked, instead of toggling the legend) seems tricky.

**Comment by smurching** [comment]
Also, do you know if this modal behavior is also possible to implement e.g. for the scatter plot & parallel coordinates plot?

**Comment by gioa** [comment]
Thank you for coming up with a solution so quickly @harupy! Using this on-click fallback function seems the right way! 

One suggestion, a modal is a little bit disruptive, could we try a popover style instead? See the mockup attached. I also add the run info in the popover so a user can confirm the run is what he/she clicks on. Let us know what you think!

![JumpToTheRun](https://user-images.githubusercontent.com/1960721/72113174-93b8eb00-32f4-11ea-87b7-2f5a76f29a33.png)

**Comment by clemens-db** [comment]
The popover would be a better user flow. One consideration is what happens when there are multiple overlapping data points. The current plot shows all of those datapoints at the same time when you hover. In this case the popover would have to list all runs with a way to navigate to each. The current mock takes up too much space for that. E.g. you'd have to have one "jump to the run" button next to each run but only one close button.

**Comment by gioa** [comment]
Thank you @clemens-db for the feedback! In that case, we can change the layout as below to display multiple run links.  
![JumpToTheRun_multiple](https://user-images.githubusercontent.com/1960721/72116921-9e797d00-3300-11ea-8ffa-f7cab2820d1b.png)


@harupy Btw Clemens and I also discussed, if we can persist the tooltip when clicking on a data point, somehow add the "Jump to the run" in the tooltip UI, it would look more familiar to the users. See a similar example [here](https://public.tableau.com/en-us/gallery/2019-global-multidimensional-poverty-index?tab=viz-of-the-day&type=viz-of-the-day). 
![Example](https://user-images.githubusercontent.com/1960721/72117208-aede2780-3301-11ea-8d18-13a3ecdef408.png)

 Not sure how hard that would be, may not worth the effort.

**Comment by harupy** [comment]
@smurching 

> Also, do you know if this modal behavior is also possible to implement e.g. for the scatter plot & parallel coordinates plot?

Haven't tried yet, but I think it's possible to implement this for scatter and parallel coordinate plots.

**Comment by harupy** [comment]
@gioa @clemens-db Thanks for the feedback. The popover looks nice, but not sure if it's possible to toggle a popover on the plotly chart. Let me try.

**Comment by harupy** [comment]
It seems we can't attach a popover to data points. One way to implement a popup is to create a component which has `x`, `y`, and `visible` as props, and update this component's props when the click event occurs (Please take a look at the demo in the attached gif). I'm looking for a component that behaves similarly in Ant Design, but haven't found one yet.

```javascript
class Popup extends React.Component {
  static propTypes = {
    x: PropTypes.number.isRequired,
    y: PropTypes.number.isRequired,
    selectedRunUuid: PropTypes.string.isRequired,
    visible: PropTypes.bool.isRequired,
  }

  render() {
    const { x, y, selectedRunUuid, visible } = this.props;
    const width = 100;
    const height = 100;
    const style = {
      left: x,
      top: y - width,
      width,
      height,
      backgroundColor: 'lightgreen',
      position: 'absolute',
      zIndex: 1,
    };

    if (!visible) return null;

    return (
      <div style={style}>
        <h1>Jump to the run</h1>
        <a href={`http://localhost:3000/#/experiments/0/runs/${selectedRunUuid}`}>
          run link
        </a>
      </div>);
  }
}
```

![popover](https://user-images.githubusercontent.com/17039389/72140228-a35b3100-33d3-11ea-8d85-744b888e369f.gif)

**Comment by gioa** [comment]
@harupy Appreciate you looking into this and the extra effort involved! The new gif looks like what we need! Could you style the popover like the mock, similar to Ant Design's [popover](https://ant.design/components/popover/)?

**Comment by harupy** [comment]
Ok, I'll try to make a popup component that works and looks similar to one in Ant Design.

**Comment by harupy** [comment]
I found a nice workaround. I'll open a PR.
