### ISSUE TITLE
[BUG] Inconsistent error message 

### ISSUE THREAD

**Issue by zaher-mh** [mlflow/mlflow#2283]
Going through the code of pyfunc, I've noticed that an error message is not consistent with the code that throw the exception. 
The condition is `(loader_module is None) and (python_model is None)`. However the message says 

> Either `loader_module` or `python_model` must be specified!

Here's a [link ](https://github.com/mlflow/mlflow/blob/v1.5.0/mlflow/pyfunc/__init__.py#L586)to the line in question

**Comment by sueann** [comment]
I think the message is correct - maybe it is not clear? The condition means neither `loader_module` nor `python_model` is specified and the message demands that at least one of them be specified. Would it be more clear if it said "At least one of `loader_module` or `python_model` must be specified!" ?

**Comment by zaher-mh** [comment]
It's indeed correct. It was confusing for me as I was debugging an error.
Nevertheless, The suggested new message is more expressive.

**Comment by sueann** [comment]
Ah I see - thanks. Is there a better error it could have given in your case?

**Comment by zaher-mh** [comment]
I made a silly error, I was passing a function instead of a class in `python_model` to `mlflow.pyfunc.log_model`. I got the error message specified in this issue. It gave me no clue that my input is not correct.  Type/instance test should be added ? Not sure.

**Comment by andychow-db** [comment]
I've created a PR with an updated error message. https://github.com/mlflow/mlflow/pull/2404
