### ISSUE TITLE
[FR] Update mlflow to use new Azure APIs

### ISSUE THREAD

**Issue by csteegz** [mlflow/mlflow#2284]
### Describe the proposal
MLFlow is currently using out-of-date APIs for deploying models to Azure. These introduce added complexity and an extra step of building an image when not required. We should update the Azure implementation to leverage up-to-date Model.package() and Model.deploy() APIs.

### Motivation
Keep MLFlow's Azure implementation up to date and simplify model deployment.
 
### Proposed Changes
Modify existing [Azure ML Module](https://github.com/mlflow/mlflow/blob/master/mlflow/azureml/__init__.py#L30) to use new Model.deploy() API as opposed to webservice.deploy_from_image.

Introduce a new `deploy` API similar to the [SageMaker Module](https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/__init__.py#L138). This will use the new [Azure ML API](https://docs.microsoft.com/python/api/azureml-core/azureml.core.model(class)?view=azure-ml-py#deploy-workspace--name--models--inference-config-none--deployment-config-none--deployment-target-none--overwrite-false-) to deploy the model.

**Comment by akshaya-a** [comment]
@pogil we're happy to pick up the work here - just wanted to get some clarity on what exactly it'd take to remove the experimental tag from the deployment commands

**Comment by dbczumar** [comment]
Now that #2375 is merged, I'm going to go ahead and close this! Thanks @csteegz !
