### ISSUE TITLE
Maybe tone tone down the stale bot?

### ISSUE THREAD

**Issue by jpambrun** [mlflow/mlflow#2290]
The stalebot is very spammy. It's set way too aggressive given the responsiveness of the team. You should consider setting the threshold to 90 days or something.

Right now, from my perspective, it feels borderline disrespectful. I spent time and effort putting together a carefully written and detailed bug report. I am not expecting or demanding anything from the team. However, I did not sign up to be spammed and asked to take action every ~20 days.

**Comment by sueann** [comment]
Thank you for the feedback! Created https://github.com/mlflow/mlflow/pull/2291 to increase the to-stale period to 365 days and the closing period to 365 days after that.

**Comment by sueann** [comment]
Merged the PR. Hopefully the stale bot will follow the instructions... :-)
