### ISSUE TITLE
Allow MLFLOW_NO_CONDA

### ISSUE THREAD

**Issue by tomberek** [mlflow/mlflow#2294]
# Describe the proposal
Allow an environment variable version of `--no-conda` such as MLFLOW_NO_CONDA

### Motivation
Convenience to turn off conda without a cli argument.

### Proposed Changes
I'm new to mlflow and the click library, but i suspect using a `click.option(..., envvar="MLFLOW_NO_CONDA")` would be relatively simple.

I'm mostly looking at these lines.
https://github.com/mlflow/mlflow/blob/master/mlflow/utils/cli_args.py#L23
https://github.com/mlflow/mlflow/blob/master/mlflow/cli.py#L72-L73

**Comment by mparkhe** [comment]
Hi @tomberek,

Can you please provide a bit more context about your environment that makes it hard to change the CLI command options. If you are deploying MLflow server in a bash script, can you condition `--no-conda` based on your local flag?

**Comment by tomberek** [comment]
Of course I can solve this with a simple wrapper script, just thought that the existing env var support could extend to this cli flag. 

Context: I’m using NixOS and while using conda does work, I enjoy using Nix to define the python environments.

**Comment by tallen94** [comment]
Hey guys! Maybe I have another use case for a similar issue. I am trying to deploy using sagemaker and also trying to disable the conda environment so I can manage the environment through docker. https://github.com/mlflow/mlflow/issues/2385 I think this could be a cool area to enhance!

**Comment by huxuan** [comment]
Hi mlflow buddies, after more than one and a half years, I wonder if there is any opinion to have this feature. For me, I want to promote mlflow to my colleagues as a required dependency for their daily work, but our ordinary work does not depend on conda actually. I would rather to have a setup script for them where handles all the settings well via environments variables with no need to specify the option every time in their daily work.

**Comment by BenWilson2** [comment]
This functionality is now handled through the environment configuration for the environment manager. Setting this attribute to "local" will use a user-defined environment.
