### ISSUE TITLE
mlflow run . errors attempting to conda activate during multistep_workflow example[BUG]

### ISSUE THREAD

**Issue by Wookinpanubs** [mlflow/mlflow#2296]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No custom code.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win 10 Pro 10.0.18363
- **MLflow installed from (source or binary)**: pip installed mlflow
- **MLflow version (run ``mlflow --version``)**: tried 1.4 and 1.5
- **Python version**: tried 3.7.4 and 3.8.1
- **Exact command to reproduce**: ~ \multistep_workflow> mlflow run .

### Describe the problem
Running "mlflow run ." from the provided multistep_workflow folder in command prompt (or anaconda prompt) creates the mlflow-#### and then errors with:

--------------------------------------------------------------------------------------
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
--------------------------------------------------------------------------------------
Running 'conda init" or any of  the given variants "conda init bash" etc don't change the result.  I can activate the env manually from cli, but the "mlflow run ." command errors every time.  I even tried pairing down the yaml dependencies, MLproject file and main.py to bare minimum and same error.

### Code to reproduce issue
mlflow run .

### Other info / logs
My only steps on a fresh windows 10 install are to download and install python 3.7.4, Anaconda 4.7.12, and pip install mlflow.  I also tried to conda-forge install mlflow, but got same result.

------------------------
2020/01/11 19:37:29 INFO mlflow.projects: === Running command 'conda activate mlflow-4172aafa43eb88172d061a0f0988e2658e7017e6 && python main.py' in run with ID 'aa92cfd61fc54a6d885b6c34a99ae541' ===

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

2020/01/11 19:37:30 ERROR mlflow.cli: === Run (ID 'aa92cfd61fc54a6d885b6c34a99ae541') failed ===
---------------------------

**Comment by orair** [comment]
I have the same problem.

**Comment by gawain-git-code** [comment]
I have the same problem as well.

**Comment by SebastianScherer88** [comment]
same issue for me.

**Comment by jerrywang8472** [comment]
same issue for me~

**Comment by sd1ver** [comment]
sane issue for me

**Comment by maximeturenne** [comment]
Same issue for me with mlflow 1.7, Windows 10 and conda 4.7.12.

**Comment by Trollgeir** [comment]
Same issue mlflow 1.7.2 Windows 10 conda  4.8.3

**Comment by darknessnerd** [comment]
same issue for me 1.7.2 Windows 10 conda 4.8.3

**Comment by chenmoneygithub** [comment]
There has not been any activity for 3 years, so I am closing it. We can reopen on demand.
