### ISSUE TITLE
[BUG] saving Mlflow experiments to ADLS mounted to DBFS 

### ISSUE THREAD

**Issue by jamborta** [mlflow/mlflow#2298]
### System information
Azure Databricks (DB runtime: 6.1)

### Describe the problem
We use DBFS with ADLS mounted in dbfs:/mnt/team1. When I create an MLFLOW experiment and specify dbfs:/mnt/team1/mlflow/experiment1 as a the artifact location, mlflow doesn't work. 

(Note: dbutils works fine with that folder)

- From the UI when clicking on a specific run it goes to a blank page `Something went wrong`
- From python CLI when trying to log an artefact or a model it fails with:

`MlflowException: API request to https://westeurope.azuredatabricks.net/dbfs/mnt/team1/mlflow/experiment1/5a8bb3dfcec14282aa266b301f3f515e/artifacts/model/model.pkl failed to return code 200 after 3 tries`

```API response body: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /dbfs/mnt/team1/mlflow/experiment1/tmp. Reason:
<pre>    Unknown internal error</pre></p>
<hr />
</body>
</html>```

**Comment by AveshCSingh** [comment]
It looks like this issue is not pertinent to OSS mlflow, so I'm going to close it.

If you're a Databricks customer, please follow up Databricks support, or at ideas.databricks.com.
