### ISSUE TITLE
[FR] Customizing the tracking server's logging format

### ISSUE THREAD

**Issue by htgislason** [mlflow/mlflow#2300]
## Describe the proposal
The possibility to customize the logging format of the MLFlow Python tracking server.

### Motivation
When the command mlflow server [options] is run, two processes come alive: The MLFlow Tracking server and Gunicorn (the underlying HTTP server). These two processes don't use the same logging format by default. Example:

Gunicorn:
`[2020-01-08 17:55:50 +0000] [19] [INFO] Starting gunicorn 20.0.4`

MLFlow:
`2020/01/08 18:22:17 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]`

Gunicorns' logging format can be changed using the mlflow server --gunicorn-opts. It would be useful to be able to do the same for MLFlow. Currently, this is not possible since the MLFlow logging format is not customizable.

### Proposed Changes
An argument could be added to the mlflow server API: https://www.mlflow.org/docs/latest/cli.html#mlflow-server to set the MLFLow tracking server logging format. The logging format is currently hardcoded here: https://github.com/mlflow/mlflow/blob/v1.5.0/mlflow/utils/logging_utils.py#L10

**Comment by chenmoneygithub** [comment]
This is a good addon feature, but considering our huge size of backlog, I am afraid we won't have bandwidth for this.
