### ISSUE TITLE
[FR] Display version in rest api

### ISSUE THREAD

**Issue by HungUnicorn** [mlflow/mlflow#2304]
## Describe the proposal
Display version information in REST API, so maintainer and user can check which version is deployed easily and fast.

### Motivation
As a user, I want to know which version of tracking server is deployed by calling REST API.
As a maintainer, I want to present the version of tracking server simply to the user by calling REST API.

### Proposed Changes
Display version in the response when requesting `/api/version`. The version information can be extracted from tag of github.

**Comment by mparkhe** [comment]
Thank you for your feedback. This sounds like a good idea.

**Comment by HungUnicorn** [comment]
I can send a PR, will not get from github tag, and use the version info from`version.py` - https://github.com/mlflow/mlflow/blob/v1.6.0/mlflow/version.py 

The endpoint also needs agreement. `/info` is also one option.

**Comment by chenmoneygithub** [comment]
my understanding is more commonly, `api/version` returns the release version rather than the framework version. Since there has not been activity for years, I am closing it. We can reopen on demand.
