### ISSUE TITLE
[BUG] Type check on code_paths parameter when saving model

### ISSUE THREAD

**Issue by jacobdanovitch** [mlflow/mlflow#2309]
### System information
Google Colab

### Describe the problem

When saving a PyTorch model using `mlflow.pytorch.save_model`, no type checking is performed on the `code_paths` parameter. Specifically, it is not considered that this parameter could accidentally be passed as a string, leading to the following (funny) outcome.

Consider the code at [line 252](https://github.com/mlflow/mlflow/blob/e70d287bcf75ac26d22db287861029ac1a5fa3d1/mlflow/pytorch/__init__.py#L252): 
```python
    if code_paths is not None:
        code_dir_subpath = "code"
        for code_path in code_paths:
            _copy_file_or_tree(src=code_path, dst=path, dst_dir=code_dir_subpath)
```
If someone were to hypothetically pass an absolute path as the parameter to code_paths (for example, `/content/myfolder/mymodelcode`), then the string is iterated through, starting with `/`. This accidentally copies the entire file system into the output directory.

~~I definitely didn't accidentally do this.~~

### Possible Fix

```python
    if code_paths is not None:
        if not isinstance(code_paths, list):
            raise TypeError(f'Argument code_paths should be a list, not {type(code_paths)}')
        code_dir_subpath = "code"
        for code_path in code_paths:
            _copy_file_or_tree(src=code_path, dst=path, dst_dir=code_dir_subpath)
```

The documentation is plenty clear about this ("code_paths – A **list** of local filesystem paths"), but given the possible outcome, it might be helpful regardless.

**Comment by dbczumar** [comment]
@jacobdanovitch thanks for pointing this out. The side effect here is definitely unfortunate. Can you file a PR with the fix you specified in the issue? Alternatively, we could modify the behavior to treat a string as a single-element list - I think that sounds like a pretty good approach.
