### ISSUE TITLE
[DOC-FIX] Broken link in https://www.mlflow.org/docs/latest/cli.html#mlflow-db-upgrade

### ISSUE THREAD

**Issue by HungUnicorn** [mlflow/mlflow#2312]
### URL(s) with the issue:
Broken link
https://github.com/mlflow/mlflow/blob/master/mlflow/store/db_migrations/README

in

https://www.mlflow.org/docs/latest/cli.html#mlflow-db-upgrade

### Description of proposal (what needs changing):
link is broken and should be reachable
https://github.com/mlflow/mlflow/tree/master/mlflow/store/db_migrations
or
https://github.com/mlflow/mlflow/blob/master/mlflow/store/db_migrations/README.md

**Comment by dbczumar** [comment]
@HungUnicorn Great catch! I've filed https://github.com/mlflow/mlflow/pull/2377 to fix this and am going to close this issue.
