### ISSUE TITLE
[FR]Support pytorch distributed training

### ISSUE THREAD

**Issue by AlexLuya** [mlflow/mlflow#2323]
Any plan for supporting pytorch distributed training?

**Comment by smurching** [comment]
@AlexLuya what sort of support would you like to see? I'm not super familiar with the distributed PyTorch API, but I'd imagine you could run a distributed PyTorch job & use MLflow APIs to log to a tracking server within it

**Comment by pogil** [comment]
Thank you for your suggestion @AlexLuya. Without additional context about the request, we can't move forward with prioritizing this feature request. Please feel reopen and reply to @smurching's query if you are still interested in this support.
