### ISSUE TITLE
console.log in setupAjaxHeaders.js

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#2326]
Is this `console.log` (line 22) necessary? (Sorry, this is not a bug. I should've used a blank issue.)

https://github.com/mlflow/mlflow/blob/a4b395b4d07407074db3d4684833b5e7f670490a/mlflow/server/js/src/setupAjaxHeaders.js#L19-L30

**Comment by harupy** [comment]
@smurching @Zangr

**Comment by smurching** [comment]
@harupy it's not necessary, happy to review a PR that removes it

**Comment by harupy** [comment]
@smurching Opened a PR.
