### ISSUE TITLE
[SETUP-BUG] Table schema in latest_schema.sql gives errors on Microsoft SQL Server

### ISSUE THREAD

**Issue by arees88** [mlflow/mlflow#2330]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 18.4 / Microsoft Windows 10 
- **MLflow installed from (source or binary)**:	source
- **MLflow version (run ``mlflow --version``)**:	1.5.0
- **Python version**:					        Python 3.7.3
- **Database version**:				                Microsoft SQL Azure (RTM) - 12.0.2000.8		
- **Exact command to reproduce**:

Run the schema from tests/resources/db/latest_schema.sql on Microsoft SQL database.
For example:

•	Start Microsoft SQL Server Management Studio
•	Connect to the database where mlflow tables should be created
•	Start SQL editor (New Query)
•	Cut and paste code from latest_schema.sql (or just the code snippet below) into the SQL editor
•	Execute the SQL

CREATE TABLE metrics_test (
        key VARCHAR(250) NOT NULL,
        value FLOAT NOT NULL,
        timestamp BIGINT NOT NULL,
        run_uuid VARCHAR(32) NOT NULL,
        step BIGINT DEFAULT '0' NOT NULL,
        is_nan BOOLEAN DEFAULT '0' NOT NULL,
        CONSTRAINT metric_pk PRIMARY KEY (key, value, timestamp, run_uuid, step, is_nan),
        FOREIGN KEY(run_uuid) REFERENCES runs (run_uuid)
)

Errors encountered are displayed below. 

Issue 1:  Column names:

key VARCHAR(250) NOT NULL,
Msg 156, Level 15, State 1, Line 11
Incorrect syntax near the keyword 'key'.

Fix applied:	Use square brackets for keywords, for example:

                        [key] VARCHAR(250) NOT NULL,

Issue 2:  Boolean data type:

is_nan BOOLEAN DEFAULT '0' NOT NULL,
Msg 2715, Level 16, State 6, Line 90
Column, parameter, or variable #5: Cannot find data type BOOLEAN.

Fix applied:	Use data type BIT instead of BOOLEAN, for example:

                        is_nan BIT DEFAULT '0' NOT NULL,

Abstract

The table schema in tests/resources/db/latest_schema.sql gives errors when Microsoft SQL database is used as the backend store.
What database types are supported by mlflow? Is Microsoft SQL Server database supported?
Can we amend the mlflow database schema so it works with Microsoft SQL database?

Additional information

I have successfully installed mlflow version 0.91 in May 2019 but had to amend the table schema first as I was getting syntax errors. I am now trying to install the latest version and still have issues.

One of the issues I encountered last year was with 'lifecycle_stage' column being duplicated in two tables, experiments and runs. I can see this has now been corrected in version 1.0. Thank you.

I am still encountering syntax errors when the table column use SQL reserved words i.e. ‘key’.
In addition, Microsoft SQL Server does not support the BOOLEAN type.
Is Microsoft SQL database supported as the backend store in mlflow?

**Comment by dbczumar** [comment]
@arees88 Copying the `latest_schema.sql` file should not be necessary / is not the recommended approach for using the SQL Tracking backend. Can you try setting your MLflow tracking URI to point to a fresh SQLServer database via `mlflow.set_tracking_uri()` and then attempt to log to MLflow?

**Comment by arees88** [comment]
@dbczumar Many thanks for your prompt response.
May I confirm that if I set the MLFLOW_TRACKING_URI environment variable to point to a fresh SQLServer database, then all the required tables will be automatically created in the database when I try to log to MLflow for the first time, e.g. call mlflow.log_param() from the python code?
B.T.W, Which part of the source code is invoked to create the new tables in the DB?

**Comment by dbczumar** [comment]
@arees88 That's correct! For reference, please check out the constructor of the `SqlAlchemyStore` class (https://github.com/mlflow/mlflow/blob/07d2b4a1a13f9245d1519423ad775a2e064faecb/mlflow/store/tracking/sqlalchemy_store.py#L66). I'm going to go ahead and close this issue; feel free to re-open it if you're still running into issues.

**Comment by arees88** [comment]
@dbczumar That's what I did last year with 0.91 but did not get very far because of the  'lifecycle_stage' column being duplicated bug. Hence I created the tables directly on the DB and after a few other fixes in the code everything worked fine. 

Re: 1.5.0
I have run one of the example scripts to initialise the tables in the database:

python examples/sklearn_elasticnet_wine/train.py

I did not get very far this time either. The execution stopped with the NotImplementedError exception in:
lib\site-packages\sqlalchemy\engine\interfaces.py", line 413, in get_check_constraints
      raise NotImplementedError()

Looks like the implementation for SQLAlchemy interface methods is missing or not found.

Please note, I have initialised the MLFLOW_TRACKING_URI  to point to an empty DB, so not sure why all the migration steps were triggered, as it is seen in the trace below:

2020/01/23 11:28:25 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2020/01/23 11:28:25 INFO mlflow.store.db.utils: Updating database tables at mssql://<cut>
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
Traceback (most recent call last):
  File "examples/sklearn_elasticnet_wine/train.py", line 56, in <module>
    with mlflow.start_run():
. . .
  File "C:\Users\AgnieszkaRees\Anaconda3\envs\mlflow_last\lib\site-packages\mlflow\store\db_migrations\versions\cfd24bdc0731_update_run_status_constraint_with_killed.py", line 38, in _has_check_constraints
    for constraint in inspector.get_check_constraints("runs")]
  File "C:\Users\AgnieszkaRees\Anaconda3\envs\mlflow_last\lib\site-packages\sqlalchemy\engine\reflection.py", line 569, in get_check_constraints
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "C:\Users\AgnieszkaRees\Anaconda3\envs\mlflow_last\lib\site-packages\sqlalchemy\engine\interfaces.py", line 413, in get_check_constraints
    raise NotImplementedError()
NotImplementedError

**Comment by dbczumar** [comment]
@arees88 Are you running the latest version of sqlalchemy? If not, can you try upgrading?

**Comment by arees88** [comment]
@dbczumar I installed sqlalchemy-1.3.12 today again

**Comment by dbczumar** [comment]
@arees88 I'll take a look at this as soon as possible.

**Comment by arees88** [comment]
@dbczumar, @smurching, @AveshCSingh Thanks for the quick turnaround.
In which release will the fix be available?

**Comment by AveshCSingh** [comment]
No problem! (@dbczumar did all the work for this, but I'll take credit :P )

It will be in 1.6.0, scheduled for release next week.

**Comment by arees88** [comment]
Thank you :-)
