### ISSUE TITLE
[FR] Add run lifecycle_stage to run UI page

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#2331]
Currently the run's lifecycle_stage is not displayed on the run details page. Adding this would be especially useful for deleted runs. For example, you can navigate to the run details page from a registered model's version.

**Comment by AveshCSingh** [comment]
Hey Andre,

If I understand this correctly, I think we already display the lifecycle_stage on the runs page. 

<img width="733" alt="Screen Shot 2020-01-31 at 2 24 16 PM" src="https://user-images.githubusercontent.com/1208791/73578830-80052e00-4435-11ea-9dc1-7f3478c36438.png">

I'm closing this for now, but feel free to re-open if this doesn't address your request.
