### ISSUE TITLE
[BUG] Tensorflow inference doesn't work with Spark UDFs

### ISSUE THREAD

**Issue by fhoering** [mlflow/mlflow#2335]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **MLflow installed from (source or binary)**: Yes
- **MLflow version (run ``mlflow --version``)**: 1.5.1
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem

Currently there are several issues with the [TensorFlow flavor](https://mlflow.org/docs/latest/models.html#tensorflow-tensorflow) in MLFlow models.

- Tensorflow model needs to be exported with columns names 0,1,2,3 to have it working. See https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/__init__.py#L443. This brings a lot of constraints for the model owner to name the Pandas/Spark df columns with generic names and also seems currently undocumented
- The predict function of TF 1.x wrapper only works with regression models https://github.com/mlflow/mlflow/blob/master/mlflow/tensorflow.py#L414 not with classification models for example where the output will be a dictionary of several tensors
- PyArrow currently has several limitations on datastructures https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html#supported-sql-types i.e. doesn't support ArrayTypes which means the inference with those tensors  doesn't work

### Proposal for fixes:

- One needs to document better on how the TensorFlow model needs to be exported and which use cases are supported
- For Spark vectorized UDFs one workaround woud be to convert the whole dataframe to tf records and the export the model to accept udfs. This is all supported by default by TensorFlow. So it would be a very generic solution that doesn't have a lot of edge cases
For online inference it is still better to directly accept tensors (to prevent serialization and de-serialization). So this probably means that the model owner needs to export his model with two functions (one that accepts tensors and one that accepts tf records).

For DataFrame to tfr record conversion we could use this udf (in fact our own upstreamed solution from Criteo) that we use and that works well in a lot of cases:
https://github.com/tensorflow/ecosystem/tree/master/spark/spark-tensorflow-connector#python-inference-with-pandas_udf-and-estimators-requires-spark--24

- To fix the column naming problem in pyspark udfs we could get the input tensor keys directly from the TensorFlow model, but it means add an additional property to the pyfunc model wrapper (that currently only has the predict method), if we agree on the intermediate tf record step this would take away this constraint as we only need one single bytestream column for the tf record.

###  Other remarks

- we currently still mostly use estimators  but for keras one can also provide different serving functions https://www.tensorflow.org/api_docs/python/tf/saved_model/save
- default export functions for estimators 
https://www.tensorflow.org/api_docs/python/tf/estimator/export/build_raw_serving_input_receiver_fn, 
https://www.tensorflow.org/api_docs/python/tf/estimator/export/build_parsing_serving_input_receiver_fn
- to be checked how also this works with tf 2 (most probably the same)

**Comment by dbczumar** [comment]
TensorFlow inference is now supported with PySpark UDFs.

**Comment by fhoering** [comment]
Thanks @dbczumar
