### ISSUE TITLE
.load_context() does not seem to run imports or assign global variables

### ISSUE THREAD

**Issue by djrscally** [mlflow/mlflow#2345]
Weird one maybe. I have a DNN built in Keras which I'm wrapping in an Sklearn wrapper so that I can use it with Pipeline. This means I have to use the `mlflow.pyfunc` module, which is fine. 

One problem I need to solve is that 4 of my features are multi-variate; I.E. each of those features contains an array of values, like the Item History feature below:

```
  CustomerAccountNum                        Item History
0          100378466                            [964538]
1          100383315  [443583, 3508270, 4021856, 955424]
2          100383315  [443583, 3508270, 4021856, 955424]
3          100383315  [443583, 3508270, 4021856, 955424]
4          100383315  [443583, 3508270, 4021856, 955424]
```

The problem is that that needs encoding obviously, and sklearn's preprocessors don't accept partial-fit (which would let me sweep over the arrays and partially fit on each row). For that reason I'm pre-fitting ordinal encoders, and then building [FunctionTransformers](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html) using a helper function that transforms each of those features in the way I want (transforms using the pre-fitted estimators, then pads to 200 items). Like this:

```Python
# Pre-fit the encoder
le = LabelEncoder()
le.fit(df.Item)

# Helper Functions

def PlusOneTransformer(X):
    """
    Just increases every encoded value by one; necessary to avoid labels mapped to 0 being discarded by Keras
    masking
    """
    return X + 1

def _pad(x):
    """
    Wrapped function defining max pad length
    """
    return pad_sequences([x], maxlen=200)[0]

def PrePadder(X):
    """
    Pads Item History to shape.
    """
    return X.applymap(_pad)

def ItemLabelEncoder(x):
    """
    Converts Item History to prefitted encoder values
    """
    return x.applymap(le.transform)

preprocessor = Pipeline(steps=[
    ('LabelEncode', FunctionTransformer(ItemLabelEncoder)),
    ('PlusOne', FunctionTransformer(PlusOneTransformer)),
    ('PrePadder', FunctionTransformer(PrePadder))
])
```

Now; all that works fine in the training script. I create a class that inherits from `mlflow.pyfunc.PythonModel` that (in the training script) has a `.save()` method to dump the constituent parts to disk and has a `.load_context()` method defined that **should** import everything back in hunky dory, like so:

```Python
class ProductRecommender(PythonModel):
    
    def __init__(self):
        return
        
    def load_context(self, context):
        
        import keras
        from keras.metrics import sparse_top_k_categorical_accuracy
        from helper_functions import \
            PlusOneTransformer, \
            ItemLabelEncoder, \
            ManufacturerLabelEncoder, \
            CategoryLabelEncoder, \
            SubCategoryLabelEncoder, \
            _pad, \
            PrePadder, \
            add_sq_cols, \
            add_cbrt_cols, \
            top_10_categorical_accuracy
        
        global le
        global mle
        global cle
        global scle
        
        le = joblib.load(context.artifacts['item_encoder'])
        mle = joblib.load(context.artifacts['manufacturer_encoder'])
        cle = joblib.load(context.artifacts['category_encoder'])
        scle = joblib.load(context.artifacts['subcategory_encoder'])
        
        self.keras_model = keras.models.load_model(context.artifacts["keras_model"], custom_objects={'top_10_categorical_accuracy':top_10_categorical_accuracy})
        self.sklearn_preprocessor = joblib.load(context.artifacts["sklearn_preprocessor"])
        
        self.sklearn_model = KerasModelRegressor(self.keras_model, epochs=5, validation_split=0.2)
        
        self.pipeline = Pipeline(steps=[
            ('preprocessor', self.sklearn_preprocessor),
            ('estimator', self.sklearn_model)
        ])
    
    def save(self, pipeline, le, mle, cle, scle):
        pipeline.named_steps.estimator.model.save('artifacts/keras_model.h5')
        joblib.dump(pipeline.named_steps.preprocessor, 'artifacts/sklearn_preprocessor.joblib')
        joblib.dump(le, 'artifacts/le.joblib')
        joblib.dump(mle, 'artifacts/mle.joblib')
        joblib.dump(cle, 'artifacts/cle.joblib')
        joblib.dump(scle, 'artifacts/scle.joblib')
        
    def predict(self, context, X):
        return self.pipeline.predict(X)
```

and then I log that against the run using `.log_model()`:

```Python
with mlflow.start_run() as run:
    
    print('This Run ID: ', run.info.run_id)
    
    pipeline.fit(df, le.transform(df.Item))
    pr = ProductRecommender()
    pr.save(
        pipeline,
        le,
        mle,
        cle,
        scle
    )
    
    conda_env = {
        'name': 'mlflow-env',
        'channels': [
            'defaults',
            'anaconda',
            'conda-forge'
        ],
        'dependencies': [
            'python=3.7.0',
            'cloudpickle',
            'keras==2.2.5',
            'joblib==0.13.2',
            'scikit-learn==0.20.3',
            'sys'
        ]
    }

    artifacts = {
        'keras_model':'artifacts/keras_model.h5',
        'sklearn_preprocessor':'artifacts/sklearn_preprocessor.joblib',
        'item_encoder':'artifacts/le.joblib',
        'manufacturer_encoder':'artifacts/mle.joblib',
        'category_encoder':'artifacts/cle.joblib',
        'subcategory_encoder':'artifacts/scle.joblib'
    }

    mlflow.pyfunc.log_model(
        artifact_path='Model',
        code_path=['artifacts/sklearn_wrapper.py', 'artifacts/helper_functions.py'],
        python_model=pr,
        conda_env=conda_env,
        artifacts=artifacts
    )
```

Note that in addition to passing the pickled objects as artifacts, I'm also passing the file defining the helper functions to `code_path`. That `log_model()` operation seems to be fine.

My problem in a nutshell is that when I called `model = mlflow.pyfunc.load_model()` to import that saved mode, the import statements and assignment of global variables inside `.load_context()` don't seem to happen; so if I run this as my loading command:

```Python
import mlflow
import mlflow.pyfunc
model = mlflow.pyfunc.load_model('runs:/292c8c28f3ce468cb89e4aa9e1dded25/Model')
```

An exception is thrown:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-19d417ca6b69> in <module>
      1 import mlflow
      2 import mlflow.pyfunc
----> 3 model = mlflow.pyfunc.load_model('runs:/292c8c28f3ce468cb89e4aa9e1dded25/Model')

c:\users\dscally\appdata\local\programs\python\python37\lib\site-packages\mlflow\pyfunc\__init__.py in load_model(model_uri, suppress_warnings)
    290         mlflow.pyfunc.utils._add_code_to_system_path(code_path=code_path)
    291     data_path = os.path.join(local_model_path, conf[DATA]) if (DATA in conf) else local_model_path
--> 292     return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
    293 
    294 

c:\users\dscally\appdata\local\programs\python\python37\lib\site-packages\mlflow\pyfunc\model.py in _load_pyfunc(model_path)
    221 
    222     context = PythonModelContext(artifacts=artifacts)
--> 223     python_model.load_context(context=context)
    224     return _PythonModelPyfuncWrapper(python_model=python_model, context=context)
    225 

<ipython-input-22-56b57b832a62> in load_context(self, context)

c:\users\dscally\appdata\local\programs\python\python37\lib\site-packages\joblib\numpy_pickle.py in load(filename, mmap_mode)
    603                     return load_compatibility(fobj)
    604 
--> 605                 obj = _unpickle(fobj, filename, mmap_mode)
    606 
    607     return obj

c:\users\dscally\appdata\local\programs\python\python37\lib\site-packages\joblib\numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    527     obj = None
    528     try:
--> 529         obj = unpickler.load()
    530         if unpickler.compat_mode:
    531             warnings.warn("The file '%s' has been generated with a "

c:\users\dscally\appdata\local\programs\python\python37\lib\pickle.py in load(self)
   1086                     raise EOFError
   1087                 assert isinstance(key, bytes_types)
-> 1088                 dispatch[key[0]](self)
   1089         except _Stop as stopinst:
   1090             return stopinst.value

c:\users\dscally\appdata\local\programs\python\python37\lib\pickle.py in load_global(self)
   1374         module = self.readline()[:-1].decode("utf-8")
   1375         name = self.readline()[:-1].decode("utf-8")
-> 1376         klass = self.find_class(module, name)
   1377         self.append(klass)
   1378     dispatch[GLOBAL[0]] = load_global

c:\users\dscally\appdata\local\programs\python\python37\lib\pickle.py in find_class(self, module, name)
   1428             return _getattribute(sys.modules[module], name)[0]
   1429         else:
-> 1430             return getattr(sys.modules[module], name)
   1431 
   1432     def load_reduce(self):

AttributeError: module '__main__' has no attribute 'ItemLabelEncoder'
```

So the `from helper_functions import blah blah` bit of `.load_context()` isn't working. If I define those functions (or locally import them from the actual helper_functions.py) then the `model = mlflow.pyfunc.load_model()` call completes properly, but the le, mle, cle and scle objects that are defined as global variables in `.load_context()` are not instantiated:

```Python
>>> le
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-286ef15a1c47> in <module>
----> 1 le

NameError: name 'le' is not defined
```

But the assignments of class attributes (`self.keras_model` etc) DO work fine. 

I'm not sure if this is a bug, something unimplemented yet or if I'm just using it completely wrong (which wouldn't be the first time). Can anyone give any advice on a way forward? I hope I've given enough detail here to show what the problem is but please let me know if you need anything more.

**Comment by tomasatdatabricks** [comment]
Hi @djrscally, thanks for posting. 

It does look like your source files are missing. Can you save the model locally and verify that the extra python files are there? The code_path argument should be a local path to your source files, I see you point to artifacts directory.

**Comment by djrscally** [comment]
Hi @tomasatdatabricks, thanks for responding. 

I've got the model save locally; the helper_function.py file is stored in `mlruns\6\292c8c28f3ce468cb89e4aa9e1dded25\artifacts\Model\code` and the pickled objects in mlruns\6\292c8c28f3ce468cb89e4aa9e1dded25\artifacts\Model\artifacts`. The artifacts directory in `code_path` isn't inside the `runid/artifacts/Model` folder, but I recognise it probably wasn't the best naming to use :P

So yeah, source files definitely seem to be present and correct

**Comment by tomasatdatabricks** [comment]
I see. Actually looking at it second time, I think the problem is something else. It looks like the import worked fine (i.e. did not throw an exception). I think the problem is that pickle is looking for classes defined in __main__ module but your classes are actually in helper_functions module. Did you import them from helper_functions.py in your train script or were they just defined in the __main__?

**Comment by djrscally** [comment]
In the training script, they're just defined in **main**, not imported.

**Comment by tomasatdatabricks** [comment]
Yeah that's probably the problem. Can you either import them from the same module or use cloudpickle instead of pickle and drop the code dependencies? I think that should fix it.

**Comment by djrscally** [comment]
@tomasatdatabricks Thanks, I'll try both. Struggling a little to discern how to store them with cloudpickle...can you dump a file like pickle/joblib that I can include as an artifact?

**Comment by tomasatdatabricks** [comment]
I am not familiar with joblib tbh. You can try to replace joblib.dump and joblib.load with cloudpickle.dump and cloudpickle.load and see if it works.

**Comment by djrscally** [comment]
Yeah it was `.dump()` for file rather than `.dumps()` for string that was confusing me...the cloudpickle github only has `.dumps()` and I'm not familiar with pickle so it didn't twig. I'll give it a go in the morning. 

Thanks for your help, I appreciate it

**Comment by djrscally** [comment]
@tomasatdatabricks all fixed; cloudpickle worked fine. Interesting one, thanks. Scikit-learn [recommends](https://scikit-learn.org/stable/modules/model_persistence.html?highlight=persisting) that joblib is the way to go, however it certainly seems to be inferior to cloudpickle in terms of persisting the dependencies of a pickled function in addition to the function itself. 

Thanks again for your help.
