### ISSUE TITLE
[BUG] SQL Server connection doesn't write data

### ISSUE THREAD

**Issue by Effervex** [mlflow/mlflow#2351]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Mostly no. Slight variation on https://mlflow.org/docs/latest/tracking.html#id42
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: source (conda)
- **MLflow version (run ``mlflow --version``)**: 1.5.0
- **Python version**: 3.7.6
- **npm version, if running the dev UI**: NA
- **Exact command to reproduce**: NA

### Describe the problem
I am attempting to use MS SQL Server for my MLFlow tracking. I can connect it with a valid connection string (see below code - some details obfuscated for privacy), and it will create the necessary tables for tracking in the database (`experiments, metrics, params, runs, tags`). But it will not go any further and produce an error:
`OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC SQL Server Driver]Neither DSN nor SERVER keyword supplied (0) (SQLDriverConnect)')
(Background on this error at: http://sqlalche.me/e/e3q8)`

It seems odd to me that it is able to access the DB, create the necessary tables, but fail at adding any data to the tables. My user privileges are adequate for INSERTing rows, and I have connected and INSERTed into this DB before with pyodbc, so I suspect the issue lies somewhere within MLFlow.

### Code to reproduce issue
```
import urllib
import mlflow

params = urllib.parse.quote_plus('DRIVER={SQL Server};'
                              'SERVER=<server address>;'
                              'DATABASE=<dbname>;'
                              'UID=<username>;'
                              'PWD=<password>')
remote_server_uri = 'mssql+pyodbc:///?odbc_connect={}'.format(params)
mlflow.set_tracking_uri(remote_server_uri)
with mlflow.start_run():
    mlflow.log_param("a", 1)
    mlflow.log_metric("b", 2)
```

As stated, this results in tables being created, but no data added.

**Comment by tallen94** [comment]
I think this is a related issue. I proposed a solution on it if you are interested in trying it out. Let me know what you think! https://github.com/mlflow/mlflow/issues/2381

**Comment by Effervex** [comment]
Thanks for the tip. Unfortunately, it does not appear to be the solution.
When I run my 'mlflow server' command (see below), I get output that tables are being created (as before) on the DB, but the command then quietly exits, rather than continuously running.

I tested the 'mlflow server' with a local file system location as the --backend-store-uri and that worked just fine, but it seems to be with this mssql connection (and maybe other DB connections) that it breaks down.

Complete output of running the 'mlflow server' command (using <<blah>> in place of private details):
```
mlflow server --backend-store-uri mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BSQL+Server%7D%3BSERVER%3D<<obfuscated server>>%3BDATABASE%3DMLFlow%3BUID%3D<<obfuscated user>>%3BPWD%3D<<obfuscated password>> --default-artifact-root <<local directory>>

2020/02/04 13:21:59 INFO mlflow.store.db.utils: Creating initial MLflow database tables...

2020/02/04 13:22:00 INFO mlflow.store.db.utils: Updating database tables at mssql+pyodbc:///?odbc_connect=DRIVER={SQL Server};SERVER=<<obfuscated server>>;DATABASE=MLFlow;UID=<<obfuscated user>>;PWD=<<obfuscated password>>
```
At this point control returns to the console - no error, no hanging, nothing.

I suspect the connection quietly drops after completing the database table creation, meaning that further DB calls fail (see original message error).

**Comment by tallen94** [comment]
Interesting. Yeah, this wasnt the solution for the other thread as well. I have this setup working with just a mysql database (Aurora on AWS). Ill let you know if I think of something else!

**Comment by andychow-db** [comment]
Are you using the SQL Server plugin? 
https://www.mlflow.org/docs/latest/plugins.html#sql-server-plugin

**Comment by dbczumar** [comment]
@andychow-db The SQL Server plugin is designed for artifact storage. This ticket pertains to issues with run metadata storage on SQL Server. @Effervex We're looking into this!

**Comment by Effervex** [comment]
> Are you using the SQL Server plugin?
> https://www.mlflow.org/docs/latest/plugins.html#sql-server-plugin

Just to answer: no, I am not using that plugin. I am not too worried about artifact storage at the moment. Thanks for the attention - I hope this isn't just me making a dumb mistake.

**Comment by chenmoneygithub** [comment]
I am closing this issue since there has not been any activity for 3 years, we can reopen on demand.
