### ISSUE TITLE
[FR] Allow additional keyword args for Pyfunc model

### ISSUE THREAD

**Issue by eliasmistler** [mlflow/mlflow#2360]
### Describe the proposal
Currently, Pyfunc models' `predict` function strictly take a single data argument. For some models, you may want extra inputs, which is why, for example, [sklearn allows additional keyword args to be passed into a pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.predict)
I suggest allowing keyword args for Pyfunc models as well.

### Motivation
I appreciate a similar result can be achieved by making `model_input` a `dict`, containing a number of inputs. However, I do think it makes sense to keep the APIs reasonably consistent between the sklearn and pyfunc implementations.

### Proposed Changes
* `PythonModel.predict` to allow `**kwargs`
* `_PythonModelPyfuncWrapper.predict` to take `**kwargs` and pass through to `PythonModel.predict`

**Comment by tanmaymathur89** [comment]
Would love to have support for kwargs. A lot of our models require additional paramaters that don't fit into the input dataframe.

**Comment by anggao** [comment]
Any updates on this, this feature will be useful to some of our models :)

**Comment by mkierans** [comment]
Please provide some updates here. This would also be useful for my models.

**Comment by HansBambel** [comment]
Yes, that would definitely be helpful for me as well :)

**Comment by dbczumar** [comment]
This has now been implemented in MLflow 2.6: https://mlflow.org/docs/latest/models.html?highlight=params#model-inference-params. Thank you for using MLflow!
