### ISSUE TITLE
[FR] Add Run's status to main dashboard

### ISSUE THREAD

**Issue by tianchuliang** [mlflow/mlflow#2362]
## Describe the proposal
Currently, in MLflow's main dashboard for a given experiment, the list of runs don't have a clear indication of which is currently running, which is dead or completed, etc. It'd be a helpful addition to have a column, indicating current runs' statuses. 

### Motivation
For data scientists to easily see what runs are active/dead/suceeded/failed. 

### Proposed Changes
Add a column in front-end display of runs, have it fetch current run's information periodically.

**Comment by dbczumar** [comment]
@tianchuliang Thanks for your input! This feature has been released in MLflow 1.6 with other useful updates to our Runs table view.
