### ISSUE TITLE
MLflow serve is not working - throwing Not Found message in the browser

### ISSUE THREAD

**Issue by suresh88** [mlflow/mlflow#2368]
I am having the trouble accessing the mlflow serve url
System Information:
OS: ubuntu 18.04
mlflow version: 1.6.0
python version: 3.7.3

commands to reproduce:
mlflow run sklearn_logistic_regression
mlflow models serve -m runs:/6456aa2de1f84dce91c190bf93fc2431/model --port 3456
facing the Not Found error all the time

Is there any permanent solution available?

**Comment by dbczumar** [comment]
@suresh88 The model server responds to `POST` requests containing request content and is not meant to respond to `GET` requests issued during browser navigation. See https://mlflow.org/docs/latest/models.html#deploy-mlflow-models for an example of querying an MLflow Model server.

**Comment by ravi289-97** [comment]
Hi @dbczumar , I am working on windows and i have encountered the same issue.
I have set my tracking uri as postgres db and artifacts to local system with the below command
**mlflow server --backend-store-uri postgresql://mlflow_user:mlflow@localhost/mlflow_test --default-artifact-root file:D:/Practice/Mlflow/mlruns -h 0.0.0.0 -p 8000**

Then I have registered the model into a production and tried this command 
**model = mlflow.sklearn.load_model(
    model_uri=f"models:/{model_name}/{stage}"
)**
and the predictions work as expected.
However, if I wanted to serve it using mlflow models serve with same uri as above it says the model is not registered. I am not sure why this works with code and not with the CLI.
This is the command that gives me error:  
**mlflow models serve --model-uri models:/myclassifier/Production -p 5001 --no-conda**
Please help. Thanks in advance
