### ISSUE TITLE
Add a way to retrieve active run's Conda environment.

### ISSUE THREAD

**Issue by tomasatdatabricks** [mlflow/mlflow#237]
### Describe the problem
Currently there does not seem to be a good way to retrieve Conda environment of an active run. For example, say I run my code via mlflow run and I have an Conda environment specified in my MLproject file and I want to log a model and pass it the same Conda environment as I use in my run. 

Proposed solution: Add this information to ActiveRun.

**Comment by hamroune** [comment]
it will be nice to have this feature

**Comment by tomasatdatabricks** [comment]
There has not been much interest in this feature and it does not look like we're gonna do this anytime soon. Furthermore, this use case is partially covered by default conda environments defined by model flavors. Closing it for now.
