### ISSUE TITLE
[BUG] mlflow models build-docker fails to find mvn artifact

### ISSUE THREAD

**Issue by paeselhz** [mlflow/mlflow#2372]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: Source
- **MLflow version (run ``mlflow --version``)**: 1.6.0
- **Python version**: 3.7.4
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: 

### Describe the problem
After tracking the model in mlflow, when trying to build a docker image this error appears:
`Could not find artifact org.mlflow:mlflow-scoring:jar:1.6.0 in central (https://repo.maven.apache.org/maven2)`.
I've tracked the maven repository and it appears that for Mlflow version 1.5.0 there is a mlflow-scoring-1.5.0.jar, but for Mlflow 1.6.0, there is no such file, onlye the mlflow-scoring-1.6.0-sources.jar

### Code to reproduce issue
mlflow models build-docker -m "runs:/421150b7ed274a659b2d6ead91f063df/model" -n "mlflow-model-docker"

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (default-cli) on project standalone-pom: Unable to find artifact. Could not find artifact org.mlflow:mlflow-scoring:jar:1.6.0 in central (https://repo.maven.apache.org/maven2)
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=org.mlflow -DartifactId=mlflow-scoring -Dversion=1.6.0 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=org.mlflow -DartifactId=mlflow-scoring -Dversion=1.6.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   org.mlflow:mlflow-scoring:jar:1.6.0
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command '/bin/sh -c mvn  --batch-mode dependency:copy -Dartifact=org.mlflow:mlflow-scoring:1.6.0:jar -DoutputDirectory=/opt/java/jars' returned a non-zero code: 1
```

**Comment by dbczumar** [comment]
Hi @paeselhz, the `mlflow-scoring` package for MLflow 1.6 landed on Maven a couple hours ago. Can you try again? If this issue persists, feel free to reopen this ticket!
