### ISSUE TITLE
[FR] Avoid git call if it is known that the project is not in a git repository

### ISSUE THREAD

**Issue by akk5597** [mlflow/mlflow#2379]
## The Proposal
Currently it is necessary to have an executable for git and the git library in Python in order to run a project, even if it is not a git repository. Can it be altered in order to not use git at all and continue the execution of project?

### Motivation
In deployment of an application using MLflow in production, it may be possible that a customer may not allow installation of git as it will be able to get code from a remote repository.

### Proposed Changes
It may be inferred from an environment variable if git is to be used. This would bring a change in the ```run``` API of ```mlflow.projects```.

**Comment by dbczumar** [comment]
@akk5597 Thanks for raising this. We'll take a look and see if the `git` dependency can be made optional.

**Comment by chenmoneygithub** [comment]
I am closing this issue since there has not been any activity for 3 years, we can reopen on demand.
