### ISSUE TITLE
Add support for logging environment of the run.

### ISSUE THREAD

**Issue by tomasatdatabricks** [mlflow/mlflow#238]
### Describe the problem
Currently there is no support for logging of the run's environment. Being able to retrieve the exact environment is critical for reproducibility. While the users can log it manually e.g. as an param and / or an artifact  it's not easy. I would be nice to automatically log the Conda environment of every run, or at least to add more logging support specific to the environment.

**Comment by dbczumar** [comment]
@tomasatdatabricks Yay! We did this!

**Comment by tomasatdatabricks** [comment]
Did we? :)

**Comment by dbczumar** [comment]
No
