### ISSUE TITLE
[FR] Is it possible to trigger a model deployment ( or model state transition ) from the UI. Trigger a Jenkins job for example 

### ISSUE THREAD

**Issue by echarso** [mlflow/mlflow#2383]
Add a hook to the model registry so as to trigger functions/events when a user is changing the state of the models

### Motivation
Now it is possible to have the desired functionality by using MLFlow APIs and by periodically asking model states . However since we want to trigger deployments asap a model changes stat , then it means that we should continuously  check for model updates. It would be much better if we had hooks we can register out code there

**Comment by dbczumar** [comment]
@echarso Can you complete the Issue Template for this feature request? Model stage transitions can be made through the Model Version UI. You can use the Model Registry APIs to periodically query and fetch the latest model in a particular stage and deploy it (e.g., via Jenkins Job). Deployment functionality is not natively integrated into the Model Registry UI/API at this point.

**Comment by echarso** [comment]
@dbczumar  Thank you for this answer!

Yes I am using model Registry APIs to periodically check model state transitions. 
However it will be better if we had ' hooks' to register functions to be executed on events.

A small addition also perhpas a litle bit off topic....

since I want to generate deployments  after transition of models and I want to extract pre processing code from github then it would be nice from the APIs to be able to extract the relevant git repo also. Not just the git commit id.

**Comment by rmalav15** [comment]
Have a look at this: https://github.com/indix/mlflow-gocd

**Comment by pogil** [comment]
Just want to add a note that some form of webhooks support for Model Registry is on the roadmap here at Databricks, but we're still designing it. 

@echarso for getting information about which git repo I'd recommend setting this yourself as a tag for now. It might be worth creating a separate feature request for this idea as well, but it requires a bit of thought about which git repo to log (current, origin, ?)

**Comment by pogil** [comment]
We may close this issue and link to a more detailed issue when we're ready to get some community feedback on webhooks. (cc @mparkhe)

**Comment by echarso** [comment]
Thanks, for the suggestion with the tag ,we are actually setting the git repo as a tag right now.
We can close this , hope the functionality with web-hooks will come !

**Comment by vishal-ramesh2** [comment]
Hi @pogil is there an ETA on when this webhooks in model registry might be available?

The way we are looking to use is that we have custom model servers and when we promote a model in the model registry, we want to trigger a Jenkins CI/CD pipeline with some parameters about the model (like the model version or the remote path to download the model from)

**Comment by phitoduck** [comment]
I saw a demo by databricks of an MLFlow workflow. Webhooks are implemented now. But only for the databricks distro of MLFlow. Sadly, we're not looking to start using another vendor so this is not of use to our group. 

If the features are only available in the vendor-hosted version, you certainly increase vendor lock-in to Databricks if you start to rely on webhooks :/

At that point, I think you'd have to treat Databricks as just another vendor, and consider *all* the possible model registry vendors (ClearML, WandB, etc.)

**Comment by Annamalaisaravanan** [comment]
Guys, Currently I am trying to add a mlflow transition webhook in databricks. Can anyone please tell how can I trigger github actions yml file with the webhook?
