### ISSUE TITLE
[BUG] Keras support in tensorflow 2.0

### ISSUE THREAD

**Issue by mrtj** [mlflow/mlflow#2390]
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.6.0
- **Python version**: 3.7.4
- **npm version, if running the dev UI**: n/a
- **Exact command to reproduce**: mlflow.keras.autolog()
- **TensorFlow version**: 2.0.0
- **keras version**: 2.2.4-tf

### Describe the problem
I try to use the keras autologger with the keras built-in in TensorFlow 2.0. The call to`mlflow.keras.autolog()` fails with `ModuleNotFoundError: No module named 'keras'`

### Code to reproduce issue
```python
import mlflow.keras
mlflow.keras.autolog()
```

### Other info / logs
The the `autolog()` function  in `mlflow.keras` module tries to import keras directly from the global namespace, however in TF 2.0 keras is a submodule of TensorFlow. In fact if I change the line 427 in keras.py from `import keras` to `from tensorflow import keras` the autologging works as expected.

Tracelog of the exception:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-8539acb3e9a3> in <module>
----> 1 mlflow.keras.autolog()
      2 
      3 with mlflow.start_run():
      4 
      5     y = y_ctr

~/anaconda3/envs/tf2/lib/python3.7/site-packages/mlflow/keras.py in autolog()
    425     excluding ``mode`` and ``verbose``.
    426     """
--> 427     import keras
    428 
    429     class __MLflowKerasCallback(keras.callbacks.Callback):

ModuleNotFoundError: No module named 'keras'
```

**Comment by dbczumar** [comment]
@juntai-zheng Can you take a look at this?

**Comment by harupy** [comment]
@mrtj Did you install keras?

**Comment by harupy** [comment]
Maybe we could do something like:

```python
if keras_installed:
    import keras
elif tf2_installed:
    from tensorflow import keras
else:
    raise ModuleNotFoundError
```

**Comment by juntai-zheng** [comment]
@mrtj `tf.keras` autologging is handled by [`mlflow.tensorflow.autolog()`](https://www.mlflow.org/docs/latest/tracking.html#tensorflow-and-keras-experimental) rather than `mlflow.keras.autolog()` due to different ways we patch the modules and deal with additional TensorBoard logs for `tf.keras` models. Can you try switching to `mlflow.tensorflow.autolog()` and tell us what happens?

**Comment by mrtj** [comment]
Hello, I tried to switch to `mlflow.tensorflow.autolog()` and  it works (even if some metrics are logged with different name, eg. `optimizer_name` vs `opt_name`, `learning_rate` vs `opt_learning_rate`, etc.). Maybe it's worth to specify in the docs that for keras in tf2 one should use this method.

**Comment by juntai-zheng** [comment]
`mlflow.tensorflow.autolog()` actually has a parameter `every_n_iter=100` (see the [docs](https://mlflow.org/docs/latest/python_api/mlflow.tensorflow.html#mlflow.tensorflow.autolog)) that dictates how many 'iterations' must pass before MLflow logs metrics, which is different between TF 1.X and TF 2.X. In TF 1.X an iteration is a batch, while in TF 2.X an iteration is an epoch. To get the metrics for every epoch, you will probably want to set `every_n_iter=1`. It might be good to change the default value in MLflow when using TF 2.X so issues like this don't pop up in the future - would you be willing to make a change for that @mrtj?

**Comment by maximeturenne** [comment]
I suggest that the tensorflow example https://github.com/mlflow/mlflow/blob/master/examples/tensorflow/tf2/train_predict_2.py show a usage example of the **every_n_iter** attribute.

**Comment by juntai-zheng** [comment]
I think changing `every_n_iter=1` and updating the example would be good. I'll open up a PR tomorrow for that.

**Comment by hmamdouh** [comment]
> Maybe we could do something like:
> 
> ```python
> if keras_installed:
>     import keras
> elif tf2_installed:
>     from tensorflow import keras
> else:
>     raise ModuleNotFoundError
> ```

Can this solution added to the source code of mlflow for tf2?
I am seeing the same error.

**Comment by honestaburke** [comment]
Same issue as OP. I tried `mlflow.tensorflow.autolog()` as well, which leads to a different issue.

**Comment by dbczumar** [comment]
`mlflow.tensorflow.autolog()` supports TensorFlow 2.0, as well as the `every_n_iter` parameter, in recent versions of MLflow. Accordingly, I'm going to go ahead and close this issue. Feel free to reopen it if this problem still occurs.
