### ISSUE TITLE
[FR] Syntax highlighting for text artifact viewer

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#2406]
I'm working on a syntax highlighting feature for the text artifact viewer.

![highlight-demo](https://user-images.githubusercontent.com/17039389/74078809-32f70c80-4a72-11ea-9996-5583099aae11.gif)

I used this package: https://github.com/conorhastings/react-syntax-highlighter

**Comment by harupy** [comment]
Dark theme

![dark-theme](https://user-images.githubusercontent.com/17039389/74438520-b7e88880-4ead-11ea-8316-32cf8bf4d881.gif)

**Comment by smurching** [comment]
@harupy this is awesome! Would be happy to review a PR for this - how much larger does the new dependency make the MLflow UI bundle?

**Comment by harupy** [comment]
@smurching 

The current master (commit hash: bceb50024c98c8b372092557cbe4e93330fb2c94)

```
2.19 MB   build/static/js/2.37d9d786.chunk.js
96.26 KB  build/static/css/2.0604402e.chunk.css
64.48 KB  build/static/js/main.f816a51d.chunk.js
4.42 KB   build/static/css/main.8b0809bf.chunk.css
769 B     build/static/js/runtime~main.34eeba64.js
```

[Light Build](https://github.com/conorhastings/react-syntax-highlighter#light-build)

```
2.2 MB    build/static/js/2.f4841b6f.chunk.js
96.26 KB  build/static/css/2.0604402e.chunk.css
64.64 KB  build/static/js/main.a8726800.chunk.js
4.42 KB   build/static/css/main.8b0809bf.chunk.css
769 B     build/static/js/runtime~main.34eeba64.js
```

**Comment by smurching** [comment]
@harupy nice! Seems like minimal impact either way, but especially minimal impact if we use the light build, if that's not too much work :) - would be happy to review a PR

**Comment by smurching** [comment]
Oh, I see - with the light build we need to explicitly specify which languages to enable syntax highlighting for. Given the relatively minimal bundle-size impact + lower maintenance burden of using the full build, maybe we can just use that.

**Comment by harupy** [comment]
Agree with using the full build. I'll submit a PR!

**Comment by harupy** [comment]
@smurching Submitted a PR ⬆️
