### ISSUE TITLE
mlflow with scala: java.lang.IllegalStateException: "Default client requires MLFLOW_TRACKING_URI is set. Use fromTrackingUri() instead."

### ISSUE THREAD

**Issue by P-mir** [mlflow/mlflow#2407]
When launching mlflow in  scala with 

`val mlflowContext = new MlflowContext()
`

I get 

> java.lang.IllegalStateException: 
> Default client requires MLFLOW_TRACKING_URI is set. Use fromTrackingUri() instead.

I also tried
```
val MLFLOW_TRACKING_URI = "http://localhost:5000" 
val mlflowContext = new MlflowContext(MLFLOW_TRACKING_URI)
```
but then the error becomes:

> org.mlflow_project.apachehttp.conn.HttpHostConnectException: Connect to localhost:5000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused

Is it a bug or am I doing something wrong?

**Comment by dbczumar** [comment]
@P-mir The `MlflowContext()` object requires that a tracking URI be passed as a constructor parameter *or* specified as an environment variable via `MLFLOW_TRACKING_URI`. It looks like your second attempt successfully constructed an `MlflowContext` object, but the MLflow client was unable to reach a tracking server at address `http://localhost:5000`; please confirm that a tracking server is running at that address and feel free to re-open this issue if you're still having trouble!

**Comment by HichemMaiza** [comment]
I faced the same problem using the Java API and QuickStartDriver Example. The solution to this specific use case is simple, but not well documented.  In a **local setup**, you first need to install mlflow python package and run the server.  
```python
pip install mlflow
mlflow serve # your server is runing by default on http://localhost:5000 
```
Now, you can create your client instance and launch your experiment  
```java
String MLFLOW_TRACKING_URI = "http://localhost:5000 
MlflowClient client = new MlflowClient(MLFLOW_TRACKING_URI ) 
```

It would be more practical if we had a maven plugin to automatically launch the server without the Python setup.

**Comment by rwoodard-prog** [comment]
One minor tweak to that most excellent answer:

> ```python
> pip install mlflow
> mlflow serve # your server is runing by default on http://localhost:5000 
> ```

It should be `mlflow server` (at least with `mlflow, version 1.27.0`).
