### ISSUE TITLE
[BUG] Model predict with json input fails if the dataframe has multi-index

### ISSUE THREAD

**Issue by Vysybyl** [mlflow/mlflow#2412]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: I can make an existing example script fail just by adding a couple of lines
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 19.3
- **MLflow installed from (source or binary)**: conda install mlflow
- **MLflow version (run ``mlflow --version``)**: 1.6.0
- **Python version**: 3.7.5
- **npm version, if running the dev UI**: none
- **Exact command to reproduce**: 
Just run the flower classifier example after changing it as explained below

### Describe the problem
Any json serialization of a multi-index dataframe ('split' or 'records') will raise

* ValueError: Number of features of the model must match the input. Model n_features is 169 and input n_features is 2 *

### Code to reproduce issue
Replace lines 36-37 of /examples/flower_classifier/score_images_rest.py with
`data = pd.DataFrame(data=[base64.encodebytes(read_image(x)) for x in filenames],
                        columns=["image"])
data.columns = pd.MultiIndex.from_tuples(('dummy', c) for c in data.columns)
data = data.to_json(orient="split")`
Then run the example.

### Other info / logs
This should both give a better error message and be documented.
You can fix it by flattening the multi-index before calling `to_json`

**Comment by tomasatdatabricks** [comment]
I don't think this is a bug in mlflow. The model that does not expect multi-indexed data frame.
