### ISSUE TITLE
[BUG] cloudpickle version specification

### ISSUE THREAD

**Issue by clyman23** [mlflow/mlflow#2429]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.15 and Linux
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.6.0
- **Python version**: 3.6.8 
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: mlflow.pyfunc.load_model(model_path)

### Describe the problem

MLflow does not call out a specific version of cloudpickle in its requirements. This creates a problem with the introduction of cloudpickle 1.3.0. Now, MLflow models that were created using cloudpickle 1.2.2 (the last version) produce an error when loaded if MLflow was installed by a user after cloudpickle upgraded to 1.3.0. 

### Code to reproduce issue

1. Create an MLflow Model using the latest version of mlflow (1.6.0) and cloudpickle 1.2.2
    * Alternatively, use an MLflow Model that was created with the latest version of mlflow (1.6.0) before 10 February 2020 (when cloudpickle published 1.3.0)
1. Upgrade cloudpickle to 1.3.0
1. Load the MLflow Model with `mlflow.pyfunc.load_model()`
    * Should produce warning similar to: `2020/02/13 19:19:57 WARNING mlflow.pyfunc: The version of CloudPickle that was used to save the model, `CloudPickle 1.2.2`, differs from the version of CloudPickle that is currently running, `CloudPickle 1.3.0`, and may be incompatible`
    * Should give error: 
```python
File "/usr/local/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 415, in _builtin_type
     return getattr(types, name)
 AttributeError: module 'types' has no attribute 'ClassType'
```

### Other info / logs

This error was found while running our CI pipeline on an MLflow Model that had been created using the latest version of mlflow (1.6.0) before cloudpickle was upgraded from 1.2.2 to 1.3.0. When cloudpickle upgraded to 1.3.0, our pipeline failed with the error described above. This is most likely because MLflow does not call out a specific version of cloudpickle in the requirements, so older MLflow Models are subject to issues from new releases of dependent packages.

**Comment by pradithya** [comment]
I tried to load model created using cloudpickle 1.3.0 but the same error is returned
```
File "/usr/local/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 415, in _builtin_type
     return getattr(types, name)
 AttributeError: module 'types' has no attribute 'ClassType'
```
The previous warning disappears though (expected):
```
WARNING mlflow.pyfunc: The version of CloudPickle that was used to save the model, CloudPickle 1.2.2, differs from the version of CloudPickle that is currently running, CloudPickle 1.3.0, and may be incompatible
```

**Comment by mzhang-code** [comment]
FYI, this looks like how pyspark code deals with it:

https://github.com/apache/spark/blob/068bdd44158d591e6fa48b105cf8d3fc33845695/python/pyspark/cloudpickle.py#L93

```
import types
types.ClassType = type
```

**Comment by dpasqualin** [comment]
Any workaround for this? Thank you.

**Comment by ogrisel** [comment]
cloudpickle is not meant to store long lived Python objects. As per cloudpickle's [README](https://github.com/cloudpipe/cloudpickle#cloudpickle):

> Using cloudpickle for long-term object storage is not supported and strongly discouraged.

Why not use regular Python pickle for long term object storage in MLflow?

**Comment by ogrisel** [comment]
FYI, we released cloudpickle 1.4.1 with a low maintenance compatibility fix that should remove this bug.

But keep in mind that cloudpickle is not meant to archive objects loaded in Python environment with different versions of the libraries (Python version, third party libraries and cloudpickle itself).

It is only meant to ship transient objects over the nodes of a compute cluster.

**Comment by andychow-db** [comment]
Created a PR to pin to 1.4.1. 
https://github.com/mlflow/mlflow/pull/2777

**Comment by juntai-zheng** [comment]
Thanks everyone for the input and fix! Will close this issue now.

**Comment by dbczumar** [comment]
> cloudpickle is not meant to store long lived Python objects. As per cloudpickle's [README](https://github.com/cloudpipe/cloudpickle#cloudpickle):
> 
> > Using cloudpickle for long-term object storage is not supported and strongly discouraged.
> 
> Why not use regular Python pickle for long term object storage in MLflow?

Hi @ogrisel , unfortunately, Python pickle doesn't provide support for deserializing objects defined in the `__main__` scope of a Python script or in an interactive notebook environment unless the user also packages and re-imports their `__main__` / notebook code along with the set of pickled objects. Capturing and shipping notebook code along with a serialized ML model is often cumbersome for developers, which is why we've adopted it for MLflow Models. Let me know if you have any insight into how to achieve this goal without depending on cloudpickle or how to make our usage of cloudpickle more robust.

**Comment by ogrisel** [comment]
You can depend on cloudpickle as long as your enforce the fact that the environment that loads the pickle has the same version number for Python, cloudpickle and all the dependencies of the pickled models. Basically I would advise to pip freeze or conda list whenever you pickle a model with cloudpickle to be able to rebuild the exact same environment on the prediction machines and provides tool to retrain the model whenever version upgrade is required (e.g. for security reasons).
