### ISSUE TITLE
[FR] Provide way to "unset" an experiment

### ISSUE THREAD

**Issue by kbrose** [mlflow/mlflow#2433]
## Describe the proposal

Provide some way to "unset" an experiment. This would perform the inverse operation of `mlflow.set_experiment`.

It would also be nice if a context manager was provided to automate the unsetting, e.g.

```python
import mlflow
with mlflow.experiment_context('my-exp'):  # or some better name...
    with mlflow.start_run('my-run'):
        # log to run my-run in experiment my-exp
        mlflow.log_metric('awesomeness', 100)
with mlflow.start_run('my-other-run'):
    # log to run my-other-run in the default experiment
    mlflow.log_param('global_state_usage', 'minimal')
```

### Motivation

To achieve this behavior right now, I'm doing some variation on

```python
mlflow.set_experiment('my-exp')
with mlflow.start_run('my-run'):
    mlflow.log_metric('awesomeness', 20)
mlflow.set_experiment('Default')
...
```

which is clunky and error prone.

My current workflow involves the same python interpreter session running multiple, different experiments, but logging some results to the default experiment so it acts as a kind of landing page for higher ups who want to see top level results instead of the details. 

(Specifically, the experiments define a set of runs of param grid searches, and the best run is reported to the default experiment.)

### Proposed Changes
Add a function `mlflow.unset_experiment()` which takes no inputs and does the inverse operation of `mlflow.set_experiment()`.

Also, possibly add a context manager to automatically handle the unsetting (which would have the same parameters as `mlflow.set_experiment()`).

**Comment by pogil** [comment]
Thanks for the input, @kbrose - logging to the "Default" experiment is intended to make it easy for people to get started using MLflow. I'm not sure I am convinced that reverting to the "Default" experiment is a typical behavior that we'd want to hard-code into the fluent client. Once our users are advanced enough to explicitly choose an experiment, we'd rather that become part of the normal process for where their runs go. 

I'd even go so far as to recommend that you choose to write to your best models from hyperparameter search to an experiment other than "Default", as you or another user may accidentally forget to set the experiment and log unrelated runs to "Default."
