### ISSUE TITLE
Feature request: support adding metrics, parameters and artefacts to completed runs

### ISSUE THREAD

**Issue by 5ke** [mlflow/mlflow#244]
Currently the API allows for tracking during the training and validation stage. In my use-case, promising experiments get selected for further testing. This evaluation stage can involve anything from simply running another script after completion, using proprietary software, and to doing extensive studies with human subjects. So even though the original experiment (by mlflow definition) was completed months ago, I would like to be able to add metrics and artefacts. Also, from experience, I know that I continuously find new hyper parameters worth tuning (even though I didn’t think so the first time around), and then it’s nice to add the default value to older experiments, so that they can be compared to newer experiments where that parameter has changed. 

Now I’ve noticed I can just place parameters, artefacts and metrics in their respective folders, and then the website shows them just fine  However, it’d be nice to have official support for this feature, so that I can rely upon it not to break sometime in the future.

**Comment by smurching** [comment]
Thanks for bringing up this point @5ke. It's actually currently possible to add new metrics/parameters to completed runs - if you pass a run ID to `mlflow.start_run()`, MLflow will resume the old run and calls to `log_metric`, `log_param` etc will write to the old run. However, it is a bit clunky in that the end time & termination status of the original run will be overwritten, and we have been thinking about refactoring the `start_run` API, which is currently overloaded to support both starting & resuming runs. I'd be curious to hear if the `start_run` workaround addresses your use case for the time being :)
