### ISSUE TITLE
[BUG] Azure backend crashes with bad error when there is more than 200 metrics

### ISSUE THREAD

**Issue by epa095** [mlflow/mlflow#2441]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **MLflow installed from (source or binary)**: From pip
- **MLflow version (run ``mlflow --version``)**: mlflow==1.5.0
- **Python version**: 3.7

### Describe the problem
We are using the `azureml-mlflow` version `1.0.85 `, and using azure ML workspace as the sever. When we are posting a batch-request with more than 200 metrics ml-flow crashes with a bad error:

```
  File "/usr/local/lib/python3.7/site-packages/gordo/reporters/mlflow.py", line 413, in log_machine
    mlflow_client.log_batch(run_id, **get_batch_kwargs(machine))
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 242, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 231, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics, params=params, tags=tags)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 240, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "/usr/local/lib/python3.7/site-packages/azureml/mlflow/_internal/store.py", line 88, in _call_endpoint
    return super(AzureMLRestStore, self)._call_endpoint(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 32, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 137, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 103, in verify_rest_response
    raise RestException(json.loads(response.text))
  File "/usr/local/lib/python3.7/site-packages/mlflow/exceptions.py", line 62, in __init__
    super(RestException, self).__init__(message, error_code=ErrorCode.Value(error_code))
  File "/usr/local/lib/python3.7/site-packages/google/protobuf/internal/enum_type_wrapper.py", line 71, in Value
    self._enum_type.name, name))
ValueError: Enum ErrorCode has no value defined for name 1
```
When inspecting the request manually we see that it contains this response:
```{'Error': {'Code': 'UserError', 'Message': 'No more than 200 metrics per batch.', 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None}, 'Correlation': {'operation': '0db01b139bfe9e43835dc67568e26c69', 'request': 'e7b03bcd644fbf23'}, 'Environment': 'northeurope', 'Location': 'northeurope', 'Time': '2020-02-17T08:07:59.4923142+00:00', 'error_code': 1}```

The problem is the error message we get in the stacktrace, which gives no hint about this being the issue.

**Comment by singankit** [comment]
The fix has been rolled out. The response to log batch request with metrics count more than 200 is as follows :
```
RestException: INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'No more than 200 metrics per batch. Request contains 210 metrics', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None}, 'Correlation': {'operation': '7bfc0b2e952a5140bf1556f43dea45f6', 'request': '39afda331e879544'}, 'Environment': 'northeurope', 'Location': 'northeurope', 'Time': '2020-09-15T22:52:33.9244889+00:00', 'ComponentName': 'run-history', 'error_code': 'INVALID_PARAMETER_VALUE'}
```

**Comment by singankit** [comment]
We are actively working on increasing the number of metrics that can be posted in a batch request.

**Comment by singankit** [comment]
@epa095 Can you please confirm and close this bug ?

**Comment by epa095** [comment]
> 
> 
> @epa095 Can you please confirm and close this bug ?

I don't have to opportunity to check anymore (new employment). Do you prefer that I close this issue then?
