### ISSUE TITLE
[FR] Improved UI performance on large datasets (plotly)

### ISSUE THREAD

**Issue by mjlbach** [mlflow/mlflow#2448]
## Describe the proposal
The current performance plotting datasets with > 10000 points is somewhat poor. Even only logging training metrics every 100 steps, a typical training run at 100k steps produces 1000 datapoints, comparing this across 10 runs yields slow plots in the UI.

### Motivation
Improving the performance makes it easier to compare experiments/leverage the nice UI.

### Proposed Changes
* See #2447 
* There's also been some work integrating datashaders into plotly, which scale even better than the webgl backend
* Another option would be a subsampling mechanism for plotting, decoupling the density of plots from the density of logging

**Comment by smurching** [comment]
@mjlbach thank you again for contributing this performance improvement! Marking the issue as closed 🎉
