### ISSUE TITLE
[FR] Mlflow serve - sending an image

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [mlflow/mlflow#2452]
Dear all,

It seems that the only input available to the model that is been server is a `pd.DataFrame`. I would like to send an image, or generally, an array. I have looked in the doc but I have found no example.

This is how I created the model:

```python
import torch
from PIL import Image
import torch.nn as nn
from torchvision.models import alexnet
from mlflow.pytorch import save_model

model = alexnet(True)
save_model(model, './alexnet')

```

Should I wrap my Pytorch model inside a function that accepts a `pd.DataFrame` with a column containing the image? In this case, what is the best way to encode the image?

Can you show me an example code? 

After solving this issue I will be more than happy to include an example in the doc and the repo :)

Thank you.

Cheers,

Francesco Saverio Zuppichini

**Comment by FrancescoSaverioZuppichini** [comment]
The problem is here

https://github.com/mlflow/mlflow/blob/60e5a2c05ac306b6c88dcb7e43f1b3f1adfe9a5d/mlflow/pytorch/__init__.py#L382

Would it be possible to make the code more usable by passing a function to pass the input? Something like 
```
save_model(...., input_parser = lambda x: torch.Tensor(x['x']))
```

Assuming I am sending an image to the server in this form {columns: ['x'], data:[[[...]]]])

This will also allow sending almost all types of vectors. Even if I think it should be allowed to just send one vector, I don't see why you should depend on pandas.

I can create a PR, let me know!

**Comment by vadakattu** [comment]
Not sure if you noticed already, but there's an [example](https://github.com/mlflow/mlflow/tree/master/examples/flower_classifier) of scoring images via spark & the rest api, as well as a pyfunc custom wrapper for Keras -- seems like your idea is to do the analogous for pytorch.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi, I will check them out :) Thanks
