### ISSUE TITLE
Python API is missing methods from REST API

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#246]
A number of REST API methods are not implemented in the Python API.
- get_experiment - https://mlflow.org/docs/latest/rest_api.html#get-experiment
- get_metrics - https://mlflow.org/docs/latest/rest_api.html#get-metric
- get_metrics_history - https://mlflow.org/docs/latest/rest_api.html#get-metrics-history
- search - https://mlflow.org/docs/latest/rest_api.html#search-runs

Documentation links:
- Index of Python API methods - https://mlflow.org/docs/latest/genindex.html
- REST API - https://mlflow.org/docs/latest/rest_api.html

**Comment by parkerzf** [comment]
Any update on this issue? Thanks

**Comment by max-allen-db** [comment]
I think these are all implemented now. Closing issue.
