### ISSUE TITLE
[FR] MLflow Model Deployment in SQL Server

### ISSUE THREAD

**Issue by avflor** [mlflow/mlflow#2469]
SQL Server provides ML functionality through SQL Server Machine Learning Services that allow running Python scripts on relational data. This includes feature engineering, model training and model deployment within the database.

Deploying models through MLflow to SQL Server is important for users that might train their models either outside SQL Server (e.g., using Spark in Microsoft’s Big Data Cluster) or in SQL Server but want to eventually score the model in a different SQL Server instance for data privacy/governance reasons as a large fraction of production data is still in the RDBMS. One such scenario would be training the model in the Big Data Cluster on-prem, but eventually deploying the model on SQL Edge.

I have  created a [document ](https://docs.google.com/document/d/1lJbxzIngLO5hOi0hGzlHljPdnc395OJTLT9T2PqmIUs/edit?usp=sharing) that provides a high-level description on how to implement the deploy operation in SQL Server. The plan is to proceed in two steps:

1) Implement a deploy operation through the following API:
`mlflow database deploy --db_uri --flavor --table-name --column-name`

We already have a prototype for the ONNX flavors (See document for more details).
In this first part, we will simply download the model from the artifact store, make sure it is supported by SQL Server, and store it in the table/column that the user provided as a BLOB.

2) In the second step, we want to additionally automatically generate a SQL query (or stored procedure) that can be used to score the model in SQL Server. Please see a high-level description of this part on the document. We'd like to note that this part is not fully-fledged yet as we are in discussions with the SQL Server team on what is the best way to do this in the database. Once we have more clearance on some of the implementation issues, I will update the document with more concrete information.

**Comment by andychow-db** [comment]
This sounds very cool. Thank you for submitting this proposal. @tomasatdatabricks check this out

**Comment by tomasatdatabricks** [comment]
Hi @avflor, thanks fro submitting. I think this would fit perfectly into our new [deployment plugin system](https://www.mlflow.org/docs/latest/cli.html#mlflow-deployments). Can you check that out and let us know if there is anything missing for your use case?

**Comment by avflor** [comment]
Thanks @tomasatdatabricks  for the pointer. I was waiting for this plugin! Will check it out and let you know if it works.

**Comment by safrazRampersaud** [comment]
Following @avflor ... this looks like a solution I have been looking for. Any updates would be great!

**Comment by dbczumar** [comment]
This functionality has been implemented and is available here: https://mlflow.org/docs/latest/plugins.html#sql-server-plugin / https://pypi.org/project/mlflow-dbstore/. Accordingly, I'm going to go ahead and close this issue.
