### ISSUE TITLE
Expand Artifact Repository Interface to grant access to extra Storage Client API parameters

### ISSUE THREAD

**Issue by InspiredIdealist** [mlflow/mlflow#247]
### Feature Request
Expand the ArtifactRepository interface to have a `**kw_args` parameter (which would always be optional) which is passed into the cloud / local storage mechanism (i.e. boto3's S3 client). This would then allow consumers to access the extra options available via the client API of choice (AWS, Azure, Google Cloud or Local Storage).

### Sample Use Case
There is currently no support for the extra arguments for encryption and other auxillary s3 options (perhaps adding object tagging metadata as well?).

While it is possible to have S3 "default" a security option in a specific bucket, there are plenty of use cases where that isn't possible (i.e. Bring-Your-Own-Key scenarios).

Passing the `**kw_args` parameter down the chain of method invocations would allow such behavior to be accessed by consumers of the MLFlow API.

**Comment by mateiz** [comment]
One challenge I see with this is that user code might need to pass these `kw_args`, but one of the main goals of MLflow projects is to have your code run the same way everywhere (say on your laptop or on EC2), so it would be bad to have to change your project code for each setting. Is that right or am I missing something? In the extreme case, imagine you wanted to `mlflow run` a project that someone else wrote that's on GitHub, where you don't even want to change the code, but you still want it to access S3 using your preferred auth process.

To enable this, I'd prefer if all these options could be set in environment variables or config files outside the MLflow project and picked up that way. In that case we could have these `kw_args` in the internal API or we could just have each artifact store pick up its own config in its own way. For example, for the S3 store, we could add some extension point that lets it pick up a key provider Python objects; then users would set some environment variable, say MLFLOW_S3_KEY_PROVIDER=mycode.mypythonmodule, and it would call into that. You could then use it without modifying the MLflow clients calling log_artifact.

**Comment by InspiredIdealist** [comment]
That's a really good point. I like the idea of using an IoC pattern here.

**Comment by InspiredIdealist** [comment]
What if the args were persisted in one of the meta.yaml files? Perhaps the 'Experiment' one? This could be read by the server at runtime, and passed to the client that wants to access a prior run, or create a new run in that experiment.

**Comment by zmhassan** [comment]
@mateiz @hamroune  I'm interested in using the `endpoint_url` as well to be able to store our models internally in ceph s3. In the meantime I'm overwriting the S3ArtifactRepository.py file to pickup an environment variable S3_ENDPOINT and pass it into boto3. Thoughts?

**Comment by hamroune** [comment]
@mateiz @zmhassan is it possible to make a PR?

**Comment by mateiz** [comment]
@hamroune adding an environment variable for the endpoint sounds great, but can you do a bit of research to see what other libraries are calling it? Ideally, we'd call it the same thing. If there's no standard name, then we should prefix it with MLFLOW_, for example MLFLOW_S3_ENDPOINT.

**Comment by zmhassan** [comment]
@mateiz You can use the same boto3 library just include endpoint in the constructor. I send details to mani via email of how to connect and test it works. Same library different parameters

**Comment by zmhassan** [comment]
session = boto3.session.Session()
session.client( service_name='s3',
                               endpoint_url='http://http://192.168.0.10:8000')

We want to be able to add an environment variable $MLFLOW_S3_ENDPOINT

That way we can store models in s3

**Comment by hamroune** [comment]
I created a couple of days ago an issue https://github.com/boto/botocore/issues/1526 unfortunely there is no way to specify endpoint through config, for now, so I create  MLFLOW_S3_ENDPOINT_URL env variable if present it override the Amazon endpoint.
I make a PR for review

**Comment by tomasatdatabricks** [comment]
It looks like this issue has not been active for a while and I see that we did add MLFLOW_S3_ENDPOINT_URL variable so I am assuming the issue has been solved. Closing it for now.
