### ISSUE TITLE
[BUG] Failed to save to csv with pandas after importing mlflow

### ISSUE THREAD

**Issue by dehiker** [mlflow/mlflow#2478]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac OS Catalina, 10.15.3
- **MLflow installed from (source or binary)**: binary (with pip)
- **MLflow version (run ``mlflow --version``)**: version 1.6.0
- **Python version**: Python 3.7.4
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Failed to save to csv with pandas after importing mlflow.

### Code to reproduce issue
```
>>> import pandas as pd
>>> import mlflow
>>>
>>> df = pd.DataFrame({'a': [1, 3,], 'b': [3, 4]})
>>> df.to_csv('t2')
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database:
[libprotobuf FATAL google/protobuf/descriptor.cc:1370] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
[1]    8615 abort      python
```
### Other info / logs
NA

**Comment by pogil** [comment]
@dehiker, are you still facing this issue? I wasn't able to reproduce this issue using mlflow 1.7.2, python 3.7.1, and mac 10.14.6. A quick search suggests that it might be related to Tensorflow and linkage with protobuf. Did you build your own version of Tensorflow?
