### ISSUE TITLE
Duplicate methods in MLflow Python API packages mlflow and mlflow.tracking

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#248]
The following methods (may be others too) exist in both mlflow and mlflow.tracking Python packages:
- log_param  
- log_metric  
- log_artifact 
- log_artifacts
- etc. ...

This is confusing - are these the same methods or are they subtly different?. Per Occam's razor, we should have one canonical API method.

**Comment by smurching** [comment]
Thanks @amesar, they are the same methods (and are intended to be the same methods). Agreed that it's somewhat confusing to have the same public API exposed in two modules, one way to address the issue would be to make the APIs in `mlflow.tracking` private and expose only `mlflow.log_param` etc (though this would be a pretty substantial breaking change).  @mateiz do you have any thoughts on this?

**Comment by aarondav** [comment]
We made `mlflow`'s methods canonical, but exposed the lower-level interface (i.e., applying these methods to historical runs) in the MLflow Tracking Service API (e..g, `mlflow.tracking.get_service()`). We could consider renaming the ones in the Service API, but currently think that hiding them in the `get_service()` object should help clarify that users should prefer `mlflow.log_param` unless they are doing something a bit more advanced.
