### ISSUE TITLE
[BUG] Deploy to SageMaker - (IllegalLocationConstraintException) when calling the CreateBucket operation

### ISSUE THREAD

**Issue by liorshk** [mlflow/mlflow#2491]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.6.0
- **Python version**: Python 3.6.8
- **Exact command to reproduce**: mlflow.sagemaker.deploy

### Describe the problem
When trying to deploy a model using `mlflow.sagemaker.deploy`, and `bucket=None` and a region: `us-west-2`, it goes to the function `_get_default_s3_bucket` and tries to create a bucket `s3.create_bucket`, but the problem is that `s3` object was initialized by default to `us-west-1` so it throws the error `IllegalLocationConstraintException`.

The solution should be to initialize the s3 session with the `region_name`

### Code to reproduce issue
`    mfs.deploy(app_name = app_name,
            model_uri = model_uri,
            region_name = "us-west-2",
            mode = "replace", # like that you can overwrite
            execution_role_arn = arn,
            image_url = image_url)`

### Other info / logs
`botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The us-west-2 location constraint is incompatible for the region specific endpoint this request was sent to.`

**Comment by dbczumar** [comment]
In order to address this issue, the bucket name and region name must both be specified.
