### ISSUE TITLE
[FR] Enable upload and download of artifacts via MLflow server

### ISSUE THREAD

**Issue by BigNerd** [mlflow/mlflow#2512]
## Proposal
Currently, when using an MLflow server in combination with an AWS S3 bucket as artifact storage, clients are required to be able to directly upload and download artifacts to S3. As a new feature, please enable upload and download of artifacts via MLflow server (HTTP interface) in the same way as parameters, tags and metrics can be uploaded and downloaded via the MLflow server.

### Motivation
This feature will remove the requirement that clients need to setup a security solution for authentication and authorization of direct access to an S3 bucket. Also, users of MLflow server with other types of backend storage such server-side file system will benefit in the same way.

**Comment by dbczumar** [comment]
This has (finally) been implemented in MLflow 1.24.0. You can check it out the updated docs here - https://mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers.
