### ISSUE TITLE
Drop Python 2 support from MLflow in MLflow 1.8.0

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#2522]
## Proposal
The upcoming MLflow release (1.7.0, to be published in the next week), will ship with a deprecation warning indicating that Python 2 support will be dropped in a future release, in light of Python 2 reaching end-of-life in January 2020.

Given that Python 2 is EOL, we should drop Python 2 support in MLflow in an upcoming release, e.g. the MLflow 1.8.0 release, with an expected release date around end of March 2020.

This would bring a number of benefits, e.g. significantly reducing MLflow's maintenance burden (no need to write code / tests / manage test environments across increasingly divergent Python 2 & Python 3 lines), and speeding up CI times.

Things to note:
* Python 2 workflows that depend on the "latest" MLflow version will still work (e.g. workflows that depend on the mlflow PyPI library but don't specify a version). These workflows will simply use MLflow 1.7.0. Similarly, Python 2 workflows depending on MLflow versions < 1.7.0 will still work.
* Python 2 users will not have access to new MLflow features & most bug fixes. This aligns with the strategy of other open-source libraries, as ML libraries like [Numpy](https://numpy.org/neps/nep-0029-deprecation_policy.html), [Pandas](http://l/20540), [Scikit-learn](https://scikit-hep.org/supported-python-versions), and [TensorFlow](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0) have already dropped support.
* We may, in exceptional cases, consider backporting critical security fixes to the 1.7 branch and making 1.7.x patch releases for Python 2 users. We don't expect to regularly publish 1.7.x MLflow releases - Python itself has [already stopped accepting security fixes](https://www.python.org/dev/peps/pep-0373/#maintenance-releases) (as of Jan 1, 2020) for Python 2.

## Feedback Welcome

Please reply to this issue with any questions or thoughts - we're open to delaying dropping Python 2 support, but would strongly prefer to stick to the end-of-March timeline if at all possible.

Barring major objections, we'll go ahead & publish an official announcement the week of March 8 - thank you!

**Comment by smurching** [comment]
Update on this, looks like we're cleared to move forward with dropping Python 2 support (was unable to find any strong pushback against it), will publish a formal announcement on mlflow.org and the users mailing list. Thanks all!

**Comment by PhilipMay** [comment]
I do not care about python 2. Dropping it is very welcome.

**Comment by keigohtr** [comment]
Can anyone review and retest this PR? -> https://github.com/mlflow/mlflow/pull/2538

**Comment by smurching** [comment]
Closed in #2534
