### ISSUE TITLE
problem using FTP artifact storage

### ISSUE THREAD

**Issue by redballon345** [mlflow/mlflow#2526]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.6.0
- **Python version**: 3.8.1
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
I am using ftp artifact storage. Storing artifacts during runs works, but if I select an artifact in the mlflow UI the error "something went wrong" without any further information is displayed. 
Also the console output from mlflow ui does not contain any further information.
I had a look on similar issues in this forum, but the soultions proposed there did not work for me.  I would be very grateful for any suggestions as to what might be wrong here. Also, how can I get to more verbose log/debug information from the UI?

**Comment by smurching** [comment]
@redballon345 what browser are you using to view the UI? If you open your browser's developer tools, is there an error that shows up in the console? For example with Chrome, you can press `cmd + option + j` (Mac) or `ctrl + shift + j` (Windows) as described [here](https://developers.google.com/web/tools/chrome-devtools/console/log#setup) to open the browser console, and then view browser-side errors that are occurring. 

Getting any error messages / stacktraces that appear in the browser console would be super helpful in diagnosing this issue - thanks! 

Alternatively, if you can find a simple, minimal reproducible example for this type of failure, feel free to post a description & we can reproduce/investigate the issue.

**Comment by smurching** [comment]
Closing for now, but @redballon345 please feel free to reopen if you're still hitting this issue/have a reproducible example!
