### ISSUE TITLE
[BUG] Large images not showing correctly in artifacts section

### ISSUE THREAD

**Issue by lopezco** [mlflow/mlflow#2535]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian (Docker from python:3.7)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: Tested on 1.6.0 and 1.7.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: none

### Describe the problem
When logging large images (height-wise) the MLflow **server** UI cannot resize the Plotly Graph correctly in the Artifacts section (see the image below)

![image](https://user-images.githubusercontent.com/6637618/75756738-6f482080-5d31-11ea-87fd-c2426293f7ca.png)

This image was automatically generated by `mlflow.lightgbm.autolog()` when the model has a lot of variables.

**Expected looks:**
Larger image with scrolling bar.
![image](https://user-images.githubusercontent.com/6637618/75759388-c3ed9a80-5d35-11ea-80a1-64114d6af04d.png)

### Code to reproduce issue
Log any big image as artifact. For comparison, you can find the file `mlflow.lightgbm.autolog()` produced [here](https://user-images.githubusercontent.com/6637618/75758468-77ee2600-5d34-11ea-8b2d-46b9d43813bb.png).

```python
import mlflow
with mlflow.start_run():
    mlflow.log_artifact(big_image)
```

**Comment by harupy** [comment]
Like this?

![scrollable](https://user-images.githubusercontent.com/17039389/75769626-db567300-5d89-11ea-85c0-d41946386f08.gif)

**Comment by harupy** [comment]
We should maybe make the image viewer scrollable when the image height (or width) is larger than a certain threshold.

**Comment by harupy** [comment]
@lopezco 
This might not be related to this issue, but would you want an option to limit the number of features to plot for `mlflow.lightgbm.autolog()`?

**Comment by lopezco** [comment]
@harupy 
Funny you asked. I way planning to open an issue about this subject.

I think this option would be very useful. However, I think the matplotlib layout needs some work if we want to show a lot of variables.
Have you considered also exporting the graph as a Plotly graph using json? Maybe it would be easier to display.

**Comment by harupy** [comment]
> it needs some work if we want to show a lot of variables (labels overlap with each other).
Yes, just increasing the figure height doesn't seem to work.

> Have you considered also exporting the graph as a Plotly graph using json? Maybe it would be easier to display.
Yes, I actually have implemented before.
