### ISSUE TITLE
[FR] compressing models stored by log_model (for example mlflow.sklearn.log_model API)

### ISSUE THREAD

**Issue by mowrang** [mlflow/mlflow#2545]
## Describe the proposal
Can you please add compression to log_model? 

### Motivation
The motivation is that the files take less space on storage system. 
My immediate usage is for Azure blob storage.

### Proposed Changes
you would need to add a type to SUPPORTED_SERIALIZATION_FORMATS for example for sklearn it would a new type added to mlflow.sklearn.SUPPORTED_SERIALIZATION_FORMATS in addition to pickle and cloudpickel

**Comment by mathiasottenbreit** [comment]
It would be good if you reopened and implemented this. Some ML algorithms create large pickle files that can be substantially compressed.

**Comment by leo83** [comment]
Agree. Loading some artefacts leads to problems like 
```
UnpicklingError: pickle data was truncated
```
