### ISSUE TITLE
[FR] Format output in UI to reasonable number of s. f.

### ISSUE THREAD

**Issue by Rizhiy** [mlflow/mlflow#2548]
Currently, the UI prints the full floating value for metrics. This is excessive, takes up a lot of space and not necessary.

I would suggest formatting all metrics to three significant figures.

**Comment by dbczumar** [comment]
I've filed https://github.com/mlflow/mlflow/pull/2398 to address this; will get it merged shortly.

**Comment by aarondav** [comment]
Should be fixed!
