### ISSUE TITLE
[FR] UI: separate selection checkbox into it's own column.

### ISSUE THREAD

**Issue by Rizhiy** [mlflow/mlflow#2549]
Currently, to select subset of runs the 'Date' field has to be active, since selection is tied to that.

IMO, when the experiment is not important and I always try to hide it.

It would be useful if selection column for runs was always visible.

**Comment by harupy** [comment]
I'm actually working on this and hopefully will open a PR next week.

**Comment by harupy** [comment]
@Rizhiy I opened a PR #2559.
