### ISSUE TITLE
[FR] UI: Keep column sizes when sorting

### ISSUE THREAD

**Issue by Rizhiy** [mlflow/mlflow#2550]
Currently, when I try to sort any column, all columns are expanded to default width. This is annoying, since most of the time default width is widely off what I need.

It would be great if the UI remembered the layout selected by user and kept it when changing displayed runs.

**Comment by juntai-zheng** [comment]
Thanks for pointing this out! @Zangr do you have input on how we can get this to work?

**Comment by Zangr** [comment]
@Rizhiy thanks for filing this FR. We are aware of this issue and have a plan to implement column drag/drop and memorized column position width for the runs table. Here is the FR https://github.com/mlflow/mlflow/issues/3101
