### ISSUE TITLE
[FR] Publish separate mlflow-client package that doesn't contain server-only dependencies

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#2557]
## Describe the proposal
Alongside the main `mlflow` PyPI package, we should consider publishing an `mlflow-client` package that excludes some of the heavier dependencies (sqlalchemy, alembic, flask, gunicorn) needed to run the MLflow server.

### Motivation
Many use cases do not actually require the MLflow server's dependencies - for example:
* If running a production ML training job, it becomes harder to introduce MLflow when there are unneeded/unused server dependencies - these increase the likelihood that MLflow will muck with the environment of your production job and change its behavior
* If building a standard data-science docker image to share with your data science team, it becomes more complex to reason about the runtime environment if unnecessary server dependencies are pulled in. 

### Proposed Changes
We should additionally publish a standalone mlflow-client package containing only the Python client logic (i.e. for the tracking, projects, models, and model registry components). In particular, MLflow currently has the following Python requirements:

```
    install_requires=[
        'alembic',
        'click>=7.0',
        'cloudpickle',
        'databricks-cli>=0.8.7',
        'requests>=2.17.3',
        'six>=1.10.0',
        'waitress; platform_system == "Windows"',
        'gunicorn; platform_system != "Windows"',
        'Flask',
        'numpy',
        'pandas',
        'python-dateutil',
        'protobuf>=3.6.0',
        'gitpython>=2.1.0',
        'pyyaml',
        'querystring_parser',
        'simplejson',
        'docker>=4.0.0',
        'entrypoints',
        'sqlparse',
        'sqlalchemy',
        'gorilla',
        'prometheus-flask-exporter',
    ],
```

Which contains the following, seemingly-unnecessary-for-client-only operation libraries:
* `alembic`: used to run database migrations, currently invoked during initialization of the SqlAlchemyStore
* `sqlalchemy`: used to perform database operations in SqlAlchemyStore
* `waitress`, `gunicorn`, `flask`: used to run the open-source REST API server and serve MLflow models as part of `mlflow models serve`. Also used when building docker images for `mlflow sagemaker` and `mlflow azureml` CLIs?
* `prometheus-flask-exporter`: used to expose service metrics to Prometheus when running the OSS server

If we were to remove these libraries, we'd end up with a client package dependent on:
```
    install_requires=[
        'click>=7.0',
        'cloudpickle',
        'databricks-cli>=0.8.7',
        'requests>=2.17.3',
        'six>=1.10.0',
        'numpy',
        'pandas',
        'python-dateutil',
        'protobuf>=3.6.0',
        'gitpython>=2.1.0',
        'pyyaml',
        'querystring_parser',
        'simplejson',
        'docker>=4.0.0',
        'entrypoints',
        'sqlparse',
        'sqlalchemy',
        'gorilla',
    ],
```

Which would be significantly smaller (TODO how much) & have a smaller transitive closure of dependencies.

### What APIs will be available in the mlflow-client package? How will we document them?
Say we publish an `mlflow-client` package with a reduced dependency set, but that this package contains all the APIs supported by the main `mlflow` package. This may lead to confusing behavior where users attempt to use APIs documented in the main package, only to find that they don't work (e.g. `mlflow models serve` will not work without the `gunicorn` server dependency, for example).

One simple approach could be to simply expose the same APIs (so that we don't need to separately document the two packages), but attempt to show informative error messages that clearly indicate to mlflow-client users why certain functionality fails or is otherwise unavailable.

The main APIs this is relevant for are (TODO flesh out this list):
* `mlflow models serve` & `mlflow models predict`?
* TODO: `mlflow sagemaker ...` and `mlflow azureml ...` CLIs?
* 

My hope is that this audit will show that the number of affected APIs is relatively small

**Comment by smurching** [comment]
Thinking about this some more, some more off-the-cuff thoughts:
* Tracking & model registry: given that we want to drop the gunicorn & SQLalchemy dependencies, seems reasonable for the client to contain only FileStore and RestStore implementations of the tracking & model registry AbstractStores (with ``mlflow-client``, you can log to a remote server or your local filesystem)
* Projects: The client should be capable of running projects
* Flavors: Client should support autologging, `save_model`, `log_model`, `load_model` APIs for flavors, as well as the ``mlflow.pyfunc`` APIs for scoring models on pandas and Spark DataFrames
* Models: The [FlavorBackend interface](https://github.com/mlflow/mlflow/blob/HEAD/mlflow/models/flavor_backend.py#L4), defining the methods underlying the `mlflow models serve/predict/build-docker` CLIs, should not be part of the client, as it requires a `gunicorn` dependency
* Model deployment APIs could be part of the client, as they don't add additional dependencies (users are responsible for installing boto, azureml, etc)
* CLI: tricky to split. We actually rely on the CLI to log artifacts from the Java and R clients, and `mlflow.projects.run(..., synchronous=False)` invokes `mlflow run` in a subprocess (also currently depends on the CLI). These CLI dependencies aren't fundamental, but would take quite a bit of work to remove (would require reimplementing available Python artifact repos in Java/R etc). Another extreme is to include the full CLI, where some commands (e.g. ``mlflow server``) would just fail if you don't have the appropriate dependencies installed

I think reasonable next steps on this would be to:
* Investigate what other packages do - is it reasonable to include APIs where users are required to install dependencies in order to use those APIs (as we currently do flavors, e.g. ``mlflow.tensorflow`` APIs), or would this lead to too much user confusion / should the ``mlflow-client`` package not contain such APIs?
* Write out the long-term packaging structure we'd like MLflow to have (an `mlflow-client` package that `mlflow` depends on, splitting out additional packages from `mlflow` as appropriate, where all of the packages are co-versioned and released together?)
* Investigate options (given what Python packaging supports) to define the `mlflow-client` package. Ideally, we can keep the ``mlflow-client`` code within the main MLflow repo for ease of development

**Comment by dbczumar** [comment]
[mlflow-skinny](https://pypi.org/project/mlflow-skinny/) is now available!
