### ISSUE TITLE
[BUG]  Failed to import Git, so Git SHA is not available

### ISSUE THREAD

**Issue by lucmos** [mlflow/mlflow#2564]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Manjaro
- **MLflow installed from (source or binary)**: poetry (binary)
- **MLflow version (run ``mlflow --version``)**: 1.7.0
- **Python version**: 3.7.5

### Describe the problem
The new update 1.7.0 breaks the git SHA retrieval with the following warning:

```
2020/03/09 11:28:00 WARNING mlflow.tracking.context.git_context: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: 'gitdb' could not be found in your PYTHONPATH
```

I tried to install `gitdb` as suggested in the error, but it does not  change the behaviour.
With MLFlow 1.6.0 everything worked.

**Comment by kinoute** [comment]
Hi, since you closed the issue, did you find a solution? I have the same problem. Thanks

**Comment by lucmos** [comment]
Hello,

I closed the issue because I wasn't able to reproduce the problem: downgrading to MLFlow 1.6.0 did not solve the problem.
Now it is working again, but I don't know what changed in my configuration.

**Comment by esskay0000** [comment]
same problem. any tips?

**Comment by esalvucci** [comment]
@esskay0000 probably I'm late but... I had the same problem running mlflow 1.13.1 in a docker container.
I solved the issue by installing git through the Dockerfile
`RUN apt-get update && get upgrade -y && get install -y git`

I really don't understand why mlfow does need git installed!

**Comment by avenatti** [comment]
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y git

**Comment by dingobar** [comment]
Hi, why does mlflow need git installed?

**Comment by ehddnr301** [comment]
The git commit hash value is also logged in the mlflow run, so it seems that git is needed
This is a problem that I encountered when I was logging to Mllfow while inside the docker

**Comment by poult-lab** [comment]
> sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y git

these command fixed my issues. 
thank you so much, My system is ubuntu22.04
