### ISSUE TITLE
[BUG] list_registered_models always returns empty list in mlflow v1.7.0

### ISSUE THREAD

**Issue by vbaretskyTA** [mlflow/mlflow#2572]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14.6
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.7.0
- **Python version**: 3.7.1
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: client = mlflow.tracking.MlflowClient(tracking_uri=<mlflow_tracking_uri>)
client.list_registered_models()

### Describe the problem
We have an MLFlow tracking server running mlflow v1.5.0 backed by postgres and hdfs. It includes a model registry which has several registered models. When calling list_registered_models on an MlflowClient in the python API v1.7.0, it returns an empty list. If I use mlflow v1.6.0 instead, it returns a list of RegisteredModelDetailed objects matching those in the registry UI as expected.

### Code to reproduce issue
client = mlflow.tracking.MlflowClient(tracking_uri=<mlflow_tracking_uri>)
client.list_registered_models()

**Comment by ravilkashyap** [comment]
Try giving registry_uri as a paramter to mlflowclient

**Comment by vbaretskyTA** [comment]
If I pass registry_uri (which has the same value as tracking_uri) I see the same behavior - it works as expected in 1.6.0 and it returns an empty list in 1.7.0

**Comment by smurching** [comment]
@vbaretskyTA sorry for the slow response - the MLflow 1.7.0 release contained breaking changes to model registry APIs ([see changelog](https://github.com/mlflow/mlflow/blob/master/CHANGELOG.rst#170-2020-03-02) for more details). Would you be able to try upgrading your server to run with MLflow 1.7.0? I'd expect that to resolve the issue.

**Comment by vbaretskyTA** [comment]
You're right upgrading the server to MLflow 1.7 fixed the issue. Thank you!
