### ISSUE TITLE
[FR] Add possibility to use client cert. with tracking api

### ISSUE THREAD

**Issue by PhilipMay** [mlflow/mlflow#2574]
I would like to use client certs with tracking API.
Could you add that?

You basically have to add the possibility to add a filename to the cert param of the `requests.request` function. See here: https://requests.readthedocs.io/en/master/api/

Here are the 2 calls that need to be extended:
- https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L51
- https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L62

**Comment by dbczumar** [comment]
@PhilipMay both https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L51 and https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L62 already accept a `**kwargs` parameter that can be used to forward cert arguments to the `requests.request` function. However, these are internal methods meant to be called by the `RestStore` during MLflow Tracking operations; users are not expected to call these directly.

I think we might want to add a cert path field to the `MlflowHostCreds` abstraction (https://github.com/mlflow/mlflow/blob/74465b29c396e9c442031f7b0d3720f1312442bc/mlflow/utils/rest_utils.py#L143) instead, along with an environment variable that can be used to specify a cert path (similar to the variables defined here: https://github.com/mlflow/mlflow/blob/476dcd63a50d739ca8f4272bfd0215880419ce30/mlflow/tracking/_tracking_service/utils.py#L20-L23.

cc @aarondav for input here.

**Comment by dbczumar** [comment]
@PhilipMay Would you be willing to contribute this type of enhancement?

**Comment by dbczumar** [comment]
@PhilipMay Just checking in again! Any thoughts here?

**Comment by PhilipMay** [comment]
I will have a look into it. 
Maybe I will just add "client cert. with tracking api" with the possibility to set an env-variable.

**Comment by PhilipMay** [comment]
Well - I did some code changes but I am blocked by this bug at the moment: https://github.com/mlflow/mlflow/issues/2812

**Comment by dbczumar** [comment]
Hi @PhilipMay , I responded to #2812. Please let me know if this unblocks you!

**Comment by PhilipMay** [comment]
> Hi @PhilipMay , I responded to #2812. Please let me know if this unblocks you!

I found a workaround.

**Comment by PhilipMay** [comment]
Started a PR: #2843

**Comment by PhilipMay** [comment]
PR is merged. Closing this.
