### ISSUE TITLE
[FR] Why can't the backend store uri be an s3 location?

### ISSUE THREAD

**Issue by ksanjeevan** [mlflow/mlflow#2585]
## Describe the proposal
Allow for `backend-store-uri` to be an s3 location. That way parameters/metrics are in the same location as the artifacts (same as when working in local mode).

### Motivation
Makes sense to have the params/metrics in a SQL db to be able to query and such, but since we can also interact with them through the `mlflow ui`, it would be more convenient to allow it all to point to a single s3 location and have `mlflow server` run only against it.

### Proposed Changes
Allow for `backend-store-uri` to be an s3 location, essentially having the same as local mode but instead of a single local file path have it be s3.

**Comment by tomasatdatabricks** [comment]
Hi @ksanjeevan , this is an interesting idea, thanks for posting! Unfortunately, this would require a new type of tracking store backend and we are not planning to add a new type of store at this time nor can we support it at this time.

**Comment by oren-hecht** [comment]
Any chance this can considered again as an option?

Most people have an S3 bucket already as they need it for artifact storage. Why make them handle additional DB infrastructure, if there isn't a very important reason?

I'm sure this can be a really useful feature for many!
(also, this was marked closed as `completed` but it should have been marked as `not-planned`, no?)
