### ISSUE TITLE
[FR] Line smoothing based on moving average rather than on splines

### ISSUE THREAD

**Issue by Valentyn1997** [mlflow/mlflow#2596]
The current implementation (based on Catmull-Rom splines) doesn't actually show the overall trend. I think it is better to use some variant of moving average smoothing (https://en.wikipedia.org/wiki/Moving_average). 

E.g. here splines just make interpolation:
![image](https://user-images.githubusercontent.com/23198776/76858164-26c35380-6857-11ea-9d97-2a918d22cb2a.png)
![image](https://user-images.githubusercontent.com/23198776/76858347-802b8280-6857-11ea-96d1-bc5c4338bf72.png)

P.S. Tensorboard uses namely exponential moving average.

**Comment by dbczumar** [comment]
@Valentyn1997 Absolutely. This is something that we'd love to do. Would you be willing to work on / file a PR for this?

**Comment by Valentyn1997** [comment]
@dbczumar - yes, I could work on this 😊
