### ISSUE TITLE
[BUG] Cannot log artifact to MinIO with custom region name

### ISSUE THREAD

**Issue by 9dogs** [mlflow/mlflow#2599]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 10.2 (python:3.7.5-slim-buster Docker image)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.7.1
- **Python version**: 3.7.5
- **npm version, if running the dev UI**: -
- **Exact command to reproduce**: see below

### Describe the problem
When I try to use `log_artifact` with on-premise MinIO as a storage by setting `MLFLOW_S3_ENDPOINT_URL` env variable, I got an exception:
`botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://s3.k8s00-local.amazonaws.com/mlflow-artifacts/0/b967297521b54050a81d65b498a653fd/artifacts/test_folder/test_file.txt"`

I suspect it has to do with **region name** MinIO configuration. Currently there is no way to pass region name to `S3ArtifactRepository` class.

May be we can provide an env variable alongside with `MLFLOW_S3_ENDPOINT_URL`, say `MLFLOW_S3_REGION_NAME`?

### Code to reproduce issue
MWE got too big, please, see https://github.com/9dogs/mlflow-minio-test

### Other info / logs
[trace.txt](https://github.com/mlflow/mlflow/files/4346088/trace.txt)

**Comment by tomasatdatabricks** [comment]
Hi @9dogs, thanks for posting!

Can you verify that the missing region is the problem by creating boto client yourself and connecting to you storage?

**Comment by 9dogs** [comment]
I forgot to mention it, but yes, I tried. Surprisingly for me, `list_buckets()` command works fine but any write operation gives the same exception:
`botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://s3.k8s00-local.amazonaws.com/mlflow-artifacts`

You can try code below in "experiment" container:
`docker-compose run --entrypoint python experiment`

```python
import boto3

# Without region name
client = boto3.client('s3', endpoint_url='http://minio:9000')
client.list_buckets()  # works
client.create_bucket('mlflow-artifacts')  # fails
client.list_objects(Bucket='mlflow-artifacts')  # fails
client.upload_file('/app/Dockerfile', 'mlflow-artifacts', 'Dockerfile')  # fails
# Without region name
s3 = boto3.resource('s3', endpoint_url='http://minio:9000')
files = list(s3.Bucket('mlflow_artifacts').objects.all())  # fails
s3.Bucket('mlflow_artifacts').put_object(Key='test', Body=open('/app/Dockerfile').read())  # fails
# With region name
client = boto3.client('s3', endpoint_url='http://minio:9000', region_name='k8s00-local')
client.create_bucket('mlflow-artifacts')  # works
client.upload_file('/app/Dockerfile', 'mlflow-artifacts', 'Dockerfile')  # works
client.list_objects(Bucket='mlflow-artifacts')  # works
```

**Comment by tomasatdatabricks** [comment]
I see, thanks for the clarification! Yeah it makes perfect sense to add a way to specify at least the region name but maybe also more of the boto client config. Perhaps we could have an environment variable pointing to a config file. 

Unfortunately, I am not sure how quickly we can get to this at the moment, but if you would be interested in contributing let me know. I would be more than happy to help with any questions you may have.

**Comment by 9dogs** [comment]
I started digging in boto3 docs and it turned out that all the configuration are [already available](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variable-configuration) (including region name)!
Sorry for a false alarm. Maybe MLFlow documentation on S3 storage should have a link or a full description of these environment variables? If so, I can make a PR to docs.

**Comment by tomasatdatabricks** [comment]
Oh nice. 

Yes, it would be great to have this documented. Doc PR would be greatly appreciated!
