### ISSUE TITLE
question - what version of azure.storage.blob required? having troubles with 12.3.0

### ISSUE THREAD

**Issue by twarmuz** [mlflow/mlflow#2602]
I am using latest: azure-storage-blob-12.3.0
and trying to log my artifacts into azure blob storage using:

experiment_id = "123456789"
experiment = mlflow.get_experiment(experiment_id)
mlflow.set_tracking_uri("databricks")
mlflow.set_experiment(experiment.name)
mlflow.start_run()
test_df = pd.DataFrame({"test", "abc"})
test_df.to_pickle("test.pkl")
os.environ["AZURE_STORAGE_ACCESS_KEY"] = "secret"
mlflow.log_artifact("test.pkl", experiment_id)

and my mlflow experiment with the experiment_id is configured with the Artifact Location wasbs://mlflow-artifacts@blah-blah-sa.blob.core.windows.net/

yet, executing the line mlflow.log_artifact()

will give me following error:

File "C:\Users\xxxxx\AppData\Local\conda\conda\envs\mainpy\lib\site-packages\mlflow\store\artifact\azure_blob_artifact_repo.py", line 30, in __init__
    from azure.storage.blob import BlockBlobService
ImportError: cannot import name 'BlockBlobService'

which version of azure.storage.blob should I be running then?
The documentation doesn't say anything explicit.

**Comment by tomasatdatabricks** [comment]
Hi @twarmuz, thanks for posting.

The current azure artifact repository uses azure-storage==0.36.0 library. There is a pending PR updating the artifact repo to v12 version of the library, you can check it here : https://github.com/mlflow/mlflow/pull/2594. 

It will most likely be include in the next mlflow release. For now, please use the older library version or you can try to build custom wheel out of that PR and see if it works for you.

**Comment by tomasatdatabricks** [comment]
The above PR has been merged. The next mlflow release should work with v12 version.

**Comment by twarmuz** [comment]
sounds great @tomasatdatabricks ! many thanks for prompt response!
