### ISSUE TITLE
[FR] Support range requests in mlflow server

### ISSUE THREAD

**Issue by ahirner** [mlflow/mlflow#2606]
## Describe the proposal
Artifact links should support range requests. `mlflow server` with a file-system store (1.7.0) errors with `fsspec`s `HTTPFileSystem` if `block_size` is None or smaller than the file (https://github.com/intake/filesystem_spec/issues/160). `fsspec` is also used by `dask`.
```
from fsspec.implementations.http import HTTPFileSystem
fs = HTTPFileSystem()
f = fs.open("http://localhost:5000/get-artifact?path=test%2Fyour_file.zip&run_uuid=4156145406a242128b30bf749a16fad0")
f.seek(10)
f.read(10)
```
Raises:
```
Traceback (most recent call last):
  File "fs.py", line 6, in <module>
    f.read(10)
  File "/Users/abc/miniconda3/lib/python3.6/site-packages/fsspec/implementations/http.py", line 278, in read
    return super().read(length)
  File "/Users/abc/miniconda3/lib/python3.6/site-packages/fsspec/spec.py", line 1130, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/Users/abc/miniconda3/lib/python3.6/site-packages/fsspec/caching.py", line 339, in _fetch
    self.cache = self.fetcher(start, bend)
  File "/Users/abc/miniconda3/lib/python3.6/site-packages/fsspec/implementations/http.py", line 319, in _fetch_range
    "Got more bytes (%i) than requested (%i)" % (cl, end - start)
ValueError: Got more bytes (22467554) than requested (5242890)
```

### Motivation
We load learning models by seeking/reading zip files. In general, random seek is beneficial for media files.

### Proposed Changes
Ideally there is a canonical way to respond to range requests in `Flask`. However, there might be complications depending on mlflow storage backends.

**Comment by tomasatdatabricks** [comment]
Hi @ahirner, thanks for posting. 

I don't have context on range requests unfortunately. Can you clarify what exactly failed for you with mlflow and include mlflow stack trace?  And what exact behavior (i.e. api request and response) would you like from mlflow ?

**Comment by ahirner** [comment]
Thx for follow-up @tomasatdatabricks . 
Nothing fails in `mlflow server`. However, clients cannot randomly access large files like zipped data or seek in a video via http as `ffmpeg` does. We deal a lot with both and hence noticed the missing support of [range queries](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).
If feasible, I can take a stab on it given guidance at which places local files are served.

**Comment by tomasatdatabricks** [comment]
I see, thanks for the clarification. I am still not sure I understand where do you want to have the range queries. Do you mean you want to access parts of artifacts? Currently the tracking server does not serve artifacts, those are handled by artifact repository, so e.g. sftp or s3.

**Comment by ahirner** [comment]
Indeed, right now our artifact store is local to the server. We tend to share artifacts via http links (download button) for experimental scripts which are only authenticated with `mlflow server`. For this case range queries would still be helpful, but I see your point, so feel free to close.

**Comment by tomasatdatabricks** [comment]
Ok cool. I am closing it for now, please reopen if you feel like there is a missing mlflow api or functionality. Thanks!
