### ISSUE TITLE
Running MLflow training with Docker Env doesn't support GPUs

### ISSUE THREAD

**Issue by ksanjeevan** [mlflow/mlflow#2607]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.7.0
- **Python version**: 3.7.4
- **npm version, if running the dev UI**: N/A

### Describe the problem
When running `mlflow run` with an MLproject that looks like:
```
name: nn-training

docker_env: 
    image: docker-image-with-cuda

entry_points:
    train:
        parameters:
            config: {type: string}
        command: "python train.py --config {config}"
```
I get the following message:
```
NVIDIA Release 20.02 (build 10315040)
PyTorch Version 1.5.0a0+3bbb36e

Container image Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2019 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

```

I've tested this image locally, and simply passing `--gpus all` to `docker run` makes GPU functionality available. But I can't find how to set this flag (or any other useful `docker run` flag) with mlflow.

Since mlflow is built for the ML life-cycle an training nets requires GPUs, I know I must be missing something regarding setting the docker environment's runtime. Can someone point me in the right direction?

### Code to reproduce issue
Build any image (`nvcr.io/nvidia/pytorch:20.02-py3` in our case), and then run `mlflow run` with the docker env set to that image and no other `docker_env` params.

**Comment by tritab** [comment]
I wonder if you might be able to work around this by ensuring your docker daemon is setup following these instructions to enable the GPU for docker by default? https://github.com/NVIDIA/nvidia-container-runtime

**Comment by tritab** [comment]
See related issue https://github.com/mlflow/mlflow/issues/1093

**Comment by ksanjeevan** [comment]
@tritab yeah thanks I'm going to try this workaround, but with GPU functionality being such a major feature I was hoping there was a way to this directly with the mlflow API.

**Comment by tomasatdatabricks** [comment]
Hi @ksanjeevan thanks for posting! That's a good point. I think we should have a way to specify extra docker parameters when running docker project.

**Comment by ksanjeevan** [comment]
@tomasatdatabricks Gotcha, so right now the only way we can do MLflow training with GPUs is using conda env correct?

 In that case it could easily work for docker environments as well if we could set on MLproject file something like:
```
docker_env:
    image: my-image
    run_params: [['--gpus', 'all'], ['--other-flag', 'value'], ...]
```
And have `run_params` propagated to wherever mlflow calls `docker run` and just append them.

**Comment by tomasatdatabricks** [comment]
As for running on gpus - @tritab 's suggestion did not work for you? 

As for adding run params -  Maybe, although I am not sure if we want to specify extra flags in the project file since the projects are supposed to be able to run in different environments. We could also surface docker parameters to the mlflow cli  and let you set the defaults in the MLproject file.

**Comment by ksanjeevan** [comment]
> As for running on gpus - @tritab 's suggestion did not work for you?

Will try it out! After some reading looks like that works for people, so should be a valid workaround... Just wanted a cleaner way to allow for GPU usage, since we want to use a workflow of spinning up machines and automating the training jobs. 

> [...] We could also surface docker parameters to the mlflow cli and let you set the defaults in the MLproject file.

Big 👍. That would cleanly solve all of this and give great flexibility!

**Comment by tomasatdatabricks** [comment]
Cool, let me know if you would be interested in contributing this update, I'd be happy to review you PR. Otherwise we'll try to get to it soon.

**Comment by ksanjeevan** [comment]
Thanks @tomasatdatabricks. So I've created [this draft pr](https://github.com/mlflow/mlflow/pull/2608) to show how it could work? I didn't go into tests or doc or anything like that, just a straightforward implementation that kinda follows what's being done for `--param-list` :)

It'd be awesome if you guys could implement it. If the general idea of the PR looks good to you but you don't think you'll be able to get to it, I can try to work on it thought it might take me longer. Let me know!

**Comment by Zethson** [comment]
> @tomasatdatabricks Gotcha, so right now the only way we can do `mlflow run` with GPUs is using conda env correct?
> 
> In that case it could easily work for docker environments as well if we could set on MLproject file something like:
> 
> ```
> docker_env:
>     image: my-image
>     run_params: [['--gpus', 'all'], ['--other-flag', 'value'], ...]
> ```
> 
> And have `run_params` propagated to wherever mlflow calls `docker run` and just append them.

This solution looks great to me!

**Comment by ksanjeevan** [comment]
Hey @Zethson, check out [this PR draft](https://github.com/mlflow/mlflow/pull/2608). I ended up going with a CLI approach but would work similarly.

**Comment by Zethson** [comment]
Dear @ksanjeevan I examined this PR already. 
I prefer the solution above with docker parameters being defined in the MLproject file, but I would be happy about ANY solution for now.
So thank you for picking this up and I hope that we can find a solution here quickly.

Let's hope that @tomasatdatabricks has some time soon to comment on how to proceed.

**Comment by tomasatdatabricks** [comment]
@ksanjeevan I have commented on you PR, I think it would be great to get that in. 

@Zethson I think we can consider specifying default docker arguments to the project file as well. Adding them to the cli is simpler though so I think we should start with that.

**Comment by Zethson** [comment]
@tomasatdatabricks Awesome, thank you very much!

**Comment by ksanjeevan** [comment]
Addressed in https://github.com/mlflow/mlflow/pull/2608
