### ISSUE TITLE
[BUG] log-param REST call doesn't return reason for failure

### ISSUE THREAD

**Issue by maximeturenne** [mlflow/mlflow#2628]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
CentOS 7
- **MLflow installed from (source or binary)**:
binary
- **MLflow version (run ``mlflow --version``)**:
1.7
- **Python version**:
3.8
- **npm version, if running the dev UI**:
20.0.2
- **Exact command to reproduce**:
1. Setup environment variables to connect on a mlflow server:
```
export MLFLOW_TRACKING_URI=
export MLFLOW_TRACKING_USERNAME=
export MLFLOW_TRACKING_PASSWORD=
```

2. Create an experiment logging a parameter with a string value over 500 bytes
```
with mlflow.start_run():
    mlflow.log_param("A parameter", "Over 500 bytes string...")
```

3. Run you experiment
python3 your_file.py ....

### Describe the problem

The rest API will return a generic error message.
We should see an error message indicating the maximum value are exceeded. 

I assume this maximum is intended because it is specified in the API documentation: https://www.mlflow.org/docs/latest/rest-api.html#log-param
Therefore, there is no reason not to give information regarding this error. 

### Other info / logs

Only the following message is returned:

> ERROR mlflow.utils.rest_utils: API request to MLFLOW_SERVER/api/2.0/mlflow/runs/log-parameter failed with code 500 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by Zangr** [comment]
@maximeturenne Thank you for reporting this. It sounds like a valid thing to improve. We'll take a look.
