### ISSUE TITLE
[BUG] Invalid "stage" name on ".travis.yml"

### ISSUE THREAD

**Issue by keigohtr** [mlflow/mlflow#2631]
### Describe the problem
According to the Travis official doc, `TRAVIS_BUILD_STAGE_NAME` will be automatically capitalized but actually not.
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

### Code to reproduce issue
Run travisci

### Other info / logs
In my case.
```
$ echo "Build stage $TRAVIS_BUILD_STAGE_NAME";
Build stage small
```

Log
https://travis-ci.org/github/mlflow/mlflow/jobs/666239656#L446

**Comment by dbczumar** [comment]
@keigohtr I'm a bit confused about why capitalization of the stage name is important here. Is some behavior broken or incorrect because of capitalization discrepancies?

**Comment by keigohtr** [comment]
@dbczumar 
This is the reason -> https://github.com/mlflow/mlflow/pull/2639

**Comment by dbczumar** [comment]
@keigohtr Thanks! cc @tomasatdatabricks @aarondav

**Comment by tomasatdatabricks** [comment]
hi @keigohtr, I am not sure if I understand correctly. We had a bug in our test setup that resulted in running large tests instead of small and this was resolved in #2639 along with a conda issue related pyspark. 

Can we close this ticket now? Or is there still something wrong?

**Comment by keigohtr** [comment]
Yes!
You can close this ticket.

**Comment by tomasatdatabricks** [comment]
Ok, thanks!
