### ISSUE TITLE
 I can't find 'serving' tab in my model registry

### ISSUE THREAD

**Issue by pavin** [mlflow/mlflow#2640]
I saw below image from documentation.
But I can't find 'serving' tab in my model registry.

Anyone help please?

![oss_registry_3c_version](https://user-images.githubusercontent.com/6386718/77627116-be2c5300-6f89-11ea-9385-fb4e8c5d885d.png)

**Comment by pogil** [comment]
Whoops! @pavin, those are from UI mocks and aren't from an actual feature. We'll get those docs fixed quickly.
