### ISSUE TITLE
[BUG] mlflow run overrides script config

### ISSUE THREAD

**Issue by Tyrannas** [mlflow/mlflow#2649]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 1.7.1
- **Python version**: 3.7

### Describe the problem
I have a script where I:

1. set the tracking uri to an mlflow server ('http://127.0.0.1:5000')
2. mlflow.start_run
3. log some metrics and parameters

Now I launch this script manually it works perfectly. But if I try to launch it with mlflow run
I get this error
`mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run '744b34adb6174fd2bae34b67aaae93a0' not found`

This is because mlflow run creates a run locally and not on the tracking server. (Although i configured mlflow in the script to use my server as the backend).

The only way of making it work is to set manually MLFLOW_TRACKING_URI *before* running mlflow run. And so the mlflow.set_tracking_uri becomes useless.

Is this supposed to be a normal behaviour? 

### Code to reproduce issue

In main.py

```python
import mlflow
mlflow.set_tracking_uri('http://127.0.0.1:5000')
with mlflow.start_run():
    mlflow.log_metric('mse', 0.80)
```
I launch the server with the following command, and I can visualize the UI properly.
```
mlflow server -h 127.0.0.1
```

I created an MLproject.yml with 
```yaml
name: TestModel
entry_points:
  main:
    command: "python main.py"
```
And then:

```
mlflow run .
```

**Comment by mparkhe** [comment]
I am closing issue since this is same as #608
