### ISSUE TITLE
[BUG] DB Tracking URI: client never releases DB connection

### ISSUE THREAD

**Issue by MFreidank** [mlflow/mlflow#2650]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**:
Binary via `pip`
- **MLflow version (run ``mlflow --version``)**:
1.6.0
- **Python version**:
3.6.10
- **npm version, if running the dev UI**:
*UI not used*
- **Exact command to reproduce**:
python db_uri_connection_example.py

### Describe the problem

When using a tracking URI that points to a database, the line:
`client = mlflow.tracking.MlflowClient(tracking_uri=tracking_uri)`
allocates a database connection. 
This database connection is not closed/deallocated when the client object is overwritten, deleted or goes out of its defining scope. 
This can lead to left-over database connections accumulating, ultimately resulting in errors (e.g. `sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1040, 'Too many connections')`),

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
# db_uri_connection_example.py
import os
import mlflow

def f():
    client = mlflow.tracking.MlflowClient(tracking_uri=os.environ["MLFLOW_TRACKING_URI"])

for _ in range(1000):
    f()
```

This example assumes that an environment variable `"MLFLOW_TRACKING_URI"` was set that contains a valid `pymysql` database URI. In that case, the execution of the code above results in:

`sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1040, 'Too many connections')
(Background on this error at: http://sqlalche.me/e/e3q8)`

**Comment by juntai-zheng** [comment]
Hi @MFreidank, can I ask what the use case for creating more connections than sqlalchemy allows is? Ideally you wouldn't need to create so many of the same connection to the database.

**Comment by dbczumar** [comment]
@juntai-zheng @MFreidank regardless of use case, the fact that the MLflow Client holds a database connection after the object has exited scope and is no longer accessible seems problematic and should be corrected.

**Comment by MFreidank** [comment]
Hi @juntai-zheng 
The actual problem occurred inside a REST route (flask) that needed to load things from the tracking database upon user request. 
As I was creating a tracking client object inside the route function, this would lead to the flask app  
crashing after a certain number of requests, because connections are never freed up. 
Users believe they are only using a single database connection, because there is only a single tracking client object in scope, when in reality there can be open connections that can not be closed anymore because the tracking client object that allocated them is no longer even accessible.

@dbczumar Agreed, it can easily lead to hard-to-find bugs with long-running applications crashing seemingly randomly - hence why I opened this issue to at least have things documented. 

A potential workaround is to wrap a tracking client object in a singleton pattern to ensure a single instance across the entire application. 
I believe an update to the documentation highlighting the existence of this problem and guiding on avoiding it (with my workaround above or a different, better one) could be sufficient, if a principled fix seems difficult/out of reach.

**Comment by dbczumar** [comment]
@MFreidank Thanks for the input here; I think the ideal workaround would be to fix potential session management gaps in the `SqlAlchemyStore`. Unfortunately, I attempted to reproduce this issue and was unable to achieve the same `Too many connections` error against a MySQL database. Here's the code I used:

```
import mlflow
from mlflow.tracking.client import MlflowClient

def f():
    client = MlflowClient("mysql://root:password@localhost:33060/mydb")
    client.create_run(0)

for _ in range(10000):
    f()
```

Can you provide more information about the database URI that was passed to `MLFLOW_TRACKING_URI` and the version of MySQL that you're using?

**Comment by dmatrix** [comment]
Waiting for the author feedback and label it as area/tracking

**Comment by Casyfill** [comment]
having same issue with postgresql. mlflow UI turned belly-up once limit of connections is above the limit

**Comment by dbczumar** [comment]
@Casyfill Can you provide more information about the database URI that was passed to MLFLOW_TRACKING_URI and the Postgres configuration that you're using (version, etc)? I'm still having difficulties reproducing this issue.

**Comment by dbczumar** [comment]
Resolved by https://github.com/mlflow/mlflow/pull/4663
