### ISSUE TITLE
FileNotFoundError while creating a directory

### ISSUE THREAD

**Issue by HarshSharma12** [mlflow/mlflow#2655]
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: binary (pip)
- **MLflow version (run ``mlflow --version``)**: 1.2.0
- **Python version**: 3.7.6
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**:
mlflow.pyfunc.save_model(
            path=mlflow_pyfunc_model_path,
            python_model=MLFlowWrapper(),
            code_path=[args.projectPath + "modeling"],
            artifacts=artifacts,
            conda_env=args.projectPath + "env.yaml"
        )

### Describe the problem
While saving the model, I get a _FileNotFoundError_ when the code reaches line 86 (os.mkdir(local_path)) in mlflow\store\artifact_repo.py

The error is not generated if I update line 86 to os.makedirs(local_path) instead.

### Code to reproduce issue
mlflow.pyfunc.save_model(
            path=mlflow_pyfunc_model_path,
            python_model=MLFlowWrapper(),
            code_path=[args.projectPath + "modeling"],
            artifacts=artifacts,
            conda_env=args.projectPath + "env.yaml"
        )

### Other info / logs
```
  File "scripts\train.py", line 144, in <module>
    main()
  File "scripts\train.py", line 114, in main
    conda_env=args.projectPath + "env.yaml"
  File "C:\Users\harsh.sharma\Anaconda3\lib\site-packages\mlflow\pyfunc\__init__.py", line 579, in save_model
    code_paths=code_path, mlflow_model=mlflow_model)
  File "C:\Users\harsh.sharma\Anaconda3\lib\site-packages\mlflow\pyfunc\model.py", line 157, in _save_model_with_class_artifacts_params
    artifact_uri=artifact_uri, output_path=tmp_artifacts_dir.path())
  File "C:\Users\harsh.sharma\Anaconda3\lib\site-packages\mlflow\tracking\artifact_utils.py", line 66, in _download_artifact_from_uri
    artifact_path=artifact_path, dst_path=output_path)
  File "C:\Users\harsh.sharma\Anaconda3\lib\site-packages\mlflow\store\local_artifact_repo.py", line 60, in download_artifacts
    return super(LocalArtifactRepository, self).download_artifacts(artifact_path, dst_path)
  File "C:\Users\harsh.sharma\Anaconda3\lib\site-packages\mlflow\store\artifact_repo.py", line 113, in download_artifacts
    return download_artifacts_into(artifact_path, dst_path)
  File "C:\Users\harsh.sharma\Anaconda3\lib\site-packages\mlflow\store\artifact_repo.py", line 86, in download_artifacts_into
    os.mkdir(local_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\HARSH~1.SHA\\AppData\\Local\\Temp\\1\\tmpc2qqahyq\\weights\\catboos
```

**Comment by HarshSharma12** [comment]
I would suggest to use makedirs instead of mkdir everywhere as it ensures parent directories exist before trying to create the directory. Also, I can submit a PR if required.

**Comment by AveshCSingh** [comment]
Hi Harsh, thanks for reporting this issue. I believe it has been fixed [here](https://github.com/mlflow/mlflow/commit/39d47fa6351c7a39a2af3904819d3edcc394aff3).

Would you mind updating to v1.8.0 and checking if the error still occurs? I suspect it will fix this, so will close out the issue.
