### ISSUE TITLE
unable to log artifacts on azure blobs

### ISSUE THREAD

**Issue by praymalik2000** [mlflow/mlflow#2663]
i am trying to log artifacts on azure blob storage. 
1. created a storage account on azure
2. created container
3. provided public access level to container.
4. created AZURE_STORAGE_CONNECTION_STRING environment variable and assigned the storage account connection string as the value 
5. executed mlflow server  --default-artifact-root wasbs://containername@storageacountname.blob.core.windows.net/
6. CODE:
exp = mlflow.create_experiment('myfirstexperiment2')
mlflow.start_run(experiment_id=int(exp.experiment_id))
ds = pd.read_csv('car_evaluation.csv')
log_artifact('car_evaluation.csv')

ISSUE: THE ARTIFACTS ARE STILL BEING LOGGED IN MY ./mlruns DIRECTORY. 

what am i missing. there is not much documentation available on https://www.mlflow.org/docs/latest/tracking.html#tracking-server regarding permissions associated with storage account for AZURE

thanks

**Comment by harupy** [comment]
Can you try this?

```python
with mlflow.start_run():
    ds = pd.read_csv('car_evaluation.csv')
    log_artifact('car_evaluation.csv')
```

**Comment by pogil** [comment]
Hi @praymalik2000, 

It looks like you may need to also set the environment variable `MLFLOW_TRACKING_URI` to the host running the service (e.g. `http://127.0.0.1:5000`). This will then use your service to fetch the tracking URI. Note that if you run the service on a separate machine, you'll need to set up access for the client using the same `AZURE_STORAGE_CONNECTION_STRING` environment variable.

**Comment by dongy** [comment]
I meet the same issue. Get Loading Artifacts Failed
Unable to list artifacts stored under <code>{artifactUri}</code> for the current run. Please contact your tracking server administrator to notify them of this error, which can happen when the tracking server lacks permission to list artifacts under the current run's root artifact directory.

**Comment by csvlrs-lak** [comment]
@dongy, install azure-storage-blob before starting the server
