### ISSUE TITLE
[BUG] Numeric parameter with value >= 1'000 can't be supplied in R mlflow::mlflow_run()

### ISSUE THREAD

**Issue by lorenzwalthert** [mlflow/mlflow#2664]
### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow): Yes.**
- macOS 10.15.3.
- **MLflow installed from source (GitHub)**:
- **MLflow version 1.7.3 (dev)**:
- **Python version: 3.6**:
- **Exact command to reproduce**:

```r
mlflow::mlflow_run('.', entry_point = 'R/script.R', parameters = list(
  large_dbl = 1000000,
  other = 3
))
```

### Describe the problem

It's impossible to supply a parameter value larger or equal to 1'000 by default in R mlflow when running `mlflow::mlflow_run()` because the scientific formatting will kick in and the number won't be recognised as numeric anymore somewhere downstream. The root of the problem can be observed in the R console:

```r
10000000
#> [1] 1e+07
```

With the above command, I get the following error:

```
2020/04/03 18:03:13 INFO mlflow.projects: === Created directory /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/tmp1zqfgvss for downloading remote URIs passed to arguments of type 'path' ===
2020/04/03 18:03:13 INFO mlflow.projects: === Running command 'source /Users/lorenz/opt/miniconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-da39a3ee5e6b4b0d3255bfef95601890afd80709 1>&2 && Rscript -e "mlflow::mlflow_source('R/script.R')" --args --large_dbl 1e+06 --other 3' in run with ID '6e1420faad164528b654a16b08c2da80' ===

Error: Provided value for `large_dbl` cannot be casted to type numeric: `x` cannot be casted to a double vector.
```

This is what happens: When any number is supplied to `mlflow::mlflow_run()`, it may be displayed in scientific notation, remains of class numeric. Then, to prepare the call to `mlflow::mlflow_source()`, it's `paste0()`d and hence converted to character. Like all other numbers. Then, it is passed to `mlflow::mlflow_source()` as command line arguments. The difference to "normal" numbers is that in `parse_command_line()`,where `yaml::yaml.load()` is used, strings like "3" will be turned into numeric again, but not scientific notation. I see two solutions:

- convert all numeric input to non-scientific before passing it to `mlflow::mlflow_source()`. Drawback: If a user supplies 1e6, it will be logged  as 1000000. This may take a lot of space, in particular in the UI when comparing many runs with big numers.

- recover scientific notation in `parse_command_line()`. Drawback: We might turn  a parameter that was supplied as string into numeric, i.e. when you supplied  "1e3" initially, this will be turned into 1000 and the user has to see how to  turn that back into 1e3.

I think the second approach is preferred and I submited #2665 to implement it.
### Code to reproduce issue

Run the above command in [this](https://github.com/lorenzwalthert/mlflow-r-casting-bug/tree/master/R) minimally reproducible git repo, file `R/runner.R`.

**Comment by dbczumar** [comment]
@lorenzwalthert Thank you for filing this issue and a fix in https://github.com/mlflow/mlflow/pull/2665. Out of curiosity, is this an issue for other MLflow APIs as well (e.g., `mlflow_log_metric` in Tracking?)

**Comment by lorenzwalthert** [comment]
For metrics: Apparently not, because these are always casted to non-scientific double somewhere in the process. Before the REST API call is made, it's still in a scientific format as a string though. I checked an example with a local storage backend in `mlruns/0/:hash/metrics/:metric/`. The flat file contains a non-scientific number. Don't know about other storage backends. Opposed to parameters, metrics always must be numeric so I guess the REST API handles this already correctly.

**Comment by dbczumar** [comment]
@lorenzwalthert Thanks for investigating `log_metric` - awesome that the fix for Projects has been merged!
