### ISSUE TITLE
[FR] Customizing the `mlflow ui`

### ISSUE THREAD

**Issue by fzyzcjy** [mlflow/mlflow#2668]
Proposal: Let the users be able to customize the UI by adding some more code. For instance, in addition to the "compare" button, I want to have one more "refresh my external toolkit" button which will call a toolkit with selected runs. Currently, I did not find any discussions, or any documentations, about such UI customization. Thanks!

**Comment by aarondav** [comment]
So is the idea that you would send a set of selected runs as a request to another web page? This might actually be best accomplished as a chrome extension which injects HTML into the MLflow page which can be installed in your organization.

Separately, you could fork the MLflow UI and add the customizations you're looking for on top.

I can't think of a great extension point for this kind of arbitrary code snippet injection, though.

**Comment by fzyzcjy** [comment]
Thanks!
