### ISSUE TITLE
[BUG]: unable to run mlflow projects on windows 10

### ISSUE THREAD

**Issue by praymalik2000** [mlflow/mlflow#2674]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.7.1
- **Python version**: 3.7.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:  mlflow run testproject
-**Anaconda3

### Describe the problem
i am trying to run mlflow project by execute the following command on anaconda powershell prompt using administrative privileges 
mlflow run <foldername>

I followed two steps: 
**Step 1**
MLFLOW_CONDA_HOME: environment variable set:  D:\anaconda (anaconda installation folder)

while trying to run a mlflow project, I am getting the following error:

ERROR mlflow.cli: === Could not find Conda executable at D:\anaconda\bin/conda. Ensure Conda is installed as per the instructions at https://conda.io/projects/conda/en/latest/user-guide/install/index.html. You can also configure MLflow to look for a specific Conda executable by setting the MLFLOW_CONDA_HOME environment variable to the path of the Conda executable ===
(base) PS D:\DataScience\learning\P14-Machine-Learning-AZ-Template-Folder\Part_12_MLFlow\projects>

there is no bin folder created by anaconda in windows 10. The mlflow cli always looks for the bin folder. if i specify d:\anaconda\Library\bin as the path of environment variable i get some scripting error. 

**Step 2**
1.  Removed the environment variable and added conda to my path variable 
2.  execute the following command on anaconda powershell prompt using administrative privileges
mlflow run <projectfolder directory>
3. Error: 
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

**My MLproject file:**
name: testproject

conda_env: conda.yaml

entry_points:
  main:
    command: "python mlflowtrace.py"

Am i missing a setting or is there an alternate path?

**Comment by pdudzic123** [comment]
It appears that the problem is caused by "&&" in generated command.
The following command is generated:
`conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac && python train.py 0.42 0.1`
and Powershell is unable to parse this command correctly.
The dirty workaround for this is to run:
`conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac`
manually before running the
`mlflow run . --no-conda`

Note that:

    -I used mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac as conda env. This env was created by mlflow and it changes. You can find your envs by executing conda env list
    -I added --no-conda to the second statement.

I hope they will fix this parsing issue in the near future.
Best

**Comment by dbczumar** [comment]
@pdudzic123 Unfortunately, MLflow does not yet offer explicit support for MLflow Project execution on Windows. Please let me know if this is something you'd be willing to contribute towards. 

Regarding the parsing issue with `&&`, is this a powershell-specific problem?

**Comment by praymalik2000** [comment]
the problem was resolved based on suggestions from pdudzic123. thanks a lot.
