### ISSUE TITLE
how to migrate filesystem runs to db?

### ISSUE THREAD

**Issue by verasativa** [mlflow/mlflow#2676]
Hello, I have some tracked experiments stored on local file system, how could I migrate them to a db?

ps: I tried to set a question label for issue, but looks like I don't have the proper permissions

**Comment by smurching** [comment]
Hi @verasativa, apologies for the delay - there's no official tooling yet to support this use case, but there are some third-party scripts that enable it. In particular, @amesar's written scripts for migrating experiments between tracking servers in https://github.com/amesar/mlflow-tools/blob/master/mlflow_tools/export_import/README.md. Note that in general for this kind of migration, we strongly encourage backing up your existing experiment data prior to migration.

We'd also welcome / be happy to advertise an actively-maintained migration tool on mlflow.org. Thanks!

**Comment by weldpua2008** [comment]
@verasativa I've recently started the migration 0.8.1 -> 1.8.0 and wrote the following script https://gist.github.com/weldpua2008/7f0c4644d247bd0fc7ba9a83c2d337d5

**Comment by smurching** [comment]
Closing as dup of #2382
