### ISSUE TITLE
"MlflowException: API request to http://mlflow:5000/api/2.0/mlflow/experiments/create failed to return code 200 after 3 tries" on docker container

### ISSUE THREAD

**Issue by jralfonsog** [mlflow/mlflow#2682]
### System information
- Have I written custom code (as opposed to using a stock example script provided in MLflow)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linut Mint 19.3
- MLflow version (run mlflow --version): 1.3.0 and 1.7.2
- Python version: 3.7.7
- Exact command to reproduce: 

### Describe the problem:
I'm have 3 dockers containers running: Jupyter, MLflow and min.io. My MLFLOW_TRACKING_URI is set to http://mlflow:5000, and I'm running the following snippet:
`experiment = 'iris_classification'
mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
mlflow.set_experiment(experiment)`
With this output:

> 2020/04/09 00:52:12 ERROR mlflow.utils.rest_utils: API request to http://mlflow:5000/api/2.0/mlflow/experiments/create failed with code 500 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
> 
> INFO: 'iris_classification' does not exist. Creating a new experiment
> 
> 2020/04/09 00:52:15 ERROR mlflow.utils.rest_utils: API request to http://mlflow:5000/api/2.0/mlflow/experiments/create failed with code 500 != 200, retrying up to 1 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
> 
> 2020/04/09 00:52:18 ERROR mlflow.utils.rest_utils: API request to http://mlflow:5000/api/2.0/mlflow/experiments/create failed with code 500 != 200, retrying up to 0 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
> 
> ---------------------------------------------------------------------------
> MlflowException                           Traceback (most recent call last)
> <ipython-input-11-1dbf8bcef03a> in <module>
>       2 experiment = 'iris_classification'
>       3 mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
> ----> 4 mlflow.set_experiment(experiment)
> 
> /opt/conda/lib/python3.7/site-packages/mlflow/tracking/fluent.py in set_experiment(experiment_name)
>      49     if exp_id is None:  # id can be 0
>      50         print("INFO: '{}' does not exist. Creating a new experiment".format(experiment_name))
> ---> 51         exp_id = client.create_experiment(experiment_name)
>      52     elif experiment.lifecycle_stage == LifecycleStage.DELETED:
>      53         raise MlflowException(
> 
> /opt/conda/lib/python3.7/site-packages/mlflow/tracking/client.py in create_experiment(self, name, artifact_location)
>     159         :return: Integer ID of the created experiment.
>     160         """
> --> 161         return self._tracking_client.create_experiment(name, artifact_location)
>     162 
>     163     def delete_experiment(self, experiment_id):
> 
> /opt/conda/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py in create_experiment(self, name, artifact_location)
>     126         return self.store.create_experiment(
>     127             name=name,
> --> 128             artifact_location=artifact_location,
>     129         )
>     130 
> 
> /opt/conda/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py in create_experiment(self, name, artifact_location)
>      52         req_body = message_to_json(CreateExperiment(
>      53             name=name, artifact_location=artifact_location))
> ---> 54         response_proto = self._call_endpoint(CreateExperiment, req_body)
>      55         return response_proto.experiment_id
>      56 
> 
> /opt/conda/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py in _call_endpoint(self, api, json_body)
>      30         endpoint, method = _METHOD_TO_INFO[api]
>      31         response_proto = api.Response()
> ---> 32         return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
>      33 
>      34     def list_experiments(self, view_type=ViewType.ACTIVE_ONLY):
> 
> /opt/conda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py in call_endpoint(host_creds, endpoint, method, json_body, response_proto)
>     134     else:
>     135         response = http_request(
> --> 136             host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
>     137     response = verify_rest_response(response, endpoint)
>     138     js_dict = json.loads(response.text)
> 
> /opt/conda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py in http_request(host_creds, endpoint, retries, retry_interval, max_rate_limit_interval, **kwargs)
>      78             time.sleep(retry_interval)
>      79     raise MlflowException("API request to %s failed to return code 200 after %s tries" %
> ---> 80                           (url, retries))
>      81 
>      82 
> 
> MlflowException: API request to http://mlflow:5000/api/2.0/mlflow/experiments/create failed to return code 200 after 3 tries

In case it helps, please find attached a zip file with my docker-compose.yml and Dockerfile:
[docker-files.zip](https://github.com/mlflow/mlflow/files/4453451/docker-files.zip)

I've searched through the relevant issues, but haven't found a solution (I've added EXPORT 5000 to the Dockerfile, and made sure MLFLOW_TRACKING_URI was properly set)

Thanks for your time.

**Comment by andychow-db** [comment]
@jralfonsog 

I'm not an expert at Docker but it looks like you need to specify the host DNS such as `127.0.0.1:5000` if the hosts are sitting on the same host.

When specifying a tracking_uri, it can be a URL such as `http://localhost:5000`. [set_tracking_uri Documentation](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tracking_uri)

`http://mlflow` is not a valid URL.

**Comment by jralfonsog** [comment]
Hi, @andychow-db . Thanks for your response.

"mlflow" is the name of the docker host, so http://mlflow:5000 should be the right URL. Actually, I found that the snippet works if the variable `experiment` corresponds with an existent run, but if doesn't if I the `experiment` doesn't exist. Does it make any sense to you?

**Comment by andychow-db** [comment]
Oh interesting! That's a great find. 

It looks like MLflow fails out when we try to create a new experiment when it does not exist. (https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/fluent.py#L47-L51)

I think the next step is to look at the MLflow server's logs to see what caused the INTERNAL_ERROR. Would you mind pulling those logs?

**Comment by jralfonsog** [comment]
[9a5301d49e05689c4d9efd0ca4fc2312ce85c2a59840490f7b5d5c9370106906-json.log](https://github.com/mlflow/mlflow/files/4484033/9a5301d49e05689c4d9efd0ca4fc2312ce85c2a59840490f7b5d5c9370106906-json.log)
Sure, find them attached here

**Comment by andychow-db** [comment]
I cleaned up the logs a bit and pulled out what I thought was interesting: 

```
2020/04/14 08:23:21 ERROR mlflow.server: Exception on /api/2.0/mlflow/experiments/create [POST]"
Traceback (most recent call last):"
  File \"/opt/conda/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app"
    response = self.full_dispatch_request()"
  File \"/opt/conda/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request"
    rv = self.handle_user_exception(e)"
  File \"/opt/conda/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception"
    reraise(exc_type, exc_value, tb)"
  File \"/opt/conda/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise"
    raise value"
  File \"/opt/conda/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request"
    rv = self.dispatch_request()"
  File \"/opt/conda/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request"
    return self.view_functions[rule.endpoint](**req.view_args)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/server/handlers.py\", line 102, in wrapper"
    return func(*args, **kwargs)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/server/handlers.py\", line 149, in _create_experiment"
    request_message.artifact_location)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/store/file_store.py\", line 235, in create_experiment"
    return self._create_experiment_with_id(name, str(experiment_id), artifact_location)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/store/file_store.py\", line 211, in _create_experiment_with_id"
    write_yaml(meta_dir, FileStore.META_DATA_FILE_NAME, experiment_dict)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/utils/file_utils.py\", line 128, in write_yaml"
    if not exists(root):"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/utils/file_utils.py\", line 31, in exists"
    return os.path.exists(name)"
  File \"/opt/conda/lib/python3.7/genericpath.py\", line 19, in exists"
    os.stat(path)"
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType"
WARNING:root:Malformed experiment '1'. Detailed error Yaml file '/opt/mlruns/1/meta.yaml' does not exist."
Traceback (most recent call last):"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/store/file_store.py\", line 193, in list_experiments"
    experiment = self._get_experiment(exp_id, view_type)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/store/file_store.py\", line 247, in _get_experiment"
    meta = read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/utils/file_utils.py\", line 159, in read_yaml"
    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)"
mlflow.exceptions.MissingConfigException: Yaml file '/opt/mlruns/1/meta.yaml' does not exist."
WARNING:root:Malformed experiment '1'. Detailed error Yaml file '/opt/mlruns/1/meta.yaml' does not exist."
Traceback (most recent call last):"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/store/file_store.py\", line 193, in list_experiments"
    experiment = self._get_experiment(exp_id, view_type)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/store/file_store.py\", line 247, in _get_experiment"
    meta = read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)"
  File \"/opt/conda/lib/python3.7/site-packages/mlflow/utils/file_utils.py\", line 159, in read_yaml"
    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)"
mlflow.exceptions.MissingConfigException: Yaml file '/opt/mlruns/1/meta.yaml' does not exist."
```

**Comment by jralfonsog** [comment]
Thanks, @andychow-db . What should be the next step? Shouldn't this be created when generating a new experiment?

**Comment by rahulraj80** [comment]
I am able to run your code as long as the name of the experiment is unique. 
Reusing the same name gives the API error you mentioned.

Simple test - in your code, change the name to:
import sys
EXPERIMENT_NAME = sys.argv[1]

And call then call the script by adding `uuid` at the end. (sudo apt install uuid , if you do not have it)

**Comment by jralfonsog** [comment]
Sorry for the late response. Please, let me give it a look and come back here. Thanks for the idea

**Comment by smurching** [comment]
Looking at the stacktrace, looks like we call `write_yaml` [here](https://github.com/mlflow/mlflow/blob/v1.3.0/mlflow/store/file_store.py#L211) with a `meta_dir` that is `None`. AFAICT the only way this can happen is if `mkdir` returns `None` [here](https://github.com/mlflow/mlflow/blob/v1.3.0/mlflow/store/file_store.py#L205), which only seems possible if `self.root_directory` is `None` in the `FileStore`. Thus I suspect the command in your dockerfile for running the server may not actually be setting the backend store URI of the server properly - are you able to create/view any experiments under your server?

**Comment by jralfonsog** [comment]
> I am able to run your code as long as the name of the experiment is unique.
> Reusing the same name gives the API error you mentioned.
> 
> Simple test - in your code, change the name to:
> import sys
> EXPERIMENT_NAME = sys.argv[1]
> 
> And call then call the script by adding `uuid` at the end. (sudo apt install uuid , if you do not have it)

Naming the experiment with uuid, the problem remains in my case :/



> Looking at the stacktrace, looks like we call `write_yaml` [here](https://github.com/mlflow/mlflow/blob/v1.3.0/mlflow/store/file_store.py#L211) with a `meta_dir` that is `None`. AFAICT the only way this can happen is if `mkdir` returns `None` [here](https://github.com/mlflow/mlflow/blob/v1.3.0/mlflow/store/file_store.py#L205), which only seems possible if `self.root_directory` is `None` in the `FileStore`. Thus I suspect the command in your dockerfile for running the server may not actually be setting the backend store URI of the server properly - are you able to create/view any experiments under your server?

I am able to view an existent experiment from before (I am using a volume for the "experiment" folder which already has a run from before this setup), but I can't create a new one because each time I try it gives the error.

**Comment by harupy** [comment]
@jralfonsog I was able to run the following on Jupyter using your docker-compose.yml:

```
mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
mlflow.set_experiment("iris_classification")
```

**Comment by jralfonsog** [comment]
And suddenly, after all this time... it works now! I have an EXT4 unit for Linux, a NTFS for Windows, and a bigger NTFS shared one (where I had placed the project). Turns out that I was having some kind of permission problems, and they were solved by moving it to the EXT4. I can't believe it...

Thanks a lot to everyone for your time.

**Comment by harupy** [comment]
@jralfonsog Awesome! Can we close this issue?

**Comment by jralfonsog** [comment]
Yes! I had just edited my message to say so :)

Thanks again!
