### ISSUE TITLE
REST API should return 4xx codes when error is caused by client

### ISSUE THREAD

**Issue by andremesarovic** [mlflow/mlflow#269]
For REST API operations, currently all errors return 500 (Internal Server Error). The API should return standard 4xx HTTP status codes when the error is caused by the client. 5xx should be rare - returned only by unexpected internal server errors. 

Some examples:
- 404 (Not Found) should be returned when looking up a non-existent resource, .e.g. experiments/get?experiment_id=foo
- 400 (Bad Request) when bad JSON is submitted to any POST operation such as create experiment
- 409 (Conflict)- when trying to create an experiment with duplicate name 

 See: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4

**Comment by dbczumar** [comment]
@andremesarovic Thank you for filing this issue! It has finally been addressed, most recently by https://github.com/mlflow/mlflow/pull/5458 to handle 400-level errors due to invalid request input.
