### ISSUE TITLE
[BUG] Having to manually _active_run_stack to bypass exceptions when using jupyter

### ISSUE THREAD

**Issue by ahmed-shariff** [mlflow/mlflow#2692]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch linux
- **MLflow installed from (source or binary)**: pip
- **Environment**: jupyter
- **MLflow version (run ``mlflow --version``)**: 1.7.2
- **Python version**: 3.8

### Describe the problem
I was playing around with using mlflow on jupyter and was using the `MLflowClient` to check the results. At one point I had manually deleted the mlruns folder. After that, wheen try to start a run again I kept getting the 
```
Run with UUID {} is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
```
When I try to call `end_run`, it kept throwing `MLflowException` since the directory doesn't exist.
I had to manually set the `_active_run_stack`:
```
mlflow.tracking.fluent._active_run_stack = []
```

A potential solution:
wrap the line https://github.com/mlflow/mlflow/blob/63f1333c0436f897bcbb2de0ad65e21390f9434d/mlflow/tracking/fluent.py#L164 in a try catch?

**Comment by juntai-zheng** [comment]
Thanks for identifying the bug and putting in the fix! Closing the issue as it's resolved now.
