### ISSUE TITLE
feature request: support auto commits for tracked or working directory files

### ISSUE THREAD

**Issue by yogeshg** [mlflow/mlflow#271]
Can we add auto commits for tracked or working directory files?

the api could look something like this:

```python
with mlflow.start(auto_commit="tracked revert"):
    ## run experiment
    mlflow.log_artifacts("./")
```

the `auto_commit` parameter can take options similar to what the `mode` parameter for python file opening command takes: 
```
auto_commit="<files_to_commit> <behavior_of_commit>"
files_to_commit : added / tracked
behavior_of_commit : keep / revert
```

* `added` commits all the files that were already git added or staged in the working directory. It can be equivalent to `git commit -m "auto commit added files"`.
* `tracked` commits added and tracked files in the working directory. It can be equivalent to  `git commit -m "auto commit added files"` `git commit -am "auto commit tracked files"`.
If there are large blobs in the working directory that users do not wish to keep in git history, they should be warned to ".gitignore" them

* `revert` should revert the changes introduced in the recent run of auto tracking. This way, the use can see the git commit from mlflow ui, also do `git checkout <hash_from_ui>` and yet keep their git branch's history clean.
* `keep` can also add all commits to the current git branch.

We can also brainstorm about other features such as `tag_run_number` that can tag the commits with a best effort incremental run number of the current directory, this can introduce a new best practice of run tags like `runv_1.0.42` akin to release tags.

**Comment by GCBallesteros** [comment]
I always do autocommits and you don't need to modify MLFlow in order to do so. My approach is simply to call an `autocommit` function that makes the commit (using GitPython) and pass the resulting commit to the `source_version` parameter in `mlflow.start_run`. My current version of the function has many limitations but it does the job for me.

I do agree that it would nice to have a `mlflow.autocommit` function which is better tested and a bit more general than what I have at the moment.

I don't have access to the code but I will share my current solution as soon as I can.

**Comment by GCBallesteros** [comment]
Below is the code that I'm using. Its biggest limitation is that I don't want my function to commit things that I may have staged but forgotten about them so I just raise an exception. What I would like to do is save the staged area do the commit on the file and then get back my original staged files. The only way I've found is [via an interactive rebase](https://stackoverflow.com/questions/15020237/how-to-save-the-current-state-of-my-staging-area) but that won't work here.

```
from git import Repo

def auto_commit(repo, file_path, home_dir='', branch=None):
    if branch == None:
        branch = repo.active_branch
    
    if repo.git.diff("--cached"):
        raise Exception("You have uncommited staged changes. Clear that up!")

    # Call directly git because otherwise the filters are not applyed
    file_path = home_dir + file_path
    repo.git.add(file_path)
    try:
        repo.git.commit("-m AUTOML commit")
    except:
        # Nothing to commit because file was untouched
        pass
    
    last_commit = list(repo.iter_commits(branch))[:1][0]
    
    return last_commit.hexsha
```

**Comment by drorata** [comment]
@GCBallesteros Can you also include an example how you use `auto_commit` as part of a script?

**Comment by drorata** [comment]
Another possible approach is to check whether the working directory is clean (if there is a git repo) and if it is not clean, fail all `log_*` actions.

**Comment by GCBallesteros** [comment]
@drorata `git stash` alone won't work unfortunately. Lets say you have files `train.py` and `other_project.py`, the latter has been modified and staged while `train.py` has been modified and is unstaged and waiting to be autocommited  when I run it. If I `git stash` everything is hidden and there won't be anything left to commit. What I need is to:

1. Save the the currently staged files, `other_project.py` in the example above.
2. Commit `train.py`
3. Bring back the staged files I had before.

The steps to do this are described in [this stackoverflow question](https://stackoverflow.com/questions/15020237/how-to-save-the-current-state-of-my-staging-area), but that requires an interactive rebase to switch the two commits. [Searching further](https://stackoverflow.com/questions/4981061/how-to-re-order-commits-in-git-non-interactively) I've figured out that you can do the switching of the commits with a `git reset` and `git cherry-pick`. This is the approaching that I'm figuring out right now.

**Comment by GCBallesteros** [comment]
I wasn't seeing the forest for the tree. I can simply commit only the file I want to track.
```
repo.git.add(file_path)
repo.git.commit(file_path, "-m AUTOML")
```

**Comment by drorata** [comment]
@GCBallesteros Can you put together a minimal example how you use this auto-committing alongside the actual tracking?

**Comment by GCBallesteros** [comment]
@drorata I modified the mlflow-examples/train.py to show how the functionality is used. The only change is to the call to start_run. You can see it in the following gist:
https://gist.github.com/GCBallesteros/be0f19a8b2dd216713f9f5d17e248545

Please also find a greatly improved version of autocommit which is used in the gist below:
https://gist.github.com/GCBallesteros/6419f64400097efb0ff506aea0798c71

The improvements include:
- no more cherry picking and resetting craziness
- automatically looks for a repo is non is specified
- can track more than one file
- multiples committing behaviours

**Comment by ankitmathur-db** [comment]
This looks like something that is definitely useful but potentially outside the scope of what's necessary in a framework like MLFlow. Thanks @GCBallesteros for putting in the effort to display your solution!
