### ISSUE TITLE
[BUG] build_docker breaks due to missing pip

### ISSUE THREAD

**Issue by crauterb** [mlflow/mlflow#2713]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes and no - the script for training is from this repo, the infrastructure is set up
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.04
- **MLflow installed from (source or binary)**: Using pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.7.2
- **Python version**: 3.7
- **npm version, if running the dev UI**: -
- **Exact command to reproduce**: `MLFLOW_S3_ENDPOINT_URL=http://localhost:9001 AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 mlflow models build-docker -m s3://mlflow/1/dec0da53101b41539d3e6d9b35403f35/artifacts/model -n mlflow-wine-test`

### Describe the problem
After setting up ML-Flow to run in a Docker Container with MySQL and Minio, I wanted to use the `build-docker` command to build a wrapper for my trained model.
However, the script breaks with the error message, that `pip` can not be found.
this occurs when mlflow is locally (!) trying to build the image container. 
As specified in [models/docker_utils.py](https://github.com/mlflow/mlflow/blob/3253c77f7945b8e26a7c8aed809a4af5b43261b2/mlflow/models/docker_utils.py#L14), it uses Ubuntu 18.04 as a base image and then tries to setup up ML-Flow using `pip`
If I am not mistaken, this procudes the crash, as Ubuntu 18.04 does not contain `pip`.

### Code to reproduce issue
I used [the elasticnet exampe](https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_wine/train.py) to execute a run to generate an according RunId. 
If desired, I am more than happy to provide the according `docker-compose` file, yet I do not think this is the reason for the error - please let me know if I am mistaken :-)

### Other info / logs
Full stack trace of the error:
```
2020/04/16 15:39:28 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2020/04/16 15:39:28 INFO mlflow.models.docker_utils: Building docker image with name mlflow-wine-test
/tmp/tmp2yjjhrsk/
/tmp/tmp2yjjhrsk/model_dir
/tmp/tmp2yjjhrsk/model_dir/model
/tmp/tmp2yjjhrsk/model_dir/model/conda.yaml
/tmp/tmp2yjjhrsk/model_dir/model/model.pkl
/tmp/tmp2yjjhrsk/model_dir/model/MLmodel
Sending build context to Docker daemon   7.68kB

Step 1/17 : FROM ubuntu:18.04
 ---> 4e5021d210f6
Step 2/17 : RUN apt-get -y update && apt-get install -y --no-install-recommends          wget          curl          nginx          ca-certificates          bzip2          build-essential          cmake          openjdk-8-jdk          git-core          maven     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 995b6f92f3dc
Step 3/17 : RUN curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh >> miniconda.sh
 ---> Using cache
 ---> 837336292266
Step 4/17 : RUN bash ./miniconda.sh -b -p /miniconda; rm ./miniconda.sh;
 ---> Using cache
 ---> 5b3c460a6c01
Step 5/17 : ENV PATH="/miniconda/bin:$PATH"
 ---> Using cache
 ---> 7a71b3273f80
Step 6/17 : ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
 ---> Using cache
 ---> 1891b64ce480
Step 7/17 : ENV GUNICORN_CMD_ARGS="--timeout 60 -k gevent"
 ---> Using cache
 ---> c27ed6cb6483
Step 8/17 : WORKDIR /opt/mlflow
 ---> Using cache
 ---> 9dae737b8e0b
Step 9/17 : RUN pip install mlflow==1.7.2
 ---> Running in e5f5c1966c21
/bin/sh: 1: pip: not found
The command '/bin/sh -c pip install mlflow==1.7.2' returned a non-zero code: 127
```

I do hope I am not overseeing something - help is greatly appreciated. :-)

**Comment by dbczumar** [comment]
@crauterb This has been fixed via #2699. We will release MLflow 1.8, which will contain this fix, shortly. 

Duplicate issue for reference: https://github.com/mlflow/mlflow/issues/2691
