### ISSUE TITLE
[DOC-FIX] Broken link on Tutorials and Examples page

### ISSUE THREAD

**Issue by tdhopper** [mlflow/mlflow#2722]
### URL(s) with the issue:

https://www.mlflow.org/docs/latest/tutorials-and-examples/index.html

### Description of proposal (what needs changing):

[The link](https://github.com/mlflow/mlflow/blame/2bc7f80141cc032ebdeb187a912db911aad7e7ec/docs/source/tutorials-and-examples/index.rst#L17) to "Write & Use MLflow Plugins" is broken.

**Comment by dmatrix** [comment]
This has been fixed now.

https://mlflow.org/docs/latest/plugins.html#writing-your-own-mlflow-plugins
