### ISSUE TITLE
[FR] Improve the accessibility of MLflow web UI

### ISSUE THREAD

**Issue by pogil** [mlflow/mlflow#2728]
## Describe the proposal

Address accessibility issues in MLflow web UI found by http://aka.ms/AccessibilityInsights

### Motivation

This will make MLflow web UI more broadly usable by a wide range of users.

### Proposed Changes

The first round of issues we'd like to address are relate to contrast, form labels, aria tags, and titles in iframes.

Experiment runs view:
- WCAG 1.3.1: Ensures elements with an ARIA role that require child roles contain them (.ag-header-row[aria-rowindex="\32 "][role="row"])
- WCAG 1.4.3: Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds (.search-button)
- WCAG 2.4.1: Ensures <iframe> and <frame> elements contain a non-empty title attribute (#mlflow-iframe-id)

Model registry main page:
- WCAG 1.4.3: Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds (.ant-tag-green)
- WCAG 1.3.1,WCAG 3.3.2: Ensures every form element has a label (input)
- WCAG 2.4.1: Ensures <iframe> and <frame> elements contain a non-empty title attribute (#mlflow-iframe-id)

Model registry model page:
- WCAG 1.4.3: Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds (.ant-tabs-tab-active)

For contrast issues, we do have some colors / mocks for buttons and table headers we can share.

**Comment by Zangr** [comment]
Resolved by #2802 #2071 #2872
