### ISSUE TITLE
[FR] AWS Sagemaker Deploy Increase App Name Length for Users

### ISSUE THREAD

**Issue by tallen94** [mlflow/mlflow#2747]
## Describe the proposal
Currently, when deploying a model using the `mlflow sagemaker deploy`, the `--app-name` arg is limited in the length we can provide because there are a lot of random id's concatenated to this value for the `endpoint-config` for example. I ran into this issue:
```
An error occurred (ValidationException) when calling the CreateModel operation: 1 validation error detected: Value 'mfs-hello-model-linregmodel-4d7b3f-model-wabch2xdutjqvabw7y-wd4iq' at 'primaryContainer.containerHostname' failed to satisfy constraint: Member must have length less than or equal to 63
```
With a value for app-name: `hello-model-linregmodel-4d7b3f`. Here I am using the `<experiment_name>-<model_name>-<first6run_id>` to make sure I can correlate the sagemaker endpoints back to a model in MLFlow. While the length of an endpoint-config can be 63 characters, I am limited to half that because there is so much attached to that value `mfs-...-model-wabch2xdutjqvabw7y-wd4iq`.

### Proposed Changes
Make the resulting `endpoint-config` name shorter so I can put more characters in my `app-name`

**Comment by tomasatdatabricks** [comment]
Thanks for posting. The random string is there to enable multiple versions of the same model. We can likely shorten it significantly or develop and more efficient naming scheme.  

@tallen94 would you be interested in contributing this update?

**Comment by tallen94** [comment]
@tomasatdatabricks Sure thing I can help out with the contribution! Can you point me to some code that defines the current specification for naming scheme? I can define some stronger requirements from my side once I get more into how the current implementation works.

**Comment by tallen94** [comment]
I think this is the section that creates the name using a function called `get_unique_resource_id` https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/__init__.py#L609

**Comment by tallen94** [comment]
So off the bat, I think we can make an improvement [here](https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/__init__.py#L842) by only changing the value put into the `ContainerHostname`. As per the [AWS docs](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ContainerDefinition.html#sagemaker-Type-ContainerDefinition-ContainerHostname), it seems like this value only has to be unique within an inference pipeline and I believe in this case each model is a different inference pipeline. 

They also indicate that:
```
 If you don't specify a value for this parameter for a ContainerDefinition that is part of an inference pipeline, a unique name is automatically assigned based on the position of the ContainerDefinition in the pipeline.
```
Since the ContainerHostname is limited to 63 characters, and the value is `mfs-%s`, if we just didnt provide a value, that would free up 4 characters. We wouldnt have to change the logic for creating unique model identifiers yet. I think this value is sort of arbitrary since there is only ever 1 container created by MLFlow when deploying to sagemaker.

@tomasatdatabricks  What are your thoughts?

**Comment by tomasatdatabricks** [comment]
The name definition is in mlflow.sagemaker.__init__.py::_get_sagemaker_model_name.
Context: the uuid is appended so that we can deploy multiple versions of the same model. We can almost surely truncate the uuid or come up with a more efficient mechanism altogether.

**Comment by tomasatdatabricks** [comment]
> So off the bat, I think we can make an improvement [here](https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/__init__.py#L842) by only changing the value put into the `ContainerHostname`. As per the [AWS docs](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ContainerDefinition.html#sagemaker-Type-ContainerDefinition-ContainerHostname), it seems like this value only has to be unique within an inference pipeline and I believe in this case each model is a different inference pipeline.
> 
> They also indicate that:
> 
> ```
>  If you don't specify a value for this parameter for a ContainerDefinition that is part of an inference pipeline, a unique name is automatically assigned based on the position of the ContainerDefinition in the pipeline.
> ```
> 
> Since the ContainerHostname is limited to 63 characters, and the value is `mfs-%s`, if we just didnt provide a value, that would free up 4 characters. We wouldnt have to change the logic for creating unique model identifiers yet. I think this value is sort of arbitrary since there is only ever 1 container created by MLFlow when deploying to sagemaker.
> 
> What is interesting though, is there docs claim
> 
> ```
> This parameter is ignored for models that contain only a PrimaryContainer. 
> ```
> 
> But does not seem to be ignored in this case?
> 
> @tomasatdatabricks What are your thoughts?

Hi @tallen94, sorry I missed your response! I think your plan sounds good. It actually looks like the best approach is to not set the container hostname at all. It either is ignored (as the docs suggest it should be) or a new unique hostname will be automatically generated. Either way should be ok with us.
