### ISSUE TITLE
[DOC-FIX] Better documentation on Keras and TensorFlow Autologging

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#2755]
### URL(s) with the issue:

* https://www.mlflow.org/docs/latest/python_api/mlflow.keras.html#mlflow.keras.autolog
* https://www.mlflow.org/docs/latest/python_api/mlflow.tensorflow.html

### Description of proposal (what needs changing):

We need more complete documentation for the behavior and information saved for both of these autolog methods.

For the TensorFlow page, should add a link to where to find complete logging information.

_Refer to the tracking documentation for information on what is logged with different TensorFlow workflows_ 

Although the Keras page mentions some params, it is not complete. We should have the same link as in above to complete information.

There should be an explanation of the difference betwen keras.autolog() and tensorflow.autolog(). When to use one as opposed to the other? Do they log the same information? Any differences in behavior for these 2 methods using TensorFlow 1x vs TensorFlow 2x?

**Comment by juntai-zheng** [comment]
Agreed - the docs are a bit lacking on this part. I'll open up a PR to improve the docs. Thanks for pointing it out!

**Comment by dbczumar** [comment]
@juntai-zheng Did you get around to filing a PR for this? If not, is it on the backlog?

cc @dmatrix who is willing to contribute here as well

**Comment by juntai-zheng** [comment]
Ah I was planning on doing this later this week, but if @dmatrix wants to take it up feel free to!

**Comment by dmatrix** [comment]
I Will work on it.

**Comment by juntai-zheng** [comment]
Hi @amesar, @dmatrix has updated the docs to be much clearer. I'll close the issue now - let us know if there's anything more to improve on!
