### ISSUE TITLE
Can multiple mlflow registry instances run in parallel?

### ISSUE THREAD

**Issue by raman-nbg** [mlflow/mlflow#2760]
Can multiple instances of mlflow registry run in parallel behind a load balancer or is there anything in the server like a sticky session or a state?

We need the server high available and need at least two instances in parallel.

I couldn't find anything about this in the docs. I also open a [thread on stackoverflow](https://stackoverflow.com/questions/61481147/mlflow-registry-high-availability) but din't get any answer.

**Comment by dmatrix** [comment]
Added comments and answer to the thread on [StackOverflow](https://stackoverflow.com/questions/61481147/mlflow-registry-high-availability/61553326#61553326)

**Comment by ericraymond** [comment]
Can the server be run in active/active (load balancer sends request to any of the running instances)? The above is talking about active-passive (only one server handling requests)

There are edge cases where a stateless system might have problems with multiple writers.
