### ISSUE TITLE
[BUG] Javascript crash plotting metrics (possible 1.8.0 regression)

### ISSUE THREAD

**Issue by evax** [mlflow/mlflow#2763]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix
for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
NixOS 20.03
- **MLflow installed from (source or binary)**:
Source
- **MLflow version (run ``mlflow --version``)**:
1.8.0
- **Python version**:
3.7.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:
Click on a metrics link from a run overview page.

### Describe the problem
Trying to plot some metrics using the web interface results in a `Something went wrong` error page.
This behavior seems to have been introduced by the update to 1.8.0 from 1.7.2 

### Other info / logs
This error is logged in the javascript console:
`TypeError: "e.value.toFixed is not a function"`

**Comment by harupy** [comment]
@evax Does your metrics contain NaN?

**Comment by harupy** [comment]
I got the same issue with metrics that the code below creates.

```python
import mlflow

with mlflow.start_run():
    mlflow.log_metrics({"x": float("nan")}, step=0)
    mlflow.log_metrics({"x": 1}, step=1)
    mlflow.log_metrics({"x": 2}, step=2)
```

**Comment by evax** [comment]
@harupy yes, it does. I remember reading in the docs at some point NaNs were not allowed, but I couldn't find it anymore in the current documentation.

**Comment by harupy** [comment]
The error (`TypeError: "e.value.toFixed is not a function"`) occurs in the line below when calling `toFixed` against `NaN` which doesn't have `toFixed`.

https://github.com/mlflow/mlflow/blob/c006ed9672fd379c150d8444279f4c9e2bf20034/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js#L88

**Comment by harupy** [comment]
I think handling NaN as below should fix the issue.

```javascript
text: history.map((entry) => entry.value === "NaN" ? "NaN" : entry.value.toFixed(5)),
```

**Comment by harupy** [comment]
cc @smurching @dbczumar @Valentyn1997

**Comment by harupy** [comment]
@dbczumar Thanks for the fix!

**Comment by evax** [comment]
Thanks @harupy and @dbczumar!
