### ISSUE TITLE
[FR] Use CircleCI for documentation build

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#2778]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's
[Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Use CircleCI for documentation build.

## Motivation
- What is the use case for this feature?
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

This allows us to view the documentation on the browser (please take a look at the GIF below), which makes it a lot easier to review PRs that affect the documentation.

I captured this on my forked repo: https://github.com/harupy/mlflow/pull/2

![circleci-demo-640](https://user-images.githubusercontent.com/17039389/80857781-80f56800-8c8f-11ea-857c-22a83b1d7042.gif)

## Which MLflow component(s) does this feature affect?

- [ ] UI
- [ ] Command Line Interface
- [ ] API
- [ ] Examples
- [x] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Model Registry
- [ ] Scoring
- [ ] R
- [ ] Java
- [ ] Python

## Details

(Use this section to include any additional information about the feature. If you have a proposal
for how to implement this feature, please include it here. For implementation guidelines, please
refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dbczumar** [comment]
@aarondav @smurching I know you folks were taking a look at alternative build tools as a replacement for Travis. This seems like a good opportunity for exploring CircleCI. Do you have input here?

**Comment by harupy** [comment]
The advantages that I think CircleCI has are:

1. It supports artifact hosting.
2. It displays job statuses separately on GitHub so we can easily identify failed jobs.
3. It has a cleaner config format.
4. We can define a sequence of steps and reuse it across jobs (see [reusing-config](https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands)).

**Comment by dmatrix** [comment]
@harupy Since you are willing to contribute it, can you prioritize it?

**Comment by harupy** [comment]
Addressed by #3142
