### ISSUE TITLE
[BUG] Server gives 404 

### ISSUE THREAD

**Issue by PhilipMay** [mlflow/mlflow#2812]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix
for this bug to the MLflow code base?
- Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Archlinux (what else)
- **MLflow installed from (source or binary)**: source: https://github.com/mlflow/mlflow/commit/a6030d080fd4269c5c1dcc7512a2d7be2777041b
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.8.1.dev0
- **Python version**: 3.7.7
- **Exact command to reproduce**: `mlflow server`

### Describe the problem
When installing mlflow from the pip package (version 1.8.0) I can run `mlflow server` and the server is started and I can connect with the webbrowser. When I install the dev version (`pip install git+https://github.com/mlflow/mlflow.git`) it does start the server but the browser does give me a 404. On the console I can see no errors printed. Currently the last commit in master is this: https://github.com/mlflow/mlflow/commit/a6030d080fd4269c5c1dcc7512a2d7be2777041b

**Comment by dbczumar** [comment]
@PhilipMay When installing / developing MLflow from source, the UI needs to be started manually with `npm` via:

```
cd mlflows/server/js && npm install && npm start
```

**Comment by PhilipMay** [comment]
Yes thanks. That helps me. But what do I have to do to test the python server functionality?

**Comment by PhilipMay** [comment]
Well - closing it.
