### ISSUE TITLE
[BUG] mlflow server logs secrets on first startup

### ISSUE THREAD

**Issue by hajapy** [mlflow/mlflow#2832]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian Buster
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: `mlflow server --backend-store-uri postgresql://username:password@host:port/name`

### Describe the problem
The first time an mlflow server is started, tables are created and the database is updated to prepare it for use. This triggers this line: https://github.com/mlflow/mlflow/blob/8e6b27dbc3370d9fc0e550d6bbaf00a7b7feb0be/mlflow/store/db/utils.py#L124

Unfortunately, this means the log output contains the full text of the engine.url, including the database username and password, which is secret information and shouldn't appear in plaintext log files. 

Expected behaviour: sensitive information should either be masked or excluded.

I traced into sqlalchemy code and found that the URL object contained within the engine behaves differently when str() or repr()'ed: https://github.com/sqlalchemy/sqlalchemy/blob/3ab5e3781b9f44d458cb6213e89f50d01ea167dd/lib/sqlalchemy/engine/url.py#L105-L109

With str-formatting, it does not hide passwords, whereas with repr it does.

I'm happy to contribute a fix, of which I see a few options:

- Drop including the url in this log statement
- Move the url to a debug statement
- Use repr instead of str for formatting

### Code to reproduce issue
Create an server backed by a SQL database using `mlflow server --backend-store-uri <uri>`, observe the log output: "Updating database tables at <postgresql://user:password@host:port/name>"

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by sueann** [comment]
> * Drop including the url in this log statement
> * Move the url to a debug statement
> * Use repr instead of str for formatting

The first or the third one makes sense to me. I think we have previously done the dropping of the URL in other places, but if `repr` works nicely in redacting that'd be cool to see. Thanks for proposing a solution; please feel free to submit a PR!
