### ISSUE TITLE
[DOC-FIX]

### ISSUE THREAD

**Issue by OlivierBondu** [mlflow/mlflow#2835]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:
https://www.mlflow.org/docs/latest/tracking.html#artifact-stores

### Description of proposal (what needs changing):
Amazon S3 is in fact generic S3 storage. I need on-prem storage and first disregarded this option, until after reading more careully I discovered on-prem S3 exists, and is supported (with MinIO as in the example). 
I think some renaming / reordering would be great

**Comment by ankitmathur-db** [comment]
@OlivierBondu could you make a PR with what specifically you would like the docs to say? It's not clear to me what is misleading about our docs

**Comment by OlivierBondu** [comment]
@ankitmathur-db : please see the PR refered in the thread. The changes are quite minimal but would have saved me overlooking this section at first.

**Comment by ankitmathur-db** [comment]
Thanks for submitting the PR @OlivierBondu - will take a look on Monday
