### ISSUE TITLE
[DOC-FIX] - projects.run() - Missing docstring entries - 'parameters' and 'docker_args'

### ISSUE THREAD

**Issue by jkthompson** [mlflow/mlflow#2840]
### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [] Yes. I can contribute a documentation fix independently.
- [x ] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:
https://github.com/jkthompson/mlflow/blob/edb5585233f18f9f4e306901e1b5cf6bc013260f/mlflow/projects/__init__.py#L221-L222

### Description of proposal (what needs changing):
Documentation for `parameters` and `docker_args` are missing.  Propose to copy/paste from CLI help messages.  https://github.com/jkthompson/mlflow/blob/edb5585233f18f9f4e306901e1b5cf6bc013260f/mlflow/cli.py#L49-L55

**Comment by sueann** [comment]
Makes sense to me. Please feel free to create a PR. Thanks!
