### ISSUE TITLE
[FR] Set content type and encoding on logged artifacts (s3)

### ISSUE THREAD

**Issue by hajapy** [mlflow/mlflow#2855]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Allow content metadata to be set (by caller) by log_artifact calls for the S3ArtifactRepository, and guess the type if not given.

## Motivation
Currently, all artifacts are treated as binary/octet-stream in s3. This means our browsers are unable to help view the artifacts even if they are eg. images, or text files, or other files they can display nicely -- they will always just download. This applies to pre-signed urls generated for these objects, so generally including these in any web interfaces leads to a poor user experience. 

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details
There is a relatively simple solution if we only want to tackle s3, but there are potential design considerations if this would be extended beyond s3, so I would like some input before opening a PR. One approach to this would be:

1. Extend log_artifact signature to allow extra, optional kwargs: content_type, content_encoding.
2. If given, respect the given values, and set these in the ExtraArgs dict: https://github.com/mlflow/mlflow/blob/18eacdd9bde4e693942ff94882fb3da322b593c0/mlflow/store/artifact/s3_artifact_repo.py#L53-L57

We would merge these values with those given by `get_s3_file_upload_extra_args()`. 

3. If not given, use stdlib `mimetypes.guess_type` to guess these values, and set them:

```
content_type, content_encoding = guess_type(local_file)
if content_type is not None:
    extra_args['ContentType'] = content_type
if content_encoding is not None:
    extra_args['ContentEncoding'] = content_encoding
```

The open questions are:

- Is this change the log_artifact signature acceptable?
- Can the behaviour be to always guess the content type (awscli does this for cp command)?
- Would adding this to s3 necessitate doing so for other artifact repository types?

**Comment by smurching** [comment]
@hajapy thanks for the feature request & writeup of the options!

Guessing the content type using `mimetypes.guess_type` seems like a reasonable approach to me, as you mentioned I don't think we'd want to add extra `content_type` etc arguments to `log_artifact` as not all artifact stores support a notion of a `content_type`. I think it's also alright if this behavior is S3 specific, we can extend support to other artifact stores (at least the ones that support a notion of content type) in the future.

One question for you though is whether we could handle this on the UI-side itself (and if not, why not) - we currently to [guess the content type](https://github.com/mlflow/mlflow/blob/18eacdd9bde4e693942ff94882fb3da322b593c0/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.js#L27-L36) of the file in the UI based on the file extension, and this seems to work for other artifact stores (e.g. DBFS). Is there a reason it doesn't work for S3?

**Comment by hajapy** [comment]
Ah, interesting point that the ui already does some of this. I didn’t notice because the test file I created lacked a supported extension. 

Reasons to still consider doing this:
- having the metadata stored on the actual backend store is generally more useful to other applications or systems that may want to read from that location (ex: browsing s3 artifact location with aws console)
- it might be possible for the ui layer to also read this metadata and only fall back to its own guessing logic when the metadata is not there. As a file browser it would be superior to have more types supported even if there is no built-in viewer for each type

Thoughts?

**Comment by smurching** [comment]
@hajapy agree that having additional content-type metadata in S3 seems strictly more useful than not having it - would be happy to review a PR that adds support for inferring content types to the S3 artifact repository. Thanks for bringing this up!

**Comment by hajapy** [comment]
@smurching PR opened: https://github.com/mlflow/mlflow/pull/2881
