### ISSUE TITLE
[BUG]Registry UI Workflow Not Working As Documented

### ISSUE THREAD

**Issue by nayaks** [mlflow/mlflow#2863]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.6
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: 1.8
- **Python version**: 3.7.2
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
I have been trying out the MLFlow sample at https://github.com/mlflow/mlflow-example/blob/master/train.py. When I open the Registry UI, it doesn't have the features to request the promotion of a registered model, as stated in the opensource documentation. Generally speaking, it seems to be missing all collaboration features.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by smurching** [comment]
@nayaks thanks for filing! As you mentioned, only direct stage transitions are currently supported via the UI.

Some implementations of the MLflow REST API (e.g. the managed MLflow server in Databricks) contain extensions like stage transition requests, but this is not yet a standard part of the API spec. In particular, note that the server currently has no notion of users with which to associate stage transition requests (or manage permissions on who can create/approve transition requests) - thus I think a prerequisite might be for us to aim to solve #724, which we're happy to discuss & review proposals for.

Let me know if you have any questions, thanks!

**Comment by nayaks** [comment]
Thank you Siddharth (@smurching ). I am curious about the screen shots in the documentation that show labels like "Request Transition to Staging" and "Request Transition to Production". Is this feature only available in the licensed version of MLFlow bundled with Databricks.

Regards,
Sameer

**Comment by dmatrix** [comment]
Those are old images. We fixed it and pushed the docs again. If you try it again, you won't see the 
"Request for transition" images any [more](https://mlflow.org/docs/latest/model-registry.html#ui-workflow).

**Comment by nayaks** [comment]
Thanks for the update. Please go ahead and close this.
