### ISSUE TITLE
Unsupported pickle protocol in model serving

### ISSUE THREAD

**Issue by fclesio** [mlflow/mlflow#288]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Yes.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacBook Pro - macOS High Sierra - Version 10.13.4 - 2,3 GHzIntel Core i5, 16Gb memory
- **MLflow installed from (source or binary)**: 
`pip install mlflow`
- **MLflow version (run ``mlflow --version``)**:
`mlflow, version 0.4.2`
- **Python version**: 
`Python 2.7.15`
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
`mlflow sklearn serve /Python/mlruns/0/01ba40fe5fbb4942a6a37b62c77b8fcc/artifacts/model_random_forests -p 1234`

### Describe the problem
When I go to make the servicing of the model using the following command I receive an error - Error: `ValueError: unsupported pickle protocol: 3`

### Source code / logs
*Logs*
```
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mlflow/sklearn.py", line 102, in serve_model
    model = load_model(run_id=run_id, path=model_path)
  File "/Library/Python/2.7/site-packages/mlflow/sklearn.py", line 78, in load_model
    return _load_model_from_local_file(path)
  File "/Library/Python/2.7/site-packages/mlflow/sklearn.py", line 64, in _load_model_from_local_file
    return pickle.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 886, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
```

*Code*
```
# In[2]:
import warnings
warnings.filterwarnings("ignore")

get_ipython().run_line_magic('matplotlib', 'inline')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn import cross_validation
from sklearn import metrics
from sklearn import preprocessing
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Perceptron
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import ElasticNet

# Data
df = pd.read_csv('https://raw.githubusercontent.com/fclesio/learning-space/master/Datasets/02%20-%20Classification/default_credit_card.csv')

# Split the data into training and test sets. (0.75, 0.25) split.
train, test = train_test_split(df)

# The predicted column is "quality" which is a scalar from [3, 9]
train_x = train.drop(["DEFAULT"], axis=1)
test_x = test.drop(["DEFAULT"], axis=1)
train_y = train[["DEFAULT"]]
test_y = test[["DEFAULT"]]

# Convert Pandas datasets to numpy arrays 
train_x = train_x.as_matrix()
test_x = test_x.as_matrix()
train_y = train_y.as_matrix()
test_y = test_y.as_matrix()

# Standardize the data attributes
train_x = preprocessing.scale(train_x)
test_x = preprocessing.scale(test_x)

# Set seed
np.random.seed(12345)


# In[3]:


# RandomForestClassifier
n_estimators = [500, 1000, 3000]
min_samples_splits = [50, 100, 500]
max_depths = [10, 20, 50]

for n_estimator in n_estimators:
    for min_samples_split in min_samples_splits:    
        for depth in max_depths:
            with mlflow.start_run():
                
                lr = RandomForestClassifier(n_estimators=n_estimator, 
                                            min_samples_split=min_samples_split,
                                            max_depth=depth)
            
                lr.fit(train_x, train_y)
                accuracy = lr.score(test_x, test_y)

                predicted_qualities = lr.predict(test_x)


                print("Random Forest model (n_estimators=%f, min_samples_split=%f, max_depth=%f):" % (n_estimator,min_samples_split,depth))
                print("Accuracy: %s" % round((accuracy * 100),2))

                # Logging in mlflow to appears in UI
                mlflow.log_param("n_estimators", n_estimator)
                mlflow.log_param("min_samples_split", min_samples_split)
                mlflow.log_param("max_depth", depth)
                
                mlflow.log_metric("accuracy", accuracy)
                mlflow.sklearn.log_model(lr, "model_random_forests")


# In[4]:


# ExtraTreesClassifier
n_estimators = [1000, 3000]
max_depths = [20, 30]
min_samples_leafs = [20, 50]

for n_estimator in n_estimators:
    for min_samples_leaf in min_samples_leafs:    
        for depth in max_depths:
            with mlflow.start_run():
                
                lr = ExtraTreesClassifier(n_estimators=n_estimator, 
                                          min_samples_leaf=min_samples_leaf,
                                          max_depth=depth)
            
                lr.fit(train_x, train_y)
                accuracy = lr.score(test_x, test_y)

                predicted_qualities = lr.predict(test_x)

                print("Gradient Boosting model (n_estimators=%f, min_samples_leaf=%f, max_depth=%f):" % (n_estimator, min_samples_leaf, depth))
                print("Accuracy: %s" % round((accuracy * 100),2))

                # Logging in mlflow to appears in UI
                mlflow.log_param("n_estimators", n_estimator)
                mlflow.log_param("min_samples_leaf", min_samples_leaf)
                mlflow.log_param("max_depth", depth)
                
                mlflow.log_metric("accuracy", accuracy)
                mlflow.sklearn.log_model(lr, "model_extratrees_classifier")            


# In[5]:


# LogisticRegression
penalties  = ['l2']
fit_intercepts = [False, True]
Cs = [0.03, 0.02, 0.01, 0.005, 0.004, 0.003, 0.002, 0.001]
solvers = ['newton-cg', 'sag', 'saga', 'lbfgs']

for penalty in penalties:
    for fit_intercept in fit_intercepts:    
        for C in Cs:
            for solver in solvers:
                with mlflow.start_run():
                    lr = LogisticRegression(penalty=penalty,
                                        fit_intercept=fit_intercept,
                                        C=C,
                                        solver=solver)
            
                    lr.fit(train_x, train_y)
                    accuracy = lr.score(test_x, test_y)

                    predicted_qualities = lr.predict(test_x)

                    print("Accuracy: %s" % round((accuracy * 100),2))

                    # Logging in mlflow to appears in UI
                    mlflow.log_param("penalty", penalty)
                    mlflow.log_param("fit_intercept", fit_intercept)
                    mlflow.log_param("C", C)

                    mlflow.log_metric("accuracy", accuracy)
                    mlflow.sklearn.log_model(lr, "model_logistic_regression")
```

**Comment by smurching** [comment]
Hi @fclesio, thanks for reporting this issue - we've seen this kind of failure before when attempting to load a model trained in Python 3 in a Python 2 environment (pickle protocol 3 is only available in Python >=3). #230 adds warnings for this case, and #225 aims to help address the issue by using the `conda_env` specified when exporting the model to load it back in. 

For now, would you be able to check if the cause is indeed Python version incompatibility (i.e. your notebook is running in Python 3 while you have Python 2 locally)? You can check via `import sys; print(sys.version)` in your notebook / local Python console. Thanks!

**Comment by fclesio** [comment]
@smurching even changing the default with Python3, the error still continues:

Python Version
```
➜  artifacts git:(master) python
Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version)
3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)]
```

**Command**: 
```
mlflow sklearn serve Python/mlruns/mlruns/0/01ba40fe5fbb4942a6a37b62c77b8fcc/artifacts/model_random_forests -p 1234```

**Logs**
```
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mlflow/sklearn.py", line 102, in serve_model
    model = load_model(run_id=run_id, path=model_path)
  File "/Library/Python/2.7/site-packages/mlflow/sklearn.py", line 78, in load_model
    return _load_model_from_local_file(path)
  File "/Library/Python/2.7/site-packages/mlflow/sklearn.py", line 64, in _load_model_from_local_file
    return pickle.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 886, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
```

**Comment by smurching** [comment]
@fclesio it looks like your MLflow executable in `/usr/local/bin/mlflow` may still be invoking Python 2 under the hood (we can see from the stacktrace that it's loading packages from `Library/Python/2.7/`), even though your `python` executable is Python 3.

You can see which python `mlflow` is configured to use via `cat $(which mlflow)`. For example, I have a shebang at the top of the output that looks like: 
```
#!/Users/sid/miniconda3/bin/python
```

Running `/Users/sid/miniconda3/bin/python --version` I can see that `mlflow` is running with Python 3.

One suggestion is to reinstall MLflow via `pip uninstall mlflow` and `pip install mlflow`, which should remove & recreate `/usr/local/bin/mlflow`. If that still doesn't work (e.g. potentially because you're in a conda environment with a `pip` that doesn't know about scripts in `/usr/local/bin/mlflow`), I'd recommend removing `/usr/local/bin/mlflow` & then reinstalling MLflow.

**Comment by fclesio** [comment]
@smurching for me worked after the `uninstall` as you requested and delete the folder `/usr/local/bin/mlflow` and reinstall again.

Another thing it's for me worked when I installed using `pip3 install mlflow`.

Thanks!
