### ISSUE TITLE
[BUG] Run fails if set_experiment() is used in the code

### ISSUE THREAD

**Issue by egusev** [mlflow/mlflow#2887]
**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [*] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no + use the provided example from `examples/tensorflow/tf2`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Ubuntu 18.04.4 LTS` `Linux gpu-host1 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**:  `mlflow, version 1.8.0`
- **Python version**: `Python 3.7.7`
- **npm version, if running the dev UI**: n/a
- **Exact command to reproduce**: `mlflow run .`

### Describe the problem
mlflow cli run starts failing once I have set an experiment name in the code

### Code to reproduce issue
I have used example for tensorflow 2 by adding this line: 
`mlflow.set_experiment("test")`
tried before and after `mlflow.tensorflow.autolog()` -- the same result

### Other info / logs
Error message:

```
INFO: 'test' does not exist. Creating a new experiment
Traceback (most recent call last):
  File "train_predict_2.py", line 172, in <module>
    main(sys.argv)
  File "train_predict_2.py", line 75, in main
    with mlflow.start_run():
  File "/home/users/eugene/.conda/envs/mlflow-abcd0c6f7d0b18ba2cbd2defa219b14e8100f8a8/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 130, in start_run
    "arguments".format(existing_run_id))
mlflow.exceptions.MlflowException: Cannot start run with ID 49e3c3217f274f40837484841e794090 because active run ID does not match environment run ID. Make sure --experiment-name or --experiment-id matches experiment set with set_experiment(), or just use command-line arguments
2020/05/28 13:12:42 ERROR mlflow.cli: === Run (ID '49e3c3217f274f40837484841e794090') failed ===
```

Actually it would be awesome to have a priority list for the experiment name something like that:
1. run parameter (-experiment-name)
2. (it seems it is a feature request) a parameter of entry_point in MLproject
3. environment variable (MLFLOW_EXPERIMENT_NAME)
4. `mlflow.set_experiment` method

**Comment by dmatrix** [comment]
The current supported behavior for MLflow projects is to define the experiment name or id (if you know the id) using mlflow cli. 

It would require systemic change in the way MLflow projects are executed since `mlflow run` CLI command will create a main run (under --experiment-name argument or default). The nested run created in main with start_run needs to belong to the same parent experiment.

The only supported models is use `--experiment-name ` or `--experiment-id` in CLI command if you want log under a specific experiment.

You can now run it as : `mlflow run . --experiment-name test`
