### ISSUE TITLE
[BUG] MlflowClient do not respect tracking_uri

### ISSUE THREAD

**Issue by azachar** [mlflow/mlflow#2888]
Hello, 

I am trying to execute the official examples of integrating with azureml  (https://github.com/Azure/MachineLearningNotebooks/blob/79940/how-to-use-azureml/track-and-monitor-experiments/using-mlflow/deploy-model/deploy-model.ipynb) and I am unable to build an image, basically, I am getting this error:

```
model_path = "model"

azure_image, azure_model = mlflow.azureml.build_image(model_uri='runs:/{}/{}'.format(run.id, model_path),
                                                      workspace=ws,
                                                      model_name='pytorch_mnist',
                                                      image_name='pytorch-mnist-img',

```

**`API request to endpoint /api/2.0/mlflow/runs/get failed with error code 401 != 200`**

I would assume since the run was done on azureml and the run went well on azureml, that this URL is wrong. Moreover it seems to me that mlflow.tracking.MlflowClient is not respecting the tracking uri, because `/api/2.0/mflow...` seems like a local one instead of azure based uri. 

Could you please advice how to change that URI to the correct one?

Thank you.

PS: I am running on azure-mlflow 1.6.0 (e.g. the latest).

**Comment by dmatrix** [comment]
Following the above [notebook link](https://github.com/Azure/MachineLearningNotebooks/blob/79940/how-to-use-azureml/track-and-monitor-experiments/using-mlflow/deploy-model/deploy-model.ipynb), it seems setting the tracking URI, few cell above the failing call to azuml backend, was executed incorrectly. Therefore, it resorts to the local mode or local tracking URI.

Just as a note, this working example is part of the Azure ML notebook. You might want to set or investigate you connections to Azure ML workspace.

cc: @akshaya-a @trangevi

**Comment by azachar** [comment]
Thank you for your quick response.

I was playing a lot with it, trying to set the tracking url again and again and it was partially using. Seems like the store only got local mode. No idea why. What helped was restarting the kernel and running it again and voila it works normally.

Best regards,
Andrej

**Comment by dmatrix** [comment]
Excellent! I shall close this then.
