### ISSUE TITLE
[FR] adding Tags and Notes to Experiments with API

### ISSUE THREAD

**Issue by PhilipMay** [mlflow/mlflow#2893]
I would like to be able to add tags and notes on experiment level with the API. Would this be useful for others too?

Thanks
Philip

**Comment by mparkhe** [comment]
Use this [REST API](https://mlflow.org/docs/latest/rest-api.html#mlflowmlflowservicesetexperimenttag) or [mlflow.set_experiment_tag](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.set_experiment_tag) for python.

You can create experiment notes in UI.
