### ISSUE TITLE
[BUG] When logging metrics over time, the first value is shown in the UI

### ISSUE THREAD

**Issue by Ben-Epstein** [mlflow/mlflow#2894]
**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**:  Source
- **MLflow version (run ``mlflow --version``)**: 1.6.0
- **Python version**: 3.7.3
- **Exact command to reproduce**:
```
with mlflow.start_run(run_name='example of bad metrics'):
    for i in range(10):
        mlflow.log_metric('quality', i*0.5, step=i)
```

### Describe the problem
With the above code, the first metric value (0) is shown in the UI, not the last (5). This should be the last so when comparing multiple runs, you can compare how the "final" models performed.

### Code to reproduce issue
As above

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [X ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by mparkhe** [comment]
Hi @Ben-Epstein,

What version of mlflow are you using? I tried to reproduce this with your code with some logs

```
>>> with mlflow.start_run(run_name='example of bad metrics'):
...     print("Active run: {}".format(mlflow.active_run().info))
...     for i in range(10):
...         metric_value = i*0.5
...         print("logging metric value {} and step {}".format(metric_value, i))
...         mlflow.log_metric('quality', metric_value, step=i)
...
Active run: <RunInfo: artifact_uri='./mlruns/0/a8312c52d9504a849a9f6bfcb0dee9ef/artifacts', end_time=None, experiment_id='0', lifecycle_stage='active', run_id='a8312c52d9504a849a9f6bfcb0dee9ef', run_uuid='a8312c52d9504a849a9f6bfcb0dee9ef', start_time=1590812021718, status='RUNNING', user_id='mani'>
logging metric value 0.0 and step 0
logging metric value 0.5 and step 1
logging metric value 1.0 and step 2
logging metric value 1.5 and step 3
logging metric value 2.0 and step 4
logging metric value 2.5 and step 5
logging metric value 3.0 and step 6
logging metric value 3.5 and step 7
logging metric value 4.0 and step 8
logging metric value 4.5 and step 9
```

Test using API
```
>>> c = mlflow.tracking.client.MlflowClient()
>>> c.get_run("a8312c52d9504a849a9f6bfcb0dee9ef").data
<RunData: metrics={'quality': 4.5}, params={}, tags={'mlflow.runName': 'example of bad metrics',
 'mlflow.source.git.commit': '03f9c82e3ed2915e2dfc6cb2d32ee49c04be84f2',
 'mlflow.source.name': '',
 'mlflow.source.type': 'LOCAL',
 'mlflow.user': 'mani'}>
```

Main experiment page
![image](https://user-images.githubusercontent.com/6900999/83319271-d3c03200-a1f1-11ea-8aa0-bcd3b542f1e1.png)
![image](https://user-images.githubusercontent.com/6900999/83319275-e0448a80-a1f1-11ea-951c-ef5321a607f3.png)

Clicking into the run
![image](https://user-images.githubusercontent.com/6900999/83319282-f5b9b480-a1f1-11ea-8b31-f753fb019b9f.png)
![image](https://user-images.githubusercontent.com/6900999/83319310-3e716d80-a1f2-11ea-939d-4d49f8e72f31.png)

--
Can you try with latest version and copy-paste the UI screenshots?

**Comment by Ben-Epstein** [comment]
@mparkhe Thanks for your reply! Running mlflow 1.6.0 (in description). Very strange, do you have any suggestions for places to look? Maybe the `LATEST_METRICS` table? Obviously the other data is there because I have the graph of the metric changing over time as well.

**Comment by hajapy** [comment]
This seems to be a basic misunderstanding of range: https://docs.python.org/3.8/library/stdtypes.html#typesseq-range

The last value in range(10) is 9, not 10, so the last metric value you should expect is 4.5 not 5.

**Comment by Ben-Epstein** [comment]
@hajapy the value that's showing up in my UI is 0 (the first metric logged).

**Comment by dmatrix** [comment]
@Ben-Epstein where are we with this issue. It seems @mparkhe could not reproduce it. The UI shows the last value of `quality` logged and displayed correctly. I did the same I got the same value. I'm using the current version of 1.8.

![Screen Shot 2020-06-09 at 6 16 28 PM](https://user-images.githubusercontent.com/1117597/84216125-65932f00-aa7d-11ea-9b08-34a62e783c18.png)

Can we close this issue?

**Comment by Ben-Epstein** [comment]
@dmatrix I am still experience the problem, but I think that is due to my Tracking Store plugin. I will close, thanks for the help!
