### ISSUE TITLE
[FR] Run Docker with -t argument

### ISSUE THREAD

**Issue by Zethson** [mlflow/mlflow#2898]
**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Please enable the -t flag for docker run.

## Motivation
To enable colored output inside a run Docker container I need the `-t` flag. This requires a tty.

Colored output is very helpful to discern status and error messages when training models.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

The corresponding code is here: https://github.com/mlflow/mlflow/blob/6ef63a7f33ebfe3481ea57cacd94a8a32fc7efd8/mlflow/projects/__init__.py#L528

The cmd needs to (optionally) expand from `docker run --rm` to `docker run --rm -t`

**Comment by Zethson** [comment]
I am willing to contribute, but would like some response from the developers first.

Do you guys give me green light for this feature?

**Comment by ankitmathur-db** [comment]
Hey @Zethson! Thanks for bringing this up - @dbczumar for context

**Comment by dbczumar** [comment]
Hi @Zethson . I think adding the `-t` flag makes sense. Can you file a PR for this? More than happy to review it!
