### ISSUE TITLE
MLFLOW_CONDA_HOME Window 10 issue  Could not find Conda executable at C:\Programdata\Anaconda3\bin/conda. Ensure Conda is installed as per instructions.

### ISSUE THREAD

**Issue by makeitai** [mlflow/mlflow#2903]
MLFLOW_CONDA_HOME Window 10 issue  
Could not find Conda executable at C:\Programdata\Anaconda3\bin/conda. Ensure Conda is installed as per instructions.

**Comment by makeitai** [comment]
[#2674](https://github.com/mlflow/mlflow/issues/2674) Issue already exists feel free to delete this.

**Comment by apurva-koti** [comment]
Hello! Conda is used to install dependencies for `mlflow run` by default. You can use the `--no-conda` option to avoid this.
https://www.mlflow.org/docs/latest/quickstart.html#running-mlflow-projects
