### ISSUE TITLE
Compile protobuf to Scala code failed with scalapb

### ISSUE THREAD

**Issue by huafengw** [mlflow/mlflow#291]
I'm trying to compile `service.proto` into Scala code with ScalaPB plugin, but encountered following errors: 

```
[error] /Users/huafengw/workspace/mlp/spark-udf/target/scala-2.11/src_managed/main/com/databricks/api/proto/mlflow/CreateExperiment.scala:16: object rpc is not a member of package com.databricks
[error]     ) extends scalapb.GeneratedMessage with scalapb.Message[CreateExperiment] with scalapb.lenses.Updatable[CreateExperiment] with com.databricks.rpc.RPC[$this.Response] {
```

Looks like the trait `com.databricks.rpc.RPC` is missing. So does it mean that the current protobuf files in MLflow depends on some Databricks' private protobuf compiler or some extra artifacts? How should I get these files compiled?

**Comment by andrewmchen** [comment]
Hi! It does depend on a special RPC trait which is defined in our Databricks source code. It looks like this

```
package com.databricks.rpc

trait RPC[T]
```
