### ISSUE TITLE
Can't use `mlflow run` with git branch feature

### ISSUE THREAD

**Issue by tienthegainz** [mlflow/mlflow#2933]
Hi, I'm new to `mlflow`. I'm trying to run project on specific branch. I find that mlflow support this feature but I can't found any document about this. 
In my git repo, each model have its own branch. And I want to run them from master branch. Is this possible? Thanks.

**Comment by smurching** [comment]
Hi @tienthegainz, you should be able to specify the git branch of your code to run using the `version` argument to `mlflow run` (e.g. `mlflow run <your-project-uri> --version <desired-branch-name>`). See the [CLI docs](https://www.mlflow.org/docs/latest/cli.html#mlflow-run) and [Python API docs](https://www.mlflow.org/docs/latest/projects.html) for more details, & let me know if that works!

**Comment by juntai-zheng** [comment]
Closing this issue for now - feel free to reopen if you encounter any problems!
