### ISSUE TITLE
Question - Related to --backend-store-uri --default-artifact-root

### ISSUE THREAD

**Issue by sackh** [mlflow/mlflow#2953]
Hi,
I am trying to use both `--backend-store-uri ` and `--default-artifact-root` for mlflow plugin.
I have to run the `mlflow server` command in order to use both.
Is it possible to use both without running the server?
Please let me know.

**Comment by AveshCSingh** [comment]
Hi @sackh. You should not need to run the `mlflow server` to specify a `backend-store-uri` and `default-artifact-root`. You can set the backend-store-uri for the client by calling mlflow.set_tracking_uri or setting the MLFLOW_TRACKING_URI environment variable, and can set the artifact location in [create_experiment](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.create_experiment).
