### ISSUE TITLE
[BUG] Higher-order function causes crash when pickling MlFlowClient

### ISSUE THREAD

**Issue by Polyphenolx** [mlflow/mlflow#2954]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
I'm running on MLFlow installed from PyPi, but more relevant env info can be found below:

```
Linux Pop!_OS 20.04
Python 3.6.10 :: Anaconda, Inc.

mlflow==1.8.0
pytorch-lightning==0.7.6
torch==1.5.0
torchvision==0.2.1
```

### Describe the problem
This problem arises when pickling `MlFlowClient` objects and results in a pickling error due to the use of a higher order function within `mlflow/tracking/_tracking_service/utils.py` in the `_get_rest_store(store_uri, **_)` function. There are other implementations of pickle that can handle lambda/higher order functions (e.g. Dill, CloudPickle), but  Python's built-in pickle library can not handle these methods. 

This becomes _extremely_ problematic when using MLFlow in conjunction with 3rd party packages. One such example is Pytorch-Lightning, where they have implemented a [wrapper](https://github.com/PyTorchLightning/pytorch-lightning/issues/630) for the MlFlowClient that ends up getting pickled during distributed applications (specifically using the DistributedDataParallel or `DDP` torch backend).

### Code to reproduce issue
A minimal example for reproducing this issue that mirrors how Pytorch-Lightning configured their wrapper can be found in this [gist](https://gist.github.com/Polyphenolx/1b3970fe10ba70748204cd45b0f75139). Of course, wrapping the `MlFlowClient` is completely unnecessary for the reproduction of this bug- simply pickle and `MlFlowClient` object.

### Other info / logs
```
>> python mlflow_pickle_error.py
Traceback (most recent call last):
  File "mlflow_test.py", line 14, in <module>
    pickle.dump(cls, open('test_dump.pkl', 'wb'))
AttributeError: Can't pickle local object '_get_rest_store.<locals>.get_default_host_creds'
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### Proposed Solution

The pickle issue can be resolved by modifying `_get_rest_store` and removing/renaming the higher-order function, and using a partial to wrap the function call (Note: This requires adding `from functools import partial`). After making the changes below, the gist can run without issue. I'd be more than happy to open a PR and follow the proper protocols to contribute this fix if it is deemed acceptable.

```
def _get_default_host_creds(store_uri):
    return rest_utils.MlflowHostCreds(
        host=store_uri,
        username=os.environ.get(_TRACKING_USERNAME_ENV_VAR),
        password=os.environ.get(_TRACKING_PASSWORD_ENV_VAR),
        token=os.environ.get(_TRACKING_TOKEN_ENV_VAR),
        ignore_tls_verification=os.environ.get(_TRACKING_INSECURE_TLS_ENV_VAR) == 'true',
        client_cert_path=os.environ.get(_TRACKING_CLIENT_CERT_PATH_ENV_VAR),
        server_cert_path=os.environ.get(_TRACKING_SERVER_CERT_PATH_ENV_VAR),
    )

def _get_rest_store(store_uri, **_):
    return RestStore(partial(_get_default_host_creds, store_uri))
```

#### Output After Implementing Proposed Solution

```
>> python mlflow_pickle_error.py

Process finished with exit code 0
```

**Comment by dbczumar** [comment]
This has been fixed by #2955 . Thanks @Polyphenolx !
