### ISSUE TITLE
[BUG] `mlflow.search_runs` does not raise error or warning when passed invalid `order_by` expression

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#2976]
`mlflow.search_runs` does not raise error or warning when passed invalid `order_by` expression. I think this behavior is dangerous. Let's consider a scenario where a user wants to select the best model from a bunch of runs and writes the code below:

```python
order_by = ["metrics.accuracy DECS"]  # "DECS" is a typo, should be "DESC"
sorted_runs = mlflow.search_runs(..., order_by=order_by)
best_run = sorted_runs.iloc[0]  # select the frist row
best_model = load_model_from_run(best_run)
```

What this code does is:
- The `order_by` expression `"metrics.accuracy DECS"` doesn't end with ` desc` or ` asc` so it's parsed as a metric named `accuracy DECS`.
- `search_runs` sorts runs by the metric `accuracy DECS` which doesn't exist and returns unsorted runs.
- `sorted_runs.iloc[0]` is obviously not the best run, **but no error or warning is raised**.

**Comment by ankitmathur-db** [comment]
I think this is because we attempt to parse ASC or DESC from the oder by clause, but we default to `is_ascending=True` if we can't parse something valid from it

I can take this one
