### ISSUE TITLE
[BUG] mlflow version is not fixed in default conda env

### ISSUE THREAD

**Issue by eavidan** [mlflow/mlflow#2979]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.15.2
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.5.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow.sklearn.log_model(lr, "model")

### Describe the problem
When loging any kind of supported model, `mlflow` is added as a pip dependency to the `conda.yaml`. The issue is that it is added without any fixed version, which results in the conda env having the latest `mlflow` version even if the training environment had an older one.

### Code to reproduce issue
Any log model function uses `_mlflow_conda_env()` which adds the version less `mlflow` pip dependency.

https://github.com/mlflow/mlflow/blob/10f336a0c86cbabab3089fdfc3943884d2f807ca/mlflow/utils/environment.py#L13-L14

https://github.com/mlflow/mlflow/blob/10f336a0c86cbabab3089fdfc3943884d2f807ca/mlflow/utils/environment.py#L31-L32

for instance, the following code

```python
mlflow.sklearn.log_model(lr, "model")
```

will results in the following `conda.yaml`
```yaml
channels:
- defaults
dependencies:
- python=3.6.10
- scikit-learn=0.22.1
- pip:
  - mlflow
  - cloudpickle==1.4.1
name: mlflow-env
```

a simple fix would be to infer `mlflow` version similar to what is done with other dependencies. for instance:

https://github.com/mlflow/mlflow/blob/6e60e79a593fed2ff5a08aa637a79354bee1be0e/mlflow/sklearn.py#L46-L49

**Comment by juntai-zheng** [comment]
Agreed - pinning the mlflow version would be useful in terms of reproducibility. Would you be willing to open a PR to add this version inference?

**Comment by eavidan** [comment]
sure @juntai-zheng. Will open the PR. anything special I need to know?

**Comment by dbczumar** [comment]
Apologies for the significant delay. The desired behavior for default environment specifications is to leave `mlflow` unpinned, as it is designed to be backwards-compatible. Accordingly, I'm going to go ahead and close this issue. Thank you for using MLflow!
