### ISSUE TITLE
[DOC-FIX]

### ISSUE THREAD

**Issue by SebastianRiechert** [mlflow/mlflow#2986]
![Unbenannt](https://user-images.githubusercontent.com/23136185/85283960-936d7000-b48e-11ea-99b7-c959bdf5fed3.png)
### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [ ] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [x] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://www.mlflow.org/docs/latest/model-registry.html
https://www.mlflow.org/docs/tracking.html#backend-stores

### Description of proposal (what needs changing):
the link to additional information on setting up backend store (for Mlflow Model Registry) is dead (Access denied). I propose to revive it.

**Comment by pogil** [comment]
Looks like a broken link. The docs should point to https://www.mlflow.org/docs/latest/tracking.html#backend-stores
