### ISSUE TITLE
Argument for specifying new docker image name?

### ISSUE THREAD

**Issue by igonro** [mlflow/mlflow#2987]
I'm trying to run a project using mlflow and a docker image, like:
`mlflow run . --experiment-name EXP -A gpus=all -P ...`

In the docs, I've read the following:

> When you run an MLflow project that specifies a Docker image, MLflow adds a new Docker layer that copies the project’s contents into the /mlflow/projects/code directory. This step produces a new image. MLflow then runs the new image and invokes the project entrypoint in the resulting container.

And my question is: Is there any argument to specify the name of new docker image that mlflow creates? I've been looking into the code, but I couldn't find anything. Thanks!

**Comment by dbczumar** [comment]
@igonro This is a good question! Currently, the MLflow Project name is used for the image name. You can always rename the image after it's built using `docker tag` (https://docs.docker.com/engine/reference/commandline/tag/). Does this meet your requirements?

**Comment by igonro** [comment]
> @igonro This is a good question! Currently, the MLflow Project name is used for the image name. You can always rename the image after it's built using `docker tag` (https://docs.docker.com/engine/reference/commandline/tag/). Does this meet your requirements?

Yes, I guess it's a workaround. The problem I was facing was that I had an experiment name with uppercase letters and I've been having some errors because of that (Docker doesn't like uppercase letters in image names). What I finally did was create a new experiment, and then it worked fine. My question was because having a way to choose the image name, would allow to have experiments with uppercase letters, and working with docker. But as I didn't find anyone else complaining about this, I don't think this is a big issue.

Thanks for your response, I'm closing this issue.
