### ISSUE TITLE
[SETUP-BUG] Option to compare model version no longer available

### ISSUE THREAD

**Issue by iamkuldeepsingh** [mlflow/mlflow#2994]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this installation issue template to ensure a timely and thorough response.**

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: Pip install
- **MLflow version (run ``mlflow --version``)**: 1.9.0
- **Python version**: 3.7.3 
- **Exact command to reproduce**:
I installed mlflow 10 days back on local setup and it used to show me Option to compare model version which seems no longer available
### Describe the problem
Option to compare model version is no longer available, not sure if its disabled now 
### Other info / logs
I will attach the snapshot of error 

earlier working setup

![image](https://user-images.githubusercontent.com/26478064/85514087-48339880-b619-11ea-9e33-b44ba6aa7818.png)

Now its no longer visible

![image](https://user-images.githubusercontent.com/26478064/85514169-63060d00-b619-11ea-8be0-e5c4547b1613.png)

**Comment by harupy** [comment]
@iamkuldeepsingh The UI in your screenshot looks similar to the UI for MLflow 1.7.0:

![Screen Shot 2020-06-24 at 16 48 43](https://user-images.githubusercontent.com/17039389/85518302-103d4d00-b63b-11ea-9f76-341b0acae7e9.png)


Can you check the version of MLflow running the following command?

```
mlflow --version
```

**Comment by iamkuldeepsingh** [comment]
@harupy Thanks for quick response, you might be right- Is there a way to find it from UI (I am running server and client separately) about the version, I can cross check else I will wait for the team who maintains it to run the command and share with me.

**Comment by harupy** [comment]
@iamkuldeepsingh Can you check the name of the main js file on your browser?

![Screen Shot 2020-06-24 at 18 58 33](https://user-images.githubusercontent.com/17039389/85535768-7501a300-b64d-11ea-81a8-465f33a6ed16.png)

**Comment by iamkuldeepsingh** [comment]
Here you go, it looks same as yours
![image](https://user-images.githubusercontent.com/26478064/85537096-4bd31980-b631-11ea-9f86-8f155ead0c36.png)

**Comment by harupy** [comment]
Mine is for MLflow 1.7.0.

**Comment by iamkuldeepsingh** [comment]
This helps, Thanks a lot for all the help. I will close the issue

**Comment by harupy** [comment]
@iamkuldeepsingh My pleasure!
