### ISSUE TITLE
[FR] Put a download button on each artiafct tree node to make it easier to download multiple files

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#3007]
![artifact-buttons](https://user-images.githubusercontent.com/17039389/85675779-f8300100-b700-11ea-978d-a8d760053e93.gif)

Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Currently, when a user wants to download multiple artifacts, he/she needs to repeat the following process multiple times.

1. Select an artifact
2. Click the download button on the right-top of the artifact file viewer

This is a pain. To solve this issue, put a download button on each artifact tree node and allow users to download multiple artifacts without opening them.

## Motivation
- What is the use case for this feature?
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by smurching** [comment]
@harupy nice! The use case of downloading multiple artifacts seems pretty reasonable. An alternative UX for this would be to add a checkbox e.g. to the left of each artifact tree node & a download button (e.g. have a checkbox UX for selecting artifacts similar to the runs table)

This would potentially enable a select-all-artifacts-and-download-as-zip flow in the future & make it harder to misclick the download button for the wrong artifact, but also might be a bit odd in that the artifact-selection checkbox and expand-artifact-directory-toggle would be located close to each other in the UI.

cc @gioa for thoughts

**Comment by harupy** [comment]
@smurching The checkbox approach definitely makes sense (it might complicates the UI though). It'd be nice if the checkbox on a directory node allows selecting all files under that directory, which definitely helps a user when the number of files the user wants to download is large.

**Comment by gioa** [comment]
Thanks, @harupy for working on this! I also feel the checkbox may complicate the UI. To download multiple files under one folder, can we add a download per folder (download-as-zip)? We can also extend it to a "More actions" icon so later we can add more actions like Copy Path in its dropdown.

Also since the primary function of this artifact viewer is to browse files, what do you think of hiding all the download icons by default? We can show the icon on hover to avoid cluttering the UI. 

![DownloadFiles](https://user-images.githubusercontent.com/1960721/86072770-3eee6580-ba37-11ea-9419-a0d25821e5bf.png)

**Comment by jkthompson** [comment]
This approach would address #2978.  Would be a big help for my use case.

**Comment by harupy** [comment]
@gioa Thanks for great ideas! I have created a prototype for the download-all approach (by tweaking the server-side code a bit).

![zip-demo](https://user-images.githubusercontent.com/17039389/86161326-0e4a2100-bb48-11ea-849b-d92c6f47a14a.gif)

**Comment by gioa** [comment]
@harupy Awesome! Thank you for the quick turnaround!
