### ISSUE TITLE
[FR] allow kwarg passing to MLmodel for pyfunc loader_module paradigm

### ISSUE THREAD

**Issue by wamartin-aml** [mlflow/mlflow#3008]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Ideally, `pyfunc.log_model` would directly support passing kwargs that will be included in the MLmodel file while using the loader_module paradigm. The documentation suggests that this is the existing implementation. 

https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlmodel-configuration
"Optionally, any additional parameters necessary for interpreting the serialized model in pyfunc format"

The main request here is for a change to the pyfunc module, but an update to the documentation to explain addition of custom parameters would be very helpful as well.

## Motivation
- What is the use case for this feature? 
In general, users with varied python function models may not want to or be able to use the PythonModel option and may have additional important information for rehydrating their models that should go into the MLmodel config.
- Why is this use case valuable to support for MLflow users in general? 
It expands the usability of pyfunc models to a greater diversity of model serialization formats.
- Why is this use case valuable to support for your project(s) or organization? 
We're working on logging model evaluations, which follow a similar format to models. In particular, they are collections of artifacts with metadata that is useful for efficient deserialization.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
To start with, `pyfunc.log_model` just doesn't take kwargs to pass along to `Model.log`. Beyond that, even if trying to use `Model.log` directly with the `python_function` flavor, `Model.log` will pass those kwargs to `pyfunc.save_model`, but `pyfunc.save_model` throws away any kwargs other than `model`.

``` python
mlflow_model = kwargs.pop('model', mlflow_model)
    if len(kwargs) > 0:
        raise TypeError("save_model() got unexpected keyword arguments: {}".format(kwargs))
```

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

The main proposal is to add a `**kwargs` parameter to `pyfunc.log_model`, which would be passed through `Model.log` to the kwargs of `pyfunc.save_model`. `pyfunc.save_model` would then pass all kwargs other than `model` through to `_save_model_with_loader_module_and_data_path` (probably to the artifact-based function as well), which would in turn pass them to `pyfunc.add_to_model`. Once given as input there, they will automatically be added to the MLmodel config by existing code.

If changing the high-usage `log_model` function is considered too risky or might cause confusion for users, a compromise would be to at least update the function signatures from `pyfunc.save_model` and lower so that the useful pyfunc internals are still accessible from `Model.log` with kwargs. This would enable lower level development but leave the most visible piece unchanged.

**Comment by wamartin-aml** [comment]
To be clear, this is a separate request from #2360

**Comment by tomasatdatabricks** [comment]
Hi @wamartin-aml, sorry for the delayed response! 

Can you clarify what parameters do you need to add in your case?  One way fo doing this today is to include additional file with metadata for your model and read it in your loader module. Would that work for you?

**Comment by wamartin-aml** [comment]
No problem! We've come up with a workaround in the meantime using Model.log() directly.

Our parameters are metadata associated with Model Explanations which we want to be able to query on without downloading all of the files of a given model. We're well aware that we could pass metadata in its own special file, but that isn't the neat solution we're hoping for.

In particular, this request comes from the way pyfunc describes its MLmodel file generation: https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlmodel-configuration

Among the parameters that we're told we can pass in, there is: "Optionally, any additional parameters necessary for interpreting the serialized model in pyfunc format."

If you don't want to add the support for additional parameters/metadata in the pyfunc log_model, maybe the wording here could be clarified?

**Comment by tomasatdatabricks** [comment]
Thanks for the clarification! 

Yes, definitely, either the docs need to be fixed or the kwargs should be passed to the MLmodel file. We're considering whether to allow arbitrary kwargs as pyfunc arguments. The reason why we did not do it initially was to keep MLmodel file minimal.

**Comment by wamartin-aml** [comment]
Wonderful! Thanks for upping priority - either option seems reasonable, it'll just be nice to have the system and docs consistent.

**Comment by wamartin-aml** [comment]
no longer relevant
