### ISSUE TITLE
[SETUP-BUG] azure requirement required by default

### ISSUE THREAD

**Issue by xinluh** [mlflow/mlflow#3009]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this installation issue template to ensure a timely and thorough response.**

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: cross platform
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.9.1
- **Python version**: 3.8
- **Exact command to reproduce**: n/a

### Describe the problem
Azure dependencies are installed by default:
https://github.com/mlflow/mlflow/blob/master/setup.py#L32

Expect azure dependency to be install only via the `extras` bundle similar to boto and gcs dependencies

Happy to submit a PR if this is indeed an unintended extra dependency.

**Comment by arjundc-db** [comment]
Hi @xinluh 
Thanks for filing.
The azure dependency was changed to support a new artifact repository added (https://github.com/mlflow/mlflow/pull/2911) in the 1.9 release. 
I will go ahead and close this issue, thanks for filing again.

**Comment by xinluh** [comment]
@arjundc-db Circling back on this - is the new artifact repository mandatory? For example, if user only uses gcs or aws, will the azure dependency ever come into play? Mlflow seems to be doing a good job in being modular and backend agnostic so far; this seems to break the pattern a little.
