### ISSUE TITLE
[FR] Atomic Chained Stage Transitioning

### ISSUE THREAD

**Issue by gtadamson** [mlflow/mlflow#3016]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary

Allow for atomic stage transitions for multiple versions (ideally in the GUI along with programmatically). For example, transition v2 from Staging to Production and v1 from Production to Archived as a single transaction. The issue this is working around is a requirement that only a single model be deployed to an environment at a time. If more than 1 is in any stage, additional logic is required to ascertain which one is to be used.

## Motivation
- What is the use case for this feature? A model deployment environment which requires a single model to be the model that is used for that environment. If a query to determine which model is in a stage happens to occur while the user is transitioning models (i.e. 0 or 2 in a stage), then it's ambiguous as to which model (if any) should be utilized)
- Why is this use case valuable to support for MLflow users in general? If MLflow is to become the "truth" for ML models, it needs to support the use of registered models by production systems. This FR allows a simplification of the logic to determine which model should be used in various deployment environments.
- Why is this use case valuable to support for your project(s) or organization? We currently have added logic to address the more than 1 model case (chose the latest version number) and require the person executing the deployment in MLflow to promote the new model first before promoting (or Archiving) the existing model. This works fine, but an atomic solution would be cleaner.
- Why is it currently difficult to achieve this use case? I wouldn't call it difficult, but it's less than optimal. See above.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by dmatrix** [comment]
@gtadamson,

Thanks for filing this enhancement. This multi-step atomic transition feature is part of the enterprise-grade MLflow on Databricks, where you can elect to transition other models versions in the production stage to the archived stage. The net effect is that, as you point out, only a single version is production: "transition v2 from Staging to Production, and v1 from Production to Archived as a single transaction."

Maybe, in the future, this might become an OSS feature, but for now, it's part of enterprise MLflow on Databricks. However, 
we welcome contributions from the community. 


cc: @sueann @mparkhe

**Comment by gtadamson** [comment]
@dmatrix thanks for the information. Unfortunately our use case requires us to run our own server and it doesn't appear your enterprise edition is purchasable as a software package.

**Comment by dmatrix** [comment]
No, it's not a separate package but integrated with the Databricks Unified Analytics Platform. For now, I'll close this enhancement. Let me know if that' okay with you.

**Comment by gtadamson** [comment]
That is fine with me unless you think someone in the community will pick it
up to work on. I leave it up to you to know what the best course of action
is.

**Comment by sueann** [comment]
There is actually already an option available in the MLflow client to perform this particular type of chained state transitions: https://github.com/mlflow/mlflow/blob/8cb5e58bb3e7698cc1a004d70b276567544fc21f/mlflow/tracking/_model_registry/client.py#L162-L163. But the model registry backend (`SQLAlchemyStore`) does not implement it yet. We do want to add this support soon, so let's leave this issue open. 

cc @pogil

**Comment by dmatrix** [comment]
Thanks @sueann.

**Comment by sueann** [comment]
Assigning it to @harupy since he is currently implementing this feature.

**Comment by harupy** [comment]
Addressed by #3134
