### ISSUE TITLE
[FR] Option to show more than 10 registered models per page (or just don't paginate)

### ISSUE THREAD

**Issue by gtadamson** [mlflow/mlflow#3017]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary

Pagination of only 10 registered models is limiting, and the page you're on isn't stored in the URL so going back always takes you to the first page. I'd prefer all models be on a single page with a scrollbar, but could the number per page be configurable?

## Motivation
- What is the use case for this feature? Navigation back to page that you were on, seeing all models on a single page, user missed the models on the second page.
- Why is this use case valuable to support for MLflow users in general? Who likes 10 per page by default?
- Why is this use case valuable to support for your project(s) or organization? Easier to navigate and see the state of all models (which are production, etc) if they're on a single page.
- Why is it currently difficult to achieve this use case? This is a minor issue and there is no unachievable use case

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by dmatrix** [comment]
@Zangr Do you have any feedback on this enhancement?

1. Can we preconfigure the number of models per page, with default being 10?
2. Is back arrow takes you to the previous page or the first page?

**Comment by dmatrix** [comment]
@ankitmathur-db including you to comment on this too.

**Comment by ankitmathur-db** [comment]
The issue with the URL back/forward should be fixed by: https://github.com/mlflow/mlflow/pull/3022

I'm open to exploring possible ways to pre-configure things - is that actually necessary if the back/forward functionality works @gtadamson

**Comment by Zangr** [comment]
Thanks for creating the FR @gtadamson. It makes sense to make the model version per page configurable. 
cc @gioa maybe we can provide a list of options like 10 20 50 100? What do you think?

**Comment by gtadamson** [comment]
@ankitmathur-db Personally I prefer more models per page under any circumstances (even if the page navigation is fixed). I've seen the 10 25 50 100 type options before, that seems reasonable. It would be nice if your choice was stored as the default for the next time you viewed it. Maybe I'm an outlier but I always immediately select the largest number of results per page.

**Comment by ankitmathur-db** [comment]
@gtadamson - some other UI work is pending, but I have code written for this. The v1 probably won't remember your settings across sessions (just based on bandwidth), but I'll ping here once that PR is up

**Comment by dmatrix** [comment]
Thanks @ankitmathur-db for responding and prioritizing.

**Comment by ankit-db** [comment]
@gtadamson - this is fixed as of a release ago, and in MLflow 1.13.0, we actually persist your choice in the UI. Sorry about the delay here, and happy holidays!
