### ISSUE TITLE
Docker container instead of conda environment

### ISSUE THREAD

**Issue by wielandbrendel** [mlflow/mlflow#302]
Is there a way or future plan to use docker containers / dockerfiles instead of conda environments? On our cluster users are supposed to start docker containers on free GPUs to run their experiments. Hence, my typical setup is to define a docker image which I am then using to execute my python scripts. Just starting mlflow within a docker container is possible, but would require me to first start a container by hand, ssh into the container and then run the experiment (instead of directly running the experiment which starts a container itself).

**Comment by arinto** [comment]
+1 on this feature :)

**Comment by hamroune** [comment]
@wielandbrendel  I want understand your need, I think you just need to create a Dockerfile that takes conda.yml/MLproject+Python scripts and then start the container and automatically inside it load these file an d do mlflow run...?

**Comment by wielandbrendel** [comment]
@arinto That's exactly what I meant.

**Comment by marcusrehm** [comment]
Hi all,

I did the [PR 555](https://github.com/mlflow/mlflow/pull/555) as a first attempt to run experiments on docker. Right now it mounts local directories as volumes inside a container, but I'm working on create the steps to build a image with the project deployed on it so we can deploy in kubernetes for example.

This approach frees us from the need to create conda environments in every run.

**Comment by alexvorobiev** [comment]
+1 to this feature. We use [Nix](https://nixos.org/nix/) for python (and soon R) development (https://nixos.org/nixpkgs/manual/#python). Nix is very good at creating isolated and reproducible development environments which do not conflict with the underlying OS.

**Comment by KailasJanardhanan** [comment]
Is the feature to export Spark models as Docker images supported yet? I started using this for a day only and could not find any relevant documentation explaining this. If this feature is in the development stage and is being planned for future releases, please confirm the same. Thanking you in anticipation.

**Comment by govindKAG** [comment]
+1 for this feature.

**Comment by smurching** [comment]
@wielandbrendel thanks for raising this, @marcusrehm contributed support for running MLflow projects in MLflow 0.9.0 ([see changelog](https://github.com/mlflow/mlflow/blob/master/CHANGELOG.rst#090-2019-03-13) and [docs](https://www.mlflow.org/docs/latest/projects.html#project-environments)). Will close for now but please reopen if anything comes up!
