### ISSUE TITLE
[FR] Add pip native support

### ISSUE THREAD

**Issue by huberemanuel** [mlflow/mlflow#3021]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [X] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

The actual version of mlflow is heavily dependent on conda package, on the other hand the use of the default pip package is widely used by the community. Therefore, the native support to pip will encourage a lot of users that do not use the conda package to start using mlflow.

## Motivation
- What is the use case for this feature? Use of mlflow without needing to use conda environments.
- Why is this use case valuable to support for MLflow users in general? It will allow to non-conda users to use features from mlflow without workarounds (like serve models).
- Why is this use case valuable to support for your project(s) or organization? It will become a standard to use mlflow since we do not use conda.
- Why is it currently difficult to achieve this use case? The user needs to install manually all the packages from a requirements.txt file, this process can be automated with the proposed feature.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

The proposed feature request can be done by adding a new flag on MLproject files indicating the filename which contains all packages and their versions (pip freeze output). Then the mlflow can install those packages in the current environment, or create a local environment.

**Comment by huberemanuel** [comment]
After carefully reading the Project section on the docs, I found that is possible to use the flag "--no-conda" to use the mlflow without a conda environment. It's a peculiar design choice to the conda environment to be the standard choice, instead of the system current environment, but this solves the issue. I will close this issue.

**Comment by asmaier** [comment]
The option is described like

> --no-conda
> If specified, will assume that MLmodel/MLproject is running within a Conda environment with the necessary dependencies for the current project instead of attempting to create a new conda environment.
> https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-models-prepare-env-no-conda

That only means no dependencies get installed via conda. But what if I want to install dependencies via pip and a requirements.txt file? The latter doesn't seem to be supported by mlflow. This is a pity, because pip is the standard tool for dependency managements in python. Or, if I'm wrong, at least the documentation should show an example without using conda. So I think this ticket should be reopened.

**Comment by huberemanuel** [comment]
My initial concern was to run mlflow without conda, then I found a documented way and close this issue. But for an automatically run through mlflow-project API, it would be really nice to have this feature of installing packages with pip. @asmaier I think you are right and we should re-open this issue, thank you for the feedback.

**Comment by joshuacook** [comment]
@huberemanuel @asmaier Can't this be done with a `pip` key in your `dependencies` list, trivially:

```
name: trivial_env
dependencies:
  - python=3.7
  - pip:
    - pytest
```

**Comment by asmaier** [comment]
@joshuacook But for that one still needs to install conda. If mlflow had native support for pip an additional installation of conda would not be necessary at all.

**Comment by arainboldt** [comment]
I wanted to second the sentiment expressed here regarding mlflow's choice of conda for package management. Pip is a much more natural choice at this point in Python's history. Hopefully the contributors rethink this at some point soon.

**Comment by onacrame** [comment]
Agreed, with the Anaconda licence changes, Anaconda is a nonstarter.  Pip and Poetry would be great.

**Comment by siddhartha2202** [comment]
Agreed,  I think that Pip and Poetry  would be an excellent option

**Comment by pbower** [comment]
Hi, I started logging this exact same issue, but came across this existing one. Therefore including the populated template below, as there are some commercial reasons to highlight.


## Willingness to contribute
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Please consider adding PIP as an alternative to using CONDA and Docker package management. In which case, leave non-Python dependencies to the user to manage.

## Motivation
- What is the use case for this feature?
1. PIP installation is quick and painless. Conda these days is extremely slow to install packages.
2. Conda is NOT open source. Therefore, from this perspective it is inconsistent with ML Flow as an open source ecosystem. See https://www.anaconda.com/terms-of-service
3. As a result of #2 above, it is very difficult for a company to use ML Flow. Anything it builds on top of this and consider serving to customers is bound to Anaconda's terms of service, in which there are significant clauses e.g. risk of being booted off.

- Why is this use case valuable to support for MLflow users in general?
PIP is easier, quicker, and better supported than Anaconda in 2021. Though it offers a reduced feature-set (Python only), it is broadly within the target users' interests to consider using PIP.

- Why is this use case valuable to support for your project(s) or organization?
I cannot speak for an organisation, but with regards to personal projects, this allows me to build off ML Flow's functionality without fear of Anaconda and its commercial tentacles, licensing and restrictions.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Anaconda only supports Conda, Docker and Filesystem as formats. PIP could be an additional format like 'File System' where it places the onus on the user to include non-Python dependencies. 

### What component(s), interfaces, languages, and integrations does this feature affect?
Components (these may need to be reviewed)
- [X ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [X] `area/projects`: MLproject format, project running backends

Interfaces
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models

**Comment by dbczumar** [comment]
Hi folks, in MLflow 1.26.0, we will be introducing support for virtualenv + pyenv + pip as an alterative to conda. You can try this out on the MLflow `master` branch by specifying the `--env-manager virtualenv` flag for relevant CLI commands (e.g. `mlflow run`, `mlflow models serve`) and the `env_manager="virtualenv"` option for relevant API commands (e.g. `mlflow.run`, `mlflow.models.build_docker`, ...). Thank you for using MLflow!

**Comment by pbower** [comment]
Outstanding thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
