### ISSUE TITLE
[FR] Introduce a bot that automatically applies labels on issues and pull requests

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#3026]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

I'm developing a bot using GitHub Actions that automatically applies labels on issues and pull requests by detecting task lists in the description.

https://github.com/harupy/auto-labeling

## Motivation
- What is the use case for this feature?
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dmatrix** [comment]
@harupy Thanks for this enhancement. This would aid in my initial triage, as it'll automatically consign labels with ones selected
in the PR/FR/Issue list.

Will assign this to you, then.

cc @pogil

**Comment by harupy** [comment]
@dmatrix Thanks! Could you jump to [this issue](https://github.com/harupy/auto-labeling/issues/18) and just check the `enhancement` checkbox? I just want to check how the bot reacts to this change.

**Comment by harupy** [comment]
@dmatrix Thanks! Could you open an issue in [harupy/auto-labeling](https://github.com/harupy/auto-labeling) with the following description? I just want to check how the bot works when a new issue is opened.

```
- [x] `test`: unregisterd
- [x] `bug-fix`: registered
- [ ] `enhancement`: registered
```

**Comment by dmatrix** [comment]
@harupy, I just filed an [issue](https://github.com/harupy/auto-labeling/issues/35)

**Comment by dmatrix** [comment]
@harupy, created a second issue to test enhancement: https://github.com/harupy/auto-labeling/issues/36

Both `bug-fix` and `enhancement` seem to work.
Cheers!

**Comment by harupy** [comment]
@dmatrix Thanks for filing the issues! I'll briefly explain how the bot works.

The bot does the following on specified events.

1. Extract labels (checkboxes) from the description using a specified regular expression
2. Add checked ones and remove unchecked ones (ignore ones that don't exist in the repo)

For an issue, we can use the `issues` event and add labels right after the issue is opened or edited, but labeling on a pull request is a bit tricky. As explained [here](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token), `GITHUB_TOKEN` created for a PR from a forked repo doesn't have write permission for a security reason so running the bot on the `pull_request` event doesn't work. Instead, we can use the `scheduled` event and run the bot on a certain interval. I think it's fine to add labels say 10 minutes after a pull request is opened.

https://docs.github.com/en/actions/reference/events-that-trigger-workflows

**Comment by harupy** [comment]
I'll submit a PR when it's ready.
