### ISSUE TITLE
Proposal: Integrated notetaking for runs

### ISSUE THREAD

**Issue by aadamson** [mlflow/mlflow#303]
I discussed this on Slack with @aarondav and wanted to gather feedback on a feature that I'm interested in contributing.

### Motivation
During my work, after I train and evaluate a group of models, I'll typically take some notes (e.g. thoughts on what models did well and why, thoughts on what changes to try next and why) and save them to a text file in the same directory as whatever artifacts/metrics I've generated. I think having something like an integrated lab notebook in MLflow would be very helpful. 

### Proposal
Here's what I think would be a good first attempt:

#### Backend
* Add a **Note** entity to be owned by a **Run**
* Add a **Note**s field to **RunData**
* **Note** schema will look like
    - [run_uuid:string, created_time:int64, updated_time:int64, user_id:string, content:string] (option 1), or
    - [run_uuid:string, created_time:int64, updated_time:int64, user_id:string] (option 2)
* **Note**s will be stored on disk at 
    - A single yaml file containing everything from option 1 schema above
        - <root_dir>/<experiment_id>/<run_uuid>/notes/<note_uuid> 
    - Or as a metadata file and a content file:
        - <root_dir>/<experiment_id>/<run_uuid>/notes/<note_uuid>/meta.yaml (everything from option 2 above)
        - <root_dir>/<experiment_id>/<run_uuid>/notes/<note_uuid>/content.md (user-provided content
* Two new service endpoints will be added
    - list_notes (takes a run uuid and returns a list of notes, including their contents)
    - log_note (takes a run_uuid, user_id, timestamp, and optionally a note_uuid, and returns a **Note** (conforms to schema from above)
        - if *note_uuid* provided, modify content of existing note in place and update *updated_time* to *timestamp*; otherwise, create new **Note**

#### UI
 - The user will be able to view, add, and modify notes through the run page: ![image](https://user-images.githubusercontent.com/3607110/44111918-b6f1a31c-9fd1-11e8-9f6a-256e5d151f9c.png) Not shown above: the right pane could toggle between "View" (render markdown) and "Write" and have a create/update button (like the markdown editor Github provides).
- The runs table on the experiment view will have an icon that is either present or note per row indicating whether or note there are notes associated with the run
- Users can filter the runs table to runs with or without notes

### Possible extensions
- Experiment notes: allow notes to be associated with and viewed for an experiment instead of a run
- Artifact embedding: allow users to embed images saved previously as artifacts for the run

### Questions? Suggestions?
Before I start working on this, I'd love to hear suggestions or questions! I'm new to the project and not really familiar with the ins and outs of the codebase, so some of this could be very off-base or wrong-headed.

**Comment by fvinas** [comment]
👍 Would also love this feature!

**Comment by aadamson** [comment]
@aarondav @mateiz any opinion on whether the content of notes should be stored as separate files on disk like artifacts and referred to in the notes' protos or inline in the protos? I have a branch that I can clean up and submit a PR in the next few days

**Comment by mateiz** [comment]
Hey Alex,

I think this is a great feature but I would like to understand the way you want to use this a bit more. Are the notes *only* text (like comments) or can they be richer information too (say images)? And what is the use case for logging them with an API while doing the run -- is it in case you're working in a notebook or something like that? I definitely see a point to annotating runs after the run, or allowing other people to comment on them.

If the notes are going to have rich content, it might be better to make them *be* artifacts in a specially named folder, say "notes". This could contain files with this information. However, if they're going to be small and mostly text, maybe making them first-class entities will work better.

**Comment by aadamson** [comment]
Matei, thanks for the questions. The notes would just be text. I was planning on having a Markdown editor/viewer exposed in the run view UI so that users could see/edit the notes:
![image](https://user-images.githubusercontent.com/3607110/44411582-d7128e00-a534-11e8-8a24-9cda205751ef.png)
![image](https://user-images.githubusercontent.com/3607110/44411595-e1348c80-a534-11e8-802a-81fe303ad951.png)

So there wouldn't be any images or other rich content inline in the source of the note, but a renderer on the frontend would take care of converting rich content tags into images or links.

For logging during the run via an API, yeah, logging while staying in your notebook is what I was picturing, although I'm not sure how much of a real need there is for that.

**Comment by gioa** [comment]
Hi Alex, I am Joy, a designer at Databricks. Great proposal and love the Markdown editor/viewer! Thank you for the UI screenshots! Regarding the last one: do we need multiple note entries? From your motivation description, it seems we can have one entry for taking notes and keep appending there. I mocked up some designs to demonstrate where the notes can go. Thoughts?

![empty](https://user-images.githubusercontent.com/1960721/44613083-c9bf0300-a7c3-11e8-800e-ac820e062105.png)

![adding](https://user-images.githubusercontent.com/1960721/44613087-d3486b00-a7c3-11e8-8b4d-ba54a417cc2f.png)

![done](https://user-images.githubusercontent.com/1960721/44613090-d93e4c00-a7c3-11e8-8363-680165dded04.png)

You can also play with the Invision prototype here: https://invis.io/MXNPSZECN48#/316177350_empty

**Comment by andrewmchen** [comment]
Closed by https://github.com/mlflow/mlflow/pull/396.
