### ISSUE TITLE
artifacts not shown in UI

### ISSUE THREAD

**Issue by ciberger** [mlflow/mlflow#3030]
Hi, after hours searching online I couldn't find a solution when storing artifacts locally. Strangely, my test file is located within the run's artifacts directory, but it's not shown on the mlflow UI. Tried `mlflow ui --backend-store-uri models/mlruns --default-artifact-root models/mlruns` unsuccessfully. YAML file points to the right folder. 

```python
with open('test.file', 'wb') as f:
    joblib.dump(test, f)

mlflow.set_tracking_uri('../models/mlruns')
with mlflow.start_run():
    mlflow.log_artifact('test.file')
    print(mlflow.get_artifact_uri())
mlflow.end_run()

# ./models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db/artifacts
```

```batch
❯ tree models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db
models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db
├── artifacts
│   └── test.file
├── meta.yaml
├── metrics
├── params
└── tags
    ├── mlflow.source.name
    ├── mlflow.source.type
    └── mlflow.user

4 directories, 5 files

❯ cat models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db/meta.yaml
artifact_uri: ../models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db/artifacts
end_time: 1593590656375
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 838f9f54c9f24f13bc299bac6068b8db
```

# System information
**Have I written custom code (as opposed to using a stock example script provided in MLflow)**: -
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.15
**MLflow installed from (source or binary)**: pip
**MLflow version (run mlflow --version)**: mlflow, version 1.9.1
**Python version**: 3.7.4
**npm version (if running the dev UI)**: -
**Exact command to reproduce**: `mlflow ui --backend-store-uri models/mlruns --default-artifact-root models/mlruns`

_Originally posted by @ciberger in https://github.com/mlflow/mlflow/issues/884#issuecomment-652266853_

**Comment by dmatrix** [comment]
If you running this on localhost, MLflow creates the default `mlruns` directory as your local artifact and store for you. Take this
example,
`import mlflow
  import joblib

if __name__ == '__main__':
     with open('test.file', 'wb') as f:
        test = range(20)
        joblib.dump(test, f)

   with mlflow.start_run() as run:
      run_id = run.run_id = run.info.run_uuid
      mlflow.log_artifact('test.file')
      print(f"artifact_uri={mlflow.get_artifact_uri()}")
      print(f"run_id={run_id}")`

This will create `mlruns` directory as your artifact and backend store.
`artifact_uri=file:///Users/julesdamji/examples/py/mlflow/tests/mlruns/0/a3911198615847ad9d7c0e1d0bf9460e/artifacts
run_id=a3911198615847ad9d7c0e1d0bf9460e`

And if you launch `mlflow ui` from the directory where `mlruns` exists, you'll see your artifact:

![Screen Shot 2020-07-01 at 9 02 24 AM](https://user-images.githubusercontent.com/1117597/86267060-fc35a600-bb7a-11ea-8919-1e1e5c5bcd83.png)
![Screen Shot 2020-07-01 at 9 03 09 AM](https://user-images.githubusercontent.com/1117597/86267073-00fa5a00-bb7b-11ea-94fe-fc2ff036cb2e.png)

**Comment by dmatrix** [comment]
You only want to specify ``back-end-uri`` and `--default-artifact-root` as options to `mlflow ui` if 

-  your tracking server is running remotely or locally as a server, 

- you are using a backend store and artifact store are at different locations or you backstore is an `SQLAlchemy` compatible database

- you can read about this [here](https://mlflow.org/docs/latest/tracking.html#storage)

But if you just running locally, `mlruns` becomes your local backend and artifact file store. I

Let me know if you have any questions. This is not a bug or an issue.

**Comment by ciberger** [comment]
@dmatrix, thanks for your timely response 🚀

You're totally right! After running `mlflow ui` inside the `mlruns`directory I finally found the artifacts folder.

**Comment by abdoulsn** [comment]
> If you running this on localhost, MLflow creates the default `mlruns` directory as your local artifact and store for you. Take this
> 
> example: 
> 
> 
> 
> ![Screen Shot 2020-07-01 at 10 59 25 AM](https://user-images.githubusercontent.com/1117597/86276581-fabfaa00-bb89-11ea-8eef-36abc400180d.png)
> 
> 
> 
> 
> 
> This will create `mlruns` directory as your artifact and backend store.
> 
> `artifact_uri=file:///Users/julesdamji/examples/py/mlflow/tests/mlruns/0/a3911198615847ad9d7c0e1d0bf9460e/artifacts
> 
> run_id=a3911198615847ad9d7c0e1d0bf9460e`
> 
> 
> 
> And if you launch `mlflow ui` from the directory where `mlruns` exists, you'll see your artifact:
> 
> 
> 
> ![Screen Shot 2020-07-01 at 9 02 24 AM](https://user-images.githubusercontent.com/1117597/86267060-fc35a600-bb7a-11ea-8919-1e1e5c5bcd83.png)
> 
> ![Screen Shot 2020-07-01 at 9 03 09 AM](https://user-images.githubusercontent.com/1117597/86267073-00fa5a00-bb7b-11ea-94fe-fc2ff036cb2e.png)
> 
> 

Let's test this . I did not found any solution since.

**Comment by dmatrix** [comment]
@abdoulsn 

This issue was closed as demonstrated. The problem was how and what you specified as arguments to mlflow ui. The issuer
tried it and worked for him.

**Comment by sunov** [comment]
I am storing artifacts(model.pkl) in private repository and storing metrics and parameters in MYSQL DB. Not able to see metrics and parameters in mlflow UI after these settings. Could you please help me

tracking_uri = f"mysql+pymysql://{mlflow_user}:{mlflow_pass}@localhost:3306/{mysql_database}"
mlflow.set_tracking_uri(tracking_uri)

if not mlflow.get_experiment_by_name(experiment_name):
        mlflow.create_experiment(name=experiment_name, artifact_location="private repository")
    experiment = mlflow.get_experiment_by_name(experiment_name)

**Comment by PaulZhangIsing** [comment]
> @abdoulsn
> 
> This issue was closed as demonstrated. The problem was how and what you specified as arguments to mlflow ui. The issuer tried it and worked for him.
> 
> https://github.com/dmatrix/google-colab/blob/master/mlflow_issue_3030.ipynb

Hi I have read and understand the above contents.
But in my set up, I am using another machine servers as mlflow server. it is more like scenario 4.
Meanwhile my SQL, tracking server and sftp server are all on server A, and I am accessing from server B.
and I used SQL for backend storage, meanwhile I want to use sftp server for artifact storage.
Currently I could upload the files to the sftp server successfully, but if I go to the mlflow portal from browser, I cannot see the artifacts in the UI.
And there is no meta.yaml file in the --default-artifact-root sftp://user:password@home/user/
what I could do about it?
![image](https://user-images.githubusercontent.com/27721543/212831724-b079ea3d-9c04-47c8-9055-655dafcb534f.png)
![image](https://user-images.githubusercontent.com/27721543/212831785-26909fe4-dffe-4d50-8066-4ac1e0d74636.png)

**Comment by fabiosanger** [comment]
> @dmatrix , Currently, I am storing artifacts(model.pkl) in private repository and storing metrics and parameters in MYSQL DB. Not able to see metrics and parameters in mlflow UI after these settings. Could you please help me
> 
> tracking_uri = f"mysql+pymysql://{mlflow_user}:{mlflow_pass}@localhost:3306/{mysql_database}" mlflow.set_tracking_uri(tracking_uri)
> 
> if not mlflow.get_experiment_by_name(experiment_name): mlflow.create_experiment(name=experiment_name, artifact_location="private repository") experiment = mlflow.get_experiment_by_name(experiment_name)

did you manage to find a work around??
