### ISSUE TITLE
[BUG]ImportError: cannot import name 'NumpyEncoder' from 'mlflow.utils.proto_json_utils'

### ISSUE THREAD

**Issue by echarso** [mlflow/mlflow#3038]
### Willingness to contribute

- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
NO

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
mac os Siera 10.12.6 

- **MLflow installed from (source or binary)**:
pip3 install mlflow
- **MLflow version (run ``mlflow --version``)**:
1.9.0

- **Python version**:
3.7
- **npm version, if running the dev UI**:
-
- **Exact command to reproduce**:
in jupyter notebook import mlflow.xgboost

### Describe the problem

ImportError: cannot import name 'NumpyEncoder' from 'mlflow.utils.proto_json_utils' (/usr/local/lib/python3.7/site-packages/mlflow/utils/proto_json_utils.py)

### Code to reproduce issue

in jupyter notebook I import mlflow.xgboost to use for autolog and i get the problem with NumpyEncoder
I suspect i have problem with the installation of MLflow but not sure what exactly goes wrong 

I use mlflow locally

**Comment by dmatrix** [comment]
@echarso Thanks for filing this. Can you try installing the following:

- `conda install -c conda-forge xgboost`

- `conda install -c anaconda py-xgboost`

**Comment by juntai-zheng** [comment]
Hi @echarso, since it's been a while since the last response, I'll go ahead and close the issue. Feel free to reopen/create a new issue if you are still having trouble. Thanks!
