### ISSUE TITLE
[BUG] MLFlow version not specified in packages

### ISSUE THREAD

**Issue by mikeoconnor0308** [mlflow/mlflow#3043]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: 1.9.1
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem

MLFlow packages do not specify an MLFlow version in the produced conda.yaml: 

e.g.
```yaml
channels:
- defaults
- conda-forge
dependencies:
- python=3.7.7
- fastai=1.0.61
- pip
- pip:
  - mlflow
name: mlflow-env
```

This may be an intentional feature rather than a _bug_, but it strikes me as a bit odd to assume a package produced from one version of mlflow will work with a newer version? 

Is there some rationale of compatibility here, or should the ability to specify the mlflow version when saving a model by added?

**Comment by dmatrix** [comment]
@mikeoconnor0308 

Thanks for filing this issue. 

Have you been able to save a model with a specific version of mlflow and run that as a project, to see if the versions are identical?

@dbczumar @tomasatdatabricks We don't seem to save mlfow version as part of the conda.yaml 
![Screen Shot 2020-07-06 at 10 47 47 AM](https://user-images.githubusercontent.com/1117597/86623298-32f22e80-bf76-11ea-8a41-4a4e127328e9.png)

Is there a particular reason why and how do we reproduce the environment during mlflow run  for projects?
I know that it works but where do we get the mlflow version from?

**Comment by tomasatdatabricks** [comment]
@dmatrix @mikeoconnor0308 Yes this is indeed intentional and the assumption is that models logged with older versions of MLflow will continue to work with newer MLflow versions.

The main reason for this is that the MLflow dependency is also used to serve the model (i.e. it defines the web server) and if there are any changes to the model server in the future MLflow these would not apply to older models.

**Comment by dmatrix** [comment]
Thanks, @tomasatdatabricks for the quick response. 

@mikeoconnor0308, this indeed is intentional for forward compatibility. As much, can we close this issue, not as a bug?

**Comment by mikeoconnor0308** [comment]
Yep, thanks for the explanations.
