### ISSUE TITLE
[FR] UI should show the version and point to according documentation

### ISSUE THREAD

**Issue by OlivierBondu** [mlflow/mlflow#3044]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature request)

Title says pretty much everything: it is not visible which version of MLFlow is actually running. The pointer to the documentation should also go towards the proper version instead of 'latest' since there are regularly API changes.

## Motivation
- What is the use case for this feature?
point to the correct documentation, easy check that an upgrade was succesful, ...

- Why is this use case valuable to support for MLflow users in general?
NA
- Why is this use case valuable to support for your project(s) or organization?
NA
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
NA

you need to go where the MLFlow UI is running and check manually which version is running

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dmatrix** [comment]
@OlivierBondu 

Thanks for filling this bug. I assume that you are referring to the `Docs` link in the MLflow UI launched. 

Your ask is that depending on what version of the MLflow you are currently running, the docs link should go to that respective version of the docs, not always the latest, and that mlflow ui should indicate that respective version?

![Screen Shot 2020-07-06 at 11 28 47 AM](https://user-images.githubusercontent.com/1117597/86628218-70f35080-bf7e-11ea-84ea-8e33b3ac8840.png)

@Zangr Any comment on this? Seems there are two parts: one is the website `index.html` which always points to `docs/latest.html` and the second is some indication what version of the mlflow somewhere on the top banner.

**Comment by ankitmathur-db** [comment]
Seems reasonable to me! @OlivierBondu, would you be able to file a PR for this that we could review?

**Comment by Zangr** [comment]
Currently, the doc link is hardcoded in App.js. 
```
<a href={'https://mlflow.org/docs/latest/index.html'}>
  <div className='docs'>
    <span>Docs</span>
  </div>
</a>
```
We can change this to `https://mlflow.org/docs/<x.y.z>/quickstart.html` based on the current MLflow version. 
cc @andreakress to confirm the docs URL pattern

We also need a way to get the current version of MLflow like a static file that gets update per release. 
cc @smurching, do you know if we have a file with updated current version?

**Comment by dmatrix** [comment]
@Zangr, @andreakress, 

The `https://mlflow.org` site Docs link, IMHO, should point to the latest, which is hardcoded in the `index.html`.  However, for the mlflow ui, when launched, could dynamically link to https://mlflow.org/docs/<x.y.z>/index.html`, reflecting the installed version of the mlflow. 

There is an `mlflow/version.py` in our mlflow Github that gets updated. @smurching can confirm it. 

```
import mlflow
version  = mlflow.__version__
```

We can get that as part of <x.y.z>

**Comment by OlivierBondu** [comment]
@ankitmathur-db : unfortunately UI-facing changes are not really part of my skillset, I think this would be solved quicker and in a cleaner way by someone else... This should be an easy fix though ?

**Comment by Zangr** [comment]
@OlivierBondu, we are currently working on improving the MLflow onboarding user journey in Q3. I'll include this FR to the effort and update this thread with our progress.
