### ISSUE TITLE
[CI] move R tests from Travis to github actions

### ISSUE THREAD

**Issue by yl790** [mlflow/mlflow#3047]
As discussed with Javier, this change should help unblock https://github.com/mlflow/mlflow/pull/2367

**Comment by lorenzwalthert** [comment]
I have wip at https://github.com/lorenzwalthert/mlflow/pull/2. Will open a PR here today or tomorrow.

**Comment by yl790** [comment]
@lorenzwalthert Great!
Re familiarity with GH action: yes I worked with GH actions on 2 projects, so, I would somewhat experienced : )
Let me know if you need help.

**Comment by lorenzwalthert** [comment]
@yl790 I submitted #3048, you are welcome to have a look. I think we should at some point clean up all the CI/CD scripts for R, but I'd like to wait until after we merged #2367 because there is some interaction between the two topics.
