### ISSUE TITLE
No Artifacts Recorded

### ISSUE THREAD

**Issue by flouraNadar** [mlflow/mlflow#3086]
I am unable to store, view, and retrieve the artifacts in MLFlow. The artifact folder is empty irrespective of creating a new experiment and assign proper experiment name and location.

Server: mlflow server --backend-store-uri mlruns/ --default-artifact-root mlruns/ --host 0.0.0.0 --port 5000

Create an Experiment: mlflow.create_experiment(exp_name, artifact_location='mlruns/')

```
with mlflow.start_run():
    mlflow.log_metric("mse", float(binary))
    mlflow.log_artifact(data_path, "data")
    # log model
    mlflow.keras.log_model(model, "models")
```
The code compiles and runs but does not have any artifacts recorded. It has mlflow.log-model.history file but not the model.h5

Furthermore I tried to work with the standard Wine dataset it still faces the same issue all the log is recorded except the artificats. Any help is appreciated. Thanks.

The code and ML server resides inside conda Windows environment.

**Comment by harupy** [comment]
@flouraNadar Thanks for filing this. Does the same thing happen when you run the python code without running `mlflow server ...`?

**Comment by flouraNadar** [comment]
Yes, even without using mlflow server(used mlflow ui) for tracking and also without using mlflow.create_experiment() encountered the same problem. Nothing recorded in artifacts. 

FYI: The artifacts folder is created in mlruns folder in default location but does not log any information in it.

**Comment by harupy** [comment]
@flouraNadar Can you try runnning this code after deleting a `mlruns` directory?

```python
import os
import tempfile

import mlflow


with tempfile.TemporaryDirectory() as tmp_dir, mlflow.start_run() as run:
    fname = 'sample.txt'
    tmp_path = os.path.join(tmp_dir, fname)

    # create a text file to log
    with open(tmp_path, 'w') as f:
        f.write("sample")

    # logging
    mlflow.log_param("p", 0)
    mlflow.log_metric("m", 1)
    mlflow.log_artifact(tmp_path)
```

**Comment by flouraNadar** [comment]
I did try the above code, it does not add anything to the MLFlow interface. But does create mlruns and a folder with name 0 (I understand the 0th run) which contains only a metafile.

**Comment by harupy** [comment]
@flouraNadar Thanks! That's strange. Can you run the code below and check where your tracking uri points to?

```python
import os
import tempfile

import mlflow


with tempfile.TemporaryDirectory() as tmp_dir, mlflow.start_run() as run:
    # Added this line
    print('tracking uri:', mlflow.get_tracking_uri())

    fname = 'sample.txt'
    tmp_path = os.path.join(tmp_dir, fname)

    # create a text file to log
    with open(tmp_path, 'w') as f:
        f.write("sample")

    # logging
    mlflow.log_param("p", 0)
    mlflow.log_metric("m", 1)
    mlflow.log_artifact(tmp_path)

    # assert the text file is logged
    local_artifact_dir = mlflow.get_artifact_uri().replace("file://", "")
    assert fname in os.listdir(local_artifact_dir)

```

**Comment by flouraNadar** [comment]
Hey,

Thank you so much. It does register now. I might have set the environment value for artifacts URI to the default location which was different than the one where it was pointing to in the code. Resolved. Thank you

**Comment by harupy** [comment]
@flouraNadar My pleasure!

**Comment by flouraNadar** [comment]
Yes! definitely

**Comment by prateethvnayak** [comment]
> Hey,
> 
> Thank you so much. It does register now. I might have set the environment value for artifacts URI to the default location which was different than the one where it was pointing to in the code. Resolved. Thank you

Can you Please elaborate on this ? I'm having the same issue. 

Do I need to add (is it valid api at all below) ? : 

```python
server_uri = "http://127.0.0.1:6008"
mlflow.set_tracking_uri(server_uri)
mlflow.set_artifact_uri(server_uri)
```
Also, secondary question is that, I'm running it locally and not logging to an external server, so should I run `mlflow server` always before I run experiment ? Or is there a way to log and just spawn the `mlflow server` to just have the ui ?

**Comment by steveepreston** [comment]
This was happened because of a malformed `experiment`
This code has fixed the saving artifact problem:
```diff
# malformed "EXP"
- os.environ['MLFLOW_EXPERIMENT_NAME'] = "EXP"
+ os.environ['MLFLOW_EXPERIMENT_NAME'] = "NEW-EXP"
```
