### ISSUE TITLE
Bump project version number to snapshot # after each release

### ISSUE THREAD

**Issue by andyk** [mlflow/mlflow#310]
Currently our convention is to update the project version number in mlflow/version.py right before a release, but it would be helpful when doing testing if the version number in master was updated right after a release to represent that it is alpha code for the subsequent version.

So we would bump the version in mlflow/version.py to something like 0.4.3dev0 right after we release 0.4.2

This will make it easier to tell when you're using a master version of MLflow vs a release.

**Comment by mateiz** [comment]
Makes sense to me too.

**Comment by aarondav** [comment]
We do this now!
