### ISSUE TITLE
[FR] Show diagrams and elaborate on interaction between the client and the tracking server

### ISSUE THREAD

**Issue by dmatrix** [mlflow/mlflow#3108]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ X] Yes. I can contribute a documentation fix independently.
- [ ] Yes. I would be willing to contribute a documented fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### Description of the proposal (what needs changing):
Provide a clear description. Why is the proposed documentation better?

Based on my interactions on MLflow slack channel and these related issues—[3086], [3116](https://github.com/mlflow/mlflow/issues/3116) (https://github.com/mlflow/mlflow/issues/3086), [2834](https://github.com/mlflow/mlflow/issues/2834), [2045](https://github.com/mlflow/mlflow/issues/2045), and [3046](https://github.com/mlflow/mlflow/pull/3046)—there seems to be some confusion around two crucial concepts: `backend-store` and `default-artifact-store` usage and its relationshipt with `mlflow` tracking server and `mlflow ui`.

The proposal is to elaborate with the help of a diagram showing the interaction between the client and the tracking server and how and where MLflow entities are stored, based on backend-store and artifact store arguments. For example, show the following scenarios:

How an API interaction and request flow among the client, tracking server, and mlflow ui:

- on localhost (default backend and artifact store)
- on the remote host (specified artifact store and backend store)
- with/without SQLAlchemy compatible backend-store for both localhost and remote

Showing how MLflow entities—params, metrics, artifacts—flow and logged among the individual components in these scenarios help readers new to MLflow comprehend and visualize what transpires during a tracking API call.

**Comment by raman-nbg** [comment]
I would really appreciate this. I'm confused about the parameters and which component (client/server) uses which backend/store.

**Comment by marcraminv** [comment]
I hope this pic can help a bit to develop this issue.

@dmatrix Let me know if I can help/contribute with something related with that

![mlfrow_diagram](https://user-images.githubusercontent.com/13021787/96181562-84766600-0f34-11eb-9f8b-81d5b1bd1d4c.png)

**Comment by dmatrix** [comment]
@marcraminv Thanks for the picture, it's a good start. Will try to break it up and modularize for different scenarios, and will try use our standard icons so we have consistency across our figures in the docs. Thanks for the good start, and share the pictures with you here!

**Comment by Minyus** [comment]
@marcraminv 
@dmatrix 

Let me share the architecture for MLflow based on my understanding.
![image](https://user-images.githubusercontent.com/33908456/100733988-f4b84880-3409-11eb-94e8-952cbe68bfc1.png)

If you find anything incorrect/misleading, please let me know or feel free to edit this image: [Original SVG file (remove .txt extension to open with draw.io)](https://github.com/mlflow/mlflow/files/5622180/mlflow.drawio.svg.txt)

**Comment by dmatrix** [comment]
@Minyus Thanks for the diagram. A couple of things:

1. You might want to distinguish between a local instance and a remote instance of the tracking server. 
2. For local instance, the client directly interacts with the local FileStore (`file:/path/mlruns`) and local backend store if set with `sqlite:///mlruns.db`
3. For remote instance, running at port XXXX, the client interacts with the tracking server via REST API. The remote tracking server interacts with the backend store and artifact store when launched with ---backend-store-uri and --default_root_artifact
4. The dashed box with "Backend Store" and "Artifact Store" are a bit misleading; they suggest a process.

**Comment by marcraminv** [comment]
@dmatrix are this pics available in the documentation? they look really cool! Kudos for that 👍

**Comment by Minyus** [comment]
Hi @dmatrix 

Thank you for sharing the diagrams.

First, data files are uploaded to and downloaded from the artifact storage directly (mentioned at https://github.com/mlflow/mlflow/issues/2834), so the diagram named "MLflow Tracking Server" is a bit inaccurate.

Second, the database (PostgreSQL, MySQL, MS SQL) can be accessed through APIs (e.g. REST API, CLI, Python) directly without using MLflow Tracking Server although MLflow Tracking server is still need to use the Web UI.
This way, the models registered in the Model Registry can be deployed through the APIs even if MLflow Tracking server is down. So, I'd suggest to add 3rd diagram for this more robust setup.

**Comment by dmatrix** [comment]
@Minyus [here are scenarios and workflow](https://github.com/dmatrix/mlflow-tests/tree/master/py/mlflow/server) of how clients and tracking server in MLflow interact with respective backend and artifact stores, based on default and/or supplied arguments while launching the tracking server. I have reviewed this with our eng team.

Use these scenarios as a way to understand how each component interacts with which backend and artifact store, and the respective code responsible for it. We will add it as part of the documentation.

**Comment by Minyus** [comment]
Hi @dmatrix , 
Thank you for the update. I hope the diagrams will be helpful to understand how MLflow works.

**Comment by dmatrix** [comment]
I'm going to close this issue.
