### ISSUE TITLE
How can I use these functionalities in registry 

### ISSUE THREAD

**Issue by Astonzzh** [mlflow/mlflow#3152]
Please remind me if I miss somthing on lastest doc, thank you.

In the webpage https://databricks.com/blog/2020/06/25/mlflow-joins-the-linux-foundation-to-become-the-open-standard-for-machine-learning-platforms.html, I can see this picture

![image](https://user-images.githubusercontent.com/60844171/88162142-838aac80-cc43-11ea-9ddb-fbc8caa68efb.png)

Seems like this picture illustrates that by comparing two models, it can point out the schema are incompatible between two different versions of model.

However, when I look at model page and compare 2 models, which I have logged signature with them, I didn't see the schema information as it should be in the first picture.

![image](https://user-images.githubusercontent.com/60844171/88163744-b635a480-cc45-11ea-8b32-42daf543905d.png)

Are there some setting I didn't do, or this work in some particular way ?

**Comment by zhidongqu-db** [comment]
@Astonzzh Thanks for reaching out! The compare model version view that is displayed in the webpage is currently only supported in Databricks MLflow, you can check it out right now in the community version of databricks. In the meantime, We are definitely planning to open source this feature in the near future so stay tuned for that!

**Comment by dmatrix** [comment]
@Astonzzh Based on @zhidongqu-db comments and its future availability, can we close the issue?

**Comment by Astonzzh** [comment]
I see, Thank you for explaining!
