### ISSUE TITLE
ImportError: cannot import name 'RegisteredModelTag' from 'mlflow.entities.model_registry' 

### ISSUE THREAD

**Issue by chatan89** [mlflow/mlflow#3155]
I am using azuresql for tracking and azure blob for artifact. But i came across an issue while trying to create experiment/ run experiement. 

**Error :** 
ImportError: cannot import name 'RegisteredModelTag' from 'mlflow.entities.model_registry' (**/User\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\entities\model_registry\__init__.py)

Manually checked the local  path and i could find the scripts.

**Code :** 

```
mlflow.set_tracking_uri(azuresql_uri)
experiment_name = "experimentsklearn_test_model"
if not mlflow.get_experiment_by_name(experiment_name):
    mlflow.create_experiment(name=experiment_name,artifact_location=azureBlob) 
experiment = mlflow.get_experiment_by_name(experiment_name)
```

**Comment by harupy** [comment]
@chatan89 Thanks for filing this. Can you share the whole stack trace?

**Comment by chatan89** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-46-43a4ead2b0bb> in <module>
      1 experiment_name = "experimentsklearn_test_model"
      2 ## check if the experiment already exists
----> 3 if not mlflow.get_experiment_by_name(experiment_name):
      4     mlflow.create_experiment(name=experiment_name,artifact_location=azureBlob)
      5 experiment = mlflow.get_experiment_by_name(experiment_name)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\tracking\fluent.py in get_experiment_by_name(name)
    343     :return: :py:class:`mlflow.entities.Experiment`
    344     """
--> 345     return MlflowClient().get_experiment_by_name(name)
    346 
    347 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\tracking\client.py in __init__(self, tracking_uri, registry_uri)
     39                              defaults to the service set by ``mlflow.tracking.set_registry_uri``. If
     40                              no such service was set, defaults to the tracking uri of the client.
---> 41         """
     42         final_tracking_uri = utils._resolve_tracking_uri(tracking_uri)
     43         self._registry_uri = registry_utils._resolve_registry_uri(registry_uri, tracking_uri)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\tracking\_tracking_service\client.py in __init__(self, tracking_uri)
     30         """
     31         self.tracking_uri = tracking_uri
---> 32         self.store = utils._get_store(self.tracking_uri)
     33 
     34     def get_run(self, run_id):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\tracking\_tracking_service\utils.py in _get_store(store_uri, artifact_uri)
    122 _tracking_store_registry.register_entrypoints()
    123 
--> 124 
    125 def _get_store(store_uri=None, artifact_uri=None):
    126     return _tracking_store_registry.get_store(store_uri, artifact_uri)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\tracking\_tracking_service\registry.py in get_store(self, store_uri, artifact_uri)
     35         store_uri = utils._resolve_tracking_uri(store_uri)
     36         builder = self.get_store_builder(store_uri)
---> 37         return builder(store_uri=store_uri, artifact_uri=artifact_uri)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\tracking\_tracking_service\utils.py in _get_sqlalchemy_store(store_uri, artifact_uri)
     83 
     84 def _get_sqlalchemy_store(store_uri, artifact_uri):
---> 85     from mlflow.store.tracking.sqlalchemy_store import SqlAlchemyStore
     86     if artifact_uri is None:
     87         artifact_uri = DEFAULT_LOCAL_FILE_AND_ARTIFACT_PATH

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\store\tracking\sqlalchemy_store.py in __init__(self, db_uri, default_artifact_root)
    102         self.ManagedSessionMaker = mlflow.store.db.utils._get_managed_session_maker(SessionMaker,
    103                                                                                     self.db_type)
--> 104         mlflow.store.db.utils._verify_schema(self.engine)
    105 
    106         if is_local_uri(default_artifact_root):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\store\db\utils.py in _verify_schema(engine)
     46 
     47 def _verify_schema(engine):
---> 48     head_revision = _get_latest_schema_revision()
     49     current_rev = _get_schema_version(engine)
     50     if current_rev != head_revision:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\store\db\utils.py in _get_latest_schema_revision()
     37     config = _get_alembic_config(db_url="")
     38     script = ScriptDirectory.from_config(config)
---> 39     heads = script.get_heads()
     40     if len(heads) != 1:
     41         raise MlflowException("Migration script directory was in unexpected state. Got %s head "

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\script\base.py in get_heads(self)
    318         :return: a tuple of string revision numbers.
    319         """
--> 320         return list(self.revision_map.heads)
    321 
    322     def get_base(self):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\util\langhelpers.py in __get__(self, obj, cls)
    228         if obj is None:
    229             return self
--> 230         obj.__dict__[self.__name__] = result = self.fget(obj)
    231         return result
    232 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\script\revision.py in heads(self)
     70 
     71         """
---> 72         self._revision_map
     73         return self.heads
     74 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\util\langhelpers.py in __get__(self, obj, cls)
    228         if obj is None:
    229             return self
--> 230         obj.__dict__[self.__name__] = result = self.fget(obj)
    231         return result
    232 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\script\revision.py in _revision_map(self)
    121         has_branch_labels = set()
    122         has_depends_on = set()
--> 123         for revision in self._generator():
    124 
    125             if revision.revision in map_:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\script\base.py in _load_revisions(self)
    110                     continue
    111                 dupes.add(path)
--> 112                 script = Script._from_filename(self, vers, file_)
    113                 if script is None:
    114                     continue

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\script\base.py in _from_filename(cls, scriptdir, dir_, filename)
    904                 return None
    905 
--> 906         module = util.load_python_file(dir_, filename)
    907 
    908         if not hasattr(module, "revision"):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\util\pyfiles.py in load_python_file(dir_, filename)
     96     if ext == ".py":
     97         if os.path.exists(path):
---> 98             module = load_module_py(module_id, path)
     99         else:
    100             pyc_path = pyc_file_from_path(path)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\alembic\util\compat.py in load_module_py(module_id, path)
    182         spec = importlib.util.spec_from_file_location(module_id, path)
    183         module = importlib.util.module_from_spec(spec)
--> 184         spec.loader.exec_module(module)
    185         return module
    186 

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\store\db_migrations\versions\27a6a02d2cf1_add_model_version_tags_table.py in <module>
     11 
     12 # revision identifiers, used by Alembic.
---> 13 from mlflow.store.model_registry.dbmodels.models import SqlModelVersionTag
     14 
     15 revision = '27a6a02d2cf1'

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\store\model_registry\dbmodels\models.py in <module>
      5 from sqlalchemy.orm import relationship, backref
      6 
----> 7 from mlflow.entities.model_registry import (RegisteredModel, ModelVersion, RegisteredModelTag, ModelVersionTag)
      8 from mlflow.entities.model_registry.model_version_stages import STAGE_NONE, STAGE_DELETED_INTERNAL
      9 from mlflow.entities.model_registry.model_version_status import ModelVersionStatus

ImportError: cannot import name 'RegisteredModelTag' from 'mlflow.entities.model_registry' (C:\Users\Anand.Suresh\AppData\Local\Continuum\anaconda3\lib\site-packages\mlflow\entities\model_registry\__init__.py)

**Comment by harupy** [comment]
@chatan89 Thanks! How does your `mlflow\entities\model_registry\_init_.py` look like?

**Comment by chatan89** [comment]
@harupy 
Thats correct... its same as above
i checked it before too and it matched with the source code in git

**Comment by harupy** [comment]
@chatan89 hmm strange

**Comment by harupy** [comment]
@chatan89 can you execute `from mlflow.entities.model_registry.registered_model_tag import RegisteredModelTag` or does it throw an error?

**Comment by chatan89** [comment]
same error

**Comment by chatan89** [comment]
@harupy   After reinstalling it worked.  Thanks for the help

**Comment by harupy** [comment]
@chatan89 my pleasure!

**Comment by chatan89** [comment]
Was installation error
