### ISSUE TITLE
[FR] Support tensor inputs to MLflow inference APIs

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#3159]
**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
MLflow's framework-agnostic inference APIs (e.g. `mlflow models serve` for RESTful inference, `mlflow.pyfunc.spark_udf` for batch scoring with Spark, `mlflow.pyfunc.load_model(...).predict(df)` are largely based around scoring DataFrame inputs (although they're capable of producing numpy-array output). In particular, it's difficult to score multidimensional input (e.g. tensors) with the `mlflow.pyfunc` API and related tools. We should investigate ways to make it easier to score such tensor input, either by extending the existing pyfunc flavor or by introducing a new flavor (e.g. tensorfunc? pytensorfunc?)

## Motivation
- What is the use case for this feature? Users of deep learning frameworks, e.g. PyTorch, TensorFlow, and Keras, often want to train and predict with models that accept multidimensional input (e.g. image or NLP models). It's currently not possible to score such models with MLflow
- Why is this use case valuable to support for MLflow users in general? See above - we'd make MLflow models usable for a wide range of deep learning use cases

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by mohammedi-haroune** [comment]
In fact, many issues were open in the mlflow github repo to allow predict to accept multidimensional arrays:

Open issues: 
* [[BUG] ONNX predict fails for high-dimensional models #3229](https://github.com/mlflow/mlflow/issues/3229)
* [[BUG] Predict N-dimensional data with pyfunc from MLmodel #2830](https://github.com/mlflow/mlflow/issues/2830)
* [[FR] Support tensor inputs to MLflow inference APIs #3159](https://github.com/mlflow/mlflow/issues/3159)

Pull requests:
* [Added support for high dimensional onnx models #3307](https://github.com/mlflow/mlflow/pull/3307/)

Closed issues:
* [How to pass 2D array as an input to the MLFlow Model #1480](https://github.com/mlflow/mlflow/issues/1480)
* [[FR]How to transfer the multi-dimensional pixel information of the image to the model after the model is deployed as docker？ #1668](https://github.com/mlflow/mlflow/issues/1668)
* [[BUG] Model predict with json input fails if the dataframe has multi-index #2412](https://github.com/mlflow/mlflow/issues/2412)
* [[FR] Mlflow serve - sending an image #2452](https://github.com/mlflow/mlflow/issues/2452)
* [Recommended handling of I/O for pyfunc? #702](https://github.com/mlflow/mlflow/issues/702)
* [TensorFlow wrapper ravels outputs on predict #1066](https://github.com/mlflow/mlflow/issues/1066)

This is clearly something that blocks so many users from properly use their models logged by MLFlow, some work was done to allow onnx to accept multidimensional data in the pull request linked above trying to understand if the client wants to shape their DataFrame as a multi-dimensional array. I still don't understand why MLFlow predict method is tightly coupled to DataFrames which clearly can't represent a wide range of inputs, why don't we just allow passing numpy arrays?
