### ISSUE TITLE
[FR] Add 'use_conda' parameter to MLflow projects backend plugin

### ISSUE THREAD

**Issue by KarishmaDaga** [mlflow/mlflow#3162]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
The addition of 'use_conda' parameter in MLflow Project backend plugins would support end-to-end data science workflows for customers using a backend plugin for their project execution. It would allow them to test their conda environment and MLproject locally with the plugin before using compute resources for remote execution.

## Motivation
- What is the use case for this feature?
Data scientists can quickly test if their project works locally with their specified conda environment (either local or from mlproject) with their backend plugin before remote execution. 
- Why is this use case valuable to support for MLflow users in general?
Adding use_conda would make it possible for a smooth, end-to-end experience for data scientists using a backend plugin for their training and execution. This would also save time and allow all artifacts and metrics from an experiment to be stored in the plugin's tracking store instead of in two locations. 
- Why is this use case valuable to support for your project(s) or organization?
My project involves creating an AzureML integration with MLflow Projects. Adding this feature would support a full workflow experience for data scientists using AzureML for their backend service.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
Currently use_conda is not passed to backend plugins, so there is no reliable way to infer in the plugin if a user wants to run their project with their local conda environment or the environment specified in MLproject. 
### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [x] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details
These are the main details for the feature!

**Comment by jdlesage** [comment]
Hello @KarishmaDaga.  In the original PR we agreed with mlflow core developers to use the backend_config to pass this argument. The local backend will be good example for the AzureML plugin you are developing. The PR is still in review but you can have a look on how I get this information: https://github.com/mlflow/mlflow/pull/3124/files#diff-093ff776ec235c7cdf333d81948e87f0R50

In this PR, the conda methods are also moved into a separate module in mlflow. You can rely on it to create your environment. Another alternative is to use https://github.com/criteo/cluster-pack that would ship your python environment in a distributed environment.

Does it fit your need ? (cc @smurching )

**Comment by fhoering** [comment]
Hello,

Some additional information. We currently building a yarn backend that implements this api:
https://github.com/criteo/mlflow-yarn

Currently it supports conda.yaml by the mlflow internal apis:
https://github.com/criteo/mlflow-yarn/blob/master/mlflow_yarn/yarn_backend.py#L99

As a next step we will use our own library cluster-pack for packaging which supports conda & using pip with pypi only (https://github.com/criteo/cluster-pack). 
We also plan to add a flag somehow to support also and install from requirements.txt from pypi.

**Comment by KarishmaDaga** [comment]
Hey @jdlesage! Using backend_config works for me, thanks for linking the local backend PR :) 
@fhoering This looks interesting, it might not fit our use case for the plugin but I'll check it out.
