### ISSUE TITLE
[DOC-FIX] Description of filter argument syntax for MlflowClient.search_registered_models is missing

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#3173]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [ ] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ x] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.search_registered_models

### Description of proposal (what needs changing):

We need a description of the syntax that the filter_string argument of MlflowClient.search_registered_models accepts. For example, search_registered_models and search_model_versions do provide descriptions.

Currently search_registered_models simply says "filter_string – Filter query string, defaults to searching all registered models."

**Comment by dmatrix** [comment]
@amesar thanks for filling this. We'll work on providing code snippets and descriptions, not only to newly added APIs but to all APIs. This is an ongoing effort.
