### ISSUE TITLE
[SETUP-BUG] Databricks/R: install_mlflow() by setting MLFLOW_PYTHON_BIN and MLFLOW_BIN

### ISSUE THREAD

**Issue by n8shadow** [mlflow/mlflow#3177]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux 4.15.0-1050-azure
- **MLflow installed from (source or binary)**: Databricks runtime ML 7.1
- **MLflow version (run ``mlflow --version``)**: 1.10.0
- **Python version**: 3.6
- **Exact command to reproduce**: %r mlflow::install_mlflow(...)

### Describe the problem
I'm working on Azure Databricks and I would like to use mlflow. However, my company is restricting the internet connection such that the required files cannot be downloaded to build up the conda environment.
In the docu I read:
"Alternatively, you can set MLFLOW_PYTHON_BIN and MLFLOW_BIN environment variables
instead. MLFLOW_PYTHON_BIN should point to python executable and MLFLOW_BIN to
mlflow cli executable."
I don't see how to set these parameters to make use of an existing environment that - to my understanding - should in general be available on Databricks 7.x and what the correct paths (e.g. /dbfs/databricks/...) are.
Any clarification on that would be muchappreciated, thanks in advance!

### Other info / logs
-

**Comment by dmatrix** [comment]
@n8shadow thanks for filling this. 

Are you a Databricks customer? If so you might want to file a ticket. Mostly issues here deal with OSS.

**Comment by n8shadow** [comment]
@dmatrix thanks for replying. Yes, I am a Databricks customer. However, I guess the mlflow R - package is maintained on mlflow side and I hoped to get quick help in form of an extension/elaboration of the package docu which is lacking details. That would be great!

**Comment by dmatrix** [comment]
@n8shadow Even though [MLflow -R ](https://rdrr.io/cran/mlflow/) maintained as part of OSS MLflow,  you are referring to[ this documentation](https://www.mlflow.org/docs/latest/R-api.html#install-mlflow) lacking details. What additional details you think are missing?

One way you can set these environment variables is via the ["Advanced Options"](https://stackoverflow.com/questions/56856005/how-to-set-environment-variable-in-databricks) when creating clusters.

Try this option.

**Comment by n8shadow** [comment]
@dmatrix Here is what worked for in the end without docker image or init script. I suggest to add such a code snippet to the R package docu:
     ### run on databricks R notebook to use existing environment
     library(mlflow)
     ## get paths
     system("which mlflow")
     # /databricks/conda/envs/databricks-ml/bin/mlflow
     system("which python")
     # /databricks/conda/envs/databricks-ml/bin/python
     ## set paths
     Sys.setenv(MLFLOW_BIN=system("which mlflow"))
     Sys.setenv(MLFLOW_PYTHON_BIN=system("which python"))
     ## set tracking uri to "databricks"
     mlflow::mlflow_set_tracking_uri("databricks")

**Comment by dmatrix** [comment]
Excellent!
