### ISSUE TITLE
Migrating from file-store to database-store without losing experiment information?

### ISSUE THREAD

**Issue by lotsoffood** [mlflow/mlflow#3218]
Is it possible to migrate from a file-store backend to a database-store backend without losing any existing experiment data or artifacts?

**Comment by dmatrix** [comment]
@lotsoffood Yes, there are [tools and scripts](https://github.com/amesar/mlflow-tools/tree/master/mlflow_tools/export_import) you can use for migration.

**Comment by lotsoffood** [comment]
@dmatrix Thank you! I was no aware of that set of tools. I'll close this out, as it does what I"m looking for.
