### ISSUE TITLE
[BUG]Model Registry is not working from the UI.

### ISSUE THREAD

**Issue by abhishekmm** [mlflow/mlflow#3235]
Hi all,
I tried using the sqlite as well as MYSQL on ubuntu system using following command :
mlflow server --backend-store-uri sqlite:///mlruns.db --default-artifact-root gs://mflowdemo/ --host 0.0.0.0
yet I am not ablet register the model from mlflow UI
mlflow --version
mlflow, version 1.10.0

**Comment by harupy** [comment]
@abhishekmm Thanks for filing this. Did you got an error when you tried to register a model from the run page?

**Comment by abhishekmm** [comment]
@harupy I am not any error on log console. the register button itself is not visible
![reg_issue](https://user-images.githubusercontent.com/8172732/89514712-d2177980-d7f3-11ea-82c9-0db362efc3cc.png)

**Comment by harupy** [comment]
@abhishekmm Thanks. I guess you're using an old version of MLflow. Can you update it to the latest?

**Comment by abhishekmm** [comment]
@harupy 
I have  used following line  in 
mlflow.sklearn.log_model(sk_model=model,artifact_path=None)

**Comment by harupy** [comment]
@abhishekmm 
Can you try `mlflow.sklearn.log_model(sk_model=model, artifact_path="model")` instead? After running this, you should be able to see a `mdoel` folder in the UI.

**Comment by abhishekmm** [comment]
@harupy 
I agree even expected the same however the  register-model button is not visible onUI as shown in screenshot before

**Comment by harupy** [comment]
@abhishekmm Do you see a folder named "model"?

**Comment by abhishekmm** [comment]
@harupy   yes  I am  able  see regester button 
artifact_path: model
previously it was null
thanks

**Comment by harupy** [comment]
@abhishekmm My pleasure!

**Comment by NilakshanKunananthaseelan** [comment]
> @abhishekmm
> Can you try `mlflow.sklearn.log_model(sk_model=model, artifact_path="model")` instead? After running this, you should be able to see a `mdoel` folder in the UI and it has a register-model button.

After running this I  ran `mlflow server --backend-store-uri sqlite:///mydb.db  --default-artifact-root /home/ubuntu/Desktop/ExentAI/textofia_web/mlflow/sklearn/mlruns/ -h 0.0.0.0 -p 8005
`
It gave me an empty mlflow UI,but  `mlflow ui` command ca[tures runs.

![image](https://user-images.githubusercontent.com/25349618/127734871-96bd9c53-65ad-4457-8663-cc92dabf17c5.png)
