### ISSUE TITLE
Package mlflow model with preprocessing

### ISSUE THREAD

**Issue by dqsy** [mlflow/mlflow#3261]
Is there any way we can package a deployed mlflow model with preprocessing required for model input such that the end user can simply call the API curl command using the original raw features which returns the prediction?

**Comment by dmatrix** [comment]
@dqsy There maybe a couple of ways to achieve this. One way is to write it the model as [Python Customized Model](https://mlflow.org/docs/latest/models.html#custom-python-models), which will allow you to pre-and post-process your input code.

Another way is to create a REST endpoint which does the following:

- Loads your desired model 

- preprocess the model's input

- invoke model.predict(modief_input)

- return the predicted result.

So, in fact, your curl and POST the workload as raw input, the API hander on your REST server can preprocess the input, load the model, cache it, and the repeatedly service the request.
