### ISSUE TITLE
License for MLflow icon

### ISSUE THREAD

**Issue by Gsbreddy** [mlflow/mlflow#3280]
Hey @gioa
Hope you are well.
I am using mlflow svg icon you [provided](https://github.com/mlflow/mlflow/issues/1853) in my own application. I wanted to know if there is a license for this image. I opened up that[ zip ](https://github.com/mlflow/mlflow/files/3881869/MLflow-logo-set.zip)you provided and there's no license in there either. Without a license, I can't use the images, is there perhaps one on website or anything? (here's an example from github https://github.com/logos)

Please help me on this. Thanks!

**Comment by Gsbreddy** [comment]
Can anyone please help me on this? Thanks in advance.

**Comment by dmatrix** [comment]
@Gsbreddy Thanks for asking this question. @pogil given MLfow joining the Linux Foundation, do we any additional license requirements that you are aware of for using MLflow usage other than[ LICENSE.txt](https://github.com/mlflow/mlflow/blob/master/LICENSE.txt)?

**Comment by gioa** [comment]
Thank you for the question @Gsbreddy! Here is the trademark policy from Linux Foundation which includes MLflow:
https://lfprojects.org/policies/trademark-policy/

Let us know what else you may need!

**Comment by Gsbreddy** [comment]
Let me take this back and see if this is what we are looking for. Thanks guys!

**Comment by dmatrix** [comment]
@Gsbreddy, you welcome. I'll close this issue.
