### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KarimSamehSadek** [mlflow/mlflow#3300]
- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [X] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: stock example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Both Windows and Linux got the same error
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 1.10.0 and 1.8.0
- **Python version**: 3.7.6 , 3.7.7, 3.8.5
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:import mlflow.pyfunc

### Describe the problem
I want to use the mlflow custom python function but all my interpreters on all envrionments I have on both windows and a remote linux server result in the same error

### Code to reproduce issue
import mlflow.pyfunc

### Other info / logs
AttributeError: module 'mlflow' has no attribute 'pyfunc'

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages
- [x] python 
Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@KarimSamehSadek Can you provide your code?

**Comment by KarimSamehSadek** [comment]
> @KarimSamehSadek Can you provide your code?

Hi, I already resolved it. I created a new file and copied the same code and worked. thank you though
