### ISSUE TITLE
[SETUP-BUG] Mlflow is not writting to the s3 bucket

### ISSUE THREAD

**Issue by rd16395p** [mlflow/mlflow#3305]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this installation issue template to ensure a timely and thorough response.**

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **MLflow installed from (source or binary)**:  Source
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.10.0
- **Python version**: 3.7
- **Exact command to reproduce**:

I am launching the ml server on an ec2 with a postgres database and a s3 bucket, and local host 0.0.0.0

### Describe the problem
Provide the exact sequence of commands / steps that you executed before running into the problem.

When I create an experiment either on the command line or through the ui, it does not show up in the s3 at all. I am able to write to the s3 bucket through the aws cli. 

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rd16395p** [comment]
@harupy Just tried this out and it is not showing on my mlflow tracking server - but it is logged to my s3 bucket. Is there something I am missing?

**Comment by harupy** [comment]
What's not show in your mlflow server?

**Comment by rd16395p** [comment]
@harupy Yup, the experiment itself.

**Comment by harupy** [comment]
@rd16395p Just to confirm, the code in https://github.com/mlflow/mlflow/issues/3305#issuecomment-678787885 worked and showed the experiment properly on the UI?

**Comment by rd16395p** [comment]
@harupy  Yes, it did when I tried it on the server itself. 

If I store my experiments on the same s3 and postgres, would it show up on the mlflow server? 

Thank you for helping me so much!

**Comment by harupy** [comment]
@rd16395p 

> If I store my experiments on the same s3 and postgres, would it show up on the mlflow server?

I think it would if the mlfow server points to the correct backed store.

**Comment by rd16395p** [comment]
@harupy I understand, but it would be better to send it to the server right?

**Comment by rd16395p** [comment]
with the great here, and this link I finished the server 👍 
https://medium.com/@alexanderneshitov/how-to-run-an-mlflow-tracking-server-on-aws-ec2-d7afd0ac8008

**Comment by pagronau** [comment]
I have a similar issue with minio as S3:
````
import mlflow

mlflow.set_tracking_uri("sqlite:///sql.db")
mlflow.set_registry_uri("http://127.0.0.1:9000")   # replace
expr_name = "new_experiment_2"
s3_bucket = "S3://mlflow"  # replace

mlflow.create_experiment(expr_name, s3_bucket)
mlflow.set_experiment(expr_name)

with mlflow.start_run():
    # debug
    print(mlflow.get_artifact_uri())
    print(mlflow.get_tracking_uri())
    
    mlflow.log_param("foo", 0)
    mlflow.log_metric("bar", 1)
    
    with open("test.txt", "w") as f:
        f.write("test")

    mlflow.log_artifact("test.txt")
````

throws:
````
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised an unhandled exception: Not supported URL scheme s3
````

s3_bucket = "S3://127.0.0.1:9000" 
s3_bucket = "S3://127.0.0.1:9000/mlflow"
both throw:
````
Invalid bucket name "127.0.0.1:9000": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
````

s3_bucket = "http://127.0.0.1:9000/mlflow"
throws
````
mlflow.exceptions.MlflowException: Could not find a registered artifact repository for: http://127.0.0.1:9000/mlflow/b2c2ef8adb444db08de266a60ccdd3ff/artifacts. Currently registered schemes are: ['', 'file', 's3', 'gs', 'wasbs', 'ftp', 'sftp', 'dbfs', 'hdfs', 'viewfs', 'runs', 'models']
````

**Comment by pedro-fraguas** [comment]
@3WlVzK0N I had the same issue last week. What happened to me was that there was a policy preventing me from using s3 as the artifact store. You can simulate your permissions in the following link.
[https://policysim.aws.amazon.com/]
Hope this helps!

**Comment by nfarley-soaren** [comment]
I tried harupy's code to log the test.txt to my S3 bucket but it only wrote test.txt to a local file, though it printed out the correct URIs.  Not sure how to get it to actually log to S3.
```

mlflow.set_tracking_uri(<mysql db>) 
expr_name = "new_experiment" 
s3_bucket = <my S3 bucket>  # replace this value
mlflow.create_experiment(expr_name, s3_bucket)
mlflow.set_experiment(expr_name)

with mlflow.start_run():
    print(mlflow.get_artifact_uri())  # should print out an s3 bucket path
    
    # create a file to log
    with open("test.txt", "w") as f:
        f.write("test")

    mlflow.log_artifact("test.txt")
```
