### ISSUE TITLE
How do I set a different local directory for mlflow?

### ISSUE THREAD

**Issue by MatthiasHerp** [mlflow/mlflow#3317]
I want to run the mlflow ui from a different folder. By default it creates a folder called 'mlruns' in the folder of my user. If create runs in a Jupiter-Notebook using a specific working directory a new Folder 'mlruns' is created in that directory. My goal is to run the mlflow ui acccessing the 'mlruns' Folder in this self specified Directory. So far I have tried:
running mlflow ui in the anaconda prompt PowerShell from the Directory i use
defining the Directory in running the mlflow Server by:

mlflow ui --backend-store-uri file:///'directory here'

I use Windows, Anaconda, Python, Jupiter-Notebook and the latest mlflow Version (1.10)

**Comment by harupy** [comment]
@MatthiasHerp What issue are you experiencing?

**Comment by dmatrix** [comment]
@MatthiasHerp Thanks for asking the question. You have to set the experiment URI too.

Here is a [Jupyter Example](https://github.com/dmatrix/google-colab/blob/master/mlflow_issue_3317.ipynb).

**Comment by MatthiasHerp** [comment]
@harupy : there was no error message. the server works but doesn't go to the desired folder.

@dmatrix: thanks for the response and the example.
And sorry for the late response.

I tried the following Code:
(my URI is at : C:User/User/mah/Desktop/M5_Wallmart_Challenge)

import mlflow

mlflow.set_tracking_uri("file:///Desktop/M5_Wallmart_Challenge")

get_ipython().system_raw("mlflow ui --backend-store-uri file:///Desktop/M5_Wallmart_Challenge --port 5000 &")

But the Server still goes to the Default Location of the user: C:User/User/mah

**Comment by harupy** [comment]
@MatthiasHerp have you tried using `\` instead of `/`?

**Comment by MatthiasHerp** [comment]
@harupy yes, then I get the error: 

<>:1: DeprecationWarning: invalid escape sequence \D
<>:1: DeprecationWarning: invalid escape sequence \D
<>:1: DeprecationWarning: invalid escape sequence \D
<ipython-input-3-b9629adec179>:1: DeprecationWarning: invalid escape sequence \D
  mlflow.set_tracking_uri("file:\\\Desktop\M5_Wallmart_Challenge")

**Comment by harupy** [comment]
Can you try `file:///\D\...`?

**Comment by MatthiasHerp** [comment]
@harupy I get the same error as above:

> <>:1: DeprecationWarning: invalid escape sequence \D
> <>:1: DeprecationWarning: invalid escape sequence \D
> <>:1: DeprecationWarning: invalid escape sequence \D
> :1: DeprecationWarning: invalid escape sequence \D
> mlflow.set_tracking_uri("file:\\Desktop\M5_Wallmart_Challenge")

I tried it with two or three slashes (/), as well as with User twice and one in the URI as you wrote above.

**Comment by harupy** [comment]
I have updated the command

**Comment by MatthiasHerp** [comment]
The Code only run with / . Could It be something else. For example to run the Server I run 'mlflow ui' in the anaconda prompt powershell. I tired running it in the Default loacation (C:/User/mah) and in the specific Folder (C:/User/mah/desktop/M5_Wallmart_Challenge) but neither helped. Do I Need to deactivate the old server?

**Comment by harupy** [comment]
Have you tried without `file://`?

**Comment by MatthiasHerp** [comment]
just tried it.

get_ipython().system_raw("mlflow ui --backend-store-uri C:/User/mah/Desktop/M5_Wallmart_Challenge --port 5000 &")

now Ends and doesn't run continously. But still the Directory of the ui does not change

**Comment by harupy** [comment]
Are runs logged in the directory set by `mlflow.set_tracking_uri`?

**Comment by MatthiasHerp** [comment]
@harupy : yes

**Comment by harupy** [comment]
When you run `mlflow ui` in the anaconda prompt, did you gey an error or a warning?

**Comment by MatthiasHerp** [comment]
Hello,
I looked into the Problem with a fresh perspective after I tended to urgent work.
Apparently your tipps worked fine, i don't really know what my issue was.

In short:
1. To set up the UI Server taking the experiment and run information from a certain folder type the following in the Anaconda Prompt Powershell: mlflow ui --backend-store-uri file///:'Directory to the mlrun folder' for example mlflow ui --backend-store-uri file///:User/mah/mlruns

2. To determine in which folder runs are logged type the following in python before runs:
mlflow.set_tracking_uri("file///:'Directory to the mlrun folder'") for example:  mlflow.set_tracking_uri("file///:User/mah/mlruns")

Thanks to @harupy and @dmatrix for your help :)
I hope this last post helps people who have a similar Problems and read this Issue.

**Comment by philippengani** [comment]
> Hello,
> I looked into the Problem with a fresh perspective after I tended to urgent work.
> Apparently your tipps worked fine, i don't really know what my issue was.
> 
> In short:
> 
> 1. To set up the UI Server taking the experiment and run information from a certain folder type the following in the Anaconda Prompt Powershell: mlflow ui --backend-store-uri file///:'Directory to the mlrun folder' for example mlflow ui --backend-store-uri file///:User/mah/mlruns
> 2. To determine in which folder runs are logged type the following in python before runs:
>    mlflow.set_tracking_uri("file///:'Directory to the mlrun folder'") for example:  mlflow.set_tracking_uri("file///:User/mah/mlruns")
> 
> Thanks to @harupy and @dmatrix for your help :)
> I hope this last post helps people who have a similar Problems and read this Issue.

Hey thanks for this detailed answer. Please can you change the position of the ":"? 

I think it should be **file:///User/mah/mlruns** instead of **file///:User/mah/mlruns**.

Furthermore, note that you should end all running **mlflow ui **. If not, the default location will not change.
