### ISSUE TITLE
Support HDFS Artifact Repository

### ISSUE THREAD

**Issue by nilday** [mlflow/mlflow#332]
We would really like to contribute a hdfs artifact repository implement, . Would you like to have one?

There is a tiny problem: Most of the hdfs client in python (such as `pip intall hdfs`) only support webhdfs protocal. We would like to have a native hdfs support. So we 'd like to introduce a dependency `pyarrow` which support libhdfs or libhdfs3. Does it sound acceptable, for it's not a very light dependency?

**Comment by nilday** [comment]
I found that local mode only support file store and aritifact, while using mlflow server could solve my problem. Sorry for bothering you.

**Comment by mparkhe** [comment]
Hi @nilday: Thanks for the question. One of the ways to get around this would be `import pyarrow` and `HadoopFileSystem` locally inside constructor for `HdfsArtifactRepository`. Something like this-

```
class HdfsArtifactoryRepository(ArtifactRepository):
    def __init__(self, ...):
            import pyarrow
            from pyarrow.hdfs import connect
            self.hdfs = connect(...)
    # implement other methods
```

Most of the model flavors (h2o, keras, pytorch ... etc) do it this way due to the same reason. As you rightly noted the heavy dependency is not loaded automatically. 
Note: test harness already installs `pyarrow`.

One quick question: What is the nature of your project? As you mentioned WebHDFS is a lighter protocol. What are the requirements that are necessitating a native hdfs support?

**Comment by nilday** [comment]
@mparkhe webhdfs protocol does not support ha. It's not a big problem because I find python hdfs client support ha ha in client end. In some cases, the hadoop cluster may disable webhdfs protocol. I think it's just a trade off, whether support more feathers with heavier dependency or just use lighter protocol. 
How about use pyarrow native libhdfs  by default and fallback to webhdfs if it's pyarrow or libhdfs not installed?(But there is still a problem: hdfs and webhdfs default ports are different, we cannot indicate  two ports at the same for fallback usage without introducing new configuration )

**Comment by mparkhe** [comment]
I think it would be cleaner to have these are separate artifact repos classes. I agree with concern about increase import time and additional dependencies. It would be cleanest to import `pyarrow` only in the `__init__` function to instantiate the file system handler.

Do you want to submit a pull request for a native `HdfsArtifactRepository` using `pyarrow` library? If needed we can write another `WebHdfsArtifactRepository` in future if there is a use case for it.

Thanks!

**Comment by nilday** [comment]
Yes I would submit a pull request. I've finished coding work. I will submit a pr as soon as I write some test and document.

**Comment by nilday** [comment]
@mparkhe hello, I've finished main code a long time, but I have some problem dealing with unit test. I'm not very familiar with python Mock, so I find it really hard for me to write the right unit test. Would you mind I submit without unit test? Or you don't mind wait a little longer so that I could figure out how to write the right unit test?

**Comment by jaroslawk** [comment]
@nilday is there any progress on the HDFS artifact repository? We would be also interested in using it.

**Comment by kiranvaranasi81** [comment]
We are working on hdfs artifact repository https://github.com/kiranvaranasi81/mlflow/commits/hadoop_artifact. We will soon raise pull request completing our testing.

**Comment by jaroslawk** [comment]
got it. I will take a look. There is a chance we will start using ml flow and this is an important part we are missing.

**Comment by DatPhanTien** [comment]
Dear all, we are interesting in using MLFlow. Just wonder if the HDFS support (as the DB to store the ML models) is currently implemented in MLFlow?
Thanks

**Comment by jaroslawk** [comment]
@DatPhanTien the implementation got just merged to the master: https://github.com/mlflow/mlflow/pull/1011 
I have been using it for a while and it works ok.

In case you got any issues/questions you can ping me.

**Comment by jaroslawk** [comment]
@nilday @mparkhe guess we can close this issue?
