### ISSUE TITLE
R on databricks: ..cannot import name 'BlobPrefix' when calling mlflow_load_model 

### ISSUE THREAD

**Issue by saroup** [mlflow/mlflow#3321]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks 6.5 x86_64-pc-linux-gnu, Running under: Ubuntu 16.04.6 LTS
- **MLflow installed from (source or binary)**: from source
- **MLflow version (run ``mlflow --version``)**: r-mlflow-1.10.0
- **Python version**: 3.6

### Describe the problem
On Databricks, I have an R notebook that is trying to load a model from an Azure storage location and it fails to do so.

### Code to reproduce issue
install.packages("mlflow")
library(mlflow)
install_mlflow()
mlflow_run_id = "123456789"

run <- mlflow_get_run(run_id = mlflow_run_id)
model_location <- paste0(run$artifact_uri,"/model.rds")
loaded_model <- mlflow_load_model(model_uri =model_location)

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
  System command 'mlflow' failed, exit status: 1, stderr:
E> Traceback (most recent call last):
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/bin/mlflow", line 8, in 
E>     sys.exit(cli())
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/click/core.py", line 829, in __call__
E>     return self.main(*args, **kwargs)
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/click/core.py", line 782, in main
E>     rv = self.invoke(ctx)
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
E>     return _process_result(sub_ctx.command.invoke(sub_ctx))
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
E>     return _process_result(sub_ctx.command.invoke(sub_ctx))
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
E>     return ctx.invoke(self.callback, **ctx.params)
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/click/core.py", line 610, in invoke
E>     return callback(*args, **kwargs)
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/mlflow/store/artifact/cli.py", line 112, in download_artifacts
E>     print(**_download_artifact_from_uri**(artifact_uri))
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/mlflow/tracking/artifact_utils.py", line 74, in _download_artifact_from_uri
E>     artifact_path=artifact_path, dst_path=output_path)
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/mlflow/store/artifact/artifact_repo.py", line 127, in download_artifacts
E>     if self._is_directory(artifact_path):
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/mlflow/store/artifact/artifact_repo.py", line 62, in _is_directory
E>     listing = self.list_artifacts(artifact_path)
E>   File "/databricks/conda/envs/r-mlflow-1.10.0/lib/python3.6/site-packages/mlflow/store/artifact/azure_blob_artifact_repo.py", line 89, in list_artifacts
**E>     from azure.storage.blob._models import BlobPrefix
E> ImportError: cannot import name 'BlobPrefix'**

SessionInfo() gives:

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.2.2 usethis_1.5.1  mlflow_1.7.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         compiler_3.6.3     pillar_1.4.6       later_1.1.0.1     
 [5] remotes_2.1.1      prettyunits_1.1.1  TeachingDemos_2.10 base64enc_0.1-3   
 [9] tools_3.6.3        testthat_2.3.1     pkgload_1.0.2      pkgbuild_1.0.6    
[13] zeallot_0.1.0      digest_0.6.25      memoise_1.1.0      jsonlite_1.7.0    
[17] tibble_3.0.3       lifecycle_0.2.0    lattice_0.20-40    pkgconfig_2.0.3   
[21] rlang_0.4.7        Matrix_1.2-18      cli_2.0.2          curl_4.3          
[25] yaml_2.2.1         swagger_3.9.2      withr_2.2.0        httr_1.4.2        
[29] hwriter_1.3.2      desc_1.2.0         vctrs_0.3.2        fs_1.5.0          
[33] askpass_1.1        rprojroot_1.3-2    grid_3.6.3         reticulate_1.16   
[37] glue_1.4.1         forge_0.2.0        R6_2.4.1           processx_3.4.3    
[41] fansi_0.4.1        sessioninfo_1.1.1  callr_3.4.2        purrr_0.3.4       
[45] SparkR_2.4.5       magrittr_1.5       backports_1.1.5    ps_1.3.4          
[49] promises_1.1.1     hwriterPlus_1.0-3  htmltools_0.4.0    ellipsis_0.3.1    
[53] assertthat_0.2.1   Rserve_1.8-6       httpuv_1.5.4       ini_0.3.1         
[57] openssl_1.4.2      crayon_1.3.4      

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
Language 
- [X ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [X ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X ] `integrations/databricks`: Databricks integrations

**Comment by saroup** [comment]
install_mlflow() shows that azure-storage-blob 12.4.0 is being installed.

**Comment by saroup** [comment]
In azure-blob-storage 12.4.0 blobPrefix hasn't been imported here : https://github.com/Azure/azure-sdk-for-python/blob/azure-storage-blob_12.4.0/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py 
where as in 12.3.2: https://github.com/Azure/azure-sdk-for-python/blob/azure-storage-blob_12.3.2/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py

**Comment by dbczumar** [comment]
Hi @saroup , I've filed #3348 to address this issue. In 12.4.0, it appears that the `BlobPrefix` object became part of the public API and is now included as `azure.storage.blob.BlobPrefix`, rather than `azure.storage.blob._models.BlobPrefix`. This fix will be merged and included in MLflow 1.11.0 (due for release next week).

**Comment by dbczumar** [comment]
#3348 has been merged - this issue should now be resolved!
