### ISSUE TITLE
How could I use different store and artifact repo?

### ISSUE THREAD

**Issue by nilday** [mlflow/mlflow#333]
If I'm going to use, for example, rest store as well as gcs artifact repo, how could  I config it?
I've only found one configuration that may related to this, which is 'MLFLOW_TRACKING_URI'.
As the artifact_uri mostly init by store, I find there's no way to use two different store and artifact repo at the same time. And also, I find s3, gcs, azure artifact repo only exists in test file. I doubt you have only test file store and artifact repo end-to-end.
Am I wrong? Is there a way to configure it?
If there's not, I would really like to implement one.

**Comment by smurching** [comment]
Hi @nilday, it is confusing to keep track of the different stores & artifact repos - @mparkhe actually brought this up today (we should likely refactor mlflow.store into two separate modules). 

Conceptually, FileStore & RestStore are clients of the tracking API. RestStore is used to talk to remote tracking servers, while FileStore is used to write tracking information to the local filesystem. Both classes are actually intended to be internal - MLflow will automatically use the right store based on the tracking URI you specify (as you stated, you can specify the tracking URI via `MLFLOW_TRACKING_URI` or by calling `mlflow.set_tracking_uri`, etc)

**Comment by nilday** [comment]
I found that local mode only support file store and artifact, while using mlflow server could solve my problem. Thanks a lot

**Comment by jrderuiter** [comment]
@smurching Wouldn't it make sense to allow a user also to specify their own ArtifactStore instance? This would allow users to implement their own ArtifactStore implementation when needed, as long as it follows the correct interface. (We have an environment where this would be useful.)

Following this idea, you could then instantiate an MlFlowClient using:

```
client = MlflowClient(store=MyCustomRepository())
```

Of course, the default can still be to infer the correct repository from the tracking URL where possible.
