### ISSUE TITLE
[BUG] mlflow run won't accept parameters' value containing "="

### ISSUE THREAD

**Issue by alpancs** [mlflow/mlflow#3346]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes I do
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Manjaro Linux 20.1
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.10.0
- **Python version**: Python 3.7.7
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: `mlflow run . -P equation="1 + 2 = 3"`

### Describe the problem
Command `mlflow run` doesn't parse parameters correctly. It fails when the value of a parameter contains "=".

### Code to reproduce issue
Here I have an `MLproject` file
```yaml
entry_points:
  main:
    parameters:
      equation: string
    command: python equation-parser.py {equation}
```
and a python code `equation-parser.py`.
```python
import sys

print('got equation:', sys.argv[1])
```

Then I run the following commands
```sh
$ mlflow run . -P equation="1 + 2 = 3"
Invalid format for -P parameter: 'equation=1 + 2 = 3'. Use -P name=value.
$ mlflow run . -P "equation=1 + 2 = 3"
Invalid format for -P parameter: 'equation=1 + 2 = 3'. Use -P name=value.
```

### Other info / logs
N/A

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@alpancs Thanks for filing this issue. 

With MLproject file: 
```
entry_points:
  main:
    parameters:
      equation: {type: string, default: "y=mx+c"}
    command: python equation-parser.py --equation {equation}
```
and the equation_parser.py:
```
import sys

if __name__ == "__main__":
   equation = sys.argv[1] if len(sys.argv)  > 1 else "y=mx+c"
   print(f"equation={equation}")
```

`mlflow run . -e main -P equation="2mx+c"`         # <- seems to work
`mlflow run . -e main`                                                     # <- seems to work
`mlflow run . -e main -P equation="y=2mx+c"`   # <- gives you the error

Invalid format for -P parameter: 'equation=y=2mx+c'. Use -P name=value.

**Comment by alpancs** [comment]
> Curious, what's the use case where you want an expression with an equality sign in the -P <name>=<value=expression>?

@dmatrix: for instance, I need to pass an URI that points to a table's snapshot in a data warehouse, e.g.
```
gs://some-bucket/some-db/some-table/snapshot/date=2020-08-27
```

Actually it is valid on mlflow 1.9.1, but invalid on mlflow 1.10.0.

**Comment by dbczumar** [comment]
@alpancs Thanks for pointing this out. This is a regression in 1.10.0 introduced by #3061. I've filed #3347 to fix it; this will be merged and included in the next release of MLflow (slated for release next week). For now, you can either leverage MLflow 1.9.1 or check out the PR branch and install MLflow from there (https://github.com/dbczumar/mlflow/tree/param_fix). Sorry for the inconvenience that this may have caused!

**Comment by alpancs** [comment]
Thanks @dbczumar for fixing it!
