### ISSUE TITLE
Unpin sqlalchemy

### ISSUE THREAD

**Issue by CaselIT** [mlflow/mlflow#3353]
Hi,

Currently mlflow pins sqlalchemy to `<= 1.3.13`. I wanted to use this package on a projects that requires a more updated version of sqlalchemy.
Would it be possible to unpit sqlalchemy or to change the constraint to disallow specific version of it? (like `!=1.3.14` etc?)

Thanks

**Comment by harupy** [comment]
@CaselIT Thanks for filing this.

https://stackoverflow.com/a/12759996/6943581

> pip has a --no-dependencies switch. You should use that.

**Comment by CaselIT** [comment]
Thanks for the suggestion, but I would then manually have to track all the other mlflow dependencies, so it becomes hard to maintain. I'll do that for the moment.

**Comment by harupy** [comment]
Or you can try:

```
pip install mlflow
pip install -U sqlalchemy
```

you'll get a warning though.

**Comment by CaselIT** [comment]
Would a PR be accepted to unpin it? I gather that the problem was 1.3.14?

**Comment by harupy** [comment]
See https://github.com/mlflow/mlflow/pull/2587

**Comment by CaselIT** [comment]
#2587 is outdated, 1.3.16+ no longer use pep517.

**Comment by harupy** [comment]
@CaselIT you're right. In 1.3.16, sqlalchemy started uploading wheels: https://pypi.org/project/SQLAlchemy/1.3.16/#files

**Comment by harupy** [comment]
@smurching Should we unpin `sqlalchemy` (We need to verify that a newer version of `sqlalchemy` doesn't cause errors in Databricks though)?

**Comment by CaselIT** [comment]
Yes, also pep517 was disabled here https://github.com/sqlalchemy/sqlalchemy/commit/fcb22fa8e26eaf7f0c1a99b8b20275a3557a240f
