### ISSUE TITLE
Coupling of Tracking and Projects

### ISSUE THREAD

**Issue by kevinykuo** [mlflow/mlflow#337]
In https://mlflow.org/docs/latest/concepts.html#concepts it is implied that one can use one component of MLflow without the others. However, currently running a projects triggers a Tracking experiment run: https://github.com/mlflow/mlflow/blob/766ff1d1a36b17b58319e8f70cd71aa8d29141a2/mlflow/projects/__init__.py#L44-L47 

Is this intended? One could potentially have the use case of wanting a reproducible model run without wanting tracking functionality.

**Comment by pogil** [comment]
It's true that there is some coupling here. If this is an issue, you could use a local tracking service or create a no-op tracking service that drops requests.
