### ISSUE TITLE
If synchronous was False, it won't pass docker_args in subprocess?

### ISSUE THREAD

**Issue by Gingersna** [mlflow/mlflow#3372]
https://github.com/mlflow/mlflow/blob/d743a40426d5dedbde395a4e6bbdeebadbccd4dc/mlflow/projects/backend/local.py#L101-L109

**Comment by dmatrix** [comment]
@smurching what do you think, it seems like the behavior for [constructing the cmd_str ](https://github.com/mlflow/mlflow/blob/d743a40426d5dedbde395a4e6bbdeebadbccd4dc/mlflow/projects/backend/local.py#L94)is different if the `synchronous` flag is `true.` Is that intentional?

**Comment by alfozan** [comment]
> @smurching what do you think, it seems like the behavior for [constructing the cmd_str ](https://github.com/mlflow/mlflow/blob/d743a40426d5dedbde395a4e6bbdeebadbccd4dc/mlflow/projects/backend/local.py#L94)is different if the `synchronous` flag is `true.` Is that intentional?

this looks like a bug to me.

**Comment by alfozan** [comment]
PR fix https://github.com/mlflow/mlflow/pull/3563
Bug report: https://github.com/mlflow/mlflow/issues/3562

I think this issue can be closed in favor of #3562 
cc @dmatrix 
Thanks

**Comment by dmatrix** [comment]
@alfozan, yes make sense since you working on that PR and @harupy feedback. Will close this now.
Thanks!
