### ISSUE TITLE
Documentation does not match REST API JSON attribute types

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#339]
### System information
- **Linux, Mac**:
- **MLflow installed from binary**: 
- **MLflow version 0.5.0**:
- **Python version**: 2.7 and 3.5
- **Exact command to reproduce**: ``http://localhost:5000/api/2.0/preview/mlflow/runs/get?run_uuid=288d0742693e40bd90cea02bac2e5e9a``

### Describe the problem

Attributes such as experiment_id and start_time are defined as INT64 types in the REST API documentation for Create Experiment, Create Run, RunInfo, etc. But the actual JSON returned is always a string. Furthermore the Python client returns an int. Either the REST API should return "int" or the documentation should be changed to "string".

For example, the return payload for Create Experiment is
```
{  "experiment_id": "9"} 
```
but should be (or change doc)
```
{  "experiment_id": 9} 
```
Similarly for Get Run response RunInfo
```
 "run": {
    "info": {
      "experiment_id": "1"
      "start_time": "1533581041487",
      "end_time": "1533581042488",
       },
```

### Source code / logs

https://mlflow.org/docs/latest/rest_api.html

**Comment by mparkhe** [comment]
Hi @amesar: This is a really good question. According to this [Proto Buf documentation](https://developers.google.com/protocol-buffers/docs/proto3#json), `int64` are JSON serialized to `string`. `int32` and `float` fields are mapped to `number`, as can be seen in the following example. This is the tutorial example run using: `mlflow run example/tutorial -P alpha=0.4`. As you can see the `int64` fields as you reported were encoded as strings, but metric values which are floats are numbers. 

```
$ > curl http://localhost:5000/api/2.0/preview/mlflow/runs/get?run_uuid=2eb13e6ff7674028a80873c8cbb0a714
{
  "run": {
    "info": {
      "status": "FINISHED",
      ...
      "start_time": "1535173990439",
      "source_type": "LOCAL",
      "run_uuid": "2eb13e6ff7674028a80873c8cbb0a714",
      "end_time": "1535173991117",
      "experiment_id": "0",
      ...
    },
    "data": {
      "metrics": [
        {
          "timestamp": "1535173991",
          "value": 0.6174288392066956,
          "key": "mae"
        },
        {
          "timestamp": "1535173991",
          "value": 0.19207580387592316,
          "key": "r2"
        },
        {
          "timestamp": "1535173991",
          "value": 0.7909069061279297,
          "key": "rmse"
        }
      ],
      "params": [
        {
          "value": "0.1",
          "key": "l1_ratio"
        },
        {
          "value": "0.4",
          "key": "alpha"
        }
      ]
    }
  }
}
```

I found few interesting links on this topic-
- https://groups.google.com/forum/#!topic/protobuf/4-BY-k-Lk-g
- https://github.com/protocolbuffers/protobuf/issues/1823
- https://github.com/grpc-ecosystem/grpc-gateway/issues/438
