### ISSUE TITLE
keras.autolog() fails when running model within a sklearn pipeline [BUG]

### ISSUE THREAD

**Issue by sephib** [mlflow/mlflow#3402]
## Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux SLES 12)**:
- **MLflow installed from **: anaconda
- **MLflow version ()**: 1.11
- **Python version**: 3.7
- **Exact command to reproduce**:  

wrapping the code from this [keras-nlp-pipeline](https://github.com/diegoglozano/keras-nlp-pipeline) example with `mlflow`  

<details>  

```
import pandas as pd
import numpy as np
import joblib
import mlflow
import mlflow.keras
from sklearn.pipeline import Pipeline
from gensim.models import KeyedVectors
from keras.wrappers.scikit_learn import KerasClassifier

from library_pipeline_nlp.my_transformers import TokenizerTransformer, PadSequencesTransformer
from library_pipeline_nlp.my_model import create_model

mlflow.keras.autolog()

# PATHS
DATA_PATH = '../data/texts.csv'
EMBEDDING_PATH = '../data/embedding.bin'
PIPE_PATH = '../objects/pipeline.joblib'

# DATA
df = pd.read_csv(DATA_PATH, index_col='id', nrows=100)

# X / y
X = df['tweet'].copy()
y = df['label'].copy()

# DIMENSIONS
longest_text = X.str.split().str.len().max()  # Para padsequences()
EMBEDDING_DIM = 300  # Dimensión Word2Vec

# PRETRAINED WORD2VEC
word_vectors = KeyedVectors.load_word2vec_format(EMBEDDING_PATH, limit=1000, binary=True)

# VOCABULARY SIZE (+1)
vocab_size = len(word_vectors.vocab.keys()) + 1
embedding_weights = np.vstack([np.zeros(word_vectors.vectors.shape[1]), word_vectors.vectors])


# DECLARE ESTIMATORS
my_tokenizer = TokenizerTransformer()
my_padder = PadSequencesTransformer(maxlen=longest_text)
my_model = KerasClassifier(build_fn=create_model,
                           epochs=2,
                           embedding_input_dim=vocab_size,
                           embedding_output_dim=300,
                           embedding_weights=embedding_weights)

# DECLARE PIPELINE
pipeline = Pipeline([
    ('tokenizer', my_tokenizer),
    ('padder', my_padder),
    ('model', my_model)
])

# TRAIN
with mlflow.start_raun() as mlrun:
  pipeline.fit(X, y)
```   

</details>   

### Describe the problem
When running with `autolog` the function that is passed is:    
`<function mlflow.keras.autolog.<locals>.fit(self, *args, **kwargs)>  `
while when running without `autolog` th function is:   
`tensorflow.python.keras.engine.training.Model.fit`  

So when the`autolog` fn parameters are checked in [the keras wrapper](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/wrappers/scikit_learn.py#L77)  
` self.check_params(sk_params)`  
it fails.   

To by pass this you can comment the above check.    
However even with this by pass the code does not consider the `epochs` parameter since it is not gather the argument  in this function:  
[fit_args = copy.deepcopy(self.filter_sk_params(Sequential.fit))](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/wrappers/scikit_learn.py#L163)   
since the`Sequential` object is of `<function mlflow.keras.autolog.<locals>.fit(self, *args, **kwargs)>  ` which does not have the `epochs` param.  
and then the fn  fails with 
[if has_arg(fn, params_name):]( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/wrappers/scikit_learn.py#L102)   

### Workaround  to get `keras.autolog` in current versions:
Add to the `MLflowKerasCallback` class to the `callbacks` in the  KerasClassifier:     
```
my_model = KerasClassifier(build_fn=create_model,
                           epochs=2,
                           embedding_input_dim=vocab_size,
                           embedding_output_dim=300,
                           embedding_weights=embedding_weights,
                           callbacks = [mlflow_keras_callback.__MLflowKerasCallback()],
)
```

### Code to reproduce issue
see [github repo - keras-nlp-pipeline](https://github.com/diegoglozano/keras-nlp-pipeline) with the additional example in this post.  

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends

**Comment by dbczumar** [comment]
@sephib This issue has been addressed via https://github.com/mlflow/mlflow/pull/3387, which will be incorporated into the next release of MLflow. Prior to #3387, autologging calls overwrote function definitions / signatures, resulting in the parameter  validation failures described in this issue.

I've confirmed that the following code now succeeds on the `master` branch of MLflow, while it currently fails on MLflow 1.11.0:

```
#
# Build a KerasClassifier wrapper object.
# I had trouble getting the callable class approach to work. The method approach seems to be pretty universial anyway.
#
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.optimizers import SGD

# Generate dummy data
import numpy as np
import pandas as pd

X_train = np.random.random((1000, 3))
y_train = pd.get_dummies(np.argmax(X_train[:, :3], axis=1)).values
X_test = np.random.random((100, 3))
y_test = pd.get_dummies(np.argmax(X_test[:, :3], axis=1)).values

import mlflow.keras
mlflow.keras.autolog()


from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

# Doesn't work?
# class TwoLayerFeedForward:
#     def __call__():
#         clf = Sequential()
#         clf.add(Dense(9, activation='relu', input_dim=3))
#         clf.add(Dense(9, activation='relu'))
#         clf.add(Dense(3, activation='softmax'))
#         clf.compile(loss='categorical_crossentropy', optimizer=SGD())
#         return clf

def twoLayerFeedForward():
    clf = Sequential()
    clf.add(Dense(9, activation='relu', input_dim=3))
    clf.add(Dense(9, activation='relu'))
    clf.add(Dense(3, activation='softmax'))
    clf.compile(loss='categorical_crossentropy', optimizer=SGD(), metrics=["accuracy"])
    return clf


# clf = KerasClassifier(TwoLayerFeedForward(), epochs=100, batch_size=500, verbose=0)
clf = KerasClassifier(twoLayerFeedForward, epochs=100, batch_size=500, verbose=0)

from sklearn.model_selection import StratifiedKFold, cross_val_score

trans = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

import pandas as pd

# Keras classifiers work with one hot encoded categorical columns (e.g. [[1 0 0], [0 1 0], ...]).
# StratifiedKFold works with categorical encoded columns (e.g. [1 2 3 1 ...]).
# This requires juggling the representation at shuffle time versus at runtime.
scores = []
for train_idx, test_idx in trans.split(X_train, y_train.argmax(axis=1)):
    X_cv, y_cv = X_train[train_idx], pd.get_dummies(y_train.argmax(axis=1)[train_idx]).values
    clf.fit(X_cv, y_cv)
    scores.append(clf.score(X_cv, y_cv))

print(scores)
```

@sephib Can you try out your workflow on `master` and let me know if you're still encountering this problem? For now, I'm going to go ahead and close this issue. Please reopen it if you find that it still occurs.

**Comment by sephib** [comment]
Hi,
I can confirm that it works and that I'm not getting any errors
