### ISSUE TITLE
Get artifact endpoint does not seem to exist

### ISSUE THREAD

**Issue by adrian555** [mlflow/mlflow#343]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacOS
- **MLflow installed from (source or binary)**: 
binary
- **MLflow version (run ``mlflow --version``)**:
0.5.0
- **Python version**: 
3.6.5
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
from insomnia, request `GET http://127.0.0.1:5000/api/2.0/preview/mlflow/artifacts/get?run_uuid=7b12489c71b14d5ab7115c3139ff44df` returned 404.

### Describe the problem
It does not seem that `GET artifacts/get` endpoint exists, at least it is not defined in the handler.py. So either it should be added or the rest_api.rst doc should be updated.

**Comment by smurching** [comment]
@adrian555 thanks for the catch - you're right, our REST API docs are currently out of date. The GetArtifact API endpoint was moved in 0.5.0, as described in the [changelog](https://github.com/mlflow/mlflow/blob/master/CHANGELOG.rst#050-2018-08-17):
> REST API endpoint /ajax-api/2.0/preview/mlflow/artifacts/get has been moved to $static_prefix/get-artifact.

Thus assuming you ran your server without the `--static-prefix` argument, visiting `http://127.0.0.1:5000/get-artifact?run_uid=...path=...` should work
