### ISSUE TITLE
[FR] Allow viewing full-size images without rescaling or cropping in Artefacts view

### ISSUE THREAD

**Issue by dniku** [mlflow/mlflow#3432]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Provide an interface for opening full-size images from Artefacts view.

## Motivation

Working with computer vision or generative models, one often needs to inspect logged images. Especially in the case of generative models, it is crucial to see pixel-perfect renditions of the produced images, in full size, unperturbed by rescaling or cropping.

Using Tensorboard, I can click an image saved in the Images tab and see it in the original size. I would like to request a similar feature to be added to MLFlow.

Currently, the Artefacts view in MLFlow uses Plotly to render saved images. While this is a powerful interface for panning or zooming, it seems to have no option to render images in full size, without cropping or rescaling.

A caveat: this change would need to play well with https://github.com/mlflow/mlflow/issues/2696 (comparing images between different runs).

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

A possible solutions is to partly mimic Tensorboard's interface and add a button to toggle between showing the image in the original size and the standard resized and cropped version. Mimicking it fully and implementing this functionality via a click on the image is unlikely to work well, since it would conflict with Plotly.

**Comment by ankit-db** [comment]
Hi @dniku - is there a reason that you would like to avoid downloading the image?

**Comment by dniku** [comment]
Yes — that's simply faster (fewer clicks), and therefore more convenient.

**Comment by dbczumar** [comment]
This has been addressed in MLflow 1.27.0. Thank you for using MLflow!
