### ISSUE TITLE
[Bug]`Models` Tab Broken in 1.11.0

### ISSUE THREAD

**Issue by voganrc** [mlflow/mlflow#3433]
When I click on the `Models` tab in version 1.11.0, I get the following error message:

```
INVALID_PARAMETER_VALUE: Invalid clause(s) in filter string: 'name', 'ilike', ''%%''. Expected search filter with single comparison operator. e.g. name='myModelName'
```

This person seems to be having the same issue:
https://stackoverflow.com/questions/63721148/getting-error-when-i-click-on-models-in-mlflow

**Comment by harupy** [comment]
@voganrc Thanks for reporting this. I was able to reproduce the error using `sqlparse==0.3.0`:

![sqlparse-error](https://user-images.githubusercontent.com/17039389/93547290-aca78f00-f99f-11ea-9321-429e3b8438e5.gif)

**Comment by tinaxi** [comment]
Hi @harupy I am able to verify that pinging `sqlparse` to `0.3.1` solves the issue. Thank you for your quick response!

**Comment by voganrc** [comment]
Confirmed... `sqlparse==0.3.1` fixes this!
