### ISSUE TITLE
MLflow Hyperparm does not capture parameters

### ISSUE THREAD

**Issue by Nithinbs18** [mlflow/mlflow#3442]
Dear team,

Greetings!

I am trying to use MLflow for Hyperparameter tuning as instructed in the example documents (examples/hyperparam) but every time I run the program irrespective of the entry point (I tried all the options available random, gpyopt, and hyperopt) the program does not record any parameters.

![image](https://user-images.githubusercontent.com/44024922/93706669-bdcfd780-fb28-11ea-92d5-feba12528d43.png)

![image](https://user-images.githubusercontent.com/44024922/93706674-cd4f2080-fb28-11ea-8478-8f9136163b77.png)

Can you please help me out what I am doing wrong resolve this. 
Thank you very much.

**Comment by harupy** [comment]
@Nithinbs18 Thasks for reporting this issue. I was able to reproduce the issue and identify the cause.

**Comment by harupy** [comment]
Inserting `mlflow.log_params` like thsi should fix the issue.
```diff
        with mlflow.start_run(nested=True) as child_run:
+                params = {
+                    "training_data": training_data,
+                    "epochs": str(nepochs),
+                    "learning_rate": str(lr),
+                    "momentum": str(momentum),
+                    "seed": str(seed),
+                }
+                mlflow.log_params(params)
                p = mlflow.projects.run(
                    run_id=child_run.info.run_id,
                    uri=".",
                    entry_point="train",
                    parameters=params,
                    experiment_id=experiment_id,
                    synchronous=False,
                )
```

**Comment by Nithinbs18** [comment]
Hi @harupy 
Thanks for your time and response. It works as expected now.

Regards,
Nithin
