### ISSUE TITLE
Missing version update to 1.11.1.dev0 on master [SETUP-BUG]

### ISSUE THREAD

**Issue by zanitete** [mlflow/mlflow#3493]
Rebasing my PR on master, I noticed the version on master is still 1.10.1.dev0, should't it be 1.11.1.dev0?
I see that normally there's a PR from 'mlflow-automation' that bumps it (i.e. https://github.com/mlflow/mlflow/pull/3174) but I don't see it for the 1.11 release.

**Comment by dmatrix** [comment]
cc: @harupy is this a bug?

**Comment by harupy** [comment]
@dmatrix 
I think we just forgot to update the version.

**Comment by dmatrix** [comment]
@harupy do you want me to update this since I have a branch for code snippets?

VERSION = "1.10.1.dev0" -> 1.11.1.dev0?
