### ISSUE TITLE
only metrics and params showing in UI, not tags, model nor other artifacts 

### ISSUE THREAD

**Issue by AVSuni** [mlflow/mlflow#3505]
I am running MLFlow 1.11.0. 

mlflow.log commands work perfectly fine and folders for artifacts and tags are saved in the same folder as the folders for metrics and params. However, only metrics and params are displayed in the UI. Any ideas what might cause this? 

UI shows `" Artifact Location   file:///home/jovyan/host_drive/mlruns/5"`

Running 
`mlflow.get_artifact_uri()`

gives 

`'file:///home/jovyan/host_drive/mlruns/5/c6070a5d0bc449b7bd1c2a071bd68cea/artifacts'`

 
the uuid matches the URL where only metrics and parameters are displayed:

`http://localhost:5000/#/experiments/5/runs/c6070a5d0bc449b7bd1c2a071bd68cea`

**Comment by harupy** [comment]
@AVSuni Could you share your code?

**Comment by AVSuni** [comment]
Thanks @harupy . I am basically using the logistic regression example from mlflow/examples

![image](https://user-images.githubusercontent.com/29711150/95570488-a7ce7c00-0a2f-11eb-80e0-0c8442d2742c.png)

**Comment by harupy** [comment]
@AVSuni Can you paste the code as a comment?

**Comment by AVSuni** [comment]
`import numpy as np
import mlflow
import mlflow.sklearn
from sklearn.linear_model import LogisticRegression

penalty = 'l2'
X = np.array([-4,2 -1, 0, 1, 2, 1]).reshape(-1, 1)
np.savetxt("foo.csv", X, delimiter=",")
y = np.array([0, 0, 1, 1, 1, 0])
lr = LogisticRegression(penalty = penalty)
lr.fit(X, y)
score = lr.score(X, y)
print("Score: %s" % score)
mlflow.log_metric("score", score)
mlflow.log_param("penalty", penalty)
mlflow.sklearn.log_model(lr, "model")
mlflow.log_artifact("./foo.csv", "data")
print("Model saved in run %s" % mlflow.active_run().info.experiment_id)`

**Comment by harupy** [comment]
I wasn't anble to reproduce the issue in my environment.

<img width="551" alt="Screen Shot 2020-10-09 at 19 16 40" src="https://user-images.githubusercontent.com/17039389/95571828-06155200-0a64-11eb-8dad-2dedd1d2473a.png">

**Comment by harupy** [comment]
Does the same thing occur when you run the code as a script, not in the notebook?

**Comment by AVSuni** [comment]
Thanks. That's good to know. Yes, the same thing happens when running as script

**Comment by harupy** [comment]
Can you remove the `mlruns` folder and try running the code again?

**Comment by AVSuni** [comment]
Had no effect I'm afraid

**Comment by harupy** [comment]
How did you lauch the MLflow UI?

**Comment by AVSuni** [comment]
I have used the following:

`mlflow server --backend-store-uri file:///host_drive/mlruns --default-artifact-root file:///host_drive/mlruns --host 0.0.0.0`

**Comment by harupy** [comment]
Can you try `mlflow ui` (without any option)?

**Comment by AVSuni** [comment]
`mlflow ui` without options does not give me any of my runs, so even worse than the starting point :)

**Comment by AVSuni** [comment]
One odd detail is that I get `status: UNFINISHED` in all of my runs in the UI

![image](https://user-images.githubusercontent.com/29711150/95578442-917aed00-0a3c-11eb-89b3-f7b03e1813b1.png)

**Comment by harupy** [comment]
Did you run the code in https://github.com/mlflow/mlflow/issues/3505#issuecomment-706095780 without `create_experiment` or `set_experiment`?

**Comment by AVSuni** [comment]
Including/excluding `create_experiment` or `set_experiment` does not make any difference.

**Comment by harupy** [comment]
It's strange. The code should create an `mlruns` directory in the current directory and `mlflow ui` should load the runs stored in it.

**Comment by AVSuni** [comment]
Found the cuplrit! I had the training model running in one container and MLflow server in another container. Clearly metrics and params don't mind that the file path looks different inside the two containers, but artifacts won't show correctly unless the paths are identical inside the containers even when though everything is saved in the same location on the host. As you can see, the two paths inside the containers [ #3505 (comment)](https://github.com/mlflow/mlflow/issues/3505#issue-718009202) and #3505 [(comment)](https://github.com/mlflow/mlflow/issues/3505#issuecomment-706111579) were not identical, changing the latter path inside the MLserver container to match former path fixed the problem. Thanks so much for your persistence and sorry I didn't give all the details in the beginning!
