### ISSUE TITLE
descenders in scatterplot x-axis label are truncated

### ISSUE THREAD

**Issue by stbof** [mlflow/mlflow#353]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
![scatter](https://user-images.githubusercontent.com/20482960/44497884-9c8e1b80-a630-11e8-9efe-6137792b22d6.png)

**Comment by ToonKBC** [comment]
PR #363 fixes this
