### ISSUE TITLE
Enhancement: Handle fields in RequestBody of REST APIs

### ISSUE THREAD

**Issue by adrian555** [mlflow/mlflow#354]
Several REST APIs including `POST runs/create` take a RequestBody in JSON format. If some fields in the request are not specified with a value, the current code just take the json default. For example, the `timestamp` is default to 0, which is wrong.

Enhancement is needed to look at every field in a request body and set the proper default value. And if a field is required but no value is specified, then an exception should be raised with status code 400.

Refer #349

**Comment by pogil** [comment]
@adrian555 thanks for contributing #349! Are there still remaining gaps?

**Comment by adrian555** [comment]
@pogil this was opened for discussions. Since there are none response probably it is not critical enough to keep opened.
