### ISSUE TITLE
setup the authenticaion to tracking server via Python

### ISSUE THREAD

**Issue by bozzlab** [mlflow/mlflow#3545]
Hi everyone, 

I would like to setup the authenticaion to tracking server via Python. Which is I had read the this docs https://www.mlflow.org/docs/latest/tracking.html#logging-to-a-tracking-server

As I know that we have to assign the environment variables such as 
```
MLFLOW_TRACKING_TOKEN
MLFLOW_TRACKING_USERNAME
MLFLOW_TRACKING_PASSWORD
```
to the both server and client right ? 

But when I try it doesn't work.

I still can use the tracking server without any env var authentication. 

So I'm quite confure about how to setup this authentication 

Do anyone has recommend to me? which step or section that I was missing.

**Comment by dmatrix** [comment]
@bozzlab How are you setting up your tracking server? Is it behind an NGINX or Apache httpd server as a proxy? This is done on the [client-side](https://github.com/mlflow/mlflow/blob/3f53b46177789924f00bae29a182f459ec123e16/mlflow/tracking/_tracking_service/utils.py#L120)

**Comment by bozzlab** [comment]
> @bozzlab How are you setting up your tracking server? Is it behind an NGINX or Apache httpd server as a proxy? This is done on the [client-side](https://github.com/mlflow/mlflow/blob/3f53b46177789924f00bae29a182f459ec123e16/mlflow/tracking/_tracking_service/utils.py#L120)

Thanks for reply, 
No, I don't have any proxy like that for my project. 
Because I used the Serverless (Cloud Run/Fergate) for deploying. 
These services already had the Load balancer and proxy layer.

So the MLflow required the Nginx or Apache for authentication right? 
If I don't want to work with Nginx or Apache, It's anyway to used this feature?

**Comment by themowski** [comment]
> So the MLflow required the Nginx or Apache for authentication right?
> If I don't want to work with Nginx or Apache, It's anyway to used this feature?

As you may have discovered by now, you are correct -- MLflow does not support authentication out of the box. If you set either the `MLFLOW_TRACKING_TOKEN` or both the `MLFLOW_TRACKING_USERNAME` and `MLFLOW_TRACKING_PASSWORD` environment variables, then an "Authorization" header will be set on the HTTP requests that MLflow makes. You will need to run a proxy that supports authentication via values passed through request headers.

* In the case of basic authorization, setting `MLFLOW_TRACKING_USERNAME` and `MLFLOW_TRACKING_PASSWORD` will set the header `Authorization: Basic {user}:{password}`.
* In the case of Bearer token authorization, setting `MLFLOW_TRACKING_TOKEN` will set the header `Authorization: Bearer {token}`.
* If all 3 variables are set, then basic authentication will take precedence.

A slightly lower-level view, based on some quick navigation through the codebase (GitHub search picked commit 11898c5, published a few days ago, so I believe this is still relevant): these environment variables are injected into an [`mlflow.utils.rest_utils.MlflowHostCreds`](https://github.com/mlflow/mlflow/blob/11898c564207ce7bfc7ba89636f93584e885ac90/mlflow/utils/rest_utils.py#L235) object by the `mlflow.tracking._tracking_service.utils._get_default_host_creds` function:

https://github.com/mlflow/mlflow/blob/11898c564207ce7bfc7ba89636f93584e885ac90/mlflow/tracking/_tracking_service/utils.py#L120-L129

The `MlflowHostCreds` object is used by the [`mlflow.utils.rest_utils.http_request`](https://github.com/mlflow/mlflow/blob/11898c564207ce7bfc7ba89636f93584e885ac90/mlflow/utils/rest_utils.py#L25) function. This extracts the credentials:

https://github.com/mlflow/mlflow/blob/11898c564207ce7bfc7ba89636f93584e885ac90/mlflow/utils/rest_utils.py#L41-L45

And then sets the header:

https://github.com/mlflow/mlflow/blob/11898c564207ce7bfc7ba89636f93584e885ac90/mlflow/utils/rest_utils.py#L50-L51

As far as I can tell, that is the extent of MLflow Tracking Service's built-in authentication support. As noted above, you would need to capture incoming requests to the server (via a separate service/proxy), check the "Authentication" header, and then determine whether to allow the request to be passed to the MLflow server or not.

**Comment by ajperry2** [comment]
Maybe this should be it's own issue but it seems like the Authentication header is first correctly written as you describe, but then it is not sent to the request.Session which instead of using it generates authentication based on netrc (not sure what that is but seems like a file). 

This bug could be resolved by adding a line here:
https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L89
Such as:
`else: kwargs["auth"] = (host_creds.username, host_creds.password)`

Would this be a good addition? Or is this still working for other people?

**Comment by dbczumar** [comment]
Hi folks, MLflow now has built-in support for authentication and authorization. Please try it out at https://mlflow.org/docs/latest/auth/index.html and let us know if you have feedback. Thank you for using MLflow!
