### ISSUE TITLE
Run server by python code, not mlflow command

### ISSUE THREAD

**Issue by bozzlab** [mlflow/mlflow#3551]
Hi everyone, 
I would like to run the the mlflow server via python code like this. 
```
#python file
import mlflow 

#some code config or oparetion

if __main__=="__name__":
   mlflow.server(....)

```

To instead the command ```mlflow server```

Do the MLFlow have it ?

**Comment by harupy** [comment]
@bozzlab 

Hope this is what you're looking for.

```python
import mlflow.cli


mlflow.cli.server()

```

**Comment by bozzlab** [comment]
> @bozzlab
> 
> Hope this is what you're looking for :)
> 
> ```python
> import mlflow.cli
> 
> 
> mlflow.cli.server()
> ```

Thanks !!!

**Comment by harupy** [comment]
@bozzlab My pleasure! Can I close this issue?

**Comment by bozzlab** [comment]
> @bozzlab My pleasure! Can I close this issue?

Hi, I got the trouble when I passed the value to the server()
```
import mlflow
from mlflow import cli 

cli.server(port=8080) 
```
Why it error ?
```
TypeError: __init__() got an unexpected keyword argument 'port'
```

**Comment by harupy** [comment]
I think this is beause `server` is annotated by `click`. A workaround that I found is:

```
mlflow.cli.server(["--port", "8000"])
```

**Comment by bozzlab** [comment]
> I think this is beause `server` is annotated by `click`. A workaround that I found is:
> 
> ```
> mlflow.cli.server(["--port", "8000"])
> ```

Oh Thanks, 
How about **default_artifact_root or artifact** can used with that command?

**Comment by harupy** [comment]
I haven't tried but they should work too.

**Comment by bozzlab** [comment]
> I haven't tried but they should work too.

Thanks for reply, But It's doesn't work TT
```
Usage: main.py [OPTIONS]
Try 'main.py --help' for help.

Error: no such option: --backend_store_uri
```

**Comment by harupy** [comment]
You need to use `-` instead of `_`.

```
cli.server(["--backend-store-uri", "./mlruns"])
```

**Comment by alfozan** [comment]
Another example:
the equivalent of the CLI cmd: 
```bash
mlflow models serve --model-uri URI --host 0.0.0.0 --port 5000 --workers 1 --no-conda
```
is
```python
import mlflow.models.cli
mlflow.models.cli.serve(["--model-uri", "URI", "--no-conda", "--host", "0.0.0.0", "--port", 5000, "--workers", 1])
```
