### ISSUE TITLE
[FR] make flavor a viable filter on search_model_versions and search_registered_models

### ISSUE THREAD

**Issue by wamartin-aml** [mlflow/mlflow#3580]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature request)

## Motivation
- What is the use case for this feature? It's useful for downstream applications that only support certain model flavors to be able to filter down to only those in their requests.
- Why is this use case valuable to support for MLflow users in general? This adds convenience for users of all kinds who work with more than one flavor of model.
- Why is this use case valuable to support for your project(s) or organization? We have customers who have specifically requested to be able to do this because they only work with a certain type of models.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient) Right now, there's no way to do this besides doing something hacky with `name` or filtering on the client side.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dmatrix** [comment]
@wamartin-aml Can you provide some extra information the feature enhancement is? During filing an FR, you are prompted with some questions to answer, whose answers are missing above. Can you please answer those questions so that we can assess the problem and guide you on how to proceed?

Thanks!

**Comment by wamartin-aml** [comment]
Which questions are those? The only ones I see are in the `Motivation` section, which I've filled out.

For a proposal summary: Right now, `search_model_versions` and `search_registered_models` can filter on `name` and `run_id` but nothing else. I also propose allowing users to filter on model flavor (i.e. pyfunc, sklearn).

**Comment by dmatrix** [comment]
@wamartin-aml Sorry, I missed that, for your answers were on the same line as the questions, so I missed them while reading. I'm used to looking at them on a separate line ... :-)

I see that you want additional attributes in the search filter such as model flavors. 

cc: @sueann @mparkhe

**Comment by wamartin-aml** [comment]
no longer relevant
