### ISSUE TITLE
[BUG] `MetricsPlotView` crashes when metric value is large and converted to string by `JsonBigInt`

### ISSUE THREAD

**Issue by elgehelge** [mlflow/mlflow#3586]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We're seeking help with the implementation of roadmap items tagged with the `help wanted` label.

For requirements clarifications and implementation questions, or to request a PR review, please tag @jinzhang21 in your communications related to this issue.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ArchLinux
- **MLflow installed from (source or binary)**:
Unknown
- **MLflow version (run ``mlflow --version``)**:
1.8.0
- **Python version**:
3.7.9
- **npm version, if running the dev UI**:
-
- **Exact command to reproduce**:
Click on a metrics link from a run overview page.

### Describe the problem
Trying to plot some metrics using the web interface results in a Something went wrong error page.

### Code to reproduce issue
Not needed

### Other info / logs
This error is logged in the javascript console:
`Uncaught TypeError: "e.value.toFixed is not a function"`

When I put a breakpoint in the javascript UI `render` function and do an inspection I get the following:
```
>>> this.props.metrics[0].history[0]["value"]
465.9117431640625
>>> this.props.metrics[0].history[3]["value"]
"8.194174265635981e+20"
```
Note the type is a string in the second output. I believe this to be the problem because `"some string".toFixed(5)` gives the same error (`Uncaught TypeError: "some string".toFixed is not a function`)

If a look at the MLFlow API request response from `http://192.168.130.110:5001/ajax-api/2.0/preview/mlflow/metrics/get-history?run_uuid=e409f89d35714f4bb3f2897db5ffe0c1&metric_key=val_loss` it looks like the following:
```
{
  "metrics": [
    {
      "key": "val_loss",
      "value": 465.9117431640625,
      "timestamp": "1603356692187",
      "step": "0"
    },
    {
      "key": "val_loss",
      "value": 1503.7987060546875,
      "timestamp": "1603359627609",
      "step": "1"
    },
    {
      "key": "val_loss",
      "value": 8566823372980224.0,
      "timestamp": "1603362580753",
      "step": "2"
    },
    {
      "key": "val_loss",
      "value": 8.194174265635981e+20,
      "timestamp": "1603365524015",
      "step": "3"
    },
    ...
```

So the error seems to be caused by the client side is not able to parse the API responses proberly.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@elgehelge Thanks for reporting this. I was able to reproduce the issue.

```python
import mlflow

with mlflow.start_run():
    mlflow.log_metric("a", 1)
    mlflow.log_metric("a", 1e20)
```

**Comment by harupy** [comment]
`1e20` is larger than `Number.MAX_SAFE_INTEGER` and is converted to a string.

**Comment by ianshan0915** [comment]
@dbczumar, I'm able to fix the issue with the following code change in [mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js.](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js#L79) Would you please confirm if my solution is good? If so, I'll create a PR for this. Thanks!

````
     const historyValues = history.map((entry) => entry.value);
````
to
````
     const historyValues = history.map((entry) => typeof entry.value === 'number'
        ? entry.value
        : Number(entry.value));
````

**Comment by dbczumar** [comment]
@ianshan0915 This makes sense to me! Thank you in advance for your contribution!

cc @harupy for input as well

**Comment by dbczumar** [comment]
Closing now that https://github.com/mlflow/mlflow/pull/4947 is merged. Thanks @ianshan0915 !
