### ISSUE TITLE
[BUG] Experiment Tags not included in Exported CSV

### ISSUE THREAD

**Issue by NielsOerbaek** [mlflow/mlflow#3641]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We're seeking help with the implementation of roadmap items tagged with the `help wanted` label.

For requirements clarifications and implementation questions, or to request a PR review, please tag @dbczumar in your communications related to this issue.

### Describe the problem

Custom tags are not included in the exported CSV file. Only metrics, params and the fixed ['Run ID', 'Name', 'Source Type', 'Source Name', 'User', 'Status']

### Code to reproduce issue
run
```
import mlflow
with mlflow.start_run():
    mlflow.set_tag("foo", "bar")
    mlflow.log_param("bug", True)
    mlflow.log_metric("error", 1)
```
Then launch the ui (`mlflow ui`) and press the "Download CSV"-button. The downloaded CSV does not include the "foo" tag or the "bar" value.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ianshan0915** [comment]
@dbczumar, is this bug already fixed? the csv I downloaded contains the tags. 

Run ID | Name | Source Type | Source Name | User | Status | bug | error | foo
-- | -- | -- | -- | -- | -- | -- | -- | --
|f50c642ea75041cbb2cf646886898702 |  |  LOCAL  |  | ianshen | FINISHED | TRUE | 1 | bar

**Comment by harupy** [comment]
@dbczumar I remember that I've addressed this issue. Now the downloaded CSV files should contain **run** tags.

**Comment by dbczumar** [comment]
I see. The ticket title refers to *experiment* tags, while the body refers to *run* tags. I'll go ahead and close this & will file a new ticket to track another class of improvement for Download CSV.

**Comment by dbczumar** [comment]
Hi @ianshan0915 , I've filed https://github.com/mlflow/mlflow/issues/4850 as a replacement for this ticket that is still related to the "Download CSV" functionality. Please let me know if you're interested in working on it.
