### ISSUE TITLE
[FR] Let tracking server just store files in locale filesystem.

### ISSUE THREAD

**Issue by PhilipMay** [mlflow/mlflow#3689]
AFAIK MLflow must store artifacts in an Artifact Store:
- Amazon S3 and S3-compatible storage
- Azure Blob Storage
- Google Cloud Storage
- FTP server
- SFTP Server
- NFS
- HDFS

It would be nice if the Artifact can just be transfered by HTTP and REST to the tracking server and there stored in locale file system. That seems to be unpossible at the moment.

**Comment by harupy** [comment]
@PhilipMay We have `LocalArtifactRepository` which allows us to store files in a local directory.

https://github.com/mlflow/mlflow/blob/c967e22676156ad33ba544537a655b056b4c237c/mlflow/store/artifact/local_artifact_repo.py#L15

**Comment by PhilipMay** [comment]
Hey dear project maintainers @harupy and @smurching :
What about this suggestion / improvement.
For me my colleagues and others this might be an important improvement of MLflow.
What do you think about that? Are you planning to consider this or do you just wait for an contribution?

**Comment by PhilipMay** [comment]
Hi @dmatrix - maybe you could provide some feedback about this FR?

**Comment by dbczumar** [comment]
Support for this has been included in recent versions of MLflow, e.g. MLflow 1.27.0. The documentation is available here: https://mlflow.org/docs/latest/tracking.html#using-the-tracking-server-for-proxied-artifact-access. Thank you for using MLflow!

**Comment by PhilipMay** [comment]
Thanks for letting me know @dbczumar ! I will test this.
