### ISSUE TITLE
[BUG] mlflow prevents user's ability to disable warnings

### ISSUE THREAD

**Issue by stas00** [mlflow/mlflow#3704]
As discussed here https://github.com/PyTorchLightning/pytorch-lightning/issues/4699#issuecomment-728391953
mlflow takes away user's control over PYTHONWARNINGS

Currently, we get:

```
PYTHONWARNINGS=ignore python -c "import mlflow, wandb"
/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/wandb/util.py:36: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import namedtuple, Mapping, Sequence
/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/wandb/vendor/graphql-core-1.1/graphql/type/directives.py:55: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Pyth
```

As you can see there is no way to turn the warnings off. Once I comment out:
https://github.com/mlflow/mlflow/blob/2f5b870d81b92d0e3558c3b36a820f8eaf3cda59/mlflow/__init__.py#L45
the problem goes away

The original problem came from being unable to turn warnings for `transformers`, which I traced down to `pytorch-lightening` (which had its own inconsiderate override), which when removed didn't help and finally traced it down to `mlflow`.

While fine on their own, all these various components are then integrated into huge projects like `pytorch-lightening` and even bigger `transformers` and every inconsiderate override then impacts a huge number of users at large. And it's not easy to track these down. 

Thank you.

**Comment by harupy** [comment]
Addressed by #3621
