### ISSUE TITLE
[Help] Putting model dependent mlflow code into the model class

### ISSUE THREAD

**Issue by pietz** [mlflow/mlflow#3734]
_I'm starting a discussion here because the databricks mlflow forum doesn't seem to be very active._

I'm working with a large hierarchy of different models and parameters, which all extend a `BaseModel` class that I defined. I want to put as much mlflow related code into the specific model classes, so I don't have to deal with it from the outside. It seems to me this is an approach that mlflow doesn't really motivate. All examples I've looked at do all their `mlflow.log...` calls from the outside.

Why is that?

The OCD programmer voice in my head wants to put logging calls related to a model into the model definition. No matter how helpful mlflow is, I want to deal with it as little as possible. Looking at the examples mlflow encourages this code style:

```
exp_id = mlflow.create_experiment('Test')
p = Prophet()
mlflow.start_run(experiment_id=exp_id)
mlflow.log_param('ProphetModel')
mlflow.log_param('log_scale', log_scale)
p.fit(df1)
mae = calc_mae(gt, p.predict(df2)
mlflow.log_metric('MAE', mae)
mlflow.pyfunc.log_model('Prophet' python_model=ProphetWrapper(p))
mlflow.end_run()
# do this for all other models
```

From the outside it seems much nicer to do:

```
exp_id = mlflow.create_experiment('Test')
ProphetModel(exp_id, log_scale).fit_evaluate(df, tr_cutoff)
# do this for all other models
```

I mean, my version doesn't get rid of the code but it places the model dependent code where the model is.

What would be downsides of my approach and do you know any reference projects that support this style of code structure?

Thank you

**Comment by dmatrix** [comment]
@pietz Can you post this on the [mlflow slack channel](https://join.slack.com/t/mlflow-users/shared_invite/zt-g6qwro5u-odM7pRnZxNX_w56mcsHp8g), please?

**Comment by dmatrix** [comment]
> I'm working with a large hierarchy of different models and parameters, which all extend a BaseModel class that I defined. I want to put as much mlflow related code into the specific model classes, so I don't have to deal with it from the outside. It seems to me this is an approach that mlflow doesn't really motivate. All examples I've looked at do all their mlflow.log... calls from the outside.
> 
> Why is that?

This is more to do with the evolution of APIs for tracking. I reckon as we are moving toward universal `mflow.autolog()` this may not be that much of an issue, as all MLflow entities are automatically logged for you. You can use the API for any additional entities that you will to log. 

It's not unreasonable to extend the model flavor and wrap your specific log entities, in addition to autologging. And this works well
if you writing your own Custom Python Models.

**Comment by pietz** [comment]
thank you @dmatrix That's definitely a better place. Feel free to close the issue.
