### ISSUE TITLE
[SETUP-BUG] - unit test failures after following developer setup in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by jkthompson** [mlflow/mlflow#3739]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this installation issue template to ensure a timely and thorough response.**

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux version 5.4
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.12.1.dev0
- **Python version**:  Python 3.6.12
- **Exact command to reproduce**:
conda create --name mlflow-dev-env python=3.6
source activate mlflow-dev-env
pip install -r dev-requirements.txt
pip install -r test-requirements.txt
pip install -e .
./dev/run-small-python-tests.sh

### Describe the problem
I observe the following test failures:

ERROR collecting tests/store/artifact/test_gcs_artifact_repo.py
Traceback:
tests/store/artifact/test_gcs_artifact_repo.py:7: in <module>
    from google.cloud.storage import client as gcs_client
E   ModuleNotFoundError: No module named 'google.cloud'

ERROR collecting tests/store/artifact/test_sftp_artifact_repo.py 
Traceback:
tests/store/artifact/test_sftp_artifact_repo.py:4: in <module>
    import pysftp
E   ModuleNotFoundError: No module named 'pysftp'

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Running the following command resolves the error by installing the missing dependencies.  
pip install -e .[extras]

**Comment by harupy** [comment]
fixed by #3740
