### ISSUE TITLE
[FR] Publishing Docker Container to Registry

### ISSUE THREAD

**Issue by twsl** [mlflow/mlflow#3783]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

I propose the implementation of publishing the mlflow docker container to a registry.

## Motivation
- What is the use case for this feature?

Starting mlflow without having to worry about the os and setup.

- Why is this use case valuable to support for MLflow users in general?

Setting up mlflow with the docker container is the easiest way to get it running.

- Why is this use case valuable to support for your project(s) or organization?

I run all the software on my server as docker containers. Unofficial builds exist, but none is up-to-date. Instead of building the container myself I want to contribute directly to the project, so other can profit as well.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Building containers from another repo on push without the event is difficult and requires constant polling.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

There is already an old issue #826 from 2019 , where the problem was labled as important-longterm.
But it doesnt follow the template and an issue over a year old without any implementation, which makes me think, that it has been forgotten.
So I thought of creating a new one, to bring it back on the agenda.
The dockerfile already exist, the only step missing is the actual publishing.
Possible solution can be found here #3709

**Comment by bioshazard** [comment]
I am also interested in MLFlow managing an official image in GHCR on the primary repo. I want to use MLFlow in my enterprise setting but am discouraged by the limited support for a canonical image. If the action were set up correctly, it could fully automate all future releases leveraging whatever build script is used to create the `pip` package.

**Comment by desaintmartin** [comment]
In order to have an official chart, a requirement would be to have an official container image: https://github.com/mlflow/mlflow/issues/826

**Comment by lungdart** [comment]
> rder to have an official chart, a requirement would be to have an official container ima

This issue is for creating the container, not for a helm chart.

We we're considering using this tool at our company, but the lack of movement on the issues regarding containers and helm charts is a big red flag for us!

**Comment by umialpha** [comment]
any update?  an official image on dockerhub is really needed today.

**Comment by dbczumar** [comment]
Hi folks, we have published official Docker images to https://github.com/mlflow/mlflow/pkgs/container/mlflow. They are updated with each release. Thank you for using MLflow!
