### ISSUE TITLE
Pyfun Serve : Bind Adress 

### ISSUE THREAD

**Issue by hamroune** [mlflow/mlflow#379]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux
- **MLflow installed from (source or binary)**: 
Yes
- **MLflow version (run ``mlflow --version``)**:
0.5.1
- **Python version**: 
3.6
- **npm version (if running the dev UI):

- **Exact command to reproduce**:
mlflow pyfun server -m path/to/model

### Describe the problem
the server starts with host 127.0.0.1, we should just like Server choose other binding adress like "-h 0.0.0.0" option, I tried to hack gunicorn but unfortunely I cannot change the host, so I cannot access the server from outside.

### Source code / logs
mlflow pyfun server -m path/to/model -h 0.0.0.0 -p 5001

**Comment by mparkhe** [comment]
hi @hamroune : Please look at #21 for conversation on security concerns about `0.0.0.0`

**Comment by hamroune** [comment]
I make PR https://github.com/mlflow/mlflow/pull/401

**Comment by aarondav** [comment]
#401 is merged!
