### ISSUE TITLE
Serving artifacts from Google Cloud Storage: AttributeError: '_BlobIterator' object has no attribute 'pages'

### ISSUE THREAD

**Issue by edilsonacjr** [mlflow/mlflow#385]
### System information
- **Python version**: 3.5 
- **MLflow version**: 0.5.0
- **Exact command to reproduce**: mlflow server --default-artifact-root gs://<BUCKET_TEST>/

### Describe the problem
Serving artifacts from Google Cloud Storage does not work. The 'BlobIterator' has no attribute called 'pages'.

### Source code / logs
Code that originated the error (store/gcs_artifact_repo.py):
```
        for page in results.pages:
            dir_paths.update(page.prefixes)
```

That problem was solved by replacing this peace of code for:
```
        while results.has_next_page():
            response = results.get_next_page_response()
            blobs = list(results.get_items_from_response(response))
            dir_paths.update(results.prefixes)
```

**Comment by smurching** [comment]
cc @jakeret have you seen this issue as well? @edilsonacjr to confirm, which version of `google-cloud-storage` is installed on the machine on which you're running `mlflow server`?

**Comment by mparkhe** [comment]
Hi @edilsonacjr : Based on GCP documentation [`Bucket.list_blobs`](https://googlecloudplatform.github.io/google-cloud-python/latest/storage/buckets.html#google.cloud.storage.bucket.Bucket.list_blobs) returns an [`Iterator`](https://googlecloudplatform.github.io/google-cloud-python/latest/core/page_iterator.html#google.api_core.page_iterator.Iterator) of types Blobs that has a [`pages()`](https://googlecloudplatform.github.io/google-cloud-python/latest/core/page_iterator.html#google.api_core.page_iterator.Iterator.pages) method.

We are using this version of GCP apis for python

```
google-api-core                    1.3.0
google-cloud-core                  0.28.1
google-cloud-storage               1.10.0
```

What version of `google-cloud-store` has the `BlobIterator` implementation?

**Comment by edilsonacjr** [comment]
Hi @mparkhe, I'm using the same versions as you. Maybe you should put Google packages in the requirements because those APIs change really fast and that could break `mlflow`.

Google packages:
```
google-api-core          1.3.0    
google-auth              1.5.1    
google-cloud             0.19.0   
google-cloud-core        0.28.1   
google-cloud-datastore   1.7.0    
google-cloud-storage     1.10.0   
google-gax               0.13.0   
google-resumable-media   0.3.1 
```

**Comment by jakeret** [comment]
Sorry for not responding earlier. 
Would it be an option to have these optional dependencies defined as [`extras_require`](http://peak.telecommunity.com/DevCenter/setuptools#declaring-extras-optional-features-with-their-own-dependencies) in the `setup.py`? Then the mlflow installation could look something like this:

```
pip install mlflow[gcp,aws,xxx]
```

This would allow us to fix the dependencies while not forcing everybody to install the heavy libs

**Comment by edilsonacjr** [comment]
@jakeret, I think that for now this solution is good.
