### ISSUE TITLE
[FR] Make URLs clickable in the MLflow Tracking UI

### ISSUE THREAD

**Issue by jhagege** [mlflow/mlflow#3908]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Feature scope

This roadmap feature’s complexity is classified as:

- [X] `good-first-issue`: This feature is limited in complexity and effort required to implement.

## Proposal Summary

Make HTML Hyperlinks clickable in MLFlow Tracking UI ? 
Such as the following: 

JobUrl | <a href="https://someurl.com/job/develop/185/">185<a>
-- | --

![image](https://user-images.githubusercontent.com/39497902/183740549-1fd9d8e6-81aa-4308-8298-4c8842809cd7.png)

**Comment by jhagege** [comment]
![image](https://user-images.githubusercontent.com/7504908/103105723-3074b580-4638-11eb-9e04-3c9bd34e5514.png)

**Comment by abhinandanpatni** [comment]
I would like this feature as well. It's possible to store strings representing URLs, but these don't seem to be clickable yet. Is there a plan to work on this in the future?

**Comment by addisonklinke** [comment]
I'd find this super useful for linking to a specific git commit or Docker image within a remote repository. It'd be even better if MLflow recognized commit and image hashes and auto-shortened/formatted them like Github does with issue/pull request numbers

**Comment by marijncv** [comment]
Hey @dbczumar, I created #6526 to address this FR. Curious to hear what you think!

**Comment by jhagege** [comment]
> Hey @dbczumar, I created #6526 to address this FR. Curious to hear what you think!

Thanks much!!

**Comment by PaulZhangIsing** [comment]
@jhagege seems in 1.29.0 the tags are able to show the hyperlink.
However, in the lastest version 2.1.1, this feature has been removed.
we could only add it through the description there

**Comment by KansaiTraining** [comment]
What happened with this feature?

**Comment by arnaudh** [comment]
Looks like this was removed as part of https://github.com/mlflow/mlflow/pull/7507

From a cursory glance at the new code structure, it should be possible to add it back. I may have a go at it myself.

**Comment by evan-sadler** [comment]
Can we add it back? It's pretty useful to link to external dashboards like a orchestrator page or a ray dashboard.
