### ISSUE TITLE
[DOC-FIX] change curl example for windows

### ISSUE THREAD

**Issue by pauldj54** [mlflow/mlflow#3936]
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://www.mlflow.org/docs/latest/tutorials-and-examples/tutorial.html

### Description of proposal (what needs changing):
The CURL command for Windows to POST the pandas dataframe failed with the combination of single quotes and escaped double quotes. I fixed it and it worked like this:

`curl -X POST -H "Content-Type:application/json; format=pandas-split" --data "{\"columns\":[\"alcohol\", \"chlorides\", \"citric acid\", \"density\", \"fixed acidity\", \"free sulfur dioxide\", \"pH\", \"residual sugar\", \"sulphates\", \"total sulfur dioxide\", \"volatile acidity\"],\"data\":[[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}" http://127.0.0.1:1234/invocations
`
It seems to be solved in the latest documentation version on github, but this version is not available on the mlflow docs tutorial for version 1.13.1.

**Comment by harupy** [comment]
@pauldj54 Thanks for reporthing this.

> It seems to be solved in the latest documentation version on github, but this version is not available on the mlflow docs tutorial for version 1.13.1.

Could you clarify this a bit?

**Comment by pauldj54** [comment]
Hi @harupy , 
yes sure. If you compare the article published on: https://www.mlflow.org/docs/latest/tutorials-and-examples/tutorial.html
with the master version in the git repo:  https://github.com/mlflow/mlflow/blob/master/docs/source/tutorials-and-examples/tutorial.rst
They differed. In particular in the section "Serving the model" in the command to call the REST endpoint

**From www.mlflow.org/docs:**
```
# On Windows
curl -X POST -H "Content-Type:application/json; format=pandas-split" --data '{\"columns\":[\"alcohol\", \"chlorides\", \"citric acid\", \"density\", \"fixed acidity\", \"free sulfur dioxide\", \"pH\", \"residual sugar\", \"sulphates\", \"total sulfur dioxide\", \"volatile acidity\"],\"data\":[[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}' http://127.0.0.1:1234/invocations
```
**From github.com/mlflow/mlflow/blob/master/docs;**
`curl -X POST "http://127.0.0.1:8090/predict/" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"fixed acidity\": 6.2, \"volatile acidity\": 0.66, \"citric acid\": 0.48, \"residual sugar\": 1.2, \"chlorides\": 0.029, \"free sulfur dioxide\": 29, \"total sulfur dioxide\": 75, \"density\": 0.98, \"pH\": 3.33, \"sulphates\": 0.39, \"alcohol\": 12.8}"`

The first did not work, which is the one most people used.

The second should work, but I have not tested it yet. I just sucessfully tested the first version modified like this:
```
# On Windows
curl -X POST -H "Content-Type:application/json; format=pandas-split" --data '{\"columns\":[\"alcohol\", \"chlorides\", \"citric acid\", \"density\", \"fixed acidity\", \"free sulfur dioxide\", \"pH\", \"residual sugar\", \"sulphates\", \"total sulfur dioxide\", \"volatile acidity\"],\"data\":[[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}' http://127.0.0.1:1234/invocations
``````
# On Windows
curl -X POST -H "Content-Type:application/json; format=pandas-split" --data "{\"columns\":[\"alcohol\", \"chlorides\", \"citric acid\", \"density\", \"fixed acidity\", \"free sulfur dioxide\", \"pH\", \"residual sugar\", \"sulphates\", \"total sulfur dioxide\", \"volatile acidity\"],\"data\":[[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}" http://127.0.0.1:1234/invocations
```
Disregarding this correction, I would like to know why the master version of the example documentation is not shown in here https://www.mlflow.org/docs/latest/tutorials-and-examples/tutorial.html ?

I hope this clarified a bit more.

**Comment by harupy** [comment]
The R doc uses `"` but the python one doesn't:

<img width="587" alt="Screen Shot 2021-01-04 at 17 17 36" src="https://user-images.githubusercontent.com/17039389/103514800-c3bbaf80-4eb0-11eb-91da-0ba1d4c258d1.png">

**Comment by pauldj54** [comment]
Hi @harupy , 
I got it :)
This explains why documentation looks different, I forgot the Python/R versions. 
But then the curl command for python has a bug from my point of view, and btw. the way you pass the data to curl must not differed from R to python, since the REST call is independent on the underlying language.

I had to replace single quotes with double quotes in order to make it work as follows:
```
# Windows python version
curl -X POST -H "Content-Type:application/json; format=pandas-split" --data "{"columns":["alcohol", "chlorides", "citric acid", "density", "fixed acidity", "free sulfur dioxide", "pH", "residual sugar", "sulphates", "total sulfur dioxide", "volatile acidity"],"data":[[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}" http://127.0.0.1:1234/invocations
```
Can someone test and verify it?

**Comment by harupy** [comment]
> the way you pass the data to curl must not differed from R to python, since the REST call is independent on the underlying language.

I agree. Would you be interested in making a PR to fix this?

**Comment by pauldj54** [comment]
Yes, sure. 
Is there any link to guidelines on how to do that for mlflow or should I follow a general git flow procedure?

**Comment by harupy** [comment]
I think you can just follow a general git flow procedure :)
