### ISSUE TITLE
MLflow as a conda-package

### ISSUE THREAD

**Issue by ToonKBC** [mlflow/mlflow#400]
A very useful feature would be to be able to install MLflow via conda.

Only two dependencies aren't conda packages yet:
 - databricks-cli
 - querystring_parser

**Comment by jaroslawk** [comment]
attempting to create conda forge PR 
 https://github.com/conda-forge/staged-recipes/pull/8072

**Comment by jaroslawk** [comment]
@mparkhe can add MLflow to conda-forge? any concerns with this>

**Comment by RoyalTS** [comment]
This would be super useful to have!

**Comment by jaroslawk** [comment]
it's a messy task. It looks like now there are 4 dependencies missing in conda-forge:

- docker[version='>=3.6.0']
- querystring_parser
- mleap[version='>=0.8.1']
- databricks-cli[version='>=0.8.0']

**Comment by jaroslawk** [comment]
querystring_parser is now in conda.

In contact with @andrewmchen  about the databricks-cli.

**Comment by jaroslawk** [comment]
@mateiz @mparkhe who can I contact from Databricks about this initiative? 
 Most of the dependencies are now conda-forge except of  ```databricks-cli``` the PR for it is done:
https://github.com/conda-forge/staged-recipes/pull/8101

all I need is your feedback/approval.

**Comment by mparkhe** [comment]
Hi @jaroslawk : @andrewmchen has offered to help out with this. Thanks!

**Comment by jaroslawk** [comment]
@mparkhe Perfect - Thank you!

**Comment by jaroslawk** [comment]
All it looks like mlflow version 0.9.0.1 is now available in conda - use command:

```conda install mlflow```

we can close this issue.

**Comment by mateiz** [comment]
That's great! Thanks for your help with this.
