### ISSUE TITLE
[enhancement] Proposal: Evaluate/Inference Model in the RUN page view

### ISSUE THREAD

**Issue by hamroune** [mlflow/mlflow#403]
it can be useful to do some inference in the Run page view directly, a sort of Postman integrated in the page, sometimes we would like to "test/verify" the model for a specific input. the cons that I see is the strong coupling btw Tracking and the Serving part.

**Comment by Zangr** [comment]
There is a keynote demo at the Spark+AI summit showing a prototype on the model registry work.
https://youtu.be/QJW_kkRWAUs?t=1381
