### ISSUE TITLE
Size of Javascript file

### ISSUE THREAD

**Issue by jhagege** [mlflow/mlflow#4040]
Hi, I noticed the Javascript file that is served by MLFlow server is around 8MB. 
Is there a way to compress it somehow so that serving will be faster ? 

Thanks !

**Comment by dmatrix** [comment]
@harupy @xanderwebs Does this cause an issue?

**Comment by xanderwebs** [comment]
The size of the JS bundle shouldn't inherently cause any issues besides from it being slow to load. I wouldn't necessarily say that it's a bug, but definitely an opportunity to improve the UX.

**Comment by dmatrix** [comment]
@jhagege Yeah, I would tend to agree that this is not a bug, per se, but could be improved, and rather be filed as a feature enhancement, and based on priorities, we can triage it accordingly.

Do you mind closing this issue or changing it to a feature enhancement rather than a bug

**Comment by jhagege** [comment]
Thanks all for your quick feedback. 
We have found it to be an issue in our case since we are serving from China server to EMEA region. 
It would sometimes crash in the middle of the download.
We solved by serving website through CDN. 

I'm unsure how to add / change label, I think it's reserved to admins. 
I'll close for now, do you mind adding label "feature improvement" ? 
Thanks !
