### ISSUE TITLE
[BUG] log_model, load_model,register_model... very slow under win10

### ISSUE THREAD

**Issue by potoo0** [mlflow/mlflow#4062]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution**: win10 20H2
- **MLflow installed from**: binary
- **MLflow version**: mlflow, version 1.13.1
- **Python version**: 3.8.5
- **DB**: mysql 8.0.21 for Win64 on x86_64 (MySQL Community Server - GPL)
- **Storage**: FTP from Internet Information Services (IIS)

### Describe the problem
log_model, load_model,register_model... very slow under win10

### Code to reproduce issue
timemeasur.py
```python
import time
import mlflow
import numpy as np
from mlflow.pyfunc import load_model

from model_builder import Test1


# config
tracking_server = 'http://localhost:8088'
experiment_name = 'pyfunc_model_t1'
registered_name = experiment_name
run_name = 'test1'
stage = None


st = time.time()
mlflow.tracking.set_tracking_uri(tracking_server)
print(f'time cost - set_tracking_uri: {time.time() - st}')

st = time.time()
mlflow.set_experiment(experiment_name)
print(f'time cost - set_experiment: {time.time() - st}')


# log model
model = Test1()
st = time.time()
with mlflow.start_run(run_name=run_name) as run:
    mlflow.pyfunc.log_model(
        'model',
        python_model=model,
        code_path=['model_builder.py']
    )
print(f'time cost - log_model: {time.time() - st}')

# register model
st = time.time()
reg_info = mlflow.register_model(
    f"runs:/{run.info.run_id}/model",
    registered_name
)
print(f'time cost - register_model: {time.time() - st}')

# load model
st = time.time()
loadedml_1 = load_model(f"models:/{registered_name}/{stage}")
print(f'time cost - load_model: {time.time() - st}')
```
model_builder.py
```python
import mlflow.pyfunc
import numpy as np


class Test1(mlflow.pyfunc.PythonModel):
    def __init__(self):
        super().__init__()

    def load_context(self, context):
        import numpy as np

        return

    def predict(self, context, model_input):
        '''
        Args:
            model_input: ndarray, shape: (-1)
        '''
        res = np.sum(model_input)

        return res
```

### Other info / logs
```
time cost - set_tracking_uri: 0.0
time cost - set_experiment: 2.0557515621185303
time cost - log_model: 8.30472469329834
Registered model 'pyfunc_model_t1' already exists. Creating a new version of this model...
2021/02/04 18:00:57 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: pyfunc_model_t1, version 6
Created version '6' of model 'pyfunc_model_t1'.
time cost - register_model: 6.139993906021118
time cost - load_model: 4.121163606643677
```

**Comment by dmatrix** [comment]
@potoo0 Thanks for reporting this behavior. Have you tried this on a non-win10 machine, like your UNIX flavored laptop or machine?
Curious if this is only win10 or any windows platform.

**Comment by potoo0** [comment]
I know it works fine under linux, but curious why it is so slow under win10.
I thought it was a mysql problem, so changed db to mysql:5.7.33 in docker. But still slow.
```
time cost - set_tracking_uri: 0.0
INFO: 'pyfunc_model_t1' does not exist. Creating a new experiment
time cost - set_experiment: 4.654943466186523
time cost - log_model: 8.642141580581665
Successfully registered model 'pyfunc_model_t1'.
2021/02/20 11:25:40 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: pyfunc_model_t1, version 1
Created version '1' of model 'pyfunc_model_t1'.
time cost - register_model: 6.309450626373291
time cost - load_model: 4.178121566772461
```

performance of the project running under centos7:
```
time cost - set_tracking_uri: 1.6689300537109375e-06
INFO: 'pyfunc_model_t1' does not exist. Creating a new experiment
time cost - set_experiment: 0.015707015991210938
time cost - log_model: 0.22059178352355957
Successfully registered model 'pyfunc_model_t1'.
2021/02/20 11:36:01 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: pyfunc_model_t1, version 1
Created version '1' of model 'pyfunc_model_t1'.
time cost - register_model: 0.06252670288085938
time cost - load_model: 0.03381514549255371
```

Why the performance of win10 and Linux are so different?

**Comment by PVShutov** [comment]
Hi! I confronted with the same bug on win10 and found that it is caused when server uri written as: `http://localhost:...`. In the case of specifying the uri through `localhost`, requests to the tracking server (that works through `requests` library) take about 2 seconds and when uri written as `http://127.0.0.1:...` that take just a few milliseconds. I found several questions on the stackoverflow about that problem with `requests.request`  ([1](https://stackoverflow.com/questions/47766158/why-is-python-requests-to-localhost-slow), [2](https://stackoverflow.com/questions/59506097/python-requests-library-is-very-slow-on-windows)) and I have not concretely idea why it occurs.

**Comment by potoo0** [comment]
> Hi! I confronted with the same bug on win10 and found that it is caused when server uri written as: `http://localhost:...`. In the case of specifying the uri through `localhost`, requests to the tracking server (that works through `requests` library) take about 2 seconds and when uri written as `http://127.0.0.1:...` that take just a few milliseconds. I found several questions on the stackoverflow about that problem with `requests.request` ([1](https://stackoverflow.com/questions/47766158/why-is-python-requests-to-localhost-slow), [2](https://stackoverflow.com/questions/59506097/python-requests-library-is-very-slow-on-windows)) and I have not concretely idea why it occurs.

thx, it works.
 Just change `tracking_server = 'http://localhost:8088'` to `tracking_server = 'http://127.0.0.1:8088'`.
