### ISSUE TITLE
[FR] Add a refresh button on MLflow UI

### ISSUE THREAD

**Issue by xavierbrt** [mlflow/mlflow#4073]
## Willingness to contribute

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

On the MLflow UI, add a refresh button above the table. When clicking on this button, the runs are reloaded. 

## Motivation

This feature is useful when new runs have been made since we loaded the interface. The current way to display new runs on the interface is to refresh the whole page, but by doing it we loose the display adjustments we made (collapse experiments list, column lengths, filters, etc.).
One of my usage of MLFlow is to open the interface, then open runs on new tabs to compare them. Then, I perform new runs on my ML code, I come back to the interface, retrieve the new runs (painful step to refresh the whole page each time I come back to the interface) and open the new experiments on new tabs.

### What component(s), interfaces, languages, and integrations does this feature affect?
Interfaces
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

## Details

I propose to implement a button like this one (the left one). It seems to require to modify the components `ExperimentView` and `ExperimentPage`. It would be a pleasure to work on it (as my first contribution !) once I have your validation.

![image](https://user-images.githubusercontent.com/23191816/107146079-22f46000-6946-11eb-9b3c-81742fab16f4.png)

**Comment by dmatrix** [comment]
@xavierbrt Thanks for filling this enhancement. 

@xanderwebs Is this something we should consider, given that you may have the UI and runs page up while running more runs that may not show up dynamically unless we refresh it manually. This 'button' is may be equivalent to 'reload` the run's page.

**Comment by mohammedayub44** [comment]
@xavierbrt This would be a great addition. I ran into this recently and was looking for any settings inside MLFlow docs.

**Comment by dbczumar** [comment]
A refresh button has been added. Thank you for using MLflow!
