### ISSUE TITLE
Error when using mlflow.sklearn.autolog()

### ISSUE THREAD

**Issue by ngu086** [mlflow/mlflow#4075]
On Databricks Runtime 6.4 (includes Apache Spark 2.4.5, Scala 2.11)

I get an error 'str' object has no attribute 'clear', when I try to use mlflow.sklearn.autolog().

I tried updating the scikit-learn. But this seems to be bother yet.

Following is the log which also mentions "ImportError: cannot import name 'all_estimators' from 'sklearn.utils' (/databricks/python/lib/python3.7/site-packages/sklearn/utils/__init__.py)"

Attaching the complete log.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/databricks/python/lib/python3.7/site-packages/mlflow/sklearn/utils.py in _all_estimators()
    729     try:
--> 730         from sklearn.utils import all_estimators
    731 

ImportError: cannot import name 'all_estimators' from 'sklearn.utils' (/databricks/python/lib/python3.7/site-packages/sklearn/utils/__init__.py)

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<command-3446996804139076> in <module>
      1 # Enable autolog()
      2 # mlflow.sklearn.autolog() requires mlflow 1.11.0 or above.
----> 3 mlflow.sklearn.autolog()
      4 
      5 # With autolog() enabled, all model parameters, a model score, and the fitted model are automatically logged.

/databricks/python/lib/python3.7/site-packages/mlflow/utils/autologging_utils.py in autolog(*args, **kwargs)
    343             AUTOLOGGING_INTEGRATIONS[name] = config_to_store
    344 
--> 345             return _autolog(*args, **kwargs)
    346 
    347         wrapped_autolog = _update_wrapper_extended(autolog, _autolog)

/databricks/python/lib/python3.7/site-packages/mlflow/sklearn/__init__.py in autolog(log_input_examples, log_model_signatures, log_models, disable, exclusive)
    933                 return original(self, *args, **kwargs)
    934 
--> 935     _, estimators_to_patch = zip(*_all_estimators())
    936     # Ensure that relevant meta estimators (e.g. GridSearchCV, Pipeline) are selected
    937     # for patching if they are not already included in the output of `all_estimators()`

/databricks/python/lib/python3.7/site-packages/mlflow/sklearn/utils.py in _all_estimators()
    732         return all_estimators()
    733     except ImportError:
--> 734         return _backported_all_estimators()
    735 
    736 

/databricks/python/lib/python3.7/site-packages/mlflow/sklearn/utils.py in _backported_all_estimators(type_filter)
    797     # Ignore deprecation warnings triggered at import time and from walking
    798     # packages
--> 799     with ignore_warnings(category=FutureWarning):
    800         for _, modname, _ in pkgutil.walk_packages(path=[root], prefix="sklearn."):
    801             mod_parts = modname.split(".")

/databricks/python/lib/python3.7/site-packages/sklearn/utils/testing.py in __enter__(self)
    366         self._module.filters = self._filters[:]
    367         self._showwarning = self._module.showwarning
--> 368         clean_warning_registry()
    369         warnings.simplefilter("ignore", self.category)
    370 

/databricks/python/lib/python3.7/site-packages/sklearn/utils/testing.py in clean_warning_registry()
    799             continue
    800         if hasattr(mod, reg):
--> 801             getattr(mod, reg).clear()
    802 
    803 

AttributeError: 'str' object has no attribute 'clear'

**Comment by harupy** [comment]
@ngu086 hi, what happens if you run this code?

```python
reg = "__warningregistry__"
for mod_name, mod in list(sys.modules.items()):
    if 'six.moves' in mod_name:
        continue
    if hasattr(mod, reg):
        # getattr(mod, reg).clear()
        print(mode, reg, getattr(mod, reg))
```

**Comment by ngu086** [comment]
I could have done it, in search of solution I updated the Databricks version from 6.1 to 7.5 and looks like it resolved.

Thanks for the solution. If I again get stuck will try the same.

**Comment by harupy** [comment]
@ngu086 Got it :)
