### ISSUE TITLE
[FR] support non-pandas-based dataframe input formats in REST API

### ISSUE THREAD

**Issue by yitao-li** [mlflow/mlflow#4094]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

According to https://mlflow.org/docs/latest/models.html#deploy-mlflow-models dataFrames can only be sent in JSON-serialized split-orientation format, JSON-serialized records orientation, or in CSV format. It would be nice to support other formats such as arrow.

## Motivation
- What is the use case for this feature? Users won't need to convert from other formats such as arrow when sending over dataframes through the REST API. Also, arrow is a highly performant, in-memory serialization mechanism that is widely used.
- Why is this use case valuable to support for MLflow users in general? Because arrow format is well supported in multiple programming languages (Python, R, Java, etc), MLflow users will have the option of sending over dataframe in arrow format once arrow format is supported by MLflow server. 
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case?

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@yitao-li Thanks for filing this. @tomasatdatabricks is implementing to include Tensors support in addition to Panda DataFrame. This includes accepting a numpy array, a list of numpy arrays, or a dictionary of numpy arrays. So it may be a duplicate effortl, as changing the model input signature affects the REST API too, I believe.

**Comment by tomasatdatabricks** [comment]
@dmatrix @yitao-li Tensor input support will be part of the next release, however, the input for the model is still expected as JSON. We do not have plans to add binary input format (e.g. Arrow or protobuf) in the immediate future, but we would certainly welcome contributions.

**Comment by yitao-li** [comment]
@dmatrix @tomasatdatabricks Awesome! Thanks for letting me know.
