### ISSUE TITLE
Documentation page seems to be down https://www.mlflow.org/docs/latest/index.html

### ISSUE THREAD

**Issue by axsaucedo** [mlflow/mlflow#4127]
We have a linter that checks in our build for links, and it seems that this was flagged up - the docs are not accessible through the usual link (nor the one in the mlflow website) https://www.mlflow.org/docs/latest/index.html

**Comment by harupy** [comment]
@axsaucedo Thanks for reporting this. We're investigating why this is happening:

- https://mlflow.org/docs/1.13.1/tracking.html  # available
- https://mlflow.org/docs/1.14.0/tracking.html  # unavailable

**Comment by harupy** [comment]
@axsaucedo We've re-uploaded files for the latest version documentation.

**Comment by axsaucedo** [comment]
Great, thank you @harupy , our docs lint passes as well, thanks
