### ISSUE TITLE
Use MLflow's CLI to upload artifacts from R

### ISSUE THREAD

**Issue by javierluraschi** [mlflow/mlflow#415]
This issue is tracking work to:
- Expose artifact upload to AWS, Google, Azure, etc in MLflow's CLI
- Make use of this functionality in the R client.

Currently, artifacts are written to AWS using the [cloudyr/aws.s3](https://github.com/cloudyr/aws.s3) and the Azure/Google CLIs; however, we are planning to use MLflow's CLI instead.

**Comment by kevinykuo** [comment]
Related: https://github.com/mlflow/mlflow/pull/391. We'll need to evaluate the drawbacks pointed out in the PR and decide how to proceed.

**Comment by javierluraschi** [comment]
The comment I added in https://github.com/mlflow/mlflow/pull/370:

> I did experimented with the new MLflow CLI artifacts command today a bit. However, I found out this might not work without additional changes for remote (tracking) servers. The error that I get is `Invalid run ID: '###'` since I'm using a remote tracking server, but when logging an artifact to S3 the local CLI is not aware of the remote run ID. I think what would make the most sense is to track this one with https://github.com/mlflow/mlflow/issues/415 and figure it out and provide a fix after we merge this PR.

**Comment by javierluraschi** [comment]
(( We found out we can use the `MLFLOW_TRACKING_URI` env var to register remote services and still use the CLI )).

**Comment by javierluraschi** [comment]
This one was fixed with https://github.com/mlflow/mlflow/pull/370.
