### ISSUE TITLE
[DOC-FIX] No clear difference between mlflow.azureml.build_image and mlflow.azureml.deploy API methods

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#4165]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [ x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

- https://mlflow.org/docs/latest/python_api/mlflow.azureml.html#mlflow.azureml.build_image
- https://mlflow.org/docs/latest/python_api/mlflow.azureml.html#mlflow.azureml.deploy

### Description of proposal (what needs changing):

The documentation for these two methods is practically identical. If there is a difference it needs to be called out. Otherwise, one of them is redundant. 

- [mlflow.azureml.build_image](https://mlflow.org/docs/latest/python_api/mlflow.azureml.html#mlflow.azureml.build_image) - Register an MLflow model with Azure ML and build an Azure ML ContainerImage for deployment. The resulting image can be deployed as a web service to Azure Container Instances (ACI) or Azure Kubernetes Service (AKS).
- [mlflow.azureml.deploy](https://mlflow.org/docs/latest/python_api/mlflow.azureml.html#mlflow.azureml.deploy) - Register an MLflow model with Azure ML and deploy a websevice to Azure Container Instances (ACI) or Azure Kubernetes Service (AKS).

**Comment by dmatrix** [comment]
@amesar Thanks, Andre.  Please do file a PR.

**Comment by dbczumar** [comment]
These APIs are deprecated and will be removed in MLflow 2.0.
