### ISSUE TITLE
Unable to download punkt from nltk 

### ISSUE THREAD

**Issue by jabraunlin** [mlflow/mlflow#4169]
I am trying to deploy a model on sagemaker with mlflow. The model requires that the nltk "punkt" model is downloaded.
This can usually be done inside python code with 
`import nltk`
`nltk.download('punkt`)

However, this doesn't work in docker. This can be overcome by using the following line in the Dockerfile:
`RUN python -m nltk.downloader "punkt"

I haven't found any way to do this with mlflow. Is there a way I can somehow save it as an artifact, add the data manually, or edit the conda_env.yaml file to download it?

**Comment by dmatrix** [comment]
@jabraunlin You can save a directory with files as an artifact. Here is the [sample code snippet](https://github.com/dmatrix/mlflow-tests/blob/master/py/mlflow/mlflow_issues/issue_4169.py) that will do the trick; just replace the download path with yours.

The result will the directory is logged as an MLflow artifact.

![Screen Shot 2021-03-11 at 9 50 38 AM](https://user-images.githubusercontent.com/1117597/110832228-e8852800-824f-11eb-886c-35cd07531dbe.png)

If this helps, let's close this issue.
