### ISSUE TITLE
Artifact listing error on remote server

### ISSUE THREAD

**Issue by vertikal-andrea** [mlflow/mlflow#4170]
I am trying to setup a MLFlow tracking server on a remote machine as a systemd service.
I have a sftp server running and created an SSH key pair.

Everything seems to work fine except the artifact logging. MLFlow seems to not have permissions to list the artifacts saved in the `mlruns` directory.

I create an experiment and log artifacts in this way:

```
    uri = 'http://192.XXX:8000' 
    mlflow.set_tracking_uri(uri)
    
    mlflow.create_experiment('test', artifact_location='sftp://192.XXX:_path_to_mlruns_folder_')
    
    experiment=mlflow.get_experiment_by_name('test')
    with mlflow.start_run(experiment_id=experiment.experiment_id, run_name=run_name) as run:
           mlflow.log_param(_parameter_name_, _parameter_value_)     
           mlflow.log_artifact(_an_artifact_, _artifact_folder_name_)
```

I can see the metrics in the UI and the artifacts in the correct destination folder on the remote machine. However, in the UI I receive this message when trying to see the artifacts:

_Unable to list artifacts stored
under sftp://192.XXX:_path_to_mlruns_folder_/_run_id_/artifacts
for the current run. Please contact your tracking server administrator
to notify them of this error, which can happen when the tracking
server lacks permission to list artifacts under the current run's root
artifact directory._

I cannot figure out why as the `mlruns` folder has `drwxrwxrwx` permissions and all the subfolders have `drwxrwxr-x`. 
What am I missing?

In general, I think tt would be nice to have a more detailed documentation on how to set up remote MLFLow tracking servers.

**Comment by vertikal-andrea** [comment]
Turns out that the sytemd service should not be run by root (default) but a User with the right permissions should be defined.
(Still getting some warning though, so maybe a better solution is out there)

I believe my comment on a better documentation still stands.

**Comment by vertikal-andrea** [comment]
Turns out that the sytemd service should not be run by root (default) but a User with the right permissions should be defined.
(Still getting some warning though, so maybe a better solution is out there)

I believe my comment on a better documentation still stands.

**Comment by Yuchen-Li** [comment]
Did you solved this issue mate？I`m in the same trouble. The different is I run the service by the user with the right permissions, but I still got
```
Unable to list artifacts stored
under sftp://192.XXX:path_to_mlruns_folder/run_id/artifacts
for the current run. Please contact your tracking server administrator
to notify them of this error, which can happen when the tracking
server lacks permission to list artifacts under the current run's root
artifact directory.
```

**Comment by vertikal-andrea** [comment]
I solved it.
The problem is where your mlruns folders sits and who is running the server service.
Two options:
1) `mlruns` sits somewhere under your user's home: need to specify `User=your_user` under the `[Service]` section of the `mlflow-tracking.service` file, and to create a SSH key pair from 192.XXX to 192.XXX itself.
2) `mlruns` sits directly under` /root `: **maybe** no need to do anything. Not really tried this one.

**Comment by Ankur-singh** [comment]
I am facing the same issue. I am using GCP bucket to store my artifacts. I can see the artifacts in the bucket but for some reason  the UI is not able to display the preview. 

- Before `mlflow.end_run()` I see the following message.
<img width="945" alt="image" src="https://user-images.githubusercontent.com/14893062/156553523-85b1c62f-e12f-4ab4-bb2d-36d28485aa9e.png">

- after `mlflow.end_run()`, I am getting the loading image
<img width="919" alt="image" src="https://user-images.githubusercontent.com/14893062/156553760-1214ae30-c845-442e-8420-26b56434bb51.png">

- When I am running the server locally, I am able to see the artifacts and can also preview the ML Model correctly.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/14893062/156554249-daf079ba-922c-4e0d-bc9e-f6b771086dd2.png">

IMO, it has something to do with the GCP bucket. Am I doing anything wrong?
