### ISSUE TITLE
[FR] Add delete_artifact method to mlflow API

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#4185]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

We need to add a mlflow.delete_artifact method to the API as an analog to mlflow.log_artifact. 

## Motivation

If clients can add an artifact they should be able to delete it.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by dmatrix** [comment]
@amesar Thanks for filing this. Yeah, this is an interesting question as it poses a question about how long should we retain experiment runs and associated artifacts for auditing. Currently, we just move the experiment into a _.trash_ folder under _mlruns_ and have `mlflow gc...` have it clean up in the OSS version, at least. 

This would be a good proposal to address this retention as a documented policy, as I understand.

**Comment by ankh6** [comment]
Hey @dmatrix I'd like to make my first contribution if the issue is free
I've searched for the module but have not found it. Could you redirect me to the relevant code section as I am not familiar (yet) with MLflow

**Comment by SaravananSathyanandhaQC** [comment]
@dmatrix bump on this - any openness to this (I'm happy to implement if so)? Alternative as a user I'd also be fine with going directly to the aritfact repository - but as per for example https://github.com/mlflow/mlflow/blob/312f5f9f46f4ca4da6e0bf594bb7c23bbec4dbd2/mlflow/store/artifact/local_artifact_repo.py#LL114 it seems `delete_artifacts` is designed specifically to delete directories, not individual files. Would be open to changing this to support individual files too

**Comment by alam-shahul** [comment]
Hi there, I think it would be great if the `delete_artifacts` method could just be changed so that it works with either files or directories. It seems like a simple enough fix.
