### ISSUE TITLE
[DOC-FIX] Document the maximum value and legal characters for log_param, log_metric and set_tag

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#4202]
### URLS with the issue:

* https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_param
* https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_metric
* https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tag

### Description of proposal:

Document the maximum value and legal characters for log_param, log_metric and set_tag. Note that log_metric's value is already documented as float.

Tags:
* Apparently there is a 250  character limit for tag keys. See https://github.com/mlflow/mlflow/blob/master/mlflow/utils/validation.py#L31.
* There is a 5000 character limit for tag values. See: https://github.com/mlflow/mlflow/blob/master/mlflow/utils/validation.py#L30.

Sample error messages for set_tag::
* `Tag value 'x...' had length 5001, which exceeded length limit of 250`
* `Tag value 'vv...' had length 5001, which exceeded length limit of 5000`

However, there seems to be no limit to a parameter's key or value.

Metrics:
* MlflowException: Invalid metric name: '01: running time in mins'. Names may only contain alphanumerics, underscores (_), dashes (-), periods (.), spaces ( ), and slashes (/)

**Comment by tmnhat2001** [comment]
@dmatrix If this issue is open for taking, I could open a PR to document the information above.

**Comment by westford14** [comment]
@dmatrix -- hey all, i've picked this up really quickly, is there a process for getting eyes on a PR?

**Comment by karan-kaushik-searce** [comment]
Hey @dmatrix 
Is this still open? Anywhere I can help out?

**Comment by karan-kaushik** [comment]
Hey @dmatrix 
Anywhere I can help out if this is still open?

**Comment by atharvapatil123** [comment]
Hey @dmatrix
Is this issue still open?!

**Comment by dmatrix** [comment]
looks like it’s closed & merged

**Comment by rafaelvp-db** [comment]
@amesar just drop in to confirm if this has been closed - would you be able to close it, if it's indeed the case? (if it's not closed I'm happy to contribute)
