### ISSUE TITLE
Log dictionaries as artifacts

### ISSUE THREAD

**Issue by drorata** [mlflow/mlflow#424]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.5.2
- **Python version**: 3.6

### Describe the problem
I would like to keep track of dictionaries produced during a run. For example, keep track of an attribute `param_grid` of a grid search. However, I don't want to keep a dump of this JSON outside of mlflow. I tried the following workaround. As is, `log_artifact` expects a filename. Therefore, I dump the `dict` into a temp file and try to log it:

```python
with tempfile.NamedTemporaryFile(delete=False) as f:
    f.write(json.dumps(clf.param_grid).encode())
    log_artifact(f.name)
```

In the `mlruns` directory I can find the file generated, but it is empty. Note that the actual temp file (which is kept as `delete=False`) can be found and it is not empty but it holds the right content.

* What am I doing wrong? Why isn't it correctly tracked by mlflow?
* I would argue that `log_artifact` should support objects as well and keep their string representation. What do you think?

**Comment by drorata** [comment]
I found the solution

```python
with tempfile.NamedTemporaryFile(mode='w', suffix='.txt') as f:
    # Note the mode is 'w' so json could be dumped
    # Note the suffix is .txt so the UI will show the file
    json.dump(clf.param_grid, f)
    f.seek(0) # You cannot close the file as it will be removed. You have to move back to its head
    log_artifact(f.name)
```

**Comment by drorata** [comment]
Isn't it desired to let `log_artifact` get an object as an input and not only a string referring to an existing file?

**Comment by smurching** [comment]
@drorata sorry for the delayed response! I can see that it'd be nice to be able to pass an object to `log_artifact` instead of having to log a file, but it also doesn't seem too hard to write to a file & then log it, and I think the semantics of logging an object get kinda tricky - for example, if someone doesn't pass `artifact_path`, how do we determine a name for the artifact?
