### ISSUE TITLE
[FR] Add Transformers Pretrained Model Flavor

### ISSUE THREAD

**Issue by twolffpiggott** [mlflow/mlflow#4245]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

This proposal would add a [Transformers](https://github.com/huggingface/transformers) [pretrained model](https://huggingface.co/transformers/pretrained_models.html) flavor to MLflow.

### What is the use case for this feature?

The custom model flavor will enable full integration of Transformer pretrained model artifacts with tracking server runs and the MLflow model registry, and enable downstream integration with [Seldon](https://docs.seldon.io/projects/seldon-core/en/v1.1.0/servers/mlflow.html) via the resulting MLmodel. Users will be able to serialise transformers model artifacts via a simple `mlflow.log_model` call, and load via `mlflow.pyfunc.load_model`.

### Why is this use case valuable to support for MLflow users in general?

Transformers is a very popular NLP library (it has significantly more stars, for example, than [Catboost](https://github.com/catboost/catboost), for which a flavor was recently added). Its integration with the MLflow tracking server and model registry will support many NLP use cases for experimentation and deployment. Many MLflow users will have interests in NLP projects.

### Why is this use case valuable to support for your project(s) or organization?

My projects involve fine-tuning transformers pretrained models for specific use cases. This involves experimentation using the MLflow tracking server and publishing new model versions via the MLflow model registry, which is connected to production pipelines. A transformers pretrained model flavor supports seamless integration of the full model artifacts with the tracking server runs and model registry.

### Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Transformers pretrained models use [custom serialisation methods](https://github.com/huggingface/transformers/blob/4b919657313103f1ee903e32a9213b48e6433afe/src/transformers/modeling_utils.py#L784), that save and load a number of model dependencies in addition to the Pytorch model binary. Transformers pretrained models are also generally expected to be serialised together with a [tokenizer](https://github.com/huggingface/transformers/blob/cb38ffcc5e0ae2fac653342ac36dc75c15ea178f/src/transformers/tokenization_utils_base.py#L1839).

Additionally, the PyFunc wrapper for a transformers pretrained model should ideally include tokenisation. By contrast, the [existing Pytorch model flavor](https://github.com/mlflow/mlflow/blob/master/mlflow/pytorch/__init__.py) assumes only the bare `torch.save` and `torch.load` functions are used for (de)serialisation, and has a parsimonious `_PyTorchWrapper` that cannot currently include tokenisation.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

This proposal would add a [Transformers](https://github.com/huggingface/transformers) [pretrained model](https://huggingface.co/transformers/pretrained_models.html) flavor to MLflow.

Since the underlying models are Pytorch-based, the implementation would be similar to the [existing Pytorch model flavor](https://github.com/mlflow/mlflow/blob/master/mlflow/pytorch/__init__.py).

However, it would specifically add saving and loading functionality for [Transformers pretrained models](https://huggingface.co/transformers/pretrained_models.html) and [tokenizers](https://huggingface.co/transformers/main_classes/tokenizer.html).

Instead of using the bare `torch.save` and `torch.load`, it would invoke the `save_pretrained` methods for [Transformers pretrained models](https://github.com/huggingface/transformers/blob/4b919657313103f1ee903e32a9213b48e6433afe/src/transformers/modeling_utils.py#L784) and [tokenizers](https://github.com/huggingface/transformers/blob/cb38ffcc5e0ae2fac653342ac36dc75c15ea178f/src/transformers/tokenization_utils_base.py#L1839).

This flavor would also implement a custom `_TransformerPretrainedWrapper` for the PyFunc implementation.

**Comment by dmatrix** [comment]
@twolffpiggott Thanks for filling this enhancement. I think in general this will be a valuable addition to the community by adding
Transformers as an MLflow Model flavor. 

Adding committers to suggest any additional input for design or questions
cc: @smurching @harupy @dbczumar

**Comment by twolffpiggott** [comment]
Fantastic, thanks @dmatrix. I'll get started with an initial version shortly and keep this thread updated.

**Comment by s-udhaya** [comment]
Hi, I spent sometime and came up with an implementation to support transformers flavor in mlflow and created a draft PR #7473 . It supports explicit logging for both pytorch and tensorflow models and auto logging for pytorch models. There are multiple examples in the PR that shows how to use this flavor. I have not written any tests yet. Before I spend more time on implementing the tests, I would love to get an initial review from the community to see if the implementation and design decision makes sense. @smurching @harupy @dbczumar Could you guys please have a look at my draft PR and provide me with your valuable opinion so that I will know if it makes sense to move forward with writing tests and finalising the PR?

**Comment by hugocool** [comment]
is there any movement on this issue?
Could I contribute in any way? Id like to log transformer models to MLFlow, so id love to use this flavor.

**Comment by PhilipMay** [comment]
@hugocool maybe this helps?
https://github.com/telekom/transformer-tools/blob/main/transformer_tools/mlflow_transformers_flavor.py

**Comment by dbczumar** [comment]
@BenWilson2 can you share updates here?

**Comment by hugocool** [comment]
> @hugocool maybe this helps? https://github.com/telekom/transformer-tools/blob/main/transformer_tools/mlflow_transformers_flavor.py

That is really nice, although it does not support mlflow v > 2. (I get an error with respect to mlflow.pyfunc.utils)
So ill have a look at the implementation in this PR, and the package you mentioned, merge them, see whether they work for my purposes, and ill report back.

**Comment by BenWilson2** [comment]
Hi all, We're planning to start work on this flavor starting today. 
We'll be leaning heavily into supporting PIpeline abstractions as a first class citizen (for pyfunc, spark_udf use cases) but also supporting the logging of Trainers, individual model components (logging a model, a tokenizer, and a feature extractor separately), and maintaining metadata logging to ensure that loading of any of these components from a saved state will create the appropriate object from the correct subclass. 
We should have this flavor officially supported and part of MLflow by the time that the next minor release is out! 
Thank you all for your continued interest in this and we'll be sure to have something useful for you to streamline your use of the fantastic transformers package!

**Comment by hugocool** [comment]
Could we also add a flavor for AutoGluon (multimodal) while we are at it?
Since in that case we need to store a larger breadth of prepocessing elements, it could be a nice litmus test for whether the currently considered approach will work.

Im currently relying on the kedro-mlflow definition of a pipeline, and storing everything as such as a pyfunc. This also allows one to store entire pipelines as well (alhough it is more opinionated).

anyway,[ there is already an issue open at Autogluon](https://github.com/autogluon/autogluon/issues/1404)

**Comment by B-Step62** [comment]
Transformers is supported in MLflow >= 2.3, please take a look at [the documentation](https://mlflow.org/docs/latest/llms/transformers/index.html) for the detailed usage.
