### ISSUE TITLE
[FR] Use other package manager than conda for MLFlow Projects

### ISSUE THREAD

**Issue by FloMrt** [mlflow/mlflow#4246]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary
Have the capacity to build virtual environment with other tools than conda when using MLFlow Projects. For example poetry (https://github.com/python-poetry/poetry)

## Motivation
- What is the use case for this feature?
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details
Currently MLFlow use conda to automatically create virtual environment when using the MLFlow Projects. If you don't want to use conda you only have docker or system environment left. But that does not leave the same "reproductibility" capacity because you can't directly run a git repository without having to be sure that either:
- The docker image is up to date (and stored locally or in dockerhub, private repos are not accessibles)
- The system environment have all the packages that you need

I know that there are many package manager for python out there, but having the capacity to automatically build environment with other tools than conda will be well appreciated !

Thank for the hard and good works :)

**Comment by dmatrix** [comment]
@FloMrt We are looking into ways to replace Conda with other mechanisms since conda has changed its commercial usage policy.

**Comment by FloMrt** [comment]
Yeah that's another reason to do so :)
I'll gladly help to investigate if needed !

**Comment by onacrame** [comment]
Pip and Poetry please

**Comment by dbczumar** [comment]
Virtualenv support has been added to MLflow Projects. You can try it out in MLflow 1.27.0. Thank you for using MLflow!
