### ISSUE TITLE
[FR] Create a public ROADMAP file

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#4258]
Many MLflow users have expressed a desire to know the MLflow roadmap. Having a ROADMAP file in github would enable us to be more transparent. 
A good example is https://github.com/kubeflow/kfserving/blob/master/ROADMAP.md.

**Comment by dmatrix** [comment]
cc: @harupy @smurching @WeichenXu And also use the slack channel #mlflow-roadmap to publish it.

**Comment by dbczumar** [comment]
We're now publishing roadmaps incrementally using GitHub Issue milestones. Thanks folks!
