### ISSUE TITLE
how to run mlflow project with iterative-loop

### ISSUE THREAD

**Issue by YOONAHLEE** [mlflow/mlflow#4306]
Hello,
I want to run mlflow projects with iterative-loop.

for example, I want to compare the result when key[one of parameter] is different from 1~255

Rather than writing all of those commands (255),
is there way to use iterative-loop for command in entry points?

**Comment by dmatrix** [comment]
@YOONAHLEE MLflow project is a single unit of execution, meaning that you supply parameters or use default parameters to execute a run. For each parameter, you will have to supply a different argument, resulting in a new run. 

One thing you could probably do is that iterate your mlflow.start_run() .... : code inside a loop where you providing a new argument.

This way you will have only a single MLflow project run execution, but 255 different runs within that project. In effect, you will have a single entry point, with multiple runs withing the code that executes it. Try that.

**Comment by YOONAHLEE** [comment]
I see. Thank you for answering to the question!
