### ISSUE TITLE
TSV files are not displayed in the preview pane

### ISSUE THREAD

**Issue by whiletruelearn** [mlflow/mlflow#434]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **MLflow installed from (source or binary)**:  binary
- **MLflow version (run ``mlflow --version``)**:  0.5.2
- **Python version**: 2.7
- **npm version (if running the dev UI):
- **Exact command to reproduce**: `mlflow.log_artifact(<file.tsv>)`

### Describe the problem
TSV files are a common file format for artifacts, `mlflow.log_artifact` does persist `tsv` files in the artifact repository, but they are not displayed in preview pane. 

### Source code / logs
#433

**Comment by andrewmchen** [comment]
Resolved by https://github.com/mlflow/mlflow/pull/433. Thanks for the PR!
