### ISSUE TITLE
Request: Add ability to delete 

### ISSUE THREAD

**Issue by normster** [mlflow/mlflow#437]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 0.5.2
- **Python version**: 3.6.5

Currently if I launch a run with incorrect arguments, even if I kill it after 1s it is still logged and shows up in the mlflow ui. In order to delete the run, I have to launch the ui to find the run id by matching the short duration/incorrect arguments, then go back to my terminal and manually remove the bad run's directory. Can we add a button to the ui to delete a run directly?

**Comment by aadamson** [comment]
Current WIP addressing this: https://github.com/mlflow/mlflow/pull/418

**Comment by apurva-koti** [comment]
Closing as this was merged.
