### ISSUE TITLE
[BUG] - INVALID_PARAMETER_VALUE: Model registry functionality is unavailable; got unsupported URI

### ISSUE THREAD

**Issue by Matinrokzz** [mlflow/mlflow#4399]
I am using mlflow in local machine, I can see the experiments tab but when I click on the model tab in mlflow UI, I get this error, can anyone please help
"INVALID_PARAMETER_VALUE: Model registry functionality is unavailable; got unsupported URI './mlruns' for model registry data storage. Supported URI schemes are: ['postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations."

**Comment by Matinrokzz** [comment]
found the fix, run this in your terminal
mlflow server --backend-store-uri sqlite:///:memory --default-artifact-root ./mlruns

**Comment by eacatalyst** [comment]
I am having the exact issue as irfaanz
I only get to see the models when I run:  model ui
When running:  mlflow server --backend-store-uri sqlite:///:memory --default-artifact-root ./mlruns the runs are not available

**Comment by dachosen1** [comment]
I'm having the same issues too.

**Comment by toby-htx** [comment]
Me too.

**Comment by phdd** [comment]
> found the fix, run this in your terminal mlflow server --backend-store-uri sqlite:///:memory --default-artifact-root ./mlruns

This is not a fix, as tracking data persistence will not work. This issue has to be reopened.

**Comment by lifesboy** [comment]
I'm having same issue when run 
`/usr/local/bin/mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://postgres:postgres@127.0.0.1:5432/postgres --default-artifact-root /drl/mlruns`

gotting error:
```
During handling of the above exception, another exception occurred:
--
  |  
  | [36mray::RayServeWrappedReplica.reconfigure()[39m (pid=6330, ip=192.168.66.180, repr=<ray.serve.replica.anomaly-staging object at 0x7f0562278588>)
  | File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/client.py", line 95, in _get_registry_client
  | registry_client = ModelRegistryClient(self._registry_uri)
  | File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_model_registry/client.py", line 36, in __init__
  | self.store  # pylint: disable=pointless-statement
  | File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_model_registry/client.py", line 40, in store
  | return utils._get_store(self.registry_uri)
  | File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_model_registry/utils.py", line 169, in _get_store
  | return _get_store_registry().get_store(store_uri)
  | File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_model_registry/registry.py", line 37, in get_store
  | return self._get_store_with_resolved_uri(resolved_store_uri)
  | File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_model_registry/registry.py", line 46, in _get_store_with_resolved_uri
  | builder = self.get_store_builder(resolved_store_uri)
  | File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/registry.py", line 79, in get_store_builder
  | unsupported_uri=store_uri, supported_uri_schemes=list(self._registry.keys())
  | mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'file:///mlruns' for model registry data storage. Supported URI schemes are: ['databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.

```

**Comment by lifesboy** [comment]
Find solution: Fixed by add enviroment variable before starting ray 
`Environment=MLFLOW_TRACKING_URI=postgresql://postgres:postgres@127.0.0.1:5432/postgres`

**Comment by YJonmo** [comment]
> Environment

where did you put this Environment?

**Comment by Cybernorse** [comment]
If you are using python3.7 and you have mlflow version 1.27.* and you have this error, you need to update the mlflow to 1.30.* to resolve this error.
It worked for me
