### ISSUE TITLE
Cannot log artifact in R on Windows 10

### ISSUE THREAD

**Issue by FrieseWoudloper** [mlflow/mlflow#4426]
### Willingness to contribute
No. I cannot contribute a bug fix at this time.

### System information
- Have I written custom code (as opposed to using a stock example script provided in MLflow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- MLflow installed from (source or binary): binary
- MLflow version: 1.17.0
- Python version: 3.8.10
- R version: 4.1.0
- mlflow R package version: 1.17.0
- Exact command to reproduce in R:
```
library(mlflow)
mlflow_log_param("foo", 42)
mlflow_log_metric("mse", 0.87)
mlflow_set_tag("training-data-cutoff", "Dec 2017")
writeLines("Blahdieblah", "output.txt")
mlflow_log_artifact("output.txt")
mlflow_end_run()
```

### Describe the problem
I've installed MLFlow and the `mlflow` package in R. Logging parameters and metrics works fine, but when I try to log an artifact, I get an error:

```
Error in rethrow_call(c_processx_exec, command, c(command, args), pty,  : 
  Command 'C:/Users/XXXXXX/.conda/envs/r-mlflow-1.17.0/mlflow' not found @win/processx.c:982 (processx_exec)
```

### Code to reproduce issue
```
library(mlflow)
writeLines("Blahdieblah", "output.txt")
mlflow_log_artifact("output.txt")
mlflow_end_run()
```

### Other info / logs
When I log an artifact in Python, everything works fine. So I guess the problem is in R.

I have the problem when I try to connect to a local file store, as well as a dbfs store on Microsoft Azure.

```
Stack trace:

 1. mlflow:::mlflow_log_artifact("output.txt")
 2. mlflow:::mlflow_cli("artifacts", command, local_param, path,  ...
 3. withr:::with_envvar(env, { ...
 4. base:::force(code)
 5. processx:::run(mlflow_bin, args = unlist(args), echo = echo,  ...
 6. process$new(command, args, echo_cmd = echo_cmd, wd = wd, windows_verbatim_args = win ...
 7. processx:::initialize(...)
 8. processx:::process_initialize(self, private, command, args, stdin,  ...
 9. rethrow_call(c_processx_exec, command, c(command, args), pty,  ...

 x Command 'C:/Users/XXXXXX/.conda/envs/r-mlflow-1.17.0/mlflow' not found @win/processx.c:982 (processx_exec) 
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

Language 
- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by FrieseWoudloper** [comment]
I turned on verbose logging. Output:

```
Running "C:/Users/XXXXXX/.conda/envs/r-mlflow-1.17.0/mlflow" artifacts log-artifact --local-file output.txt --run-id \
  74e7f2bfc87f43f191f76aaf8f0b7f59
Error in rethrow_call(c_processx_exec, command, c(command, args), pty,  : 
  Command 'C:/Users/XXXXXX/.conda/envs/r-mlflow-1.17.0/mlflow' not found @win/processx.c:982 (processx_exec)
```

`mlflow.exe` is one directory deeper, in `C:/Users/XXXXXX/.conda/envs/r-mlflow-1.17.0/mlflow/Scripts`. Could that be the problem? If so, how do I solve it?

**Comment by FrieseWoudloper** [comment]
I think I've found the problem. It's located in `python_mlflow_bin()`.

```
python_mlflow_bin <- function() {
  in_env <- Sys.getenv("MLFLOW_BIN")
  if (in_env != "") {
    return(in_env)
  }
  python_bin_dir <- dirname(python_bin())
  file.path(python_bin_dir, "mlflow")
}
```
When the `MLFLOW_BIN` environment variable is not set, `mlflow.exe` is assumed to be located in the Python bin directory. However, this is the wrong location on my Windows 10 machine. 

So this is my workaround:
Create the environment variable `MLFLOW_BIN` and have it refer to `mlflow.exe`. Like this:
`Sys.setenv(MLFLOW_BIN = "C:/Users/willy/.conda/envs/r-mlflow-1.17.0/Scripts/mlflow")`

**Comment by FrieseWoudloper** [comment]
I think this problem is resolved in PR https://github.com/mlflow/mlflow/pull/3766. So I will close this issue.

**Comment by lorenzwalthert** [comment]
Seems you are right in your analysis. I am afraid #3766 won't get merged (soon) because it got too convoluted (with other changes), which means the build never passed and has accumulated too many merge conflicts. I think it would be a good thing to narrow the scope down and just fix the executable path in a small PR...

**Comment by lorenzwalthert** [comment]
In the meanwhile, set the executable via env variable manually: https://github.com/mlflow/mlflow/issues/3206#issuecomment-708421032

**Comment by mkspwr** [comment]
Thanks for getting to this point..but, after resolving this error..I am now stuck at this :

Error in wait_for(function() mlflow_rest("experiments", "list", client = client),  : 
  Operation failed after waiting for 10 seconds
