### ISSUE TITLE
[BUG] Inconsistent UI when using nested runs and the runs list is paginated

### ISSUE THREAD

**Issue by kbrose** [mlflow/mlflow#4528]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.8
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: n/a

### Describe the problem
If there are enough runs in the UI that they are paginated, then nested runs sometimes display incorrectly (runs which are nested appear as top-level runs). It seems like this happens when a child run is in the UI, but its parent run has not been loaded. Once "Load More" is clicked to ensure all runs appear in the UI, then the runs show up correctly nested.

I have a before/after clicking "Load More". Apologies for the black bar, but I didn't want to leak any information. The red rectangle shows runs that should all be nested under a single parent run, but the parent run hasn't been loaded so they all appear as top level runs.

![Screen Shot 2021-07-02 at 4 27 24 PM](https://user-images.githubusercontent.com/4053170/124330377-e4f51400-db52-11eb-8abb-2ebb683243d3.png)

And after clicking "Load More", all those runs from the red rectangle above now show up as only one line in the UI.

![Screen Shot 2021-07-02 at 4 27 37 PM](https://user-images.githubusercontent.com/4053170/124330392-ede5e580-db52-11eb-8bbd-8aa95d5174a3.png)

### Code to reproduce issue
N/A

### Other info / logs
N/A

### What component(s), interfaces, languages, and integrations does this bug affect?
Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by ankit-db** [comment]
@kbrose , just to confirm, is the version of MLflow you're using 1.8? Can you try upgrading? We have been working on an updated UX around this particular issue.

cc: @jimmyxu-db

**Comment by kbrose** [comment]
Correct, version 1.8 is what I'm using. I don't have unilateral authority to upgrade, we're using this deployment for pulling models in production. I can let you know if the problem persists after the next upgrade, though.

**Comment by jimmyxu-db** [comment]
Thanks for taking a look ankit! This was added as part of https://github.com/mlflow/mlflow/pull/3867/files#diff-8bd288f600bbae6050422b7830cb59d442203b13ff993c75fe64049e3bfd7d64R120

**Comment by ankit-db** [comment]
Great! @kbrose we're relatively confident that the fix for this is included as of MLflow 1.13.0, so closing out this issue for now. If upgrading does not work, please reopen the issue and we can look into it as well

**Comment by kbrose** [comment]
Sounds good, thanks.
