### ISSUE TITLE
Unable to run the sample example for MLFlow JAVA client

### ISSUE THREAD

**Issue by rahulpshah** [mlflow/mlflow#456]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Mac OSX 10.13.6
- **MLflow installed from (source or binary)**: 
    mlflow, version 0.6.0.dev0 - Installed from source
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 
      Python 3.6.5
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
     - `mvn package` in the src directory of the client of the java directory
     - `Start the MLFlow Tracking server` with MLFLOW_TRACKING_URI set.
     -   `java -cp target/mlflow-client-0.6.0.jar org.mlflow.tracking.samples.QuickStartDriver`
 - JAVA version
     - java version "1.8.0_181"
### Describe the  problem
Log4j.Logger class is not present in the uber-jar created by the mvn package as it excluded by the shade plugin. This can be resolved by including adding the log4j:log4j in uber-jar's artifactSet

### Source code / logs
Important Logs from mvn package:

```
[INFO] --- maven-shade-plugin:3.1.0:shade (default) @ mlflow-client ---
[INFO] Excluding log4j:log4j:jar:1.2.17 from the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.5.6 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.4.10 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.2 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.10 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:3.6.0 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java-util:jar:3.6.0 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:19.0 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.7 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.5 in the shaded jar.
[INFO] Including org.ini4j:ini4j:jar:0.5.4 in the shaded jar.
```

StackTrace from running the last command:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at org.mlflow.tracking.MlflowHttpCaller.<clinit>(MlflowHttpCaller.java:30)
	at org.mlflow.tracking.MlflowClient.<init>(MlflowClient.java:44)
	at org.mlflow.tracking.MlflowClient.<init>(MlflowClient.java:35)
	at org.mlflow.tracking.MlflowClient.<init>(MlflowClient.java:30)
	at org.mlflow.tracking.samples.QuickStartDriver.process(QuickStartDriver.java:24)
	at org.mlflow.tracking.samples.QuickStartDriver.main(QuickStartDriver.java:18)
```

**Comment by alkersan** [comment]
I think that java client library should not use `log4j` as a runtime dependency. Instead it should only depend on `slf4j-api`.

**Comment by tduquette** [comment]
you can work around this by downloading the missing jar: https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.25

then specifying it in your classpath at executiona

java -cp target/mlflow-client-0.9.1.jar:/path/to/slf4j-api-1.7.25.jar org.mlflow.tracking.samples.QuickStartDriver http://localhost:5000
