### ISSUE TITLE
[DOC-FIX] The link for release notes for 1.19.0 references 1.18.0

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#4562]
The link for 1.19.0 release is https://mlflow.org/news/2021/07/14/1.18.0-release/index.html.
Should be https://mlflow.org/news/2021/07/14/1.19.0-release/index.html.

**Comment by harupy** [comment]
@amesar Thanks for the catch, I'm working on fixing this!

**Comment by harupy** [comment]
@amesar The link has been fixed! Could you check it?
