### ISSUE TITLE
[FR] Use s3:// protocol instead of https:// protocol to upload Sagemaker model data to S3

### ISSUE THREAD

**Issue by jinnig** [mlflow/mlflow#4667]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Sagemaker by default uses s3:// protocol for the URL where model artifacts are stored in S3. However, MLflow currently uses https:// URL. I want to change how URL parsed in _upload_s3() and _delete_sagemaker_model() APIs from https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/__init__.py.

## Motivation
- What is the use case for this feature?
  Change the HTTPS S3 URL to the default s3:// protocol. So user can click it as a link to the s3 location within the AWS Console.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [x] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details
![sagemaker_model](https://user-images.githubusercontent.com/64722800/128455317-4787fbc1-cc2f-4d50-b09d-230a152504fc.png)
As shown in the above image, Sagemaker by default uses s3:// protocol for the URL where model artifacts are stored in S3. However, MLflow currently uses https:// URL as follows.
![https_s3_url](https://user-images.githubusercontent.com/64722800/128455542-77dc6ae0-4c78-49f6-aa5f-13ce391258a0.png)
I want to change how URL parsed in _upload_s3() and _delete_sagemaker_model() APIs from https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/__init__.py.

**Comment by dbczumar** [comment]
Hi @jinnig . Sounds good! Feel free to file a PR for this.

**Comment by jinnig** [comment]
Hey @dbczumar, this issue has been resolved in [4669](https://github.com/mlflow/mlflow/pull/4669/commits/fc6a452975ab3816ff99634a02deca4ad186cf87). Please feel free to close this issue. Thanks!

**Comment by dbczumar** [comment]
Sounds great! Thanks for your contribution @jinnig !
