### ISSUE TITLE
[BUG] Error loading runs preview (UI)

### ISSUE THREAD

**Issue by kelvins** [mlflow/mlflow#4727]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: `pip install`
- **MLflow version (run ``mlflow --version``)**: 1.19.0
- **Python version**: 3.8.0
- **npm version, if running the dev UI**: -
- **Exact command to reproduce**: -

### Describe the problem
The runs preview is not being loaded properly for a specific use case.

Supposing we have two experiments as follows:
- `experiment1`: has 150 runs.
- `experiment2`: has 5 runs.

When accessing the Mlflow server (UI) and clicking on the `experiment1` option, the first 100 runs are shown, then if we click on the `experiment2` option no runs are shown.

By inspecting the page (Network tab) we can see that the second request (`experiment2`) to the `/ajax-api/2.0/preview/mlflow/runs/search` endpoint is not returning any value.

When clicking on the `experiment1` option, it is performing a POST request to the endpoint with the following payload:

```json
{
    "experiment_ids":["1"],
    "filter":"",
    "run_view_type":"ACTIVE_ONLY",
    "max_results":100,
    "order_by":[],
    "page_token":null
}
```

Then if we click on the `experiment2`, it is performing a POST request with the following payload:

```json
{
    "experiment_ids":["2"],
    "filter":"",
    "run_view_type":"ACTIVE_ONLY",
    "max_results":100,
    "order_by":[],
    "page_token":"eyJvZmZzZXQiOiAxMDB9"
}
```

When decoding the `page_token` (`echo eyJvZmZzZXQiOiAxMDB9 | base64 --decode`) we can see it represents `{"offset": 100}` which is probably used for pagination purposes.

It looks like the `page_token` generated by `experiment1` pagination is being used for the `experiment2` request and it is returning an empty response since we just have 5 runs for `experiment2`.

**Note that when refreshing the `experiment2` page, the `page_token` is set to `null` and the runs are loaded properly.**

### Code to reproduce issue
- Create a virtual environment with Python 3.8.
- Install Mlflow: `pip install mlflow==1.19.0`
- Run the `mlflow server` locally.
- Create the experiments and runs using the following script:
```python
import mlflow

mlflow.set_experiment('experiment1')
for i in range(150):
    with mlflow.start_run():
        mlflow.log_param('x', i)

mlflow.set_experiment('experiment2')
for i in range(5):
    with mlflow.start_run():
        mlflow.log_param('y', i)
```
- Open the Mlflow server in a web browser: `http://127.0.0.1:5000`
- Click the `experiment1`: the first 100 runs should be loaded.
- Click the `experiment2`: no runs should be loaded:
![image](https://user-images.githubusercontent.com/1009397/130500375-81146364-5324-434a-ba08-5bd59b79f8ae.png)
- Refresh the page (F5), the runs now appears:
![image](https://user-images.githubusercontent.com/1009397/130500458-038c7448-68af-432d-8d91-f2ff31209f85.png)

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @kelvins, thanks for reporting this issue! I was able to reproduce the issue using the attached code.

**Comment by harupy** [comment]
@kelvins The issue has been fixed. If you want, you could download a wheel in the link below and install MLflow containing a patch for the issue:

https://github.com/mlflow/mlflow/suites/3577750930/artifacts/86012647
