### ISSUE TITLE
[FR] Use mamba for creating environments

### ISSUE THREAD

**Issue by giacomov** [mlflow/mlflow#4745]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

A following up PR will implement the following proposed modifications:

* allow for the use of a new environment variable, `MLFLOW_CONDA_CREATE_ENV_CMD`, that allows the user to specify an executable to be used for creating environments. If the user does not set it, `conda` will be used. If the user sets it, for example as `MLFLOW_CONDA_CREATE_ENV_CMD=mamba`, then `mamba` will be used (of course, the user will have to take care of installing `mamba` first).
* only one minor change is required, in the file `utils/conda.py`. Tests for this change will also be provided.

## Motivation
- What is the use case for this feature?

 [`mamba`](https://github.com/mamba-org/mamba) is a package manager compatible with Conda, but many times faster than conda when creating environments and installing packages. When using MLflow, creating the environment can be very time consuming, sometimes dominating the total runtime of an MLflow project. This feature allows to use `mamba` instead of `conda` to create the environments. 

It only requires the user to set the env variable `MLFLOW_CONDA_CREATE_ENV_CMD=mamba` (after having installed mamba, of course).

It also allows, for advanced users, to create a wrapper script or executable that runs only when creating environments. Just point `MLFLOW_CONDA_CREATE_ENV_CMD` to the wrapper.

- Why is this use case valuable to support for MLflow users in general?

It makes the execution of MLflow project and pipelines potentially much faster, by speeding up the environment creation step without requiring any change whatsoever to the MLflow project.

- Why is this use case valuable to support for your project(s) or organization?

We use MLflow extensively for pipelines, and sometimes the environment creation step is the most time-consuming part of executing a pipeline step. Using mamba speeds up some of our pipeline steps by up to a factor of 10x.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Currently it is possible to specify a custom installation of conda, but it is impossible to use `conda` for environment management (listing, for example) and `mamba` for creating the environments. It is not possible to use `mamba` in place of `conda` for everything because commands like `mamba activate` are not available.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by jinzhang21** [comment]
Thanks for raising the issue, Giacomo.

FYI the MLflow community is moving away from conda in favor of Pypi (pip), owing to Anaconda changed its terms of service. Going forward conda-associated development will be kept at minimal level.

That being said. Do you mind expanding a bit more on the section below?
"We use MLflow extensively for pipelines, and sometimes the environment creation step is the most time-consuming part of executing a pipeline step. Using mamba speeds up some of our pipeline steps by up to a factor of 10x."

I'm curious what your pipeline setup look like, and why replacing conda could result in 10x speedup. Could it imply that the training is so fast that using ML project is an over-kill?

**Comment by giacomov** [comment]
Thanks for the info. Is there a place where I can find more information
about the move to pypi? I have a lot of questions, for example: what are
the new terms of services that are problematic? Does the switch to pypi
mean all existing conda-based MLflow projects will be broken? Pypi contains
a very small subset of what is available in conda, for example, it doesn't
provide the CUDA toolkit and so on, how do we deal with that?

Regarding the 10x speedup, some pipeline steps are as simple as "download a
small file" or "fit a logistic regression on 50k rows", so the core
computation takes less than a second. However, the creation of the
environment takes up to a couple of minutes due to the slowness of conda.

Thanks for reviewing this, and let me know if you have any further
questions.

**Comment by jinzhang21** [comment]
Thanks for the quick reply, Giacomo.

The decision to move away from conda is partially related to Anaconda's change announced here: https://www.anaconda.com/blog/anaconda-commercial-edition-faq

MLflow will continue to support conda. You are free to use conda with either Anaconda managed channels or conda-forge (which has been made the default conda channel). Existing conda-based projects will continue to work as is.

Despite of the general direction of consolidating towards Pypi, I'm happy to review your PR and get it merged. Your use case is not unique. Many users could potentially benefit from this change. Thanks for taking the initiative!

**Comment by giacomov** [comment]
great, thanks!

**Comment by harupy** [comment]
Addressed by #4746
