### ISSUE TITLE
Metric history showing a bar plot with only one value while multiple values are logged

### ISSUE THREAD

**Issue by programistagd** [mlflow/mlflow#478]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
I modified examples/sklearn_elasticnet_wine/train.ipynb, adding
```
for i in range(0, 5):
            time.sleep(1)
            mlflow.log_metric("rmse", rmse + i/100.)
            mlflow.log_metric("r2", r2 + i/100.)
            mlflow.log_metric("mae", mae + i/100.)
            mlflow.log_metric("i", i)
```
in place of old metrics to see how history behaves.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 	Ubuntu 18.04.1 LTS
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.6.0
- **Python version**: 3.6
- **npm version (if running the dev UI): n/a
- **Exact command to reproduce**: open the notebook, make stated changes and run all cells

### Describe the problem
The metrics graph should show history of the metrics, but only one (latest) value is shown.

It looks like it may be related to #117, but that might not necessarily be true.

**Comment by programistagd** [comment]
I've tried debugging the issue and after installing the development version, I found out that sometimes the metrics property (MetricView.js) seems to have only one value.

When I refresh the page multiple times and use the navigation (it doesn't seem very deterministic), sometimes the full chart shows up (so the property has all needed values).

Most of the time there's only one value displayed - the last one.

This proves it probably doesn't have much to do with #117, but rather there seems to be some issue with sending / loading the metrics array to the client.

To be sure, I've checked the corresponding metrics/mae file and it's content is following:
```
1536765376 0.6278761410160691
1536765377 0.6378761410160692
1536765378 0.6478761410160692
1536765379 0.6578761410160692
1536765380 0.6678761410160692
```

So the metrics have surely been logged.

**Comment by smurching** [comment]
Thanks for investigating @programistagd, I've also hit this while working on #476. Will investigate what exactly is happening.

**Comment by smurching** [comment]
I think I've found the issue - [MetricReducer](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/reducers/MetricReducer.js)'s methods set metric data both in response to successful GetRun and GetMetricHistory REST API requests. GetRun returns just a single value for each unique metric in a run, while GetMetricHistory returns the entire history of the metric data. The [MetricPage](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/components/MetricPage.js#L28) component fires both GetRun and GetMetricHistory actions to obtain data for the MetricView component. The non-deterministic behavior comes from the fact that the available metrics are set based on whichever of {GetRun, GetMetricHistory} finish last. I'll look more into a specific fix tomorrow, just wanted to write out what I'd found.

**Comment by ignaczgerg** [comment]
In my case, the issue was that the metrics were not logged with a "step".
