### ISSUE TITLE
Can't install mlflow in amazon sagemaker notebook

### ISSUE THREAD

**Issue by schipiga** [mlflow/mlflow#482]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Linux ip-172-16-44-178 4.9.119-44.140.amzn1.x86_64 #1 SMP Fri Aug 10 19:17:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- **MLflow installed from (source or binary)**:  `pip install --no-cache-dir mlflow`
- **MLflow version (run ``mlflow --version``)**: `mlflow v0.6.0`
- **Python version**: `Python 3.6.5 :: Anaconda custom (64-bit)`

### Describe the problem

I have a problem to install `mlflow` in sagemaker notebook.
I use sagemaker lifecycle configuration with next script on start:

```
#!/bin/bash

set -e # exit immediately on error
set -x # print command before execution

sudo su ec2-user

sudo ln -s /usr/libexec/gcc/x86_64-amazon-linux/4.8.5/cc1plus /usr/bin

source /home/ec2-user/anaconda3/bin/activate python3

pip install --upgrade pip
pip install --no-cache-dir xgboost
pip install --no-cache-dir graphviz
pip install --no-cache-dir shap
pip install --no-cache-dir mlflow
pip install --no-cache-dir lightgbm
pip install --no-cache-dir catboost

source /home/ec2-user/anaconda3/bin/deactivate
```

And very often (~50%) it failes with error:

```
Requirement already satisfied: docutils>=0.10 in ./anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<1.11.0,>=1.10.79->boto3->mlflow) (0.14)
Requirement already satisfied: nose in ./anaconda3/envs/python3/lib/python3.6/site-packages (from nose-exclude>=0.5.0->mleap>=0.8.1->mlflow) (1.3.7)
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker-1.9.0.dist-info/METADATA'
```

Looks like it tries to find `sagmaker v1.9.0`, but as I see in sagemaker terminal (when it's launched successfully) there is `sagemaker v1.10.0` only:

```
sh-4.2$ pwd
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages
sh-4.2$ cd sagemaker
sagemaker/                         sagemaker_pyspark/
sagemaker-1.10.0.dist-info/        sagemaker_pyspark-1.1.4.dist-info/
sh-4.2$ cd sagemaker
```

Could you please to help to find workaround?

**Comment by mparkhe** [comment]
@schipiga is this still an issue. `mlflow` does not install sagemaker.
