### ISSUE TITLE
[FR] Sort runs table on multiple columns

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#4821]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We're seeking help with the implementation of roadmap items tagged with the `help wanted` label.

For requirements clarifications and implementation questions, or to request a PR review, please tag @sunishsheth2009 in your communications related to this issue.

## Proposal Summary

Introduce support for sorting the Runs table in the MLflow Experiment UI by multiple columns at once. Users should be able to select and deselect columns for sorting and sorting them in both ascending and descending order.

## Motivation
- What is the use case for this feature? Multiple metrics and parameters are often important to determining a model's configuration and performance characteristics. It can be difficult to identify optimal run(s) via the experiment UI when runs table sorting is only allowed on a single column.
- Why is this use case valuable to support for MLflow users in general? Many MLflow users leverage the experiment UI / runs table to identify good candidate runs.
- Why is this use case valuable to support for your project(s) or organization? Many Databricks users leverage the experiment UI / runs table to identify good candidate runs.
- Why is it currently difficult to achieve this use case? Users must currently use the MLflow API to sort runs on multiple metrics, parameters, etc simultaneously; this is not offered in the UI.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by coder-freestyle** [comment]
@dbczumar I feel that this issue is still open and hasn't been picked up for development. I am interested in working on this.

**Comment by coder-freestyle** [comment]
@dbczumar Do we need to show all the selected filters in the dropdown? (Attached is a screenshot for visual reference). Currently, since sorting is done on a single parameter, the selected orderByKey is shown to the user. 

<img width="661" alt="Screenshot 2021-11-09 at 6 40 29 PM" src="https://user-images.githubusercontent.com/60594457/140929992-569a22bf-e99f-4658-a477-48b9e0940a02.png">

Let me know your thoughts.

**Comment by dbczumar** [comment]
Hi @coder-freestyle , apologies for the delay here. It would be helpful to show all the selected filters in the dropdown.

**Comment by dbczumar** [comment]
Hi @coder-freestyle , did you get a chance to take a look at this?

**Comment by r3stl355** [comment]
Hey, looks like nothing is happening here, can I pick it up?

**Comment by dbczumar** [comment]
Upon further investigation, we've determined that this capability isn't quite what users want. Multi-column sorting is only useful in the case of breaking ties, and most models are unlikely to commonly produce identical values for one or more metrics.
