### ISSUE TITLE
[FR] Display default column sorting order in runs table in experiment UI

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#4825]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary

By default, the runs table in the MLflow experiment UI is sorted by the `startTime` in descending order. This default sorting order is not made visible in the runs table column headers or in the column sorting dropdown. For clarity, it should be displayed by default.

I.e. the default view of the experiment runs table and sorting dropdown should look like:

<img width="1236" alt="Screen Shot 2021-09-17 at 12 16 50 PM" src="https://user-images.githubusercontent.com/39497902/133842150-49372082-cd48-4566-8d21-f4389d713d23.png">

Instead of:

<img width="1232" alt="Screen Shot 2021-09-17 at 12 17 51 PM" src="https://user-images.githubusercontent.com/39497902/133842244-74f3809c-c74a-4f11-9054-7c15133d0f3d.png">

## Motivation
- What is the use case for this feature? When users change the column being sorted on, it is currently difficult for them to revert to the default sorting order because they don't know which column is sorted by default.
- Why is this use case valuable to support for MLflow users in general? ^
- Why is this use case valuable to support for your project(s) or organization? ^
- Why is it currently difficult to achieve this use case? Users must currently know / infer that StartTime is the default column used for sorting.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by marijncv** [comment]
Hey @dbczumar, another small contribution in https://github.com/mlflow/mlflow/pull/4847. Curious what you think about using `state` the management of the orderByKey instead of `props`. The React framework is still quite new to me and was not able to find a way to use `props` and get it working
