### ISSUE TITLE
[FR] Add a duration column to the runs table in the experiment UI

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#4826]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We're seeking help with the implementation of roadmap items tagged with the `help wanted` label.

For requirements clarifications and implementation questions, or to request a PR review, please tag @dbczumar in your communications related to this issue.

## Proposal Summary

Introduce a run duration column to the Runs table in the MLflow Experiment UI. For simplicity, sorting capabilities are not initially required on the column and can be added in the future. If a run has not yet completed, duration information should be left empty.

## Motivation
- What is the use case for this feature? Run duration is often a meaningful heuristic in ML training, serving as a proxy for the quality of a model or illuminating issues in the training process (e.g. poor convergence).
- Why is this use case valuable to support for MLflow users in general? ^
- Why is this use case valuable to support for your project(s) or organization? ^
- Why is it currently difficult to achieve this use case? MLflow currently reports duration on the Run page for an individual run, but it's difficult for users to view / compare run duration.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by marijncv** [comment]
Hey @dbczumar,

I created PR #4840 to close this issue. Any thoughts of the location of the column in relation to the existing standard columns? I've now placed it to the right of the "Start Time" column.

**Comment by dbczumar** [comment]
@marijncv Thank you for your contribution! I've approved the PR - https://github.com/mlflow/mlflow/pull/4840. I think the placement of the column to the right of `Start Time` makes perfect sense!
