### ISSUE TITLE
[DOC-FIX] Doc missing for REST API POST 2.0/mlflow/artifacts/credentials-for-read

### ISSUE THREAD

**Issue by maitre-matt** [mlflow/mlflow#4839]
### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://www.mlflow.org/docs/latest/rest-api.html

### Description of proposal (what needs changing):

The Python MLFlow SDK relies on the REST API below to retrieve credentials to download artifacts, which does not appear to be documented. It will be helpful to add it for clients that are not in a language natively supported by MLFlow (e.g. .NET).

```
POST https://adb-<snip>.0.azuredatabricks.net/api/2.0/mlflow/artifacts/credentials-for-read
{
    'headers': {'User-Agent': 'mlflow-python-client/1.20.2', 'Authorization': 'Bearer <snip>'},
    'verify': True,
    'timeout': 120,
    'json': {'run_id': '<snip>', 'path': ['model/MLmodel', 'model/conda.yaml', 'model/model.pkl', 'model/requirements.txt']}
}

{
	"credentials": {
		"run_id": "<snip>",
		"path": "model/MLmodel",
		"signed_uri": "https://<snip>.blob.core.windows.net/jobs/<snip>/mlflow-tracking/<snip>/<snip>/artifacts/model/MLmodel?sig=<snip>&api-version=2019-02-02&se=2021-09-22T02%3A07%3A16Z&sv=2019-02-02&spr=https&sp=r&sr=b",
		"type": "AZURE_SAS_URI"
	},
	"credential_infos": [
		{
			"run_id": "<snip>",
			"path": "model/MLmodel",
			"signed_uri": "https://<snip>.blob.core.windows.net/jobs/<snip>/mlflow-tracking/<snip>/<snip>/artifacts/model/MLmodel?sig=<snip>&api-version=2019-02-02&se=2021-09-22T02%3A07%3A16Z&sv=2019-02-02&spr=https&sp=r&sr=b",
			"type": "AZURE_SAS_URI"
		},
		{
			"run_id": "<snip>",
			"path": "model/conda.yaml",
			"signed_uri": "https://<snip>.blob.core.windows.net/jobs/<snip>/mlflow-tracking/<snip>/<snip>/artifacts/model/conda.yaml?sig=<snip>&api-version=2019-02-02&se=2021-09-22T02%3A07%3A16Z&sv=2019-02-02&spr=https&sp=r&sr=b",
			"type": "AZURE_SAS_URI"
		},
		{
			"run_id": "<snip>",
			"path": "model/model.pkl",
			"signed_uri": "https://<snip>.blob.core.windows.net/jobs/<snip>/mlflow-tracking/<snip>/<snip>/artifacts/model/model.pkl?sig=<snip>&api-version=2019-02-02&se=2021-09-22T02%3A07%3A16Z&sv=2019-02-02&spr=https&sp=r&sr=b",
			"type": "AZURE_SAS_URI"
		},
		{
			"run_id": "<snip>",
			"path": "model/requirements.txt",
			"signed_uri": "https://<snip>.blob.core.windows.net/jobs/<snip>/mlflow-tracking/<snip>/<snip>/artifacts/model/requirements.txt?sig=<snip>&api-version=2019-02-02&se=2021-09-22T02%3A07%3A16Z&sv=2019-02-02&spr=https&sp=r&sr=b",
			"type": "AZURE_SAS_URI"
		}
	]
}
```

**Comment by dbczumar** [comment]
Hi @maitre-matt. This API is unique to Databricks and is not exposed by MLflow Tracking servers outside of Databricks. We can certainly work with our Databricks Docs team to provide documentation. Please let me know if this is still of interest to your group given the limited surface area to Databricks / Azure Databricks.

**Comment by maitre-matt** [comment]
Thanks for the update! Doc update would be very helpful, even if limited to Databricks Docs. This will avoid our service taking a dependency on an undocumented API. Not sure if there is a contribution model on Databricks Docs, but I would be happy to contribute a PR there.

More long term there would be value in standardizing that API in MLFlow. Azure ML also implemented a similar custom API. It sounded like a workaround to unblock their scenarios and there was interest in a more standard solution. I could open a Feature Request for tracking.

**Comment by dbczumar** [comment]
@maitre-matt Awesome! For the docs improvement, I'll file an internal ticket and work with the docs team to get this done.

Regarding a standardized API, there was some discussion around a standard interface for presigned URLs here - https://github.com/mlflow/mlflow/issues/629#issuecomment-845839644. I think this is a good piece of functionality to support, and it can likely be added as a capability to the `mlflow-artifacts` API being introduced for streaming uploads by @harupy via https://github.com/mlflow/mlflow/pull/4946. We would definitely welcome contributions in this area after working with you to align on a design.
