### ISSUE TITLE
Large JSON artifact takes a long time to load and not kept in memory

### ISSUE THREAD

**Issue by dtpryce** [mlflow/mlflow#4865]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
We are running the MLflow server on K8s using S3 and RDS. Successfully logging an artifact which is a 2MB JSON file, however when trying to view this file within the UI it takes a long time to load (minutes) and Firefox even complains it is slowing the browser down. 

Then if a user clicks off and tries to view once again the loading restarts. This is not a great UX, so the enhancements I would suggest:

* Try to load these larger files a different / faster way
* If that's not entirely possible change the UI to tell the user to wait a little longer or a loading bar on first load and then ... 
* Implement some form of caching to enable faster second load

## Motivation
- What is the use case for this feature? Large file viewing in the artifact screens
- Why is this use case valuable to support for MLflow users in general? Some artifacts are not necessarily small and would be useful for debugging experiments and their runs
- Why is this use case valuable to support for your project(s) or organization? We use various pieces of metadata and extra artifacts in our ensemble or pipelines which are useful to been seen alongside our metrics
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient) as explained above it's mostly around latency and UX not quite being there for this use case

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details
I am no frontend developer but imagine it's a UI update for the loading bar and then leveraging in browser caches potentially.

**Comment by dtpryce** [comment]
I think this might be solved by #5359 will test this week!

**Comment by dtpryce** [comment]
> I think this might be solved by #5359 will test this week!

Tested and much better in newest versions so will close here

**Comment by hagerf** [comment]
Hi, I was wondering if this bug has reappeared, as we're using MLflow 1.28.0 and opening a json artifact in the UI that is just barely bigger than 1 MB results in the browsers freezing. Tested on Safari and MS Edge. I think this issue is still present and this bug opened again IMHO.

**Comment by YoshihikoFuruhashi** [comment]
I have the same problem with MLFlow 2.0.1.
Is the json preview heavy?
