### ISSUE TITLE
Error while using UI for tracking results

### ISSUE THREAD

**Issue by rtmatx** [mlflow/mlflow#49]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.13.3	
- **MLflow installed from (source or binary)**: using pip
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.1.0	
- **Python version**: 3.6
- **npm version (if running the dev UI): 
- **Exact command to reproduce**:

### Describe the problem
Hi, I receive the following error while opening the terminal for tracking results	

### Source code / logs

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by aarondav** [comment]
What URL were you accessing?

**Comment by Genie-Liu** [comment]
I'm wondering if you should use pip3 install mlflow? After using pip install mlflow, I got the same problem. The server looks working good, but I can't connect to it.

**Comment by rtmatx** [comment]
I was using http://localhost:5000

**Comment by mateiz** [comment]
Can you also do `which mlflow`? This would normally happen if you've tried to build it from source and have that ahead of the pip-installed one on your path. Or it may be that your `pip` is from a different Python installation than your `python`.
