### ISSUE TITLE
Indicating the origin of the git repository

### ISSUE THREAD

**Issue by drorata** [mlflow/mlflow#491]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.60
- **Python version**: 3.6

### Describe the problem
In the `run` view we can see the git commit, but it might be not enough and the remote (location of the repository) is needed as well. Consider a use case where a single MLflow server is shared between a team. Each team member working tracks results of run in an experiment. However, the knowledge where the code actually resides is lost.

Therefore, it might be worthy to add a field showing the value of the remote repo.

**Comment by mateiz** [comment]
That makes a lot of sense. I think the solution is to turn this into a tag -- actually we'd like to turn a lot of the standalone metadata fields that exist now into tags too to make them more consistent.

**Comment by drorata** [comment]
What do you mean by "tag"?

**Comment by whiletruelearn** [comment]
@mateiz @drorata I am interested in picking this up.  What all information do we need to capture, I can think of `branch name` and `commit author`

**Comment by adrian555** [comment]
FYI the `branch name` is already a tag through this PR #469.

**Comment by whiletruelearn** [comment]
@adrian555 Thanks for pointing out, will add `remote url` alone then.
