### ISSUE TITLE
[FR] Add custom plots (images) to run

### ISSUE THREAD

**Issue by RoelantStegmann** [mlflow/mlflow#4982]
Sometimes I would like to add a custom plot to a run, and ideally view these plots within MLflow. As far as I know, this cannot be done at the moment. 

## Willingness to contribute

I cannot contribute this feature at this time.

## Proposal Summary

Have a syntax that allows you to upload local images to the MLflow server, and allow you to inspect them in the MLflow interface. 

`mlflow.add_image("image-name", "some-image.png")`

For example

`mlflow.add_image("embedding visualisation", "epoch-11.png")`

At the moment I am uploading custom files to S3 and analysing them there, but it's a lot of switching between tabs.

### What component(s), interfaces, languages, and integrations does this feature affect?
- [ X] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by guigautier** [comment]
Good idea 
Possible to add some plot images from numpy for example.

**Comment by AveshCSingh** [comment]
Would it be sufficient to log the image as an artifact? eg
```
mlflow.log_artifact("/tmp/clippy.png", "img")
```
will result in:
![Screen Shot 2021-11-05 at 10 00 18 AM](https://user-images.githubusercontent.com/1208791/140549514-e1a05524-2736-4d06-963f-31879896527c.png)

**Comment by BenWilson2** [comment]
@RoelantStegmann thank you for the inquiry. Hopefully image storing as an artifact works well for you. Feel free to reopen this Issue if you would like to discuss more.
