### ISSUE TITLE
Windows displays the error: Oops! Something went wrong. If this error persists, please report an issue to our Github.

### ISSUE THREAD

**Issue by abhishekms1047** [mlflow/mlflow#50]
### System information
- OS Platform and Distribution :Windows 10
- **MLflow installed from (source or binary)**: PIP installed in terminal-pip install mlflow
- **MLflow version : Alpha
- **Python version**: 3.6.5

### Describe the problem
Whenever I try to view the artifact/MLmodel and model.pkl  in UI ,"Oops! Something went wrong. If this error persists, please report an issue to our Github" with Niagara picture on the screen shows up

### Source code / logs
location where the resources reside:
C:\Users\myname\mlruns\0\3419ce0a40154cd0a378fd1b5d69d241\artifacts\model

full path of model as visible in UI -
/Users/myname/mlruns\0\3419ce0a40154cd0a378fd1b5d69d241\artifacts/model

**Comment by Genie-Liu** [comment]
Have the same problem. My OS platform is also windows10.

**Comment by tomyc** [comment]
I have the same problem during running the example "wine quality" on mlflow v. 0.1.0, MS Windows 10, 1803.

**Comment by Genie-Liu** [comment]
I think the reason is the different path seperator between linux and windows.

**Comment by aarondav** [comment]
This should be resolved, as we added Windows support!
