### ISSUE TITLE
Feature request: Support for SpaCy models

### ISSUE THREAD

**Issue by suzil** [mlflow/mlflow#500]
It would be nice if there was a `mlflow.spacy` module for SpaCy models. [Here is an example usage of training a SpaCy text classification model.](https://spacy.io/usage/training#textcat)

The two relevant functions for creating the module would be `nlp = spacy.load(model_path)` and `nlp.to_disk(output_path)`. To make a prediction, you would run something like `nlp("Here is some example text to classify").cats['CATEGORY']`.

I think this should be easy to implement? The part that I'm not so sure about is how to write the prediction part.

**Comment by juntai-zheng** [comment]
SpaCy support has been added in! Closing this issue now.
