### ISSUE TITLE
Clicking same code tab more than once closes all tabs

### ISSUE THREAD

**Issue by stbof** [mlflow/mlflow#513]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.6
- **MLflow installed from (source or binary)**:  source
- **MLflow version (run ``mlflow --version``)**: 0.6.0
- **Python version**: Python 3.6.5
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

In the tutorial page, click any Python or R code tab more than once. All the content in the code tab containers disappears. Since all the content in the tutorial was put inside these containers, **all the** content disappears.

![codetabs2](https://user-images.githubusercontent.com/20482960/45701850-209acc80-bb25-11e8-9baf-e573bc05bfd7.png)

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

The tutorial is using code tabs to distinguish Python and R versions of each example. There are three problems:

- If you click the Python or R code tab more than once, everything inside the code tab container disappears.
-  The “tabbed” content isn't visually indicated, so user can't see what content is code-specific and what isn’t.
- All the tutorial content was put in the code tab container, not just the code. The narrative text that is not language specific was duplicated, which is less maintainable. In addition, because of the bug described in the previous bullet, when you click the same code tab twice, there is no content displaying on the page. The code tab container should should just contain code, not all the narrative content describing the code. 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by aarondav** [comment]
Fixed in #527.
