### ISSUE TITLE
[SETUP-BUG]

### ISSUE THREAD

**Issue by Neethugkp** [mlflow/mlflow#5146]
I am trying to configure MSSQL db as the backend uri

 Dockerfile is as below:-

FROM python:3.7-slim-buster
ARG BUCKET=bucketname
ARG ACCESS_KEY=key
ARG SECRET_ACCESS_KEY=key
ARG MSSQL_DATABASE=mlflowtest1

RUN apt-get update \
   && apt-get install gcc -y \
 && apt-get install unixodbc -y \
 && apt-get install unixodbc-dev -y \
 && apt-get install --reinstall build-essential -y

 
RUN mkdir -p /mlflow/ \
  && pip install  mlflow \
    boto3 \
    mlflow[sqlserver] \
    pyodbc 

RUN chmod -R 777 /mlflow/

EXPOSE 5000

ENV BACKEND_URI mssql+pyodbc://usr:pass@ip:port/DBMLFlow
ENV ARTIFACT_ROOT s3://bucket
ENV MLFLOW_S3_ENDPOINT_URL https://endpointurl
ENV AWS_ACCESS_KEY_ID $ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY $SECRET_ACCESS_KEY
ENV AWS_CA_BUNDLE /mlflow/cacert.pem

CMD mlflow server \
  --backend-store-uri "${BACKEND_URI}" \
  --default-artifact-root "${ARTIFACT_ROOT}" \
  --host 0.0.0.0

### Describe the problem
Error in connecting to db
2021/12/06 09:38:37 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/14/rvf5)

could you please help me to figure out the issue

**Comment by alexsee** [comment]
It doesn't look like a bug, you may be missing the `mssql-odbc` driver. (from https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)

**Comment by Neethugkp** [comment]
@alexsee, Thank you for your reply. I was able to solve the issues

**Comment by ZYWNB666** [comment]
Seek Assist

I plan to use mysql as the back-end database

This is my configuration

```yaml

mysql:

# -- Specifies if you want to use mysql backend storage

enabled: true

# -- MySQL host address. e.g. your Amazon RDS for MySQL

host: "mysql-staging-mysql.mysql-staging.svc" # required

# -- MySQL service port

port: 3306 # required

# -- mlflow database name created before in the mysql instance

database: "mlflow" # required

# -- mysql database user name which can access to mlflow database

user: "root" # required

# -- mysql database user password which can access to mlflow database

password: "**********" # required

# -- mysql database connection driver. e.g.: "pymysql"

driver: "pymysql"

` ` `



The following is the error, is there a kind person can help me solve this problem

```bash

WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.

(pymysql. Err. OperationalError) (1045, "Access denied for user 'root' @ '10.244.4.226' (using password: YES)")

(Background on this error at: https://sqlalche.me/e/20/e3q8)

The Operation will be retried in 6.3 seconds

` ` `
