### ISSUE TITLE
[BUG] Cannot set MFLOW_TRACKING_URI environment variable

### ISSUE THREAD

**Issue by pelekhs** [mlflow/mlflow#5150]
**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (Occurs both in Windows 11 and Ubuntu 20.04)**:
- **MLflow installed ffrom (pip)**:
- **MLflow version (1.22.0)**:
- **Python version (3.9.6)**:
- **Exact command to reproduce (MLFLOW_TRACKING_URI = os.environ.get('MLFLOW_TRACKING_URI'))**:

### Describe the problem
Let's suppose that we work inside a python virtual environment with mlflow installed. A remote MLflow server for tracking is defined inside a .venv file as follows:
```
os.environ["MLFLOW_TRACKING_URI"]= <my_remote_ip>
```
For some reason, during runtime the command will fail to update the MLFLOW_TRACKING_URI environment variable command contrary to the rest of environment variables. Therefore, the tracking server will be arbitrarily set to the default value, namely localhost:5000.

### Code to reproduce issue
With the above .env file present in the current directory and MLflow and python-dotenv installed in the python virtual environment, run the following code:
```
from dotenv import load_dotenv
load_dotenv()
MLFLOW_TRACKING_URI = os.environ.get('MLFLOW_TRACKING_URI')
print(MLFLOW_TRACKING_URI)
```

### Other info / logs
Nope

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by SeguinBe** [comment]
This does not seem to be related to mlflow, no? It's just that your dotenv setting does not set the environment variable properly?

**Comment by pelekhs** [comment]
I 've thought about that and maybe you are right. But i wanted to mention it as this specific environment variable is the only one that cannot be set by dotenv. Other variables, such as for example MLFLOW_S3_ENDPOINT_URL or AWS_ACCESS_ID etc. are normally set from within the .env file. And that is the second project that I experience this problem. What do you think?

**Comment by dbczumar** [comment]
@pelekhs This appears to be an issue with `python-dotenv`, rather than MLflow. Accordingly, I'm going to go ahead and close it out. Note that, within Python, you can use `os.environ` to set the desired environment variable(s) and / or using `mlflow.set_tracking_uri()` to set the tracking URI. Thank you for using MLflow!
