### ISSUE TITLE
code tabs distort Copy button 

### ISSUE THREAD

**Issue by stbof** [mlflow/mlflow#533]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem

The new code tab code distorts the look of the Copy button at the far right of a code block

Before tabs:
![copy1](https://user-images.githubusercontent.com/20482960/45849832-6bb10d00-bce8-11e8-9a24-f1583bdcf846.png)

After tabs:

![copy2](https://user-images.githubusercontent.com/20482960/45849834-6bb10d00-bce8-11e8-9991-5bd461c521e8.png)

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by javierluraschi** [comment]
@aarondav I can take a look at this one today or tomorrow, probably related to the R doc changes.

**Comment by aarondav** [comment]
Fix has been merged.
