### ISSUE TITLE
[FR] Parallelize ModelsArtifactRepository.download_artifacts() file access

### ISSUE THREAD

**Issue by tdiepenbrock-databricks** [mlflow/mlflow#5338]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Parallelize the download of artifact files from ModelsArtifactRepository.

## Motivation
- What is the use case for this feature?

ModelsArtifactRepository.download_artifacts() currently access files in a single-threaded way.  For models with only a few artifacts, this is ok, however there are models out there with a great number of files.  This causes the initial download of the model to take much longer than it ideally should.

- Why is this use case valuable to support for MLflow users in general?

Faster download times for large models.

- Why is this use case valuable to support for your project(s) or organization?

If our customer can download their large models faster, it will allow them to train/develop models faster and distribute them to a wider user base.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

The existing MLFlow implementation currently doesn't parallelize these operations, causing the file I/O to become a bottleneck.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors

Interfaces

Languages 

Integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dbczumar** [comment]
Closing now that #5359 is merged :)
