### ISSUE TITLE
Error in MLFlow Tracking docs

### ISSUE THREAD

**Issue by GCBallesteros** [mlflow/mlflow#536]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
No
- **MLflow version (run ``mlflow --version``)**:
0.6.0

### Describe the problem
The docs at https://www.mlflow.org/docs/latest/tracking.html#sftp-server say that one can connect to a SFTP server by hardcoding the password into the artifact store location as `sftp://pass:user@host/` when it should actually be in the `sftp://user:pass@host/` format.

**Comment by smurching** [comment]
Thanks for the catch, would you be interested in making a PR? The relevant source file is https://github.com/mlflow/mlflow/blob/master/docs/source/tracking.rst

**Comment by GCBallesteros** [comment]
Sure, that is a quick fix. In what branch should I introduce the change?

**Comment by smurching** [comment]
Great! I'd open a PR against the master branch of MLflow (you can push the change to a branch on your fork of MLflow, then open the PR as described [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)).
