### ISSUE TITLE
Feature: mlflow tracking with automated machine learning libraries

### ISSUE THREAD

**Issue by ratchetwrench** [mlflow/mlflow#537]
### System information
None.

### Describe the problem
When using automated machine learning engines, how would one integrate mlflow tracking? I use libraries such as TPOT, Auto-Sklearn, Auto-Keras. They are more black-box than I would suspect being able to utilize the mflow tracking. Knowing a lot of persons are moving toward these automated ML techniques.

mlflow models [built-in flavors](https://www.mlflow.org/docs/latest/models.html#built-in-model-flavors) has support for sklearn and keras already, so whatever is output by auto-ml techniques should conform to a deployable standard still.

### Source code / logs
None.

**Comment by sangramga** [comment]
@ratchetwrench @sonnehansen There have been fruitful changes in Mlflow 0.8.0 - to integrate hyper parameter optimization flows. Check [https://github.com/mlflow/mlflow/issues/628#issuecomment-439916277](https://github.com/mlflow/mlflow/issues/628#issuecomment-439916277)

**Comment by ankitmathur-db** [comment]
We recently released autologging with Tensorflow and Keras! If you try using these autoML libraries with the autologging, do you get results that look better? 

We also released a parallel coordinate plot that should make hyperparameter tuning a little easier to do in these frameworks as well. 

If there's a specific feature request, we'd love to hear it and engage with auto ML.
