### ISSUE TITLE
Scale Scatterplots for Run Comparisons

### ISSUE THREAD

**Issue by m-dinardo** [mlflow/mlflow#538]
I like the scatterplot to compare runs, it's a great feature. Currently it scales based on `(0, max)` and I would suggest the plot should scale based on `(min, max)`. I think people are more likely to care about visualizing the distances between the observations rather than the distances of the observations to 0, which is what it currently visualizes.

**Comment by adima** [comment]
I totally support this request, this is a major issue for me as well! It might also be useful to control the scale of the plot like in tensorboard. Without proper scale scatter plots are pretty much useless unless your metric happens to be centered around 0.
