### ISSUE TITLE
Experiments UI showing "Oops! Something went wrong"

### ISSUE THREAD

**Issue by adiwijaya** [mlflow/mlflow#541]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform LINUX Centos
- **MLflow installed from pip
- **MLflow version (run ``mlflow --version``)**: 0.6.0
- **Python version**:  3.6.4 anaconda
- **Exact command to reproduce**: Click date on Web UI, on one of listed built model

### Describe the problem
I'm following this tutorial https://docs.databricks.com/_static/notebooks/mlflow/mlflow-quick-start-notebook.html

Everything is working, just when I open tried to open the detail view of my model.
It shows me  "Oops! Something went wrong" Page with waterfall picture.

**Comment by CloudChaoszero** [comment]
Hey! Just a random person, but by any chance, did you:

1. Run the ```mlflow ui``` command, and let it stay running? (Do not ```Ctrl +C```)
2. Run the ``` mlflow ui ``` command, and not in some parent level directory respective of your file(s)?

**Comment by adiwijaya** [comment]
Hi random person!

Spot on. my case fall to number 2.
Thank you!
 
Solved
