### ISSUE TITLE
[DOC-FIX] Keras vs TensorFlow autologging confusion

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#5441]
https://www.mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores

Very confusing that Keras autologging is handled by mlflow.tensorflow.autolog() and not mlflow.keras.autolog(). So what is the purpose of mlflow.keras.autolog? In fact, why have both since Keras now only runs on TensorFlow.

```
Note that autologging for tf.keras is handled by [mlflow.tensorflow.autolog()](https://www.mlflow.org/docs/latest/python_api/mlflow.tensorflow.html#mlflow.tensorflow.autolog), not [mlflow.keras.autolog()](https://www.mlflow.org/docs/latest/python_api/mlflow.keras.html#mlflow.keras.autolog).
```

**Comment by dbczumar** [comment]
We'll be removing support for `mlflow.keras.autolog()` shortly.
