### ISSUE TITLE
MLflow remote Tracking server not receiving information

### ISSUE THREAD

**Issue by dudgnskim** [mlflow/mlflow#545]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
I am experimenting with MLflow tracking server with very simple examples.
- Node A: where I write codes and run / Node B: where mlflow server is running
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Node A: Ubuntu 18.04 / Node B: CentOS 6
- **MLflow installed from (source or binary)**:  using pip
- **MLflow version (run ``mlflow --version``)**: both 0.6.0
- **Python version**: Node A: 3.6 / Node B: 2.7
- **npm version (if running the dev UI): Node A: not installed / Node B: 3.10.10

- **Exact command to reproduce**:
Node A:
```
import mlflow
from mlflow.tracking import set_tracking_uri as uri
uri('http://x.x.x.x:5000')

with mlflow.start_run():
    mlflow.log_param('a', 1)
    mlflow.log_param('b', 2)
```

**Tracking Server command**
Node B:
`mlflow server --file-store /file/store/location --default-artifact-root /default/artifact/root --host x.x.x.x`

### Describe the problem
Above simple code should not produce any error. However, when I run the code from node A, it keeps running for like 2 minutes, and shows the error message saying:

```
API request to http://x.x.x.x:5000/api/2.0/preview/mlflow/runs/create failed with code 504 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Notification: Gateway Timeout</title>
<style type="text/css">
<!--
body {
    margin-left: 2%;
    margin-right: 2%;
}
p {
    font-family: verdana, Arial, Helvetica, sans-serif;
    font-size: 12px;
    top: 0px;
    margin-top: 6px;
    margin-bottom: 6px;
}
td {
    font-family: verdana, Arial, Helvetica, sans-serif;
    font-size: 12px;
    top: 0px;
}
.code {
    font-family: courier;
    font-size: 12px;
    top: 0px;
}
h1 {
    font-family: verdana, Arial, Helvetica, sans-serif;
    font-size: 16px;
    margin-top: 24px;
    margin-bottom: 8px;
}
hr {
    margin-top: 2px;
    margin-bottom: 2px;
}
-->
</style>
</head>

<body>

<h1>This Page Cannot Be Displayed</h1>
<hr>

<p>
The system cannot communicate with the external server (&nbsp;x.x.x.x&nbsp;).
The Internet server may be busy, may be permanently down, or may be
unreachable because of network problems.
</p>

<p>
Please check the spelling of the Internet address entered.
If it is correct, try this request later.
</p>



<p>
If you have questions, or feel this is an error, please contact
your organization's network administrator 
and provide the codes shown below.
</p>

<hr>
<table>
  <tr valign="top">
    <td valign="top" width="10%">Notification&nbsp;codes:&nbsp;</td>
    <td valign="top" class="code" width="90%">(1, GATEWAY_TIMEOUT, x.x.x.x)</td>
  </tr>
</table>

</body>
</html>
```

*** x.x.x.x is the ip address of Node B

I tried

1. Reinstalling mlflow on both nodes
2. Checking internet connection of both nodes as well as the communications between the nodes
3. Checking if running from Node B itself with the same format of codes would work (Same problem)
4. Changing the location of the mlflow tracking server storage
5. Using HDFS as mlflow tracking server storage
6. Checking if logging is possible from windows based machine
7. Checking if hosting mlflow server on Node A works (Same problem with Node A ip)

No luck on all the attempts. Address for the tracking server was correct and no internet problem on either nodes. Other applications / softwares on both Node A and B are running without any issues, so I can only imagine that this has to do with mlflow server issue. Please help me resolve this issue..! Let me know if you need any more information from me to resolve this issue!

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
Traceback:
---------------------------------------------------------------------------
MlflowException                           Traceback (most recent call last)
<ipython-input-6-af1864c9f8ff> in <module>()
      2 uri("http://x.x.x.x:5000")
      3 
----> 4 with mlflow.start_run():
      5     mlflow.log_param('a', 1)
      6     mlflow.log_param('b', 2)

/usr/local/lib/python3.6/dist-packages/mlflow/tracking/fluent.py in start_run(run_uuid, experiment_id, source_name, source_version, entry_point_name, source_type, run_name)
    107                 source_version=source_version or _get_source_version(),
    108                 entry_point_name=entry_point_name,
--> 109                 source_type=source_type or _get_source_type())
    110     _active_run = ActiveRun(active_run_obj)
    111     return _active_run

/usr/local/lib/python3.6/dist-packages/mlflow/tracking/client.py in create_run(self, experiment_id, user_id, run_name, source_type, source_name, entry_point_name, start_time, source_version, tags)
     63             start_time=start_time or int(time.time() * 1000),
     64             source_version=source_version,
---> 65             tags=[RunTag(key, value) for (key, value) in iteritems(tags)],
     66         )
     67 

/usr/local/lib/python3.6/dist-packages/mlflow/store/rest_store.py in create_run(self, experiment_id, user_id, run_name, source_type, source_name, entry_point_name, start_time, source_version, tags)
    147             source_type=source_type, source_name=source_name, entry_point_name=entry_point_name,
    148             start_time=start_time, source_version=source_version, tags=tag_protos))
--> 149         response_proto = self._call_endpoint(CreateRun, req_body)
    150         run = Run.from_proto(response_proto.run)
    151         if run_name:

/usr/local/lib/python3.6/dist-packages/mlflow/store/rest_store.py in _call_endpoint(self, api, json_body)
     65         host_creds = self.get_host_creds()
     66         response = http_request(host_creds=host_creds, endpoint=endpoint, method=method,
---> 67                                 json=json_body)
     68         js_dict = json.loads(response.text)
     69 

/usr/local/lib/python3.6/dist-packages/mlflow/utils/rest_utils.py in http_request(host_creds, endpoint, retries, retry_interval, **kwargs)
     51             time.sleep(retry_interval)
     52     raise MlflowException("API request to %s failed to return code 200 after %s tries" %
---> 53                           (url, retries))
     54 
     55 

MlflowException: API request to http://x.x.x.x:5000/api/2.0/preview/mlflow/runs/create failed to return code 200 after 3 tries
```

**Comment by dbczumar** [comment]
@dudgnskim I see that the `--host` argument of your `mlflow server` invocation is `x.x.x.x`, which you defined as the IP address of Node B. Can you replace `x.x.x.x` with `0.0.0.0` and try again?

**Comment by dudgnskim** [comment]
@dbczumar Tried with 0.0.0.0 and the same issue still occurs. Could you explain what the meaning of using 0.0.0.0 as the host ip in this case?

**Comment by dudgnskim** [comment]
@dbczumar Actually, instead of 504 != 200, this time it says 503 != 200. The rest of the error message is the same.

**Comment by dbczumar** [comment]
@dudgnskim `0.0.0.0` indicates that the server should bind to all network interfaces, in order to listen for external traffic. If possible, can you try using the [GNU netcat](http://netcat.sourceforge.net) tool on Node A to determine if port 5000 is accessible on Node B? You can run `nc -vz x.x.x.x 5000`.

**Comment by dudgnskim** [comment]
It says:
root@lcarvalh-lnx121:~# nc -vz x.x.x.x 5000
Connection to x.x.x.x 5000 port [tcp/*] succeeded!
from Node A

**Comment by dudgnskim** [comment]
@dbczumar It says:
Node A:~# nc -vz x.x.x.x 5000
Connection to x.x.x.x 5000 port [tcp/*] succeeded!
from Node A

** Just in case you haven't received any notification from my previous comment

**Comment by dbczumar** [comment]
@dudgnskim Sorry I missed this! Are there any logs produced on the server side (Node B)? Have you tried using version `0.7.0` of MLflow on both Nodes?

**Comment by dudgnskim** [comment]
@dbczumar I just upgraded and tried again, but it seems like the problem persists..

**Comment by dbczumar** [comment]
@dudgnskim Is there any log output from the tracking server running on Node B?

**Comment by dudgnskim** [comment]
@dbczumar Could you tell me where to look for the log file?

**Comment by dbczumar** [comment]
@dudgnskim Log output should be emitted in the shell that you used to execute the `mlflow server... command`

**Comment by dudgnskim** [comment]
This is the output from Node B
```
[NodeB data1]# mlflow server --file-store /data1/tracking/ --default-artifact-root /data1/tracking/ --host x.x.x.x
[2018-10-04 13:44:49 +0000] [9897] [INFO] Starting gunicorn 19.9.0
[2018-10-04 13:44:49 +0000] [9897] [INFO] Listening at: http://x.x.x.x1:5000 (9897)
[2018-10-04 13:44:49 +0000] [9897] [INFO] Using worker: sync
[2018-10-04 13:44:49 +0000] [9901] [INFO] Booting worker with pid: 9901
[2018-10-04 13:44:49 +0000] [9925] [INFO] Booting worker with pid: 9925
[2018-10-04 13:44:50 +0000] [9926] [INFO] Booting worker with pid: 9926
[2018-10-04 13:44:50 +0000] [9927] [INFO] Booting worker with pid: 9927
```

It seems like nothing was logged from executing this.
```
### Set tracking uri to node B
mlflow.tracking.set_tracking_uri("http://x.x.x.x:5000")

with mlflow.start_run():
    mlflow.log_param('a', 1)
    mlflow.log_param('b', 2)
    mlflow.log_param('c', 3)
```

**Comment by dbczumar** [comment]
@dudgnskim What happens if you run `mlflow server --host 0.0.0.0` on Node B without specifying any additional parameters?

**Comment by dudgnskim** [comment]
@dbczumar It shows the same error message as before as when I ran mlflow server with 0.0.0.0.
```
API request to http://0.0.0.0:5000/api/2.0/preview/mlflow/runs/create failed with code 503 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Notification: DNS Failure</title>
<style type="text/css">
```

**Comment by smurching** [comment]
@dudgnskim sorry just to make sure, did you try the combination below?:

* On Node A, call `mlflow.set_tracking_uri("http://x.x.x.x:5000")`
* On Node B, run `mlflow server --host 0.0.0.0`

Specifically, the `mlflow server` invocation on node B needs to run with `--host 0.0.0.0` so that it binds to all network interfaces, but node A should still reference node B via its public IP address (`x.x.x.x` rather than `0.0.0.0`).

**Comment by dudgnskim** [comment]
@smurching I just tried the instruction that you told me, and it shows the original error message.
```
API request to http://x.x.x.x:5000/api/2.0/preview/mlflow/runs/create failed with code 504 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Notification: Gateway Timeout</title>
<style type="text/css">
```

**Comment by smurching** [comment]
Hm that is bizarre, let me try to reproduce it - are you running in a cloud environment e.g. EC2?

**Comment by dudgnskim** [comment]
@smurching I am running on a physical workstation machines at work. Our office has multiple workstations clustered up for local data storage/modeling purposes, so both Node A and B have physical ip address and body.

**Comment by Wasala** [comment]
@dudgnskim I came across a similar issue, and it turned out to be due to a proxy issue. If both Node A and B resides within the same sub-net, but if a proxy is set in your Node A (client),  mlflow fails to communicate with the server. In my case, all I have to do is add os.environ['NO_PROXY'] = 'x.x.x.x' (where x.x.x.x is your mlflow servers IP) to the client script, before mlflow is initialized and that resolved the problem. 

I realized in the rest_utils.py, the request is sent without defining a proxy so the _requests_ always ends up timeout. #597 and #111 might be relevant for this issue too. @smurching It's useful if there is a feature to set or unset proxy for client/server.

**Comment by Pisou** [comment]
how to fix this error ?
mlflow.exceptions.MlflowException: API request to http://0.0.0.0:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='0.0.0.0', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by ResponseError('too many 500 error responses'))

**Comment by qq240035000** [comment]
nohup mlflow server --host 0.0.0.0 --port 5000 --workers 1 --backend-store-uri "mysql://xxx:xxx@xx:3306/mlflow?charset=utf8"
maybe the db connect error。have to add charset=utf8，it's my expe

**Comment by itskoi** [comment]
> @dudgnskim I came across a similar issue, and it turned out to be due to a proxy issue. If both Node A and B resides within the same sub-net, but if a proxy is set in your Node A (client), mlflow fails to communicate with the server. In my case, all I have to do is add os.environ['NO_PROXY'] = 'x.x.x.x' (where x.x.x.x is your mlflow servers IP) to the client script, before mlflow is initialized and that resolved the problem.
> 
> I realized in the rest_utils.py, the request is sent without defining a proxy so the _requests_ always ends up timeout. #597 and #111 might be relevant for this issue too. @smurching It's useful if there is a feature to set or unset proxy for client/server.

It's worked for me, you save my day!
