### ISSUE TITLE
[FR] in the web UI, provide access to some server information, at least the server version

### ISSUE THREAD

**Issue by jlmeunier** [mlflow/mlflow#5451]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ x] No. I cannot contribute this feature at this time.

## Proposal Summary

When accessing a MLFLOW server with a web browser, it would be nice to have access to some key info about the server.
At least the  mlflow library version
Also possibly:
- python version 
- version of all installed libraries mlflow  depends on? (CORE_REQUIREMENTS in setup.py) ?
- data storage scheme + location + size ?
- artifact location schema + location + size ?
- usage stats (if available??)

## Motivation
- What is the use case for this feature?  monitoring MLFLOW servers
- Why is this use case valuable to support for MLflow users in general? Would also be helpful to precisely describe the context of any issue
- Why is this use case valuable to support for your project(s) or organization? as for others
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient): today, I need access to the server installation to get this info

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dbczumar** [comment]
Hi @jlmeunier ! Thank you for raising this. It's being tracked by https://github.com/mlflow/mlflow/issues/3044. We'd absolutely welcome contributions for this. @adamreeve, is this something you could contribute?

**Comment by dbczumar** [comment]
Closing this in lieu of https://github.com/mlflow/mlflow/issues/3044.

**Comment by adamreeve** [comment]
Hi @dbczumar, sure, I've opened a PR for this at #5504, although it looks like this needs some support from someone at Databricks to update the script that modifies version numbers for releases.
