### ISSUE TITLE
[BUG] EvaluationResult from DefaultEvaluator throws ValueError (unknown file extension) when calling .save()

### ISSUE THREAD

**Issue by MarkYHZhang** [mlflow/mlflow#5475]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Added one additional line.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Big Sur
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.24.0
- **Python version**: 3.9.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: Add `result.save("output")` to the end of [`evaluate_on_regressor.py`](https://github.com/mlflow/mlflow/blob/master/examples%2Fevaluation%2Fevaluate_on_regressor.py). Then `python mlflow/examples/evaluation/evaluate_on_regressor.py`

### Describe the problem
This error occurs because `ImageEvaluationArtifact` relies on [pillow's save() method](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save). It infers the image format based on the provided path's file extension. However, the provided path to [`EvaluationResult.save`](https://github.com/mlflow/mlflow/blob/78df312065d73cbd117767157a72cc68ae176d35/mlflow/models/evaluation/base.py#L135) by `DefaultEvaluator` from [here](https://github.com/mlflow/mlflow/blob/4c38389e15e44b8ac2bc00ab89d7b288d2f1e9da/mlflow/models/evaluation/default_evaluator.py#L381) consists of only the artifact's name (without extension).

### Code to reproduce issue
```python
import mlflow
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

mlflow.sklearn.autolog()

california_housing_data = fetch_california_housing()

X_train, X_test, y_train, y_test = train_test_split(
    california_housing_data.data, california_housing_data.target, test_size=0.33, random_state=42
)

with mlflow.start_run() as run:
    model = LinearRegression().fit(X_train, y_train)
    model_uri = mlflow.get_artifact_uri("model")

    result = mlflow.evaluate(
        model_uri,
        X_test,
        targets=y_test,
        model_type="regressor",
        dataset_name="california_housing",
        evaluators="default",
        feature_names=california_housing_data.feature_names,
        evaluator_config={"explainability_nsamples": 1000},
    )
result.save("output")
```

### Other info / logs
```console
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/anaconda3/lib/python3.9/site-packages/PIL/Image.py in save(self, fp, format, **params)
   2219             try:
-> 2220                 format = EXTENSION[ext]
   2221             except KeyError as e:

KeyError: ''

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/var/folders/5d/lcq9fgm918l8mg8vlbcq4d0c0000gp/T/ipykernel_77385/2290762558.py in <module>
     26         evaluator_config={"explainability_nsamples": 1000},
     27     )
---> 28 result.save("output")

/usr/local/anaconda3/lib/python3.9/site-packages/mlflow/models/evaluation/base.py in save(self, path)
    133 
    134         for artifact_name, artifact in self.artifacts.items():
--> 135             artifact._save(os.path.join(artifacts_dir, artifact_name))
    136 
    137     @property

/usr/local/anaconda3/lib/python3.9/site-packages/mlflow/models/evaluation/artifacts.py in _save(self, output_artifact_path)
      6 class ImageEvaluationArtifact(EvaluationArtifact):
      7     def _save(self, output_artifact_path):
----> 8         self._content.save(output_artifact_path)
      9 
     10     def _load_content_from_file(self, local_artifact_path):

/usr/local/anaconda3/lib/python3.9/site-packages/PIL/Image.py in save(self, fp, format, **params)
   2220                 format = EXTENSION[ext]
   2221             except KeyError as e:
-> 2222                 raise ValueError(f"unknown file extension: {ext}") from e
   2223 
   2224         if format.upper() not in SAVE:

ValueError: unknown file extension: 
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Thanks @MarkYHZhang !
