### ISSUE TITLE
[DOC-FIX] Updating built-in deployment tools for MLFlow models in Azure ML

### ISSUE THREAD

**Issue by santiagxf** [mlflow/mlflow#5479]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [x] Yes. I can contribute a documentation fix independently.
- [ ] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

[Deploy a python_function model on Microsoft Azure ML](https://www.mlflow.org/docs/latest/models.html#id50)

### Description of proposal (what needs changing):
Current documentation suggests the use of `mlflow.azureml.deploy` method to deploy `mlflow` models into Azure. However, such method is deprecated as indicated on [its documentation](https://www.mlflow.org/docs/latest/python_api/mlflow.azureml.html#mlflow.azureml.deploy). The current recommended way to deploy models is using an MLflow plug in `azureml-mlflow`. Documentation needs to be updated in order to reflect that. I already updated the documentation page [in the following branch](https://github.com/santiagxf/mlflow/blob/c302d5c26227402c00bc7975afcb69be06477478/docs/source/models.rst):

**Comment by santiagxf** [comment]
Addressed on [PR 5491](https://github.com/mlflow/mlflow/pull/5491)

**Comment by dbczumar** [comment]
Hi @santiagxf , I'm going to go ahead and close this issue now that we have a PR. Thank you for contributing this!
