### ISSUE TITLE
Upgrade GitHub actions managed by `https://github.com/actions` to v3

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5492]
https://github.com/actions recently released v3 for their actions (e.g. https://github.com/actions/setup-python/releases/tag/v3.0.0). We should upgrade our GitHub Actions config to use the new version.

Example:

https://github.com/mlflow/mlflow/blob/f9e5200a3a1e8d5ec86fd4ed9776f1c2392ce18e/.github/actions/setup-python/action.yml#L32

```diff
-      - uses: actions/setup-python@v2
+      - uses: actions/setup-python@v3
```

**Comment by harupy** [comment]
cc @BenWilson2

**Comment by Sohamkayal4103** [comment]
@harupy  I would like to work on this issue

**Comment by harupy** [comment]
@Sohamkayal4103 Thanks! Feel free to submit a PR. We'd be happy to review it :)
