### ISSUE TITLE
[Question] Can /invocations endpoint return CSV?

### ISSUE THREAD

**Issue by john-munar** [mlflow/mlflow#5496]
Hello there. I looked at the docs for the /invocation endpoint and though I am able to feed the endpoint with csv data, I get the data returned in json format. Is it possible to get this data returned as csv?

**Comment by dbczumar** [comment]
Hi @john-munar - the MLflow server can only provide responses in JSON format. This way, consumers of model scoring REST endpoints only have to handle a single output type. Please let me know if there's a particular use case requiring that records be returned in CSV format, and feel free to create a feature request ticket if JSON isn't sufficient for whatever reason. Thank you for using MLflow!
