### ISSUE TITLE
sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause

### ISSUE THREAD

**Issue by HaraldVanWoerkom** [mlflow/mlflow#5499]
I get the mentioned exception when I query my experiments (this is also the query used by the mlflow module):
<MLFLOW HOST>/api/2.0/mlflow/experiments/list?view_type=ALL&max_results=1000
I do not get this when I ask for the full list:
<MLFLOW HOST>/api/2.0/mlflow/experiments/list

In our configuration, we use a tracking server with the mssql+pyodbc: protocol.

The error is self-explanatory: if you query for a part of a list, mssql requires you to specify how the order of the list is made deterministic. Since I have not seen this problem with sqlite, I assume that this is something that is specific to mssql.

A fix is also straightforward:
- in sqlalchemy_store.py, line 294, add an order_by(SqlExperiment.experiment_id) clause.
- so the query now reads:
                queried_experiments = (
                    session.query(SqlExperiment)
                    .options(*query_options)
                    # Next line added
                    .order_by(SqlExperiment.experiment_id)
                    .filter(*conditions)
                    .offset(offset)
                    .limit(max_results_for_query)
                    .all()
                )

**Comment by HaraldVanWoerkom** [comment]
Hi @dbczumar . Unfortunately I do not have a development environment for mlflow set up (I hacked my fix directly into my Python environment). I'm afraid that setting up an environment that also runs all tests will be a lengthy exercise.

**Comment by BenWilson2** [comment]
@HaraldVanWoerkom thank you again for bringing this issue up to us! This should be completely fixed in the next release of MLflow so that you don't have to fork the repo and apply a manual fix. Cheers!

**Comment by HaraldVanWoerkom** [comment]
@BenWilson2 Thanks for picking this up so promptly.
