### ISSUE TITLE
[BUG] Aquasec scan failed for the docker image from dockerutil.py

### ISSUE THREAD

**Issue by moshinde** [mlflow/mlflow#5524]
Hi,

Aquasec scan is failing for the docker image generated by "mlflow models build-docker".
Please find an attached json file containing all the vulnerabilities.

[AquascanReports.docx](https://github.com/mlflow/mlflow/files/8333905/AquascanReports.docx)

**Comment by BenWilson2** [comment]
Is this in reference to the miniconda vulnerabilities listed in this NIST report? If so, we are using the latest version of miniconda. A better place to refer to might be to notify anaconda of these vulnerabilities.
