### ISSUE TITLE
[BUG] Inconsistency in serving between json and csv data

### ISSUE THREAD

**Issue by vvijay-bolt** [mlflow/mlflow#5525]
The parse csv input function [here](https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/scoring_server/__init__.py) is used to decode requests during model serving. Unlike the json function in the same file, it does not use the model schema to inform the choice of datatypes. This causes errors when the dataframe is later compared against the schema [here](https://github.com/mlflow/mlflow/blob/41deb9ee5705d2727dc3df7fe60ce2c09231c8cc/mlflow/pyfunc/__init__.py)

In particular, when the input schema contains an int32 column, serving will work with json but not with csv.

### Willingness to contribute
Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community. (Need guidance on testing)

### Describe the problem
Problem: serving with csv fails when an input column has type int32. In contrast, serving with json works.

### Code to reproduce issue

Train and serve the modified logistic regression example below.
Save the following in test_csv.csv:
x
1
-1

Then try:
curl -d '{"columns":["x"],"index":[0,1],"data":[[1],[-1]]}' -H 'Content-Type: application/json'  localhost:5000/invocations
curl --data-binary '@test_csv.csv' -H 'Content-Type: text/csv'  localhost:5000/invocations

The json request returns [1, 0].
The csv request will produce: {"error_code": "BAD_REQUEST", "message": "Incompatible input types for column x. Can not safely convert int64 to int32."}

The json command

Modified logistic regression example:

```
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from mlflow.models.signature import infer_signature

import mlflow
import mlflow.sklearn

if __name__ == "__main__":
    X = pd.DataFrame({'x': [-2, -1, 0, 1, 2, 1]}, dtype='int32')
    y = np.array([0, 0, 1, 1, 1, 0])
    lr = LogisticRegression()
    lr.fit(X, y)
    score = lr.score(X, y)
    print("Score: %s" % score)

    class Model(mlflow.pyfunc.PythonModel):
        def __init__(self, m):
            self.m = m

        def predict(self, context, x):
            return self.m.predict(x)

    model = Model(lr)
    signature = infer_signature(X, model.predict(None, X))
    print('Signature')
    print(signature)
    mlflow.pyfunc.log_model('model', python_model=model, signature=signature)
    print("Model saved in run %s" % mlflow.active_run().info.run_uuid)
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by dbczumar** [comment]
@arjundc-db @tomasatdatabricks Can you take a look?

**Comment by vvijay-bolt** [comment]
I opened a pr here: https://github.com/mlflow/mlflow/pull/5531

Could you please take a look?

The tests seem to be failing because there's an error while building the docs. My changes shouldn't be causing it.

**Comment by arjundc-db** [comment]
Fixed by https://github.com/mlflow/mlflow/pull/5531
