### ISSUE TITLE
Be able to set run output path

### ISSUE THREAD

**Issue by sbracaloni** [mlflow/mlflow#556]
This issue is a feature request.
We try to version a whole Machine Learning pipeline using [MLV-tools](https://github.com/peopledoc/ml-versioning-tools/) and we need to have a deterministic output structure for each run. 
For example:
`mlflow.start_run(ouput_path='/my/custom/path', experiment_id=12)`

          /my/custom/path/12/
                          |- [param_name_combi1]
                          |- [param_name_combi2]

Here the major difference is the replacement of unpredictable uuid with a deterministic name.

**Comment by max-allen-db** [comment]
@sbracaloni Have you considered storing the runs in a non-file store backend? For example, using a database with SQLAlchemy?

**Comment by max-allen-db** [comment]
Also, is it good enought to get the path of the run after you create it? `mlflow.start_run()` returns an `ActiveRun` object from which you can grab the runId that id used to determine the path to the run.
