### ISSUE TITLE
Remove `print` functions in `tests`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5566]
In https://github.com/mlflow/mlflow/pull/5556, we added a custom pylint rule to prevent print function usage. As a follow-up task for this, we should remove `print` functions in the `tests` directory:

## Instructions

1. Remove the following lines:
https://github.com/mlflow/mlflow/blob/5f956fbdfc1ca741c66743d4e8f0082a26393870/pylint_plugins/print_function.py#L13-L14

2. Remove all `print` functions in `tests`:

Example:
https://github.com/mlflow/mlflow/blob/0fa849ad75e5733bf76cc14a4455657c5c32f107/tests/server/test_handlers.py#L116

**Comment by harupy** [comment]
Command to list lines containing `print`:

```
pylint $(git ls-files | grep '\.py$') | grep print-function
```

output should look like:

```
tests/examples/test_examples.py:72:8: W0002: print function should not be used (print-function)
tests/helper_functions.py:230:16: W0002: print function should not be used (print-function)
tests/helper_functions.py:234:16: W0002: print function should not be used (print-function)
tests/helper_functions.py:237:8: W0002: print function should not be used (print-function)
tests/models/test_default_evaluator.py:350:4: W0002: print function should not be used (print-function)
...
```

**Comment by Kr4is** [comment]
We should delete also eprints `from mlflow.utils.logging_utils import eprint`? Change prints by eprints? or just delete prints as said at the issue title? :thinking:

**Comment by harupy** [comment]
@Kr4is I think we can just remove print in the tests directory.

**Comment by Kr4is** [comment]
@harupy okay! I'll fix this issue!

**Comment by harupy** [comment]
@Kr4is Thanks!
