### ISSUE TITLE
[FR] Custom Name Model Versioning

### ISSUE THREAD

**Issue by Clayrisee** [mlflow/mlflow#5575]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x]  Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Hallo MLFlow Team! I think for model versioning name, we can add fitur custom model versioning name instead of automatic increament. For current MLFlow Model Registry when we have 2 models and we want to do versioning, the model version automatic increament like model version 1, model version 2, etc. 

My proposal is to create an option for user to do manual versioning, like model version 1.0.0 , model version 1.0.1, etc.

## Motivation
- What is the use case for this feature?
User can add manual model versioning if they have standardize model version in their organization.

- Why is this use case valuable to support for MLflow users in general?
Yup, this use case can support MLFlow users to implement this tools into their organization.

- Why is this use case valuable to support for your project(s) or organization?
In my current organization, they have standardizes model versioning like version 1.0.0. 

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
None

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dbczumar** [comment]
Hi @Clayrisee , unfortunately, many components of MLflow and the Model Registry depend on the autoincrementing version scheme. We don't have plans to loosen or adjust the version scheme at this time. One workaround that may help would be to use Model Registry tags (e.g. https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.set_model_version_tag) to tag your model versions with your internal version ID scheme. You can then fetch model versions for a particular registered model using https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.search_model_versions and find the desired internal version based on the tag value. This could be made easier by completing the tag-based search implementation that was started here: https://github.com/mlflow/mlflow/pull/3296.

Thank you for using MLflow!

**Comment by Clayrisee** [comment]
awesome! thanks for your reply!
