### ISSUE TITLE
Unable to deploy mlflow model on Azure ML

### ISSUE THREAD

**Issue by manishpyy** [mlflow/mlflow#5588]
I am following the mlflow documentation for deploying the model in Azure ML (doc link: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-mlflow-models). In the following piece of code:
<img width="458" alt="Capture" src="https://user-images.githubusercontent.com/102793299/161497019-e0139e1d-ca3e-48f7-ae19-b0d23c5b0e84.PNG">

The output of mlflow.get_tracking_uri = 'http://127.0.0.1:5000/'    (localhost)

However while executing the line:  client = get_deploy_client(mlflow.get_tracking_uri), I am getting the following error:

KeyError: 'http'

During handling of the above exception, another exception occurred:

MlflowException: No plugin found for managing model deployments to "http". In order to deploy models to "http", find and install an appropriate plugin from https://mlflow.org/docs/latest/plugins.html#community-plugins using your package manager (pip, conda etc).

Could anybody help me with this scenario?

**Comment by harupy** [comment]
@manishpyy Did you set the MLflow tracking URI to your Azure ML Workspace?

**Comment by manishpyy** [comment]
> @manishpyy Did you set the MLflow tracking URI to your Azure ML Workspace?

Yes,  I had set the tracking URI, this is the command for the same:

mlflow.set_tracking_uri("http://127.0.0.1:5000/")
mlflow.set_experiment("wine_regression")

**Comment by harupy** [comment]
Is `http://127.0.0.1:5000/` is your local address, right? Can you follow https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-mlflow#set-up-tracking-environment and set up the tracking URI properly?

**Comment by manishpyy** [comment]
Yes, I had set it to the local address, hence the error. I guess had to set it to the uri of the microsoft workspace. Closing this issue. Thanks :)
