### ISSUE TITLE
Replace `["--no-conda"]` with `["--env-manager", "local"]` in tests

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5590]
In https://github.com/mlflow/mlflow/pull/5567, we added `--env-manager` to specify an environment manager (e.g. `conda`) to restore a model's environment for MLflow Models and Projects, and marked `--no-conda` as deprecated. We still use `--no-conda` in tests, which should be replaced with `--env-manager local`.

### Example

https://github.com/mlflow/mlflow/blob/881919bc96f6858381e79f80c367f270395fb748/tests/catboost/test_catboost_model_export.py#L34

```diff
- EXTRA_PYFUNC_SERVING_TEST_ARGS = [] if _is_available_on_pypi("catboost") else ["--no-conda"] 
+ EXTRA_PYFUNC_SERVING_TEST_ARGS = [] if _is_available_on_pypi("catboost") else ["--env-manager", "local"] 
```

### Notes:

`--no-conda` in the following directories should not be replaced:

- `tests/projects`
- `tests/models`

**Comment by harupy** [comment]
@nishipy Yes! Looking forward to your PR!

**Comment by nishipy** [comment]
Thank you! Let me try to fix it and get back to you later.

**Comment by harupy** [comment]
@nishipy Assigned this task to you :)

**Comment by nishipy** [comment]
I created PR #5604 so please review it.
