### ISSUE TITLE
[DOC-FIX] Add a Twitter badge on README

### ISSUE THREAD

**Issue by guelate** [mlflow/mlflow#5594]
**What is the expected behavior?**

I want to add the dependency for Twitter

[![Twitter follow](https://img.shields.io/twitter/follow/MLflow?style=social)](https://twitter.com/MLflow)

**What is motivation or use case for adding/changing the behavior?**

I think it is important to put forward the community.

**Comment by harupy** [comment]
@guelate Makes sense, looking forward to your PR :)

**Comment by guelate** [comment]
@harupy Yes, here it is: https://github.com/mlflow/mlflow/pull/5605 :)

**Comment by harupy** [comment]
Addressed by https://github.com/mlflow/mlflow/pull/5605
