### ISSUE TITLE
Concatenate adjacent strings that look like `"a" "b"`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5635]
Concatenate strings that look like this:

```python
print("a" "b")
```

This should be fixed to:

```python
print("ab")
```

These adjacent strings were created when we introduced black in this repository.

### Example:

https://github.com/mlflow/mlflow/blob/191ce7038e7aee44bd8ee55917338229f70e55a0/mlflow/deployments/cli.py#L123

### Instructions:

- If your code editor supports regular expression search, `" "[^"]+"` should find lines containing string that should be concatenated. Note this regular expression might catch false postives.
- Concatenate them.
- Run `black .` to format.

**Comment by BenWilson2** [comment]
@erich-db has claimed this one! :)

**Comment by kutal10** [comment]
Hey @BenWilson2 , didn't see the prior assignment to erich, but just added a PR to resolve this at #5646
