### ISSUE TITLE
Proxy server for artifacts just doesn't work

### ISSUE THREAD

**Issue by ibobak** [mlflow/mlflow#5659]
Based on documentation https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access
there is a scenario when tracking server should act as proxy artifact: 
![image](https://user-images.githubusercontent.com/8807043/162745908-1c87d48a-0107-4845-81df-b2d86f3f8130.png)

I am running the server using this command:
```
mlflow server --backend-store-uri postgresql+psycopg2://myuser:mypassword@db:5432/mlflow_db --artifacts-destination s3://mybucker/mlflow/prod --serve-artifacts --host 0.0.0.0
```

But unfortunately, I can clearly see that this code on the client side

```
mlflow.set_tracking_uri("http://my_server_on_amazon")
mlflow.set_experiment("test")
...
log_artifacts("outputs")
```

tries to access S3 directly  (instead of sending all requests to the http://my_server_on_amazon, as I expect it to do).

May I have a question:  is documentation is bad and this feature of artifact proxying is still not implemented? 
Or I am doing something wrong with "mlflow server .... (parameters)"  command?

MLflow version:  1.24.0.
Thanks in advance.

**Comment by harupy** [comment]
@ibobak What does the code below print out in your environment?

```python
mlflow.set_tracking_uri("http://my_server_on_amazon")
mlflow.set_experiment("test")

with mlflow.start_run():
    mlflow.get_artifact_uri()
```

**Comment by harupy** [comment]
@ibobak Is the experiment "test" a new experiment? If it's not, it might use an S3 artifact URI because the artifact URI doesn't change.

**Comment by ibobak** [comment]
Yes, you're right:  "test" was created before I made a run with --serve-artifacts.

So, I created a new experiment and now I am getting this when running print(mlflow.get_artifact_uri()):
```
mlflow-artifacts:/2/749c6887839140879e9339b79f8b65b7/artifacts
```
I removed all S3 credentials on the client side and even removed boto3 library from the environment, and I see it is writing artifact files anyway, which means that it does it using proxy.

So, it means that this is a TODO point for fixing the documentation: it is necessary to state that if experiment was launched without "--serve-artifacts"  and later this command line parameter was added, it won't affect on how the old experiment will behave.

**Comment by ibobak** [comment]
Feel free to close the issue, if needed.  Or change status  to "problem in documentation", whatever.

Thanks again!

**Comment by harupy** [comment]
@ibobak Thanks for the reply!

**Comment by harupy** [comment]
@ibobak 

> So, it means that this is a TODO point for fixing the documentation: it is necessary to state that if experiment was launched without "--serve-artifacts" and later this command line parameter was added, it won't affect on how the old experiment will behave.

Thanks for the suggestion, but this is already documented :)

https://mlflow.org/docs/latest/tracking.html

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/17039389/163076254-78c6304a-7baf-4719-857c-be44c2be7bcd.png">

**Comment by njanopoulos** [comment]
I am having the exact issue that was posted here at the beginning of the conversation. Unfortunately, the solution provided hasn't worked for me. Anybody have more suggestions of things to try or look for?
