### ISSUE TITLE
Remove unnecessary `warnings.simplefilter("ignore")` and `warnings.catch_warnings()`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5667]
Remove unnecessary `warnings.simplefilter("ignore")` and `warnings.catch_warnings()` because warnings are usually helpful and should not be hidden unless they cause errors or print out too many messages.

## Example

https://github.com/mlflow/mlflow/blob/fe6618823a2e6038149ee0da675503d2764552ca/tests/store/tracking/test_sqlalchemy_store.py#L777-L781

This block needs to be fixed to:

```python
 with self.assertRaises(MlflowException) as exception_context: 
     self.store.log_metric(run.info.run_id, metric) 
 assert exception_context.exception.error_code == ErrorCode.Name(INVALID_PARAMETER_VALUE) 
```

**Comment by Safirangi** [comment]
Can I work on this issue?

**Comment by harupy** [comment]
@Safirangi Yes, looking forward to your PR!

**Comment by harupy** [comment]
Please let me know if you have any questions :)

**Comment by Safirangi** [comment]
Since I'm changing this from the browser, do I have to run tests?

**Comment by Safirangi** [comment]
I have problem with understanding the Pull Request format, since it asks questions about classifying the issue. So I haven't changed much in the pull request.

**Comment by harupy** [comment]
Ok, let me update the PR description.

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/5679#discussion_r848658410

> I'm sorry, I am struggling to contribute. I don't think I can contribute to this project, since it's above my knowledge. I apologize for wasting your time. Thank you for guiding me.
