### ISSUE TITLE
Replace `unittest.TestCase.assertRaises` with `unittest.TestCase.assertRaisesRegex`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5680]
Some tests use `unittest.TestCase.assertRaises` to test an exception is raised for illegal operations, but they need to be replaces with `unittest.TestCase.assertRaisesRegex`.

### Why do we need this change?

Let's say we have a function that raises an exception:

```python
def throw_exception(...):
    if condition_1:
        raise TypeError("condition_1")
    if condition_2:
        raise TypeError("condition_2")
    ...
```

If we test this function using `assertRaises`:

```python
class MyTest(unittest.TestCase):
    def test_throw_exception(self):
        # Does `throw_exception` really raise the second TypeError?
        # It might throw the first TypeError, then the test will pass.
        with self.assertRaises(TypeError):
            throw_exception(...)  # should raise TypeError("condition_2")
```

If we test this function using `assertRaisesRegex`:

```python
class MyTest(unittest.TestCase):
    def test_throw_exception(self):
        # This test fails when `throw_exception` raises the first TypeError.
        with self. assertRaisesRegex(TypeError, "condition_b"):
            throw_exception(...)  # should raise TypeError("condition_2")
```

### Example

https://github.com/mlflow/mlflow/blob/fe6618823a2e6038149ee0da675503d2764552ca/tests/store/tracking/test_sqlalchemy_store.py#L107

The code above needs to be fixed to the following:

```python
 # "<string that matches the error message>" must be replaced
 with self.assertRaisesRegex(MlflowException, "<string that matches the error message>") as e:
```

### References

- https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises
- https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaisesRegex

### Instructions

https://github.com/mlflow/mlflow/blob/101ad6e8eb383c769178df0df83d1d2a1cea6b4a/pylint_plugins/assert_raises_without_msg.py#L20-L33

Ping me with the file you want to work on :)

| File                                                  | Assignee    | PR    | Done |
| :---------------------------------------------------- | :---------- | :---- | :--- |
| `tests/entities/test_run_status.py`                   | @Sumanth077 |       |      |
| `tests/store/model_registry/test_sqlalchemy_store.py` | @ognis1205  | #5875 | ✅   |
| `tests/store/db/test_utils.py`                        | @erich-db   |       |      |
| `tests/store/tracking/__init__.py`                    | @Sumanth077 |       |      |
| `tests/store/tracking/test_file_store.py`             | @andy1122   |       |      |
| `tests/store/tracking/test_sqlalchemy_store.py`       | @ognis1205  | #5875 | ✅   |

**Comment by harupy** [comment]
cc @BenWilson2

**Comment by BenWilson2** [comment]
@erich-db this one is all yours!

**Comment by erich-db** [comment]
@BenWilson2 On it!

**Comment by harupy** [comment]
Hi @erich-db, could you tell me which file you're going to fix?

**Comment by erich-db** [comment]
@harupy I'll start with these three:
1. tests/entities/test_run_status.py
2. tests/store/db/test_utils.py
3. tests/store/tracking/__init__.py

**Comment by harupy** [comment]
@erich-db Sounds good!

**Comment by andy1122** [comment]
@harupy I would like to work on this file.

 tests/store/tracking/test_file_store.py

**Comment by harupy** [comment]
@andy1122 Awesome, looking forward to your PR :)

**Comment by harupy** [comment]
@erich-db @andy1122 Let me share the documentation of `assertRaies`:

https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises

**Comment by harupy** [comment]
@erich-db @andy1122 Looks like my understanding of the `msg` argument was wrong. Let me update the PR description.

**Comment by harupy** [comment]
Filed https://github.com/mlflow/mlflow/pull/5708 to fix the rule. @BenWilson2 Would you mind taking a look?

**Comment by ognis1205** [comment]
Hello, folks!
I would like to contribute to the project so I am considering to participate in this issue to start with. It seems nobody is working on the following two files:

  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py

Would you mind if I worked on these two files? Thank you.

**Comment by harupy** [comment]
@ognis1205 Thanks, looking forward to your PR!

**Comment by Sumanth077** [comment]
@harupy I would like to contribute to this, do any other files remaining.
Thank You

**Comment by harupy** [comment]
@Sumanth077 Thanks! Could you fix `tests/entities/test_run_status.py` and `tests/store/tracking/__init__.py`?

**Comment by ognis1205** [comment]
Created the PR https://github.com/mlflow/mlflow/pull/5875
@harupy Would you mind reviewing it? Thank you.

**Comment by Sumanth077** [comment]
@harupy Thankyou, will create a PR.

**Comment by Sumanth077** [comment]
Hi @harupy is this Issue still opened?

**Comment by harupy** [comment]
Hi @Sumanth077, I should've informed you but #5914 replaced all the `assertRaises` calls.
