### ISSUE TITLE
Enhancement: Add ability to log failure reason

### ISSUE THREAD

**Issue by aadamson** [mlflow/mlflow#569]
Right now, we can only track the status of a run, possibly marking it as failed upon failure. It would be nice to be able to add a failure reason along with the failure status. The reason could be something like a serialized stacktrace stored as a tag or simply an error code provided by the user. In either case, the user would be responsible for specifying the failure reason.

**Comment by whiletruelearn** [comment]
This will be a nice feature to have. +1 for idea of  storing this as a tag.

**Comment by addisonklinke** [comment]
Any progress on this? A system tag like `mlflow.status = SUCCESS, FAILURE` would be cool if it corresponded to the green checkmark and a red X next to the run row in the experiment table, respectively
