### ISSUE TITLE
Replace `--no-conda` in examples

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5697]
We recently deprecated `--no-conda` flag, but our examples still use it. They should be updated to use `--env-manager=local` instead.

https://github.com/mlflow/mlflow/blame/master/examples/pytorch/AxHyperOptimizationPTL/README.md#L26

```
mlflow run . --no-conda
```

The code above needs be fixed to the following:

```
mlflow run . --env-manager=local
```

**Comment by aashish-khub** [comment]
I'd like to work on this! @harupy

**Comment by shaikmoeed** [comment]
Do we need to update in `readme.md` file? @harupy

**Comment by harupy** [comment]
@aashish-khub thanks!

**Comment by harupy** [comment]
Addressed by https://github.com/mlflow/mlflow/pull/5707, Thanks @aashish-khub!
