### ISSUE TITLE
Convert the bug report template into a GitHub issue form

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5709]
## Task

Convert [the bug report template](https://github.com/mlflow/mlflow/blob/master/.github/ISSUE_TEMPLATE/bug_report_template.md) into a GitHub issue form:

## Motivation

- To make it easier to write a bug report.
- To clarify which information is required to submit an issue.

## Example

scikit-learn's bug report form:

https://github.com/scikit-learn/scikit-learn/issues/new?assignees=&labels=Bug%2CNeeds+Triage&template=bug_report.yml

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/17039389/163754491-fdc5bc04-04db-4cd9-9b6a-e8776e671d76.png">

## Instructions

1. Convert the bug report template into a YAML form definition.
2. Make sure the issue form renders fine. Feel free to create a new repository for faster experiments if necessary. We're happy to take a look and give feedback. 
3. Open a PR.

### References

- [Creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
- [Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
- [Issue forms in the scikit-learn repository](https://github.com/scikit-learn/scikit-learn/tree/main/.github/ISSUE_TEMPLATE)

### Notes

- This is our first attempt to use the issue-form feature. If we can successfully convert the bug report template, we can probably do the same thing for other templates.

**Comment by ahlag** [comment]
@harupy 
Can I have a try?

**Comment by harupy** [comment]
@ahlag Yes!

**Comment by ahlag** [comment]
@harupy 
Thank you!

**Comment by harupy** [comment]
Addressed by #5797 and #5803
