### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5712]
| Line                                                             | Typo          | Assignee         | PR    |
| :--------------------------------------------------------------- | :------------ | :--------------- | :---- |
| [dev/set_matrix.py#l304]                                         | exisiting     | @shaikmoeed      | #5730 |
| [mlflow/projects/databricks.py#L21]                              | avaialable    | @shaikmoeed      | #5730 |
| [tests/store/tracking/__init__.py#L10]                           | overriden     | @shaikmoeed      | #5730 |
| [dev/update_ml_package_versions.py#L122]                         | exlucde       | @lucalves        | #5734 |
| [dev/update_pypi_package_index.py#L3]                            | depenndencies | @lucalves        | #5734 |
| [mlflow/models/utils.py#l54]                                     | matric        | @lucalves        | #5734 |
| [mlflow/projects/utils.py#l186]                                  | availble      | @kzhang01        | #5743 |
| [mlflow/server/handlers.py#l726]                                 | entites       | @kzhang01        | #5743 |
| [mlflow/tracking/context/registry.py#L72]                        | dicitonary    | @kzhang01        | #5743 |
| [mlflow/tracking/request_header/registry.py#l56]                 | dicitonary    | @subramaniam02   | #5735 |
| [mlflow/store/artifact/s3_artifact_repo.py#l35]                  | consmption    | @subramaniam02   | #5735 |
| [tests/store/tracking/test_sqlalchemy_store.py#l2054]            | attibutes     | @subramaniam02   | #5735 |
| [mlflow/sklearn/__init__.py#l1518]                               | relatinoship  | @akaigraham      | #5746 |
| [mlflow/server/__init__.py#l17]                                  | intenrnal     | @akaigraham      | #5746 |
| [mlflow/fastai/__init__.py#l441]                                 | capabilites   | @akaigraham      | #5746 |
| [mlflow/sklearn/utils.py#l809]                                   | actuall       | @zhixuanevelynwu | #5747 |
| [tests/spark/autologging/ml/test_pyspark_ml_autologging.py#l747] | accruacy      | @zhixuanevelynwu | #5747 |

[dev/set_matrix.py#l304]: https://github.com/mlflow/mlflow/blob/22e69c3bdba7c4af616f6f0ce4e74821dc665b10/dev/set_matrix.py#L304
[mlflow/projects/databricks.py#l21]: https://github.com/mlflow/mlflow/blob/fe6618823a2e6038149ee0da675503d2764552ca/mlflow/projects/databricks.py#L213
[tests/store/tracking/__init__.py#l10]: https://github.com/mlflow/mlflow/blob/19e84f6cfd0c137925d113621bd7d96d610bb265/tests/store/tracking/__init__.py#L10
[dev/update_ml_package_versions.py#l122]: https://github.com/mlflow/mlflow/blob/19d34e0d49577e0903577bdc8d558f63975cc504/dev/update_ml_package_versions.py#L122
[dev/update_pypi_package_index.py#l3]: https://github.com/mlflow/mlflow/blob/258e0281026c3586b4f6bde6e2ee6b864d5c01f0/dev/update_pypi_package_index.py#L3
[mlflow/models/utils.py#l54]: https://github.com/mlflow/mlflow/blob/017674d2d9958298100a7b3ca3df443467446b30/mlflow/models/utils.py#L54
[mlflow/projects/utils.py#l186]: https://github.com/mlflow/mlflow/blob/c423e3ef6c648fdcdf1546d11e6768a536edfa85/mlflow/projects/utils.py#L186
[mlflow/server/handlers.py#l726]: https://github.com/mlflow/mlflow/blob/a274c5b7d540d05b5f7b9c512cdc3ac8b30f9498/mlflow/server/handlers.py#L726
[mlflow/tracking/context/registry.py#l72]: https://github.com/mlflow/mlflow/blob/19e84f6cfd0c137925d113621bd7d96d610bb265/mlflow/tracking/context/registry.py#L72
[mlflow/tracking/request_header/registry.py#l56]: https://github.com/mlflow/mlflow/blob/e78d6e90b0011b4ad33aa9cda84e8e0c7d202349/mlflow/tracking/request_header/registry.py#L56
[mlflow/store/artifact/s3_artifact_repo.py#l35]: https://github.com/mlflow/mlflow/blob/19a82fe7ea7c3ca7aa291741e6fa19ce5011d713/mlflow/store/artifact/s3_artifact_repo.py#L35
[tests/store/tracking/test_sqlalchemy_store.py#l2054]: https://github.com/mlflow/mlflow/blob/05f431081e4fdbad6a783a0c1a4e0d40345cb375/tests/store/tracking/test_sqlalchemy_store.py#L2054
[mlflow/sklearn/__init__.py#l1518]: https://github.com/mlflow/mlflow/blob/834194ad4d540d90ea714ec0b88b95d1a990f52f/mlflow/sklearn/__init__.py#L1518
[mlflow/server/__init__.py#l17]: https://github.com/mlflow/mlflow/blob/c98313482168137e39a6e6b0ed7169de5bfe0ba5/mlflow/server/__init__.py#L17
[mlflow/fastai/__init__.py#l441]: https://github.com/mlflow/mlflow/blob/834194ad4d540d90ea714ec0b88b95d1a990f52f/mlflow/fastai/__init__.py#L441
[mlflow/sklearn/utils.py#l809]: https://github.com/mlflow/mlflow/blob/017674d2d9958298100a7b3ca3df443467446b30/mlflow/sklearn/utils.py#L809
[tests/spark/autologging/ml/test_pyspark_ml_autologging.py#l747]: https://github.com/mlflow/mlflow/blob/fe6ee93bed24d9885abc2cad597ceade40091f32/tests/spark/autologging/ml/test_pyspark_ml_autologging.py#L747

**Comment by harupy** [comment]
For those willing to address this issue, please fix only one item per pull request.

**Comment by subramaniam02** [comment]
@harupy I am interested in this issue. Please let me know.

**Comment by harupy** [comment]
@subramaniam02 Thanks! Please let me know which items you would like to work on :)

**Comment by shaikmoeed** [comment]
@harupy I will work on [dev/set_matrix.py#l304](https://github.com/mlflow/mlflow/blob/22e69c3bdba7c4af616f6f0ce4e74821dc665b10/dev/set_matrix.py#L304), [mlflow/projects/databricks.py#L21](https://github.com/mlflow/mlflow/blob/fe6618823a2e6038149ee0da675503d2764552ca/mlflow/projects/databricks.py#L213), [tests/store/tracking/init.py#L10](https://github.com/mlflow/mlflow/blob/19e84f6cfd0c137925d113621bd7d96d610bb265/tests/store/tracking/__init__.py#L10)

**Comment by harupy** [comment]
@shaikmoeed Thanks, assigned them to you!

**Comment by lucalves** [comment]
@harupy I will work on [dev/update_ml_package_versions.py#L122](https://github.com/mlflow/mlflow/blob/19d34e0d49577e0903577bdc8d558f63975cc504/dev/update_ml_package_versions.py#L122), [dev/update_pypi_package_index.py#L3](https://github.com/mlflow/mlflow/blob/258e0281026c3586b4f6bde6e2ee6b864d5c01f0/dev/update_pypi_package_index.py#L3) and [mlflow/models/utils.py#l54](https://github.com/mlflow/mlflow/blob/017674d2d9958298100a7b3ca3df443467446b30/mlflow/models/utils.py#L54).

**Comment by harupy** [comment]
@lucalves Awesome, assigned them to you!

**Comment by kzhang01** [comment]
@harupy Hi I can work on [mlflow/projects/utils.py#l186](https://github.com/mlflow/mlflow/blob/c423e3ef6c648fdcdf1546d11e6768a536edfa85/mlflow/projects/utils.py#L186), [mlflow/server/handlers.py#l726](https://github.com/mlflow/mlflow/blob/a274c5b7d540d05b5f7b9c512cdc3ac8b30f9498/mlflow/server/handlers.py#L726), and  [mlflow/tracking/context/registry.py#L72](https://github.com/mlflow/mlflow/blob/19e84f6cfd0c137925d113621bd7d96d610bb265/mlflow/tracking/context/registry.py#L72)

**Comment by harupy** [comment]
@kzhang01 Thanks!

**Comment by subramaniam02** [comment]
@harupy I will work on rest of the files ? Thanks !

**Comment by harupy** [comment]
@subramaniam02 Yes!

**Comment by subramaniam02** [comment]
@harupy 
mlflow/tracking/request_header/registry.py#L56
mlflow/store/artifact/s3_artifact_repo.py#L35
/tests/store/tracking/test_sqlalchemy_store.py#L2054

**Comment by akaigraham** [comment]
Can I take these?
mlflow/sklearn/init.py#l1518
mlflow/server/init.py#l17
mlflow/fastai/init.py#l441

**Comment by harupy** [comment]
@akaigraham Yes!

**Comment by zhixuanevelynwu** [comment]
@harupy Hi! May I work on [mlflow/sklearn/utils.py#l809](https://github.com/mlflow/mlflow/blob/017674d2d9958298100a7b3ca3df443467446b30/mlflow/sklearn/utils.py#L809) and  [tests/spark/autologging/ml/test_pyspark_ml_autologging.py#l747](https://github.com/mlflow/mlflow/blob/fe6ee93bed24d9885abc2cad597ceade40091f32/tests/spark/autologging/ml/test_pyspark_ml_autologging.py#L747)?

**Comment by harupy** [comment]
@ zhixuanevelynwu Yes!
