### ISSUE TITLE
REST API document for mlflow version 1.25.1

### ISSUE THREAD

**Issue by Neethugkp** [mlflow/mlflow#5714]
Update the REST API document for mlflow version 1.25.1. (scenario 5)

Can you please help by providing request & response structure of api call
PUT //api/2.0/mlflow-artifacts/artifacts/2/ce16fe9ec5554f5486521479d7b6a975/artifacts/output.txt

**Comment by WeichenXu123** [comment]
You can see this file:
https://github.com/mlflow/mlflow/blob/master/mlflow/protos/mlflow_artifacts.proto

**Comment by Neethugkp** [comment]
@WeichenXu123 ,

Tried the below steps:-
Rest call:-    PUT /mlflow-artifacts/artifacts
                    parameter artifact_path


Output from client:-
HTTPError: 404 Client Error: Not Found for url: https://api_url/api/2.0/mlflow-artifacts/artifacts/2/f9fae9e8459b4d60a38ea20ce0a9ca8a/artifacts/output.txt

**Comment by WeichenXu123** [comment]
Could you try mlflow python API to see whether it work ? (In python code you should call `mlflow.set_tracking_uri` to set the correct tracking server uri first)

The rest API is used internally, and python API should be able to fulfill all your demands.

**Comment by Neethugkp** [comment]
with right datatype for parameters in API method solved the issue.

Thank you
