### ISSUE TITLE
Can not log_artifact to remote server???

### ISSUE THREAD

**Issue by WangMingJue** [mlflow/mlflow#572]
### System information
Remote Server: Centos 7.2
Local: MacOS 10.13.6
           Python 3.6.5 |Anaconda, Inc.|

### Code
Remote Server: mlflow server --file-store /tmp/MLFlow/ -h 0.0.0.0
Local:
   mlflow.tracking.set_tracking_uri("http://my_remote_server_ip:5000/")
   mlflow.start_run()
   mlflow.log_param("my", "param")
   mlflow.log_metric("score", 100)
   mlflow.log_artifact(local_path='output.txt')
   mlflow.end_run()

### Issue
The code of local running correctly, but i can not found that artifact file in /tmp/MLFlow/experiment_id/run_id/artifacts/

**Comment by DorIndivo** [comment]
I had the same issue, this code saving the artifact on the your local machine (macOS in this case) instead the remote server.

**Comment by whiletruelearn** [comment]
After executing the command for remote server `mlflow server --file-store /tmp/MLFlow/ -h 0.0.0.0` , can you check if you are able to access the mlflow UI through the tracking server url. 

This should be the same url that you set as the tracking uri

**Comment by ike-dai** [comment]
Hi, I have same error.

I try to use MLflow Project.

MLflow: 0.7.0
Python: 3.6.3

random_forest_sample/learning_job.py
```
#!/usr/bin/python3

import sklearn.datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import mlflow
import mlflow.sklearn
import sys

n_estimators = int(sys.argv[1]) if len(sys.argv) > 1 else 10
max_depth = int(sys.argv[2]) if len(sys.argv) > 2 else 5
random_state = int(sys.argv[3]) if len(sys.argv) > 3 else 71

iris = sklearn.datasets.load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=random_state)

model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, random_state=random_state)
model.fit(X_train, y_train)

print(model.predict(X_test))
score = model.score(X_test, y_test)

mlflow.start_run()
mlflow.set_tracking_uri('http://10.2.2.110:5000')
mlflow.log_param("n_estimatores", n_estimators)
mlflow.log_param("max_depth", max_depth)
mlflow.log_param("random_state", random_state)
mlflow.log_metric("score", score)
mlflow.sklearn.log_model(model, "ml_models")
mlflow.end_run()

```

random_forest_sample/MLproject
```
name: ProjectA

conda_env: conda.yaml

entry_points:
  main:
    parameters:
      n_estimators: {type: float, default: 10}
      max_depth: {type: float, default: 5}
      random_state: {type: float, default: 71}
    command: "python learning_job.py {n_estimators} {max_depth} {random_state}"
```

random_forest_sample/conda.yaml
```
name: ProjectA
channels:
  - defaults
dependencies:
  - python=3.6.3
  - numpy=1.14.5
  - pandas=0.23.3
  - scikit-learn=0.19.2
  - pip:
    - mlflow
```

At remote server, the mlflow tracking server is executed.

```
$ mlflow server --file-store /mlflow --port 5000 --host 0.0.0.0
```

I can access to web ui.
I can get success to execute python directly.

```
$ python random_forest_sample/learning_job.py
```

But, When I use mlproject run, I got failure..

```
$ mlflow run random_forest_sample -P n_estimators=15 -P max_depth=2 -P random_state=71

=== Created directory /tmp/tmp0w4bepel for downloading remote URIs passed to arguments of type 'path' ===
=== Running command 'source activate mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f && python learning_job.py 15 2 71' in run with ID '2152f0d9c96b4a82a06a7f0cf4b1d71b' === 
[2 0 1 1 1 1 0 2 2 2 2 0 0 1 0 0 2 1 1 1 1 0 1 1 1 2 2 2 2 2 2 0 0 2 0 1 1
 0 0 0 1 1 0 1 1]
API request to http://10.2.2.110:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

API request to http://10.2.2.110:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 1 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

API request to http://10.2.2.110:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 0 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

Traceback (most recent call last):
  File "learning_job.py", line 38, in <module>
    mlflow.log_param("n_estimatores", n_estimators)
  File "/home/ubuntu/anaconda3/envs/mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 174, in log_param
    run_id = _get_or_start_run().info.run_uuid
  File "/home/ubuntu/anaconda3/envs/mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 249, in _get_or_start_run
    return start_run()
  File "/home/ubuntu/anaconda3/envs/mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 105, in start_run
    active_run_obj = MlflowClient().get_run(existing_run_uuid)
  File "/home/ubuntu/anaconda3/envs/mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f/lib/python3.6/site-packages/mlflow/tracking/client.py", line 37, in get_run
    return self.store.get_run(run_id)
  File "/home/ubuntu/anaconda3/envs/mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 126, in get_run
    response_proto = self._call_endpoint(GetRun, req_body)
  File "/home/ubuntu/anaconda3/envs/mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 68, in _call_endpoint
    json=json_body)
  File "/home/ubuntu/anaconda3/envs/mlflow-15279de32928f0ea0ae0ce4eb82ef3271fcbd75f/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 53, in http_request
    (url, retries))
mlflow.exceptions.MlflowException: API request to http://10.2.2.110:5000/api/2.0/preview/mlflow/runs/get failed to return code 200 after 3 tries
=== Run (ID '2152f0d9c96b4a82a06a7f0cf4b1d71b') failed ===
```

remote server log
```
[2018-10-02 09:37:03,599] ERROR in app: Exception on /api/2.0/preview/mlflow/runs/get [GET]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/server/handlers.py", line 218, in _get_run
    response_message.run.MergeFrom(_get_store().get_run(request_message.run_uuid).to_proto())
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/store/file_store.py", line 296, in get_run
    run_info = self._get_run_info(run_uuid)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/store/file_store.py", line 310, in _get_run_info
    raise Exception("Run '%s' not found" % run_uuid)
Exception: Run '2152f0d9c96b4a82a06a7f0cf4b1d71b' not found
[2018-10-02 09:37:06,609] ERROR in app: Exception on /api/2.0/preview/mlflow/runs/get [GET]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/server/handlers.py", line 218, in _get_run
    response_message.run.MergeFrom(_get_store().get_run(request_message.run_uuid).to_proto())
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/store/file_store.py", line 296, in get_run
    run_info = self._get_run_info(run_uuid)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/store/file_store.py", line 310, in _get_run_info
    raise Exception("Run '%s' not found" % run_uuid)
Exception: Run '2152f0d9c96b4a82a06a7f0cf4b1d71b' not found
[2018-10-02 09:37:09,617] ERROR in app: Exception on /api/2.0/preview/mlflow/runs/get [GET]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/server/handlers.py", line 218, in _get_run
    response_message.run.MergeFrom(_get_store().get_run(request_message.run_uuid).to_proto())
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/store/file_store.py", line 296, in get_run
    run_info = self._get_run_info(run_uuid)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mlflow/store/file_store.py", line 310, in _get_run_info
    raise Exception("Run '%s' not found" % run_uuid)
Exception: Run '2152f0d9c96b4a82a06a7f0cf4b1d71b' not found
```

Should I set any other settings?

Best regards.

**Comment by whiletruelearn** [comment]
Are you able to access `http://10.2.2.110:5000` from browser 

From the logs  it looks there is some issue while connecting to server
`mlflow.exceptions.MlflowException: API request to http://10.2.2.110:5000/api/2.0/preview/mlflow/runs/get failed to return code 200 after 3 tries`

**Comment by WangMingJue** [comment]
> After executing the command for remote server `mlflow server --file-store /tmp/MLFlow/ -h 0.0.0.0` , can you check if you are able to access the mlflow UI through the tracking server url.
> 
> This should be the same url that you set as the tracking uri

I can access the mlflow UI and log_param, log_metric, but i can not put .txt to remote server

**Comment by ike-dai** [comment]
Thank you for reply.

Yes, I can connect to Tracking server web ui from browser and from curl command in cli.
And when I execute this learning_job.py script with python command, tracking info is registered correctly.
So, I think that this python code can access to tracking server uri.

Furthermore, I executed tracking server and ml project run at the same server, but "mlflow run" received the same error...

**Comment by hamroune** [comment]
may be somehting tied to Permissions/Rights? may you choose something other than /tmp for the server?

**Comment by harmw** [comment]
Running into the same issue here, when trying to `mlflow.sklearn.log_model()`. I've started my remote tracking server with `--file-store /tmp/mlruns --default-artifact-root /tmp/artifacts` though I can see the `.pkl` file being created on my **local machine**, under `/tmp/`.

Try the following in your code:
`print(mlflow.get_artifact_uri())`

Output:
`/tmp/artifacts/0/c6609d80cb78431a84ce846761106145/artifacts`

**Comment by smurching** [comment]
Apologies for the delayed response - MLflow doesn't currently support logging artifacts to the local filesystem of a remote tracking server. This is because artifacts are actually written by the client, which just obtains an artifact location to write to from the tracking server. Instead, we recommend launching your tracking server with ``--default-artifact-root`` set to an artifact location accessible to both the tracking server & the client, e.g. an S3 bucket URI. See the [tracking docs](https://mlflow.org/docs/latest/tracking.html#storage) and [this SO post](https://stackoverflow.com/questions/52331254/how-to-store-artifacts-on-a-server-running-mlflow) for more information.

Also one gotcha worth noting from the SO post:

> Note that the server uses ``--default-artifact-root`` only when assigning artifact roots to newly-created experiments - runs created under existing experiments will use an artifact root directory under the existing experiment's artifact root.

So you'll need to create a new experiment for the artifact root change to take place. Thanks all for discussing this, it's come up a few times - I'd suggest these simple changes to make using `log_artifact` smoother:

* Log a warning when `mlflow server` is run without ``--default-artifact-root`` (and eventually, require `--default-artifact-root`)
* Log the artifact path being used when `log_artifact` is called.

**Comment by bertomartin** [comment]
The docs here (https://www.mlflow.org/docs/latest/tracking.html#amazon-s3) state that you can use a minio server for logging. If I'm running the server in a docker container, should I be setting the environment variable in the container? Can I do this through the python api?

**Comment by smurching** [comment]
@bertomartin sorry for the super late response, yep you should be setting the environment variable in the container. BTW, nowadays for questions of this sort we recommend asking in https://stackoverflow.com/tags/mlflow/

**Comment by mparkhe** [comment]
As per @smurching 's [comment above](https://github.com/mlflow/mlflow/issues/572#issuecomment-427718078), support for remote logging is supported through `--default-artifact-root`. Refer [docs](https://mlflow.org/docs/latest/tracking.html#artifact-stores) for for support for various type of artifact store types.

**Comment by mirekphd** [comment]
> As per @smurching 's [comment above](https://github.com/mlflow/mlflow/issues/572#issuecomment-427718078), support for remote logging is supported through `--default-artifact-root`. Refer [docs](https://mlflow.org/docs/latest/tracking.html#artifact-stores) for for support for various type of artifact store types.

I'd argue, that there is still no support for uploading artifacts to server side. Like for instance it is with H2O, which uses separate functions for remote and local actions (download / upload vs import / save). NFS is not remote if it has to be mounted locally on the client side... One needs yet another server apart from `mlflow server` or else our most important artifacts will be dispersed in local users folders, siloed, passworded, or manually deleted as the `./mflow` folder is not hidden...

Compared to H2O, where one can upload data to a training server and then download trained models from the server, even using a browser, without any scripting (and without having to set up another server such as NFS), remote storage of artifacts in MLflow Tracking is non-existent.

**Comment by H4dr1en** [comment]
> remote storage of artifacts in MLflow Tracking is non-existent.

Is it still true?

**Comment by mirekphd** [comment]
> > remote storage of artifacts in MLflow Tracking is non-existent.
> 
> Is it still true?
Yes, in the sense that an object storage server like minio is needed to perform the storage of artifacts, which must be first saved locally to a temporary folder and then uploaded by the mlflow python client directly to the s3 endpoint. To provide universal storage support neither client nor server have anything to do with minio client (a separate package) or server (a minio container is required as a server and boto3 package dependencies are on both sides: the python client system and the mlflow container). This is a completely opposite design paradigm than in case of H2O: loose coupling / microservices architecture as opposed to bundling all features into a monolithic application. I'm running 4 separate containers, including nginx as a reverse proxy purely for authentication. Compare and contrast with H20, which any 20-year old intern with some basic R could put up and use within minutes...

**Comment by monicatao** [comment]
Hi, is there any update for this so far? Can we log artifacts on server now?

**Comment by mauvilsa** [comment]
Is there a feature request to support logging artifacts on a remove mlflow server? This seems to me an obvious feature that many people would like to have.

**Comment by AllieUbisse** [comment]
# Logging Plugin
---

Please help me with creating a custom plugin to log the current running notebook and also log .py to a remote server.

**Comment by ozichert** [comment]
You can bypass this issue by using volumes if working with docker containers.

**Comment by UnoYakshi** [comment]
> 
> 
> You can bypass this issue by using volumes if working with docker containers.

Can you elaborate? I couldn't manage to run a remote server and log artefacts to it. Instead, the client (Python MLflow API) is trying to write to the client's local storage with the **path I defined in a docker container**.

My `docker-compose.yml` looks like:
```docker-compose
services:
    db:
        <PostgreSQL set-up>
    web:
        build: mlflow
        restart: always
        image: mlflow_server
        container_name: mlflow_server
        ports:
            - "5000":"5000"
        depends_on:
            - db
        volumes:
            - ./mlruns:/var/lib/mlflow/mlruns
        command: "mlflow server
                           --backend-store-url postgresql://...
                           --default-artifact-root /var/lib/mlflow/mlruns
                           --host 0.0.0.0"
```
Even if I put `file://<remote's IP>/var/lib/mlflow/mlruns` it still tries to write artifacts to the client's `/var/lib/mlflow/mlruns` (for which it doesn't have access).

Note: I have a simple `Dockerfile` in `<workdir>/mlflow/mlflow`.

**Comment by ozichert** [comment]
This is how it works on my local machine as NFS variant. The clients artifacts folder has to be the same as the folder of the mlflow container. This is achieved by a volume. Additionally you have to change the command property to `--default-artifact-root /mlflow/` since it is the property that is returned by the get_artifact_url function in python.

`
services:
  dsplatform-postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - /postgres/data:/var/lib/postgresql/data
    restart: always
  dsplatform-mlflow:
    build: ./mlflow
    ports:
      - 5000:5000
    volumes:
      - ./artifacts/:/mlflow
      - /opt/mlflow/scripts
    restart: always
    depends_on:
      - dsplatform-postgres
  dsplatform-jupyter:
    image: jupyter/base-notebook:python-3.8.5
    environment:
      PASSWORD: "${JUPYTER_PASSWORD}"
    ports:
      - 8888:8888
    volumes:
      - ./artifacts/:/mlflow
    restart: always
`

**Comment by qcha41** [comment]
Having the same problem using mlflow on an EC2 instance without S3 storage. So I will try with an S3 storage now.

**Comment by jparkhill** [comment]
> Is there a feature request to support logging artifacts on a remove mlflow server? This seems to me an obvious feature that many people would like to have.

Yeah. Gotta agree... I hardly see the purpose of MLflow beyond a per-experiment key-value store without this feature. You'd pretty much be better off writing your own with FastAPI or something.

**Comment by YJonmo** [comment]
Yes I did and it also hung and did nothing.
Could it be the server's firewall blocking the port connection?

**Comment by ghost** [comment]
Any update on this, can this be done without minio?
