### ISSUE TITLE
Unable to access mlflow client functions outside Databricks

### ISSUE THREAD

**Issue by manishpyy** [mlflow/mlflow#5770]
I am unable to access the mlflow client functions outside Databricks environment. For example, to list the experiments in an mlflow server, using the get_experiment_by_name() function, I am getting unauthorized error 401. I am also setting the 'DATABRICKS_HOST', 'DATABRICKS_TOKEN' environment variables as well.

os.environ['MLFLOW_TRACKING_URI'] = 'databricks'
os.environ['DATABRICKS_HOST'] = https://adb-(workspace-id).azuredatabricks.net/
os.environ['DATABRICKS_TOKEN'] = (token generated from databricks)
exp_name = '/Users/(username)/(experiment name)'

mlflow_client = mlflow.tracking.MlflowClient(tracking_uri=(databricks uri))
mlflow_client.get_experiment_by_name(exp_name)

Could you kindly advise if I am missing anything?
Thanks.

**Comment by harupy** [comment]
@manishpyy Can you run this code?

```python
with mlflow.start_run():
  padd
```

**Comment by manishpyy** [comment]
I am still getting 401 unauthorized error.

**Comment by harupy** [comment]
Is your token valid?

**Comment by manishpyy** [comment]
Yes, when I do a GET request using the token as bearer token, it gives the output

headers = {"Authorization": "Bearer %s" %db_auth_token}
experiments_list = requests.get(databricks_tracking_uri+'api/2.0/mlflow/experiments/get-by-name',
 params={'view_type':'ALL','experiment_name': '/Users/username/exp-name'}, headers=headers)

When I am trying to acheive the same using the get_experiment_by_name function, getting 403 forbidden error.

**Comment by harupy** [comment]
Can you try this?

```python
mlflow_client = mlflow.tracking.MlflowClient(tracking_uri="databricks")
```

**Comment by manishpyy** [comment]
oh yes, got it. So I had to set the tracking uri as just 'databricks', before this I was setting the uri as the entire databricks url. Thank you for your help.

**Comment by harupy** [comment]
You're welcome!

**Comment by prabhatgup** [comment]
Thanks this also helped me
