### ISSUE TITLE
Upload model and artifacts to a mlflow server

### ISSUE THREAD

**Issue by manishpyy** [mlflow/mlflow#5771]
I have the artifacts/model in my local computer. I am able to create a registered model using the mlflow REST API, but is there any way to transfer this artifacts/model to the mlflow server (in databricks) from my local machine?

**Comment by WeichenXu123** [comment]
Could you try this rest API ?
https://github.com/mlflow/mlflow/blob/43237e94af2f52b16776a72c72c12423762a0b37/mlflow/protos/mlflow_artifacts.proto#L4

**Comment by WeichenXu123** [comment]
You can see this doc page:
https://docs.databricks.com/applications/mlflow/access-hosted-tracking-server.html

to config your local mlflow to connect to databricks mlflow server,

then run `mlflow.log_artifact` uri in your local machine, it will log files to databricks mlflow server.

Thank you.
