### ISSUE TITLE
Providing notice of Stable Baselines3 PR around automated MLflow logging integration

### ISSUE THREAD

**Issue by git-thor** [mlflow/mlflow#5783]
Please refer with feedback, discussions or support to https://github.com/DLR-RM/stable-baselines3/pull/889

**Comment by dbczumar** [comment]
Hi @git-thor. Thank you for the notice. In contrast to the recommendation from @araffin here https://github.com/DLR-RM/stable-baselines3/pull/889#issuecomment-1110638553, we would prefer that this functionality be contributed directly to Stable Baselines3 or to separate package / repository. Thank you for your interest in MLflow!
