### ISSUE TITLE
[BUG] "exception Object of type _EnvManager is not JSON serializable" when I execute "mlflow run -b databricks" MLFlow 1.25.1

### ISSUE THREAD

**Issue by momoa16** [mlflow/mlflow#5791]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [X] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks runtime version 9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12) 
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.25.1
- **Python version**: 3.8.10
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

```
%sh

echo -e "[DEFAULT]\nhost = https://XYZ.azuredatabricks.net/\ntoken = MyToken\njobs-api-version = 2.1" > ~/.databrickscfg

mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=5.0 --experiment-id 1234567890 --backend databricks --backend-config cluster_conf.json
```

### Describe the problem
When I execute "mlflow run" with a databricks backend I receive the error "exception Object of type _EnvManager is not JSON serializable" with MLFlow version 1.25.1. The same command is running fine with MLFlow version 1.24.0

### Tracking information

For bugs related to the tracking features (e.g. mlflow should log a run in my database but it doesn't), please insert the following code in your python script / notebook where you encountered the bug and run it:

```python
print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())
```

Then, make sure the printed out information matches what you expect and paste it (with sensitive information masked) in the box below:

```
```

If you know the command that was used to launch your tracking server (e.g. `mlflow server -h 0.0.0.0 -p 5000`), please provide it:

```
```

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [x] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@momoa16 Thanks for reporting this issue. I was able to reproduce the error. Can you try installing a development version of mlflow from the master branch and check if it works?

```
pip install git+https://github.com/mlflow/mlflow.git
```

**Comment by momoa16** [comment]
The error disappeared with the version on git (mlflow==1.25.2.dev0) with "--env-manager local"
If no --env-manager is specified execution fails with error --env-manager is "" expecting local or conda.

**Comment by harupy** [comment]
@momoa16 

> If no --env-manager is specified execution fails with error --env-manager is "" expecting local or conda.

Could you share the command you used?

**Comment by momoa16** [comment]
Yes, I wasn't using --env-manager at all, expecting conda to be used as default as specified in https://mlflow.org/docs/latest/cli.html#mlflow-run,  "If unspecified, default to conda"

**Comment by harupy** [comment]
@momoa16 Got it, is the `mlflow run ` command printed out somewhere in stdout or stderr?

**Comment by harupy** [comment]
I was able to reproduce the error. Investigating what's causing this error.

**Comment by harupy** [comment]
Identified the root cause. When `--env-mangaer` is unspecified, `mlflow_run_arr` looks like `[..., "--env-manager", "''"]` because `env_manager` is `None` and `shlex_quote` returns `''`:

https://github.com/mlflow/mlflow/blob/d9058fcddb47f473dacd6435f4b4fa96c370935b/mlflow/projects/databricks.py#L330-L344

**Comment by harupy** [comment]
👆👆👆 Filed a PR
