### ISSUE TITLE
Question: Mlflow metrics with distributed training using pytorch/tensorflow

### ISSUE THREAD

**Issue by mChowdhury-91** [mlflow/mlflow#5798]
I would like to know if there is any documentation or example for logging mlflow metrics with distributed training using tensorflow or pytorch.

**Comment by dbczumar** [comment]
@shrinath-suresh Do you have example references for distributed training? I see that https://medium.com/pytorch/mlflow-and-pytorch-where-cutting-edge-ai-meets-mlops-1985cf8aa789 mentions the existence of such examples, but https://github.com/mlflow/mlflow/blob/master/examples/pytorch/BertNewsClassification/bert_classification.py doesn't seem to contain distributed example content.

**Comment by shrinath-suresh** [comment]
@dbczumar [MNIST example](https://github.com/mlflow/mlflow/tree/master/examples/pytorch/MNIST) can be used as a reference . `python mnist_autolog_example.py --max_epochs 1 --gpus 2 --strategy ddp` trains the model in multi gpu mode.

In latest version of PTL the backend name has changed from `accelerator` to `strategy`. I have issued a [PR](https://github.com/mlflow/mlflow/pull/5816) and attached the CPU, multi GPU logs for both MNIST and bert example.

**Comment by dbczumar** [comment]
Thanks so much, @shrinath-suresh ! I've approved your PR. I'll go ahead and close out this issue; thank you for providing these examples to @mChowdhury-91 and the rest of the community!

**Comment by mChowdhury-91** [comment]
@shrinath-suresh Thank you for sharing the example. I've a follow-up question to this example. 
If I run this on 2 gpu's, will the autolog not create 2mlflow logs, what is the best practice? Should the logs be created from master?
