### ISSUE TITLE
[DOC-FIX] mlflow.set_experiment() code example (fluent API)

### ISSUE THREAD

**Issue by anjakuchenbecker** [mlflow/mlflow#5804]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [ ] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [x] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://mlflow.org/docs/latest/_modules/mlflow/tracking/fluent.html#set_experiment
https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/fluent.py

### Description of proposal (what needs changing):
Provide a clear description. Why is the proposed documentation better?

Change documentation / code example from 

```
import mlflow
# Set an experiment name, which must be unique and case sensitive.
mlflow.set_experiment("Social NLP Experiments")
# Get Experiment Details
experiment = mlflow.get_experiment_by_name("Social NLP Experiments")
print("Experiment_id: {}".format(experiment.experiment_id))
print("Artifact Location: {}".format(experiment.artifact_location))
print("Tags: {}".format(experiment.tags))
print("Lifecycle_stage: {}".format(experiment.lifecycle_stage))
```
to 

```
import mlflow
# Set an experiment name, which must be unique and case sensitive.
experiment = mlflow.set_experiment("Social NLP Experiments")
# Get Experiment Details
print("Experiment_id: {}".format(experiment.experiment_id))
print("Artifact Location: {}".format(experiment.artifact_location))
print("Tags: {}".format(experiment.tags))
print("Lifecycle_stage: {}".format(experiment.lifecycle_stage))
```
As the mlflow.set_experiment returns an instance of [mlflow.entities.Experiment](https://mlflow.org/docs/latest/python_api/mlflow.entities.html#mlflow.entities.Experiment) representing the new active experiment, there is no need to use ```mlflow.get_experiment_by_name(...)``` in addition within the code example.

**Comment by ketangangal** [comment]
I am willing to fix this issue!

**Comment by ketangangal** [comment]
I have fixed the issue and created a pull request.

**Comment by ketangangal** [comment]
#5808

**Comment by dbczumar** [comment]
Thanks so much, @ketangangal @anjakuchenbecker ! This is an excellent docs improvement!
