### ISSUE TITLE
[BUG] Delete temporary directory and its content created by mlflow.pytorch.load_state_dict

### ISSUE THREAD

**Issue by agarfau** [mlflow/mlflow#5814]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Buster (docker image python:3.9-slim-buster)
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.24.0
- **Python version**: 3.9.10

### Describe the problem

**Actual behaviour**
The function `mlflow.pytorch.load_state_dict(...)` always creates a temporary directory using `tempfile.mkdtemp`. The latter's documentation says:
>Caller is responsible for deleting the directory when done with it.

This deletion is not carried out in mlflow, which in my case resulted in filling up disk space because of accumulated temporary directories.

**Expected behaviour**
After calling `torch.load(state_dict_path, **kwargs)` within `mlflow.pytorch.load_state_dict(...)`, the temporary directory and all its content should be automatically deleted, since the user does not have access to these files.

### Code to reproduce issue

```python
with mlflow.start_run():
    artifact_path = "model"
    mlflow.pytorch.log_state_dict(model.state_dict(), artifact_path)
    state_dict_uri = mlflow.get_artifact_uri(artifact_path)

state_dict = mlflow.pytorch.load_state_dict(state_dict_uri)
```

**Comment by dbczumar** [comment]
@agarfau These contents are downloaded to a temporary directory, and temp directories are eventually removed by the OS. The reason we do not remove files immediately after they are read into memory is that it's hard to determine whether or not the API used to load the files into memory might try to access them later; for example, some frameworks incrementally read model contents from a directory of files as needed.

If you want to control removal of these files, we recommend first downloading them via `mlflow.artifacts.download_artifacts()` and cleaning up the returned path when you're done using them. Thank you for using MLflow! :)
