### ISSUE TITLE
[FR] Allow passing pathlib.Path to set_tracking_uri

### ISSUE THREAD

**Issue by cacharle** [mlflow/mlflow#5820]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

It would be intuitive that we could pass the standard library's paths object to `set_tracking_uri`.

It's also easy to implement, we just have to call `path.as_uri()`.

I assume there is other places where the user can pass an uri, would be nice if the behavior could be uniform across the API.

#### What is the use case for this feature?

```python
from pathlib import Path
path = Path("foo/bar")
mlflow.set_tracking_uri(path / "baz")
mlflow.start_run()
```

currently outputs:

```
AttributeError: 'PosixPath' object has no attribute 'decode'
```

#### Why is this use case valuable to support for MLflow users in general?

It's intuitive that this would work.

#### Why is this use case valuable to support for your project(s) or organization?

Our team has some standard path stored in `Path` instead of strings (e.g a standard path to store mlflow results).

#### Why is it currently difficult to achieve this use case?

It's not, but it is confusing that it isn't supported

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @cacharle , thank you for raising this feature request. We'd be happy to review a PR that implements it. Thank you in advance for your contribution!

**Comment by jhallard** [comment]
Why are we using `pathlib.Path` to represent a URI? `pathlib.Path("http://localhost:5000").as_uri()` doesn't even appear to work

**Comment by cacharle** [comment]
@jhallard I use it to represent paths, not URI.

```python
>>> p =  Path("foo/bar")
>>> p.resolve().as_uri()
'file:///Users/me/foo/bar'
```

**Comment by jhallard** [comment]
> @jhallard I use it to represent paths, not URI.
> 
> ```python
> >>> p =  Path("foo/bar")
> >>> p.resolve().as_uri()
> 'file:///Users/me/foo/bar'
> ```

Yes, but tracking servers aren't at local file paths..

**Comment by cacharle** [comment]
Not sure I understand, I just use  `set_tracking_uri` to change where the logs and artifacts are stored on the disk (I don't use a remote server)
