### ISSUE TITLE
Support inference script for serving models

### ISSUE THREAD

**Issue by saichandrapandraju** [mlflow/mlflow#5821]
Hi,

I trained a model and it is saved using MLFlow's autologging api. Now I can call `mlflow models serve` to serve the model. 
However, there is no way I can pass an inference script to control the `predict` call of the model (eg. I may preprocess the data before predict call). 

Could anyone plz suggest how can I add a custom inference script while deploying..?

**Comment by dbczumar** [comment]
Hi @saichandrapandraju. Great question! We recommend following the guidance in https://mlflow.org/docs/latest/models.html#custom-python-models. Once you've logged a model with autologging, you can follow these instructions to create a new model based on your logged model that adds preprocessing / postprocessing capabilities. Please let me know if you have any questions, and thank you for using MLflow!

**Comment by saichandrapandraju** [comment]
Hi @dbczumar , Thanks for the reply!

You're suggesting to create a new python model with inference logic and log this model before deploying. Is my understanding correct ?

But what if I want to add inference script on-the-fly while deploying ? 
The main reason for asking this is - 
I will have multiple runs and delegate logging (params, metrics, artifacts) to MLflow. 
After multiple runs, I register a model with best performance. Now if I want to deploy the model using `model_name` and `version` AND want to control the inference logic, I couldn't find a way to add a custom script.
