### ISSUE TITLE
Is it possible to show multiple experiments stored in different folders?

### ISSUE THREAD

**Issue by Jingnan-Jia** [mlflow/mlflow#5828]
### Discussed in https://github.com/mlflow/mlflow/discussions/5827

<div type='discussions-op-text'>

<sup>Originally posted by **Jingnan-Jia** May  7, 2022</sup>
Hi, I am runing multiple different projects and want to track them. The structures are like：

Project1
- docs
- source_code
  - main.py
  - mlruns
    - 0
      - a6de16f6cb134095b607967b20eff70e
      - a6de16f6cb134095b607967b20eff70f
    - 1 

Project2
- docs
- source_code
  - main.py
  - mlruns
    - 0
      - b6de16f6cb134095b607967b20eff70e
      - c6de16f6cb134095b607967b20eff70f
    - 1 

At present, I can not see all the experiments and runs in the two different projects from mlflow UI at the same time. I have to navigate to Project1/source_code and run `mlflow ui` to see the experiments and runs for Project1, then navigate to Project2/source_code and run `mlflow ui` again to see the experiments and runs for Project2. 

However, I want to see that all the experiments and runs in the two different projects can be shown in mlflow UI at the same time. How to achieve it?</div>

**Comment by harupy** [comment]
@Jingnan-Jia https://github.com/mlflow/mlflow/pull/5822 is going to support viewing runs from different experiments. To use this feature, project 1 and 2 need to log runs in the same tracking server.

```python
# main.py in project1

mlflow.set_tracking("file:///path/to/mlruns")
```

```python
# main.py in project2

mlflow.set_tracking("file:///path/to/mlruns")
```

**Comment by harupy** [comment]
@Jingnan-Jia 

> By the way, apart from the code method, I think it would be better if there is a button on the UI of mlflow like "Load/Import Experiment" from which we can select the directory which saves the other experiments.

I think this is challenging because the tracking server can take a look at a single tracking URI. Let's say two people (A and B) are sharing the tracking server and viewing experiments in the tracking URI X. If A switches the tracking URI to Y, it would change what B is viewing.
