### ISSUE TITLE
[BUG] mlflow autologging with mlflow skinny broken in recent versions

### ISSUE THREAD

**Issue by temporaer** [mlflow/mlflow#5839]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: linux ubuntu 
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.25.1
- **Python version**: 3.7.11
- **npm version, if running the dev UI**: n/a

### Describe the problem

When installing mlflow-skinny and launching `mlflow.autolog()`, an ImportError occurs (see below for trace).
Note that this worked in earlier versions of mlflow skinny, e.g. 1.20.0. 1.22.0 seems to be the last version where it's working.

### Code to reproduce issue

```bash
$ pip install mlflow-skinny
```
```python
import mlflow; mlflow.autolog()
```

### Other info / logs

```python-traceback
>>> import mlflow; mlflow.autolog()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/mlflow/utils/autologging_utils/__init__.py", line 416, in autolog
    return _autolog(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 1574, in autolog
    from mlflow import (
  File "/opt/conda/lib/python3.7/site-packages/mlflow/tensorflow/__init__.py", line 26, in <module>
    import mlflow.keras
  File "/opt/conda/lib/python3.7/site-packages/mlflow/keras.py", line 21, in <module>
    from mlflow import pyfunc
  File "/opt/conda/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 228, in <module>
    from mlflow.models import Model, ModelSignature, ModelInputExample
ImportError: cannot import name 'ModelInputExample' from 'mlflow.models' (/opt/conda/lib/python3.7/site-packages/mlflow/models/__init__.py)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@temporaer I think this line fails:

https://github.com/mlflow/mlflow/blob/c577c7f199d9efa076344785dabb2121edb7e6c8/mlflow/models/__init__.py#L44


Can you install `scipy` and run `mlflow.autolog` again?

**Comment by temporaer** [comment]
Oh wow, it does work, thank you! I'm installing mlflow-skinny because i don't want heavy dependencies. Is scipy really always needed for autolog? Can we defer the import? Also even if that's not possible, could we print a more obvious error message?

**Comment by harupy** [comment]
> Is scipy really always needed for autolog?

Good question. No, it's needed only when you're using sparse matrices.
