### ISSUE TITLE
[BUG] MLflow UI 1.25.1 "No Experiments Exist" bug

### ISSUE THREAD

**Issue by grybeck** [mlflow/mlflow#5849]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux 7
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.25.1
- **Python version**: 3.9.7
- **npm version, if running the dev UI**:

### Describe the problem

When I go to the mlflow 1.25.1 UI and click on MLflow in the top left corner, I get the following screenshot:
![Screen Shot 2022-05-11 at 4 12 46 PM](https://user-images.githubusercontent.com/6519271/167939510-5ec22c81-a91b-47f3-9b55-469e24a8aff9.png)
The default experiment clearly exists and yet it gives this error.

### Code to reproduce issue

go to localhost:5000

Running in docker with postgres backend

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by grybeck** [comment]
We believe the issue is from this change: https://github.com/mlflow/mlflow/pull/5504/files#diff-e9c073048d4146ed9784ee913351e44b92d5c88dcb55366e96d32e07d32d8f08

**Comment by harupy** [comment]
@grybeck How did you launch your tracking server? Did you use `--backend-store-uri` like


```
mlflow server --backend-stre-uri <postgres URI> ...
```

?

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/5504/files#diff-e9c073048d4146ed9784ee913351e44b92d5c88dcb55366e96d32e07d32d8f08 is probably not the cause of this issue because it didn't change how MLflow UI fetches experiments.

**Comment by grybeck** [comment]
this bug did not occur in 1.24.1 with the same `mlflow server --backend-stre-uri <postgres URI> ` start up command

**Comment by harupy** [comment]
@grybeck I was able to reproduce the issue and filed https://github.com/mlflow/mlflow/pull/5859
