### ISSUE TITLE
[BUG]sftp Artifact  password not work 

### ISSUE THREAD

**Issue by trillionmonster** [mlflow/mlflow#5855]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 20.04
- **MLflow installed from (source or binary)**:binary
- **MLflow version (run ``mlflow --version``)**:1.25.1
- **Python version**:3.9
- **npm version, if running the dev UI**:no

### Describe the problem

sftp Artifact not work when the Artifact root is sftp://root@password .......

password not work ,and it seem to find hostkeys 

my solution is add code to mlflow/mlflow/store/artifact/sftp_artifact_repo.py line 69 

```
if self.get("password") is not None:
                
      self.config["cnopts"] = pysftp.CnOpts()
      self.config["cnopts"].hostkeys = None
```

### Code to reproduce issue

```
mlflow server -h 0.0.0.0 -p 5000 --default-artifact-root sftp://root:132456@127.0.0.1/mlflow-root/

```

```
import mlflow
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.startrun()
mlflow.log_dict({"test_sftp":1},"test.json")
```

### Other info / logs

```
>>> mlflow.log_dict({"test_sftp":1},"test.json")
/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 787, in log_dict
    MlflowClient().log_dict(run_id, dictionary, artifact_file)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1094, in log_dict
    json.dump(dictionary, f, indent=2)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1020, in _log_artifact_helper
    self.log_artifact(run_id, tmp_path, artifact_dir)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 329, in log_artifact
    artifact_repo = self._get_artifact_repo(run_id)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 314, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 107, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 73, in get_artifact_repository
    return repository(artifact_uri)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/mlflow/store/artifact/sftp_artifact_repo.py", line 69, in __init__
    self.sftp = pysftp.Connection(**self.config)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/pysftp/__init__.py", line 132, in __init__
    self._tconnect['hostkey'] = self._cnopts.get_hostkey(host)
  File "/opt/anaconda3/envs/mlflow/lib/python3.9/site-packages/pysftp/__init__.py", line 71, in get_hostkey
    raise SSHException("No hostkey for host %s found." % host)
paramiko.ssh_exception.SSHException: No hostkey for host 127.0.0.1 found.
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
This is a known issue: https://stackoverflow.com/questions/38939454/verify-host-key-with-pysftp

**Comment by trillionmonster** [comment]
> This is a known issue: https://stackoverflow.com/questions/38939454/verify-host-key-with-pysftp

yes,but still exist

**Comment by harupy** [comment]
Can you try downgrading pysftp?

```
pip install pysftp==0.2.8
```

**Comment by trillionmonster** [comment]
> 

I just add three lines code as Describe

**Comment by harupy** [comment]
@trillionmonster 

See https://stackoverflow.com/a/43389508

> If you want to keep using pysftp, do not set cnopts.hostkeys = None (as the second most upvoted answer shows), unless you do not care about security. You lose a protection against [Man-in-the-middle attacks](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) by doing so.

**Comment by trillionmonster** [comment]
@harupy 
I suggest you do it my way, same as this https://stackoverflow.com/a/43389508

**Comment by harupy** [comment]
https://stackoverflow.com/a/43389508 doesn't recommend your approach.

**Comment by harupy** [comment]
Can you set up key-based authentication?

**Comment by trillionmonster** [comment]
> Can you set up key-based authentication?

we are not talking about how to set up authentication , the better way to limit authentication method is deleting the code of reading password .

**Comment by harupy** [comment]
@trillionmonster 

Have you tried `pysftp=0.2.8` as I suggested?

```
import pysftp
import time

# Run an SFTP server before running this script:
# docker run -p 2222:22 -d atmoz/sftp foo:pass:::upload


with pysftp.Connection("localhost", username="foo", password="pass", port=2222) as sftp:
    print(sftp.listdir())
```

works with `pysftp=0.2.8` but doesn't with `pysftp=0.2.9`?

**Comment by harupy** [comment]
@trillionmonster gentle ping

**Comment by harupy** [comment]
@trillionmonster Feel free to reopen this ticket if you're still experiencing the issue.

**Comment by HitHereX** [comment]
sorry if it was rude for somebody else to come and ask for a closed issue.
If opening new issue is right and link this page, feel free to tell me. I will follow your suggestion.

I am experiencing same error on same **mlflow version 1.25.1**
tried downgrading to **pysftp=0.2.8** but it gives paramiko error like below:

```paramiko.ssh_exception.SSHException: Unable to connect to xx.xx.xxx.xx: [Errno 110] Connection timed out```

the only possible cause for me is that **I am trying to connect to mlflow server on the same device.**
(which means mlflow server~ command and mlflow.log_model() was ran on same device, different cmd windows)

```mlflow server --backend-store-uri postgresql://mlflow_user:mlflow@localhost/mlflow_remote --default-artifact-root sftp://sftpuser:password@49.50.164.14/mlruns -p 2247 --host 0.0.0.0```

can it cause a problem? 

and can you please give me a bit detailed explaination about 'IT WORKS WITH PYSFTP==0.2.8'

i tried your test code above and it gave me error like this:
```
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

please feel free to tell me any lack of info.
thanks in advance.
