### ISSUE TITLE
[FR] support pyspark.ml.autolog read log_model_allowlist file from storage

### ISSUE THREAD

**Issue by serena-ruan** [mlflow/mlflow#5862]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Update pyspark.ml.autolog's behavior to accept log_model_allowlist file that's stored in storage like S3 or Azure blob storage. 

#### What is the use case for this feature?
Let pyspark.ml.autolog accept log_model_allowlist file from most storage including S3, Azure blob storage, etc.

#### Why is this use case valuable to support for MLflow users in general?
Take databricks for example, we need to set cluster spark configuration of `spark.mlflow.pysparkml.autolog.logModelAllowlistFile` to point to the file, and if we support reading from whatever storage then this config can accept link to files stored outside of dbfs.

#### Why is this use case valuable to support for your project(s) or organization?
Make the updating log_model_allowlist file process easier, and for specific libraries we can provide a default link that users could point to without downloading & uploading themselves.

#### Why is it currently difficult to achieve this use case?
Currently pyspark.ml.autolog is reading log_model_allowlist file using python's `open` function, which only supports reading files from local disk. This behavior makes updating log_model_allowlist file a bit complicated. 

### Details

1. Within the source code we're reading the file using python's built-in `open` method to read the log_model_allowlist file, one option would be that we replace this `open` with `smart_open.open()`. This `smart_open` library supports reading files from lots of storages (https://github.com/RaRe-Technologies/smart_open) But this need mlflow to depend on smart_open library.
2. We check the format of the config link, and it should be a public-accessible link that we don't need extra confidential to download, then if it's a downloadable link we can download the file and read it.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Support reading the config from a downloadable link (http protocol) looks reasonable. We don't need to introduce a new dependency library.

CC @dbczumar @harupy Thoughts ? :)

**Comment by serena-ruan** [comment]
@dbczumar @harupy Kindly ping on this 😃

**Comment by dbczumar** [comment]
@serena-ruan That approach sounds great! I'll go ahead and close https://github.com/mlflow/mlflow/pull/5857 in favor of the new approach you've outlined. Apologies for the delay!

**Comment by WeichenXu123** [comment]
Thanks @serena-ruan . Sorry for late response. I will help review your new PR.
