### ISSUE TITLE
Replace `npm` with `yarn` in `CONTRIBUTING.rst`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5878]
https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#javascript-and-ui needs to be updated because we no longer use `npm` but currently use `yarn`.

```
> cat CONTRIBUTING.rst | grep npm
The MLflow UI is written in JavaScript. ``npm`` is required to run the Javascript dev server and the tracking UI.
You can verify that ``npm`` is on the PATH by running ``npm -v``, and
`install npm <https://www.npmjs.com/get-npm>`_ if needed.
   npm install
If modifying dependencies in ``mlflow/server/js/package.json``, run ``npm update`` within
   npm start
   npm run build
```

**Comment by rafaelvp-db** [comment]
@harupy currently trying to replace ```npm install``` with ```yarn install```. Had to do a quick workaround - ```touch yarn.lock``` but seems to be working now. Can I create a PR for this one?

**Comment by rafaelvp-db** [comment]
nevermind, just seen that @kugland already tackled it
