### ISSUE TITLE
[BUG] Error registering a model with quotes

### ISSUE THREAD

**Issue by gvelimir** [mlflow/mlflow#5883]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

When registering a new model i.e. entering a new name that includes quotes, the registered model is successfully created but when accessed, the UI becomes unresponsive.

### Code to reproduce issue

Just enter a new model to register that includes quotes in the name.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Thanks for the issue report. Could you provide some additional details? Is this through entering a registered model name when using a flavor's `log_model` method, when using the model registry APIs directly, or through renaming within the UI?

```python
mlflow.set_experiment("my_experiment")

with mlflow.start_run(run_name="some_run"):
    params = {"n_estimators": 42, "random_state": 42}
    model = RandomForestRegressor(**params)

    mlflow.log_params(params)

    mlflow.sklearn.log_model(
        sk_model=model,
        artifact_path="some_location",
        registered_model_name="'my_model_name'"
    )
```
Is this what you're doing?

**Comment by gvelimir** [comment]
Directly through the UI, but you described the same thing using the **log_model**.

**Comment by harupy** [comment]
I was able to reproduce the issue:

https://user-images.githubusercontent.com/17039389/168991126-3cde5084-8c67-463a-9df4-b309e9353298.mov

**Comment by harupy** [comment]
This line throws an error:

https://github.com/mlflow/mlflow/blob/fe6618823a2e6038149ee0da675503d2764552ca/mlflow/utils/search_utils.py#L692-L697

**Comment by adamfrly** [comment]
Hello, does this issue still require fixing? I'm relatively new to open source contributing and would like to try resolving it.

**Comment by gvelimir** [comment]
Confirmed, as of version 1.28.0, the issue does not appear anymore.
