### ISSUE TITLE
How to connect to a MySQL instance thats requires SSL using PyMySql

### ISSUE THREAD

**Issue by haripraghash** [mlflow/mlflow#5885]
I am currently using 

`mlflow server --backend-store-uri=mysql+pymysql://${MLFLOW_USER}:${MLFLOW_PASS}@${MLFLOW_DB_ADDR}:${MLFLOW_DB_PORT}/${MLFLOW_DB_NAME} --default-artifact-root=${MLFLOW_ARTIFACT_PATH} --host 0.0.0.0 --port 80
`
and trying to connect to MySQL. But it is failing and the MYSQL server has enforced SSL. I have a client certificate that I can use. But how do I set it up with mlfow?

**Comment by nov301996** [comment]
@haripraghash , Do you have a solution to this ?

**Comment by haripraghash** [comment]
@nov301996 We run mlflow on AKS and we use Azure Database for MySql. Our docker image has an custom entrypoint which is a script. We do the following

mlflow server --backend-store-`uri=mysql+pymysql://${MLFLOW_USER}:${MLFLOW_PASS}@${MLFLOW_DB_ADDR}:${MLFLOW_DB_PORT}/${MLFLOW_DB_NAME}?ssl_ca=./BaltimoreCyberTrustRoot.crt.pem --default-artifact-root=${MLFLOW_ARTIFACT_PATH} --serve-artifacts --gunicorn-opts "--log-level warning" --host 0.0.0.0 --port 80`
