### ISSUE TITLE
[BUG] Nested runs not displayed properly

### ISSUE THREAD

**Issue by Nika-St** [mlflow/mlflow#5894]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.22.0
- **Python version**: 3.9.10
- **yarn version, if running the dev UI**:

### Describe the problem

![2022-05-18](https://user-images.githubusercontent.com/29167311/169028297-278c82d1-4144-4124-94c5-43d56f877ec0.png)

Instead of being properly grouped under the parent run, nested runs are scrambled (apparently, sorted by date). The expectation is that standalone and parent runs would be sorted by date but _nested_ runs would be shown _nested_ under parent ones.

### Code to reproduce issue

```python
with mlflow.start_run(run_name='some_name') as parent_run:
    for x in range(20):
        with mlflow.start_run(run_name='some_other_name' + x, nested=True) as child_run:
            mlflow.log_param('some_param', x)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by adamreeve** [comment]
Hi @Nika-St, you're using quite an old version of mlflow. Can you reproduce this with 1.26.0? 1.26.0 included some changes I made to the runs grid, so this issue caught my eye, but I think nested runs were already working correctly before 1.26.0.

**Comment by Nika-St** [comment]
Thanks @adamreeve ! I requested an update from the admin.

**Comment by dbczumar** [comment]
As indicated by @adamreeve , this has been resolved in recent versions of MLflow. Thank you for using MLflow!

**Comment by vandit2209** [comment]
Heyyy guys  for version  2.22.0 I am again facing same issue....
mlflow server \
  --host 127.0.0.1 \
  --port 5005 \
  --workers 6 \
  --gunicorn-opts="--limit-request-line 65536" \
  --backend-store-uri PATH
  --default-artifact-root PATH

I am seeing correct nesting

BUT FOR

mlflow ui --port 5010 --backend-store-uri PATH --default-artifact-root PATH 

It is lost

<img width="1552" alt="Image" src="https://github.com/user-attachments/assets/c9a9333b-7812-4dbe-981d-f1dd0bbd6d82" />
<img width="1552" alt="Image" src="https://github.com/user-attachments/assets/24d7e96f-1a9c-4649-b1f0-f10c9343bbd1" />
