### ISSUE TITLE
[FR] Highlight or filter only different parameters in the 'Compare Runs' functionality

### ISSUE THREAD

**Issue by Nika-St** [mlflow/mlflow#5896]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

The 'Compare Runs' page shows all parameters logged for the runs being compared.
It would be much more convenient if one could filter only those parameters that are different for the given runs or if they were highlighted.

#### What is the use case for this feature?
There is too much noise in the run comparison interface

#### Why is it currently difficult to achieve this use case?
One can only find differentiating parameters for the compared runs by visually looking through all of them (and there may be a few dozen * a lot of runs)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Nika-St `mlflow>=1.24.0` supports this feature. Am I missing something?

https://user-images.githubusercontent.com/17039389/169260350-ca20e905-8256-4fa5-8949-af002ebd5660.mov

**Comment by harupy** [comment]
@Nika-St `mlflow>=1.24.0` supports this feature. Am I missing something?

https://user-images.githubusercontent.com/17039389/169260350-ca20e905-8256-4fa5-8949-af002ebd5660.mov

**Comment by Nika-St** [comment]
Oh, thanks a lot @harupy ! We've missed a useful update, then :)
