### ISSUE TITLE
[ASK] How do I automatically Log stderr and stdout to MLFlow Tracking Server Artifact?

### ISSUE THREAD

**Issue by Clayrisee** [mlflow/mlflow#5901]
Hello MLFlow Team!

I have a question, how can I log stdout and stderr from failed experiment to MLflow tracking server? 

Currently, I already tried using nohup command to catch STDERR and STDOUT and store the training log artifact on my tracking server. But, I have an issue differentiating between a running experiment and a failed experiment caused they have the same status which is 
FINISHED. is it possible to store my artifact from my failed experiment? so I can easily differentiate between successful experiments and failed experiments on MLFlow Tracking UI?

Example Log using nohup
![image](https://user-images.githubusercontent.com/54859935/169197839-e963783d-bbfd-4784-9b66-698cee0f4707.png)

Example hist experiment between unsuccessful experiments (with nohup and without nohup)
![image](https://user-images.githubusercontent.com/54859935/169197715-faf34228-cfc3-4649-895e-52a42624b968.png)

Thank you!

**Comment by BenWilson2** [comment]
Have you tried throwing after catching the exception within the mlflow.start_run context wrapper if you'd like the run to be classified as failed so that you get the indication of a failed run instead of using the no-hang-up exception eating at the close of the context reference?

**Comment by Clayrisee** [comment]
> Have you tried throwing after catching the exception within the mlflow.start_run context wrapper if you'd like the run to be classified as failed so that you get the indication of a failed run instead of using the no-hang-up exception eating at the close of the context reference?

Yeah, it is already solved using this method! Thank for ur reply Ben

**Comment by Clayrisee** [comment]
For anyone who wonders how to log stderr and stdout, you can use this implementation.

1. Run mlflow project using nohup.
```
nohup mlflow run . --no-conda > train_logs.txt
```
2. Log the model using this code.

```python

def generate_mlflow_status(name_file:str, status_code:int):
    run_uuid = mlflow.active_run().info.run_uuid
    dt_string = datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    with open(name_file, 'a+') as f:
        data = f.read(100)
        if len(data) > 0 :
            f.write("\n")
        if status_code == 0:
            f.write(f"{dt_string} INFO mlflow.projects: === Run (ID '{run_uuid}') succeeded ===")
        else:
            f.write(f"{dt_string} ERROR mlflow.cli: === Run (ID '{run_uuid}') failed ===")

if __name__ == "__main__":
    status_code= 0
    try:
        train_and_log_model_artifact()
        generate_mlflow_status('training_log.txt', status_code=status_code)
    except:
        status_code=1
        # Append mlflow error line so it can be detected on tracking server
        generate_mlflow_status('training_log.txt', status_code=status_code)        
    mlflow.log_artifact('training_log.txt')
    sys.exit(status_code)

```
