### ISSUE TITLE
Metric Alerting

### ISSUE THREAD

**Issue by parkerzf** [mlflow/mlflow#591]
### Describe the problem
A key use of metrics is creating alerts. For example, you may want to send an email to relevant people if the model prediction accuracy is lower than 0.5. It may be a small issue when you have small number of models/projects, but it becomes challenging if you need to manage large amount of models and update models periodically in an automatic way. Something ideas from prometheus project:

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
https://github.com/prometheus/alertmanager

Alternatively, we could use the RESTful API to get metrics and process alert outside of mlflow, but it is better to have this feature integrated.

**Comment by ankitmathur-db** [comment]
We think this is probably best done as something that's on top of MLFlow, since the REST API enables use cases that are not strictly in scope but which seem to make a lot of sense.

**Comment by rjalan01** [comment]
we had a similar use-case, want to understand the exact reason for it being closed. What is meant by "Rest API enable use-case is not in scope"?

**Comment by ankit-db** [comment]
Thanks for bringing this back up! The idea certainly sounds valuable - at the time of my comment, it was outside the scope of MLflow. What I meant at the time was that it's possible to build software around our REST API that implements such extensions. For example, one could configure a job that is polling for completed runs and sends such an email.

cc: @dbczumar for possible integration into the future roadmap at this point.
