### ISSUE TITLE
Fix typos in `tests/generate_ui_test_data.py`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5915]
Fix the following lines:

https://github.com/mlflow/mlflow/blob/0a9ea27b3cc11d4be90eb698cc689fffc88494fb/tests/generate_ui_test_data.py#L102

https://github.com/mlflow/mlflow/blob/0a9ea27b3cc11d4be90eb698cc689fffc88494fb/tests/generate_ui_test_data.py#L123

**Comment by harupy** [comment]
If you don't mind, please let us know how you found this issue.

**Comment by ianstewart4** [comment]
Hello, I can fix the typos if you'd like
