### ISSUE TITLE
Fix shebang in `hooks/prepare-commit-msg`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5934]
`hooks/prepare-commit-msg` throws the following error because of an incorrect shebang:

```
hooks/prepare-commit-msg: 9: [[: not found
```

https://github.com/mlflow/mlflow/blob/7b87441a6d3061eccbb605254686decd5aa78288/hooks/prepare-commit-msg#L1

`#!/bin/sh` needs to be fixed to `#!/bin/bash` as follows:

```diff
diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
index 42775b62a..ceaf05356 100755
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # A git hook to block an unsigned-off commit
```

**Comment by kvaithin** [comment]
Hi could I pick this up pls.

**Comment by harupy** [comment]
@kvaithin yes!
