### ISSUE TITLE
[BUG] The intermediate state of MLflow is incorrect.

### ISSUE THREAD

**Issue by shenwpo** [mlflow/mlflow#5963]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### System information

- **Have I written custom code**: [test code](https://github.com/shenwpo/test_mlflow/tree/main)
- **OS Platform and Distribution)**: Linux Ubuntu 20.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.26.0
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

When an error occurs during training, only the `finished` state can be obtained instead of the `failed` state. Is it allowed to set a callback function to get the final state?

### run 
```
git clone https://github.com/shenwpo/test_mlflow/tree/main
pip install mlflow==1.26.0
cd test_mlflow & python3 test.py
```

### Code to reproduce issue

```https://github.com/shenwpo/test_mlflow/tree/main```

### Other info / logs

```
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    train()
  File "train.py", line 19, in train
    error = 1 / 0
ZeroDivisionError: division by zero
Active run: None
end_time 1653661423338
run_id: d302841f538347f78968c0ca3dc37370; status: FINISHED
2022/05/27 22:23:43 ERROR mlflow.cli: === Run (ID 'd302841f538347f78968c0ca3dc37370') failed ===
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@shenwpo I found you called `mlflow.end_run()` in [this line](https://github.com/shenwpo/test_mlflow/blob/47fdf86010d4aedca03fe90f3fd5c148a1a3d4db/train.py#L27), which sets the runs status to `FINISHED`.

**Comment by shenwpo** [comment]
> @shenwpo I found you called `mlflow.end_run()` in [this line](https://github.com/shenwpo/test_mlflow/blob/47fdf86010d4aedca03fe90f3fd5c148a1a3d4db/train.py#L27), which sets the runs status to `FINISHED`.
> 
> doc for `mlflow.end_run`: https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.end_run

Thanks for replying, I know that. But how do you get a `failed` state？

**Comment by harupy** [comment]
You can use `with mlflow.status_run()` to terminate the run with `failed` status.

```python
import atexit
import time
from random import random, randint

import mlflow

import os


RUN_ID = None


def train():
    global RUN_ID
    with mlflow.start_run() as run:
        RUN_ID = run.info.run_id
        mlflow.log_param("param1", randint(0, 100))

        # Log a metric; metrics can be updated throughout the run
        mlflow.log_metric("foo", random())
        mlflow.log_metric("foo", random() + 1)
        mlflow.log_metric("foo", random() + 2)

        time.sleep(3)

        # error
        error = 1 / 0
        print(error)


def end_up():
    print(RUN_ID)
    # Check for any active runs
    run = mlflow.get_run(RUN_ID)
    print("end_time", run.info.end_time)
    # status is FINISHED
    print("run_id: {}; status: {}".format(run.info.run_id, run.info.status))


atexit.register(end_up)

if __name__ == "__main__":
    train()

```
