### ISSUE TITLE
Parameterize saved_code_subpath in mlflow.pyfunc.save_model()  [FR]

### ISSUE THREAD

**Issue by mdamircoder** [mlflow/mlflow#5966]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

You should make "**_saved_code_subpath_**" variable customizable in  **_mlflow.pyfunc.model._save_model_with_class_artifacts_params()_** 

mlflow.pyfunc.save_model() ==> _save_model_with_class_artifacts_params()
In "_save_model_with_class_artifacts_params", saved_code_subpath is hardcoded as "code", it should be dynamic. 

Anaconda has a "code" module (code.py). This "code" module causes problems during the relative import of python files/folders specified via code_paths. Hence, suggesting to parameterize this variable. 

### Motivation

> #### What is the use case for this feature?

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @mdamircoder, can you share the code that can reproduce the issue?

**Comment by harupy** [comment]
> In "_save_model_with_class_artifacts_params", saved_code_subpath is hardcoded as "code", it should be dynamic.

Can replace `code` with a random string?

```diff
diff --git a/mlflow/pyfunc/model.py b/mlflow/pyfunc/model.py
index 6de95c626..fff4b98c0 100644
--- a/mlflow/pyfunc/model.py
+++ b/mlflow/pyfunc/model.py
@@ -7,6 +7,7 @@ import os
 import posixpath
 import shutil
 import yaml
+import uuid
 from abc import ABCMeta, abstractmethod
 
 import cloudpickle
@@ -196,7 +197,7 @@ def _save_model_with_class_artifacts_params(
 
     saved_code_subpath = None
     if code_paths is not None:
-        saved_code_subpath = "code"
+        saved_code_subpath = uuid.uuid4().hex
         for code_path in code_paths:
             _copy_file_or_tree(src=code_path, dst=path, dst_dir=saved_code_subpath)
```

**Comment by harupy** [comment]
@mdamircoder What do you think about the approach above?

**Comment by harupy** [comment]
@mdamircoder Gentle ping.

**Comment by harupy** [comment]
@mdamircoder Feel free to reopen this issue.
