### ISSUE TITLE
Support mounting the UI into a sub-path behind a reverse proxy

### ISSUE THREAD

**Issue by elgalu** [mlflow/mlflow#597]
#### Feature request:
Support mounting the UI into a sub-path behind a reverse proxy

At the moment the base path `"/"` is hard-coded so is difficult to expose the ui behind a reverse proxy in a sub-directory.

The request is to provide something similar to `spark.ui.proxyBase`

https://github.com/mlflow/mlflow/blob/241d43cd656f2a4619563f77ddf7354799427ff6/mlflow/server/js/src/sdk/MlflowService.js#L24

**Comment by brasie** [comment]
Referencing https://github.com/mlflow/mlflow/issues/111#issuecomment-475035699, perhaps another option would be simply to make the AJAX API calls relative, i.e. not have a base `/` at all and just do e.g. 
```js
     return $.ajax('ajax-api/2.0/preview/mlflow/experiments/create', { 
```

**Comment by jakubczakon** [comment]
@elgalu 
You could also have your MLflow experiment runs hosted on [neptune.ml][1]. By doing so it would be super easy to share your experiment runs with however you like (assuming you give them access to see it). I think it should solve your problems with exposing UI. For example, let me share [some experiments](https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments) with you.

We have recently released free Neptune version and developed integration with MLflow which, I think , brings a lot of value to the community.

Also if you are interested, I have just written a [blog post about it][3].

  [1]: https://neptune.ml/?utm_source=stack_exchange&utm_medium=forum&utm_campaign=neptune_is_free&utm_term=mlflow
  [2]: https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments
  [3]: https://medium.com/neptune-ml/collaborate-on-mlflow-experiments-in-neptune-fb4f8f84a995"""

**Comment by LucaMoschella** [comment]
Hi, any update on this?
I'm hitting the same problem. The mlflow server is accessible but it doesn't work behind a reverse proxy.

![image](https://user-images.githubusercontent.com/11019190/70715806-56f4d680-1ceb-11ea-95dd-29385f51ecb0.png)

**Comment by pogil** [comment]
Hi all, using a reverse proxy w/ MLflow has come up a bunch, but it's a bit hard to for us to keep track of the issues and help here. We definitely need some community help. I've created #2823 as a place to request this help.
