### ISSUE TITLE
Replace `lr` with `learning_rate` in `tests/keras/test_keras_autolog.py`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5973]
`lr` for `Adam` is deprecated and needs to be replaced with `learning_rate`:

https://github.com/mlflow/mlflow/blob/ba6312ab000ddd165b0973342aec11760f6879a5/tests/keras/test_keras_autolog.py#L55

https://github.com/mlflow/mlflow/runs/6622093586?check_suite_focus=true#step:12:83

```
tests/keras/test_keras_autolog.py: 28 warnings
  /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
    super(Adam, self).__init__(name, **kwargs)
```

If you've never created a PR before, https://opensource.com/article/19/7/create-pull-request-github might be helpful.

**Comment by punitkashyup** [comment]
Can i work on this?

**Comment by harupy** [comment]
@punitkashyup Thanks for the comment, but @EB-Joel is already working on this.

**Comment by harupy** [comment]
@punitkashyup Would you be interested in working on #5977?

**Comment by punitkashyup** [comment]
Yes. i can

**Comment by harupy** [comment]
Awesome, can I post a comment on #5977 so we can assign it to you?

**Comment by Yash-Var** [comment]
I want to work on it
