### ISSUE TITLE
Remove `from StringIO import StringIO`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5977]
Remove `from StringIO import StringIO` because we no longer support Python 2.

https://github.com/mlflow/mlflow/blob/e40493a03088e2f939a9d5f0e409207871e983a1/mlflow/pyfunc/scoring_server/__init__.py#L48

https://github.com/mlflow/mlflow/blob/1e2b4ed051bc760fd3e7d69149e1fbc1f7928edf/tests/models/test_cli.py#L18

https://github.com/mlflow/mlflow/blob/ba6312ab000ddd165b0973342aec11760f6879a5/tests/pyfunc/test_scoring_server.py#L16

When you work on this issue, please make sure to follow https://opensource.com/article/19/7/create-pull-request-github, sign off your commits using `git commit -s ...`, and **do not make a commit on GitHub UI, which causes our DCO check to fail**.

**Comment by punitkashyup** [comment]
Yes I can work on this . Pls assign

**Comment by harupy** [comment]
@punitkashyup thanks, please make sure to take a look at the notes in #5978.

**Comment by punitkashyup** [comment]
Okay!
