### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5978]
🚨 When you work on this issue, please make sure the following 🚨

- Follow https://opensource.com/article/19/7/create-pull-request-github if you're unfamiliar with how to create a pull request on GitHub.
- Create a PR from a non-master branch.
- Do not create commits on GitHub UI. [The DCO bot](https://github.com/apps/dco) doesn't work well with commits created on GitHub UI.
- Sign off your commits by using the `-s` flag (e.g. `git commit -s -m "fix typo"`).
- Fix only one item per pull request.
- Reference this issue in the PR.
- Ping me with the item you want to work on (e.g. @harupy I'd like to work on `occured -> occurred`).

### Typos (✅ means "Done")

---

🚀 Assignee: @punitkashyup (#5981 ✅)

occured -> occurred

https://github.com/mlflow/mlflow/blob/6700ba2b2fea445fe1c3ced686124d457c7b4511/mlflow/exceptions.py#L43

https://github.com/mlflow/mlflow/blob/6700ba2b2fea445fe1c3ced686124d457c7b4511/mlflow/exceptions.py#L71

---

🚀 Assignee: @elk15 (#5983 ✅)

resposne -> response

https://github.com/mlflow/mlflow/blob/1e2b4ed051bc760fd3e7d69149e1fbc1f7928edf/tests/helper_functions.py#L330

---

🚀 Assignee: @nitin154

reutrn -> return 

https://github.com/mlflow/mlflow/blob/1e2b4ed051bc760fd3e7d69149e1fbc1f7928edf/tests/helper_functions.py#L334

---

🚀 Assignee: @NeoKish (#6017 ✅)

direcotry -> directory 

https://github.com/mlflow/mlflow/blob/4e444efdf73c710644ee039b44fa36a31d716f69/tests/conftest.py#L104

---

🚀 Assignee: CaioCavalcanti (#6007 ✅)

relave -> relative

https://github.com/mlflow/mlflow/blob/834194ad4d540d90ea714ec0b88b95d1a990f52f/mlflow/utils/requirements_utils.py#L92

---

🚀 Assignee: @NeoKish (#6002 ✅)

senstive -> sensitive 

https://github.com/mlflow/mlflow/blob/ae27f677f7b6af693e766aaf7718fddd3d87b556/mlflow/tracking/fluent.py#L937

---

🚀 Assignee: @NeoKish (#6002 ✅)

adtive -> active 

https://github.com/mlflow/mlflow/blob/ae27f677f7b6af693e766aaf7718fddd3d87b556/mlflow/tracking/fluent.py#L1096

---

🚀 Assignee: @seyyidibrahimgulec (#5986 ✅)

comperator -> comparator 

https://github.com/mlflow/mlflow/blob/2a05d7d0cc65d4d72bc42b47321ae5b5011944dc/tests/utils/test_python_env.py#L108
https://github.com/mlflow/mlflow/blob/2a05d7d0cc65d4d72bc42b47321ae5b5011944dc/tests/utils/test_python_env.py#L121
https://github.com/mlflow/mlflow/blob/2a05d7d0cc65d4d72bc42b47321ae5b5011944dc/mlflow/utils/environment.py#L139
---

🚀 Assignee: @Asinsa (#6005 ✅)

legnth -> length 

https://github.com/mlflow/mlflow/blob/011ee78cebd492ab3d75d8f87f5c9d80334d2bf6/tests/utils/test_utils.py#L32

---

🚀 Assignee: @NeoKish (#6017 ✅)

theese -> these

https://github.com/mlflow/mlflow/blob/4b7c41e42d9fdb7f0e4c5d8937a8eb7296d22d1f/mlflow/sklearn/utils.py#L161

**Comment by harupy** [comment]
Ping me if you find new typos.

**Comment by punitkashyup** [comment]
Can i also work on this?

**Comment by harupy** [comment]
@punitkashyup yes!

**Comment by punitkashyup** [comment]
Thanks

**Comment by harupy** [comment]
@punitkashyup please tell me which item you  want work on.

**Comment by punitkashyup** [comment]
Anyone.

**Comment by harupy** [comment]
@punitkashyup Assigned the first item.

**Comment by elk15** [comment]
@harupy I'd like to work on resposne -> response.

**Comment by harupy** [comment]
@elk15 Thanks, assigned!

**Comment by seyyidibrahimgulec** [comment]
@harupy I'd like to work on comperator -> comparator

**Comment by harupy** [comment]
@seyyidibrahimgulec Thanks, assigned!

**Comment by seyyidibrahimgulec** [comment]
@harupy Thanks

**Comment by harupy** [comment]
@nitin154 Thanks, assigned :)

**Comment by NeoKish** [comment]
@harupy, I would like to work on senstive -> sensitive and adtive -> active since the both the typos are present in the same file

**Comment by harupy** [comment]
@NeoKish Thanks, assigned!

**Comment by NeoKish** [comment]
@harupy , can I take other unassigned ones or do you want to keep them open for other contributors?

**Comment by harupy** [comment]
@NeoKish I'd like to keep them open for a few more days for other contributors.

**Comment by NeoKish** [comment]
@harupy, Sounds good to me. Thanks!

**Comment by harupy** [comment]
@NeoKish I'll ping you in a few days if this issue is not closed yet.

**Comment by Asinsa** [comment]
@harupy I'd like to work on legnth -> length

**Comment by harupy** [comment]
@Asinsa Thanks!

**Comment by CaioCavalcanti** [comment]
@harupy I'd like to work on `relave -> relative`

**Comment by Sumanth077** [comment]
Hi, @harupy I would like to contribute, is any Typo left?

**Comment by harupy** [comment]
@Sumanth077 They are reserved by @NeoKish.


@NeoKish Feel free to take unassigned ones :)

**Comment by NeoKish** [comment]
@harupy, Thanks, I am gonna do a PR soon

**Comment by harupy** [comment]
@nitin154 Any updates?

**Comment by rotate2050** [comment]
@harupy I have found a new typo that is not in the list. Can I fix it? Here is the detail:

truncacted -> truncated 

https://github.com/mlflow/mlflow/blob/1e2b4ed051bc760fd3e7d69149e1fbc1f7928edf/mlflow/utils/import_hooks/__init__.py#L42

**Comment by harupy** [comment]
@rotate2050 Thanks, yes you can! Can you also fix the following typo?

https://github.com/mlflow/mlflow/blob/1e2b4ed051bc760fd3e7d69149e1fbc1f7928edf/tests/helper_functions.py#L334

**Comment by rotate2050** [comment]
@harupy 

> Can you also fix the following typo (reutrn -> return)?
Sure.

I created PR : https://github.com/mlflow/mlflow/pull/6026. I did realize that I fixed two different typos in a single PR. I am sorry for that. I can fix it if you want. Let me know.
