### ISSUE TITLE
Merge pytest commands in `dev/run-python-skinny-tests.sh`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5987]
_Notes: When you work on this issue, please make sure the following:_

- Follow https://opensource.com/article/19/7/create-pull-request-github if you're unfamiliar with how to create a pull request on GitHub.
- Create a PR from a non-master branch.
- Do not create commits on GitHub UI. [The DCO bot](https://github.com/apps/dco) doesn't work well with commits created on GitHub UI.
- Sign off your commits by using the `-s` flag (e.g. `git commit -s -m "fix typo"`).
- Reference this issue in the PR with `Close #5987`.
- Ping me before you start working on this issue.

---

pytest commands in [`dev/run-python-skinny-tests.sh`](https://github.com/mlflow/mlflow/blob/master/dev/run-python-skinny-tests.sh) can be merged into a single pytest test command as follows:

```diff
diff --git a/dev/run-python-skinny-tests.sh b/dev/run-python-skinny-tests.sh
index 888717ea6..49aabc531 100755
--- a/dev/run-python-skinny-tests.sh
+++ b/dev/run-python-skinny-tests.sh
@@ -25,15 +25,16 @@ python -m pip install sqlalchemy alembic sqlparse
 # unintended libraries.
 pytest tests/test_skinny_client_omits_data_science_libs.py
 
-pytest tests/test_runs.py
-pytest tests/tracking/test_client.py
-pytest tests/tracking/test_tracking.py
-pytest tests/projects/test_projects.py
-pytest tests/deployments/test_cli.py
-pytest tests/deployments/test_deployments.py
-pytest tests/projects/test_projects_cli.py
-pytest tests/utils/test_requirements_utils.py::test_infer_requirements_excludes_mlflow
-pytest tests/utils/test_search_utils.py
-pytest tests/store/tracking/test_file_store.py
+pytest \
+  tests/test_runs.py \
+  tests/tracking/test_client.py \
+  tests/tracking/test_tracking.py \
+  tests/projects/test_projects.py \
+  tests/deployments/test_cli.py \
+  tests/deployments/test_deployments.py \
+  tests/projects/test_projects_cli.py \
+  tests/utils/test_requirements_utils.py::test_infer_requirements_excludes_mlflow \
+  tests/utils/test_search_utils.py \
+  tests/store/tracking/test_file_store.py

```

This change makes it easier to find tests that failed.

**Comment by harupy** [comment]
`pytest tests/test_skinny_client_omits_sql_libs.py` and `pytest tests/test_skinny_client_omits_data_science_libs.py` should be executed separately.

**Comment by SaumyaBhushan** [comment]
Hey @harupy I would like to work on this issue.

**Comment by harupy** [comment]
@SaumyaBhushan Thanks, go ahead!
