### ISSUE TITLE
mlflow cli not linked in path after pip install

### ISSUE THREAD

**Issue by nkarpovdb** [mlflow/mlflow#599]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu, 18.04 LTS (amazon ami)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: n/a
- **Python version**:  2.7.14
- **Exact command to reproduce**: pip install mlflow, mlflow ui

### Describe the problem
Clean install doesn't link mlflow to any of the directories usually on the path (/usr/local/sbin:/usr/local/bin etc)

The install does work otherwise (... python2.7/site-packages/mlflow/cli.py exists)

### Source code / logs
```
Successfully built mleap querystring-parser simplejson pyyaml itsdangerous nose-exclude tabulate configparser MarkupSafe
Installing collected packages: numpy, six, setuptools, protobuf, jmespath, docutils, python-dateutil, urllib3, botocore, futures, s3transfer, boto3, Werkzeug, click, MarkupSafe, Jinja2, itsdangerous, Flask, gunicorn, smmap2, gitdb2, gitpython, pytz, pandas, scipy, scikit-learn, argparse, nose, nose-exclude, mleap, idna, certifi, chardet, requests, querystring-parser, simplejson, pyyaml, tabulate, configparser, databricks-cli, mlflow

ubuntu@ip-###:~$ mlflow ui

Command 'mlflow' not found, did you mean:

  command 'mflow' from deb mblaze

Try: sudo apt install <deb name>
```

**Comment by mparkhe** [comment]
Hi @nkarpovdb : Are you using some virtual env before installing `mlflow`? Either of `virtualenv` and `conda create` before doing a `pip install` should help. Please lemme know if that does not help.

**Comment by nenetto** [comment]
I usually use `virtualenv`and sometimes, for python packages with scripts that need to be added to path are not correctly found by the OS due to the virtual environment. To fix this, I have to install the package in the root python installation without activating any environment so script can be found properly.

Try to install `mlflow` in the root python installation and deactivating first the environment. Then, install mlflow in the environment you want to use mlflow from. That should fix your issue

**Comment by stevenkwong** [comment]
I am using anaconda, and run in root env. It practical for me, you can have a try:
after pip mlflow, you can find the exec file in the fellowing path:

${anaconda path}/bin/mlflow

then build a soft link, and you can use "mlflow" in command line.

**Comment by conradbm** [comment]
Where does mlflow drop the application `mlflow` that can leverage the command `mlflow ui`? I am trying to find it, but I am not clear on where it is in the folder structure.

**Comment by TFrascaroli** [comment]
> Where does mlflow drop the application `mlflow` that can leverage the command `mlflow ui`? I am trying to find it, but I am not clear on where it is in the folder structure.

@conradbm After installing it, it told me where it installed to, warning me that its path was not in PATH. For me (and I guess for everyone) it is located at `/home/<username>/.local/bin`. Then doing
`PATH=$PATH:/home/<username>/.local/bin`
fixed the issue, and now I can run mlflow ui.

**Comment by JuliaHoerrmann** [comment]
Great, thank you. That worked for me as well!
