### ISSUE TITLE
Call `super()` without arguments

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#5993]
🚨 When you work on this issue, please make sure the following 🚨

- Follow https://opensource.com/article/19/7/create-pull-request-github if you're unfamiliar with how to create a pull request on GitHub.
- Create a PR from a non-master branch.
- Do not create commits on GitHub UI. [The DCO bot](https://github.com/apps/dco) doesn't work well with commits created on GitHub UI.
- Sign off your commits by using the `-s` flag (e.g. `git commit -s -m "fix typo"`).
- Reference this issue in the PR with `Close #5987`.
- Do not modify the PR template because our CI checks will fail.
- Ping me before you start working on this issue.

---

We don't support Python 2 anymore and need to call `super()` with arguments. For example,

https://github.com/mlflow/mlflow/blob/ba6312ab000ddd165b0973342aec11760f6879a5/tests/onnx/test_onnx_model_export.py#L109

can be fixed to:

```
            super(MyModel, self).__init__() 
```

The following files contain `super()` called with arguments:

```
> pylint --enable super-with-arguments $(git ls-files | grep '\.py$')
************* Module mlflow.sagemaker
mlflow/sagemaker/__init__.py:1801:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
************* Module mlflow.sklearn
mlflow/sklearn/__init__.py:492:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
************* Module mlflow.utils.autologging_utils.safety
mlflow/utils/autologging_utils/safety.py:225:16: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
mlflow/utils/autologging_utils/safety.py:232:25: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
mlflow/utils/autologging_utils/safety.py:244:16: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
************* Module test_onnx_model_export
tests/onnx/test_onnx_model_export.py:109:12: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
************* Module test_paddle_model_export
tests/paddle/test_paddle_model_export.py:58:12: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
tests/paddle/test_paddle_model_export.py:280:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
```

**Comment by Regis-Caelum** [comment]
Hey @harupy  I would like to work on this issue,

**Comment by harupy** [comment]
@Regis-Caelum thanks!
