### ISSUE TITLE
[BUG] sklearn.autolog fails without matplotlib installed

### ISSUE THREAD

**Issue by fa9r** [mlflow/mlflow#5994]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

1.26.1.dev0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS (with M1 chip)
- **Python version**: 3.8.13
- **yarn version, if running the dev UI**:

### Describe the problem

Since release 1.26.0, mlflow.sklearn.autolog fails to log experiments if matplotlib is not installed.

The issue is that you import matplotlib outside of the try block on line 489 in mlflow/mlflow/sklearn/utils.py.

Proposed fix: move matplotlib code into the try/except block (only place where it is used anyways).

### Code to reproduce issue

def tree_trainer_with_mlflow(
        X_train: np.ndarray,
        y_train: np.ndarray,
    ):
    mlflow.sklearn.autolog()  # log all model hparams and metrics to MLflow
    model = DecisionTreeClassifier()
    model.fit(X_train, y_train)
    return model

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@fa9r Thanks for filing the PR :)
