### ISSUE TITLE
[FR] Delete artifact over HTTP is not implemented

### ISSUE THREAD

**Issue by idlefella** [mlflow/mlflow#5996]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

The `http_artifact_repository` doesn't implement the `delete_artifacts` method, therefore it's not possible to permanently delete artifacts (for instance with the garbace collector `mlflow gc`).

### Motivation

> #### What is the use case for this feature?

Delete artifacts with e.g. `mlflow gc`.

> #### Why is this use case valuable to support for MLflow users in general?

The abstract `ArtifactRepository` defines a `delete_artifacts` method, which is not implemented in the `HttpArtifactRepository`. Making this endpoint available completes the API.

> #### Why is this use case valuable to support for your project(s) or organization?

We use the `mlflow gc` (experimental) command to clean deleted experiment data. Since we use the `--serve-artifacts` option on the server, the experiments use the `HttpArtifactRepository` to store the models. But because that doesn't have the `delete_artifacts` method implemented, the garbace collector doesn't work.

> #### Why is it currently difficult to achieve this use case?

We had to implement our own `gc` method.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@idlefella Thanks for the PR, we'll take a look :)
