### ISSUE TITLE
[FR] Show More than 3 Metrics & Tags from the Web UI

### ISSUE THREAD

**Issue by jyk4100** [mlflow/mlflow#6009]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Allow MLflow UI to show more than 3 "columns" for "Metrics" and "Tags". 
Within UI I can only see up to 3 metrics and tags so I don't have a "bird-eye view" of my experiment results. 
Using mlflow version set up for my org (mlflow 1.16) and not sure if this is already addressed in the latest version but still posting here as FR.

For example, even when there are space to right and additional metrics and tags are selected from the "Columns" drop-down, it only shows up to 3 metrics and 3 tags so I can't sort and look through multiple metrics and tags as I would like.
![Screen Shot 2022-05-31 at 8 57 50 PM](https://user-images.githubusercontent.com/14896560/171307420-d7275105-50e7-4f4c-aef0-0bd733e9a09e.png)

### Motivation

> #### What is the use case for this feature?
I cannot see more than 3 metrics or tags from the web UI. I have to use `client.search_runs` or `mlflow.search_run` to get experiment run_name, metrics and tags and compare experiments and get a sense of runs within my experiment.

> #### Why is this use case valuable to support for MLflow users in general?
Same as above, web UI should provide visibility into experiments without hassle but its very to navigate through multiple metrics and tags.

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@jyk4100 You can view more than 3 columns for metrics, tags, and params:

https://user-images.githubusercontent.com/17039389/171337270-02920dee-dd61-4a24-803f-3e6a7f3fab9b.mov

**Comment by jyk4100** [comment]
Thanks - I am not able to do such on my end and also the layout is slightly different so it must be a version/set up issue. Closing this thanks!
