### ISSUE TITLE
[BUG] Wrong link to model in Runs table of the Experiments view

### ISSUE THREAD

**Issue by hctpbl** [mlflow/mlflow#6011]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: python:3.10.4 docker image for linux/amd64 platform
- **Python version**: 3.10.4
- **yarn version, if running the dev UI**: -

### Describe the problem

When clicking on a model, in the "Models" column of the Runs table in the Experiments view, a 404 page is shown.
<img width="1132" alt="Screenshot 2022-06-01 at 15 41 18" src="https://user-images.githubusercontent.com/651015/171419115-813305c2-66ba-45ee-96a3-36c128cebbca.png">

This is due to the link being generated having `undefined` as the run id. Like this:

```
http://mlflow.stylesage.internal/#/experiments/5/runs/undefined/artifactPath/model
```

I've never programmed in react, so bear with me if this makes no sense but, debugging the code, I think the error comes from the following line: https://github.com/mlflow/mlflow/blob/v1.26.1/mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js#L396

As you can see, to create the `models` object, the `runInfo.runUuid` property is trying to be accessed, but that property is not camelCased, it's snake_cased, so it should be `runInfo.run_uuid`, which is the how the property is accessed [just three lines before the probably wrong one](https://github.com/mlflow/mlflow/blob/v1.26.1/mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js#L393).

My debugging of the minified javascript code also seems to indicate the same:
<img width="600" alt="Screenshot 2022-06-01 at 15 47 48" src="https://user-images.githubusercontent.com/651015/171421335-3f23db7c-9857-4487-bb39-61001c0f115d.png">

### Steps to reproduce the bug

Just go to the Experiments view, select any experiment to see the Runs table, and click on any model link in the Models column of any run.

**Comment by harupy** [comment]
As @hctpbl pointed out,

```diff
diff --git a/mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js b/mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
index e716f97f5..670a4bc59 100644
--- a/mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
+++ b/mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
@@ -389,11 +389,13 @@ export class ExperimentRunsTableMultiColumnView2 extends React.Component {
         childrenIds,
       };
 
       const models = {
         registeredModels: modelVersionsByRunUuid[runInfo.run_uuid] || [],
         loggedModels: Utils.getLoggedModelsFromTags(tags),
         experimentId: runInfo.experiment_id,
-        runUuid: runInfo.runUuid,
+        runUuid: runInfo.run_uuid,
       };
 
       const version = {
```

fixed the issue:


https://user-images.githubusercontent.com/17039389/171425347-85810d76-e46a-4e79-b7c5-46d60917afed.mov

**Comment by harupy** [comment]
Got it, Enjoy your holidays! We'll wait for you to come back :)
