### ISSUE TITLE
[FR] Create admin API endpoints for MLflow tracking server

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#6016]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

It's pretty standard for APIs to have admin endpoints for:
- Display current internal state, e.g. number of experiments, models, etc.
- Shut down the tracking server gracefully. Most important.
  - Currently the only solutions is to figure out the PID from the port, e.g. `lsof -n -i :5002` and then grab the PID from the output and `kill $PID`. It's both painful and error-prone.

Notes:
- A use case is when running a test suite - you want to launch a tracking server, run your tests and then tear down the server. Launching is done with `mlflow server` but what is missing is an analogous `mlflow server down`.
- Current situation doesn't lend itself well to MLOps CI/CD pipelines.

### Motivation

> #### What is the use case for this feature?

MLOps CI/CD pipelines. You need to launch a tracking server, run your tests, and the tear down the tracking server.

> #### Why is this use case valuable to support for MLflow users in general?

Best practices for admin API endpoints.

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

The only workaround is to use get the tracking server PID from the port (`lsof -n -i :5002`) which is a pain.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@amesar We don't plan to implement such endpoints at this time; server administrators can simply stop / kill the processes associated with the server. In general, an MLflow Tracking server is intended to operate as a long-lived resource for data scientists / machine learning engineers to record and query their model training sessions; shutdown is not intended to be a frequently-used operation. Consider Databricks-managed MLflow where MLflow Tracking is *always* available.
