### ISSUE TITLE
[Enhancement] Delete Run only deletes the metadata from UI, but not the artifacts from the artifact location.

### ISSUE THREAD

**Issue by whiletruelearn** [mlflow/mlflow#602]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**: 0.7
- **Python version**: 2.7
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
I see that `Delete run`  from  UI removes the run details from the UI and this is a great feature to have. An enhancement would be to delete the artifact directory created for the run also. This could lead to lots of savings on storage such as `S3` , `gcp` etc

**Comment by mparkhe** [comment]
One of the concerns with removing artifacts and other details (metrics, params, tags) is that the action would not be restorable. Depending on how the backend store is implemented, one can write a simple cron job to periodically purge deleted runs (and associated artifacts).

This `purge` is not natively supported currently. Will keep this request around to consider in future.

**Comment by mlisovyi** [comment]
Maybe this can be implemented as a two-step procedure? In the UI one can already switch between _"Active"_ and _"Deleted"_ state. It would be useful to have a _"Purge"_ button for the latter state in addition to the currently provided _"Restore"_

**Comment by mparkhe** [comment]
We have debated about this. Depending on the backend artifact store the SLAs and performance expectation for deleting or moving artifacts objects can vary. Hence it is not added as MLflow APIs and UI.

**Comment by jaklan** [comment]
That's really disappointing and making the maintenance of MLFlow tough - the `delete` button should exist at least for a use of local MLFlow & MLFlow Server, if you worry about other storages. `s3`, `gcp` etc. could be then added incrementally.

**Comment by mparkhe** [comment]
Hi @jaklan : One of the main principles for MLflow is open APIs that can be applied to a large # of use cases regardless of the backend implementations. With delete artifacts API, the concern is defining clear expectations in terms of SLAs etc. This depends on the backend system used.

For local store, it might easier to use command line (`rm` like commands) to remove the runs that admins deems can be deleted. All deleted runs are moved to `.Trash` folder per implementation in `FileStore` -- so these deleted runs are easier to find and identify. Arguably, deleting multiple runs will be easier using system commands and tools.

**Comment by jaklan** [comment]
@mparkhe thank you for the answer.

> All deleted runs are moved to .Trash folder per implementation in FileStore -- so these deleted runs are easier to find and identify.
That's interesting, because I don't observe that behaviour. I've just deleted some runs and they are still visible in the experiment catalog, the only difference is the status in `meta.yaml`. They are moved there after some time or it's a potential bug? But in general - if that worked, it would be fair enough workaround.

Btw one more question - what about deleting experiments? Why can't I delete an experiment from GUI level? It's really limiting its usage (you have to keep the number of experiments rather small and stable, not dynamic, to not create a mess). And also comparing runs between experiments would be really helpful to create own, optimal per use-case strategy of using experiments & runs.

**Comment by mparkhe** [comment]
You are right. I misquoted. Deleted experiments are moved to trash folder. Runs are marked as metadata. You can get this of deleted run using [list_run_infos](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.list_run_infos) API.

Deleting experiment can be done using [`mlflow.delete_experiment`](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.list_run_infos) API. 

I understand about controlling to access to disks. One of the mechanisms could be to periodically clean up deleted experiments and runs using a cron job.

Having a mechanism to delete experiments from UI sounds like a good idea.  Feature to compare across experiments has been asked before we well. If you would like to contribute any of these changes, I would recommend you write a short proposal before implementing UI changes. cc: @gioa, @Zangr, @smurching

**Comment by jaklan** [comment]
@mparkhe I see. Analogical mechanism for runs would be great - you can then just set up a cron job to clean all .Trash folders recursively, without checking `meta.yaml` or listing proper runs with MLFlow API.

In general running `mlflow experiments delete` would be quite okay, but... it doesn't work:
```
$ export MLFLOW_TRACKING_URI=http://mlflow_server.com
$ mlflow experiments list
  Experiment Id  Name     Artifact Location
---------------  -------  ------------------------------------------
              0  default  /Users/some_user/Repositories/some_project/mlruns/0
```
I still get the list of local experiments, even when I export the proper envar. Am I missing sth?

**Comment by jaklan** [comment]
One more comment to summarize that - even when I use MLFlow Server (pointed by `MLFLOW_TRACKING_URI`), artifacts are stored locally (as default). In docs I can see some options for setting up FTP, S3 etc. storage, but I still miss how can I just log artifacts to the same server location as experiments and runs (so via HTTP)? Is it not possible until I set up FTP connection with the server? @mparkhe

**Comment by mparkhe** [comment]
Do you mean to say that you are creating an `mlflow server` with some `--default-artifact-root` which is not on local file system and yet you see artifacts logged locally? Or do you mean to say that you expect to see the full path in experiment's `meta.yaml` file?

Do you see the artifacts pulled up on the UI? If that is the case, the artifacts are being logged correctly. Sorry--I am a bit confused. In any case, if you believe that it is a bug (or documentation issue) can you file a different issue (or submit a fix as a pul request) for this? One of us will take a look. Also, easier to track as a separate issue regarding artifact location/logging.

**Comment by jaklan** [comment]
@mparkhe sure, I can create a new issue, I just wanted to make sure if it's actually a bug or just my misunderstanding.

The flow is:
- I run a container with MLFlow Server at http://some_server.com
- the only command in a Dockerfile is `mlflow server --host 0.0.0.0`, so other options are should use default values
- locally, I export the `MLFLOW_TRACKING_URI` envar with the above server path (and nothing more)
- in some Python script I use `mlflow.set_experiment` (I only set `experiment_name` value) and `mlflow.start_run` (I only set `run_name` value) & log some metrics, params, tags and an artifact
- I run the script
- metrics, params and tags are sent to the above server as expected and visible in GUI
- artifact is saved locally, there's no trace of it on the server
