### ISSUE TITLE
[BUG] WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements

### ISSUE THREAD

**Issue by zmce2018** [mlflow/mlflow#6056]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

fastai==2.6.3, mlflow == 1.26.1 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:
E:\ANA\envs\TSAI\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
epoch     train_loss  valid_loss  time    
0         3.303364    3.672163    00:00                     
1         3.227255    3.531538    00:00                     
2         3.423550    3.387718    00:00                     
3         3.354039    3.291163    00:00                     
Epoch 5/5 :                                                 4         3.355100    3.254609    00:00     
2022/06/14 14:34:34 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\chunr\AppData\Local\Temp\tmpwrfgx_r3\model, flavor: fastai), fall back to return ['fastai==2.6.3']. Set logging level to DEBUG to see the full traceback.

### Describe the problem

Run the example code (https://github.com/mlflow/mlflow/tree/master/examples/fastai) but found error

### Tracking information

def main():
    # Parse command-line arguments
    args = parse_args()

    # Enable auto logging
    mlflow.fastai.autolog()

    # Create Learner model
    learn = Learner(get_data_loaders(), Model(), loss_func=nn.MSELoss(), splitter=splitter)

    # Start MLflow session
    with mlflow.start_run():
        # Train and fit with default or supplied command line arguments
        learn.fit_one_cycle(args.epochs, args.lr)

if __name__ == "__main__":
    main()

### Code to reproduce issue

learn.fit_one_cycle(args.epochs, args.lr)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @zmce2018 , thank you for raising this issue. Can you run the following code before your fast.ai training logic and provide the DEBUG logs that are produced?

```
import logging

logging.getLogger("mlflow").setLevel(logging.DEBUG)
```

**Comment by zmce2018** [comment]
@dbczumar Hello and thanks for your reply. Here is the error code after I put your code before your fast.ai training logic

```
2022/06/15 12:28:49 DEBUG mlflow.utils.autologging_utils: Called autolog() method for fastai autologging with args '()' and kwargs '{'log_models': True, 'disable': False, 'exclusive': False, 'disable_for_unsupported_versions': False, 'silent': False, 'registered_model_name': None}'
2022/06/15 12:28:49 DEBUG mlflow.utils.autologging_utils: Invoked patched API '<class 'fastai.learner.Learner'>.fit' for fastai autologging with args '(<fastai.learner.Learner object at 0x00000295A420F7C0>, 5)' and kwargs '{'cbs': [ParamScheduler], 'reset_opt': False, 'wd': None}'
2022/06/15 12:28:49 DEBUG mlflow.utils.autologging_utils: Original function invoked during execution of patched API '<class 'fastai.learner.Learner'>.fit' for fastai autologging. Original function was invoked with args '(<fastai.learner.Learner object at 0x00000295A420F7C0>, 5)' and kwargs '{'cbs': [ParamScheduler], 'reset_opt': False, 'wd': None}'
epoch     train_loss  valid_loss  time    
0         2.930746    3.362615    00:00                     
1         2.972328    2.992625    00:00                     
2         2.821007    2.602981    00:00                     
3         2.727268    2.318845    00:00                     
Epoch 5/5 :                                                 4         2.544970    2.205879    00:00     
2022/06/15 12:28:54 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\chunr\AppData\Local\Temp\tmpd321qg_t\model, flavor: fastai), fall back to return ['fastai==2.6.3']. Set logging level to DEBUG to see the full traceback.
2022/06/15 12:28:54 DEBUG mlflow.utils.environment: 
Traceback (most recent call last):
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\utils\environment.py", line 378, in infer_pip_requirements
    return _infer_requirements(model_uri, flavor)
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\utils\requirements_utils.py", line 345, in _infer_requirements
    modules = _capture_imported_modules(model_uri, flavor)
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\utils\requirements_utils.py", line 266, in _capture_imported_modules
    _run_command(
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\utils\requirements_utils.py", line 218, in _run_command
    raise MlflowException(msg)
mlflow.exceptions.MlflowException: Encountered an unexpected error while running ['E:\\ANA\\envs\\TSAI\\python.exe', 'E:\\ANA\\envs\\TSAI\\lib\\site-packages\\mlflow\\utils\\_capture_modules.py', '--model-path', 'C:\\Users\\chunr\\AppData\\Local\\Temp\\tmpd321qg_t\\model', '--flavor', 'fastai', '--output-file', 'C:\\Users\\chunr\\AppData\\Local\\Temp\\tmpohp0woig\\imported_modules.txt', '--sys-path', '["E:\\\\ANA\\\\envs\\\\TSAI\\\\python38.zip", "E:\\\\ANA\\\\envs\\\\TSAI\\\\lib\\\\site-packages\\\\git\\\\ext\\\\gitdb", "E:\\\\ANA\\\\envs\\\\TSAI\\\\DLLs", "E:\\\\ANA\\\\envs\\\\TSAI\\\\lib", "E:\\\\ANA\\\\envs\\\\TSAI", "", "E:\\\\ANA\\\\envs\\\\TSAI\\\\lib\\\\site-packages", "E:\\\\ANA\\\\envs\\\\TSAI\\\\lib\\\\site-packages\\\\win32", "E:\\\\ANA\\\\envs\\\\TSAI\\\\lib\\\\site-packages\\\\win32\\\\lib", "E:\\\\ANA\\\\envs\\\\TSAI\\\\lib\\\\site-packages\\\\Pythonwin", "E:\\\\ANA\\\\envs\\\\TSAI\\\\lib\\\\site-packages\\\\gitdb\\\\ext\\\\smmap"]']
exit status: 1
stdout: 
stderr: Traceback (most recent call last):
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\utils\_capture_modules.py", line 134, in <module>
    main()
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\utils\_capture_modules.py", line 109, in main
    mlflow.pyfunc.load_model(model_path)
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\pyfunc\__init__.py", line 735, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\utils\_capture_modules.py", line 106, in _load_pyfunc_patch
    return original(*args, **kwargs)
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\fastai\__init__.py", line 351, in _load_pyfunc
    return _FastaiModelWrapper(_load_model(path))
  File "E:\ANA\envs\TSAI\lib\site-packages\mlflow\fastai\__init__.py", line 332, in _load_model
    return load_learner(os.path.abspath(path))
  File "E:\ANA\envs\TSAI\lib\site-packages\fastai\learner.py", line 392, in load_learner
    try: res = torch.load(fname, map_location='cpu' if cpu else None, pickle_module=pickle_module)
  File "E:\ANA\envs\TSAI\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "E:\ANA\envs\TSAI\lib\site-packages\torch\serialization.py", line 1046, in _load
    result = unpickler.load()
  File "E:\ANA\envs\TSAI\lib\site-packages\torch\serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Custom classes or functions exported with your `Learner` are not available in the namespace currently.
Please re-declare or import them before calling `load_learner`:
	Can't get attribute 'splitter' on <module '__main__' from 'E:\\ANA\\envs\\TSAI\\lib\\site-packages\\mlflow\\utils\\_capture_modules.py'>

2022/06/15 12:28:54 DEBUG mlflow.utils.autologging_utils: Original function invocation completed successfully during execution of patched API call '<class 'fastai.learner.Learner'>.fit' for fastai autologging. Original function was invoked with with args '(<fastai.learner.Learner object at 0x00000295A420F7C0>, 5)' and kwargs '{'cbs': [ParamScheduler], 'reset_opt': False, 'wd': None}'
2022/06/15 12:28:54 DEBUG mlflow.utils.autologging_utils: Patched API call '<class 'fastai.learner.Learner'>.fit' for fastai autologging completed successfully. Patched ML API was called with args '(<fastai.learner.Learner object at 0x00000295A420F7C0>, 5)' and kwargs '{'cbs': [ParamScheduler], 'reset_opt': False, 'wd': None}'
```

**Comment by dbczumar** [comment]
@zmce2018 Thank you for providing the debug-level outputs. It appears that your model is defined using a custom class that is not packaged with the model when it is saved. To correct the issue, we recommend logging your model with `mlflow.fastai.log_model()` (https://mlflow.org/docs/latest/python_api/mlflow.fastai.html#mlflow.fastai.log_model) and specifying the path to your custom class definition via the `code_paths` argument. Here's some example code:

```
import mlflow
mlflow.fastai.autolog(log_models=False)

# Create Learner model
learn = Learner(get_data_loaders(), Model(), loss_func=nn.MSELoss(), splitter=splitter)

# Start MLflow session
with mlflow.start_run():
    # Train and fit with default or supplied command line arguments
    learn.fit_one_cycle(args.epochs, args.lr)
    mlflow.fastai.log_model(learn, code_paths=["path_to_your_python_file_containing_model_class_definition"])
```

Please let me know if this resolves the issue. Since this doesn't appear to be a problem with pip dependency inference but, rather, an issue with the way the model is persisted, I'm going to go ahead and close this issue. Feel free to let me know if you're still facing this problem after leveraging the `code_paths` argument, and I can reopen the ticket. 

Thank you for using MLflow!

**Comment by zmce2018** [comment]
@dbczumar Thanks for your time. This issue is corrected by removing the splitter from the learner function. 

A friendly reminder that this learner is not self-defined class as it is from the template code from mlflow, which can be found here (https://github.com/mlflow/mlflow/tree/master/examples/fastai). 

Many thanks for your help and all the best.
