### ISSUE TITLE
SQLAlchemy min version should be 1.4.37

### ISSUE THREAD

**Issue by moghadas76** [mlflow/mlflow#6090]
### System information

python == 3.8
OS: ubuntu 21.10

### Code to reproduce issue

```bash
pip install mlflow
```

### Describe the problem

ERROR: Could not find a version that satisfies the requirement sqlalchemy.future (from versions: none)
ERROR: No matching distribution found for sqlalchemy.future

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/6024 fixed this.
