### ISSUE TITLE
[DOC-FIX] Mistake in the docs of mlflow.pytorch.autolog

### ISSUE THREAD

**Issue by comojin1994** [mlflow/mlflow#6107]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://www.mlflow.org/docs/latest/python_api/mlflow.pytorch.html#module-mlflow.pytorch

### Description of proposal (what needs changing)

Hi,

I found the small mistake in the example of `mlflow.pytorch.autolog`.

As shown under code, it calculated the accuracy comparing the loss and y (label).

```python
class MNISTModel(pl.LightningModule):
    def __init__(self):
        super(MNISTModel, self).__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = F.cross_entropy(self(x), y)
        acc = accuracy(loss, y)

```

However, it raise the under error,

```
IndexError: tuple index out of range
```

The reason for this error is that it calculated the accuracy using the wrong values.
So, I think that it is better to fix the docs like under code.

```python
class MNISTModel(pl.LightningModule):
    def __init__(self):
        super(MNISTModel, self).__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_nb):
        x, y = batch
        logits = self(x)
        loss = F.cross_entropy(logits, y)
        pred = logits.argmax(dim=1)
        acc = accuracy(pred, y)
```

If I am right, I'm going to open PR.
Thanks!

**Comment by dbczumar** [comment]
@comojin1994 Thank you for pointing this out! We would be very excited to review a PR that fixes this issue. Thank you in advance for your contribution!

**Comment by comojin1994** [comment]
Created PR: https://github.com/mlflow/mlflow/pull/6113
