### ISSUE TITLE
[DOC-FIX] Slack link no longer working

### ISSUE THREAD

**Issue by pbarker** [mlflow/mlflow#6121]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://mlflow.org/

### Description of proposal (what needs changing)

slack link at bottom of page is broken, unable for me to contribute due to permissions

**Comment by harupy** [comment]
@pbarker Does this https://join.slack.com/t/mlflow-users/shared_invite/zt-1b7gbsopj-ckYE002CMSDR4_Bioztv8g work? If yes, we'll update the link.
