### ISSUE TITLE
[FR] Run `mlflow gc` based on time since last deletion

### ISSUE THREAD

**Issue by Jason-CKY** [mlflow/mlflow#6128]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Adding more functionality to `mlflow gc`, where administrators can delete runs based on time criteria (e.g. delete runs that have been tagged as `deleted` > 1 month ago). This could be done by adding a `delete_date` column into `runs` table in the sqlstore.

### Motivation

> #### What is the use case for this feature?
Sometimes developers would want to restore their runs that they previously deleted, so just running `mlflow gc` to delete all `deleted` runs periodically might cause developers to lose their data. By being able to delete runs that have been deleted for some time, we can be more sure that the deleted run is no longer needed.

> #### Why is this use case valuable to support for MLflow users in general?
Sometimes developers would want to restore their runs that they previously deleted, so just running `mlflow gc` to delete all `deleted` runs periodically might cause developers to lose their data. By being able to delete runs that have been deleted for some time, we can be more sure that the deleted run is no longer needed.

> #### Why is this use case valuable to support for your project(s) or organization?
Sometimes developers would want to restore their runs that they previously deleted, so just running `mlflow gc` to delete all `deleted` runs periodically might cause developers to lose their data. By being able to delete runs that have been deleted for some time, we can be more sure that the deleted run is no longer needed.

> #### Why is it currently difficult to achieve this use case?
`runs` table only have `start_time` and `end_time` column that tracks when the run is created and finished. However, it does not track when the run is deleted so it is impossible to delete based on this criteria.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @Jason-CKY, thank you for requesting this feature. We would be very excited to review a PR that implements it. Feel free to file a pull request, and please let me know if you have any questions. cc @WeichenXu123

**Comment by Jason-CKY** [comment]
Thanks, was busy for the past few weeks. I will work on this and put up a PR for this feature!
