### ISSUE TITLE
Remote tracking server: How to store logs remotely ?

### ISSUE THREAD

**Issue by Ycallaer** [mlflow/mlflow#613]
### System information
- OS Platform and Distribution: Docker file starting from image python:3.7.0-stretch
- MLflow installed : through pip
- MLflow version: mlflow==0.7.0
- Python version: Python 3.7.0 (default, Sep  5 2018, 03:25:31) 

### Describe the problem
I have currently a docker file which allows me to run the tracking server. I have configured the artifact root to log to Azure blob storage. 
If I run my program the logs show up in the UI and if I save the model I see the model appearing on blob storage.

However, the logs that were generated during the application run are only stored inside the docker and not remote. Is there a way to store the logs remote from the configuration or would I need to devise a system to store the logs as well on a remote system ?

Thanks for your insights

### Source code / logs
There aren't really logs / issues. Current implementation from the code looks as follows:
`mlflow.tracking.set_tracking_uri("http://0.0.0.0:5000/")
with mlflow.start_run():
            self.pdq_list = self.__pdq_iterations()
            for param in self.pdq_list:
                for param_season in self.__seasonal_pdq():
                    try:
                        mlflow.log_param("seasonal_pdq", param_season)`

In the dockerfile the server is started in the following fashion:

`mlflow server --file-store "$MLFLOW_SERVER_FILE_STORE" --default-artifact-root "$MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT" --host 0.0.0.0`

**Comment by Azadehkhojandi** [comment]
Any update on this issue?

BUG=> mlflow ignores --file-store and --default-artifact-root flags and saves metrics and artifacts under mlflow5000 folder

I have a docker compose file docker-compose.yml

```
version:  '3'
services:
  # docker-compose run mlflow
  mlflow:
    image: mlflow
    ports:
      - "5000:5000"
    container_name: mlflowcontainer
    volumes:
       - ./aztestmlflow:/mlflow
  terminal:
    image: mlflowterminal
    container_name: terminal
    #working_dir: /work
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
       - ./code:/code
```
mlflowterminal.dockerfile
Update values of AZURE_STORAGE_ACCESS_KEY , AZURE_STORAGE_CONNECTION_STRING 
```
FROM continuumio/anaconda3

LABEL maintainer "Azadeh Khojandi <azadehkhojandi@gmail.com>"



RUN pip install mlflow
RUN pip install azure-storage

ENV AZURE_STORAGE_CONNECTION_STRING 'DefaultEndpointsProtocol=https;AccountName=mlflowruns;AccountKey=xxxx==;EndpointSuffix=core.windows.net'
ENV AZURE_STORAGE_ACCESS_KEY 'xxx=='
```
mlflow.dockerfile
Update values of AZURE_STORAGE_ACCESS_KEY , AZURE_STORAGE_CONNECTION_STRING  and blobstorage wasbs
```
FROM python:3.7.0

LABEL maintainer "Azadeh Khojandi <azadehkhojandi@gmail.com>"



RUN pip install mlflow
RUN pip install azure-storage

ENV AZURE_STORAGE_CONNECTION_STRING 'DefaultEndpointsProtocol=https;AccountName=mlflowruns;AccountKey=xxxx==;EndpointSuffix=core.windows.net'
ENV AZURE_STORAGE_ACCESS_KEY 'xxx=='

EXPOSE 5000

CMD echo "running mlflow" &&  echo $AZURE_STORAGE_CONNECTION_STRING && echo $AZURE_STORAGE_ACCESS_KEY && ls /mlflow && mlflow server  --file-store /mlflow --default-artifact-root wasbs://xmlflowcontainerx@xmlflowrunsx.blob.core.windows.net/  --host 0.0.0.0
```
create a folder and name it `code`
create a folder and name it `aztestmlflow`

These two folders were mounted in docker compose file
inside code add these below two files (create.py,test.py)
create.py

```
import os
import mlflow
from mlflow import log_metric, log_param, log_artifact

if __name__ == "__main__":
    print ('test')
    
   # mlflow.set_tracking_uri("http://52.147.26.203:5000")
    mlflow.set_tracking_uri("mlflow:5000")
    
    exp=mlflow.create_experiment("aztest2") 
    print(exp)


```
test.py
```

import os
import mlflow
from mlflow import log_metric, log_param, log_artifact

if __name__ == "__main__":
    print ('test')

   
    # Log a parameter (key-value pair)
    mlflow.set_tracking_uri("mlflow:5000")
    log_param("param1", 5)
    
    # Log a metric; metrics can be updated throughout the run
    log_metric("foo", 1)
    log_metric("foo", 2)
    log_metric("foo", 3)

    # Log an artifact (output file)
    with open("output2.txt", "w") as f:
       f.write("Hello world!")
    
    file = open("output2.txt","r") 
    print (file.read()) 

    log_artifact("output2.txt")

    print(mlflow.get_artifact_uri())
```   


then run below commands 
```
docker build -t mlflow -f mlflow.dockerfile . 
docker build -t mlflowterminal -f mlflowterminal.dockerfile . 
docker-compose up
```

go inside mlflowterminal  container  and go to code folder run 

```
python ./create.py
python ./test.py
```

BUG=> mlflow ignores --file-store and --default-artifact-root flags and saves metrics and artifacts under `mlflow5000` folder

**Comment by DoktorMike** [comment]
Any news on this. I would sort of depend on this feature being present. :) Happy to help with testing etc.

**Comment by mrosales** [comment]
I think that the best way to do this (esp with python experiments) would just be to use standard logging and multiple destinations https://docs.python.org/3/howto/logging-cookbook.html#logging-to-multiple-destinations

You can pretty easily make the experiment log to both stdout/stderr and a file at a higher verbosity level and then just save the log file as an artifact which is already supported in MLFlow. I can't speak for anyone working on the MLFlow project, but I would much rather take this approach than try to have mlflow intercept logs or something of that nature.

If mlflow wanted to include this as a feature maybe it would look something like exposing a logging handler that could be added that would automatically be uploaded at the end of the run.

That would look something like:

```
logger = logging.getLogger(__name__)
# set up local logging configuration
mlflow.set_tracking_uri('http://localhost:5000') 
mlflow.set_experiment('my-logging-experiment')
logger.info('this is not uploaded since my run has not started')
with mlflow.start_run():
    logger.addHandler(mlflow.get_log_handler())
    logger.info('my experiment is running so the log handler will collect and upload this log')
logger.info('this is not uploaded since my run is over')
```

**Comment by E-B-Manohar** [comment]
I'm just curious.. is this issue solved? 
followed the trail from :
https://towardsdatascience.com/getting-started-with-mlflow-52eff8c09c61#:~:text=mlFlow%20is%20a%20framework%20that,each%20with%20it's%20own%20capabilities.

**Comment by SeguinBe** [comment]
This seems to be a much needed feature to me, something that I remeber wandb doing very well.

I agree with @mrosales proposition, was there something done in that direction in the end?
