### ISSUE TITLE
log_param fails if the value string has multiple lines.

### ISSUE THREAD

**Issue by hangelwen** [mlflow/mlflow#614]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**: 0.7.0
- **Python version**: 2.7.15
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
When I tried to use log_param to log a multiple line json string, it failed with 500. 

### Source code / logs
Source code to reproduce:
```
from  mlflow.tracking import MlflowClient
client = MlflowClient(MLFLOW_TRACK_SERVER)
run = client.create_run(0) # returns mlflow.entities.Run
client.log_param(run.info.run_uuid, "hello", "hello\nworld")
client.set_terminated(run.info.run_uuid)

```

Errors on client side:
```
PI request to http://relevance-datamining-utility2.snc1:5000/api/2.0/preview/mlflow/runs/update failed with code 500 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

API request to http://relevance-datamining-utility2.snc1:5000/api/2.0/preview/mlflow/runs/update failed with code 500 != 200, retrying up to 1 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Errors on Server side:
```
ERROR in app: Exception on /api/2.0/preview/mlflow/runs/update [POST]
Traceback (most recent call last):
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xxxi/anaconda2/lib/python2.7/site-packages/mlflow/server/handlers.py", line 160, in _update_run
    request_message.end_time)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/mlflow/store/file_store.py", line 243, in update_run_info
    run_info = self.get_run(run_uuid).info
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/mlflow/store/file_store.py", line 298, in get_run
    params = self.get_all_params(run_uuid)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/mlflow/store/file_store.py", line 403, in get_all_params
    params.append(self._get_param_from_file(parent_path, param_file))
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/mlflow/store/file_store.py", line 382, in _get_param_from_file
    % param_name)
Exception: Unexpected data for param 'hello'. Param recorded more than once
```

This happened for both python and Java API. Not sure about R since I did not use that.

**Comment by mparkhe** [comment]
Yes. The current tradeoff here for `FileStore` is that we are recording a single param (also metric) on a line. We want to ensure that a param is not logged again with a different value, hence the assertion.

Can you help me understand the use case here for multi-line params. `log_param` API was design to records hyper parameter used for a run, and we did not envision multi-line text. If you want to record additional information about a run, please consider using tags. Since version `0.7.0` you can record multi-line tags using `set_tag` API. It works similar to `log_params` and all you need to change is the method name.

**Comment by hangelwen** [comment]
@mparkhe Thanks for the details. I was not aware of the tag functionality. My use case was that I have some json strings from the pipeline: a. output meta data b. some stats about the input dataframe (e.g columns stats of input dataframe). I was kind of abusing the param logging to log these :) I'll use tag then. Thanks.

**Comment by rahulpshah** [comment]
@mparkhe I think we use to check in the log_params if the `value` that is sent contains a new line and raise ValueError. Currently, if someone sends a value with "\n", they are not able to work with active experiment due to the global `fluent._active_run_stack` which contains the corrupted run.
