### ISSUE TITLE
[FR] Treatment of Existing Model Versions in a Stage When Making Transitions

### ISSUE THREAD

**Issue by MinuraPunchihewa** [mlflow/mlflow#6156]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

It is possible to transition model versions using the `MlflowClient` as shown below,
```
client = MlflowClient()
client.transition_model_version_stage(
    name="sk-learn-random-forest-reg-model",
    version=3,
    stage="Production"
)
```
This does not provide any feature to define how models that already exist in the stage that the transition is made to, should be treated.

For example, in the above scenario, when version 3 is transitioned to Production and if version 2 is already in Production, it will continue to stay in Production.

However, I would like to be able to define how to treat version 2 in this situation. The default can still be to allow multiple versions in each stage.

This feature is already available through the UI,
![image](https://user-images.githubusercontent.com/49385643/176254936-cd8f9a01-00a7-4977-a4b9-8e0efe79a5fa.png)

### Motivation

> #### What is the use case for this feature?
It may sometimes be necessary for certain projects or use cases, to maintain only a single version of a model in Staging, Production or both. Therefore, when making transitions, it would be quite useful to be able to specify what to do with models that already exist in the stage that is being transitioned to.

> #### Why is this use case valuable to support for MLflow users in general?
I believe that this may be a common use case for many users: to be able to maintain a single model version in a chosen stage.

> #### Why is this use case valuable to support for your project(s) or organization?
For each model that we develop, we want to maintain a single Staging and Production version. Our model transitions are facilitated via a pipeline and it is quite cumbersome to first, find if there is a version of the model already in the stage that is being transitioned to and to make that transition to a different stage beforehand.

> #### Why is it currently difficult to achieve this use case?
Currently, before each transition, we will need to first transition the existing model version (in a given stage) to a different stage prior.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @MinuraPunchihewa. The behavior you're looking for is available by specifying the `archive_existing_versions=True` flag when calling `MlflowClient.transition_model_version_stage()`. For more information, see https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.transition_model_version_stage. Thank you for using MLflow!

**Comment by MinuraPunchihewa** [comment]
@dbczumar Thank you very much. Maybe that ought to be added here as well,
https://www.mlflow.org/docs/latest/registry.html

I was looking through here and I did not find that flag.
