### ISSUE TITLE
[FR] Currently unable to specify variant names when deploying models to Sagemaker

### ISSUE THREAD

**Issue by nfarley-soaren** [mlflow/mlflow#6178]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

I would like to add the ability to pass in a specific name for the model variant when deploying to Sagmaker as an additional argument to the deploy method in sagemaker/__init__.py.  Currently, variant names are autogenerated by _get_sagemaker_model_name using the endpoint name, model name and uid.  

### Motivation

> #### What is the use case for this feature?
To supply a specific name to each model variant hosted on Sagemaker.

> #### Why is this use case valuable to support for MLflow users in general?
The name would be more meaningful than the current default.

> #### Why is this use case valuable to support for your project(s) or organization?
This would be especially important for endpoints that host multiple models or different version of the same model (ex: for testing purposes).  It would make it much easier for the user to better understand the purpose of a given model based on its name and distinguish between models.  

> #### Why is it currently difficult to achieve this use case?
Currently, there is not way to specify the variant name when deploying, they are just generated automatically

### Details

I propose adding an argument to the deploy method where a specific name can be entered.  This will throw an error if that name currently exists or if it violates any naming conventions.  Use the current default method if no name is specified when calling this method.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
To make the model name unique, shall we define this additional argument as a suffix  ? so the final model_name will be {generated_model_name}-{suffix}

**Comment by nfarley-soaren** [comment]
Adding a suffix would allow for some model name customization.  Is the {generated_model_name} you mention in your comment above the full name (endpoint_name-model-uid) that is currently being generated by _get_sagemaker_model_name or do you propose substituting the suffix for the uid?   Is there a particular reason why you would not want to allow the names to be fully customizable?

**Comment by dbczumar** [comment]
@nfarley-soaren Your proposal sounds great. If you're still interested in contributing this feature, we'd be happy to review a pull request that extends the `mlflow.sagemaker` module with the custom model naming capability. Please let me know if you have any questions!

**Comment by nfarley-soaren** [comment]
@dbczumar I have code to submit but I don't have permission to do so.  How do I get that?
