### ISSUE TITLE
[BUG] Log_params seems to not use the correct maximum length of value

### ISSUE THREAD

**Issue by johnyNJ** [mlflow/mlflow#6183]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution MacOS 12.1**:
- **Python version 3.8.13**:

### Describe the problem

`log_params` seems to use different validation logic for max. parameter value length compared to `log_param`.
According to doc, parameter value should support length up to 5000 but in fact 250 limit seems to be there.
This passes:
```
some_params= {'p': [float(c) for c in range(int(45))]}
mlflow.log_param('p', some_params['p'])
```

But the same parameter logged with `log_params` will cause error
```
mlflow.log_params(some_params)
```

### Tracking information

```
MLflow version: 1.27.0
Tracking URI: file:///***/mlflow-bug/mlruns
Artifact URI: file:///***/mlflow-bug/mlruns/0/726fe0e42d564b7a93e395cb81fa593f/artifacts
```

### Code to reproduce issue

```python
import mlflow

print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())
r=45
some_params= {'p': [float(c) for c in range(int(r))]}
print("Length of stringified param", len((str(some_params['p']))))

mlflow.end_run()
with mlflow.start_run(experiment_id='0'):
    rid2 = mlflow.active_run().info.run_id
    mlflow.log_params(some_params)
```

### Other info / logs

```python-traceback
Traceback (most recent call last):
  File "repro_mini.py", line 13, in <module>
    mlflow.log_params(some_params)
  File "/Users/jan.sindlar/Library/Caches/pypoetry/virtualenvs/mlflow-bug-ZZrSkkBy-py3.8/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 675, in log_params
    MlflowClient().log_batch(run_id=run_id, metrics=[], params=params_arr, tags=[])
  File "/Users/jan.sindlar/Library/Caches/pypoetry/virtualenvs/mlflow-bug-ZZrSkkBy-py3.8/lib/python3.8/site-packages/mlflow/tracking/client.py", line 918, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/Users/jan.sindlar/Library/Caches/pypoetry/virtualenvs/mlflow-bug-ZZrSkkBy-py3.8/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 315, in log_batch
    self.store.log_batch(
  File "/Users/jan.sindlar/Library/Caches/pypoetry/virtualenvs/mlflow-bug-ZZrSkkBy-py3.8/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 883, in log_batch
    _validate_batch_log_data(metrics, params, tags)
  File "/Users/jan.sindlar/Library/Caches/pypoetry/virtualenvs/mlflow-bug-ZZrSkkBy-py3.8/lib/python3.8/site-packages/mlflow/utils/validation.py", line 320, in _validate_batch_log_data
    _validate_param(param.key, param.value)
  File "/Users/jan.sindlar/Library/Caches/pypoetry/virtualenvs/mlflow-bug-ZZrSkkBy-py3.8/lib/python3.8/site-packages/mlflow/utils/validation.py", line 148, in _validate_param
    _validate_length_limit("Param value", MAX_PARAM_VAL_LENGTH, value)
  File "/Users/jan.sindlar/Library/Caches/pypoetry/virtualenvs/mlflow-bug-ZZrSkkBy-py3.8/lib/python3.8/site-packages/mlflow/utils/validation.py", line 268, in _validate_length_limit
    raise MlflowException(
mlflow.exceptions.MlflowException: Param value '[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 4' had length 260, which exceeded length limit of 250
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Thanks for reporting this ! I will help review your fixing PR.

**Comment by WeichenXu123** [comment]
The `log_params` limit the param value length <= 250 at here:
https://github.com/mlflow/mlflow/blob/8693a26bf2acd418aa93aa5ea2e5536caa199fc3/mlflow/utils/validation.py#L148

**Comment by WeichenXu123** [comment]
@dbczumar 

Which param value length limitation shall we use ?

* `log_param` doc say value length limitation is 5000, but the code does not valiate the value length.
* `log_params` validate the value length to be <= 250, otherwise raise error
* `autologging` automatically truncate value to be length <= 250

**Comment by johnyNJ** [comment]
If I may... I see at least two reasons why not 250: 1) consistency, so `log_params` should allow the user to achieve the same as `log_param`. 2) 250 seems too low, e.g. in the case of parameter vectors of doubles it would only allow very short vectors after stringification.

**Comment by WeichenXu123** [comment]
Yea, 250 is too low, we can consider to increase it. And we should add the same value length limit validation for `log_param`.  @dbczumar WDYT ?

**Comment by dbczumar** [comment]
@johnyNJ @WeichenXu123 Thank you for raising this issue and discussing solutions. Here's my proposal:

1. Increase the minimum parameter value length supported by all backends to 500, as documented in https://mlflow.org/docs/latest/rest-api.html#log-param. This will require a database migration for `SqlAlchemyStore`, which current defines `value` as a length-500 column: https://github.com/mlflow/mlflow/blob/2037b384f3cef6c2e8828ec68201040bc3790235/mlflow/store/tracking/dbmodels/models.py#L410. It also requires adjusting length-checking logic in backend validation utilities (https://github.com/mlflow/mlflow/blob/8693a26bf2acd418aa93aa5ea2e5536caa199fc3/mlflow/utils/validation.py#L148), as pointed out by @WeichenXu123.

2. Fix the documentation for `mlflow.log_param()` to reflect that all backend stores support values up to length *500*, instead of *5000*. Also update the REST API documentation (https://mlflow.org/docs/latest/rest-api.html#log-param) to indicate that some backends may support larger parameter values (e.g. third-party backends).

3. Remove all *client-side* validation of parameter length from `log_param()` / `log_params()`, if any is present.

4. Adjust autologging behavior to only truncate parameters to length-500, rather than length-250.

@johnyNJ @WeichenXu123 Let me know what you think of this proposal. We are open to supporting longer values, though we'd like to understand the use case(s) first.

**Comment by WeichenXu123** [comment]
@dbczumar Good proposal, thank you !

**Comment by WeichenXu123** [comment]
@johnyNJ Would you create PR according to @dbczumar 's proposal above ? 
Or if you have better idea you can also raise it here.

**Comment by johnyNJ** [comment]
So it looks like I have misunderstood _raison d'être_ of `log_params` a bit. Ever since I became mlflow user, I have been logging parameters with `log_params`. Now I am beginning to understand that `log_params` is, in fact, meant exclusively for hyper-parameters logging while logging of model parameters (ie.e. those estimated by the model) is supposed to be done (indirectly) with `log_model`. Is this understanding correct? If not, then 500 limit will be easily exceeded which is how I found out about this problem. If yes, maybe we can clarify somewhere in doc that params is for hyper-parameters while model.

As for the proposal by @dbczumar above, looks ok and I will have no other comment there.

**Comment by dbczumar** [comment]
@harupy That sounds good to me. Additionally, it would be nice to fix the documentation so that we no longer claim that all backends support parameters of length 5000.

**Comment by johnyNJ** [comment]
@WeichenXu123 @harupy i am working on PR... i am not clear if I should do db migration script as well ([https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#database-schema-changes](url) ) since SqlAlchemyStore column is going to be enlarged. Any advice on that? Thanks

**Comment by harupy** [comment]
@johnyNJ The column length should be enlarged through migration.

**Comment by harupy** [comment]
```diff
diff --git a/mlflow/store/tracking/dbmodels/models.py b/mlflow/store/tracking/dbmodels/models.py
index 20979681f..dd23e764f 100644
--- a/mlflow/store/tracking/dbmodels/models.py
+++ b/mlflow/store/tracking/dbmodels/models.py
@@ -407,7 +407,7 @@ class SqlParam(Base):
     """
     Param key: `String` (limit 250 characters). Part of *Primary Key* for ``params`` table.
     """
-    value = Column(String(250), nullable=False)
+    value = Column(String(500), nullable=False)
     """
     Param value: `String` (limit 250 characters). Defined as *Non-null* in schema.
     """
```

Just changing `String(250)` to `String(500)` doesn't update the DB schema.

**Comment by harupy** [comment]
@johnyNJ Please let us know if we can help with migration part.
