### ISSUE TITLE
[FR] Add pyfunc example

### ISSUE THREAD

**Issue by sniafas** [mlflow/mlflow#6192]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

We can add a new section in examples/pyfunc and add some pyfunc examples.

### Motivation

> #### What is the use case for this feature?

Pyfunc is a powerful feature MLFlow offers

> #### Why is this use case valuable to support for MLflow users in general?

It's a nice idea to provide some hands on guidelines

> #### Why is this use case valuable to support for your project(s) or organization?

Pyfunc is a core functionality that supports our deployed models in production 

> #### Why is it currently difficult to achieve this use case?

Pyfunc has a bit steep learning curve to grasp and digest. Haven't spotted any fully reproducible example at the moment

### Details

We can start with an example inspired from this one https://github.com/mlflow/mlflow/pull/5663

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@sniafas This is a great idea. Looking forward to your contribution. Please let @WeichenXu123 if you have any questions. Thank you!
