### ISSUE TITLE
No module named pandas when " mlflow run"

### ISSUE THREAD

**Issue by forestlzj** [mlflow/mlflow#62]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.1.0
- **Python version**: 3.5.1
- **npm version (if running the dev UI):
- **Exact command to reproduce**:mlflow run example/tutorial -P alpha=0.5 --no-conda

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

 pandas 0.22.0 is installed in ubuntu16.04, it successfully run python example/tutorial/train.py:
python example/tutorial/train.py 
Elasticnet model (alpha=0.500000, l1_ratio=0.500000):
  RMSE: 0.82224284976
  MAE: 0.627876141016
  R2: 0.126787219728

but failed as below:
 mlflow run example/tutorial -P alpha=0.5 --no-conda
=== Fetching project from example/tutorial ===
=== Work directory for this run: example/tutorial ===
=== Created directory /tmp/tmpigdg385u for downloading remote URIs passed to arguments of type 'path' ===
=== Running command: python train.py 0.5 0.1 ===
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import pandas as pd
ImportError: No module named pandas
=== Run failed ===

double checked that pandas installed:
$ python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>>

**Comment by tomasatdatabricks** [comment]
Hi Forest.

I was not able to reproduce your issue unfortunately. 
The only thing that is different between the two runs is the working directory so my guess would be that your pandas is installed in a nonstandard location visible from the first directory and not visible from the second.

To verify, can you please try:

```
cd example/tutorial
python -c "import pandas as pd; print(pd.__version__)"

```

Best,

Tomas

**Comment by forestlzj** [comment]
~/git/mlflow/example/tutorial$ python -c "import pandas as pd; print(pd.__version__)"
0.22.0

python2 and python3 are installed in ubuntu and set python as python3 alias in .bashrc.  
alias python=python3

**Comment by smurching** [comment]
Hi @forestlzj, thanks for reporting the issue. Just wanted to check in on this - are you able to reproduce this issue with the latest MLflow? i.e. if you run `pip install --upgrade mlflow` and run `mlflow run example/tutorial -P alpha=0.5 --no-conda`?

**Comment by ailurus1991** [comment]
same error.
I printed the `sys.path` and found it was python2's.
So I changed the `python train.py {alpha} {l1_ratio}` in MLproject to `python3 train.py {alpha} {l1_ratio}`, it's ok now.

**Comment by baldwint** [comment]
I encountered this bug when running the [quickstart](https://mlflow.org/docs/latest/quickstart.html). I added the `--no-conda` flag to one of the commands because conda is not installed on my system.

Exact command to reproduce (from `mlflow/examples` directory): `mlflow run --no-conda sklearn_elasticnet_wine -P alpha=0.5`

OS: macOS Mojave 10.14.5
MLflow installed from: binary (via pip)
MLflow version: 1.0.0
Python version: 3.7.0

Output:


    2019/06/12 12:57:32 INFO mlflow.projects: === Created directory /var/folders/zp/5cf5y0t5653fnb4ml05_gqm80000gp/T/tmpdcvqo4ur for downloading remote URIs passed to arguments of type 'path' ===
    2019/06/12 12:57:32 INFO mlflow.projects: === Running command 'python train.py 0.5 0.1' in run with ID '537f948c1c2b412da48a6fa83cd7dcd4' === 
    Traceback (most recent call last):
      File "train.py", line 9, in <module>
        import pandas as pd
    ImportError: No module named pandas
    2019/06/12 12:57:32 ERROR mlflow.cli: === Run (ID '537f948c1c2b412da48a6fa83cd7dcd4') failed ===

I do have pandas installed.

**Comment by baldwint** [comment]
Shortly after posting, I was able to resolve the problem.

The python I thought I was using (my homebrewed install) is actually invoked using `python3`. I have a bash alias that maps `python` to `python3`. The command specified in the MLProject file does not apply bash aliases, so this was trying to run the example in my system python (which does not have pandas installed).

I was able to resolve this issue by modifying the `command` line in the `MLProject` file to say `python3`.

**Comment by DeboraLott** [comment]
I think my problem was very similar, it was: 

(base) C:\RepositoriosGitLab\mlflow_nexa_test>mlflow run examples/sklearn_elasticnet_wine_teste -P alpha=0.42
2021/02/10 15:13:29 INFO mlflow.projects.utils: === Created directory C:\Users\DEBORA~1.LOT\AppData\Local\Temp\tmp771791pl for downloading remote URIs passed to arguments of type 'path' ===
2021/02/10 15:13:29 INFO mlflow.projects.backend.local: === Running command 'conda activate mlflow-004410b12f95e2e00831a0ba11ee1bfdc29d6f9d && python train.py 0.42 0.1' in run with ID '05383b0542d14b7bac28472f6ff9f27e' ===
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    import boto3, os, io
ModuleNotFoundError: No module named 'boto3'
2021/02/10 15:13:31 ERROR mlflow.cli: === Run (ID '05383b0542d14b7bac28472f6ff9f27e') failed ===

But I tryed all solutions listed here, and in the end the solution for my problem was really simple, I just needed to add the library that I was trying to import as a dependence in the archive: **conda.yaml**.
Previous of my modification the archive was:

          name: tutorial
          channels:
            - defaults
          dependencies:
            - python=3.6
            - pip
            - pip:
              - scikit-learn==0.23.2
              - mlflow>=1.0
              
Now I just put boto3 in the end, turning it on this:

          name: tutorial
          channels:
            - defaults
          dependencies:
            - python=3.6
            - pip
            - pip:
              - scikit-learn==0.23.2
              - mlflow>=1.0
              - boto3
              
End them, finally it works!
