### ISSUE TITLE
Upgrade `pylint` to  `2.14.4`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#6200]
We currently use pylint 2.11.1. This is a bit old so we should upgrade it to the latest version (2.14.4):

https://github.com/mlflow/mlflow/blob/d40780be361f4bd2741c2e8fcbd428c1d693edcf/requirements/lint-requirements.txt#L1

- https://pypi.org/project/pylint/2.11.1/
- https://pypi.org/project/pylint/2.14.4/

**Comment by harupy** [comment]
Note pylint 2.14.4 might report issues that 2.11.1 doesn't.

**Comment by KarthikKothareddy** [comment]
Is this being worked on? If not I would like to make this tiny change as a first issue.

**Comment by harupy** [comment]
@KarthikKothareddy No, I just assigned myself as a reviewer. Looking forward to your PR :)

**Comment by KarthikKothareddy** [comment]
Thank you let me make that change and submit a PR :)

**Comment by KarthikKothareddy** [comment]
@harupy sorry for the confusion on the first PR, it looks like I didn't add the signature and I had to cancel it and open a new one. Please take a look (sorry if I missed anything obvious as this is my first PR here )

**Comment by harupy** [comment]
Not a problem!
