### ISSUE TITLE
[BUG] FileNotFoundError: [WinError 2] The system cannot find the file specified when running mlflow pipelines run --profile local

### ISSUE THREAD

**Issue by rvUnipart** [mlflow/mlflow#6201]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro (64 bit)
- **Python version**: 3.7.13 (also tried 3.8)
- **yarn version, if running the dev UI**:

### Describe the problem

Following the tutorials for the new MLflow Pipelines https://mlflow.org/docs/latest/pipelines.html and https://github.com/mlflow/mlp-regression-template. Just trying to get the template example to run.

Not sure if related but... if I try running the Jupyter Notebook example from the template, it can't find the module:
ModuleNotFoundError: No module named 'mlflow.pipelines' (imports fine if I try from Python CLI in Anaconda Prompt)

### Code to reproduce issue

1. Started a new conda env with "conda create -n mlflowpipelines python=3.7"
2. Activated env with "conda activate mlflowpipelines"
3. Cloned template with "git clone https://github.com/mlflow/mlp-regression-template.git"
4. Changed into dir with "cd mlp-regression-template"
5. Installed dependencies with "pip install -r requirements.txt"
6. Ran "mlflow pipelines run --profile local"

### Other info / logs

```
2022/07/06 11:37:50 INFO mlflow.pipelines.pipeline: Creating MLflow Pipeline 'mlp-regression-template' with profile: 'local'
Traceback (most recent call last):
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\mlflow\pipelines\cli.py", line 46, in run
    Pipeline(profile=profile).run(step)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\mlflow\pipelines\regression\v1\pipeline.py", line 337, in run
    return super().run(step=step)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\mlflow\pipelines\pipeline.py", line 79, in run
    self._get_step(step) if step else self._steps[-1],
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\mlflow\pipelines\utils\execution.py", line 74, in run_pipeline_step
    extra_env=make_env,
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\mlflow\pipelines\utils\execution.py", line 285, in _run_make
    extra_env=extra_env,
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\mlflow\utils\process.py", line 98, in _exec_cmd
    **kwargs,
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@rvUnipart Is `make` available on your machine?

**Comment by rvUnipart** [comment]
I think so, I've used `make` commands for Sphinx document creation on this setup

**Comment by harupy** [comment]
@rvUnipart Can you run this command?

```python
import subprocess

subprocess.run(["make", "--help"], check=True)
```

**Comment by rvUnipart** [comment]
Ah yes, same error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Also if I just run `make --help` in Anaconda terminal I get:

'make' is not recognized as an internal or external command,
operable program or batch file.

**Comment by harupy** [comment]
Can you install make?

**Comment by harupy** [comment]
@dbczumar It might be helpful to check if `make` is available and throw an error with a helpful message if it's not.

**Comment by rvUnipart** [comment]
I installed chocolately (non-admin) from here https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
then ran `choco install make` and `make --help` confirms it's installed.

Going back and running `mlflow pipelines run --profile local` again now fully completes (albeit with some warnings):

2022/07/07 11:04:59 INFO mlflow.pipelines.pipeline: Creating MLflow Pipeline 'mlp-regression-template' with profile: 'local'
2022/07/07 11:05:05 INFO mlflow.pipelines.steps.ingest.datasets: Resolving input data from '['C:\\Users\\Vizer\\Documents\\GitHub\\mlp-regression-template\\data\\sample.parquet']'
2022/07/07 11:05:05 INFO mlflow.pipelines.steps.ingest.datasets: Resolved input data to 'C:\Users\Vizer\AppData\Local\Temp\tmpir1n07dr\sample.parquet'
2022/07/07 11:05:05 INFO mlflow.pipelines.steps.ingest.datasets: Converting dataset to parquet format, if necessary
2022/07/07 11:05:05 INFO mlflow.pipelines.steps.ingest: Successfully stored data in parquet format at 'C:\Users\Vizer\.mlflow\pipelines\208664532fd0817634c474633ef5a5f6ff95373d8793410855a3c24d64c25765\steps\ingest\outputs\dataset.parquet'
2022/07/07 11:05:05 INFO mlflow.pipelines.steps.ingest: Profiling ingested dataset
2022/07/07 11:05:31 INFO mlflow.pipelines.steps.ingest: Wrote dataset profile to 'C:/Users/Vizer/.mlflow/pipelines/208664532fd0817634c474633ef5a5f6ff95373d8793410855a3c24d64c25765/steps/ingest/outputs\dataset_profile.html'
2022/07/07 11:05:36 INFO mlflow.pipelines.steps.split: Creating hash buckets on input dataset containing 10000 rows consumes 0.15857791900634766 seconds.
2022/07/07 11:05:36 INFO mlflow.pipelines.steps.split: Split dataset result: train split (8051 rows), validation split (959 rows), test split (990 rows).
2022/07/07 11:06:55 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2022/07/07 11:06:55 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
INFO  [alembic.runtime.migration] Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2022/07/07 11:06:55 INFO mlflow.pipelines.utils.tracking: Experiment with name 'sklearn_regression_experiment' does not exist. Creating a new experiment.
2022/07/07 11:07:00 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SGDRegressor was fitted with feature names
  "X does not have valid feature names, but"
C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\mlflow\models\signature.py:129: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  inputs = _infer_schema(model_input)
2022/07/07 11:07:24 INFO mlflow.models.evaluation.base: Evaluating the model with the default evaluator.
2022/07/07 11:07:24 INFO mlflow.models.evaluation.base: Evaluating the model with the default evaluator.
C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SGDRegressor was fitted with feature names
  "X does not have valid feature names, but"
C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SGDRegressor was fitted with feature names
  "X does not have valid feature names, but"
2022/07/07 11:07:36 INFO mlflow.models.evaluation.base: Evaluating the model with the default evaluator.
C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SGDRegressor was fitted with feature names
  "X does not have valid feature names, but"
C:\Users\Vizer\Anaconda3\envs\mlflowpipelines\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SGDRegressor was fitted with feature names
  "X does not have valid feature names, but"
X does not have valid feature names, but SGDRegressor was fitted with feature names
2022/07/07 11:07:38 INFO mlflow.models.evaluation.default_evaluator: Shap explainer _PatchedKernelExplainer is used.

  0%|          | 0/10 [00:00<?, ?it/s]X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names

 40%|####      | 4/10 [00:00<00:00, 30.76it/s]X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names

 80%|########  | 8/10 [00:00<00:00, 31.41it/s]X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names

100%|##########| 10/10 [00:00<00:00, 31.04it/s]
Unable to serialize underlying model using MLflow, will use SHAP serialization
Setuptools is replacing distutils.
elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
2022/07/07 11:07:48 INFO mlflow.models.evaluation.base: Evaluating the model with the default evaluator.
X does not have valid feature names, but SGDRegressor was fitted with feature names
X does not have valid feature names, but SGDRegressor was fitted with feature names
Successfully registered model 'taxi_fare_regressor'.
2022/07/07 11:07:53 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: taxi_fare_regressor, version 1
Created version '1' of model 'taxi_fare_regressor'.

Many thanks for the help harupy :)

**Comment by harupy** [comment]
Awesome! Can we close this issue?

**Comment by rvUnipart** [comment]
Happy to close

**Comment by OSobky** [comment]
I was trying out MLflow pipelines yesterday and I faced the same problem. I see @dbczumar already merged a PR to solve this problem. Maybe also consider adding this note in the [Regression Template](https://github.com/mlflow/mlp-regression-template#installation-instructions) so it is clear everywhere.
