### ISSUE TITLE
Timeout value too small: when downloading large model files, timeout is reached

### ISSUE THREAD

**Issue by bwallima** [mlflow/mlflow#6202]
https://github.com/mlflow/mlflow/blob/d40780be361f4bd2741c2e8fcbd428c1d693edcf/mlflow/store/artifact/http_artifact_repo.py#L63

**Comment by harupy** [comment]
Hi @bwallima, I filed https://github.com/mlflow/mlflow/pull/6206 to make the timeout value customizable by setting the `MLFLOW_HTTP_REQUEST_TIMEOUT` environment variable.
