### ISSUE TITLE
[FR] Support overriding profile.yml confs when running an MLflow pipeline  

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#6204]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

I'm trying to run an MLflow pipeline in production. I want to log runs to an experiment / register model versions to a registered model created and managed via the [Databricks Terraform Provider](https://github.com/databrickslabs/terraform-provider-databricks). The experiment ID / model name created by Terraform are stored in JSON files (e.g. `terraform-output/prod.json`).

It'd be nice if I could dynamically augment the conf of my pipeline before running it. Unfortunately this is difficult to achieve (AFAICT) using current tools - see the "Motivation" section below for detail

### Option 1: Provide Python API to override MLflow Pipeline configs
Add a `conf_overrides` constructor argument to the `Pipeline` class for passing pipeline overrides.

```python
def load_resource_ids(env):
  with open(os.path.join("terraform-output", f"{env}.json"), "r") as terraform_resources_handle:
    return json.load(terraform_resources_handle)

env = "prod"
# Produces a dict like {"mlflow_experiment_id": <id>, "mlflow_registered_model_name": <name>}
ids = load_resource_ids(env)

# Create a pipeline with config overrides supplied as a dict
p = Pipeline(profile=env, conf_overrides=ids)
p.run()
```

Pros:
* Flexible, allows loading confs from any external source, writing custom logic to conditionally set confs, etc.

Cons:
* Splits source of truth of pipeline configs across ML code, `profiles/*.yaml` files, and `profile.yaml`. Makes it harder to understand what configs are being used when code is run -> harder to reproduce and debug pipeline execution.

### Option 2: Provide custom DSL (Jinja filter) to read confs from terraform output YAML files

Another (much less flexible but more declarative) way to enable this use case could be to add a custom jinja filter for loading YAML (since JSON is a subset of YAML) to the [jinja Environment](https://github.com/mlflow/mlflow/blob/972c67dc48534befeb6b9664caeaf05afd0d0599/mlflow/utils/file_utils.py#L222-L224) used to render the final materialized pipeline YAML, e.g. just expose `yaml.load`-ing a file as a Jinja filter named `load_yaml`. Then profile.yml files could contain code like the following to load confs from JSON/YAML:

```yaml
experiment:
  id: {{ ("terraform-output/prod.json" | load_yaml )["mlflow_experiment_id"] }}
```

Pros:
* Compared to option 1, preserves `pipeline.yaml` and `profiles/*.yaml` files as the main mechanisms for customizing pipeline config
* Extensible to option 1 later on

Cons:
* Not as flexible as option 1 upfront
* Custom DSL for loading confs from JSON/YAML may be hard to discover. Users may also struggle to find docs for it and understand its behavior.

#### What is the use case for this feature?
Referencing production resources managed through infra-as-code in MLflow pipelines

#### Why is this use case valuable to support for MLflow users in general?
Simplifies and enables more production use cases with MLflow pipelines

#### Why is this use case valuable to support for your project(s) or organization?
Unblocks my usage of MLflow pipelines for production use :) 

#### Why is it currently difficult to achieve this use case?

The workarounds I can think of aren't great:

**Workaround 1: Leverage native YAML / Jinja functionality to include terraform output in pipeline config**
Unfortunately it seems YAML provides [no way to do this natively](https://stackoverflow.com/questions/528281/how-can-i-include-a-yaml-file-inside-another), and in Jinja there are [no builtin filters](https://jinja.palletsprojects.com/en/3.1.x/templates/#list-of-builtin-filters) for parsing JSON & [it's not possible](https://stackoverflow.com/a/4829057/12111347) to define custom Python code within templates themselves. [Jinja macros](https://jinja.palletsprojects.com/en/3.0.x/templates/#import) are also limited to executing Jinja code and so not a viable solution.

**Workaround 2: Convert terraform output into JSON that can be Jinja [`include`](https://jinja.palletsprojects.com/en/3.0.x/templates/#include)-d into profile.yaml**
This approach pushes the responsibility for producing MLP-compatible config output to external tools like Terraform. At least in the case of Terraform, [there's no obvious way](https://learn.hashicorp.com/tutorials/terraform/outputs#generate-machine-readable-output) to customize output format, so users would need to write their own logic for this using e.g. `jq`. This approach is pretty unwieldy.

**Workaround 3: Create a temporary profile.yml with configs substituted in**
Write user code to create a temporary profile.yml files with JSON terraform output merged in, call `pipeline.run()`, then tear down the temporary profile.yml file. This option is complicated and error-prone

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Thank you for filing this - we are looking into it.

**Comment by jinzhang21** [comment]
Working on this issue this week.

**Comment by jinzhang21** [comment]
Added a functionality to read a dictionary or a value from an external JSON file.
