### ISSUE TITLE
[BUG] Http artifact repo time out for large artifact downloads

### ISSUE THREAD

**Issue by Jason-CKY** [mlflow/mlflow#6205]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker
- **Python version**: 3.7
- **yarn version, if running the dev UI**:

### Describe the problem

The default timeout for downloading artifacts via http artifact store is 10seconds (https://github.com/mlflow/mlflow/blob/master/mlflow/store/artifact/http_artifact_repo.py#L63-L72).

This causes timeout errors if the server takes longer than 10 seconds to serve the artifact (may happen for large file downloads)

Suggest to set this as a keyword argument so that we can set a timeout for mlflow.pyfunc.load_model for large file downloads that will may take more than 10s for a response.

### Code to reproduce issue

```python
import mlflow

mlflow.pyfunc.load_model("runs:/xxx/xxx")
```

If the model .pkl file is very large, it will cause urllib to throw timeout errors with every retry due to the hard-coded 10s timeout.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @Jason-CKY, I filed https://github.com/mlflow/mlflow/pull/6206 to make the timeout value customizable by setting the MLFLOW_HTTP_REQUEST_TIMEOUT environment variable.
