### ISSUE TITLE
Artifacts logged from a Windows based client won't appear in a remote mlflow server that has been configured to use GCS

### ISSUE THREAD

**Issue by Wasala** [mlflow/mlflow#621]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: stock
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 (client), Ubuntu 16.04 server
- **MLflow installed from (source or binary)**:  pip install mlflow
- **MLflow version (run ``mlflow --version``)**: 0.7.0
- **Python version**:  3.7
- **npm version (if running the dev UI):
- **Exact command to reproduce**: Attempting to log artifact from Windows client to gcs bucket

### Describe the problem
An mlflow client running on Windows is set to track a remote mlflow server (running on Ubuntu) and the remote server is configured to log artifacts to Google Cloud Storage (GCS). When an artifact is logged in a run (via client), it will successfully get uploaded into the GCS bucket, but mlflow server's tracking UI shows no artifacts and it shows "No Artifacts Recorded. Use the log artifact APIs to store file outputs from MLflow runs." When examining the bucket it was noticed that the file has been uploaded as "artifacts\maxresdefault.jpg" into the bucket. i.e. It was not uploaded into a separate "artifacts" folder but  as a file with a forward slash in its name. It seems that in Windows, "path.join()" using the forward slash "\" seem to be the issue here.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Client code is running on Windows Jupyter notebook :
```
...
mlflow.set_tracking_uri(mlflow_tracking_URI)
..
with mlflow.start_run(run_name="experiment-5", source_name="this_script"):
	mlflow.log_artifact('maxresdefault.jpg')

```
Server ran as:
	`mlflow server --file-store ./mlflow-metadata --default-artifact-root gs://path-to-my-gcs-bucket --host 0.0.0.0`

I've modified the store/gcs_aritifact_repo.py's log_artifact function so that it will replace all the forward slashes with backslashes as follows.
```
    def log_artifact(self, local_file, artifact_path=None):
        (bucket, dest_path) = self.parse_gcs_uri(self.artifact_uri)
        if artifact_path:
            dest_path = build_path(dest_path, artifact_path)
        dest_path = build_path(dest_path, os.path.basename(local_file))
        gcs_bucket = self.gcs.Client().get_bucket(bucket)
        blob = gcs_bucket.blob(dest_path.replace('\\','/'))
        blob.upload_from_filename(local_file)

```
This resolved the issue for me. But a more permanent and a  better solution needs to be investigated.

**Comment by shadab-entrepreneur** [comment]
Were you able to resolve this issue? Similar kind of [issue](https://github.com/mlflow/mlflow/issues/2571) even I'm facing, can you have a look at this?
