### ISSUE TITLE
[FR] Support for Classification Pipelines

### ISSUE THREAD

**Issue by KarthikKothareddy** [mlflow/mlflow#6210]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Hello, thanks for the fantastic Pipelines release. I would like to know if along with the Regression Pipeline, the timeline for Classification, Time Series or even Custom templates. 
I would be happy to contribute to build out the Classification Pipeline with guidance from community. 

### Motivation

> #### What is the use case for this feature?
Integrate MLFlow Pipelines with Classification type problems
> #### Why is this use case valuable to support for MLflow users in general?
Since classification type problems are very common use case in ML world, it makes sense to include this into Pipelines.
> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@KarthikKothareddy Thank you for filing this feature request. I agree that a classification pipeline would be very useful. We're currently looking into this and should have more information soon about the timeline and how you can contribute.

**Comment by KarthikKothareddy** [comment]
> @KarthikKothareddy Thank you for filing this feature request. I agree that a classification pipeline would be very useful. We're currently looking into this and should have more information soon about the timeline and how you can contribute.

@dbczumar Thank you for your reply. Looking forward to the timeline!

**Comment by sunishsheth2009** [comment]
Hey @KarthikKothareddy, We recently added classification pipeline(now renamed to recipes) as part of the MLflow 2.0 release. We support both binary and multi-class classification. Here is a [template](https://github.com/mlflow/recipes-classification-template) and an [example](https://github.com/mlflow/recipes-examples/tree/main/classification) for you to play around. 
Did you get a chance to play around with it? If so, would love to hear some feedback. :) 
Thank you
