### ISSUE TITLE
[BUG] Batch inference with mlflow.pyfunc.spark_udf fails against timestamp input data types

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#6211]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Databricks ML Runtime 11.0

### Describe the problem

I'm trying to score a table using `mlflow.pyfunc.spark_udf`. The table has the schema shown below, with timestamp columns:
![image](https://user-images.githubusercontent.com/2358483/177837792-b77e3d53-a6ce-4f94-b80e-25149ee73475.png)

I have some wrapper logic around `mlflow.pyfunc.spark_udf` :

```python
import mlflow
from pyspark.sql.functions import struct


def predict_batch(spark_session, model_uri, input_table_name, output_table_name):
    """
    Apply the model at the specified URI for batch inference on the table with name input_table_name,
    writing results to the table with name output_table_name
    """
    table = spark_session.table(input_table_name)
    predict = mlflow.pyfunc.spark_udf(spark_session, model_uri, result_type="string", env_manager="conda")
    output_df = table.withColumn("prediction", predict(struct(*table.columns)))
    output_df.display()
    output_df.write.format("delta").mode("overwrite").saveAsTable(output_table_name)
```

When I try to call this function, e.g:
```python
predict_batch(spark, model_uri, input_table_name, output_table_name)
```

I get the following exception:
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (ip-10-68-149-252.us-west-2.compute.internal executor driver): org.apache.spark.api.python.PythonException: 'TypeError: Object of type Timestamp is not JSON serializable'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 1274, in udf
    os.kill(scoring_server_proc.pid, signal.SIGTERM)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 1116, in _predict_row_batch
    result = predict_fn(pdf)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 1247, in batch_predict_fn
    return client.invoke(pdf)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/pyfunc/scoring_server/client.py", line 39, in invoke
    post_data = json.dumps(scoring_server._get_jsonable_obj(data, pandas_orient="split"))
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:696)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:101)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:50)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:649)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
...
```

However, performing predictions locally using `mlflow.pyfunc.predict` doesn't hit the same JSON serialization issue:
```
import pandas as pd
pdf = spark.read.table("nyc_taxi_data_train").toPandas()
p.predict(pdf)
```

### Code to reproduce issue

See above

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by smurching** [comment]
I realized that the model I'm performing inference with (the one trained by https://github.com/mlflow/mlp-regression-template) does some feature engineering in its MLP `split` step to remove timestamp columns at training time, so I need to apply the same transformations at inference time. But still I think ^this bug may be worth fixing

**Comment by harupy** [comment]
Hey @smurching, we could define an encoder for `pandas.Timestamp` to avoid the error:

```pandas
import json
import pandas as pd


class PandasTimeStampEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, pd.Timestamp):
            return str(obj)
        return json.JSONEncoder.default(self, obj)


try:
    print(json.dumps({"timestamp": pd.Timestamp("2017-01-01T12")}))
except:
    print("error")

print(json.dumps({"timestamp": pd.Timestamp("2017-01-01T12")}, cls=PandasTimeStampEncoder))
```

**Comment by WeichenXu123** [comment]
> Hey @smurching, we could define an encoder for `pandas.Timestamp` to avoid the error:
> 
> ```python
> import pandas as pd
> 
> import json
> 
> 
> class PandasTimeStampEncoder(json.JSONEncoder):
>     def default(self, obj):
>         if isinstance(obj, pd.Timestamp):
>             return str(obj)
>         return json.JSONEncoder.default(self, obj)
> 
> 
> try:
>     print(json.dumps({"timestamp": pd.Timestamp("2017-01-01T12")}))
> except Exception as e:
>     print("Error", e)
> 
> print(json.dumps({"timestamp": pd.Timestamp("2017-01-01T12")}, cls=PandasTimeStampEncoder))
> ```
> 
> Output:
> 
> ```
> Error Object of type Timestamp is not JSON serializable
> {"timestamp": "2017-01-01 12:00:00"}
> ```
> 
> This might cause an issue if the model contains a transformer that takes a `timestamp` column and converts it to some numeric columns.

Shall we add the encoder into MLflow inference server code ?

**Comment by smurching** [comment]
@harupy @WeichenXu123 thanks for taking a look -

> This might cause an issue if the model contains a transformer that takes a timestamp column and converts it to some numeric columns.

To confirm my understanding, are you saying this might cause an issue because the timestamp (`"2017-01-01 12:00:00"`) would then be deserialized as a string rather than a timestamp, and so the model might not be able to perform inference on it? I wonder (but not sure) if this could be solved by adding logic in the inference server to deserialize timestamp types, as I think @WeichenXu123 is suggesting above. How do people usually get around this issue when working with `pandas`?

**Comment by harupy** [comment]
@smurching Yes, that's what I meant.

> How do people usually get around this issue when working with pandas?

I think they just extract some numerical features (e.g. `month`, `is_holiday`) from a datetime column, then drop it.

**Comment by smurching** [comment]
Thanks for the super speedy fix on this!
