### ISSUE TITLE
No such command 'models'

### ISSUE THREAD

**Issue by zz397** [mlflow/mlflow#6221]
want to use mlflow command line to run: `mlflow models ...` got Error: `No such command 'models'`. 
Tried installation with `pip install mlflow` or `pip install mlflow[extra]`. neither works.
Here is the output for `mlflow --help`

<img width="674" alt="Screen Shot 2022-07-08 at 10 51 17 AM" src="https://user-images.githubusercontent.com/54643014/178016852-28897607-3c66-4e6c-b510-d20fdf40b6cf.png">

**Comment by harupy** [comment]
@zz397 Thanks for reporting this issue. We're already aware of this issue and started working on fixing it. The PR will be filed soon :)

**Comment by harupy** [comment]
@zz397 Can you run `pip install git+https://github.com/harupy/mlflow.git@raise-import`, and then run `mlflow --help`? This should reveal why the `models` subcommand is not available.

**Comment by zz397** [comment]
> @zz397 Can you run `pip install git+https://github.com/harupy/mlflow.git@raise-import` ([branch](https://github.com/harupy/mlflow/tree/raise-import)), and then run `mlflow --help`? This should reveal why the `models` subcommand is not available.

this works!

**Comment by harupy** [comment]
@zz397 Thanks for the comment. What was the root cause?
