### ISSUE TITLE
[SETUP-BUG] custom gunicorn settings

### ISSUE THREAD

**Issue by raphaelauv** [mlflow/mlflow#6222]
### System information

no relative

### Code to reproduce issue

no relative

### Describe the problem

how can I custom the number of workers that run gunicorn ?

currently it run 4 workers , I would prefer only one so I can setup a lower ressource requests for my K8S preprod env

### Other info / logs

![Screenshot from 2022-07-08 17-08-41](https://user-images.githubusercontent.com/10202690/178020877-c72cab55-93ac-4ae4-b73f-db1e59996239.png)

**Comment by harupy** [comment]
Hi @raphaelauv, you can use specify the number of workers using `--workers`.

Doc: https://www.mlflow.org/docs/latest/cli.html#cmdoption-mlflow-server-w

**Comment by raphaelauv** [comment]
thanks @harupy
