### ISSUE TITLE
Unable to create an experiment with an old name

### ISSUE THREAD

**Issue by iamharsha1999** [mlflow/mlflow#6223]
I created an experiment with the name `dummy_test`. I deleted the experiment with the following piece of code. 
```
def delete_experiment(exp_id, tracking_uri = 'http://192.168.86.103:50034'):
    """
    Args:
        exp_id (int): Experiement ID
        tracking_uri (str): Tracking URI
    """
    

    print('Deleting the experiment...')
    # Clear the MLflow experiment and all their runs
    client = mlflow.tracking.MlflowClient(tracking_uri)
    experiment = client.get_experiment(exp_id)
    print("Name: {}".format(experiment.name))
    print("Artifact Location: {}".format(experiment.artifact_location))
    print("Lifecycle_stage: {}".format(experiment.lifecycle_stage))
    client.delete_experiment(exp_id)

```

And then I ran mlflow gc CLI to delete everything with lifecycle stage  = 'deleted'

Im now trying to create an experiment with the same name `dummy_test`. 

It outputs the following error for me. 

```
 raise MlflowException("API request to %s failed with exception %s" % (url, e))
mlflow.exceptions.MlflowException: API request to http://192.168.86.103:50034/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='192.168.86.103', port=50034): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by ResponseError('too many 500 error responses'))

```

However If I change the experiment name to something else, the code runs smoothly.

**Comment by harupy** [comment]
Hi @iamharsha1999, `mlflow gc` only delete runs. Unfortunately, we don't provide a command or API that permanently deletes an experiment.

Related SO question: https://stackoverflow.com/questions/60088889/how-do-you-permanently-delete-an-experiment-in-mlflow

**Comment by iamharsha1999** [comment]
I was using "psql <connection_string>" as my backend_store parameter value. So it was basically creating with the same name rather than actually saving in the db. Hence I was deleting data in the wrong place and expected a change. 

I believe you incorporate some mechanism to check the validity of different parameter values. 

However I'm closing the issue for now.
