### ISSUE TITLE
GRPC api for MLFlow Tracking

### ISSUE THREAD

**Issue by zak-hassan-hs** [mlflow/mlflow#623]
### New Feature Request
GRPC api for MLFlow Tracking

### Describe the problem
If we had a grpc api for mlflow tracking. I think it would make it easy for support in multiple languages. You would be able to auto generate clients in multiple programming languages.

**Comment by pogil** [comment]
This is great idea and would welcome a community contribution in this space. However, it's unlikely we'll implement this in the near term. I'll close this ticket for now.

**Comment by ulhaqi12** [comment]
Is there any update on this?
I am willing to contribute if there's any existing plan or if we can make one.

-Ikram
