### ISSUE TITLE
How does the mlflow artifact proxy server configure AWS credentials?

### ISSUE THREAD

**Issue by zstern** [mlflow/mlflow#6233]
I am trying to use an mlflow server with proxied artifact storage set up in s3.  
https://www.mlflow.org/docs/latest/tracking.html#logging-to-a-tracking-server

The mlflow server is running in its own container in an ec2 instance. So far it is either unable to access the s3 bucket (invalid access token) or I've had to configure client side credentials.  When I configure client side credentials i am able to load a model to the registry.  Also, I can use the mlflow client to list registered models just fine.

since the mlflow server is running in a container do you need to map a folder so that it can access aws credentials? Do the credentials need to be stored in environment variables when the server is started? How else would the mlflow server in the container get the aws credentials to access the S3 bucket? 

This is what I'm running to start the mlflow server:
`CMD mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_ROOT} \ 
    --host 0.0.0.0 --port 5000 --artifacts-destination ${ARTIFACT_ROOT} \ 
    --serve-artifacts`

**Comment by harupy** [comment]
The mellow server just let boto3 look for AWS credentials: 

https://github.com/mlflow/mlflow/blob/81cbfa64ff80cb204ea3740e69ed168b1788acdc/mlflow/store/artifact/s3_artifact_repo.py#L53-L58


> since the mlflow server is running in a container do you need to map a folder so that it can access aws credentials?

Can you elaborate on `map a folder`? You mean mounting the `~/.aws` folder in the container?

> Do the credentials need to be stored in environment variables when the server is started?

yes

**Comment by zstern** [comment]
OK. Thank you.  Makes sense, I just didn't see it in the docs so was wondering how the auth would work.  Thanks.

**Comment by zstern** [comment]
I have added the AWS credentials as environment variables but MLFLOW is still unable to access the s3 bucket.  If I ssh into the running docker container running mlflow, bring up a python interpreter and use the boto3 package, I can successfully interact with my s3 bucket (listing and downloading files) without any problem:


```
>>> import boto3
>>> resource = boto3.resource('s3')
>>> bucket = resource.Bucket('my-bucket')
```

So I am certain in that scenario that boto3 is correctly finding the env vars.  

When I go to my local client and configure the mlflow_client to point to the mlflow server, I can sucesfully connect and list the experiements, but when I got to upload a model and artifacts using


```
with mlflow.start_run(run_name=name, tags={'type':'fmv'},
                      experiment_id='1') as run:
                      
                      mlflow.log_artifact(f'{path}/MLmodel', artifact_path=name)
                      mlflow.log_artifact(f'{path}/config.yml', artifact_path=name)
                      mlflow.log_artifact(f'{path}/conda.yaml', artifact_path=name)
                      mlflow.log_artifact(f'{path}/model_config.yaml', artifact_path=name)
                      mlflow.log_artifact(f'{path}/processing.py', artifact_path=name)
                      mlflow.onnx.log_model(model, artifact_path=name)
```


I get the error:
`NoCredentialsError: Unable to locate credentials`

My dockerized version of mlflow is running from the following docker files:


```
FROM python:3-slim
ARG MLFLOW_VERSION=1.27.0

WORKDIR /mlflow/

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

WORKDIR /mlflow/


EXPOSE 5000

CMD mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_ROOT} \ 
    --host 0.0.0.0 --port 5000 --artifacts-destination ${ARTIFACT_ROOT} \ 
    --serve-artifacts
```

```
version: '3'

services:
  mlflow:
    image: 'atcommons/mlflow-server'
    build: .
    ports:
      - "8080:5000"
    volumes:
      - "./data:/mlflow"
      - "./scripts:/mlflow/scripts"
    environment:
      BACKEND_URI: sqlite:////mlflow/mlflow.db
      ARTIFACT_ROOT: s3://<mybucket>
      AWS_ACCESS_KEY_ID: key
      AWS_SECRET_ACCESS_KEY: secret
      AWS_SESSION_TOKEN:token
```

To clarify, I understood the correct behavior of running mlflow in '--server-artifacts' mode, was that I would not have to put in credentials on the client side to upload/download artifacts.  But that is not able to happen in this scenario.  

Any help or insight would be appreciated.

Thanks,

**Comment by harupy** [comment]
@zstern I think it's because experiment `1` still uses a non-proxied artifact.

https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/17039389/179325106-f2b68c27-dacf-4d98-a7c9-91babae4405e.png">

**Comment by harupy** [comment]
@zstern Any updates here?

**Comment by zstern** [comment]
Created new experiment through gui and tried to upload artifacts and also created new experiment via the code snippet you listed above.  Tried to log artifacts and get `NoCredentialsError: Unable to locate credentials` , though in doing some other tests there may be some other admin settings preventing access. For some reason the boto3 access, which was working, does not work now.  Feel free to close this ticket and I will reopen if necessary if mlflow appears to be the source of the error again. Thank you.

**Comment by michalisfrangos** [comment]
Hi all, I am using DigitalOcean application platform to start an mlflow  server following **[option 5]**(https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access) so that the credentials are sorted out only on the server side. I am using **mlflow, version 2.1.1.**

All work fine if I run the server with (option 1 , all saved locally on the server): 

`mlflow server 
    --host 0.0.0.0 
    --port 5000 
    --backend-store-uri ${DATABASE_URL} `

**However I have an issue when I try to set as an artifacts location  a SPACES bucket (equivalent to S3 bucket) with:** 

I provide below more information. I have tried various things unsuccessfully, hence my post over here. Any suggestions much appreciated. Thanks.

=============== 
SERVER SIDE
===============
I create a digital ocean app where the following environments are exposed during the creation of the docker image creation and these persist within the docker image once the server is up and running.

```The environment variables are defined  
# ${BUCKET_KEY_VALUE} 
# ${BUCKET_KEY_NAME}
# ${MLFLOW_S3_ENDPOINT_URL}
# ${MLFLOW_BUCKET}
# {DATABASE_URL} 
The Dockerfile I used on the server side is :

```
FROM python:3.9-slim
EXPOSE 5000
WORKDIR /root/local/mlflow
COPY . .
RUN pip3 install -r requirements.txt
CMD mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri ${DATABASE_URL} \
    --artifacts-destination s3://${MLFLOW_BUCKET}/artifacts \
    --serve-artifacts

And the requirements.txt:

```
boto3
pymysql
psycopg2-binary
sqlalchemy 
mlflow[extras]

```

===============
CLIENT SIDE
===============
```
import mlflow
import uuid

uri = "https://nameofapp.ondigitalocean.app"  # this is the same as ${MLFLOW_S3_ENDPOINT_URL} env on the server
mlflow.set_tracking_uri(uri)
mlflow.set_experiment(uuid.uuid4().hex)

model = Model()
with mlflow.start_run() as run:
      model_info = mlflow.pyfunc.log_model(artifact_path="model",
                                                                     python_model=model,
                                                                     registered_model_name="some_model_name")
```
---------------
ERRORS
---------------

When I go at the app url I see the MLFLOW user interface with an experiment id and  the a run name. I also see that artifact location is set to (is this the expected?)

`https://bucketname.region.digitaloceanspaces.com/0
`
The bucket is empty though (0 bytes) and the following error appears:

![Screenshot 2023-02-24 215618](https://user-images.githubusercontent.com/17205240/221278310-dc58c8c9-f899-48d0-8aa8-990b4c57604a.png)

Checking on the server:

```
2023/02/24 19:39:31 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/artifacts/list [GET]
[mlflow] [2023-02-24 19:39:31] Traceback (most recent call last):
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
[mlflow] [2023-02-24 19:39:31]     response = self.full_dispatch_request()
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
[mlflow] [2023-02-24 19:39:31]     rv = self.handle_user_exception(e)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
[mlflow] [2023-02-24 19:39:31]     rv = self.dispatch_request()
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
[mlflow] [2023-02-24 19:39:31]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 459, in wrapper
[mlflow] [2023-02-24 19:39:31]     return func(*args, **kwargs)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 529, in wrapper
[mlflow] [2023-02-24 19:39:31]     return func(*args, **kwargs)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 940, in _list_artifacts
[mlflow] [2023-02-24 19:39:31]     artifact_entities = _get_artifact_repo(run).list_artifacts(path)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 159, in list_artifacts
[mlflow] [2023-02-24 19:39:31]     for result in results:
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
[mlflow] [2023-02-24 19:39:31]     response = self._make_request(current_kwargs)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
[mlflow] [2023-02-24 19:39:31]     return self._method(**current_kwargs)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
[mlflow] [2023-02-24 19:39:31]     return self._make_api_call(operation_name, kwargs)
[mlflow] [2023-02-24 19:39:31]   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
[mlflow] [2023-02-24 19:39:31]     raise error_class(parsed_response, operation_name)
[mlflow] [2023-02-24 19:39:31] botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: Unknown
[mlflow] [2023-02-24 19:40:14] 2023/02/24 19:40:14 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/artifacts/list [GET]
[mlflow] [2023-02-24 19:40:14] Traceback (most recent call last):
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
[mlflow] [2023-02-24 19:40:14]     response = self.full_dispatch_request()
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
[mlflow] [2023-02-24 19:40:14]     rv = self.handle_user_exception(e)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
[mlflow] [2023-02-24 19:40:14]     rv = self.dispatch_request()
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
[mlflow] [2023-02-24 19:40:14]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 459, in wrapper
[mlflow] [2023-02-24 19:40:14]     return func(*args, **kwargs)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 529, in wrapper
[mlflow] [2023-02-24 19:40:14]     return func(*args, **kwargs)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/mlflow/server/handlers.py", line 940, in _list_artifacts
[mlflow] [2023-02-24 19:40:14]     artifact_entities = _get_artifact_repo(run).list_artifacts(path)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 159, in list_artifacts
[mlflow] [2023-02-24 19:40:14]     for result in results:
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
[mlflow] [2023-02-24 19:40:14]     response = self._make_request(current_kwargs)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
[mlflow] [2023-02-24 19:40:14]     return self._method(**current_kwargs)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
[mlflow] [2023-02-24 19:40:14]     return self._make_api_call(operation_name, kwargs)
[mlflow] [2023-02-24 19:40:14]   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
[mlflow] [2023-02-24 19:40:14]     raise error_class(parsed_response, operation_name)
[mlflow] [2023-02-24 19:40:14] botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: Unknown
```

**Comment by dotdothu** [comment]
I am facing a similar situation (GCP not AWS).

Has your issue got sorted @zstern ?

https://github.com/mlflow/mlflow/issues/10326
