### ISSUE TITLE
log_param fails and breaks mlflow server if value is an empty string

### ISSUE THREAD

**Issue by pdrharris** [mlflow/mlflow#624]
### System information
- Custom code based on stock example
- Ubuntu running in docker container
- installed from binary
- MLflow version (run ``mlflow --version``)**: 0.7.0
- Python Version 3.6.1
- npm version (if running the dev UI): N/A
- mlflow.log_param('Purpose', input("What is the purpose of this run? "))

### Describe the problem
On passing an empty string as the value field to log_param, there is no error.
However, the next attempt to log anything throws an error (traceback below). 

MLFlow server then responds to any attempts to view that experiment or any runs in it with "Oops! Something went wrong..."

The only way to retrieve the situation is 
1) Delete the experiment (or possibly the run)
2) Restart the MLFlow server

### Source code / logs
mlflow.log_param('Purpose', input("What is the purpose of this run? "))
<_Blank input is given, i.e. enter is pressed_>
logger.log_param('Run Title', 'Test Run Runnymede')

ExceptionTraceback (most recent call last)
<ipython-input-8-7b381bc20b27> in <module>
----> 1 logger.log_param('Run Title', 'Test Run Runnymede')
      2 for index, line in enumerate([5, 1, -1]):
      3     logger.log_metric('x', line, index)  # log_metric will store the whole history of these values, so that you can see, e.g. how loss decreased.
      4     logger.log_metric('y', 1/line, index)

<ipython-input-7-782860fca693> in log_param(self, key, value)
     44 
     45     def log_param(self, key, value):
---> 46         mlflow.log_param(key, value)
     47 
     48     def log_metric(self, key, value, index):

/opt/conda/envs/fabrik/lib/python3.6/site-packages/mlflow/tracking/fluent.py in log_param(key, value)
    173     """
    174     run_id = _get_or_start_run().info.run_uuid
--> 175     MlflowClient().log_param(run_id, key, value)
    176 
    177 

/opt/conda/envs/fabrik/lib/python3.6/site-packages/mlflow/tracking/client.py in log_param(self, run_id, key, value)
    134         _validate_param_name(key)
    135         param = Param(key, str(value))
--> 136         self.store.log_param(run_id, param)
    137 
    138     def set_tag(self, run_id, key, value):

/opt/conda/envs/fabrik/lib/python3.6/site-packages/mlflow/store/file_store.py in log_param(self, run_uuid, param)
    463         _validate_run_id(run_uuid)
    464         _validate_param_name(param.key)
--> 465         run = self.get_run(run_uuid)
    466         check_run_is_active(run.info)
    467         param_path = self._get_param_path(run.info.experiment_id, run_uuid, param.key)

/opt/conda/envs/fabrik/lib/python3.6/site-packages/mlflow/store/file_store.py in get_run(self, run_uuid)
    296         run_info = self._get_run_info(run_uuid)
    297         metrics = self.get_all_metrics(run_uuid)
--> 298         params = self.get_all_params(run_uuid)
    299         tags = self.get_all_tags(run_uuid)
    300         return Run(run_info, RunData(metrics, params, tags))

/opt/conda/envs/fabrik/lib/python3.6/site-packages/mlflow/store/file_store.py in get_all_params(self, run_uuid)
    401         params = []
    402         for param_file in param_files:
--> 403             params.append(self._get_param_from_file(parent_path, param_file))
    404         return params
    405 

/opt/conda/envs/fabrik/lib/python3.6/site-packages/mlflow/store/file_store.py in _get_param_from_file(parent_path, param_name)
    377         param_data = read_file_lines(parent_path, param_name)
    378         if len(param_data) == 0:
--> 379             raise Exception("Param '%s' is malformed. No data found." % param_name)
    380         if len(param_data) > 1:
    381             raise Exception("Unexpected data for param '%s'. Param recorded more than once"

Exception: Param 'Purpose' is malformed. No data found.

**Comment by dstine** [comment]
Same behavior experienced with version 0.8.2: #888

**Comment by rharang** [comment]
More or less identical behavior occurs on 1.0.0 (failing the run, breaking the UI, unfixable without deleting the run/experiment) also occurs if you're running mlflow on linux and your MLproject file has windows style (CRLF) line breaks instead of Linux-style (LF) line breaks.

**Comment by ankitmathur-db** [comment]
@rharang - I cannot reproduce this issue in 1.1.0. Can you post repro instructions and reopen the issue when you do?

Given that we don't support Projects on Windows, I wouldn't expect there to be logic checking for this. If it's easy enough, we'd love to see a PR for this.
