### ISSUE TITLE
[SETUP-BUG] Python 3.7 not so supported

### ISSUE THREAD

**Issue by Judekeyser** [mlflow/mlflow#6262]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: irrelevant
- **MLflow installed from (source or binary)**: from pip
- **MLflow version (run ``mlflow --version``)**: 1.27.0
- **Python version**: 3.7

### Code to reproduce issue

```bash
python3.7 -m venv e
source e/bin/activate
pip install mlflow==1.27.0
```

### Describe the problem

When installing mlflow==1.27.0 using pip in a Python 3.7 environment, pip fetches scipy version 1.8.1; which seems ok with respect to the core-requirements.txt file (scipy<2 in there). However, scipy version 1.8.1 cannot be installed with python < 3.8.

My project does not need scipy, so I do not wish to manually install an earlier version to make it possible to use mlflow. I think MLflow dependencies should stay coherent with the minimal supported version (from mlflow's setup.py file).

**Comment by harupy** [comment]
@Judekeyser You don't have to manually install an older version of scipy. pip automatically selects the version that can be installed. scipy 1.7.3 should be installed in Pythion 3.7.

**Comment by Judekeyser** [comment]
Confirmed on a clean machine. I suspect the bug is due to tox py37. Thank you anyway, now I know where to look at.
