### ISSUE TITLE
Enable `useless-object-inheritance` for pylint

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#6269]
### Task

Enable `useless-object-inheritance` for pylint to prevent useless object inheritance:
https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/useless-object-inheritance.html

### Lines that need to be changed

https://github.com/mlflow/mlflow/blob/4f5d3f095da9ed6699941d8aacb9925488ff2fb5/pylintrc#L174-L177

**Comment by KarthikKothareddy** [comment]
@harupy I can take this if you haven’t started.
