### ISSUE TITLE
Tracking UI breaks when there are too many runs for a single experiment

### ISSUE THREAD

**Issue by PsiPhire** [mlflow/mlflow#627]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 18.04, Firefox 62.0.3 and Chrome 69.0.3497.100
- **MLflow installed from (source or binary)**:  binary (via pip)
- **MLflow version (run ``mlflow --version``)**: 0.7
- **Python version**: 3.7
- **npm version (if running the dev UI):** N/A
- **Exact command to reproduce**: mlflow ui

### Describe the problem
I'm running mlflow locally and I am logging all my runs to a single experiment (the default experiment). Everything works fine, until there are too many runs at which point the UI breaks: up to 1700 runs worked fine, but as soon as there are 1701 runs the UI breaks (i.e. all I see is the Niagara falls image).

In my browser console I can see that the GET request ( `GET http://localhost:5000/ajax-api/2.0/preview/mlflow/experiments/get?experiment_id=0`) was successful, but the UI is broken.

I can view all the runs for this experiment fine by using cURL: `curl http://localhost:5000/api/2.0/preview/mlflow/experiments/get --request GET --header "Content-Type: application/json" --data '{"experiment_id": "0"}'`.

#### Successful request and UI working fine with 1700 runs (there are 1700 runs in the `./mlruns/0/` folder, but the UI says there are only 1698).

![mlflow_working](https://user-images.githubusercontent.com/25529496/46903302-5b4d1600-ced3-11e8-8dba-8a6bcb75ef47.png)

#### Successful request but broken UI with 1701 runs

![mlflow_breaking](https://user-images.githubusercontent.com/25529496/46903305-5ee09d00-ced3-11e8-9da7-854d69de0c9e.png)

**Comment by Ace139** [comment]
I'm facing the same issue in version 0.8 also. Has this issue addressed yet ?

**Comment by Deborah-Yin** [comment]
I am also facing the issue! Any idea on how to resolve this? Many thanks

**Comment by smurching** [comment]
Hi all, sorry for the delayed response on this - from what I can tell this happens because the runs search endpoint becomes quite slow (taking >30 seconds) for large numbers of runs (see chrome developer console screenshot below):

<img width="1670" alt="screen shot 2018-12-04 at 6 02 22 pm" src="https://user-images.githubusercontent.com/2358483/49485189-d2759b00-f7ee-11e8-853c-9361b29c6cd2.png">

It turns out gunicorn has a [default request timeout of 30 seconds](http://docs.gunicorn.org/en/stable/settings.html#timeout), so the server kills the connection. In MLflow 0.8.0, it's possible to increase this timeout via the `--gunicorn-opts` flag, e.g. by running `mlflow server --gunicorn-opts "--timeout=120"` I'm then able to get the UI to load, although it takes nearly 2 minutes for me to load 1700 runs & the UI is quite laggy. We're aware the current tracking storage implementation & UI have scaling issues, with the former being tracked in https://github.com/mlflow/mlflow/issues/685 & the latter to-be-addressed via a combination of pagination and [virtualizing the runs table](https://github.com/bvaughn/react-virtualized). In the mean time I think the best available workaround is to try to split runs across experiments.

**Comment by shadowdsp** [comment]
> Hi all, sorry for the delayed response on this - from what I can tell this happens because the runs search endpoint becomes quite slow (taking >30 seconds) for large numbers of runs (see chrome developer console screenshot below):
> 
> <img alt="screen shot 2018-12-04 at 6 02 22 pm" width="1670" src="https://user-images.githubusercontent.com/2358483/49485189-d2759b00-f7ee-11e8-853c-9361b29c6cd2.png">
> 
> It turns out gunicorn has a [default request timeout of 30 seconds](http://docs.gunicorn.org/en/stable/settings.html#timeout), so the server kills the connection. In MLflow 0.8.0, it's possible to increase this timeout via the `--gunicorn-opts` flag, e.g. by running `mlflow server --gunicorn-opts "--timeout=120"` I'm then able to get the UI to load, although it takes nearly 2 minutes for me to load 1700 runs & the UI is quite laggy. We're aware the current tracking storage implementation & UI have scaling issues, with the former being tracked in #685 & the latter to-be-addressed via a combination of pagination and [virtualizing the runs table](https://github.com/bvaughn/react-virtualized). In the mean time I think the best available workaround is to try to split runs across experiments.

I want to watch my metrics, but there are about 100,000 data points, and it has the above error even if I set `--gunicorn-opts "--timeout=120"`. I have never wait for a long time(10s), and my get request return 200.

**Comment by mbelang** [comment]
related: https://github.com/mlflow/mlflow/issues/1517

**Comment by pogil** [comment]
We believe we have addressed this with limits and "Load More" functionality in MLflow 1.1

**Comment by daviddwlee84** [comment]
Same issue. When my runs exceeded 100 this happened.

```python
mlflow.search_runs(experiment_names=["the_exp_exceed_100_runs"])
```
```txt
mlflow.exceptions.MlflowException: API request to http://192.168.222.235:8080/api/2.0/mlflow/runs/search failed with exception HTTPConnectionPool(host='192.168.222.235', port=8080): Max retries exceeded with url: /api/2.0/mlflow/runs/search (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```

[MLflow Tracking Server — MLflow 2.13.0 documentation](https://mlflow.org/docs/latest/tracking/server.html)

I am guessing it is because the default backend store is using file system.

> By default, the tracking server logs runs metadata to the local filesystem under ./mlruns directory.
>
> By default, the tracking server stores artifacts in its local filesystem under ./mlartifacts directory.

**Comment by daviddwlee84** [comment]
Seems in file system mode, MLFlow will go through the entire folder and cause worker timeout.

Adhoc fixing this by removing runs from `./mlruns/exp_id`

```bash
# List the 100 oldest folders
ls -lt --time=ctime --time-style=long-iso ./mlruns/exp_id | grep '^d' | tail -n 100

# Move the 100 oldest folders
for dir in $(ls -lt --time=ctime --time-style=long-iso ./mlruns/exp_id | grep '^d' | tail -n 100 | awk '{print $8}'); do
  mv ./mlruns/exp_id/"$dir" /mlruns_backup/exp_id/
done
```

This operation is fine even with the MLFlow server running.
