### ISSUE TITLE
Enable `super-with-arguments` rule for pylint

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#6270]
### Task

Enable `super-with-arguments` for pylint to prevent useless `super` arguments:
https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/super-with-arguments.html

### Lines that need to be changed

https://github.com/mlflow/mlflow/blob/4f5d3f095da9ed6699941d8aacb9925488ff2fb5/pylintrc#L174-L177

**Comment by KarthikKothareddy** [comment]
@harupy I can take this too

**Comment by harupy** [comment]
@KarthikKothareddy Thanks for the help!

**Comment by harupy** [comment]
@KarthikKothareddy Any updates?
