### ISSUE TITLE
[BUG] OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by zstern** [mlflow/mlflow#6274]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
as underlying OS

Running Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
docker-compose version 1.25.0

```
FROM python:3-slim
ARG MLFLOW_VERSION=1.27.0

WORKDIR /mlflow/

COPY ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

EXPOSE 5000

CMD mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_ROOT} \ 
    --host 0.0.0.0 --port 5000 
```
```
version: '3'

services:
  mlflow:
    image: 'atcommons/mlflow-server'
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./data:/mlflow
      - ./data/mlartifacts:/mlflow/mlartifacts:rw
    environment:
      BACKEND_URI: sqlite:////mlflow/mlflow.db
      ARTIFACT_ROOT: /mlflow/mlartifacts
```

requirements.txt:

mlflow==1.27.0
psycopg2-binary
boto3

### Describe the problem

If I try to log an experiment and add artifacts using the following:

```
import uuid
import mlflow
model = onnx.load(f'{path}/model.onnx')
mlflow.set_experiment(uuid.uuid4().hex)

with mlflow.start_run(run_name=name):
    mlflow.get_artifact_uri()
    mlflow.log_artifact(f'{path}/MLmodel', artifact_path=name)
    mlflow.log_artifact(f'{path}/config.yml', artifact_path=name)
    mlflow.log_artifact(f'{path}/conda.yaml', artifact_path=name)
    mlflow.log_artifact(f'{path}/model_config.yaml', artifact_path=name)
    mlflow.log_artifact(f'{path}/processing.py', artifact_path=name)
    mlflow.onnx.log_model(model, artifact_path=name)

```

I get the error:
`OSError: [Errno 30] Read-only file system: '/mlflow'`

If I ssh into the container I can go to the mounted file that is at `/mlflow/mlartifacts` and create a file manually, exit the container and see the file on the local system all without issue.  

### Code to reproduce issue

see Describe the problem above

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@zstern 

> OSError: [Errno 30] Read-only file system: '/mlflow'

Can you share the full stack trace?

**Comment by zstern** [comment]
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/var/folders/ph/bmdywq8d3gvcn2xps9_389bc0000gp/T/ipykernel_1952/282632136.py in <module>
      2                       experiment_id='1') as run:
      3 
----> 4                       mlflow.log_artifact(f'{path}/MLmodel', artifact_path=name)
      5                       mlflow.log_artifact(f'{path}/config.yml', artifact_path=name)
      6                       mlflow.log_artifact(f'{path}/conda.yaml', artifact_path=name)

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/tracking/fluent.py in log_artifact(local_path, artifact_path)
    750     """
    751     run_id = _get_or_start_run().info.run_id
--> 752     MlflowClient().log_artifact(run_id, local_path, artifact_path)
    753 
    754 

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/tracking/client.py in log_artifact(self, run_id, local_path, artifact_path)
    953             is_dir: False
    954         """
--> 955         self._tracking_client.log_artifact(run_id, local_path, artifact_path)
    956 
    957     def log_artifacts(

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py in log_artifact(self, run_id, local_path, artifact_path)
    363             artifact_repo.log_artifacts(local_path, path_name)
...
--> 225         mkdir(name, mode)
    226     except OSError:
    227         # Cannot rely on checking for EEXIST, since the operating system

OSError: [Errno 30] Read-only file system: '/mlflow'
```

**Comment by harupy** [comment]
Looks like it's truncated.

**Comment by zstern** [comment]
```
In [9]: import uuid
   ...: import mlflow
   ...: 
   ...: mlflow.set_experiment(uuid.uuid4().hex)
   ...: 
   ...: with mlflow.start_run(run_name=name):
   ...:     mlflow.get_artifact_uri()
   ...:     mlflow.log_artifact(f'{path}/MLmodel', artifact_path=name)
   ...:     mlflow.log_artifact(f'{path}/config.yml', artifact_path=name)
   ...:     mlflow.log_artifact(f'{path}/conda.yaml', artifact_path=name)
   ...:     mlflow.log_artifact(f'{path}/model_config.yaml', artifact_path=name)
   ...:     mlflow.log_artifact(f'{path}/processing.py', artifact_path=name)
   ...:     mlflow.onnx.log_model(model, artifact_path=name)
   ...: 
2022/07/19 17:21:30 INFO mlflow.tracking.fluent: Experiment with name '4d5783c7a3cc4b5d8ff0a5f1f47167dc' does not exist. Creating a new experiment.
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-e8b0295b52b8> in <module>
      6 with mlflow.start_run(run_name=name):
      7     mlflow.get_artifact_uri()
----> 8     mlflow.log_artifact(f'{path}/MLmodel', artifact_path=name)
      9     mlflow.log_artifact(f'{path}/config.yml', artifact_path=name)
     10     mlflow.log_artifact(f'{path}/conda.yaml', artifact_path=name)

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/tracking/fluent.py in log_artifact(local_path, artifact_path)
    750     """
    751     run_id = _get_or_start_run().info.run_id
--> 752     MlflowClient().log_artifact(run_id, local_path, artifact_path)
    753 
    754 

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/tracking/client.py in log_artifact(self, run_id, local_path, artifact_path)
    953             is_dir: False
    954         """
--> 955         self._tracking_client.log_artifact(run_id, local_path, artifact_path)
    956 
    957     def log_artifacts(

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py in log_artifact(self, run_id, local_path, artifact_path)
    363             artifact_repo.log_artifacts(local_path, path_name)
    364         else:
--> 365             artifact_repo.log_artifact(local_path, artifact_path)
    366 
    367     def log_artifacts(self, run_id, local_dir, artifact_path=None):

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/store/artifact/local_artifact_repo.py in log_artifact(self, local_file, artifact_path)
     35         )
     36         if not os.path.exists(artifact_dir):
---> 37             mkdir(artifact_dir)
     38         shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
     39 

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/utils/file_utils.py in mkdir(root, name)
    117     except OSError as e:
    118         if e.errno != errno.EEXIST or not os.path.isdir(target):
--> 119             raise e
    120     return target
    121 

~/opt/anaconda3/lib/python3.9/site-packages/mlflow/utils/file_utils.py in mkdir(root, name)
    114     target = os.path.join(root, name) if name is not None else root
    115     try:
--> 116         os.makedirs(target)
    117     except OSError as e:
    118         if e.errno != errno.EEXIST or not os.path.isdir(target):

~/opt/anaconda3/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    213     if head and tail and not path.exists(head):
    214         try:
--> 215             makedirs(head, exist_ok=exist_ok)
    216         except FileExistsError:
    217             # Defeats race condition when another thread created the path

~/opt/anaconda3/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    213     if head and tail and not path.exists(head):
    214         try:
--> 215             makedirs(head, exist_ok=exist_ok)
    216         except FileExistsError:
    217             # Defeats race condition when another thread created the path

~/opt/anaconda3/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    213     if head and tail and not path.exists(head):
    214         try:
--> 215             makedirs(head, exist_ok=exist_ok)
    216         except FileExistsError:
    217             # Defeats race condition when another thread created the path

~/opt/anaconda3/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    213     if head and tail and not path.exists(head):
    214         try:
--> 215             makedirs(head, exist_ok=exist_ok)
    216         except FileExistsError:
    217             # Defeats race condition when another thread created the path

~/opt/anaconda3/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    213     if head and tail and not path.exists(head):
    214         try:
--> 215             makedirs(head, exist_ok=exist_ok)
    216         except FileExistsError:
    217             # Defeats race condition when another thread created the path

~/opt/anaconda3/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    223             return
    224     try:
--> 225         mkdir(name, mode)
    226     except OSError:
    227         # Cannot rely on checking for EEXIST, since the operating system

OSError: [Errno 30] Read-only file system: '/mlflow'

I think this is the entire thread now. Thanks!

```

**Comment by harupy** [comment]
@zstern I think you're logging artifacts in the local file system, not in the container.

**Comment by harupy** [comment]
@zstern Where did you run this code?

```python
import uuid
import mlflow

model = onnx.load(f'{path}/model.onnx')
mlflow.set_experiment(uuid.uuid4().hex)

with mlflow.start_run(run_name=name):
    mlflow.get_artifact_uri()
    mlflow.log_artifact(f'{path}/MLmodel', artifact_path=name)
    mlflow.log_artifact(f'{path}/config.yml', artifact_path=name)
    mlflow.log_artifact(f'{path}/conda.yaml', artifact_path=name)
    mlflow.log_artifact(f'{path}/model_config.yaml', artifact_path=name)
    mlflow.log_artifact(f'{path}/processing.py', artifact_path=name)
    mlflow.onnx.log_model(model, artifact_path=name)

```

**Comment by harupy** [comment]
@zstern Any updates?

**Comment by harupy** [comment]
If you want to log artifacts in the tracking server, you need to run `mlflow server` with `--serve-artifacts and --artifacts-destination`. [This example](https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts) might help. Feel free to reopen the issue if you need further help.

**Comment by tk-drummer717** [comment]
Just a comment for those who have come here with the same problem.
I'm not sure if this problem is actually caused by mlflow or not, but removing the MLFLOW_DEFAULT_ARTIFACT_ROOT option created /mlartifacts and solved the problem.

[https://yijoon009.tistory.com/entry/Docker-mlflow-OSError-Errno-30-Read-only-file-system-mlflow#%ED%95%B4%EA%B2%B0%20%EB%B0%A9%EB%B2%95%203%20-%20mlartifacts%20%ED%8F%B4%EB%8D%94%20%EC%82%AC%EC%9A%A9-1 ](url)

This blog is helpful.

before: 
`mlflow ui --default-artifact-root /some/dir --host 0.0.0.0 --port 1234`

after: 
`mlflow ui --host 0.0.0.0 --port 1234`

I would also like to add that in my case the problem occurred during the generation of the experiment, so I had to delete the experiment from my browser before create new experiment to see if the problem was resolved.

The cause of the problem is unknown, but it is likely that it is not a problem that comes to everyone, as it occurred one day out of the blue.
Also, it is not a pure mlflow container, but a derived container with temporary psql.

https://hub.docker.com/r/imichael/mlflow

I've googled around and found that replacing the HDD will solve the problem, or a permissions issue in the host or container, or many other possibilities, but I'm surprised that the above method solved the problem.

I know it is difficult to reproduce and difficult to pinpoint the cause, but I am recording this in the hope that it will give some insight.

**Comment by fabianjkrueger** [comment]
I had the same issue and what @valleyriver717 posted here solved it for me. Thank you very much!

> Just a comment for those who have come here with the same problem. I'm not sure if this problem is actually caused by mlflow or not, but removing the MLFLOW_DEFAULT_ARTIFACT_ROOT option created /mlartifacts and solved the problem.
> 
> [https://yijoon009.tistory.com/entry/Docker-mlflow-OSError-Errno-30-Read-only-file-system-mlflow#%ED%95%B4%EA%B2%B0%20%EB%B0%A9%EB%B2%95%203%20-%20mlartifacts%20%ED%8F%B4%EB%8D%94%20%EC%82%AC%EC%9A%A9-1 ](url)
> 
> This blog is helpful.
> 
> before: `mlflow ui --default-artifact-root /some/dir --host 0.0.0.0 --port 1234`
> 
> after: `mlflow ui --host 0.0.0.0 --port 1234`
> 
> I would also like to add that in my case the problem occurred during the generation of the experiment, so I had to delete the experiment from my browser before create new experiment to see if the problem was resolved.
> 
> The cause of the problem is unknown, but it is likely that it is not a problem that comes to everyone, as it occurred one day out of the blue. Also, it is not a pure mlflow container, but a derived container with temporary psql.
> 
> https://hub.docker.com/r/imichael/mlflow
> 
> I've googled around and found that replacing the HDD will solve the problem, or a permissions issue in the host or container, or many other possibilities, but I'm surprised that the above method solved the problem.
> 
> I know it is difficult to reproduce and difficult to pinpoint the cause, but I am recording this in the hope that it will give some insight.
