### ISSUE TITLE
[DOC-FIX] Cannot run pytests due to missing dependencies in default development environment

### ISSUE THREAD

**Issue by jerrylian-db** [mlflow/mlflow#6275]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

CONTRIBUTING.rst

### Description of proposal (what needs changing)

I followed the `CONTRIBUTING.rst` and ran `dev/dev-env-setup.sh -d .venvs/mlflow-dev -q` in a fresh clone of the mlflow repo to create an virtual environment to develop within. However, when I ran `./dev/run-python-tests.sh` to run the tests, I got the error
```
ImportError while loading conftest '/Users/jerry.liang/mlflow/tests/conftest.py'.
tests/__init__.py:1: in <module>
    from mlflow.utils.logging_utils import _configure_mlflow_loggers
mlflow/__init__.py:32: in <module>
    import mlflow.tracking._model_registry.fluent
mlflow/tracking/__init__.py:8: in <module>
    from mlflow.tracking.client import MlflowClient
mlflow/tracking/client.py:13: in <module>
    import yaml
E   ModuleNotFoundError: No module named 'yaml'
```
After installing `pyyaml` and rerunning the command, I got the error `ModuleNotFoundError: No module named 'google'`. I'm assuming that the environment setup script doesn't install all the test requirements?

**Comment by jerrylian-db** [comment]
This was fixed after running
```
pip install -r requirements/dev-requirements.txt
pip install -e '.[extras]'
```

**Comment by harupy** [comment]
@jerrylian-db It should but looks like it actually doesn't:

https://github.com/mlflow/mlflow/blob/0c884e04cfde020b2d9464d18bb455df0ec5c61b/dev/dev-env-setup.sh#L223-L237

`pip install $(quiet_command) -e .[extras]` (which should install `pyyaml`) is only executed when `$full` is not empty.

**Comment by harupy** [comment]
@jerrylian-db Filed #6276
