### ISSUE TITLE
[FR] Proxy uploading of artifacts through the tracking service

### ISSUE THREAD

**Issue by harmw** [mlflow/mlflow#629]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. 

## Proposal Summary

As per request from @smurching I'm leaving it here as a topic for future discussion :)

Currently the `mlflow` workflow describes sending artifacts to a location specified by the tracking service. For example, the service will return an Amazon S3 location in which the client may place the artifacts. This, however, means the clients will have to know about S3 and must require access to the bucket - requiring specific IAM roles to be configured for client access, which may or may not be feasible.

Furthermore, when looking at it from a deployment pipeline (CI/CD) perspective I would expect my client to be considerably _dumb_ and simply end the model training, fitting etc. with something like `mlflow.deploy(supermodel)`. Which would kick-off a proper CI/CD process and essentially ship my model.

For a regular (?) models, this should be pretty straightforward as they range in the order of MBs, right. It'll probably get interesting with artifacts sizing several GBs, though scaling a (new/additional?) component of the tracking service could be a potential fix for that.

Anyway, I'm very interested about the general and MLflow-specific view on this topic and where it should or could go :)

**Comment by cpedrinaci** [comment]
I'd also find this feature quite appealing. While I understand that this adds an additional hop to data transfer and some additional complexity to the tracking server, often it may not be that easy or even viable to ensure that every client has access to the underlying artefacts store, e.g., S3.

Do you have any plans in this regard?

**Comment by vsandvold** [comment]
I request tracking server proxy uploads to S3, as well. Setting up MLflow server as a multi-tenant solution is difficult when credentials have to be shared between autonomous teams in our organization, each using the own AWS accounts. It seems awkward that clients must possess the same credentials as the server, and it goes against the flexibility provided by the MLflow client SDK.

Mounting S3 as a file system on the mlflow server with `s3fs` could solve the problem, but in a very roundabout way.

**Comment by dstine** [comment]
I also would like this feature, and +1-ed this issue above. Had a quick exchange on Slack with @acroz, who suggested I comment here.

My suggestion is to support two options.

**Option 1: direct client-to-repo artifact uploads (already supported)**
Pro: does not impose requirement for extra server compute resources
Con: requires additional configuration that at best must be managed for each client, at worst is not practical (as others have noted above)

**Option 2: proxied client-to-server-to-repo artifact uploads**
Pro: simpler client configuration
Con: requires additional server-side compute resources

I would suggest Option 2 as the default, because it is an easier getting-started experience. Which as a breaking change, should be done before 1.0.

Note that this feature might impact the [current proposal](https://gist.github.com/acroz/48a7b9455f1a054f6b14acf676d6df46) for changes to the artifact repo API. I have not studied the proposal and code base closely enough to be sure.

Would love to hear from the maintainers on this topic.
@smurching @aarondav @mparkhe

**Comment by enpinzolas** [comment]
I also support this change, it would simplify a lot storing into the tracking server.

Right now, if I want to store the artifacts in the local storage of the tracking server, I need to set up a sftp server (or ftp) and handle all the key management correctly.

**Comment by dakl** [comment]
Supporting both seems like a good way. Default should IMO be client to server to repo.

**Comment by MrSaints** [comment]
We've just started using MLflow, and the existing behaviour was slightly _[astonishing](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)_. Maybe I am missing the use-case for why it is the way it is, but it seems to make configuration on the server, and client more brittle

That said, I can understand if the client uploads directly to say S3. It saves unnecessary data transfer. And it is relatively achievable without the need of credentials on the client-side using presigned URLs (https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html). So this may be a potential option too for some cloud-based artifact storage.

**Comment by dstine** [comment]
I am not aware of any resolution to this issue.

**Comment by ArsTapatun** [comment]
Not having proxied uploads complicates things even more in case of a slightly more complex setup.

Let's say that you're deploying a service on AWS ECS/ECR and set up the necessary infra (S3 bucket and access policies) through Terraform scripts. The mlflow service is given access to the bucket, and the end user assumes that you just push stuff to the service and it will get sorted out on that end; 

But with the current implementation, you have to create your individual IAM role, log in to AWS with that role and change the terraform to give that role access to the bucket in addition to the service... Times the number of clients? Not a really sustainable approach as others have noted above.

**Comment by dstine** [comment]
Proposed documentation update to clarify current state of affairs: #2075

**Comment by MrSaints** [comment]
I don't speak for all data scientists, and ML engineers, but I feel it is worth resolving the _experience_ of how artifacts are stored.

At the moment, there are some implicit prerequisites, and synchronisation costs to have an artifact uploaded by an end-user, and read by another end-user on the MLflow UI (or even via the client SDK). It's esoterics, and internal guts that I feel data scientists, and ML engineers shouldn't really know or care about. It could be stored in Dropbox for all they care. Documentation alone won't really _fix this_ since it is an _experience_ problem.

**Comment by Serhiy-Shekhovtsov** [comment]
This feature would help a lot!

**Comment by smurching** [comment]
Thanks all for chiming in & apologies for the delay, would be happy to consider proposals on how we might achieve this - one initial idea would be to add an `http` (or similar) artifact URI scheme, mirroring the existing S3, GCS, `file://` local-filesystem artifact URI schemes, that provides a GET & POST-able endpoint for reading/writing artifacts. You could then start an MLflow server with e.g. `mlflow server --default-artifact-root=http://localhost:5000/artifacts`, experiments created under the server would inherit artifact URIs of the form `http://localhost:5000/artifacts/<experiment-id>/`, and the server could handle artifact uploads/downloads to the `/artifacts` endpoint.

We'd need to weigh the tradeoffs of adding this new endpoint (would it be part of the standard MLflow REST API or OSS-server only, with the aim of supporting proxying artifact uploads? if the former, there's added maintenance / engineering cost in that every implementor of the MLflow REST API would need to also support this artifact-upload-proxying functionality, which may not scale particularly well)

**Comment by mohammedi-haroune** [comment]
Hello, we're facing the exact same problem. The client code which is written by external users in our case should be able to access the S3 credentials which put us on a big vulnerability, users could created/delete anything from S3. 

Is there any plans to fix this ?

**Comment by pogil** [comment]
This is a case where we would really like some community help. If anyone is interested - I'd recommend starting with a proposed design. In addition to @smurching's suggestions, I think it would be good if the proxy support can be configured on/off, and have it be optional support for a service. Sid's proposal to add a new default artifact root with a new URI scheme would make this feasible. 

A design in this space should touch on managing threads for artifact writes and how other lighter weight calls won't get starved if some clients are writing large artifacts through the proxy.

**Comment by synchronizing** [comment]
Is there a reason why the `mlflow.set_artifact_uri()` (mentioned here https://github.com/mlflow/mlflow/issues/2671) function, and `MFLOW_ARTIFACT_URI` environmental variable is missing from the codebase? 

I have been quite lost regarding this. With the current codebase, are we have to have our data scientists manually push the local artifacts folder to our SFTP server? Documentation does not make this clear.

**Comment by swigicat** [comment]
Is there any update on this topic? I am trying to introduce MLFlow to our department but this issue makes it impossible to use the framework as intended for a shared project.

**Comment by nosound2** [comment]
This essential feature has not been resolved in two years really makes me question our organization decision to use MLFlow.

**Comment by synchronizing** [comment]
My assumption at this point is that the folks running the project (Databricks) do not want to support this because it's one of the "secret sauces" to their payed service. With direct upload support + an account management system their online version of MLFlow would become partially obsolete.

**Comment by hanan-vian** [comment]
any news on this? artifacts should be saved via the server not directly from the client. In some sense I want my users to NOT have access to the s3 bucket of artifacts. only the mlflow server should have direct access.

**Comment by dbczumar** [comment]
Hi folks, here's an RFC for proxying artifact operations through the MLflow server: https://docs.google.com/document/d/1fG3Ntf8oBryIYcYLhuw36vOsMiykvjFxlcFcNWmmN5A/edit?usp=sharing. Feedback would be appreciated. It would be great to get help from the community with the implementation as well, once an approach has been agreed upon.

**Comment by leviplj** [comment]
I've created a simple 3-4 steps solution that works with at least s3 when logging artifacts. The solution would use S3 pre-signed URLs to solve the auth problem on the client-side.
  - Create a dict following the structure {'local_file_path': 'desired_s3_key'}. I guess the names are self-explanatory. 
  - Send the dict to the server via POST. The server process the dict and for each `desired_s3_key` it generates a pre-signed URL and replace the s3 key with the URL.
  - The client receives a dict with the `local_file_path` and the pre-signed URL to push the files to s3.
  
Now the server must have `getObject` permission on the bucket. With the changes, we'd need to add a `putObject` so it can generate pre-signed URLs that can put objects on S3.

Bellow a fully-functional basic implementation of how the code would be.

```python
import os
import posixpath
import uuid

import boto3
import requests
from mlflow.utils.file_utils import relative_path_to_artifact_path


# This code would be on the server as an endpoint [/mlflow/s3/pre-signed-urls ??]
def HttpPostToServer(d):
    """
    d = {
        [ local path   ]: [ s3 path/key                                       ]
        './folder/3.txt': '0/-89803ca6c60648c49208af01ab2e15f6/artifacts/3.txt',
    }

    return
    {
        [ local path   ]: [ pre-signed url                   (0/-89803ca6c60648c49208af01ab2e15f6/artifacts/3.txt) < desired key ]
        './folder/3.txt': 'https://my-bucket.s3.amazonaws.com/0/-89803ca6c60648c49208af01ab2e15f6/artifacts/3.txt?AWSAccessKeyId=',
    }
    """
    client = boto3.client('s3')
    l=[]
    for local_path, desired_s3_key in d.items():
        r = client.generate_presigned_url('put_object', Params=dict(Bucket='mlflow-test-levi', Key=desired_s3_key), ExpiresIn=3600)
        l.append((local_path, r))

    return dict(l)



# Very simplified and not accurate version of S3 Artifact Repo
class S3ArtifactRepo:
    def _upload(self, new_d):
        """
        new_d = {
            [ local path   ]: [ pre-signed url                                                                                       ]
            './folder/3.txt': 'https://my-bucket.s3.amazonaws.com/0/-89803ca6c60648c49208af01ab2e15f6/artifacts/3.txt?AWSAccessKeyId=',
        }
        """
        for local_path, presigned_url in new_d.items():
            with open(local_path, 'rb') as file:
                print('putting', local_path)
                response = requests.put(presigned_url, data=file.read())
                print('Do Sth with response if needed', response)

    def _build_s3_paths(self, local_dir, run_id):
        """
        local_dir = './folder'

        return
        {
            [ local path   ]: [ s3 path/key              ]
            './folder/3.txt': '0/{run_id}/artifacts/3.txt',
        }
        """
        l=[]
        dest_path = posixpath.join('0', run_id)
        for (root, _, filenames) in os.walk(local_dir):
            upload_path = dest_path

            if root != local_dir:
                rel_path = os.path.relpath(root, local_dir)
                rel_path = relative_path_to_artifact_path(rel_path)
                upload_path = posixpath.join(dest_path, rel_path)

            for f in filenames:
                l.append((
                    posixpath.join(root, f), posixpath.join(upload_path, f)
                ))
        return dict(l)

    def log_artifacts(self, local_dir, run_id):
        s3_paths = self._build_s3_paths(local_dir, run_id)

        presigned_urls = HttpPostToServer(s3_paths)

        self._upload(presigned_urls)



S3ArtifactRepo().log_artifacts('./folder', '-' + uuid.uuid4().hex)

```

**Comment by leviplj** [comment]
Below a preview of what I believe to be the changes that impact the user experience directly. At first, it would be just the addition of the env var `MLFLOW_ENABLE_S3_PRESIGNED_URL`, enabling the user to send files to s3 without the need to be authorized at AWS.

https://github.com/mlflow/mlflow/blob/a776b54fa8e1beeca6a984864c6375e9ed38f8c0/mlflow/store/artifact/s3_artifact_repo.py#L11-L13

```python
from mlflow.utils.file_utils import relative_path_to_artifact_path

USE_PRESIGNED_URL_ENV_VAR = "MLFLOW_ENABLE_S3_PRESIGNED_URL"
```

https://github.com/mlflow/mlflow/blob/a776b54fa8e1beeca6a984864c6375e9ed38f8c0/mlflow/store/artifact/s3_artifact_repo.py#L159-L161

```python
                listed_object_path=file_path, artifact_path=dest_path
            )
            s3_client.delete_object(Bucket=bucket, Key=file_path)

class S3ArtifactRepositoryV2(S3ArtifactRepository):
    def _build_s3_paths(self, local_dir, artifact_path=None):
        (bucket, dest_path) = data.parse_s3_uri(self.artifact_uri)
        if artifact_path:
            dest_path = posixpath.join(dest_path, artifact_path)

        local_dir = os.path.abspath(local_dir)
        paths = []
        for (root, _, filenames) in os.walk(local_dir):
            upload_path = dest_path
            if root != local_dir:
                rel_path = os.path.relpath(root, local_dir)
                rel_path = relative_path_to_artifact_path(rel_path)
                upload_path = posixpath.join(dest_path, rel_path)
            for f in filenames:
                paths.append(
                    (posixpath.join(root, f), posixpath.join(upload_path, f))
                )

        return dict(paths)

    def _upload(self, new_d):
        """
        new_d = {
            [ local path   ]: [ pre-signed url                                                                                       ]
            './folder/3.txt': 'https://my-bucket.s3.amazonaws.com/0/-89803ca6c60648c49208af01ab2e15f6/artifacts/3.txt?AWSAccessKeyId=',
        }
        """
        for local_path, presigned_url in new_d.items():
            with open(local_path, 'rb') as file:
                print('putting', local_path)
                response = requests.put(presigned_url, data=file.read())
                print('Do Sth with response if needed', response)

    def log_artifacts(self, local_dir, artifact_path=None):
        s3_paths = self._build_s3_paths(local_dir, artifact_path)

        server_url = get_tracking_uri() + '/ajax-api/2.0/preview/mlflow/s3/get-presigned-urls'

        response = requests.post(server_url, s3_paths)

        self._upload(response.json())

def s3_artifact_repo_factory(artifact_uri):
    if os.environ.get(USE_PRESIGNED_URL_ENV_VAR, "").lower() != "false":
        return S3ArtifactRepositoryV2(artifact_uri)
    else:
        return S3ArtifactRepository(artifact_uri)
```

https://github.com/mlflow/mlflow/blob/a776b54fa8e1beeca6a984864c6375e9ed38f8c0/mlflow/store/artifact/artifact_repository_registry.py#L12-L14

```python
from mlflow.store.artifact.runs_artifact_repo import RunsArtifactRepository
from mlflow.store.artifact.s3_artifact_repo import s3_artifact_repo_factory
from mlflow.store.artifact.sftp_artifact_repo import SFTPArtifactRepository
```

**Comment by Klintrup** [comment]
I agree with @leviplj that S3 Presigned URL's would be the best solution for this issue (at least on AWS S3). This would remove the reliance on client systems to authenticate against AWS while still keeping mlflow lightweight and security in place.

**Comment by leviplj** [comment]
No interest in solving this problem???

**Comment by miro-mlynarik** [comment]
@pogil Can you please check the solution, @leviplj proposed?

**Comment by yuvrajz** [comment]
@leviplj 
Can you help and explain more on 
server_url = get_tracking_uri() + '/ajax-api/2.0/preview/mlflow/s3/get-presigned-urls'
I have tried setting mine tracking uri instead but i am not able to get repose from tracking url in that case also what is added after tracking uri ajax call? How to prepare that urls.??in my case 
response = requests.post(server_url, s3_paths) gives 404 and other exceptions if i replace tracking url

**Comment by leviplj** [comment]
@yuvrajz
That URL doesn't exist.
We'd have to implement it according to the function `HttpPostToServer` on [my first comment](https://github.com/mlflow/mlflow/issues/629#issuecomment-845822550).

That function implements the logic on how to get the s3 pre-signed URLs.

**Comment by dbczumar** [comment]
Hi @leviplj, thank you for the proposal for a more efficient and lightweight artifact upload paradigm based on S3 presigned URLs. I think this is a good idea for S3 artifact storage use cases, which are quite common. Here are a couple thoughts:

1. Admins of the MLflow server will need to supply credentials / configuration to use for presigned URL generation. We should only expose the endpoint for generation (e.g. `/api/2.0/mlflow/s3/get-presigned-urls`) if these credentials / confs are supplied. Can you propose / clarify how admins should tell the `mlflow server` CLI  that the endpoint should be exposed (e.g. via commandline argument) and how credentials should be supplied (e.g. via the standard AWS credential provider chain used by `boto3`)?

2. Using an environment variable to control whether or not clients request presigned URLs seems like it may complicate workflows - e.g. users are required to make sure this environment variable is set in all processes that attempt to log artifacts. It may also be failure prone - e.g. what happens if the MLflow server doesn't expose the required endpoint but the client is configured to try to use presigned URLs? Perhaps we could try to query the endpoint unconditionally and fall back to local creds if the endpoint isn't available; for users who want to save the extra network request, we could provide an opt-out environment variable.

3. Could we support GCP / Azure signed URLs as well via a more generic endpoint such as `/api/2.0/mflow/artifacts/get-presigned-url`? It's fine if we begin with an S3-only implementation, and there's an extensibility benefit to using a more generic name.

Let me know what you think!

**Comment by leviplj** [comment]
@dbczumar 
1. When the user configures the artifact repo to be an s3 bucket the admin already has to configure AWS credentials. The best way would be configuring the CLI (standard way), which also configures any SDK (boto3 in this case) that AWS provides.
I think the URL should be always exposed. If the server has the necessary permissions it generates the pre-signed URLs 
otherwise, it returns an error.

2. I believe env vars are the best way to enable/disable this behaviour. If it is a one-time thing you set it on the terminal and if it is permanent you set it on the SO config.
If the user wants to use pre-signed URLs they have to consciously set MLFlow to do so.

3. Azure has [Shared Access Signature (SAS)](https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature) and GCP has [Signed URLs](https://cloud.google.com/storage/docs/access-control/signed-urls). I'm not familiar with their implementation but it might be similar.
Not sure if we should have a generic endpoint as the server doesn't know where is the artifact repo located (AWS, Azure or GCP), so it can't really identify which service generate the URLs. If we add a generic endpoint, we'd have to either send the id of the artifact so the server can get what is the storage type or send the type in the body message. I'd still prefer to have different endpoints as each provider have a different name to their "pre-signed URLs".

**Comment by yuvrajz** [comment]
@leviplj 
How the client will download the artifacts, if S3 credentials are not provided to client.
method like download_artifacts(run_id: str, path: str, dst_path: Optional[str] = None) internally call auth.py in botocore lib
I think S3 credentials are still required for it.

**Comment by leviplj** [comment]
@yuvrajz 
Pre-signed URLs can be used to either upload or download files.

**Comment by dbczumar** [comment]
Hi folks, in MLflow 1.23.0, we released the highly-requested capability to stream artifacts through the MLflow server. This is now documented here: https://mlflow.org/docs/latest/tracking.html#using-the-tracking-server-exclusively-for-proxied-artifact-access. Accordingly, I'm going to go ahead and close this issue now that the requested feature has been implemented. Please let me know if there are any questions or concerns.

**Comment by leviplj** [comment]
@dbczumar How does this work? I've tried to setup a small server to test it but with no success.

server start:
```bash
mlflow server --host 0.0.0.0 \
  --port 8001 \
  --serve-artifacts \
  --artifacts-only \
  --backend-store-uri postgresql://user:pass@localhost:5432/mlflow \
  --artifacts-destination s3://mlflow-test
```

python code:
```python title=main.py
import os

from mlflow import log_artifacts

if __name__ == "__main__":
    if not os.path.exists("outputs"):
        os.makedirs("outputs")

    with open("outputs/test.txt", "w") as f:
        f.write("hello world")

    log_artifacts("outputs")
```

code call:
```bash
export MLFLOW_TRACKING_URI=http://localhost:8001
python main.py
```

I'm getting this error:
```
...
mlflow.exceptions.MlflowException: API request to http://localhost:8001/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by ResponseError('too many 503 error responses'))
```

If I remove `--artifacts-only`, I get the following error:
```bash
...
  File "/home/workspace/mlflow/.venv/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 43, in _cached_get_s3_client
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

**Comment by antoinevokleber** [comment]
Hi all, i use MLflow 1.24.0 and i  have tested the server with proxied artifact access on blob azure.  When MLflow client, i don't send artifact without added information to access blob azure. I have tried different options on server mlflow (--serve-artifact, --default-artifact-root, --artifacts-destination wasbs://...). when i added AZURE_STORAGE_ACCESS_KEY and AZURE_STORAGE_CONNECTION_STRING variable environment on my client, it's work. for me, the proxy process does not work.

**Comment by jhadjar** [comment]
@mohammedi-haroune Does the previous mention by @Toumash affect automatic experiment tracking (detecting models, metrics, parameters, and saving to S3) for notebooks on iko.ai?

**Comment by mohammedi-haroune** [comment]
> @mohammedi-haroune Does the previous mention by @Toumash affect automatic experiment tracking (detecting models, metrics, parameters, and saving to S3) for long-running background notebooks on [iko.ai](https://iko.ai)?

No effect on [iko.ai](https://iko.ai).
