### ISSUE TITLE
Native handling of gunicorn options

### ISSUE THREAD

**Issue by mparkhe** [mlflow/mlflow#630]
PR #626 adds an ability for users of `mlflow server` and `mlflow ui` to pipe in custom `gunicorn` command line options. However, they may override some of the default options.

This is a stand in task to redesign customization of server initiation

ref: https://github.com/mlflow/mlflow/pull/626#discussion_r224923960

**Comment by jmrr** [comment]
Can I give this issue a try? I also liked your suggestion of [integrating gunicorn](http://docs.gunicorn.org/en/latest/custom.html) vs subprocessing.

**Comment by mparkhe** [comment]
Hi @jmrr:

Thank you for your interesting. Please feel free to give this a shot. I am happy to help out if you have any question. One of my colleagues @dbczumar had this idea. I am sure he would like to be in the loop as well.

Thanks,
mani

**Comment by jmrr** [comment]
Thanks @mparkhe been quite busy these past two weeks. I'll give it a shot this weekend.

**Comment by jmrr** [comment]
Hi guys, I have a very early draft of the solution in my [fork](https://github.com/jmrr/mlflow/commit/4873a259a3d74f21e17baf6f941e7462bed9c711), but hit a hurdle with the current `gunicorn_opts`. I think it was meant to be used by passing `click` CLI something like `--gunicorn-opts "--reload --keyfile mykey"` and then `shlex` would do the string splitting.

However this would be tricky if we go for full native integration without doing something like `gunicorn` does in its CLI as [this integration](http://docs.gunicorn.org/en/latest/custom.html) requires a dictionary with the options. I see some alternatives, like taking some of the parsing of `gunicorn`, passing a serialized dictionary in the CLI or suggesting the user to use a `gunicorn` config file. 

Shall I create a WIP PR so we can discuss there?

Thanks!
