### ISSUE TITLE
[BUG] Metric plot is very slow when X = Time (Relative)

### ISSUE THREAD

**Issue by hatimbr** [mlflow/mlflow#6332]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow, version 1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.4 LTS and Red Hat Enterprise Linux release 8.4 (Ootpa)

### Describe the problem

When I try to visualize a loss curve of a training (at least 8000 steps), it’s way slower to load it when X is Time (Relative) than Step or Time (Wall). Every tweaks that I want to apply to the curves (like change the smoothness for example) is also slower when X = Time (Relative). The biggest problem is that when I load a loss metric it’s by default with Time (Relative) as X, so whenever I want to check a curve it’s very slow. Is it normal that it's that slow ? And if yes, can we at least change the default configuration ?
I use the database configuration btw, but it was slower with a file configuration.

### Steps to reproduce the bug

Check any metric curve with at least 8000 steps

**Comment by harupy** [comment]
@hatimbr cc @dbczumar 

I'm looking at the relevant code.

https://github.com/mlflow/mlflow/blob/086c4114acb73cd2c4981cc62b7b5e464d258460/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js#L95-L100

When X is Time (Relative/Wall), we apply `MetricsPlotView.parseTimestamp` to each point.

https://github.com/mlflow/mlflow/blob/086c4114acb73cd2c4981cc62b7b5e464d258460/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js#L68-L74

**Comment by harupy** [comment]
I pulled out `const minTimestamp = _.minBy(history, 'timestamp').timestamp;` from `parseTimestamp` as shown below

```diff
diff --git a/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js b/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js
index 7002984bb..e325e7b2e 100644
--- a/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js
+++ b/mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js
@@ -65,9 +65,8 @@ export class MetricsPlotView extends React.Component {
     return legend;
   };
 
-  static parseTimestamp = (timestamp, history, xAxis) => {
+  static parseTimestamp = (timestamp, minTimestamp, xAxis) => {
     if (xAxis === X_AXIS_RELATIVE) {
-      const minTimestamp = _.minBy(history, 'timestamp').timestamp;
       return (timestamp - minTimestamp) / 1000;
     }
     return Utils.formatTimestamp(timestamp);
@@ -90,13 +89,14 @@ export class MetricsPlotView extends React.Component {
       const visible = !deselectedCurvesSet.has(Utils.getCurveKey(runUuid, metricKey))
         ? true
         : 'legendonly';
+      const minTimestamp = _.minBy(history, 'timestamp').timestamp;
       return {
         name: MetricsPlotView.getLineLegend(metricKey, runDisplayName, isComparing),
         x: history.map((entry) => {
           if (xAxis === X_AXIS_STEP) {
             return entry.step;
           }
-          return MetricsPlotView.parseTimestamp(entry.timestamp, history, xAxis);
+          return MetricsPlotView.parseTimestamp(entry.timestamp, minTimestamp, xAxis);
         }),
         y: isSingleHistory ? historyValues : EMA(historyValues, lineSmoothness),
         text: historyValues.map((value) => (isNaN(value) ? value : value.toFixed(5))),
```

and compared the performance (with 10000 steps):

### Before:

https://user-images.githubusercontent.com/17039389/181196760-acf7edcb-fff9-4f26-b6cc-0fd1eb411eeb.mov

### After:

https://user-images.githubusercontent.com/17039389/181195853-de761765-8ea3-4f51-bcd7-54ab89d86c7d.mov


Code to generate test data

```python
import mlflow
import random
from tqdm import tqdm


mlflow.set_registry_uri("sqlite:///mlflow.db")

with mlflow.start_run():
    for step in tqdm(range(10_000)):
        mlflow.log_metrics({"m": random.random()}, step=step)
```

**Comment by hatimbr** [comment]
It looks great, thank you !!

**Comment by harupy** [comment]
@hatimbr I filed #6341. The next version (1.28.0) will include this patch :)
