### ISSUE TITLE
[BUG] Logging params with an empty string as value gives INVALID_PARAMETER_VALUE

### ISSUE THREAD

**Issue by Davidswinkels** [mlflow/mlflow#6384]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows
- **Python version**:
Python 3.8
- **yarn version, if running the dev UI**:

### Describe the problem
**Expected behavior**
mlflow.log_params() can log empty strings.

**Actual behavior** 
mlflow.log_params() cannot log empty strings and raises error code:
b'{"error_code": "INVALID_PARAMETER_VALUE", "message": "Invalid value [{\'key\': \'hi\', \'value\': \'\'}] for parameter \'params\' supplied. Hint: Value was of type \'list\'. See the API docs for more information about request parameters."}'

### Code to reproduce issue

```python
import mlflow
mlflow_tracking_uri="http://localhost:5000"
mlflow.set_tracking_uri(mlflow_tracking_uri)
mlflow.set_experiment(experiment_name="1")
with mlflow.start_run(run_name="1"):
  mlflow.log_params({"hi": ""})
```

### Stack trace

```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\mlflow\tracking\fluent.py", line 675, in log_params
    MlflowClient().log_batch(run_id=run_id, metrics=[], params=params_arr, tags=[])
  File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\mlflow\tracking\client.py", line 918, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\mlflow\tracking\_tracking_service\client.py", line 315, in log_batch
    self.store.log_batch(
  File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\mlflow\store\tracking\rest_store.py", line 309, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\mlflow\utils\rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\mlflow\utils\rest_utils.py", line 185, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Invalid value [{'key': 'hi', 'value': ''}] for parameter 'params' supplied. Hint: Value was of type 'list'. See the API docs for more information about request parameters.
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @Davidswinkels. This has been fixed via https://github.com/mlflow/mlflow/pull/6179, which has been merged into the master branch of MLflow. You can install it via `pip install git+https://github.com/mlflow/mlflow`. This fix will be included in the MLflow 1.28.0 release, which we hope to provide within the next 2 weeks. Apologies for the regression here, and thank you for using MLflow!
