### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by slavakurilyak** [mlflow/mlflow#639]
# Goals

As an artificial intelligence developer, I want to use MLflow in my reinforcement learning (RL) models, so that I can freely experiment with wild ideas, also known as speculative research.

# Consider

- Consider using Google's [Dopamine](https://github.com/google/dopamine), a research framework for fast prototyping of reinforcement learning algorithms.

# Inspiration

## Google's Dopamine

Most existing RL frameworks do not provide the combination of flexibility and stability that enables researchers to iterate on RL methods effectively, and thus explore new research directions that may not have immediately obvious benefits. Further, reproducing the results from existing frameworks is often too time consuming, which can lead to scientific reproducibility issues down the line. ([Google, 2018](https://ai.googleblog.com/2018/08/introducing-new-framework-for-flexible.html))

Reproducing results is one of the strengths of MLflow.

## DeepMind's AlphaGo Zero

In order to understand the potential of reinforcement learning, it is important to look at the AlphaGo Zero case study.

AlphaGo Zero is the strongest Go player in the world. It outperformed all previous versions of AlphaGo. It defeated the version of AlphaGo that won against the world champion Lee Sedol by 100 games to 0.

What was the difference between AlphaGo and AlphaGo Zero? AlphaGo was trained by supervised learning from human expert moves, and by reinforcement learning from self-play. AlphaGo Zero was trained solely on reinforcement learning, without human data.

If you want to learn more about AlphaGo Zero, [watch this video](https://www.youtube.com/watch?v=tXlM99xPQC8) (2 min).

Feeling inspired yet? Great! Start coding.

**Comment by ankitmathur-db** [comment]
What is the feature request specific to Dopamine here? Please feel free to re-open with a specific request
