### ISSUE TITLE
[FR] Specify artifact_location when running ml

### ISSUE THREAD

**Issue by nfarley-soaren** [mlflow/mlflow#6394]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

I am currently using S3 for remote artifact logging and would like to be able to specify the name of the artifact location when running an mlflow project.  Right now the location defaults the a directory named by the experiment_id.  Outside of an mlflow project it's easy to do this when creating an experiment by specifying the artifact_location argument in `mlflow.create_experiment()`.  I propose adding an artifact_location argument when calling `mlflow run <path>` (CLI) or `mlflow.projects.run()` (SDK).

### Motivation

> #### What is the use case for this feature?
Being able to specify a meaningful name for artifact storage
> #### Why is this use case valuable to support for MLflow users in general?
Easier to match experiments with corresponding artifacts
> #### Why is this use case valuable to support for your project(s) or organization?
Easier to match experiments with corresponding artifacts
> #### Why is it currently difficult to achieve this use case?
I haven't found any other way to do this.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @nfarley-soaren, thank you for raising this feature request. Currently, we recommend passing the `experiment_id` or `experiment_name` argument to `mlflow.run()` in order to specify the Experiment to which to log MLflow Project Runs. The Experiment determines the artifact location. To use a different artifact location, create a new experiment and specify the `artifact_location` parameter to `mlflow.create_experiment()`, as you stated; then, call `mlflow.run()` and pass in the ID or name of the experiment. Thank you for using MLflow!
