### ISSUE TITLE
[FR] Add APIs for loading text, JSON, and images to mlflow.artifacts

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#6428]
### Willingness to contribute

No. I cannot contribute this feature at this time.

## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Feature scope

This roadmap feature’s complexity is classified as:

- [X] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

Introduce the following APIs to MLflow:

1. `mlflow.artifacts.load_text()`: Takes a URI referring to a text file as a parameter, downloads the file, and loads the file's contents as a string that is returned to the caller.

2. `mlflow.artifacts.load_json()`: Takes a URI referring to a JSON file as a parameter, downloads the file, and loads the file's contents as a dictionary that is returned to the caller via JSON parsing, throwing if the file cannot be parsed as JSON.

3. `mlflow.artifacts.load_image()`: Takes a URI referring to an image file as a parameter, downloads the file, and loads the file's contents as an image using Pillow's `Image.load()` function (https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.load), throwing if the file cannot be loaded as an image. The Pillow image object should be returned to the caller; if the function is called in a Jupyter notebook environment, it should also be displayed automatically.

### Motivation

> #### What is the use case for this feature?

Provide users a way to easily load common MLflow artifacts as Python objects.

> #### Why is this use case valuable to support for MLflow users in general?

Many users log text, JSON, and images, and they need to load them later for further analysis / processing.

> #### Why is it currently difficult to achieve this use case?

MLflow's `mlflow.artifacts.download_artifacts()` API (https://mlflow.org/docs/latest/python_api/mlflow.artifacts.html#mlflow.artifacts.download_artifacts) only downloads file contents to disk; it is up to users to parse them.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by subramaniam02** [comment]
@dbczumar I would like to work on this :) Please assign it to me.

**Comment by dbczumar** [comment]
@subramaniam02 Fantastic! I've assigned this to you. Looking forward to your pull request! Let me know if you have any questions.
