### ISSUE TITLE
UI showing "Oops! Something went wrong." because of PROXY

### ISSUE THREAD

**Issue by vshlpunjabi** [mlflow/mlflow#643]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **MLflow installed from (source or binary)**: Binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.7.0
- **Python version**: Python 2.7.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

I have a nginx proxy server that redirects to the container that has mlflow installed and running server on port 5000. So for eg. https://server-ip:port/ml-flow-server/

This is the redirect that points to my container that runs mlflow on port 5000.

I am running mlflow on the container like this. mlflow folder is present
mlflow server --file-store /mlflow --host 0.0.0.0

Do i need to change or do in order to make it work. i read about setting some tracking URI variable but i am not clear what should i set it too. I tried to export MLFLOW_TRACKING_URI=https://server-ip:port/ml-flow-server but it dint work.

Please help

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by GBPeters** [comment]
Has anyone found a solution to this issue yet? I'm trying to the same (redirect to mlflow from an nginx location), and I get the same issue. I ran gunicorn with debug logging on, and got this output:

```[30204] [DEBUG] GET /
[30204] [DEBUG] GET /static-files/fontawesome/css/fontawesome-all.min.css
[30204] [DEBUG] GET /static-files/static/js/main.bd2390e6.js
[30201] [DEBUG] GET /static-files/static/css/main.f6127f30.css
[30204] [DEBUG] GET /static-files/static/media/home-logo.7a9dd62d.png
[30204] [DEBUG] GET /static-files/static/media/niagara.dc8f4b7e.jpg
[30204] [DEBUG] GET /static-files/favicon.ico```

For readability I left out the timestamps. Ubuntu 16.04, Python 3.7,  MLflow 0.9.0 installed from pip in it's own Conda environment.
