### ISSUE TITLE
[FR] Format CSV output as a table in ArtifactViewer

### ISSUE THREAD

**Issue by nnethery** [mlflow/mlflow#6439]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

If a logged artifact is a CSV file, we try parsing the file and laying out a slice of the data in an embedded table in the artifact viewer.

### Motivation

> #### What is the use case for this feature?
To have a more aesthetically pleasing experience viewing tabular data in MLflow

> #### Why is this use case valuable to support for MLflow users in general?
As users rely more on the artifact viewer as a part of their mlops experience, this could create less time switching to another app to show a slice of training data or testing results.

> #### Why is this use case valuable to support for your project(s) or organization?
We don't shy away from showing our business partners our experiment runs. Being able to preview CSV files (especially training data) would be a big help when we present our work.

> #### Why is it currently difficult to achieve this use case?
* You would need to utilize a CSV parser dependency to be able to lay out the data preview

### Details

* If a CSV file cannot be parsed, fallback to the plaintext preview of the file with a banner saying it was unable to be parsed
* To limit performance issues in the browser, maybe we limit the CSV preview to the first `N` rows
* We can reuse the CSS in the experiments table in the experiments page
* Utilize an alternating cell background color to ease the eyes
* Important that we don't turn this feature into a tabular data viewer and gently encourage the user to download their CSV file to view in their spreadsheet editor of choice by:
1. Not allowing a sort feature on the column header, and 
2. Not allowing the user to re-order columns

See below for current way CSVs are visualized in MLflow
<img width="1678" alt="Screen Shot 2022-08-10 at 8 02 30 PM" src="https://user-images.githubusercontent.com/11582381/184044064-b085e14d-7f00-41e8-88c0-ecd28785e466.png">

See below on implementations from similar tools

Snowflake

![snowflake_table_example](https://user-images.githubusercontent.com/11582381/184043905-273180fd-88c1-4328-ae68-862a3a360efb.jpeg)

Dataiku

![dataiku_table_example](https://user-images.githubusercontent.com/11582381/184044056-6c1addfc-e213-4367-8ce0-6f6c54c412fe.png)

GitHub

![github](https://user-images.githubusercontent.com/17039389/185298152-143b2987-85cd-4a43-93d6-844015b0cf69.png)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@nnethery This is a great idea! Feel free to file a pull request whenever it's convenient; we're looking forward to your contribution!

cc @xanderwebs @sunishsheth2009
