### ISSUE TITLE
[DOC-FIX] Document MLflow experiment delete semantics

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#6444]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.delete_experiment
https://mlflow.org/docs/latest/rest-api.html#delete-experiment

### Description of proposal (what needs changing)

Apparently when you delete an experiment it is not permanently deleted from the database. Instead it is "tombstoned" and marked as "deleted" in the "lifecycle_stage" column. When you try to create a new experiment with the same name you get the following error: 
`mlflow.exceptions.MlflowException: Cannot set a deleted experiment 'sklearn_iris' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.`

There is no documentation on how to "permanently delete" the experiment.  If you have permissions to the underlying database you have to do the following hack for every run of the experiment before you can delete the experiment permanently:
```
delete from latest_metrics where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from metrics where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from params where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from tags where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from runs where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;

delete from experiments where name = 'my_experiment' ;
```
Note, that this issue does not pertain to Databricks MLflow where apparently you can recreate a deleted experiment.

**Comment by dbczumar** [comment]
@ninabacc-db Can we add some information to the MLflow docs indicating that deleting an experiment does not permanently delete it; rather, the experiment is soft-deleted?

**Comment by dbczumar** [comment]
Awesome! Thanks @ninabacc-db! We'll track this using the Databricks Docs tickets. I've also filed https://github.com/mlflow/mlflow/issues/6617 to track introducing a mechanism for permanently removing deleted experiments.
