### ISSUE TITLE
[BUG] Implement permanent delete of experiment

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#6445]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OSS MLflow**:
- **Python version: python >- 3.7.6**:

### Problem

When you delete an experiment in OSS MLflow you cannot then recreate the experiment.  Instead it is "tombstoned" and marked as "deleted" in the "lifecycle_stage" column in the underlying database. The error message is:
```
mlflow.exceptions.MlflowException: Cannot set a deleted experiment 'sklearn_iris' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.
```
There is no API method to "permanently delete" the experiment per error message.

Related issue: Document MLflow experiment delete semantics](https://github.com/mlflow/mlflow/issues/6444#top)

Note that this is for OSS MLflow and not Databricks MLflow. The latter does allow you to recreate a deleted experiment.

The semantics for deleting an experiment should be consistent with those of deleting a registered model where there is no tombstone semantics.

Database tombstone example:
```
select * from experiments;
+---------------+--------------+-----------------------------------+-----------------+
| experiment_id | name         | artifact_locatio                  | lifecycle_stage |
+---------------+--------------+-----------------------------------+-----------------+
|             0 | Default      | file://opt/mlflow_server/mlruns/0 | active          |
|             1 | sklearn_iris | file://opt/mlflow_server/mlruns/1 | deleted         |
+---------------+--------------+-----------------------------------+-----------------+
```

### Solution

Add an option to `Mlflow.delete_experiments()` to permanently delete the experiment. Since there is no "ON DELETE CASCADE" clause on the `experiments` table,  you would need to do the following in the underlying database:
```
delete from latest_metrics where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from metrics where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from params where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from tags where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;
delete from runs where run_uuid = 'e30e657d4fa14807a8c1dae9ef66f2d6' ;

delete from experiments where name = 'my_experiment' ;
```

### Tracking information

client.delete_experiment(experiment_id)
mlflow.create_experiment(experiment_name)

### Code to reproduce issue

client.delete_experiment(experiment_id)
mlflow.create_experiment(experiment_name)

### Stack trace

mlflow.exceptions.MlflowException: Cannot set a deleted experiment 'sklearn_iris' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@amesar Can you convert this to a feature request?

**Comment by amesar** [comment]
@dbczumar 
I have converted the issue to FR. Why is this been marked as "closed this as completed"? If I delete experiment "foo", I currently cannot create a new experiment "foo".

**Comment by anencore94** [comment]
Is this feature is available in the latest version?
