### ISSUE TITLE
[FR] Implement `last_update_time` and `creation_time` for experiments

### ISSUE THREAD

**Issue by Andrew-Crosby** [mlflow/mlflow#6462]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Documentation for mlflow experiments returned via the REST API refers to `last_update_time` and `creation_time` fields https://www.mlflow.org/docs/latest/rest-api.html#mlflowexperiment, but these values are never returned in the response.

Under the hood, these fields appear to be missing from the [experiment entity](https://github.com/mlflow/mlflow/blob/master/mlflow/entities/experiment.py) and are only defined in the [protobuf message](https://github.com/mlflow/mlflow/blob/174c81f14364425f00fb9deca789fa5435446c0f/mlflow/protos/service.proto#L668-L672).

Would it be possible to implement these fields as the documentation suggests?

### Motivation

> #### What is the use case for this feature?
* Parity between docs and implementation - the docs already imply the existence of this functionality

> #### Why is this use case valuable to support for MLflow users in general?
* They won't be misled by the docs

> #### Why is this use case valuable to support for your project(s) or organization?
* We are attempting to export mlflow experiment/run data via KafkaConnect into a separate system with more powerful visualization functionality. The lack of `last_update_time` means that you can't easily detect which experiments have been updated since the last run.

> #### Why is it currently difficult to achieve this use case?
* No timestamp fields on experiment entities

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Andrew-Crosby Thanks for the FR! Adding `last_update_time` and `creation_time` makes sense and can enhance experiment search. I added the help-wanted label to ask for help from the community.

**Comment by subramaniam02** [comment]
@harupy Willing to contribute :) Thanks !

**Comment by Andrew-Crosby** [comment]
Thanks for implementing this so quickly 👍
