### ISSUE TITLE
[SETUP-BUG] ValueError: Anonymous credentials cannot be refreshed

### ISSUE THREAD

**Issue by shahasim** [mlflow/mlflow#6471]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux version 5.15.58-flatcar (build@pony-truck.infra.kinvolk.io) (x86_64-cros-linux-gnu-gcc (Gentoo Hardened 10.3.0-r2 p3) 10.3.0
- **MLflow installed from (source or binary)**: source, installed using `pip install mlflow[extras]==1.27.0` in docker container
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.27.0
- **Python version**: python3.8, using base docker image `from python:3.8.2-slim`

### Code to reproduce issue

**Docker File** 
```
FROM python:3.8.2-slim

ENV MLFLOW_HOME /app/mlflow
ENV SERVER_PORT 5000
ENV SERVER_HOST 0.0.0.0
ENV ARTIFACT_STORE /mnt/mlflow
ENV BACKEND_STORE mysql+pymysql://mluser:<your_password>@<ip>:30036/mlflow
ENV GOOGLE_APPLICATION_CREDENTIALS /secrets/service-account.json

RUN pip install --upgrade pip && \ 
    pip install PyMySQL==1.0.2 && \   
    pip install psycopg2-binary==2.9.3 && \
    pip install google-cloud-storage==2.4.0 && \
    pip install mlflow[extras]==1.27.0

RUN apt-get update; apt-get --assume-yes install curl

RUN curl https://sdk.cloud.google.com > install.sh
RUN bash install.sh --disable-prompts --install-dir=/workdir/

ENV PATH=/workdir/google-cloud-sdk/bin:$PATH

EXPOSE ${SERVER_PORT}

ENTRYPOINT ["mlflow", "server"]
```

**kubernetes command:**
`mlflow  server --host=0.0.0.0 --backend-store-uri=$(BACKEND_STORE) --artifacts-destination=$(ARTIFACT_STORE) --default-artifact-root=$(ARTIFACT_STORE) --serve-artifacts` 

**Envs**
```
          - name: ARTIFACT_STORE
            value: "gs://bucket-name/mlflow"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secrets/service-account.json"
```

**code** 

```
mlflow.set_tracking_uri("https://mlflowserver.system/")
mlflow.set_experiment("test")

with mlflow.start_run() as run:
    mlflow.log_params(params)
    model_info = mlflow.catboost.log_model(model, artifact_path="model")
    mlflow.log_artifact("../data/features.txt", artifact_path="features")
    model_uri = mlflow.get_artifact_uri("model")
    result = mlflow.evaluate(
        model_info.model_uri,
        eval_data,
        targets="label",
        model_type="classifier",
        evaluators="default",
        evaluator_config={"explainability_kernel_link":"logit"},
        feature_names=X_train[selected_features].columns
    )
```

### Describe the problem

I have deployed mlflow server on Kubernetes cluster and unless I explicitly set the following ENVs in python script / Jupyter notebook, it throws `"ValueError: Anonymous credentials cannot be refreshed."` error.

```
# Workaround
# import os 
# os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/Users/myname/Documents/json_serv.json'
```

In our container we have explicitly set `GOOGLE_APPLICATION_CREDENTIALS` environment variable and expect mlflow server to handle authentication with the google cloud storage bucket using the service account set by the env, but that's not the case.

Please do let me know if this is not possible and we do need to explicitly set the credentials in every script / notebook. 

Ideally we do not want to be in a situation that for every user we need to create a service account with appropriate permission and that requires manually setting ENVs in every script / notebook. 

From what I have seen so far, our setup requires us to explicitly set credentials in order to upload model artefacts. 

Please do let me know if there is something wrong with my setup / code and if you need more details.

Thanks in advance in helping me solve this issue :) 

### Other info / logs

<img width="671" alt="Screenshot 2022-08-15 at 15 32 27" src="https://user-images.githubusercontent.com/26812995/184694853-24e593a8-a164-4ba2-b43b-a2b552e85b6b.png">

**Comment by harupy** [comment]
@shahasim Can you share the full stacktrace?

**Comment by shahasim** [comment]
Hey @harupy, as requested

```
ValueError                                Traceback (most recent call last)
/Users/benhicks/Documents/UW/ml-template/notebooks/template-notebook.ipynb Cell 18 in <cell line: 8>()
      5 eval_data = X
      6 eval_data["label"] = y
----> 8 model.log_model(experiment_name="test", dataset_name="test", eval_data=eval_data, targets='label')

File ~/Documents/UW/ml-template/utils/catboost.py:447, in CatBoostWrapper.log_model(self, experiment_name, dataset_name, eval_data, targets, uri, tags, evaluators, feature_folder, *args, **kwargs)
    444 mlflow.log_params(self.training_parameters)
    445 mlflow.log_param("dataset", dataset_name)
--> 447 mlflow.log_artifact(feature_file, artifact_path="features")
    448 mlflow.log_artifact(target_file, artifact_path="features")
    450 self.model_info = mlflow.catboost.log_model(
    451     self.model, artifact_path="model"
    452 )

File ~/Documents/UW/ml-template/.venv/lib/python3.8/site-packages/mlflow/tracking/fluent.py:774, in log_artifact(local_path, artifact_path)
    751 """
    752 Log a local file or directory as an artifact of the currently active run. If no run is
    753 active, this method will create a new active run.
   (...)
    771         mlflow.log_artifact("features.txt")
    772 """
    773 run_id = _get_or_start_run().info.run_id
--> 774 MlflowClient().log_artifact(run_id, local_path, artifact_path)
...
    171     """Raises :class:`ValueError``, anonymous credentials cannot be
    172     refreshed."""
--> 173     raise ValueError("Anonymous credentials cannot be refreshed.")

ValueError: Anonymous credentials cannot be refreshed.
```

**Comment by harupy** [comment]
@shahasim Thanks for the stacktrace.

> expect mlflow server to handle authentication with the google cloud storage bucket using the service account set by the env

No, it doesn't by default. I think https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access can help.

Here's an example: https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts

**Comment by shahasim** [comment]
@harupy thank you for the feedback. I'll investigate this options and get back to you.

I am trying to simplify the use of mlflow for my team, so essentially when they add `mlflow.evaluate()` or `mlflow.log_artifact()` to their pipelines they don't have to explicitly define `os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/Users/myname/Documents/json_serv.json'`.. 

I'll check the scenario 5 and associated example and provide my feedback... many thanks :)

**Comment by harupy** [comment]
@shahasim When logging artifact, did you create a new experiment?

> When an experiment is created, the artifact storage location from the configuration of the tracking server is logged in the experiment’s metadata. When enabling proxied artifact storage, any existing experiments that were created while operating a tracking server in non-proxied mode will continue to use a non-proxied artifact location. In order to use proxied artifact logging, a new experiment must be created. If the intention of enabling a tracking server in -serve-artifacts mode is to eliminate the need for a client to have authentication to the underlying storage, new experiments should be created for use by clients so that the tracking server can handle authentication after this migration.

**Comment by harupy** [comment]
@shahasim Any updates here?

**Comment by shahasim** [comment]
@harupy .. apologies for not getting back to you earlier. We went down a rabbit role trying to understand the example you shared, mainly our fault … for some reason we felt we needed a separate `tracking` and `artefact` server. Whereas all we needed was the `serve-artifacts` flag on the tracking server and a new experiment. Based on the initial tests with this setup I think we are good. Please feel free to close this issue and thanks for your help 🙂

**Comment by harupy** [comment]
Got it! Thanks for reply :)
