### ISSUE TITLE
[BUG]mlflow model use more memory and can't release the used memmory

### ISSUE THREAD

**Issue by loredp** [mlflow/mlflow#6477]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.23.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:3.6.5
- **yarn version, if running the dev UI**:

### Describe the problem

when i load a model with a version, but how can i release the model used memory? just reboot the container? 

### Code to reproduce issue

``` python
pc_mem = psutil.virtual_memory()
print(pc_mem.available / pc_mem.total)
model = mlflow.pyfunc.load_model("models:/{}/{}".format(name,version)
model.predict(data)
pc_mem = psutil.virtual_memory()
print(pc_mem.available / pc_mem.total)
```

### Stack trace

``` python
model = mlflow.pyfunc.load_model("models:/{}/{}".format(name,version)
model.predict(data)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@loredp Can you provide the runnable code (that can be copy-and-pasted in a python terminal to reproduce the error)? What are the expected and actual behaviors?

**Comment by loredp** [comment]
> @loredp Can you provide the runnable code (that can be copy-and-pasted in a python terminal to reproduce the error)? What are the expected and actual behaviors? Can you also provide the output?

``` python

def clear_model_schedule():
    try:
        pc_mem = psutil.virtual_memory()
        available_percent = pc_mem.available / pc_mem.total
        if available_percent < 0.8:
            dic.clear()
            gc.collect()
            logger.info("model clear")
        pc_mem = psutil.virtual_memory()
        available_percent = pc_mem.available / pc_mem.total
    except Exception as exception:
        ...

def load_model(function_name, function_version):
    url = "models:/{}/{}".format(function_name, function_version)
    loaded_model = mlflow.pyfunc.load_model(url)
    if loaded_model is not None:
        dic[dickey] = loaded_model

```
i just want to release the memory used by dict. i cache the model in the dict by model name and version, when i clear the dict and gc.collect is not avaliable.
out put is :
model cache 0.7110894521077474
model clear
model cache 0.7111040751139323

clear is not work!!!

**Comment by harupy** [comment]
See https://stackoverflow.com/questions/10446839/does-dictionarys-clear-method-delete-all-the-item-related-objects-from-memory

> [Python documentation on dicts](http://docs.python.org/library/stdtypes.html?highlight=dict#dict) states that del d[key] removes d[key] from the dictionary while d.clear() removes every key, so basically their behavior is the same. On the memory issue, in Python when you "delete" you are basically removing a reference to an object. **When an object is not referenced by any variable nor other object or becomes unreachable, it becomes garbage and can be removed from memory. Python has a garbage collector that from time to time it does this job of checking which objects are garbage and releases the memory allocated for them. If the object you are deleting from the dictionary is referenced by other variable then it is still reachable, thus it is not garbage so it won't be deleted.** I leave you here some links if you are interested in reading about garbage collection in general and python's garbage collection in particular.

**Comment by loredp** [comment]
> 

Thank you! But in my code, we have not more reference just dict,  the method clear() means remove the only reference to the model instance.  So the fact is when the dict clear and model cache is not release. 
In my scene, we use the model instance frequently, so i need to cache the instance to be used in the next request. if i don't cache it, any good idea to suggest?

**Comment by harupy** [comment]
`loaded_model` is referencing to the model.

**Comment by harupy** [comment]
Quick test:


```python
import psutil
import gc

pc_mem = psutil.virtual_memory()
print(pc_mem.available / pc_mem.total)

model = "x" * 1_000_000_000_0

d = dict()
d["m"] = model

pc_mem = psutil.virtual_memory()
print(pc_mem.available / pc_mem.total)

d.clear()
gc.collect()

print("after clear")
pc_mem = psutil.virtual_memory()
print(pc_mem.available / pc_mem.total)

del model

d.clear()
gc.collect()

print("after del")
pc_mem = psutil.virtual_memory()
print(pc_mem.available / pc_mem.total)
```

Output:

```
0.9089007501354657
0.7601312782778884
after clear
0.7601312782778884
after del
0.9091223104196724
```

**Comment by harupy** [comment]
@loredp Feel free to reopen the issue if further investigation is needed.

**Comment by loredp** [comment]
> @loredp Feel free to reopen the issue if further investigation is needed.

thank for your patience, OK. i checked and tested my code, it mybe not 0 reference  in uvicorn multiprocess framework. 
mlflow is a great product,thank you.
