### ISSUE TITLE
[FR] Add Model Registry support to the FileStore

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#6485]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Add Model Registry support to the MLflow File Store so that users can use the Model Registry with better scale than sqlite without setting up SQL databases.

### Motivation

> #### What is the use case for this feature?

Enable easier / more scalable Model Registry use than what we currently provide with sqlite.

> #### Why is this use case valuable to support for MLflow users in general?

^

> #### Why is this use case valuable to support for your project(s) or organization?

^

> #### Why is it currently difficult to achieve this use case?

FileStore does not currently support Model Registry

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@serena-ruan Would you be interested in working on this item?

**Comment by serena-ruan** [comment]
@dbczumar Yes this sounds good, could you provide some entry point for me to get started on this task?

**Comment by dbczumar** [comment]
Truly excellent work on this, @serena-ruan ! Thanks so much!
