### ISSUE TITLE
local mlflow tracking server on windows

### ISSUE THREAD

**Issue by ACatAC** [mlflow/mlflow#6496]
In the past I was able to follow [this guide][1] to setup a local MLFLow tracking server.
Now, I am stuck with a Windows machine and I am clueless on ow to go about doing the same.

Especially on the 

> You need to go into the /etc/systemd/system directory and create a new file called mlflow-tracking.service

thing, as I am able to install MLFlow locally, of course, but every time I need to spin it up. How can I do that on Win?

Any help is welcome!

  [1]: https://towardsdatascience.com/setup-mlflow-in-production-d72aecde7fef

**Comment by harupy** [comment]
@ACatAC https://www.reddit.com/r/selfhosted/comments/8ijs26/systemdlike_to_create_windows_services_from/ might help.
