### ISSUE TITLE
[FR]: Github-like CSV Previews in the MLFlow UI

### ISSUE THREAD

**Issue by mrkaye97** [mlflow/mlflow#6498]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Throwing an idea out there -- I have no idea how difficult this would be to implement (am certainly not a JS expert and haven't been in the codebase much).

Right now, CSVs are displayed as text flat files in the UI, which are hard to glance at and understand. In Github, there's nicely formatted CSV files that you can preview (up to a certain size limit). See example [from FiveThirtyEight](https://github.com/fivethirtyeight/data/blob/master/ahca-polls/ahca_polls.csv)

![Screen Shot 2022-08-17 at 8 35 58 PM](https://user-images.githubusercontent.com/44219491/185267071-247b2aee-3169-4f69-bba7-848bc19a9ad2.png)
 

Again, no idea if this is a huge lift (or even possible), but it'd be an awesome feature!

### Motivation

> #### What is the use case for this feature?

It'd make it a lot easier to parse CSV files saved as artifacts

> #### Why is this use case valuable to support for MLflow users in general?

See 1)

> #### Why is this use case valuable to support for your project(s) or organization?

Also see 1). Often we'll just end up loading the artifact into R from MLFlow since it's hard to skim it in the UI, rendering the CSV in the UI almost totally useless

> #### Why is it currently difficult to achieve this use case?

CSVs are previewed as text files

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@mrkaye97 The proposal makes sense! Added the `help wanted` to find a contributor who would like to implement this :)

**Comment by dbczumar** [comment]
@harupy @mrkaye97 Is this equivalent to https://github.com/mlflow/mlflow/issues/6439, which is currently being worked on?

**Comment by harupy** [comment]
It is. Let's close this issue.

**Comment by harupy** [comment]
Updated https://github.com/mlflow/mlflow/issues/6439 to include Github's CSV viewer as an example.

**Comment by mrkaye97** [comment]
Awesome, this is super cool! thanks a bunch @harupy @dbczumar :)
