### ISSUE TITLE
[BUG] Failed to save the model to the HDFS

### ISSUE THREAD

**Issue by gaogao110** [mlflow/mlflow#6499]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow, version 1.27.0

### System information

Centos 7.9

### Describe the problem

I set up :
`mlflow server \
   --backend-store-uri mysql://xxxx:.xxxx@hd01:3306/mlflow_test \
   --host 0.0.0.0 -p 5001 \
   --default-artifact-root hdfs://mycluster/mlprojects/models`

running save model :
`2022/08/17 17:02:54 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/anaconda3/envs/mlflow-1.27.0/lib/python3.7/site-packages/mlflow/store/artifact/hdfs_artifact_repo.py:186: FutureWarning: pyarrow.hdfs.connect is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead."
2022/08/17 17:02:54 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during autologging: Prior attempt to load libhdfs failed`

I think is hdfs_artifact_repo.py prothem and pyarrow version 

I tried lowering the PyArrow version to 1.0,  But the same error is reported

### Code to reproduce issue

mlflow server \
   --backend-store-uri mysql://xxxx:.xxxx@hd01:3306/mlflow_test \
   --host 0.0.0.0 -p 5001 \
   --default-artifact-root hdfs://mycluster/mlprojects/models

### Stack trace

2022/08/17 17:02:54 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/anaconda3/envs/mlflow-1.27.0/lib/python3.7/site-packages/mlflow/store/artifact/hdfs_artifact_repo.py:186: FutureWarning: pyarrow.hdfs.connect is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead."
2022/08/17 17:02:54 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during autologging: Prior attempt to load libhdfs failed
258/258 [==============================] - 2s 5ms/step - loss: 1.1702 - accuracy: 0.5270 - val_loss: 0.9022 - val_accuracy: 0.6350
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: /tmp/tmpkjs57s12/model/data/model/assets
INFO:tensorflow:Assets written to: /tmp/tmpkjs57s12/model/data/model/assets
2022/08/17 17:03:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/anaconda3/envs/mlflow-1.27.0/lib/python3.7/site-packages/mlflow/store/artifact/hdfs_artifact_repo.py:186: FutureWarning: pyarrow.hdfs.connect is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead."
2022/08/17 17:03:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during tensorflow autologging: Prior attempt to load libhdfs failed
79/79 - 0s - loss: 0.8998 - accuracy: 0.6334 - 202ms/epoch - 3ms/step
/ntest loss: 0.8997762203216553
test accuracy: 0.6333597302436829

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@gaogao110 I found a few related issues:

- https://stackoverflow.com/questions/53027961/unable-to-load-libhdfs
- https://stackoverflow.com/questions/53087752/unable-to-load-libhdfs-when-using-pyarrow

**Comment by harupy** [comment]
This is where MLflow establishes the connection to HDFS: 

https://github.com/mlflow/mlflow/blob/16bf9f558ad51eb14f8682e2241cfac50797ddf7/mlflow/store/artifact/hdfs_artifact_repo.py#L160-L190

Can you directly run this code and check if the error occurs?

**Comment by gaogao110** [comment]
thanks for your reply ，I test 

` hdfs = pa.HadoopFileSystem(host, port, user='hdfs', kerb_ticket=kerb_ticket)
__main__:1: FutureWarning: pyarrow.hdfs.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/pyarrow-test/lib/python3.7/site-packages/pyarrow/hdfs.py", line 49, in __init__
    self._connect(host, port, user, kerb_ticket, extra_conf)
  File "pyarrow/_hdfsio.pyx", line 85, in pyarrow._hdfsio.HadoopFileSystem._connect
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: Prior attempt to load libhdfs failed
`

**Comment by harupy** [comment]
Thanks for the test. It looks like this is a pyarrow issue.

**Comment by gaogao110** [comment]
Thanks for your reply , I try python 3.8  is successed

**Comment by harupy** [comment]
Can we close this ticket?

**Comment by gaogao110** [comment]
Thanks for your reply , I try python 3.8  is successed
