### ISSUE TITLE
[BUG] mlflow.evaluate() fails for dataframes containing non-string column names

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#6503]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Python version**: 3.8
- **yarn version, if running the dev UI**: NA

### Describe the problem

When passing a Pandas DataFrame dataset to ``mlflow.evaluate()`` that contains non-string column names, evaluation fails because it attempts to string concatenate the column names with the `,` separator without converting the column names to strings:

```
Traceback (most recent call last):
  File "eval.py", line 50, in <module>
    results = mlflow.evaluate(
  File "/Users/corey.zumar/mlflow/mlflow/models/evaluation/base.py", line 1164, in evaluate
    dataset = EvaluationDataset(
  File "/Users/corey.zumar/mlflow/mlflow/models/evaluation/base.py", line 379, in __init__
    md5_gen.update(",".join(self._feature_names).encode("UTF-8"))
TypeError: sequence item 0: expected str instance, int found
```

### Tracking information

MLflow version: 1.28.0
Tracking URI: file:///Users/corey.zumar/mlexamples/sklearn/mlruns
Artifact URI: file:///Users/corey.zumar/mlexamples/sklearn/mlruns/0/b51876eec22b45468af3c4bb8be84121/artifacts

### Code to reproduce issue

```
import mlflow
from mlflow.models.evaluation import EvaluationDataset
from mlflow.models import MetricThreshold

import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# prepare train and test data
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

xy_test = pd.DataFrame(X_test)
xy_test["label"] = y_test

with mlflow.start_run():
    logistic = LogisticRegression(C=1.0)
    logistic.fit(X_train, y_train)
    mod = mlflow.sklearn.log_model(logistic, artifact_path="mymodel")

    results = mlflow.evaluate(
        model=mod.model_uri,
        model_type="classifier",
        data=xy_test,
        evaluator_config={
            "log_model_explainability": False,
        },
        evaluators="default",
        targets="label",
    )
```

### Stack trace

```
$ python reproeval.py
/Users/corey.zumar/opt/anaconda3/envs/base2/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
Traceback (most recent call last):
  File "reproeval.py", line 24, in <module>
    results = mlflow.evaluate(
  File "/Users/corey.zumar/mlflow/mlflow/models/evaluation/base.py", line 1164, in evaluate
    dataset = EvaluationDataset(
  File "/Users/corey.zumar/mlflow/mlflow/models/evaluation/base.py", line 379, in __init__
    md5_gen.update(",".join(self._feature_names).encode("UTF-8"))
TypeError: sequence item 0: expected str instance, int found
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dsgibbons** [comment]
I can provide a fix for this

**Comment by dbczumar** [comment]
Thank you, @dsgibbons ! Feel free to file a PR, and let me know if you have any questions.

**Comment by dbczumar** [comment]
Thanks @dsgibbons !

**Comment by dsgibbons** [comment]
It looks as though the above code breaks if `log_model_explainability=True`. I'll file an issue and find a fix.
