### ISSUE TITLE
DockerFile build is Failing

### ISSUE THREAD

**Issue by nov301996** [mlflow/mlflow#6513]
### Discussed in https://github.com/mlflow/mlflow/discussions/6512

<div type='discussions-op-text'>

<sup>Originally posted by **nov301996** August 19, 2022</sup>
Hi Guys, The Docker Build is getting failed with the below error, Please have a look at this issue.

8 78.80 Setting up gpg-wks-server (2.2.19-3ubuntu2.2) ...
#8 78.80 Setting up zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu1.3) ...
#8 78.81 Setting up cpp (4:9.3.0-1ubuntu2) ...
#8 78.82 Setting up cmake (3.16.3-1ubuntu1) ...
#8 78.82 Setting up libmysqlclient-dev (8.0.30-0ubuntu0.20.04.2) ...
#8 78.83 Setting up default-libmysqlclient-dev:amd64 (1.0.5ubuntu2) ...
#8 78.83 Setting up gcc-9 (9.4.0-1ubuntu1~20.04.1) ...
#8 78.84 Setting up libstdc++-9-dev:amd64 (9.4.0-1ubuntu1~20.04.1) ...
#8 78.85 Setting up gpg-wks-client (2.2.19-3ubuntu2.2) ...
#8 78.85 Setting up gcc (4:9.3.0-1ubuntu2) ...
#8 78.87 Setting up libprotobuf-dev:amd64 (3.6.1.3-2ubuntu5) ...
#8 78.87 Setting up g++-9 (9.4.0-1ubuntu1~20.04.1) ...
#8 78.89 Setting up g++ (4:9.3.0-1ubuntu2) ...
#8 78.90 update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
#8 78.90 update-alternatives: warning: skip creation of /usr/share/man/man1/c++.1.gz because associated file /usr/share/man/man1/g++.1.gz (of link group c++) doesn't exist
#8 78.91 Setting up gnupg (2.2.19-3ubuntu2.2) ...
#8 78.91 Setting up build-essential (12.8ubuntu1.1) ...
#8 78.92 Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
#8 79.53 Collecting package metadata (current_repodata.json): ...working... failed
#8 86.68 
#8 86.68 CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
#8 86.68 Elapsed: -
#8 86.68 
#8 86.68 An HTTP error occurred when trying to retrieve this URL.
#8 86.68 HTTP errors are often intermittent, and a simple retry will get you on your way.
#8 86.68 'https//conda.anaconda.org/conda-forge/linux-64'
#8 86.68 
#8 86.68 
------
executor failed running [/bin/sh -c apt-get update &&     apt-get install -y default-libmysqlclient-dev build-essential curl     cmake protobuf-compiler &&      conda install python=3.7 charset-normalizer=2.0.12 &&     pip install -r requirements/dev-requirements.txt --no-cache-dir &&     pip install --no-cache-dir -e . &&     mkdir -p /usr/share/man/man1 && apt-get install -y openjdk-11-jre-headless]: exit code: 1
</div>

**Comment by harupy** [comment]
@nov301996 Can you retry the build as the error message (`simple retry will get you on your way`) suggests?

**Comment by nov301996** [comment]
@harupy , we tried a lot of times but still we are getting same error

**Comment by harupy** [comment]
I guess something is wrong with your network. Can you try the build with this dockerfile?

```
FROM condaforge/miniforge3

RUN conda install python=3.7
```

**Comment by nov301996** [comment]
Still same error - 

 mlflow % docker build . -t mlflow_orgin 

[+] Building 12.5s (6/10)                                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 35B                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/condaforge/miniforge3:latest                                                                                                                                2.3s
 => CACHED [1/6] FROM docker.io/condaforge/miniforge3@sha256:21aeb04ae1909ec6bc51219a0a7cc9e9467c786faae0d664bdba034e6f7e0fad                                                                          0.0s
 => [internal] load build context                                                                                                                                                                      0.2s
 => => transferring context: 83.51kB                                                                                                                                                                   0.2s
 => ERROR [2/6] RUN conda install python=3.7                                                                                                                                                          10.2s
------                                                                                                                                                                                                      
 > [2/6] RUN conda install python=3.7:                                                                                                                                                                      
#4 0.814 Collecting package metadata (current_repodata.json): ...working... failed                                                                                                                          
#4 10.05                                                                                                                                                                                                    
#4 10.05 CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>                                                                         
#4 10.05 Elapsed: -
#4 10.05 
#4 10.05 An HTTP error occurred when trying to retrieve this URL.
#4 10.05 HTTP errors are often intermittent, and a simple retry will get you on your way.
#4 10.05 'https//conda.anaconda.org/conda-forge/linux-64'
#4 10.05 
#4 10.05 
------
executor failed running [/bin/sh -c conda install python=3.7]: exit code: 1

**Comment by nov301996** [comment]
@harupy  - I also tried with different python versions but still it failed with same error

**Comment by harupy** [comment]
@nov301996 What happens when you run conda on your host machine?

**Comment by nov301996** [comment]
@harupy - 

mlflow % conda --version
conda 4.12.0

mlflow % conda create -y -n my-python-env python=3.9.12
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base -c defaults conda



It is actually create a new conda env

**Comment by harupy** [comment]
I have no clue why it fails when building the image.

**Comment by harupy** [comment]
Can you try the docker build again?

**Comment by nov301996** [comment]
@harupy  - sure, tried with and without VPN, both the time it is failing

**Comment by nov301996** [comment]
> I have no clue why it fails when building the image.

It will be helpful if you can tag someone who knows/worked on this DockerFile

**Comment by harupy** [comment]
I think you can file an issue in https://github.com/conda/conda.
