### ISSUE TITLE
[FR] create new cli command for generating dockerfile

### ISSUE THREAD

**Issue by anuarkaliyev23** [mlflow/mlflow#6532]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

We have ability to create an docker image for ml model, stored and tracked in mlflow with command
`mlflow models build-docker <...> ` 
This command has several arguments\flags that can be specified, full list of which can be found in the [documentation](https://mlflow.org/docs/latest/cli.html#mlflow-models-build-docker) 

However, I find this approach rather opinionated in regard of building docker image. I find it more flexible to be able to extract said dockerfile and build this image using standard docker tools.

I propose a solution to overcome those difficulties without affecting any currently available functionality: **new cli command to generate `dockerfile` only**, which can be manipulated afterwards

### Motivation

> #### What is the use case for this feature?

For example, it can be useful in several scenarios:

- Building docker image on a remote host, even allowing us to use some tools like `buildx` to do so  (oftentimes useful with ci/cd pipelines)
- Changing resulting dockerfile, changing base image (useful when dealing with troublesome installments that have docker image of themselves, such as CUDA)
- Setting up cache policies for apt packages (keeping in mind considerate image size, it can be pretty useful coupled with remote host docker build)

> #### Why is this use case valuable to support for MLflow users in general?

Most of the scenarios are the ones, we are experiencing currently, introducing mlflow to our ml development, so I do believe they are applicable to the variety of users.

I believe, this approach will ease many processes related to integrating mlflow models or mlflow itself in ci/cd pipelines/cycles.

> #### Why is this use case valuable to support for your project(s) or organization?

We, at our organization restructuring our approaches regarding development of ML services. We find mlflow of great value regarding this process. It allows us to concentrate on ML model for ML team and on domain features for product teams, since it can automate "wrapping" our ml model in RESTful service. However we struggle sometimes with our currently existing ci/cd pipelines which were created with mindset of somewhat total control over things like dockerfile, which we must overcome sometimes, since it's easier for us to adapt to existing pipelines rather than changing ci/cd approaches we have

> #### Why is it currently difficult to achieve this use case?

Since mlflow calls docker implicitly it is difficult to pass arguments (such as `-H` for remote build). Python is not a primary language for my organization so it would be very troublesome to fork mlflow, since we coudn't possibly provide adequate support for it.
We've found some ways around those issues (such as setting `DOCKER_HOST` environment variable), but we are struggling right now with "post-build-docker" steps, such as installment of CUDA toolkit. We could possibly use ml model, built with mlflow, as a base image and manipulate over it (to install some software, for example) but this will add a major step to our ci/cd pipelines and will require us to maintain it

Ability to generate dockerfile would ease out those cases since we could change it afterwards and will allow us to reduce complexity of the steps necessary to deploy ml service

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@anuarkaliyev23 Thanks for the FR! Creating a new CLI command for generating a Dockerfile sounds good to me.

**Comment by anuarkaliyev23** [comment]
I am very glad to hear it.
As was said, I am willing to contribute with guidance from the community. Since my experience with Python is very limited, I will be more than glad to hear any suggestions or tips regarding contributing to this issue.
My initial plan was to add new function somewhere in `mlflow/models/cli.py`, with pretty much the same decorators as `build_docker` function is defined

Then I can reuse some things from from `build_image` function in file `mlflow/pyfunc/backend.py` and `_build_image` function in file `mlflow/pyfunc/backend.py` to produce dockerfile

Then I might need to add documentation, and here I have very limited understanding of where to start
As a more experienced member of community, @harupy are you OK with this plan, or am I missing something here?

**Comment by harupy** [comment]
@anuarkaliyev23 The plan sounds great!
