### ISSUE TITLE
Remove useless `os.system` calls

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#6548]
We can remove the following useless `os.system` calls:

https://github.com/mlflow/mlflow/blob/f15aa399c0fab866e95b54dab858b794a760cfe5/mlflow/models/container/__init__.py#L190-L192

https://github.com/mlflow/mlflow/blob/bd56ed75f776cbfaf4bb8b4c5f204d59acbe6fc6/mlflow/models/docker_utils.py#L193

**Comment by kitsiosvas** [comment]
Hello, is this issue open?
