### ISSUE TITLE
Cant start ui server 

### ISSUE THREAD

**Issue by paulgureghian** [mlflow/mlflow#655]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
When I go to localhost:5000 .  I get: Oops! Something went wrong.
If this error persists, please report an issue on our GitHub page.

**Comment by DorIndivo** [comment]
I had the same issue, In my case one of the experiments folders not saved properly.
Try delete the last experiment folder (the folder with the max id).

**Comment by paulgureghian** [comment]
yup. I just deleted folders from the 'mlruns' folder and it worked.
