### ISSUE TITLE
[SETUP-BUG] Relax docker version to allow 6.0.0

### ISSUE THREAD

**Issue by jmahlik** [mlflow/mlflow#6562]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **MLflow installed from (source or binary)**: either, wheel or git
- **MLflow version (run ``mlflow --version``)**: 1.28.0
- **Python version**: 3.10.6

### Code to reproduce issue

requirements.txt

```
mlflow==1.28.0
docker>=5.0.0
```

constraints.txt

```
docker>=6.0.0; platform_system == "Windows"
```

```
python -m pip install mlflow==1.28.0 # results in way old version of docker 4.x series that is not likely to work with other deps, transitive deps clash ex. sagemaker[local]
python -m pip install -r requirements.txt # does not resolve
# or 
python -m pip install -r requirements.txt -c constraints.txt # does not resolve
```

### Describe the problem

Currently, the docker major version is restricted to `5.x.x` in the [core requirements](https://github.com/mlflow/mlflow/blob/master/requirements/core-requirements.yaml#L13). This makes installing mlflow into a windows python 3.10 environment quite difficult, or not possible if there are other transitive deps relying on docker. Docker 5.0.0 fails to install due to a transitive pinned dep on pywin32 which doesn't work with python 3.10. 

Docker just released 6.0.0 which would make installation possible on windows.  Consider bumping the max allowable version of docker to 6. This would allow users to pin docker as needed and make installation possible on windows python 3.10.

There's not really a workaround other than relaxing the docker version or downgrading python to 3.9. Python 3.9 is discontinuing binary installers with the next release, so keeping python 3.9 up to date with security fixes will not be easy for the majority of python users on windows (building from source is not fun on windows).

https://github.com/docker/docker-py/releases/tag/6.0.0

https://github.com/docker/docker-py/pull/3004

**Comment by harupy** [comment]
Hi @jmahlik, we filed https://github.com/mlflow/mlflow/pull/6564 to update the docker requirement.
