### ISSUE TITLE
[BUG] Problems with protobuf:  Descriptors cannot not be created directly

### ISSUE THREAD

**Issue by ibobak** [mlflow/mlflow#6572]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.25.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 20.04
- **Python version**:  3.9
- **yarn version, if running the dev UI**:

### Describe the problem

This code
```
import mlflow
```
produces this exception - see stacktrace below.
I had the latest protobuf, and for me the workaround was this:
```
pip insrtall protobuf==3.20.0
```
based on what google found, and it worked. 

However, it would be good if you check and try to fix the dependencies.

### Code to reproduce issue

import mlflow

### Stack trace

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1248], in <module>
----> 1 import mlflow
      2 from mlflow.tracking.fluent import ActiveRun, end_run, get_run
      3 from tempfile import TemporaryDirectory

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/__init__.py:32, in <module>
     30 from mlflow.version import VERSION as __version__  # pylint: disable=unused-import
     31 from mlflow.utils.logging_utils import _configure_mlflow_loggers
---> 32 import mlflow.tracking._model_registry.fluent
     33 import mlflow.tracking.fluent
     35 # Filter annoying Cython warnings that serve no good purpose, and so before
     36 # importing other modules.
     37 # See: https://github.com/numpy/numpy/pull/432/commits/170ed4e33d6196d7

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/tracking/__init__.py:8, in <module>
      1 """
      2 The ``mlflow.tracking`` module provides a Python CRUD interface to MLflow experiments
      3 and runs. This is a lower level API that directly translates to MLflow
      4 `REST API <../rest-api.html>`_ calls.
      5 For a higher level API for managing an "active run", use the :py:mod:`mlflow` module.
      6 """
----> 8 from mlflow.tracking.client import MlflowClient
      9 from mlflow.tracking._tracking_service.utils import (
     10     set_tracking_uri,
     11     get_tracking_uri,
   (...)
     14     _TRACKING_URI_ENV_VAR,
     15 )
     16 from mlflow.tracking._model_registry.utils import (
     17     set_registry_uri,
     18     get_registry_uri,
     19 )

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/tracking/client.py:16, in <module>
     13 import yaml
     14 from typing import Any, Dict, Sequence, List, Optional, Union, TYPE_CHECKING
---> 16 from mlflow.entities import Experiment, Run, RunInfo, Param, Metric, RunTag, FileInfo, ViewType
     17 from mlflow.store.entities.paged_list import PagedList
     18 from mlflow.entities.model_registry import RegisteredModel, ModelVersion

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/entities/__init__.py:6, in <module>
      1 """
      2 The ``mlflow.entities`` module defines entities returned by the MLflow
      3 `REST API <../rest-api.html>`_.
      4 """
----> 6 from mlflow.entities.experiment import Experiment
      7 from mlflow.entities.experiment_tag import ExperimentTag
      8 from mlflow.entities.file_info import FileInfo

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/entities/experiment.py:2, in <module>
      1 from mlflow.entities._mlflow_object import _MLflowObject
----> 2 from mlflow.entities.experiment_tag import ExperimentTag
      3 from mlflow.protos.service_pb2 import (
      4     Experiment as ProtoExperiment,
      5     ExperimentTag as ProtoExperimentTag,
      6 )
      9 class Experiment(_MLflowObject):

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/entities/experiment_tag.py:2, in <module>
      1 from mlflow.entities._mlflow_object import _MLflowObject
----> 2 from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag
      5 class ExperimentTag(_MLflowObject):
      6     """Tag object associated with an experiment."""

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/protos/service_pb2.py:18, in <module>
     13 # @@protoc_insertion_point(imports)
     15 _sym_db = _symbol_database.Default()
---> 18 from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
     19 from . import databricks_pb2 as databricks__pb2
     22 DESCRIPTOR = _descriptor.FileDescriptor(
     23   name='service.proto',
     24   package='mlflow',
   (...)
     28   ,
     29   dependencies=[scalapb_dot_scalapb__pb2.DESCRIPTOR,databricks__pb2.DESCRIPTOR,])

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/mlflow/protos/scalapb/scalapb_pb2.py:29, in <module>
     18 DESCRIPTOR = _descriptor.FileDescriptor(
     19   name='scalapb/scalapb.proto',
     20   package='scalapb',
   (...)
     24   ,
     25   dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
     28 OPTIONS_FIELD_NUMBER = 1020
---> 29 options = _descriptor.FieldDescriptor(
     30   name='options', full_name='scalapb.options', index=0,
     31   number=1020, type=11, cpp_type=10, label=1,
     32   has_default_value=False, default_value=None,
     33   message_type=None, enum_type=None, containing_type=None,
     34   is_extension=True, extension_scope=None,
     35   serialized_options=None, file=DESCRIPTOR)
     36 MESSAGE_FIELD_NUMBER = 1020
     37 message = _descriptor.FieldDescriptor(
     38   name='message', full_name='scalapb.message', index=1,
     39   number=1020, type=11, cpp_type=10, label=1,
   (...)
     42   is_extension=True, extension_scope=None,
     43   serialized_options=None, file=DESCRIPTOR)

File /opt/anaconda3/envs/spark32/lib/python3.9/site-packages/google/protobuf/descriptor.py:560, in FieldDescriptor.__new__(cls, name, full_name, index, number, type, cpp_type, label, default_value, message_type, enum_type, containing_type, is_extension, extension_scope, options, serialized_options, has_default_value, containing_oneof, json_name, file, create_key)
    554 def __new__(cls, name, full_name, index, number, type, cpp_type, label,
    555             default_value, message_type, enum_type, containing_type,
    556             is_extension, extension_scope, options=None,
    557             serialized_options=None,
    558             has_default_value=True, containing_oneof=None, json_name=None,
    559             file=None, create_key=None):  # pylint: disable=redefined-builtin
--> 560   _message.Message._CheckCalledFromGeneratedFile()
    561   if is_extension:
    562     return _message.default_pool.FindExtensionByName(full_name)

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@ibobak https://github.com/mlflow/mlflow/pull/5945 fixed this issue. You can upgrade mlflow to a newer version.
