### ISSUE TITLE
[FR] Heavy installation requirements, many conflicts. Please create separate client and server pypi package.

### ISSUE THREAD

**Issue by hughperkins** [mlflow/mlflow#6583]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

[FR] Heavy installation requirements, many conflicts. Please create separate client and server pypi package.

### Motivation

> #### What is the use case for this feature?

Tried to `poetry add mlflow` on my M2 mac. It tries to install various really old dependencies, such as scipy and numpy. Which fails because M2 mac needs new dependencies. But why do I need scipy and so on just to log metrics to the server?

> #### Why is this use case valuable to support for MLflow users in general?

No-one likes installing a zillion packages when one will do.

> #### Why is this use case valuable to support for your project(s) or organization?

Makes installation easier.

> #### Why is it currently difficult to achieve this use case?

mlflow uses the exact same requirements for both server and client installations. Of coruse, the server has tons of depenendics.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Could you try install mlflow-skinny ?

**Comment by harupy** [comment]
> Perhaps could be made more obvious, in the doc? 

Would you be interested in filing a PR to improve the doc?

**Comment by harupy** [comment]
> Also, maybe mlflow-client might be a more intuitive name?

`mlflow-client` doesn't sounds like it's a lightweight version of `mlflow`.

**Comment by dbczumar** [comment]
Going to go ahead and close this out, since `mlflow-skinny` is the recommended solution. While I think that `mlflow-client` would be a more intuitive name, we don't currently plan to change the package name. Thanks @hughperkins !
