### ISSUE TITLE
[BUG] unable to pass artifacts between steps in multistep workflow

### ISSUE THREAD

**Issue by nfarley-soaren** [mlflow/mlflow#6585]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.10.4
- **yarn version, if running the dev UI**:

### Describe the problem

I'm trying to run a multistep mlflow project.  When trying to use artifacts generated in an earlier step and stored in an S3 bucket in a subsequent step, the files cannot be loaded due to the fact that the file path argument to the artifacts are passed in nested quotes.  It causes the following error: 
OSError: [Errno 22] Invalid argument.  I would expect a normal file path to be passed to the downstream step so the file can be read in and used.  

### Code to reproduce issue

```python
import mlflow
import argparse

parser = argparse.ArgumentParser(argument_default=argparse.SUPPRESS)
parser.add_argument("--fully_preprocessed_train_data", type=str, default="fully_preprocessed_train_data.pkl")
parser.add_argument("--fully_preprocessed_test_data", type=str, default="fully_preprocessed_test_data.pkl")
parser.add_argument("--fully_preprocessed_oot_data", type=str, default="fully_preprocessed_oot_data.pkl")
args = parser.parse_args()

preprocessing_params = {raw_data: raw_data_filepath}
train_params = {}

def workflow():
    with mlflow.start_run(description="Running workflow") as run:
        print("Performing custom preprocessing")
        custom_preprocessing_run = mlflow.run(".", "custom_preprocess", parameters=preprocessing_params)
        custom_preprocessing_runid = mlflow.tracking.MlflowClient().get_run(custom_preprocessing_run.run_id)
        data_path_uri = custom_preprocessing_runid.info.artifact_uri
        print(f"Sourcing training data from {data_path_uri}")
        mlflow.set_tag(key="custom_preprocess_runid", value=custom_preprocessing_runid)
        train_params["preprocessed_train_data_path"] = os.path.join(data_path_uri, args.fully_preprocessed_train_data).replace("\\", 
        "/")
        train_params["preprocessed_test_data_path"] = os.path.join(data_path_uri, args.fully_preprocessed_test_data).replace("\\", 
        "/")
        train_params["preprocessed_oot_data_path"] = os.path.join(data_path_uri, args.fully_preprocessed_oot_data).replace("\\", 
        "/")
        print("Launching training script")
        train_run = mlflow.run(".", "train", parameters=train_params)

if __name__ == "__main__":
    workflow()
```

### Stack trace

```
Launching training script
2022/08/23 11:58:40 INFO mlflow.utils.conda: Conda environment mlflow-f9436806216344de765e4a9ad154d6365504135b already exists.
2022/08/23 11:58:40 INFO mlflow.projects.utils: === Created directory C:\Users\NICOLE~1\AppData\Local\Temp\tmp23zpl4w1 for downloading remote URIs passed to arguments of type 'path' ===
2022/08/23 11:59:05 INFO mlflow.projects.backend.local: === Running command 'conda activate mlflow-f9436806216344de765e4a9ad154d6365504135b && python train.py  --preprocessed_train_data_path 'C:\Users\NICOLE~1.FAR\AppData\Local\Temp\tmp23zpl4w1\param_1\fully_preprocessed_train_data.pkl' --preprocessed_test_data_path 'C:\Users\NICOLE~1\AppData\Local\Temp\tmp23zpl4w1\param_2\fully_preprocessed_test_data.pkl' --preprocessed_oot_data_path 'C:\Users\NICOLE~1\AppData\Local\Temp\tmp23zpl4w1\param_3\fully_preprocessed_oot_data.pkl'  in run with ID '8931f30fbffe411696b49dd67d77596d' ===
Traceback (most recent call last):
  File "C:\Users\nicole\Desktop\repos\data-science-projects\multistep_workflow\train.py", line 252, in <module>
    train()
  File "C:\Users\nicole\Desktop\repos\data-science-projects\multistep_workflow\train.py", line 80, in train
    train_trans = pd.read_pickle(args.preprocessed_train_data_path)
  File "C:\Users\nicole\Miniconda3\envs\mlflow-f9436806216344de765e4a9ad154d6365504135b\lib\site-packages\pandas\io\pickle.py", line 187, in read_pickle
    with get_handle(
  File "C:\Users\nicole\Miniconda3\envs\mlflow-f9436806216344de765e4a9ad154d6365504135b\lib\site-packages\pandas\io\common.py", line 798, in get_handle
    handle = open(handle, ioargs.mode)
OSError: [Errno 22] Invalid argument: "'C:\\Users\\NICOLE~1\\AppData\\Local\\Temp\\tmp23zpl4w1\\param_1\\fully_preprocessed_train_data.pkl'"
Traceback (most recent call last):
  File "C:\Users\nicole\Desktop\repos\data-science-projects\pti_multistep_workflow\main.py", line 98, in <module>
    workflow()
  File "C:\Users\nicole\Desktop\repos\data-science-projects\pti_multistep_workflow\main.py", line 93, in workflow
    train_run = mlflow.run(".", "train", parameters=train_params)
  File "C:\Users\nicole\Miniconda3\envs\mlflow-f9436806216344de765e4a9ad154d6365504135b\lib\site-packages\mlflow\projects\__init__.py", line 346, in run
    _wait_for(submitted_run_obj)
  File "C:\Users\nicole\Miniconda3\envs\mlflow-f9436806216344de765e4a9ad154d6365504135b\lib\site-packages\mlflow\projects\__init__.py", line 363, in _wait_for       
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID '8931f30fbffe411696b49dd67d77596d') failed
2022/08/23 11:59:32 ERROR mlflow.cli: === Run (ID '12d3ed0d7c3d47eb9a200c9f2ceff20c') 
failed ===
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@nfarley-soaren On Windows, what does the following command print out?

```
import argparse

# python test.py  --param1 'C:\Users\test' --param2 "C:\Users\test"

parser = argparse.ArgumentParser(description="Process some integers.")
parser.add_argument("--param1")
parser.add_argument("--param2")
args = parser.parse_args()
print("param1", args.param1)
print("param2", args.param2)
```

On Ubuntu, the output is:

```
param1 C:\Users\test
param2 C:\Users\test
```

**Comment by harupy** [comment]
Single quotes are added in this line: https://github.com/mlflow/mlflow/blob/aa9ad78d175839144d40237ef662a9f8a0e9e4e6/mlflow/projects/_project_spec.py#L230

```python
>>> from shlex import quote
>>> print(quote("C:\\User\\test"))
'C:\User\test'
```

**Comment by nfarley-soaren** [comment]
@harupy On windows, you test.py prints out:  
param1 'C:\Users\test'
param2 C:\Users\test

I traced the issue through the source code.  In projects/utils.py get_entry_point_command() calls the
 _get_storage_dir function which creates a temp directory for downloading artifacts.  The subdirectories get added by compute_value() in _project_spec.py.  The file paths that are returned have single quotes.  When _sanitize_param_dict (in _project_spec.py) calls quote() it takes the single quoted file path and adds the double quotes around them.  This causes the windows error.

**Comment by harupy** [comment]
Looks like `shlex.quote` should not be used on Windowss: https://docs.python.org/3/library/shlex.html#shlex.quote

**Comment by nfarley-soaren** [comment]
@harupy That seems like a pretty big problem.

**Comment by dbczumar** [comment]
@harupy Any updates here?

**Comment by harupy** [comment]
@nfarley-soaren The approach in [this StackOverflow answer](https://stackoverflow.com/a/29215357) might be able to solve the issue.

**Comment by harupy** [comment]
@nfarley-soaren Would you mind running this code and sharing the output?

```python
# test.py
import argparse

parser = argparse.ArgumentParser(description="")
parser.add_argument("--param1")
parser.add_argument("--param2")
parser.add_argument("--param3")
args = parser.parse_args()
print("param1", args.param1)
print("param2", args.param2)
print("param3", args.param3)

# python test.py  --param1 'C:\Users\test' --param2 "C:\Users\test" --param3 ^"a b c^"
```

**Comment by nfarley-soaren** [comment]
@harupy  Sure thing.  I received the following error:
`test.py: error: unrecognized arguments: c --param3 ^a b c`

**Comment by GregRav** [comment]
Maybe on windows something similar would solve the problem (in _project_spec.py).

```python
if os.name != "nt":
    from shlex import quote
else:
    from mslex import quote
```

At least for me it worked for windows quoting issues in multistep projects.

**Comment by harupy** [comment]
@GregRav Thanks for the comment! I'll try `mslex` :)

**Comment by harupy** [comment]
@nfarley-soaren I opened https://github.com/mlflow/mlflow/pull/6745. Can you run the following command and check whether the PR can fix this issue?

```
pip install git+https://github.com/harupy/mlflow.git@fix-quote-issue
```
