### ISSUE TITLE
Feature request - Regex filtering for viewing only subset of params/metrics

### ISSUE THREAD

**Issue by erankam** [mlflow/mlflow#659]
Hi :)

I am now starting to use the package, and it is great so far. I thought of a small feature that I believe would be useful.
When using the UI of for ML Tracking, it would be great to filter down columns with basic regex.
For example - I am logging all my Layer1 params as L1.param (for example L1.Num_nurons = 3) and all my Layer2 params as L2.param. I would like to view the table with Layer1 columns only - view all variables that begin with L1*.

Thanks!

**Comment by sim-san** [comment]
This is a useful feature request.
