### ISSUE TITLE
[FR] Support for flags as arguments for runs

### ISSUE THREAD

**Issue by fabian-gringel** [mlflow/mlflow#6594]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Currently, when using the `mlflow run` command, parameters can be passed on to an entry point specified in `MLproject` using the option
[`-P, --param-list <NAME=VALUE>`](https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-run-P). This option does not support passing on flags.

It would be cool to support using flags to make it possible to use entry points that are already equipped with a CLI.

### Motivation

> #### What is the use case for this feature?
It would allow passing on flags from `mlflow run` to entry points specified in `MLprojects`.

> #### Why is this use case valuable to support for MLflow users in general?
In general, it would make it easier to integrate MLflow into an existing codebase where CLI entry points are already specified e.g. in a `setup.py`.

> #### Why is this use case valuable to support for your project(s) or organization?
It would reduce the overhead of integrating MLflow into existing projects.

> #### Why is it currently difficult to achieve this use case?
Currently, one would have to rewrite entry points using flags to work only with key-value parameters.

### Details

Support for flags could be achieved by either allowing to specify parameters of the form `-P, --param-list <NAME>` which get passed on as `--<NAME>` to the entry point, or by creating an additional option like `-F, --flag-list <NAME>`.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi fabian, could this be achieved currently as follows?

MLproject file `main` entrypoint section:

```
  main:
    parameters:
      my_optional_flags: {type: str, default: ""}
    command: "python main.py {my_optional_flags}"
```

`mlflow run` invocation:

```
mlflow run path/to/my/project -P "my_optional_flag=--flag1,--flag2"
```

Let me know if this helps.

**Comment by fabian-gringel** [comment]
Hi Corey,

that actually solves my problem. Thanks a lot for the quick help!
