### ISSUE TITLE
[DOC-FIX] Make doc link static and provide dropdown to select doc version

### ISSUE THREAD

**Issue by WeichenXu123** [mlflow/mlflow#6598]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.PyFuncModel.predict

### Description of proposal (what needs changing)

* Make doc link static, e.g., replace [https://www.mlflow.org/docs/latest/python_api/…](https://www.mlflow.org/docs/latest/python_api/%E2%80%A6) with [https://www.mlflow.org/docs/1.28.0/python_api/…](https://www.mlflow.org/docs/latest/python_api/%E2%80%A6)
so that when user saved the url, next time user open it, it will always go to the fixed 1.28.0 version doc.

* provide dropdown to select doc version

**Comment by dbczumar** [comment]
Thanks @harupy ! All done!
