### ISSUE TITLE
Cant Run mlflow_install()

### ISSUE THREAD

**Issue by Amrtarek0123** [mlflow/mlflow#660]
### System information
- **Windows 7**
- **MLflow installed from (Rstudio UI)**
- **Python3**
- **Exact command to reproduce**:mlflow_install()

### Error  
Solving environment: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/free/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)

**Comment by Amrtarek0123** [comment]
security team :S

**Comment by sai-krishna-msk** [comment]
Setting the environment variables as instructed in the following article helped

https://arandika.medium.com/error-on-anaconda-creating-new-environment-using-conda-command-on-windows-7-cb0758431654
