### ISSUE TITLE
[BUG] - Sagemaker - Can't deploy pytorch model trained on GPU to CPU

### ISSUE THREAD

**Issue by stobias123** [mlflow/mlflow#6601]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.28

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
- **Python version**: 3.9

### Describe the problem

When I've trained a model on GPU, I cannot run sagemaker on CPU. There seem to be extremely limited options for customizing or modifying the sagemaker dockerfile.

Everything works fine if I just set `map_location=torch.device('cpu')` as described in the error text, but I cannot build that into the sagemaker deploy.

### Code to reproduce issue

```bash
mlflow sagemaker run-local -m models:/Multi-Vehicle/1 --help

```

### Stack trace

```bash
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
[2022-08-26 03:01:03 +0000] [495] [INFO] Worker exiting (pid: 495)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [x] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @stobias123, thank you for raising this issue. The best solution available at the moment is to create a custom python model with custom loading logic as follows:

```
import mlflow.pyfunc

class CPUCompatibleModel(mlflow.pyfunc.PythonModel):
    def load_context(self, context):
        import torch
        import mlflow.pytorch
        
        if torch.cuda.is_available():
            self.torch_model = mlflow.pytorch._load_pyfunc(context.artifacts["torch_model"])
        else:
            self.torch_model = mlflow.pytorch._load_pyfunc(
                context.artifacts["torch_model"],
                map_location=torch.device('cpu')
            )

    def predict(self, context, model_input):
        return self.torch_model.predict(model_input)

compatible_model = mlflow.pyfunc.log_model(
    python_model=CPUCompatibleModel(),
    artifacts={
        "torch_model": "models:/Multi-Vehicle/1"
    },
)

print(compatible_model.model_uri)
```

Then, you should be able to run `mlflow sagemaker run-local` with the model URI output by the above script. Please let me know if this helps and feel free to reopen the issue if this solution does not resolve the problem. Thank you for using MLflow!
