### ISSUE TITLE
[BUG]icon of deleting experiment is gone on MLflow 1.28.0

### ISSUE THREAD

**Issue by greatzt** [mlflow/mlflow#6607]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

we upgraded to mlflow 1.28, but found the experiment deleting button was gone. 
![missing deleting](https://user-images.githubusercontent.com/39129610/186924523-80c15b17-fc28-46b3-bd0b-f59dd91e5040.png)
we can see this link on version 1.25.1 as below
![with deleting](https://user-images.githubusercontent.com/39129610/186924639-4afb4dbb-d594-4bb1-acf1-f928eac73bb3.png)

### Steps to reproduce the bug

see the experiment list on MLflow UI

**Comment by dbczumar** [comment]
@greatzt Thank you for filing this issue. We've addressed it via https://github.com/mlflow/mlflow/pull/6569, which will be released in a couple of weeks as part of MLflow 1.29.0. Thank you for using MLflow!
