### ISSUE TITLE
[BUG] _TF2Wrapper.predict method fails to handle 1-dimensional output tensors

### ISSUE THREAD

**Issue by LiamConnell** [mlflow/mlflow#6610]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS, Ubuntu 18
- **Python version**: 3.8.13

### Describe the problem

I have a model that was trained using the Tensorflow Object Detection API and saved with mlflow. One of the outputs of the model is a 1D tensor (i.e. shape=(batch_size,)) and is called `num_detections`. When the code flow reaches the third line of the [following block](https://github.com/mlflow/mlflow/blob/master/mlflow/tensorflow/__init__.py#L544-L549), it fails because the code block cant handle 1D tensors: 

```
        pred_dict = {col_name: raw_preds[col_name].numpy() for col_name in raw_preds.keys()}
        for col in pred_dict.keys():
            if all(len(element) == 1 for element in pred_dict[col]):
                pred_dict[col] = pred_dict[col].ravel()
            else:
                pred_dict[col] = pred_dict[col].tolist()
```

I'm happy to help contribute a fix for this bug. I'll be back online Monday! 

### Code to reproduce issue

```
from mlflow.pyfunc import load_model
import numpy as np
from PIL import Image

model = load_model(model_path)
img = Image.open(image_path)
data = np.expand_dims(np.array(img), axis=0)

model.predict({"input_tensor": data})
```

### Stack trace

```
  File "test.py", line 28, in <module>
    print(model.predict({"input_tensor": data}))
  File "/Users/connellliam/.pyenv/versions/3.8.13/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 652, in predict
    return self._model_impl.predict(data)
  File "/Users/connellliam/.pyenv/versions/3.8.13/lib/python3.8/site-packages/mlflow/tensorflow/__init__.py", line 543, in predict
    if all(len(element) == 1 for element in pred_dict[col]):
  File "/Users/connellliam/.pyenv/versions/3.8.13/lib/python3.8/site-packages/mlflow/tensorflow/__init__.py", line 543, in <genexpr>
    if all(len(element) == 1 for element in pred_dict[col]):
TypeError: object of type 'numpy.float32' has no len()
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @LiamConnell, thank you for raising this issue! We'd be thrilled to review a PR that fixes the issue. Please let me know if you have any questions, and we're looking forward to your fix!

**Comment by LiamConnell** [comment]
@dbczumar I just created a PR. (Sorry about the delay!) I'm happy to continue the discussion at #6796
