### ISSUE TITLE
[BUG] conda environment creation attempt when running project with --no-conda/--env-manager=local causes failure

### ISSUE THREAD

**Issue by nfarley-soaren** [mlflow/mlflow#6611]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Windows Server 2019 Standard
- **Python version**: 3.10.4
- **yarn version, if running the dev UI**:

### Describe the problem

I am attempting to run mlflow project from a github repo on remote Windows Server.  I have not had any problems running the same command on my local Windows 10 machine.   The run failed on remote due to a conda error during environment creation so I manually created an environment to use.  However, when I try to run the project with the local environment (either using --no-conda or --env-manager=local) it still attempts to create the project environment and fails at this step.  Any insight would be greatly appreciated.

### Code to reproduce issue

```
mlflow run https://{GITHUB_ACCESS_TOKEN}@github.com/CompanyName/data-science-projects.git#pti_multistep_workflow --version my_model --experiment-name my_experiment --env-manager=local
```

### Stack trace

```
2022/08/26 13:56:35 INFO mlflow.projects.utils: === Fetching project from https://{GITHUB_ACCESS_TOKEN}@github.com/CompanyName/data-science-projects.git#pti_multistep_workflow into C:\Users\NICOLE~1.FAR\AppData\Local\Temp\6\tmph1v6_xbz ===
2022/08/26 13:56:56 INFO mlflow.projects.utils: === Created directory C:\Users\NICOLE~1.FAR\AppData\Local\Temp\6\tmpj97ildpr for downloading remote URIs passed to arguments of type 'path' ===
2022/08/26 13:56:56 INFO mlflow.projects.backend.local: === Running command 'python main.py' in run with ID 'bab43bcd1c23482c8bc0b5383d572b61' ===
2022/08/26 13:57:04 INFO mlflow.utils.conda: === Creating conda environment mlflow-f9436806216344de765e4a9ad154d6365504135b ===
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/win-64'


Traceback (most recent call last):
  File "C:\Users\NICOLE~1.FAR\AppData\Local\Temp\6\tmph1v6_xbz\pti_multistep_workflow\main.py", line 106, in <module>
    workflow()
  File "C:\Users\NICOLE~1.FAR\AppData\Local\Temp\6\tmph1v6_xbz\pti_multistep_workflow\main.py", line 85,
in workflow
    custom_preprocessing_run = mlflow.run(".", "custom_preprocess", parameters=preprocessing_params)
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\projects\__init__.py", line
331, in run
    submitted_run_obj = _run(
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\projects\__init__.py", line
95, in _run
    submitted_run = backend.run(
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\projects\backend\local.py",
line 136, in run
    conda_env_name = get_or_create_conda_env(project.env_config_path)
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\utils\conda.py", line 214, in get_or_create_conda_env
    process._exec_cmd(
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\utils\process.py", line 116, in _exec_cmd
    raise ShellCommandException.from_completed_process(comp_process)
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['C:\\ProgramData\\Miniconda3\\condabin\\..\\Scripts\\conda', 'env', 'create', '-n', 'mlflow-f9436806216344de765e4a9ad154d6365504135b', '--file', 'C:\\Users\\NICOLE~1.FAR\\AppData\\Local\\Temp\\6\\tmph1v6_xbz\\pti_multistep_workflow\\conda.yaml']
2022/08/26 13:57:15 ERROR mlflow.cli: === Run (ID 'bab43bcd1c23482c8bc0b5383d572b61') failed ===
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @nfarley-soaren, thank you for raising this issue. I'll investigate why `--env-manager=local` is still resulting in the use of Conda during an MLflow Project invocation.

**Comment by harupy** [comment]
@nfarley-soaren 

> it still attempts to create the project environment and fails at this step. Any insight would be greatly appreciated.

Looks like your `main.py` calls `mlflow.run`, which attempts to create a project environment with conda when `env_manager` is unspecified.

```
Traceback (most recent call last):
  File "C:\Users\NICOLE~1.FAR\AppData\Local\Temp\6\tmph1v6_xbz\pti_multistep_workflow\main.py", line 106, in <module>
    workflow()
  File "C:\Users\NICOLE~1.FAR\AppData\Local\Temp\6\tmph1v6_xbz\pti_multistep_workflow\main.py", line 85,
in workflow
                               👇👇👇👇👇👇
    custom_preprocessing_run = mlflow.run(".", "custom_preprocess", parameters=preprocessing_params)
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\projects\__init__.py", line
331, in run
    submitted_run_obj = _run(
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\projects\__init__.py", line
95, in _run
    submitted_run = backend.run(
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\projects\backend\local.py",
line 136, in run
    conda_env_name = get_or_create_conda_env(project.env_config_path)
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\utils\conda.py", line 214, in get_or_create_conda_env
    process._exec_cmd(
  File "C:\Users\nicole\.conda\envs\tutorial\lib\site-packages\mlflow\utils\process.py", line 116, in _exec_cmd
    raise ShellCommandException.from_completed_process(comp_process)
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['C:\\ProgramData\\Miniconda3\\condabin\\..\\Scripts\\conda', 'env', 'create', '-n', 'mlflow-f9436806216344de765e4a9ad154d6365504135b', '--file', 'C:\\Users\\NICOLE~1.FAR\\AppData\\Local\\Temp\\6\\tmph1v6_xbz\\pti_multistep_workflow\\conda.yaml']
2022/08/26 13:57:15 ERROR mlflow.cli: === Run (ID 'bab43bcd1c23482c8bc0b5383d572b61') failed ===
```

**Comment by nfarley-soaren** [comment]
@harupy Thank you!

**Comment by Minhvt34** [comment]
@harupy @nfarley-soaren I just encountered this issue, how can I handle it? Thanks

**Comment by nfarley-soaren** [comment]
@Minhvt34 You need to remember to set the `env_manager="local"` argument inside of the mlflow.run() command in the script also.
