### ISSUE TITLE
[FR] Extend `mlflow gc` to support removing deleted experiments

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#6617]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Add an `--experiment-ids` flag to the `mlflow gc` CLI (https://mlflow.org/docs/latest/cli.html#mlflow-gc). For each experiment ID that is specified, `mlflow gc` should remove the experiment and all of its runs. 

Before performing deletion, `mlflow gc` should verify that all of the specified experiments are in the `DELETED` state. `mlflow gc` should support specifying `--experiment-ids` and `--run-ids` at the same time, and `--older-than` should be extended to apply to runs and experiments

### Motivation

> #### What is the use case for this feature?

Enable MLflow admins to permanently remove deleted experiments

> #### Why is this use case valuable to support for MLflow users in general?

The inability to delete experiments means that experiment names cannot be reused and experiment storage space cannot be freed. This FR would address these issues.

> #### Why is this use case valuable to support for your project(s) or organization?

^

> #### Why is it currently difficult to achieve this use case?

MLflow does not currently offer a way to permanently remove deleted experiments

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by shaikmoeed** [comment]
@dbczumar I can contribute to this issue if someone from the community can guide me :)

**Comment by dbczumar** [comment]
Hi @shaikmoeed, absolutely! I've assigned the issue to you. The code for `mlflow gc` is here: https://github.com/mlflow/mlflow/blob/c750b031604eed321a29d9ac3f2298f6ef2006b4/mlflow/cli.py#L497-L574. We'll want to:

1. List all soft-deleted experiments with last_update_timestamp <= now - timedelta (https://github.com/mlflow/mlflow/blob/c750b031604eed321a29d9ac3f2298f6ef2006b4/mlflow/cli.py#L548)

2. For each soft-deleted experiment, list its runs and add them to the list of run IDs to delete (https://github.com/mlflow/mlflow/blob/c750b031604eed321a29d9ac3f2298f6ef2006b4/mlflow/cli.py#L550-L555)

3. Add a `backend_store._hard_delete_experiment()` API to https://github.com/mlflow/mlflow/blob/master/mlflow/store/tracking/file_store.py and https://github.com/mlflow/mlflow/blob/master/mlflow/store/tracking/sqlalchemy_store.py. Call this API for each soft-deleted experiment after run deletion completes (i.e. after https://github.com/mlflow/mlflow/blob/c750b031604eed321a29d9ac3f2298f6ef2006b4/mlflow/cli.py#L557-L574).

Please let me know if you have any questions; happy to provide further guidance! Thank you in advance for your contribution!

**Comment by shaikmoeed** [comment]
How this implementation is used? Is `mlflow gc --experiment-ids="exp_id1,exp_id2"` command is valid? Can you share example usage commands for this?

**Comment by dbczumar** [comment]
> Thanks for guiding me, I would also like to know,
> 
> 1. How this implementation is used? Is `mlflow gc --experiment-ids="exp_id1,exp_id2"` command is valid? Can you share example usage commands?
> 2. What should happen, if `--experiment-ids` is not provided as it's an optional flag?
> 3. How to fetch soft deleted experiments? Is there any API for this like `backend_store._get_deleted_experiments(older_than=current_timestamp) # with LifecycleStage.DELETED` where `current_timestamp = datetime.now() - timedelta(**time_params)`?

Great questions!

1. If the user specifies `--experiment-ids`, then only the specified soft-deleted experiments will be removed. If the user does not specify `--experiment-ids`, all soft-deleted experiments will be removed. The syntax you included is great!

2. `--experiment-ids` is optional

3. Soft deleted experiments can be queried via `search_experiments()` (https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_experiments) with `view_type` `DELETED_ONLY`.

**Comment by shaikmoeed** [comment]
Thanks for the detailed answers! The work is almost done, I was a bit confused in creating `_hard_delete_experiment` for https://github.com/mlflow/mlflow/blob/master/mlflow/store/tracking/file_store.py.

To delete the experiment directory using `_hard_delete_experiment`, do I need to create a `_find_experiement_root` or can I use `_find_experiment_folder` from https://github.com/mlflow/mlflow/blob/53db21f3d81405f6dcb4e7c66af5ec3621e3604b/mlflow/store/tracking/file_store.py#L550

Can you help in getting `run_path`?
```
def _hard_delete_experiment(self, exp_id):
    run_path = # not sure how to get run path
    exp_dir = self._find_experiment_folder(run_path)
    shutil.rmtree(run_dir)
```

**Comment by shaikmoeed** [comment]
I am a little new to writing test cases, can I get guidance on writing test cases if needed to close this issue?
