### ISSUE TITLE
[FR] Implement a set_model_version_tag API in the R client

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#6618]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Implement a set_model_version_tag API in the MLflow R client, which should provide equivalent functionality to https://github.com/mlflow/mlflow/blob/0645f9228b874e0b1d9f37cb0a0761c0736fea30/mlflow/tracking/client.py#L2804-L2806.

### Motivation

> #### What is the use case for this feature?

Enable R users to set model version tags.

> #### Why is this use case valuable to support for MLflow users in general?

^

> #### Why is this use case valuable to support for your project(s) or organization?

^

> #### Why is it currently difficult to achieve this use case?

No such API exists in the R client

### Details

For reference, the existing implementation of set_experiment_tag may be helpful because the set_model_version_tag implementation is likely to be very similar: https://github.com/mlflow/mlflow/blob/0645f9228b874e0b1d9f37cb0a0761c0736fea30/mlflow/R/mlflow/R/tracking-experiments.R#L115-L129

Test coverage for set_experiment_tag is located at https://github.com/mlflow/mlflow/blob/0645f9228b874e0b1d9f37cb0a0761c0736fea30/mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R#L177-L216. Comparable coverage for set_model_version_tag should be implemented in https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/tests/testthat/test-model-registry.R.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by leeweijie** [comment]
Anyone working on this? Otherwise happy to work on this issue!

**Comment by dbczumar** [comment]
Hi @leeweijie, thank you for picking up this issue! Looking forward to your contribution!

**Comment by leeweijie** [comment]
@dbczumar thank you! I've just created a PR (#7401 ) for this issue.
