### ISSUE TITLE
[DOC-FIX] broken link to outdated blog post on mlflow.org

### ISSUE THREAD

**Issue by andreakress** [mlflow/mlflow#6652]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://mlflow.org/

<img width="1231" alt="image (1)" src="https://user-images.githubusercontent.com/62267356/187533297-7ba90bfa-9aa1-46d8-96db-ac15f9ba5ef5.png">

### Description of proposal (what needs changing)

The link highlighted in the previous field goes to a 404.

**Comment by db-william-lee** [comment]
Redirect added to correct URL

**Comment by dbczumar** [comment]
Thanks @db-william-lee !
