### ISSUE TITLE
[BUG] Can't gc a run: Run not found

### ISSUE THREAD

**Issue by mautini** [mlflow/mlflow#6659]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

I'm using mlflow-cli

### Describe the problem

I would like to permanently delete some deleted runs in my mlflow server but the command `mlflow gc` seems to do nothing, so I tried to gc a particular run with the command `mlflow gc run-ids <run_id>` but I got the error `mlflow.exceptions.MlflowException: Run '<run_id>' not found`.

However, using `mlflow runs describe --run-id <run_id>` I could get the following result so the run exists and its lifecycle_stage is deleted (sensitive information masked).

```json
{
    "info": {
        "artifact_uri": "gs://path/to/gcs/bucket",
        "end_time": 1643994897180,
        "experiment_id": "0",
        "lifecycle_stage": "deleted",
        "run_id": "<run_id>",
        "run_uuid": "<run_uuid>",
        "start_time": 1643994886466,
        "status": "FINISHED",
        "user_id": "root"
    },
    "data": {
        "metrics": {},
        "params": {},
        "tags": {
            "mlflow.user": "root",
            "mlflow.source.name": "/Users/root/Documents/training.py",
            "mlflow.source.type": "LOCAL",
            "mlflow.source.git.commit": "<git_commit>"
        }
    }
}
```

### Tracking information

- MLflow version: 1.27.0
- Tracking URI: http://localhost:8081/ (I'm using some port forwarding)
- Artifact URI: gs://path/to/gcs/bucket

### Code to reproduce issue

mlflow gc --run-ids <run_id>  

### Stack trace

```python
Traceback (most recent call last):
  File "/Users/root/Documents/venv/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/mlflow/cli.py", line 486, in gc
    run = backend_store.get_run(run_id)
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 530, in get_run
    run_info = self._get_run_info(run_id)
  File "/Users/root/Documents/venv/lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 549, in _get_run_info
    raise MlflowException(
mlflow.exceptions.MlflowException: Run '<run_id>' not found
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @mautini, if you run `mlflow gc` without specifying a `--backend-store-uri`, `mlflow gc` will search for runs in the `./mlruns` directory under the current working directory by default. Specifying `--backend-store-uri <uri_for_your_mlflow_tracking_store>` should resolve the issue. Thank you for using MLflow!
