### ISSUE TITLE
[BUG]MlflowException: Detected out-of-date database schema (found version bd07f7e963c5, but expected cc1f77228345). Mlflow 1.28

### ISSUE THREAD

**Issue by Neethugkp** [mlflow/mlflow#6703]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

Mlflow 1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

Failed to initialize database.
DB in use MSSQL 2016

Works with mlflow 1.27.0 not with mlflow 1.28.

### Code to reproduce issue

By upgrading  mlflow 1.26.1 to mlflow 1.28

### Stack trace

2022/09/05 15:05:44 ERROR mlflow.cli: Error initializing backend store
2022/09/05 15:05:44 ERROR mlflow.cli: Detected out-of-date database schema (found version bd07f7e963c5, but expected cc1f77228345). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mlflow/cli.py", line 461, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/server/handlers.py", line 267, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/server/handlers.py", line 246, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/server/handlers.py", line 114, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/store/tracking/sqlalchemy_store.py", line 147, in __init__
    mlflow.store.db.utils._verify_schema(self.engine)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/store/db/utils.py", line 61, in _verify_schema
    "more detail." % (current_rev, head_revision)
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version bd07f7e963c5, but expected cc1f77228345). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.

### Other info / logs

pip install from mlflow 1.27.0 deployment
Package                   Version  
------------------------- ---------
alembic                   1.8.1    
boto3                     1.24.66  
botocore                  1.27.66  
certifi                   2022.6.15
charset-normalizer        2.1.1    
click                     8.1.3    
cloudpickle               2.1.0    
databricks-cli            0.17.3   
docker                    6.0.0    
entrypoints               0.4      
Flask                     2.2.2    
gitdb                     4.0.9    
GitPython                 3.1.27   
greenlet                  1.1.3    
gunicorn                  20.1.0   
idna                      3.3      
importlib-metadata        4.12.0   
importlib-resources       5.9.0    
itsdangerous              2.1.2    
Jinja2                    3.1.2    
jmespath                  1.0.1    
Mako                      1.2.2    
MarkupSafe                2.1.1    
mlflow                    1.27.0   
numpy                     1.21.6   
oauthlib                  3.2.0    
packaging                 21.3     
pandas                    1.3.5    
pip                       20.0.2   
prometheus-client         0.14.1   
prometheus-flask-exporter 0.20.3   
protobuf                  4.21.5   
PyJWT                     2.4.0    
pymssql                   2.2.5    
pyodbc                    4.0.28   
pyparsing                 3.0.9    
python-dateutil           2.8.2    
pytz                      2022.2.1 
PyYAML                    6.0      
querystring-parser        1.2.4    
requests                  2.28.1   
s3transfer                0.6.0    
scipy                     1.7.3    
setuptools                41.1.0   
six                       1.16.0   
smmap                     5.0.0    
SQLAlchemy                1.4.40   
sqlparse                  0.4.2    
tabulate                  0.8.10   
typing-extensions         4.3.0    
urllib3                   1.26.12  
websocket-client          1.4.1    
Werkzeug                  2.2.2    
zipp                      3.8.1  

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Neethugkp Did you run `mlflow db upgrade <database_uri>`?

**Comment by BenWilson2** [comment]
@Neethugkp please ensure that you upgrade your database definitions with the utility function that @harupy mentioned. This should solve your issue.

**Comment by Neethugkp** [comment]
Thank you @harupy @BenWilson2 . After upgrade of dburi it worked.
