### ISSUE TITLE
MlflowClient set tracking_uri not working

### ISSUE THREAD

**Issue by bwallima** [mlflow/mlflow#6709]
https://github.com/mlflow/mlflow/blob/c20c664e037b895ff4bd49dda4a26604e55a9b93/mlflow/tracking/client.py#L46

When handing over the tracking_uri and at the same time an environment variable "MLFLOW_TRACKING_URI" is set, the artifact is tried to be downloaded from the uri set in the environment variable "MLFLOW_TRACKING_URI" and not from the handed over parameter:
```
client = MlflowClient(tracking_uri='new_uri')
model_path = client.download_artifacts(run_id='bee74a92fc0e42fab432bd1994fd194f', path='full_model')
```
However when you change the environment variable in advance the new uri is used.
```
os.environ["MLFLOW_TRACKING_URI"] = "new_uri"
client = MlflowClient()
model_path = client.download_artifacts(run_id='bee74a92fc0e42fab432bd1994fd194f', path='full_model')
```

**Comment by harupy** [comment]
@bwallima 

```python
import mlflow
import os


with mlflow.start_run() as run:
    mlflow.log_artifact(__file__, artifact_path="dir")

os.environ["MLFLOW_TRACKING_URI"] = "./unknown"
client = mlflow.MlflowClient(tracking_uri="./mlruns")
model_path = client.download_artifacts(run_id=run.info.run_id, path="dir")
print(model_path)
```

worked. Am I missing something?

**Comment by bwallima** [comment]
This is not working for me:
```
    os.environ["MLFLOW_TRACKING_URI"] = 'bla'
    client = MlflowClient(tracking_uri="https://modelregistry.train.prod.mlp.suvanet.ch/")
    model_path = client.download_artifacts(run_id='bee74a92fc0e42fab432bd1994fd194f', path='full_model')
```

However this is working:
```
    os.environ["MLFLOW_TRACKING_URI"] = "https://modelregistry.train.prod.mlp.suvanet.ch/"
    client = MlflowClient()
    model_path = client.download_artifacts(run_id='bee74a92fc0e42fab432bd1994fd194f', path='full_model')
```

**Comment by harupy** [comment]
What do you mean by `not working`?

**Comment by bwallima** [comment]
well I get back an error 'not found'. I mean 'bla' is not existing.

**Comment by harupy** [comment]
Can you share the traceback?

**Comment by bwallima** [comment]
by the way I use  "from mlflow.tracking import MlflowClient" with mlflow==1.24.0. Ist that wrong?

**Comment by harupy** [comment]
No, it's fine.

**Comment by harupy** [comment]
You can try a newer version of mlflow.

**Comment by bwallima** [comment]
ok, I will try that.
