### ISSUE TITLE
provide experiment_id field in MLproject file

### ISSUE THREAD

**Issue by areshytko** [mlflow/mlflow#673]
When we run the code via mlflow run a new interpreter is being spawned for the actual code that invokes mlflow.tracking APIs. And looks like it reads the environment variable MLFLOW_RUN_ID which was set by mlflow previouly and all python API that set experiment id don't work:

mlflow.set_experiment()
mlflow.start_run(experiment_id=<id>)

both of these APIs are ignored and this is very confusing. Everyhing is still tracked under default experiment (if no argument was provided to mlflow run or the env variable wasn't set)

In my setup each MLproject is an experiment on it's own. And I don't want to set the id manually for every one. And looks like I can't use python API for that either.

So, please, either fix the python API for the case when the code is invoked by mlflow run or provide a field in MLproject file for experiment id.

**Comment by aakashganga** [comment]
You need to use --experiment-id argument while issuing mlflow run commnad. See `mlflow run --help`

**Comment by shayts7** [comment]
Using `--experiment-id` indeed works but it's not convenient at all. You have to create the experiment ahead and pass the id of it, so practically I need to have a script that creates the experiment if not exist, grabs the id and pass it in the `mlflow run` command line, instead that set_experiment() will work as expected.

**Comment by amitreches** [comment]
I have the same problem and use the same workaround. I wanted to know if this issue has been resolved or advanced in some form? Thank you.
