### ISSUE TITLE
[BUG] ValueError: Enum ErrorCode has no value defined for name '403' in mlflow.set_experiment()

### ISSUE THREAD

**Issue by MinuraPunchihewa** [mlflow/mlflow#6734]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.19.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **Python version**: 3.10.4
- **databricks-connect version**: 7.3.45

### Describe the problem

I am trying to run some code to  train a model, while logging my results to MLflow on Databricks. I am using Databricks Connect to achieve this.

However, before I get to that step, the given error pops up when I try to make a call to `mlflow.set_experiment()`.

What exactly is going on here?

I was able to run my code without an issue a while ago, but when I came back to it, I encountered this error.

### Code to reproduce issue

```
# set the mlflow registry and tracking URIs
mlflow.set_registry_uri(remote_server_uri)
mlflow.set_tracking_uri(remote_server_uri)

# create the MLflow client
client = MlflowClient(remote_server_uri)

# set base path for experiment
base_path = '/base/path/to/mlflow/experiments'

# set experiment to log mlflow runs
mlflow.set_experiment(base_path + experiment_name)
```

Note: The value set for the variable `remote_server_uri` is 'databricks'.

### Stack trace

```
    mlflow.set_experiment(base_path + experiment_name)
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\tracking\fluent.py", line 84, in set_experiment
    experiment = client.get_experiment_by_name(experiment_name)
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\tracking\client.py", line 463, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 155, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\store\tracking\rest_store.py", line 321, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\utils\rest_utils.py", line 170, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\utils\rest_utils.py", line 122, in verify_rest_response
    raise RestException(json.loads(response.text))
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\mlflow\exceptions.py", line 75, in __init__
    super().__init__(message, error_code=ErrorCode.Value(error_code))
  File "C:\Users\minurap\Anaconda3\envs\oct_use_case_2\lib\site-packages\google\protobuf\internal\enum_type_wrapper.py", line 82, in Value
    raise ValueError('Enum {} has no value defined for name {!r}'.format(
ValueError: Enum ErrorCode has no value defined for name '403'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Is your REST API token still valid?

**Comment by MinuraPunchihewa** [comment]
@BenWilson2 Yes, I generated a new one today.

**Comment by BenWilson2** [comment]
Did you restart your computer to ensure that cached references to that key aren't pushing the old key through DBConnect?

**Comment by MinuraPunchihewa** [comment]
@BenWilson2 I just tried restarting my computer and running it again. No change.

**Comment by BenWilson2** [comment]
Since you are a Databricks customer and this issue is related to DBConnect (and perhaps your account), could you contact your support team (or file a support ticket with Databricks) for resolution and assistance in troubleshooting?

**Comment by dosalwaryogi** [comment]
Hi @MinuraPunchihewa, 
I am also facing same issue. 
Mlflow version = 1.21.0

Any suggestions?
Thank you

**Comment by the-guish** [comment]
I had the same issue today, because I got a wrong token.

I'm using only the MLFlow 2.1.1 cli from the terminal, connecting to a remote tracking server from Databricks.

Any command with the CLI fails with this stack:
```
    return self.store.search_experiments(
  File "/Users/luis/extra_code/mlops/mlserver-trial/venv/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 75, in search_experiments
    response_proto = self._call_endpoint(SearchExperiments, req_body)
  File "/Users/luis/extra_code/mlops/mlserver-trial/venv/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/luis/extra_code/mlops/mlserver-trial/venv/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 283, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/luis/extra_code/mlops/mlserver-trial/venv/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
  File "/Users/luis/extra_code/mlops/mlserver-trial/venv/lib/python3.9/site-packages/mlflow/exceptions.py", line 103, in __init__
    super().__init__(message, error_code=ErrorCode.Value(error_code))
  File "/Users/luis/extra_code/mlops/mlserver-trial/venv/lib/python3.9/site-packages/google/protobuf/internal/enum_type_wrapper.py", line 82, in Value
    raise ValueError('Enum {} has no value defined for name {!r}'.format(
ValueError: Enum ErrorCode has no value defined for name '403'
```

adding debug I see the server response has status 403 and body 
```json
{"error_code":"403","message":"Invalid access token."}
```

The path to error is then:
https://github.com/mlflow/mlflow/blob/ffe005c58dd45e4f200bfb5a77aa5273a57ca39d/mlflow/utils/rest_utils.py#L205-L208

as the response can be parsed a RestException is raised:
https://github.com/mlflow/mlflow/blob/ffe005c58dd45e4f200bfb5a77aa5273a57ca39d/mlflow/exceptions.py#L93-L103

That error code dictionary comes from:
https://github.com/mlflow/mlflow/blob/ffe005c58dd45e4f200bfb5a77aa5273a57ca39d/mlflow/protos/databricks_pb2.py#L20-L33

That seems to respond to other API codes, that are not http status.

Fixing this will allow cli users to have a better experience, by being able to visualize the error, could be invalid token or any other non 200 status code.

I can work on it but doesn't know how those error codes will fit together with standard http status codes.

Any thougths @BenWilson2 @harupy ?

**Comment by BenWilson2** [comment]
To provide a specific error handling message that is much more user friendly, we'd likely want to create a decorator for the main cli entrypoint that catches this Exception and throws with a new message. Thoughts on this, @harupy ?
