### ISSUE TITLE
No such command 'models'

### ISSUE THREAD

**Issue by VishnuMurthyChakka** [mlflow/mlflow#6744]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

Windows 10
- python 3.10.2

### Describe the problem

When I am trying to build API end point for machine learning model using mlflow, it is returning the error message

C:\Users\user\Machine Learning>mlflow models --help
C:\Users\user\anaconda3\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Usage: mlflow [OPTIONS] COMMAND [ARGS]...
Try 'mlflow --help' for help.

Error: No such command 'models'.

### Tracking information

Tracking URI - 'file:///C:/Users/user/Machine%20Learning/mlruns'
Artifact URI: file:///C:/Users/user/Machine%20Learning/mlruns/0/bcc97f32a9804b78923d826da22df42b/artifacts

### Code to reproduce issue

This is not issue with mlflow code. This is related to creating endpoint API for the model. The command line is not working as it could not find submodule 'models'

### Stack trace

C:\Users\user\Machine Learning>mlflow models --help
C:\Users\user\anaconda3\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Usage: mlflow [OPTIONS] COMMAND [ARGS]...
Try 'mlflow --help' for help.

Error: No such command 'models'.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Did you install that library that the stack trace is telling you to install on your system?

**Comment by VishnuMurthyChakka** [comment]
Hi Ben, after resolveing the issue related to mkl-server, I am able to see 'models' as an option for mlflow. Thanks for your help.
