### ISSUE TITLE
[DOC-FIX] Make R installation instructions more clear

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6747]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://www.mlflow.org/docs/latest/R-api.html#details

### Description of proposal (what needs changing)

The instructions are not perfectly clear about the sequence of commands required for installing MLflow on R in the event that a conda environment is not available. 
The documentation on this page should provide examples of:
1. Installing with an available conda environment
2. Installing by manually setting the environment variables of `MLFLOW_PYTHON_BIN` and `MLFLOW_BIN`. 

Related: https://github.com/mlflow/mlflow/issues/6738

**Comment by Ashwin1102** [comment]
Hey @BenWilson2, I am a begginer. Can I work on this issue?

**Comment by darshan8850** [comment]
Hey @BenWilson2, I can work on this issue. Please assigned it to me!

**Comment by harupy** [comment]
@darshan8850 Thanks, assigned!
