### ISSUE TITLE
[FR] Runs page UI links to initiate search when clicked

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6749]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Within a runs page, the fields `user_id` and `lifecycle_stage` should be links that, when clicked, execute a search for runs that match the current run's criteria.

For instance, if I am viewing a run initiated by myself, I should be able to click my user_id which will execute a runs search of all other runs that I have initiated in the experiments page view.

### Motivation

> #### What is the use case for this feature?
Improved UX navigation and ease of use.

> #### Why is this use case valuable to support for MLflow users in general?
It prevents users from having to maintain perform as many actions for common tasks for navigation within the UI.

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?
It is not supported currently.

### Details

Dependent on #6748

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by jaeday** [comment]
Hi guys, I'll be down to pick this issue up if help is still needed :)

**Comment by dbczumar** [comment]
Hi @jaeday, thank you for picking up this issue! Looking forward to your contribution!

**Comment by jaeday** [comment]
@dbczumar I've just created a PR (#7462) for this issue!
