### ISSUE TITLE
Add scheduler

### ISSUE THREAD

**Issue by lastnod** [mlflow/mlflow#675]
I work in a large organisazion and we dont have Infinite resources that is why we have to schedule our jobs. Could we implement a scheduler with customisable queues like LSF spectrum or slurm ?

**Comment by harryprince** [comment]
it sounds airflow is your option.

**Comment by magick93** [comment]
On the MLFlow talk (see https://youtu.be/wb-ZxtIwSTA?t=3759) a person in the audience had a really good question / suggestion regarding scheduling. This would be a cool feature!

**Comment by talgo10** [comment]
@harryprince An abstraction on top of airflow would be great.
It also will solve the current complex solution for multistep-workflow
(https://github.com/mlflow/mlflow/tree/master/examples/multistep_workflow)

**Comment by srinivascreddy** [comment]
Does MLFlow integrate with Airflow? Reading this thread, just about to explore MLFlow for my needs, already big user of AirFlow for data pipelines. @harryprince thoughts?
