### ISSUE TITLE
Add padding to artifact text viewer

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#6757]
Text displayed in the artifact text viewer almost touches the left edge as shown in the screenshot below. Padding should be inserted to make it look nice.

<img width="527" alt="Screen Shot 2022-09-12 at 9 51 25" src="https://user-images.githubusercontent.com/17039389/189556982-5a9cd623-671f-461b-894d-d6cc3a78d9e3.png">

**Comment by RohanBha1** [comment]
Hey could I work on this issue?

**Comment by harupy** [comment]
@RohanBha1 Thanks for the comment!

First, I think you need to set up the dev environment:

https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#javascript-and-ui

**Comment by harupy** [comment]
@RohanBha1 Once the dev environment is setup, you can modify `ShowArtifactTextView.js`:

```diff
diff --git a/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.js b/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.js
index 7ad9985f7..e98338991 100644
--- a/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.js
+++ b/mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.js
@@ -58,6 +58,7 @@ class ShowArtifactTextView extends Component {
         marginTop: '0',
         width: '100%',
         height: '100%',
+        padding: '10px',
       };
       const renderedContent = ShowArtifactTextView.prettifyText(language, this.state.text);
       return (
```

**Comment by harupy** [comment]
@shraddhafalane Would you mind giving @RohanBha1 an opportunity to contribute to OSS?

**Comment by RohanBha1** [comment]
Did @shraddhafalane solve the issue already?

**Comment by harupy** [comment]
@RohanBha1 She did. See https://github.com/mlflow/mlflow/pull/6778.

**Comment by harupy** [comment]
@RohanBha1 If it's ok for you, we can assign you a different issue.

**Comment by RohanBha1** [comment]
Hey, @harupy @shraddhafalane if this issue is already taken care of I do not mind working on any other issues around the same difficulty.

**Comment by harupy** [comment]
@RohanBha1 Understood. I'll find an issue with the same difficulty.
