### ISSUE TITLE
[FR] Add possibility to unwrap python_model from PyFuncModel class

### ISSUE THREAD

**Issue by ikrizanic** [mlflow/mlflow#6794]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

FR could be solved by adding `unwrap(self)` method to `PyFuncModel` class. `unwrap(self)` would return `self._model_impl`, thus providing direct access to the wrapped python model. It could also return `self._model_impl` if user wants that.

### Motivation

> #### What is the use case for this feature?
Users would be able to load their custom python objects by calling `unwrap()` method when using `mlflow.pyfunc.load_model`.

> #### Why is this use case valuable to support for MLflow users in general?
This is valuable because methods such as `save_model, log_model` and `load_model` could still be used, but much more flexibility with custom models would be achieved.
> #### Why is this use case valuable to support for your project(s) or organization?
This is valuable to my projects because we often use custom models and need access to it's custom methods.
> #### Why is it currently difficult to achieve this use case?
The current implementation of `PyFuncModel` class implements only one useful method for interaction with loaded model (`predict(data) -> predictions`). When using a custom python object as a model (while inheriting `mlflow.pyfunc.PythonModel`) it's very limiting to have only one method exposed.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ikrizanic** [comment]
I would also like to mention that I've seen several examples of using predict() method to return python_model, which is a workaround I have also used, this FR would provide a dedicated method for doing just this.

**Comment by skylarbpayne** [comment]
I'd like to understand the needs here a little bit better.

Are these models that you want to use other functions of other supported model flavors? For example, are you logging something like `mlflow.sklearn.log_model` then loading via the pyfunc flavor and you want access to the methods of the underlying sklearn model (or other model flavor)?

My gap in understanding is that pyfunc sort of "unifies" the interface over many types of models -- i.e. it gives a consistent interface to load & score models, regardless of the underlying library/framework used. But if you want direct access to the internals, these are not necessarily the same across model flavors, so it makes me wonder whether the pyfunc flavor is what's desired. Is it possible to just load that model flavor directly and skip using pyfunc flavor entirely?

**Comment by ikrizanic** [comment]
@skylarbpayne Hello, thank you for your interest in this FR.

Custom models which I refer to when talking about unwrapping them could be (and often are) completely custom python classes which I use in inference pipelines.

I understand your concern with pyfunc originally used for "unifying" and now using it just as a wrapper for any custom model, but this option is very useful in workflows where there is a need for storing custom python objects as pickled models. `mlflow.pyfunc` already implements save_model, log_model and load_model in the exact manner it is needed for most of the cases when using python objects, and I have no real need for creating custom flavors in that case.
That's why I still want to use pyfunc, while getting some more freedom in interacting with my objects.
