### ISSUE TITLE
REST API Get Run returns 404, although a run with the specified UUID exists

### ISSUE THREAD

**Issue by nickto** [mlflow/mlflow#680]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 (in Docker)
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.7.0
- **Python version**: 3.6.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**: `requests.get("http://mlflow:5000/2.0/preview/mlflow/runs/get", data={"run_uuid": "a9add735afd94b68925dd83d5ebf963b})`

### Describe the problem
REST API Get Run request returns Error 404 although a run with the specified UUID exists (note that it's the same UUID as in the output of the code provided below):
![run_uuid screenshot](https://user-images.githubusercontent.com/11967792/47784935-7c04d080-dd07-11e8-8d27-1e5a200cece4.png)

### Source code / logs
```python
# Import MLflow and start tracking
import mlflow
import requests

MLFLOW_URL = "http://mlflow:5000"
mlflow.set_tracking_uri(MLFLOW_URL)

# Log sample run
with mlflow.start_run():
    mlflow.log_param("param_name", "param_value")
    mlflow.log_metric("metric_name", 0.5)    

# Access list of experiments

experiments_response = requests.get("http://mlflow:5000/api/2.0/preview/mlflow/experiments/get", data={"experiment_id": 0})

# Check this list, specifically that `run_uuid` is valid
print(experiments_response.json())
# Output:
# {'experiment': {'experiment_id': '0',
#   'name': 'Default',
#   'artifact_location': '/app/mlruns/0',
#   'lifecycle_stage': 'active'},
#  'runs': [{'run_uuid': 'a9add735afd94b68925dd83d5ebf963b',
#    'experiment_id': '0',
#    'name': '',
#    'source_type': 'LOCAL',
#    'source_name': '/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py',
#    'user_id': 'root',
#    'status': 'FINISHED',
#    'start_time': '1540984088610',
#    'end_time': '1540984088802',
#    'artifact_uri': '/app/mlruns/0/a9add735afd94b68925dd83d5ebf963b/artifacts',
#    'lifecycle_stage': 'active'}]}

experiments = experiments_response.json()
run = experiments["runs"][0]
run_response = requests.get("http://mlflow:5000/2.0/preview/mlflow/runs/get", data={"run_uuid": run["run_uuid"]})

print(run_response)
# Output:
# <Response [404]>
```

**Comment by aarondav** [comment]
Two problems with your get request:

- The URI is slightly incorrect, as you need an `/api` prior to `2.0`.
- Instead of passing the parameters as data, for a get request we should use the query string.

So if you change the code to

```python
run_response = requests.get("http://mlflow:5000/api/2.0/preview/mlflow/runs/get?run_uuid=" + run["run_uuid"])
```

then it should work!
