### ISSUE TITLE
[BUG] Tensorflow, Keras autologged models cause UI errors

### ISSUE THREAD

**Issue by JJ11teen** [mlflow/mlflow#6819]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.28.0

### System information

Don't believe this is system specific

### Describe the problem

Autologged models for Tensorflow & Keras specify their default artifact paths as "model", as seen [here](https://github.com/mlflow/mlflow/blob/6eccc69286b7d8b34ce6d34a20bf821e8c69feba/mlflow/keras.py#L734) and [here](https://github.com/mlflow/mlflow/blob/6eccc69286b7d8b34ce6d34a20bf821e8c69feba/mlflow/tensorflow/__init__.py#L1038)

This results in the following directory structure:
![image](https://user-images.githubusercontent.com/1443174/190835782-86973e3c-bdec-4cbe-ba7d-d01516943199.png)
When a user selects the top level `/model` directory, they are presented with the schema of the model and the MLflow model spark & pandas snippets. My understanding is that this information is pulled from the `/model/MLmodel` file.

The issue is that when a user selects the nested `/model/data/model` directory in the UI, it appears mlflow attempts to do the same, and tries to load a `/model/data/model/MLmodel` file. As this file does not exist, it fails, and then the UI then displays: "Couldn't load model information due to an error."
A temporary pop up also appears describing the exact missing file error:
```
INTERNAL_ERROR: The following failures occurred while downloading one or more artifacts from <artifact_uri>: {'model/data/model/MLmodel': "ResourceNotFoundError('The specified blob does not exist.<redacted>)"}
```
Note I have redacted some specific request details/uris from the above.

Expected behaviour is that as `/model/data/model` is just a directory, the default "select a file to preview" UI should be shown.
![image](https://user-images.githubusercontent.com/1443174/190835919-a8fb6305-330a-4a3d-80a9-4cc9c25b713f.png)

### Code to reproduce issue

`mlflow.tensorflow.autolog()` and any keras model & fit call within an mlflow run

### Stack trace

NA

### Other info / logs

I have manually copied the MLmodel file from `/model/MLmodel` to `/model/data/model/MLmodel` and the UI then shows the schema & code snippet UI when either the root `/model` directory or the `/model/data/model` directory is selected.

I have also turned off auto model logging, and instead used `mlflow.keras.log_model` and specified an `artifact_path` other than "model", and that also seems to fix the issue. I have only called out keras/tensorflow as they are just the two I use, I suspect this may be an issue for all autologgers that have `artifact_path="model"`.

So at this point I am not sure if it makes more sense to classify the bug as "autologged models use an `artifact_path` that results in UI errors", or "UI makes incorrect assumptions about directory structure/names that results in UI errors" 

Also worth noting I am using a custom artifact_repository plugin, but at this point I believe the issue is within mlflow core.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @JJ11teen can you validate this behavior outside of your plugin and confirm that you see the exact same issue with 'vanilla MLflow' ? If so, we would be happy to review a fix to (either the JS code or the underlying artifact repository code) that addresses the path parsing issue that appears to be happening.

**Comment by harupy** [comment]
@JJ11teen @BenWilson2 I was able to reproduce the issue in MLflow 1.28.0:

```python
import mlflow
from sklearn.linear_model import LogisticRegression

with mlflow.start_run():
    mlflow.sklearn.log_model(LogisticRegression(), "model")
    mlflow.log_artifact(__file__, "model/data/model")
```

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/6753 erased this issue but introduced a new issue.
