### ISSUE TITLE
[BUG] using git tags in `mlflow run --version TAG` fails

### ISSUE THREAD

**Issue by graelo** [mlflow/mlflow#6821]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 12.4
- **Python version**: 3.9.13
- **yarn version, if running the dev UI**: None

### Describe the problem

First, thanks a lot for this project.

In the command `mlflow run --version VVV https://...`, the term _version_ looks like you could use a git tag, and a few versions ago (I think around 1.14) this used to work.

However, in recent versions such as 1.27 and 1.28.0, using an existing git tag such as `1.0.0` just fails with:

```
2022/09/17 19:16:52 ERROR mlflow.cli: === Unable to checkout version '1.0.0' of git repo https://github.com/org/repo- please ensure that the version exists in the repo. Error: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 1.0.0
  stderr: 'error: pathspec '1.0.0' did not match any file(s) known to git' ===
```

The command only works with branch names or commit SHAs. Is that the desired behavior? The docs for this `--version` argument mention "Git commit references", so it looks like tags should be accepted.

Ideally, could you please reinstate this feature?
Thanks!

### Code to reproduce issue

```console
$ pip install mlflow==1.28.0
$ mlflow run git@github.com:graelo/mlflow-example.git -v 1.0.0
2022/09/17 19:26:55 INFO mlflow.projects.utils: === Fetching project from git@github.com:graelo/mlflow-example.git into /var/folders/hb/9_9_kvm96fb7w3zrqwzp3kkh0000gn/T/tmpesd_pz9h ===
2022/09/17 19:26:57 ERROR mlflow.cli: === Unable to checkout version '1.0.0' of git repo git@github.com:graelo/mlflow-example.git- please ensure that the version exists in the repo. Error: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 1.0.0
  stderr: 'error: pathspec '1.0.0' did not match any file(s) known to git' ===
```

### Stack trace

```console
$ mlflow run git@github.com:graelo/mlflow-example.git -v 1.0.0
2022/09/17 19:26:55 INFO mlflow.projects.utils: === Fetching project from git@github.com:graelo/mlflow-example.git into /var/folders/hb/9_9_kvm96fb7w3zrqwzp3kkh0000gn/T/tmpesd_pz9h ===
2022/09/17 19:26:57 ERROR mlflow.cli: === Unable to checkout version '1.0.0' of git repo git@github.com:graelo/mlflow-example.git- please ensure that the version exists in the repo. Error: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 1.0.0
  stderr: 'error: pathspec '1.0.0' did not match any file(s) known to git' ===
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
It looks like to make this work with tags will need a modification to https://github.com/mlflow/mlflow/blob/5ddfe9a1b48e065540094d83125040d3273c48fa/mlflow/projects/utils.py#L194-L235 to support prefacing a tag with `tag/<tag_id>` when submitted with the `-v` option to the projects cli run command. 

Marking this as open for community engagement.

**Comment by graelo** [comment]
Thanks for your insight!

**Comment by BenWilson2** [comment]
Let me know if you're going to work on the PR :)

**Comment by graelo** [comment]
Yes, I just don't have the bandwidth right now, but I will let you know if I work on it!

**Comment by AvikantSrivastava** [comment]
Hey @BenWilson2 @graelo if no one is working on this issue, can I work on it?

**Comment by graelo** [comment]
Sure, i think that would be great, thanks

**Comment by AvikantSrivastava** [comment]
@graelo @BenWilson2 
looks like we don’t fetch tags when we do a git fetch here
https://github.com/mlflow/mlflow/blob/5ddfe9a1b48e065540094d83125040d3273c48fa/mlflow/projects/utils.py#L211


https://stackoverflow.com/a/17356120

**Comment by AvikantSrivastava** [comment]
@BenWilson2 @graelo I have raise a PR for the fix https://github.com/mlflow/mlflow/pull/7043

can you take a look?
