### ISSUE TITLE
[BUG] Docker container built using mlflow build-docker throws '413 Request Entity Too Large' on inferencing data above 5m.

### ISSUE THREAD

**Issue by chaturvedakash** [mlflow/mlflow#6825]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.6 LTS (Bionic Beaver)
- **Python version**: Python 3.8.5
- **yarn version, if running the dev UI**:None

### Describe the problem

Docker container built using mlflow build-docker throws '413 Request Entity Too Large' on inferencing data above 5m. The issue is due to  'client_max_body_size 5m;' set by default in the nginx.conf. This can be solved by increasing the 'client_max_body_size' to 100m, so that nginx can process inferencing medium/large datasets.

### Code to reproduce issue

***
Pass in inferencing data above 5m to the inferencing (/invocations) endpoint in the dockercontainer built using mlflow build-docker command.

### Stack trace

'<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor="white">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n'

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @chaturvedakash thank you for agreeing to work on a PR for this. We'll eagerly review it once it is submitted. Feel free to reach out with any questions!
