### ISSUE TITLE
Support for storing metadata in database instead of file store

### ISSUE THREAD

**Issue by aneja-rahul** [mlflow/mlflow#685]
Hello,

We are planning to use mlflow to track our experiments in production. Instead of storing metadata in filestore , we want to use database as the storage. Is there any work currently going on, where I can contribute?

Thanks,
Rahul Aneja

**Comment by aarondav** [comment]
This definitely makes sense. I think the current thought is to use a library like SQLAlchemy to create a store that can run on top of a variety of databases (sqlite, postgres, mysql, etc.), and it definitely makes sense!

So far the only implementation work I've seen is here: #640, although this work is specific to DynamoDB.

**Comment by EvanZ** [comment]
Ok, it seems my hunch is correct that there currently is no option for database storage. That seems awfully half-baked to me if true.

**Comment by mdgoldberg** [comment]
I also would love to see some sort of DB backend, PostgreSQL would work well. I'm just getting into MLFlow, but am very concerned about issues like https://github.com/mlflow/mlflow/issues/627

It also becomes much easier to scale MLFlow and add redundancy if multiple instances don't need to share the same persistent location on disk. Please consider it!

**Comment by jmrr** [comment]
#756 was merged providing SQLAlchemy-compatible database backends support and #868 will get released soon adding docs for this support.

I guess this could be closed then? @mparkhe @tomasatdatabricks

**Comment by Seanspt** [comment]
great to have v0.9 relaesed.

I'm wandering if there is any tool to migration file store data into a database store.

**Comment by bnekolny** [comment]
@Seanspt I wrote a script for my migration, feel free to use, comment, etc.
https://gist.github.com/bnekolny/8ec96faa0d57913eea6bb7848c06b912

**Comment by elgalu** [comment]
This can be closed as fixed via v0.9.0 right?

**Comment by andrewmchen** [comment]
Yup. I will close this issue.

**Comment by weldpua2008** [comment]
> @Seanspt I wrote a script for my migration, feel free to use, comment, etc.
> https://gist.github.com/bnekolny/8ec96faa0d57913eea6bb7848c06b912

I'd recently started the migration 0.8.1 -> 1.8.0 and wrote the following script based on the above https://gist.github.com/weldpua2008/7f0c4644d247bd0fc7ba9a83c2d337d5
