### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Yarden234** [mlflow/mlflow#6857]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

Hello, I want to filter in the UI al rows in experiment that the numeric value in column is null.
<img width="1801" alt="image" src="https://user-images.githubusercontent.com/93072519/191764693-a5177d63-9659-4f13-b865-09831f7ab646.png">
for example all rows that the metrics.auc is null.
But I can't find the right syntax for that.
Thanks.

### Steps to reproduce the bug

metrics.auc is null
metrics.auc = 'null'

**Comment by BenWilson2** [comment]
Hi @Yarden234 , this isn't a bug. This functionality has never been supported. 
For a syntax guide and a listing of allowable operations for the search runs functionality within the UI, please see: https://www.mlflow.org/docs/latest/search-runs.html
If you'd like to get runs where you've failed to log metrics, I recommend using the `search_experiments` API and parsing the output with data manipulation operations.
