### ISSUE TITLE
[FR] Enable users to search for runs by run ID

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#6867]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Extend the search filter syntax for `mlflow.search_runs()` to support two forms of search by Run ID:

1. Search for a single run by ID: `attributes.run_id = 'ab204ab19ef64d2eb2af6138c16584d0'`.

2. Search for multiple runs by ID: `attributes.run_id IN ('ab204ab19ef64d2eb2af6138c16584d0', '301d0343282a4df882fb56019ac12c2e', ...)`.

### Motivation

> #### What is the use case for this feature?

Users often want to retrieve a specific run or group of runs. Right now, they have to use the GetRun API to do this, which doesn't support batching.

> #### Why is this use case valuable to support for MLflow users in general?

^

> #### Why is this use case valuable to support for your project(s) or organization?

^

> #### Why is it currently difficult to achieve this use case?

There aren't any batch APIs for fetching runs

### Details

1. We can implement single-run search by adding the `@searchable_attribute` decorator to `RunInfo.run_id` here: https://github.com/mlflow/mlflow/blob/fa96efefc6f415d39038ce489aaf55217c6018af/mlflow/entities/run_info.py#L95, and we can add tests here: https://github.com/mlflow/mlflow/blob/master/tests/utils/test_search_utils.py.

2. We can implement multi-run search by adapting the support offered by model version search (see https://github.com/mlflow/mlflow/blob/fa96efefc6f415d39038ce489aaf55217c6018af/mlflow/utils/search_utils.py#L51 / https://github.com/mlflow/mlflow/blob/fa96efefc6f415d39038ce489aaf55217c6018af/mlflow/utils/search_utils.py#L891-L903) to MLflow Runs search. We can add tests here: https://github.com/mlflow/mlflow/blob/master/tests/utils/test_search_utils.py.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by av-maslov** [comment]
Hello, I would like to work on it

**Comment by alexacole** [comment]
Hello, can I try to work on this issue

**Comment by dbczumar** [comment]
@alexacole Fantastic - of course! I've assigned the issue to you. Thank you in advance for your contribution, and let me know if you have any questions!

**Comment by alexacole** [comment]
Hello, would you mind clarifying detail 2. regarding adapting it to mlflows run search? Am I simply modifying line 51 to use the potential mlflows run search function from the current model version search?

**Comment by dbczumar** [comment]
> @dbczumar Hello, would you mind clarifying detail 2. regarding adapting it to mlflows run search? Am I simply modifying line 51 to use the potential mlflows run search function from the current model version search?

Hi @alexacole , apologies for the delay. We can start with 1.  initially, since it's substantially simpler than 2., and we can file a separate PR for 2. later.

Regarding 2., we need to adjust the comparator validation logic for runs search to indicate the `IN` is supported: https://github.com/mlflow/mlflow/blob/cdfc3bb5fdd63d701156d3e69a6aacf417bc278a/mlflow/utils/search_utils.py#L699 (for a similar modification in model version search, see: https://github.com/mlflow/mlflow/blob/fa96efefc6f415d39038ce489aaf55217c6018af/mlflow/utils/search_utils.py#L924).

We then need to update https://github.com/mlflow/mlflow/blob/72cba73bf83cb32fe586d9fc4a777fc1899cfcb0/mlflow/store/tracking/sqlalchemy_store.py#L1238-L1262 to translate the user's `IN` statement to a SQL `IN` query, similar to what is done in https://github.com/mlflow/mlflow/blob/fa96efefc6f415d39038ce489aaf55217c6018af/mlflow/store/model_registry/sqlalchemy_store.py#L441-L446 for model version search.

Please let me know if you have questions! :)

**Comment by alexacole** [comment]
@dbczumar Thank you for the response and I have 1. completed with simply adding the @searchable_attribute decorator. I just need to write the test and then I can move onto 2.

**Comment by dbczumar** [comment]
@alexacole Thank you so much! It looks like @harupy has implemented 2. in https://github.com/mlflow/mlflow/pull/6945/; apologies for the lapse in ownership judgement here. @harupy 's PR doesn't include the test case for 1., so it would be great to get your PR with implementation + test merged for 1., at which point @harupy can rebase. After that, we're happy to help with any additional contributions you'd like to make.

**Comment by alexacole** [comment]
Okay, thank you. I had started working on 2. but I can easily get rid of that code and finish the test for 1. and PR it within an hour maximum if that is alright with you?

**Comment by dbczumar** [comment]
> Okay, thank you. I had started working on 2. but I can easily get rid of that code and finish the test for 1. and PR it within an hour maximum if that is alright with you?

That's perfect! Thanks @alexacole  - no rush here.

**Comment by alexacole** [comment]
@dbczumar submitted the pull request, but having issues linking it to this issue. Also, please review my test as this is honestly my first test written in the python language and I don't feel I did justice with fully checking the single run search. Thank you

**Comment by harupy** [comment]
Closing as completed in #6952.
