### ISSUE TITLE
[FR] Make it easier to find the exact way to search for runName, source name etc.

### ISSUE THREAD

**Issue by hughperkins** [mlflow/mlflow#6869]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Make it easier to find the exact way to search for runName, source name etc. Ideally, provide a mouse-over for the columns on the results table, that gives the method to search for taht thing. eg if you mouse over the 'RunName' column, it will say 'tags.mlflow.runName'.

### Motivation

> #### What is the use case for this feature?

Make it easy to enter queries into the UI

> #### Why is this use case valuable to support for MLflow users in general?

Without being easy to search runs, the UI is much harder to use.

> #### Why is this use case valuable to support for your project(s) or organization?

I need to be able to search runs easily.

> #### Why is it currently difficult to achieve this use case?

Not easy to remember what is the exact thing to query if want to search for run name, duration, etc

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
@hughperkins Thanks for the idea! 
If anyone is interested in working on this, feel free to comment here and we'll work on getting a submitted PR reviewed!

**Comment by ridhimag11** [comment]
Hi @hughperkins I'm a designer working on MLflow. Would you be open to getting on a short call to share your experience using search on MLflow? I'm also working on some design improvements on Search and would love to get your feedback. If you're okay with that, could you sign-up using this [form](https://forms.gle/V4kUfQ1YPB31AatP9) and I will get in touch with you. 

Thanks, 
Ridhima

**Comment by hughperkins** [comment]
Great! Filled in the form. Thank you :)

**Comment by BenWilson2** [comment]
Hi @utkarsh867 thank you for volunteering! Please let me know if you need any help!

**Comment by ridhimag11** [comment]
Hey @utkarsh867 great to know that you're using MLflow often for your work. I'm a UX Designer on MLflow and would love t to chat with you to learn more about your experience using MLflow. If this is something that's interesting to you, could you fill out this [form](https://forms.gle/V4kUfQ1YPB31AatP9) and I'll get in touch with you?

**Comment by utkarsh867** [comment]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/19630580/194067384-adb5d05a-0108-4312-8f1e-0d3208a7fa6a.png">

@BenWilson2 @hughperkins I wonder if something like this is acceptable?

**Comment by hughperkins** [comment]
That looks great :)

**Comment by utkarsh867** [comment]
Will make a PR now :)

**Comment by hughperkins** [comment]
Awesome :)

**Comment by BenWilson2** [comment]
note that `run_name` is now a top-level attribute for run info. While `run.data.tags.get('mlflow.runName')` will still be supported for backwards compatibility, `run.info.run_name` should be the recommended hint.

**Comment by utkarsh867** [comment]
> note that `run_name` is now a top-level attribute for run info. While `run.data.tags.get('mlflow.runName')` will still be supported for backwards compatibility, `run.info.run_name` should be the recommended hint.

Ah that is interesting! Let me see if I can find an approach to do that.

**Comment by hughperkins** [comment]
I see this is working in 1.30.0. Thank you :)
<img width="291" alt="Screen Shot 2022-10-30 at 3 49 27 PM" src="https://user-images.githubusercontent.com/123560/198898651-918800c2-2bbc-45e2-a199-de9953ababfe.png">
