### ISSUE TITLE
[BUG] `mlflow model serve` not working in Docker

### ISSUE THREAD

**Issue by ZiChuanBuXiu** [mlflow/mlflow#6904]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.29

### System information

- **OS Platform and Distribution**: MacOS Monterey 12.6
- **Python version**: 3.8

### Describe the problem

`mlflow model serve` not working in Docker run. No response received when calling the endpoint.

### Code to reproduce issue

1. Build docker image `{image_name}` with `Dockerfile` which downloads model artifact and serve with port `5000`

```Dockerfile
FROM python:3.8 as base

RUN pip install mlflow==1.29

RUN --mount=type=secret,id=databricks_token \
    MLFLOW_TRACKING_URI=databricks \
    DATABRICKS_HOST=https://??? \
    DATABRICKS_TOKEN="$(cat /run/secrets/databricks_token)" \
    mlflow artifacts download -r ??? -a model -d /model_run


ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh
RUN conda --version

RUN mlflow models prepare-env -m /model_run/model

EXPOSE 5000

CMD mlflow models serve -m /model_run/model -p 5000
```

2. Then run Docker image with `docker run -it -p 5000:5000 {image_name} `

3. Try invoke endpoint with 
```curl
curl --location --request POST 'http://0.0.0.0:5000/invocations' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "f1": 0,
        "f2": 0
    }
]'
```
4. Receive error response `curl: (52) Empty reply from server` 

### Stack trace

No stack trace available

### Other info / logs

Log is shown as below, no additional log appears when calling the endpoint
```
2022/09/27 17:24:43 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2022/09/27 17:24:44 INFO mlflow.utils.conda: Conda environment mlflow-f2cbeeb60fee9d352bdab1e4130447dbc86cb3eb already exists.
2022/09/27 17:24:44 INFO mlflow.pyfunc.backend: === Running command 'source activate mlflow-f2cbeeb60fee9d352bdab1e4130447dbc86cb3eb 1>&2 && exec gunicorn --timeout=60 -b 127.0.0.1:5000 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app'
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[2022-09-27 17:24:45 +1000] [23] [INFO] Starting gunicorn 20.1.0
[2022-09-27 17:24:45 +1000] [23] [INFO] Listening at: http://127.0.0.1:5000 (23)
[2022-09-27 17:24:45 +1000] [23] [INFO] Using worker: sync
[2022-09-27 17:24:45 +1000] [31] [INFO] Booting worker with pid: 31
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
1. can you ping the server?
2. could you attempt to pass curl request like this:
```bash
curl http://127.0.0.1:5000/invocations -H 'Content-Type: application/json; format=pandas-records' -d '[
    {
        "f1": 0,
        "f2": 0
    }
]'
```
and see what the responses are in both situations?

**Comment by ZiChuanBuXiu** [comment]
> 1. can you ping the server?
> 2. could you attempt to pass curl request like this:
> 
> ```shell
> curl http://127.0.0.1:5000/invocations -H 'Content-Type: application/json; format=pandas-records' -d '[
>     {
>         "f1": 0,
>         "f2": 0
>     }
> ]'
> ```
> 
> and see what the responses are in both situations?

1. Which command to use to ping? 
2. Still get the same `curl: (52) Empty reply from server`.

I managed to run the serve command locally and can call the API successfully, but just not able to serve model inside docker.

**Comment by BenWilson2** [comment]
Are you port forwarding in docker?

**Comment by ZiChuanBuXiu** [comment]
> Are you port forwarding in docker?

Find the root issue, it was that I need to specify the host in the Dockerfile like `CMD mlflow models serve -m /model_run/model -p 5000 -h 0.0.0.0` to accept all traffic rather than only from local machine
