### ISSUE TITLE
Errors when running in Ubuntu on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by andrie** [mlflow/mlflow#691]
### System information
- I'm testing using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
- I installed Ubuntu in WSL
- MLflow installed from source, using [instructions](https://github.com/mlflow/mlflow/tree/master/mlflow/R/mlflow)
- mlflow, version 0.7.0
- Python 3.7.0
- npm version 3.5.2

### Describe the problem

When I run:

```r
library(mlflow)
mlflow_set_experiment("Test")
```

I get: 

```
Error in supervisor_start() :
  processx supervisor was not ready after 5 seconds.
```

**Comment by ankitmathur-db** [comment]
Hi, given the age of this issue, I'm going to go ahead and close this out. Please reproduce with MLFlow 1.1 and file a new issue in case you have a problem!

Thanks for using MLFlow!

**Comment by andrie** [comment]
I have tried again, using MLFlow 1.1.0, but get the same error:

```
Error in supervisor_start() :
  processx supervisor was not ready after 5 seconds.
```
