### ISSUE TITLE
Fix `pylint: disable=dangerous-default-value` in `tests/pipelines/test_train_step.py`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#6914]
Just fix the following code:

https://github.com/mlflow/mlflow/blob/fa96efefc6f415d39038ce489aaf55217c6018af/tests/pipelines/test_train_step.py#L137-L140

to:

```python
def estimator_fn(estimator_params=None):
    from sklearn.linear_model import SGDRegressor 
 
    return SGDRegressor(random_state=42, **(estimator_params or {})) 
```

`{}` is mutable and should not use as a default value for a function argument.

**Comment by av-maslov** [comment]
Hi, I can do it
