### ISSUE TITLE
[FR] Multipart uploading for HTTP Artifact Repository

### ISSUE THREAD

**Issue by danilopeixoto** [mlflow/mlflow#6929]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Implement multipart upload for HTTP Artifact Repository. This will allow users to upload big size files under a more robust service.

### Motivation

> #### What is the use case for this feature?

Use MLflow to proxy big artifacts. Improve the HTTP experience to make it similar to S3, GCS and other stores.

> #### Why is this use case valuable to support for MLflow users in general?

Users will be able to retrieve artifacts with big sizes independent from network or proxy settings.

> #### Why is this use case valuable to support for your project(s) or organization?

MLflow creates a common interface for users independent from artifact store in the backend.
All features provided by `--serve-artifacts` option.
Avoid to store big file in memory.

> #### Why is it currently difficult to achieve this use case?

The file is loaded in memory and sent to server in a single request. Usually large files are broken in parts for uploading.
This helps to build a robust upload service. It's easier to retry the smaller chunks than a big file.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by danilopeixoto** [comment]
**Proposal**

Client:

```python
class HttpArtifactRepository(ArtifactRepository):
    """Stores artifacts in a remote artifact storage using HTTP requests"""

    def _http_upload_file(self, credentials, local_file, endpoint):
        index = 0
        offset = 0
        content_size = os.stat(local_file).st_size

        for chunk in yield_file_in_chunks(local_file, _HTTP_UPLOAD_CHUNK_SIZE):
            offset = index + len(chunk)
            content_range = "bytes %s-%s/%s" % (index, offset - 1, content_size)
            index = offset

            resp = http_request(
                credentials,
                endpoint,
                "PUT",
                files={"file": chunk},
                headers={"Context-Range": content_range}
            )
            augmented_raise_for_status(resp)

    def log_artifact(self, local_file, artifact_path=None):
       verify_artifact_path(artifact_path)

       file_name = os.path.basename(local_file)
       paths = (artifact_path, file_name) if artifact_path else (file_name,)
       endpoint = posixpath.join("/", *paths)
       self._http_upload_file(self._host_creds, local_file, endpoint)

...
```

**Comment by dbczumar** [comment]
Hi @danilopeixoto, this is a great idea! One thing we'll need to figure out before implementation is what the MLflow server should do with the each part of the multi-part upload. Right now, the server writes the content to a local temporary file and then logs it using `ArtifactRepository.log_artifact()`, where the artifact repository is determined by the MLflow server configuration (e.g. S3, Azure Blob Storage, local filesystem): https://github.com/mlflow/mlflow/blob/df327134d1278f98b6142ddaef77295a146aba18/mlflow/server/handlers.py#L1509-L1520.

Do you have a proposal for what the MLflow server should do with each part of a multi-part upload?

**Comment by dbczumar** [comment]
Hi @danilopeixoto, thank you for proposing APIs. The structure makes sense to me. Would you be able to outline how the APIs would be implemented in the existing MLflow server?
