### ISSUE TITLE
Error when serving rfunc model

### ISSUE THREAD

**Issue by lpatruno** [mlflow/mlflow#693]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 9
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.7.0
- **Python version**: 3.7

### Describe the problem
Hi folks. I've run into a bug when trying to serve an R model. I created and saved an R model by running the `examples/r_wine` script. I then serve the model by running
```
mlflow rfunc serve -m mlruns/0/8d5350192e7e4c46bfb73445954374bb/artifacts/model
```

This all works, but I get an error when I try to hit the endpoint.

When I try this command
```
curl -d '[{"fixed acidity": 7, "volatile acidity":0.27, "citric acid":0.36, "residual sugar": 20.7, "chlorides": 0.045, "free sulfur dioxide":45, "total sulfur dioxide":170,"density":1.001,"pH":3,"sulphates":0.45,"alcohol":8.8}]' -H 'Content-Type: application/json' -X POST localhost:5000/invocations
```
I get the following error:
```
Invalid Request.  argument 'x' must be a raw vector
```
I've looked into the `model-serve.R` file and located the following block
```
serve_prediction <- function(json_raw, model) {
  mlflow_verbose_message("Serving prediction: ", json_raw)

  df <- data.frame()
  if (length(json_raw) > 0) {
    df <- jsonlite::fromJSON(
      rawToChar(json_raw),
      simplifyDataFrame = FALSE,
      simplifyMatrix = FALSE
    )
  }

  df <- as.data.frame(df)

  mlflow_predict_flavor(model, df)
}
```
but I'm not really sure what to do about that `raw_toChar` call. Any ideas?

BTW, awesome job on this library! I'm super excited about it.

**Comment by lpatruno** [comment]
Solved the issue. The correct endpoint to call is `localhost:5000/predict` not `localhost:5000/invocations`. Might want to add that to the Deployment section [here](https://github.com/mlflow/mlflow/tree/master/mlflow/R/mlflow).

**Comment by akarsh3007** [comment]
@lpatruno Is` localhost:5000/predict` only for R models? Because serving `python_function` and calling ` localhost:5000/predict`  does not works, but `localhost:5000/invocations` does. 
Also, the documentation is missing this information.

**Comment by lpatruno** [comment]
Interesting @akarsh3007 . I'm not sure, as I only tried it with the `rfunc`.

**Comment by akarsh3007** [comment]
@lpatruno thanks for your reply. I am working on a R model will test it out.

**Comment by akarsh3007** [comment]
@lpatruno Yes `/predict` works for R and `/invocations` works for Python functions respectively.

**Comment by lpatruno** [comment]
Good to know. Thanks @akarsh3007 ! This is catnip for documentation...
