### ISSUE TITLE
Proposal:Add the function returning the result of predict_proba() to Model API

### ISSUE THREAD

**Issue by masa26hiro** [mlflow/mlflow#694]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows10(Docker : Debian GNU/Linux 9)
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**:0.7.0
- **Python version**: 3.7.0

### Describe the problem
 Currently, the serve_model method of mlflow/sklearn.py returns only "model.predict(records)".
I think that there are times when we want to know the classification probability of each class when classifying.
So I suggest adding a function to return "model.predict_proba(records)" results to this method.

Thank you.

**Comment by MichaelMarien** [comment]
Hi,

a quick fix would be to overwrite the "predict" function of your sklearn model with "predict_proba" before saving it. This is a bit hacky though. Not sure what the view of the core dev team is, but if they want to adress this mroe nicely, I'd be happy to pick it up.

**Comment by masa26hiro** [comment]
Hi,

Thanks for your reply.
I used to rewrite predict () into predict_proba () by myself before too. I believe there is a demand for data scientists who wish to use predict_proba ().

**Comment by yassineAlouini** [comment]
I have a similar use case but with another custom function `predict_distribution`. 
For now, I will override the `predict` method during the training but it would be better to offer a way to do it natively. Any help or suggestions are welcome. Thanks in advance. :)

**Comment by smurching** [comment]
Hi all, sorry for the delayed response - this should be possible in MLflow >= 1.0 by using custom Python models ([see the docs](https://www.mlflow.org/docs/latest/models.html#model-customization)), in particular [this example](https://www.mlflow.org/docs/latest/models.html#example-saving-an-xgboost-model-in-mlflow-format) - you can define a wrapper model class that loads the persisted sklearn model & returns the results of `predict_proba`. Please feel free to reopen with any questions!

**Comment by ssimontacchi** [comment]
Hi, can you explain what you mean here in a little more detail? Thanks!

**Comment by skylarbpayne** [comment]
@smurching Coming back to this. This seems like something a lot of folks would find useful. Seems a tad silly to have all users write their own custom wrapper just to change the predict function.

How would you feel about me making a PR to add an optional argument to the sklearn model flavor to specify the "predict" function that should be used? This would be backwards compatible and would avoid the need for everyone to create their own wrapper.

E.g.

```python
mlflow.sklearn.log_model(model, predict_func='predict_proba')
```

How would you feel about something like this :)?

**Comment by ssimontacchi** [comment]
That would be amazing. My workaround has been to save a path to an unwrapped model object and just use that. So yeah — this would be worlds better!

**Comment by skylarbpayne** [comment]
E.g.: https://github.com/mlflow/mlflow/pull/6631 is a simple way to address this need. Happy to iterate on it, but given how lightweight it was to implement it, felt it would be easier to have a concrete solution to critique :)
