### ISSUE TITLE
[FR] batch retrieval for runs

### ISSUE THREAD

**Issue by wamartin-aml** [mlflow/mlflow#6953]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Looking to add something like:
def get_run_batch(run_ids: List[str], max_results: int = 100, order_by: Optional[List[str]] = None, page_token: Optional[str] = None) -> PagedList[Run]

### Motivation

> #### What is the use case for this feature?
This allows users to get the run information for many runs in one network call without needing to come up with special search parameters and without needing to do lots of filtering on the client side.

> #### Why is this use case valuable to support for MLflow users in general?
Users in general create many runs. Being able to pull details for multiple runs as once for comparison purposes is valuable.

> #### Why is this use case valuable to support for your project(s) or organization?
We have users building their own UIs who want to be able to pull information about many runs and models in one view.

> #### Why is it currently difficult to achieve this use case?
To build this view currently, users must make hundreds of network calls to create these views. Otherwise, customers can work around the issue by putting a special tag on runs that will be queried together, but it's hard to know everything that needs to be tagged ahead of time.

### Details

If a new API is undesirable, there are a couple of other options. 

- Functionality could be folded into get_run, which would change its behavior if a list is passed and would need to start taking optional pagination parameters.
- Functionality could be folded into search_runs, which would start taking a list of run_ids as an additional optional filter.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @wamartin-aml, https://github.com/mlflow/mlflow/pull/6945 appears to address this FR by including support for run_id-based search in `searchRuns` with operators `=`, `IN`, and `NOT IN`. We'll have this merged shortly. Cheers!
