### ISSUE TITLE
Issue While Serializing Model When Logging With Mlflow Mleap

### ISSUE THREAD

**Issue by HassanRaza1313** [mlflow/mlflow#6958]
I am facing an issue when logging my model through the mlflow.mleap.log_model function. Below are my following settings:

I created an experiment with the local file path set as the artifact_location argument.

mlflow.create_experiment\
    (
        name="decision_tree",
        artifact_location="file:/D:/Mlflow/artifacts",
        tags={"version":"v1","priority":"p1"},
    )
  
I used the spark model sample code written on the [mlflow mleap](https://www.mlflow.org/docs/latest/python_api/mlflow.mleap.html) page. 

![image](https://user-images.githubusercontent.com/61215448/193506309-2253b26a-d312-4486-a1c0-5a6ac609a2dd.png)

However, when I call the mlflow.mleap method, it raises the following issue:

![image](https://user-images.githubusercontent.com/61215448/193506406-b87855aa-2326-4078-8148-0ef23588f706.png)

I have tried to change the artifact location to different local path files and even HDFS path, but the same issue occurs. Kindly look into this and let me know if it is an issue from my side.

**Comment by dbczumar** [comment]
@HassanRaza1313 Thank you for filing this issue; I've filed https://github.com/mlflow/mlflow/pull/6966 to address it.

**Comment by dbczumar** [comment]
@HassanRaza1313 Apologies for the substantial delay. https://github.com/mlflow/mlflow/pull/6966 has been merged and will be included in the next MLflow release to fix this issue.
