### ISSUE TITLE
Proposal:Add deployment functions for multiple models

### ISSUE THREAD

**Issue by masa26hiro** [mlflow/mlflow#696]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows10(Docker : Debian GNU/Linux 9)
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**:0.7.0
- **Python version**: 3.7.0

### Describe the problem
Currently, in order to provide multiple models, it is necessary to serve each model for each port.
So, I propose the function to specify the model path to execute as an argument to URL.

Thank you.

**Comment by mparkhe** [comment]
Hi @masa26hiro:

Can you give a bit more detail on the use that that requires multiple models deployed in a single container? If memory is not a constraint, one of the ways to do that would be to use [python_function with custom loader](https://mlflow.org/docs/latest/models.html#built-in-deployment-tools) to load in multiple models and use parameter to execute a particular model. However, this will always have memory limitations and put constraint on number, size, and types of models you can pack into a single container.

A scalable way to approach this would be use some load balancing + routing logic to route traffic to appropriate hosts based on model being executed.
