### ISSUE TITLE
[FR] Add batch retrieval of registered models from a list of model versions

### ISSUE THREAD

**Issue by wamartin-aml** [mlflow/mlflow#6964]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Extend search_registered_models or create a new method that allows users to get registered models in a single call from a list of model versions.

### Motivation

> #### What is the use case for this feature?
User has a set of model versions and wants all associated registered models.

> #### Why is this use case valuable to support for MLflow users in general?
Users in general create multiple models. Being able to pull groups of registered models at once is valuable.

> #### Why is this use case valuable to support for your project(s) or organization?
We have customers building their own third-party dashboards, displaying registered models alongside associated run parameters and metrics.

> #### Why is it currently difficult to achieve this use case?
Right now, filling this dashboard in requires a linear number of network calls - the dashboard can get a list of model versions filtered on run IDs, but then has to go through each model version individually to build the list of associated registered models. Some of their customers create many model versions, making this strategy infeasible for a performant user experience.

### Details

It's worth considering adding a `run_id IN (...)` option to the search_registered_models() API, but since run ID isn't directly linked to a registered model, that might be harder to achieve. I'm willing to work on it either way.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @wamartin-aml, thanks for filing this issue! For now, we'd prefer to prioritize https://github.com/mlflow/mlflow/issues/6866 to clearly document the capabilities supported by model version / registered model search, including the ability to fetch model versions by run ID via `run_id IN (...)` syntax. We would also like to introduce support for retrieving a batch of registered models by searching with `name IN (...)`. This way, users could achieve the desired workflow via:

1. Call search_model_versions() to get a list of model versions; extract the `name` attribute from each version
2. Call search_registered_models("name in (<the registered model names from 1>)").

Does this 2-step workflow suffice?

**Comment by wamartin-aml** [comment]
That should work just fine!

**Comment by dbczumar** [comment]
> That should work just fine!

Awesome! Thanks @wamartin-aml !
