### ISSUE TITLE
[BUG] Model version UI page requires MLmodel at top level of artifact directory

### ISSUE THREAD

**Issue by kevingreer** [mlflow/mlflow#6984]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: server is a docker image based on `python:3.8.10`, browser is Google Chrome Version 105.0.5195.125 (Official Build) (arm64) running on macOS Monterey v12.3.1 (M1 chip)
- **Python version**: 3.8.10
- **yarn version, if running the dev UI**: N/A, not running dev UI

### Describe the problem

After upgrading from version 1.26.1 to version 1.28.0, each time we load the model version UI page (/models/.../versions/...), we see the following error at the top of the page:
```
INTERNAL_ERROR: The following failures occurred while downloading one or more artifacts from s3://<path>/artifacts: {'MLmodel': "ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')"}
```
It appears that this is because an `MLmodel` file is required to be at the top level of the directory, but this is not the case for any of our models. Some of our models have only custom artifacts, but even the ones that were packaged by MLflow have the MLmodel file within a `model` directory and not at the top level.

I tried downgrading back to v1.26.1, and the networking error described in the console below is still present, but for some reason the error is not displayed on the UI (which is fine for us, this error does not seem to be affecting anything in the UI). I also tried digging into the MLflow code around this call and everything I've found has not been touched in years. 

### Steps to reproduce the bug

1. Run a v1.28.0 MLflow server with an s3 artifact repo (we were using mysql for model registry and tracking stores, but not sure if that's relevant to this issue)
2. Create a run with no artifacts (you can use the code block below)
3. Navigate to the model version page for your created model `<mlflow_base_url>/#/models/<model_name>/versions/<model_version>`
4. Observe the error in the UI

### Code to generate data required to reproduce the bug

```py
import mlflow
from mlflow.tracking import MlflowClient

tracking_uri = '<your-tracking-uri>'

client = MlflowClient(tracking_uri)
mlflow.set_experiment(experiment_id='<your-experiment-id>')

with mlflow.start_run() as run:
    artifact_uri = run.info.artifact_uri
    run_id = run.info.run_id

model_name = '<your-model-name>'
client.create_registered_model(model_name)
client.create_model_version(model_name, artifact_uri, run_id)
```

### Is the console panel in DevTools showing errors relevant to the bug?

```
GET https://<url>/model-versions/get-artifact?path=MLmodel&name=<model_name>&version=<version_number> 500

"{"error_code": "INTERNAL_ERROR", "message": "The following failures occurred while downloading one or more artifacts from s3://<path>/artifacts: {'MLmodel': \"ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')\"}"}"
```

### Does the network panel in DevTools contain failed requests relevant to the bug?

# Headers:
## General:
Request URL: https://<url>/model-versions/get-artifact?path=MLmodel&name=<model_name>&version=1
Request Method: GET
Status Code: 500 
Remote Address: <ip>
Referrer Policy: strict-origin-when-cross-origin

## Response Headers:
content-length: 308
content-type: application/json
date: Wed, 05 Oct 2022 22:59:30 GMT
strict-transport-security: max-age=15724800; includeSubDomains

## Request Headers:
:authority: <url>
:method: GET
:path: /model-versions/get-artifact?path=MLmodel&name=<model_name>&version=1
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
referer: <url>
sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

# Payload
path: MLmodel
name: <model_name>
version: 1

# Response
{"error_code": "INTERNAL_ERROR", "message": "The following failures occurred while downloading one or more artifacts from s3://<path>/artifacts: {'MLmodel': \"ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')\"}"}

**Comment by harupy** [comment]
I was able to reproduce the issue. It looks like the model-version page assumes that the artifact directory the model version is associated with contains an `MLmodel` file:

https://user-images.githubusercontent.com/17039389/194232852-eefed5c1-95a4-465e-907f-7170a920059e.mov

**Comment by harupy** [comment]
This line throws the error message:

https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/common/utils/ArtifactUtils.js#L40

**Comment by kevingreer** [comment]
Thank you @harupy for taking a look! Glad you were able to reproduce the issue. I can see a few ways to proceed, but I'm not sure which the maintainers would prefer:
1. Just remove that `Utils.logErrorAndNotifyUser(error)` line
2. Add a flag in `getArtifactContent` to not call that line
3. Stop requesting the `MLmodel` file every time the model version page loads. (I'm not sure what is done after the file is fetched. Seems like `parseMlModelFile` is called [here](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/model-registry/components/ModelVersionPage.js#L117), but the function just [returns](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/model-registry/actions.js#L109) some data that is not used).

**Comment by dbczumar** [comment]
@kevingreer @harupy Thank you for your investigation and for proposing some solutions here. The `MLmodel` file is being parsed in order to render the `Schema` section in the UI (the schema is embedded in `MLModel`) - https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/model-registry/components/ModelVersionPage.js#L226. However, you're absolutely correct that this error message reflects an undue assumption that all MLflow Registered Model Versions contain an `MLModel` file. 

@kevingreer I'm inclined to agree with your first suggestion to remove this line: https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/common/utils/ArtifactUtils.js#L40. It should be up to individual components to define behavior for handling absent artifacts. For example, ModelVersionPage already expects `MLModel` to be missing in some cases: https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/model-registry/components/ModelVersionPage.js#L124-L134

@harupy Do you agree that removing https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/common/utils/ArtifactUtils.js#L40 is the best course of action?

**Comment by harupy** [comment]
Can we do `fetch MLmodel if it exists` instead of `always attempts to fetch MLmodel which might not exist`?

pseudo code:

```
const artifacts = list_artifacts_for_this_model_version(...)
if ("MLmodel" in artifacts) {
   const MLmodel = fetchMLmodel(...);
   # do something MLmodel
}
```

**Comment by dbczumar** [comment]
> No, I don't. Can we do `fetch MLmodel if it exists` instead of `always attempt to fetch MLmodel which might not exist`?
> 
> pseudo code:
> 
> ```
> const artifacts = list_artifacts_for_this_model_version(...)
> if ("MLmodel" in artifacts) {
>    const MLmodel = fetchMLmodel(...);
>    # do something MLmodel
> }
> ```

Ideally, this would be nice. However, we don't currently have a public API for listing model version artifacts. 

@kevingreer I discussed this offline with @harupy and the other maintainers. We agree that removing https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/common/utils/ArtifactUtils.js#L40 is the best path forward. Would you be willing to implement this?

**Comment by harupy** [comment]
Instead of removing `Utils.logErrorAndNotifyUser(error);`, can we just log the error as follows?

```diff
diff --git a/mlflow/server/js/src/common/utils/ArtifactUtils.js b/mlflow/server/js/src/common/utils/ArtifactUtils.js
index d16bf74e2..e0c2f7247 100644
--- a/mlflow/server/js/src/common/utils/ArtifactUtils.js
+++ b/mlflow/server/js/src/common/utils/ArtifactUtils.js
@@ -37,7 +37,7 @@ export function getArtifactContent(artifactLocation, isBinary = false) {
         fileReader.readAsText(blob);
       }
     } catch (error) {
-      Utils.logErrorAndNotifyUser(error);
+      Utils.logError(error);
       reject(error);
     }
   });
diff --git a/mlflow/server/js/src/common/utils/Utils.js b/mlflow/server/js/src/common/utils/Utils.js
index e584980e4..566ecf492 100644
--- a/mlflow/server/js/src/common/utils/Utils.js
+++ b/mlflow/server/js/src/common/utils/Utils.js
@@ -925,23 +925,34 @@ class Utils {
     });
   }
 
-  static logErrorAndNotifyUser(
-    // Prevent formatting after edge block removal
-    // prettier-ignore
-    e,
-    passErrorToParentFrame = false,
-  ) {
-    console.error(e);
+  static notifyError(e) {
     if (typeof e === 'string') {
       message.error(e);
     } else if (e instanceof ErrorWrapper) {
       // not all error is wrapped by ErrorWrapper
       message.error(e.renderHttpError());
-      // eslint-disable-next-line no-empty
-    } else {
     }
   }
 
+  static logError(
+    // Prevent formatting after edge block removal
+    // prettier-ignore
+    e,
+    passErrorToParentFrame = false,
+  ) {
+    console.error(e);
+  }
+
+  static logErrorAndNotifyUser(
+    // Prevent formatting after edge block removal
+    // prettier-ignore
+    e,
+    passErrorToParentFrame = false,
+  ) {
+    Utils.logError(e, passErrorToParentFrame);
+    Utils.notifyError(e);
+  }
+
   static logGenericUserFriendlyError(e, intl) {
     const errorMessages = {
       404: intl.formatMessage({
```

cc @sunishsheth2009

**Comment by sunishsheth2009** [comment]
Yes I think if we expect this error and we don't want to throw this and silently just log it in console, then the above solution makes sense.

We ideally don't need to change the utils class, we can directly switch `Utils.logErrorAndNotifyUser(error);` in [ArtifactUtils.js](https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/common/utils/ArtifactUtils.js#L40) with `console.error(error)` rather than creating a separate abstraction for it. What do you think?

**Comment by harupy** [comment]
@sunishsheth2009 Thanks for the comment! 


> in [ArtifactUtils.js](https://github.com/mlflow/mlflow/blob/5add07673760aa4e2659e828c32c49cc5a1596ef/mlflow/server/js/src/common/utils/ArtifactUtils.js#L40) with console.error(error) rather than creating a separate abstraction for it. What do you think?

This sounds good to me :)

**Comment by kevingreer** [comment]
Thanks everyone for the discussion, I would be happy to put up a PR for this change.
