### ISSUE TITLE
[BUG] model can't be registered on MLFLOW

### ISSUE THREAD

**Issue by hahmad2008** [mlflow/mlflow#6994]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

 1.28.0

### System information

- **OS Platform and Distribution**: macOS 12.0
- **Python version**: Python 3.8.13

### Describe the problem

I tried to save and registered the transformer model on **mlflow**, I followed this [example][1], and the model is successfully saved at the Artifact for the current run. However, **it can't be registered to the model registry.** Any idea why?

    import mlflow
    
    mlflow.set_experiment('bert-classification')
    
    with mlflow.start_run():
        mlflow.pyfunc.log_model('classifier', 
                                python_model=BertTextClassifier(), 
                                artifacts=artifacts, 
                                signature=signature,
                                registered_model_name='bert-rating-classification')

**Note: I can registry the artifact model manually from UI, but I need to do it via code.**
  [1]: https://github.com/santiagxf/mlflow-deployments/blob/main/transformer-classifier/bert-for-classification.ipynb

### Code to reproduce issue

    import mlflow
    
    mlflow.set_experiment('bert-classification')
    
    with mlflow.start_run():
        mlflow.pyfunc.log_model('classifier', 
                                python_model=BertTextClassifier(), 
                                artifacts=artifacts, 
                                signature=signature,
                                registered_model_name='bert-rating-classification')

### Stack trace

Only stuck after saving the model and can't end the execution.

```
/Users/myuser/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @hahmad2008, to confirm, are you using a SQL-based storage backend, which is required in order to use the Model Registry? Asking because `mlflow.set_tracking_uri()` doesn't appear to be specified in your code.

If your code is indeed pointing to a SQL-based storage backend, can you include a more complete stacktrace / set of logs prior to the hang?

**Comment by hahmad2008** [comment]
@dbczumar Thanks for your reply. It seems that it is a problem regarding the large-size model, it can't be saved. I noticed that all artifacts were uploaded except the model which has 700MB.  I tried the following, but it still failed. 

`mlflow server --gunicorn-opts "-t 1800"
` from [your solution ](https://github.com/mlflow/mlflow/issues/6331#issuecomment-1197414500)

and this:

`MLFLOW_HTTP_REQUEST_TIMEOUT=4000` is solved from this [PR](https://github.com/mlflow/mlflow/pull/6206).

Still, I got a timeout exception for the model, my connection speed 11Mpbs. 



```
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    mlflow.pyfunc.log_model('model', 
  File "/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 1584, in log_model
    return Model.log(
  File "/lib/python3.8/site-packages/mlflow/models/model.py", line 295, in log
    mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
  File "/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 726, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1001, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 346, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/lib/python3.8/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 40, in log_artifacts
    self.log_artifact(os.path.join(root, f), artifact_dir)
  File "/lib/python3.8/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f, timeout=4000)
  File "/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 163, in http_request
    raise MlflowException("API request to %s failed with exception %s" % (url, e))
mlflow.exceptions.MlflowException: API request to file failed with exception HTTPSConnectionPool(host='url', port=443): Max retries exceeded with url: (Caused by ResponseError('too many 502 error responses'))
```

**Comment by evalkaz** [comment]
+1 we also encountered this problem with [deployment scenario 5](https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access). When trying to send a 100mb size model:
```
HTTPError: 413 Client Error: Request Entity Too Large for url: https://<MLFLOW_URL>/api/2.0/mlflow-artifacts/artifacts/7/7b54ce3c6cb34f5f884ea3bb9dee18e0/artifacts/mysupermodel/data/model/variables/variables.data-00000-of-00001. Response text: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by hahmad2008** [comment]
@dbczumar Thanks. upgrading mlflow to 1.29 solved the problem.

**Comment by hahmad2008** [comment]
@dbczumar  Thanks. upgrading mlflow to 1.29 solved the problem.
