### ISSUE TITLE
    import mlflow.sklearn ModuleNotFoundError: No module named 'mlflow.sklearn'; 'mlflow' is not a package

### ISSUE THREAD

**Issue by shivprasad94** [mlflow/mlflow#6995]
### System information

- Edition	Windows 10 Enterprise, Version 21H2
- mlflow, version 1.29.0
- Python 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)] on win32

### Code to reproduce issue

https://www.mlflow.org/docs/latest/tutorials-and-examples/tutorial.html

### Describe the problem

installed mlflow on my windows machine with

`pip install mlflow`

followed by other dependent library pandas,NumPy,sklearn

Ran a tutorial on the wine quality model from the given link
https://www.mlflow.org/docs/latest/tutorials-and-examples/tutorial.html

I am getting the below error.

```
import mlflow.sklearn
ModuleNotFoundError: No module named 'mlflow.sklearn'; 'mlflow' is not a package
```
I thought it may be some firewall issue, so I tried on my personal system, and it's still the same error.

What could be the mistake I am doing here? or some library-related issues I am facing here?

**Comment by harupy** [comment]
I think you saved the code in a file named `mlflow.py`:

```
> echo "import mlflow.sklearn" > mlflow.py
> python mlflow.py
Traceback (most recent call last):
  File "mlflow.py", line 1, in <module>
    import mlflow.sklearn
  File "/home/haru/Desktop/repositories/mlflow/outputs/mlflow.py", line 1, in <module>
    import mlflow.sklearn
ModuleNotFoundError: No module named 'mlflow.sklearn'; 'mlflow' is not a package
```

**Comment by shivprasad94** [comment]
in my mini conda environment mlfow is not getting detected 
so had to use : https://anaconda.org/conda-forge/mlflow

**Comment by dbczumar** [comment]
Awesome, thanks for the resolution @harupy. I'm going to go ahead and close this issue. @shivprasad94 Feel free to reopen it if an MLflow bug has been identified :)
