### ISSUE TITLE
[BUG] npm install && npm run build unexpected token

### ISSUE THREAD

**Issue by AGrosserHH** [mlflow/mlflow#7003]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.29.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **Python version**: 3.8.12
- **yarn version, if running the dev UI**: 0.32+git

### Describe the problem

when runninng npm install && npm run build I am getting the following error

> @mlflow/mlflow@0.1.0 build /home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js
> craco --max_old_space_size=8192 build

(node:162152) UnhandledPromiseRejectionWarning: /home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/craco.config.js:71
        .filter((oneOf) => oneOf.test?.toString() === /\.css$/.toString())
                                      ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at module.exports.moduleId (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/import-fresh/index.js:32:59)
    at loadJs (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/cosmiconfig/dist/loaders.js:16:18)
    at ExplorerSync.loadFileContentSync (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/cosmiconfig/dist/ExplorerSync.js:84:26)
    at ExplorerSync.createCosmiconfigResultSync (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/cosmiconfig/dist/ExplorerSync.js:89:30)

### Code to reproduce issue

npm install && npm run build

### Stack trace

npm WARN @apideck/better-ajv-errors@0.3.6 requires a peer of ajv@>=8 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@12.0.2 requires a peer of eslint@^4.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of @typescript-eslint/eslint-plugin@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of @typescript-eslint/parser@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of babel-eslint@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint@^7.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-flowtype@^5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.1.1 requires a peer of eslint@>=1.6.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.1.1 requires a peer of webpack@>=2.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN pdfjs-dist@2.1.266 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN radium@0.19.6 requires a peer of react@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-pdf@4.2.0 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-pdf@4.2.0 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-treebeard@2.1.0 requires a peer of react@^15.5.4 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-treebeard@2.1.0 requires a peer of react-dom@^15.5.4 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-promise-middleware@5.0.0 requires a peer of redux@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN velocity-react@1.4.3 requires a peer of react@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN velocity-react@1.4.3 requires a peer of react-dom@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-filter-warnings-plugin@1.2.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@2.0.0 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 27.437s

404 packages are looking for funding
  run `npm fund` for details

> @mlflow/mlflow@0.1.0 build /home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js
> craco --max_old_space_size=8192 build

(node:162152) UnhandledPromiseRejectionWarning: /home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/craco.config.js:71
        .filter((oneOf) => oneOf.test?.toString() === /\.css$/.toString())
                                      ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at module.exports.moduleId (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/import-fresh/index.js:32:59)
    at loadJs (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/cosmiconfig/dist/loaders.js:16:18)
    at ExplorerSync.loadFileContentSync (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/cosmiconfig/dist/ExplorerSync.js:84:26)
    at ExplorerSync.createCosmiconfigResultSync (/home/andi/Programming/Python/Kununu_Scraping/mlflow/mlflow/server/js/node_modules/cosmiconfig/dist/ExplorerSync.js:89:30)
(node:162152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:162152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@AGrosserHH We no longer use `npm`. Please use `yarn`.

**Comment by harupy** [comment]
@AGrosserHH Feel free to reopen the issue if you encounter the same issue with yarn.
