### ISSUE TITLE
[FR] Allow signing all outgoing request using AWS Sig V4

### ISSUE THREAD

**Issue by pdifranc** [mlflow/mlflow#7019]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Add possibility to sign request using [AWS SigV4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html).

This would allow to implement authentication / authorization via shielding the `<MLFLOW_TRACKING_URI>/api` route with an Amazon API Gateway which implements IAM Authorizers. By doing so, you can either:
* use your AWS access key and secret key to sign the request
* (prefferred) use the instance role (if for example running on an EC2 instance, or on the sagemaker maanged infrastructure) and use the `boto3` session, thus temporary credentials automatically handled by AWS.

### Motivation

> #### What is the use case for this feature?

Authentication / Authorization handled with IAM policies when shielding MLflow with an API Gateway

> #### Why is this use case valuable to support for MLflow users in general?

More flexibility to handle authentication / authorization.

> #### Why is this use case valuable to support for your project(s) or organization?

We want to have a fine grained control over who can do what via the APIs

> #### Why is it currently difficult to achieve this use case?

We have been using an nginx reverse proxy with basic auth, but this approach has some limitation, e.g. credential sharing, anyone with the credentials is essentially admin. A plugin is not really possible because to compute all headers for the signature, I need to have the URL that is being requested, which is not available when using the provided plugin like the [one provided](https://github.com/mlflow/mlflow/blob/95793b30c05ebf506b62c0112249b67d0276b2c5/mlflow/tracking/request_header/abstract_request_header_provider.py#L4) to add headers to every outgoing request (unfortunately)

### Details

I have actually implemented this already as part of a bigger sample I wrote to run MLFlow on AWS, which also includes changes to the MLFlow UI to use Amazon Cognito to authenticate. For this specific use case, I am proposing to add a new env variable, e.g. `MLFLOW_TRACKING_AWS_SIGV4` in the similar way `MLFLOW_TRACKING_USERNAME`, `MLFLOW_TRACKING_PASSWORD`, and `MLFLOW_TRACKING_TOKEN` have been implemented.
 Details of the whole architecture and how this fits can be found [here](https://github.com/pdifranc/sagemaker-studio-mlflow-integration#architecture).

The changes for this pull request can be found [here](https://github.com/pdifranc/mlflow/commit/2d01bd0d9c638cfb49bb05e916e992f82bc38215)

For the MLFlow UI I would open a different feature request to keep it simpler

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @pdifranc, thank you for filing this feature request. The motivation makes perfect sense, and the proposed implementation is great. One minor ask: can we add the new  `MLFLOW_TRACKING_AWS_SIGV4` environment variable to `mlflow.environment_variables` so that it will appear in the docs here?: https://mlflow.org/docs/latest/python_api/mlflow.environment_variables.html

**Comment by pdifranc** [comment]
I have written unit tests too (I havent written a unit test in python in ages :D, I hope they it is enough)
Since I am using a library, I was wondering where exactly I should have placed the dependency. I have placed it in `extras` but maybe there is a better place.
Any further feedback would be appreciated
