### ISSUE TITLE
Recommended handling of I/O for pyfunc?

### ISSUE THREAD

**Issue by colebaileygit** [mlflow/mlflow#702]
I'm developing a pytorch model that take multi-dimensional data (Currently 3D data, 4D if considering batch processing)

Currently, I have two options for exporting models logged using the `mlflow.pytorch` package:
A) Export pytorch model directly via `mlflow.pytorch.load_model`

This requires me to duplicate code for preprocessing. For now I can embed this into my model class and handle preprocessing through my own code. 

In my case, this means adding a new `predict` function to my model class, which accepts a URL parameter, reads the file, converts the file to features (3D numpy data), packs this into a Tensor, and finally calls the native `forward` method of pytorch.

B) Export function via `mlflow.pyfunc.load_pyfunc`

This function seems to be unusable for my use-case. The model requires a dataframe as input, but I cannot easily embed a 3D or 4D tensor as a dataframe. Alternatively, it may be advantageous to use URLs as inputs, and embed pre-processing logic as indicated above. However, I cannot find a recommended way of handling this type of issue.

I have a suitable work-around using native pytorch, but it seems pyfunc integration is not adaptable for this use-case. 

Are there any recommended methods to overcome this type of issue? Do you have any plans to further streamline model packaging with easily configurable pre-processing steps?

**Comment by dbczumar** [comment]
Hi @colebaileygit. We're actively thinking about how to make it easier to embed pre/postprocessing logic into models.

Currently, our recommendation is to use the [mlflow.pyfunc.save_model](https://github.com/mlflow/mlflow/issues/695) method to store custom preprocessing and model inference code. Was this the method you were trying to use?

Regarding representing high-dimensional Tensors as Pandas DataFrames for inference with `pyfunc` models, have you tried using the Pandas `MultiIndex` feature documented here: https://pandas.pydata.org/pandas-docs/stable/advanced.html#multiindex-advanced-indexing ?

**Comment by colebaileygit** [comment]
Thanks for sharing these best practices, I'll look into it. 

Since I'm using pytorch, I saved the model directly using `mlflow.pytorch` instead of `mlflow.pyfunc`. It's good to know about these different solutions, and I'm sure moving forward things can be streamlined a bit or at least have well-documented best practices.

It seems I'll need to commit to a slightly different solution if I plan to deploy my model using `mlflow.pyfunc` vs `mlflow.pytorch` - however at this stage I'm not sure which will be more appropriate, hence the confusion.

**Comment by ssYkse** [comment]
Hi.
Any news on this front? I have the exact same problem/situation infront of me. I am currently creating a seminar on MLFlow for collegues and would like a clean workflow.

In particular, I am using MNIST to build a model - I will use a preprocessing which normalizes the images. Finally I want to host a mlflow server which takes as input an image of arbitary size (which I will draw with paint), send it to the server via curl (or a quick script), and recieve a classification.

How can I package the preprocessing into the final mlflow model which is being served?

**Comment by kimballh** [comment]
I have the same issue as @ssYkse , particularly when serving the model. Doesn't really make a lot of sense to use MLflow to serve a pytorch model which takes images as an input when the input is only allowed to be a 2D json serialized pandas dataframe.

**Comment by mparkhe** [comment]
Recommended practice to higher dimensional inputs to encode as byte strings within a single dataframe column. flatten and then base64 encode the inputs on the client side. Scoring function needs to base64 decode and reshape to required dims before passing to models.

Similar example: https://github.com/mlflow/mlflow/tree/master/examples/flower_classifier
