### ISSUE TITLE
[FR] Allowing changing the Keras serialization format when using `mlflow.keras.autolog()`

### ISSUE THREAD

**Issue by balvisio** [mlflow/mlflow#7024]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Currently, it is not possible to change the serialization format of the Keras models (tf) to HDF% when using the `mlflow.keras.autolog()`. It would be great if this could be configured. One way could be for `autolog()` to take a `kwargs` that is passed to inner functions so that serialization configuration can be set when using `autolog()` 

### Motivation

> #### What is the use case for this feature?

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @balvisio, thank you for your feature request. I think that introducing a `save_format` argument to `mlflow.tensorflow.autolog()` makes sense to me, which may be slightly easier to implement and easier for users to reason about than generic **kwargs for `mlflow.tensorflow.autolog()`. We would be very excited to review a pull request that implements this capability.

**Comment by balvisio** [comment]
Thanks @dbczumar. Will work in the PR in the coming weeks.

**Comment by balvisio** [comment]
@dbczumar I created the PR: https://github.com/mlflow/mlflow/pull/7123. I only added the param for the `keras` flavor only since it looks likethat for `tensorflow` it is more designed for the `SavedFormat` format only.
