### ISSUE TITLE
[FR] Metrics plot if getting too small when metric names are long

### ISSUE THREAD

**Issue by jlmeunier** [mlflow/mlflow#7045]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

I'm plotting 6 metrics, whose names are relatively long, e.g. "medical.valid.en-de.valid.loss"
So the textbox named "Y-axis is very large, and the area where the plot is actually done becomes very narrow. 
So the plot of teh metrics is not really readable.
This is an issue with the layout of the page, I think.

### Motivation

> #### What is the use case for this feature?
Plotting several metrics
> #### Why is this use case valuable to support for MLflow users in general?
The plot is the most important part on this page, so the page layout should maybe priviledge it.
> #### Why is this use case valuable to support for your project(s) or organization?
Daily use currently. And more colleagues coming to it. :-)
> #### Why is it currently difficult to achieve this use case?
<img width="1463" alt="Screenshot 2022-10-13 at 15 06 40" src="https://user-images.githubusercontent.com/15045456/195608528-d97ffc67-5ece-44a8-a67b-3f57989bc3dc.png">

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@jlmeunier Thanks for reporting the issue. I will take a look today.

**Comment by harupy** [comment]
Code to create example data:

```python
import uuid
import mlflow

with mlflow.start_run():
    metrics = {uuid.uuid4().hex: i for i in range(10)}
    mlflow.log_metrics(metrics, step=0)
    mlflow.log_metrics(metrics, step=1)

```
