### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adeepak7** [mlflow/mlflow#7062]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
- **Python version**: 3.6.5
- **yarn version, if running the dev UI**:

### Describe the problem

When we use set_registered_model_tag() method and the value of the tag is Chinese (or non English), we get the following exception:

`mlflow.exceptions.MlflowException: API request to http://0.0.0.0:8000/api/2.0/preview/mlflow/registered-models/set-tag failed with exception HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /api/2.0/preview/mlflow/registered-models/set-tag (Caused by ResponseError('too many 500 error responses',))`

Our code snippet for which we get the above exception:
`mlflow_client.set_registered_model_tag(name=model_id, key='name', value='中文菜单')`

Potential cause of it:

The function `set_registered_model_tag()` method inside `mlflow.store.model_registry.rest_store.RestStore` uses `message_to_json()` method.

Now `message_to_json()` uses `json.loads()` without setting the encoding scheme as follows:

` json_dict_with_int64_as_str = json.loads(
        MessageToJson(message, preserving_proto_field_name=True))`

This might be the potential reason of why Chinese or non-English strings are failing while setting the values of tags.

### Tracking information

MLflow version - 1.28.0
Tracking URI: localhost:8000
Artifact URI: Our own aws S3 bucket (private)

### Code to reproduce issue

mlflow_client = MlflowClient()
mlflow_client.set_registered_model_tag(name=model_id, key='name', value='中文菜单')

### Stack trace

`mlflow.exceptions.MlflowException: API request to http://0.0.0.0:8000/api/2.0/preview/mlflow/registered-models/set-tag failed with exception HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /api/2.0/preview/mlflow/registered-models/set-tag (Caused by ResponseError('too many 500 error responses',))`

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [X] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@adeepak7 I ran the following code and it worked:

```python
import mlflow
import uuid

mlflow_client = mlflow.MlflowClient("http://localhost:5000")
name = uuid.uuid4().hex
mlflow_client.create_registered_model(name)
mlflow_client.set_registered_model_tag(name=name, key=uuid.uuid4().hex, value="中文菜单")
```

Can you check the tracking server log?

**Comment by adeepak7** [comment]
@harupy unfortunately and surprisingly I didn’t find any error in the tracking sever logs even at debug level.

Also, thanks for the prompt response 🙏

**Comment by adeepak7** [comment]
@harupy once more thing- the same code worked on Mac OS, but not on Ubuntu

**Comment by harupy** [comment]
Strange. `mlflow_client.set_registered_model_tag(name=name, key=uuid.uuid4().hex, value="english")` work?

**Comment by adeepak7** [comment]
@harupy yes, the English values work

**Comment by harupy** [comment]
Can you try running this code?

```python
import mlflow
import uuid

mlflow_client = mlflow.MlflowClient("sqlite:///mlruns.db")
name = uuid.uuid4().hex
mlflow_client.create_registered_model(name)
mlflow_client.set_registered_model_tag(name=name, key=uuid.uuid4().hex, value="中文菜单")
```

**Comment by harupy** [comment]
@adeepak7 

> the same code worked on Mac OS, but not on Ubuntu

Can you check what's different (e.g. python, version, mlflow version, protobuf version)?

**Comment by harupy** [comment]
> unfortunately and surprisingly I didn’t find any error in the tracking sever logs even at debug level.

The tracking sever logs look like this?

<img width="722" alt="image" src="https://user-images.githubusercontent.com/17039389/196102265-a917c17b-a312-4298-9349-63e99b81c173.png">

**Comment by harupy** [comment]
@adeepak7 Any updates?

**Comment by harupy** [comment]
@adeepak7 Feel free to reopen the issue if it still persists.
