### ISSUE TITLE
MLFlow Tracking Server Outside Databricks

### ISSUE THREAD

**Issue by debanshu-mutt** [mlflow/mlflow#7075]
### Discussed in https://github.com/mlflow/mlflow/discussions/7074

<div type='discussions-op-text'>

<sup>Originally posted by **debanshu-mutt** October 17, 2022</sup>
Hi, so I have been trying to access Mlflow tracking server outside of databricks following this documentation 
https://docs.databricks.com/mlflow/access-hosted-tracking-server.html#step-3-configure-the-mlflow-cli
The authorization is done but when I try to create a new experiment or call an old experiment file 
I get this error 
 File "C:\Users\DMU108\Anaconda3\envs\mlflow_env\lib\site-packages\mlflow\utils\rest_utils.py", line 206, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/create failed with error code 404 != 200. Response body: ''

Can you please help out in this? </div>

**Comment by harupy** [comment]
Hi @debanshu-mutt, can you list experiments?

```python
mlflow.set_tracking_uri("databricks")
mlflow.search_experiments()
```

**Comment by debanshu-mutt** [comment]
No it throws the same error as mentioned above.

**Comment by harupy** [comment]
Are you sure your credentials are vaild?

**Comment by debanshu-mutt** [comment]
yes 
databricks workspace ls /Users/admdmu108@crb.apmoller.net
is listing all my notebooks in the cmd line

**Comment by debanshu-mutt** [comment]
yes it's empty

**Comment by debanshu-mutt** [comment]
Databricks host as in - in the config file right? 
From what I got to understand from the documentation 
my host is actually a workspace so something like - https://url.azuredatabricks.net/?o=id
id indicating workspace

**Comment by harupy** [comment]
@debanshu-mutt I don't think `/?o=id` is necessary. Can you try removing it?
