### ISSUE TITLE
context is empty in load_context 

### ISSUE THREAD

**Issue by inderpreetsingh01** [mlflow/mlflow#7083]
class _MLflowWrapped(PythonModel):
          def __init__(self, model, model_input_schema):
              self.model = model
              self.model_input_schema = model_input_schema
            
          def load_context(self, context):
              import pickle
              print('context', context)

I have logged a sklearn model in pickle format as artifacts using client.log_artifact,
I need to load the model inside pyfunc class above, i am trying to load it from context but in above load_context function context is empty while i see the artifacts logged in UI. 
Any help would be appreciated.

**Comment by harupy** [comment]
@inderpreetsingh01 Ok, can you share the code you have and how we can reproduce the error with it?

**Comment by harupy** [comment]
@inderpreetsingh01 Any updates here?

**Comment by harupy** [comment]
The following code ran successfully:

```python
import mlflow
import pandas as pd


class MyModel(mlflow.pyfunc.PythonModel):
    def predict(self, context, _model_input):
        return context.artifacts


add5_model = MyModel()
with mlflow.start_run():
    model_info = mlflow.pyfunc.log_model(
        artifact_path="model", python_model=add5_model, artifacts={"a.py": __file__}
        #                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    loaded_model = mlflow.pyfunc.load_model(model_info.model_uri)


model_input = pd.DataFrame([range(10)])
assert "a.py" in loaded_model.predict(model_input)
```

I think you forgot to specify the `artifacts` argument

**Comment by harupy** [comment]
Feel free to reopen the issue if specifying `the `artifacts` argument` doesn't help.
