### ISSUE TITLE
Upgrade from version 1.23 to Latest

### ISSUE THREAD

**Issue by helensumathih** [mlflow/mlflow#7106]
Hi,

We are using mlflow 1.23 with some UI changes done specific to our organization needs. Now we would like to upgrade to the latest version which has the pipelines. Can anyone please suggest on how to upgrade or is there any sequence of steps or best practices to adopt?

**Comment by harupy** [comment]
@helensumathih I think you can do:

1. Clone the latest release branch (1.29 for now).
2. Make the UI changes for your organization needs.
3. Run `yarn build` in the `mlflow/server/js` directory to build UI assets.
4. Build a wheel by running `python setup.py bdist_wheel`.
5. Install it.

**Comment by harupy** [comment]
Feel free to reopen the issue if you need further help.
