### ISSUE TITLE
Add `mlflow runs` CLI utility

### ISSUE THREAD

**Issue by aarondav** [mlflow/mlflow#712]
It is often convenient to query the MLflow tracking server from the command line, as opposed to invoking REST calls or starting a Python REPL, for example. Currently, we have support for several convenience functions being invoked from the `mlflow` CLI, including the ability to query and update experiments.

A similar level of functionality would also be useful for runs. For example, if I could do `mlflow runs list --experiment-id 0` based on the result of my `mlflow experiments list`, and see all or some subset of my runs, with the date of execution, run id, run name, and ideally some of the metrics or parameters. Then from here, I might be able to delete some that follow some pattern.

**Comment by DorIndivo** [comment]
I start working on this issue

**Comment by mparkhe** [comment]
`mlflow runs` CLI command was added in #720, #1320, ... etc

```
$ > mlflow runs --help
Usage: mlflow runs [OPTIONS] COMMAND [ARGS]...

  Manage runs. To manage runs of experiments associated with a tracking
  server, set the MLFLOW_TRACKING_URI environment variable to the URL of the
  desired server.

Options:
  --help  Show this message and exit.

Commands:
  delete    Mark a run for deletion.
  describe  All of run details will print to the stdout as JSON format.
  list      List all runs of the specified experiment in the configured...
  restore   Restore a deleted run.
```
