### ISSUE TITLE
Support development environment creation on Windows[FR]

### ISSUE THREAD

**Issue by mpeaton-ng** [mlflow/mlflow#7120]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

dev-env-setup.sh currently fails with error: `Unknown operating system environment: unknown exiting.`
Consider providing support for developers that are constrained to Windows operating systems via conda environment.

### Motivation

As an mlflow user who develops for remote heterogeneous targets from a base Windows os (corporate constrained) it would be convenient to enable contribution/debugging from local host os.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@mpeaton-ng `dev-env-setup.sh` only supports UNIX systems. Here's the command to create a minimum development environment via conda, which should work on windows:

```
conda create -n mlflow-dev-env python=3.8
pip install -e .
pip install -r requirements/test-requirements.txt requirements/doc-requirements.txt requirements/lint-requirements.txt
```

**Comment by harupy** [comment]
https://learn.microsoft.com/en-us/windows/wsl/install might help.

**Comment by harupy** [comment]
You can also use a service like https://www.gitpod.io/.

**Comment by harupy** [comment]
Feel free to reopen the issue if https://github.com/mlflow/mlflow/issues/7120#issuecomment-1285536283 doesn't help.

**Comment by mpeaton-ng** [comment]
Incidentally it seems to almost work for me with the following patch:

index 2c90b995..ca3d2232 100755
--- a/dev/dev-env-setup.sh
+++ b/dev/dev-env-setup.sh
@@ -89,6 +89,7 @@ fi
case "$(uname -s)" in
   Darwin*)                       machine=mac;;
   Linux*)                        machine=linux;;
+  MING*)                        machine=linux;;
   *)                             machine=unknown;;
esac

From: Harutaka Kawamura ***@***.***>
Sent: Thursday, October 20, 2022 9:25 AM
To: mlflow/mlflow ***@***.***>
Cc: Eaton, Michael [US] (DS) ***@***.***>; Mention ***@***.***>
Subject: EXT :Re: [mlflow/mlflow] Support development environment creation on Windows[FR] (Issue #7120)


@mpeaton-ng<https://github.com/mpeaton-ng> dev-env-setup.sh only supports UNIX systems. Here's the command to create a minimum development environment via conda, which should work on windows:

conda create -n mlflow-dev-env python=3.8

pip install -e .

pip install -r requirements/test-requirements.txt requirements/doc-requirements.txt requirements/lint-requirements.txt

**Comment by mpeaton-ng** [comment]
Wsl is not an option in my environment

From: Harutaka Kawamura ***@***.***>
Sent: Thursday, October 20, 2022 9:26 AM
To: mlflow/mlflow ***@***.***>
Cc: Eaton, Michael [US] (DS) ***@***.***>; Mention ***@***.***>
Subject: EXT :Re: [mlflow/mlflow] Support development environment creation on Windows[FR] (Issue #7120)


https://learn.microsoft.com/en-us/windows/wsl/install might help.

**Comment by mpeaton-ng** [comment]
fatal: unable to access 'https://github.com/databricks/databricks-cli.git/': Received HTTP code 407 from proxy after CONNECT

**Comment by harupy** [comment]
Found https://stackoverflow.com/questions/24907140/git-returns-http-error-407-from-proxy-after-connect
