### ISSUE TITLE
can't build SageMaker container with mlflow 0.8

### ISSUE THREAD

**Issue by omeomi** [mlflow/mlflow#713]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
No 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.10
- **MLflow installed from (source or binary)**: 
binary (pip)
- **MLflow version (run ``mlflow --version``)**:
0.8.0
- **Python version**: 
3.7.1
- **npm version (if running the dev UI):
n.a.
- **Exact command to reproduce**:
mlflow sagemaker build-and-push-container

### Describe the problem
Since installing version 0.8.0 I can't build the default docker image anymore. It fails with the errors shown below. It seems to be related to it not being able to find something in the Maven repository. Perhaps this has not been updated yet?

### Source code / logs
```
[INFO] Configured Artifact: org.mlflow:mlflow-scoring:0.8.0:pom
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/mlflow/mlflow-scoring/0.8.0/mlflow-scoring-0.8.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.188 s
[INFO] Finished at: 2018-11-13T17:08:30+00:00
[INFO] Final Memory: 17M/393M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (default-cli) on project standalone-pom: Unable to find artifact. Could not find artifact org.mlflow:mlflow-scoring:pom:0.8.0 in central (https://repo.maven.apache.org/maven2)
[ERROR] 
[ERROR] org.mlflow:mlflow-scoring:pom:0.8.0
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command '/bin/sh -c mvn --batch-mode dependency:copy -Dartifact=org.mlflow:mlflow-scoring:0.8.0:pom -DoutputDirectory=/opt/java' returned a non-zero code: 1
```

Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by dbczumar** [comment]
Hi @omeomi. Thank you for informing us of this issue! We're currently working to resolve an issue with our Java scoring artifacts on Maven; these artifacts aren't being resolved correctly, which is why you're seeing this error.

In the mean time, I recommend cloning the MLflow GitHub repository on your local machine and building the image using `mlflow.sagemaker.build_image(mlflow_home="/path/to/cloned/mlflow/repository")`. This approach should work properly.

**Comment by omeomi** [comment]
Hey @dbczumar, just tried your suggestion and that indeed works without a problem. Thanks !

**Comment by weldpua2008** [comment]
@dbczumar Please suggest any workaround.
```
RUN mvn --batch-mode dependency:copy -Dartifact=org.mlflow:mlflow-scoring:0.8.0:pom  -DoutputDirectory=/opt/java
RUN mvn --batch-mode dependency:copy -Dartifact=org.mlflow:mlflow-scoring:0.8.0:jar  -DoutputDirectory=/opt/java/jars
RUN cd /opt/java && mv mlflow-scoring-0.8.0.pom pom.xml &&  mvn --batch-mode dependency:copy-dependencies -DoutputDirectory=/opt/java/jars

```
To something like: 
```
RUN mkdir -p /opt/ && git clone https://github.com/mlflow/mlflow.git /opt/mlflow/  && \
    P="${PWD}" && \
    cd /opt/mlflow/ && git checkout v0.8.0 && \
    cd /opt/mlflow/mlflow/java/scoring  && \
    mvn --batch-mode package -DskipTests && \
     mkdir -p /opt/java/jars && \
     mv /opt/mlflow/mlflow/java/scoring/target/mlflow-scoring-*-with-dependencies.jar /opt/java/jars && \
     cd "${P}"
```

**Comment by mkhrbi** [comment]
is this problem still exist?
