### ISSUE TITLE
[BUG] Security Vulnerability

### ISSUE THREAD

**Issue by SkiFast1** [mlflow/mlflow#7169]
**Vulnerability description (without details):**
CSV injection in mlflow ui, scope of attack - user of the application, additional information may be provided upon request.
**Version:** 
1.26.1 - 1.30.0

**Comment by SkiFast1** [comment]
Hello!
This issue is different from the #7166, is the testing mentioned by mistake?

**Comment by harupy** [comment]
Yes, I mentioned this issue by mistake.

**Comment by harupy** [comment]
@SkiFast1 Thanks for filing this issue. Can you provide details? Here's my gmail address: hkawamura0130@gmail.com

**Comment by SkiFast1** [comment]
Hi! Sent the details to the email above
