### ISSUE TITLE
How to add the name of experiment when registering a model built with mlflow in AzureML?

### ISSUE THREAD

**Issue by flippercy** [mlflow/mlflow#7173]
Hi:

I am building models using mlflow in AzureML and then registering them through mlflow.register_model(). However, I cannot find any place to add the name of the experiment; as a result, the experiment name is empty in the dashboard.

![image](https://user-images.githubusercontent.com/51969693/198121510-8d3d2373-2f84-494d-9aa8-6ab669652c73.png)

How can I add the name of experiment, please? 

Thank you.

**Comment by BenWilson2** [comment]
Hi @flippercy this question is better served by filing it within https://github.com/mlflow/mlflow/discussions . Issues are reserved for Feature Requests and Bugs. Closing this Issue.
