### ISSUE TITLE
Enable pylint rules in group C

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#7205]
We currently disable all pylint rules in group C (e.g. [invalid-name](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/invalid-name.html)). There might be rules that should NOT be disabled. This issue tracks finding & enabling them.

|Rule|PR|Note
|:-|:-|:-|
|missing-function-docstring|TODO|Involved|
|consider-using-f-string|TODO|simple|
|wrong-input-order|TODO|simple|
|import-outside-toplevel|TODO|may require many exclusions|
|missing-module-docstring|TODO|involved, multiple PRs|
|missing-class-docstring|TODO|involved, multiple PRs|
|ungrouped-imports|#7348|simple|
|too-many-lines|TODO|may require many exclusions|
|consider-iterating-dictionary|#7310|simple|
|unidiomatic-typecheck|TODO|simple|
|trailing-whitespace|TODO|simple|
|use-maxsplit-arg|TODO|simple|
|consider-using-enumerate|#7306|simple|
|unused-argument|TODO|exclusions required|
|superfluous-parens|#7298|simple|
|c-extension-no-member|TODO|requires whitelisting|
|disallowed-name|TODO|simple|
|wrong-import-position|TODO|simple|

**Comment by ayushthe1** [comment]
hey @harupy ,can I work on this issue ?
Also ,can u give some idea on how to approach this .

**Comment by ayushthe1** [comment]
hey @harupy ,can I work on this issue ?
Also ,can u give some idea on how to approach this .

**Comment by BenWilson2** [comment]
@ayushthe1 It's recommended for this one to tackle separate elements (enabling convention checking alone is going to create a VERY big 'fix it list' that is far too large and comprehensive for a single PR. 
I'll update the list above with the specific rules to enable. 

When tackling the first of these, the following change will need to be made:

- Delete entry "C"
- Add:

```python
missing-function-docstring,
consider-using-f-string,
wrong-import-order,
import-outside-toplevel,
missing-module-docstring,
missing-class-docstring,
ungrouped-imports,
too-many-lines,
consider-iterating-dictionary,
unidiomatic-typecheck,
trailing-whitespace,
use-maxsplit-arg,
consider-using-enumerate,
unused-argument,
superfluous-parens,
c-extension-no-member,
disallowed-name,
wrong-import-position,
```

Here: https://github.com/mlflow/mlflow/blob/132a57a58af57b958541338e7bfb0cc67f16bd2b/pylintrc#L137

**Comment by ayushthe1** [comment]
Thanks @BenWilson2 ,so i guess these are the steps i need to do ?
* remove 'C' from disable.
* add any one of the above rule (eg: missing-function-docstring) to enable .
* run .dev/lint.sh to find out all the instances where the added rule is not followed.
* fix all the instances to comply with the rule
* make a pr corresponding to the added rule

**Comment by BenWilson2** [comment]
@ayushthe1 we're in the process of merging a PR that takes care of most of the steps here to identify elements to work on.
#7290 
Once that's merged (should be shortly), feel free to remove one of the marked rules in the table above with the "simple" note and proceed with fixing the pylint errors that are generated :) A great one to get started with is `superfluous-parens`

**Comment by BenWilson2** [comment]
#7290 is merged now :)

**Comment by ayushthe1** [comment]
Understood  @BenWilson2 😄
Will start working on `superfluous-parens`

**Comment by tsugumi-sys** [comment]
@harupy 
I'm checking `consider-using-f-string` and the results are [here](https://gist.github.com/tsugumi-sys/7caac1b56c316d05ab56f7803b3efff8).  Is it okay to make a whole change in one PR or should I split pull requests with each files?

**Comment by harupy** [comment]
@tsugumi-sys I think `consider-using-f-string` is too strict. `.format` is more readable in some cases.

**Comment by harupy** [comment]
If `consider-using-f-string` blindly suggests that any `"<string>".format(...)` be replaced with `f"..."`, I don't think we should enable it.

**Comment by tsugumi-sys** [comment]
I agree. 

> @tsugumi-sys I think `consider-using-f-string` is too strict. `.format` is more readable in some cases.
> 
> Example:
> 
> ```python
> print(f"{my_function1(['hello', 'world'])} string {my_function2(['foo', 'baz'])}")
> 
> # vs.
> 
> print(
>     "{} string {}".format(
>         my_function1(["hello", "world"]),
>         my_function2(["foo", "baz"]),
>     )
> )
> ```

**Comment by harupy** [comment]
A simple case like `"{} foo".format(baz)` should be fixed though.

**Comment by harupy** [comment]
We can create our lint custom rule for f-string.

**Comment by harupy** [comment]
@tsugumi-sys Can you fix a line that contains a simplifiable `"...".format`, and then file a PR? I can push changes to implement the custom lint rule to that PR.

**Comment by sipsmehta** [comment]
@harupy Can you please assign this task to me? I would be using pep 8 for this task

**Comment by tsugumi-sys** [comment]
@sipsmehta @harupy 
I can work on some tasks here. Can I work on `wrong-input-order`?

**Comment by harupy** [comment]
We can close this isssue. We switched to ruff. Thanks for all the contributions!
