### ISSUE TITLE
[BUG] MLflow with ray starts another experiment

### ISSUE THREAD

**Issue by AugustoPeres** [mlflow/mlflow#7206]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.30.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.1 LTS
- **Python version**: 3.10.6
- **yarn version, if running the dev UI**:

### Describe the problem

Ray opens another mlflow experiment.

I am using pytorch_lightning together with ray for distributed training and mlflow to track my experiments.

I first start and experiment to log several things:

```python
def _log_parameters(**kwargs):
    for key, value in kwargs.items():
        mlflow.log_param(str(key), value)

#... snip ...#
def main():
    if FLAGS.mlflow_server_uri is not None:
        mlflow.set_tracking_uri(FLAGS.mlflow_server_uri)
    mlflow.start_run()
    _log_parameters(some_parameters)
```

Then I start ray as follows:

```python
            ray.init(address='auto')
            plugin = RayStrategy(num_workers=FLAGS.num_workers,
                                 num_cpus_per_worker=FLAGS.num_cpus_per_worker,
                                 use_gpu=FLAGS.use_gpu)
            trainer = pl.Trainer(max_epochs=FLAGS.max_epochs,
                                 strategy=plugin,
                                 logger=False,
                                 callbacks=all_callbacks,
                                 precision=int(FLAGS.precision))
          trainer.fit()
```

Then I notice that all metrics from training are being logged to `mlruns` instead of the experiment created by mlflow.start_run()

### Code to reproduce issue

cannot provide code to reproduce the issue at the moment .

### Stack trace

There is no error log. But everything is logged somewhere else.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by AugustoPeres** [comment]
The bug persists even if I initialise ray before mlflow:

```python
def main():
    if FLAGS.use_ray:
        ray.init(address='auto')
    if FLAGS.mlflow_server_uri is not None:
        mlflow.set_tracking_uri(FLAGS.mlflow_server_uri)
    mlflow.start_run()
```

**Comment by BenWilson2** [comment]
If you're logging from Ray workers, can you try to pass the generated run_id (in the return value from `mlflow.start_run()`) to the worker executable code and ensure that the run is set as the active run before logging anything? Since the head node is generating the call to generate a new experiment, the workers likely won't have the context access to the head daemon.

**Comment by BenWilson2** [comment]
Hi @AugustoPeres I'm not seeing your use of either the `@mlflow_mixin` decorator mixin or defining an `MLflowLoggerCallback` from within a ray tuner instantiation. 
Are you following along with the docs here https://docs.ray.io/en/latest/tune/examples/tune-mlflow.html to utilize the integration for ray worker processes to MLflow? 
I highly recommend giving this a read: https://medium.com/distributed-computing-with-ray/ray-mlflow-taking-distributed-machine-learning-applications-to-production-103f5505cb88 to get a good feel about how to use MLflow from within Ray (as well as the great example that the Ray team built: https://docs.ray.io/en/latest/tune/examples/includes/mlflow_ptl_example.html )

**Comment by AugustoPeres** [comment]
@BenWilson2. The first solution worked for me.

I now use:

```python
    with mlflow.start_run():
        run_id = mlflow.active_run().info.run_id
        _log_parameters(some_parameters)
```

and then, whenever logging something from ray I simply use:

```python
with mlflow.start_run(run_id=run_id):
```

I also needed to set:

```python
runtime_env = {
                     'env_vars': {
                         'MLFLOW_TRACKING_URI': FLAGS.mlflow_server_uri
                     }
                 }
```

to ensure logging to the proper server uri

Thanks, will mark this as closed.

**Comment by BenWilson2** [comment]
I'm glad that it worked as a solution for you :) Thank you for using MLflow!

**Comment by MakGulati** [comment]
when using same run_id with ray parallel iterators it throws error that run_id doesn't exist.

```
import ray

ray.init(address="auto")
from mlflow import log_metric
import mlflow


@ray.remote
def task(client_id, run_id):
    val = client_id + 10
    with mlflow.start_run(run_id=run_id, nested=True):
        log_metric(f"global_accuracy", val)


if __name__ == "__main__":
    mlflow.set_tracking_uri("sqlite:///ml.db")
    mlflow.start_run()
    run_id = mlflow.active_run().info.run_id
    print(run_id)
    ray.get([task.remote(i, run_id) for i in range(6)])
```
error: 

> 
>     raise MlflowException(
> mlflow.exceptions.MlflowException: Run '5ebd062069d0401892e603df3ef6187c' not found

**Comment by BenWilson2** [comment]
@MakGulati Does your remote machine have a concept of what the tracking server's uri is? Since these are isolated processes, you're going to have to set the uri within the remote function to get it to log to the correct location.

**Comment by MakGulati** [comment]
> @MakGulati Does your remote machine have a concept of what the tracking server's uri is? Since these are isolated processes, you're going to have to set the uri within the remote function to get it to log to the correct location.

Thanks @BenWilson2  it worked when I set uri inside remote function i.e. ```task```
