### ISSUE TITLE
[FR] Add custom metadata in the MLmodel file

### ISSUE THREAD

**Issue by jdonzallaz** [mlflow/mlflow#7235]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

We need to be able to add custom metadata to the `MLmodel` file.

### Motivation

> #### What is the use case for this feature?

It would be nice to be able to add metadata to the `MLmodel` file in order to give additional information how the model should be deployed.

> #### Why is this use case valuable to support for your project(s) or organization?

Our models are deployed differently according to their characteristics. It would be nice to keep this information in the registry.

> #### Why is it currently difficult to achieve this use case?

The `kwargs` aren't passed to the constructor so it is impossible to achieve this use case.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
An interesting idea. Thank you for bringing it up. While we discuss this internally, could you provide a bit more context around the proposed structure, content types supported, and how the encapsulated data would be accessed and logged as part of the `<flavor>.log_model()` APIs?

**Comment by jdonzallaz** [comment]
Thanks for your follow-up.

Our use case is the following: We want to distinguish two types of models:
- Models trained online which use user data - this kind of model cannot be shared between users when deployed.
- Models trained offline and is stateless. Weights are trained and frozen - it can be shared between users.

We could tag the models as stateless/stateful with the following code (our PR add this feature):
```python
# Log the model with the custom metadata
Model.log(
    flavor=mlflow.pyfunc,
    python_model=MyModel(),
    registered_model_name="MyModel",
    metadata={"stateful":True},
)

# Load the model and access the custom metadata
model = mlflow.pyfunc.load_model(model_uri="models:/MyModel/latest")
print(model.metadata.stateful)
```

For now, the `<flavor>.log_model()` is not supported, but we could easily add the `metadata` parameter to every flavor.

Writing the metadata is already supported by MLflow through the `Model.to_dict()` function. Content types supported are the same as the ones supported by this function (yaml-serializable types).

**Comment by BenWilson2** [comment]
Sounds good! If you could update the flavors, add a few simple validation tests for the flavors and ensure that serving functions correctly with a model artifact that includes this metadata element in the serialized structure, I think we'll be good to proceed :)

**Comment by jdonzallaz** [comment]
Good! So I updated the pull request. Please get back to me if I forgot something in my implementation.

**Comment by dbczumar** [comment]
Closing this out now that it's shipped. Thanks again, @jdonzallaz !
