### ISSUE TITLE
[BUG] MLflow REST API incorrectly reports "database down" as BAD_REQUEST (HTTP 400) error

### ISSUE THREAD

**Issue by barrywhart** [mlflow/mlflow#7238]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 1.30.0
- Tracking server: 1.30.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Slim
- **Python version**: 3.7
- **yarn version, if running the dev UI**:

### Describe the problem

I'm testing the behavior MLflow REST server when the database server (e.g. Postgres) goes down. I discovered that the server returns an HTTP 400 **client** error, which is not retried by the MLflow client. Hence, a job using MLflow fails immediately rather than retrying.

The incorrect code is [here](https://github.com/mlflow/mlflow/blob/v1.30.0/mlflow/store/db/utils.py#L105).

I propose adding another `except` block above this one, resulting in:
```
        except sqlalchemy.exc.OperationalError as e:
            session.rollback()
            raise MlflowException(message=e, error_code= INTERNAL_ERROR)
        except sqlalchemy.exc.SQLAlchemyError as e:
            session.rollback()
            raise MlflowException(message=e, error_code=BAD_REQUEST)
```

[PEP 249 – Python Database API Specification v2.0 | peps.python.org](https://peps.python.org/pep-0249/#operationalerror) [Core Exceptions — SQLAlchemy 1.4 Documentation] describes `OperationalError` as:
> Exception raised for errors that are related to the database’s operation and not necessarily under the control of the programmer, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a memory allocation error occurred during processing, etc.

This exception type is primarily for errors that occur at runtime, relating to the operational environment of the application, rather than a bug in the application (or something the MLflow user / client did wrong).

### Code to reproduce issue

```
import mlflow

experiment_name = f"foobar"
mlflow.set_experiment(experiment_name)
with mlflow.start_run():
    pass
```

### Stack trace

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 455, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 528, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 711, in _update_run
    run_id, request_message.status, request_message.end_time, request_message.run_name
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 650, in update_run_info
    return run.info
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 105, in make_managed_session
    raise MlflowException(message=e, error_code=BAD_REQUEST)
mlflow.exceptions.MlflowException: (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Sounds good to me! Please let us know when you file the PR :)

**Comment by barrywhart** [comment]
Done! Created PR #7240. Are there pre-existing tests for this area of the code?
