### ISSUE TITLE
Fix `assert expected == actual` to `assert actual == expected`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#7248]
## Details

We have assert statements that looks like:

```python
assert expected == actual
```

For example,

https://github.com/mlflow/mlflow/blob/ce1b4da8b1f1acbc5bf052f39e0894398c27641a/tests/store/tracking/test_sqlalchemy_store.py#L1590

The actual and expected values need to be swapped as follows:

```diff
- assert [] == self._search(exp, run_view_type=ViewType.DELETED_ONLY) 
+ assert self._search(exp, run_view_type=ViewType.DELETED_ONLY) == []
```

I created [a script](https://gist.github.com/harupy/e7656c4c2b8bb5018c7674ddac73a312) to automate the transformation. The following command runs this script on files in the `tests` directory.

```
pip install libcst && python -c "$(curl https://gist.githubusercontent.com/harupy/e7656c4c2b8bb5018c7674ddac73a312/raw/1a9a2bf9fbebfb9b8fe6450a439cfb7b91188a85/swap_literal.py)" $(git ls-files "tests/**/*.py") && black .
```

**Comment by harupy** [comment]
Aakash Thette will work on this issue.

**Comment by harupy** [comment]
Aakash Thette hasn't responded. @ayushthe1 Are you interested in working on this issue?

**Comment by ayushthe1** [comment]
> Aakash Thette hasn't responded. @ayushthe1 Are you interested in working on this issue?

Yes ,for sure. 🙂
