### ISSUE TITLE
MLFlow+Flyte+Pytorch: Encountered an unexpected error while inferring pip requirements

### ISSUE THREAD

**Issue by tamis-laan** [mlflow/mlflow#7252]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow, version 1.30.0

### System information

- Arch linux
- Python 3.10.8

### Describe the problem

I'm using a combination of MLflow, Flyte and pytorch to train a model locally and store the result into MLflow. When the model is stored into MLflow I get the following error:

```
2022/11/04 09:58:08 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp3k6c3_ff/model/data, flavor: pytorch), fall back to return ['torch==1.13.0', 'cloudpickle==2.2.0']. Set logging level to DEBUG to see the full traceback.
/$HOME/.local/share/virtualenvs/ai-template-ekyeoNrO/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```

### Code to reproduce issue

``` python
import os
import typing

import mlflow
import pandas

import torch
import torchvision

import flytekit
from flytekit import LaunchPlan, CronSchedule, workflow, task, Resources
from flytekit.types.file import FlyteFile
from flytekit.types.directory import FlyteDirectory

# Construct model
class Model(torch.nn.Module):
    # Construct model
    def __init__(self):
        # Initialise parent
        super(Model, self).__init__()
        # First layer
        self.l1 = torch.nn.Sequential(
            torch.nn.Conv2d(1, 16, 5, 1, 2), torch.nn.ReLU(), torch.nn.MaxPool2d(2)
        )
        # Second layer
        self.l2 = torch.nn.Sequential(
            torch.nn.Conv2d(16, 32, 5, 1, 2), torch.nn.ReLU(), torch.nn.MaxPool2d(2)
        )
        # Third layer
        self.l3 = torch.nn.Sequential(
            torch.nn.Flatten(), torch.nn.Linear(32 * 7 * 7, 10), torch.nn.Softmax(-1)
        )

    # Forward data through model
    def forward(self, inputs: torch.Tensor):
        interme = self.l1(inputs)
        interme = self.l2(interme)
        outputs = self.l3(interme)
        return outputs

    # Loss function
    def loss(self, outputs, targets):
        # Convert targets to one hot
        targets = torch.nn.functional.one_hot(targets, 10)
        # Compute negative log likelihood
        return -torch.mean(torch.sum(targets * torch.log(outputs), -1))


@task(cache=True, cache_version="1.0")
def download_mnist() -> FlyteDirectory:
    # Data path
    data_path = str(flytekit.current_context().working_directory) + "/mnist"

    # Log data path
    print("data path", data_path)

    # download the training set
    torchvision.datasets.MNIST(root=data_path, train=True, download=True)

    # Download the test set
    torchvision.datasets.MNIST(root=data_path, train=False, download=True)

    # Return data
    return FlyteDirectory(path=data_path)


@task
def fit(data: FlyteDirectory) -> str:
    # Construct the training set
    train_set = torchvision.datasets.MNIST(
        root=str(data.path),
        train=True,
        transform=torchvision.transforms.ToTensor(),
    )

    # Construct the test set
    test_set = torchvision.datasets.MNIST(
        root=str(data.path), train=False, transform=torchvision.transforms.ToTensor()
    )

    # Construct train set loader
    train = torch.utils.data.DataLoader(
        train_set,
        batch_size=100,
        shuffle=True,
        num_workers=1,
    )

    # Construct test set loader
    test = torch.utils.data.DataLoader(
        test_set,
        batch_size=100,
        shuffle=True,
        num_workers=1,
    )

    # Configure the device to run on
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Materialize model
    model = Model()

    # Set the experiment
    experiment = mlflow.set_experiment("mnist")

    # Start logging run
    with mlflow.start_run(experiment_id=experiment.experiment_id) as run:

        # Define number of epochs
        epochs = 20

        # Define learning rate
        alpha = 0.0005

        # Log params
        mlflow.log_param("epochs", epochs)
        mlflow.log_param("learning rate", alpha)

        # Get optimizer
        optimizer = torch.optim.Adam(model.parameters(), lr=alpha)

        # Start optimization process
        for epoch in range(epochs):
            for i, (inputs, targets) in enumerate(train):
                # Run batch through model
                outputs = model(inputs)
                # Compute the loss
                loss = model.loss(outputs, targets)
                # Clear optimizer gradients
                optimizer.zero_grad()
                # Back propagate loss
                loss.backward()
                # Apply gradients
                optimizer.step()
                # Log loss metric
                mlflow.log_metric("negative log likelihood", loss.item())
                # Log to console
                if (i + 1) % 50 == 0:
                    print(f"[{epoch+1},{epochs}] [{i+1},{len(train)}], {loss.item()}")

        # Log model
        mlflow.pytorch.log_model(model, "mnist model")

        # Return run id
        return run.info.run_id


@workflow
def train() -> None:
    # Download dataset
    data = download_mnist()
    # Fit model
    run_id = fit(data=data)
```

Execute code with:
```
> pyflyte run main.py train
```

### Stack trace

2022/11/04 09:58:08 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp3k6c3_ff/model/data, flavor: pytorch), fall back to return ['torch==1.13.0', 'cloudpickle==2.2.0']. Set logging level to DEBUG to see the full traceback.
/$HOME/.local/share/virtualenvs/ai-template-ekyeoNrO/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
It's not an error, but a warning. You can insert the following code to see what went wrong:

```python
import logging

logging.getLogger("mlflow").setLevel(logging.DEBUG)
```

**Comment by harupy** [comment]
If you want to disable the requirement inference, you can explicitly specify `pip_requirements`  in `mlflow.pytorch.log_model`:

```
mlflow.pytorch.log_model(..., pip_requirements=[])
```

**Comment by tamis-laan** [comment]
```

**Comment by BenWilson2** [comment]
This isn't exactly an MLflow problem. The exception that you're getting is that you don't have an executable entry point in your code. Please refactor your implementation and provide an inheritable entry point to your class so that the partial function can access the `.predict()` method.

**Comment by steveepreston** [comment]
Hey @BenWilson2, can you open the issue?

facing similar issue: ['tensorflow==2.16.1', 'cloudpickle==3.0.0']
