### ISSUE TITLE
[BUG] When performing Sagemaker update the Data Capture setting are gone from a Sagemaker Endpoint

### ISSUE THREAD

**Issue by edvorkin** [mlflow/mlflow#7255]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.29.0
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

When I create an endpoint using create_deployment call and supply the following data capture config `data_capture_config = {
    'EnableCapture': True,
    'InitialSamplingPercentage': data_capture_InitialSamplingPercentage,
    'DestinationS3Uri': data_capture_bucket,
    'CaptureOptions': [
        {'CaptureMode': 'Input'},
        {'CaptureMode': 'Output'}
    ]
}`
I do see the data capture setting in AWS Console. But when I execute the update_deployment call against the same endpoint using the same config, the data capture settings are gone from the console. 

### Code to reproduce issue

You can use any test configuration
```
if endpoint_exists:
    config['mode']=mlflow.sagemaker.DEPLOYMENT_MODE_REPLACE
    config['data_capture_config']=data_capture_config
    client.update_deployment(
    deployment_name,
    flavor="python_function",
    model_uri=model_uri,
    config=config)
else:
    client.create_deployment(
    deployment_name,
    flavor="python_function",
    model_uri=model_uri,
    config=config
)
```

### Stack trace

none

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @edvorkin thank you for reporting. We're currently investigating this functionality and will look into this. Thank you for reporting!

**Comment by harupy** [comment]
Hi @edvorkin, we filed a PR to fix this issue: https://github.com/mlflow/mlflow/pull/7281

**Comment by harupy** [comment]
I created a branch (base ref: v1.29.0) to test the fix: https://github.com/harupy/mlflow/tree/v1.29.0-data-capture-fix

The following command installs mlflow from this branch:

```
pip install git+https://github.com/harupy/mlflow.git@v1.29.0-data-capture-fix
```

**Comment by harupy** [comment]
@edvorkin Thank you for testing the fix. Glad. It's working :)

**Comment by edvorkin** [comment]
when do you think it can be merged into the main release?
