### ISSUE TITLE
[BUG] Mlflow runs do not persist across files

### ISSUE THREAD

**Issue by danre07** [mlflow/mlflow#7257]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client:  1.30.0
- Tracking server:  1.30.0

### System information

- ** macOS 12.6.1 **:
- **Python3.10**:

### Describe the problem

I'm currently using Papermill to run my notebooks in a loop, and I want to save artifacts to a single run, but a new run is created in the notebook each time. 

`set_experiment` appears to be required, as it will default to experiment 0 which would cause mlflow to crash, since I deleted the default experiment. 

### Code to reproduce issue

```py
if __name__ == '__main__':
    mlflow.set_tracking_uri('http://127.0.0.1:5000')
    mlflow.set_experiment(f'Validation')

    mlflow.start_run(run_name="First Trial")
  
    for i in range(3):
        pm.execute_notebook(
            'model_train.ipynb',
            '/dev/null',
            parameters = dict(i=3)
        )
```

Then inside `model_train.ipynb`, I have in the cell:
```py
import mlflow
mlflow.set_experiment(f'Validation')
...
mlflow.log_figure(fig, f"myfig_{i}.png")
```

### Stack trace

Not applicable

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
This isn't a bug. This is a feature. Isolation between processes is a good thing. 
If you're looking for a free tip on implementing something that will work for your use case, try generating a run_id from within your for loop and pass that run_id to your notebook. 

Example:

```python
import mlflow

if __name__ == "__main__":
    
    mlflow.set_tracking_uri("http:://127.0.0.1:5000")
    experiment_id = mlflow.create_experiment(name="My Cool Experiment",
                                                                             tags={"mlflow.note.content": "An experiment I'm going to use"})
    run = mlflow.start_run(experiment_id=experiment_id, run_name="A run I'm going to reuse")
    
    for i in range(3):
        pm.execute_notebook(
            "model_train.ipynb",
            "/dev/null",
            parameters = {"i": 3, "run_id": run.info.run_id}
        )
    mlflow.end_run()
```

Then, from within your notebook, simply parse that ```**kwargs``` value and consume the passed-in run_id. You _may_ need to set the tracking server address at the top of the notebook as well just to be certain. 

Another tip: you really shouldn't delete the default experiment. It will only create headaches for you. You can recreate it (and it will be auto-recreated for you if you do delete it in the upcoming 2.0 release).
