### ISSUE TITLE
mlflow.sklearn pickle error

### ISSUE THREAD

**Issue by suzhenyu22** [mlflow/mlflow#727]
something wrong about sklearn pickle.
mlflow-0.8.0
code: mlflow.sklearn

log_model's default serialization_format is pickle (line 100:), 
but save_model is cloudpickle (line 36), 
load_model from server is pickle (line 145)

that's my code not run season.
`AttributeError: Can't get attribute 'xxx_class or function' on <module '__main__' from 'test33.py'>`

please check it, thanks.

**Comment by suzhenyu22** [comment]
when I all use cloudpickle, no more error.

**Comment by dbczumar** [comment]
Hi @suzhenyu22, we've fixed the discrepancy between the default serialization format for `save_model` and `log_model` in the `master` branch; this will be incorporated into the next release of MLflow.

To clarify, does everything work as long as `log_model` specifies `serialization_format="cloudpickle"`?

**Comment by suzhenyu22** [comment]
serialization_format="cloudpickle"  all working.
thanks.

**Comment by dbczumar** [comment]
Excellent. Thanks!
