### ISSUE TITLE
No module named mlflow.recipes

### ISSUE THREAD

**Issue by luistelmocosta** [mlflow/mlflow#7297]
Hello, I noticed that there is a new version of the MLFlow Pipelines (now MLFlow Recipes). After upgrading to the new version and installing `mlflow>=2.0.0rc0`, when I try to initialize my new Recipe I get the following error: `ModuleNotFoundError: No module named 'mlflow.recipes'` 

```
from mlflow.recipes import Recipe
r = Recipe(profile="databricks")
```

Is there any extra that I need to install? With pipelines we needed to install using `pip install mlflow[pipelines]` but I don't think that the extra `recipes` is included in this new version.

Any idea?

**Comment by BenWilson2** [comment]
This hasn't been included in the release candidate. It will be a part of the full 2.0 release. If you want to try out features that are in progress, you will have to install MLflow from the master branch directly: 
`pip install mlflow@git+https://github.com/mlflow/mlflow@master`

**Comment by xxxpsyduck** [comment]
@BenWilson2 I have MLflow 2.1.1 and still can not import `receipes` module. Is `Receipe` officially available?

**Comment by BenWilson2** [comment]
You have a typo in your import. Try:
```from mlflow.recipes import Recipe```
