### ISSUE TITLE
MLflow is not working after latest release 2.0.0

### ISSUE THREAD

**Issue by poonamgoyal080** [mlflow/mlflow#7305]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.28.0
- **Python version**: 3.7

### Code to reproduce issue

python3 setup.py sdist bdist_wheel
pip3 install mlflow-1.28.0.dev0-py3-none-any.whl
mlflow --version
import mlflow

### Describe the problem

I wanted to use old version of mlflow but after latest release whenever I am trying to build wheel file using below command

**python3 setup.py sdist bdist_wheel**

and then installing using

**pip3 install mlflow-1.28.0.dev0-py3-none-any.whl**

then running

**mlflow --version**
or
**import mlflow**

getting below error

> Traceback (most recent call last):
>   File "/opt/conda/miniconda3/bin/mlflow", line 5, in <module>
>     from mlflow.cli import cli
>   File "/opt/conda/miniconda3/lib/python3.8/site-packages/mlflow/__init__.py", line 47, in <module>
>     import mlflow.pipelines
>   File "/opt/conda/miniconda3/lib/python3.8/site-packages/mlflow/pipelines/__init__.py", line 32, in <module>
>     from mlflow.pipelines.pipeline import Pipeline
>   File "/opt/conda/miniconda3/lib/python3.8/site-packages/mlflow/pipelines/pipeline.py", line 194, in <module>
>     from mlflow.pipelines.regression.v1.pipeline import RegressionPipeline
>   File "/opt/conda/miniconda3/lib/python3.8/site-packages/mlflow/pipelines/regression/v1/__init__.py", line 1, in <module>
>     from mlflow.pipelines.regression.v1.pipeline import (
>   File "/opt/conda/miniconda3/lib/python3.8/site-packages/mlflow/pipelines/regression/v1/pipeline.py", line 116, in <module>
>     from mlflow.pipelines.steps.train import TrainStep
>   File "/opt/conda/miniconda3/lib/python3.8/site-packages/mlflow/pipelines/steps/train.py", line 34, in <module>
>     from mlflow.utils.mlflow_tags import (
> ImportError: cannot import name 'MLFLOW_PIPELINE_PROFILE_NAME' from 'mlflow.utils.mlflow_tags' (/opt/conda/miniconda3/lib/python3.8/site-packages/mlflow/utils/mlflow_tags.py)

I am using python 3.7 but then I saw changes in latest release so I thought python version is the issue, then i tried with 3.8 but still getting same error.
I faced the similar type of issue earlier also(when I am not taking latest pull then the docker file if it is changed or any import is removed then getting some error) after previous release. Is it mandatory to take latest pull even if I am maintaining old version? and if not then which part of code is still pointing to the MLflow git repository? 
@dbczumar  Can you please help? It's been more than 2 weeks I am blocked because of this.

**Comment by poonamgoyal080** [comment]
@harupy If I want to install a minor version for example 1.28.1 or 1.28.2 after changing version in mlflow/version.py file then I have to generate wheel file right?

**Comment by poonamgoyal080** [comment]
getting below error after running `pip install mlflow==1.28.0`

> ERROR: Could not find a version that satisfies the requirement mlflow==1.28.2 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.0.1, 0.9.1, 1.0.0, 1.1.0, 1.1.1.dev0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.12.0, 1.12.1, 1.13, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.20.0, 1.20.1, 1.20.2, 1.21.0, 1.22.0, 1.23.0, 1.23.1, 1.24.0, 1.25.0, 1.25.1, 1.26.0, 1.26.1, 1.27.0, 1.28.0, 1.29.0, 1.30.0, 2.0.0rc0)
> ERROR: No matching distribution found for mlflow==1.28.2

**Comment by harupy** [comment]
Where did you run `python3 setup.py sdist bdist_wheel`? If you have a repository, please share it.

**Comment by poonamgoyal080** [comment]
@harupy I am running `python3 setup.py sdist bdist_wheel` in Dockerfile but tried running in my local also but it is throwing same error.

**Comment by harupy** [comment]
>  If you have a repository, please share it.

**Comment by poonamgoyal080** [comment]
I won't be able to share repository but last release I cloned from mlflow that only I want to use with custom changes on top of it.

**Comment by harupy** [comment]
I think something is wrong with custom changes.

**Comment by poonamgoyal080** [comment]
My custom changes are nothing apart from the dockerfile I shared in #7231

**Comment by harupy** [comment]
Which parts of this are custom changes?

```Dockerfile
FROM python:3.7

ARG VERSION=
ARG EXPOSE_PORT=5000

WORKDIR /app

ADD . /app

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update &&
# install prequired modules to support install of mlflow and related components
apt-get install -y default-libmysqlclient-dev build-essential curl openjdk-11-jre-headless
# cmake and protobuf-compiler required for onnx install
cmake protobuf-compiler &&
# install required python packages
pip install -r requirements/dev-requirements.txt --no-cache-dir &&
# install mlflow in editable form
pip install --no-cache-dir -e .

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - &&
apt-get update && apt-get install -y nodejs &&
npm install --global yarn &&
cd mlflow/server/js &&
yarn install &&
yarn build

RUN python3 setup.py sdist bdist_wheel
```

**Comment by poonamgoyal080** [comment]
`RUN python3 setup.py sdist bdist_wheel`
added this so that wheel file can be generated and anyways I am facing same issue even if I am not building wheel with docker

**Comment by harupy** [comment]
What does `ADD . /app` add?

**Comment by poonamgoyal080** [comment]
It's a folder which I created

**Comment by harupy** [comment]
Is it a mlflow fork?

**Comment by poonamgoyal080** [comment]
you mean for app folder?

**Comment by harupy** [comment]
You modified the mlflow source code, right?

**Comment by poonamgoyal080** [comment]
yes, this folder you can ignore it is doing nothing.

**Comment by harupy** [comment]
Please share the changes you made.

**Comment by poonamgoyal080** [comment]
I didn't made any changes as I mentioned earlier I made change in version and docker file. When I build wheel file without docker in my local and install it in VM then mlflow --version shows same Traceback in green colour but it doesn't stop me to import mlflow. But when I build wheel file using docker file and install it in VM then I am not even able to import mlflow and mlflow --version is also throwing same Traceback.

Same code was working just before latest release.

**Comment by harupy** [comment]
Please fill in the following Dockerfile.

```
# DO NOT USE COPY OR ADD. We don't have access to the files on your machine.

mlflow --version
```

```
docker build .
```

**Comment by poonamgoyal080** [comment]
In new release import mlflow.pipelines is removed from mlflow/__init__.py file but in old version it is still there

**Comment by poonamgoyal080** [comment]
sure let me try this

**Comment by harupy** [comment]
@poonamgoyal080

```Dockerfile
FROM python:3.7

RUN git clone -b v1.28.0 https://github.com/mlflow/mlflow.git
RUN cd mlflow && python setup.py sdist bdist_wheel && pip install dist/*.whl
RUN mlflow --version
```

works fine.

**Comment by harupy** [comment]
I have no idea what changes you made on top of mlflow 1.28.0, but please make sure the changes are valid.

**Comment by harupy** [comment]
@poonamgoyal080 Any updates here?

**Comment by harupy** [comment]
@poonamgoyal080 Feel free to reopen the issue if you need further help.
