### ISSUE TITLE
ftp store something wrong

### ISSUE THREAD

**Issue by suzhenyu22** [mlflow/mlflow#732]
mlflow.store.ftp_artifact_repo.py

1. def _mkdir: at lint 49
mkdir dir not work , please use this:
```
def _mkdir(self, artifact_dir):
    """ like os.makedirs """
    # artifact_dir = 'a/b/c'
    dest_dirname = artifact_dir.split('/')  # split to sub_dir ('a','b','c')
    with self.get_ftp_client() as ftp:
        for subdir in dest_dirname:
            try:
                ftp.cwd(subdir)  # cd to dir_a 
            except ftplib.error_perm:
                ftp.mkd(subdir)  # if can't cd to dir_a, make it
                ftp.cwd(subdir)  # cd dir_a, then try cd dir_b or create dir_b
```

2. def download_files: at line 65-79
download file from ftp,
`ftp.retrbinary("RETR " + ftp_file, f)` not work, 
use this code:
`ftp.retrbinary("RETR " + ftp_file, f.write)`

test on python 3.6, win10.

3. def log_artifacts: at line 90-109
when log_sklearn_model, when param artifact_path not None, it build twice the path (build_path), 
esult remote path like '/0/runid/model/0/runid/model...`
delete code like:
```
    def log_artifacts(self, local_dir, artifact_path=None):
        if artifact_path:
            dest_path_re = artifact_path
        local_dir = os.path.abspath(local_dir)
        for (root, _, filenames) in os.walk(local_dir):
            upload_path = dest_path_re
            if root != local_dir:
                rel_path = get_relative_path(local_dir, root)
                upload_path = build_path(dest_path_re, rel_path)
            if not filenames:
                self._mkdir(build_path(self.path, upload_path))
            for f in filenames:
                if os.path.isfile(build_path(root, f)):
                    self.log_artifact(build_local_path(root, f), upload_path)
```
build_local_path function because work on win10, if use build_path result like '/aaa/bbb\ccc\ddd', the correct is `c:\aaa\bbb\ccc\ddd`, not important.

```
def build_local_path(*paths):
    return os.path.join(*paths)


def build_path(*path_segments):
    """then remote path generate on win10, if use os.path.join ,the path like '/0/runid\model\Project"""
    # if platform is windows, change remote path to linux format 
    if system_type().lower() == 'windows':
        return '/'.join(path_segments).replace('//', '/')
    else:
        return os.path.join(*path_segments).replace('//', '/')
```

4. _download_file: at line 144
mlflow ui, cat not show txt content, wrong with _download_file function,
`ftp.retrbinary('RETR ' + remote_full_path, f)`
change to 
`ftp.retrbinary('RETR ' + remote_full_path, f.write)`

also download_artifacts function at line 140,
`ftp.retrbinary('RETR ' + full_path, f)` 
change to 
`ftp.retrbinary('RETR ' + full_path, f.write)`

all test mlflow server on centos, mlflow client on win10.
all test done.

**Comment by smurching** [comment]
Hi @suzhenyu22, thanks for catching the bugs - would you be interested in making a PR to fix them? Would be happy to review it :)

**Comment by enpinzolas** [comment]
I am having issues with this too. seeing that it has not been fixed, I'll try making a pull request but it's my first time so I'd appreciate some guidance 😄

I'll try doing it regardless since right now, after uploading the first artifact every other try results in a crash, and the files cannot be seen from the server.

**Comment by xd21303** [comment]
ftp

**Comment by ca8888** [comment]
bummer that the issue has not been solve yet

**Comment by rahulraj80** [comment]
@ca8888 , @xd21303 : check https://github.com/mlflow/mlflow/issues/2677 . Editing store/artifact/test_ftp_artifact_repo.py as suggested there, might fix the issue for you. Can you check and revert?
