### ISSUE TITLE
Unable to run mlflow project on local

### ISSUE THREAD

**Issue by r0goyal** [mlflow/mlflow#735]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mohave 
- **MLflow installed from (source or binary)**:  Used pip for installation
- **MLflow version (run ``mlflow --version``)**: 0.8.0
- **Python version**: 2.7.15 (Installed through anaconda)
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
I am running mlflow server on my local machine using `mlflow server`. Server is starting up fine. 
Next I am running a project from another directory using  `export KMP_DUPLICATE_LIB_OK=TRUE; export PATH=~/anaconda2/bin:$PATH; mlflow run .` 
However it seems my run is not getting stored correctly and I am getting following log output in client -
API request to http://127.0.0.1:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 2 more times. API response body: {"message": "Run '5882270d6c234d3ab07bf091c2c3b983' not found", "error_code": "RESOURCE_DOES_NOT_EXIST"}
API request to http://127.0.0.1:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 1 more times. API response body: {"message": "Run '5882270d6c234d3ab07bf091c2c3b983' not found", "error_code": "RESOURCE_DOES_NOT_EXIST"}
API request to http://127.0.0.1:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 0 more times. API response body: {"message": "Run '5882270d6c234d3ab07bf091c2c3b983' not found", "error_code": "RESOURCE_DOES_NOT_EXIST"}
Not sure what I am doing wrong here

**Comment by vaibhavkhanduja** [comment]
Same issue .. any suggestions please? It though worked fine for the first time ..

**Comment by hanyucui** [comment]
Is this still an issue on 0.8.1? Since you indicated you are not using custom code, which example script did you use?

**Comment by jonathanhar** [comment]
Same here, used to work then suddenly these errors

**Comment by gnthibault** [comment]
No update on this issue ?
