### ISSUE TITLE
[BUG] Downloading an artifact from a remote MLflow results in "Connection broken: IncompleteRead"

### ISSUE THREAD

**Issue by dfdx** [mlflow/mlflow#7360]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.0.1
- Tracking server: 1.28.0

### System information

Server: 
* Docker image based on Ubuntu 18.04, running in Kubernetes
* Python 3.9.13

Client: 
* Ubuntu 22.04
* Python 3.10.6

### Describe the problem

I have an MLflow Tracking Server running in a remote Kubernetes cluster, and a client running from my laptop at home. Whenever I try to download a model either using `mlflow.pytorch.load_models` or directly `mlflow.artifacts.download_artifacts()`, the request fails with the "Connection broken: IncompleteRead" error (see the full stacktrace below). 

Some important facts:
* The server is configured with artifacts HTTP proxy
* The error doesn't appear when testing the code from inside the cluster, so I suppose it's related to the network speed or stability
* The time from the request start to the failure varies between 30 and 70 seconds so I suppose it's not a timeout configuration issue
* Number of bytes read and left changes every time, so it's also not deterministic

From the code of `download_artifacts()` I understand that mlflow downloads artifacts in separate threads, some of which fail, but their logs are not printed. Instead, the main thread checks the size of downloaded files and detects inconsistency. Alternatively, the main thread may try to check the artifacts before child threads are finished.

### Tracking information

```
System information: Linux #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022
Python version: 3.10.6
MLflow version: 2.0.1
MLflow module location: /home/username/venv/common/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: http://<ip>:5000
Registry URI: http://<ip>:5000
MLflow environment variables: {}
MLflow dependencies: {
    "pyyaml": "6.0",
    "scipy": "1.9.3",
    "databricks-cli": "0.17.3",
    "sqlparse": "0.4.3",
    "pandas": "1.5.1",
    "gitpython": "3.1.29",
    "scikit-learn": "1.1.3",
    "protobuf": "3.20.1",
    "matplotlib": "3.6.2",
    "gunicorn": "20.1.0",
    "pyarrow": "10.0.0",
    "numpy": "1.23.3",
    "click": "8.1.3",
    "cloudpickle": "2.2.0",
    "requests": "2.28.1",
    "shap": "0.41.0",
    "docker": "6.0.1",
    "importlib-metadata": "5.0.0",
    "Flask": "2.2.2",
    "pytz": "2022.6",
    "sqlalchemy": "1.4.44",
    "alembic": "1.8.1",
    "querystring-parser": "1.2.4",
    "markdown": "3.4.1",
    "packaging": "21.3",
    "Jinja2": "3.1.2",
    "entrypoints": "0.4"
}
```

### Code to reproduce issue

Assuming we have a large model saved as an artifact using `mlflow.pytorch.log_model()`:

```python
import mlflow

ip = ...
run_id = ...
mlflow.set_tracking_uri(f'http://{ip}:5000')

mlflow.artifacts.download_artifacts(run_id=run_id, artifact_path="model")
```

### Stack trace

```python
---------------------------------------------------------------------------
MlflowException                           Traceback (most recent call last)
Cell In [4], line 1
----> 1 mlflow.artifacts.download_artifacts(run_id='24b15bcbea6c410cac462e8bc18d6bfb', artifact_path="model")

File ~/venv/common/lib/python3.10/site-packages/mlflow/artifacts/__init__.py:63, in download_artifacts(artifact_uri, run_id, artifact_path, dst_path, tracking_uri)
     61 artifact_uri = store.get_run(run_id).info.artifact_uri
     62 artifact_repo = get_artifact_repository(artifact_uri)
---> 63 artifact_location = artifact_repo.download_artifacts(artifact_path, dst_path=dst_path)
     64 return artifact_location

File ~/venv/common/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repo.py:263, in ArtifactRepository.download_artifacts(self, artifact_path, dst_path)
    260         failed_downloads[inflight_download.src_artifact_path] = repr(e)
    262 if len(failed_downloads) > 0:
--> 263     raise MlflowException(
    264         message=(
    265             "The following failures occurred while downloading one or more"
    266             " artifacts from {artifact_root}: {failures}".format(
    267                 artifact_root=self.artifact_uri,
    268                 failures=failed_downloads,
    269             )
    270         )
    271     )
    272 return dst_local_path

MlflowException: The following failures occurred while downloading one or more artifacts from http://<ip>:5000/api/2.0/mlflow-artifacts/artifacts/6/24b15bcbea6c410cac462e8bc18d6bfb/artifacts: {'model/data/model.pth': "ChunkedEncodingError(ProtocolError('Connection broken: IncompleteRead(6 bytes read, 309 more expected)', IncompleteRead(6 bytes read, 309 more expected)))"}
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @dfdx, thank you for raising this. The client-side HTTP request timeout is 120 seconds (https://mlflow.org/docs/latest/python_api/mlflow.environment_variables.html#mlflow.environment_variables.MLFLOW_HTTP_REQUEST_TIMEOUT), so I agree that this does not appear to be a client-side timeout issue. 

However, I suspect that the server may be killing the request after a certain period if time. Note that the default timeout for a gunicorn worker is 60 seconds. Can you try increasing the timeout by specifying `--gunicorn-opts "--timeout 120"` and see if it helps? If 120 seconds is insufficient, you may also want to try increasing the timeout further. You may also have more success by provisioning additional network bandwidth to your Kubernetes node(s) on which the server is being hosted.

Please let me know if these suggestions don't help and feel free to reopen this issue if there's a suspicion that it's directly caused by an MLflow bug. Thank you so much for using MLflow!

**Comment by CJxD** [comment]
I've just encountered this issue while running `mlflow models build-docker`: I have an embeddings model as an artifact that is 800MB and it seems it's not able to load it all before timing out.

As `build-docker` can't take gunicorn options as a flag, it can be given with the env var `GUNICORN_CMD_ARGS="--timeout=120" mlflow models build-docker ...` which solved the problem for me.
