### ISSUE TITLE
Can't see my runs. "No runs yet"

### ISSUE THREAD

**Issue by praksharma** [mlflow/mlflow#7378]
I am using mlflow 1.30.0. I can't see my runs even though I run `mlflow ui`  in the same directory containing the `mlruns` directory. The directory structure is like this:

```sh
[s.1915438@scs2043(sunbird) 15. hydra_zen_joblib_multi_gpu]$ ls
2.clear_while_testing.sh  master_python_script.py  multirun   mlruns

[s.1915438@scs2043(sunbird) 15. hydra_zen_joblib_multi_gpu]$ ls mlruns/
0

[s.1915438@scs2043(sunbird) 15. hydra_zen_joblib_multi_gpu]$ ls mlruns/0
0f4f67841fb346d69f78834c5640f78b  538672bf8c7844519934d1e117fc29fb  7e66ad8a00d141a081d0533d048ab291  adbef3da2b9d40e7881177554c7e7f9f  e764a7288f64487ebedd79bdaa71bd5d
12895799c26044bb9370d4ecefa49ddb  5a91dc5a62f542089805814bd6bb723b  8599b76e645944ab922e06a05d8fc8f0  afa9e83deccb444881a708485abb04c0  ef648994cd1f4e0fbda8e0acc16bb64a
30943fa36a6c4529be20d10d853323f3  5aeff665cc7f41ad9c775979cbf3f2ed  85a5697428924bed8270c2280385a0b6  b09d25d3fd574018bab5340abbb76902  f805a34276cc473590250ed19834b641
33b521ff465a4e48929eb413d2d4f653  6710ca36590b4d22b07f311765ffaeac  8b7e147af8af4e7e8fff6d754d387185  b2843afc7bb448fcb3bf7afd4b9a80b8  ff3ddd82da7e46c8ab457ac917e82428
366d20214b8a47cb89badb9fe5541cb0  683edf102f674cbf8eaa653f2a14a64a  93e2c3fa423f4e93b86862eee18299c1  bfc7a2014bc3475fa9160797786128b1  meta.yaml
3eefafe74c4d498dbef223adaa0587d2  6bc3336d10b449aca6b2a033049efda5  98c35257d231468c90034d7666419820  cb4892fc86a346c4b5bc8a0b27c50b5d
4457ec3b8f4f4eaf9bcb798639207bf8  6ca948723ac24ae3818b0082a4ea21e4  9953b1817b204b858d48b2c078159322  d1f09513244b494d9ab13e79e83ad086
4ce66b5165ce45e6bf81bc1dd0a9000a  7e55334301c14952a26b249c2982a094  9ebf68264a6f4ad18f344d4987c7e9d9  df3c4f383b4846e98fabb1aabbdb6a2c
```

I run the `mlflow ui` command in the same directory:
```sh
[s.1915438@scs2043(sunbird) 15. hydra_zen_joblib_multi_gpu]$ mlflow ui
[2022-11-22 10:28:35 +0000] [53484] [INFO] Starting gunicorn 20.1.0
[2022-11-22 10:28:35 +0000] [53484] [INFO] Listening at: http://127.0.0.1:5000 (53484)
[2022-11-22 10:28:35 +0000] [53484] [INFO] Using worker: sync
[2022-11-22 10:28:35 +0000] [53485] [INFO] Booting worker with pid: 53485
```

It shows me 5 days old training results from another directory:

![image](https://user-images.githubusercontent.com/70601302/203293257-b08a0a65-2e2f-4496-836d-a1df090f94f7.png)

I also tried the `mlflow ui --backend-store-uri /path/to/my/directory` from [this](https://github.com/mlflow/mlflow/issues/1755#issuecomment-523115772) answer. I also used the "new experiment" option in the `mlflow ui`. Both shows no runs.

![image](https://user-images.githubusercontent.com/70601302/203294188-d7330dba-9548-4a8a-b9c2-9154ab0868d3.png)

BTW the location to the `mlruns` directory (`/scratch/s.1915438/2. inverse+forward/15. hydra_zen_joblib_multi_gpu`) contains spaces.   So I enclosed the path within a " ".

**Comment by harupy** [comment]
Hi @praksharma, can you run `env | grep MLFLOW_BACKEND_STORE_URI` to see whether `MLFLOW_BACKEND_STORE_URI` is set or not?

**Comment by praksharma** [comment]
Hi, it is empty.

```sh
[s.1915438@scs2043(sunbird) 15. hydra_zen_joblib_multi_gpu]$ env | grep MLFLOW_BACKEND_STORE_URI
[s.1915438@scs2043(sunbird) 15. hydra_zen_joblib_multi_gpu]$ 
```

**Comment by praksharma** [comment]
Is there some sort of cache which it loads by default? I check the hidden files. Nothing there.

**Comment by harupy** [comment]
No, there isn't.

**Comment by harupy** [comment]
@praksharma 

> still it shows me the same 5 days old training from a different directory.

What is the relative path to the different directory from your working directory?

**Comment by praksharma** [comment]
The one starting with `10.` is the 5 days older results. The one starting with `15.` is my directory of interest.
```
[s.1915438@scs2043(sunbird) 2. inverse+forward]$ ls
10. mlflow and hydra         13. Optuna multiple best value using Hydra Zen   15. hydra_zen_joblib_multi_gpu  4. one inverse model               7. working
11. hydra + mlflow + optuna  14. Joblib_parallel_standard                     2. logging                      5. Hydra conf + inverse            8. conf with dictionary
12. Horovod                  1. 5 data points                                 3. Hyda hyperparamter tuning    6. inverse + logger (not working)  9. multi gpu submitit
```

One more thing, I just found in this directory `10. mlflow and hydra `, mlflow is creating a new directory each time I create a new experiment in `mlflow ui` alongside the existing one created 5 days ago.

```sh
[s.1915438@scs2043(sunbird) 2. inverse+forward]$ cd 10.\ mlflow\ and\ hydra/
[s.1915438@scs2043(sunbird) 10. mlflow and hydra]$ cd mlruns/
[s.1915438@scs2043(sunbird) mlruns]$ ls
0  5
[s.1915438@scs2043(sunbird) mlruns]$ ls 5
meta.yaml
[s.1915438@scs2043(sunbird) mlruns]$ cat 5/meta.yaml 
artifact_location: file:///scratch/s.1915438/2.%20inverse%2Bforward/15.%20hydra_zen_joblib_multi_gpu/mlruns/0/09d31d5799924d6fae0285debe29819f/artifacts
creation_time: 1669116148391
experiment_id: '5'
last_update_time: 1669116148391
lifecycle_stage: active
name: new_1
```

This is weird.

**Comment by harupy** [comment]
@praksharma Can you create an empty directory, move in the directory, run `mlflow server`, and open `http://127.0.0.1:5000`?

**Comment by harupy** [comment]
Have you run a tracking server against `10. mlflow and hydra ` before?

**Comment by praksharma** [comment]
Sorry, I don't remember. How do I revert it and make things normal?

**Comment by harupy** [comment]
Can you try running `pkill -f mlflow`?

**Comment by harupy** [comment]
> I finally deleted this folder 10. mlflow and hydra . Now I can't use mlflow ui. It says "Something went wrong".


This indicates there is a tracking server running against

**Comment by praksharma** [comment]
Thank you so much. I can finally see the training in action.

![image](https://user-images.githubusercontent.com/70601302/203311707-03868493-c5e6-487c-af5b-0d03955cd974.png)

**Comment by harupy** [comment]
What was the cause?

**Comment by praksharma** [comment]
Looks like a server was running in the backend. This one worked `pkill -f mlflow`.

**Comment by praksharma** [comment]
So, I was using an HPC cluster not local PC. There are multiple login nodes with its own set of ports. It was running on `sl1` port 5000. I was using `sl2` port 5000. The problem is when I was port forwarding the port 5000 to my local PC I was not specifying the login node, so connects me to the `sl1` port 5000. I will just make sure that I port forward from within the same login node. Also, I will use a different port using `mlflow ui --port <PORT>`. This command is useful preventive measure `pkill -f mlflow`.

**Comment by harupy** [comment]
Makes sense. Thanks for the reply :)
