### ISSUE TITLE
html support on web view

### ISSUE THREAD

**Issue by DorIndivo** [mlflow/mlflow#738]
Hey Contributors!
I saved plotly/bokeh html plots files as artifacts on the mllfow server and I notice that there is only 'txt' and 'png' support (on the web view).
I think that the html support is great feature, and a simple iframe can be used in order to achieve this task.
Thx

**Comment by zmabzug** [comment]
Has there been any comment on this? It would be great to render HTML artifacts!

**Comment by patryk-oleniuk** [comment]
I just started using MLflow. As @zmabzug described above, I'm also saving html plots as experiment artifacts. Would love to see it rendering on the experiment web view.

**Comment by sim-san** [comment]
Such a feature would be very helpful and would make working with MLFlow even more efficient.

**Comment by pogil** [comment]
We've released the HTML viewer in MLflow 1.3 provided in #1838
