### ISSUE TITLE
Change version number of model manually

### ISSUE THREAD

**Issue by Voigt1022** [mlflow/mlflow#7397]
Can I set version number of model to whatever string I want to set? 
Or it have to be version1.0, version 2.0 ... generated by MLflow automatically?

**Comment by WeichenXu123** [comment]
No, you can't.
See https://github.com/mlflow/mlflow/blob/9c38bd649fe33cf9d2d48316fddc2bb24d765e7c/mlflow/utils/validation.py#L347

But, you can append a version tag to store any string you like. :)
