### ISSUE TITLE
[BUG][Warning][MlflowException] Changing param values is not allowed.

### ISSUE THREAD

**Issue by tsungjung411** [mlflow/mlflow#7402]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow: 1.29.0
- Client: (how to query it?)
- Tracking server: (how to query it?)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Python version**: 3.8.10
- **yarn version, if running the dev UI**:

#### Scenario 
LightGBM + Scikit-learn's pipeline (for data preprocessing)
```python
clf = LGBMClassifier()
clf = make_pipeline(clf)
clf.fit(train_X, train_y)
```
but there is an unexpected exception that a parameter with key='verbose' is already logged. (100% reproducible) (see the exception below)

<br>

#### MlflowException
- #### if the sklearn's pipeline precedes LGBMClassifier (reproducible: 29/30 )
  > 2022/11/25 11:45:17 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during lightgbm autologging: The following failures occurred while performing one or more logging operations:  [MlflowException('Failed to perform one or more operations on the run with ID 68e5d682e86d4afaa34cb71f728a759d. Failed operations: [MlflowException("Changing param values is not allowed. **Param with key=\'verbose\' was already logged with value=\'False\' for run ID=\'68e5d682e86d4afaa34cb71f728a759d\'. Attempted logging new value \'-1\'.**")]')]
Pipeline(steps=[('lgbmclassifier', LGBMClassifier())])

- #### if LGBMClassifier precedes the sklearn's pipeline (reproducible: 1/30 )
  > 2022/11/25 15:58:31 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The following failures occurred while performing one or more logging operations: [MlflowException('Failed to perform one or more operations on the run with ID f642171dc7fe4c9ab470f4e2fd323fc9. Failed operations: [MlflowException("Changing param values is not allowed. **Param with key=\'verbose\' was already logged with value=\'-1\' for run ID=\'f642171dc7fe4c9ab470f4e2fd323fc9\'. Attempted logging new value \'False\'.**")]')]
Pipeline(steps=[('lgbmclassifier', LGBMClassifier())])
  ![image](https://user-images.githubusercontent.com/14820019/203935542-0e788933-90bf-402f-9c94-050f970ace1b.png)

<br>

### Root Cause
- The sklearn's pipeline precedes LGBMClassifier.
   - The sklearn's pipeline gets parameters from the LGBMClassifier object, where `verbose` is `False`
      - I guess: `-1` should be the value used internally, `False` should be the value used externally
      - i.e. LGBMClassifier has a value of `-1` inside and `False` outside
- Sometimes LGBMClassifier precedes the sklearn's pipeline.
   -  that is, there are `log_params` competitions between mlflow.sklearn and mlflow.lightgbm
- There is a `fit` API in the sklearn's pipeline, so `verbose: False` is logged first.
- There is a `fit` API in the LGBMClassifier object, so `verbose: -1` is logged later.
- This is why the the param with key=`verbose` are logged twice.

### Tracking information

MLflow version: 1.29.0
Tracking URI: file:///mlruns
Artifact URI: file:///mlruns/0/ad371fb0485c4c4cb7bb7b281bf10053/artifacts

#### Required Packages
```bash
# mlflow(mlflow.utils.git_utils) requires git SHA
apt-get update
apt-get install -y git

# mlflow compatibility: "mlflow==1.29.0", "lightgbm==3.3.2", "scikit-learn==1.1.2"
# matplotlib: for mlflow tasks, lightgbm requires to log feature importance plot
pip install "lightgbm==3.3.2" "scikit-learn==1.1.2" matplotlib
pip install "mlflow==1.29.0" "requests>=2.26.0" "urllib3>=1.26.0"
```

<br>

#### Print more logs for mllfow
```
mlflow/utils/autologging_utils/client.py:176:
    def log_params(self, run_id: Union[str, PendingRunId], params: Dict[str, Any]) -> None:
```
add the code below to `mlflow/utils/autologging_utils/client.py#177`
```
print('[DEBUG] run_id:', run_id, ', params:', params)
```
![image](https://user-images.githubusercontent.com/14820019/203896999-6cef3ac4-b71a-4a6d-a36f-98e9d0aef484.png)

<br>

#### Python Code
```python
# import packages
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from lightgbm import LGBMClassifier

import mlflow
import os

# load dataset
iris = load_iris()
train_X, test_X, train_y, test_y = train_test_split(iris.data, iris.target, stratify=iris.target)

# start to train
mlflow.autolog()
clf = LGBMClassifier()
clf = make_pipeline(clf)
clf.fit(train_X, train_y)
mlflow.end_run()
```

### Stack trace

2022/11/25 11:45:17 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.

2022/11/25 11:45:17 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.

2022/11/25 11:45:17 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '68e5d682e86d4afaa34cb71f728a759d', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

[DEBUG] run_id: 68e5d682e86d4afaa34cb71f728a759d , params: {'memory': None, 'steps': [('lgbmclassifier', LGBMClassifier())], 'verbose': False, 'lgbmclassifier': LGBMClassifier(), 'lgbmclassifier__boosting_type': 'gbdt', 'lgbmclassifier__class_weight': None, 'lgbmclassifier__colsample_bytree': 1.0, 'lgbmclassifier__importance_type': 'split', 'lgbmclassifier__learning_rate': 0.1, 'lgbmclassifier__max_depth': -1, 'lgbmclassifier__min_child_samples': 20, 'lgbmclassifier__min_child_weight': 0.001, 'lgbmclassifier__min_split_gain': 0.0, 'lgbmclassifier__n_estimators': 100, 'lgbmclassifier__n_jobs': -1, 'lgbmclassifier__num_leaves': 31, 'lgbmclassifier__objective': None, 'lgbmclassifier__random_state': None, 'lgbmclassifier__reg_alpha': 0.0, 'lgbmclassifier__reg_lambda': 0.0, 'lgbmclassifier__silent': 'warn', 'lgbmclassifier__subsample': 1.0, 'lgbmclassifier__subsample_for_bin': 200000, 'lgbmclassifier__subsample_freq': 0}

[DEBUG] run_id: 68e5d682e86d4afaa34cb71f728a759d , params: {'boosting_type': 'gbdt', 'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_jobs': -1, 'num_leaves': 31, 'random_state': None, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0, 'verbose': -1, 'num_class': 3, 'objective': 'multiclass', 'metric': ['multiclass']}

[DEBUG] run_id: 68e5d682e86d4afaa34cb71f728a759d , params: {'num_boost_round': 100, 'feature_name': 'auto', 'categorical_feature': 'auto', 'early_stopping_rounds': None, 'evals_result': None, 'verbose_eval': 'warn', 'keep_training_booster': False}

2022/11/25 11:45:17 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during lightgbm autologging: The following failures occurred while performing one or more logging operations: [MlflowException('Failed to perform one or more operations on the run with ID 68e5d682e86d4afaa34cb71f728a759d. Failed operations: [MlflowException("Changing param values is not allowed. **Param with key=\'verbose\' was already logged with value=\'False\' for run ID=\'68e5d682e86d4afaa34cb71f728a759d\'. Attempted logging new value \'-1\'**.")]')]
Pipeline(steps=[('lgbmclassifier', LGBMClassifier())])

---

if LGBMClassifier precedes the sklearn's pipeline, the last message will become:

2022/11/25 15:58:31 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The following failures occurred while performing one or more logging operations: [MlflowException('Failed to perform one or more operations on the run with ID f642171dc7fe4c9ab470f4e2fd323fc9. Failed operations: [MlflowException("Changing param values is not allowed. **Param with key=\'verbose\' was already logged with value=\'-1\' for run ID=\'f642171dc7fe4c9ab470f4e2fd323fc9\'. Attempted logging new value \'False\'**.")]')]
Pipeline(steps=[('lgbmclassifier', LGBMClassifier())])

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by tsungjung411** [comment]
## stack trace for 2nd `log_params`
[[lightgbm][native] lightgbm+iris+mlflow-log_params-2nd.zip](https://github.com/mlflow/mlflow/files/10090304/lightgbm.native.lightgbm%2Biris%2Bmlflow-log_params-2nd.zip)

## stack trace for 3rd `log_params()`
[[lightgbm][native] lightgbm+iris+mlflow-log_params-3rd.zip](https://github.com/mlflow/mlflow/files/10090311/lightgbm.native.lightgbm%2Biris%2Bmlflow-log_params-3rd.zip)

**Comment by WeichenXu123** [comment]
Thank you for reporting the bug. I just reproduced it. I will file fix soon.

**Comment by WeichenXu123** [comment]
According to correct design, mlflow should skip logging the nested estimator in pipeline, but this case it does not skip it. It is a bug. Let me fix it.

**Comment by harupy** [comment]
@tsungjung411 It looks like enabling both `lightgbm` and `sklearn` autologging causes this issue. You can avoid the issue by enabling only sklearn autologging.

**Comment by WeichenXu123** [comment]
> You can avoid the issue by enabling only sklearn autologging.

This causes another issue, if solely run `LGBMClassifier.fit`, the `parameter, metric, and non-model artifact` won't be logged.

**Comment by harupy** [comment]
> This causes another issue, if solely run LGBMClassifier.fit, the parameter, metric, and non-model artifact won't be logged.

sklearn autologging should only enable logging for sklearn's estimators.

**Comment by harupy** [comment]
Fix to suppress the error:

```diff
diff --git a/mlflow/lightgbm.py b/mlflow/lightgbm.py
index 02bb5dbbe..40329cc17 100644
--- a/mlflow/lightgbm.py
+++ b/mlflow/lightgbm.py
@@ -483,6 +483,15 @@ def autolog(
         original(self, *args, **kwargs)
 
     def train(_log_models, original, *args, **kwargs):
+        from mlflow.sklearn import _SklearnTrainingSession
+
+        if any(
+            x.clazz.__module__.startswith("lightgbm")
+            for x in _SklearnTrainingSession._session_stack
+        ):
+            return
+        traceback.print_stack()
+
         def record_eval_results(eval_results, metrics_logger):
             """
             Create a callback function that records evaluation results.
diff --git a/mlflow/sklearn/utils.py b/mlflow/sklearn/utils.py
index 18b85a5e0..cea338cbd 100644
--- a/mlflow/sklearn/utils.py
+++ b/mlflow/sklearn/utils.py
@@ -57,6 +57,7 @@ def _gen_lightgbm_sklearn_estimators_to_patch():
             package_name == mlflow.lightgbm.FLAVOR_NAME
             and issubclass(class_object, base_class)
             and class_object != base_class
+            and class_object is not lgb.sklearn.LGBMModel
         ):
             sklearn_estimators.append(class_object)
```

**Comment by WeichenXu123** [comment]
```
diff --git a/mlflow/sklearn/utils.py b/mlflow/sklearn/utils.py
index 18b85a5e0..cea338cbd 100644
--- a/mlflow/sklearn/utils.py
+++ b/mlflow/sklearn/utils.py
@@ -57,6 +57,7 @@ def _gen_lightgbm_sklearn_estimators_to_patch():
             package_name == mlflow.lightgbm.FLAVOR_NAME
             and issubclass(class_object, base_class)
             and class_object != base_class
+            and class_object is not lgb.sklearn.LGBMModel
         ):
             sklearn_estimators.append(class_object)
```

This has an issue, LGBMModel is a public estimator class, we should patch autologging for it, and in previous version we already do autologging for it.

**Comment by harupy** [comment]
Ok, I thought LGBMModel is a base class. Remove it.

**Comment by tsungjung411** [comment]
> @tsungjung411 It looks like enabling both `lightgbm` and `sklearn` autologging causes this issue. You can avoid the issue by enabling only sklearn autologging.
> 
> ```python
> from sklearn.datasets import load_iris
> from sklearn.model_selection import train_test_split
> from sklearn.pipeline import make_pipeline
> from lightgbm import LGBMClassifier
> 
> import mlflow
> 
> # load dataset
> iris = load_iris()
> train_X, test_X, train_y, test_y = train_test_split(iris.data, iris.target, stratify=iris.target)
> 
> # start to train
> # mlflow.autolog()
> mlflow.sklearn.autolog()
> clf = LGBMClassifier()
> clf = make_pipeline(clf)
> print(clf)
> with mlflow.start_run():
>     clf.fit(train_X, train_y)
> ```

In our computing container, we installed sklearn, xgboost, lightgbm, autosklearn(AutoML), autogluon (AutoML). Following your recommendations, we should only enable `sklearn` autologgining (call `mlflow.sklearn.autolog()`) no matter user's input ML algorithm (Xgboost, LightGBM, Autosklearn, AutoGluon, else: sklearn)

i.e.
- sklearn's pipeline + sklearn -> `mlflow.sklearn.autolog()`
- sklearn's pipeline + xgboost -> `mlflow.sklearn.autolog()`
- sklearn's pipeline + lightgbm -> `mlflow.sklearn.autolog()`
- sklearn's pipeline + autosklearn -> `mlflow.sklearn.autolog()`
- sklearn's pipeline + autogluon -> `mlflow.sklearn.autolog()`

How about the cases blow: 
**sklearn's pipeline + autosklearn?**
Both of them belong to sklearn.
```
clf = RandomForestClassifier()
clf = make_pipeline( label-to-id, imputer, standard-scaler, ..., clf)   # plain text explanation
```

**sklearn's pipeline + autogluon?**
Some ML algorithms in autogluon belong to sklearn, such as RF(random forest), XT(extremely randomized trees), KNN(k-nearest neighbors), LR(linear regression).
```
from autogluon.tabular import TabularPredictor
clf = TabularPredictor(...)  # will include RF, XT, KNN
clf = make_pipeline( label-to-id, imputer, standard-scaler, ..., clf)   # plain text explanation
```

Both cases should cause nested logging (?)

**Comment by tsungjung411** [comment]
### For the case: **sklearn's pipeline + autosklearn**

### Full code
```python
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from autosklearn.classification import AutoSklearnClassifier

import mlflow
import cloudpickle

X, y = load_iris(return_X_y=True)
train_X, test_X, train_y, test_y = train_test_split(X, y)

params = {}
params['memory_limit'] = 1024 * 12 # (in MB) (default: 3072 MB)
params['time_left_for_this_task'] = 30
params['per_run_time_limit'] = 15

# mlflow.autolog() precedes `import AutoSklearnClassifier` will fail to write a pickle
mlflow.autolog()

clf = AutoSklearnClassifier(**params)
clf = make_pipeline(clf)  # 使用＆不使用 pipeline
clf.fit(train_X, train_y)

with open('iris.pkl', 'wb') as f:
    model_in_bytes = cloudpickle.dumps(clf)
    f.write(model_in_bytes)

print('training: done')

with open('iris.pkl', 'rb') as f:
    model_in_bytes = f.read()
    clf2 = cloudpickle.loads(model_in_bytes)

print('model: ', clf2)
print('pred_y:', clf2.predict(test_X))
print('true_y:', test_y)
print('score:', clf.score(test_X, test_y))

ask = clf2.steps[0][1]
print(ask.sprint_statistics())
```

![image](https://user-images.githubusercontent.com/14820019/204487229-65bf1251-f2ed-45ab-a860-2de16b2be656.png)

![image](https://user-images.githubusercontent.com/14820019/204487157-3e8f558d-c7f8-4fff-a3d4-48c2d06511a0.png)

It works fine. No nested logging found.

**Comment by tsungjung411** [comment]
### For the case: **sklearn's pipeline + autosklearn**
```
mlflow.sklearn.autolog()
```

#### Full code
```python
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline

from pandas import DataFrame
from autogluon.tabular import TabularPredictor

import mlflow
import cloudpickle

iris = load_iris()
train_X, test_X, train_y, test_y = train_test_split(iris.data, iris.target, stratify=iris.target)
train_Xy = DataFrame(train_X, columns=iris.feature_names)
train_Xy['target'] = train_y
test_Xy = DataFrame(test_X, columns=iris.feature_names)
test_Xy['target'] = test_y

mlflow.sklearn.autolog()

clf = TabularPredictor(label='target')
clf = make_pipeline(clf)

# autogluon requires X & y
# - if there is no target column in X, autogluon will raise an exception
# - this is just demo code for mlflow testing
clf.fit(train_Xy)
```
![image](https://user-images.githubusercontent.com/14820019/204505930-957824de-07f3-4634-8357-b414d4912432.png)

It works fine. No nested logging found.

But there are no AutoGluon parameters in the pipeline. I thought AutoGluon does not implement `get_param` and `set_params`(?), so mlflow could not fill the AutoGluon parameters in the pipeline.(?)

**Comment by WeichenXu123** [comment]
> But there are no AutoGluon parameters in the pipeline. I thought AutoGluon does not implement get_param and set_params

This should be a separate issue. You can file another ticket. It probably because it does not implement `get_param` interface.
