### ISSUE TITLE
[BUG] Even with 'Only show differences' turned on, all columns are displayed

### ISSUE THREAD

**Issue by Nika-St** [mlflow/mlflow#7412]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.1
- **Python version**: 3.10.6
- **yarn version, if running the dev UI**:

### Describe the problem

Even with 'Only show differences' turned on, all columns are displayed. Maybe this filter applies to all runs in the current experiment and not only the ones displayed (selected using 'Start time', 'Search' or other Filters). I believe the point is however  to hide columns with identical values for the runs displayed and not all runs ever logged
<img width="593" alt="2022-11-28" src="https://user-images.githubusercontent.com/29167311/204299284-b66335da-07da-4ba1-bf69-477e8b7c33dc.png">

### Steps to reproduce the bug

Select runs, e.g. from the 'Last 24 hours'
Toggle 'Only show differences'

Columns with all identical values are still shown

**Comment by harupy** [comment]
@Nika-St We removed the `Only show differences` switch in MLflow 2.0.

**Comment by Nika-St** [comment]
Oh no....

**Comment by ReHoss** [comment]
Button disappeared on v2.0 ........

**Comment by ReHoss** [comment]
> @Nika-St We removed the `Only show differences` switch in MLflow 2.0.

Could you please explain why, I am about to downgrade to 1.x for this reason ?

Kind regards,
