### ISSUE TITLE
[FR] Add Python fluent API for search_registered_models

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#7416]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Introduce a Python API for search_registered_models:

```
mlflow.search_registered_models(filter_string: Optional[str] = None, max_results: int = 100, order_by: Optional[List[str]] = None)
```

### Motivation

> #### What is the use case for this feature?

Help users easily search registered models without having to handle pagination

> #### Why is this use case valuable to support for MLflow users in general? ^ 

> #### Why is this use case valuable to support for your project(s) or organization? ^ 

> #### Why is it currently difficult to achieve this use case? Users must rely on the https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_registered_models API, which requires them to handle page tokens manually

### Details

The API should be implemented in https://github.com/mlflow/mlflow/blob/7f2152370b8e93ed7bf8cc3e5e1e7ff39cd69ca5/mlflow/tracking/fluent.py

The only difference between this API and https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_registered_models is that it should automatically handle pagination: instead of including a `page_token` argument, the API should 1. call https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_registered_models, 2. retrieve the page token from the PagedList, 3. Call https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_registered_models with the page token and append the results to the previous PagedList, 4. Continue until https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_registered_models no longer returns a page token.

For reference, see https://github.com/mlflow/mlflow/blob/7f2152370b8e93ed7bf8cc3e5e1e7ff39cd69ca5/mlflow/tracking/fluent.py#L1154-L1167. MLflow provides a utility to help with pagination: https://github.com/mlflow/mlflow/blob/7f2152370b8e93ed7bf8cc3e5e1e7ff39cd69ca5/mlflow/utils/__init__.py#L224.

We can add some simple tests to https://github.com/mlflow/mlflow/blob/master/tests/tracking/fluent/test_fluent.py.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by TSienki** [comment]
I'll try this one

**Comment by dbczumar** [comment]
> I'll try this one

Thank you, @TSienki ! I've assigned the issue to you. Please let me know if you have any questions!

**Comment by TSienki** [comment]
@dbczumar  I created a PR earlier, but doing this change I come up with one question. 
 I've found out that `search_experiments` (without specifying order) returns records (experiments here) ordered reversed to the order of inserting. On the other hand, `search_registered_models` returns records (registered models here) sorted alphabetically. 
Is it intended behavior? IMO, The default behavior for fetching entities from the database should be consistent. 

Related code: 
```python
import mlflow
from mlflow import MlflowClient

sqlite_uri = "http://127.0.0.1:5001"
mlflow.set_tracking_uri(sqlite_uri)
l = list(range(30))
l = l[:5] + l[15:25] + l[5:15] + l[25:]

for i in l:
    mlflow.create_experiment(f"experiment_{i}")
    MlflowClient().create_registered_model(f"model_{i}")

experiments = mlflow.search_experiments()
print("-" * 64)
print([experiment.name for experiment in experiments])

models = mlflow.search_registered_models()
print("-" * 64)
print([model.name for model in models])
```
Results:
```
----------------------------------------------------------------
['experiment_29', 'experiment_28', 'experiment_27', 'experiment_26', 'experiment_25', 'experiment_14', 'experiment_13', 'experiment_12', 'experiment_11', 'experiment_10', 'experiment_9', 'experiment_8', 'experiment_7', 'experiment_6', 'experiment_5', 'experiment_24', 'experiment_23', 'experiment_22', 'experiment_21', 'experiment_20', 'experiment_19', 'experiment_18', 'experiment_17', 'experiment_16', 'experiment_15', 'experiment_4', 'experiment_3', 'experiment_2', 'experiment_1', 'experiment_0', 'Default']
----------------------------------------------------------------
['model_0', 'model_1', 'model_10', 'model_11', 'model_12', 'model_13', 'model_14', 'model_15', 'model_16', 'model_17', 'model_18', 'model_19', 'model_2', 'model_20', 'model_21', 'model_22', 'model_23', 'model_24', 'model_25', 'model_26', 'model_27', 'model_28', 'model_29', 'model_3', 'model_4', 'model_5', 'model_6', 'model_7', 'model_8', 'model_9']

```

**Comment by harupy** [comment]
@TSienki @dbczumar 

> Is it intended behavior?

Yes, the default ordering is `["creation_time DESC", "experiment_id ASC"]` (`experiment_id` is a tiebreaker) to list newer experiments first.
