### ISSUE TITLE
[BUG] downloading directories with many subdirectories using SFTP causes deadlock

### ISSUE THREAD

**Issue by LieberwirthF** [mlflow/mlflow#7422]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.0.1
- Tracking server: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux 6.0.10-arch2-1
- **Python version**: 3.10.8
- **yarn version, if running the dev UI**: -

### Describe the problem

Downloading a directory with a high (my tests required >=32) amount of subdirectories causes a deadlock using sftp artifact storage. 
This Issue seems to be related to #5656. 

### Tracking information

Tracking Server Command: 
`mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///home/<user>/server/db.sqlite --default-artifact-root sftp://<user>@<ip>:/home/<user>/experiments`

Tracking information:
`System information: Linux #1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000`
`Python version: 3.10.8`
`MLflow version: 2.0.1`
`MLflow module location: /home/<user>/<repo>/.venv/lib/python3.10/site-packages/mlflow/__init__.py`
`Tracking URI: http://<ip>:5000`
`Registry URI: http://<ip>:5000`
`MLflow environment variables: {
    "MLFLOW_TRACKING_URI": "http://<ip>:5000"
}`
`MLflow dependencies: {
    "click": "8.1.3",
    "cloudpickle": "2.2.0",
    "databricks-cli": "0.17.3",
    "entrypoints": "0.4",
    "gitpython": "3.1.29",
    "pyyaml": "6.0",
    "protobuf": "3.19.6",
    "pytz": "2022.6",
    "requests": "2.28.1",
    "packaging": "21.3",
    "importlib-metadata": "5.0.0",
    "sqlparse": "0.4.3",
    "alembic": "1.8.1",
    "docker": "6.0.1",
    "Flask": "2.2.2",
    "numpy": "1.23.3",
    "scipy": "1.9.1",
    "pandas": "1.5.1",
    "querystring-parser": "1.2.4",
    "sqlalchemy": "1.4.43",
    "scikit-learn": "1.1.2",
    "pyarrow": "10.0.1",
    "shap": "0.41.0",
    "markdown": "3.4.1",
    "matplotlib": "3.6.0",
    "gunicorn": "20.1.0",
    "Jinja2": "3.1.2"
}`

### Code to reproduce issue

**Working**:
```python
import numpy as np
import mlflow
run_id = None

experiment = mlflow.get_experiment_by_name("test_mlflow")

with mlflow.start_run(experiment_id=experiment.experiment_id, run_name="test sftp") as run:
    run_id = run.info.run_id
    
    random_images = np.random.randint(0, 256, size=(32, 500, 500, 3), dtype=np.uint8)
    
    for i in range(random_images.shape[0]):
        mlflow.log_image(random_images[i], f"images/{i}.png")

print("downloading")
images_path = mlflow.artifacts.download_artifacts(run_id=run_id, artifact_path="images")

print(images_path)
```

**Not Working**:
mind the line logging each image in a subdirectory 
```python
mlflow.log_image(random_images[i], f"images/{i}/{i}.png")
```
```python
import numpy as np
import mlflow
run_id = None

experiment = mlflow.get_experiment_by_name("test_mlflow")

with mlflow.start_run(experiment_id=experiment.experiment_id, run_name="test sftp") as run:
    run_id = run.info.run_id
    
    random_images = np.random.randint(0, 256, size=(32, 500, 500, 3), dtype=np.uint8)
    
    for i in range(random_images.shape[0]):
        mlflow.log_image(random_images[i], f"images/{i}/{i}.png")

print("downloading")
images_path = mlflow.artifacts.download_artifacts(run_id=run_id, artifact_path="images")

print(images_path)

```

### Stack trace

Interrupting deadlock:

```
Traceback (most recent call last):
  File "/home/<user>/<repo>/test_mlflow.py", line 17, in <module>
    
  File "/home/<user>/<repo>/.venv/lib/python3.10/site-packages/mlflow/artifacts/__init__.py", line 63, in download_artifacts
    artifact_location = artifact_repo.download_artifacts(artifact_path, dst_path=dst_path)
  File "/home/<user>/<repo>/.venv/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repo.py", line 240, in download_artifacts
    dst_local_path, inflight_downloads = async_download_artifact_dir(
  File "/home/<user>/<repo>/.venv/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repo.py", line 206, in async_download_artifact_dir
    inflight_downloads += async_download_artifact_dir(
  File "/home/<user>/<repo>/.venv/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repo.py", line 197, in async_download_artifact_dir
    for file_info in self.list_artifacts(src_artifact_dir_path)
  File "/home/<user>/<repo>/.venv/lib/python3.10/site-packages/mlflow/store/artifact/sftp_artifact_repo.py", line 111, in list_artifacts
    with self.pool.get_sfp_connection() as sftp:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/<user>/<repo>/.venv/lib/python3.10/site-packages/mlflow/store/artifact/sftp_artifact_repo.py", line 33, in get_sfp_connection
    self._cond.wait_for(lambda: bool(self._connections))
  File "/usr/lib/python3.10/threading.py", line 355, in wait_for
    self.wait(waittime)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@LieberwirthF Thanks for reporting the issue. I'll take a look tomorrow.
