### ISSUE TITLE
Saving logs (metrics, params, artifacts) in azure blob storage

### ISSUE THREAD

**Issue by Azadehkhojandi** [mlflow/mlflow#744]
mlflow server  --default-artifact-root wasbs://xmlflowcontainerx@xmlflowrunsx.blob.core.windows.net/  --host 0.0.0.0

only saves artefacts inside the blob, is it possible to add a flag to install metrics, prams inside the container as well?

**Comment by mparkhe** [comment]
Hi @Azadehkhojandi : `mlflow server` has a `--file-store PATH` argument. This is the root for file storage for experiments and run data. If unspecified the default which is `./mlruns` on your local machine is used to store this data.
