### ISSUE TITLE
[BUG] SVG displaying issue

### ISSUE THREAD

**Issue by diegodebrito** [mlflow/mlflow#7452]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Enterprise 21H2
- **Python version**: 3.10.8
- **yarn version, if running the dev UI**: Not using this

### Describe the problem

The UI is not displaying svg images (when saved as artifacts) anymore. This worked before I updated to MLflow 2.0.1, so not sure if intended or a regressions.

### Steps to reproduce the bug

![svg-not-displaying](https://user-images.githubusercontent.com/47297554/205711218-315eb0bb-4013-493f-b5a7-e4fbac512095.gif)

### Code to generate data required to reproduce the bug

``` python
import mlflow
import subprocess
import matplotlib.pyplot as plt
import numpy as np

# create sample svg image
fig, ax = plt.subplots()
xpoints = np.array([0, 5])
ypoints = np.array([0, 5])
plt.plot(xpoints, ypoints)

plt.ylabel("Y-axis ")
plt.xlabel("X-axis ")

image_format = 'svg'
image_name = 'myimage.svg'

fig.savefig(image_name, format=image_format, dpi=1200)

# start mlflow server and log image as an artifact
cmd = [
        "mlflow",
        "server",
        "--host",
        "localhost",
        "--port",
        "5000",
    ]

proc = subprocess.Popen(  # nosec docker
            cmd,
            stdin=subprocess.PIPE,
        )

mlflow.set_tracking_uri("http://localhost:5000")
exp = mlflow.set_experiment("svg-experiment")

with mlflow.start_run(experiment_id=exp.experiment_id):
    mlflow.log_artifact(image_name)

```

**Comment by harupy** [comment]
Hi @diegodebrito, we're aware of this issue. We'll create a patch for this issue before the next release.

**Comment by diegodebrito** [comment]
Thanks for the quick response, @harupy!
