### ISSUE TITLE
Convert `code-block` in `mlflow/tracking/fluent.py` to `test-code-block`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#7457]
Convert:

```
    .. code-block:: python

        # python code
```

to:

```
    .. test-code-block:: python

        # python code
```

## Motivation

- Ensure the code runs successfully.
- Prevent human errors when updating examples (e.g. removing a variable that shouldn't be removed).
- Reduce review cost. Currently, we need to copy code and run it locally, which is inconvenient.

## How to test

```shell
cd docs
make rsthtml  # should dump code blocks in `docs/.examples` as python scripts.
make test-examples
```

## Notes

- I believe most of the existing examples should work without any modifications.

## Additional info

- `test-code-block` was introduced in https://github.com/mlflow/mlflow/pull/7450.

**Comment by harupy** [comment]
@tsugumi-sys Are you interested in working on this?

**Comment by tsugumi-sys** [comment]
Yes! Please assign me :)

**Comment by harupy** [comment]
@tsugumi-sys Awesome!

**Comment by harupy** [comment]
When you file a PR, can you also update `docs/conftest.py` like this?

```diff
diff --git a/docs/conftest.py b/docs/conftest.py
index 5554688a2..ef0e553e3 100644
--- a/docs/conftest.py
+++ b/docs/conftest.py
@@ -7,3 +7,11 @@ def tracking_uri_mock(tmp_path, monkeypatch):
     tracking_uri = "sqlite:///{}".format(tmp_path / "mlruns.sqlite")
     mlflow.set_tracking_uri(tracking_uri)
     monkeypatch.setenv("MLFLOW_TRACKING_URI", tracking_uri)
+    yield
+    mlflow.set_tracking_uri(None)
+
+
+@pytest.fixture(autouse=True)
+def reset_active_experiment_id():
+    yield
+    mlflow.tracking.fluent._active_experiment_id = None
```
