### ISSUE TITLE
[BUG] Log_model required 'artifact_path' while 'default-artifact-root' of MLflow server was defined as an S3 storage

### ISSUE THREAD

**Issue by ann-lab52** [mlflow/mlflow#7460]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.29.0
- Tracking server: 1.29.0

### System information

- **OS Platform and Distribution**: Ubuntu 18.04.4 LTS
- **Python version**: 3.0.7
- **yarn version, if running the dev UI**: None

### Describe the problem

In our case, MLFlow server and ML experiments was run on the  same machine. When the MLFlow server deploy, the `default-artifact-root`  was defined as an `MLFLOW_S3_ENDPOINT_URL`. This mean  MLflow client will use the value provided by `--default-artifact-root` as default `artifact_path` following the third warning at [officials docs](https://www.mlflow.org/docs/latest/tracking.html#id13). This lead to an unexpected problem that when the we try to use [mlflow.pytorch.log_model()](https://www.mlflow.org/docs/latest/python_api/mlflow.pytorch.html?highlight=log_model#mlflow.pytorch.log_model), it required `artifact_path` must be passed some value although `artifact_path` value was provided by MLFlow Server. So we if try to pass something into `artifact_path` then 

> boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmpgwr6044u/model/python_env.yaml to /s3_url/value_of_artifact_path. An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

 will be raised. 

This problem made the our scientist who run ML experiments confused for a while and luckily it was solve by pass an **empty string** to `artifact_path`. However, I think there more efficient way to solve this problem, like remove required of `artifact_path`, accept the `None` value or add this special case as an warning to the document.

### Tracking information

**Example of CLI we used to run MLFlow server**
` mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri   sqlite://backend_store --default-artifact-root s3:///bucket/path: --serve-artifacts`

### Code to reproduce issue

**Example of an ML experiments we did:**
```
mlflow.set_tracking_uri('http://0.0.0.0:9696')
mlflow.set_experiment('S3_TEST')
os.environ['MLFLOW_S3_ENDPOINT_URL'] = 'https://s3.endpoint/'
os.environ['AWS_ACCESS_KEY_ID'] = 'key id'
os.environ['AWS_SECRET_ACCESS_KEY'] = 'secret key'
with mlflow.start_run():
            artifact_uri = mlflow.get_artifact_uri()
            # https://s3.endpoint/

            for epoch in run_experiment:
                train_some_model()
                mlflow.pytorch.log_model(self.model, artifact_path='required_some_value', registered_model_name="ModelName")
```
                

### Stack trace

> File "train_pipeline.py", line 150, in <module>
>     train_command()
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "train_pipeline.py", line 146, in train_command
>     train_obj.run(data_directory=data_dir, save_path=full_save_path)
>   File "train_pipeline.py", line 86, in run
>     mlflow.pytorch.log_model(self.model, artifact_path=artifact_uri, registered_model_name="OurModel")
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 321, in log_model
>     **kwargs,
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/mlflow/models/model.py", line 373, in log
>     mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 811, in log_artifacts
>     MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/mlflow/tracking/client.py", line 1117, in log_artifacts
>     self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 431, in log_artifacts
>     self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 146, in log_artifacts
>     key=posixpath.join(upload_path, f),
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 118, in _upload_file
>     s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
>     callback=Callback,
>   File "/apps/conda/envs/kube/lib/python3.7/site-packages/boto3/s3/transfer.py", line 296, in upload_file
>     filename, '/'.join([bucket, key]), e
> boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmpgwr6044u/model/python_env.yaml to bucket/1/825051e047fb4b779315e218f336ffcd/artifacts/s3://bucket/1/825051e047fb4b779315e218f336ffcd/artifacts/python_env.yaml: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@ann-lab52 

> This mean MLflow client will use the value provided by --default-artifact-root as default `artifact_path`.

`--default-artifact-root` represents the **_root_** artifact directory. The artifact destination is represented by `<default_artifact_root>/<experiment_id>/<run_id>/<artifact_path>`

**Comment by harupy** [comment]
> botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

Are you sure your AWS credentials are valid?

**Comment by ann-lab52** [comment]
> > botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
> 
> Are you sure your AWS credentials are valid?

Yes it is. There's no problem with the AWS credentials. Like I said, this problem was solve by parsing an empty string into `artifact_path`.

**Comment by ann-lab52** [comment]
> @ann-lab52
> 
> > This mean MLflow client will use the value provided by --default-artifact-root as default `artifact_path`.
> 
> `--default-artifact-root` represents the **_root_** artifact directory. The artifact destination is expressed as `<default_artifact_root>/<experiment_id>/<run_id>/<artifact_path>`

Yes, I got it. However this is the quote of the document's warning that I was mentioned:

> The MLflow tracking server utilizes specific reserved keywords to generate a qualified path. These environment configurations, if present in the client environment, can create path resolution issues. For example, providing --default-artifact-root $MLFLOW_S3_ENDPOINT_URL on the server side and MLFLOW_S3_ENDPOINT_URL on the client side will create a client path resolution issue for the artifact storage location. Upon resolving the artifact storage location, the MLflow client will use the value provided by --default-artifact-root and suffixes the location with the values provided in the environment variable MLFLOW_S3_ENDPOINT_URL. Depending on the value set for the environment variable MLFLOW_S3_ENDPOINT_URL, the resulting artifact storage path for this scenario would be one of the following invalid object store paths: https://<bucketname>.s3.<region>.amazonaws.com/<key>/<bucketname>/<key> or s3://<bucketname>/<key>/<bucketname>/<key>. To prevent path parsing issues, ensure that reserved environment variables are removed (unset) from client environments.

In our case, the MLFlow server and ML experiments was run on the same machine which mean we can't remove environment variables from client environments separately.

**Comment by harupy** [comment]
@ann-lab52

> Yes it is. There's no problem with the AWS credentials. Like I said, this problem was solve by parsing an empty string into artifact_path.

I'm wondering why a non-empty string causes the error.

**Comment by ann-lab52** [comment]
@harupy 
> @ann-lab52
> 
> > Yes it is. There's no problem with the AWS credentials. Like I said, this problem was solve by parsing an empty string into artifact_path.
> 
> I'm wondering why an empty string works, but a non-empty string doesn't.

Actually when we pass a non-empty string, for example `artifact_uri=s3://artifact_uri`  , then `artifact_path`  value will be  `artifact_uri/s3://artifact_uri`  instead `s3://artifact_uri`  . This why the empty string worked. I will update the full stack trace into my description.

**Comment by harupy** [comment]
@ann-lab52 Can you try this?

```
mlflow.pytorch.log_model(self.model, artifact_path="model", registered_model_name="OurModel")
```

**Comment by ann-lab52** [comment]
> @ann-lab52 Can you try running this? `artifact_path` must be relative.
> 
> ```
> mlflow.pytorch.log_model(self.model, artifact_path="model", registered_model_name="OurModel")
> ```

I'm sorry for the late reply. Unfortunately, our MLFlow server was terminated lately, therefore I can't reproduce it anymore. 

I will close this issue then.  If anyone have the same issue, please feel free to reopen it. Thanks
