### ISSUE TITLE
[BUG] get_latest_versions throws an Exception for unregistered models

### ISSUE THREAD

**Issue by agapebondservant** [mlflow/mlflow#7463]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Python version**: 3.10.6

### Describe the problem

How should I be performing a query to get the latest version of a model that possibly hasn't been registered yet?

When I attempt to perform a query using `get_latest_versions` for an unregistered model, an error is raised that aborts the run. Please see below. (I was expecting that it would return an empty iterable.) What I would ultimately like to do is to return the latest version of the model if it has been registered, and None otherwise. Please advise - thanks!

### Code to reproduce issue

```
client = MlflowClient()
latest_versions = client.get_latest_versions('my-unregistered-model', stages=['None'])
```

### Stack trace

```
File "/parent/scdfutils/utils.py", line 256, in get_latest_model_version
    latest_versions = client.get_latest_versions(name, stages=stages)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/client.py", line 2063, in get_latest_versions
    return self._get_registry_client().get_latest_versions(name, stages)
  File "/usr/local/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 134, in get_latest_versions
    return self.store.get_latest_versions(name, stages)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/model_registry/rest_store.py", line 173, in get_latest_versions
    response_proto = self._call_endpoint(GetLatestVersions, req_body, call_all_endpoints=True)
  File "/usr/local/lib/python3.10/site-packages/mlflow/store/model_registry/rest_store.py", line 60, in _call_endpoint
    return call_endpoints(self.get_host_creds(), endpoints, json_body, response_proto)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 294, in call_endpoints
    raise e
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 291, in call_endpoints
    return call_endpoint(host_creds, endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 280, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/usr/local/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 206, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Registered Model with name=baseline_model not found
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @agapebondservant, you can use `search_registered_models` to check whether a model has been registered or not.

```python
import mlflow

print(mlflow.search_registered_models(filter_string="name = 'I_do_not_exist'"))
```
