### ISSUE TITLE
[Issue]: Unknown property 'css' found  react/no-unknown-property

### ISSUE THREAD

**Issue by mChowdhury-91** [mlflow/mlflow#7482]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Mac
- **Python version**: 3.10
- **yarn version, if running the dev UI**:

### Describe the problem

When trying to run the latest UI on local 3000 port, getting the following error:
/mlflow/mlflow/server/js/src/common/components/CollapsibleTagsCell.jsx
  46:12  error  Unknown property 'css' found  react/no-unknown-property

/mlflow/mlflow/server/js/src/shared/building_blocks/Spacer.jsx
  35:17  error  Unknown property 'css' found  react/no-unknown-property

/mlflow/mlflow/server/js/src/shared/building_blocks/FlexBar.jsx
  19:12  error  Unknown property 'css' found  react/no-unknown-property

and in many more files

### Steps to reproduce the bug

Command 1: npm run lint inside js folder

Command 2: npm start inside js folder

On npm start I'm getting the below error:
(node:24427) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'exclude' of undefined
    at enableOptionalTypescript (/mlflow/mlflow/server/js/craco.config.js:109:68)
    at configure (/mlflow/mlflow/server/js/craco.config.js:300:25)
    at giveTotalControl (/mlflow/mlflow/server/js/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:28:25)
    at mergeWebpackConfig (/mlflow/mlflow/server/js/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:63:38)
    at overrideWebpackDev (/mlflow/mlflow/server/js/node_modules/@craco/craco/lib/features/webpack/override.js:11:36)
    at /mlflow/mlflow/server/js/node_modules/@craco/craco/scripts/start.js:24:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24427) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24427) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by harupy** [comment]
@mChowdhury-91 We no longer use `npm`. You can use `yarn`.

**Comment by harupy** [comment]
@mChowdhury-91 Feel free to reopen the issue if you encounter the same issue with yarn.
