### ISSUE TITLE
[BUG]mlflow run_recipe_step raising an error "The system cannot find the file specified"(mlflow\recipes\recipe.py:87)

### ISSUE THREAD

**Issue by smsrghosh** [mlflow/mlflow#7483]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

mlflow run_recipe_step raising an error "The system cannot find the file specified"(mlflow\recipes\recipe.py:87) while executing 
"classification" model on  wine data set. The code is exact copy of mlflow github "https://github.com/mlflow/recipes-examples/tree/main/classification".

the proper has been defined in local.yaml file already as below
INGEST_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-classification-template#ingest-step
  using: csv
  location: ["./data/winequality-white.csv", "./data/winequality-red.csv"]
  loader_method: load_file_as_dataframe

### Code to reproduce issue

 %load_ext autoreload
%autoreload 2
from mlflow.recipes import Recipe
import os
r = Recipe(profile="local")
r.clean()
r.inspect()

r.run("ingest")

### Stack trace

 FileNotFoundError                         Traceback (most recent call last)
Cell In[6], line 1
----> 1 r.run("ingest")

File c:\Users\M1097476\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\recipes\classification\v1\recipe.py:267, in ClassificationRecipe.run(self, step)
    195 def run(self, step: str = None) -> None:
    196     """
    197     Runs the full recipe or a particular recipe step, producing outputs and displaying a
    198     summary of results upon completion. Step outputs are cached from previous executions, and
   (...)
    265         classification_recipe.run()
    266     """
--> 267     return super().run(step=step)

File c:\Users\M1097476\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\recipes\recipe.py:87, in _BaseRecipe.run(self, step)
     85 self._steps = self._resolve_recipe_steps()
     86 target_step = self._get_step(step) if step else self._get_default_step()
---> 87 last_executed_step = run_recipe_step(
     88     self._recipe_root_path,
     89     self._get_subgraph_for_target_step(target_step),
     90     target_step,
     91     self._recipe,
     92 )
     94 self.inspect(last_executed_step.name)
...
   1455     self._close_pipe_fds(p2cread, p2cwrite,
   1456                          c2pread, c2pwrite,
   1457                          errread, errwrite)
FileNotFoundError: [WinError 2] The system cannot find the file specified

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
MLflow Recipes is part of MLflow 2.x. Can you try upgrading your client?

**Comment by BenWilson2** [comment]
@apurva-koti Sorry for the ping here, but have you seen issues with running the example on Windows?

**Comment by apurva-koti** [comment]
@BenWilson2 haven't so far - also haven't run the example on windows recently. cc @sunishsheth2009 ?

**Comment by harupy** [comment]
@smsrghosh Did you install `make`?

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/issues/6201 looks similar

**Comment by smsrghosh** [comment]
Is it solved  by installing make in windows ?

Regards,
Subrata

**Comment by harupy** [comment]
#6201 was solved by installing make.

**Comment by smsrghosh** [comment]
Thanks the issue got fixed. Subsequently I am getting error in
 r.run("split")
2022/12/09 15:08:33 INFO mlflow.recipes.utils.execution: ingest: No
changes. Skipping.
process_begin: CreateProcess(NULL, # Run MLFlow Recipe step: split, ...)
failed.
make (e=2): The system cannot find the file specified.

make: *** [Makefile:21: steps/split/outputs/train.parquet] Error 2

**Comment by harupy** [comment]
@smsrghosh Can you provide the full traceback?

**Comment by smsrghosh** [comment]
This is the full stack trace only :

-> r.run("split")

2022/12/09 15:08:33 INFO mlflow.recipes.utils.execution: ingest: No
changes. Skipping.
process_begin: CreateProcess(NULL, # Run MLFlow Recipe step: split, ...)
failed.
make (e=2): The system cannot find the file specified.

make: *** [Makefile:21: steps/split/outputs/train.parquet] Error 2

**Comment by harupy** [comment]
Found https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified

**Comment by harupy** [comment]
@smsrghosh Can we close this issue?

**Comment by smsrghosh** [comment]
Yes. Please close the issue.thanks for the support.

**Comment by PrashantKartikeya** [comment]
I'm using a windows machine and I have "make" installed that helped me run the "r.ingest" step but I'm seeing this error at "r.split" step, can someone please help?
