### ISSUE TITLE
[BUG] Environment variables are not passed to python subprocess when used in Java API

### ISSUE THREAD

**Issue by drod331** [mlflow/mlflow#7488]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 1.29.0
- Tracking server: 1.29.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Python version**: 3.9
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When calling `MlflowClient.listArtifact("runId")` from the Java API, and using a remote Mlflow tracking server with an HDFS artifact store, I get an error stating that libhdfs.so cannot be found, with the path being the default one constructed by PyArrow via $HADOOP_HOME/lib/native, even though I specify the environment variable ARROW_LIBHDFS_DIR, which should override it.  

I can confirm that both in the native Python MlflowClient 
`mlflow.list_artifacts("run_id")` 

and command-line via 
`python -m mlflow.store.artifact.cli list -r run_id` 

that the ARROW_LIBHDFS_DIR env variable works as intended and I get the correct artifacts back.  

We either need to pass that specific env variable through like we do for MLFLOW_TRACKING_URI in setProcessEnvironment or the more general, better solution would be to allow for the user to specify env variables to be passed through to the Python process.

### Code to reproduce issue

See above

### Stack trace

See above

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [X] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by drod331** [comment]
I'm more than willing to put in a PR for this, just would be curious to hear what you all think the API should look like for specifying env variables

**Comment by dbczumar** [comment]
Hi @drod331 , thank you for filing this issue. The MLflow Java client's listArtifacts() implementation calls the MLflow Python client's list artifacts APIs via the MLflow Python CLI by forking a subprocess. My hunch is that this subprocess does not properly inherit environment variables from the parent process; here's the relevant environment construction code: https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/java/client/src/main/java/org/mlflow/artifacts/CliBasedArtifactRepository.java#L223-L228.

Ideally, it would be great to modify https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/java/client/src/main/java/org/mlflow/artifacts/CliBasedArtifactRepository.java#L223-L228 such that the subprocess inherits the environment variables correctly, which should address the issue you're encountering. Please let me know if you have any questions, and thank you in advance for your contribution - we're looking forward to reviewing it!

**Comment by drod331** [comment]
After inspecting the source code, it seems to be preserving the environment variables as intended.  After taking a second look at my setup and the environment variables, somehow only ARROW_LIBHDFS_DIR was not being passed through, with others being passed through correctly.  I'm thinking it might be a strange bug with this 3rd party library that's passing the env vars to Mlflow, so I'll mark as closed due to not being a bug with this project.
