### ISSUE TITLE
[DOC-FIX] Populate API and usage examples for Pmdarima module

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#7501]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://www.mlflow.org/docs/latest/python_api/mlflow.pmdarima.html (for `mlflow.pyfunc`)
https://www.mlflow.org/docs/latest/python_api/mlflow.pmdarima.html#mlflow.pmdarima.load_model
https://www.mlflow.org/docs/latest/python_api/mlflow.pmdarima.html#mlflow.pmdarima.log_model
https://www.mlflow.org/docs/latest/python_api/mlflow.pmdarima.html#mlflow.pmdarima.save_model

### Description of proposal (what needs changing)

Updates should be made to
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/pmdarima.py#L7-L10
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/pmdarima.py#L91-L130
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/pmdarima.py#L207-L256
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/pmdarima.py#L275-L294

To add relevant API usage examples in the same vein as the examples in:
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/pytorch/__init__.py#L232-L303

NOTE: please use `..test-code-block:: python` for all code examples to ensure that unit tests on encapsulated code are tested.

NOTE: In order to perform local testing of code within comments:

``` shell
cd docs
make rsthtml  # should dump code blocks in `docs/.examples` as python scripts.
make test-examples
```

**Comment by WeichenXu123** [comment]
@canerturkseven Are you interested to contribute on this task ? :)

**Comment by canerturkseven** [comment]
@WeichenXu123 Yes, I am interested. I started working on it.

**Comment by canerturkseven** [comment]
@WeichenXu123 @BenWilson2 Hi, I would like to contribute. I started working on this. I will submit the PR request this week.

**Comment by WeichenXu123** [comment]
@canerturkseven Appreciate your contribution!

**Comment by Aman123lug** [comment]
can i work on this
