### ISSUE TITLE
[DOC-FIX] Populate API and usage examples for LightGBM module

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#7502]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://www.mlflow.org/docs/latest/python_api/mlflow.lightgbm.html

### Description of proposal (what needs changing)

Provide API examples for each public-facing API within `mlflow.lightgbm.py`

https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/lightgbm.py#L7-L9
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/lightgbm.py#L81-L83
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/lightgbm.py#L92-L95
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/lightgbm.py#L111-L143
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/lightgbm.py#L248-L288
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/lightgbm.py#L343-L362
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/lightgbm.py#L414-L458

To add relevant API usage examples in the same vein as the examples in:
https://github.com/mlflow/mlflow/blob/50a0a869a58e63d064bf63744a782b034544b638/mlflow/pytorch/__init__.py#L232-L303

NOTE: please use `..test-code-block:: python` for all code examples to ensure that unit tests on encapsulated code are tested.

NOTE: In order to perform local testing of code within comments:

``` shell
cd docs
make rsthtml  # should dump code blocks in `docs/.examples` as python scripts.
make test-examples
```

**Comment by canerturkseven** [comment]
Hi @BenWilson2,

I am willing to contribute. Which existing API can I use as an example to do this?

**Comment by canerturkseven** [comment]
Hi,

I want to contribute, and I started working on it.

**Comment by WeichenXu123** [comment]
@canerturkseven Thank you! Happy to see your PR!
