### ISSUE TITLE
[BUG] Unable to list artifacts stored under <code>{artifactUri}</code> for the current run.

### ISSUE THREAD

**Issue by hrahmanStratuscent** [mlflow/mlflow#7518]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.0.1
- Tracking server: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**: python:3.8
- **yarn version, if running the dev UI**:

### Describe the problem

Created and deployed MLflow docker image on K8S cluster. Using Google Cloud Storage as the root artifact directory.
The Dockerfile:

```
FROM python:3.8-slim
RUN apt update && apt install -y python3-venv gcc
RUN apt-get install -y python3-dev build-essential curl

ENV VENV=/.venv/myenv
RUN python3 -m venv ${VENV}
RUN mkdir -p $VENV/src
ENV PATH=$VENV/bin:$PATH
RUN pip install -U pip psycopg2-binary mlflow==2.0.1 google-cloud google-cloud-storage
# Mount the credentials json file under the following directory
RUN mkdir -p /workdir/gcloud-credentials/
WORKDIR /workdir/
RUN curl https://sdk.cloud.google.com > install.sh
RUN bash install.sh --disable-prompts --install-dir=/workdir/
ENV PATH=/workdir/google-cloud-sdk/bin:$PATH
# Expose the port that the MLFlow tracking server runs on
EXPOSE 5000
# Default database credentials

ENTRYPOINT gcloud auth activate-service-account --key-file=/workdir/gcloud-credentials/gcloud-credentials.json && \
        mlflow server \
        --default-artifact-root gs://ml1-bucket \
        --backend-store-uri postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_URL/$DB_NAME --host 0.0.0.0
```

The Service Account has read-write permission. But UI not showing artifacts with this error:

```
Loading Artifacts Failed
Unable to list artifacts stored under <code>{artifactUri}</code> for the current run. Please contact your tracking server administrator to notify them of this error, which can happen when the tracking server lacks permission to list artifacts under the current run's root artifact directory.
```

### Code to reproduce issue

```
print("MLflow Version:", mlflow.__version__)
print("Tracking URI:", mlflow.tracking.get_tracking_uri())
client = mlflow.tracking.MlflowClient()


if __name__ == "__main__":
    with mlflow.start_run() as run:
        mlflow.log_param("alpha", 5)
        mlflow.log_metric("rmse", 0.789)
        with open("info.txt", "w") as f:
            f.write("Hi artifact")
        mlflow.log_artifact("info.txt")
        params = [Param("p1", "0.1"), Param("p2", "0.2")]
        now = round(time.time())
        metrics = [Metric("m1", 0.1, now, 0), Metric("m2", 0.2, now, 0)]
        tags = [RunTag("tag1", "hi1"), RunTag("tag2", "hi2")]
        client.log_batch(run.info.run_id, metrics, params, tags)
```

### Stack trace

```
Loading Artifacts Failed
Unable to list artifacts stored under <code>{artifactUri}</code> for the current run. Please contact your tracking server administrator to notify them of this error, which can happen when the tracking server lacks permission to list artifacts under the current run's root artifact directory.
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @hrahmanStratuscent, thank you for filing this report. My strong suspicion is that this is a credentialing / authentication issue with the GCS setup that you're using. Can you make a post in the GitHub discussions section (https://github.com/mlflow/mlflow/discussions) and tag @JHibbard there for further assistance? To debug, I would recommend programmatically ensuring that you can download artifacts / files from GCS from within the Kubernetes pod where `mlflow server` is running.

Since there isn't strong evidence of an MLflow bug here, I'm going to close this issue for now. Please feel free to reopen it if the investigation from the Discussions board identifies an MLflow issue. Thank you for using MLflow!
