### ISSUE TITLE
[BUG] "register" step does not show the model version in UI

### ISSUE THREAD

**Issue by smsrghosh** [mlflow/mlflow#7519]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

Not able to see registered model version in UI from mlflow.recipes import Recipe

### Code to reproduce issue

 import os

r = Recipe(profile="local")
r.clean()
r.inspect()
r.run("split")
r.run("transform")
r.run("train")
r.run("evaluate")

--> r.run("register")

Model Name: red_wine_classifier

Model Version: 1

Model Source URI: runs:/df1efb172db4463284267a532add15bb/train/model

Run duration (s): 0.783

Last updated: 2022-12-09 17:57:20

### Stack trace

 import os

r = Recipe(profile="local")
r.clean()
r.inspect()
r.run("split")
r.run("transform")
r.run("train")
r.run("evaluate")

--> r.run("register")

Model Name: red_wine_classifier

Model Version: 1

Model Source URI: runs:/df1efb172db4463284267a532add15bb/train/model

Run duration (s): 0.783

Last updated: 2022-12-09 17:57:20

### Other info / logs

--> r.run("register")

Model Name: red_wine_classifier

Model Version: 1

Model Source URI: runs:/df1efb172db4463284267a532add15bb/train/model

Run duration (s): 0.783

Last updated: 2022-12-09 17:57:20

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Could you provide:
* your recipe "local.yaml" config file
* your command to start MLflow UI
?

I want to check whether the registry uri used by MLflow UI is consistent with the uri recipe used.

**Comment by smsrghosh** [comment]
The issue is resolved. Thanks
