### ISSUE TITLE
[FR] Clearer pagination UI in Registered Models view

### ISSUE THREAD

**Issue by guyrosin** [mlflow/mlflow#7520]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

The Registered Models pagination feature should indicate the existance of multiple pages in a clear way.
Currently it's almost impossible to realize there are multiple pages, as you can see in the below screenshot: the only difference is that the arrow is in black instead of gray.
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1250162/207339052-9c74a75c-aeee-4eb2-a73a-415cbcfc5e5c.png">
Please show multiple page numbers (as in Google search, for example), or at least make the indication of the "next page" button clearer.
[Note I'm using mlflow 1.26 for the UI so maybe this has been improved in recent versions]

### Motivation

> #### What is the use case for this feature?
Looking for registered models when more than 10 models are registered.
> #### Why is this use case valuable to support for MLflow users in general?
Pagination is currently not intuitive; it's easy to miss it and thus think your models weren't registered.
> #### Why is this use case valuable to support for your project(s) or organization?
To get easier navigation and avoid possible mistakes.
> #### Why is it currently difficult to achieve this use case?
It requires a small UI change, shouldn't be difficult at all.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@guyrosin This is what the latest MLflow UI (on master) looks like.

When the next page is available:

<img width="376" alt="Screen Shot 2022-12-16 at 19 45 51" src="https://user-images.githubusercontent.com/17039389/208082675-28788d84-91a2-4604-99bb-616d14c0bc89.png">

When the next page is unavailable:

<img width="376" alt="Screen Shot 2022-12-16 at 19 46 00" src="https://user-images.githubusercontent.com/17039389/208082678-472143dc-2937-4fe7-9eed-a1f61aabd03c.png">

**Comment by guyrosin** [comment]
Thanks @harupy for including these screenshots! It looks much better. 
I still think a clearer UI would either show several page numbers, as Google does
![image](https://user-images.githubusercontent.com/1250162/208093356-2561dde7-9205-4bd7-aea0-a118186e035c.png)
or show the number of available pages, as in this example: 
![image](https://user-images.githubusercontent.com/1250162/208093714-523b0227-574e-41f5-9eeb-be8b5224ca20.png)
But I don't think the current MLFlow API supports retrieving the total amount of registered models / pages, so I'm not sure how much work this change would require (please feel free to close this issue if it's not worth it in your eyes)

**Comment by harupy** [comment]
> I don't think the current MLFlow API supports retrieving the total amount of registered models / pages

No, it doesn't. We can retrieve the total amount of registered models / pages by calling the search-registered-models API until we hit the last page, but this can be expensive.
