### ISSUE TITLE
[BUG] Can't train via CLI command `mlflow run .`.  No such file or directory.

### ISSUE THREAD

**Issue by pedrety** [mlflow/mlflow#7532]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.0.1
- Tracking server: 2.0.1

### System information

- **OS Platform and Distribution**: Ubuntu 20.04
- **Python version**: Python 3.8.10

### Describe the problem

I just recently updated to MLflow version 2.0.1. I tried to run my training as usual running `mlflow run . --experiment-name "Name" ...` using a MLproject with a Docker environment. Sadly it returns:

```bash
python3: can't open file 'scripts/run_experiment.py': [Errno 2] No such file or directory
```

This didn't happen in the previous version of MLflow and I tried downgrading the version and it runs smoothly. Seems like my docker container does not have my training scripts and so the training can't be executed.

Maybe I missed some changes in the MLproject and CLI commands and now I should link the volume to my docker container.

### Code to reproduce issue

My file structure is:

```
root_directory
      |---scripts
      |         |--files.py
      |         |--
      |
      |---MLproject
```

To reproduce the issue just try to run something using the run command. I tried two types of trainings and both failed.

```bash
mlflow run . --experiment-name "Experiment name" \
    -P ... \
    -P ... \
    -A gpus=all \
    -A network=host

### Stack trace

Some parts of the stack trace are indicated as `[a bunch of commands]` for privacy purpose

```bash
2022/12/15 10:49:57 INFO mlflow.projects.docker: registry.cinfo.es/ai-mlflow-experiments/mlflow-darknet-experiment/experiment:latest already exists
2022/12/15 10:49:57 INFO mlflow.projects.utils: === Created directory /tmp/tmpezlbdz06 for downloading remote URIs passed to arguments of type 'path' ===
2022/12/15 10:49:57 INFO mlflow.projects.backend.local: === Running command 'docker run --rm --gpus all --network host --tty -e [a bunch of commands] registry.cinfo.es/ai-mlflow-experiments/mlflow-darknet-experiment/experiment:latest python3 scripts/run_experiment.py [a bunch of commands(again)] in run with ID '819450cd379e4b1c9992ad62b112a229' === 
python3: can't open file 'scripts/run_experiment.py': [Errno 2] No such file or directory
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@pedrety I think this is because of the `--build-image` flag we added in MLflow 2.0.1. Can you try adding this flag?

```
mlflow run ... --build-image
```

**Comment by pedrety** [comment]
That seems to fix my problem. For some reason the documentation is still with the old behavior since it says:

> By default, MLflow builds a new image that’s based on the specified image and files contained in the project directory. To disable this behavior and use the image directly, run the project with the --skip-image-build argument specified.

**Comment by harupy** [comment]
Looks like the documentation is outdated.

**Comment by pedrety** [comment]
I'll keep that in mind then. Thanks for the help 😺
