### ISSUE TITLE
[BUG] The link is not found for "Edit on GitHub" on the right upper corner of the docs.

### ISSUE THREAD

**Issue by Jingnan-Jia** [mlflow/mlflow#7535]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.0.1

### System information

Any system, it is the docs' issue.

### Describe the problem

Now, go to (this page of docs)[https://www.mlflow.org/docs/latest/_modules/mlflow/tracking/client.html#MlflowClient.restore_run]

Click the link of "Edit on GitHub" at the right upper corner, it shows

"The 'mlflow/mlflow' repository doesn't contain the 'docs/source/_modules/mlflow/tracking/client' path in 'master'.  "

### Code to reproduce issue

Not applied

### Stack trace

Not applied

### Other info / logs

Not applied

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
The edit button is there:

https://www.mlflow.org/docs/latest/index.html
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/19235986/208027855-d1a85e15-a99f-4a60-b06a-1275919f0d2f.png">

Is it your browser issue ?

**Comment by harupy** [comment]
@WeichenXu123 That's not the issue. The issue is the link of "Edit on GitHub" is broken.

**Comment by WeichenXu123** [comment]
Mlflow doc generate the github edit link from sphinx "pagename" variable (value is like "_modules/mlflow/tracking/client.html") , which is incorrect, we should generate the link from the source file path (like "tracking.rst", anyone knows does sphinx provide a variable that contains the source file path ?

**Comment by harupy** [comment]
I think we can remove the link.
