### ISSUE TITLE
[DOC-FIX] `dataframe_records` typo

### ISSUE THREAD

**Issue by zhouyangyu** [mlflow/mlflow#7536]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://www.mlflow.org/docs/latest/models.html#local-model-deployment

### Description of proposal (what needs changing)

> dataframe_records field with pandas DataFrame in the records orientation. For example, data = {"dataframe_split": pandas_df.to_dict(orient='records').

should be

> dataframe_records field with pandas DataFrame in the records orientation. For example, data = {"dataframe_records": pandas_df.to_dict(orient='records').

**Comment by WeichenXu123** [comment]
@zhouyangyu Thanks for catching this. Hope to see your PR !
