### ISSUE TITLE
[BUG] urllib3.exceptions.LocationParseError: Failed to parse:

### ISSUE THREAD

**Issue by Voigt1022** [mlflow/mlflow#7555]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 1.23.1
- Tracking server: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
- **Python version**: 3.6.6
- **yarn version, if running the dev UI**:

### Describe the problem

As you can see, the MLflow version and the tracking serve is not the same. And when I am trying to log artifact and an exception occurs. So I am wondering if this is caused by the different version from client and tracking.

I have to keep python version at 3.6.6 due to my machine learning python code.

### Code to reproduce issue

``` python
# I am trying to log artifact with userClient
client.log_artifact(run.info.run_id, zip_file_path, artifact_path=pickle_artifact_path)
```

### Stack trace

``` python 

Traceback (most recent call last):
  File "/opt/miniconda3/envs/env_opp/lib/python3.6/site-packages/requests/models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/opt/miniconda3/envs/env_opp/lib/python3.6/site-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://XXXXXX:None/api/2.0/mlflow-artifacts/artifacts/3/f688903569444af6b79c4064c74af19f/artifacts/test/delivery_tags_VB.xlsx
```

### What component(s) does this bug affect?

- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
The URL printed has issue: `Failed to parse: https://XXXXXX:None/api/2.0/...`

What's your tracking URI ? And could you provide your command to setup MLflow tracking server ?

**Comment by Voigt1022** [comment]
Hi, I run my tracking server on a remote VM. And here is my tracking server start up shell:
```
nohup mlflow server \
    --backend-store-uri postgresql://postgres:xxxxxx@127.0.0.1:5432/postgres \
    --serve-artifacts \
    --host 0.0.0.0 > mlserver.out 2>&1 \
    --gunicorn-opts "--timeout=1200" & 
```

**Comment by Voigt1022** [comment]
Hi this is solved, I forgot to set tracking URI port. And since my tracking server is https, the port should be 443.
