### ISSUE TITLE
[FR] Integration between Mlflow and CouchDB

### ISSUE THREAD

**Issue by jhonnye0** [mlflow/mlflow#7578]
### Willingness to contribute

No, I can't

### Proposal Summary

Hi, I was digging through the documentation and the source code to figure out if it's possible to integrate mlflow with CouchDB (an HTTP-based DB). 

### Motivation

> #### What is the use case for this feature?
In a way that we need synchronization between some databases, CouchDB implements a replication protocol
> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support your project(s) or organization?
We have an application that needs this synchronization due to a cloud and desktop proposal.
> #### Why is it currently difficult to achieve this use case?
The engine sqlalchemy doesn't support this kind of DB

### Details

This request is more like a question than a FR.

**Comment by harupy** [comment]
@jhonnye0 MLflow currently supports the databases that SQLAlchemy is compatible is.
