### ISSUE TITLE
[SETUP-BUG] Running "yarn start" fails when following contributors guide

### ISSUE THREAD

**Issue by bissont** [mlflow/mlflow#7590]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
-  This happens on OS X M1(through run-test-container.sh)
- disabled airflow (which was also listening on port 5000)
- **MLflow installed from (source or binary)**:
mlflow, version 2.1.1.dev0
- **MLflow version (run ``mlflow --version``)**:
- **Python version**:
- 3.8

### Code to reproduce issue

yarn start from inside the container

### Describe the problem

I can run the `mlflow ui` command (and I et the correct message about:
`Unable to display MLflow UI - landing page (index.html) not found.`

However, when I run the `yarn start` command: I always get this error:
```
oot@f452cf900a9c:/app/mlflow/server/js# yarn start
(node:25616) UnhandledPromiseRejectionWarning: /app/mlflow/server/js/craco.config.js:72
        .filter((oneOf) => oneOf.test?.toString() === /\.css$/.toString())
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at module.exports (/app/mlflow/server/js/node_modules/import-fresh/index.js:32:59)
    at loadJs (/app/mlflow/server/js/node_modules/cosmiconfig/dist/loaders.js:16:18)
    at ExplorerSync.loadFileContentSync (/app/mlflow/server/js/node_modules/cosmiconfig/dist/ExplorerSync.js:84:26)
    at ExplorerSync.createCosmiconfigResultSync (/app/mlflow/server/js/node_modules/cosmiconfig/dist/ExplorerSync.js:89:30)
(node:25616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
root@f452cf900a9c:/app/mlflow/server/js# 
 *  History restored 

root@f452cf900a9c:/app/mlflow/server/js# 

```

Has anyone seen something similar?

### Other info / logs

I also tried to run `yarn start` directly on my mac (mlflow running inside container). In that case I don't get the error condition, but I just get a timeout trying to reach 127.0.0.1:3000 like the image
<img width="2197" alt="Screenshot 2022-12-22 at 6 02 58 PM" src="https://user-images.githubusercontent.com/509759/209256271-ee751886-833b-49e1-af24-9b70d94e70f8.png">

**Comment by harupy** [comment]
@bissont What is your node version?

**Comment by bissont** [comment]
Thanks @harupy  - I didn't realize I need the `yarn build`. That fixed it.
