### ISSUE TITLE
[BUG] Sagemaker deployment error in _install_pyfunc_deps

### ISSUE THREAD

**Issue by nfarley-soaren** [mlflow/mlflow#7611]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.10.4
- **yarn version, if running the dev UI**:

### Describe the problem

I am trying to deploy a registered pyfunc model to Sagemaker using mlflow version 2.0.1.  Deployment fails when trying to create the environment.  I've had no problems in the past using mlflow version 1.29.0.  I'm logging my model with it's conda environment defined in the same way as before (see below).  I might just be missing something in the new version but I haven't been able to determine what that is so I'm creating this issue.

`    model_env = {
            "name": "my-env",
            "channels": ["conda-forge"],
            "dependencies": [
                "python=3.10.4",
                "pip<=21.2.4",
                {
                    "pip": [
                        "mlflow==2.0.1", 
                        "hyperopt==0.2.5",
                        "joblib==1.1.0",
                        "catboost==1.1.1",
                        "matplotlib==3.5.2",
                        "numpy==1.22.4",
                        "pandas==1.4.1",
                        "scikit_learn==1.1.1",
                        "seaborn==0.11.2",
                        "boto3==1.24.0"
                    ],
                },
            ],
        }

    mlflow.pyfunc.log_model(
        python_model=MyModelWrapper(
            model=best_model,
        ),
        code_path=["./my_model_wrapper.py"],
        artifact_path="model",
        registered_model_name="My_Awesome_Model",
        conda_env=model_env
    )
`

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
from mlflow.deployments import get_deploy_client

config=dict(
    execution_role_arn=SAGEMAKER_EXECUTION_ROLE_ARN,
    bucket_name=AWS_S3_BUCKET,
    image_url=image_url,
    region_name=AWS_REGION,
    archive=False,
    instance_type="ml.m5.large",
    instance_count=1,
    synchronous=True,
    timeout_seconds=300,
)

deploy_client = get_deploy_client("sagemaker")

deploy_client.create_deployment(
            name=endpoint_name,
            model_uri=model_uri,
            flavor="python_function",
            config=config)

```

### Stack trace

```
File "<string>", line 1, in <module>
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 57, in _init
    _serve(env_manager)
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 84, in _serve
    _serve_pyfunc(m, env_manager)
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 156, in _serve_pyfunc
    _install_pyfunc_deps(
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 109, in _install_pyfunc_deps
    env_path_dst = os.path.join("/opt/mlflow/", env)
  File "/miniconda/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/miniconda/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict````


### Other info / logs

<!-- PLEASE KEEP BACKTICKS AND CHECK PREVIEW -->
```
REPLACE_ME
```


### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@nfarley-soaren In what version of mlflow did you run the following code?

```python
import mlflow
from mlflow.deployments import get_deploy_client

config=dict(
    execution_role_arn=SAGEMAKER_EXECUTION_ROLE_ARN,
    bucket_name=AWS_S3_BUCKET,
    image_url=image_url,
    region_name=AWS_REGION,
    archive=False,
    instance_type="ml.m5.large",
    instance_count=1,
    synchronous=True,
    timeout_seconds=300,
)

deploy_client = get_deploy_client("sagemaker")

deploy_client.create_deployment(
            name=endpoint_name,
            model_uri=model_uri,
            flavor="python_function",
            config=config)

```

The error you encountered sounds like you're trying to deploy a model logged in MLflow 2.0 with MLflow < 2.0.

**Comment by nfarley-soaren** [comment]
@harupy I was trying to deploy using mlflow 2.0.1.

**Comment by harupy** [comment]
@nfarley-soaren I see the following line in your stack trace:

```
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 156, in _serve_pyfunc
    _install_pyfunc_deps(
```

#### MLflow 1.29.0

https://github.com/mlflow/mlflow/blob/2487179a9f239024667946e7d31706a91f2536b8/mlflow/models/container/__init__.py#L156

#### MLflow 2.0.1

https://github.com/mlflow/mlflow/blob/f2dd5e4bfdcc4e8e2db51ad38c1e9fa0afd99de7/mlflow/models/container/__init__.py#L156

I think you're using MLflow < 2.0.1.

**Comment by nfarley-soaren** [comment]
Ahhh....I think I might know the issue.  I'm running 2.0.1 for building models and deploying.  Could this error be coming from the version of mlflow used in the base container?  I expected the version of mlflow that would be installed and used would come from the specified environment.  I had to build a custom container for deployment because I needed customizability that isn't present in the mlflow autogenerated container.  I had to use a much earlier version of mlflow for this because there were problems with the scoring jar files from maven with more recent versions.  If this is the case, I will need to build and register a new container.  Can you recommend a newer version that will work?

**Comment by harupy** [comment]
> Could this error be coming from the version of mlflow used in the base container?

It could.

> Can you recommend a newer version that will work?

>= 2.0.1 should work.

**Comment by nfarley-soaren** [comment]
Ok, I built the container with 2.0.2 and it seems to create an endpoint now.  Thanks for your help!
