### ISSUE TITLE
[BUG] The way models are shown in the UI changed from version 1.27.0 to version 1.28.0

### ISSUE THREAD

**Issue by ibiscp** [mlflow/mlflow#7612]
### MLflow version

1.28.0 or newer

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Ventura 13.0.1
- **Python version**: 3.8.16
- **yarn version, if running the dev UI**: 

### Describe the problem

I discovered an issue while testing Pycaret with MLflow. I noticed a significant difference in the way experiments are logged between version 1.27.0 and version 1.28.0 or newer. In version 1.27.0, the results seem to be correct and how I would expect them to be displayed. However, when I update to version 1.28.0 or newer, all of the models are displayed in a cascaded format.

<img width="1673" alt="Screenshot 2022-12-27 at 15 57 17" src="https://user-images.githubusercontent.com/19699606/209711357-c1bdd937-3430-4c13-93ed-f7546a592b7d.png">

<img width="1673" alt="Screenshot 2022-12-27 at 15 55 38" src="https://user-images.githubusercontent.com/19699606/209711365-97ef50f1-276b-421e-a814-46c16f09f45c.png">

### Code to generate data required to reproduce the bug

```
from pycaret.datasets import get_data
from pycaret.regression import *

data = get_data('diamond')

# initialize setup
s = setup(data, target = 'Price', transform_target = True, log_experiment = True, experiment_name = 'diamond', silent=True)

best = compare_models()
```

**Comment by harupy** [comment]
@ibiscp It looks like pycare dones't handle nested runs properly. Can you raise an issue in the pycare repository?

We can  

```python
import mlflow

with mlflow.start_run() as run1:
    with mlflow.start_run(nested=True) as run2:
        with mlflow.start_run(nested=True) as run3:
            pass

```

The reason you're observing the difference is MLflow 1.28 includes https://github.com/mlflow/mlflow/pull/6065.
