### ISSUE TITLE
[DOC-FIX] Add sktime to community model flavors

### ISSUE THREAD

**Issue by benjaminbluhm** [mlflow/mlflow#7617]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

[Community Model Flavors](https://mlflow.org/docs/latest/models.html#id21)

### Description of proposal (what needs changing)

There now exists a community model flavor for [sktime library](https://github.com/sktime/sktime) (see [changelog](https://www.sktime.org/en/latest/changelog.html) for latest release 0.15.0). We also included an [example notebook](https://github.com/sktime/sktime/blob/main/examples/mlflow.ipynb) and [Sphinx documentation](https://www.sktime.org/en/latest/api_reference/deployment.html#mlflow) for this feature.

Proposal is to list the sktime custom flavor in the MLflow docs as part of the [community model flavor section](https://mlflow.org/docs/latest/models.html#id21) including a short code usage example.

**Comment by harupy** [comment]
@benjaminbluhm Sounds good to me. Looking forward to your PR :)
