### ISSUE TITLE
[BUG] list_artifacts and download_artifacts are in different namespaces

### ISSUE THREAD

**Issue by santiagxf** [mlflow/mlflow#7620]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.1
- Tracking server: 2.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Python version**: 3.10
- **yarn version, if running the dev UI**: NA

### Describe the problem

In MLflow 2.0, the method `MlflowClient.download_artifacts` has been moved to `mlflow.artifacts.download_artifacts` and the former marked as deprecated. However, the method `MlflowClient.list_artifacts` remains inside of the MLflow client. This creates an inconsistent programming model.

### Tracking information

NA

### Code to reproduce issue

List artifacts:

```python
import mlflow

client = mlflow.tracking.MlflowClient()
client.list_artifacts(last_run.info.run_id)
```

Download artifacts:

```python
file_path = mlflow.artifacts.download_artifacts(
    run_id=last_run.info.run_id,
    artifact_path="feature_importance_weight.png"
)
```

### Stack trace

NA

### Other info / logs

NA

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @santiagxf , not sure I'm following the issue here. What is the inconsistency?

**Comment by santiagxf** [comment]
I would expect `list_artifacts` to be in `mlflow.artifacts.list_artifacts` instead of in the `MlflowClient.list_artifacts` to be consistent with `mlflow.artifacts. download_artifacts` method.

**Comment by B-Step62** [comment]
Resolved by https://github.com/mlflow/mlflow/pull/11008
