### ISSUE TITLE
[DOC-FIX] Duplicate entry for community model flavor section

### ISSUE THREAD

**Issue by benjaminbluhm** [mlflow/mlflow#7625]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

There is duplicate entry for community model flavor section:

https://mlflow.org/docs/latest/models.html#community-model-flavors

https://mlflow.org/docs/latest/models.html#id21

### Description of proposal (what needs changing)

Move all content under https://mlflow.org/docs/latest/models.html#id21

Afterwards delete https://mlflow.org/docs/latest/models.html#community-model-flavors

**Comment by dbczumar** [comment]
Hi @benjaminbluhm , thank you for raising this issue. We would very much appreciate a pull request for this and are looking forward to it. Please let me know if you have any questions!
