### ISSUE TITLE
Issues while running prediction on ONNX Serialized SparkML Model Using Mlflow.pyfunc

### ISSUE THREAD

**Issue by HassanRaza1313** [mlflow/mlflow#7628]
I have created a spark pipeline model using the following code:

![image](https://user-images.githubusercontent.com/61215448/210042270-ebfc590c-4e6e-405c-88e9-c85ff6592778.png)

Next I build the initial_types for this model using the following code:

![image](https://user-images.githubusercontent.com/61215448/210042320-b4ae7e9c-74c1-4996-b683-da99d2060e33.png)

Then I converted the model to onnx using the following code:

![image](https://user-images.githubusercontent.com/61215448/210042332-9ff73658-be28-411f-97b9-be68764180d5.png)

Then I logged the onnx model using Mlflow using the following code:

![image](https://user-images.githubusercontent.com/61215448/210042363-00c48d48-6708-4a24-9c60-d1451a1b26ba.png)

Next I loaded the model using the mlflow.pyfunc module for prediction:

![image](https://user-images.githubusercontent.com/61215448/210042399-2caaf4c5-5a04-4ad5-9e28-d2aa8f7b51f6.png)

I created the "new_test" variable by converting the test dataframe to Pandas and converted the datatypes using the folliowiing code:
![image](https://user-images.githubusercontent.com/61215448/210042438-66c2dc7a-baf6-4379-a86f-be263a500650.png)

When I run inference I get the following error:

![image](https://user-images.githubusercontent.com/61215448/210042469-ffbcc7d4-7639-447d-856f-d65d1b462a9f.png)

How to resolve this issue?

**Comment by BenWilson2** [comment]
This isn't an issue with MLflow. This is a problem with your use of the ONNX library. Perhaps this might help? http://www.xavierdupre.fr/app/onnxruntime/helpsphinx/auto_examples/plot_common_errors.html
