### ISSUE TITLE
Feature request: support for downloading MLflow projects from S3, Azure blob store, etc

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#763]
Currently, MLflow projects that are stored remotely (e.g. in `.zip` format) can only be downloaded via HTTP or cloned via Git. 

We should support the resolution of remote projects from S3 buckets, Azure blob stores, etc.

**Comment by pogil** [comment]
Closed in favor of a more recent related issue with notes on how this could be done. https://github.com/mlflow/mlflow/issues/2233
