### ISSUE TITLE
PyTorch nightly build compromised

### ISSUE THREAD

**Issue by pietermarsman** [mlflow/mlflow#7634]
Hi, 

The [PyTorch nightly build was recently compromised](https://pytorch.org/blog/compromised-nightly-dependency/), and one of its dependencies has malware. Since Mlflow sometimes depends on pytorch, you should check if Mlflow users are impacted by this. 

I checked my local code, and mlflow pops up sometimes if I search for "nightly" and "pytorch" on the same line. In the current repo I could only find [this line](https://github.com/mlflow/mlflow/blob/9afde60e1fd87f447a4793415d0e71b72f6b48dc/mlflow/ml-package-versions.yml#L35). 

 This issue is just an FYI. Feel free to close it if you don't think Mlflow users are impacted by this.

**Comment by dbczumar** [comment]
Thanks so much, @pietermarsman ! @harupy can you take a look?

**Comment by harupy** [comment]
@pietermarsman Thanks for reporthing this. We checked GitHub Actions logs generated during Dec 25 ~ Dec 30, but didn't find `torchtoriton`. I investigated why and found https://github.com/pytorch/pytorch/pull/91539. My hypothesis is that `torchtoriton` is an optional dependency and `pip install --upgrade --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html` doesn't install it (but `pip install --upgrade --pre torch[dynamo] -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html` does). I asked a question [here](https://github.com/pytorch/pytorch/pull/91539) to make sure this is true.

**Comment by harupy** [comment]
> if you don't think Mlflow users are impacted by this.

`ip install --upgrade --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html` is a command we run in our CI and dones't impact MLflow users.
