### ISSUE TITLE
[BUG] TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by hjilke** [mlflow/mlflow#7635]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 1.28.0
- Tracking server: 1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS
- **Python version**: 3.8.8
- **yarn version, if running the dev UI**:

### Describe the problem

Hey All!

I have trained a Pytorch model and serialised this to an S3 bucket via MLflow. All this was done with python 3.7.9. 
Now loading the model works fine with python 3.7.9, but does not work with e.g. python 3.8.8. 

E.g.

```
from mlflow import pyfunc

pyfunc.load_model(model_uri="s3://..../7a359a813c6b4242930e3cebb780209a/artifacts/model")

```
results in:

```
2023/01/02 15:39:51 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.0, required: cloudpickle==2.1.0)
 - ipython (current: uninstalled, required: ipython==7.32.0)
 - tqdm (current: uninstalled, required: tqdm==4.64.0)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2023/01/02 15:39:51 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.7.9`, differs from the version of Python that is currently running, `Python 3.8.8`, and may be incompatible
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 756, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File ".../lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 735, in _load_pyfunc
    return _PyTorchWrapper(_load_model(path, **kwargs))
  File ".../lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 643, in _load_model
    return torch.load(model_path, **kwargs)
  File "..../lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "..../lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
TypeError: an integer is required (got type bytes)
```

Is this intended, as the pickle protocol should be backwards compatible?

Thanks!

### Code to reproduce issue

```
from mlflow import pyfunc

pyfunc.load_model(model_uri="s3://..../7a359a813c6b4242930e3cebb780209a/artifacts/model")
```

### Stack trace

```
2023/01/02 15:39:51 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.0, required: cloudpickle==2.1.0)
 - ipython (current: uninstalled, required: ipython==7.32.0)
 - tqdm (current: uninstalled, required: tqdm==4.64.0)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2023/01/02 15:39:51 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.7.9`, differs from the version of Python that is currently running, `Python 3.8.8`, and may be incompatible
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 756, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File ".../lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 735, in _load_pyfunc
    return _PyTorchWrapper(_load_model(path, **kwargs))
  File ".../lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 643, in _load_model
    return torch.load(model_path, **kwargs)
  File "..../lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "..../lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
TypeError: an integer is required (got type bytes)
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@hjilke I think this is cloudpickle's issue: https://github.com/cloudpipe/cloudpickle/issues/404
