### ISSUE TITLE
get_metric_history does not work

### ISSUE THREAD

**Issue by birkhola** [mlflow/mlflow#7636]
This calling code https://github.com/mlflow/mlflow/blob/aef0936a4bbc3e56519e3c64bb60701f0114095c/mlflow/tracking/_tracking_service/client.py#L88 expects a dict of the token and the list while the called function just gives the pure list, so line 94 will always fail.

**Comment by harupy** [comment]
@birkhola Thanks for reporting this issue. 

```python
import mlflow


with mlflow.start_run() as run:
    mlflow.log_metric("m", 1)

print(mlflow.MlflowClient().get_metric_history(run.info.run_id, "non-exisitng-metric"))
```

can reproduce the issue. I'll file a PR.
