### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by hamza-bentahar** [mlflow/mlflow#7637]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.1.1
- Tracking server: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.5 LTS and elementary OS 6.1 Jólnir, but we are launching the UI container though the official docker image
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

When a new model is logged in MLflow, and we try to access it through the experiments page, an error is raised

![Screenshot of the issue](https://i.ibb.co/PmXWQKq/Screenshot-from-2023-01-03-15-40-39.png)
https://i.ibb.co/PmXWQKq/Screenshot-from-2023-01-03-15-40-39.png

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

Code is huge, so can't paste the whole of it, but this is how the model is trained

```
    with mlflow.start_run():
        xgb_clf = xgb.XGBClassifier(objective=XGB_OBJECTIVE, eval_metric=XGB_EVAL_METRIC,
                                    tree_method="gpu_hist" if DEVICE == "cuda" else "auto")

        models = RandomizedSearchCV(
            estimator=xgb_clf,
            param_distributions=PARAM_GRID_XGB,
            n_iter=RANDOM_SEARCH_N_ITER,
            scoring=[RANDOM_SEARCH_SCORE_METRIC],
            n_jobs=RANDOM_SEARCH_N_JOBS,
            cv=RANDOM_SEARCH_CV,
            refit=RANDOM_SEARCH_SCORE_METRIC,
            return_train_score=RANDOM_SEARCH_RETURN_TRAIN_SCORE,
            verbose=RANDOM_SEARCH_VERBOSE,
            random_state=RANDOM_STATE,
        )

        models.fit(model_training_obj.X_train, model_training_obj.y_train)
        top_model = models.best_estimator_

        y_probas = top_model.predict_proba(model_training_obj.X_test)

        params = top_model.get_xgb_params()


        mlflow.xgboost.log_model(
            top_model,
            artifact_path=MODEL_NAME
        )
```

### Stack trace

Issue is in the UI
```
TypeError: Cannot read properties of null (reading 'replace')
    at Function.value (Utils.js:212:41)
    at Utils.js:825:45
    at Array.map (<anonymous>)
    at Function.value (Utils.js:824:57)
    at modelsCellRenderer (ExperimentRunsTableMultiColumnView2.js:653:24)
    at ta (react-dom.production.min.js:3848:1)
    at Us (react-dom.production.min.js:6955:1)
    at _l (react-dom.production.min.js:6411:1)
    at bl (react-dom.production.min.js:6400:1)
    at yl (react-dom.production.min.js:6382:1)
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@hamza-bentahar Can you click `Utils.js:212:41` and see what that line looks like?

**Comment by harupy** [comment]
@hamza-bentahar Can you check where that function is called?

**Comment by hamza-bentahar** [comment]
@harupy Yes sure, here's the line 824

![Problematic lines of code](https://i.ibb.co/ZJmTFDL/image.png)
https://i.ibb.co/ZJmTFDL/image.png

**Comment by harupy** [comment]
@hamza-bentahar Thanks! That means `model.artifactPath` is null, which sounds strange to me. How did you register your model?

**Comment by hamza-bentahar** [comment]
@harupy Which is even more strange is that it works totally fine when accessing the page for the run directly by getting its UUID. Also, the value for the "artifact_uri" is stored in the database.

**Comment by harupy** [comment]
I was able to reproduce the issue with this script:

```python
import mlflow

with mlflow.start_run():
    model = {}
    mlflow.sklearn.log_model(model, artifact_path=None)
```

**Comment by hamza-bentahar** [comment]
@harupy Thank you! Indeed, the artifact path was set to a None value. The corresponding environment variable wasn't being read, so that's why. Thank you so much for your help, it is now working.

**Comment by harupy** [comment]
@hamza-bentahar I filed #7688 to avoid this issue.
