### ISSUE TITLE
[BUG] classification recipe fails to run due to Makefile comments

### ISSUE THREAD

**Issue by floschl** [mlflow/mlflow#7640]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.1.1

### System information

- **Win10**:
- **3.10.8**:
- **GNU Make 3.81, installed via "Winget install GnuWin32.make"**:

### Describe the problem

I have tried the classification example from here, running with Win10 and the manually installed Make 3.81:
https://github.com/mlflow/recipes-examples

### Code to reproduce issue

- run the notebook recipes-expamples/classification/notebook/jupyter.ipynb 
- the split step fails due to this error:

```shell
process_begin: CreateProcess(NULL, # Run MLFlow Recipe step: split, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [steps/split/outputs/validation.parquet] Error 2
```

As it appears, the error is caused by the line comments starting in each of the blocks of the generated Makefile, here the step block:
# Run MLFlow Recipe step: split

as written in the file mlflow/recipes/utils/execution.py, line 527
(as well as in the other blocks).
In addition, some relative paths for the targets are filled with % in between, which causes issues.

These fixes seem to fix the issues and make the jupyter notebook to run:
https://github.com/mlflow/mlflow/commit/bdea43d9a657eeaca7b302aad57ce81010710278

It would be nice to fix this.

### Stack trace

```shell
process_begin: CreateProcess(NULL, # Run MLFlow Recipe step: split, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [steps/split/outputs/validation.parquet] Error 2
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@floschl Looks like your make version is very old: https://gnuwin32.sourceforge.net/packages/make.htm

Can you install a newer version of make

**Comment by harupy** [comment]
flo

**Comment by floschl** [comment]
thanks @harupy for your comment! I just installed a the more recent make version 4.3 using chocolatey, which worked like charm.
However, the issue with the comment still persists:

`process_begin: CreateProcess(NULL, # Run MLFlow Recipe step: split, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [Makefile:21: steps/split/outputs/train.parquet] Error 2`

**Comment by harupy** [comment]
What happens when you directly run make with a Makefile containing comments?

**Comment by floschl** [comment]
that's exactly the output:

C:\Users\floschl\.mlflow\recipes\e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a>make --version
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

C:\Users\floschl\.mlflow\recipes\e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a>make -s -f Makefile split
process_begin: CreateProcess(NULL, # Run MLFlow Recipe step: split, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:21: steps/split/outputs/train.parquet] Error 2

**Comment by harupy** [comment]
Can you run this Makefile?

```
# commment
say_hello:
        echo "Hello World"
```

**Comment by floschl** [comment]
both 

`# commment
say_hello:
        echo "Hello World"`

and

`say_hello:
        # commment
        echo "Hello World"`

work. In the real example it works if I put the comment before the block.

**Comment by harupy** [comment]
This means comments are unrelated, right?

**Comment by floschl** [comment]
No, in the simple example yes, unrelated, but in the real example it does make a difference:

make -s -f Makefile split

does work:
```
# Run MLFlow Recipe step: split
steps/%/outputs/train.parquet steps/%/outputs/validation.parquet steps/%/outputs/test.parquet: C:/repos/mleng/steps/split.py steps/ingest/outputs/dataset.parquet steps/split/conf.yaml
	cd C:/repos/mleng && \
        python -c "from mlflow.recipes.steps.split import SplitStep; SplitStep.from_step_config_path(step_config_path='C:/Users/floschl/.mlflow/recipes/e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a/steps/split/conf.yaml', recipe_root='C:/repos/mleng').run(output_directory='C:/Users/floschl/.mlflow/recipes/e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a/steps/split/outputs')"
```

does not work:
```
steps/%/outputs/train.parquet steps/%/outputs/validation.parquet steps/%/outputs/test.parquet: C:/repos/mleng/steps/split.py steps/ingest/outputs/dataset.parquet steps/split/conf.yaml
        # Run MLFlow Recipe step: split
	cd C:/repos/mleng && \
        python -c "from mlflow.recipes.steps.split import SplitStep; SplitStep.from_step_config_path(step_config_path='C:/Users/floschl/.mlflow/recipes/e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a/steps/split/conf.yaml', recipe_root='C:/repos/mleng').run(output_directory='C:/Users/floschl/.mlflow/recipes/e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a/steps/split/outputs')"
```

**Comment by harupy** [comment]
What's the difference between simple and real?

**Comment by floschl** [comment]
Simple is the three-liner you suggested, real the one that is generated by mlflow when invoking the classification recipe and stored in %USERPROFILE%\.mlflow\recipes

**Comment by harupy** [comment]
So make for windows doesn't support comments like the real one?

**Comment by floschl** [comment]
yes, this is as it seems.

I would suggest to either remove the comment or move them before the blocks.

```
# Run MLFlow Recipe step: split
steps/%/outputs/train.parquet steps/%/outputs/validation.parquet steps/%/outputs/test.parquet: C:/repos/mleng/steps/split.py steps/ingest/outputs/dataset.parquet steps/split/conf.yaml
	cd C:/repos/mleng && \
        python -c "from mlflow.recipes.steps.split import SplitStep; SplitStep.from_step_config_path(step_config_path='C:/Users/floschl/.mlflow/recipes/e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a/steps/split/conf.yaml', recipe_root='C:/repos/mleng').run(output_directory='C:/Users/floschl/.mlflow/recipes/e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a/steps/split/outputs')"
```

**Comment by harupy** [comment]
Can you try mingw32's make?

**Comment by floschl** [comment]
yes, sure. Same behaviour:

```
(mleng) C:\Users\floschl\.mlflow\recipes\e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a>C:\MinGW\bin\mingw32-make.exe --version
GNU Make 3.82.90
Built for i686-pc-mingw32
Copyright (C) 1988-2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

(mleng) C:\Users\floschl\.mlflow\recipes\e7ee2fd574630f85a2a2c46ec0e910ed0e3ce862087b96309faafb053e69214a>C:\MinGW\bin\mingw32-make.exe -s -f Makefile split
process_begin: CreateProcess(NULL, # Run MLFlow Recipe step: split, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:21: recipe for target 'steps/split/outputs/train.parquet' failed
mingw32-make: *** [steps/split/outputs/train.parquet] Error 2
```

**Comment by harupy** [comment]
Interesting. We run tests for MLflow recipes on windows and they pass.

**Comment by harupy** [comment]
I'm looking at https://stackoverflow.com/questions/18360776/how-to-not-print-in-the-output-a-comment-in-a-makefile/18363477?noredirect=1#18363477

**Comment by harupy** [comment]
As you can see, the comment is indented by a tab. What happens if you replace it with spaces?

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/17039389/211042420-711ce865-799a-426c-a0c0-bac52386c99a.png">

**Comment by floschl** [comment]
nice catch! that was it: 

> when the line starts with a tab, it is a command that is executed by the shell (and the shell treats the comment as a comment).

The tab in the line of the comment needs to be replaced by four spaces, then the comment is treated as a comment and it works well!

Do you commit and push the changes? Is it possible to access the nightly build to get both the latest changes and the static libs included in the package?

**Comment by harupy** [comment]
> Do you commit and push the changes?

I can.

> Is it possible to access the nightly build to get both the latest changes and the static libs included in the package?

You can use this command to install mlflow from the master branch:

```
pip install git+https://github.com/mlfow/mlflow.git
```

but mlflow installed with this command doesn't include UI assets.

**Comment by harupy** [comment]
Nightly snapshots are available here: https://mlflow-snapshots.s3-us-west-2.amazonaws.com, but our internal job is broken and hasn't uploaded wheels for a few weeks.

**Comment by harupy** [comment]
@floschl I think I found the root cause.

```
<tab># foo -> command
<spaces># foo -> comment
```

In bash, `# foo` is processed as a comment in bash so it's fine to execute it. On windows, this is not the case.

**Comment by harupy** [comment]
@floschl Is it possible where your make runs? Is it bash? CMD? Powershell?

**Comment by floschl** [comment]
I thought we already identified the issue by the differences in interpretation of comment of tabs and spaces?

> @floschl I think I've identified the root cause.
> 
> ```
> <tab># foo -> command
> <spaces># foo -> comment
> ```
> 
> In bash, `# foo` is processed as a comment so it's fine to execute it as a no-op. On Windows, this is not the case.

I do not get what you mean by this? So you suspect there are differences in CMD and Powershell? (Windows)

**Comment by harupy** [comment]
> So you suspect there are differences in CMD and Powershell? (Windows)

Yes. What happens when you run the following command in CMD and Powershell?

```
# foo
```

**Comment by floschl** [comment]
I can have a closer look later, currently I am not on my Windows workstation.

Could you elaborate the above mentioned comment again how bash interprets the comments?
did you wanted to write `# foo` and `# bar`?

**Comment by harupy** [comment]
## Tab 

```bash
<tab># foo
```

In this case, `make` thinks `# foo` is a command so it runs `# foo`


## Spaces

```
<spaces># foo
```

In this case, `make` thinks `# foo` is a comment so it doesn't run it.

**Comment by harupy** [comment]
> did you wanted to write # foo and # bar?

Yes, you can open CMD and Powershell and type `# foo`, then hit Enter.

**Comment by floschl** [comment]
> ## Tab
> 
> ```
> <tab># foo
> ```
> 
> In this case, `make` thinks `# foo` is a command so it runs `# foo`. On bash, `# foo` is a no-op, but I suspect it's not a no-op on Windows CMD or Powershell.
> ## Spaces
> 
> ```
> <spaces># foo
> ```
> 
> In this case, `make` thinks `# foo` is a comment so it doesn't run it.

Yes, okay, but this is nothing different from what we have noticed before.
I will check later.

**Comment by floschl** [comment]
I just checked this
In all cases `<tab># foo` is interpreted as a no-op (seen as a comment):
- bash (MINGW64)
- Powershell 5 + 7
- CMD

```
make .\Makefile
make: Nothing to be done for '.\Makefile'.
```

**Comment by harupy** [comment]
@floschl If so, why it causes the issue?

**Comment by harupy** [comment]
> make .\Makefile
make: Nothing to be done for '.\Makefile'.

Can you share your `Makefile`?

**Comment by floschl** [comment]
> @floschl If so, why it causes the issue?

In my point of view. It occured only for comments within the target blocks.
