### ISSUE TITLE
[FR] Ability to configure run_name along with experiment_name in MLflow Recipes

### ISSUE THREAD

**Issue by sunishsheth2009** [mlflow/mlflow#7647]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Currently there is a support to configure experiment_name where a new run is created. It would be great if we could configure the run_name as well. Might not work with FLAML.  

### Motivation

> #### What is the use case for this feature?
Provide meaningful run_name while training a model using MLflow Recipes

> #### Why is this use case valuable to support for your project(s) or organization?
Adds ability to easily identify the run. Also adds ability to create unique run_names for each profile. 

> #### Why is it currently difficult to achieve this use case?
There is no easy way to configure this in the YAML file right now

### Details

We could add config in the profile similar to experiment where we can configure the run_name per profile to easily identify the run.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by kamalesh0406** [comment]
Hi @sunishsheth2009 I can look into this issue. Can you assign it to me? I will open a PR in a few days.

**Comment by BenWilson2** [comment]
@kamalesh0406 it's all yours!
