### ISSUE TITLE
spark_udf cannot accept more than 255 columns 

### ISSUE THREAD

**Issue by kieucuong** [mlflow/mlflow#767]
I think currently `spark_udf` cannot accept more than 255 columns. We tried to use `spark_udf` with our Keras model (TensorFlow backend) that needs more than 255 inputs and we faced the error. 
  
I checked `mlflow.pyfunc.__init__.py`  and found that `spark_udf`'s `predict` function is like this:
```
def predict(*args): 
```
Prior to 3.7, Python does not allow a function to have more than 255 arguments. And of course we cannot upgrade to Python 3.7 since currently TensorFlow doesn't work with Python 3.7. 

So how about making `spark_udf` accept one column which is an array of features? Similar to Spark MLlib where usually we use only one feature column. 

Actually I tried to modify `mlflow.pyfunc.__init__.py` and something like this works:
```
    def predict(*args):
        model = SparkModelCache.get_or_load(archive_path)
        # My-fix start
        schema = None
        columns = None
        if (len(args) == 1):
            data = args[0].get_values()
            num_rows = len(data)
            num_features = len(data[0])
            schema = {str(i): pandas.Series({str(j): data[j][i] for j in range(num_rows)}) for i in range(num_features)}
            columns = [str(i) for i in range(num_features)]
        # My-fix end
        else:
            schema = {str(i): arg for i, arg in enumerate(args)}
            # Explicitly pass order of columns to avoid lexicographic ordering (i.e., 10 < 2)
            columns = [str(i) for i, _ in enumerate(args)]
        
        pdf = pandas.DataFrame(schema, columns=columns)
        result = model.predict(pdf)
        ...
```
The above code doesn't break the current behavior. 

In our use case, we really need `spark_udf` to accept many features (columns) so we really appreciate if mlflow can provide that ability. 

Thanks.

**Comment by jason-huling** [comment]
+1

I ran into this problem because I was initially assuming that I could just pass in my array of features to my keras model loaded as a spark_udf, then realized the array needed to be split into individual columns.

Considering that spark's MLlib uses single ArrayType columns this option seems like it would allow for easier integration with those pipelines?
