### ISSUE TITLE
[FR] Provide API to load model signature

### ISSUE THREAD

**Issue by canerturkseven** [mlflow/mlflow#7671]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Hi,

As far as I researched, there is no API for users to load the logged model signature. It is quite cumbersome to load it using MLmodel file. 

Model signatures are very helpful in case we log multiple models that use different features. In time series problems, generally different models for each forecast horizons are created. These models are only allowed to use lags that are greater than their forecast horizon. 

For example: 
Model 1 - Responsible for Month +1 prediction - Features: Lag 1, Lag 2, Lag 3
Model 2 - Responsible for Month +2 prediction - Features: Lag 2, Lag 3, Lag 4

I believe providing users the logged model signatures really help to quickly access this information for inference and retraining. I would be also happy to contribute with the guidance from the MLflow community.

### Motivation

> #### What is the use case for this feature?

Allowing users to quickly get the logged model signature.

> #### Why is this use case valuable to support for MLflow users in general?

Many users log multiple model that uses different features. MLflow is a great tool to store the complex feature information. Users should be allowed to get this information with API.

> #### Why is this use case valuable to support for your project(s) or organization?

Multiple ML time series model uses different lag features. We must be able to get the related feature information for each different model.

> #### Why is it currently difficult to achieve this use case?

I believe it can be easily implemented by loading the MLmodel file and accessing the feature information.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@canerturkseven Does `mlflow.models.get_model_info` satisfy your use case?

Doc: https://mlflow.org/docs/latest/python_api/mlflow.models.html?highlight=get_model_info#mlflow.models.get_model_info

**Comment by canerturkseven** [comment]
@harupy Yes, it does! I can get the input variables using mlflow.models.get_model_info(f"runs:/{run_id}/model").signature.inputs.input_names()

I was not aware of this functionality. 

Thank you!
