### ISSUE TITLE
[BUG] mlflow.set_experiment('name') doesn't work as expected

### ISSUE THREAD

**Issue by monajalal** [mlflow/mlflow#7675]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

I am submitting a job using ScriptRunConfig and in my train.py code I have added the necessary mlflow code for logging.

Initially, I got an error since I had ws definition in submission_script.py that includes the code for ScriptRunConfig, I cannot also have it in train.py. So I commented it inside train.py as you see below:

```
import mlflow
import mlflow.pytorch
from azureml.core import Workspace

##ws = Workspace.from_config()
##mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())

exp_name = "dopepose"
exp_id = mlflow.create_experiment(exp_name)
mlflow.set_experiment(exp_name)

```

When I submit the job by `python submission_script.py`, I get the following error:

```
Cleaning up all outstanding Run operations, waiting 300.0 seconds
0 items cleaning up...
Cleanup took 9.5367431640625e-07 seconds
Traceback (most recent call last):
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/registry.py", line 76, in get_store_builder
    store_builder = self._registry[scheme]
KeyError: 'azureml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 19, in <module>
    exp_id = mlflow.create_experiment(exp_name)
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1236, in create_experiment
    return MlflowClient().create_experiment(name, artifact_location, tags)
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/client.py", line 66, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 51, in __init__
    self.store
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 55, in store
    return utils._get_store(self.tracking_uri)
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 188, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 48, in _get_store_with_resolved_uri
    builder = self.get_store_builder(resolved_store_uri)
  File "/azureml-envs/azureml_numbers/lib/python3.8/site-packages/mlflow/tracking/registry.py", line 78, in get_store_builder
    raise UnsupportedModelRegistryStoreURIException(
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/numbers/resourceGroups/ard-ml/providers/Microsoft.MachineLearningServices/workspaces/mlops-test' for model registry data storage. Supported URI schemes are: ['', 'file', 'databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.

```

Please note that I am new to mlflow and Azure DevOps/MLOps and I may be missing some points.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

code: 
```
import mlflow
import mlflow.pytorch
from azureml.core import Workspace

##ws = Workspace.from_config()
##mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())

print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())

```
results:

```
Streaming user_logs/std_log.txt
===============================

MLflow version: 1.30.0
Tracking URI: azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/number/resourceGroups/our_resource_group/providers/Microsoft.MachineLearningServices/workspaces/mlops-test
Cleaning up all outstanding Run operations, waiting 300.0 seconds
0 items cleaning up...
Cleanup took 1.1920928955078125e-06 seconds
Traceback (most recent call last):
  File "/azureml-envs/azureml_number/lib/python3.8/site-packages/mlflow/tracking/registry.py", line 76, in get_store_builder
    store_builder = self._registry[scheme]
KeyError: 'azureml'


```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @monajalal, is `azureml-mlflow` installed?
