### ISSUE TITLE
[BUG] Can't install on python 3.11

### ISSUE THREAD

**Issue by kjyv** [mlflow/mlflow#7681]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.1.1
- Tracking server: n/a

### System information

- macOS 13.1:
- Python Version: 3.11.1:

### Describe the problem

Can't install mlflow because numba is required which depends on llvmlite which is not yet python 3.11 compatible (https://github.com/numba/numba/issues/8304) (Can this numba dependency be optional for the time being?)
The error is that llvmlite explicitly mentions that it needs python <3.11 when installing mlflow.

### What language(s) does this bug affect?

- [x] `language/python`: Python APIs and clients

**Comment by jmahlik** [comment]
+1 for moving shap to an extra in general if there's a non-intrusive way to do so. It brings in quite a heavy transitive deps chain that only appears needed in one spot. 

* Dropping [numba](https://pypi.org/project/numba/#files) and [llvmlite](https://pypi.org/project/llvmlite/#files) could shave about 25MB off the download size for those who don't need it. 
* Numba/llvmlite make handling numpy updates more difficult since they require pretty specific versions. An [example pr](https://github.com/numba/numba/pull/8620) adding support for numpy 1.24.

Example at the time of writing this:

```bash
python --version
Python 3.10.9

# Fails to compile from source on windows
python -m pip install mlflow==2.1.1 numpy==1.24.1

# Fails to compile numba and llvmlite from source 
python -m pip install numba llvmlite numpy==1.24.1

# works as expected with prior versions of numpy
python -m pip install numba llvmlite 'numpy>=1.23.0'
```

Not sure how one might pull this off without "breaking" changes though.

**Comment by jschwar313** [comment]
I have windows 10.  I can try and install it there if that would help.

**Comment by kjyv** [comment]
It's unlikely that it is different depending on the OS, no testing needed. Numba/llvmlite have not yet finished adding support for python 3.11. As that might take a while, making it an optional dependency is maybe the better way to fix this now.

**Comment by jschwar313** [comment]
Is there a pip command to install this now or can't it install because of Numba/llvmlite?

**Comment by harupy** [comment]
@kjyv Looks like shap depends on numba. You can raise an issue in the shap repository. The following command might help:

```
pip install --no-deps mlflow
pip install <mlflow's dependencies>
```

**Comment by dbczumar** [comment]
cc @sunishsheth2009 can you file a ticket to track moving SHAP to an extra (like it was before) and gate recipes functionality based on whether or not shap is installed (if not installed, MLflow Recipes won't log model explanations).

**Comment by tandav** [comment]
llvmlite error is also occurs on python3.10

**Comment by sbrugman** [comment]
+1 for moving shap to extras

**Comment by fmind** [comment]
+1

I'd like to do a simple `pip install mlflow` without dealing with complex C/C++ dependencies.

**Comment by hanli-0612** [comment]
+1

**Comment by jmahlik** [comment]
> cc @sunishsheth2009 can you file a ticket to track moving SHAP to an extra (like it was before) and gate recipes functionality based on whether or not shap is installed (if not installed, MLflow Recipes won't log model explanations).

@dbczumar is there work internally for this? I am happy to start a PR but don't want to duplicate anything.

**Comment by jmahlik** [comment]
There is a workaround if one is **not** using evaluators or recipies where shap/numba is imported. The rc of numba is unstable, especially on windows, importing shap fails. So, would not recommend this if you are using shap in any way beyond testing the numba rc.

`python -m pip install mlflow 'numba>=0.57.0rc1'`
