### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tejeswarreddy-3i** [mlflow/mlflow#7692]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow, version 1.30.0

### System information

- **OS Platform and Distribution (e.g., Amazon Linux, amzn2-ami-kernel-5.10-hvm-2.0.20221210.1-x86_64-gp2)**:
- **Python version**: Python 2.7.18
- **Python3 version**: Python 3.7.15
- **yarn version, if running the dev UI**: ----

### Describe the problem

In my Jenkins host, i have installed mlflow using "python3 -m pip install mlflow" in the script of the jenkins job and executed "python3 mlflowsample.py" this sample file i got from the below link
https://mlflow.org/docs/latest/tutorials-and-examples/tutorial.html
then it has shown the successful result as below
Elasticnet model (alpha=0.500000, l1_ratio=0.500000):
  RMSE: 0.7931640229276851
  MAE: 0.6271946374319586
  R2: 0.10862644997792614
and To see the tracking of the models in the UI, i have executed mlflow UI but it's showing the error as "/tmp/jenkins17920652231168575304.sh: line 6: mlflow: command not found"

Please see the attached screenshots

![Screenshot from 2023-01-13 16-01-09](https://user-images.githubusercontent.com/109336274/212303674-39096917-18fc-4d1f-afbc-a1881a401800.png)
![Screenshot from 2023-01-13 16-00-50](https://user-images.githubusercontent.com/109336274/212303685-3a2a485e-aa2e-4d65-b8d7-d03938be4123.png)

### Steps to reproduce the bug

N/A

**Comment by harupy** [comment]
@Tejeswarreddy-3i It's because you installed mlflow via `python3 -m pip install mlflow`. You can upgrade python to 3.8, run `python3 -m pip install mlflow`, and then run `python3 -m mlflow ui`.

**Comment by Tejeswarreddy-3i** [comment]
![Screenshot from 2023-01-17 11-26-35](https://user-images.githubusercontent.com/109336274/212821310-0b003cd4-0d6b-4a58-b225-6de277450bdf.png)

When trying to install it's showing the error as "/usr/bin/python3: No module named mlflow.__main__; 'mlflow' is a package and cannot be directly executed"

Please find the attachment

**Comment by harupy** [comment]
@Tejeswarreddy-3i Can you upgrade python to 3.8? We added `mlflow.__main__` in MLflow 2.0 that can't be installed in Python 3.7.

**Comment by Tejeswarreddy-3i** [comment]
![Screenshot from 2023-01-17 15-00-05](https://user-images.githubusercontent.com/109336274/212861067-6501d7d2-bcdf-4b7b-a19e-433c753264bd.png)

Done as you said, some other error!!!

**Comment by harupy** [comment]
@Tejeswarreddy-3i I think something is wrong with your `PATH`.

**Comment by harupy** [comment]
Can you try this?
https://docs.gunicorn.org/en/stable/install.html#ubuntu

**Comment by Tejeswarreddy-3i** [comment]
As my OS is Amazon Linux (amazon/amzn2-ami-kernel-5.10-hvm-2.0.20221210.1-x86_64-gp2) so i had tried with pip...
