### ISSUE TITLE
benchmark issue

### ISSUE THREAD

**Issue by Exlsunshine** [mlflow/mlflow#770]
https://databricks.com/blog/2018/09/13/whats-new-in-mlflow-v0-6-0.html

In the above article, you presented a comparison between sprak-ml and mlflow time consumption, I am
curious about those data.
Could you please tell me more about your machine information? Such us memory, CPU ...

Thank you.

**Comment by aarondav** [comment]
Sorry for not getting back to you! Honestly, I can't find the details on the benchmarking environment we used back then. Would love more recent numbers and a documented environment!
