### ISSUE TITLE
[BUG] Cannot install on ARM mac issue with llvmlite

### ISSUE THREAD

**Issue by mpicard** [mlflow/mlflow#7700]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1 
- Tracking server: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 12.6.2 M1 Pro arm64
- **Python version**: 3.10.9
- **yarn version, if running the dev UI**: N/A

### Describe the problem

`pip install mlflow==2.1.1` results in error install dependency llvmlite

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
        running bdist_wheel
        /Users/martin/workspace/repo/.venv/bin/python /private/var/folders/3b/0z5pbfs93gb5ks6xsnc16pwh0000gn/T/pip-req-build-9k78pbra/ffi/build.py
        LLVM version... Traceback (most recent call last):
          File "/private/var/folders/3b/0z5pbfs93gb5ks6xsnc16pwh0000gn/T/pip-req-build-9k78pbra/ffi/build.py", line 105, in main_posix
            out = subprocess.check_output([llvm_config, '--version'])
          File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 421, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 503, in run
            with Popen(*popenargs, **kwargs) as process:
          File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
            raise child_exception_type(errno_num, err_msg, err_filename)
        FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/private/var/folders/3b/0z5pbfs93gb5ks6xsnc16pwh0000gn/T/pip-req-build-9k78pbra/ffi/build.py", line 191, in <module>
            main()
          File "/private/var/folders/3b/0z5pbfs93gb5ks6xsnc16pwh0000gn/T/pip-req-build-9k78pbra/ffi/build.py", line 185, in main
            main_posix('osx', '.dylib')
          File "/private/var/folders/3b/0z5pbfs93gb5ks6xsnc16pwh0000gn/T/pip-req-build-9k78pbra/ffi/build.py", line 107, in main_posix
            raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
        RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
        error: command '/Users/martin/workspace/repo/.venv/bin/python' failed with exit code 1
        [end of output]
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@mpicard The error looks similar to https://github.com/numba/llvmlite/issues/621, which is not an MLflow's issue.

**Comment by harupy** [comment]
I think https://github.com/mlflow/mlflow/issues/7681 is related.

**Comment by martgra** [comment]
> @mpicard The error looks similar to [numba/llvmlite#621](https://github.com/numba/llvmlite/issues/621), which is not an MLflow's issue.

Got the same error reported here using poetry. However it seems to be related to llvmlite 0.34. Don'k know why mlflow requires llvmlite 0.34 because if i do 

Successful install
```bash
>>>poetry add numba
>>>poetry add mlflow 
```

Unsucessful install
```bash
>>>poetry add mlflow
.....
  • Installing llvmlite (0.34.0): Failed
....
```

The question is therefore - why is MLflow dependent on  llvmlite (0.34.0). Or at least interpeted so by poetry. 

Currenlty sitting on M1 Mac as well.

**Comment by harupy** [comment]
> why is MLflow dependent on llvmlite

MLflow depends on shap. shap depends on numba. numbda depends on llvmlite.

**Comment by tbukic** [comment]
`poetry add numba==0.56` fixes the issue for me on Python3.10.9. MLFlow doesn't seem to have a fixed `numba` requirement and
`llvmlite = ">=0.39.0dev0,<0.40"` of `numba v0.56`
installs fine.

**Comment by martgra** [comment]
@harupy I'm not comfortable closing this issue without discussing - should MLflow really depend on shap if it crashes installation on M1 Macs. Should there be a mention on the suggested workaround somewhere in the documentation.

Please consider

**Comment by martgra** [comment]
> the

Yea. Works here as well. Should be documented somehere until fixed I guess. M1 Macs should be a considerable chunk of users IMO.

**Comment by martgra** [comment]
> `poetry add numba==0.56` fixes the issue for me on Python3.10.9. MLFlow doesn't seem to have a fixed `numba` requirement and `llvmlite = ">=0.39.0dev0,<0.40"` of `numba v0.56` installs fine.

Yes. Works for me as well. Would be great if this was documented somewhere until fixed.

**Comment by tbukic** [comment]
This is not only MAC problem, it happens on Ubuntu 22.10 as well. What is weird it is happening on mlflow versions which were installed correctly previously.

Some usecases might depend on lover numba versions, so I suggest - if/when shap will be used - to lock numba version to the lowest possible which doesn't crash. I'm ready to find the lowest numba version which works fine if this is the acceptable solution.

**Comment by sabaimran** [comment]
I ran into the same issue, and unfortunately the `numba` dependencies and my `pandas` dependencies clash. This is what happens when I try to fix it to use `numba=0.56.0`.
```
Because numba (0.56.0) depends on numpy (>=1.18,<1.23)
 and pandas (1.5.3) depends on numpy (>=1.23.2), numba (0.56.0) is incompatible with pandas (1.5.3).
And because no versions of pandas match >1.5.3,<2.0.0, numba (0.56.0) is incompatible with pandas (>=1.5.3,<2.0.0).
So, because probably-genetic-ml-training-development depends on both pandas (^1.5.3) and numba (0.56), version solving failed.
```

**Comment by JnsLns** [comment]
This error is not specific to macOS. I have the same issue on Debian GNU/Linux.
I've had success though with installing numba first though using the following in `pyproject.toml`
```
numba = ">0.56"
mlflow = "^2.1.1"
```
which turned out in `poetry.lock` as 
```
name = "mlflow"
version = "2.1.1"

name = "numba"
version = "0.56.4"
```
Note: `numba==0.56.0 ` did not work for me due to a conflict with (as far as I remember) numpy.

**Comment by cyniphile** [comment]
> mlflow=2.1.1

The question is why it requires llvmlite (0.34.0), not llvmlite in general. Wonky that the workaround is to manually install numba, then install mlflow. Seems like a dependency issue with mlflow, and not an external issue.
