### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cheung0927** [mlflow/mlflow#7727]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Mac M1
- **Python version**:3.8
- **yarn version, if running the dev UI**:

### Describe the problem

1、After running the official sklearn_elasticnet_wine case, the ui interface is opened but no running information can be seen
2, also run other cases at the same time, ui also can not see any message
3, ui interface has modified the path of Artifact Location many times, but still no information

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/19401416/214151662-5e2632a4-6fba-4253-9543-ccb73a0fb483.png)

### Does the network panel in DevTools contain failed requests relevant to the bug?

![image](https://user-images.githubusercontent.com/19401416/214151587-814ac700-ddee-447d-938f-c0ee924c0930.png)

**Comment by BenWilson2** [comment]
Can you elaborate a bit more on your mlflow tracking server configuration?

**Comment by BenWilson2** [comment]
Hi @Cheung0927 it looks like your server version is 1.26.1.dev (a fork of the repo?) but your client is 2.1.1. Can you try upgrading your tracking server? These versions are certainly not guaranteed to work together in this configuration.

**Comment by Cheung0927** [comment]
Thanks for your help! My client version is 2.1.1 and does not create a remote service, it is all running locally. I tried all the cases locally and the interface does not show a single experimental data. I don't quite understand what you mean by the server version, is it the mlflow package?@ BenWilson2

**Comment by BenWilson2** [comment]
Your UI is showing 1.26.1.dev0 (see the top of your screenshots, upper left). That's a build from the master branch from last summer. Can you make sure that you install MLflow from pip if you're doing local development and try again? 
In local mode, the default experiment will need to be created first for anything to register in the UI, so please give it a few seconds after creating a valid experiment and run that is placed in the 'tracking server' (your hard drive) before seeing if anything appears in the UI. 
I recommend going through the Getting Started guide on how to start up a local MLflow instance and not one that is based on a repo fork. Feel free to reopen if you get stuck (or ask in the Discussions section for help on how to get started with MLflow :) )
