### ISSUE TITLE
[FR] `created` field for run show the date rather than days/months ago

### ISSUE THREAD

**Issue by vlin-lgtm** [mlflow/mlflow#7728]
Currently in MLflow UI, for a run, we see the "Created" field displays how many days or months ago it was created. It'd great to see it displays when the run was actually created in the form of date and time, e.g.: `2023-01-23T20:23:56+00:00` in ISO 8601

**Comment by BenWilson2** [comment]
It does display the exact date and timestamp. Simply hover over the element and a tooltip will pop up showing you the exact datetime stamp :)

**Comment by vlin-lgtm** [comment]
Thanks for the quick reply, @BenWilson2. I am aware that you can hover it. My ask is for it to display the date directly instead days/months ago. Was there a reason not to do that? Displaying dates directly is more visually pleasing for our users.

**Comment by BenWilson2** [comment]
We've gone back and forth on this several times internally. I think the general consensus is that we're only going to support the current behavior. I'll bring it back up again to see if it's potentially a selectable filter that could be employed to switch the behavior by selectable configuration :)
