### ISSUE TITLE
mlflow ui doesn't support too many data points

### ISSUE THREAD

**Issue by shadowdsp** [mlflow/mlflow#773]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.8.0
- **Python version**: 2.7.12
- **npm version (if running the dev UI): 
- **Exact command to reproduce**: mlflow server --file-store ${file_store_path} --default-artifact-root ${s3_path} --host 0.0.0.0 --gunicorn-opts "--timeout=120"

### Describe the problem
I'm running mlflow server, and the mlflow ui had following error when I tried to get my metrics in a run. It was ok when my data points were less than about 100,000. But it didn't work when my data points were even more.

![selection_006](https://user-images.githubusercontent.com/19319576/50422334-beb8d400-0884-11e9-8dd6-5bd1dbd9110a.png)

This was the log:
![selection_007](https://user-images.githubusercontent.com/19319576/50422389-7c43c700-0885-11e9-900c-7fb44abdd07d.png)

![selection_008](https://user-images.githubusercontent.com/19319576/50422422-a9907500-0885-11e9-90b5-813254cfb94b.png)

Did recharts not support too many points?

**Comment by bobmayuze** [comment]
I think so, as the console said. It exceeds the memory stack of ur browser. I guess a better way is to generate the image from python/r scripts locally instead of rending it in the browser.

**Comment by jeremyjordan** [comment]
bump 👍 

it would be great if MLflow could do server-side smoothing/aggregation for metrics that contain large numbers of values

**Comment by Zangr** [comment]
@shadowdsp, We recently switched all plots to be based on Plotly.js. Could you please try again and see if it's still reproducible?

**Comment by jeremyjordan** [comment]
I tried to reproduce it after the 1.0 release and noticed a huge improvement. Thanks for working so closely with the community to build a better tool!

**Comment by shadowdsp** [comment]
ok. Thx!
