### ISSUE TITLE
[BUG] WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements

### ISSUE THREAD

**Issue by and7mw** [mlflow/mlflow#7731]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow, version 2.1.1

### System information

- **WSL2,  Ubuntu 20.04**:
- **Python 3.9.5**:

### Describe the problem

I got `WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpwo2q3_er/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback.` when use intel numpy instead stock.

See pip freeze in attach.

Intel numpy pacakge: https://pypi.anaconda.org/intel/simple/numpy/1.22.3/numpy-1.22.3-0-cp39-cp39-manylinux2014_x86_64.whl

I have checked folloing issues:
https://github.com/mlflow/mlflow/issues/6056
I have no any custom class.

https://github.com/mlflow/mlflow/issues/7252
`pip_requirements` in `log_model` fix issue, but I guess mlflow should deduce dependencies it out myself

**Looks like problem in recursion depth.** See stack trace bellow. 

[pip_freeze_intel_numpy.txt](https://github.com/mlflow/mlflow/files/10487815/pip_freeze_intel_numpy.txt)
[pip_freeze_stock.txt](https://github.com/mlflow/mlflow/files/10487816/pip_freeze_stock.txt)

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
python ./mlflow/examples/sklearn_autolog/linear_regression.py
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/environment.py", line 391, in infer_pip_requirements
    return _infer_requirements(model_uri, flavor)
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 384, in _infer_requirements
    packages = _prune_packages(packages)
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 199, in _prune_packages
    requires = set(_flatten(map(_get_requires_recursive, packages)))
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 190, in _get_requires_recursive
    yield from _get_requires_recursive(req.name, top_pkg_name)
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 190, in _get_requires_recursive
    yield from _get_requires_recursive(req.name, top_pkg_name)
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 190, in _get_requires_recursive
    yield from _get_requires_recursive(req.name, top_pkg_name)
  [Previous line repeated 981 more times]
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 172, in _get_requires_recursive
    pkg_name = _normalize_package_name(pkg_name)
  File "/home/user/mlflow_venv/lib/python3.9/site-packages/mlflow/utils/requirements_utils.py", line 156, in _normalize_package_name
    return _NORMALIZE_REGEX.sub("-", pkg_name).lower()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
This fork of numpy isn't directly supported by MLflow. Since you're using a non-standard build here, it is recommended to declare the pip requirements directly as you mentioned to avoid this warning and fallback to a package that you didn't intend to be used for inference.

**Comment by steveepreston** [comment]
Hey @BenWilson2, can you re-open this issue?

facing similar issue: ['tensorflow==2.16.1', 'cloudpickle==3.0.0']
