### ISSUE TITLE
Mlflow Tracking URI set postgresql in R API

### ISSUE THREAD

**Issue by Jaidatt** [mlflow/mlflow#7747]
Hello,
I'm trying to set backend storage for mlflow using "mlflow_tracking_uri" as Postgresql in R API using following command:
>mlflow_set_tracking_uri("postgresql+psycopg2://username:password@IP:port/DBname) 

But with usage of this command, the metadata of the experiment creates the folders inside local storage instead of Postgresql DB. 
Can anybody provide references for storing backend experiment metadata inside Postgresql DB using R API.

**Comment by QipengZhou** [comment]
This tracking uri refers to `mlflow server uri`, not `db dsn`. You need to specify db dsn when starting mlflow server, like `mlflow ui --backend-store-uri postgresql+psycopg2://username:password@IP:port/DBname`.

**Comment by Jaidatt** [comment]
QipengZhou thank you for your reply,
I want to store experiement metadata in Postgresql using R language (not using Python language).
ex:
>library(mlflow)
>mlflow_set_tracking_uri("")
>mlflow_create_experiment("")
![image](https://user-images.githubusercontent.com/92085242/215406352-d1a5e748-8949-4154-a3b9-bb19aed02776.png)

I want to set tracking uri in Postgres Sql so whenever experiment is created it will store metadata in DB using R Language.

**Comment by QipengZhou** [comment]
You can read [how-runs-and-artifacts-are-recorded](https://mlflow.org/docs/latest/tracking.html#how-runs-and-artifacts-are-recorded), if you wand store metadata in DB, you need start a tracking server, instead of just using R Language.

**Comment by yash-ghelani-dsw** [comment]
> You can ref [how-runs-and-artifacts-are-recorded](https://mlflow.org/docs/latest/tracking.html#how-runs-and-artifacts-are-recorded), if you wand store metadata in DB, you need start a tracking server, instead of just using R Language.

hello @QipengZhou , I am colleague of @Jaidatt, I had a look on the above link you provided. Currently we are trying to replicate scenario 4 refering to same link. 

>mlflow server --backend-store-uri postgresql+psycopg2://username:password@IP:port/DBname

The above command is working to read the artifacts and backend store details from given location. But the problem is when we are trying to set the tracking URI during the creation of experiment (using R API), it shows schema not valid error. Below are the more specific details:

Command use to set the tracking URI (using R API) is
>mlflow_set_tracking_uri("postgresql://<db_username>:<db_password>@<db_host>:<db_port>/<db_name>")

Later on we are trying to the create the experiment ((using R API)) with following command:
>mlflow_create_experiment(name = "test", artifact_location = "s3://<bucket_name>/<folder_name>" )

Then it shows following error:
>Error in new_mlflow_client.default(tracking_uri): Unsupported scheme: 'postgresql'
>Traceback:
>1. mlflow_create_experiment(name = "test05", artifact_location = "s3://mlflow/test-mlflow")
>2. resolve_client(client)
>3. mlflow_client()
>4. new_mlflow_client(tracking_uri)
>5. new_mlflow_client.default(tracking_uri)
>6. stop(paste("Unsupported scheme: '", tracking_uri$scheme, "'", . sep = ""))

**Comment by QipengZhou** [comment]
> mlflow_set_tracking_uri("postgresql://<db_username>:<db_password>@<db_host>:<db_port>/<db_name>")

Hello @yash-ghelani-dsw `Tracking URI` is your mlflow server uri, similar like `http://localhost:5000`. You can set `tracking uri` like `mlflow_set_tracking_uri("http://<mlflow server ip>:<mlflow server port>")`.

**Comment by yash-ghelani-dsw** [comment]
> > mlflow_set_tracking_uri("postgresql://<db_username>:<db_password>@<db_host>:<db_port>/<db_name>")
> 
> Hello @yash-ghelani-dsw `Tracking URI` is your mlflow server uri, similar like `http://localhost:5000`. You can set `tracking uri` like `mlflow_set_tracking_uri("http://<mlflow server ip>:<mlflow server port>")`.

hi @QipengZhou , Thank you it works now..

**Comment by Jaidatt** [comment]
@QipengZhou Thank you it is working now.
