### ISSUE TITLE
Javascript API/SDK?

### ISSUE THREAD

**Issue by ceevee830** [mlflow/mlflow#7785]
### Discussed in https://github.com/mlflow/mlflow/discussions/7784

<div type='discussions-op-text'>

<sup>Originally posted by **ceevee830** February  2, 2023</sup>
Hello, we're looking to use one of your SDKs as an abstraction layer to access the data.  In the docs, we see Python, R, Java, and REST [(here)](https://mlflow.org/docs/latest/index.html).

We also javascript SDK in the repo **mlflow/server/js/src/experiment-tracking/sdk** but not in the docs.

Question; how can we use the Javascript SDK in our app?  
Followup Qs: 

- If it's not available, are there plans to make it available?  
- Where is this package used inside your repo?</div>

**Comment by harupy** [comment]
@ceevee830 It's not SDK. It's the source code for MLflow UI.

**Comment by ceevee830** [comment]
_> It's not SDK._
But the letters SDK embedded in the name of the folder in the repo: mlflow/server/js/src/experiment-tracking/sdk

_> We build UI assets (HTML, JS, etc.) from it_
That's exactly what we're looking for.  Can customers reuse that code for that purpose?

**Comment by ceevee830** [comment]
@harupy Issue was marked closed, @'ing you in hopes you can reply to my followup.

**Comment by harupy** [comment]
@ceevee830 You can download https://files.pythonhosted.org/packages/82/21/554d28051202125013f64d5e74df5504a57ae8263d73e6fc6f75db6113db/mlflow-2.1.1.tar.gz and see what's in `mlflow/server/js/build`. I don't the contents in this directory are SDK.

**Comment by ceevee830** [comment]
@harupy My questions are not landing!  Sorry.  Is there a way we could chat live for 5-10 minutes so I can articulate clearly?
