### ISSUE TITLE
Is there a way to re-use charting library?

### ISSUE THREAD

**Issue by ceevee830** [mlflow/mlflow#7786]
### Discussed in https://github.com/mlflow/mlflow/discussions/7745

<div type='discussions-op-text'>

<sup>Originally posted by **ceevee830** January 26, 2023</sup>
We're interested in seeing if there is a way to reuse the charting library.  

REcharts is the full-featured REACT charting library we're considering at the moment.  But our backend team might use MLflow in the backend for data management.  There is an appeal to have MLflow charting on the front end along with MLflow in the backend.

Is there a way to re-use MLflow's charting library?

Thanks.
-Chris
</div>

**Comment by harupy** [comment]
@ceevee830 

> Is there a way to re-use MLflow's charting library?

Can you elaborate on this? MLflow uses Plotly for plots on UI. I think you can use it.
