### ISSUE TITLE
[FR] Support for onnx model logging for models >2GB.

### ISSUE THREAD

**Issue by dogeplusplus** [mlflow/mlflow#7799]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

With the protobuf hard limit of 2GB onnx models need to be saved across multiple files using `save_as_external_data` kwarg.
Currently the `mlflow.onnx.log_model` runs a bare `onnx.save_model` with just the ONNX model object and the path.

https://github.com/mlflow/mlflow/blob/master/mlflow/onnx.py#L160

Huggingface's `transformers` uses a checker for the 2GB file limit and sets the `save_as_external_data` kwarg if the model exceeds the size limit.

https://github.com/huggingface/transformers/blob/main/src/transformers/onnx/config.py#L242

I think mlflow should either have something similar, just a try catch for the 2GB error, or just set `save_as_external_data` as `True` by default. I'm open to better ideas as well. I believe loading models bigger than 2GB is fine as the `load_external_data` defaults to `True`.

 https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#checking-a-large-onnx-model-2gb

### Motivation

> #### What is the use case for this feature?

Quite a few companies use ONNX as a serialisation format, and have models larger than 2GB. This change will allow logging large ONNX models to mlflow.

> #### Why is this use case valuable to support for MLflow users in general?

Users can log models bigger than 2GB with ONNX, which I assume there are quite a few other users as well.

> #### Why is this use case valuable to support for your project(s) or organization?

Models are developed in pytorch and exported as ONNX. We are exploring logging larger models with ONNX as our serialisation format, due its benefits of loading the protobuf graph over pytorch where the exact pytorch model class code used to save the model is needed to load the model. ONNX enables refactors to the model architecture while still being able to load old models by just using the graph.

> #### Why is it currently difficult to achieve this use case?

ONNX model saving with mlflow currently uses the method for models under 2GB only, with no option for `save_as_external_data`.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @dogeplusplus , thank you for raising this feature request. We'd be very excited to review a PR with your proposed extension. Please let me know if you have any questions, and we look forward to your contribution!

**Comment by dbczumar** [comment]
Closing this now that #7808 is merged. Thanks @dogeplusplus !

**Comment by Matesanz** [comment]
I found a problem for the actual approach, the actual code is the following:

```python
    # Save onnx-model
    if Version(onnx.__version__) >= Version("1.9.0"):
        onnx.save_model(onnx_model, model_data_path, save_as_external_data=True)
    else:
        onnx.save_model(onnx_model, model_data_path)
 ```
 
With this approach multiple files will be generated: the `model.onnx` file and a external alphanumeric file (ie.: `f02a9b26-4caa-11ee-9c58-df96ee46208e`, and therefore, uploaded to the MLFLOW server, resulting in this structure:
 
![image](https://github.com/mlflow/mlflow/assets/44867923/d1d8d19f-56c3-4db5-9fea-18c8f4be33d7)

 The point is that, this code won't work any longer:
 
 ```python
 model_path = "models:/MyModel/Production/model.onnx"
dst_path = mlflow.artifacts.download_artifacts(artifact_uri=model_path)
session = onnxruntime.InferenceSession(dst_path, providers=providers)
```

as **it won't download the aphanumeric file, resulting in this error**:

```shell
2023-09-06 15:15:02.752271604 [E:onnxruntime:, inference_session.cc:1530 operator()] Exception during initialization: [/onnxruntime_src/onnxruntime/core/optimizer/initializer.cc:44] onnxruntime::Initializer::Initializer(const onnx::TensorProto&, const onnxruntime::Path&) [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid fd was supplied: -1
```

Leading to no information of where the problem comes from.

**Potential solutions:**

:point_right:  It would be nice if `save_as_external_data` could configurable.
:point_right:  Or, at least, checking if the file given model size is >2Gb to apply external data AND advise the user.
