### ISSUE TITLE
[FR] UI Filtering nested Runs

### ISSUE THREAD

**Issue by bjoerm** [mlflow/mlflow#7809]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.0.1

### System information

UI via browser.

### Describe the problem

Observed behavior:
When having nested runs in the UI, the filter is only filtering on the parent's characteristics and tags.

Expected behavior:
Filtering in the UI also shows/filters on child characteristics and tags. Or there is a switch for turning this on.

### Steps to reproduce the bug

* Have some nested runs (with parameter "nested=True" and give the childs (not the parent) a tag (e.g. tags={"task": "abc"}) in mlflow.start_run) and log those.
* Go to the web UI.
* Select the respective experiment.
* You should see the runs. They are nested and should only show the name of the parent run.
* Enter in the filter tags.task="abc"

Now you should see none of the runs. Not even the child runs with that tag.

* Remove the filter and you shoud see again all (parent) runs.
* Click on the + in front of each run to open/expand each run to see also the child runs.
* Enter again in the filter tags.task="abc"

Now you see the respective child runs.

### Code to generate data required to reproduce the bug

```
import mlflow

with mlflow.start_run(run_name=f"Debug (parent)"):
    mlflow.log_param("p", 0)
    mlflow.log_metric("m", 1)

    with mlflow.start_run(run_name="Debug (child 1)", nested=True, tags={"task": "abc"}):
        mlflow.log_param("p", 0)
        mlflow.log_metric("m", 1)

    with mlflow.start_run(run_name="Debug (child 2)", nested=True, tags={"task": "def"}):
        mlflow.log_param("p", 0)
        mlflow.log_metric("m", 1)
```

### Is the console panel in DevTools showing errors relevant to the bug?

No

### Does the network panel in DevTools contain failed requests relevant to the bug?

No

**Comment by dbczumar** [comment]
Hi @bjoerm , when submitting search queries in the UI, the run nesting hierarchy is not shown. Rest assured, all of the runs that match the specified criteria are shown correctly, including child runs and their parents. The hierarchy just isn't displayed. Thank you for using MLflow!

**Comment by bjoerm** [comment]
Thanks @dbczumar for the swift response and your work on MLflow! 

I guess we misunderstand each other. Thus, I attached some screenshots to make the observed and expected behavior clearer. 

Starting point:
![No Filter](https://user-images.githubusercontent.com/8392548/218740057-e8d7850d-7a5c-48ce-b654-ce7f092affa2.PNG)

When I filter for a tag that exists on a child and not on the parent, I would expect that the child is shown here, so that the filter omits parents without that tag but still shows childs that have that tag. Instead neither the parent nor the childs are shown (only pinned stay):
![Filtered (Only Pinned Remain)](https://user-images.githubusercontent.com/8392548/218740919-60f8f63d-2d90-45af-9faa-a20156510668.PNG)


Showing you the child and the behavior when I manually expanded the parent to show the child. You can see the tag here. 
![No Filter Opened](https://user-images.githubusercontent.com/8392548/218740534-009f72eb-80f8-4e3d-adf9-c883184a9d80.PNG)

When I filter now, the child gets shown.
![Filtered (Pinned And Open Childs Remain)](https://user-images.githubusercontent.com/8392548/218741666-0c880be5-d8fc-4f00-9745-b3918e63fc8c.PNG)

So for filtering on children in 2.0.1 to work (as I expect it to work) I would need to expand all parents manually to show the childs before filtering. 

Hope this helps. :-)

**Comment by luigibrancati** [comment]
We would like this feature too :)

**Comment by bjoerm** [comment]
@dbczumar Maybe you can have a look at this as there seems to be another person (see above) who (likely) saw the same unexpected behavior. Thanks.
