### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by paprocki-r** [mlflow/mlflow#7810]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks
- **Python version**:  3.8.10
- **yarn version, if running the dev UI**:

### Describe the problem

I am getting an error when I want to check all the runs in the "Experiments", as in the screenshot

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/3410289/217798545-204f5340-8ed6-4c77-bdc4-db70ff0b2e1d.png)

**Comment by dbczumar** [comment]
Hi @paprocki-r , we are in the process of releasing a fix for this bug. If you're a multitenant customer, the fix should have already been applied to your workspace about 24 hours ago. If you're a single tenant customer, the fix will be applied next week. As an alternative, you can use shift + click to select multiple runs for comparison. Thank you for using MLflow!
