### ISSUE TITLE
Autologging does currently continue logging to run after run is explicitly ended[FR]

### ISSUE THREAD

**Issue by ddejaco** [mlflow/mlflow#7814]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

The MLflow documentation states that mlflow.autologging() can automatically start a run when for example a FIT is performed (if no run is already active). This makes sense.

But when I explicitly end the run in the code (with mlflow.end_run()) I would expect MLflow to stop autologging to the run.
However, it keeps autologging for example the metrics calculated with the sklearn.metrics package.

### Motivation

> #### What is the use case for this feature?

> #### Why is this use case valuable to support for MLflow users in general?
I think it would be more intuitive.

> #### Why is this use case valuable to support for your project(s) or organization?
It is more intuitive expecially for people new to MLflow

> #### Why is it currently difficult to achieve this use case?
You have to explicitly enable and diable autologging after each run to stop autologging

### Details

Python code to reproduce the behavior: (mlflow 2.1.1)

[IssuesAutologging.txt](https://github.com/mlflow/mlflow/files/10707010/IssuesAutologging.txt)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @ddejaco, this behavior is intended because we assume that the metrics correspond to the model that was logged by calling the sklearn `fit()` method. Thank you for using MLflow!
