### ISSUE TITLE
[BUG] Artifacts not being saved into experiment_id folder. Instead, artifacts are saved in root `mlruns/` folder under a folder `mlflow/run_id`

### ISSUE THREAD

**Issue by bryanwhiting** [mlflow/mlflow#7817]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow, version 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac M1
- **Python version**: 3.8.16

### Describe the problem

The problem is when i pass in an experiment_id into `mlflow.start_run()` it will duplicate the run_id in two locations. it'll save the artifacts in the main `mlruns/` folder, and copy that run_id hash into the experiment_id folder.

You can see below that metrics are logging in the right place (MAPE, RMSE), but artifacts folder is empty in the exp/run folder. instead they were saved in the mlruns/run_id folder for some reason.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/18710907/218283785-4ca5fac9-5de1-46f1-a501-772011e17b9f.png">

tweaked code from here: https://towardsdatascience.com/5-tips-for-mlflow-experiment-tracking-c70ae117b03f

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import json
import plotly.express as px
import mlflow
import requests

### prepare sample files to log
# test data
df = px.data.iris()

# sample CSV file
df.to_csv("1_data_sample.csv")

# sample pandas HTML file
df.to_html("2_data_sample.html")

# sample image
r = requests.get(
    "https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png"
)
with open("3_image_sample.png", "wb") as f:
    f.write(r.content)

# sample gif
r = requests.get("https://media1.giphy.com/media/bU3YVJAAXckCI/giphy.gif")
with open("4_gif_sample.gif", "wb") as f:
    f.write(r.content)

# sample plotly plot - HTML
fig = px.scatter(
    df,
    x="sepal_width",
    y="sepal_length",
    color="species",
    marginal_y="rug",
    marginal_x="histogram",
)
fig.write_html("5_plot_sample.html")

# sample geojson
with open("6_map_sample.geojson", "w+") as f:
    data = requests.get(
        "https://gist.githubusercontent.com/wavded/1200773/raw/e122cf709898c09758aecfef349964a8d73a83f3/sample.json"
    ).json()
    f.write(json.dumps(data))

### log files to mlflow experiment
import os
from pathlib import Path

# experiment_id = mlflow.create_experiment(
#     "client2",
#     artifact_location=Path.cwd().joinpath("mlruns").as_uri(),
#     tags={"target": "revenue", "priority": "P1"},
# )
# exp = mlflow.set_experiment("client2")
exp_id = "584226892336041065"
# with mlflow.start_run(experiment_id=exp.experiment_id, run_name="2023-02-rev") as run:
with mlflow.start_run(experiment_id=exp_id, run_name="2023-02-rev") as run:

    mlflow.log_param("parameter", "test")
    mlflow.log_param("p2", "train")
    mlflow.log_metric("MAPE", 42.0)
    mlflow.log_metric("RMSE", 34.0)

    mlflow.log_artifact("./1_data_sample.csv")
    mlflow.log_artifact("./2_data_sample.html")
    mlflow.log_artifact("./3_image_sample.png")
    mlflow.log_artifact("./4_gif_sample.gif")
    mlflow.log_artifact("./5_plot_sample.html")
    mlflow.log_artifact("./6_map_sample.geojson")

```

### Stack trace

No warnings/errors.

### Other info / logs

None

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by bryanwhiting** [comment]
Note, this error happens if exp_id is a string or an int:
```
with mlflow.start_run(experiment_id=584226892336041065, run_name="2023-02-rev") as run:
```

Also, this doesn't happen with the default exp_id. But it happens if I pass in an experiment_id into `start_run()` or if i use the `mlflow.set_experiment(exp_name)`.

**Comment by dbczumar** [comment]
Thanks @bryanwhiting ! A couple small questions:

1. What is your tracking URI?
2. From what directory are you running the `Code to reproduce issue`?

**Comment by dbczumar** [comment]
Hi @bryanwhiting, upon closer inspection it appears that the following code is the source of the issue:

```
# experiment_id = mlflow.create_experiment(
#     "client2",
#     artifact_location=Path.cwd().joinpath("mlruns").as_uri(),
#     tags={"target": "revenue", "priority": "P1"},
# )
# exp = mlflow.set_experiment("client2")
```

The `client2` experiment is being created with the `mlruns` directory as the artifact location. As a result, artifacts are logged in run ID subdirectories of `mlruns`. Creating a new experiment and omitting `artifact_location` as follows should resolve the issue:

```
experiment_id = mlflow.create_experiment(
    "client3",
    tags={"target": "revenue", "priority": "P1"},
)
exp = mlflow.set_experiment("client3")
```

Thank you for using MLflow!
