### ISSUE TITLE
A small suggestion on docs

### ISSUE THREAD

**Issue by hanyucui** [mlflow/mlflow#783]
This issue is just FYI, not critical.

I was reading Quickstart in docs and encountered this command line:
`curl -d '{"columns":["x"], "data":[[1], [-1]]}' -H 'Content-Type: application/json; format=pandas-split' -X POST localhost:5000/invocations` ([link](https://github.com/mlflow/mlflow/blame/master/docs/source/quickstart.rst#L176))

The `-X POST` is redundant. Using option [`-d, --data`](https://curl.haxx.se/docs/manpage.html#-d) is sufficient to send a POST command. I have verified this by printing what was sent with and without `-X POST`. According to the [documentation of `-X, --request`](https://curl.haxx.se/docs/manpage.html#-X), it is unnecessary for commands with dedicated options, like `GET`, `HEAD`, etc, and sometimes might cause unintended side-effects.

**Comment by dbczumar** [comment]
@hanyucui Thank you for this feedback. Since this issue does not seem to affect the correctness of the quickstart guide, I am going to mark it closed. Please feel free to follow up with a PR to address it.
