### ISSUE TITLE
[DOC-FIX] The scikit-learn API is *not?* supported.

### ISSUE THREAD

**Issue by turbotimon** [mlflow/mlflow#7843]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/tracking.html#xgboost

### Description of proposal (what needs changing)

It says:
> The [scikit-learn API](https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn) is not supported.

However, this page says that scikit-learn interface ist supported?
https://github.com/mlflow/mlflow/tree/master/examples/xgboost/xgboost_sklearn

> XGBoost Scikit-learn Model Example .. also supports XGBoost scikit-learn models

**Comment by harupy** [comment]
Yes, it's supported. Looking forward to your PR!

**Comment by turbotimon** [comment]
see PR https://github.com/mlflow/mlflow/pull/7849

**Comment by dbczumar** [comment]
Thank you for filing https://github.com/mlflow/mlflow/pull/7849, @turbotimon ! Closing this now that it's merged :)
