### ISSUE TITLE
[FR] Add custom domain git

### ISSUE THREAD

**Issue by gusghrlrl101** [mlflow/mlflow#7853]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

In [getGitCommitUrl](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/common/utils/Utils.js#L274-L304) function, it would check only `github.com`, `gitlab.com`.

If I use custom domain git (eg. `git.godhyum.com`), projects's `Source`, `Git Commit` value is not linking.

<img width="1503" alt="스크린샷 2023-02-17 오전 11 42 04" src="https://user-images.githubusercontent.com/38372691/219536082-144e03d2-66ac-446a-97c9-277361a5de9c.png">

So, I want to add custom git option to mlflow.

### Motivation

> #### What is the use case for this feature?
Using custom domain git.
> #### Why is this use case valuable to support for MLflow users in general?
When users use custom domain git, they can go to their git by hypertext link.
> #### Why is this use case valuable to support for your project(s) or organization?
I'm using custom domain git, so I need this option.
> #### Why is it currently difficult to achieve this use case?
MLflow checks only github.com, gitlab.com now.

### Details

Add custom domain git variable like `MLFLOW_GIT_REPO`.

If it exists, set git url to it's value.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [X] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @gusghrlrl101 sounds like a great idea! Feel free to modify the existing regex matching patterns to simplify the existing implementation wherein we don't do explicit guarded checking of the set(github.com, gitlab.com, bitbucket.com) so that any valid git handler will integrate with the UI. Let us know when you have the PR ready! Thanks!
