### ISSUE TITLE
Only allow logging param/metric names/values that are valid inputs to the search API/UI

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#789]
We should make the set of param/metric (and eventually tag) names & values accepted by the search API / UI match the set of names/values that users are allowed to log. For example, the search JS currently disallows searching on metric/param names that contain non-alphanumeric characters (e.g. metric names like "hidden-layer/weights"), while the Python search API (and by extension R & Java APIs) allow [alphanumerics, underscores (_), dashes (-), periods (.), spaces ( ), and slashes (/)](https://github.com/mlflow/mlflow/blob/bb62bfb0a316db92f0f7ed1b558f98e7a8617658/mlflow/utils/validation.py#L15). Also, it's not currently possible to search on negative metric values.

**Comment by peter-schmidbauer** [comment]
I would suggest updating the search UI to allow these special characters instead. We're using them in a lot of parameters and it's annoying not being able to search for them.

**Comment by peter-schmidbauer** [comment]
I just noticed you cannot search for params containing the word "and" anywhere in it's name either. The UI will just complain that you are not using the correct syntax. Annoying if you are trying to filter e.g. for 'params.model="randomforest"' and it just fails.

**Comment by SchJens** [comment]
I would also suggest to allow at least a certain set of non-alphanumeric characters, in particular since we cannot currently search for tags in the WebUI which forces me to log everything as parameters (including e.g. path names).

**Comment by peter-schmidbauer** [comment]
Any update on this? 
Metrics with non-alphanumeric characters still don't work. It doesn't even show an error. The special chars are just stripped in the UI now and searching/filtering for them shows no results.
