### ISSUE TITLE
[FR] visualize tif files in mlflow viewer

### ISSUE THREAD

**Issue by mehran66** [mlflow/mlflow#7894]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

mlflow viewer supported these formats: image, text, html, pdf, geojson files
tif image is a common format too but it is not supported. Thanks!

### Motivation

> #### What is the use case for this feature?

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @mehran66 TIFF files, while incredibly detailed, are remarkably large. As such, they're not supported on most modern browsers that people would be using Mlflow UI on. 
Based on my search of browser documentation, I can see that TIFF is supported only in:
- Internet Explorer (permanently end-of-life as of June 15th, 2022)
- Edge
- Safari
- A few niche browsers that don't have much market share.


TIFF is not supported in: Chrome or Firefox without installing a plugin. 

I'm not sure if it's advisable for us to enable support for something that will be completely broken for users unless they choose to install a plugin to their browsers. Based on this: https://gs.statcounter.com/browser-market-share I think that the vast majority of our users would run into this problem if they tried to log such an image expecting it to display correctly.
