### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MANOJ21K** [mlflow/mlflow#7927]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.2.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

<img width="955" alt="223" src="https://user-images.githubusercontent.com/85425358/222407797-578795cf-ef80-4204-bd41-47b77362241d.PNG">

### Steps to reproduce the bug

Opening mlflow through anaconda prompt in local

**Comment by harupy** [comment]
@MANOJ21K Thanks for reporting the issue. Can you open Chrome DevTools and check the console?

**Comment by harupy** [comment]
> Opening mlflow through anaconda prompt in local

Can you provide more details? Can you provide the code that can generate data that can reproduce the issue?

**Comment by harupy** [comment]
I ran this command to test MLflow UI:

```
docker run --rm -w /mlflow -v $(pwd)/mlruns:/mlflow/mlruns -p 5000:5000 python:3.8 bash -c 'pip install mlflow==2.2 && mlflow server --host 0.0.0.0 --gunicorn-opts "--log-level debug"'
```

but wasn't able to reproduce the issue.

**Comment by harupy** [comment]
@MANOJ21K Feel free to reopen the issue if it still persists.
