### ISSUE TITLE
is there support for an S3 store?

### ISSUE THREAD

**Issue by ophiry** [mlflow/mlflow#794]
I understand there's support for S3 as a backend for the server, but is there an option to store the artifacts directly on s3 (like using a local file store, without having to keep a server running)?

**Comment by dbczumar** [comment]
@ophiry MLflow already supports S3 as an artifact storage backend. We do not plan to introduce support for storing run metadata (metrics, params, tags) in S3, though we are open to accepting a feature contribution from the community.
