### ISSUE TITLE
[BUG] Search endpoints for REST API should consistently use GET instead of both GET and POST

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#7949]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.2.1
- Tracking server:  2.2.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Python version**: >= 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

The search endpoints for MLflow resources use both GET and POST method. They should be consistent and use GET per HTTP API best practices since the server state is not being modified.

**GET**

2.0/mlflow/registered-models/search
https://mlflow.org/docs/latest/rest-api.html#search-registeredmodels

2.0/mlflow/model-versions/search
https://mlflow.org/docs/latest/rest-api.html#search-modelversions

**POST**

2.0/mlflow/experiments/search
https://mlflow.org/docs/latest/rest-api.html#search-experiments

2.0/mlflow/runs/search
https://mlflow.org/docs/latest/rest-api.html#search-runs

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Unfortunately, we can't make this change at this time due to limitations from partner integrations on the size of GET request query strings. cc @akshaya-a.
