### ISSUE TITLE
[DOC-FIX] MNIST example with MLFlow points to nonexistent reference

### ISSUE THREAD

**Issue by robmarkcole** [mlflow/mlflow#7974]
### Willingness to contribute

Yes. I would be willing to contribute a document fix with guidance from the MLflow community.

### URL(s) with the issue

https://github.com/mlflow/mlflow/tree/master/examples/pytorch/MNIST

### Description of proposal (what needs changing)

The [mnist example at pl](https://github.com/Lightning-AI/lightning/blob/master/pl_examples/basic_examples/mnist.py) no longer exists. I guess you will just delete this reference

**Comment by WeichenXu123** [comment]
Hoping to see your PR !
