### ISSUE TITLE
[FR] Support for Auto-Logging of System Resources in MLflow

### ISSUE THREAD

**Issue by dvirginz** [mlflow/mlflow#7983]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

As a user of MLflow, I would like to request a new feature that enables auto-logging of system resources such as GPU, CPU, and memory usage during machine learning experiments. This feature is already available in other tracking platforms like W&B, and it would be very beneficial to have it in MLflow as well.

With this feature, Users would be able to easily monitor the resource consumption of any experiment and optimize their models accordingly. This would save a lot of time and effort, as users wouldn't have to manually log these metrics every time I run an experiment.

Therefore, I kindly request the MLflow team to consider adding support for auto-logging of system resources in their platform. I believe this would greatly enhance the user experience and make MLflow an even more powerful tool for machine learning practitioners.

Below, a screen-shot from WandB
![image](https://user-images.githubusercontent.com/31047807/223341117-ae486a75-dc9f-4649-8a70-9809331ded55.png)

Thank you for your consideration!

### Motivation

What is the use case for this feature?
The use case for this feature is to automatically log system resource usage during machine learning experiments. This information can be used to optimize models and understand the resource consumption of experiments.

Why is this use case valuable to support for MLflow users in general?
This use case is valuable for MLflow users as it can save a lot of time and effort in monitoring the resource consumption of experiments. It can also help in optimizing models and improving the overall performance of machine learning projects.

Why is this use case valuable to support for your project(s) or organization?
This use case is valuable for our organization as we frequently run machine learning experiments that involve the use of GPU, CPU, and memory resources. Automatic logging of these metrics can help us optimize our models and reduce resource consumption, which can lead to cost savings and improved performance.

Why is it currently difficult to achieve this use case?
Currently, it is difficult to achieve this use case in MLflow because the platform does not have built-in support for auto-logging of system resources. Users have to manually log these metrics, which can be time-consuming and prone to errors. This feature is already available in other tracking platforms like W&B, so adding it to MLflow would make it more competitive and user-friendly.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Good idea!
But I have a couple of questions:

* If multiple users runs mlflow training tasks concurrently, the logged usage data is affected by other user's workloads. This prevent us to analyze the logged resources usage chart. How to distinguish the usage that is used by the logged mlflow training routine or used by other unrelated workloads ?

* We might have multiple GPU devices on machine, shall we log all GPU usages or the GPUs used only by the logged training routine ? How to know which GPU cores it uses ?

**Comment by dbczumar** [comment]
Hi @dvirginz, thank you for your feature request. The motivation and use cases are clear to me. As @WeichenXu123 pointed out, there are definitely some important design questions to answer before we implement the feature. We have noted the feature on our backlog for future prioritization. Thank you for using MLflow!

**Comment by dvirginz** [comment]
I'm not, unfortunately, although I believe it can be a great addition to
mlflow
ᐧ

**Comment by AbeOmor** [comment]
Hi @dvirginz MLflow 2.8 should have solved this for you.

Just wanted to follow up with some docs on MLflow 2.8 with the system metrics update.

Example: https://github.com/mlflow/mlflow/blob/master/examples/system_metrics/collect_system_metrics.py 

Docs: https://mlflow.org/docs/latest/python_api/mlflow.html?highlight=enable_system_metrics_logging#mlflow.enable_system_metrics_logging 

What's New: https://mlflow.org/docs/latest/new-features/index.html

**Comment by AmgadHasan** [comment]
> Hi @dvirginz MLflow 2.8 should have solved this for you.
> 
> Just wanted to follow up with some docs on MLflow 2.8 with the system metrics update.
> 
> Example: https://github.com/mlflow/mlflow/blob/master/examples/system_metrics/collect_system_metrics.py
> 
> Docs: https://mlflow.org/docs/latest/python_api/mlflow.html?highlight=enable_system_metrics_logging#mlflow.enable_system_metrics_logging
> 
> What's New: https://mlflow.org/docs/latest/new-features/index.html

Hi @AbeOmor 
Does this also track gpu metrics?

I tried this feature and it tracked everything except the gpu (which is the most important resource to track)

![image](https://github.com/mlflow/mlflow/assets/109704569/11c88beb-2727-44bc-bf6a-bcbb79c80d62)

**Comment by AmgadHasan** [comment]
> @AmgadHasan, I had the same, did you see a warning like the one I got?
> 
> > Skip logging GPU metrics because creating `GPUMonitor` failed with error: `pynvml` is not installed, to log GPU metrics please run `pip install pynvml` to install it..
> 
> Simply installing the pynvml package solved it

Thanks
I tried this and it worked

I didn't see the warning though. I think this should be clearly mentioned in the docs for logging system metrics
