### ISSUE TITLE
[BUG] Positive DISABLE_NGINX env variable value should equal "true"

### ISSUE THREAD

**Issue by morelen17** [mlflow/mlflow#7986]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.2.1
- Tracking server: N/A

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Ventura 13.2.1 (22D68)
- **Python version**: 3.8.13
- **yarn version, if running the dev UI**: N/A

### Describe the problem

A positive value of the `DISABLE_NGINX` environment variable is expected to be equal to `"true"` (see [mlflow/models/container/\_\_init\_\_.py#L150](https://github.com/mlflow/mlflow/blob/ffe005c58dd45e4f200bfb5a77aa5273a57ca39d/mlflow/models/container/__init__.py#L150)) whereas in some docstrings in [mlflow/sagemaker/\_\_init\_\_.py](https://github.com/mlflow/mlflow/blob/v2.2.1/mlflow/sagemaker/__init__.py) and in tests in [tests/sagemaker/test_sagemaker_deployment_client.py](https://github.com/mlflow/mlflow/blob/v2.2.1/tests/sagemaker/test_sagemaker_deployment_client.py) (although, apparently, the tests _do not_ fail) it equals `"1"`.

### Code to reproduce issue

```python
import os


DISABLE_NGINX = "DISABLE_NGINX"

os.environ["DISABLE_NGINX"] = "1"
disable_nginx = os.getenv(DISABLE_NGINX, "false").lower() == "true"
print(disable_nginx)
>>> False

os.environ["DISABLE_NGINX"] = "true"
disable_nginx = os.getenv(DISABLE_NGINX, "false").lower() == "true"
print(disable_nginx)
>>> True
```

### Stack trace

N/A

### Other info / logs

N/A

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Thanks for catching this!

**Comment by UponTheSky** [comment]
Thank you for this issue.

Can I ask a question?

You mentioned as 

> A positive value of the DISABLE_NGINX environment variable is expected to be equal to "true"  

However,  the link you mentioned(https://github.com/mlflow/mlflow/blob/ffe005c58dd45e4f200bfb5a77aa5273a57ca39d/mlflow/models/container/__init__.py#L150) has the comment line saying 

> # option to disable manually nginx. The default behavior is to enable nginx.(https://github.com/mlflow/mlflow/blob/ffe005c58dd45e4f200bfb5a77aa5273a57ca39d/mlflow/models/container/__init__.py#L149)

So from the code, any other text value than "true" or its variants(like "True" or "TRUE"), will give `disable_nginx` the value `False`. I wonder if I am missing something.

**Comment by morelen17** [comment]
Hey @UponTheSky !

You are correct. The default behavior is `disable_nginx = False` which leads to running an `nginx` server as a proxy. On the other hand, the intended behavior in docstring examples and tests is to disable `nginx` (`disable_nginx = True`; why else would you assign `"1"` and not `"0"` in that case? Or just avoid passing the env var at all to eventually get `nginx` enabled?). So my point is to change `"1"` to `"true"`; otherwise, the intention might be misleading for the newcomers or people who look through the codebase. Moreover, the tests _may_ operate a bit differently (that also needs to be verified).

 Hope, it's become clearer for you now.

**Comment by morelen17** [comment]
It may also be confusing since negative variable names are present here. As a best practice, we should avoid using such variable names

**Comment by UponTheSky** [comment]
Thank you for the clear explanation!
Yes, for a newcomer like me, just reading the code doesn't tell me much about test settings. It should be helpful for more readable code. I appreciate your effort. Thank you!
