### ISSUE TITLE
[FR] Add a feature to hide experiments in the web interface

### ISSUE THREAD

**Issue by sauerburger** [mlflow/mlflow#7989]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

It would be great to hide experiments in the experiments list in the web interface. This does not have to be as complex as a new column in the database and a toggle switch. It could be a very simple mechanism as to hide all experiments starting with a dot as long as the search box is empty.

### Motivation

> #### What is the use case for this feature?

The list of experiments is just that a flat list and can become unwieldy. The search box helps to navigate and *search* a particular experiment, but I think it is common that some experiments don't need to be visible at all.

> #### Why is this use case valuable to support for MLflow users in general?

See above.

> #### Why is this use case valuable to support for your project(s) or organization?

I use MLflow on an on-premise deployment and have implemented automated end-to-end tests. These tests train models, push them to MLflow and retrieve them again for evaluation. The value we get from these tests is the confidence that the MLflow infrastructure works as expected, our custom models are packed and uploaded properly, and can be unpacked and deployed automatically.

However, these tests produce a number of experiments that in my view distract from actual ML/DS experiments and pollute the web interface. A simple mechanism to hide these automatically created experiments would tidy up the experiments list.

> #### Why is it currently difficult to achieve this use case?

To my knowledge, there is no feature to create hidden, technical-only experiments.

### Details

I do not suggest any changes to the API, only a minor change to the user interface. Please find an example implementation in my merge request.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
* Q1: One concern is, this looks like a breaking change, some user might have experiment name starting with dot, after upgrading they become invisible.

* Q2: What can user do if they want to view these experiment on web UI ?

**Comment by sauerburger** [comment]
@WeichenXu123 thanks for your feedback.

- Q1: Indeed, it is a breaking change if there are experiments that start with a dot. In my view, the only reason to have experiments starting with a dot, is to expect them to be hidden. However, I see, that this is clearly subjective.
- Q2: The easiest way to see these experiments again is to enter any string into the search field. If a user is interested in *all* hidden experiments, I'd suggest entering a dot (`.`) into the search box. All hidden experiments will match the query and will be visible.

**Comment by WeichenXu123** [comment]
@sauerburger Thank you!

For Q1:
> Q1: Indeed, it is a breaking change if there are experiments that start with a dot. In my view, the only reason to have experiments starting with a dot, is to expect them to be hidden. However, I see, that this is clearly subjective.

What do you think @dbczumar ?
What about showing a tip bar on the dashboard saying "experiments starting with dot are hidden, if you want to view them, type . in the search box" if there's some experiments starting with dot existing.

**Comment by dbczumar** [comment]
Thank you, @sauerburger. For now, we do not plan to implement name-based experiment hiding. We do recommend using experiment tags or experiment naming conventions of your choosing, along with the https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.rename_experiment API, to keep track of which experiments are relevant and which can be deleted later on.

Thank you so much for using MLflow!
