### ISSUE TITLE
Search for float requires leading 0 in web interface

### ISSUE THREAD

**Issue by sotte** [mlflow/mlflow#801]
### System information
- **Have I written custom code **: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**:  via pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.1
- **Python version**: 3.7
- **npm version (if running the dev UI)**: 6.4.1

### Describe the problem

The search of the web interface requires floating point numbers to start with a 0 when they are smaller than 1. E.g. I can search for `metrics.val_roc_auc > 0.95` but not `metrics.val_roc_auc > .95`. I don't think the 0 should be required.

**Comment by mateiz** [comment]
This should be fixed now. Thanks for reporting it!

**Comment by sotte** [comment]
Thanks.
