### ISSUE TITLE
Dockerfile related questions: older version of OS/Python + installing JDK + 3rd party libraries

### ISSUE THREAD

**Issue by smartlymo** [mlflow/mlflow#8013]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- MLflow == 2.2.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: 3.10.6
- **yarn version, if running the dev UI**:

### Describe the problem

Thanks for the hard work!
When using MLFlow with the intent of using SageMaker for inference runtime, primarily in batch-transform mode, I generated the docker file using ```mlflow models generate-docker file``` to inspect it. The docker file generated is based on older version of Ubuntu, and uses an older version of Python. Additionally, it includes JDK 8 and then proceeds to install a host of libraries.
It is not clear to me why the java dependencies are there. What is the use case for this and what would be the impact on SageMaker based deployment if we remove it?
I have customised the docker file then out of band built a customised image, with more recent OS and Python. However I did not remove the JDK related installations as it was not immediately clear what the impact could be.
It would be great if someone could elaborate a bit on the Java stuff, why is it needed, if/when it is safe to remove it.

I believe this issue might be best broken into several issues:

- Documentation related: Document the mechanics around Docker image creation better.
- Documentation related: State the use case for the JAVA related installations more explicitly, and whether they can be removed.
- Feature request: Add support for customising the docker image
- Feature request: Add support to customise the docker entry point. It seems to me that an example entry point could serve the user well, once there is some more control over the Dockerfile content.

I ran into some odd behaviour with images getting renamed automatically and incorrectly  on the local system, but I hadn't had the time to reproduce this reliably enough to make an issue of it.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
mlflow models generate-dockerfile
cat mlflow-dockerfile/Dockerfile
```

### Stack trace

```

```

### Other info / logs

I can't help right away with this, but if someone on the team could help with some information, I can try to come back to it with a PR when I have more bandwidth.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Thanks @smartlymo! The Java dependencies are included in the MLflow model server to support serving Spark models with MLeap. There is no other purpose for the JDK, and you can remove it if you don't need to serve Spark models with MLeap.

We'll get this information documented.

I absolutely agree that the ability to specify customer dockerfiles would be very useful. We will consider this for future prioritization.

**Comment by smartlymo** [comment]
Thanks @dbczumar , I am glad you confirmed this because I had already removed it earlier today :)
and thank you for building MLFlow! Please feel free to close the ticket now. I apologise if filing it as a bug might have caused you any grief.

**Comment by dbczumar** [comment]
Thanks @smartlymo ! No grief at all! Cheers!
