### ISSUE TITLE
Search for tags via web interface

### ISSUE THREAD

**Issue by sotte** [mlflow/mlflow#802]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **MLflow installed from (source or binary)**: via pip 
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.1
- **Python version**: 3.7
- **npm version (if running the dev UI)**: 6.4.1

### Describe the problem
I want to be able to search for tags via the web interface. Currently only metrics and params are supported.

(My current workaround: log everything as parameter and make it searchable this way.)

Also see #781

**Comment by smurching** [comment]
@sotte thanks for raising this, @mparkhe added support for searching on tags in MLflow 1.0. You can now search using syntax like `tags.myTagName = 'myTagVal'` as documented [here](https://www.mlflow.org/docs/latest/search-syntax.html). Closing this for now, thanks!
