### ISSUE TITLE
[FR] Support content-type headers when uploading artifacts via proxied artifact storage

### ISSUE THREAD

**Issue by WillEngler** [mlflow/mlflow#8026]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

When the MLFlow client uploads artifacts via the HttpArtifactRepository, it should send the proper HTTP Content-Type header. It currently does not set a Content-Type header at all. The logic in #7827 that maps file extensions to Content-Types should work great on the upload side too.

This is a similar request to https://github.com/mlflow/mlflow/issues/7548. But this request is for _uploading_ artifacts while that one was for downloading.

### Motivation

> #### What is the use case for this feature?

Proper implementation of the HTTP spec and better supporting use cases where MLFlow sits behind a proxy.

> #### Why is this use case valuable to support for MLflow users in general?

This is mostly useful to integrators and benefits MLFlow users by letting MLFlow be plugged into more network architectures.

> #### Why is this use case valuable to support for your project(s) or organization?

Some proxy and API Gateway products trigger different passthrough behavior based on a request's Content-Type header. In particular, AWS API Gateway will try to parse all payloads as UTF-8 unless the request has a Content-Type header that has been specifically enumerated as a binary type. So when MLFlow is proxied behind AWS API Gateway, models uploaded via HTTP get corrupted by AWS API Gateway. If the artifact upload requests had the right Content-Type headers, integrators could instruct AWS API Gateway not to mangle the binary payloads.

> #### Why is it currently difficult to achieve this use case?

As far as I can tell, the MLFlow client does not set _any_ Content-Type headers for outbound calls. There is also no sort of `extra_headers` argument one could pass down. The only way I found to work around this for now was to abuse the `RequestHeaderProvider` system. (See https://github.com/Garden-AI/garden/pull/80 for our team's workaround.)

### Details

It seems like the RequestHeaderProvider is not a good fit for this change because the providers can't see individual requests and decide based on their contents. 

So instead my first approach would be:
- add an optional `extra_headers` parameter to the `http_request` utility. Merge any provided headers from that dict with the headers gathered from the RequestHeaderProviders via `resolve_request_headers`.
- In HttpArtifactRepository.log_artifact, use the same logic that the server does to pick the right Content-Type header for different file extensions. Pass the Content-Type header down to `http_request` via the `extra_headers` dict.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@WillEngler Thank you for filing this issue. The use case and proposal make perfect sense to me, and we'd be excited to review a pull request with this functionality. Please let me know if you have any questions, and we look forward to your contribution. Thanks in advance!

**Comment by WillEngler** [comment]
Hey @dbczumar great, happy to help. I have a solution mostly there but I've hit one snag. Could you give me advice on how to handle this circular import problem in my draft PR? https://github.com/mlflow/mlflow/pull/8048#discussion_r1139391853
