### ISSUE TITLE
[FR] Add Core TensorFlow Example to mlflow/examples

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#8049]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

With MLflow 2.x, we removed the seriously outdated TF1.x example (due to relevance issues). We'd like to solicit a new example from the community of fantastic TF users to create a replacement example that leverages purely TF core APIs (no Keras usage). 

### Motivation

> #### What is the use case for this feature?
To help users with a utilization example that uses the TF core library.

> #### Why is this use case valuable to support for MLflow users in general?
There are MLflow users that leverage base core TF library to build projects. It would be great to have an up to date example on how to leverage the interaction with MLflow APIs.

> #### Why is this use case valuable to support for your project(s) or organization?
This is helpful for TF users who do not use Keras for a project.

> #### Why is it currently difficult to achieve this use case?
We removed the old (arguably irrelevant) 1.x examples with the 2.x release of MLflow.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dheerajnbhat** [comment]
Hi @BenWilson2 

I have added core tensorflow 2.x api example to mlflow/examples. Request you to do a review the same

**Comment by dheerajnbhat** [comment]
Hi @BenWilson2

I have created a PR for this issue. Can you review the same?
