### ISSUE TITLE
using craco to rebuild the frontend 

### ISSUE THREAD

**Issue by Zhangjiawei-Beinloft** [mlflow/mlflow#8052]
The frontend is bootstrapped with [create-react-app](https://create-react-app.dev/) and can be rebuild by:

- first installing the dependencies with `yarn install`  in the `mlflow/mlflow/server/js` folder.
- running `yarn build` .

When running  `yarn build`, it report a error: 
```
craco:  *** Cannot find ESLint plugin (ESLintWebpackPlugin). ***
C:\mlflow\server\js\craco.config.js:87
    throw new Error('Failed to fix CSS paths!');
```
The version of nodejs is 16.18. How to solve this error?

**Comment by Zhangjiawei-Beinloft** [comment]
> @Zhangjiawei-Beinloft I wasn't able to reproduce the issue. This might be because you're using windows.

why can't I use windows and what should I use?

**Comment by harupy** [comment]
@Zhangjiawei-Beinloft 

> why can't I use windows

Line 74 in `craco.config.js` may not match on Windows:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/17039389/226077493-7a5f059e-d572-49de-885c-a080ae848456.png">

> what should I use?

Linux or Mac

**Comment by harupy** [comment]
@Zhangjiawei-Beinloft btw why do you need to run `yarn build`?

**Comment by Zhangjiawei-Beinloft** [comment]
> @Zhangjiawei-Beinloft
> 
> > why can't I use windows
> 
> Line 74 in `craco.config.js` may not match on Windows:
> 
> <img alt="image" width="748" src="https://user-images.githubusercontent.com/17039389/226077493-7a5f059e-d572-49de-885c-a080ae848456.png">
> 
> If line 74 matches nothing, that would leave `cssRuleFixed` `false`, then cause the error.
> 
> > what should I use?
> 
> Linux or Mac should work. If you don't have them, https://github.com/features/codespacess should help.

it worked！Thanks！

**Comment by Zhangjiawei-Beinloft** [comment]
> @Zhangjiawei-Beinloft btw why do you need to run `yarn build`?

Because I‘m fixing the problem that mlflow UI not working in iframe. 
[mlflow UI not working in iframe[BUG]--cross origin issue](https://github.com/mlflow/mlflow/issues/3583#issue-727989150)
