### ISSUE TITLE
Mlflow autologging lightning doesn't log anything / log is empty

### ISSUE THREAD

**Issue by AmaanAnsari** [mlflow/mlflow#8054]
This is a tip for all that face this problem: You have to use the 'pytorch_lightning' module instead of the 'lightning' module because it seems to be that mlflow does not recognize the new 'lightning' as 'pytorch_lightning'

**Comment by harupy** [comment]
No, mlflow doesn't. We need to update the code.

**Comment by JuanFMontesinos** [comment]
I've been passing the logger explicitly as follows:
`logger = MLFlowLogger(run_id=net.run_id, log_model=True)` and so far it works. Still need to try with pytorch 2 and lightning 2.
(I'm not using autolog)

**Comment by harupy** [comment]
Shoulbe fixed by 8072
