### ISSUE TITLE
how can we record the metrics without autolog()

### ISSUE THREAD

**Issue by 652994331** [mlflow/mlflow#8058]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Hi, I am new to mlflow, I followed your eras example: https://github.com/mlflow/mlflow/blob/master/examples/keras/train.py
and write a keras base bert classification task. However , autolog() record nothing, no metrics and no artifects.  I am thinking about using log_metrics() and log_model() but not sure how to use them, can u help? thank you 

### Motivation

> #### What is the use case for this feature?

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @652994331, hope the following code helps:

```python
with mlflow.start_run():
    metrics = compute_metrics(model, ...)
    mlflow.log_metrics(metrics)
    mlflow.tensorflow.log_model(model)
```

**Comment by harupy** [comment]
Freel free to reopne the issue if the code above doesn't work.

**Comment by 652994331** [comment]
thank you for your help, I got a problem here, 
![Screen Shot 2023-03-20 at 13 14 29](https://user-images.githubusercontent.com/51428350/226252522-73e10e65-727f-41ee-a93d-b4933aef51fd.png)

the codes are as below:
![Screen Shot 2023-03-20 at 13 17 57](https://user-images.githubusercontent.com/51428350/226252971-e724fe9a-c561-4f8d-a659-07b27c64a6e3.png)

**Comment by harupy** [comment]
It looks like you're using python 3.7 and mlflow < 2.0. Can you update python to 3.8 and install mlflow >= 2.0?

**Comment by 652994331** [comment]
@harupy your right, I am using python 3.7.7 and mlflow-1.28.0. Will have a try and update later, thanks👍

**Comment by 652994331** [comment]
@harupy  another tricky question is,  I found that I can't put experiment_id, run_name in to mlflow.start_run() (like below)
![Screen Shot 2023-03-20 at 14 11 59](https://user-images.githubusercontent.com/51428350/226260952-b08e1ead-4530-4d87-a92f-cc15f9bf9a0b.png)
it gave me a error said: 
![Screen Shot 2023-03-20 at 14 13 04](https://user-images.githubusercontent.com/51428350/226261098-216d9ffb-8c92-40ad-b971-fdf5c00e242c.png)

but if I write with mlflow.start_run() with no parameters inside, although the code passed, there's no record on my UI board.
