### ISSUE TITLE
[DOC-FIX]

### ISSUE THREAD

**Issue by Judekeyser** [mlflow/mlflow#8065]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/models.html#model-signature-and-input-example

### Description of proposal (what needs changing)

The current typing for `ColSpec` goes as follow:
```
    def __init__(
        self, type: DataType, name: Optional[str] = None  # pylint: disable=redefined-builtin
    ):
```
As such, the examples of the documentation are confusing, because they go against the specified typing of the method (one shouldn't be able to pass `"double"` but `DataType.double` instead, for instance.

In view of the implementation of `__init__`, there is a clear intent to support strings as well. But the typing is against.

There should be a documentation update if `DataType` is meant to be the correct type, or else a doc-string update together with a typing update, if `str` is explicitly allowed:
```
type: Union[DataType, str]
```
for example (likely with a doc-string explanation that the intent of `str` is to refer to one of the key supported in `DataType`). The documentation online should make it explicit too.

**Comment by harupy** [comment]
@Judekeyser `Union[DataType, str]` sounds good to me, looking forward to your PR!

**Comment by Judekeyser** [comment]
OOps, I ticked the wrong box ; but it's okay I guess I can do that ;
