### ISSUE TITLE
[BUG] MlflowException: The following failures occurred while downloading one or more artifacts

### ISSUE THREAD

**Issue by thingumajig** [mlflow/mlflow#8081]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- mlflow, version 2.2.2

### System information

- Ubuntu 20.10
- python 3.8.10:

### Describe the problem

I ran tracking server ui on one server, registered the model. Then I try to load the model from another server, where I'm going to serve the model. I get an exception when I try to load the model.
The model contains custom artifacts.
![image](https://user-images.githubusercontent.com/8703531/227100598-695b1caa-c7ed-4d3d-8481-d2f076d5b17a.png)

I would be grateful for a hint.

### Tracking information

```
MLflow version: 2.2.2
Tracking URI: http://192.168.10.38:5000/
Artifact URI: mlflow-artifacts:/0/950b130860fa4c9aa6bd21c4f9ac7eb0/artifacts
System information: Linux #202103201033 SMP Sat Mar 20 10:38:21 UTC 2021
Python version: 3.8.10
MLflow version: 2.2.2
MLflow module location: /root/doc-classifier/.venv/lib/python3.8/site-packages/mlflow/__init__.py
Tracking URI: http://192.168.10.38:5000/
Registry URI: http://192.168.10.38:5000/
Active experiment ID: 0
Active run ID: 950b130860fa4c9aa6bd21c4f9ac7eb0
Active run artifact URI: mlflow-artifacts:/0/950b130860fa4c9aa6bd21c4f9ac7eb0/artifacts
MLflow dependencies: 
  Flask: 2.2.3
  Jinja2: 3.0.3
  alembic: 1.9.4
  click: 8.0.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.3
  gitpython: 3.1.24
  gunicorn: 20.1.0
  importlib-metadata: 6.0.0
  markdown: 3.3.6
  matplotlib: 3.5.1
  numpy: 1.21.4
  packaging: 21.3
  pandas: 1.4.2
  protobuf: 3.20.3
  pyarrow: 6.0.1
  pytz: 2021.3
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.0.1
  scipy: 1.7.3
  shap: 0.41.0
  sqlalchemy: 2.0.4
  sqlparse: 0.4.3
```

### Code to reproduce issue

```
import mlflow.pyfunc
import mlflow

TRACKING_URI='http://192.168.x.x:5000'
mlflow.set_tracking_uri(TRACKING_URI)

model_name = "classifier-roberta-large"
stage = "Production"

model = mlflow.pyfunc.load_model(model_uri=f"models:/{model_name}/{stage}")

model.predict('xxxxxxx')
```

### Stack trace

```
---------------------------------------------------------------------------
MlflowException                           Traceback (most recent call last)
/tmp/ipykernel_3956245/2041802459.py in <module>
      8 stage = "Production"
      9 
---> 10 model = mlflow.pyfunc.load_model(model_uri=f"models:/{model_name}/{stage}")
     11 
     12 model.predict('простой текст')

~/doc-classifier/.venv/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py in load_model(model_uri, suppress_warnings, dst_path)
    561                      path will be created.
    562     """
--> 563     local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
    564 
    565     if not suppress_warnings:

~/doc-classifier/.venv/lib/python3.8/site-packages/mlflow/tracking/artifact_utils.py in _download_artifact_from_uri(artifact_uri, output_path)
     98     """
     99     root_uri, artifact_path = _get_root_uri_and_artifact_path(artifact_uri)
--> 100     return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
    101         artifact_path=artifact_path, dst_path=output_path
    102     )

~/doc-classifier/.venv/lib/python3.8/site-packages/mlflow/store/artifact/models_artifact_repo.py in download_artifacts(self, artifact_path, dst_path)
    124         :return: Absolute path of the local filesystem location containing the desired artifacts.
    125         """
--> 126         return self.repo.download_artifacts(artifact_path, dst_path)
    127 
    128     def _download_file(self, remote_file_path, local_path):

~/doc-classifier/.venv/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py in download_artifacts(self, artifact_path, dst_path)
    263 
    264         if len(failed_downloads) > 0:
--> 265             raise MlflowException(
    266                 message=(
    267                     "The following failures occurred while downloading one or more"

MlflowException: The following failures occurred while downloading one or more artifacts from http://192.168.x.x:5000/api/2.0/mlflow-artifacts/artifacts/692308151846849404/28f77b11d12c42a6837007ca73517541/artifacts/classifier: {'artifacts/tf_model.h5': 'ChunkedEncodingError(ProtocolError("Connection broken: InvalidChunkLength(got length b\'\', 0 bytes read)", InvalidChunkLength(got length b\'\', 0 bytes read)))'}``
```

### Other info / logs

# Tracking server logs
[2023-03-23 03:57:36 +0000] [1532257] [CRITICAL] WORKER TIMEOUT (pid:1533183)
[2023-03-23 03:57:36 +0000] [1533183] [INFO] Worker exiting (pid: 1533183)
[2023-03-23 03:57:37 +0000] [1543499] [INFO] Booting worker with pid: 1543499
[2023-03-23 04:01:31 +0000] [1532257] [CRITICAL] WORKER TIMEOUT (pid:1532260)
[2023-03-23 04:01:31 +0000] [1532260] [INFO] Worker exiting (pid: 1532260)
[2023-03-23 04:01:32 +0000] [1547117] [INFO] Booting worker with pid: 1547117

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@thingumajig This might be because the file is very large. Can you download a small file wihtout any issues?

**Comment by thingumajig** [comment]
@harupy I'm not loading a file, I'm loading the model as a whole. I need to rework the processing pipeline to shrink the model... I can't make it that fast yet, sorry.

**Comment by thingumajig** [comment]
@harupy This is now the usual size of models, I would even say closer to small ;)

**Comment by harupy** [comment]
Setting the `MLFLOW_HTTP_REQUEST_TIMEOUT` environment variable might help.

```
export MLFLOW_HTTP_REQUEST_TIMEOUT=600  # 10 minutes
```

**Comment by thingumajig** [comment]
@harupy tried it this way: 
```
import mlflow.pyfunc
import mlflow

import os
os.environ["MLFLOW_HTTP_REQUEST_TIMEOUT"] = "600"

TRACKING_URI='http://192.168.x.x:5000'
mlflow.set_tracking_uri(TRACKING_URI)

model_name = "xxxxxxx"
stage = "Production"

model = mlflow.pyfunc.load_model(model_uri=f"models:/{model_name}/{stage}")

model.predict('xxxxxx')

```
same error. I also tried it this way:
```

#!/bin/bash
# Set environment variable for the tracking URL where the Model Registry resides
export MLFLOW_TRACKING_URI=http://192.168.x.x:5000
export MLFLOW_HTTP_REQUEST_TIMEOUT=600 

# Serve the production model from the model registry
mlflow models serve -m "models:/classifier-ruRoberta-large/Production"

```
same error

**Comment by harupy** [comment]
Can you create a smaller model and try the same thing?

**Comment by thingumajig** [comment]
@harry it's not easy, it was an experiment with hugging face model setup, respectively it was custom mlflow.pyfunc.PythonModel and artifacts. I need to actually come up with a new little model of some sort, I can't do it quickly.

**Comment by harupy** [comment]
Can you use an sklearn model as a test?

**Comment by thingumajig** [comment]
@harupy Ok, I'll try, but later. Thanks 👍🏻

**Comment by thingumajig** [comment]
@harupy I checked on the scikit-learn model, it works.
Any other recommendations? Maybe the timeout should be increased on the server side?

Client-side working code for scikit-learn model:
```
import mlflow.pyfunc
import mlflow

import os
os.environ["MLFLOW_HTTP_REQUEST_TIMEOUT"] = "600"

TRACKING_URI='http://192.168.10.38:5000'
mlflow.set_tracking_uri(TRACKING_URI)

model_name = "ElasticnetWineModel"
stage = "Production"

model = mlflow.sklearn.load_model(model_uri=f"models:/{model_name}/{stage}")

model.predict([[7.4, 0.70, 0.00, 1.9, 0.076, 11.0, 34.0, 0.9978, 3.51, 0.56, 9.4]])
```

**Comment by thingumajig** [comment]
@harupy I restarted my mlflow model-registry server with an extended timeout for gunicorn:
`GUNICORN_CMD_ARGS="--timeout 600" mlflow server  -h 0.0.0.0 -p 5000 `
That seems to have helped. I'll fix the next batch of bugs and see if that's true.

**Comment by thingumajig** [comment]
@harupy Yes, the timeout for model-registry server as in the previous post helped me. Thanks

**Comment by harupy** [comment]
Glad increasing the timeout helped! Can we close this issue?

**Comment by thingumajig** [comment]
@harupy Yes, of course. Thanks again.
