### ISSUE TITLE
[BUG] Unable to Deploy MLFlow On Cloud Run and Connect to CloudSQL via Unix Socket Connection

### ISSUE THREAD

**Issue by Sj1218305** [mlflow/mlflow#8098]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Tracking server: 2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Python version**: 3.8

### Describe the problem

I am trying to deploy MLflow on Cloud Run. The Cloud Run Service needs to be connected to CloudSQL. I am trying to establish the connection by running CloudSQL proxy in the same docker container and connecting ML flow with the same. 
In the logs I am able to see that the CloudSQL proxy is able to connect to the Cloud SQL instance but logs for Mlflow server are not there, nor I am able to access MLflow via UI

### Tracking information

```Dockerfile
FROM python:3.8-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y bash && apt-get install -y wget gnupg2 && \
    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && \
    chmod +x cloud_sql_proxy && \
    pip install mlflow pymysql

FROM gcr.io/cloudsql-docker/gce-proxy:1.22.0

# Copy the service account JSON file to the container
COPY ./<path-to-credential-file> .

# Expose the default Cloud SQL port
EXPOSE 5000

ENV INSTANCE_CONNECTION_NAME=<instance-connection-name>
ENV MYSQL_USER=<username>
ENV MYSQL_PASSWORD=<password>
ENV MYSQL_DATABASE=<database_name>

# Start the Cloud SQL proxy
CMD ["/cloud_sql_proxy", "-instances=$INSTANCE_CONNECTION_NAME=tcp:0.0.0.0:3306", "-credential_file=<credential-file>", "-dir=/cloudsql & mlflow server \
    --default-artifact-root gs://<gcs-bucket-uri> \
    --host 0.0.0.0 --port 5000 \
    --backend-store-uri mysql+pymysql://$MYSQL_USER:$MYSQL_PASSWORD@localhost:3306/$MYSQL_DATABASE?unix_socket=/cloudsql/$INSTANCE_CONNECTION_NAME"]
```

### Code to reproduce issue

current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
using credential file for authentication; email=local-dev@labellerrdev.iam.gserviceaccount.com
Listening on 0.0.0.0:3306 for labellerrdev:us-central1:labellerdev
Ready for new connections

### Stack trace

```
Ready condition status changed to False for Revision mlflow-00002-fih with message: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=labellerrdev&resource=cloud_run_revision/service_name/mlflow/revision_name/mlflow-00002-fih&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22mlflow%22%0Aresource.labels.revision_name%3D%22mlflow-00002-fih%22 
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Sj1218305 Thanks for reporting. Do you have more detailed stacktrace?

**Comment by Sj1218305** [comment]
I have raised a more precised and new issue: https://github.com/mlflow/mlflow/issues/8168
Closing this one.
