### ISSUE TITLE
[BUG] Artifacts section in MLFLOW UI keep loading forever

### ISSUE THREAD

**Issue by Coder-Vishali** [mlflow/mlflow#8113]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Python version**: 3.9
- **yarn version, if running the dev UI**:

### Describe the problem

I am using JFrog artifactory as a artifact store to storage my trained models. I am able to successfully push the trained models to JFrog Artifactory. The problem I see is it doesn't shows the artifactory URL and option to download the trained model from the MLFLOW UI like how it shows for local filestore. 

### Steps to reproduce the bug

mlflow.create_experiment(<mlflow_experiment_name>, artifact_location=f"https://{jfrog_user}:{jfrog_pass}@<artifactory server>/<repository_name>/")

**Comment by harupy** [comment]
@Coder-Vishali MLflow doesn't support using JFrog as an artifact repository.

**Comment by harupy** [comment]
Got it. As I suggested, you can check the network tab in the browser devtools.

**Comment by Coder-Vishali** [comment]
Thank you for your response
