### ISSUE TITLE
[BUG] "Source Run" field in Model Version UI page points to wrong run model artifact in Run UI page

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#8150]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

If you have logged more than one model artifact in a run, the "Source Run" field of the Model Version UI page always links to the last model artifact in the Run UI page. 

In addition, the "Source Run" field name should be renamed "Source Model" and the model artifact name should be appended to the run name that appears in the field. So instead of `my-run` it should be `my-run/my-correct-model`.

This bug appears in both OSS and Databricks MLflow.

### Steps to reproduce the bug

Create a run and log two models.
Register the models as two versions in a registered model.
Go to the version UI page of the first model you registered as a version (see attached screenshot 1).
Click on the "Source Run" link and it will take you to the Run UI page and it highlights the last model artifact (see attached screenshot 2).

<img width="379" alt="01_version_ui_page" src="https://user-images.githubusercontent.com/1721873/229386529-9c563a66-286e-4b96-a6b6-2a98bc603648.png">
<img width="251" alt="02_run_ui_page" src="https://user-images.githubusercontent.com/1721873/229386537-b6be585f-09e9-48cd-90d4-499ff59b0060.png">

### Code to generate data required to reproduce the bug

[test_model_version_source.py.txt](https://github.com/mlflow/mlflow/files/11133650/test_model_version_source.py.txt)

**Comment by WeichenXu123** [comment]
The model version source https://github.com/mlflow/mlflow/blob/8622d73aa75423c839f02fbe21d0a66673ef5d3d/mlflow/server/js/src/model-registry/components/ModelVersionView.js#L320 is a link like:

`http://localhost:3000/#/experiments/0/runs/94bf8e51c0b545aabeff2c9ce4e3c8c8`

Such link page always hight the latest model in a run.

**Comment by WeichenXu123** [comment]
I am investigating how to fix this...

**Comment by harupy** [comment]
@amesar 

> If you have logged more than one model artifact in a run, the "Source Run" field of the Model Version UI page always links to the last model artifact in the Run UI page.

The "Source Run" field just links to the run. The run page makes it look like it links to the last model artifact.
