### ISSUE TITLE
[BUG] Step plotting using MlfowClient, plotted vertically.

### ISSUE THREAD

**Issue by ksterx** [mlflow/mlflow#8182]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04, Windows11
- **Python version**: 3.10.10

### Describe the problem

Hi! I have a problem when checking plots.
I am using `MlflowClient` for the plots, and I have found that the step numbers in the plots is incorrect.

![Screenshot 2023-04-06 132120](https://user-images.githubusercontent.com/76713276/230271322-21b7a141-e88c-49e9-9e4f-15ad944eb0d0.png)

Is this normal behavior?

Thank you.

### Steps to reproduce the bug

```python
from mlflow.tracking import MlflowClient

client = MlflowClient(tracking_uri="file:./mlruns")
run = client.create_run(experiment_id="0")
run_id = run.info.run_id
for i in range(100):
    client.log_metric(run_id, "test", i, i)
client.set_terminated(run_id)
```
-> This does not work

```python
import mlflow
with mlflow.start_run() as run:
    for i in range(50):
        mlflow.log_metric("test", i, i)
```
-> This works!

**Comment by harupy** [comment]
@ksterx The third argument of `MlflowClient.log_metric` is `timestamp`, not `step`.

**Comment by ksterx** [comment]
Oh, I misunderstood.
Thank you~
