### ISSUE TITLE
[FR] support hugging face (transformers) as a flavor 

### ISSUE THREAD

**Issue by abelzhao** [mlflow/mlflow#8195]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Hugging face (transformers) collected many good models all over the world, https://huggingface.co/. 

Today many researchers use its large pre-trained model in many projects.  I hope some one can develop a flavor to support using it, just like pytorch, xgboost and so on.

### Motivation

> #### What is the use case for this feature?
so many!

> #### Why is this use case valuable to support for MLflow users in general?
hugging face is now a very big machine learning model community, and transformers is a very famous python package.

> #### Why is this use case valuable to support for your project(s) or organization?
I want to use mlflow and transformers in my projects,  which means I can manage the pre-trained nlp model from transformers and the fine-tunes them with mlflow .

> #### Why is it currently difficult to achieve this use case?
not support at the moment.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
We're working on it! #8181 (and the first part is already part of master :)) We sincerely hope that you get some great use from the flavor at the next release!

**Comment by BenWilson2** [comment]
This feature is now released in MLflow 2.3
