### ISSUE TITLE
[DOC-BUG] Documentation broken (v1.3) !! Acess denied!!!

### ISSUE THREAD

**Issue by tamis-laan** [mlflow/mlflow#8196]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://mlflow.org/docs/1.30.1/models.html

### Description of proposal (what needs changing)

When visiting `https://mlflow.org/docs/1.30.1/models.html` I get:
``` xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>CJ4H2ZXJACBGEW6D</RequestId>
  <HostId>
    5IY7sX9T8aFTmEKnHlLgbupQ5YOcdS5il60pAMwhS8lyfbFoHJvi0STBsh6YMWubpRrVqUTRk5U=
  </HostId>
</Error>
```

**Comment by BenWilson2** [comment]
Hi @tamis-laan thank you for bringing this to our attention. We're going to investigate.

**Comment by tamis-laan** [comment]
@BenWilson2 
Still broken, this bug makes it impossible to work with MLFlow v1

**Comment by BenWilson2** [comment]
Docs have been updated! Thank you for your patience :)
