### ISSUE TITLE
Setting environment variables for tracking username/password in Rstudio does not work

### ISSUE THREAD

**Issue by vsandvold** [mlflow/mlflow#820]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: running stock example in Rstudio (https://mlflow.org/docs/latest/tutorial.html)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.2
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 0.8.1
- **Python version**: 3.7.2
- **Exact command to reproduce**: mlflow_create_experiment("test_experiment")

### Describe the problem
I have set up an MLflow server with basic HTTP authentication. Using the MLflow client for python works fine with the environment variables `MLFLOW_TRACKING_USERNAME` and `MLFLOW_TRACKING_PASSWORD` defined.

Setting the same environment variables in Rstudio doesn't seem to work when connecting to the same tracking server (with HTTP authentication). Connecting to a different tracking server without HTTP authentication works as expected.

### Source code / logs
Console commands in a clean install of Rstudio:
```
> install.packages("mlflow")
> mlflow::mlflow_install()
> library(mlflow)
> mlflow_set_tracking_uri(<server with http autentication>)
> Sys.setenv(MLFLOW_TRACKING_USERNAME = "username")
> Sys.setenv(MLFLOW_TRACKING_PASSWORD = "password")
> Sys.getenv("MLFLOW_TRACKING_USERNAME")
[1] "username"
> Sys.getenv("MLFLOW_TRACKING_PASSWORD")
[1] "password"
> mlflow_create_experiment("test_experiment")
Error: lexical error: invalid char in json text.
                                       <html>  <head><title>401 Author
                     (right here) ------^
> mlflow_set_tracking_uri(<another server without http autentication>)
> mlflow_create_experiment("test_experiment")
[creates experiment as expected]
```

**Comment by aarondav** [comment]
This was resolved a few releases ago -- please let us know if it is still an issue. cc @tomasatdatabricks
