### ISSUE TITLE
[BUG] FutureWarning: pyarrow.hdfs.connect is deprecated

### ISSUE THREAD

**Issue by julcsii** [mlflow/mlflow#8213]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Python version**: 3.9.6
- **pyarrow version**: 5.0.0

### Describe the problem

When loading a model from the MLflow Model Registry (backend store is HDFS) I get the following warning:

```
legobricks/lib/python3.9/site-packages/mlflow/store/artifact/hdfs_artifact_repo.py:188: FutureWarning: pyarrow.hdfs.connect is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
  connected = pa.hdfs.connect(
```

### Steps to reproduce the bug

1. Create a conda env with mlflow and pyarrow installed
2. Start Mlflow with hdfs as backend store
3. Train a model and save it
4. Store the trained model in the model registry
5. Load model from the registry

**Comment by harupy** [comment]
@julcsii The suggestion makes sense to me! Looking forward to your PR :)
