### ISSUE TITLE
[BUG] mlflow.pytorch.save_model() results in "Serialization of parametrized modules is only supported through state_dict()"

### ISSUE THREAD

**Issue by tueboesen** [mlflow/mlflow#8214]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.2.2

### System information

- Ubuntu 22.04.1
- Python 3.10

### Describe the problem

Whenever I try to use mlflow.pytorch.save_model() or mlflow.pytorch.log_model() with my pytorch models I get the following error:

```
Traceback (most recent call last):
  File "/snap/pycharm-community/327/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/tue/PycharmProjects/VirtualEnvironments/ConstrainedMD/lib/python3.10/site-packages/mlflow/pytorch/__init__.py", line 323, in log_model
    return Model.log(
  File "/home/tue/PycharmProjects/VirtualEnvironments/ConstrainedMD/lib/python3.10/site-packages/mlflow/models/model.py", line 551, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/home/tue/PycharmProjects/VirtualEnvironments/ConstrainedMD/lib/python3.10/site-packages/mlflow/pytorch/__init__.py", line 540, in save_model
    torch.save(pytorch_model, model_path, pickle_module=pickle_module, **kwargs)
  File "/home/tue/PycharmProjects/VirtualEnvironments/ConstrainedMD/lib/python3.10/site-packages/torch/serialization.py", line 423, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/tue/PycharmProjects/VirtualEnvironments/ConstrainedMD/lib/python3.10/site-packages/torch/serialization.py", line 635, in _save
    pickler.dump(obj)
  File "/home/tue/PycharmProjects/VirtualEnvironments/ConstrainedMD/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
  File "/home/tue/PycharmProjects/VirtualEnvironments/ConstrainedMD/lib/python3.10/site-packages/torch/nn/utils/parametrize.py", line 306, in getstate
    raise RuntimeError(
RuntimeError: Serialization of parametrized modules is only supported through state_dict(). See:
https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training

```
I haven't seen anyone else report this, which surprises me since this seems like a general problem with mlflow and pytorch models.

I am able to run the command mlflow.pytorch.log_state_dict(), but that doesn't save all the information like the other methods.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

# I don't have a minimal working example unfortunately since I use rather large custom models.
    mlflow.set_tracking_uri(path)
    with mlflow.start_run(run_name=c.run.name) as run:
        mlflow.pytorch.log_model(model, "models")

### Stack trace

    mlflow.set_tracking_uri(c.logging.mlflow_folder)
    with mlflow.start_run(run_name=c.run.name) as run:
        artifact_path = "models"
        log_parameters(c)
        metrics = Metrics(name='train')
        for epoch in range(c.run.epochs):
            for name in names:
                if name in dataloaders:
                    loss = run_model(epoch,c,model,dataloaders[name],optimizer,loss_fnc,metrics,type=name)
        if 'test' in dataloaders:
            loss = run_model(0, c, model, dataloaders['test'], optimizer, loss_fnc, metrics, type='test')
        mlflow.pytorch.log_state_dict(model.state_dict(), artifact_path)
        mlflow.pytorch.save_model(model,'modelsdfs')
        mlflow.pytorch.log_model(model.to(device='cpu'), "models")
    return loss

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
The exception is being thrown from pytorch. We simply rely on their serialization utilities to store model artifacts. 
What sort of additional information did you need to save that is incompatible with the native pytorch save functionality?

**Comment by tueboesen** [comment]
> The exception is being thrown from pytorch. We simply rely on their serialization utilities to store model artifacts. What sort of additional information did you need to save that is incompatible with the native pytorch save functionality?

I see. It is a highly customized model and I'm not sure exactly what is incompatible. Normally I would save the state_dict, which is the recommended way in pytorch from what I understand, but I can understand why you would do it this way.
I believe a method that enables the user to log the model converted to torchscript or jit compilated might be able to fix this issue, but I don't know enough about that.

**Comment by BenWilson2** [comment]
Hi @tueboesen the current pytorch implementation in MLflow supports `torch.jit.script` or `torch.jit.trace` to be passed to the `pytorch_model` argument in `save_model()` and `log_model()`. Have you given this a try?

**Comment by deardeer7** [comment]
I kind of solved this. I encountered this when I added `weight_norm` (via`from torch.nn.utils.parametrizations import weight_norm`) to some layers in my model, code like `weight_norm(nn.Linear(h, k), dim=None)`. While after I remove `weight_norm`, everything goes well. After I replaced `weight_norm` to `from torch.nn.utils.weight_norm import weight_norm`, it goes well, too.

**Comment by anjalyv** [comment]
@tueboesen Is this issue resolved? I am also facing same issue while logging MMS (Pytorch ) model into MLflow. This was working fine with Pytorch 2.0.1 and the issue is there from version >2.0.1. Is there any solution for this?

**Comment by anjalyv** [comment]
Hi @tueboesen,  Is this issue resolved? I am also facing the same issue while logging an MMS (PyTorch) model into MLflow. This was working fine with PyTorch 2.0.1, but the issue has appeared in versions >2.0.1. Is there any solution for this?

**Comment by tueboesen** [comment]
Sorry I completely forgot about this one. My issue was resolved, it is indeed as @BenWilson2 says that they just pipe the request through to pytorch.
@anjalyv check whether you can save the model using the pytorch calls directly.
