### ISSUE TITLE
MLflow - Need Info

### ISSUE THREAD

**Issue by deepakrajak582** [mlflow/mlflow#823]
Hi Mlflow users,

Can you please let me know the below ?

1. What are the system requirements for mlflow ? i.e. RAM , software etc

2. How frequent we have the new mlflow release ? Means how frequent the Databricks team releasing the version ?

3. Is the MLflow stable as of now ?

**Comment by apurva-koti** [comment]
Most of this can be found in the docs: https://mlflow.org/docs/latest/index.html

We don't have a planned release schedule as of now. With the recent 1.1 release, MLflow is stable.
