### ISSUE TITLE
Can't Join MLFlow Slack Channel 2023 Edition [BUG]

### ISSUE THREAD

**Issue by PsionTheory** [mlflow/mlflow#8239]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y
- I'd like to join MLFlow Slack but is puts me in sometype of loop or tells me to contact the MLFlow administrator. this is frustrating 
- 
- ![image](https://user-images.githubusercontent.com/3756590/232332084-a0c824c4-9858-4e2c-92f2-420dc58dd480.png)
- 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

I'd like to join MLFlow Slack but is puts me in sometype of loop or tells me to contact the MLFlow administrator. this is frustrating 
- ![image](https://user-images.githubusercontent.com/3756590/232332084-a0c824c4-9858-4e2c-92f2-420dc58dd480.png)

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@PsionTheory Sorry for the inconvenience, #8244 should be fix the issue.

**Comment by PsionTheory** [comment]
Here's the issue thats not resolved. Seems MLFlow is expecting me to already be joined, when im applying to join the group, and thusly won't let me join the group.
 
I Put in my email to join group 
 
 
 
 
 
This is the loop thats happening

**Comment by PsionTheory** [comment]
same thing happens with other corporate emails as well

> ---------- Original Message ----------
> From: Neil Barnett ***@***.***>
> To: mlflow/mlflow ***@***.***>
> Date: 04/17/2023 10:20 AM EDT
> Subject: Re: [mlflow/mlflow] Can't Join MLFlow Slack Channel 2023 Edition [BUG] (Issue #8239)
>  
>  
>  
> Here's the issue thats not resolved. Seems MLFlow is expecting me to already be joined, when im applying to join the group, and thusly won't let me join the group.
>  
> I Put in my email to join group 
>  
>  
>  
>  
>  
> This is the loop thats happening 
>  
>  
>  
>

**Comment by harupy** [comment]
@PsionTheory I directly invited you in the channel.

**Comment by PsionTheory** [comment]
Not yet, not to neil@adaptive-structures.com

**Comment by harupy** [comment]
Sent an invitation to [neil@adaptive-structures.com](mailto:neil@adaptive-structures.com)

**Comment by PsionTheory** [comment]
just got it thank you ! 

![image](https://user-images.githubusercontent.com/3756590/232517890-4e683fd7-16b7-4a2d-afc0-533d57ceb25c.png)
