### ISSUE TITLE
[BUG] Unable to register model using the python api

### ISSUE THREAD

**Issue by stealthBanana** [mlflow/mlflow#8249]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.30.1
- Tracking server: 2.2.2

### System information

- **Image: apache/Airflow:latest**
- **OS: Debian 11**:
- **Python Version: 3.7.16**:

### Describe the problem

I'm trying to train a model, log it and then register it in an apache airlfow task. Logging the parameters, metrics and artifact works just fine, I can see them logged in the UI, however, when trying to register the model it seems that it is not found, while creating the registered model using the UI works just fine.

### Tracking information

```shell
MLflow version: 1.30.1
Tracking URI: http://localhost:5000/
Artifact URI: mlflow-artifacts:/0/15ba3cb168a94a9d8df83e8ae3f68a7a/artifacts
```
`mlflow server --host 0.0.0.0 --backend-store-uri postgresql://mlflow:mlflow@localhost:5432/mlflow_db`

### Code to reproduce issue

```
import mlflow
import mlflow.xgboost
import numpy as np
import pendulum
from airflow.decorators import dag, task
from xgboost import XGBRegressor


@task
def training():
    
    X = np.random.rand(100, 10)
    y = np.random.rand(100, 7)
    
    artifact_name = 'test_regressor'
    model_name = 'xgb_model'
    mlflow.set_tracking_uri("http://localhost:5000")
    
    mlflow.xgboost.autolog(log_models=False)
    with mlflow.start_run(run_name="test_regressor") as run:
        
        model = XGBRegressor()
        model.fit(X, y)
        
        mlflow.xgboost.log_model(xgb_model=model,
                                 artifact_path=artifact_name,
                                 registered_model_name=model_name)

@dag(schedule=None,
     start_date=pendulum.datetime(2023, 4, 10, tz="UTC"),
     catchup=False)
def test_api():
    
    training()

test_api()

```

### Stack trace

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 27, in training
    registered_model_name=model_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/xgboost/__init__.py", line 277, in log_model
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/models/model.py", line 387, in log
    await_registration_for=await_registration_for,
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/_model_registry/fluent.py", line 74, in register_model
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/_model_registry/fluent.py", line 65, in register_model
    create_model_response = client.create_registered_model(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 1847, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/_model_registry/client.py", line 59, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/store/model_registry/rest_store.py", line 83, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/store/model_registry/rest_store.py", line 64, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 280, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 214, in verify_rest_response
    error_code=get_error_code(response.status_code),
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/preview/mlflow/registered-models/create failed with error code 404 != 200. Response body: '<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
'
```

### Other info / logs

Docker compose:
```
services:

  mlflow_db:
    container_name: mlflow_db
    image: postgres:latest
    hostname: "mlflow_db"
    network_mode: "host"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db

  mlflow_server:
    container_name: mlflow_server
    build: ./mlflow_dockerfile
    hostname: "mlflow_server"
    network_mode: "host"
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri postgresql://mlflow:mlflow@localhost:5432/mlflow_db

  airlow_server:
      container_name: airflow_server
      build: ./airflow_dockerfile
      hostname: "airflow_server"
      network_mode: "host"
      command: airflow standalone
```

mlflow_dockerfile
```
FROM ghcr.io/mlflow/mlflow

RUN pip3 install scikit-learn xgboost psycopg2-binary
```

airflow_dockerfile
```
FROM apache/airflow

RUN pip install pip --upgrade
RUN pip install mlflow xgboost scikit-learn matplotlib

COPY ./dags /opt/airflow/dags

EXPOSE 8080
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@stealthBanana Can you share your `test_dag.py`?

**Comment by harupy** [comment]
@stealthBanana I think the root cause is a version mismatch between the client and server. The client (airflow) uses MLflow < 2.0, but the server uses MLflow >= 2.0. We removed the `/api/2.0/preview/...` routes in MLflow 2.0. Can you replace `apache/airflow
` with `apache/airflow:latest-python3.8
`?

**Comment by stealthBanana** [comment]
By following your instruction mlflow 2.2.2 was installed on the airflow server and model registering now works. Thanks !!!
