### ISSUE TITLE
[FR] The SHARE button would shorter links

### ISSUE THREAD

**Issue by jlmeunier** [mlflow/mlflow#8256]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

The SHARE button would produce short links, for sharing among users.

In my case, because of ~200 params and ~400 metrics, the link produced by the SHARE button is about 32700 characters.

I cannot store it in the experiment description (because saving the description is no longer possible).
I cannot make it shorter using TinyUrl, because its limit is 32000 characters.
So sharing the link is difficult.

Proposal: SHARE button either does a lossless compression of the URI or returns a unique URI and keeps a record of their mapping to long URI.

### Motivation

> #### What is the use case for this feature?
I want to share an experiment view but the URI becomes too long.

> #### Why is this use case valuable to support for MLflow users in general?
Sharing experiment view is useful, and good for MLFlow to get better known.

> #### Why is this use case valuable to support for your project(s) or organization?
Our runs have hundreds of metrics and params. Current URIs cannot be shared conveniently.

> #### Why is it currently difficult to achieve this use case?
The URI is 32700 characters long.

### Details

I imagine 2 possible solutions:

1. compressing parameter part of the URI in a lossless fashion and that is compatible with URI scheme.
2. generating a key and storing the mapping key->long URI in MLFlow persistent store

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by jlmeunier** [comment]
Actually, the selectedColumns is precisely what I want to share with others. (once I've carefully selected the columns of interest for a particular goal).
Thanks @harupy for the interest.

**Comment by harupy** [comment]
I see, so the selectedColumns parameter is very long?

**Comment by jlmeunier** [comment]
Sorry, I shared part of the long link, but it did not went thru. Here again below!

Maybe another solution would consist in omitting the "uncheckedKeys" in the URL. Somehow doing the reverse of what is done currently where MLFlow shows everything that is not omitted. Showing only what is mentioned in the link cannot be so large since it corresponds to what a user wants to look at.
And then maybe adding a boolean parameter that tells that non-mentioned key must be omitted?

An excerpt of the long parameter value, which represents most of the 32k:
`categorizedUncheckedKeys[metrics]=alpha,bleu,bsz,chrf,chrfpp,full_loss,gate_loss,gnorm,gpu_0_mem,gpu_0_use,gpu_1_mem,gpu_1_use,gpu_2_mem,gpu_2_use,gpu_3_mem,gpu_3_use,kl_loss,langid,len_ratio,lines,load_wall,loss,loss_scale,lps,lr,max_mem,nll_loss,ppl,spbleu,src_oov,tgt_oov,tokens,total_wall,ups,valid-it.cs-da%2Fbleu,valid-it.cs-da%2Fbsz,valid-it.cs-da%2Fchrf,valid-it.cs-da%2Fchrfpp,valid-it.cs-da%2Flen_ratio,valid-it.cs-da%2Flines,valid-it.cs-da%2Floss,valid-it.cs-da%2Flps,valid-it.cs-da%2Fnll_loss,valid-it.cs-da%2Fppl,valid-it.cs-da%2Fspbleu,valid-it.cs-da%2Fups,valid-it.cs-da%2Fwall,valid-it.cs-da%2Fwpb,valid-it.cs-da%2Fwps,valid-it.cs-de%2Fbleu,valid-it.cs-de%2Fbsz,valid-it.cs-de%2Fchrf,valid-it.cs-de%2Fchrfpp,valid-it.cs-de%2Flen_ratio,valid-it.cs-de%2Flines,valid-it.cs-de%2Floss,valid-it.cs-de%2Flps,valid-it.cs-de%2Fnll_loss,valid-it.cs-de%2Fppl,valid-it.cs-de%2Fspbleu,valid-it.cs-de%2Fups,valid-it.cs-de%2Fwall,valid-it.cs-de%2Fwpb,valid-it.cs-de%2Fwps,valid-it.cs-en%2Fbleu,valid-it.cs-en%2Fbsz,valid-it.cs-en%2Fchrf,valid-it.cs-en%2Fchrfpp,valid-it.cs-en%2Flen_ratio,valid-it.cs-en%2Flines,valid-it.cs-en%2Floss,valid-it.cs-en%2Flps,valid-it.cs-en%2Fnll_loss,valid-it.cs-en%2Fppl,valid-it.cs-en%2Fspbleu,valid-it.cs-en%2Fups,valid-it.cs-en%2Fwall,valid-it.cs-en%2Fwpb,valid-it.cs-en%2Fwps,valid-it.cs-fr%2Fbleu,valid-it.cs-fr%2Fbsz,valid-it.cs-fr%2Fchrf`

**Comment by harupy** [comment]
@jlmeunier What is your MLflow version?

**Comment by jlmeunier** [comment]
my version is 1.29.0

Yes the URL you showed is promising for my case!

I'll update my server and come back to you. Thanks for the help!

**Comment by harupy** [comment]
@jlmeunier Thanks! I'll close this issue, but let me know if the issue still persists in the latest version of MLflow :)
