### ISSUE TITLE
Released container

### ISSUE THREAD

**Issue by kfox1111** [mlflow/mlflow#826]
Could the project please post prebuilt containers up to the docker hub? There are lots of folks posting their own builds but are not kept up to date and are not official.

**Comment by mparkhe** [comment]
This is a good question and this request has come up before. I marked this as an enhancement--we will consider how we can support this as a part of MLflow release process.

**Comment by kfox1111** [comment]
Thanks. :)

**Comment by twsl** [comment]
Is there a reason this hasn't been implemented yet? Do you need help creating this?

**Comment by twsl** [comment]
Feel free to upvote the referenced pull request, that should publish the mlflow server to github container registry

**Comment by zhangchi1** [comment]
Hi MLflow, I'm wondering do we have any updates on this PR? Do we have a timeline for publishing the MLflow Sagemaker image to the public Docker Hub? 

Thanks,
