### ISSUE TITLE
[DOC-FIX]

### ISSUE THREAD

**Issue by jhaneyrf** [mlflow/mlflow#8269]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_experiment

### Description of proposal (what needs changing)

Explicitly following the Python API for the mlflow.set_experiment() function using the experiment_name parameter to create a new experiment produced the following error for me on Azure Databricks:

RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'correlation_threshold_efx_corev2'. An experiment name must be an absolute path within the Databricks workspace,

Nothing in the description of set_experiment says anything about name needing to be a valid path, and the example experiment name is simply a string "Social NLP Experiments".

Someone using mlflow for the first time should be given sufficient information to write code that will successfully execute. If name is a string on some platforms but a path on other platforms, a sentence warning users about this would be useful.

**Comment by harupy** [comment]
@jhaneyrf Thanks for filing this issue! I filed #8271 to improve the doc for `experiment_name`.

**Comment by ramniwasbaheti** [comment]
is this completed or changes has been made ?
