### ISSUE TITLE
mlflow.tensorflow: Failed to infer model signature on Google Colab[BUG]

### ISSUE THREAD

**Issue by nikshingadiya** [mlflow/mlflow#8275]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

mlflow=2.3.0

### System information

- **Google Colab**:
- **Python version : 3.9.16**:
- **Tensorflow:2.12.0**:

### Describe the problem

why on google colab mlflow.keras.autolog()  is not logging tensorflow model . I don't know if this is coming from google colab side or mlflow but based on logs I feel this issue coming from mlflow . please analyze my logs.
Thank You

### Tracking information

MLflow version: 2.3.0
Tracking URI: https://dagshub.com/bhuvnesh.shukla/Eye_disease_MLflow.mlflow
Artifact URI: mlflow-artifacts:/0411983f2f254beb8954cb509d521fb7/a048ae4c8e8b4b5aa77fb7bb018d7706/artifacts
System information: Linux #1 SMP Sat Dec 10 16:00:40 UTC 2022
Python version: 3.9.16
MLflow version: 2.3.0
MLflow module location: /usr/local/lib/python3.9/dist-packages/mlflow/__init__.py
Tracking URI: https://dagshub.com/bhuvnesh.shukla/Eye_disease_MLflow.mlflow
Registry URI: https://dagshub.com/bhuvnesh.shukla/Eye_disease_MLflow.mlflow
Active experiment ID: 0
Active run ID: a048ae4c8e8b4b5aa77fb7bb018d7706
Active run artifact URI: mlflow-artifacts:/0411983f2f254beb8954cb509d521fb7/a048ae4c8e8b4b5aa77fb7bb018d7706/artifacts
MLflow environment variables: 
  MLFLOW_TRACKING_PASSWORD: 52687268971419b4c00c2fbc44446938db3cd8dd
  MLFLOW_TRACKING_URI: https://dagshub.com/bhuvnesh.shukla/Eye_disease_MLflow.mlflow
  MLFLOW_TRACKING_USERNAME: 52687268971419b4c00c2fbc44446938db3cd8dd
MLflow dependencies: 
  Flask: 2.2.3
  Jinja2: 3.1.2
  alembic: 1.10.3
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.6
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 6.3.0
  markdown: 3.4.3
  matplotlib: 3.7.1
  numpy: 1.22.4
  packaging: 23.0
  pandas: 1.5.3
  protobuf: 3.20.3
  pyarrow: 9.0.0
  pytz: 2022.7.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.27.1
  scikit-learn: 1.2.2
  scipy: 1.10.1
  sqlalchemy: 2.0.9
  sqlparse: 0.4.3

### Code to reproduce issue

```
mlflow.keras.autolog()
dagshub.init("Eye_disease_MLflow", "bhuvnesh.shukla", mlflow=True)
# New run
mlflow.start_run(run_name="Aptos_Resnet_5")
# Run id
run_id = mlflow.active_run().info.run_id
history = model.fit(x=x_train, y=y_train, batch_size=16, epochs=20, verbose = 1, validation_data = (x_val, y_val), validation_batch_size = 16, callbacks = callback)
```

### Stack trace

There is not exception or error occured  just based on logs i can track this issue

### Other info / logs

```
WARNING mlflow.tensorflow: Failed to infer model signature: could not sample data to infer model signature: tuple index out of range 
WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs. Warning untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 155). These functions will not be directly callable after loading.
WARNING mlflow.utils.requirements_utils: Found jaxlib version (0.4.7+cuda11.cudnn86) contains a local version label (+cuda11.cudnn86).MLflow logged a pip requirement for this package as 'jaxlib==0.4.7' with
out the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@nikshingadiya You can set the `MLFLOW_AUTOLOGGING_TESTING` environment variable to see what went wrong.

**Comment by harupy** [comment]
```python
mlflow.keras.autolog()
dagshub.init("Eye_disease_MLflow", "bhuvnesh.shukla", mlflow=True)
# New run
mlflow.start_run(run_name="Aptos_Resnet_5")
# Run id
run_id = mlflow.active_run().info.run_id
history = model.fit(x=x_train, y=y_train, batch_size=16, epochs=20, verbose = 1, validation_data = (x_val, y_val), validation_batch_size = 16, callbacks = callback)
```

is not runnable. Can you:

- add all the required import statements
- add undefined variables
- make sure it can be executed by copy & pasting

?

**Comment by nikshingadiya** [comment]
we can't share all the codes with github it's our personal project  sry for
the inconvenience.

**Comment by harupy** [comment]
> we can't share all the codes with github it's our personal project  sry for


You don't have to share your code. What we need is code that can reproduce the issue. If you don't have it, please create it.

**Comment by nikshingadiya** [comment]
I will send you another code which will create this same issue thanks for
supporting us

**Comment by nikshingadiya** [comment]
Here is the link:  google colab notebook link
<https://colab.research.google.com/drive/1N5unt8ALPHlJeHuXdxxv2t4v-UsD18v_?usp=sharing>
In the artifact folder, i didn't find any TensorFlow model
Note: Run notebook to till this cell "model.fit(train_images, train_labels,
epochs=2)" and you will get those similar logs which I already defined in
github issue

**Comment by harupy** [comment]
Ran your notebook without `dagshub`. The model was logged:

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/17039389/233079863-d6601dc1-1c11-4cf0-9de3-903bb26de627.png">

**Comment by nikshingadiya** [comment]
can you share with me above code via google notebook

**Comment by harupy** [comment]
@nikshingadiya https://colab.research.google.com/drive/1N5unt8ALPHlJeHuXdxxv2t4v-UsD18v_?usp=sharing

**Comment by harupy** [comment]
@nikshingadiya Feel free to reopen the issue if it's not a dagshub's issue, but an MLflow's issue :)

**Comment by nikshingadiya** [comment]
I really love Mlflow it's a very user-friendly platform, and the way you support me I feel good Thanks to all mlflow community.

**Comment by deanp70** [comment]
Hey @nikshingadiya, @harupy – Dean from DagsHub here, I tested the notebook @harupy provided with `dagshub.init()` and it successfully logged a model to my MLflow server.

Adding the example notebook that works: https://colab.research.google.com/drive/1D8p_C9AtYhUeGM8A3xFXxEyVMxAqA52q?usp=sharing

Hopefully this is useful for other people that find this thread.

**Comment by nikshingadiya** [comment]
Awesome, thanks!
