### ISSUE TITLE
[DOC-FIX] Add model size limit to Model Serving page

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#8278]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

https://docs.databricks.com/machine-learning/model-serving/index.html#limitations
https://learn.microsoft.com/en-us/azure/databricks/machine-learning/model-serving/#limitations

### Description of proposal (what needs changing)

The model size limit should be added to the Limitations section of the Model serving with Databricks. It is currently 5 GB, but has either already increased or about to increase.

Since the model is an artifact, the artifact size limit description should also be changed on the Track machine learning training runs page. 
For [AWS](https://docs.databricks.com/mlflow/tracking.html#track-machine-learning-training-runs), it now says `the maximum size for an MLflow artifact uploaded to DBFS on AWS is 5GB` but strangely the Azure page does not mention it.

[Slack thread on 2023-04-19](https://databricks.slack.com/archives/CPS3MLXUJ/p1681912701904509?thread_ts=1681911342.594659&cid=CPS3MLXUJ).

.

**Comment by harupy** [comment]
@amesar Is there anything we need to fix in **the OSS MLflow documentation?** If no, I think we should close this and file an internal ticket to track this.
