### ISSUE TITLE
ModuleNotFoundError: No module named 'cloudpickle' in examples/sklearn_elasticnet_wine when running in mlflow docker container

### ISSUE THREAD

**Issue by jimthompson5802** [mlflow/mlflow#828]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: examples/sklearn_elasticnet_wine/train.py
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.2
- **MLflow installed from (source or binary)**:  MLFlow Docker container
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2.dev0
- **Python version**: Python 2.7.15
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
```
docker run -p 0.0.0.0:5000:5000 -v /Users/jim/Desktop/databricks_mlflow/mlflow:/opt/project mlflow:latest 
cd /opt/project/examples_sklearn_wine
mlflow run . -P alpha=0.01
```

### Describe the problem
mlflow run fails with ModuleNotFoundError: No module named 'cloudpickle'

### Source code / logs
Relevant error messages:
```
2019/01/21 21:58:22 INFO mlflow.projects: === Running command 'source activate mlflow-7d1a6285d6abcb17f2dab81619b40f9877a8629e && python train.py 0.01 0.1' in run with ID 'a2017165c14347a3af16a085f9ea439c' ===
Elasticnet model (alpha=0.010000, l1_ratio=0.100000):
  RMSE: 0.7590197857656096
  MAE: 0.5917620431231971
  R2: 0.25590897480195673
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    mlflow.sklearn.log_model(lr, "model")
  File "/opt/conda/envs/mlflow-7d1a6285d6abcb17f2dab81619b40f9877a8629e/lib/python3.6/site-packages/mlflow/sklearn.py", line 187, in log_model
    serialization_format=serialization_format)
  File "/opt/conda/envs/mlflow-7d1a6285d6abcb17f2dab81619b40f9877a8629e/lib/python3.6/site-packages/mlflow/models/__init__.py", line 73, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/opt/conda/envs/mlflow-7d1a6285d6abcb17f2dab81619b40f9877a8629e/lib/python3.6/site-packages/mlflow/sklearn.py", line 115, in save_model
    serialization_format=serialization_format)
  File "/opt/conda/envs/mlflow-7d1a6285d6abcb17f2dab81619b40f9877a8629e/lib/python3.6/site-packages/mlflow/sklearn.py", line 220, in _save_model
    import cloudpickle
ModuleNotFoundError: No module named 'cloudpickle'
2019/01/21 21:58:24 ERROR mlflow.cli: === Run (ID 'a2017165c14347a3af16a085f9ea439c') failed ===
```

See attached file for full log: [examples_sklearn_elasticnet_wine_error.txt](https://github.com/mlflow/mlflow/files/2780644/examples_sklearn_elasticnet_wine_error.txt)

### Root Cause Analysis:
Appears `cloudpickle` package missing from conda.yaml specification.    Will create pull request to fix.

**Comment by VinayGandra** [comment]
conda.yaml(Below throws error - ResolvePackageNotFound:  - cloudpickle==0.8.0)

channels:
- defaults
dependencies:
- python=3.6.5
- scikit-learn=0.20.2
- **cloudpickle==0.8.0**
name: mlflow-env

Fix:
channels:
- defaults
dependencies:
- python=3.6.5
- scikit-learn=0.20.2
- **cloudpickle**
name: mlflow-env


Please provide better way as cannot change it in each model yaml.

**Comment by kaleko** [comment]
I have had the same issue as @VinayGandra above.
