### ISSUE TITLE
[BUG] mlflow.artifacts.download_artifacts - object has no attribute 'values' in latest version

### ISSUE THREAD

**Issue by TobiasRD95** [mlflow/mlflow#8288]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.3.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker, Linux Ubuntu 22.04
- **Python version**: 3.10

### Describe the problem

I received this error many times while loading a 1gb model from Databricks:

The error occured the first time yesterday. 
I have been using the latest version always, so the error happened the same time as version 2.3.0 of MLflow was released.
I have just now downgraded to the previous version, and it works perfectly again.
Therefore, I suspect there is a bug in version 2.3.0 in regards to downloading artifacts.

### Code to reproduce issue

```
import mlflow, os
from dotenv import load_dotenv
load_dotenv()
mlflow.set_tracking_uri('databricks')
os.environ["MLFLOW_HTTP_REQUEST_TIMEOUT"] = "1200"

# loading classifier (can take 5-10 minutes)
mlflow.artifacts.download_artifacts(artifact_uri = "models:/documentClassifier/Production", dst_path = "/models/documentClassifier")
```

### Stack trace

```
Traceback (most recent call last):
  File "/code/app/ML/getModels.py", line 7, in <module>
    mlflow.artifacts.download_artifacts(artifact_uri = "models:/documentClassifier/Production", dst_path = "/models/documentClassifier")
  File "/usr/local/lib/python3.10/dist-packages/mlflow/artifacts/__init__.py", line 56, in download_artifacts
    return _download_artifact_from_uri(artifact_uri, output_path=dst_path)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/tracking/artifact_utils.py", line 100, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/usr/local/lib/python3.10/dist-packages/mlflow/store/artifact/models_artifact_repo.py", line 135, in download_artifacts
    return self.repo.download_artifacts(artifact_path, dst_path)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/store/artifact/artifact_repo.py", line 265, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from models:/documentClassifier/Production: {'artifacts/documentClassifier/pytorch_model.bin': 'MlflowException("\'NoneType\' object has no attribute \'values\'")'}
The command '/bin/sh -c python3 /code/app/ML/getModels.py' returned a non-zero code: 1
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@TobiasRD95 Thanks for trying out MLflow 2.3.0. In this version, we made a few updates to upload/download large files faster. I think the error occurs here:

https://github.com/mlflow/mlflow/blob/251428cb7ffb0977f78655a24563be7ea75d8a5f/mlflow/store/artifact/databricks_artifact_repo.py#L438

Are you using Databricks on Google Cloud?

**Comment by harupy** [comment]
Filed https://github.com/mlflow/mlflow/pull/8289

**Comment by TobiasRD95** [comment]
Hi

We are using Databricks on Azure

tor. 20. apr. 2023 15.18 skrev Harutaka Kawamura ***@***.***>:

**Comment by harupy** [comment]
@TobiasRD95 Thanks for the reply! Got it, would you mind testing the PR above?

**Comment by TobiasRD95** [comment]
Thanks, Harupy!
I have just tested it, and it worked - and it loaded the models much faster than usual :)
However, it also succeeded 3/15 times using 2.3.0.

**Comment by TobiasRD95** [comment]
Yes, it has been randomly failing and succeeding since using 2.3.0.
I have just tried again, and it succeeded .

**Comment by harupy** [comment]
Interesting. What about MLflow installed from the PR?

**Comment by TobiasRD95** [comment]
Nope, it seems to be stable using the PR version. At least it worked fine 4 out of 4 times :)

It might be relevant to say that the error mentioned in this bug appeared when building my docker container in Azure DevOps pipelines. When running the container locally, I have for a long time received a time out error once in a while, but this doesn't seem to be the case more.

**Comment by harupy** [comment]
I'm not sure why 2.3.0 is flaky. I think it should constantly fail (unless you download different models in each attempt).

**Comment by TobiasRD95** [comment]
We are downloading the same models each time - 1 big model and 20+ smaller
models, but it seems to always throw the error at the big model.

tor. 20. apr. 2023 16.54 skrev Harutaka Kawamura ***@***.***>:

**Comment by harupy** [comment]
I think there are two scenarios where we hit the return statement in the following code:

1. The file is downloaded serially.
2. The file is already in `download_path` and its size is larger than `downloaded_size`. For example, you make a download twice with the same destination.

```python
 if uri_type == ArtifactCredentialType.GCP_SIGNED_URL or uri_type is None: 
     # GCP files could be transcoded, in which case the range header is ignored. 
     # Test if this is the case by downloading one chunk and seeing if it's larger than the 
     # requested size. If yes, let that be the file; if not, continue downloading more chunks. 
     download_chunk(0, chunk_size, headers, download_path, http_uri) 
     downloaded_size = os.path.getsize(download_path) 
     # If downloaded size was equal to the chunk size it would have been downloaded serially, 
     # so we don't need to consider this here 
     if downloaded_size > chunk_size: 
         return
```

**Comment by TobiasRD95** [comment]
Yes, that could make sense. We are loading the models into the docker image, so I could imagine if I rerun the pipeline without code changes, it will cache the models.

**Comment by harupy** [comment]
Makes sense. Removing `/models/documentClassifier` or using a unique temporary directory in each run might change the result.
