### ISSUE TITLE
[BUG] autolog() causes not to stop at Python breakpoints

### ISSUE THREAD

**Issue by r-remus** [mlflow/mlflow#8310]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.3.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 22.04)**:
- **Python version**: 3.9.16
- PyCharm version: 2023.1 (231.8109.197)

### Describe the problem

Actual behavior: When using MLflow's `autolog` in conjunction with PyTorch (v2.0.0) and PyTorch Lightning (v2.0.0), PyCharm's debugger doesn't stop on breakpoints _after_ the `autolog()` call.

Expected behavior: When using MLflow's `autolog` in conjunction with PyTorch (v2.0.0) and PyTorch Lightning (v2.0.0), PyCharm's debugger stops on breakpoints irrespective of any `autolog()` call(s).

### Tracking information

```shell
none
```

### Code to reproduce issue

```
import os

import mlflow
import pytorch_lightning as L
import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import MNIST

PATH_DATASETS = os.environ.get("PATH_DATASETS", ".")
BATCH_SIZE = 256 if torch.cuda.is_available() else 64


class MNISTModel(L.LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = F.cross_entropy(self(x), y)
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.02)


mnist_model = MNISTModel()

# Init DataLoader from MNIST Dataset
train_ds = MNIST(PATH_DATASETS, train=True, download=True, transform=transforms.ToTensor())
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE)

# Initialize a trainer
trainer = L.Trainer(accelerator="auto", devices=1, max_epochs=1)
mlflow.autolog()

# Train the model ⚡
trainer.fit(mnist_model, train_loader)

print("put breakpoint on this line..")
print("..and PyCharm won't stop!")
# if you comment out the call to autolog(), however, stopping at this breakpoint works!
```

### Stack trace

```
none
```

### Other info / logs

```
none
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@r-remus I don't think this is an MLflow's issue, but a PyCharm's issue. A similar issue is reported in https://youtrack.jetbrains.com/issue/PY-4213.


I tested the attached code on VSCode and the breakpoint works fine.

**Comment by r-remus** [comment]
Thanks for getting back to me, trying it out on VSCode and sorry for not replying. I guess you're right; this must be a PyCharm bug then.
