### ISSUE TITLE
Eval_metrics are not defined in official doc

### ISSUE THREAD

**Issue by bobmayuze** [mlflow/mlflow#833]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac 10.11.4
- **MLflow installed from (source or binary)**:  source
- **MLflow version (run ``mlflow --version``)**: 0.8.1
- **Python version**: 3.6.5
- **npm version (if running the dev UI): 5.6.0
- **Exact command to reproduce**: N/A

### Describe the problem
eval_metrics function are missing in the official docs. Here is the [link](https://mlflow.org/docs/latest/tutorial.html#id6).

### Source code / logs
N/A

**Comment by mparkhe** [comment]
Hi @bobmayuze : 

That is a good catch. Docs need to be fixed to address this.

Btw: For this particular example `eval_metrics` is a function to compute metrics. It is defined in [examples/sklearn_elasticnet_wine/train.py](https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_wine/train.py#L19) file.

mani

**Comment by bobmayuze** [comment]
Hi Mani, 

 Is there any way I can help on that or I should wait till ppl from databricks fix it?
