### ISSUE TITLE
Feature request: Allow arbitrary depth in experiment table view

### ISSUE THREAD

**Issue by aadamson** [mlflow/mlflow#834]
Right now, if a run has children, you can expand the view to also display its children under it and slightly offset. However, it gathers all children of children and so on and displays them at the same offset as the immediate children instead of hiding them.

For deep model relationship trees, this makes the experiment table view confusing since there's no visual distinction between what is a child and what is a child of a child. If we could have the same collapsing/expanding and offsetting available for child runs as well, it would be much easier to grok what is going on at what level of the run hierarchy.

**Comment by mparkhe** [comment]
We are exploring ways to support multi-level runs.

**Comment by hmamdouh** [comment]
Hello,
Is there a progress about this feature request?
I am also interested in seeing multi hierarchical runs display in mlfow ui.
Thanks.

**Comment by jklen** [comment]
same here....
