### ISSUE TITLE
Feature request: Link to child runs on run page

### ISSUE THREAD

**Issue by aadamson** [mlflow/mlflow#835]
Right now, the run page links to the parent run (if it exists). It would be valuable to also be able to navigate to the child runs (if they exist).

**Comment by mparkhe** [comment]
This is a great idea! This would need some design and investment in UI and backend to be able to support this. Marked this as an enhancement.

**Comment by marcosjt7** [comment]
This would be really helpful. To add on, it would be nice if they were labeled by runName so that they're distinguishable in the case of multiple children. 

I imagine this could be handled with tags. Perhaps with two tags for each child, something like the following:
```
{
    "mlflow.childRuns.name.0": "first child",
    "mlflow.childRuns.Id.0": "d7dc4ebb145843be93e606b9e8f5660d",
    "mlflow.childRuns.name.1": "second child",
    "mlflow.childRuns.Id.1": "b7ea775a4a5248ac8309cf8f9bee7851",
}
```
