### ISSUE TITLE
[SETUP-BUG] Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by sumitgpl** [mlflow/mlflow#8360]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: v2.3.1
- **Python version**:Python 3.8.13

### Code to reproduce issue

yarn build

### Describe the problem

during yarn build getting below issue. 

Creating an optimized production build...
Failed to compile.

Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)

was facing same during `yarn start` also, but after setting `export NODE_OPTIONS=--openssl-legacy-provider` able to run.

### Other info / logs

node = v18.16.0
npm = 9.5.1
yarn = 3.5.0

**Comment by dbczumar** [comment]
Hi @sumitgpl , this appears to be a nodejs issue and not an MLflow issue. The workaround in https://stackoverflow.com/questions/69692842/ for nodejs v18 seems to help. Thank you for using MLflow!
