### ISSUE TITLE
[FR] Provide source distributions for mlflow-skinny

### ISSUE THREAD

**Issue by shimizust** [mlflow/mlflow#8361]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

mlflow-skinny < 2.1.0 (and all current versions of mlflow) provide source distributions on PyPI, which facilitate automated analysis and importation into internal, corporate repositories.

This proposal would be to publish source distributions for mlflow-skinny again, which seem to have stopped at v2.0.1.

For reference:
https://pypi.org/project/mlflow-skinny/2.0.1/#files (has source distro)
https://pypi.org/project/mlflow-skinny/2.1.0/#files (no source distro)

### Motivation

> #### Why is this use case valuable to support for your project(s) or organization?
We have automated systems for importing external libraries, which are based on automated analysis of source distributions (as opposed to built distributions). By not publishing source distributions, the process is very manual and time-consuming, and makes it difficult to stay up to date with the latest versions of mlflow-skinny.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @shimizust, thank you for notifying us of this gap. We're working to get source distributions published for future mlflow-skinny releases. Thank you for using MLflow!

**Comment by shimizust** [comment]
Thanks @dbczumar ! Glad to hear it's being worked on.

**Comment by harupy** [comment]
@shimizust We've uploaded the missing source distributions for mlflow-skinny :) Thanks for catching this!

**Comment by shimizust** [comment]
@harupy Thanks so much for fixing!
