### ISSUE TITLE
Can not create new independent run when mlflow forces to use nested run

### ISSUE THREAD

**Issue by chaupmcs** [mlflow/mlflow#838]
I create a new experiment and re-run `mlflow.start_run()` in `Python`. The  code as below
```
mlflow.set_tag('project', 'my_project' )
mlflow.set_experiment('my_project')

with mlflow.start_run():
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    .... // 
```
The error:

> Run with UUID 541c15b5fd954e1988d1ab17bccf74a2 is already active. To start a nested run call start_run with `nested=True`.

I try to deactivate runs by using `mlflow.end_run()`, but it just deactivates 1 run, and triggers the others to become active. The error still occurs. 

How to deal with the problem? I want to create a new independent run for the new experiment, and no need using a nested run here.
Any help would be appreciated.
Thank you.

### System information
- OS Platform and Distribution: Linux Ubuntu 16.04
- MLflow installed from: pip install mlflow
- MLflow version: mlflow, version 0.8.1
- Python version: Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux

**Comment by mparkhe** [comment]
Hi @chaupmcs : It looks like you are using `mlflow.set_tag` to create a tag before starting a run. Tags are defined on runs (not experiments)--not we are considering adding those in the near future.

Given you script -- `mlflow.set_tag` will create a new run and activate it. One of the mechanism to fix this would be to move after `start_run`

```
mlflow.set_experiment('my_project')

with mlflow.start_run():
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    mlflow.set_tag('project', 'my_project' )
    ...
```

cc: @smurching who debugged this issue

**Comment by piratezoro** [comment]
I am facing the same issue 
**code** 
experiment_id=mlflow.create_experiment("Exp11")
mlflow.start_run()
**ERROR**
Run with UUID 445f692a2e7b4ae086d87693b723616d is already active. To start a nested run, call start_run with nested=True
And when I try mlflow.end_run()
MlflowException: Run '445f692a2e7b4ae086d87693b723616d' not found

**Comment by mirekphd** [comment]
I get this error every time I run a seemingly innocuous read-only function `get_artifact_uri()` ("get*" functions are not supposed to alter anything...) - as a pure side effect of its being run. It breaks a python 3 code that worked previously for hundreds of runs and saved metrics for three different algos to a MariaDB database. The UI shows an empty table entry, and a db record is being created for within the current experiment.

Every time I restart mlflow server (container) I get a different UUID in the error message:
`Exception: Run with UUID 0c2471380c5949b4af7a18d0f1972f23 is already active. To start a nested run, call start_run with nested=True`

**Comment by echarso** [comment]
it happened to me also .
Thanks to the above comment, I removed the get tracking uri functions and then the problem was not visible anymore
