### ISSUE TITLE
MLflow client hangs when calling list_artifacts and download_artifacts when runing in notebooks.

### ISSUE THREAD

**Issue by AdamLouly** [mlflow/mlflow#8386]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

azureml-mlflow                          1.49.0
mlflow                                  2.3.1
mlflow-skinny                           2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

this bug is only when I  run it on a jupyter notebook 
When using the MLflow client to fetch the list of artifacts from an Azure ML (AML) job, the list_artifacts and download_artifacts function occasionally hangs, causing the script to be stuck indefinitely. The issue is inconsistent, as sometimes the function works as expected, while other times it requires multiple restarts to successfully retrieve the artifacts.

The task i'm doing is I'm trying to download output files from azureml jobs using mlflow.

like I mentioned sometimes it works and sometimes it doesn't.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow

def get_logs(model_name, run_type, deepspeed, experiment_name, run_name):
    # ... (other code) ...

    client = mlflow.tracking.MlflowClient()
    run = client.search_runs(experiment_ids=[experiment_id], filter_string=f"tags.mlflow.runName = '{run_name}'")[0]
    run_id = run.info.run_id

    logs_artifacts = client.list_artifacts(run_id, "user_logs")

    # ... (other code) ...

```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@akshaya-a @wamartin-aml can you take a look here?

**Comment by santiagxf** [comment]
This was identified as an issue in Azure ML notebooks and not related with MLflow SDK not the integration with Azure ML. @AdamLouly can we close this issue?

**Comment by AdamLouly** [comment]
sure, thank you!
