### ISSUE TITLE
MLFlow.pyfunc.log_model with artifact [BUG]

### ISSUE THREAD

**Issue by DhavalRepo18** [mlflow/mlflow#8396]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow, version 2.3.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

We are using https://mlflow.org/docs/latest/_modules/mlflow/pyfunc.html#log_model API. 

```
class MyModel4(mlflow.pyfunc.PythonModel):
            
    def predict(self, context, model_input):
        return model_output

artifact = {
    "step1": 'runs:/5e6a794686e947c891e0b7df94ef7368/model',
    "step2": 'runs:/56e7f30464364621b2fa212e8488ca83/model',
    "step3": 'runs:/84f847b19a5c438c848e0251c759e4f8/model',
}

my_model = MyModel4()
with mlflow.start_run():
    model_info = mlflow.pyfunc.log_model(artifact_path="model", python_model=my_model, artifacts=artifact)
    
print (model_info.model_uri)
```

The function run and create new artifact. However, it does not work as expected. It was suppose to copy the all of the three artifacts but then place them into a separate directory. However, due to name of model are same for each artifact it got overwrite. 

Expected Behavior: 
- [ ] Raise an error as the artifacts has same name for "model" for each of the steps in the artifacts. [Easy to implement]
- [ ] In case user provided more than one artifacts, since each of the artifact are copied in new artifacts, we should enable a check to see validity of an operation. 

The function work correctly, if each of the artifact's model name is different. I.e., 

artifact = {
    "step1": 'runs:/5e6a794686e947c891e0b7df94ef7368/model1',
    "step2": 'runs:/56e7f30464364621b2fa212e8488ca83/model2',
    "step3": 'runs:/84f847b19a5c438c848e0251c759e4f8/model3',
}

- [ ] Update to documentation is needed to warn user to carefully prepare the artifact. 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @DhavalRepo18 , the behavior you're encountering is expected. We recommend using the `artifact_path` parameter to specify different destinations for each model artifact, e.g. `artifact_path="model/step1"`, `artifact_path="model/step2"`, etc. Thank you for using MLflow!

**Comment by DhavalRepo18** [comment]
@dbczumar 

As a user, it is not expected behavior. if the user does not provide each artifact with a different name, the system uses the last steps and does not raise any warning. Users think that all is well, but it's not. At a bare minimum, an error should be popped. 

This can be a big implication for automation where machine may be packaging the artifacts.
