### ISSUE TITLE
Saving user-specific filters and user views

### ISSUE THREAD

**Issue by weitian** [mlflow/mlflow#841]
To support multi-users, mlflow tracking server should provide an optional to turn on some basic authentication, and to filter the experiments only to the user.

**Comment by mparkhe** [comment]
Hi @weitian:

A similar question was asked on mlflow-users list. Here's a [link to that question and Matei's response](https://groups.google.com/forum/#!topic/mlflow-users/E9QW4HdS8a8).

As for saved filters: we are exploring some options to support user filters in MLflow UI. If you / your team has some specific use cases for this--happy to hear those.

**Comment by weitian** [comment]
@mparkhe thanks for the quick reply.

I agree the authentication can be better handled outside (nginx, etc.).

Here is the use case for user-based filter:
We want to share a mlflow tracking server for a group of users. the web server (nginx) could handle the auth, and pass the user name in HTTP header to mlflow. Since each run has a username, we could only show the runs which match the username in HTTP header.

It will be better to have an option to filter on experiments if experiment can have a username while creating the experiment.

In our team, each developer manages their own experiments. Within an experiments, the model training usually runs in a container from a cloud environment. We could not save the 'mlruns' in container's local file system, and we need a central tracking server to collect information for all developers. But when a developer opens the mlflow tracking UI, he/she only interests in his/her own experiments.

**Comment by bobmayuze** [comment]
Agreed, probably we could take the way redash did their auth?

**Comment by n3o-Bhushan** [comment]
Any updates on this?

**Comment by Dhaval08** [comment]
Any updates? User based filters for tracking UI would be a welcome feature.

**Comment by lmatejka** [comment]
Is there any update for this? In UI is quite uneasy to specify columns again for each visit.
