### ISSUE TITLE
[DOC-FIX] Add mlflavors library to community model flavors

### ISSUE THREAD

**Issue by benjaminbluhm** [mlflow/mlflow#8414]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

[Community Model Flavors](https://mlflow.org/docs/latest/models.html#id22)

### Description of proposal (what needs changing)

I created a new library [mlflavors](https://github.com/ml-toolkits/mlflavors) which contains custom flavors for some popular ML frameworks currently not included as built-in flavors. There also exists a [package documentation](https://mlflavors.readthedocs.io/en/latest/index.html#) with detailed usage example for each flavor and API reference.

Proposal is to list the mlflavors library in the MLflow docs as part of the [Community Model Flavors](https://mlflow.org/docs/latest/models.html#id22) section providing the [Quickstart example](https://github.com/ml-toolkits/mlflavors#quickstart) from the mlflavors repo.

**Comment by WeichenXu123** [comment]
Make sense! Appreciate your contribution!
