### ISSUE TITLE
[BUG] SQL backend storage returns BAD_REQUEST instead of RESOURCE_ALREADY_EXISTS for duplicate experiment creation

### ISSUE THREAD

**Issue by ddl-ebrown** [mlflow/mlflow#8430]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.2.2
- Tracking server: 2.2.2

### System information

N/A

### Describe the problem

When creating a new experiment, MLflow returns responses inconsistently through the REST API depending on whether the backend metadata is served by the file system or a SQL database like Postgres.

Per the REST API documentation at https://www.mlflow.org/docs/latest/rest-api.html#create-experiment the error returned should be `RESOURCE_ALREADY_EXISTS`

The same problem is true for run creation

### Tracking information

```shell
System information: Linux #1 SMP Wed Nov 2 17:44:17 UTC 2022
Python version: 3.9.16
MLflow version: 2.2.2
MLflow module location: /opt/conda/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: [http://localhost:80](http://localhost/)
Registry URI: [http://localhost:80](http://localhost/)
MLflow environment variables: 
  MLFLOW_TRACKING_TOKEN: 
  MLFLOW_TRACKING_URI: [http://localhost:80](http://localhost/)
MLflow dependencies: 
  Flask: 1.1.2
  Jinja2: 3.0.3
  alembic: 1.10.2
  click: 8.0.4
  cloudpickle: 2.2.1
  databricks-cli: 0.17.6
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 6.1.0
  markdown: 3.4.3
  matplotlib: 3.6.2
  numpy: 1.23.3
  packaging: 23.0
  pandas: 1.5.0
  protobuf: 3.20.3
  pyarrow: 8.0.0
  pytz: 2022.2.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.1
  scikit-learn: 1.1.2
  scipy: 1.9.2
  shap: 0.41.0
  sqlalchemy: 1.4.47
  sqlparse: 0.4.3
```

### Code to reproduce issue

Assume the use of the following Python code

```
import mlflow

mlflow.create_experiment("foo")

mlflow.create_experiment("foo")
```

When using a file storage backend, the response from MLflow is the error `RESOURCE_ALREADY_EXISTS` as defined in the REST API documentation at https://www.mlflow.org/docs/latest/rest-api.html#create-experiment

However, when using a SQL backend like Postgres, the error returned is instead `BAD_REQUEST` like:

```
RestException: BAD_REQUEST: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "experiments_name_key"
DETAIL:  Key (name)=(foo) already exists.

[SQL: INSERT INTO experiments (name, artifact_location, lifecycle_stage, creation_time, last_update_time) VALUES (%(name)s, %(artifact_location)s, %(lifecycle_stage)s, %(creation_time)s, %(last_update_time)s) RETURNING experiments.experiment_id]
[parameters: {'name': 'foo', 'artifact_location': 'mlflow-artifacts:/mlflow', 'lifecycle_stage': 'active', 'creation_time': 1683935829736, 'last_update_time': 1683935829736}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

Not only is this inconsistent, but it also leaks internal SQL details in the error message.

### Stack trace

N/A

### Other info / logs

N/A

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by fvarno** [comment]
Using `mlflow==2.15.1` and postgres as backend, I encountered the following error:
```
RestException: BAD_REQUEST: (psycopg2.errors.NumericValueOutOfRange) value "944140571234832402" is out of range for type integer
LINE 3: WHERE experiments.experiment_id = '944140571234832402' AND e...
                                          ^

[SQL: SELECT experiments.experiment_id AS experiments_experiment_id, experiments.name AS experiments_name, experiments.artifact_location AS experiments_artifact_location, experiments.lifecycle_stage AS experiments_lifecycle_stage, experiments.creation_time AS experiments_creation_time, experiments.last_update_time AS experiments_last_update_time 
FROM experiments 
WHERE experiments.experiment_id = %(experiment_id_1)s AND experiments.lifecycle_stage IN (%(lifecycle_stage_1_1)s, %(lifecycle_stage_1_2)s)]
[parameters: {'experiment_id_1': '944140571234832402', 'lifecycle_stage_1_1': 'active', 'lifecycle_stage_1_2': 'deleted'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
```

Not sure if it ever happens with the latest mlflow version or not just dropped it here in case anyone likes to reproduce and check.
