### ISSUE TITLE
[BUG] Wrong subprocess.Popen usage

### ISSUE THREAD

**Issue by dkubicahitachi** [mlflow/mlflow#8435]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.30

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **Python version**: 3.11.0
- **yarn version, if running the dev UI**: -

### Describe the problem

Hello,

Under Windows, if the string parameter contains a space, e.g. 

```mlflow run . --param-list input_string='Sentence with spaces' --param-list input_ints=[1,2,3]  ```

program throws an error ```Error: Got unexpected extra arguments (with spaces")```.

There is a problem when executing child process in [LocalBackend class](https://github.com/mlflow/mlflow/blob/v1.30.0/mlflow/projects/backend/local.py#L257)
``` py
def _run_entry_point(command, work_dir, experiment_id, run_id):
    """
    Run an entry point command in a subprocess, returning a SubmittedRun that can be used to
    query the run's status.
    :param command: Entry point command to run
    :param work_dir: Working directory in which to run the command
    :param run_id: MLflow run ID associated with the entry point execution.
    """
    env = os.environ.copy()
    env.update(get_run_env_vars(run_id, experiment_id))
    env.update(get_databricks_env_vars(tracking_uri=mlflow.get_tracking_uri()))
    _logger.info("=== Running command '%s' in run with ID '%s' === ", command, run_id)
    # in case os name is not 'nt', we are not running on windows. It introduces
    # bash command otherwise.
    if os.name != "nt":
        process = subprocess.Popen(["bash", "-c", command], close_fds=True, cwd=work_dir, env=env)
    else:
        # process = subprocess.Popen(command, close_fds=True, cwd=work_dir, env=env)
         process = subprocess.Popen(["cmd", "/c", command], close_fds=True, cwd=work_dir, env=env)
    return LocalSubmittedRun(run_id, process)
```

Problem is with array passed to Popen. Now array looks like: ["cmd", "/c", "conda activate mlflow-b363dd556138e2715cfcc786bc5631fbf6353144 && python main.py --input_string "Sentence with spaces" --input_ints [1,2,3]"], so only two elements.
Correct array should look like this : ["cmd", "/c", "conda", "activate", "mlflow-b363dd556138e2715cfcc786bc5631fbf6353144", "&&", "python", "main.py", "--input_string", "Sentence with spaces", "--input_ints", "[1,2,3]"], so every input should be as another element of array. 

Also [documentation](https://docs.python.org/3.7/library/subprocess.html#popen-constructor) says that:

> args should be a sequence of program arguments or else a single string. By default, the program to execute is the first item in args if args is a sequence. If args is a string, the interpretation is platform-dependent and described below. See the shell and executable arguments for additional differences from the default behavior. Unless otherwise stated, it is recommended to pass args as a sequence.
> 
> An example of passing some arguments to an external program as a sequence is:
> 
> ```Popen(["/usr/bin/git", "commit", "-m", "Fixes a bug."])```
>  

I use mlflow in 1.30 version, but I see in the newest version of mlflow method ```_run_entry_point``` looks exactly this same.

Can you fix Popen call as the documentation says?

### Code to reproduce issue

```mlflow run . --param-list input_string="Sentence with spaces" --param-list input_ints=[1,2,3]  ```

``` py
import click
import sys

@click.command()
@click.pass_context
@click.option('--input_string')
@click.option('--input_ints')
def main(ctx, input_string, input_ints):
    print(ctx.params)
    print(input_string)
    print(input_ints)
```

### Stack trace

``` cmd
2023/05/15 12:13:21 INFO mlflow.utils.conda: Conda environment mlflow-b363dd556138e2715cfcc786bc5631fbf6353144 already exists.
2023/05/15 12:13:21 INFO mlflow.projects.utils: === Created directory C:\Users\DK\AppData\Local\Temp\tmpsf94svwo for downloading remote URIs passed to arguments of type 'path' ===
2023/05/15 12:13:21 INFO mlflow.projects.backend.local: === Running command 'conda activate mlflow-b363dd556138e2715cfcc786bc5631fbf6353144 && python main.py --input_string "Sentence with spaces" --input_ints [1,2,3]' in run with ID '68cd719b302540c4bcfc7d6d1eca0902' ===
Usage: main.py [OPTIONS]
Try 'main.py --help' for help.

Error: Got unexpected extra arguments (with spaces")
2023/05/15 12:13:25 ERROR mlflow.cli: === Run (ID '68cd719b302540c4bcfc7d6d1eca0902') failed ===
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Thanks for reporting this !

But we cannot easily splitting the command to multiple components, the reason is:

* on UNIX-like system, (e.g., linux/macos) , we have to use ["bach", "-c", some_command], the `some_command` must be one string containing the whole command (the command can be multiple commands connected with `&&` e.g. `'command1 && command2'`),  otherwise it does not work.
* For windows, seemingly we can split the `some_command` into a list of strings, but, if doing this, we need to change code in a lot of places, because the command here contains the part "conda activate xxx", we already generate a whole string for the activating command.

**Comment by WeichenXu123** [comment]
I think a workaround could be, setting environment variable instead of params in this case,
on windows, you can set environment variable by command like:

```
set xyz=aa bb cc
```
(xyz is the environment variable name and the content after `=` is the environment variable value)
