### ISSUE TITLE
[BUG] Why MLflow log XGBoost Model to Model Registry as model.None ?

### ISSUE THREAD

**Issue by szymonbcoding** [mlflow/mlflow#8440]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

Python API:
mlflow==2.3.2
xgboost==1.7.5

### System information

Python 3.8.10
Jupyter Notebook in Kubeflow with  image: jupyter-scipy:v1.6.0-rc.2

### Describe the problem

I have problem with logging XGBoost model. I prepared simple flow for further deploy model with KServe:
```
import mlflow
import pandas as pd

file_url = "https://azuremlexampledata.blob.core.windows.net/data/heart-disease-uci/data/heart.csv"
df = pd.read_csv(file_url)
print(df.head())

df["thal"] = df["thal"].astype("category").cat.codes

df["thal"].unique()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.drop("target", axis=1), df["target"], test_size=0.3
)

mlflow.xgboost.autolog()

from xgboost import XGBClassifier

model = XGBClassifier(use_label_encoder=False, eval_metric="logloss")

run = mlflow.start_run()

model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, recall_score, precision_score

accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy: %.2f%%" % (accuracy * 100.0))
print("Recall: %.2f%%" % (recall * 100.0))

mlflow.end_run()
```
Code works ok, but the problem is logging XGBoost model as file model.None in Model Registry.
Due to KServe Github, Kserve supports only .bst extension:
https://github.com/kserve/kserve/blob/master/python/xgbserver/xgbserver/model.py#L28

I tried to put argument to mlflow.xgboost.autolog() -> mlflow.xgboost.autolog(registered_model_name='model', model_format='bst'), but I got error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [9], in <cell line: 18>()
     12 from sklearn.model_selection import train_test_split
     14 X_train, X_test, y_train, y_test = train_test_split(
     15     df.drop("target", axis=1), df["target"], test_size=0.3
     16 )
---> 18 mlflow.xgboost.autolog(registered_model_name='model', model_format='bst')
     20 from xgboost import XGBClassifier
     22 model = XGBClassifier(use_label_encoder=False, eval_metric="logloss")

File /opt/conda/lib/python3.8/site-packages/mlflow/utils/autologging_utils/__init__.py:414, in autologging_integration.<locals>.wrapper.<locals>.autolog(*args, **kwargs)
    395 with set_mlflow_events_and_warnings_behavior_globally(
    396     # MLflow warnings emitted during autologging setup / enablement are likely
    397     # actionable and relevant to the user, so they should be emitted as normal
   (...)
    410     disable_warnings=is_silent_mode,
    411 ):
    412     _check_and_log_warning_for_unsupported_package_versions(name)
--> 414     return _autolog(*args, **kwargs)

TypeError: autolog() got an unexpected keyword argument 'model_format'
```
It is very weird, because mlflow docs describes this argument:
https://www.mlflow.org/docs/2.3.2/python_api/mlflow.xgboost.html#mlflow.xgboost.autolog

How can I fix it and save my XGBClassifier in format, which I will choose?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Thanks for reporting this, I will take a look soon.

**Comment by WeichenXu123** [comment]
Hi @szymonbcoding

Unfortunately, I cannot reproduce your issue using mlflow==2.3.2

I first tried your reproducing code in PR description, it logs model as file "model.xgb" (xgb is the default model_format)

then I called `mlflow.xgboost.autolog(model_format='bst')`,

then rerun your xgboost training code, then the model is logged as file "model.bst".

**Comment by szymonbcoding** [comment]
I have tried to reproduce this issue in my local machine with mlflow==2.3.2 and I see also that model is logged with .bst extension. I didn't suppose thah, but it could be environment problem of Jupyter Notebook in Kubeflow with image: jupyter-scipy:v1.6.0-rc.2 
Thanks for help.
