### ISSUE TITLE
[FR] Experiment id is not random number when backend store uri is sqlite

### ISSUE THREAD

**Issue by ShuxinLin** [mlflow/mlflow#8457]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

If the backend_store_uri of mlflow server is a local SQLite database, I found the experiment id always starting from 1, 2, 3, ... incrementally
On the contrary, if backend_store_uri is `./mlruns`, the experiment id is random number. I would like to know if SQLite backend can follow the same pattern.

### Motivation

> #### What is the use case for this feature?

Why I need this feature is because I am currently hosting the remote mlflow tracking server by command 
```
mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://<s3-bucket-name> --host 0.0.0.0 --port 5000
```
When I redeploy the tracking server to another cloud machine, the new experiment is always given an id starting from 1,2,3,... But since I reuse the old S3 bucket, the experiment artifacts are messed up.

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
It is legitimate that different backend uses different format experiment ID.
Just curious, what is the issue you are facing that is caused by the different ID format between filestore / sql-store backends ?

Changing sql-store backend experiment ID format is doable, but my concern is that it might cause backward-compatiblity issue, i.e. if we upgrade mlflow and new version mlflow might not work on existing mlflow database, we need to deal with such change carefully.

**Comment by ShuxinLin** [comment]
![scenario_4](https://github.com/mlflow/mlflow/assets/8956612/8125c544-14b8-48e2-a527-5ca866ac076c)

I am using this design of mlflow tracking (image from mlflow docs). I dockerized both mlflow tracking server and PostgreSQL. Everytime I reployed the tracking server and PostgreSQL, the new experiments are given experiment_id starting from 1, 2, 3, incrementally, since PostgreSQL is a fresh start. But I was reusing the same S3 bucket. Therefore the old experiments are polluted with new experiments in S3 bucket because they have same experiment id. If experiment id is  unique number, then the problem will be solved.

**Comment by WeichenXu123** [comment]
I got it. Another workaround is you can create sub-directory under the s3 bucket and configure different MLflow server to use different s3 sub-directory as the root artifact storage path, e.g.

s3://bucket_name/folder1
s3://bucket_name/folder2

What do you think ?

**Comment by WeichenXu123** [comment]
To avoid mlflow database migration issue, we decided to not change the experiment id format stored in mlflow database. We recommend this approach https://github.com/mlflow/mlflow/issues/8457#issuecomment-1553846708
But if you still have issue, feel free to reopen the ticket.

**Comment by ShuxinLin** [comment]
> I got it. Another workaround is you can create sub-directory under the s3 bucket and configure different MLflow server to use different s3 sub-directory as the root artifact storage path, e.g.
> 
> s3://bucket_name/folder1 s3://bucket_name/folder2
> 
> What do you think ?

This works well. Thanks!
