### ISSUE TITLE
An error occurred when loading MLFlow App in Databricks 

### ISSUE THREAD

**Issue by ChekrounMohammed** [mlflow/mlflow#8487]
### MLflow version

mlflow-2.3.2

### Describe the problem

I am using MLflow with databricks ,I am running my experiments in google collab and logging the params and the metrics using Databricks community cloud , Now I am trying to access databricks UI for experimentations and I am facing the following error :
![image](https://github.com/mlflow/mlflow/assets/86720032/67f624c7-e6b7-4547-aeed-b4167b593f97)

### Steps to reproduce the bug

- Open Databricks community cloud 
- Access the experiments 
- And click on the experiment you want to show

**Comment by WeichenXu123** [comment]
@ChekrounMohammed 

Thanks for reporting this !

Could you also provide your Databricks runtime version and databricks cluster config ?

**Comment by WeichenXu123** [comment]
I discussed with Mlflow dev team members, we recommand to use "run_name_prefix" in your case:
See https://github.com/mlflow/mlflow/pull/7763/files

i.e., adds an "experiment" section in recipe profile yaml file, and inside "experiment" section, adds a "run_name_prefix" config.

**Comment by hubertzub-db** [comment]
@ChekrounMohammed @ot-babs @WeichenXu123 
Thanks for reporting, the issue has been fixed a while ago. Can you confirm the experiments are accessible in Databricks Community Cloud?
