### ISSUE TITLE
Question regarding `autolog` behavior with Lightning's multi-GPU training

### ISSUE THREAD

**Issue by amorehead** [mlflow/mlflow#8494]
Hello.

I was curious whether the following code example would be compatible with PyTorch Lightning's current DDP implementation (e.g., when training with > 1 GPU)? Namely, is it sufficient to call `autolog` on `rank_zero` only, or will other ranks need to call this function as well?

https://github.com/mlflow/mlflow/blob/603f99acdab808f15ae82551d7ed72f9ecc86bf2/examples/pytorch/MNIST/mnist_autolog_example.py#L240

**Comment by WeichenXu123** [comment]
You only need to call `mlflow.pytorch.autolog()` in main thread once.

It supports pytorch DDP training.

See https://github.com/mlflow/mlflow/blob/b61e3ce24219e402aac05ec37d09a00dff5b09c4/tests/pytorch/test_pytorch_autolog.py#L348

**Comment by amorehead** [comment]
Thanks for clarifying this for me!
