### ISSUE TITLE
[BUG] with spark autolog, the Python script never finishes and hangs

### ISSUE THREAD

**Issue by florent-brosse** [mlflow/mlflow#8502]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.3.2
- Tracking server: 2.3.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 13.3.1
- **Python version**: 3.11.3

### Describe the problem

As soon we call mlflow.spark.autolog() the Python script never finishes and hangs.
If I call spark.sparkContext._gateway.close() it closes properly the spark context and the script finishes.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
from pyspark.sql import SparkSession

spark = SparkSession.builder.config("spark.jars.packages", "org.mlflow:mlflow-spark:2.3.2").getOrCreate()
import mlflow
mlflow.spark.autolog() # work if we comment autolog

#spark.sparkContext._gateway.close() # work if we close the gateway

print("DONE")
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Emm, I cannot reproduce your issue, what's your pyspark version ?

CC @hyukijin

In `mlflow.spark.autolog`, we register a callback server on py4j gateway:
https://github.com/mlflow/mlflow/blob/b61e3ce24219e402aac05ec37d09a00dff5b09c4/mlflow/_spark_autologging.py#L100

any reason that might cause the issue ?

@florent-brosse 

Did you try to add `spark.stop()` at the end of the script and see whether the python process can exit ?

**Comment by florent-brosse** [comment]
I've tried with a new venv : pyspark 3.4.0 and mlflow 2.3.2
With spark.stop() the spark UI is no more available but the script never finishes. Some threads are still running.
![Capture d’écran 2023-05-23 à 10 44 14](https://github.com/mlflow/mlflow/assets/33132524/f3fc5594-306d-4fcd-8a38-bf3d63af52b9)

**Comment by WeichenXu123** [comment]
I can reproduce your issue. I tested on spark 3.3 and spark 3.4, both of them have the issue.

**Comment by WeichenXu123** [comment]
I think we can call `spark.sparkContext._gateway.shutdown_callback_server()`, this is a better way.

**Comment by WeichenXu123** [comment]
I suggest to update mlflow code like:

* When `mlflow.spark.autolog(disable=True)` is called, trigger  `spark.sparkContext._gateway.shutdown_callback_server()`
* We register a `sys.atexit` hook, in the hook,  in the atexit hook, checking whether `mlflow.spark` autologging is ON, if it is ON we should call `mlflow.spark.autolog(disable=True)` to disable it (so that the spark callback server is shut down properly)


I can file a PR for this, if you are not familiar with related code :)

**Comment by florent-brosse** [comment]
Hi Weichen, 

I like your solution because I tried to disable the autolog and it did nothing.
Sure fill a PR that's your solution and you'll be faster than me.
Thanks again.

Florent

**Comment by florent-brosse** [comment]
Btw do you know why does it happen? In the CallbackServerParameters `daemonize=True` should prevent this, right?

**Comment by WeichenXu123** [comment]
> Btw do you know why does it happen? In the CallbackServerParameters `daemonize=True` should prevent this, right?

This should spark code bug. @@HyukjinKwon know more details. To support existing spark versions, we have to add handling code in mlflow side.

**Comment by WeichenXu123** [comment]
PR is ready:
https://github.com/mlflow/mlflow/pull/8508

Note that `atexit` hook does not work, see explanation: https://github.com/mlflow/mlflow/pull/8508#issuecomment-1560426471

So that with my fix, you still need to add `spark.stop()` at the end of main thread to ensure spark callback server shut down properly.

@florent-brosse
