### ISSUE TITLE
[FR] Parametrize the save as external data for ONNX model logging

### ISSUE THREAD

**Issue by MainRo** [mlflow/mlflow#8522]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Since #7808, ONNX models are systematically saved with the weights saved in a separate file. This introduced a behavior change, and it is needed only for big models. The associated code is here:

https://github.com/mlflow/mlflow/blob/5712024236c45e7830506bb3adba3c6e42131625/mlflow/onnx.py#L175

It would be nice to allow to enable or not this behavior so that a small model can still be serialized as a single file.

### Motivation

> #### What is the use case for this feature?

- Keep the behavior consistent this the previous one
- Serialize small models as a single file

> #### Why is this use case valuable to support for MLflow users in general?

Splitting a model into several files makes using it more complex, primarily when mlflow is not used for inference.

> #### Why is this use case valuable to support for your project(s) or organization?

We never use models bigger than 2GB, and we process models are single-file objects.

> #### Why is it currently difficult to achieve this use case?

It is not possible to log ONNX models as a single file with recent releases of mlflow.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
@MainRo sorry for taking so long to get around to fixing this. We're introducing an argument in save_model / log_model where you will be able to disable the external file behavior and allow you to save a model that is <2GB as a single file again. It will be available in the upcoming MLflow 2.8.0 release.
