### ISSUE TITLE
Feature request: support parameters for pyfunc serve

### ISSUE THREAD

**Issue by dream83619** [mlflow/mlflow#855]
I'm creating a internal used ML platform upon mlflow, and need to pass some additional parameters to start pyfunc serve. I think it will really be a good enhancement to support additional parameters for pyfunc serve. 

thanks

**Comment by smurching** [comment]
@dream83619 that seems pretty reasonable - what sort of configuration options are you interested in passing?

Some thoughts on how we could pass additional config options: for the MLflow tracking server, we support additional configuration via a `--gunicorn-opts` argument passed to `mlflow server` (see [CLI code](https://github.com/mlflow/mlflow/blob/master/mlflow/cli.py#L198) and [server initialization code](https://github.com/mlflow/mlflow/blob/master/mlflow/server/__init__.py#L65)). We could consider doing the same with the local pyfunc server. Specifically we could consider:
* Allowing passing additional arguments to our invocation of `app.run` [here](https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/cli.py#L72)
* As a follow-up, wrapping the pyfunc server in gunicorn & passing gunicorn options to the server

**Comment by yassineAlouini** [comment]
That would be a really nice feature. I have a similar use case (internal ML platform using MLflow for managing a part of the workflow) and would need to have "production" server to serve the `/invocations` end-point.
