### ISSUE TITLE
[BUG] tests/example/test_examples.py fail when run whisper example

### ISSUE THREAD

**Issue by PenHsuanWang** [mlflow/mlflow#8562]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Tracking server: 2.3.3.dev.0 
(master: 7baba5ddf5631838df51fd5025aa072fdc066d09)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04
- **Python version**: 3.8.13
- **yarn version, if running the dev UI**:

### Describe the problem

the whisper example has a fix in #8537 
but when run tests/example 
`pytest tests/examples/test_examples.py -k test_command_example[transformers-command41] --quiet --requires-ssh`

the test case still failed.

### Tracking information

```text

mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['python', 'whisper.py']
STDERR:
2023-05-30 07:58:11.188357: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-30 07:58:11.861977: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /root/pwang_dev/ForkedOpenSource/mlflow/examples/transformers/whisper.py:20  │
│ in <module>                                                                  │
│                                                                              │
│   17 # type.                                                                 │
│   18 signature = mlflow.models.infer_signature(                              │
│   19 │   audio,                                                              │
│ ❱ 20 │   mlflow.transformers.generate_signature_output(audio_transcription_p │
│   21 )                                                                       │
│   22                                                                         │
│   23 inference_config = {                                                    │
│                                                                              │
│ /root/pwang_dev/ForkedOpenSource/mlflow/mlflow/transformers.py:1530 in       │
│ generate_signature_output                                                    │
│                                                                              │
│   1527 │   │   │   error_code=INVALID_PARAMETER_VALUE,                       │
│   1528 │   │   )                                                             │
│   1529 │                                                                     │
│ ❱ 1530 │   return _TransformersWrapper(pipeline=pipeline, inference_config=i │
│   1531                                                                       │
│   1532                                                                       │
│   1533 class _TransformersWrapper:                                           │
│                                                                              │
│ /root/pwang_dev/ForkedOpenSource/mlflow/mlflow/transformers.py:1612 in       │
│ predict                                                                      │
│                                                                              │
│   1609 │   │   │   │   for x in input_data                                   │
│   1610 │   │   │   )                                                         │
│   1611 │   │                                                                 │
│ ❱ 1612 │   │   predictions = self._predict(input_data, device)               │
│   1613 │   │                                                                 │
│   1614 │   │   return predictions                                            │
│   1615                                                                       │
│                                                                              │
│ /root/pwang_dev/ForkedOpenSource/mlflow/mlflow/transformers.py:1746 in       │
│ _predict                                                                     │
│                                                                              │
│   1743 │   │   ):                                                            │
│   1744 │   │   │   return pd.DataFrame(raw_output)                           │
│   1745 │   │   else:                                                         │
│ ❱ 1746 │   │   │   output = self._parse_lists_of_dict_to_list_of_str(raw_out │
│   1747 │   │                                                                 │
│   1748 │   │   return self._sanitize_output(output, data)                    │
│   1749                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
UnboundLocalError: local variable 'raw_output' referenced before assignment
```

### Code to reproduce issue

run test
`pytest tests/examples/test_examples.py -k test_command_example[transformers-command41] --quiet --requires-ssh`

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
cc @BenWilson2

**Comment by harupy** [comment]
@PenHsuanWang Thanks for reporting this issue. Can you run the example again once the PR above is merged (will be soon)?

**Comment by PenHsuanWang** [comment]
@harupy The problem is solved, thanks a lot.

![截圖 2023-05-31 上午11 19 07](https://github.com/mlflow/mlflow/assets/13614761/547aef8b-e646-4694-b7a9-e7c5d98c34b6)
