### ISSUE TITLE
[BUG] 2.4.0 regression: `import mlflow` fails if a `datasets` directory exists

### ISSUE THREAD

**Issue by JulianJvn** [mlflow/mlflow#8641]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.4.0
- Tracking server: N/A

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04 LTS
- **Python version**: 3.10.6
- **yarn version, if running the dev UI**: N/A

### Describe the problem

* Actual behavior: `import mlflow` fails for the 2.4.0 `mlflow` Python package if a directory named `datasets` exists in the current directory. The traceback shows an `AttributeError` on line 23 of `mlflow/data/huggingface_dataset_source.py`.
* Expected behavior: `import mlflow` does not fail. It's not far-fetched that a user working with MLflow has a directory with the name `datasets`, so this should be supported by MLflow.
* The error does not appear with version 2.3.2, so this is a regression.
* This is probably related to #8186.

### Tracking information

```shell
```

### Code to reproduce issue

```console
$ mkdir mlflow-bug
$ cd mlflow-bug
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install mlflow==2.4.0
$ mkdir datasets
$ python -c "import mlflow"
```

### Stack trace

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/__init__.py", line 41, in <module>
    from mlflow import projects  # pylint: disable=unused-import
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 9, in <module>
    import mlflow.projects.databricks
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/projects/databricks.py", line 11, in <module>
    from mlflow import tracking
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/tracking/__init__.py", line 20, in <module>
    from mlflow.tracking.fluent import _EXPERIMENT_ID_ENV_VAR, _EXPERIMENT_NAME_ENV_VAR, _RUN_ID_ENV_VAR
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 13, in <module>
    from mlflow.data.dataset import Dataset
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/data/__init__.py", line 5, in <module>
    from mlflow.data import dataset_registry
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/data/dataset_registry.py", line 137, in <module>
    from mlflow.data.huggingface_dataset import from_huggingface
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/data/huggingface_dataset.py", line 11, in <module>
    from mlflow.data.huggingface_dataset_source import HuggingFaceDatasetSource
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/data/huggingface_dataset_source.py", line 10, in <module>
    class HuggingFaceDatasetSource(DatasetSource):
  File "/home/JulianJvn/mlflow-bug/.venv/lib/python3.10/site-packages/mlflow/data/huggingface_dataset_source.py", line 23, in HuggingFaceDatasetSource
    split: Optional[Union[str, datasets.Split]] = None,
AttributeError: module 'datasets' has no attribute 'Split'
```

### Other info / logs

```
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@JulianJvn Thanks for reporting the issue. I was able to make a repro.

**Comment by harupy** [comment]
To repro, `datasets` must be uninstalled.

**Comment by harupy** [comment]
Filed #8642
