### ISSUE TITLE
Integrate ONNX (Open Neural Network eXchange)

### ISSUE THREAD

**Issue by slavakurilyak** [mlflow/mlflow#865]
As a developer, I want to integrate [ONNX](https://onnx.ai/) into mlflow, so that I can use open format to represent deep learning models and more easily explore state-of-the-art tools.

Want to learn more? Onnx has an [active developer community on Github](https://github.com/onnx).

**Comment by slavakurilyak** [comment]
Also consider [Predictive Model Markup Language (PMML)](http://dmg.org/) as an open format for statistical and data mining models

**Comment by smurching** [comment]
Hi @slavakurilyak, IMO it could definitely make sense to add support for ONNX as a model flavor (see [MLflow Model docs](https://www.mlflow.org/docs/latest/models.html#mlflow-models)) - it looks like many of the frameworks MLflow currently interfaces with also have support for exporting to / importing from ONNX ([see here](https://github.com/onnx/tutorials#getting-onnx-models)). 

My gut feeling is that we could add logic to optionally generate the ONNX flavor while saving an MLflow model, but I think it'll take some design to figure out how to do this in a generic way extensible to adding support for non-ONNX export formats in the future.

**Comment by smurching** [comment]
I think next steps would be to concretely outline the pros/cons of adding ONNX support (i.e. what would we gain by adding it to MLflow, and what would it look like?) For example, one potential pro is that you'd be able to persist e.g. a PyTorch model with MLflow and load it back into TensorFlow, while a con could be that it's already easy to do so using ONNX APIs and so MLflow wouldn't provide much value.

Once we've settled that question we can go ahead & start thinking about potential designs - thanks again for bringing this up!

**Comment by AveshCSingh** [comment]
Fixed in https://github.com/mlflow/mlflow/pull/1127
