### ISSUE TITLE
Select all child runs when parent run is selected in MLflow UI

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#870]
In the MLflow UI, selecting a parent run doesn't select its children (see screenshot) - it'd be nice if it did

![image](https://user-images.githubusercontent.com/2358483/52244119-0160c980-2891-11e9-929f-4c91da4ffdd1.png)

**Comment by jakubczakon** [comment]
You could also have your MLflow experiment runs hosted on [neptune.ml][1]. You can adjust your experiment dashboard however you like and group/select whatever you like. Check out [this project](https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments), play around with grouping and see if it solves your problem. 

Drop a comment if you do, I would really like to get feedback on that.

Also if you are interested, I have just written a [blog post about it][3].

  [1]: https://neptune.ml/?utm_source=stack_exchange&utm_medium=forum&utm_campaign=neptune_is_free&utm_term=mlflow
  [2]: https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments
  [3]: https://medium.com/neptune-ml/collaborate-on-mlflow-experiments-in-neptune-fb4f8f84a995

**Comment by dbczumar** [comment]
Closing since this feature exists now :)

**Comment by ealizadeh-via** [comment]
@dbczumar @Zangr 
I have the same problem with the latest MLflow (**v1.27.0**).
My system is  **macOS Monterey (version 12.4) - Apple M1, 2020** and **Python version= 3.8.13**.

![Screen Shot 2022-08-08 at 12 20 36 PM](https://user-images.githubusercontent.com/84460342/183495947-921f9c4a-a8e4-43b8-abd5-ab4b92fc691f.png)

**Comment by dbczumar** [comment]
@ealizadeh-via Apologies, looks like https://github.com/mlflow/mlflow/pull/883 was never merged. It's unclear whether or not this feature ever existed. Reopening. We'll work on an implementation :).

**Comment by ealizadeh-via** [comment]
Thanks @dbczumar 🙏 . I thought the feature exists as per your earlier comment on Sep 17, 2021. I'm looking forward to this feature :)

**Comment by miriamelia** [comment]
me to, that would really help comparing all childruns, got like 100+ :D

**Comment by gozdi29** [comment]
Is there any way to select all children runs in one click without selecting the parent run?

**Comment by vincentvalton** [comment]
Same issue here:
- Clicking on the un-expanded parent in MLFlow tracking UI does not select its children (we need to first expand all parent runs by clicking on '+', then when selecting the parent the children are also selected). But this requires expanding all parents until one sees all the children nodes to select all the parent + children.

![Screenshot 2023-06-12 at 17 13 32](https://github.com/mlflow/mlflow/assets/22479356/e83343a8-5c6b-4999-92e5-f3cf7894c4ac)

![Screenshot 2023-06-12 at 17 13 41](https://github.com/mlflow/mlflow/assets/22479356/dd6a2bf8-7650-42b7-9874-a138f06c2327)
