### ISSUE TITLE
Support for selecting multiple runs in the UI via shift+click

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#871]
It's currently a little tricky to select multiple runs in the MLflow UI - it'd be nice to be able to use a shift+click UX to select multiple contiguous runs, e.g. mirroring gmail's UX. This may solve the pain point mentinoed in #870

**Comment by smurching** [comment]
This can be done by pulling out / calling `ExperimentViewUtil.getRowRenderMetadata` higher up in the view hierarchy (e.g. ExperimentView instead of the individual table views: ExperimentRunsTableCompactView and ExperimentRunsTableMultiColumnView). `getRowRenderMetadata` contains information (runs listed in sorted order, as well as a list of children IDs per run) needed to implement this feature and the feature requested in #870

**Comment by jakubczakon** [comment]
@smurching 
You could also have your MLflow experiment runs hosted on [neptune.ml][1] knowledge sharing hub. There is TensorBoard-style run comparison which you can easily use. 
Another benefit is that I can this [run comparison](https://ui.neptune.ml/jakub-czakon/santander/compare?shortId=%5B%22SAN1-179%22%2C%22SAN1-142%22%2C%22SAN1-141%22%2C%22SAN1-140%22%2C%22SAN1-124%22%2C%22SAN1-84%22%2C%22SAN1-59%22%2C%22SAN1-58%22%2C%22SAN1-57%22%2C%22SAN1-56%22%5D) with you with no problems. 

I know it sounds salesly but Neptune is actually free (for non-organizations) and I really feel that this integration brings a lot of value to the MLflow community.

Anyhow, I hope this helps.

Also if you are interested, I have just written a [blog post about it][3].

  [1]: https://neptune.ml/?utm_source=stack_exchange&utm_medium=forum&utm_campaign=neptune_is_free&utm_term=mlflow
  [2]: https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments
  [3]: https://medium.com/neptune-ml/collaborate-on-mlflow-experiments-in-neptune-fb4f8f84a995"

**Comment by smurching** [comment]
This is now supported in the UI (as of MLflow 1.6.0), closing it out
