### ISSUE TITLE
Restoring deleted experiment is not working 

### ISSUE THREAD

**Issue by Arsh4036** [mlflow/mlflow#878]
Below is the exception after using the restore_experiment() using tracking object:

MlflowException                           Traceback (most recent call last)
<command-1476332> in <module>()
      1 #tracking.get_experiment(21)
      2 
----> 3 tracking.restore_experiment(20)

/databricks/python/lib/python3.6/site-packages/mlflow/tracking/client.py in restore_experiment(self, experiment_id)
    116         :param experiment_id: The experiment ID returned from ``create_experiment``.
    117         """
--> 118         self.store.restore_experiment(experiment_id)
    119 
    120     def rename_experiment(self, experiment_id, new_name):

/databricks/python/lib/python3.6/site-packages/mlflow/store/rest_store.py in restore_experiment(self, experiment_id)
    106     def restore_experiment(self, experiment_id):
    107         req_body = message_to_json(RestoreExperiment(experiment_id=experiment_id))
--> 108         self._call_endpoint(RestoreExperiment, req_body)
    109 
    110     def rename_experiment(self, experiment_id, new_name):

**Comment by dbczumar** [comment]
@Arsh4036 Are you still facing this issue? Can you try to reproduce it on MLflow 1.1 and/or provide a more complete stacktrace? I am going to close the issue; please feel free to reopen it if you're still facing this problem.
