### ISSUE TITLE
[Question] Currently trying on databricks. Is openai flavour ready for Azure Openai?

### ISSUE THREAD

**Issue by andrelima666** [mlflow/mlflow#8807]
As I was testing the mlflow LLM on Azure OpenAI, I'm stuck on logging/loading model for the predict. 

I was seeting os.environ["MLFLOW_OPENAI_SECRET_SCOPE"] = "<scope-name>"  to the scope. 
It was giving me the error:
"OpenAI API key must be set in the OPENAI_API_KEY environment variable".
_Suggesting the variable setup from the yaml wasn't working._

After it, for further testing I also set the required OpenAI environment setting (changed the base as well for the AzureOpenAI uri and set the key).
I changed the model name to match the deployment name on Azure. giving me this error:
"mlflow.openai.api_request_parallel_processor: Request #0 failed with InvalidRequestError(message="Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>", param='engine', code=None, http_status=None, request_id=None)"

Also tested loading the secrets from the databricks scope and running the standalone chatCompletions from OpenAI and it's running fine. So I'm assuming the Azure OpenAI isn't currently supported on mlflow... Is my assumption correct or am I missing something?

**Comment by WeichenXu123** [comment]
Hi @andrelima666 

Could you provide your code to reproducing the issue ?

**Comment by dbczumar** [comment]
Hi @andrelima666, if you're loading the model in a notebook, the `OPENAI_API_KEY` environment variable must be set first before loading the model. Please let us know if this resolves the problem. Thank you for using MLflow!

**Comment by andrelima666** [comment]
> Hi @andrelima666
> 
> Could you provide your code to reproducing the issue ?

Hello @WeichenXu123, this is the snippet of code I've used (modified a bit on the secrets for security reasons):

`import openai
import os
GPT_ENGINE = <AzureOpenAI name deployment> 

openai.api_key = dbutils.secrets.get(scope=<AzureAISecretScopeName>, key="api_key")
openai.api_base =  dbutils.secrets.get(scope=<AzureAISecretScopeName>, key="api_url")
openai.api_type = 'azure'
openai.api_version = '2023-05-15'
os.environ["OPENAI_API_TYPE"] = 'azure'
os.environ["OPENAI_API_BASE"] = dbutils.secrets.get(scope=<AzureAISecretScopeName>, key="api_url")
os.environ["OPENAI_API_KEY"] = dbutils.secrets.get(scope=<AzureAISecretScopeName>, key="api_key")


os.environ["MLFLOW_OPENAI_SECRET_SCOPE"] = <AzureAISecretScopeName>

with mlflow.start_run():
    model_info = mlflow.openai.log_model(
        model=GPT_ENGINE,
        task=openai.ChatCompletion,
        messages=[
            {"role": "system", "content": <Tst_Content>},
            {"role": "user", "content": "{usr_content}"}],
        artifact_path="model",
    )

model = mlflow.pyfunc.load_model(model_info.model_uri)

#Goes all fine without any error until here.
#On doing the predict call it fails.

print(model.predict([{"usr_content": <usr_content_var>}]))`

When running the last line of code, this error is popping up:

> MlflowException: 1 tasks failed. See logs for details.

When looking into the Databricks Cluster logs, error is more meaningfull:

> WARNING mlflow.openai.api_request_parallel_processor: Request #0 failed with InvalidRequestError(message="Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>", param='engine', code=None, http_status=None, request_id=None)



After some testing, since AzureOpenAI uses 'engine' parameter to define the model and not the 'model' itself.
I added the 'engine' parameter with the same value:
`...
with mlflow.start_run():
    model_info = mlflow.openai.log_model(
        model=GPT_ENGINE,
        engine=GPT_ENGINE,
        task=openai.ChatCompletion,
        messages=[
            {"role": "system", "content": <Tst_Content>},
            {"role": "user", "content": "{usr_content}"}],
        artifact_path="model",
    )
...`

Now it is working fine as of now. If there is a more graceful way of doing this instead of repeating the value, I'm all ears. 
Thanks for the supp.

**Comment by WeichenXu123** [comment]
@dbczumar 

> if you're loading the model in a notebook, the OPENAI_API_KEY environment variable must be set first before loading the model.

Yes the user already do that.
According to the user testing result, there are another difference between openai and azure openai service:

azure openai requires using "engine" param key instead of "model" param key for the Openai model name.
