### ISSUE TITLE
[DOC-FIX] Misleading documentation for `sagemaker.push_model_to_sagemaker`

### ISSUE THREAD

**Issue by pdifranc** [mlflow/mlflow#8844]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/python_api/mlflow.sagemaker.html#mlflow.sagemaker.push_model_to_sagemaker

### Description of proposal (what needs changing)

The documentation describes, quote "Push an MLflow model to AWS SageMaker model registry."
This is confusing since it suggests that you can push an MLflow model to a SageMaker Model Registry, while in reality it is only creating a SageMaker Model, which is not going to the SageMaker Model Registry.

Please fix the docs to : "Push an MLflow model to Amazon SageMaker and create a SageMaker Model" or something along that line

**Comment by WeichenXu123** [comment]
Agreed! Feel free to file a PR !

**Comment by pdifranc** [comment]
PR linked - cheers
