### ISSUE TITLE
[BUG] Overwrite YAML utility routine does not respect preexisting file ACLs

### ISSUE THREAD

**Issue by flongford** [mlflow/mlflow#8878]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.4.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 13.4
- **Python version**: 3.8

### Describe the problem

The `mlflow.utils.file_utils.overwrite_yaml` function does not respect the ACLs of the preexisting YAML file, and instead will enforce elevated permissions on the updated file.

https://github.com/mlflow/mlflow/blob/152063e0b6fbadfbb2baecaf7d0ac7ca1b304b31/mlflow/utils/file_utils.py#L180-L190

This is due to the routine writing a new temporary file via `tempfile.mkstemp` with the updated data contents before move-replacing this to the prexisting file afterwards. 

As documented in the [description of `tempfile.mkstemp`](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp), new "secure" temporary files are always created with mode 0600. As a result, no matter what ACLs are set on the folder hash store root, only the creator of the file will be able to access and modify them. Users other than the creator will get a permission denied error if they attempt to access a file.

This is problematic in a scenario where multiple users are sharing the same file-backed tracking store, since the `meta.yaml` index files are updated via this function, for example, when renaming or deleting experiments:

https://github.com/mlflow/mlflow/blob/152063e0b6fbadfbb2baecaf7d0ac7ca1b304b31/mlflow/store/tracking/file_store.py#L453-L457

After being performed, these operations effectively prevent these experiments from being accessed by other user accounts on an NFS, since a `PermissionsError` exception will be raised when any `read_yaml` operation is performed on the updated `meta.yaml` file.

The preferred behavior would be for the file permissions of the preexisting YAML file to be carried over to the updated one, so that any existing ACLs of the backing file-system are respected.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

It's a bit challenging to reproduce the `PermissionsError` exception without setting up an NFS with multiple user accounts, but the change in `meta.yaml` file permissions for an updated experiment can be demonstrated using the code below:
```python
import os
from pathlib import Path

from mlflow.store.tracking.file_store import FileStore

# FIXME: change to a local directory path for testing
file_store = FileStore("file:///my/file/store")

# Create new experiment, along with associated meta.yaml file
experiment_id = file_store.create_experiment("foo")
meta_yaml_path = Path(file_store.root_directory) / experiment_id / file_store.META_DATA_FILE_NAME
print(f"Original {meta_yaml_path} permissions: ", oct(os.stat(meta_yaml_path).st_mode))

# Perform a task that modifies the meta.yaml file
file_store.rename_experiment(experiment_id, "bar")
print(f"Updated {meta_yaml_path} permissions: ", oct(os.stat(meta_yaml_path).st_mode))
```

### Stack trace

The code snippet above should produce something similar to the following output:
```
Original /my/file/store/1/meta.yaml permissions:  0o100644
Updated /my/file/store/1/meta.yaml permissions:  0o100600
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Thanks for reporting this issue ! Your analysis and proposed solution make perfect sense! Feel free to file PR !

**Comment by flongford** [comment]
> Thanks for reporting this issue ! Your analysis and proposed solution make perfect sense! Feel free to file PR !

No problem - FYI, the following PR targets this issue: #8899

**Comment by flongford** [comment]
Closing, since this is effectively a duplicate of https://github.com/mlflow/mlflow/issues/9789
