### ISSUE TITLE
clean and transparent store registration

### ISSUE THREAD

**Issue by maciejskorski** [mlflow/mlflow#8880]
These lines

https://github.com/mlflow/mlflow/blob/152063e0b6fbadfbb2baecaf7d0ac7ca1b304b31/mlflow/tracking/_tracking_service/utils.py#L194C1-L206C1

initialize a global variable holding important information about store endpoints. 

But the style is not good:
- should be moved to the top and marked clearly
- perhaps it would be beneficial to wrap them to be recycled per user request (re-register / re-initialize)

**Comment by WeichenXu123** [comment]
I reviewed your PR.
