### ISSUE TITLE
[BUG] Unable to `yarn build` on Windows

### ISSUE THREAD

**Issue by gabrielfu** [mlflow/mlflow#8890]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.4.1
- Tracking server: 2.4.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: 3.9.7
- **yarn version, if running the dev UI**: 3.5.0

### Describe the problem

Running `yarn build` for dev UI fails on Windows due to regex path matching in craco config:

https://github.com/mlflow/mlflow/blob/221d0f4a5c15f3a10dbc3b66c7a064c5b6091f2d/mlflow/server/js/craco.config.js#L73

We might need to change to something like `.match(/[\/\\]mini-css-extract-plugin[\/\\]/` ?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```shell
$ cd mlflow/server/js
$ yarn build
```

### Stack trace

```shell
craco:  *** Cannot find ESLint plugin (ESLintWebpackPlugin). ***
C:\Users\gabrielfu\PycharmProjects\mlflow\mlflow\server\js\craco.config.js:82
    throw new Error('Failed to fix CSS paths!');
          ^

Error: Failed to fix CSS paths!
    at configureIframeCSSPublicPaths (C:\Users\gabrielfu\PycharmProjects\mlflow\mlflow\server\js\craco.config.js:82:11)
    at configure (C:\Users\gabrielfu\PycharmProjects\mlflow\mlflow\server\js\craco.config.js:295:25)
    at giveTotalControl (C:\Users\gabrielfu\PycharmProjects\mlflow\mlflow\server\js\node_modules\@craco\craco\lib\features\webpack\merge-webpack-config.js:57:25)
    at mergeWebpackConfig (C:\Users\gabrielfu\PycharmProjects\mlflow\mlflow\server\js\node_modules\@craco\craco\lib\features\webpack\merge-webpack-config.js:106:38)
    at overrideWebpackProd (C:\Users\gabrielfu\PycharmProjects\mlflow\mlflow\server\js\node_modules\@craco\craco\lib\features\webpack\override.js:18:36)
    at C:\Users\gabrielfu\PycharmProjects\mlflow\mlflow\server\js\node_modules\@craco\craco\scripts\build.js:26:5
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@gabrielfu What is your node version?

**Comment by harupy** [comment]
This might be because windows uses `\` as a path separator.

**Comment by gabrielfu** [comment]
> This might be because windows uses `\` as a path separator.

Yes that's the reason. Do we change to something like 
```javascript
loader.match(/[\/\\]mini-css-extract-plugin[\/\\]/)
```
or 
```javascript
loader.match(new RegExp(`\\${path.sep}mini-css-extract-plugin\\${path.sep}`))
```
?
