### ISSUE TITLE
Unexpected data for param 'images'. Param recorded more than once

### ISSUE THREAD

**Issue by MohanKrishna-RC** [mlflow/mlflow#890]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by dstine** [comment]
@MohanKrishna-RC Parameters are write-once. They are not expected to change over the course of a run. Depending on what you are doing with “images”,  a metric may be better suited to handle your use case.
