### ISSUE TITLE
[BUG] input_example DataFrame type is always "split" no matter the format of the saved example

### ISSUE THREAD

**Issue by wamartin-aml** [mlflow/mlflow#8912]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.4.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows
- **Python version**: 3.8.16

### Describe the problem

When input_example is passed to a logged model and parsed as a dataframe, the info.pandas_orient is always set to `split` ([link](https://github.com/mlflow/mlflow/blob/master/mlflow/models/utils.py#L211)), regardless of the actual orient of the data. Since it looks like `index` and `columns` are now being deleted in default cases ([link](https://github.com/mlflow/mlflow/blob/master/mlflow/models/utils.py#L179)), calling the resulting dataframe `split` leads to errors when deserializing the json dataframe. The example below is based directly on the `input_example` example snippet from the transformers.log_model documentation.

My suggestion would be to default to `values` and use split specifically when `index` and `columns` are provided, but of course worth discussing.

### Tracking information

```shell

```

### Code to reproduce issue

```
from mlflow.models.signature import infer_signature
from mlflow.transformers import generate_signature_output
from transformers import pipeline
import mlflow
import pandas as pd

en_to_de = pipeline("translation_en_to_de")

data = "MLflow is great!"
output = generate_signature_output(en_to_de, data)
signature = infer_signature(data, output)

with mlflow.start_run() as run:
    mlflow.transformers.log_model(
        transformers_model=en_to_de,
        artifact_path="english_to_german_translator",
        signature=signature,
        input_example=data,
    )

# pulled directly from MLmodel to save space
example_info = {
		"type": "dataframe",
		"pandas_orient": "split"
	}

model_uri = f"runs:/{run.info.run_id}/english_to_german_translator"
with open(f"{model_uri}/input_example.json", 'r') as sample_input_file:
    if example_info['type'] == 'dataframe':
        sample_input = pd.read_json(
            sample_input_file,
            orient=example_info['pandas_orient'],
            dtype=False
        )

# KeyError: 'columns'
```

### Stack trace

```
Traceback (most recent call last):
  File "..\resources\mlflow_unit\get_formatted_example.py", line 28, in <module>
    sample_input = pd.read_json(
  File "C:\Users\wamartin\AppData\Local\Miniconda\4.7.12.1\envs\scoringscripttest\lib\site-packages\pandas\io\json\_json.py", line 784, in read_json
    return json_reader.read()
  File "C:\Users\wamartin\AppData\Local\Miniconda\4.7.12.1\envs\scoringscripttest\lib\site-packages\pandas\io\json\_json.py", line 975, in read
    obj = self._get_object_parser(self.data)
  File "C:\Users\wamartin\AppData\Local\Miniconda\4.7.12.1\envs\scoringscripttest\lib\site-packages\pandas\io\json\_json.py", line 1001, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "C:\Users\wamartin\AppData\Local\Miniconda\4.7.12.1\envs\scoringscripttest\lib\site-packages\pandas\io\json\_json.py", line 1134, in parse
    self._parse()
  File "C:\Users\wamartin\AppData\Local\Miniconda\4.7.12.1\envs\scoringscripttest\lib\site-packages\pandas\io\json\_json.py", line 1330, in _parse
    for col in decoded["columns"]
KeyError: 'columns'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
@wamartin-aml sounds like a good idea :) LMK when the PR is ready!
