### ISSUE TITLE
Create Helm chart for MLflow so it is easy to deploy to k8s (including as a sub-chart)

### ISSUE THREAD

**Issue by bali0019** [mlflow/mlflow#892]
After taking inspiration from Sid's presentation ( MLflow meetup on 02/12/2019) on dockerizing MLflow, I thought it would be really convenient for Kubernetes' users to refer to MLflow's standard Helm chart.

### Chart Details
- Write a standard Helm chart for MLflow to easily deploy to Kubernetes and/or be able to include it as a sub-chart within client's umbrella Helm chart (https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#complex-charts-with-many-dependencies) for a complex deployment (such as microservices orchestration). 
- Publish MLflow helm chart to official Helm repository (https://github.com/helm/charts)
- Add tests for Helm Chart testing to do "kick-the-tires" testing after a deployment. This test can train a model, load context and then do predictions (or prob). Example: https://github.com/helm/charts/blob/master/incubator/kafka/templates/tests/test_topic_create_consume_produce.yaml
- Will be a separate Helm Chart for Tracking, Projects and Models, but also publish an umbrella chart with all those three individual Helm Charts. That way, users can either choose to update one of the mlflow services or all three of them for their deployed environments

**Comment by SheldonXLD** [comment]
I agree with you

**Comment by metrofun** [comment]
Is anyone still working on it?

**Comment by bali0019** [comment]
@metrofun Not that I am aware of, but was going to look into this. Feel free to work on this ticket (if you do, let me know, so we aren't both working on the same thing)

**Comment by LeonardAukea** [comment]
Any progress on this ticket?

**Comment by afoltzm** [comment]
Hi everyone! :wave: :wave:  I'm working on a chart and a PR for this. Currently I have a Helm chart for MLFlow Tracking and have adapted the wine quality prediction ElasticNet Python example to run the training/test run in a pod, log the run to the tracking server created by the chart, and verify that the results are present in the tracking store. This is currently tested with two storage backends: the default (which is a PersistentVolume mounted on the pod's filesystem) and Postgres (which is either a pod created by the chart itself or an existing Postgres DB).

I will next work on replicating this test with the R version of the ElasticNet model example, then I'll create charts for MLFlow Models and MLFlow Experiments. Once those are tested, I can submit them as a PR for the official Helm charts.

Please let me know if you have any questions, or if you'd be interested in testing the chart on your cluster. It'd be very helpful to verify that it works in other deployments!

@bali0019 @metrofun

**Comment by LeonardAukea** [comment]
Awesome @afoltzm, we are willing to help/test your charts. We were planning to create our own since we couldn't find any existing ones.

**Comment by bali0019** [comment]
@afoltzm sweet, thanks for working on this. Let me know when you have a PR.

**Comment by whillas** [comment]
I'm building a Docker file for just `mlflow server` so my team can share experiment results. I don't think I'd want this mixed in with anything else... would i?

**Comment by afoltzm** [comment]
@bali0019 I had one question on the intended use case for helm with MLFlow Projects. At first glance, it seems like `kubectl run` is more appropriate for running individual MLFlow projects - they don't get "installed" but rather instead just run on the cluster with the appropriate resources and then terminate. I don't quite see how `helm install` makes sense here. Could you elaborate on what you meant when you suggested a Helm sub-chart for the Projects capability?

**Comment by AshuAkshi0708** [comment]
@afoltzm Do you have the helm charts to deploy mlflow? I am working on something like that. So it could be helpful if you can update it. Thanks.

**Comment by tedostrem** [comment]
I've made a helm chart and made it available in a public helm repo.

It can be installed using
```
helm repo add https://3loc.github.io/charts
helm install mlflow 3loc/mlflow
```
Source (Including Docker image):
https://github.com/3loc/charts/tree/master/mlflow

Docker image:
https://hub.docker.com/r/3loc/mlflow

**Comment by etheleon** [comment]
> I've made a helm chart and made it available in a public helm repo.
> 
> It can be installed using
> 
> ```
> helm repo add 3loc https://3loc.github.io/charts
> helm install mlflow 3loc/mlflow
> ```
> 
> Source (Including Docker image):
> https://github.com/3loc/charts/tree/master/mlflow
> 
> Docker image:
> https://hub.docker.com/r/3loc/mlflow

```
helm repo add 3loc https://3loc.github.io/charts
helm repo update
helm install mlflow 3loc/mlflow
```

**Comment by pravindahal** [comment]
For anyone still looking for this, here is a much more full featured implementation of the helm chart, except it seems to be slightly outdated, however, it can serve as a great starting point for someone willing to develop it further: https://github.com/larribas/helm-charts

**Comment by AndreaGiardini** [comment]
Can we keep this issue open?

I understand that there are alternatives out there that are maintained by individuals but I still believe it would be nice to have an official chart maintained by the MLflow community / project.

**Comment by BradLugo** [comment]
Is there an official Docker image for MLFlow Tracking? While working on a PR for this issue, I couldn't find one. It would be strange to provide an official Helm chart without an official Docker image, so, from that perspective, we should first resolve https://github.com/mlflow/mlflow/issues/826 or https://github.com/mlflow/mlflow/issues/3783. If we could get traction on https://github.com/mlflow/mlflow/pull/3709, or at least get feedback on why it can't be merged, that would be fantastic.

**Comment by sa-** [comment]
+ on reopening issue

**Comment by pbarker** [comment]
I take it this is to push people to the enterprise product? I'm in a bit of disbelief that this tool offers no means to deploy to the most used platforms. 

Can the MLflow team at least address this? Instead of just closing issues or leaving PRs open that aim to solve this problem. Is this an actual open source project or just a marketing stunt?
