### ISSUE TITLE
Nix as an alternative to conda

### ISSUE THREAD

**Issue by schlichtanders** [mlflow/mlflow#893]
The [nix package manager](https://nixos.org/nix/) is (one of) the standard cross-language package manager

it would be awesome to have support for it next to conda

The only issue about nix and mlflow I could find so far was https://github.com/mlflow/mlflow/issues/302#issuecomment-440454187 where the question is to have a generic docker setup. That would also include the possibility to use nix if I understood it correctly.

Nevertheless I think it would be beneficial to have extra support for nix itself. Just like conda has extra support.

**Comment by bali0019** [comment]
Great package manager. My 2cents on it, I think it is better to have an abstraction where users only provide their list of dependencies (readable yaml, for ex), and not care about what dockerfile uses to build mlflow container. It can be conda, nix or even npm. That way, we can keep mlflow's docker container lightweight, which is important for quickly load balancing mlflow in production setup

**Comment by schlichtanders** [comment]
dear mlflow developers
is there any take from you on supporting nix in the future or not?

**Comment by megatux** [comment]
> Great package manager. My 2cents on it, I think it is better to have an abstraction where users only provide their list of dependencies (readable yaml, for ex), and not care about what dockerfile uses to build mlflow container. It can be conda, nix or even npm. That way, we can keep mlflow's docker container lightweight, which is important for quickly load balancing mlflow in production setup

Googling for diff. of Conda vs Nix I just found this issue and also a tool to use nix with a yaml file: https://github.com/luispedro/nixml
Hope that helps. If not, sorry :)
