### ISSUE TITLE
[BUG]Attribute Error: mlflow has no attribute "list_experiments"

### ISSUE THREAD

**Issue by AnyigorTobias** [mlflow/mlflow#8941]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow version : version 2.4.1

### System information

- **Windows 11**:
- **Python version : python 3.9.16**:

### Describe the problem

I am using mlflow for my experiment tracking and model management.
I created a virtual environment with Conda and installed packages from the requirements files.  Mlflow 2.4.1 was installed in the process. Whenever I try to list experiments using this code "mlflow.list_experiments()" I get this error

 "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 mlflow.list_experiments()

AttributeError: module 'mlflow' has no attribute 'list_experiments'"

What could be the problem? 

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow

mlflow.list_experiments()
```

### Stack trace

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 mlflow.list_experiments()

AttributeError: module 'mlflow' has no attribute 'list_experiments'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Hi , `list_experiments`  API has been removed, you can use `search_experiments` instead.

**Comment by AnyigorTobias** [comment]
thank you
