### ISSUE TITLE
Enable more rules in ruff

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#8997]
We recently removed to ruff (https://github.com/mlflow/mlflow/pull/8873) to lint python files faster. We can enable more rules. This is a ticker for tracking that. To make PRs reviewable, we should enable rules one by one.

Rules that I think are useful:

- [x] https://beta.ruff.rs/docs/rules/redundant-open-modes/ (@EdAbati)
- [ ] https://beta.ruff.rs/docs/rules/#flake8-print-t20 (@Bncer)

Example PR:

https://github.com/mlflow/mlflow/pull/8958

**Comment by harupy** [comment]
@EdAbati Awesome, can we start with open-redudant-modes?

**Comment by Bncer** [comment]
Hi @harupy! I would like to take one of the task you assign.

**Comment by harupy** [comment]
@Bncer Great! Can you work on  https://beta.ruff.rs/docs/rules/#flake8-print-t20?

**Comment by Bncer** [comment]
> @Bncer Great! Can you work on https://beta.ruff.rs/docs/rules/#flake8-print-t20?

Yes

**Comment by harupy** [comment]
@Bncer Thanks, `flake8-print-t20` allows us to remove this line:

https://github.com/mlflow/mlflow/blob/10bb4e0f68a15d1fe0002bb4e97f90ca26928cbb/pylintrc#L86-L86

**Comment by EdAbati** [comment]
Hi @harupy , I have added the other 2 UP rules in PR #9007 :)

Happy to take another one. Which one should be done next? Maybe the `pylint` ones so we speed up linting tests?

**Comment by Bncer** [comment]
Dear @harupy!
Thank you for the opportunity!
I have discovered unexpected behavior of [flake8-print-t20](https://beta.ruff.rs/docs/rules/#flake8-print-t20) 
For example in add_num.py file:
```
import os
def add_numbers(a, b):
    print(f"The sum of {a} and {b} is {a + b}")
    return a + b
```
 on command  - `ruff check add_num.py`
I have following ruff status:
```
add_num.py:1:8: F401 [*] os imported but unused
add_num.py:4:5: T201 `print` found
Found 2 errors.
[*] 1 potentially fixable with the --fix option.
```
_only 1 potentially fixable_
and on command - `ruff --fix .`
```
add_num.py:3:5: T201 `print` found
Found 2 errors (1 fixed, 1 remaining).
```
So ruff auto fix F401, but leave our T201 rule.
**It seems doesn't have autofix of T201**

As for ruff checking the whole project mlflow:
we have 25 errors mainly in `dev` folder, where files used in `./.github/workflows/`
As a proposition we can include `# noqa: T201` for each line to ignore prints or add `dev` folder in exclude list of pyproject.toml

**Comment by harupy** [comment]
@Bncer Thanks for the investigation! Let's use `per-file-igbores` for files in `dev`.

**Comment by harupy** [comment]
@EdAbati Thanks! I'm selecting which rules to enable in each rule group. I'll open new issues oncd the selection is done.

**Comment by harupy** [comment]
I opened a few more good first issues. Let me know if they sound interest.
