### ISSUE TITLE
Replace `%` formatting with f-string

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9008]
## Steps

1. Copy the following script as `a.py` in the repository root.

```python
# a.py

"""
Automatically replace `%` formatting with f-string
"""
import ast
import sys
import re
import subprocess


def is_simple_expression(node: ast.AST) -> bool:
    """
    The following nodes are considered simple expressions:
    1. Name (e.g. a)
    2. Attribute consisting of only names (e.g. a.b.c)
    3. Call consisting of only names and without any any arguments (e.g. a.b.c())
    """
    if isinstance(node, ast.Name):
        return True
    elif isinstance(node, ast.Attribute):
        return is_simple_expression(node.value)
    elif isinstance(node, ast.Call):
        return (
            is_simple_expression(node.func)
            and len(node.keywords) == 0
            and all(is_simple_expression(arg) for arg in node.args)
        )
    elif isinstance(node, ast.Constant):
        return isinstance(node.value, (int, float))
    elif isinstance(node, ast.Tuple):
        return all(is_simple_expression(e) for e in node.elts)
    else:
        return False


PLACEHOLDER_PATTERN = re.compile(r"%[sd]")


class PercentFormatFinder(ast.NodeVisitor):
    def __init__(self):
        self.nodes = []

    def visit_BinOp(self, node: ast.BinOp):
        if (
            isinstance(node.op, ast.Mod)
            and isinstance(node.left, ast.Str)
            and is_simple_expression(node.right)
            and PLACEHOLDER_PATTERN.search(node.left.s)
            and node.lineno == node.end_lineno
        ):
            self.nodes.append(node)
        self.generic_visit(node)


def to_fstring(original: str, node: ast.BinOp) -> str:
    if isinstance(node.right, ast.Tuple):
        nodes = node.right.elts
    else:
        nodes = [node.right]
    left_orig = original[node.left.col_offset : node.left.end_col_offset]

    new = left_orig
    for n in nodes:
        right_orig = original[n.col_offset : n.end_col_offset]
        new = PLACEHOLDER_PATTERN.sub(f"{{{right_orig}}}", new, count=1)

    return original[: node.col_offset] + "f" + new + original[node.end_col_offset :]


def main():
    files = subprocess.check_output(["git", "ls-files", "**/*.py"]).decode().splitlines()
    counter = 0
    limit = 30

    for file in files:
        with open(file) as f:
            src = f.read()
            tree = ast.parse(src)
            visitor = PercentFormatFinder()
            visitor.visit(tree)

            if len(visitor.nodes) > 0:
                lines = src.split("\n")
                for node in visitor.nodes:
                    counter += 1
                    print(counter)
                    lines[node.lineno - 1] = to_fstring(lines[node.lineno - 1], node)

                    if counter == limit:
                        break

            else:
                continue

        with open(file, "w") as f:
            f.write("\n".join(lines))

        if counter == limit:
            break


if __name__ == "__main__":
    main()

```

2. Run `python a.py`
3. Verify the changes look correct.
4. File a PR. To make the PR reviewable, the script fixes up to 30 percent formattings.
5. Merge the PR and sync your local repo with upstream.
6. Repeat 2 ~ 5 until the script prints out nothing.

**Comment by ctagard** [comment]
Is this issue closed, or can I contribute?

**Comment by harupy** [comment]
@ctagard Thanks for the comment! No, it's not :)

**Comment by harupy** [comment]
@viktoriussuwandi Are you interested in working on this?

**Comment by Rukiyav** [comment]
hey is this issue open?
can i contribute

**Comment by Rukiyav** [comment]
iam actually beginner in contributing but Iam really interested to learn so can u please teach me
_

**Comment by Rukiyav** [comment]
thank you how can i know about it

**Comment by harupy** [comment]
1. Create a fork: https://docs.github.com/en/get-started/quickstart/fork-a-repo
2. I think codespace is easiest to start with: 
   - https://docs.github.com/en/codespaces/developing-in-codespaces/creating-a-codespace-for-a-repository
4. Once the codespace is ready, you can save the code in the issue description as `a.py` and run it, then file a PR.

Let me know if you have any questions.

**Comment by harupy** [comment]
Sounds good. Let me know if you want to need a quick call.

**Comment by Rukiyav** [comment]
@harupy what is %[sd] in PLACEHOLDER_PATTERN = re.compile(r"%[sd]")

**Comment by harupy** [comment]
@Rukiyav A regular expression maching `%s` or `%d`.

**Comment by Rukiyav** [comment]
do you want me to replace r"%[sd]" with f string

**Comment by harupy** [comment]
@Rukiyav All you need to do is just run the code.

**Comment by Rukiyav** [comment]
I run the code

**Comment by Rukiyav** [comment]
in codespace

**Comment by harupy** [comment]
Good, then you can file a PR.

**Comment by Rukiyav** [comment]
ok harupy

**Comment by Rukiyav** [comment]
should i file the pr from codespaces itself

**Comment by harupy** [comment]
yep

**Comment by Rukiyav** [comment]
when i try to create pull request form codespaces after running file it is There are no commits between the base master branch and the comparing ruk branch giving me this

**Comment by Rukiyav** [comment]
Git: bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) and this too

**Comment by harupy** [comment]
Did you make a commit with `git commit`?

**Comment by Rukiyav** [comment]
yes

**Comment by harupy** [comment]
then you can push it to the `ruk` branch.

**Comment by Rukiyav** [comment]
this command is working ,it is giving me message Everything up-to-date
but i cant able to file pr

**Comment by harupy** [comment]
then you can file a PR from GitHub UI

**Comment by harupy** [comment]
Did you really run `git commit`?

**Comment by harupy** [comment]
Run this command:

```
git add .
git commit -s -m "replace percent formatting"
git push origin HEAD
```

**Comment by Rukiyav** [comment]
ok

**Comment by Rukiyav** [comment]
> Did you really run `git commit`?

yes iam running it again

**Comment by harupy** [comment]
Can you set up this: https://docs.github.com/en/codespaces/developing-in-codespaces/working-collaboratively-in-a-codespace?

**Comment by harupy** [comment]
@Rukiyav If it's challenging to file a PR using a codespace, you can manually fix this line on GitHub UI and file a PR:

https://github.com/mlflow/mlflow/blob/b52e41732a9ee0863c686bf046adc1e0d44972c2/tests/spark/autologging/datasource/test_spark_datasource_autologging.py#L18

**Comment by Rukiyav** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?CD1A9151FE5E2386E296F5FA5B3E8D646B7F

**Comment by Rukiyav** [comment]
hey i finally filed pr

**Comment by harupy** [comment]
@Rukiyav you filed a PR in your fork, but you need to file a PR in this repository

**Comment by Rukiyav** [comment]
how to file pr in this repository from fork repository

**Comment by Rukiyav** [comment]
i merged it

**Comment by harupy** [comment]
@Rukiyav https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository should help

**Comment by Rukiyav** [comment]
they i think i filed pr for main repository

**Comment by Rukiyav** [comment]
> @Rukiyav https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository should help

thank you
