### ISSUE TITLE
[BUG]  Version Pinning bug is still present in 2.4.2 build. 

### ISSUE THREAD

**Issue by C-K-Loan** [mlflow/mlflow#9045]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.4.2

### System information

databricks/colab

### Describe the problem

![image](https://github.com/mlflow/mlflow/assets/18140070/801e2d97-68eb-49bf-9ef8-9d9fe1610b57)

Here is the bug regarding version pinning is described, fixed and merged to master https://github.com/mlflow/mlflow/pull/8687

[The bug is still present in 2.4.2 branch and was released again](https://github.com/mlflow/mlflow/blob/79c489f9c965f93b5885b434be834222de29cd63/mlflow/utils/environment.py#L467
)

and master is [here](https://github.com/mlflow/mlflow/blob/02f08b7ace76d1406ab86b700d9600f101397aef/mlflow/utils/environment.py#L468)

can you please make sure to merge this in the next release? 
You can use this colab notebook to reproduce the problem 
https://colab.research.google.com/drive/1m82RpDqZL9E2-iSqaRPEeHRNwI4uOMu_?usp=sharing

@harupy @serena-ruan 

### Code to reproduce issue

See https://colab.research.google.com/drive/1m82RpDqZL9E2-iSqaRPEeHRNwI4uOMu_?usp=sharing

### Stack trace

I just tried logging a model with latest mlflow and got this to my suprise 
It  should say `mlflow==2.4.2` but it's `mlflow==2.4` instead which will not install the latest mlflow. 
![image](https://github.com/mlflow/mlflow/assets/18140070/e8e6fc45-eda3-4aa0-989e-ae2cb7940f01)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@C-K-Loan We'll release 2.5 soon. This version includes #8687. We forgot to include it in 2.4.*.
