### ISSUE TITLE
[DOC-FIX]

### ISSUE THREAD

**Issue by jmmonteiro** [mlflow/mlflow#9052]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

https://mlflow.org/docs/latest/models.html

### Description of proposal (what needs changing)

The model serving examples provided in the [documentation](https://mlflow.org/docs/latest/models.html) do not hightligth the fact that if `mlflow models serve` is running inside a docker container, it requires  the `-h 0.0.0.0` argument to enable querying from the outside.

When I tried to query my model (served from inside a docker container), I kept getting the following error:
```curl: (56) Recv failure: Connection reset by peer```

I found a clue to what could be the problem [here](https://serverfault.com/questions/769578/curl-56-recv-failure-connection-reset-by-peer-when-hitting-docker-container), and later found that this is actually included in the `help` CLI prompt, under `mlflow models serve --help`:

```
-h, --host HOST        The network address to listen on (default:
                127.0.0.1). Use 0.0.0.0 to bind to all addresses if
                you want to access the tracking server from other
                machines.
```

While this is documented in the CLI, maybe it should be highlighted in the website documentation as well.

**Comment by serena-ruan** [comment]
Hi @jmmonteiro Feel free to raise a PR for highlighting this! Thank you!

**Comment by jmmonteiro** [comment]
Thanks @serena-ruan !
I've opened a PR here: https://github.com/mlflow/mlflow/pull/9067 but the workflows seem to be on hold.
Is there anything else that I need to do?

**Comment by serena-ruan** [comment]
Just approved the workflow! Let's see how it runs :)

**Comment by jmmonteiro** [comment]
@serena-ruan Thank you!

**Comment by serena-ruan** [comment]
Merged https://github.com/mlflow/mlflow/pull/9067 Thanks @jmmonteiro ! Will close the issue 😄
