### ISSUE TITLE
[FR] Support logging customized tags to runs created by autolog

### ISSUE THREAD

**Issue by thinkall** [mlflow/mlflow#9064]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

We'd like to add some customized tags to the runs created by autologging. For example, it would be great if autolog could support an additional parameter `tags` like `mlflow.autolog(tags={"custom_tag": "auto_created_run"})` and log the given tags to all runs created by autolog.

### Motivation

> #### What is the use case for this feature?
In hyperparameter tuning and AutoML scenarios, a lot of runs will be created. Currently, we couldn't add  customized tags to all the runs created by autolog easily.

> #### Why is this use case valuable to support for MLflow users in general?
Hyperparameter tuning and AutoML are broadly used by data science and machine learning communities, many of the engineers are also MLFlow users.

> #### Why is this use case valuable to support for your project(s) or organization?
By adding customized tags, we could organize the runs more flexibly.

> #### Why is it currently difficult to achieve this use case?
Currently, there is no such a parameter to pass into the autolog functions. We can start a run with tags and run training code in the context of the run, but we need to start hunderds of runs manually for each of the training code.

### Details

We'd like to add some customized tags to the runs created by autologging. For example, it would be great if autolog could support an additional parameter `tags` like below:
```
import mlflow
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor


mlflow.autolog(tags={"custom_tag": "auto_created_run"})

db = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

# Create and train models.
rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)
rf.fit(X_train, y_train)

# Create and train models.
rf1 = RandomForestRegressor(n_estimators=20, max_depth=6, max_features=3)
rf1.fit(X_train, y_train)
```
We want the tags be like:
![image](https://github.com/mlflow/mlflow/assets/3197038/8dc7b83c-4c93-4ecc-a0f9-4e6d1dab9867)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by thinkall** [comment]
@harupy @WeichenXu123 could you help check if this FR is needed? Or is there other workaround to log customized tags to runs created by autolog? Thanks.

**Comment by serena-ruan** [comment]
Hi @thinkall, thanks for raising the feature request! This is doable through passing tags into safe_patch function https://github.com/mlflow/mlflow/blob/6dde93758d42455cb90ef324407919ed67668b9b/mlflow/utils/autologging_utils/safety.py#L311-L315 Feel free to raise a PR and we'll review on it :)
