### ISSUE TITLE
Remove unused `_user`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9102]
This variable is not used and can be removed:

https://github.com/mlflow/mlflow/blob/92b76a5330392008968dfbbf3f462bb7f9a83c81/mlflow/server/auth/__init__.py#L422

**Comment by Ankit8848** [comment]
@harupy this whole should be removed ? I am a beginner so can u help me out ?

**Comment by harupy** [comment]
@Ankit8848 Yes, the entire line can be removed.

**Comment by Ankit8848** [comment]
@harupy Thank you , I am going to work on it .
