### ISSUE TITLE
Change Sorting in Artifact View

### ISSUE THREAD

**Issue by LeanderK** [mlflow/mlflow#911]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes, tracking code for my project
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: from pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2
- **Python version**: Python 3.6.8 :: Anaconda, Inc.
- **npm version (if running the dev UI): -
- **Exact command to reproduce**: mlflow ui --file-store .

### Describe the problem
I save samples every epoch with using a `sample [epoch].jpg` pattern, which i would guess is very common. The problem now is that the sorting in mlflow is not ideal.
It get's sorted as follows:
```
sample 1.jpg
sample 11.jpg
sample 111.jpg
sample 2.jpg
(...)
```
it would be better to sort them like this:
```
sample 1.jpg
sample 2.jpg
(..)
sample 11.jpg
sample 12.jpg
(..)
sample 111.jpg
sample 112.jpg
(...)
```
for example vscode does this.

**Comment by mparkhe** [comment]
Hi @LeanderK : This involves having a particular schema for artifact files like the one you described 

`OneOf('sample' | 'snapshot' | ...) [epoch count].OneOf(jpg, png, gif, txt, csv...)`

Most bigdata systems use leading zeros to keep files sorted. In your case, renaming sample files like so would help

```
sample-00001.jpg
sample-00002.jpg
...
sample-00011.jpg
sample-00111.jpg
sample 2.jpg
```

**Comment by LeanderK** [comment]
well, this is hard, because every time I save a sample I would have calculate the amount of leading zeros. I don't see this in other project either (for example: https://github.com/openai/glow). Isn't this just a problem in the sorting in the UI? Since it works in vscode, maybe it would be possible to just adapt their sorting-algorithm? I don't think one really needs a predefined format, just a sorting algorithm that respects blocks of numbers.

**Comment by LeanderK** [comment]
I don't think it's trivial, but since in machine learning & data-science one often has to save samples and results per iteration, I think it's worthwhile.

**Comment by ankitmathur-db** [comment]
A common workflow here is to use 12-15 leading 0s if you're worried about saving a ton of images. Supporting sort like this would involve understanding the schema with which these files are saved, and that's out of scope for MLFlow

**Comment by LeanderK** [comment]
that's really unfortunate! I think a simple parser for numerical values and sorting them accordingly would solve 99% of the use-cases. Like i said vscode (the editor) already does this sorting and it works!
