### ISSUE TITLE
[SETUP-BUG] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 34: invalid start byte

### ISSUE THREAD

**Issue by sandeshregmi** [mlflow/mlflow#9150]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
``wondows 10``
- **MLflow installed from (source or binary)**:
``conda install -c conda-forge mlflow``
- **MLflow version (run ``mlflow --version``)**:
``2.5.0``
- **Python version**:
``3.11.4``

### Code to reproduce issue

```bash
conda install -c conda-forge mlflow
```

### Describe the problem

I am able to install mlflow 2.5.0 but whenever try to import the package, first time it works but then if I close vscode window and reopen it, I get error that I have attached as a file.
[mlflow error.docx](https://github.com/mlflow/mlflow/files/12152530/mlflow.error.docx)

**Comment by harupy** [comment]
@sandeshregmi Thanks for reporting! I don't have Word. Can you paste the contents here?

**Comment by sandeshregmi** [comment]
@harupy sorry about that here is the content. ---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[1], line 1
----> 1 import mlflow

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\__init__.py:41
     38 warnings.filterwarnings("ignore", message="numpy.dtype size changed")
     39 warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
---> 41 from mlflow import projects  # pylint: disable=unused-import
     42 from mlflow import tracking  # pylint: disable=unused-import
     43 from mlflow import models  # pylint: disable=unused-import

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\projects\__init__.py:9
      6 import os
      7 import logging
----> 9 import mlflow.projects.databricks
     10 from mlflow import tracking
     11 from mlflow.entities import RunStatus

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\projects\databricks.py:11
      8 import posixpath
      9 import re
---> 11 from mlflow import tracking
     12 from mlflow.entities import RunStatus
     13 from mlflow.exceptions import MlflowException

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\tracking\__init__.py:8
      1 """
      2 The ``mlflow.tracking`` module provides a Python CRUD interface to MLflow experiments
      3 and runs. This is a lower level API that directly translates to MLflow
      4 `REST API <../rest-api.html>`_ calls.
      5 For a higher level API for managing an "active run", use the :py:mod:`mlflow` module.
      6 """
----> 8 from mlflow.tracking.client import MlflowClient
      9 from mlflow.tracking._tracking_service.utils import (
     10     set_tracking_uri,
     11     get_tracking_uri,
     12     is_tracking_uri_set,
     13     _get_store,
     14 )
     15 from mlflow.tracking._model_registry.utils import (
     16     set_registry_uri,
     17     get_registry_uri,
     18 )

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\tracking\client.py:28
     23 from mlflow.store.model_registry import (
     24     SEARCH_REGISTERED_MODEL_MAX_RESULTS_DEFAULT,
     25     SEARCH_MODEL_VERSION_MAX_RESULTS_DEFAULT,
     26 )
     27 from mlflow.store.tracking import SEARCH_MAX_RESULTS_DEFAULT
---> 28 from mlflow.tracking._model_registry.client import ModelRegistryClient
     29 from mlflow.tracking._model_registry import utils as registry_utils
     30 from mlflow.tracking._model_registry import DEFAULT_AWAIT_MAX_SLEEP_SECONDS

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\tracking\_model_registry\client.py:18
     16 from mlflow.entities.model_registry import RegisteredModelTag, ModelVersionTag
     17 from mlflow.entities.model_registry.model_version_status import ModelVersionStatus
---> 18 from mlflow.tracking._model_registry import utils, DEFAULT_AWAIT_MAX_SLEEP_SECONDS
     19 from mlflow.utils.arguments_utils import _get_arg_names
     21 _logger = logging.getLogger(__name__)

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\tracking\_model_registry\utils.py:11
      9 from mlflow.store._unity_catalog.registry.rest_store import UcModelRegistryStore
     10 from mlflow.tracking._model_registry.registry import ModelRegistryStoreRegistry
---> 11 from mlflow.tracking._tracking_service.utils import (
     12     _resolve_tracking_uri,
     13     get_tracking_uri,
     14 )
     15 from mlflow.utils import rest_utils
     16 from mlflow.utils.databricks_utils import get_databricks_host_creds

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\tracking\_tracking_service\utils.py:210
    205         _tracking_store_registry.register(scheme, _get_sqlalchemy_store)
    207     _tracking_store_registry.register_entrypoints()
--> 210 _register_tracking_stores()
    213 def _get_store(store_uri=None, artifact_uri=None):
    214     return _tracking_store_registry.get_store(store_uri, artifact_uri)

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\tracking\_tracking_service\utils.py:207, in _register_tracking_stores()
    204 for scheme in DATABASE_ENGINES:
    205     _tracking_store_registry.register(scheme, _get_sqlalchemy_store)
--> 207 _tracking_store_registry.register_entrypoints()

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\mlflow\tracking\registry.py:52, in StoreRegistry.register_entrypoints(self)
     50 def register_entrypoints(self):
     51     """Register tracking stores provided by other packages"""
---> 52     for entrypoint in entrypoints.get_group_all(self.group_name):
     53         try:
     54             self.register(entrypoint.name, entrypoint.load())

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\entrypoints.py:237, in get_group_all(group, path)
    232 """Find all entry points in a group.
    233 
    234 Returns a list of :class:`EntryPoint` objects.
    235 """
    236 result = []
--> 237 for config, distro in iter_files_distros(path=path):
    238     if group in config:
    239         for name, epstr in config[group].items():

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\site-packages\entrypoints.py:203, in iter_files_distros(path, repeated_distro)
    200 distro_names_seen.add(distro.name)
    202 cp = CaseSensitiveConfigParser(delimiters=('=',))
--> 203 cp.read([path])
    204 yield cp, distro

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\configparser.py:713, in RawConfigParser.read(self, filenames, encoding)
    711 try:
    712     with open(filename, encoding=encoding) as fp:
--> 713         self._read(fp, filename)
    714 except OSError:
    715     continue

File c:\Users\sregmi444\Anaconda3\envs\ml2\Lib\configparser.py:1036, in RawConfigParser._read(self, fp, fpname)
   1034 indent_level = 0
   1035 e = None                              # None, or an exception
-> 1036 for lineno, line in enumerate(fp, start=1):
   1037     comment_start = sys.maxsize
   1038     # strip inline comments

File :322, in decode(self, input, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 34: invalid start byte

**Comment by harupy** [comment]
@sandeshregmi Thanks! Can you also paste the code here?

**Comment by sandeshregmi** [comment]
@harupy strangely, the error I shared came from `import mlflow` command.

**Comment by harupy** [comment]
@sandeshregmi Can you constantly reproduce the issue with `c:\Users\sregmi444\Anaconda3\envs\ml2`?

**Comment by sandeshregmi** [comment]
Ok sounds good. Give me some time I will post here.

**Comment by sandeshregmi** [comment]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[4], line 1
----> 1 import mlflow

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\__init__.py:41](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/__init__.py:41)
     38 warnings.filterwarnings("ignore", message="numpy.dtype size changed")
     39 warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
---> 41 from mlflow import projects  # pylint: disable=unused-import
     42 from mlflow import tracking  # pylint: disable=unused-import
     43 from mlflow import models  # pylint: disable=unused-import

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\projects\__init__.py:9](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/projects/__init__.py:9)
      6 import os
      7 import logging
----> 9 import mlflow.projects.databricks
     10 from mlflow import tracking
     11 from mlflow.entities import RunStatus

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\projects\databricks.py:12](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/projects/databricks.py:12)
      9 import posixpath
     10 import re
---> 12 from mlflow import tracking
     13 from mlflow.entities import RunStatus
     14 from mlflow.exceptions import MlflowException

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\tracking\__init__.py:8](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/tracking/__init__.py:8)
      1 """
      2 The ``mlflow.tracking`` module provides a Python CRUD interface to MLflow experiments
      3 and runs. This is a lower level API that directly translates to MLflow
      4 `REST API <../rest-api.html>`_ calls.
      5 For a higher level API for managing an "active run", use the :py:mod:`mlflow` module.
      6 """
----> 8 from mlflow.tracking.client import MlflowClient
      9 from mlflow.tracking._tracking_service.utils import (
     10     set_tracking_uri,
     11     get_tracking_uri,
   (...)
     14     _TRACKING_URI_ENV_VAR,
     15 )
     16 from mlflow.tracking._model_registry.utils import (
     17     set_registry_uri,
     18     get_registry_uri,
     19 )

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\tracking\client.py:27](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/tracking/client.py:27)
     22 from mlflow.store.model_registry import (
     23     SEARCH_REGISTERED_MODEL_MAX_RESULTS_DEFAULT,
     24     SEARCH_MODEL_VERSION_MAX_RESULTS_DEFAULT,
     25 )
     26 from mlflow.store.tracking import SEARCH_MAX_RESULTS_DEFAULT
---> 27 from mlflow.tracking._model_registry.client import ModelRegistryClient
     28 from mlflow.tracking._model_registry import utils as registry_utils
     29 from mlflow.tracking._model_registry import DEFAULT_AWAIT_MAX_SLEEP_SECONDS

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\tracking\_model_registry\client.py:18](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/tracking/_model_registry/client.py:18)
     16 from mlflow.entities.model_registry import RegisteredModelTag, ModelVersionTag
     17 from mlflow.entities.model_registry.model_version_status import ModelVersionStatus
---> 18 from mlflow.tracking._model_registry import utils, DEFAULT_AWAIT_MAX_SLEEP_SECONDS
     21 _logger = logging.getLogger(__name__)
     23 AWAIT_MODEL_VERSION_CREATE_SLEEP_DURATION_SECONDS = 3

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\tracking\_model_registry\utils.py:10](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/tracking/_model_registry/utils.py:10)
      8 from mlflow.store._unity_catalog.registry.rest_store import UcModelRegistryStore
      9 from mlflow.tracking._model_registry.registry import ModelRegistryStoreRegistry
---> 10 from mlflow.tracking._tracking_service.utils import (
     11     _TRACKING_USERNAME_ENV_VAR,
     12     _TRACKING_PASSWORD_ENV_VAR,
     13     _TRACKING_TOKEN_ENV_VAR,
     14     _TRACKING_INSECURE_TLS_ENV_VAR,
     15     _TRACKING_CLIENT_CERT_PATH_ENV_VAR,
     16     _TRACKING_SERVER_CERT_PATH_ENV_VAR,
     17     _resolve_tracking_uri,
     18     get_tracking_uri,
     19 )
     20 from mlflow.utils import env, rest_utils
     21 from mlflow.utils.databricks_utils import get_databricks_host_creds

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\tracking\_tracking_service\utils.py:213](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/tracking/_tracking_service/utils.py:213)
    210 for scheme in DATABASE_ENGINES:
    211     _tracking_store_registry.register(scheme, _get_sqlalchemy_store)
--> 213 _tracking_store_registry.register_entrypoints()
    216 def _get_store(store_uri=None, artifact_uri=None):
    217     return _tracking_store_registry.get_store(store_uri, artifact_uri)

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\mlflow\tracking\registry.py:52](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/mlflow/tracking/registry.py:52), in StoreRegistry.register_entrypoints(self)
     50 def register_entrypoints(self):
     51     """Register tracking stores provided by other packages"""
---> 52     for entrypoint in entrypoints.get_group_all(self.group_name):
     53         try:
     54             self.register(entrypoint.name, entrypoint.load())

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\entrypoints.py:237](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/entrypoints.py:237), in get_group_all(group, path)
    232 """Find all entry points in a group.
    233 
    234 Returns a list of :class:`EntryPoint` objects.
    235 """
    236 result = []
--> 237 for config, distro in iter_files_distros(path=path):
    238     if group in config:
    239         for name, epstr in config[group].items():

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\entrypoints.py:203](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/site-packages/entrypoints.py:203), in iter_files_distros(path, repeated_distro)
    200 distro_names_seen.add(distro.name)
    202 cp = CaseSensitiveConfigParser(delimiters=('=',))
--> 203 cp.read([path])
    204 yield cp, distro

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\configparser.py:713](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/configparser.py:713), in RawConfigParser.read(self, filenames, encoding)
    711 try:
    712     with open(filename, encoding=encoding) as fp:
--> 713         self._read(fp, filename)
    714 except OSError:
    715     continue

File [c:\Users\sregmi444\Anaconda3\envs\ml\Lib\configparser.py:1036](file:///C:/Users/sregmi444/Anaconda3/envs/ml/Lib/configparser.py:1036), in RawConfigParser._read(self, fp, fpname)
   1034 indent_level = 0
   1035 e = None                              # None, or an exception
-> 1036 for lineno, line in enumerate(fp, start=1):
   1037     comment_start = sys.maxsize
   1038     # strip inline comments

File :322, in decode(self, input, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 304: invalid continuation byte

**Comment by harupy** [comment]
@sandeshregmi you can insert `print(path)` before `c:\Users\sregmi444\Anaconda3\envs\ml\Lib\site-packages\entrypoints.py:203` to see the throwing the error. I thin this file contains a character that can't be decoded in utf-8.

**Comment by harupy** [comment]
@sandeshregmi Can you reproduce this error in mlflow < 2.4?

**Comment by harupy** [comment]
Related: https://stackoverflow.com/questions/30996289/utf8-codec-cant-decode-byte-0xf3

**Comment by harupy** [comment]
I don't think this is an MLflow's issue.
