### ISSUE TITLE
[FR] mlflow recipes should indicate status of last step on failure

### ISSUE THREAD

**Issue by donour** [mlflow/mlflow#9170]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

The recipe code currently only outputs the step name and stack trace. It should also include the status of the last step to indicate whether the framework things that the step is still running or if some other condition has happened.

### Motivation

> #### What is the use case for this feature?

Debugging

> #### Why is this use case valuable to support for MLflow users in general?

Better error messages for all recipe users

> #### Why is this use case valuable to support for your project(s) or organization?

This change is already used internally at my org.

> #### Why is it currently difficult to achieve this use case?

n/a

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
@sunishsheth2009 what are your thoughts here? Seems like a good idea to me.
