### ISSUE TITLE
[FR] Deploy model to SageMaker endpoint that output text/csv ContentType

### ISSUE THREAD

**Issue by Madman-2020** [mlflow/mlflow#9172]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

I'm trying to deploy a model of `python_function` flavor to a SageMaker endpoint. 
This SageMaker endpoint will be used to serve AWS Athena UDF calls, which only accept `text/csv` content type for IO.
However, it seems it's hard coded in the `python_function` flavor that output predictions are in json format [here](https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/scoring_server/__init__.py#L336).
And it's impossible to configure [serializatier or deserializer](https://sagemaker.readthedocs.io/en/stable/v2.html#serializer-and-deserializer-classes)
Can we add `text/csv` for model predictions as it did for input [here](https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/scoring_server/__init__.py#L298-L304)?
Or, is there a better way to solve this problem? 
Thanks.

### Motivation

> #### What is the use case for this feature?
Deploy a model of `python_function` flavor to a SageMaker endpoint to serve AWS Athena UDF calls, which must accept and return `text/csv`.

> #### Why is this use case valuable to support for MLflow users in general?
Models deployed to SageMaker endpoint can be used for Athena UDF.

> #### Why is this use case valuable to support for your project(s) or organization?
With the help of KedroPipelineModel and kedro-mlops, we can create python models from kedro pipeline and use them as an AWS Athena UDF once they are deployed to SageMaker endpoint. 

> #### Why is it currently difficult to achieve this use case?
It's hard coded in python_function flavor and mlflow deploy ignored serializer and deserializer when it comes to SageMaker endpoint.

### Details

I'm trying to deploy a model of `python_function` flavor to a SageMaker endpoint. 
This SageMaker endpoint will be used to serve AWS Athena UDF calls, which only accept `text/csv` content type for IO.
However, it seems it's hard coded in the `python_function` flavor that output predictions are in json format [here](https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/scoring_server/__init__.py#L336).
And it's impossible to configure [serializatier or deserializer](https://sagemaker.readthedocs.io/en/stable/v2.html#serializer-and-deserializer-classes)
Can we add `text/csv` for model predictions as it did for input [here](https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/scoring_server/__init__.py#L298-L304)?
Or, is there a better way to solve this problem? 

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
I'm not entirely sure if this is something that is within the scope of MLflow to solve. While we did add support for passing string inputs and iterable string inputs to pyfunc to support LLM usage, modifying the return from the MLflow server to return scalar strings doesn't seem particularly useful. I think you'd want to have some middleware interface with your downstream consumption if you're needing to extract the JSON values for use in another system. 
I would recommend building that middleware service that can act as a proxy between the serving output and the subsequent forwarding to Athena in order to achieve this. Perhaps AWS has a solution involving using lambda to achieve this as a pre-processing step to an Athena query? 
I'd recommend reaching out to the sagemaker community to see if anyone has built anything like this before (I'm sure they have). 
We don't have any plans to support modifying the return values from the MLflow server to support any non-REST-compliant return values at this time.
