### ISSUE TITLE
[SETUP-BUG] ML flow browser error message: "something went wrong"

### ISSUE THREAD

**Issue by RFT86** [mlflow/mlflow#9176]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Macbook ventura 13.4.1
- **MLflow installed from (source or binary)**:Jupterlab 3.5.3
- **MLflow version (run ``mlflow --version``)**:2.5.0

### Code to reproduce issue

NA

### Describe the problem

New user to mlflow. When I run my mlflow browser, the Ui wasn't there. The error mentioned below. I think I might have deleted my directory folder. how do you check the artifact location ? 
- I tried reinstalling and installing mlflow again. It doesn't work
- I tried adding back the folder in the directory. it's don't work. maybe my location is wrong too. 
- Uninstalled and installed anaconda, the mlflow browser returned the below error. 

Your advice is much appreciated. Thanks!

'''
Something went wrong

If this error persists, please report an issue [here](https://github.com/mlflow/mlflow/issues).
'''

### Other info / logs

NA

**Comment by BenWilson2** [comment]
It might be worthwhile to go through the tutorial here: https://www.mlflow.org/docs/latest/quickstart.html and make sure that you're up to speed on all of the getting started elements for MLflow :)

**Comment by RFT86** [comment]
Hi Ben, I just read through the tutorial. I don't find my resolution for my error. when I load my ml flow on local host, this shows:
![error](https://github.com/mlflow/mlflow/assets/141021734/27aeaaff-2e32-4834-b75d-b114a93aee11)

**Comment by BenWilson2** [comment]
Did you follow the guide verbatim and were able to reproduce what the getting started guide has defined? It could be helpful to do that to get things up and running and verify that there aren't any environmental considerations on your system that are exhibiting issues.

**Comment by RFT86** [comment]
I did go went through the installation tutorial. However, I am still in the same localhost:500 error state. I am able to log mlflow tracking logs using Jupiterlab successfully(with the log files and all). I tried mlflow on another computer B and the localhost is working fine. 

I recalled that initially when I install mlflow in my Mac computer, the localhost is fine until I delete some logs.  I compare this computer and my other computer B(Localhost working) to placed back the files back same location.  it doesn't work. 

Is there any way I can uninstall mlflow together with its relevant files and do a clean mlflow installation. 
Tried in terminal # %pip install -U mlflow and pip install mlflow . It does not make a clean installation. 

Appreciate your help on this. Thanks

**Comment by harupy** [comment]
@RFT86 Can you open the dev console on your browser? That should tell us what went wrong.

**Comment by RFT86** [comment]
@harupy  I am still relatively new. how do you launch the dev console on browser ? I didn't find any answers online or chatgpt. 

I did a pkill -f gunicorn followed by a mlflow server on Mac terminal. No error message. ml server booted up and listening at localhost.

**Comment by harupy** [comment]
You can see https://developer.chrome.com/docs/devtools/open/

**Comment by RFT86** [comment]
Hi Harutaka,

here is my screenshot of my dev console.

Regards

**Comment by harupy** [comment]
@RFT86 where is the screenshot?

**Comment by RFT86** [comment]
[](url)
![Error3](https://github.com/mlflow/mlflow/assets/141021734/7e518a26-e00d-4fa5-81a3-849e93ae13b7)
![Error2](https://github.com/mlflow/mlflow/assets/141021734/8648d1d4-fecc-47ce-bfc2-fad387ccc47d)
![Error1](https://github.com/mlflow/mlflow/assets/141021734/bf69a820-0fc4-44b3-a5d2-abb326378614)

@harupy here it is, thanks.

**Comment by harupy** [comment]
Thanks! Any log message in the terminal `mlflow server` is running on?

**Comment by RFT86** [comment]
Yes. No error. exactly the same message as per your example

**Comment by harupy** [comment]
Strange

**Comment by harupy** [comment]
Can you move to an empty directory and run `mlflow server` there?

**Comment by RFT86** [comment]
hmmm... may I know.. what is the typical file path linking to localhostbrowser and the standard files ? perhaps I can try to paste in the relevant files. 

how do move to a empty directory ? cd ? let me know the steps. thanks.

**Comment by harupy** [comment]
Yes cd.

**Comment by RFT86** [comment]
oh after mkdir and cd. it works now. what actually happen?

**Comment by harupy** [comment]
Are you really sure you don't see any error messages?

**Comment by RFT86** [comment]
yes. woo! it work. I did the server in terminal no errors, the localhost is loaded. how do you linked up my previously ran logs in the UI ?

**Comment by harupy** [comment]
Did you run `mlflow server` in the directory where you encountered the error?

**Comment by RFT86** [comment]
I did a following:
cd /user/xxx/downloads
mflow server
launched local host in safari myself. 

# I don't seem to spot any errors except that the local host did not pick up any of my logs. 

Let me know if I am doing this correctly.

**Comment by harupy** [comment]
what is your OS?

**Comment by harupy** [comment]
Is `/user/xxx/downloads` the directory where you encountered the error?

**Comment by RFT86** [comment]
Not quite. I am unsure where the previous localhost is drawing its info from which dir or path. It should be the initial standard installation location. Separately, When I run my codes I direct to /user/xxx/downloads

**Comment by harupy** [comment]
I see. We can't debug if you can't reproduce.

**Comment by harupy** [comment]
@RFT86 Feel free to reopen the issue once you find how to reproduce the issue.
