### ISSUE TITLE
Previously saved ONNX model not loading with MLFlow 2.5.0

### ISSUE THREAD

**Issue by wingdagger** [mlflow/mlflow#9185]
Using the MLFlow 2.5 API, I am trying to load an ONNX model that was saved with an earlier version of MLFlow (2.1.x),  That MLmodel file created by the previous version of MLFlow did not have the "onnx_session_options" key for the "onnx" flavor.  The current code assumes it is there and check after loading it whether the value is None or not.  However, it should check if the key exists before trying to access the key "onnx_session_options". 

https://github.com/mlflow/mlflow/blob/a1f29dcbe6d415d73e59d8060876b2c2e9eb5b87/mlflow/onnx.py#L260

       options = model_meta.flavors.get(FLAVOR_NAME)["onnx_session_options"]
E       KeyError: 'onnx_session_options'

../../../.local/share/virtualenvs/aix_inferencing-1yp6t7Dw/lib/python3.10/site-packages/mlflow/onnx.py:259: KeyError

**Comment by serena-ruan** [comment]
Fixed with #9187
