### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'datasets_modules'

### ISSUE THREAD

**Issue by PhucLee2605** [mlflow/mlflow#9204]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow version 2.4.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**: Ubuntu 20.04
- **Python version**: 3.9.12

### Describe the problem

I am facing this issue when trying to load model from S3 with `mlflow.pytorch.load_model()` or running `mellow models serve`.
These models are logged atomatically with `mlflow.autolog()`.
It purpose to be loaded and I can run inference with this model.

### Tracking information

```shell
No bugs in tracking
```

### Code to reproduce issue

```
import numpy as np
import uvicorn
import re
import mlflow
from fastapi import FastAPI
from pydantic import BaseModel
import config_with_yaml as config
from transformers import AutoModelForSequenceClassification, AutoTokenizer

model_uri = "s3://path/to/model"
model = mlflow.pytorch.load_model(model_uri)
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/ubuntu/ai-call-classification/src/serve.py", line 25, in <module>
    model = mlflow.pytorch.load_model(model_uri)
  File "/home/ubuntu/.conda/envs/log/lib/python3.9/site-packages/mlflow/pytorch/__init__.py", line 743, in load_model
    return _load_model(path=torch_model_artifacts_path, **kwargs)
  File "/home/ubuntu/.conda/envs/log/lib/python3.9/site-packages/mlflow/pytorch/__init__.py", line 658, in _load_model
    return torch.load(model_path, **kwargs)
  File "/home/ubuntu/.conda/envs/log/lib/python3.9/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.conda/envs/log/lib/python3.9/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/ubuntu/.conda/envs/log/lib/python3.9/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'datasets_modules'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [X] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@PhucLee2605 What is `datasets_modules`?

**Comment by PhucLee2605** [comment]
> 
That is what I am wondering about. Searched for it but no information! I don't have it also

**Comment by harupy** [comment]
https://github.com/huggingface/datasets/blob/ef17d9fd6c648bb41d43ba301c3de4d7b6f833d8/src/datasets/config.py#L208

```
MODULE_NAME_FOR_DYNAMIC_MODULES = "datasets_modules"
```

Does it come from `datasets`?

**Comment by PhucLee2605** [comment]
> https://github.com/huggingface/datasets/blob/ef17d9fd6c648bb41d43ba301c3de4d7b6f833d8/src/datasets/config.py#L208
> 
> ```
> MODULE_NAME_FOR_DYNAMIC_MODULES = "datasets_modules"
> ```
> 
> Does it come from `datasets`?

I have installed datasets 


```
# packages in environment at /home/ubuntu/.conda/envs/log:
#
# Name                    Version                   Build  Channel
datasets                  2.13.1                   pypi_0    pypi
```

**Comment by PhucLee2605** [comment]
@harupy This is my requirements in case you need to reproduce the env

```
scipy 
transformers 
torchtext>=0.9 
ipython[notebook]>=8.0.0, <8.12.0 
setuptools==67.4.0 
# torchmetrics>=0.7, <0.12 
scikit-learn 
pytorch-lightning==1.9.5
datasets 
torch>=1.8.1, <2.0.0
mlflow==2.4.2
boto3
pyodbc
uvicorn
fastapi
config-with-yaml
```

**Comment by harupy** [comment]
@PhucLee2605 Thanks! Can you share your code that logs the model?

**Comment by harupy** [comment]
I found this code:

https://github.com/huggingface/datasets/blob/ef17d9fd6c648bb41d43ba301c3de4d7b6f833d8/src/datasets/load.py#L92C1-L107C32

```python
def init_dynamic_modules(
    name: str = config.MODULE_NAME_FOR_DYNAMIC_MODULES, hf_modules_cache: Optional[Union[Path, str]] = None
):
    """
    Create a module with name `name` in which you can add dynamic modules
    such as metrics or datasets. The module can be imported using its name.
    The module is created in the HF_MODULE_CACHE directory by default (~/.cache/huggingface/modules) but it can
    be overridden by specifying a path to another directory in `hf_modules_cache`.
    """
    hf_modules_cache = init_hf_modules(hf_modules_cache)
    dynamic_modules_path = os.path.join(hf_modules_cache, name)
    os.makedirs(dynamic_modules_path, exist_ok=True)
    if not os.path.exists(os.path.join(dynamic_modules_path, "__init__.py")):
        with open(os.path.join(dynamic_modules_path, "__init__.py"), "w"):
            pass
    return dynamic_modules_path
```

It looks like huggingface creates module and stores it in `~/.cache/huggingface/modules`?


Let's say you have two machines A and B. You train and log a model on A, and download it on B. I think A has `datasets_modules`, but B doesn't.

**Comment by PhucLee2605** [comment]
> I found this code:
> 
> https://github.com/huggingface/datasets/blob/ef17d9fd6c648bb41d43ba301c3de4d7b6f833d8/src/datasets/load.py#L92C1-L107C32
> 
> ```python
> def init_dynamic_modules(
>     name: str = config.MODULE_NAME_FOR_DYNAMIC_MODULES, hf_modules_cache: Optional[Union[Path, str]] = None
> ):
>     """
>     Create a module with name `name` in which you can add dynamic modules
>     such as metrics or datasets. The module can be imported using its name.
>     The module is created in the HF_MODULE_CACHE directory by default (~/.cache/huggingface/modules) but it can
>     be overridden by specifying a path to another directory in `hf_modules_cache`.
>     """
>     hf_modules_cache = init_hf_modules(hf_modules_cache)
>     dynamic_modules_path = os.path.join(hf_modules_cache, name)
>     os.makedirs(dynamic_modules_path, exist_ok=True)
>     if not os.path.exists(os.path.join(dynamic_modules_path, "__init__.py")):
>         with open(os.path.join(dynamic_modules_path, "__init__.py"), "w"):
>             pass
>     return dynamic_modules_path
> ```
> 
> It looks like huggingface creates module and stores it in `~/.cache/huggingface/modules`?
> 
> Let's say you have two machines A and B. You train and log a model on A, and download it on B. I think A has `datasets_modules`, but B doesn't.

Hmm till now, this is the best answer I got. But is this a bug? I mean `mlflow` supports logging artifacts to remote storages and also loading from them. I saw blame, and looks like this snippet has been there for years, how can this bug appear for the first time? (I have searched in issues and found no clues about this issue)
![image](https://github.com/mlflow/mlflow/assets/88246407/17f43b55-6f04-4b88-9e43-88d062f06147)

**Comment by harupy** [comment]
I don't think this is a bug. Not sure when or how this function is called though. MLflow logs artifacts but doesn't log modules or packages or files in `~/.cache/huggingface/modules`.

**Comment by harupy** [comment]
Related issue: https://github.com/huggingface/transformers/issues/11565

**Comment by harupy** [comment]
@PhucLee2605 Can you create a minimum reproduction code?
