### ISSUE TITLE
Recognize jsonnet extension as a text file in Artifact View

### ISSUE THREAD

**Issue by festeh** [mlflow/mlflow#921]
### Describe the problem
I'm using [Jsonnet](https://jsonnet.org/) files for configuring my deep learning experiments. I think this data format is way superior than Json for this task. For example, Jsonnet configs are used in popular NLP library [allennlp](https://allennlp.org/).

 My intention is to save a config file with each run, but sadly this data format is not recognized in artifact view as a text file. That means I cannot view full details of the run in the UI. I think this could be fixed by changing this [line](https://github.com/mlflow/mlflow/blob/544121854d4c0c56d27be72beb6f7a50fa3aafed/mlflow/server/js/src/utils/FileUtils.js#L13). Would you be interested in supporting this format?

**Comment by ankitmathur-db** [comment]
This is a good point - I'll put up a PR soon to deal with this. Maybe as part of #1664
