### ISSUE TITLE
Replace `"python"` with `sys.executable` in `tests/examples/test_examples.py`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9210]
```diff
diff --git a/tests/examples/test_examples.py b/tests/examples/test_examples.py
index d2b6a7297..c2e287aa7 100644
--- a/tests/examples/test_examples.py
+++ b/tests/examples/test_examples.py
@@ -103,7 +103,7 @@ def test_mlflow_run_example(directory, params, tmp_path):
     ("directory", "command"),
     [
         ("docker", ["docker", "build", "-t", "mlflow-docker-example", "-f", "Dockerfile", "."]),
-        ("keras", ["python", "train.py"]),
+        ("keras", [sys.executable, "train.py"]),
         (
             "lightgbm/lightgbm_native",
             [
```

`"python"` should be replaced with `sys.executable` to ensure we run the example scripts with the pyton interpreter running `tests/examples/test_examples.py`.

**Comment by scarlettrobe** [comment]
This seems like a simple issue I can easily knock out!

**Comment by harupy** [comment]
@scarlettrobe Thanks!

**Comment by harupy** [comment]
Just out of curiosity, how did you find this issue?

**Comment by scarlettrobe** [comment]
> Just out of curiosity, how did you find this issue?

https://goodfirstissue.dev/language/python

Wanted to find something related to ML and now here I am.

**Comment by Rukiyav** [comment]
hey is this issue still open

**Comment by harupy** [comment]
@Rukiyav Thanks for the comment! Unfortunately no. @scarlettrobe already filed a PR to close this issue. We have https://github.com/mlflow/mlflow/issues/9008, which is also a good first issue.
