### ISSUE TITLE
How to export dependencies alongside the model?

### ISSUE THREAD

**Issue by enpinzolas** [mlflow/mlflow#924]
On the documentation of the pyfunc flavor, it is stated that the dependencies are store directly or referenced with a conda environment.

However, I have not seen a single API function or example that has the dependencies linked locally instead of using the conda environment. 

Is it actually possible to do so or is the documentation obsolete?

Thank you!

**Comment by yassineAlouini** [comment]
You can save a model with its conda env by using the following command (`sklearn` flavor for example):  

```
mlflow.sklearn.log_model(model, artifact_path=artifact_path, conda_env=conda_env)
```

Notice that the `conda_env` variable here is a loaded  conda requirements YAML file. 
I hope this helps.

**Comment by enpinzolas** [comment]
Doing so only specifies the names of the dependencies with their version. According to the [documentation](https://mlflow.org/docs/latest/models.html#python-function-python-function), dependencies can be stored either directly or with a referenced via conda environment.

My use case is quite special, since I want to serve the models in an environment without access to the internet, since the models will be used only in LAN. Thus, exporting the dependencies locally so that the model knows where the files are would be optimal.

Right now the solution I have is building a docker image which loads the conda environment and prepares the  model for serving. This works but if there was any other solution it would be superb.

**Comment by tamirkamara** [comment]
Hi,
We have the same issue where no internet is accessible and we'd like to serve model locally.
Does anyone know if/how to store dependencies alongside the model as mentioned in the docs?

**Comment by zhangchi1** [comment]
> Doing so only specifies the names of the dependencies with their version. According to the [documentation](https://mlflow.org/docs/latest/models.html#python-function-python-function), dependencies can be stored either directly or with a referenced via conda environment.
> 
> My use case is quite special, since I want to serve the models in an environment without access to the internet, since the models will be used only in LAN. Thus, exporting the dependencies locally so that the model knows where the files are would be optimal.
> 
> Right now the solution I have is building a docker image which loads the conda environment and prepares the model for serving. This works but if there was any other solution it would be superb.

Hi, we have a similar use case, where I can install some private python library, created by ourselves. Not sure if you already have a solution of how to include your special dependencies along with your MLflow model? Thanks a lot,
