### ISSUE TITLE
[FR] Support for Huggingface PEFT model

### ISSUE THREAD

**Issue by dgormly** [mlflow/mlflow#9256]
### Willingness to contribute

Yes. I can contribute this feature independently. Any suggestions on where to look is welcome.

### Proposal Summary

The HuggingFace PEFT library allows you to fine-tune an adapter that is then attached to a base model. Currently the only way to log a PEFT model is to save the whole base model which is 10s of GB in size. The adapter is only 20mb with a config file.

### Motivation

> #### What is the use case for this feature?
Using LoRa adapters are a cheap way to fine-tune models. By supporting the PEFT library you can minimise the storage required to save a model while also enabling the use of the new MLFlow Evaluate library which allows you to compare LLM prompts.

> #### Why is this use case valuable to support for MLflow users in general?
It will allow the use of mlflow.evaluate for PEFT models which are a very cheap way to fine-tune models and helps with evaluating the prompt engineering between adapters.

> #### Why is this use case valuable to support for your project(s) or organization?
Unable to use the evaluate function. Experimentation with models leads to TB of storage if I do not save them as just artifacts.

> #### Why is it currently difficult to achieve this use case?
The kernal often fails when trying to save the whole model as a pyfunc model.

### Details

https://huggingface.co/blog/peft

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Hi @dgormly Could you provide design details ?

**Comment by dgormly** [comment]
For sure.

The PEFT library saves 2 files:
- A JSON config file that stores all the adapters settings, including which base model to pull down.
```
{
  "auto_mapping": null,
  "base_model_name_or_path": "tiiuae/falcon-7b",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "lora_alpha": 32,
  "lora_dropout": 0.05,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 16,
  "revision": null,
  "target_modules": [
    "query_key_value"
  ],
  "task_type": "CAUSAL_LM"
}
```
- A .bin file that contains the adapters weights.

To save a Peft file, all you need to do is call `model.save_pretrained("<model URI to save files into>")`

To load a Peft model, you need to load the Peft json config. Download the base model, and then wrap it in Peft:
```
# Need to figure out how to load model
PEFT_MODEL_URI = "trained-model"

config = PeftConfig.from_pretrained(PEFT_MODEL_URI)
model = AutoModelForCausalLM.from_pretrained(
    config.base_model_name_or_path,
    return_dict=True,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

model = PeftModel.from_pretrained(model, PEFT_MODEL_URI)
```

The pyfunc I have to do this looks like this (unfortunately it saves the whole base model with it which is the issue):
```
class PeftAdapterModel(mlflow.pyfunc.PythonModel):
    
    def __init__(self, model, artifacts_uri):
        self.model = model
    
    def load_finetuned_model(self, peft_loc):
        config = PeftConfig.from_pretrained(peft_loc)
        model = AutoModelForCausalLM.from_pretrained(
            config.base_model_name_or_path,
            return_dict=True,
            load_in_8bit=True, # Actually faster to train in 4 bit and inference in 8 bit
            device_map="auto",
            trust_remote_code=True
        )

        peft_model = PeftModel.from_pretrained(model, peft_loc)  
        return peft_model
    
    def load_context(self, context):
        os.environ["CUDA_VISIBLE_DEVICES"] = "0"
        self.model = self.load_finetunes_model(adapter_uri)

    def predict(self, context, model_input):
        device = "cuda:0"
        encoding = tokenizer(model_input, return_tensors="pt").to(device)
        
        with torch.inference_mode():
            outputs = self.model.generate(
                input_ids=encoding.input_ids,
                attention_mask=encoding.attention_mask,
                generation_config=gen_config,
                do_sample=False,
                use_cache=False # Seems to throw a mass amount of errors, slows down generation
            )
            
        return tokenizer.decode(outputs[0], skip_special_tokens=True)
    
    def log_model(self):
        # Save the artifacts to the specified folder
        self.save_artifacts()
        
        # Log the model without the large base model artifact
        mlflow.pyfunc.log_model("model", python_model=self, artifacts=self.artifact_uri)

    def save_artifacts(self):
        # Implement your logic to save only the necessary artifacts
        # For example, save some configuration files or small data files to artifacts_folder
        model.save_pretrained(self.artifact_uri) # <- Folder dir to save model into.
        mlflow.log_artifact(self.artifact_uri)
```
This is not exactly working just yet. I am still working out pyfunc models. It saves the whole model into a pickel file however I still need to then run the peft function which will download the base model?

**Comment by dgormly** [comment]
Is there a way that it just saves the python function and the adapter artifacts?

**Comment by WeichenXu123** [comment]
For logging PEFT model as a pyfunc model, you need to customize the saving logic to only save the "PEFT config" and the adapter weights. You can modify code here: https://github.com/mlflow/mlflow/blob/8e8d25b4298051e690c4f07ada5db3ce597ab352/mlflow/transformers.py#L209


When loading PEFT pyfunc model , you need to customize the loading func logic, you can modify code here:
https://github.com/mlflow/mlflow/blob/8e8d25b4298051e690c4f07ada5db3ce597ab352/mlflow/transformers.py#L1531 
to load the Peft json config, Download the base model, and then wrap it in a PeftModel

**Comment by dgormly** [comment]
Thank you! @WeichenXu123

**Comment by alanzhangeliiza** [comment]
Hi @WeichenXu123, we are currently creating functions to save, log and load a PEFT adapter. When using the base `model.log()` function for our own `log_model()` function we need to specify a flavor module. Is there an existing Model Flavour that we can us, otherwise how can we create our own PEFT Model Flavor? Thanks!

**Comment by WeichenXu123** [comment]
I think we can reuse transformers flavor, i.e., we can directly modify `mlflow.transformers.log_model` to make it support logging PEFT adapter. CC @BenWilson2

**Comment by dgormly** [comment]
@WeichenXu123 The PEFT model does not inherit from the transformers, it's more of a wrapper. This causes issues as it cannot be added to a Huggingface pipeline and throws errors when running `mlflow.transformers.save_model / .log_model ` with the model stored in a dictionary.

I think we need to make a new peft file? 🤔

**Comment by alanzhangeliiza** [comment]
Hi @WeichenXu123, in this method:
https://github.com/mlflow/mlflow/blob/master/mlflow/transformers.py#L1470

Would it be possible to include `PeftModelForCausalLM` or `PeftModel` as a valid model type?

**Comment by WeichenXu123** [comment]
> https://github.com/mlflow/mlflow/blob/master/mlflow/transformers.py#L1470

I think this makes sense, we can check the passed in model class type in `mlflow.transformers.save_model`

**Comment by alanzhangeliiza** [comment]
Hi @WeichenXu123 , saving and logging models seem to work by adding Peft imports to the transformers.py file. However, load_model still does not allow for PeftModels because in the `_load_model()` function, calling `getattr` on the transformers library causes an AttributeError when passing in a PeftModelForCausalLM. This is because it is not a module in the this huggingface [transformers file](https://github.com/huggingface/transformers/blob/686c68f64c9d0181bd54d4d2e2446543c3eca1fa/src/transformers/__init__.py). Do you have any ideas to work around this?

**Comment by WeichenXu123** [comment]
> Hi @WeichenXu123 , saving and logging models seem to work by adding Peft imports to the transformers.py file. However, load_model still does not allow for PeftModels because in the `_load_model()` function, calling `getattr` on the transformers library causes an AttributeError when passing in a PeftModelForCausalLM. This is because it is not a module in the this huggingface [transformers file](https://github.com/huggingface/transformers/blob/686c68f64c9d0181bd54d4d2e2446543c3eca1fa/src/transformers/__init__.py). Do you have any ideas to work around this?

We can directly update `mlflow.transformers. _load_model` code for PEFT model to make it work.

**Comment by alanzhangeliiza** [comment]
Hi @WeichenXu123 ,

I have created a codespace in which I have made changes to  transformers.py to support the PeftModel. I plan to write pytests for the changes I have made to support PeftModels. However, I am running into trouble when getting set up to contribute. 
In the codespace, when I run:
```
    ./dev/run-python-tests.sh
```
There are multiple tests that fail even before I make changes to the transformers file.
Another problem which I am running into is that when I run:
```
    pytest tests/transformers
```
I still have in import error on the package `optuna` coming from the file test_transformers_autolog.py. This package does not seem to appear in any of the requirement files at the moment. 
If I install the package within my mlflow-dev venv and run the pytests it also fails multiple tests, but it also fails to complete, terminating and citing the error: Low disk space (<5%).
Is this a problem that others have ran into, and if so how do I resolve it to run the pytests? Thanks!

**Comment by WeichenXu123** [comment]
@alanzhangeliiza You don't need to install all dependencies, for transformers testing code, you can install these dependencies:
https://github.com/mlflow/mlflow/blob/0206a2392aa9773a5c8d6eb865da67bfc1ace065/mlflow/ml-package-versions.yml#L489
and https://github.com/mlflow/mlflow/blob/0206a2392aa9773a5c8d6eb865da67bfc1ace065/mlflow/ml-package-versions.yml#L513

**Comment by songole** [comment]
Hey, any progress on this fix? When is it going to be part of a release?

**Comment by luigi-palladino-tpzg** [comment]
I am also interested in this feature

**Comment by momalepd** [comment]
Hi, any progress on this fix? Is anyone actively working on this?

**Comment by vikram71198** [comment]
Hi, is there any progress on this issue thus far? I'm really hoping this feature's released soon.

**Comment by WeichenXu123** [comment]
@dgormly Any progress on this task ? 

If you are busy, would you mind reassigning this task to @alanzhangeliiza or other volunteers ? :) 

Thanks!

**Comment by WeichenXu123** [comment]
Our team @B-Step62 is doing some work relating to this. I will assign this task to him to avoid complication. :)

**Comment by dgormly** [comment]
@WeichenXu123 We ended up leveraging PyFunc Models as we we couldn't find a pattern that was generic enough to cover most base models. Thank you for continuing the thread though.

**Comment by CJC-ds** [comment]
#11643 wanted to create a link.
Is there a way to reference `base_model_name_or_path` to a model_uri stored in databricks UC / workspace model registry?
