### ISSUE TITLE
Download CSV as a CLI option - Feature Request

### ISSUE THREAD

**Issue by dorukhansergin** [mlflow/mlflow#927]
Mlflow UI lets us download results as CSV. It would be very useful to have that as an option in the CLI. For experiments with over 1000 runs, the UI cannot load and usually crashes so we never get to use Download CSV.

An example api would be `mlflow experiments csv <experimentID> <filename.csv>` saves the results of the experiment with a certain ID to a file.

Thanks!

**Comment by liabifano** [comment]
Is anyone work on it already? If not, can I take a look on it?

**Comment by houssamzenati** [comment]
Any updates regarding this issue ? Thanks a lot

**Comment by jdlesage** [comment]
There is already the service `mlflow.search_runs`  returns a panda dataframe that can be converted to a dataframe.

**Comment by dorukhansergin** [comment]
@jdlesage Thanks a lot for the PR trial!

It was 0.9.1 (AFAIR) when I opened this issue. I think `.search_runs` was introduced in 1.1 
I don't know if the CLI option necessary now :/

**Comment by jdlesage** [comment]
Most of the commands in `mlflow experiments` are just a simple call to the python API. That's why I took the initiative to add this one. IMO, that's a nice feature and it is cheap to develop.

**Comment by jdlesage** [comment]
The PR has just be merged. Should be available in the next version of mlflow
