### ISSUE TITLE
Remove `pytest-raises-multiple-statements` in `mlflow/pylintrc`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9270]
Remove this line:

https://github.com/mlflow/mlflow/blob/28987989961d663c27cfdb75ef28fc7b6c212a17/pylintrc#L88

We no longer have this rule.

**Comment by KekmaTime** [comment]
@harupy can you assign me this issue

**Comment by harupy** [comment]
@KekmaTime Assigned!

**Comment by harupy** [comment]
@KekmaTime When you make a commit, please make sure to use `-s` to sign off your commit:

```
git commit -s -m "..."
```
