### ISSUE TITLE
[DOC-FIX] No documentation body for mlflow.search_model_versions

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#9272]
### Willingness to contribute

No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue

(https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.search_model_versions)

### Description of proposal (what needs changing)

There is no documentation body for mlflow. search_model_versions() unlike for mlflow.mlflow.search_registered_models().

**Comment by Bncer** [comment]
Hi @WeichenXu123! I want to take this issue. Can you assign it to me?

**Comment by Aman123lug** [comment]
@Bncer Are you still working on this?

**Comment by Bncer** [comment]
Hi @Aman123lug! Yes, I do

**Comment by Bncer** [comment]
@WeichenXu123 can you point out where to test/preview a docstring? As [cicleci](https://app.circleci.com/pipelines/github/mlflow/mlflow/25063/workflows/5b453813-a1ec-430b-85df-f9b40159da94/jobs/59466) fails.
cc @harupy
