### ISSUE TITLE
[BUG] Artifact relative path needs to be converted to POSIX when using Windows

### ISSUE THREAD

**Issue by GraceBrigham** [mlflow/mlflow#9278]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.5.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 and Linux Ubuntu (distribution unknown)
- **Python version**: 3.9.11

### Describe the problem

On my local machine (Windows 11), I save a model and its artifacts with `mlflow.pyfunc.save_model`. This saves relative paths for the artifact that have both '/' and '\' in the file path (e.g. '/var/azureml/models/myModel/1/artifacts/WebUpload\230810142051-2538339127\original_model').

When I deploy this model through AzureML it runs a script on Linux that calls `load_model()` on one of the artifacts. The '\' then cause 'OSError: No such file or directory'.

This is easily fixed by importing pathlib and changing mlflow/mlfow/pyfunc/model.py:203 to:
```
saved_artifact_subpath = posixpath.join(
        saved_artifacts_dir_subpath,
        pathlib.Path(os.path.relpath(path=tmp_artifact_path, start=tmp_artifacts_dir.path())).as_posix(),
)
```

### Tracking information

```shell
System information: Windows 10.0.22621
Python version: 3.9.11
MLflow version: 2.5.0
MLflow module location: [c:\Users\t-grbrigham\AppData\Local\anaconda3\envs\env\lib\site-packages\mlflow\__init__.py](file:///C:/Users/t-grbrigham/AppData/Local/anaconda3/envs/env/lib/site-packages/mlflow/__init__.py)
Tracking URI: azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/e0fd569c-e34a-4249-8c24-e8d723c7f054/resourceGroups/hawestra-rg/providers/Microsoft.MachineLearningServices/workspaces/grbrigham
Registry URI: azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/e0fd569c-e34a-4249-8c24-e8d723c7f054/resourceGroups/hawestra-rg/providers/Microsoft.MachineLearningServices/workspaces/grbrigham
MLflow dependencies: 
  Flask: 2.3.2
  Jinja2: 3.1.2
  alembic: 1.11.2
  click: 8.1.6
  cloudpickle: 2.2.1
  databricks-cli: 0.17.7
  docker: 6.1.3
  entrypoints: 0.4
  gitpython: 3.1.32
  importlib-metadata: 6.8.0
  markdown: 3.4.4
  matplotlib: 3.7.2
  numpy: 1.22.4
  packaging: 23.1
  pandas: 1.5.3
  protobuf: 4.24.0
  pyarrow: 9.0.0
  pytz: 2023.3
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.0.2
  scipy: 1.11.1
  sqlalchemy: 2.0.19
  sqlparse: 0.4.4
  waitress: 2.1.2
```

### Code to reproduce issue

```
# On windows
artifacts = {'model' :  'models:/iris_mlflow_model/1'}
mlflow.pyfunc.save_model(
    path='model',
    code_path=['./explanation_wrapper.py'],
    python_model=model,
    artifacts=artifacts
)
mlflow.register_model('file://model', 'model')

# On linux
mlflow.pyfunc.load_model('models:/model/1')
```

### Stack trace

```
  File "/var/azureml-app/score/score.py", line 253, in <module>
    model = load_model(model_path)
  File "/opt/miniconda/envs/userenv/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 597, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/opt/miniconda/envs/userenv/lib/python3.9/site-packages/mlflow/pyfunc/model.py", line 302, in _load_pyfunc
    python_model.load_context(context=context)
  File "/var/azureml-app/azureml-models/wrapper/10/wrapper/code/explanation_wrapper.py", line 50, in load_context
    self.model = mlflow.pyfunc.load_model(context.artifacts['model'])
  File "/opt/miniconda/envs/userenv/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 578, in load_model
    local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
  File "/opt/miniconda/envs/userenv/lib/python3.9/site-packages/mlflow/tracking/artifact_utils.py", line 100, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/opt/miniconda/envs/userenv/lib/python3.9/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 81, in download_artifacts
    raise OSError(f"No such file or directory: '{local_artifact_path}'")
OSError: No such file or directory: '/var/azureml/models/myModel/1/artifacts/WebUpload\230810142051-2538339127\original_model'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Thanks for reporting this! Pls file a fixing PR, appreciate your contribution!

**Comment by GraceBrigham** [comment]
@WeichenXu123 Just filed #9347

**Comment by hawestra** [comment]
@BenWilson2 which version of mlflow is this included in ?
