### ISSUE TITLE
Enable `PT013` to prevent importing `pytest` with an alias

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9298]
### Summary

Make the following change to enable [`PT013`](https://beta.ruff.rs/docs/rules/pytest-incorrect-pytest-import/):

```diff
diff --git a/pyproject.toml b/pyproject.toml
index ca9a71f03..1cfbe040d 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -24,6 +24,7 @@ select = [
   "PT009",
   "PT010",
   "PT012",
+  "PT013",
   "PT018",
   "PT023",
   "PT026",
```

### Notes

- Please make sure to open a PR from a non-master branch.
- When you make a commit, please sign off the commit using `-s`:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to add this
  ```
- When you open a PR, please make sure to link this issue with `#<id_of_this_issue>`. If the PR can close this issue, please use `Resovle #<id_of_this_issue>`.

**Comment by itsajay1029** [comment]
Can you assign it to me ? @harupy I'd love to work on it asap. Also, can you explain the issue a little ?

**Comment by harupy** [comment]
@itsajay1029 Thanks!

**Comment by harupy** [comment]
The `select` field in `pyproject.toml` is a list of enabled rules. We can add `PT013` there to enable it.

**Comment by harupy** [comment]
@itsajay1029 https://beta.ruff.rs/docs/rules/pytest-incorrect-pytest-import/ should clarify what we want to enforce.
