### ISSUE TITLE
Add "no windows support" or known OS restrictions to documentation main page

### ISSUE THREAD

**Issue by Bibonaut** [mlflow/mlflow#937]
### Describe the problem
I am running Windows 10 and I spent much time reading the documentation. In the documentation, it is not mentioned that Windows is not fully supported.

On github (https://github.com/mlflow/mlflow) there are two notes (beta status and lacking Windows support) but in the documentation (https://mlflow.org/docs/latest/index.html) only the first note (beta status) is mentioned. 

In my case, I tried to start the user interface with `mlflow ui` and came across issue #154.

### Solution
Add note in the documentation that Windows is currently not fully supported.

**Comment by marcfusterr** [comment]
Same happen to me. By the end of March it is still not hihglighted enough.

**Comment by ChangCheng-Lei** [comment]
facing the same issue, please highlight the issue, it cost much time for solving this issue

**Comment by djrscally** [comment]
Noting that this is an ongoing issue, to prevent the bot from auto-closing it.

**Comment by Bibonaut** [comment]
On my Windows machine, both commands `mlflow ui` and `mlflow server` seem to work without errors with mlflow versions 1.2.0 and 1.3.0 🎉 
If there aren't any further Windows incompatibilities, I would like to close this issue :)
