### ISSUE TITLE
MLflow tracking for images data

### ISSUE THREAD

**Issue by Hir98** [mlflow/mlflow#9415]
Hello

I want to know that can we use mlflow inference for images??
To serve yolov8(object detection) model through mlflow tracking is it possible ??
If possible then please attached some reference for that.
Can you please help me  .

Thanks

**Comment by BenWilson2** [comment]
Hi @Hir98 feel free to use the discussions forum for questions about what you can and can't do with MLflow: https://github.com/mlflow/mlflow/discussions . The Issues section of GitHub is for requesting features or reporting bugs. I think you'll get some creative answers from asking the community and some of the clever things that they've managed to do! 
Thank you for using MLflow :)
