### ISSUE TITLE
Accessing name of a run through runInfo

### ISSUE THREAD

**Issue by ahmed-shariff** [mlflow/mlflow#943]
I use the `run_name` in place of th `run_uuid` to interface with some of my older code and have some of the newer outputs more readable. In order to access the name of a run, I currently have to go through the tags of a run and get the run's `name`. Is it possible to access the `name` through the `RunInfo`? why is the name stored as a tag instead of being set as part of the run's meta data?

**Comment by SchJens** [comment]
I encountered the same issue. What is the name of a run currently used for, as opposed to the tag "Run Name"? 
It would also be quite useful to be able to filter based on a run's name (or actually based on any tag). Is something like this planned?
