### ISSUE TITLE
[FR] Support customizing auth header in outgoing http request

### ISSUE THREAD

**Issue by lu-ohai** [mlflow/mlflow#9443]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Seems the current mlflow sdk only supports adding [aws sigv4](https://github.com/mlflow/mlflow/pull/7044) as `auth` in outgoing http request to mlflow tracking server. There is `RequestHeaderProvider` plugin to allow adding extra http header, but sometimes the added header is generated based on actual http request headers, which can't be acquired while this plugin is called. It would be great that mlflow sdk can support customizing `auth` in outgoing http request for different cloud vendors for the purpose of client side authentication. 

### Motivation

> #### What is the use case for this feature?

Enable customizing `auth` in outgoing http request to mlflow tracking server.

> #### Why is this use case valuable to support for MLflow users in general?

It's beneficial for cloud vendors that need this for client side authentication of mlflow tracking server.

> #### Why is this use case valuable to support for your project(s) or organization?

We need `Authorization` header to be encoded from actual http request headers, like `date`, `(request-target)`, `host`, `content-length`, etc. and all of these require the existence of signer to be added as `auth`. 
```
import request

response = requests.get(endpoint, auth=signer, ...)
```
This feature would enable the client side authentication of our mlflow tracking server.

> #### Why is it currently difficult to achieve this use case?

There is no place to add our signer in outgoing http request to mlflow tracking server and the authentication can't be achieved.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Thank you for the FR idea and we'll gladly review your PR :) 
Do you have an idea of the mechanism from a user perspective that this would be set?

**Comment by lu-ohai** [comment]
Hello @BenWilson2 , thank you for the response.

The main idea is to add new plugin to enable customizing `auth` in the http request. 

For vendors, they'll need to implement the plugin and add their own logic in it to build their `auth` object. 

For users, similar to AWS, they will need to install vendor's plugin and set some environment variable (`MLFLOW_TRACKING_AUTH`) to enable the injection of `auth` object. The value of the environment variable is subject to vendors. 

For example

- To inject x vendor's auth
```
...
os.environ["MLFLOW_TRACKING_AUTH"] = "<x_vendors_auth_name>"

# other mlflow operations
...
```

We would also like to hear some suggestions from you, thanks!

**Comment by lu-ohai** [comment]
Hello @BenWilson2, I just submitted a pr to extend this feature and would appreciate you taking a loot at it, thanks! https://github.com/mlflow/mlflow/pull/9460
