### ISSUE TITLE
[BUG] Security Vulnerability  anyone can use /signup 

### ISSUE THREAD

**Issue by xgdgsc** [mlflow/mlflow#9448]
anyone can use /signup as https://mlflow.org/docs/latest/auth/index.html#id1  to  create an account and view previous experiments?

**Comment by tomasn4a** [comment]
I'm still running into this issue using the latest 2.7.1 official docker image. I have tried setting `default_permission = NO_PERMISSIONS` in `basic_auth.ini` and although when logging in with the new user I cannot view previous experiments I can still create new ones

**Comment by xgdgsc** [comment]
Seems fixed with 2.8.1 ?

**Comment by tomasn4a** [comment]
Thanks @xgdgsc you're right, seems to be fixed now
