### ISSUE TITLE
[BUG] mlflow fails to infer batch size when using keras.utils.Sequence as input with sample weights

### ISSUE THREAD

**Issue by dnerini** [mlflow/mlflow#9486]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.6.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.3 LTS
- **Python version**: 3.10.8

### Describe the problem

When training a keras model using a [keras.utils.Sequence](https://keras.io/api/utils/python_utils#sequence-class) object as an input, the batch size is inferred by the shape of the first training batch, see [L#1213](https://github.com/mlflow/mlflow/blob/08eb20ea701ae8e9d74dfe1a93b762ca9d802e11/mlflow/tensorflow/__init__.py#L1213C41-L1213C41) in `mlflow/tensorflow/__init__.py`. 
This works well in the common case where the data generator returns a tuple with `(inputs, targets)`. However, when using sample weights, the generator will return a 3-element tuple `(inputs, targets, sample weights)` as also indicated in the [documentation](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model#fit), which breaks the mlflow logic with the following warning: 
`WARNING mlflow.tensorflow: Encountered unexpected error while inferring batch size from training dataset: too many values to unpack (expected 2)`. Consequently, the batch size parameter is not defined and gets logged as `None` in the corresponding experiment.

The fix would be quite easy, simply replace [L#1213](https://github.com/mlflow/mlflow/blob/08eb20ea701ae8e9d74dfe1a93b762ca9d802e11/mlflow/tensorflow/__init__.py#L1213C41-L1213C41) with: `first_batch_inputs, *_ = training_data[0]`. 

If you agree, I'll go ahead and open a PR with the above fix.

### Tracking information

```shell
System information: Linux #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
Python version: 3.10.8
MLflow version: 2.6.0
MLflow module location: /home/ned/.cache/pypoetry/virtualenvs/mlflow-bug-batch-size-cbJ14gYV-py3.10/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: file:///home/ned/sandbox/mlflow-bug-batch-size/mlruns
Registry URI: file:///home/ned/sandbox/mlflow-bug-batch-size/mlruns
MLflow dependencies: 
  Flask: 2.3.3
  Jinja2: 3.1.2
  alembic: 1.11.3
  click: 8.1.7
  cloudpickle: 2.2.1
  databricks-cli: 0.17.6
  docker: 6.1.3
  entrypoints: 0.4
  gitpython: 3.1.32
  gunicorn: 21.2.0
  importlib-metadata: 6.8.0
  markdown: 3.4.4
  matplotlib: 3.7.2
  numpy: 1.24.3
  packaging: 23.1
  pandas: 2.0.3
  protobuf: 4.24.2
  pyarrow: 12.0.1
  pytz: 2023.3
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.3.0
  scipy: 1.9.3
  sqlalchemy: 2.0.19
  sqlparse: 0.4.4
```

### Code to reproduce issue

```
import mlflow
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import Sequence

# dummy sequence generator
class DummySequence(Sequence):
    def __init__(self, X, y, w=None):
        self.X = X
        self.y = y
        self.w = w

    def __len__(self):
        return 1

    def __getitem__(self, idx):
        if self.w is not None:
            return self.X, self.y, self.w
        else:
            return self.X, self.y

# dummy data
X = np.array([0, 0, 0, 1, 1, 0, 1, 1]).reshape((4, 2))
y = np.array([0, 1, 1, 0]).reshape((4, 1))
w = np.array([1, 1, 1, 1]).reshape((4, 1))

# dummy model
model = Sequential()  
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# fit models 
mlflow.autolog()
with mlflow.start_run(run_name="data-gen-x-y") as active_run: 
    data_gen = DummySequence(X, y)   
    model.fit(data_gen, epochs=3, verbose=0)
with mlflow.start_run(run_name="data-gen-x-y-w") as active_run: 
    data_gen = DummySequence(X, y, w)   
    model.fit(data_gen, epochs=3, verbose=0)

# lookup batch size for both runs
 client = mlflow.tracking.MlflowClient() 
 experiment = client.search_experiments()[0] 
 runs = client.search_runs(experiment_ids=experiment.experiment_id) 
 
 print(f'{runs[0].data.tags["mlflow.runName"]}: {runs[0].data.params["batch_size"]}') 
 print(f'{runs[1].data.tags["mlflow.runName"]}: {runs[1].data.params["batch_size"]}')
# data-gen-x-y-w: None
# data-gen-x-y: 4

```

### Stack trace

Not relevant, see log output below.

### Other info / logs

```
2023/08/30 16:06:28 WARNING mlflow.tensorflow: Encountered unexpected error while inferring batch size from training dataset: too many values to unpack (expected 2)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @dnerini sounds great! Thank you for volunteering! When pushing the PR, please add your repro code in the form of a unit test to ensure that autologging is correctly recording the fix :) Thanks!

**Comment by serena-ruan** [comment]
Close as the PR is merged.
