### ISSUE TITLE
[BUG] Mlflow not saving artifacts in AWS S3 bucket when trying to run from local to remote

### ISSUE THREAD

**Issue by hitmanagent298** [mlflow/mlflow#9496]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

**Version: 2.6.0**

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 22.04
- **Python version**: 3.8.0/3.10.12

### Describe the problem

I am using AWS ECS for creating a Mlflow server with Dockerfile containing following inputs:

```
FROM python:3.8.0

RUN pip3 install mlflow pymysql boto3

CMD mlflow server \
  --backend-store-uri my.rds.url \
  --artifacts-destination s3://bucket-url/mlflow \
  --host 0.0.0.0 \
  --serve-artifacts
  
```  

  My ECS container having mlflow server is instead saving the artifacts on the ec2 instance running behind the ECS cluster as the cluster is enabled to support both fargate and ec2 type. 

My experimental file test.py:

```
import mlflow 
import pymysql
import boto3
tracking_uri = 'my.custom.url'
experiment_name = 'new-exp1'
mlflow.set_tracking_uri(tracking_uri)
mlflow.create_experiment(experiment_name)
mlflow.set_experiment(experiment_name)
print(mlflow.get_tracking_uri()) # This should be 'http://localhost:5000' 
print(mlflow.get_artifact_uri()) # This should be '${mlruns_artifacts}/0/${uuid}/artifacts' 
mlflow.log_param("test_param", 0)
mlflow.log_metric('test_metric', 1) 
mlflow.log_artifact("/testfile.txt")   #Same directory as in test.py

```

 

### Tracking information

```

print(mlflow.get_tracking_uri()) 
print(mlflow.get_artifact_uri())

```

### Code to reproduce issue

As I mentioned earlier, the artifacts are being stored inside Ecs ec2 instance running the container instead of S3 bucket.

```
mlflow-artifacts:/789595539787324845/bc124b4050d94f378fba9595b91e1289/artifacts

```
If I also include the parameter --default-artifact-root s3://bucket-url/mlflow, its showing following in access keys error, but I want my code to directly proxy to tracking_url.

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    mlflow.log_artifact("/testfile.txt")
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 877, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1091, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 456, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 153, in log_artifact
    self._upload_file(
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 146, in _upload_file
    s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
  File "/usr/local/lib/python3.8/site-packages/boto3/s3/inject.py", line 143, in upload_file
    return transfer.upload_file(
  File "/usr/local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 292, in upload_file
    future.result()
  File "/usr/local/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.8/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/s3transfer/upload.py", line 758, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 963, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 986, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.8/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
root@02da7ad66cd5:/# exit
exit

```

### Stack trace

**None**

### Other info / logs

**None**

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @hitmanagent298 Looks like there's a missing credential in your container, if it's configured by an environment variable you should make it available in the container.

**Comment by hitmanagent298** [comment]
I have tried launching it via both with and without Environments variables by directly passing the comma separated commands in "Command" field of docker configuration part in ECS task definition. But I am still getting the same issue. Do we need to pass AWS access keys in this proxified Scenario 5 when trying from local codebase to remote tracking URI. ?

[https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access](url)

**Comment by serena-ruan** [comment]
Hi @hitmanagent298  Could you provide your command to pass environment variables?
Another thing worth trying out is to exclude mlflow in the process, could you try uploading a random file without mlflow and see if it works? If it's still the `NoCredentials` issue then we can know it's just something wrong about the setup.

**Comment by hitmanagent298** [comment]
Sure here is my dockerfile which is used to create AWS ECR image:

``` FROM python:3.8.0

RUN pip3 install mlflow pymysql boto3

ENV BACKEND_STORE="your_sql_url"
ENV ARTIFACT_STORE="your_s3_bucket_environment"

CMD mlflow server \
  --backend-store-uri $BACKEND_STORE \
  --artifacts-destination $ARTIFACT_STORE \
  --host 0.0.0.0 \
  --serve-artifacts
```

In docker configuration of task definition, for command field:
``` mlflow,server,--backend-store-uri,${BACKEND_STORE},--artifacts-destination,${ARTIFACT_STORE},--host,0.0.0.0,--serve-artifacts ```

I have added environment variables BACKEND_STORE & ARTIFACT_STORE in the AWS parameter store and using valuesFrom feature of ECS task defintion, I am accessing them. The ECS task defintion role has AmazonSSMFullAccess and S3FullAcess IAM policies attached.

Also one more thing, if I am running the above provided .py file inside the EC2 which is behind ECS task by docker exec into the container running on the instance things are working fine.

**Comment by serena-ruan** [comment]
> Also one more thing, if I am running the above provided test.py file inside the EC2 which is behind ECS task by docker exec into the container running on the instance things are working fine.

This sounds like the issue is not with MLflow. Could you try asking AWS support to fix the issue? There must be some setup configuration problems but it's quite hard for us to locate the root cause.

**Comment by hitmanagent298** [comment]
Ok it seems like things are working fine after I downgraded mlflow to 2.5.0 and pydantic to 1.10.9
