### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by joshuajennysibbu** [mlflow/mlflow#9514]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **Windows 11**:
- **Python 3.10.5**:
- **yarn version, if running the dev UI**:

### Describe the problem

I built a pytorch model. I have use mlflow log_model it stored successfully. When i load it in same file works well. But when i try to load in different file in same directory it gives "ModuleNotFoundError: No module named 'model'" error.

### Tracking information

```shell
MLflow version: 2.6.0
Tracking URI: file:///C:/Users/91787/Downloads/LJSpeech_Enhanced/mlruns
Artifact URI: file:///C:/Users/91787/Downloads/LJSpeech_Enhanced/mlruns/0/b8e176e1fc6841659d254465a8d2f504/artifacts
System information: Windows 10.0.22621
Python version: 3.10.5
MLflow version: 2.6.0
MLflow module location: C:\Users\91787\Downloads\LJSpeech_Enhanced\wav_conversion\lib\site-packages\mlflow\__init__.py
Tracking URI: file:///C:/Users/91787/Downloads/LJSpeech_Enhanced/mlruns
Registry URI: file:///C:/Users/91787/Downloads/LJSpeech_Enhanced/mlruns
Active experiment ID: 0
Active run ID: b8e176e1fc6841659d254465a8d2f504
Active run artifact URI: file:///C:/Users/91787/Downloads/LJSpeech_Enhanced/mlruns/0/b8e176e1fc6841659d254465a8d2f504/artifacts
MLflow dependencies: 
  Flask: 2.3.3
  Jinja2: 3.1.2
  alembic: 1.11.3
  click: 8.1.7
  cloudpickle: 2.2.1
  databricks-cli: 0.17.7
  docker: 6.1.3
  entrypoints: 0.4
  gitpython: 3.1.32
  importlib-metadata: 6.8.0
  markdown: 3.4.4
  matplotlib: 3.7.2
  numpy: 1.25.2
  packaging: 23.1
  pandas: 2.0.3
  protobuf: 4.24.1
  pyarrow: 12.0.1
  pytz: 2023.3
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.3.0
  scipy: 1.11.1
  sqlalchemy: 2.0.20
  sqlparse: 0.4.4
  waitress: 2.1.2
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
Traceback (most recent call last):
  File "c:\Users\91787\Downloads\LJSpeech_Enhanced\project\trainer\test_mlflow.py", line 10, in <module>
    loaded_model = mlflow.pytorch.load_model(logged_model)
  File "C:\Users\91787\Downloads\LJSpeech_Enhanced\wav_conversion\lib\site-packages\mlflow\pytorch\__init__.py", line 710, in load_model
    return _load_model(path=torch_model_artifacts_path, **kwargs)
  File "C:\Users\91787\Downloads\LJSpeech_Enhanced\wav_conversion\lib\site-packages\mlflow\pytorch\__init__.py", line 625, in _load_model
    return torch.load(model_path, **kwargs)
  File "C:\Users\91787\Downloads\LJSpeech_Enhanced\wav_conversion\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\91787\Downloads\LJSpeech_Enhanced\wav_conversion\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\91787\Downloads\LJSpeech_Enhanced\wav_conversion\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'model'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @joshuajennysibbu Could you provide your code to reproduce the problem? Are you using the model uri to load the model back?

**Comment by joshuajennysibbu** [comment]
Code snippet i use load model. 

`import mlflow
logged_model = 'runs:/6f8139403b494163abcaeb1adecf880e/model'

loaded_model = mlflow.pytorch.load_model(logged_model)
`
I tried with ipynb it load model without error in same kernel. When i restart and run a particular this code cell it give this error.

**Comment by serena-ruan** [comment]
Looks like it's a pytorch problem https://github.com/pytorch/pytorch/issues/18325. Could you try https://github.com/pytorch/pytorch/issues/18325#issuecomment-1501487230?

**Comment by WeichenXu123** [comment]
We can also try:
```
import cloudpickle
torch.save(obj, f, pickle_module=cloudpickle)
```
to address it

**Comment by harupy** [comment]
@WeichenXu123 Can you translate that code in MLflow code? This isn't a pytorch repo.

**Comment by serena-ruan** [comment]
@joshuajennysibbu You could try passing `pickle_module=cloudpickle` as kwargs when logging the model: 
```
import cloudpickle
mlflow.pytorch.log_model(model, pickle_module=cloudpickle)
```

**Comment by joshuajennysibbu** [comment]
Still same error, It's ok. Thank You for your reply. I save model using model.state_dict(). It working good😊.
