### ISSUE TITLE
Why use HTTP vs. openai python sdk? 

### ISSUE THREAD

**Issue by krrishdholakia** [mlflow/mlflow#9526]
Hi @harupy @jerrylian-db, 

I noticed MLFlow calls the HTTP openai endpoint instead of using the python sdk. Why?

**Comment by harupy** [comment]
@krrishdholakia In MLflow AI gateway?

**Comment by krrishdholakia** [comment]
I believe so? - https://github.com/mlflow/mlflow/blob/abf4140a7fa809154e3e7542fda6da7257c8a9c8/mlflow/gateway/providers/openai.py#L26

Just curious why not use the python sdk instead?
