### ISSUE TITLE
AttributeError: module 'mlflow' has no attribute 'pytorch'

### ISSUE THREAD

**Issue by DanlanChen** [mlflow/mlflow#953]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:mac
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**:0.8.2
- **Python version**: 3.6.8
- **npm version (if running the dev UI):5.6.0
- **Exact command to reproduce**:
```python>>
>>import mlflow
>>model_path_dir = "model"
>>run_id = "39e9c9fcb5a74231823287acaba7f84e"
>>pytorch_model = mlflow.pytorch.load_model(model_path_dir, run_id)
```
attributeError: module 'mlflow' has no attribute 'pytorch'

### Describe the problem
you must  do` import mlflow.pytorch` to avoid this error

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by avinashraghuthu** [comment]
It appears to be pytorch is not installed along with mlflow.I tried adding pytorch in setup.py of mlflow and it got resolved for me. 
@smurching Is it deliberately left out giving the flexibility for user to install required version or its a bug.

**Comment by hanyucui** [comment]
Not speaking for the dev team here, but it makes sense for `mlflow.pytorch` and alike to be optional. A lot of users would just use one of them. Say, if I use Tensorflow, I don't want `mlflow.pytorch` to be imported.

**Comment by ankitmathur-db** [comment]
It is - you can import mlflow.pytorch if you want it though!
