### ISSUE TITLE
[BUG] mlflow server uses different global scope from mlflowclient

### ISSUE THREAD

**Issue by akshaya-a** [mlflow/mlflow#9531]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

https://github.com/mlflow/mlflow/blob/master/mlflow/server/handlers.py#L265

While tracking down a behavioral issue for #9495 , I think the problem stems from a sharded global scope introduced by the above utility.

I propose to instead use the utils._resolve* etc that MLflowClient uses so that the entire process views the mlflow universe the same way. @serena-ruan wdyt?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @akshaya-a Thanks for locating the root cause for this! Does this PR https://github.com/mlflow/mlflow/pull/9458 solve the same problem?

**Comment by akshaya-a** [comment]
@serena-ruan  I don't see how - the failing code is a blind MLflowClient() invocation elsewhere in the process, and MLflowClient's notion of scoping is not the same as the current file I identify in the above description.

The proposal here would have to happen anyway to solve the root cause of "mlflow-related-process has 2 independent mechanisms to check the currently globally specified tracking store"

**Comment by akshaya-a** [comment]
to be a bit more clear, here is the exact change that I validated works for the AML plugin: https://github.com/mlflow/mlflow/pull/9575

**Comment by serena-ruan** [comment]
I see, sorry for the confusion! I think your change makes sense :)
