### ISSUE TITLE
[BUG] infer_signature accepts pd.Series as param value but fails when creating ParamSpec

### ISSUE THREAD

**Issue by FloridaDataGuy** [mlflow/mlflow#9554]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.6.0
- Tracking server: 2.6.0

### System information

- **OS Platform and Distribution**: Debian GNU/Linux 11 (bullseye)
- **Python version**: 3.10.12
- **yarn version, if running the dev UI**:

### Describe the problem

`mlflow.models.signature.infer_signature` accepts parameter `params`. By docstring this parameter is expected to be dict[str, Any]. So `{'test_series': pd.Series([True, False, True])}` should be a legit `params` specification.

And under the hood of `infer_signature` the `_infer_param_schema` -> `_infer_type_and_shape` accepts **pd.Series** as legit value type in this line `if isinstance(value, (list, np.ndarray, pd.Series)):`. 

But next line in `infer_signature` calls **ParamSpec** constructor and it fails because `ParamSpec` class has method `validate_type_and_shape` which in turn allows only **list** and **np.ndarray** in the following line `return isinstance(value, (list, np.ndarray)) and np.array(value).ndim == 1`.

As a result user will get error "MlflowException: Value must be a 1D array with shape (-1,) for param ..." for **pd.Series** as one of the `params` parmeter values.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import numpy as np
import pandas as pd
import mlflow

mlflow.models.signature.infer_signature(
    pd.DataFrame({'a': [1,2,3]}),
    np.array([1,2,3]),
    params={'test_series': pd.Series([True, False])}
)
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 mlflow.models.signature.infer_signature(                                                     │
│   2 │   pd.DataFrame({'a': [1,2,3]}),                                                            │
│   3 │   np.array([1,2,3]),                                                                       │
│   4 │   params={'test_series': pd.Series([True, False])}                                         │
│                                                                                                  │
│ /usr/local/lib/python3.10/site-packages/mlflow/models/signature.py:216 in infer_signature        │
│                                                                                                  │
│   213 │   """                                                                                    │
│   214 │   inputs = _infer_schema(model_input)                                                    │
│   215 │   outputs = _infer_schema(model_output) if model_output is not None else None            │
│ ❱ 216 │   params = _infer_param_schema(params) if params else None                               │
│   217 │   return ModelSignature(inputs, outputs, params)                                         │
│   218                                                                                            │
│   219                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/site-packages/mlflow/types/utils.py:517 in _infer_param_schema         │
│                                                                                                  │
│   514 │   │   │   invalid_params.append((name, value, e))                                        │
│   515 │                                                                                          │
│   516 │   if invalid_params:                                                                     │
│ ❱ 517 │   │   raise MlflowException.invalid_parameter_value(                                     │
│   518 │   │   │   f"Failed to infer schema for parameters: {invalid_params}",                    │
│   519 │   │   )                                                                                  │
│   520              

MlflowException: Failed to infer schema for parameters: [('test_series', 0     True
1    False
dtype: bool, MlflowException("Value must be a 1D array with shape (-1,) for param 'test_series': boolean (default: 0     True\n1    False\ndtype: bool) (shape: (-1,)), received Series with ndim 1"))]

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Hi @FloridaDataGuy thanks for reporting this! I raised a PR to fix the strange exception, we should not allow passing pandas Series.

**Comment by serena-ruan** [comment]
Close as the PR merged.
