### ISSUE TITLE
Enhancement: Use conda activate instead of source activate

### ISSUE THREAD

**Issue by yassineAlouini** [mlflow/mlflow#965]
### Describe the problem
For now (https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/cli.py#L26), `source activate <env_name>` is used to activate the `conda` env. As advised, it is better to use  `conda activate <env_name>`.

I can give this feature a try this weekend or the newt one. Let me know if it makes sense. :)

**Comment by hanyucui** [comment]
@yassineAlouini That makes sense and the change seems small and low-risk. I suggest you go ahead and submit a pull request. The dev team might just merge it.

Linking the relevant doc from anaconda.com: https://www.anaconda.com/how-to-get-ready-for-the-release-of-conda-4-4

**Comment by yassineAlouini** [comment]
Perfect. I will work on this on the weekend and submit a PR. More to come soon. :)

**Comment by eric-vader** [comment]
As far as I can tell, these are the 2 places to fix:

1. [https://github.com/mlflow/mlflow/blob/8e820dab991ff790957c3a2a5c679ac35bf9b7a4/mlflow/projects/__init__.py#L617](Projects)
2. [https://github.com/mlflow/mlflow/blob/8e820dab991ff790957c3a2a5c679ac35bf9b7a4/mlflow/pyfunc/backend.py#L100](Py func)

@yassineAlouini Did you manage to push the changes?

**Comment by yassineAlouini** [comment]
@eric-vader I lacked time to do it these last months and I was on vacation. I don't know if you managed to finish the PR and if it isn't done yet, I am more than happy to help you review it. Again, sorry for the late answer.

**Comment by eric-vader** [comment]
Sure no worries! I can submit the PR this week! @yassineAlouini

**Comment by yassineAlouini** [comment]
Awesome. Thanks @eric-vader. :)

**Comment by rajatpundir** [comment]
Hi, any updates on this? 'mlflow run' is failing for me because of 'source activte'. Can someone please go ahead and merge it int the master.

**Comment by eric-vader** [comment]
@yassineAlouini @rajatpundir I have just submitted the pull request for the modification to projects only. 

I am not so sure if I should make the changes repo wide in pyfunc and also in the docker backend, as I do not use them at all! From what I tell they are containerized, so changing to `conda activate` would just improve the speed and have no other effects.

1. mlflow/pyfunc/backend.py
2. mlflow/sagemaker/container/__init__.py

If someone can advise, that will be great!

**Comment by rajatpundir** [comment]
@eric-vader I don't use the docker backends as well but since 'source activate' is deprecated, I don't think replacing it with 'conda activate' would create any problem. You could leave out the changes for containers for now if you are not sure and make the other changes that you are sure about and someone else will pickup the work in future for the containers.
