### ISSUE TITLE
[BUG] Configuration Error in Databricks connecting to experiment from DeepspeedTorchDistributor

### ISSUE THREAD

**Issue by nathan-az** [mlflow/mlflow#9656]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I do not know how to fix this bug independently.

### MLflow version

- Client: 2.5.0, also attempted upgrading to 2.7.1 (both driver and worker via init script)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.3 LTS
- **Python version**: 3.10.12

### Describe the problem

The issue is occurring on Databricks (DBR 14.0 ML Beta). In my case, this prevented attempts to run the `transformers.Trainer` and log to MLFlow. I came across this using the `DeepspeedDistributor` and confirmed (to remove complexity) with the `TorchDistributor`.

The issue occurred when attempting to start a run, or set an experiment. 

I assume this is an issue with not correctly passing through the credentials through to the worker tasks, similar to an issue reported in UDFs in the past https://github.com/mlflow/mlflow/issues/1315. I largely think this due to the following line in the trace:
```databricks_cli.utils.InvalidConfigurationError: You haven't configured the CLI yet! Please configure by entering `/tmp/tmpjgk87upc/train.py configure```

### Code to reproduce issue

```py
import os
from pyspark.ml.torch.distributor import TorchDistributor

def test_func():
    import mlflow
    mlflow.start_run()

distributor = TorchDistributor(
    num_processes=1, 
    use_gpu=True,
    local_mode=False, 
)
distributor.run(
    test_func
)
```

### Stack trace

```
Started distributed training with 1 executor processes
Traceback (most recent call last):
  File "/tmp/tmpjgk87upc/train.py", line 8, in <module>
    output = fn(*args, **kwargs)
  File "/root/.ipykernel/2743/command-2582754694709039-3284724072", line 7, in test_func
  File "/databricks/python/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 365, in start_run
    active_run_obj = client.create_run(
  File "/databricks/python/lib/python3.10/site-packages/mlflow/tracking/client.py", line 327, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "/databricks/python/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 131, in create_run
    return self.store.create_run(
  File "/databricks/python/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 178, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/databricks/python/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/databricks/python/lib/python3.10/site-packages/mlflow/utils/databricks_utils.py", line 437, in get_databricks_host_creds
    config = provider.get_config()
  File "/databricks/python/lib/python3.10/site-packages/databricks_cli/configure/provider.py", line 134, in get_config
    raise InvalidConfigurationError.for_profile(None)
databricks_cli.utils.InvalidConfigurationError: You haven't configured the CLI yet! Please configure by entering `/tmp/tmpjgk87upc/train.py configure`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2471) of binary: /databricks/python/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/databricks/python/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/databricks/python/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/databricks/python/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/databricks/python/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/databricks/python/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/databricks/python/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/tmp/tmpjgk87upc/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-18_14:19:59
  host      : 0915-054331-qrxpquk4-10-0-166-168
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2471)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @nathan-az could you file a support ticket in Databricks to ensure that you get the appropriate team that can help to diagnose and resolve this issue for you?

**Comment by nathan-az** [comment]
The solution here was that the worker processes are not setup to connect to the MLFlow instance automatically like the driver is. I had to pass through the host and token as arguments to the script, and set the `DATABRICKS_TOKEN` and `DATABRICKS_HOST` environment variables inside the process.

If your MLFlow instance is in the same Databricks workspace and you are using a notebook as an entrypoint to the distributed code, you can use `db_token = dbutils.notebook.entry_point.getDbutils().notebook().getContext().apiToken().get()` to pass through a working token. Alternatively your org may store a token as a secret, especially in the case where MLFlow is [hosted in another workspace](https://docs.databricks.com/en/machine-learning/manage-model-lifecycle/multiple-workspaces.html).

**Comment by Run542968** [comment]
Hi, @nathan-az, I met the same issue. 
May I ask how you set the `host and tokens` in Python scripts (.py file)? And how you set the DATABRICKS_TOKEN and DATABRICKS_HOST in environment? 
Thank you for your help.

**Comment by nathan-az** [comment]
Hey @Run542968 - it's been a while since I followed this pattern.

From memory, I believe I:
1. Pass the `DATABRICKS_HOST` and `DATABRICKS_TOKEN` through the `kwargs`, see the [docs](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.ml.deepspeed.deepspeed_distributor.DeepspeedTorchDistributor.html).
2. In the training code, set environment variables as you usually would, i.e.
  ```py
os.environ["DATABRICKS_HOST"] = databricks_host
os.environ["DATABRICKS_TOKEN"] = databricks_token
  ```

Apologies if this doesn't work - I'm really just speculating on how I got this running originally!

**Comment by Run542968** [comment]
> Hey @Run542968 - it's been a while since I followed this pattern.
> 
> From memory, I believe I:
> 
> 1. Pass the `DATABRICKS_HOST` and `DATABRICKS_TOKEN` through the `kwargs`, see the [docs](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.ml.deepspeed.deepspeed_distributor.DeepspeedTorchDistributor.html).
> 2. In the training code, set environment variables as you usually would, i.e.
> 
> ```python
> os.environ["DATABRICKS_HOST"] = databricks_host
> os.environ["DATABRICKS_TOKEN"] = databricks_token
> ```
> 
> Apologies if this doesn't work - I'm really just speculating on how I got this running originally!

I will give it a try. Thank you！
