### ISSUE TITLE
OpenAI - inference parameters

### ISSUE THREAD

**Issue by gvelimir** [mlflow/mlflow#9678]
I am using a standard way (not by Langchain, nor with AI Gateway) of logging and registering an OpenAI chat completion model. How can I use the loaded model with parameters such as temperature, max_tokens or request_timeout? Just providing them as additional arguments or inside a param dictionary in the predict function does not seem to work.

**Comment by BenWilson2** [comment]
Hi @gvelimir the usage of inference parameter overrides is currently not supported for the OpenAI flavor. 
The only supported means of overriding these values is at model save / log time. Can you try to provide those overrides when saving the model so that when the model is loaded they are applied via the .yaml load parser?

**Comment by gvelimir** [comment]
Thx, I was not aware that it is not supported because there is a param argument in the function and I guessed that I can pass the original params.

I will try to provide them when I log the model.

**Comment by santiagxf** [comment]
This will be addressed once we merge #9507

**Comment by gvelimir** [comment]
FYI @BenWilson2 your suggestion works. Indeed there are no issues related to passing the parameters on log_model, I just hesitated to even try it that way because I will have to store another version every time I change a parameter's value.

Thx again.

**Comment by BenWilson2** [comment]
We'll get the 'real fix' as @santiagxf mentioned merged in time for the next release of MLflow!

**Comment by BenWilson2** [comment]
The ``model_params`` implementation has been merged into master branch and will be included in the upcoming MLflow 2.8.0 release :)

**Comment by santiagxf** [comment]
@gvelimir this has been merged this week.
