### ISSUE TITLE
_get_file_store() ignores 'netloc' in file:// URIs

### ISSUE THREAD

**Issue by dbczumar** [mlflow/mlflow#971]
### Describe the problem
MLflow uses the `FileStore` to save run metadata when the tracking URI has the `file:` scheme. File URIs have the following structure, as interpreted by `urllib.parse.urlparse`:

```
file://<netloc>/<path>
```

Currently, MLflow's [_get_file_store()](https://github.com/mlflow/mlflow/blob/7195f298814e9580311311d715a09425269d6b43/mlflow/tracking/utils.py#L145) method only parses the `path` component of the URI, ignoring the `netloc` entirely. This results in an incorrect output location for *relative* URIs (absolute URIs seem to work because the `netloc` is interpreted to be empty)

### Source code / logs
Reproduce by running the following code from the MLflow repository root:

```sh
export MLFLOW_TRACKING_URI="file://tmp/mydir"
mlflow run examples/sklearn_elasticnet_wine -P alpha=0.7
```

Notice that the `tmp` prefix is ignored from the output directory. The `FileStore` instead attempts to refer to `/mydir`.

**Comment by dbczumar** [comment]
cc @mparkhe @aarondav

**Comment by mateiz** [comment]
I think it's doing the correct thing unless we want to access another host! See `https://en.wikipedia.org/wiki/File_URI_scheme` for an overview of the URI scheme. The `netloc`, if present, is supposed to be a hostname (so `tmp` would be a hostname in your case). The appropriate way to refer to a local file is either `file:///path` or `file:/path`.

**Comment by dbczumar** [comment]
Ah, good catch. I'll close this.
