### ISSUE TITLE
[FR] Support specifying poetry env

### ISSUE THREAD

**Issue by ggand0** [mlflow/mlflow#9717]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

I manage Python envs with [poetry](https://python-poetry.org/) and I'd like to directly specify the venv created by poetry instead of re-defining python packages in python_env.yaml. Related: https://github.com/mlflow/mlflow/issues/4246

### Motivation

> #### What is the use case for this feature?
Invoking other scripts with `mlflow.run`; for example invoking evaluation script after training in a training script.

> #### Why is this use case valuable to support for MLflow users in general?
It's not desirable to manage another separate python env defined in python_env.yaml if you use a package manager like poetry or pipenv

> #### Why is this use case valuable to support for your project(s) or organization?
It'd be easier to automate ML workflow without having to rewrite scripts with python-fire or click if there's post-training scripts written with argparse

> #### Why is it currently difficult to achieve this use case?
It doesn't seem to be supported. Let me know if there's way to achieve this with mlflow&poetry

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @ggand0 we currently don't have any plans to support another package manager and take on the CI / dev burden to maintain compatibility with that. Is there a way for you to leverage virtualenv along with poetry?

**Comment by ggand0** [comment]
Thanks for your response. AFAIK there's no direct way other than copy-pasting packages manually from `pyproject.toml` to `python_env.yaml`. What I was trying to is invoking other scripts through `mlflow.run` using my poetry env, but I ended up directly calling functions in other modules in my training script.
