### ISSUE TITLE
[DOC-FIX] search run with "attributes.`run_name` IN ('<name>', '<name>')" clause is not actually supported

### ISSUE THREAD

**Issue by simonlsk** [mlflow/mlflow#9719]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

[The search run documentation](https://github.com/mlflow/mlflow/blob/1911991fc885aadd04fe72bebadb4c311ad5c148/docs/source/search-runs.rst?plain=1#L80) specifies that you can search runs by the `run_name` attribute. But as of my tests in `2.7.1`, the tracking server returns the error message:
`[ "Only the 'run_id' attribute supports comparison with a list of quoted string values." ]`. 

### Description of proposal (what needs changing)

Remove the entire section of search by `run_name`, or replace with `=` clause example that works.

**Comment by BenWilson2** [comment]
Thanks for the catch here @simonlsk !

**Comment by simonlsk** [comment]
Should I do as suggested, or are you going to handle this some other way?

**Comment by BenWilson2** [comment]
Removing the entries (or replacing with the supported exact match / wildcard match on equivalency on a single term) would be fine. 
searching on ``attributes.run_name = "my_run%"`` or ``attributes.run_name ILIKE "%my_run%"`` instead of the ``IN`` clause, for instance.

**Comment by simonlsk** [comment]
I mean do you want me to contribute the fix in the docs, or are you taking this?

**Comment by harupy** [comment]
@simonlsk you can take this!
