### ISSUE TITLE
git commit is not displayed for runs in jupyter notebook

### ISSUE THREAD

**Issue by mlisovyi** [mlflow/mlflow#973]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary via pip
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**: 3.5.5
- **npm version (if running the dev UI)**: ?
- **Exact command to reproduce**: `jupyter nbconvert train.ipynb --clear-output --inplace --execute --ExecutePreprocessor.timeout=-1`

### Describe the problem
The github commit (aka "Version" in the UI) is not displayed in the UI for runs performed in the jupyter notebook. I've used the `sklearn_elasticnet_wine` example. 
![Screenshot from 2019-03-10 18-01-40](https://user-images.githubusercontent.com/10157590/54088504-ec2efd00-435e-11e9-98b4-cc1fb7560268.png)
Above is the screenshot of UI showing:
- notebook execution from the command line with the aforementioned command (bottom 3 entries)
- python version execution (2nd from the top)
- function call from inside of the notebook (1st from the top)

Only the python code picks the github commit info

**Comment by aguschin** [comment]
There is a workaround, if it will help someone.

We can specify tags reserved for Mlflow run: https://mlflow.org/docs/latest/tracking.html#system-tags

For example, run in jupyter notebook:
```
    with mlflow.start_run():
        mlflow.set_tag('mlflow.source.git.commit', sha_commit)
```

**Comment by mlwkshops** [comment]
Re-opening the bug. Facing same problem.
