### ISSUE TITLE
Move mlflow/lightgbm.py to mlflow/lightgbm/__init__.py

### ISSUE THREAD

**Issue by chenmoneygithub** [mlflow/mlflow#9738]
Related to #9731 

The motivation is to keep each flavor module in its own directory for consistency. For now we just move it to `__init__.py` for simplicity, but in the future we will think about a better refactoring.

Please check #9692 for a similar PR.

Code pointer: [link](https://github.com/mlflow/mlflow/blob/master/mlflow/lightgbm.py)

If you are using VScode, the file change should be automatically tracked. If the moving is not tracked correctly, you can use `git mv` to do the renaming.

**Comment by timsinashok** [comment]
Hello, I would like to work on this issue. Could you please assign it to me?

**Comment by harupy** [comment]
@timsinashok Thanks!
