### ISSUE TITLE
[BUG] Using mlflow version 2.7.1 and trying to pass prefix using --static-prefix flag but its not working

### ISSUE THREAD

**Issue by kavita1205** [mlflow/mlflow#9778]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow version 2.7.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: linux
- **Python version**: 3.10.13
- **yarn version, if running the dev UI**:

### Describe the problem

I am trying to access mlflow using prefix "/autosense" using flag "--static-prefix /autosense" but getting "404 Not found" error message with blank page.

Below is the parameters being passed in deployment.yaml:
```
          command: 
            - /bin/bash
            - -c
            - mlflow server --host 0.0.0.0 --port ${MLFLOW_PORT} 
            - --static-prefix /autosense
            - --backend-store-uri mysql+pymysql://${MYSQL_USERNAME}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_TCP_PORT}/${MYSQL_DATABASE}
            - --gunicorn-opts '--log-level debug'
            - --default-artifact-root s3://${MLFLOW_BUCKET_NAME}
            - --serve-artifacts
```
<img width="877" alt="image" src="https://github.com/mlflow/mlflow/assets/57555403/1f00f6e3-7a80-4696-abfc-8302fa5b2b11">

Can someone please help me here.

### Steps to reproduce the bug

I have installed mlflow using helm chart.

**Comment by harupy** [comment]
@kavita1205 https://github.com/mlflow/mlflow/pull/9308 might be the cause.

**Comment by harupy** [comment]
@kavita1205 Can you create a repo and ceate all the files required to reproduce this issue?
