### ISSUE TITLE
shutil copyfile does not preserve metadata

### ISSUE THREAD

**Issue by dimitri-voytan** [mlflow/mlflow#9789]
https://github.com/mlflow/mlflow/blob/ca83a3dd71742304df21632d5f2d7152d74b01ac/mlflow/store/artifact/local_artifact_repo.py#L38C26-L38C26

`shutil.copyfile` does not preserve metadata. Consider using `shutil.copy2` which includes some metadata. I am encountering issues in a slurm cluster that uses the group id to manage storage quotas. Files are being copied with my default group id, not the group id I am setting before logging, which is causing the issue.

**Comment by harupy** [comment]
@dimitri-voytan Thanks for reporting, can you create a reproducer?

**Comment by dimitri-voytan** [comment]
Hi @harupy ,

Yes. This illustrates the point using file permissions, rather than group id, which is a little easier to emulate with python alone. You should see that the file permissions are different between the local file and the file logged in the artifact repo. 

```
from mlflow.store.artifact.local_artifact_repo import LocalArtifactRepository
import os


artifact_file = 'my_artifact.txt'
artifact_uri = './artifact_repo'

# Instantiate the local artifact reposity which uses shutil.copyfile to log artifacts
repo = LocalArtifactRepository(artifact_uri=artifact_uri)

# Write a file to disk to log w/ mlflow
with open(artifact_file, 'w+') as my_artifact_file:
    my_artifact_file.write('example artifact \n')
  
# Set the file's permissions to 777 before logging to show how `shutil.copyfile` does not preserve metadata
os.chmod(artifact_file, 0o777)
local_metadata = os.stat(artifact_file)
print(f"file permissions for local metadata: {oct(local_metadata.st_mode)}")

# Log the file into the repo
repo.log_artifact(artifact_file)

# compare to metadata in the artifact repo to the local metadata
repo_metadata = os.stat(os.path.join(artifact_uri, artifact_file))

print(f"file permissions for repo metadata: {oct(repo_metadata.st_mode)}")
```

**Comment by harupy** [comment]
@dimitri-voytan Makes sense. Let me file a PR and see what happens. I think it'll work fine.

**Comment by harupy** [comment]
Filed #9799

**Comment by dimitri-voytan** [comment]
Thanks, I can't think of a situation where it would _not_ make sense to preserve the file metadata, but hopefully this doesn't cause any issues.
