### ISSUE TITLE
Race condition in set_experiment

### ISSUE THREAD

**Issue by jseppanen** [mlflow/mlflow#979]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2
- **Python version**: Python 3.6.6
- **Exact command to reproduce**: mlflow.set_experiment

### Describe the problem

`mlflow.set_experiment("foobar")` can fail if called from more than 1 concurrent worker.

### Source code / logs

Here's the logs from a failed call to `set_experiment` from one worker of a bunch of concurrent training runs:

```
INFO: 'foobar' does not exist. Creating a new experiment
2019/03/11 17:31:08 ERROR mlflow.utils.rest_utils: API request to http://172.17.
0.1:5000/api/2.0/preview/mlflow/experiments/create failed with code 500 != 200, 
retrying up to 2 more times. API response body: {"error_code": "RESOURCE_ALREADY
_EXISTS", "message": "Experiment 'foobar' already exists."}
2019/03/11 17:31:11 ERROR mlflow.utils.rest_utils: API request to http://172.17.
0.1:5000/api/2.0/preview/mlflow/experiments/create failed with code 500 != 200, 
retrying up to 1 more times. API response body: {"error_code": "RESOURCE_ALREADY
_EXISTS", "message": "Experiment 'foobar' already exists."}
2019/03/11 17:31:14 ERROR mlflow.utils.rest_utils: API request to http://172.17.
0.1:5000/api/2.0/preview/mlflow/experiments/create failed with code 500 != 200, 
retrying up to 0 more times. API response body: {"error_code": "RESOURCE_ALREADY_EXISTS", "message": "Experiment 'foobar' already exists."}
Traceback (most recent call last):
...
    mlflow.set_experiment(experiment_name)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 49, in set_experiment
    exp_id = client.create_experiment(experiment_name)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/tracking/client.py", line 101, in create_experiment
    artifact_location=artifact_location,
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 82, in create_experiment
    response_proto = self._call_endpoint(CreateExperiment, req_body)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 58, in _call_endpoint
    host_creds=host_creds, endpoint=endpoint, method=method, json=json_body)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 73, in http_request_safe
    response = http_request(host_creds=host_creds, endpoint=endpoint, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 58, in http_request
    (url, retries))
mlflow.exceptions.MlflowException: API request to http://172.17.0.1:5000/api/2.0/preview/mlflow/experiments/create failed to return code 200 after 3 tries
```

**Comment by hanyucui** [comment]
@jseppanen Can you provide the command lines you used and the code that reproduces the issue? The can save a lot of time.

**Comment by yogeveran** [comment]
I faced this issue as well..
set_experiment fails if multiple processes try to set the same experiment in parallel.
The solution to set experiment before calling the parallel processes doesn't work because set_experiment is non blocking (async) and returns before the experiment is generated.

A suggested fix would be to make set_experiment to wait until the experiment is generated (with possible timeout error).

For now I just have a busy wait loop that throws an error after X seconds.
It queries the mlflow DB every interval Y seconds if the experiment exists.
