### ISSUE TITLE
[DOC-FIX] mlflow.pyfunc.get_model_dependencies() downloads all the artifacts

### ISSUE THREAD

**Issue by Val3nt-ML** [mlflow/mlflow#9809]
### Willingness to contribute

Yes. I can contribute a documentation fix independently.

### URL(s) with the issue

Hello,
Here is the current link of this method documentation : https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html
My issue is that the documentation of the method `mlflow.pyfunc.get_model_dependencies` doesn't specify that it downloads all the artifacts of a given model (not only the `requirements.txt` file), which causes me some troubles (`Connection broken` and `ChunkedEncodingError`) when a large model (about 500MiB) is stored in the artifacts. 

I don't know if it's you're first intention to return all the artifacts or if this method should only download and return the `requirement.txt` file. To this extent, I propose you to add a little description to indicate its behavior. Otherwise, we could imagine to add an input parameter to choose whether the user needs to download all the artifacts or only the requirements.

### Description of proposal (what needs changing)

mlflow.pyfunc.get_model_dependencies(model_uri, format='pip')[[source]](https://mlflow.org/docs/latest/_modules/mlflow/pyfunc.html#get_model_dependencies)

**Proposal ---------------**
Download all the artifacts from the model_uri, store them in a `temp/` folder and return the path of the requirements.txt file of that folder.
**-------------------------**

Parameters
model_uri – The uri of the model to get dependencies from.

format – The format of the returned dependency file. If the "pip" format is specified, the path to a pip requirements.txt file is returned. If the "conda" format is specified, the path to a "conda.yaml" file is returned . If the "pip" format is specified but the model was not saved with a requirements.txt file, the pip section of the model’s conda.yaml file is extracted instead, and any additional conda dependencies are ignored. Default value is "pip".

Returns
The local filesystem path to either a pip requirements.txt file (if format="pip") or a conda.yaml file (if format="conda") specifying the model’s dependencies.

**Comment by harupy** [comment]
We can also document how to dowload only `requirements.txt` if you think that's helpful.

**Comment by Val3nt-ML** [comment]
I understand. Yes, I think that It would be helpful :)

**Comment by Val3nt-ML** [comment]
Maybe you could also download by default only the artifacts that starts with a given prefix like “requirement(s)“ and let the user explicitly provide the list of his/her requirements files.
