### ISSUE TITLE
load pytorch model not working because of model architecture dependency in pickle save

### ISSUE THREAD

**Issue by DanlanChen** [mlflow/mlflow#982]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:0.8.2
- **Python version**: 3.6.5
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
in your documentation:https://www.mlflow.org/docs/latest/python_api/mlflow.pytorch.html
```>>python
>>import torch
>> import mlflow
>> import mlflow.pytorch
>> # set values
>> model_path_dir = ...
>> run_id="96771d893a5e46159d9f3b49bf9013e2"
>> pytorch_model = mlflow.pytorch.load_model(model_path_dir, run_id)
>> y_pred = pytorch_model(x_new_data)
```
this can not be done if you did not import the model architecture class, for example the `Net` class in your pytorch example.

so does your document https://www.mlflow.org/docs/latest/models.html#storage-format, this can not be done as the same reason.
`PyTorch (pytorch)
The pytorch model flavor enables logging and loading PyTorch models. Model is completely stored in .pth format using torch.save(model) method. Given a directory containing a saved model, you can log the model to MLflow via log_saved_model. The saved model can then be loaded for inference via mlflow.pyfunc.load_pyfunc(). For more information, see mlflow.pytorch.
`

This is a common problem in torch.save and torch.load problem, but if you do not have solution for this, it is better to document in your doc to make it accurate.

**Comment by DanlanChen** [comment]
how do you save your model @hanyucui

**Comment by hanyucui** [comment]
I was using this [example](https://github.com/mlflow/mlflow/blob/ae159840d1fa8187aa106d6e27b4a78884aeae6e/mlflow/pytorch/__init__.py#L100).

FYI I was using the tip since that's more convenient for me. Not sure it that makes a difference.

**Comment by DanlanChen** [comment]
hello @hanyucui  your link is not very clear, if you create a Model class inside the load_model script, you do not need to call the import model, it seems that this problem is still unsolved.

**Comment by hanyucui** [comment]
@DanlanChen Can you provide code that reproduces the issue? That would be very helpful.

**Comment by DanlanChen** [comment]
you can produce it in the pytorch example folder:https://github.com/mlflow/mlflow/tree/master/examples/pytorch, after you trained it, you load it in a separate folder code.
