### ISSUE TITLE
Enable more `SIM` rules

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9834]
## Summary

Enable more `SIM` rules: https://docs.astral.sh/ruff/rules/#flake8-simplify-sim

## Rules to enable

- [x] SIM103
- [x] SIM108
- [x] SIM114
- [x] SIM115
- [x] SIM210
- [ ] SIM910

## Line to update

https://github.com/mlflow/mlflow/blob/74a99a4adea2882a50f0ba22e06b425c096ba023/pyproject.toml#L51

**Comment by harupy** [comment]
cc @TomeHirata

**Comment by harupy** [comment]
@TomeHirata Can you post a comment on this issue so I can assign this task to you?

**Comment by TomeHirata** [comment]
@harupy Hi, can you assign this ticket to me?

**Comment by harupy** [comment]
Assigned!

**Comment by harupy** [comment]
@TomeHirata Added a few more rules.

**Comment by TomeHirata** [comment]
Sure, happy to work on it.
