### ISSUE TITLE
[BUG]Metrics from tsv artefacts not properly sorted on UI for integers.

### ISSUE THREAD

**Issue by jrakotobe** [mlflow/mlflow#9837]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.7.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
- **Python version**: 3.10.8
- **yarn version, if running the dev UI**: 1.22.19

### Describe the problem

Successfuly logged a .tsv file as an artifact containing my metrics. One of the metric is "number" which contain integers. The problem happen when I use the sorting button on that artifact. It gets ordered as strings:

1 11 12 2 23

### Steps to reproduce the bug

Log an artefact .tsv containing metrics (ex: 1 11 12 2 23) 
Sort by that metric

### Is the console panel in DevTools showing errors relevant to the bug?

No

### Does the network panel in DevTools contain failed requests relevant to the bug?

No

**Comment by harupy** [comment]
@jrakotobe Thanks for reporting this issue. Can you create a minimum python to log the data that can reproduce the issue and take a screen recording of the issue?

**Comment by harupy** [comment]
I was able to reproduce:

```python
import mlflow

with mlflow.start_run():
    csv_text = "a,b,c\n1,2,3\n11,22,33\n4,5,6"
    mlflow.log_text(csv_text, "my_csv_text.csv")
```

**Comment by harupy** [comment]
@jrakotobe I filed #9852.

**Comment by jrakotobe** [comment]
Great! Thank you @harupy !
