### ISSUE TITLE
[BUG] UI not loading in the browser

### ISSUE THREAD

**Issue by yuvalmaromyala** [mlflow/mlflow#9843]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.7.1

### System information

Windows 10
Python 3.8.5

### Describe the problem

I've got a completely local configuration set up with an sqlite backend store,  which has been working perfectly well for months.  Since yesterday, I'm not able to view anything in the UI in the browser.  The server itself is still working, because I can access it programmatically from my python scripts just as before.  

The browser is showing the "Something went wrong" screen, see attached.
![image](https://github.com/mlflow/mlflow/assets/91654493/a76b4b10-3103-4379-9b9f-e7b4c7a29c57)

I need to point out that this problem started when I tried to configure tracking via a remote server, being Azure Machine Learning, and I was playing around with the tracking URI.  Regrettably, I didn't stop my local server while I was experimenting with this, so I suspect this has caused my local setup to not work properly, although as I mentioned above, programmatically I can still do everything, it's only the UI that is a problem.

Other points to note:
- My environment variable MLFLOW_TRACKING_URI is still showing the correct value (http://localhost:5000)
- I've tried clearing the browser cache etc.
- I've loaded the sqlite DB in a separate DB viewer and the data looks fine

### Steps to reproduce the bug

I guess you would reproduce the bug by setting up a local config with sqlite and then modify the tracking URI to remote server while the local server is still running...

This is how I launch my local server:
```
mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host 0.0.0.0
```

And the address I put into the browser is:
```
http://localhost:5000
```

### Code to generate data required to reproduce the bug

```python

import mlflow
mlflow.set_tracking_uri('azureml://....')
mlflow.set_experiment('test_azureml_mlflow')

```

### Is the console panel in DevTools showing errors relevant to the bug?

```
:5000/ajax-api/2.0/preview/mlflow/experiments/list:1     Failed to load resource: the server responded with a status of 404 (NOT FOUND)
FetchUtils.js:78 Fetch failed:  Response
Xd @ FetchUtils.js:78
RequestStateWrapper.js:93 ERROR Array(1)
aV @ RequestStateWrapper.js:93
react-dom.production.min.js:216 Error: A request error occurred.
    at aV (RequestStateWrapper.js:94:9)
    at n.value (RequestStateWrapper.js:77:9)
    at n.value (RequestStateWrapper.js:87:17)
    at Ua (react-dom.production.min.js:187:188)
    at za (react-dom.production.min.js:186:173)
    at Vs (react-dom.production.min.js:269:427)
    at kl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at Sl (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163)
as @ react-dom.production.min.js:216
AppErrorBoundary.js:19 Error: A request error occurred.
    at aV (RequestStateWrapper.js:94:9)
    at n.value (RequestStateWrapper.js:77:9)
    at n.value (RequestStateWrapper.js:87:17)
    at Ua (react-dom.production.min.js:187:188)
    at za (react-dom.production.min.js:186:173)
    at Vs (react-dom.production.min.js:269:427)
    at kl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at Sl (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163) Object
value @ AppErrorBoundary.js:19
contentScript.bundle.js:122 i18next: languageChanged en-GB
contentScript.bundle.js:122 i18next: initialized Object
:5000/#/:1 Uncaught (in promise) e
contentScript.bundle.js:103 Object
```

### Does the network panel in DevTools contain failed requests relevant to the bug?

```
# Request URL
http://localhost:5000/ajax-api/2.0/preview/mlflow/experiments/list

# Status Code
404

# Remote Address
127.0.0.1:5000

# Response
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

# Request Headers
GET /ajax-api/2.0/preview/mlflow/experiments/list HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Cookie: mp_49719c4dbff298b1e6c9adca527948b5_mixpanel=%7B%22distinct_id%22%3A%20%22%24device%3A18b023bc0af28a-027219d079f653-26031e51-1fa400-18b023bc0af28a%22%2C%22%24device_id%22%3A%20%2218b023bc0af28a-027219d079f653-26031e51-1fa400-18b023bc0af28a%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D
Host: localhost:5000
Referer: http://localhost:5000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

```

**Comment by harupy** [comment]
@yuvalmaromyala Looks like UI is still 1.28.0. Can you upgrade it?

<img width="243" alt="image" src="https://github.com/mlflow/mlflow/assets/17039389/a8b7c99f-52e5-4a89-95da-5b75168f2e7b">

We removed `/ajax-api/2.0/preview/mlflow/experiments/list` in MLflow 2.0.

**Comment by harupy** [comment]
what does `mlflow --version` print out?

**Comment by yuvalmaromyala** [comment]
mlflow --version shows 2.7.1

regarding your question about the UI requests - did you look at the output I shared from devtools?

**Comment by harupy** [comment]
I see, it sends requests to `http://localhost:5000/ajax-api/2.0/preview/mlflow/experiments/list`

**Comment by yuvalmaromyala** [comment]
no idea...

**Comment by harupy** [comment]
@yuvalmaromyala Can you run `mlflow server` (no options) and open `http://127.0.0.1:5000`?

**Comment by yuvalmaromyala** [comment]
Just tried it, getting the same error.
![image](https://github.com/mlflow/mlflow/assets/91654493/3dee041a-cff9-4b62-8c76-8d5e64dd8009)

**Comment by harupy** [comment]
@yuvalmaromyala what happens if you change the port?

```
mlflow server --port 5001
```

**Comment by yuvalmaromyala** [comment]
same error

**Comment by harupy** [comment]
can you try `pip install --force-reinstall mlflow`?

**Comment by yuvalmaromyala** [comment]
do I need to back up any data before doing this?

**Comment by harupy** [comment]
you're already using 2.7.1, right? If so, I don't think you need t bck up.

**Comment by yuvalmaromyala** [comment]
that's right, I'm on 2.7.1, but I've done a bit of backup just in case.
ok, will give it a go now.

**Comment by yuvalmaromyala** [comment]
no luck.... getting the same error

**Comment by harupy** [comment]
> I need to point out that this problem started when I tried to configure tracking via a remote server

What do you mean by a remote server?

**Comment by yuvalmaromyala** [comment]
I was trying to set up Azure Machine Learning as a way to start tracking experiments and registering models

**Comment by harupy** [comment]
> I didn't stop my local server while I was experimenting with this

Your local server has been for months without being stopped?

**Comment by yuvalmaromyala** [comment]
No, it did get stopped occasionally when I rebooted the computer

**Comment by harupy** [comment]
can you unset MLFLOW_TRACKING_URI?

**Comment by yuvalmaromyala** [comment]
you mean unset the environment variable?

**Comment by harupy** [comment]
yes

**Comment by yuvalmaromyala** [comment]
still getting the error

**Comment by harupy** [comment]
can you create a new python environment (conda, venv, etc.) and try the same thing in that environment?

**Comment by yuvalmaromyala** [comment]
ok doing it now

**Comment by yuvalmaromyala** [comment]
and do a standard install for mlflow? ie 
``` pip install mlflow```
?

**Comment by yuvalmaromyala** [comment]
oh, actually my new env already has it....

**Comment by yuvalmaromyala** [comment]
ok, so now shall I try to start a server?

**Comment by harupy** [comment]
> actually my new env already has it

mlflow is not a built-in library. This is strange.

**Comment by yuvalmaromyala** [comment]
yeah i wasn't expecting it...

**Comment by yuvalmaromyala** [comment]
I'll create another env

**Comment by harupy** [comment]
did you activate the environment?

**Comment by harupy** [comment]
you can try `python -m mlflow server` instead `mlflow server`.

**Comment by yuvalmaromyala** [comment]
it's there again...

this is what I did:
```
conda create -n test2 python=3.8.5
conda activate test2
pip show mlflow
```

and it's displaying:

![image](https://github.com/mlflow/mlflow/assets/91654493/129e86b6-56e5-4f59-81f8-1ef97c7bc197)

**Comment by harupy** [comment]
make sure to use `python -m pip`

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/67a60a0d-4813-4d36-bc5e-0798b9d3715f)

**Comment by harupy** [comment]
looks like the environment is not activated

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/6776efd4-289f-430c-933f-fed2c023d533)

**Comment by harupy** [comment]
but the location looks weird.

**Comment by yuvalmaromyala** [comment]
yeah... it's like it's using a "global" installation?

**Comment by harupy** [comment]
can you run `python -c 'import sys; print(sys.executable)'`?

**Comment by harupy** [comment]
> yeah... it's like it's using a "global" installation?


yes

**Comment by yuvalmaromyala** [comment]
> can you run `python -c 'import sys; print(sys.executable)'`?

getting a syntax error. remember I'm running in windows:

![image](https://github.com/mlflow/mlflow/assets/91654493/66b664de-24fa-43b9-85a2-dc946796553a)

**Comment by harupy** [comment]
then try `python -c "import sys; print(sys.executable)"`

**Comment by yuvalmaromyala** [comment]
yeah that works, the output is:
```
C:\Users\wils_ymarom\Anaconda3\envs\test2\python.exe
```

**Comment by harupy** [comment]
can you run `python -m pip uninstall mlflow`?

**Comment by yuvalmaromyala** [comment]
ok, it's gone now. how should I install it?

**Comment by harupy** [comment]
python -m pip instlal mlflow

**Comment by harupy** [comment]
before install, please make sure `mlflow sever` is no longer available.

**Comment by yuvalmaromyala** [comment]
yeah actually it's still available...  ??!!

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/28603bd2-ca6b-4a66-8630-4c6e465d707b)

**Comment by harupy** [comment]
please run `where mlflow` to see where the executable is.

**Comment by yuvalmaromyala** [comment]
C:\Users\wils_ymarom\Anaconda3\Scripts\mlflow.exe

how strange....

**Comment by yuvalmaromyala** [comment]
it's got yesterday's timestamp

**Comment by harupy** [comment]
can you remove it?

**Comment by yuvalmaromyala** [comment]
done. and now I can't start the server.
now shall I install it using:
```
python -m pip instlal mlflow
```

**Comment by harupy** [comment]
yes

**Comment by yuvalmaromyala** [comment]
done.
now start the server?

**Comment by harupy** [comment]
yes

**Comment by yuvalmaromyala** [comment]
any particular way?

**Comment by harupy** [comment]
python -m mlflow server

**Comment by yuvalmaromyala** [comment]
still getting that error.
shall I set the env variable?

**Comment by harupy** [comment]
no

**Comment by yuvalmaromyala** [comment]
actually the terminal I was in already had it set, I'll remove it

**Comment by yuvalmaromyala** [comment]
no good

**Comment by harupy** [comment]
are you sure you're NOT running another mlflow server on your machine?

**Comment by yuvalmaromyala** [comment]
pretty sure... is there a way to check?

**Comment by harupy** [comment]
https://superuser.com/questions/18830/is-there-a-command-in-windows-like-ps-aux-in-unix

**Comment by yuvalmaromyala** [comment]
yeah don't see anything to suggest there's another one running, doing a reboot just in case

**Comment by yuvalmaromyala** [comment]
still getting the same error....

**Comment by harupy** [comment]
have you tried https://www.gavel.io/resources/what-is-a-hard-refresh-how-to-do-a-hard-refresh-in-any-browser?

**Comment by yuvalmaromyala** [comment]
no, but tried it just now, didn't help.

**Comment by harupy** [comment]
what happens if you install mlflow==1.28?

**Comment by yuvalmaromyala** [comment]
I'll try

**Comment by yuvalmaromyala** [comment]
no good.

btw that version installs as a standalone package, not a python package, so it created a script in that Anaconda folder as we had before.

**Comment by harupy** [comment]
I think it should install python package and a script for CLI.

**Comment by yuvalmaromyala** [comment]
but it doesn't run with python -m

**Comment by harupy** [comment]
then remove `python -m` and just run `mlflow server`

**Comment by yuvalmaromyala** [comment]
I did, same error

**Comment by harupy** [comment]
what does mlflow --version print out?

**Comment by yuvalmaromyala** [comment]
1.28.0

**Comment by harupy** [comment]
I have no idea what's goign on.

**Comment by yuvalmaromyala** [comment]
Could it be that yesterday when I installed the `azureml-mlflow` package is broke something?

**Comment by harupy** [comment]
could be.

**Comment by harupy** [comment]
let's uninstall it.

**Comment by yuvalmaromyala** [comment]
well it's not in my new env, but I'll go into the old one and uninstall it

**Comment by harupy** [comment]
You can remove the old env.

**Comment by yuvalmaromyala** [comment]
I uninstalled it from the old env, didn't help

**Comment by yuvalmaromyala** [comment]
> You can try removing the old env.

I was working in the base env before...

**Comment by harupy** [comment]
can you reinstall conda?

**Comment by yuvalmaromyala** [comment]
that's a bit drastic, do you think we're out of other options?

**Comment by harupy** [comment]
what does localhost:5000 show if mlflow server is not running?

**Comment by harupy** [comment]
stop mlflow serve and open localhost:5000

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/b635c66d-e32b-4597-8ec7-b56223af5aa3)

**Comment by harupy** [comment]
got it

**Comment by harupy** [comment]
you're using 1.28 now, right? still getting the NOT FOUND error?

**Comment by yuvalmaromyala** [comment]
yes running 1.28, getting the "something went wrong" error:

![image](https://github.com/mlflow/mlflow/assets/91654493/3d207916-b4f5-4c51-a632-853050d938ac)

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/d0824d9f-e90e-4856-8570-58ebaf7a8f34)

**Comment by harupy** [comment]
what does your terminal looks like?

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/40dbcea2-aa69-4d83-b124-00108c50fc16)

**Comment by harupy** [comment]
can you run `curl http://localhost:5000/ajax-api/2.0/preview/mlflow/experiments/list`?

**Comment by harupy** [comment]
and run `mlflow --version`

**Comment by yuvalmaromyala** [comment]
> mlflow --version

mlflow, version 1.28.0

**Comment by harupy** [comment]
did you run `curl http://localhost:5000/ajax-api/2.0/preview/mlflow/experiments/list`?

**Comment by yuvalmaromyala** [comment]
Yep:
```
curl : <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
At line:1 char:1
+ curl http://localhost:5000/ajax-api/2.0/preview/mlflow/experiments/li ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by harupy** [comment]
If you don't have curl, you can use the requests package in python.

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/504634f2-af28-4c81-8031-cdce6b8f6cf7)

**Comment by harupy** [comment]
try `http://127.0.0.1:5000/ajax-api/2.0/preview/mlflow/experiments/list` next

**Comment by yuvalmaromyala** [comment]
same error

**Comment by harupy** [comment]
try `http://127.0.0.1:5000/ajax-api/2.0/mlflow/experiments/list`

**Comment by yuvalmaromyala** [comment]
same error

**Comment by yuvalmaromyala** [comment]
same for `http://localhost:5000/ajax-api/2.0/mlflow/experiments/list`

**Comment by harupy** [comment]
strange.

**Comment by harupy** [comment]
what about `http://127.0.0.1:5000/ajax-api/2.0/preview/mlflow/runs/search`?

**Comment by yuvalmaromyala** [comment]
same

**Comment by harupy** [comment]
what about `http://127.0.0.1:5000`?

**Comment by yuvalmaromyala** [comment]
```
<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><link rel="shortcut icon" href="./static-files/favicon.ico"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="./static-files/manifest.json"/><title>MLflow</title><script defer="defer" src="static-files/static/js/main.d843a4d8.js"></script><link href="static-files/static/css/main.d148570b.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><div id="modal"></div></body></html>
```

**Comment by yuvalmaromyala** [comment]
![image](https://github.com/mlflow/mlflow/assets/91654493/7f93302e-7005-4e4d-935c-694b471f513a)

**Comment by yuvalmaromyala** [comment]
In powershell I get a different error:
![image](https://github.com/mlflow/mlflow/assets/91654493/82c10af9-6c36-49cb-b933-6dfc51512f2b)

**Comment by harupy** [comment]
Not found for `http://127.0.0.1:5000/ajax-api/2.0/preview/mlflow/runs/search` is strange.

**Comment by yuvalmaromyala** [comment]
I need to go now..... Is this something you can look into further?

**Comment by harupy** [comment]
I've tried everything I came up with.

**Comment by yuvalmaromyala** [comment]
thank you so much for your help I really appreciate it!!

**Comment by yuvalmaromyala** [comment]
so would you suggest to reinstall conda, or are there other avenues I can try?

**Comment by harupy** [comment]
we should dig into why `http://127.0.0.1:5000/ajax-api/2.0/preview/mlflow/runs/search` is not found.

**Comment by harupy** [comment]
can you also check environment varibles?

**Comment by yuvalmaromyala** [comment]
you mean `MLFLOW_TRACKING_URI`? it's definitly not set now.

**Comment by harupy** [comment]
Can you run `SET`?

**Comment by yuvalmaromyala** [comment]
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\wils_ymarom\AppData\Roaming
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_10004_JYYZJSXOBSZOGRBK
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=ARR-TFU60I7LTD0
ComSpec=C:\WINDOWS\system32\cmd.exe
CONDA_BAT=C:\Users\wils_ymarom\Anaconda3\condabin\conda.bat
CONDA_DEFAULT_ENV=test2
CONDA_EXE=C:\Users\wils_ymarom\Anaconda3\Scripts\conda.exe
CONDA_PREFIX=C:\Users\wils_ymarom\Anaconda3\envs\test2
CONDA_PREFIX_1=C:\Users\wils_ymarom\Anaconda3
CONDA_PROMPT_MODIFIER=(test2)
CONDA_PYTHON_EXE=C:\Users\wils_ymarom\Anaconda3\python.exe
CONDA_SHLVL=2
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\wils_ymarom
LOCALAPPDATA=C:\Users\wils_ymarom\AppData\Local
LOGONSERVER=\\PPADS02
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\wils_ymarom\OneDrive - Arriba Group
OneDriveCommercial=C:\Users\wils_ymarom\OneDrive - Arriba Group
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
Path=C:\Users\wils_ymarom\Anaconda3\envs\test2;C:\Users\wils_ymarom\Anaconda3\envs\test2\Library\mingw-w64\bin;C:\Users\wils_ymarom\Anaconda3\envs\test2\Library\usr\bin;C:\Users\wils_ymarom\Anaconda3\envs\test2\Library\bin;C:\Users\wils_ymarom\Anaconda3\envs\test2\Scripts;C:\Users\wils_ymarom\Anaconda3\envs\test2\bin;C:\Users\wils_ymarom\Anaconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Git\cmd;C:\Users\wils_ymarom\AppData\Local\Microsoft\WindowsApps;C:\Users\wils_ymarom\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\wils_ymarom\Anaconda3;C:\Users\wils_ymarom\Anaconda3\Scripts;C:\Users\wils_ymarom\Anaconda3\Library\bin;C:\Users\wils_ymarom\Documents\Repos\arriba_sandbox
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0c
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=(test2) $P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PYTHONPATH=C:\Users\wils_ymarom\OneDrive - Arriba Group\Documents\Repos\arriba_sandbox
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\WILS_Y~1\AppData\Local\Temp
TMP=C:\Users\WILS_Y~1\AppData\Local\Temp
USERDNSDOMAIN=REHAB.NET
USERDOMAIN=REHAB
USERDOMAIN_ROAMINGPROFILE=REHAB
USERNAME=wils_ymarom
USERPROFILE=C:\Users\wils_ymarom
windir=C:\WINDOWS
ZES_ENABLE_SYSMAN=1
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.83.0
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=c:\Users\wils_ymarom\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\wils_ymarom\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
VSCODE_GIT_ASKPASS_MAIN=c:\Users\wils_ymarom\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js  
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-f657c453b7-sock

**Comment by gabrielfu** [comment]
@harupy let me try

**Comment by harupy** [comment]
@gabrielfu Thanks! Can you try the following?

1. create a fresh python environment
2. install mlflow 1.28
3. run `mlflow server`
4. open UI

**Comment by harupy** [comment]
`curl http://127.0.0.1:5000/ajax-api/2.0/preview/mlflow/experiments/list` worked fine on Windows:

<img width="1310" alt="image" src="https://github.com/mlflow/mlflow/assets/17039389/43ade164-1b64-42cb-ad0c-4ca6fc73032a">

**Comment by harupy** [comment]
@gabrielfu thanks for the confirmation! does UI render fine?

**Comment by gabrielfu** [comment]
@harupy yup no error.

I think the key point is why OP has 1.28 UI and 2.7.1 server, and 1.28 is requesting an endpoint that 2.7.1 doesn't support?

![image](https://github.com/mlflow/mlflow/assets/22888849/89ef3378-5482-47ec-b062-0ce35c816b5e)

**Comment by gabrielfu** [comment]
![image](https://github.com/mlflow/mlflow/assets/22888849/56c5171e-269e-4c98-97d6-23a634cd68c3)

**Comment by harupy** [comment]
I think the key points are

- Where does 1.28 UI comes from. If we install mlflow 2.7.1, and run `mlflow server`, `2.7.1` should show up on the top-left.
- Why `http://localhost:5000/ajax-api/2.0/mlflow/experiments/list` fails with mlflow 1.28 on @yuvalmaromyala's machine, but doesn't on ours.

**Comment by yuvalmaromyala** [comment]
Thanks both for continuing to look into this! Just to remind you - it used to work absolutely fine on my machine, the problems started yesterday when I started playing around trying to configure mlflow for azure-ml so it most likely has something to do with that....

**Comment by gabrielfu** [comment]
guessing from the above conversations, it's possible the new conda env inheriting mlflow from the base env? 

can OP try deactivating all conda envs, use python's built-in `venv` for fresh mlflow 2.7.1, and then just copy `sqlite:///mlflow.db` & `./artifacts` from the old env? i believe this should avoid the 1.28 from unknown source?

**Comment by harupy** [comment]
> I started playing around trying to configure mlflow for azure-ml

can you elaborate on what you did?

**Comment by yuvalmaromyala** [comment]
Yes, so  I pip installed azureml-mlflow in my existing env.

Then I ran the following two lines in a Jupiter notebook:
```
mlflow.set_tracking_uri('azureml://...')
mlflow.set_experiment('test_azureml_mlflow')
```

The URI I obatined from the Azure ML console on the web.

**Comment by harupy** [comment]
@yuvalmaromyala can you rum `pip uninstall mlflow-skinny` in the old env?

**Comment by harupy** [comment]
This command can reproduce the same error:

```
docker run --rm -w /mlflow -p 5000:5000 python:3.8 bash -c 'pip install mlflow==1.28 && pip install azureml-mlflow && mlflow server --host 0.0.0.0 --gunicorn-opts "--log-level debug"'
```

<img width="2035" alt="image" src="https://github.com/mlflow/mlflow/assets/17039389/477c1a63-577a-4237-8e72-ac7f276fbea3">

**Comment by harupy** [comment]
@yuvalmaromyala please run `pip list` and check if `mlflow-skinny` is installed? If it is, run `pip uninstall mlflow-skinny` to uninstall it. After that, you can install mlflow again.

**Comment by yuvalmaromyala** [comment]
ok I've uninstalled `mlflow-skinny `

**Comment by yuvalmaromyala** [comment]
mlflow is still installed there, you want me to uninstall it as well and re-install?

**Comment by harupy** [comment]
Let's uninstall it.

**Comment by yuvalmaromyala** [comment]
ok i've un-installed and installed it

**Comment by harupy** [comment]
can you share the output of `pip list`?

**Comment by yuvalmaromyala** [comment]
MarkupSafe                         2.1.3
matplotlib                         3.7.3
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mlflow                             2.7.1
mock                               4.0.2
more-itertools                     8.6.0
mpmath                             1.1.0
msal                               1.24.1
msal-extensions                    1.0.0
msgpack                            1.0.0
msrest                             0.7.1
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.0.8
nest-asyncio                       1.4.2
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.24.4
numpydoc                           1.1.0
oauthlib                           3.2.2
olefile                            0.46
openpyxl                           3.0.5
packaging                          20.4
pandas                             1.1.3
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             10.0.1
pip                                20.2.4
pkginfo                            1.6.1
pluggy                             0.13.1
ply                                3.11
portalocker                        2.8.2
prometheus-client                  0.8.0
prometheus-flask-exporter          0.20.3
prompt-toolkit                     3.0.8
protobuf                           4.24.4
psutil                             5.7.2
py                                 1.9.0
pyarrow                            13.0.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.2
PyJWT                              2.8.0
pylint                             2.6.0
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          3.1.1
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             0.0.0
python-dateutil                    2.8.2
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             6.0.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.1
qtconsole                          4.7.7
QtPy                               1.9.0
querystring-parser                 1.2.4
regex                              2020.10.15
requests                           2.31.0
requests-oauthlib                  1.3.1
rope                               0.18.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.17.2
scikit-learn                       1.3.1
scipy                              1.10.1
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         50.3.1.post20201107
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.16.0
smmap                              5.0.1
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.4.40
sqlparse                           0.4.4
statsmodels                        0.12.0
sympy                              1.6.2
tables                             3.6.1
tabulate                           0.9.0
tblib                              1.7.0
terminado                          0.9.1
testpath                           0.4.4
threadpoolctl                      3.2.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
tornado                            6.0.4
tqdm                               4.50.2
traitlets                          5.0.5
typing-extensions                  4.8.0
tzdata                             2023.3
ujson                              4.0.1
unicodecsv                         0.14.1
urllib3                            2.0.6
waitress                           2.1.2
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   1.6.3
werkzeug                           3.0.0
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.3.7
xlwings                            0.20.8
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.17.0
zope.event                         4.5.0
zope.interface                     5.1.2

**Comment by harupy** [comment]
can you run `mlflow server`?

**Comment by yuvalmaromyala** [comment]
OMG it's working!!

**Comment by harupy** [comment]
Awesome!

**Comment by yuvalmaromyala** [comment]
Thank you so much, it's such a relief!!!

**Comment by yuvalmaromyala** [comment]
The UI in this newer version looks quite different! Looking forward to exploring it.
