### ISSUE TITLE
Remove log_metric, log_param, set_tag methods from AbstractStore & subclasses

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#985]
As discussed in #955, the single-entry `log_metric`, `log_param`, `set_tag` AbstractStore APIs are only used by the client/OSS server. As such, we might as well eliminate them entirely (from AbstractStore and its subclasses FileStore, RestStore, and SQLAlchemyStore) in favor of calling into the `log_batch` AbstractStore method.

**Comment by acroz** [comment]
As discussed in #955, I agree with not having the single-value methods be required to be implemented in implementations of the `AbstractStore`.

I think there should either be:

1. Implementations of the single-value methods in `AbstractStore` that proxy calls to `log_batch`; or
2. The `MlflowClient` calls `log_batch` directly and the single-value methods in `FileStore` etc. get prefixed with underscores to reflect their status as implementation details.

It's probably worth noting that with #881 merged, having the single-value methods in the public API of tracking stores affects third party plugin developers (hence why in option 2 above I suggest making the single-value methods private - the stores in MLflow itself are effectively the reference implementation).

**Comment by smurching** [comment]
@acroz yep makes sense - I'm in favor of 2, where additionally we can remove the single-value methods in `FileStore` entirely and (in the Python client APIs) call `log_batch` directly. In this scenario we'd have something like:

Fluent API:
* `log_metric`, `log_metrics`, `log_param`, `log_params`, `set_tag`, `set_tags`, `log_batch`, continue to call into their client API equivalents (no code change required)

Client API:
* All client logging APIs besides `log_batch` (`log_metric`, `log_metrics`, `log_param`, `log_params`, `set_tag`, `set_tags`) call into `MlflowClient.log_batch`
* `MlflowClient.log_batch` calls into `AbstractStore.log_batch`

AbstractStore & subclasses (FileStore, RestStore, SQLAlchemyStore):
* Remove `log_metric`, `log_param`, `set_tag` as they're no longer used. Note that this change is a first step towards deprecating the single-entry LogMetric, LogParam, SetTag REST APIs entirely in MLflow 1.0 (if we choose to do so), as user code will now only call into the LogBatch API via the RestStore

**Comment by acroz** [comment]
@smurching LGTM
