### ISSUE TITLE
Move mlflow/prophet.py to mlflow/prophet/__init__.py

### ISSUE THREAD

**Issue by montanarograziano** [mlflow/mlflow#9850]
### Summary

Related to #9731.

The motivation is to keep each flavor module in its own directory for consistency. For now we just move it to `__init__.py `for simplicity, but in the future we will think about a better refactoring.

Similiar PR can be found in #9692.

Code pointer: [link](https://github.com/mlflow/mlflow/blob/master/mlflow/llm.py)

**Comment by harupy** [comment]
@montanarograziano Thanks! Assigned :)
