### ISSUE TITLE
Move mlflow/statsmodel.py to mlflow/statsmodel/__init__.py

### ISSUE THREAD

**Issue by montanarograziano** [mlflow/mlflow#9863]
### Summary

Related to #9731.

The motivation is to keep each flavor module in its own directory for consistency. For now we just move it to `__init__.py` for simplicity, but in the future we will think about a better refactoring.

Similiar PR can be found in #9692.

Code pointer: [link](https://github.com/mlflow/mlflow/blob/master/mlflow/lightgbm.py)

**Comment by Gekko0114** [comment]
Hi @montanarograziano 
If you don't mind, can I work on it?

**Comment by montanarograziano** [comment]
No problem for me :) as long as @harupy is ok.

**Comment by harupy** [comment]
@Gekko0114 thanks, go ahead!
