### ISSUE TITLE
[BUG] Memory leak with MLflow AI Gateway service

### ISSUE THREAD

**Issue by nolwennz** [mlflow/mlflow#9879]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### MLflow version

- AI Gateway service 2.7.1

### System information
- **Python 3.8**

### Describe the problem

Hello, 

We deployed a MLflow server container on Kubernetes as well as a separate container with AI Gateway service.  The setup works fine but the pod with MLflow AI Gateway crashes every 10hours due to memory leak. 
As the project is in test phase, there is no call made at all on AI Gateway service (as the logs below show).

Here is a screenshot of the pod memory consumption. 
![Capture d’écran de 2023-10-03 16-51-28](https://github.com/mlflow/mlflow/assets/144008942/fcfe5a9d-b22c-439e-8ee4-fb428bf8c2c9)

### Tracking information

```shell
`mlflow gateway start --config-path config.yaml --port 7000 --host 0.0.0.0`
```

### Stack trace

Kubernetes pod crashes with pod state: OOMKilled

### Other info / logs

```
[2023-10-09 07:09:09 +0000] [16] [INFO] Starting gunicorn 21.2.0
[2023-10-09 07:09:09 +0000] [16] [INFO] Listening at: http://0.0.0.0:7000 (16)
[2023-10-09 07:09:09 +0000] [16] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-10-09 07:09:09 +0000] [19] [INFO] Booting worker with pid: 19
[2023-10-09 07:09:09 +0000] [20] [INFO] Booting worker with pid: 20
/usr/local/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.8/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
[2023-10-09 07:09:12 +0000] [20] [INFO] Started server process [20]
[2023-10-09 07:09:12 +0000] [20] [INFO] Waiting for application startup.
[2023-10-09 07:09:12 +0000] [20] [INFO] Application startup complete.
/usr/local/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.8/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
[2023-10-09 07:09:12 +0000] [19] [INFO] Started server process [19]
[2023-10-09 07:09:12 +0000] [19] [INFO] Waiting for application startup.
[2023-10-09 07:09:12 +0000] [19] [INFO] Application startup complete.

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@nolwennz Can you reproduce this issue without using Kubernetes?

**Comment by harupy** [comment]
@nolwennz Feel free to reopen this issue if necessary.

**Comment by cryoff** [comment]
I can confirm that we have similar issue with MLFlow Deployment Server when running using simple `docker run` with a single OpenAI endpoint

**Comment by cryoff** [comment]
Is there a way to enable `debug` level for logger messages? The `deployment` command does not accept custom `uvicorn` parameters
