### ISSUE TITLE
--backend-store-uri

### ISSUE THREAD

**Issue by perlinger** [mlflow/mlflow#988]
dockerfile
----
FROM centos:6

ENV LC_ALL=en_US.utf-8
ENV LANG=en_US.utf-8

RUN yum update -y
RUN yum install yum-utils -y
RUN yum install -y https://centos6.iuscommunity.org/ius-release.rpm
RUN yum install -y python36u python36u-libs python36u-devel python36u-pip

RUN yum install -y which gcc

RUN ln -fs /usr/bin/pip3.6 /bin/pip
RUN ln -fs /usr/bin/python3.6 /usr/bin/python

RUN python --version
RUN pip --version

RUN pip install salt

ENV MLFLOW_VERSION 0.8.2
ENV TERM linux
ENV BUCKET ####

ENV USERNAME #####
ENV PASSWORD #####
ENV HOST #####
ENV DATABASE mlflow

RUN pip install mlflow==$MLFLOW_VERSION

RUN mkdir -p /mlflow/

EXPOSE 5000

CMD mlflow server \
    --backend-store-uri mysql://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${DATABASE} \
    --default-artifact-root s3://${BUCKET}/mlflow-artifacts \
    --host 0.0.0.0 --gunicorn-opts "--access-logfile -"

----
When I run the docker image I get this error

Usage: mlflow server [OPTIONS]
Try "mlflow server --help" for help.

Error: no such option: --backend-store-uri

**Comment by perlinger** [comment]
How should we store meta data to a cloud database?

**Comment by perlinger** [comment]
I pulled from master today and built wheel

python3.6 setup.py bdist_wheel

I am using the wheel in this Dockerfile.

Getting 403 error when I go to localhost:5000

------------------------

# Use an official centos6 image
FROM centos:6

# Required for Python3 
ENV LC_ALL=en_US.utf-8
ENV LANG=en_US.utf-8

# Install Python3.6
RUN yum update -y
RUN yum install yum-utils -y
RUN yum install -y https://centos6.iuscommunity.org/ius-release.rpm
RUN yum install -y python36u python36u-libs python36u-devel python36u-pip

# Install Additional Packages
RUN yum install -y which gcc

# Make python3.6 the default python
RUN ln -fs /usr/bin/pip3.6 /bin/pip
RUN ln -fs /usr/bin/python3.6 /usr/bin/python

# Verify python and pip are for python3.6
RUN python --version
RUN pip --version

# Install salt if required in future extensions.
# Not required.
RUN pip install salt

# ENVs for MLFLOW
ENV MLFLOW_VERSION 0.8.2
ENV TERM linux
ENV BUCKET ngap2-cdt-platform

#ENVs for mysql Aurora
ENV USERNAME #######
ENV PASSWORD #######
ENV HOST #######
ENV DATABASE #######

# Install MLFLOW using python3.6
# RUN pip install mlflow==$MLFLOW_VERSION
COPY mlflow-0.8.3.dev0-py3-none-any.whl ./
RUN pip install mlflow-0.8.3.dev0-py3-none-any.whl

# Required for MLFLOW
RUN mkdir -p /mlflow/

# Default port for MLFLOW
EXPOSE 5000

# Command to launch MLFLOW
CMD mlflow server \
    --backend-store-uri mysql://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${DATABASE} \
    --default-artifact-root s3://${BUCKET}/mlflow-artifacts \
    --host 0.0.0.0 --gunicorn-opts "--access-logfile -"

**Comment by jmrr** [comment]
Hi @perlinger for the first issue you reported the problem was that you were installing version 0.8.2 which didn't contain the `--backend-store-uri` option yet.

For this last question, the answer should be in the container logs. Could you provide these?
