### ISSUE TITLE
[BUG] Empty space on left sidebar

### ISSUE THREAD

**Issue by janhurst** [mlflow/mlflow#9881]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.7.1

### System information

- Ubuntu 20.04 vscode devcontainer with Windows Chrome web browser:
- Python 3.10.12:

### Describe the problem

Large white empty space on left side of the view:

![image](https://github.com/mlflow/mlflow/assets/16224889/a0d54b28-d4c6-4f99-8d77-2519258eeceb)

### Steps to reproduce the bug

- conda install mlflow
- mlflow ui
- open browser to http://localhost:5000

### Is the console panel in DevTools showing errors relevant to the bug?

No errors

### Does the network panel in DevTools contain failed requests relevant to the bug?

No failed requests

**Comment by harupy** [comment]
@janhurst I don't see the empty space on my machine:

<img width="1148" alt="image" src="https://github.com/mlflow/mlflow/assets/17039389/d0a2951b-526c-47b6-99a7-67c276b3f543">

The command I used:

```
docker run --rm -w /mlflow -v $(pwd)/mlruns:/mlflow/mlruns -p 5000:5000 python:3.8 bash -c 'pip install mlflow && mlflow server --host 0.0.0.0 --gunicorn-opts "--log-level debug"'
```

**Comment by harupy** [comment]
@janhurst Can you check what's creating that space using the devtools?

<img width="1399" alt="image" src="https://github.com/mlflow/mlflow/assets/17039389/8849cd53-9536-477f-888c-b5a788b13d64">

**Comment by janhurst** [comment]
> The command I used:
> 
> ```
> docker run --rm -w /mlflow -v $(pwd)/mlruns:/mlflow/mlruns -p 5000:5000 python:3.8 bash -c 'pip install mlflow && mlflow server --host 0.0.0.0 --gunicorn-opts "--log-level debug"'
> ```
> 
> I'm using a Macbook. It could be a windows-only issue.

@harupy this is the output from the same docker command:
![image](https://github.com/mlflow/mlflow/assets/16224889/4f974f2b-2c48-4716-aefb-b8a8fe31c1a7)

I can't tell what is filling the empty space, there is no element that I can select :(
![image](https://github.com/mlflow/mlflow/assets/16224889/5783bcd3-a7b5-4043-9fce-7a447365a3ff)

If I select the empty space the outer div seems to be selected:
![image](https://github.com/mlflow/mlflow/assets/16224889/95582030-9267-4d3d-a0f7-6895d0a82240)

**Comment by janhurst** [comment]
I've now just checked in Mozilla Firefox, and the issue is not present. It seems to occur in Google Chrome and Microsoft Edge (same engine?).

**Comment by harupy** [comment]
@janhurst Thanks for the investigation! Does this occur in mlflow 2.6?

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/assets/17039389/b93ab006-9128-40a8-813a-a5ac683d5dd5

**Comment by harupy** [comment]
@janhurst What is your Chrome version?

**Comment by janhurst** [comment]
Version 117.0.5938.150 (Official Build) (64-bit)

**Comment by harupy** [comment]
What happens if you toggle `box-sizing: border-box`?

**Comment by janhurst** [comment]
not quite the same as the vid you posted, i see a scrollbar appear, but that whitespace that changes on your vid stays the same for me

**Comment by janhurst** [comment]
> @janhurst Thanks for the investigation! Does this occur in mlflow 2.6?

yes seems to be the same issue in mlflow 2.6

**Comment by harupy** [comment]
Can you try disabling all the chrome extensions?

**Comment by harupy** [comment]
Tested Microsoft  Edge:

<img width="1671" alt="image" src="https://github.com/mlflow/mlflow/assets/17039389/5668bf43-2fb3-4a0e-a4a4-65b95358c009">

Looks fine.

**Comment by janhurst** [comment]
> @janhurst Can you try disabling all the chrome extensions?

no change in incognito mode with all extensions disabled

> Tested Microsoft Edge:

I barely use edge, so on this machine it is about as "clean" as I can make it.

![image](https://github.com/mlflow/mlflow/assets/16224889/54512793-19e7-4e1b-95c5-92b0e21cc7a6)

**Comment by harupy** [comment]
What does this HTML look like on your machine?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      div {
        width: 160px;
        height: 80px;
        padding: 20px;
        border: 8px solid red;
        background: yellow;
      }

      .content-box {
        box-sizing: content-box;
      }

      .border-box {
        box-sizing: border-box;
      }
    </style>
  </head>
  <body>
    <div class="content-box">Content box</div>
    <br />
    <div class="border-box">Border box</div>
  </body>
</html>

```

**Comment by janhurst** [comment]
![image](https://github.com/mlflow/mlflow/assets/16224889/25c717b1-a481-4002-874b-122f3ab6e10a)

**Comment by harupy** [comment]
Looks fine.

**Comment by harupy** [comment]
🤔🤔🤔

**Comment by harupy** [comment]
@janhurst Can you try toggling more CSS styles?

**Comment by harupy** [comment]
@gabrielfu can you reproduce this on your machine?

**Comment by janhurst** [comment]
> @janhurst Can you try toggling more CSS styles? Is there a CSS style that removes the space?

I had a play around but nothing obvious jumped out to me....but this is where it gets weird (!)

I remoted from my laptop onto my desktop via RDP and the whitespace is gone! So exactly same browser/config is behaving differently when I am logged in locally compared to when I am remoted via RDP.

This has me wondering if there is something odd with font scaling or something similar. My laptop is a Dell XPS 17 with a 4K screen, whilst my desktop is a Samsung 49" UQHD. I am a bit of a loss as to explain whats going on here now :(

I will try to do some more testing w/ my laptop connected directly to the UQHD display and fiddling with the resolutions and scaling settings etc.

**Comment by gabrielfu** [comment]
@harupy no issues for me either, chrome 117.0.5938.150

```shell
docker run --rm -w /mlflow -v C:\Users\Gabriel\code\playground\mlruns:/mlflow/mlruns -p 5000:5000 python:3.8 bash -c 'pip install mlflow && mlflow server --host 0.0.0.0 --gunicorn-opts "--log-level=debug"'
```

![image](https://github.com/mlflow/mlflow/assets/22888849/89304706-c622-4409-956b-d975760732d9)
![image](https://github.com/mlflow/mlflow/assets/22888849/421e9dd3-51a5-4173-acb7-513e6ae6a9d2)

**Comment by harupy** [comment]
@janhurst any updates on this?

**Comment by janhurst** [comment]
I'm completely stumped :(

I have separate Chrome profiles, one works as normal, one shows the behaviour above (even when in incognito mode). I've been toggling plugins and fiddling with fairly much everything I can think of but nothing seems to stick :~(

I don't think this is a scaling issue (as one profile works and another does not)

Any suggestions on what to try next warmly welcome... but I am guessing this is somehow related to something on my client side rather than an mlflow issue?!

**Comment by janhurst** [comment]
one small additional note, i can see the behaviour kicks when the pixel width swaps from <500 to >500 ... not sure if that has any significance?

**Comment by harupy** [comment]
Can you reproduce this behavior without using mlflow?

**Comment by harupy** [comment]
Could this be an issue in Chrome?

**Comment by harupy** [comment]
@janhurst Can you also try much older versions such as mlflow 2.1.0 or 1.30?

**Comment by harupy** [comment]
Closing. I'm not sure if this is an MLflow's issue or not. @janhurst Feel free to reopen this issue if you find anything :)

**Comment by janhurst** [comment]
[like]  Jan Hurst reacted to your message:
________________________________
