### ISSUE TITLE
Confirmation of tag / metric / param logic

### ISSUE THREAD

**Issue by acroz** [mlflow/mlflow#990]
We (@facultyai) are implementing our own tracking store backend and want to make sure we get the logic right when updating tags, metrics and params on runs.

I've been discussing this already with @smurching in #955, but since that PR's closed and this discussion is only tangentially related to it, I've opened this issue.

Can someone (@smurching or otherwise) confirm that the following logic is correct so we get the right implementation of our backend:

1. When updating a tag, any existing value is overwritten.
2. When updating a param:
  * If the 'new' value is the same as the 'old' one, do not complain.
  * If the 'new' value is different from the 'old' one, this represents an error case.
3. When updating a metric, always append an additional row (i.e. there is no uniqueness constraint on `(key, timestamp)`) (see also relevant discussion in #955).
4. When determining the 'latest' metrics for a run, if there are duplicate timestamps within a metric, the one with the largest value is considered the 'latest' (as described in #972).

I also have a couple of follow up questions:

* Is the logic of doing a batch update expect to be the same as applying its contents sequentially? e.g. does a payload with the same tag being updated multiple times result the right-most tag getting set?
* Does (4) imply that we should sort by `(timestamp, value)` when returning the history for a metric?

**Comment by acroz** [comment]
FAO @tomas-milata @pbugnion @mociarain @eliasbenussi @aminehmida

**Comment by smurching** [comment]
@acroz thanks for bringing this up, 1-4 are all correct :)

For your follow-up questions:

> Is the logic of doing a batch update expect to be the same as applying its contents sequentially? e.g. does a payload with the same tag being updated multiple times result the right-most tag getting set?

Yep, the right-most tag should get set in that case, and I think we should require batch updates to behave similarly to logging the contents sequentially (log metrics, params, and tags left to right).

> Does (4) imply that we should sort by (timestamp, value) when returning the history for a metric?

Good question, here I'll defer to @dbczumar, who's been thinking about these questions + also will be working on a design for adding x-coordinate support to metrics (i.e. being able to specify metrics as `Metric(key, value, timestamp, x_coord)` as described in https://github.com/mlflow/mlflow/issues/32.

**Comment by acroz** [comment]
Thanks for the clarifications @smurching!

Look forward to hearing from @dbczumar on the ordering question - we will be implementing this on our backend soon and it will be good to have clarity.

**Comment by acroz** [comment]
@smurching The docs you added in #1001 are really good for clarifying some of these questions. I'm not sure I would have looked there though for implementing alternative store implementations as we're doing in `mlflow-faculty`, however. Can we add documentation (or even just a link to the REST docs) to appropriate `AbstractStore` methods to clarify this for plugin developers?

**Comment by dbczumar** [comment]
@acroz Regarding the ordering of results returned by the `get_metric_history()` API:

While I think that `(timestamp, value)` is a reasonable ordering for the `get_metric_history` API as it currently exists, this ordering will likely change when we introduce support for auto-incrementing, user-adjustable x-coordinates. Because the existing API doesn't explicitly order the results, I'd rather think about ordering in the context of x-coordinates in the near future, as opposed to defining an implementing a temporary ordering right now.

Does that seem reasonable?

**Comment by acroz** [comment]
Hi @dbczumar, if the ordering is undefined that is ok for us - we will likely implement an ordering by `(timestamp, value)` on our backend so that our users will have a consistent view on metrics, and then will implement the new logic when x-coordinates are added.

We are interested in staying in the loop on how the 'adding x-coordinates' project progresses (though I believe my colleague @zblz was commenting on another issue of yours on this).

**Comment by acroz** [comment]
#1004 added documentation on the expected behaviour to the abstract store, and ordering on `get_metric_history` is expected to be undefined for the time being, so closing this issue.

Thanks for the help @dbczumar and @smurching!
