### ISSUE TITLE
[DOC-FIX] default value --env-manager for `mlflow models generate-dockerfile` is incorrect

### ISSUE THREAD

**Issue by Beramos** [mlflow/mlflow#9921]
### Willingness to contribute

Yes. I would be willing to contribute a document fix with guidance from the MLflow community.

### URL(s) with the issue

https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-models-generate-dockerfile-env-manager

### Description of proposal (what needs changing)

The documentation states that virtualenv is the default value, but actually it is conda, you can see it here:

https://github.com/mlflow/mlflow/blob/1404fa6db18269d3e32bc99acee44bfabb141f60/mlflow/models/cli.py#L197

Honestly, I would like to change the CLI and not the documentation to be consistent with the default value of `build-docker` which is virtualenv:

https://github.com/mlflow/mlflow/blob/1404fa6db18269d3e32bc99acee44bfabb141f60/mlflow/models/cli.py#L266

Should I change the docs or should I change the CLI source code?

**Comment by harupy** [comment]
@Beramos thanks for reporting this. we should change the CLI source code.

**Comment by serena-ruan** [comment]
@Beramos Please feel free to raise a PR and I'll review :) Thanks!
