### ISSUE TITLE
Error when trying to use spark.log_model on managed mlflow on Databricks

### ISSUE THREAD

**Issue by SJG2019** [mlflow/mlflow#994]
Hi,
I am trying to use the managed mlflow on Databricks and the examples using sklearn ([Link](https://docs.azuredatabricks.net/applications/mlflow/tracking-examples.html#train-a-scikit-learn-model-and-save-in-scikit-learn-format)) run without any issuses. Now I  tried to use a spark Pipeline and log that model and I am running into an issue. The logging of the parameters and all works, but when Iam trying to log the model via mlflow.spark.model_log() Iam getting the following Error:
```
ERROR mlflow.utils.rest_utils: API request to https://westeurope.azuredatabricks.net/dbfs/databricks/mlflow/839842852438332/2a97393d2d6843dfac4e5086fe732560/artifacts/model/sparkml/metadata/_SUCCESS failed with code 503 != 200, 
retrying up to 2 more times. API response body: {"error_code":"TEMPORARILY_UNAVAILABLE","message":"No webapps are available to handle your request. Please try again later."}  
```
I have this issue with my own Pipeline but I also run into the Problem when I am trying to save the model from this Example ([Link](https://docs.azuredatabricks.net/applications/mlflow/tracking-examples.html#train-a-pyspark-model-and-save-in-mleap-format)) as a spark Pipeline by adjusting the code in cmd12 as follows:
```
import mlflow
import mlflow.spark

# Set the MLflow experiment
mlflow.set_experiment("/Shared/MLflow/experiments/NewsModel")

def fit_model():
  # Start a new MLflow run
  with mlflow.start_run() as run:
    # Fit the model, performing cross validation to improve accuracy
    paramGrid = ParamGridBuilder().addGrid(hashingTF.numFeatures, [1000, 2000]).build()
    cv = CrossValidator(estimator=pipeline, evaluator=MulticlassClassificationEvaluator(), estimatorParamMaps=paramGrid)
    cvModel = cv.fit(df)
    model = cvModel.bestModel
    
    model_path = "model"
    # Log the model within the MLflow run, specifying a `sample_input` argument
    # that MLeap will use when serializing the model
    mlflow.spark.log_model(model, model_path)
    run_id = run.info.run_uuid
    return model_path, run_id
```

**Comment by bhavink-db** [comment]
Try

import mlflow
from mlflow import spark as mlflow_spark

#log spark model as

mlflow_spark.log_model(model,”model_path”)

**Comment by SJG2019** [comment]
Hey, this works indeed. Maybe it would be an idea to add this to the documentation or change the name of the function as this is something everyone will run into that does not define thier own spark session?

**Comment by bhavink-db** [comment]
Sure thing, I’ll file an idea / uodate docs
