### ISSUE TITLE
[BUG] save_model's output might not be intentional when running mlflow_server

### ISSUE THREAD

**Issue by Gekko0114** [mlflow/mlflow#9948]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.7.1
- Tracking server: 2.7.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: EC2 Linux
- **Python version**: 3.9.16

### Describe the problem

Can you clarify whether this behavior is intentional or a bug?

When I run `autolog` with the MLflow server running, the output is saved to the `artifact-root` (s3).
However, when I execute `save_model` with the MLflow server running, the output is generated directly under the client-side directory (file:///home/ec2-user/model-1).

I would expect the output of save_model to be treated as artifacts and be saved under artifact-root. Is this behavior by design?

### Tracking information

server side
```shell
mlflow server -h 0.0.0.0 --backend-store-uri file:///home/ec2-user/mlflow-database --default-artifact-root s3://mlflowdummy
```

client side
```shell
export MLFLOW_TRACKING_URI=http://localhost:5000
python3 mlflow_example.py
```

mlflow_example.py
```python
import mlflow
import mlflow.sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from mlflow import log_metric, log_param, log_artifact
from mlflow.tracking import MlflowClient

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

experiment_name = "experiment-example"
experiment_id = mlflow.create_experiment(experiment_name)
print(experiment_id)

# モデルのトレーニング
with mlflow.start_run(experiment_id=experiment_id) as run:
    tracking_uri = mlflow.get_tracking_uri()
    print('Current tracking uri: {}'.format(tracking_uri))
    mr_uri = mlflow.get_registry_uri()
    print('Current model registry uri: {}'.format(mr_uri))
    artifact_uri = mlflow.get_artifact_uri()
    print('Current artifact uri: {}'.format(artifact_uri))
    mlflow.autolog() # saved to the artifact-root
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    accuracy = model.score(X_test, y_test)
    mlflow.log_metric("accuracy", accuracy)
    mlflow.sklearn.save_model(model, "model-1") # saved to the directory under client-side
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Thanks @Gekko0114 for the report, but this is expected. `save_model` saves a model **locally**. `log_model` should be used instead.

**Comment by Gekko0114** [comment]
I see, thanks!
BTW, are there any documents explaining which methods' outputs are stored to artifact-repo ?

**Comment by harupy** [comment]
> are there any documents explaining which methods' outputs are stored to artifact-repo?

No, the following APIs **log** artifacts to artifact repos.

- `mlflow.log_artifacts`
- `mlflow.log_artifact`
- `mlflow.<flavor>.log_model`

**Comment by Gekko0114** [comment]
Gotcha.
How about backend-store-uri? In order to store items to backend-store, which methods should I use?

**Comment by harupy** [comment]
`log_metric`, `log_params`, `set_tags`?

**Comment by Gekko0114** [comment]
I see, thank you!
BTW, can I add the explanation related to "how to use artifact-repo" to MLflow documents?
It would be helpful for other people as well

**Comment by harupy** [comment]
> BTW, can I add the explanation related to "how to use artifact-repo" to MLflow documents?

Can you elaborate?

**Comment by Gekko0114** [comment]
Sure, I will read MLflow documents again and elaborate which documents I want to be added.

**Comment by Gekko0114** [comment]
> Sure, I will read MLflow documents again and elaborate which documents I want to be added.

In that case, I will create another issue. So I will close this issue.
Thank you so much @harupy !

**Comment by harupy** [comment]
you're welcome!
