### ISSUE TITLE
Enalbe ruff `RUF013`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9949]
### Summary

Make this change to enable [RUF013](https://docs.astral.sh/ruff/rules/implicit-optional/):

```diff
diff --git a/pyproject.toml b/pyproject.toml
index f4b410699..db7dd6df3 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -38,6 +38,7 @@ select = [
   "PT026",
   "PT027",
   "RUF010",
+  "RUF013",
   "S307",
   "UP004",
   "UP008",
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `Resolve #{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by Sai-Suraj-27** [comment]
@harupy can I work on this?

**Comment by harupy** [comment]
@Sai-Suraj-27 Go ahead!

**Comment by harupy** [comment]
looks like @lightnsessofbein already filed a PR.

**Comment by Sai-Suraj-27** [comment]
@harupy sure, No problem 👍
