### ISSUE TITLE
Adding darkmode in the documentation website

### ISSUE THREAD

**Issue by JaynouOliver** [mlflow/mlflow#9951]
### Summary

It is straining to the eyes while looking at the documentation at night in light mode, it is better to have a feature to toggle between light and dark modes in the website.

![image](https://github.com/mlflow/mlflow/assets/88646338/d6aca363-aee5-458b-b2bc-c13a58ef0b95)

**Comment by shreyasks482** [comment]
Hey @JaynouOliver , can you assign this to me?

**Comment by serena-ruan** [comment]
Hi @JaynouOliver We're working on the new website, so we shouldn't spend effort on adding darkmode on the current one. The new website should be coming out in the following months, and if we can get the dark mode for free with the new framework, we'll support it. :)

**Comment by AmgadHasan** [comment]
Any updates on the new website? Does it include dark mode?

@serena-ruan
