### ISSUE TITLE
Enable ruff `W`

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#9968]
### Summary

Make this change:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index db7dd6df3..8feaec189 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -59,6 +59,7 @@ select = [
   "T20",
   "TID252",
   "TID251",
+  "W",
 ]
 force-exclude = true
 ignore = [
```

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `Close #{issue_number}` (e.g. `Close #123`) in the PR description when opening a PR.

**Comment by harupy** [comment]
Please make sure to comment before working on this.

**Comment by lightnessofbein** [comment]
@harupy  Hey, Could I work on this one? No sudden PR this time)
